### ISSUE TITLE
 Server currently unavailable

### ISSUE THREAD

**Issue by luweijun1992** [Graylog2/graylog2-server#10006]
Cannot use domain name to access graylog, it is normal to use IP to access .
Version: 4.0.2
ES: 7.10.2
![image](https://user-images.githubusercontent.com/58923704/106615470-6c8c2600-65a7-11eb-946e-e691af64e64e.png)

![image](https://user-images.githubusercontent.com/58923704/106614908-d8ba5a00-65a6-11eb-9eb7-5155e277eff5.png)

**Comment by asachs01** [comment]
Hi @luweijun1992, this is likely not a bug. For assistance with troubleshooting, please create a topic on our community forums here: https://community.graylog.org
