### ISSUE TITLE
Set default timezone on new LDAP users

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#1000]
New LDAP users haven't their timezone set, using UTC as default. It would be better to use something more meaningful as a default value, probably the admin user's timezone.

**Comment by kroepke** [comment]
Do they get UTC explicitly?
I think they should either get the app.conf default value or we should allow a more flexible mapping of ldap attributes. (Easiest solution would be the former, of course)

**Comment by edmundoa** [comment]
I was playing with it on 1.0.0 when I filled the issue and they do get UTC as default, maybe the behaviour changed at some point.

Reading the timezone from LDAP would be nice, but at the moment I think using the application's timezone would suffice.

**Comment by kroepke** [comment]
Agreed!

**Comment by bernd** [comment]
Fixed in #1554
