### ISSUE TITLE
Error importing contentpack. Missing Stream for widget entity

### ISSUE THREAD

**Issue by hyorch** [Graylog2/graylog2-server#10008]
Error importing contentpack.
Caused by: org.graylog2.contentpacks.exceptions.ContentPackException: Missing Stream for widget entity
## Expected Behavior

After create a conteng pack with only a dashboard and 2 related streams in one server, importing dashboard and streams in other server should work.

## Current Behavior

Can´t install content pack. The content pack is a dashboard with widgets with stream filters. Although those streams are presents in the content pack error 500 rise.
If I install first the streams and then the dasboard, the error is the same.

## Possible Solution

It seams that dashboard references streams by "local ID" not by stream name.

## Steps to Reproduce (for bugs)

1. Create Content Pack in server A version 4.0.1. Select a dashboard.
2. Content Pack wizard will add related Streams to content pack.
3. Import Content Pack in server B version 4.0.1. 
4. Error 500.

## Your Environment

* Graylog Version: 4.0.1
* Java Version:
graylog@graylog-0:~$ java -version
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)

* Elasticsearch Version:
* MongoDB Version:
* Operating System: Kubernetes Deployment
* Browser version:

**Comment by hyorch** [comment]
I´m reviewing Content Pack code. Although my widgets have only one Stream filter, I can see 2 streams in one of them.
"streams": [
                    "0b5d4c49-3cf2-4fe5-9b59-fb572ce76e6d",
                    "9921ca72-efbc-4a7b-97e3-07b23b7b92f0"
                  ],

**Comment by hyorch** [comment]
I´ve edited Content Pack file before importing and remove Stream reference that is not the correct Stream in use.
Importing this new file works.
I think those references to unknown Streams are garbage for a previus Stream that was in use by the Dashboard Widgets and was deleted from Stream configuration page. Is it posible that deleting a Stream from Stream configuration page do not delete all widget stream references?

**Comment by dennisoelkers** [comment]
Yes, this is possible. We would need to clean up dangling stream references from widgets during export. Thanks for reporting and debugging this, much appreciated!
