### ISSUE TITLE
Assign a Stream automatically to users

### ISSUE THREAD

**Issue by driyage** [Graylog2/graylog2-server#1001]
It would be very useful if you can assign a stream (as default) to users upon logging in via LDAP (or any other method)

This is very problematic when you have over 150 + users to manage them individually assigning them streams upon log in

**Comment by edmundoa** [comment]
I'm closing this issue, as it duplicates https://github.com/Graylog2/graylog2-server/issues/511. While we fix the issue, I guess the best approach is to set the permissions by using the REST API.
