### ISSUE TITLE
Relative Timerange Input cannot be cleared

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#10016]
## Expected Behavior
When deleting the text from an input I want be able to clear it completely and type the number.

## Current Behavior
When clearing the timerange input the number `1` is filled out automatically which prevents me from filling out `20` for example.
![Graylog (29)](https://user-images.githubusercontent.com/448763/106883140-e32c3f00-66df-11eb-91df-56fe619d72ad.png)

## Context
This bug will be introduced after #9569 is merged. :)

**Comment by kyleknighted** [comment]
resolved in https://github.com/Graylog2/graylog2-server/pull/10612
