### ISSUE TITLE
Separate first and last name in user profile

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#10022]
## What?
Allow specifying first and last names separately in the user profile.

## Why?
External systems usually have separate fields for the first and last names of people.
Graylog only has a single field, which can be tricky when integrating with other systems, because there's no obvious way to split a string into its components (multiple first names, multiple last names, non-western scripts etc.)

## Your Environment

* Graylog Version: 4.0

**Comment by bernd** [comment]
This requires careful planning regarding backwards compatibility and migration of existing users. :slightly_smiling_face:

**Comment by edmundoa** [comment]
Is this issue still relevant? Afaik this is already done.

**Comment by kroepke** [comment]
Yes, I believe this has been addressed in #10080 #10158 #10162 #10166 #10074.
