### ISSUE TITLE
Permission management inconsistent between user interface and REST API

### ISSUE THREAD

**Issue by juliohm1978** [Graylog2/graylog2-server#10024]
## Expected Behavior
I expect Graylog's internal behavior to be the same using either the browser user interface or the REST API.

## Current Behavior
Moving up from Graylog 3 to Graylog 4, my team was forced to improvise a permission management via external scripts that use the Graylog REST API.

I can successfully assign views, streams and dashboard permissions using the API, so I managed to create my own ad-hoc solution. I can query the API and see the permissions I created for a specific user:

GET /users/<username>

```
[
  "users:tokenremove:<username>",
  "streams:read:5b85944a7b1cef0001733d93",
  "users:edit:cwb_dtic_divisao_analise_sistema_judiciais",
  "streams:read:5cd5b65be0d9b100015c141e",
  "streams:read:5cc894b0879d8a00011f2c38",
  "streams:read:5cd4dfe4eecc1f0001aa4212",
  "streams:read:5c6adad6f0d9590001024d58",
  "streams:read:5b8590a57b1cef0001733904",
  "streams:read:5c75aef7f0d9590001100edb",
  "users:passwordchange:cwb_dtic_divisao_analise_sistema_judiciais",
  "streams:read:5c6c198df0d9590001042c79",
  "streams:read:5c6c7460f0d9590001049d64",
  "users:tokencreate:cwb_dtic_divisao_analise_sistema_judiciais",
  "streams:read:5e8488e71ff8b8002c08c66f",
  "streams:read:5b85940f7b1cef0001733d49",
  "streams:read:5ec2b25e08f51e003c35b406",
  "streams:read:5b6c8b9f7b1cef0001577ff4",
  "streams:read:5db0c2488390f2002c5542a6",
  "streams:read:5b85942f7b1cef0001733d70",
  "streams:read:5e3318765b90a6002e22dce0",
  "streams:read:5c755f5ff0d95900010fadb0",
  "streams:read:5d2cbe11fb6f52002d77e452",
  "streams:read:5c742a3df0d95900010e2ab0",
  "streams:read:5b8593b07b1cef0001733ccf",
  "streams:read:5e4c1d2ed605ed002f56012b",
  "streams:read:5b8ec3b07b1cef00017dadad",
  "streams:read:5b8594687b1cef0001733db7",
  "streams:read:5e9dee5ae69e6e003db713c5",
  "streams:read:5b8593f77b1cef0001733d26",
  "users:tokenlist:cwb_dtic_divisao_analise_sistema_judiciais",
  "streams:read:5ee17c62cc97613469395ef3",
  "streams:read:5d83b2d20fa074002cc2436c",
  "streams:read:5b8591707b1cef00017339fe",
  "streams:read:5c6c6f27f0d95900010496e3",
  "streams:read:5b8593897b1cef0001733c9c",
  "streams:read:5c004f061f68a00001f2c643",
  "streams:read:5c6c3a84f0d959000104559e",
  "streams:read:5b8593cf7b1cef0001733cf4",
  "streams:read:5c0820931f68a00001fcf110",
  "streams:read:5c7426cbf0d95900010e265d",
  "streams:read:5b8594597b1cef0001733da4",
  "metrics:read",
  "messagecount:read",
  "journal:read",
  "messages:analyze",
  "fieldnames:read",
  "messages:read",
  "indexercluster:read",
  "system:read",
  "jvmstats:read",
  "inputs:read",
  "buffers:read",
  "clusterconfigentry:read",
  "decorators:read",
  "throughput:read"
]
```

However, the same permissions created using the REST API do not show up in Graylog's user interface.

![image](https://user-images.githubusercontent.com/4145456/107126561-6d66d580-688f-11eb-9bd2-edf808171b68.png)

Testing further, I am not even able to remove or revoke permissions assigned via the user interface. The revoke API endpoint seems to touch only permissions that were assinged through the API itself.

## Possible Solution
Keep the behavior consistent between user interface and REST API.

## Steps to Reproduce

1. Create a new user with the basic Reader role.
2. Share an entity with that user via the Graylog user interface.
3. Query the API. The permission will be there. (GET /users/{username})
4. Send an empty permission list to the user API (PUT /users/{username}/permissions)
5. Query the API. The permission will still be there.
6. Revoke the user permissions via the API (DELETE /users/{username}/permissions)
7. Query the API. The permission will still be there.

Common sense tells me steps 4 and 6 should remove the permission previously assigned. Adding to the confusion, it is possible to add new permissions via the API and revoking only removes the permission assigned via the API. It does not seem to touch the permission created with the user interface.

* Graylog Version: 4.0.1 / 4.0.2
* Java Version: openjdk version "1.8.0_282"
* Elasticsearch Version: 6.8
* MongoDB Version: 4.4.1
* Browser version: Firefox

**Comment by bernd** [comment]
@juliohm1978 The UI is using the entity shares API endpoints (`/api/authz/shares/entities`) endpoints to create shares. That endpoint is creating grants in the `grants` database collection. These grants are used to generate the user permissions that you see in the user endpoint.

To manage shares with scripting, you should also use the entity shares API. That way the shares will also show up in the UI.

![image](https://user-images.githubusercontent.com/461/107250686-44337a00-6a34-11eb-9361-01ee8aca8031.png)

The easiest way to check the required JSON payload for this API is to look at the browser console when creating shares in the UI.

I hope that helps.

**Comment by juliohm1978** [comment]
Thank you. That makes more sense. Aside from an apparent inconsistency, should I be able to rely on the permission list in the user entity? It certainly works, but I guess my question is, will it be supported along with the shares entities?

**Comment by bernd** [comment]
@juliohm1978 Yes the permission list in the user object will be generated from the share grants, the explicitly set permissions in the user object and some implicitly added permissions to allow users to edit themselves.
