### ISSUE TITLE
style-loader update stopped node_module CSS from loading

### ISSUE THREAD

**Issue by kyleknighted** [Graylog2/graylog2-server#10023]
After the recent merge of #8875 the components that use CSS files from node_modules no longer appear to be parsed properly.

- graylog2-web-interface/src/components/common/ReactGridContainer.jsx
- graylog2-web-interface/src/components/common/DatePicker.jsx

And some webpack specific imports were seemingly missed in the conversion. But have not confirmed if they are causing any issues.

- graylog2-web-interface/src/views/components/messagelist/decorators/AddDecoratorButton.jsx
- graylog2-web-interface/src/components/common/SortableListItem.jsx
- graylog2-web-interface/src/views/components/messagelist/decorators/DecoratorSidebar.jsx
- graylog2-web-interface/src/views/components/messagelist/decorators/DecoratorSummary.jsx

**Comment by Gaya** [comment]
@kyleknighted thanks for filing, I'll take a look

**Comment by Gaya** [comment]
About the old style of importing: I  didn't touch this since it was also not broken. Might be good to also clean these up, but maybe in a separate PR
