### ISSUE TITLE
How can I use Graylog in windows service applications?

### ISSUE THREAD

**Issue by younussenn** [Graylog2/graylog2-server#10048]
Hi,

I have **windows service applications** and **windows form applications**. I want to use Graylog. I don't know much about graylog. Are there any documents I can use about this? 

And I add this: My applications run on windows OS. **I log record to MS Sql server using log4net package.**

Thank you.

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
