### ISSUE TITLE
Change Outgoing Traffic to display GB instead of GiB

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#10052]
## Expected Behavior

Since Graylog uses SI units for measuring data, so all elements in the UI should use SI units. 

## Current Behavior

Outgoing traffic shows `GiB` instead of `GB`.

**Comment by grotlue** [comment]
Closing this issue as discussed with @kroepke.
Background: We want to be consistent in how we measure traffic, but we are to display data in `n*1024` as this is what we work with in the backend.
