### ISSUE TITLE
Teams Migration: Duplicate ID Attribute is not possible 

### ISSUE THREAD

**Issue by makstock** [Graylog2/graylog2-server#10069]
We would like to use the UID, or the DN returned from the LDAP to use as ID Attribute in Graylog. If we test a connection or use an LDAP Browser, we can see that these fields are returned, but Graylog won't use them for its ID Attribute.

For Teams the same, we would like to use our CN as ID Attribute, the CN gets returned in a response, but Graylog won't recognize for ID Attribute:

![image](https://user-images.githubusercontent.com/62546449/108053966-5aea5a00-704e-11eb-908d-d7bbc0be4c47.png)

## Expected Behavior

The ID attributes should be used multiple times, and Graylog should be returned to the field.

## Current Behavior

When attributes are assigned for one time, it works fine, but it does not assign the same attributes in second/multiple cases.

Here are some screenshots for reference:

It looks like the Graylog would not accept that the same attribute is used twice.
Working:
![image](https://user-images.githubusercontent.com/62546449/108054351-d4824800-704e-11eb-9892-2582a15588a4.png)

Not Working:
![image](https://user-images.githubusercontent.com/62546449/108054372-dba95600-704e-11eb-89a1-00e46346c158.png)

## Possible Solution

NA

## Steps to Reproduce (for bugs)

Same as Expected behavior

## Context

Ticket# 844544

## Your Environment

* Graylog Version: 3.3 (Planning to migrate on 4.0 )
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by HenryTheSir** [comment]
The Issues happens in this lines: 
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java#L266

The 3 lines regarding if clause need to be removed to use an attribute for UUID and second entry
If the lines are removed the login works fine, but the User Login Test in Edit Authentication Service - LDAP throws an exception regarding duplicate keys in the ImmutableMap, 

https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java#L280 

config.userUniqueIdAttribute() needs an appended or prepended addition to not duplicate with the second use of an attribute.

**Comment by bernd** [comment]
@HenryTheSir Good catch, thank you! :+1:

**Comment by bernd** [comment]
We have a fix for this in https://github.com/Graylog2/graylog2-server/pull/10437. It will be part of one of the next 4.0 stable releases.
