### ISSUE TITLE
IP address changing makes graylog server unconnectable

### ISSUE THREAD

**Issue by ourlord** [Graylog2/graylog2-server#1006]
I used the ova image to build a toy graylog2 server on my laptop and using the bridged adapter for the network configuration so that external hosts can access my graylog2 server. But according to my router settings (I don't have the right to change it), the IP address for my graylog2 virtual machine keeps changing if it was rebooted. 
I understand this should not be the general case to build a log server. But is there some way to change some configuration properties so each time the IP address gets changed I can configure the settings?
I already found some places for some of the conf file, e.g. /etc/graylog/conf/ and /etc/graylog/. But still I cannot connect to my graylog2 server (actually the web-interface is accessible but saying cannot connect to the server), even after doing a "graylog-ctl reconfigure" or similar things. 
I am pretty sure the process for graylog is running.
Sorry for my poor English. Thank you.

**Comment by ourlord** [comment]
Actually I figure this out by myself. Virtualbox will keep the IP address of one vm static only if changing the network settings.

**Comment by bernd** [comment]
Thanks for the feedback.
