### ISSUE TITLE
Implement Dead Letter Queue for all kind of errors which today result in message loss

### ISSUE THREAD

**Issue by HenryTheSir** [Graylog2/graylog2-server#10083]
## What?
It would be nice, to have a dead letter queue for in the first step all Indexer Failures which are in the moment dropped and the message ID and index Name gets logged to mongodb. 

A possible solution would be to write this loglines to filesystem (or even better an external kafka broker) with an rotating file appender, so that an agent (filebeat/nxlog) can read this messages and resend them to an "Failure" (plain) Input which justs does basic processing (e.g. shorting the message to 16k)  and indexes the errormessage to an error index set. The admin has now the ability to view this messages and could contact the service owner sending the faulty messages. 

There could be a feature toggle in Graylog, so that users could disable the dumping to filesystem/kafka.

The handling which Logstash does for the elk stack could be a nice template for this function:

https://www.elastic.co/guide/en/logstash/current/dead-letter-queues.html

This could be extended, to inputs which drop messages now, when the GELF Codec is configured, but the message misses required fields or all other kinds of errors which in the moment result in message loss. 

If possible this could be handled with the existing output framework, but it has an extension so that only faulty exports to ES get routed to this output, this would allow every output plugin which is in graylog and its marketplace to be used as dead letter queue destination. 

## Why?
Graylog itself advertises as security and compliance system, so complete message loss should be the last thing to be worried about. 

Would resolve 
https://github.com/Graylog2/graylog2-server/issues/4578

and seams to be a nicer approach than the dead letter queue in previous releases
https://github.com/Graylog2/graylog2-server/pull/1498

## Your Environment

* Graylog Version: 3.3 planing the upgrade to 4.0
* Elasticsearch Version: 6.8
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by colttt** [comment]
#11124 is related

**Comment by HenryTheSir** [comment]
Feature got implemented in Enterprise Edition

**Comment by boosty** [comment]
> Feature got implemented in Enterprise Edition 

Docs: https://docs.graylog.org/docs/indexer-and-processing-failures

**Comment by colttt** [comment]
that is funny, somehow..
graylog is a log management system, what is the task of such a system? exactly receive logs, what drops Graylog? exactly logs :man_facepalming:  .. that's a fundamental function and it's just in the EE, you can put many things in the EE version, but not basic things, sorry.. 
that's why we move away from Graylog
