### ISSUE TITLE
Realtime buffers & disk journal utilization

### ISSUE THREAD

**Issue by beezoncheg** [Graylog2/graylog2-server#1008]
It will be good to see buffers & disk journal utilization in realtime like memory usage on the node page.

**Comment by brandongalbraith** [comment]
@beezoncheg This appears to be available in the latest Graylog release:

![abr3vjyaw2q95_kzhjt0s-33gopy-ihbe68sy9buzti](https://cloud.githubusercontent.com/assets/350893/7644091/a2e8d58a-fa65-11e4-9e8b-2ec8627cae13.png)

**Comment by bernd** [comment]
Updating all the buffer, disk journal, and throughput stats in real time will be in the upcoming 1.1 release.
