### ISSUE TITLE
"DiskJournal is disabled for this node" info for Read-only user.

### ISSUE THREAD

**Issue by beezoncheg** [Graylog2/graylog2-server#1009]
In node page read-only user sees that DiskJournal is disabled. But it's not. Admin user can see config and utilization.

**Comment by bernd** [comment]
@beezoncheg This will be fixed in 1.0.1. The problem was a missing permission for reader users. Once 1.0.1 is released, you have to re-create the user or use the "Set default permissions" button on the user details page to add the new permission to the user.
