### ISSUE TITLE
gelf amqp input keepalive

### ISSUE THREAD

**Issue by ynfiesta** [Graylog2/graylog2-server#1010]
when hosting graylog and rabbitmq in azure, azure kills the gelf amqp input connection if it is inactive for a minute.
This could be solved by adding a keepalive setting to the gelf amqp input.
In the meantime I am sending and empty message "{}" every 40 seconds to keep the connection alive

**Comment by bernd** [comment]
Thanks for the report. We will expose the [heartbeat timeout](https://www.rabbitmq.com/heartbeats.html) in the input configuration.

Might also be related to #699

**Comment by zolech** [comment]
Hello,

I don't this option in 1.1.3 while creating input. After upgrading from 1.0.2 all my AMQP stopped working with message "Mandatory configuration field heartbeat is missing" but I cannot set it because there is no "Heartbeat timeout" field on input creation page :<

**Comment by bernd** [comment]
@zolech I will try to reproduce this.

**Comment by bernd** [comment]
@zolech I was able to reproduce the problem with the "Mandatory configuration field heartbeat is missing" message after updating from 1.0 to 1.1. We will probably change this to not being mandatory in the future.

I cannot reproduce the problem that you do not see the "Heartbeat timeout" field when updating/creating an AMQP input. If you scroll down, you should be able to see it.
![4p8aaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/461/8324256/fd6be1b0-1a4e-11e5-9413-160a16e79ece.png)

**Comment by zolech** [comment]
Look, I am not joking.

![screenshot from 2015-06-24 09-12-15](https://cloud.githubusercontent.com/assets/2222322/8324466/282e7e10-1a51-11e5-9e59-a0431c99a0ca.png)

**Comment by bernd** [comment]
That is strange, I will investigate. Thanks for the feedback!

**Comment by zolech** [comment]
I got it working! It seems that one of my nodes hasn't been restarted during upgrade so it was still in 1.0.2. After restarting it came up as 1.1.3 and heartbeat options finally appeared. Sorry for bothering!

**Comment by bernd** [comment]
@zolech Cool, glad it's working now! :smiley:
