### ISSUE TITLE
Gelf HTTP size limit?

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#1011]
Hi,

Is it possible to raise the Gelf HTTP limit from 8kb to x?
I can't find anything in the config(s).

**Comment by joschi** [comment]
You can increase that value with the `rest_max_chunk_size` setting in your `graylog.conf` (https://github.com/Graylog2/graylog2-server/blob/1.0.0/misc/graylog2.conf#L67-68).

**Comment by dennusb** [comment]
That is for the Rest API. Not for the Gelf HTTP input, right? Because the change is not working...

**Comment by joschi** [comment]
Ah, yes. You're correct. The setting is for the REST API. We'll probably have to expose this setting for HTTP inputs as well.

**Comment by dennusb** [comment]
Would be cool if it can be implemented. Because we are hitting the 8kb limit already with stacktraces etc...

**Comment by CarlosSardo** [comment]
YES, PLEASE!! :+1:

**Comment by kroepke** [comment]
Let's increase the default (8kb seems rather too small) and also allow it to be configurable.

**Comment by dennusb** [comment]
That would be great @kroepke! :) We need it, because with large (.NET) stacktraces we are hitting the limit every time
