### ISSUE TITLE
Support flexible stream rule conditions

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1012]
Currently all stream rules are AND'ed together and messages will not match unless all stream rules can be applied successfully - this is far from ideal. Graylog should at least expose functionality to allow selecting between 'AND' or 'OR' evaluation of rules.

Under some circumstances you can also achieve the above by using regular expressions but this is not only complicated but the regular expression matching also puts unnecessary load on the server nodes.

**Comment by dfch** [comment]
:+1:

**Comment by kabl** [comment]
:+1:

**Comment by sebclick** [comment]
:+1:

**Comment by jalogisch** [comment]
AND, OR is possible with the current version
