### ISSUE TITLE
Editing the time zone for a user

### ISSUE THREAD

**Issue by yliya1991** [Graylog2/graylog2-server#10134]
## Expected behavior
I as a user want to be able to edit the timezone in Edit profile

  ## Current behavior
As a user, I log into the web interface of the graylog -> Edit profile with my username and password, after clicking the Edit User button, nothing happens.

  ## Possible Solution
Add the ability for an external user to edit Settings, Preferences via Edit profile -> Edit User

  ## Steps to reproduce (for errors)
I use the active authentication service - LDAP, the role of the reader, to enter I enter my username and password -> Edit profile -> Edit user

  ## Context
The ability to edit the time zone is available only if you go under the admin login -> Users and Teams -> select the desired user -> Edit User, I want it to be available to an external user.

  ## Your environment

  * Graylog version: 4.0.3
  * Java version: 1.8.0_275
  * Elasticsearch version: elasticsearch-oss: 7.9.3
  * MongoDB version: 3.2
  * Operating system: Linux version 5.6.19-300.fc32.x86_64
  * Browser version: 88.0.4324.150 (Official Build)
 
 when I go as an external user
<img width="1426" alt="Снимок экрана 2021-02-23 в 14 53 04" src="https://user-images.githubusercontent.com/38718724/108863429-dffae380-75f9-11eb-8818-17f8a4172394.png">

when I log in with the admin login and password
<img width="1407" alt="Снимок экрана 2021-02-23 в 10 02 14" src="https://user-images.githubusercontent.com/38718724/108863541-facd5800-75f9-11eb-91b6-22f03f3c5152.png">

**Comment by sowhatim** [comment]
@yliya1991 - did you find any alternative here ? I am also blocked on this. User's can't edit their timezone when we enabled ldap based authentication and basically whole of their debugging is affected. we only noticed this later and can't go back and have to use ldap based auth.

**Comment by yliya1991** [comment]
> @yliya1991 - did you find any alternative here ? I am also blocked on this. User's can't edit their timezone when we enabled ldap based authentication and basically whole of their debugging is affected. we only noticed this later and can't go back and have to use ldap based auth.

Hi, I added configuration to my file with graylog : 
 - name: graylog_root_timezone
               value: "EUROPE/KIEV"
               
I haven't found another solution yet.

**Comment by sowhatim** [comment]
@yliya1991 - got it. For my use-case, users are from different geos and they need to set it differently depending on the region they are working for at that moment. Unfortunately which is not possible right now :(

**Comment by sowhatim** [comment]
@bernd - is there a plan to pick this up ? (This will really unblock a critical blocker for me :( )

**Comment by yliya1991** [comment]
> @bernd - is there a plan to pick this up ? (This will really unblock a critical blocker for me :( )

hello, I checked yesterday in the new version 4.1 this functionality is available there, but the graylog itself does not work in the Enterprise, if without the Enterprise, then you can try version 4.1

**Comment by sowhatim** [comment]
this is working and proving very helpful. I have verified and allows users in my org to now update timezone as per their need.

**Comment by bernd** [comment]
This has been fixed.
