### ISSUE TITLE
Support for search based alerting

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1013]
We have a tiny jruby app that allows us to register searches and alerts based on the search results (mostly document count). The queries are executed periodically (every 1,5 or 15 minutes) for a given timeframe (mandatory range filter with an upper bound) and evaluated according to the alert definition.This allows moving window alerting and also cross-stream alerts.

I would love to have something like that built into in Graylog :)

**Comment by razvanphp** [comment]
Duplicate of [#939](https://github.com/Graylog2/graylog2-web-interface/issues/939) ? Please vote there too.

**Comment by bernd** [comment]
This can be done in the upcoming 3.1 release of Graylog.
