### ISSUE TITLE
Unable to scroll all messages widget after responsive resize

### ISSUE THREAD

**Issue by BlueTeamNinja** [Graylog2/graylog2-server#10161]
Pretty much all in the title.  There is no way to scroll through 'All Messages' when the browser is resized small enough that the UI changes to 'mobile' friendly.  Reported by graylog training student @ioivanov

## Expected Behavior
The ability to scroll the all messages widget - even without a scrollbar would make sense UI-wise but mousewheel or arrows.

## Current Behavior
No ability to scroll 

## Possible Solution
No idea.  

## Steps to Reproduce (for bugs)
Go to Search UI that contains at least 3 messages in all messages (otherwise no scrolling anyways)
Resize browser until its narrow enough that it switches to the mobile UI (on many monitors, simply snapping left or right will do this). 

Attempt to scroll "All Messages"

## Context
Without the ability to scroll, its difficult to snap to the left or right and read documentation, or specifically in this case - the Graylog training lab material. 

## Your Environment
Tested on multple desktop OS and browser and version. 

* Graylog Version: 3.3 -4.05
* Java Version: ~
* Elasticsearch Version: 6.8-7.10
* MongoDB Version: ~
* Operating System: Windows 10, Macos 11, 11.2
* Browser version: Chrome, Firefox, Safari
* 
![image](https://user-images.githubusercontent.com/1891183/109169138-8277ab80-774d-11eb-81cd-67f9774fa90d.png)

**Comment by kyleknighted** [comment]
Resolved with https://github.com/Graylog2/graylog2-server/pull/10276
