### ISSUE TITLE
Updating Output Configuration Breaks Setup

### ISSUE THREAD

**Issue by phaabe** [Graylog2/graylog2-server#10168]
After a change in the IP address in an TCP output configuration Graylog seems to stop working correctly (the visualization stops showing messages). The CPU consumption jumps up to 200% (as it is usually around 10%).
Only a restart of the Graylog service makes it work with the new configuration.

## Expected Behavior
Updating the output configuration shouldn't affect much except forwarding. 

## Current Behavior
Visualization stops showing messages.

## Your Environment

* 2 VCPU
* 4 GB RAM
* ~ 300k GELF messages per day (about half of them are forwarded through the specific output)

## Conclusion
I don't think this is normal behavior. Let me know if I can provide more information or if there is something wrong in principle with this setup.

**Comment by diesaulov** [comment]
Hi, @phaabe! Thank you for reporting the bug. May we ask to provide further details:

1. the version of Graylog in use at the time
2. values of the following properties from `server.conf`: `output_module_timeout` and `ring_size`
3. for how long did you wait before restarting the server?
4. ideally would be great to see server logs starting from the moment when you change the Output configuration until the restart

BR,
Danylo
