### ISSUE TITLE
enterprise menu present without enterprise-plugin installed

### ISSUE THREAD

**Issue by arcadesolutions** [Graylog2/graylog2-server#10188]
## Expected Behavior
Updated our Graylog community version from 3.2.6 to 3.3.11, no enterprise-plugin is installed. The UI should not display any menu entries about enterprise

## Current Behavior
Every user now an enterprise menu between dashboards and system which isn't even useable because no one has permissions.

## Possible Solution
Don't force the enterprise version on community version. A little bit hard to believe that this was suddenly implemented by accident. If I don't have the enterprise-plugin installed, no enterprise interactions should be possible 

## Steps to Reproduce (for bugs)
Based on the docs here: [Update with RPM packages](https://docs.graylog.org/en/4.0/pages/installation/operating_system_packages.html#operating-package-upgrade-rpm-yum-dnf)

1. install 3.3 repo
2. yum clean all
3. yum install graylog-server
4. restart

* Graylog Version: 3.3.11
* Java Version: openjdk 1.8.0_282
* Elasticsearch Version: 6.8.14-1
* MongoDB Version: 4.0.9-1
* Operating System: 7.9.2009
* Browser version: All of them

**Comment by bernd** [comment]
@arcadesolutions We added the Enterprise menu to the open source version to make it easier for users to get a free test license of the enterprise product. That menu is part of the open source product and only contains a traffic overview, some information about enterprise and a form to get a free test license. There are no commercial features installed.

**Comment by arcadesolutions** [comment]
Thanks for clarification, so there is no way to disable this menu? I can't see a reason why a normal user should be able to get a free test enterprise license besides that they get a permission error anyway. So it just generates confusion and would be nice to toggle this on/off.

**Comment by bernd** [comment]
@arcadesolutions What permission error do you get when doing what? A regular user shouldn't see an error. Thank you!

**Comment by arcadesolutions** [comment]
![graylog_enterprise_permission](https://user-images.githubusercontent.com/8624321/110338893-d5900f00-8027-11eb-8a21-f73ea9047c81.PNG)

Not sure if we have to grant additional permission to our users so at least they wouldn't get permission error.

**Comment by bernd** [comment]
@arcadesolutions Thanks for the info. This issue has already been fixed in 4.0. The "Enterprise" menu isn't displayed for non-admin users in 4.0 anymore.

We will check if we can backport the fix to 3.3. We don't have a timeline on a new 3.3 release, though. Now that 4.0 is the supported stable release, we don't plan for any more 3.3 releases.

**Comment by bernd** [comment]
A fix has been merged and will be part of the next 3.3.x release.
