### ISSUE TITLE
Outputs in cluster shows delete from stream button

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#10199]
The Outputs in Cluster page (`/system/outputs`) includes buttons to delete Outputs from Streams. However, it is not clear to me which Stream it is referring to. As far as I can remember we only rendered those buttons in the Outputs in Stream page (`/streams/<id>/outputs`) in the past, but I am not sure if this change was intentional or not.

<img width="1383" alt="Screenshot 2021-03-04 at 14 49 26" src="https://user-images.githubusercontent.com/716185/109989639-f9421500-7d08-11eb-9eb6-5ff998922303.png">

Clicking on the button I get a 404 error.

## Expected Behavior
Outputs in Cluster should not have an option to remove them from a Stream unless it is clear how this is going to affect the Graylog instance.

## Current Behavior
Outputs in Cluster has a button to remove Outputs from Streams but I can find no reference to which Stream this is going to affect.

## Steps to Reproduce (for bugs)
1. Go to Outputs in cluster page through `System -> Outputs`
2. Create a new Output
3. See the "Delete from Output" button next to the new Output

## Your Environment
* Graylog Version: 4.1.0-SNAPSHOT(2f5f55a5ffe0e5e29292d7601a5e4e5e0049021c)

**Comment by thll** [comment]
The button has been removed in #12195
