### ISSUE TITLE
/system/inputs and /system/outputs REST API endpoint does not reveal the the possible types

### ISSUE THREAD

**Issue by dfch** [Graylog2/graylog2-server#1019]
When creating an Input via `POST /system/inputs` REST you have to specify the `type` of plugin by stating the full qualified name of the plugin class (`org.graylog2.inputs.gelf.tcp.GELFTCPInput` for the *TCP GELF input* as seen in the example below).

However, there is no way to get the list of full qualified names of the inputs or outputs (except for user defined plugins via `GET /system/plugins`). This means we need source code access to actually be able to resolve and find these names.

	POST http://192.168.174.172:12900/system/inputs HTTP/1.1
	User-Agent: Mozilla/5.0 (Windows NT; Windows NT 6.1; de-CH) WindowsPowerShell/3.0
	Content-Type: application/json
	Authorization: Basic RWRnYXJTY2huaXR0ZW5maXR0aWNoOlBAc3N3MHJk
	Host: 192.168.174.172:12900
	Content-Length: 553

	{
		"configuration":  {
		"tls_key_password":  "P@ssw0rd",
		"recv_buffer_size":  1048576,
		"max_message_size":  2097152,
		"bind_address":  "0.0.0.0",
		"port":  12201,
		"tls_enable":  false,
		"use_null_delimiter":  true
		},
		"title":  "myNewGlobalGelfTcpInput",
		"global":  true,
		"type":  "org.graylog2.inputs.gelf.tcp.GELFTCPInput"
	}

When using `GET /system/plugins`you actually get a list where the full name of the plugins is displayed (via `unique_id` as `biz.dfch.j.graylog.plugin.alarm.dfchBizClickatellAlarmPlugin` like in the example below):

	{
	  "plugins": [
		{
		  "unique_id": "biz.dfch.j.graylog.plugin.alarm.dfchBizClickatellAlarmPlugin",
		  "name": "d-fens Clickatell AlarmCallback",
		  "author": "Ronald Rink, d-fens GmbH",
		  "url": "http://d-fens.ch",
		  "version": {
			"major": 1,
			"minor": 0,
			"patch": 0,
			"additional": null,
			"abbrev_commit_sha": null
		  },
		  "description": "d-fens plugin for sending short messages (SMS) via Clickatell",
		  "required_version": {
			"major": 1,
			"minor": 0,
			"patch": 0,
			"additional": null,
			"abbrev_commit_sha": null
		  },
		  "required_capabilities": [
			"SERVER"
		  ]
		}
	  ],
	  "total": 1
	}

* There should be something similar to *built-in* plugins. 
* The same applies to output plugins as well.

**Comment by dennisoelkers** [comment]
This is actually possible for both Inputs and Outputs. You can get all available Input types by querying /system/inputs/types which returns something like this:

```
{
  "types" : {
    "org.graylog2.inputs.gelf.http.GELFHttpInput" : "GELF HTTP",
    "org.graylog2.inputs.gelf.udp.GELFUDPInput" : "GELF UDP",
    "org.graylog2.inputs.syslog.tcp.SyslogTCPInput" : "Syslog TCP",
    "org.graylog2.inputs.kafka.KafkaInput" : "Kafka Input",
    "org.graylog2.inputs.syslog.udp.SyslogUDPInput" : "Syslog UDP",
    "org.graylog2.inputs.radio.RadioAMQPInput" : "Graylog Radio Input (AMQP)",
    "org.graylog2.inputs.gelf.tcp.GELFTCPInput" : "GELF TCP",
    "org.graylog2.inputs.radio.RadioKafkaInput" : "Graylog Radio Input (Kafka)",
    "org.graylog2.inputs.random.FakeHttpMessageInput" : "Random HTTP message generator",
    "org.graylog2.inputs.gelf.amqp.GELFAMQPInput" : "GELF AMQP",
    "org.graylog2.inputs.raw.tcp.RawTCPInput" : "Raw/Plaintext TCP",
    "org.graylog2.inputs.misc.metrics.LocalMetricsInput" : "Internal metrics reporter",
    "org.graylog2.inputs.misc.jsonpath.JsonPathInput" : "JSON path from HTTP API",
    "org.graylog2.inputs.raw.udp.RawUDPInput" : "Raw/Plaintext UDP"
  }
}
```

Key of the ```types``` map is the class name, value is the human name. You can get even more information about an available Input when querying /system/inputs/types/<class name>

Same works for the Outputs, although in a slightly different way. You can get a consolidated listing of what you can get for Inputs using both endpoints when querying /system/outputs/available.
It looks like this:

```
{
  "types" : {
    "org.graylog2.outputs.LoggingOutput" : {
      "name" : "STDOUT Output",
      "type" : "org.graylog2.outputs.LoggingOutput",
      "requested_configuration" : {
        "prefix" : {
          "additional_info" : { },
          "default_value" : "Writing message: ",
          "description" : "How to prefix the message before logging it",
          "human_name" : "Prefix",
          "is_optional" : true,
          "attributes" : [ ],
          "type" : "text"
        }
      },
      "human_name" : "An output writing every message to STDOUT.",
      "link_to_docs" : ""
    },
    "org.graylog2.outputs.GelfOutput" : {
      "name" : "GELF Output",
      "type" : "org.graylog2.outputs.GelfOutput",
      "requested_configuration" : {
        "port" : {
          "additional_info" : { },
          "default_value" : 12201,
          "description" : "This is the port of the destination",
          "human_name" : "Destination port",
          "is_optional" : false,
          "attributes" : [ ],
          "type" : "number"
        },
        "protocol" : {
          "additional_info" : {
            "values" : {
              "TCP" : "TCP",
              "UDP" : "UDP"
            }
          },
          "default_value" : "TCP",
          "description" : "The protocol used to connect",
          "human_name" : "Protocol",
          "is_optional" : true,
          "attributes" : [ ],
          "type" : "dropdown"
        },
        "hostname" : {
          "additional_info" : { },
          "default_value" : "",
          "description" : "This is the hostname of the destination",
          "human_name" : "Destination host",
          "is_optional" : false,
          "attributes" : [ ],
          "type" : "text"
        }
      },
      "human_name" : "An output sending GELF over TCP or UDP",
      "link_to_docs" : ""
    }
  }
}
```

The key of the types map is still the class name of the output, but the value is an object containing the metadata for the output and a ```requested_configuration``` attribute which contains the necessary fields and their descriptions needed to configure the output.

**Comment by dfch** [comment]
thanks for the write-up! (I just did not find it in the documentation)
