### ISSUE TITLE
Gelf HTTP size limit? (follow up on issue #1011)

### ISSUE THREAD

**Issue by CarlosSardo** [Graylog2/graylog2-server#1021]
Hi,

When Sending in log data, described here: http://docs.graylog.org/en/1.0/pages/sending_data.html?highlight=post#gelf-sending-from-applications

I noticed that messages above 8KB, sent via HTTP POST without chunking, do not get persisted.

Is there a way to raise this limit from 8KB to X KB?

Cheers,
Carlos

**Comment by joschi** [comment]
You can use the `rest_max_chunk_size` setting as described in https://github.com/Graylog2/graylog2-server/issues/1011#issuecomment-76678946

Kindly use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or [IRC channel](webchat.freenode.net/?channels=%23graylog2) for general support requests.
