### ISSUE TITLE
Failed to load SIGAR. Falling back to JMX implementations. Error while trying first install

### ISSUE THREAD

**Issue by chrispcall** [Graylog2/graylog2-server#1022]
I have searched all over and admittedly, I am not great with Linux but I am learning.

I was following along in the manual install guide and I got all the pre-reqs installed and then started mongod and then jumped into a different ssh session to my server to go into the bin directory and run the './graylogctl start' command and then when I check the log in ../log/graylog.log, I see an INFO message that says:

"INFO : org.graylog2.shared.system.stats.SigarService - Failed to load SIGAR. Falling back to JMX implementations."

The last message is "org.graylog2.shared.buffers.ProcessBuffer - Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>." and I am not receiving the "DEBUG: org.elasticsearch.transport.netty - [graylog-server] connected to node" message that the install guide says I should see.  Any help is appreciated.

Finally, if this is the wrong place to put this, please let me know and I will post this to the forum or wherever I need to post to get help.  I really appreciate it!  I did see one post about this message and a 'Telemetry' plugin problem and I tried renaming a file that had the name 'telemetry' but the plugin is still showing up as loaded in my log file.

Thanks,
Chris

**Comment by SjonHortensius** [comment]
I'm pretty sure that message is (as it's marked) purely informational. After this message; graylog logs ```org.graylog2.shared.buffers.InputBufferImpl - Message journal is enabled.``` for me. Could you have a look at your journal settings? I don't see any messages from *.netty when starting

**Comment by chrispcall** [comment]
Thank you for responding.

I actually tried installing Graylog again using this script: https://github.com/mrlesmithjr/graylog2/blob/master/install_graylog2_90_ubuntu.sh and now I am getting different errors after attempting to resolve a problem with it connecting to Elasticsearch.  Here is the output of "sudo java -jar /opt/graylog2-server/graylog2-server.jar --debug" : http://paste.ubuntu.com/10551013/

My /etc/graylog2.conf: http://paste.ubuntu.com/10551065/
My /etc/elasticsearch/elasticsearch.yml: http://paste.ubuntu.com/10551073/

I have also tried just about every combination of bind ports and change the TCP port from 9350 to 9351 and tried to see which ports are in use (right now, running "sudo netstat -tulpn | grep :9350" returns: tcp6       0      0 :::9350                 :::*                    LISTEN      23093/java) even when I am not running the "sudo java -jar /opt/graylog2-server/graylog2-server.jar --debug" command.  

I have played with Linux off and on but I'm new to manually installing and configuring software like this but I've learned a lot already in trying to get this app going.

Thanks for any help,
Chris

**Comment by joschi** [comment]
From http://paste.ubuntu.com/10551013/
> ```
org.elasticsearch.transport.BindTransportException: Failed to bind to [9350]
[...]
Caused by: org.elasticsearch.common.netty.channel.ChannelException: Failed to bind to: 0.0.0.0/0.0.0.0:9350
[...]
Caused by: java.net.BindException: Address already in use
```
There's already some process running on Port 9350 on that machine. You should close any other processes using that port before starting Graylog2 or change that port in your graylog2.conf (https://github.com/Graylog2/graylog2-server/blob/0.92.4/misc/graylog2.conf#L152-153).

This being said, I'd recommend upgrading to (or rather starting with) Graylog 1.0.0 which has been recently released: https://www.graylog.org/announcing-graylog-v1-0-ga/

And since this isn't a bug or a feature request, I'm closing this issue. Kindly use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or our [IRC channel #graylog2 at Freenode](https://webchat.freenode.net/?channels=%23graylog2) for general support requests.
