### ISSUE TITLE
Graylog Server not supporting Wired Tiger MongoDB 3 Backend

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#1024]
After upgrading to MongoDB 3, I've decided to change the backend to Wired Tiger (as suggested here: https://docs.mongodb.org/v3.0/release-notes/3.0-upgrade/)

Graylog2 Server is trying to search the collections and not working, and then tries to recreate those collections.

This issue is the same as described here: https://groups.google.com/forum/#!topic/mongodb-user/pXf8DbQwQnw

Reproduced on Graylog v1, and MongoDB 3 with the option storageEngine=wiredTiger

Thanks :)

**Comment by joschi** [comment]
The version of the MongoDB Java driver used by Graylog at the moment (2.12.x) is incompatible with MongoDB 3.0 according to http://docs.mongodb.org/ecosystem/drivers/java/#mongodb-compatibility

We'll evaluate whether an upgrade in the 1.0.x series is possible without any problems. Until then please refrain from updating to MongoDB 3.0 for the database used by Graylog.

**Comment by rikatz** [comment]
@joschi I'm using on my environment (even with the unsupported driver) and it works fine.

The only thing is that I cannot use this 'wiredTiger' version, but no problem at all.

I'm with some performance issue after removing the 'radio' nodes and using only graylog server nodes, but I think it's related with something else than MongoDB.

If you need some more information I can send them to you (about the MongoDB usage).

**Comment by rikatz** [comment]
:+1: Tks for the great job guys :)
