### ISSUE TITLE
Keep MongoDB information on memory

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#1025]
I've seen that for every message that arrives, Graylog Server asks for the MongoDB for the streams collection.

As this probably wouldn't be a big issue, I do see on the JVisualVM the 'org.bson.io.Bits.readFully()' as the top CPU time consuming (almost 30% of the CPU time)

I don't know if this is an issue of my environment, or if there is somehow a way to keep those information on Graylog Server memory (as this information is relatively small) and just get those informations from the MongoDB if there is a change on the stream rules/configuration, as an example.

Thanks :)

**Comment by runningman84** [comment]
+1

**Comment by bernd** [comment]
The server does not query MongoDB for each message for streams. There is a job that asks MongoDB every second for new and updated streams. This job runs for every processbuffer thread. (see `processbuffer_processors` setting in graylog.conf) So if you have lots of processbuffer processors running, there might be some MongoDB traffic.

There are other parts of the code that do similar queries every second. But there should be no code that queries MongoDB for every message.

We are aware of this and are going to solve this in the future. I needs some more thinking to solve this in all the different parts of the code.
