### ISSUE TITLE
Huge delay in graylog1 to update the logs

### ISSUE THREAD

**Issue by Ramasudhastv** [Graylog2/graylog2-server#1026]
I have configured graylog1 and forwarded application logs to the graylog server using gelf , but there is a 30 to 45 minutes delay to update the logs in gray log server , please help me to fix the issue.

**Comment by bernd** [comment]
Are the clock of your Graylog server and GELF sender in sync and using the same time zone?

Run a search with an absolute time range and select one day in the future for the second time. If you see new messages there, you probably have an issue with time and/or time zones.

**Comment by Ramasudhastv** [comment]
Thanks bernd , My Graylog server was not synced up with my ntp server, Problem solved now

Do we have any installation script for graylog1 latest version similar to graylog2 which we have already.
If yes please provide me the path.

**Comment by joschi** [comment]
@Ramasudhastv Which installation script do you mean?

**Comment by Ramasudhastv** [comment]
The below script we are using for Graylog2 0.20.1 installation 
Script Location: https://gist.github.com/PowerWagon/9694436 
Similarly do we have installation script for Graylog 1.0 ?

**Comment by joschi** [comment]
We recommend using our officially maintained DEB or RPM packages (see http://docs.graylog.org/en/1.0/pages/installation.html#operating-system-packages) or any other officially supported installation methods: http://docs.graylog.org/en/1.0/pages/installation.html

**Comment by Ramasudhastv** [comment]
Thank you very much quick support .
