### ISSUE TITLE
Change default search range when clicking show received messages on an input

### ISSUE THREAD

**Issue by cawfehman** [Graylog2/graylog2-server#10260]
## What?
When clicking show received messages on an input, it takes you to a search and defaults to all messages timeframe.  Change this last 5 minutes.

## Why?
If you click show received messages for a busy input that might be storing messages in multiple indices, there can be a significant delay and unnecessary strain on both GL and ES as it retrieves all messages.  Most of the time I use this feature it is to validate message types on an input and I'm really only interested in the most recent ones as a sample.  If I want a larger time frame, I can select one after.

## Your Environment

* Graylog Version: 4.0.2
* Elasticsearch Version: 6.8.14
* MongoDB Version: 4.4
* Operating System: Centos 7
* Browser version:

**Comment by bernd** [comment]
Refs https://github.com/Graylog2/graylog2-server/issues/5620

**Comment by aim4r** [comment]
Not sure if relevant, but please note that in some setups, including mine, `Last 5 minutes` option is removed. The minimum we have setup under "Search Configuration" is one hour.

If the default gets ever changed from `Search all messages` to `Last 5 minutes`, then hopefully that won't introduce a bug for those who have removed the `Last 5 minutes` option.

**Comment by cawfehman** [comment]
That's a good point... perhaps the fix should involve either making this user configurable, or programmatically determining the lowest configured search range per install and using that.

**Comment by tellistone** [comment]
I'd suggest this be last 24h rather than last 5 minutes. This button is often used for troubleshooting, and the possibility that the user sends the message and then takes more than 5 minutes to get here and click the button, and then as a result doesn't see the messages, seems all to real.

This is a fairly desirable change for Graylog Cloud - clicking this button causing Graylog Cloud to throw an error because the result set is too big is not a good look for us.

![image](https://github.com/Graylog2/graylog2-server/assets/85873295/be3b653f-577e-4b31-9b5d-7883fc115365)

**Comment by williamtrelawny** [comment]
Perhaps, but even with massive customers (approaching 1TB/day) who have a fleet of nodes and who also may not have the most sound sharding configuration, even a 24h period could be detrimental. 

I think there are 2 different use cases that we may be muddling together here: 
1. A button for troubleshooting, making sure this Input is receiving any messages
    - A solution for this would be to show the last N number of messages this Input has received, regardless of the time range.
1. A button to simply show all messages that were ingested by this Input, as users can use Inputs to logically separate messages and don't need to troubleshoot the Input itself.
    - The solution here would be to treat this like any other default search: a time range of last 5 minutes and the search filter `gl2_source_input:[input-id]` pre-populated in the search bar.

I suppose what I'm saying is there should be 2 separate buttons/clicks for the 2 separate use cases- Troubleshooting the Input and Input-based Search Filtering. Doesn't have to be another button necessary, but a distinct user click for sure.

**Comment by ed-graylog** [comment]
This is currently tied to HS 1898317237
