### ISSUE TITLE
sso-auth plugin with graylog 4.0.5

### ISSUE THREAD

**Issue by sameer29nov** [Graylog2/graylog2-server#10273]
We were using graylog3.3.8 earlier now want to upgrade it to 4.0.5, but when we tried to upgrade it got successful but sso plugin is not working , we have verified there is no old plugin present, but it still doesn't work for sso login as per https://docs.graylog.org/en/4.0/pages/upgrade/graylog-4.0.html#sso-authentication-plugin

so I wanted to know how to work with this what we need to do in docker file,

we need sso authentication to work with graylog4.0.5 like it was working for 3.X version with plugin. currently I am able to login with default username and password, but wanted to work with sso login

Graylog Version: 4.0.5
Elasticsearch Version: 7.0.11
MongoDB Version: 4.2.12
Operating System: Debian container
Browser version: chrome Version 89.0.4389.82

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
