### ISSUE TITLE
2015-03-04 10:58:28,887 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#1029]
Hi,

I've started 2 stock 1.0 AMI's at Amazon and the second node is constantly saying : 2015-03-04 10:58:28,887 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering..

What to do?

**Comment by joschi** [comment]
Kindly use the [mailing list](https://groups.google.com/forum/#!forum/graylog2) or the [IRC channel #graylog2 on Freenode](https://webchat.freenode.net/?channels=%23graylog2) for general support requests.
