### ISSUE TITLE
UI: Allow rearranging/static ordering of dashboard tabs

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#10313]
## What?

As a creator and sharer of dashboards, I'd like to be able to statically set, or drag/drop/rearrange the tabs as needed. 

## Why?

Presently, after performing an upgrade, the user I was working with found that tabs were rearranged, and then after another upgrade, the tabs were in a different order. 

## Your Environment

* Graylog Version: 4.0.5

See HS-349743119 for more context/video showing the issue.

**Comment by dennisoelkers** [comment]
Closing this in favor of https://github.com/Graylog2/graylog2-server/issues/7470.

The tab order issue was fixed in https://github.com/Graylog2/graylog2-server/pull/9812 which was part of `4.0.2`. If it was still an issue after this version, please reopen the issue.
