### ISSUE TITLE
Lost messages in Message Processing in case of errors - Debug Message Processing

### ISSUE THREAD

**Issue by mburni** [Graylog2/graylog2-server#10319]
Graylog server log shows repeatedly the message:

`2021-03-23T16:39:09.905+01:00 WARN  [ProcessBufferProcessor] Unable to process message <e9172411-8bed-11eb-a9db-005056a14fc5>: java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime`

Other Issues like [5637](https://github.com/Graylog2/graylog2-server/issues/5637) and [7363](https://github.com/Graylog2/graylog2-server/issues/7363) describes, that they are caused by incoming messages which cannot be processed by the ProcessBufferProcessor caused by a cast error in a pipeline rule or extractor.

We would like to figure out which of our hundreds of pipeline functions and extractors causes this and what the incoming message looks like.
Unfortunately only the message ID is logged and the incoming message is not stored in elasticsearch. 

## Expected Behavior
Dropped messages are logged to server log.

## Current Behavior
Messages are dropped during runtime errors from pipeline functions and extractors. A warning message containing the message ID is logged in the server log. The original message is lost.

## Possible Solution
Extend the the [logmessage](https://github.com/Graylog2/graylog2-server/blob/3.3.11/graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java#L124) to log the original incoming message, which cannot be processed.

Logging might be configurable, to enable/disable logging for the ProcessBufferProcessor subsystem at a defined loglevel.

## Context

Messages with processing errors are lost and we cannot figure out which ones. So we are not able to fix the pipeline rule or extractor which is the cause.
We have a complex environment with 7 graylog server many different inputs, some with extractors and very many pipeline rules.

It's not an option to disable inputs because messages may be lost. Disabling extractors or pipeline functions will cause messages to be processed, enriched, parsed and stored wrong.

Writing all received messages to the server logfile for debugging purposes as suggested in [this discussion](https://community.graylog.org/t/debugging-message-processing/8652/6) is not an option, because our graylog cluster processes up to 15.000 msgs/sec from different sources of the IT-infrastructure and this will flood the log files and slow down message processing.

## Your Environment

* Graylog Version: 3.3.11 (planing migration to 4.0.5)
* Java Version: 1.8
* Elasticsearch Version: 6.8.6
* MongoDB Version: 4.2
* Operating System: Red Hat 7

**Comment by bernd** [comment]
@mburni Can you please show us the complete stack trace? Without context this is hard to debug. :slightly_smiling_face: Thank you!

**Comment by mburni** [comment]
Hi @bernd,

there is no stack trace. I've posted the complete message. Here is another example, which shows the surrounding messages:

```
2021-03-25T05:18:51.055+01:00 WARN  [ArchiveRetentionStrategy] Not running archive job for index "logmonitor_11174", there is already a job running for index "logmonitor_11174"!
2021-03-25T05:18:57.442+01:00 WARN  [ProcessBufferProcessor] Unable to process message <37cad914-8d21-11eb-a9db-005056a14fc5>: java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime
2021-03-25T05:18:57.442+01:00 WARN  [ProcessBufferProcessor] Unable to process message <37cb0020-8d21-11eb-a9db-005056a14fc5>: java.lang.ClassCastException: Cannot cast java.lang.String to org.joda.time.DateTime
2021-03-25T05:19:07.790+01:00 INFO  [O365PollerTask] Input [6045fa8b1f27756091e8395e] :: Storing O365 checkpoints [{AZURE_ACTIVE_DIRECTORY=2021-03-25T04:19:06.748Z, SHAREPOINT=2021-03-25T04:19:07.095Z, EXCHANGE=2021-03-25T04:19:07.249Z, GENERAL=2021-03-25T04:19:07.551Z, DLP_ALL=2021-03-25T04:19:07.673Z}]
```

**Comment by bernd** [comment]
@mburni We have an improvement on our roadmap to make this easier to debug within the Graylog user interface in the future. A short term improvement has been implemented in #10421.

Once that's merged you will be able to enable debug logging for the `ProcessBufferProcessor` class via the `log4j2.xml` configuration file or at runtime via an API call on each node:

`curl -H Requested-by:curl -X PUT localhost:9000/api/system/loggers/org.graylog2.shared.buffers.processors.ProcessBufferProcessor/level/DEBUG` (use `INFO` to switch it back)

When `DEBUG` is enabled, the full stack trace of the error and the full message will be logged.

**Comment by l0calhost** [comment]
Thanks for the change and the quick release, @bernd! 

One additional thought about this: By logging the failing messages to the server log, they aren't indexed in Elasticsearch anymore and drop out of the graylog scope. Would it be possible to send those messages to some sort of bypass or clearing queue to keep them in the scope of indexed messages, even without being fully processed? Maybe those messages can be routed to a special stream? Or maybe they can be tagged in some way? 

As far as i remember, there once was a field "gl2_processing_error", perhaps this can be used at this point, too.

**Comment by bernd** [comment]
@l0calhost As mentioned above, we have something on our roadmap to improve the handling of these processing errors. :slightly_smiling_face: Thanks!

I am closing this now since we improved the debugging of processing errors.
