### ISSUE TITLE
Type Field Refresh Interval has no effect on Elasticsearch Template/Index refresh_interval ?

### ISSUE THREAD

**Issue by ka1lie** [Graylog2/graylog2-server#10329]
Hello! I have a problem with Index Template Settings as a Type Field Refresh Interval. My current template which created from Graylog has no value refresh_interval if I CURL ES template and as a default refresh interval to search avaliability is equal 1sec. I want to set this value much higher to reduce ES load.
## Expected Behavior

When I change Type Field Refresh Interval in index template settings or set refresh_interval by CURL, the index value refresh_interval should be appeared in template settings and apply to new index after rotation.

`curl -X PUT localhost:9200/_template/cacti-template -H 'Content-Type: application/json' -d'
{
    "index_patterns" : ["*"],
    "order" : -1,
    "settings" : {
        "number_of_shards" : 1,
		"refresh_interval" : "600s"
    }
}'`
## Current Behavior

After rotation my template has reset to defaults settings.
## Possible Solution

Idk.
## Steps to Reproduce (for bugs)

1. Change Type Field Refresh Interval value OR set refresh_interval by CURL
2. Rotate active index
3. Settings was back to defaults

## Your Environment

* Graylog Version: Prod 3.3.2 Test 4.0.5
* Java Version: 1.8.0_212 both
* Elasticsearch Version: Prod 5.6.8 Test 7.10.2
* MongoDB Version: Prod 3.6.9 Test 4.2.13
* Operating System: CentOS7
* Browser version: Google Chrome 89.0.4389.90

**Comment by ka1lie** [comment]
I do a change in template with this:

`curl -X PUT -H 'Content-Type: application/json' -d @'cacti.json' 'http://localhost:9200/_template/cacti-template?pretty'`

```
{
  "template": "cacti_*",
          "settings": {
              "index": {
                  "refresh_interval": "3600s"
                       }
             },
  "mappings": {
    "properties": {
      "http_method": {
        "type": "keyword"
      },
      "http_response_code": {
        "type": "long"
      },
      "ingest_time": {
        "type": "date",
        "format": "strict_date_time"
      },
      "took_ms": {
        "type": "long"
      }
    }
  }
}

```

I receive this template: 

`curl -X GET localhost:9200/_template/cacti-template?pretty -H 'Content-Type: application/json'`

```
{
  "cacti-template" : {
    "order" : 0,
    "index_patterns" : [
      "cacti_*"
    ],
    "settings" : {
      "index" : {
        "refresh_interval" : "3600s"
      }
    },
    "mappings" : {
      "properties" : {
        "http_method" : {
          "type" : "keyword"
        },
        "ingest_time" : {
          "format" : "strict_date_time",
          "type" : "date"
        },
        "took_ms" : {
          "type" : "long"
        },
        "http_response_code" : {
          "type" : "long"
        }
      }
    },
    "aliases" : { }
  }
}
```

And after index rotation I get this:

`curl -X GET localhost:9200/_template/cacti-template?pretty -H 'Content-Type: application/json'`

```
{
  "cacti-template" : {
    "order" : -1,
    "index_patterns" : [
      "cacti_*"
    ],
    "settings" : {
      "index" : {
        "analysis" : {
          "analyzer" : {
            "analyzer_keyword" : {
              "filter" : "lowercase",
              "tokenizer" : "keyword"
            }
          }
        }
      }
    },
    "mappings" : {
      "_source" : {
        "enabled" : true
      },
      "dynamic_templates" : [
        {
          "internal_fields" : {
            "mapping" : {
              "type" : "keyword"
            },
            "match_mapping_type" : "string",
            "match" : "gl2_*"
          }
        },
        {
          "store_generic" : {
            "mapping" : {
              "type" : "keyword"
            },
            "match_mapping_type" : "string"
          }
        }
      ],
      "properties" : {
        "gl2_processing_timestamp" : {
          "format" : "uuuu-MM-dd HH:mm:ss.SSS",
          "type" : "date"
        },
        "gl2_accounted_message_size" : {
          "type" : "long"
        },
        "gl2_receive_timestamp" : {
          "format" : "uuuu-MM-dd HH:mm:ss.SSS",
          "type" : "date"
        },
        "full_message" : {
          "fielddata" : false,
          "analyzer" : "standard",
          "type" : "text"
        },
        "streams" : {
          "type" : "keyword"
        },
        "source" : {
          "fielddata" : true,
          "analyzer" : "analyzer_keyword",
          "type" : "text"
        },
        "message" : {
          "fielddata" : false,
          "analyzer" : "standard",
          "type" : "text"
        },
        "timestamp" : {
          "format" : "uuuu-MM-dd HH:mm:ss.SSS",
          "type" : "date"
        }
      }
    },
    "aliases" : { }
  }
}

```

**Comment by bernd** [comment]
@ka1lie The "field type refresh interval" is not the ES index refresh interval. This is the interval for the background job that fetches all fields from ES indices to store them in MongoDB so we can display the fields on the search page.
