### ISSUE TITLE
Maps in reports not displaying correctly

### ISSUE THREAD

**Issue by chris-y** [Graylog2/graylog2-server#10365]
When adding a World Map to a report, the report generates with the correct circles but the map itself is invisible or washed out.

## Expected Behavior
The report should contain a map which looks like this:
![image](https://user-images.githubusercontent.com/1818803/113304387-e3b90e80-92f9-11eb-8bf3-8cfdc402ecb0.png)

## Current Behavior
The map in the report looks like this:
![image](https://user-images.githubusercontent.com/1818803/113304448-f3d0ee00-92f9-11eb-99fb-e89e9681b340.png)

## Steps to Reproduce (for bugs)

1. Create a World Map visualisation on a dashboard
2. Add the World Map to a report
3. Generate the report (via "download report now")
4. Observe that the underlying map is not displaying the same as on the dashboard

## Context

Was trying to add a world map to a report but with the map itself being barely visible the data isn't useful.

## Your Environment

* Graylog Version: 4.0.5
* Java Version: 11.0.10
* Elasticsearch Version: 7.12.0
* MongoDB Version: 3.6.8
* Operating System: Ubuntu 20.04 LTS
* Browser version: Edge Chromium 89.0.774.63

**Comment by kmerz** [comment]
Will be fixed with: https://github.com/Graylog2/graylog2-server/pull/10450

**Comment by linuspahl** [comment]
Thanks again for reporting this issue, the fix will be part of the next patch release.
