### ISSUE TITLE
information unit field type (and extractor converter)

### ISSUE THREAD

**Issue by maniel** [Graylog2/graylog2-server#1038]
Many logs contain informations regarding sent/received/stored information amount, generally in bytes. It would be nice if we could query them as their multiples, like KB, MB, MiB, GiB etc, like `sent:[1MB TO 1GB]`, there could be an extractor converter for this which would help with information units conversion (bytes to bits, kibibytes to megabits etc), the numeric bytes value would be displayed as appropriate multiple of bytes everywhere, we finally could use some more human-readable units in charts.

**Comment by jalogisch** [comment]
with the given elasticsearch query language this will not be possible. If we can change the query language this might be possible.
