### ISSUE TITLE
why  /api/cluster/metrics/multiple   /api/cluster    The request keeps sending

### ISSUE THREAD

**Issue by zhansang** [Graylog2/graylog2-server#10398]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
/api/cluster/metrics/multiple
/api/cluster
The request keeps sending

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
The Graylog web interface is executing requests on a regular basis to load metrics and status information. This is not a bug.
