### ISSUE TITLE
ES Cluster Status shows red, but UI shows green

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#10407]
## Expected Behavior

When an ES cluster is RED, the UI should have the information in red.

## Current Behavior

When restarting a cluster and waiting for shards to be assigned, the status shows as RED, but the UI shows green as the background for the message, which is a bit confusing:

![image](https://user-images.githubusercontent.com/898627/114222253-55b5d700-993c-11eb-92ef-94a1f4cccf02.png)

## Steps to Reproduce (for bugs)
In my case, all I did was restart all the nodes on my ES cluster simultaneously.

## Context
It's a bit confusing to have a red cluster status but the UI showing green. 

## Your Environment

* Graylog Version: 4.0.6
* Java Version: 1.8
* Elasticsearch Version: 7.10.2
* MongoDB Version: Percona Mongodb 4.0.2
* Operating System: Ubuntu 20.04
* Browser version: https://www.whatsmybrowser.org/b/E7ZOS

**Comment by mikkolehtisalo** [comment]
I was just observing the same using the light theme. I believe this used to work correctly at some point.
