### ISSUE TITLE
Aggregation Builder: Changing order of metric and sort aggregation elements using drag and drop.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#10418]
## What?
The order of the metric and sort aggregation elements should be configurable, because it affects the result of an aggregation. A user should be able to change the order using drag and drop.

UI example (one drag handle per element):
![image](https://user-images.githubusercontent.com/46300478/114395659-f1458280-9b9c-11eb-9399-ba85f234167b.png)

In the previous aggregation builder version, a user could change the order using drag and drop inside the select component.
![image](https://user-images.githubusercontent.com/46300478/114395917-3a95d200-9b9d-11eb-8b71-989178bfc8d7.png)

**Comment by dennisoelkers** [comment]
Fixed in #10479.
