### ISSUE TITLE
Message Table Hostname Field Content wraps to new line

### ISSUE THREAD

**Issue by edward-marrufo-graylog** [Graylog2/graylog2-server#10439]
## Expected Behavior

As a Graylog user utilizing the dashboard I would expect to see the sane host name text wrapping. For example on a hostname where the character count is longer than ~28 characters, we break the host name into a new line.

## Current Behavior

Currently we split the host name onto a new line if it exceeds ~28 characters. This can result in a single character being on a new line.

## Possible Solution

Split a host name on a period character. This was working as expected on Graylog version 3.3 however the unexpected behavior is showing on version 4.0.

## Steps to Reproduce (for bugs)

1. See HS-373843850 for supporting information.

**Comment by dennisoelkers** [comment]
Fixed in #13469.
