### ISSUE TITLE
Support for OpenSearch

### ISSUE THREAD

**Issue by T100D** [Graylog2/graylog2-server#10445]
As Announced, there is coming an open source version of Elasticsearch coming called OpenSearch, after elastic changed  to a proprietary dual license.

Could it be a consideration for Graylog to support this open version now and or in the future, to keep Graylog to completely open when needed?

The open source version is derived from Elasticsearch & Kibana 7.10.2. As it shall be a fork, future developments logically to be are unknown. There could even be a chances in a cooperation.

Link to the announcement:
https://logz.io/blog/opensearch-elasticsearch-fork/

OpenSearch on Github: https://github.com/opensearch-project

**Comment by dwbenjamin** [comment]
OpenSearch 1.0.0-rc1 fails.

1. Start Opensearch with security disabled.
`docker run --name opensearch -p 9200:9200 -p 9600:9600 \
  -e "discovery.type=single-node" \
  -e "plugins.security.disabled=true" \
  -d opensearchproject/opensearch:latest`

2. Test connection to Opensearch, using no security and admin admin as user and password.
`curl -XGET http://admin:admin@localhost:9200`

3. check the result
`{
  "name" : "542826c5649a",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "4LuAXF5tSUKdGdGC_z2-Gg",
  "version" : {
    "distribution" : "opensearch",
    "number" : "1.0.0-rc1",
    "build_type" : "tar",
    "build_hash" : "26d579287f50bb33e17c8fe1f05ea208d5c64d1f",
    "build_date" : "2021-05-28T18:18:49.848386Z",
    "build_snapshot" : false,
    "lucene_version" : "8.8.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  }
}`

4. Start Mongo
`docker run --name mongo -d mongo:4.2`

5. Start Graylog with Elasticsearch version set to 7.
`docker run --name graylog --link mongo --link opensearch \
  -p 9000:9000 -p 12201:12201 -p 1514:1514 \
  -e GRAYLOG_HTTP_EXTERNAL_URI="http://127.0.0.1:9000/" \
  -e GRAYLOG_ELASTICSEARCH_VERSION=7 \
  -e GRAYLOG_ELASTICSEARCH_HOSTS=http://admin:admin@localhost:9200 \
  -d graylog/graylog:4.0`

6. See errors in logs, complete logs attached to this post.
`2021-06-24 19:57:36,366 ERROR: org.graylog2.periodical.IndexRangesMigrationPeriodical - Uncaught exception in periodical
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: An error occurred: 
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.exceptionFrom(ElasticsearchClient.java:136) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:99) ~[?:?]
        at org.graylog.storage.elasticsearch7.ElasticsearchClient.execute(ElasticsearchClient.java:92) ~[?:?]
        at org.graylog.storage.elasticsearch7.ClusterAdapterES7.isConnected(ClusterAdapterES7.java:162) ~[?:?]
        at org.graylog2.indexer.cluster.Cluster.isConnected(Cluster.java:115) ~[graylog.jar:?]
        at org.graylog2.periodical.IndexRangesMigrationPeriodical.doRun(IndexRangesMigrationPeriodical.java:88) ~[graylog.jar:?]
        at org.graylog2.plugin.periodical.Periodical.run(Periodical.java:77) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]`
[graylog.log](https://github.com/Graylog2/graylog2-server/files/6711923/graylog.log)

**Comment by paripooranan** [comment]
See if this helps : https://github.com/opensearch-project/documentation-website/issues/72

**Comment by vrga** [comment]
Graylog v4.1.3 seems to be working fine with the compatibility option enable on opensearch 1.0.0

**Comment by uskr** [comment]
OpenSearch 1.0 is wire-compatible with Elasticsearch 7.10.2, with the only difference been that OpenSearch internally uses the OpenSearch version (1.0.x), so the major version here been "1".

For users, if you experience problems, the easy quick fix is to just set this option on your OpenSearch Cluster:

PUT /_cluster/settings
{
  "compatibility" : {
    "override_main_response_version" : true
  }
}

That's it. OpenSearch will report as 7.10.2 and not 1.0.x, and all will be well.

Long term, I suggest Graylog to add the OpenSearch implementation of the Java High Level REST client:

https://github.com/opensearch-project/OpenSearch/blob/main/client/rest-high-level/src/main/java/org/opensearch/client/

And also, the Elastic implementation of the Java High Level REST client is NO LONGER open source:

https://discuss.opendistrocommunity.dev/t/elastic-java-clients-are-no-longer-open-source/6470

**Comment by dennisoelkers** [comment]
Official support for OpenSearch has been merged (#11435) and will be part of the next version, so I am closing this for now. Thanks for your participation everybody!
