### ISSUE TITLE
never trigger alarm

### ISSUE THREAD

**Issue by guilongyang** [Graylog2/graylog2-server#10458]
when use one master two slaver ,  I never find a alarm.

## Expected Behavior
I put some message to test alarm, I will get some alarm.

## Current Behavior
no alarms occurred

## Possible Solution
the DBProcessingStatusService.queryWithOutMetrics function always try to find the earliest time to compair, I find that my one slave node's post_indexing time is 1970-01-01T00:00:00 , so that the EventProcessorDependencyCheck.hasMessagesIndexedUpTo function is always return false, so that the processor will not run to search es to find if there have the alarm message

## Steps to Reproduce (for bugs)
1. run one master,two slave cluster
2. only run filebeat to send logs
3. add a event definition
4. put some message to the log file,and let filebeat harvest it

## Context
my suggest is to modify DBProcessingStatusService.queryWithOutMetrics to find max time

## Your Environment

* Graylog Version: 4.1.0
* Java Version: 1.8 
* Elasticsearch Version: 6.5.4

**Comment by bernd** [comment]
@guilongyang If one of your node doesn't receive any traffic, the processing status will stay at the epoch.

One way to fix this is to remove the node that doesn't receive any traffic from the Graylog cluster. This is a known limitation and will be addressed in a future release.
