### ISSUE TITLE
typeahead not working in StreamRulesForm

### ISSUE THREAD

**Issue by vankop** [Graylog2/graylog2-server#10465]
<img width="1440" alt="Снимок экрана 2021-04-19 в 16 49 13" src="https://user-images.githubusercontent.com/10380560/115247160-3898b980-a12f-11eb-9390-47b2aded93ad.png">

## Expected Behavior

`field` in state should match form value. See image above

## Current Behavior

no `onChange` triggered in typeahead component

## Steps to Reproduce (for bugs)

1.  Open `New Stream Rule` form
2. fill form
3. press save
4. getting `field = ''` in `{streamid}/rules` request

## Your Environment

* Graylog Version: 4.0.6
* Java Version: any
* Elasticsearch Version: any
* MongoDB Version: any
* Operating System: any
* Browser version: chrome 89.0.4

**Comment by vitkovskii** [comment]
Hey! Same behavior using v4.0.1

**Comment by vitkovskii** [comment]
@bernd Hi! Any updates on it?

**Comment by bernd** [comment]
@gally47 Thanks for the update!
