### ISSUE TITLE
Support Multiple LDAP Server

### ISSUE THREAD

**Issue by bonzi316** [Graylog2/graylog2-server#1046]
Hi,

I would be nice if we can add more than one LDAP servers.  In case one LDAP server is not responding the interface will still available.

Thanks

**Comment by zolech** [comment]
+1

**Comment by TJM** [comment]
+2?

**Comment by libby2cm** [comment]
+10

**Comment by pszafer** [comment]
+1

**Comment by mvintila** [comment]
Any progress on this?

**Comment by kkplein** [comment]
+1! Strange something vital like this is not yet implemented!
