### ISSUE TITLE
Date Picker does not show accurate summary

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#10463]
When selecting the last 5 weeks, the date picker summary shows it as "a month ago" instead.
![image](https://user-images.githubusercontent.com/41929/115238334-dd120000-a11d-11eb-8d06-cc2f29479cdb.png)

**Comment by kyleknighted** [comment]
Unable to find a solution that doesn't round down to months.
Any thoughts on how to solve this?
https://codepen.io/kyleknighted/pen/c63bc12896d9ce7f28565e07fe868fb6?editors=0012
