### ISSUE TITLE
graylog4.0 ：How do you use dingding alarm

### ISSUE THREAD

**Issue by Soberabsurd** [Graylog2/graylog2-server#10486]
I use type： http notification .The token of Dingding robot was written in the input box, the test was successful, but it was not sent to Dingding

**Comment by bernd** [comment]
@Soberabsurd The HTTP notification currently doesn't support authentication. Please track the status of this improvement here: https://github.com/Graylog2/graylog-plugin-integrations/issues/769 Thank you!
