### ISSUE TITLE
{"type":"unavailable_shards_exception","reason":"[graylog_1][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[graylog_1][0]] containing [26] requests]"}

### ISSUE THREAD

**Issue by zhansang** [Graylog2/graylog2-server#10498]
## Expected Behavior

{"type":"unavailable_shards_exception","reason":"[graylog_1][0] primary shard is not active Timeout: [1m], request: [BulkShardRequest [[graylog_1][0]] containing [26] requests]"}
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
