### ISSUE TITLE
Field Data Types Contain Outdated Types

### ISSUE THREAD

**Issue by ChristopherKB** [Graylog2/graylog2-server#10494]
When using the search page, restricting the time range does not restrict which data types are included. 
## Expected Behavior

If searching over a single index, the data types returned in the search window should include only those data types occurrring within the time range of the search.
## Current Behavior

Data types returned include all data types in index set.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
This issue has been fixed in #10562, which is part of `4.1`.
