### ISSUE TITLE
 2021-04-25 10:40:49,698 WARN : org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Active write index for index set "Default index set" (60853d75fab88c5df892a8fe) doesn't exist yet   2021-04-25 10:40:54,301 ERROR: org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy - Could not find current deflector target of index set <Default index set>. Aborting.   org.graylog2.indexer.NoTargetIndexException: Couldn't get newest index number for indices [graylog_deflector]

### ISSUE THREAD

**Issue by zhansang** [Graylog2/graylog2-server#10499]
## Expected Behavior

2021-04-25 10:40:49,698 WARN : org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Active write index for index set "Default index set" (60853d75fab88c5df892a8fe) doesn't exist yet

2021-04-25 10:40:54,301 ERROR: org.graylog2.indexer.rotation.strategies.AbstractRotationStrategy - Could not find current deflector target of index set <Default index set>. Aborting.

org.graylog2.indexer.NoTargetIndexException: Couldn't get newest index number for indices [graylog_deflector]

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
