### ISSUE TITLE
Graylog Marketplace : Download from Github links are all broken

### ISSUE THREAD

**Issue by H2Cyber** [Graylog2/graylog2-server#10497]
## Steps to Reproduce (for bugs)
1. Visit the [Graylog Marketplace](https://marketplace.graylog.org/) and choose any content pack
2. Click on the red `Donwload from Github` button
3. Observe the error message: `404: not found error`

**Comment by bernd** [comment]
@H2Cyber I am unable to reproduce that for *every* content pack. Uploading a content pack to the marketplace requires that the author is using some conventions as documented [here](https://docs.graylog.org/en/latest/pages/marketplace.html#contributing-content-packs).

For example, the content pack file needs to be in the root of the repository and be named `content_pack.json`. If an author is using a different filename, the download link doesn't work.
