### ISSUE TITLE
Elasticsearch error

### ISSUE THREAD

**Issue by ajieup** [Graylog2/graylog2-server#10504]
## Your Environment

* Graylog Version: Graylog 4.0.6+40b7be5
* Java Version: 1.8.0_265
* Elasticsearch Version: 7.10.2-1
* MongoDB Version: 4.0.24
* Operating System: centos8.3
* Browser version: chrome89.0.4389.114

![image](https://user-images.githubusercontent.com/79831323/116056526-79a14880-a6b0-11eb-9f21-62db3a31de67.png)
Graylog reported an error, how to solve it?

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
