### ISSUE TITLE
Extractor regex fields not appear when simulating pipeline

### ISSUE THREAD

**Issue by Howard0204** [Graylog2/graylog2-server#10524]
## Expected Behavior

I extracted two fields in the input, and **I had changed message filter chain before Pipeline processor.**
I used debug to check the values and it turned null with the following rule

rule “remote session”
when
true
then
let debug_message = concat("user_source: ", to_string($message.user_source));
debug(debug_message);
let debug_message1 = concat("user_been_used: ", to_string($message.user_been_used));
debug(debug_message1);
end

## Current Behavior

I expect to have value in both fields,but it showed null
![image](https://user-images.githubusercontent.com/83268963/116495714-0da02980-a8d6-11eb-80a2-ea9887d97ad1.png)

## Steps to Reproduce (for bugs)

1. the example log:pam_unix(remote:session): session opened for user yyyyy by wwww(uid=0)
2.My regular expression settings and result
![image](https://user-images.githubusercontent.com/83268963/116496013-acc52100-a8d6-11eb-87d0-e080af481cc0.png)
![image](https://user-images.githubusercontent.com/83268963/116496020-b0f13e80-a8d6-11eb-93c9-64af7803f747.png)
![image](https://user-images.githubusercontent.com/83268963/116496053-bd759700-a8d6-11eb-96b1-ef3915a1ec39.png)

## Your Environment

* Graylog Version: Graylog v4.0.3+aef982e
* Java Version:
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.2.12
* Operating System: centos 7
* Browser version: chrome  90.0.4430.93

**Comment by bernd** [comment]
@Howard0204 This is expected behavior. The pipeline simulator only runs the pipeline rules and not the extractors.
