### ISSUE TITLE
Usernames with / not encoded in API calls

### ISSUE THREAD

**Issue by vospa** [Graylog2/graylog2-server#10530]
We have usernames with / in them (I know, bad choice), e.g. we have tom and tom/admin, dick and dick/admin to separate privileged and unprivileged accounts. These are in ldap, and break the role assignment page on Systems/Users and teams/edit.

## Expected Behavior
Role assignment page should load

## Current Behavior
Role assignment page does not load and errors with a 404 because the "/" isn't encoded in the api call.
When replacing the "/" in the APl call with %2F things work as expected.

## Possible Solution
Encode certain characters in usernames that are valid in e.g. LDAP but not in URLs like "/"

## Steps to Reproduce (for bugs)

1. Create a local user with a / in the name, e.g. test/admin
2. Try editing the user and watch role assignment not loading and leading to a 404

## Context

Cannot change the /admin users in the ldap system. 

## Your Environment
* Graylog Version: 4.0.6
* Java Version:  openjdk-11-jdk-headless 11.0.11+9-1~deb10u1
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.2.13
* Operating System: Debian 10.9
* Browser version: Firefox 88

**Comment by kyleknighted** [comment]
For future reference, here is a list I found of valid characters - https://www.ibm.com/docs/en/baw/19.x?topic=security-characters-that-are-valid-user-ids-passwords

**Comment by patrickmann** [comment]
The API call in question is:
`http://localhost:8080/api/authz/roles/user/<user>?page=1&per_page=5`
\<user\> needs to be URL-encoded to escape reserved characters.

**Comment by bernd** [comment]
@vospa Thank you for the report. This has been fixed and will be part of the next 4.0.x release.
