### ISSUE TITLE
ContentPack download  from the list of ContentPacks does not work during dev on localhost

### ISSUE THREAD

**Issue by janheise** [Graylog2/graylog2-server#10548]
## Expected Behavior
When you select "more actions"->"download" next to a ContentPack, you should be able to download the JSON using the "Save link as" option from the context menu on the link in the popup.

## Current Behavior
"Save link as" does not work during development.

## Steps to Reproduce (for bugs)

1. Select "Content Packs" from the "System" Menu
2. Select "more actions" on the right for any Content Pack
3. Select "download"
4. try to follow the download instructions in the Popup

## Context
As a developer, this is needed to check download/installation of ContentPacks

## Your Environment

* Graylog Version: 4.1-Snapshot
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Linux
* Browser version: Chrome, Chromium, FireFox

**Comment by bernd** [comment]
I can reproduce that. This would fix it, not sure if that's the right way, though. :wink: 

```diff
diff --git graylog2-web-interface/src/components/content-packs/ContentPackDownloadControl.jsx graylog2-web-interface/src/components/content-packs/ContentPackDownloadControl.jsx
index 4619780dac..36b05087b8 100644
--- graylog2-web-interface/src/components/content-packs/ContentPackDownloadControl.jsx
+++ graylog2-web-interface/src/components/content-packs/ContentPackDownloadControl.jsx
@@ -42,11 +42,15 @@ class ContentPackDownloadControl extends React.Component {
   _getDownloadUrl() {
     const { contentPackId, revision } = this.props;
 
-    const url = new URI(URLUtils.qualifyUrl(
+    let url = new URI(URLUtils.qualifyUrl(
       ApiRoutes.ContentPacksController.downloadRev(contentPackId, revision).url,
     ));
 
     if (URLUtils.areCredentialsInURLSupported()) {
+      // If we set username and password for a relative URL, we get a broken link. (e.g. "username:password@/api/...")
+      if (url.is('relative')) {
+        url = url.absoluteTo(location.href);
+      }
       url
         .username(SessionStore.getSessionId())
         .password('session');
```
