### ISSUE TITLE
Dashboard: Create Aggregation errors out

### ISSUE THREAD

**Issue by kyleknighted** [Graylog2/graylog2-server#10555]
## Expected Behavior

- Create new Dashboard
- Click Create within left sidebar
- Choose `Generic Aggregation`
- Have widget load with no data

## Current Behavior

After choosing `Generic Aggregation` the Error Page loads with 
```Cannot read property 'first' of undefined```

**Comment by kmerz** [comment]
Unable to reproduce. Probably fixed by now.
