### ISSUE TITLE
Search Aggregation: invalid characters when show the values of a column

### ISSUE THREAD

**Issue by canob** [Graylog2/graylog2-server#10559]
When you create an aggregation search view, if you use a field that is a compound of two field types at ElasticSearch level (for example, in the screenshot the client_source_IP is a compound field ip/string), the values are not showed correctly, you can see garbage characters.

## Expected Behavior
See the list of values for the corresponding field, aggregated

## Current Behavior
If the field is a compound field, you see garbage characters

## Steps to Reproduce (for bugs)
Make an aggregation search using a compound field

## Your Environment

* Graylog Version: 4.0.6-1, Docker
* Java Version: openjdk version "1.8.0_282"
* Elasticsearch Version: opendistro-for-elasticsearch:1.13.2, Docker
* MongoDB Version: mongo:4.4, Docker
* Operating System: Oracle Enterprise Linux 8, but using Dockers
* Browser version: Mozilla Firefox 88 (same behavior in Google Chrome, with diferent garbage characters showed)

## Screenshots
![imagen](https://user-images.githubusercontent.com/30271927/116952227-839eea80-ac60-11eb-817c-f81fd3745348.png)
![imagen](https://user-images.githubusercontent.com/30271927/116952327-c9f44980-ac60-11eb-8aef-d18fae6093f0.png)

**Comment by linuspahl** [comment]
I started having a look this issue. I was not sure if this may be a frontend issue, but it seems to be a backend issue:

![image](https://github.com/Graylog2/graylog2-server/assets/46300478/e56345b8-708b-4d11-b776-ef3669015811)

**Comment by luk-kaminski** [comment]
In most cases I can see that aggregating on the compound field fails immediately.

```
While retrieving data for this widget, the following error(s) occurred:
Elasticsearch exception [type=aggregation_execution_exception, 
reason=Merging/Reducing the aggregations failed when computing the aggregation [agg] because the field you gave in the aggregation query existed as two different types in two different indices].
```

Ip/text combination behaves a little bit different, but I am not sure if it should be treated differently...
I just wander if we should not block aggregating on compound fields in the UI (@linuspahl @dennisoelkers )?

**Comment by luk-kaminski** [comment]
@kroepke - what do you think? Shouldn't we try to block aggregations on complex fields?

**Comment by linuspahl** [comment]
I just saw that the characters are also being displayed in the search query input autocompletion. In my case for field values of a compound field (ip, string)

**Comment by todvora** [comment]
I tried to reproduce that on several version of opensearch and always end up with 

```
While retrieving data for this widget, the following error(s) occurred:
    OpenSearch exception [type=unknown_host_exception, reason=addr is of illegal length].
```

**Comment by williamtrelawny** [comment]
I have a customer (using Elasticsearch 7.10.2) facing this issue with a field storing data as type "ip". It is confirmed not a compound type field across the indices included in the search, but there are other indices not in the search that have this field and its data is of type "keyword." 

Is it possible the ES search query could be hitting other indices than those attached to the specified Streams in the Graylog search?

Another interesting point- if the customer moves the field to a different column in the Search widget, the issue disappears and the proper data is displayed.

Let me know if you want me to make a new BR or add any more data here.

**Comment by ed-graylog** [comment]
hi @dennisoelkers @janheise it appears customer from HS 1798759710 is still experiencing this issue. Do you want us to create a new GH ticket/escalate to dev or do you prefer to re-open this ticket?
