### ISSUE TITLE
Problem with jabber plugin

### ISSUE THREAD

**Issue by bogardan** [Graylog2/graylog2-server#1056]
Hello.
I downloaded graylog2-alarmcallback-jabber-master. I compiled it, and put alarmcallback-jabber-1.1.0-SNAPSHOT.jar in graylog plugin directory.
I rebooted graylog. In log i see this "2015-03-11T15:39:42.618+03:00 INFO  [CmdLineTool] Loaded plugins: [Jabber Alarmcallback Plugin 1.1.0 [org.graylog2.alarmcallbacks.jabber.JabberAlarmCallback]]".
Further in "streams" i done alert with jabber.But, its not working. Port on jabber server is open, and in tcpdump i dont see packets from graylog. 
But in triggered alerts i see "4 minutes ago 	cad2c440-4ca7-4754-964d-cf09b27a0e0a 	Stream had 8 messages in the last 30 minutes with trigger condition more than 0 messages. (Current grace time: 1 minutes)"

**Comment by bogardan** [comment]
Help

**Comment by joschi** [comment]
Closed in favor of Graylog2/graylog2-alarmcallback-jabber#1.
