### ISSUE TITLE
Missing parsing error indicators in pipeline rule editor

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#10571]
## Expected Behavior

The pipeline rule editor is supposed to show parsing rule errors in the editor gutter on the left:

![image](https://user-images.githubusercontent.com/461/117113792-4420ed00-ad8b-11eb-9d72-2a4a8acd26c0.png)

## Current Behavior

In current master the parsing errors are not shown and I can see an error in the browser console:

![image](https://user-images.githubusercontent.com/461/117113642-0de36d80-ad8b-11eb-9881-372b2a8cdf4b.png)

## Steps to Reproduce (for bugs)

1. Create new pipeline
2. Enter invalid pipeline syntax into the editor field
3. Observe missing errors in the editor gutter
4. Check browser console for errors

## Your Environment

* Graylog Version: 4.1.0-SNAPSHOT (rev 6f5d7e45f7)
* Operating System: Ubuntu 20.04 LTS
* Browser version: Chrome 90.0.4430.93

**Comment by ousmaneo** [comment]
Hi @bernd, I tried to reproduce this but it seems to be fixed now. Can you confirm?
I tested on my local and on `smd-dev`

**Comment by bernd** [comment]
@ousmaneo Yep, don't see this issue anymore in 4.2. Thank you!
