### ISSUE TITLE
Lookup Table in Processing Pipeline with `0/1` return does not work

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#10601]
## Expected Behavior
The processing pipeline use in Lookup tables should give the same result in all places. 

## Current Behavior
Having a lookup table result that returns `0` or `1` does work in the extractors or manual lookup, but having this in the processing pipeline does not work. 
In the processing pipeline only the default set in the processing pipeline is used when the return of the lookup is `0`.

The following code will always return `2` if the lookup result is `0`
```
    set_field("serv_mont_state", lookup_value(lookup_table:"maintenance", key:to_string($message.serial), default:"2" ));

```

## Possible Solution
Fix the processing pipeline lookup code to see the return as a string. 

## Steps to Reproduce (for bugs)
1. make a lookup table with return 0 or 1 
2. use this in extractors or the UI to see it working
3. use this with `lookup_value` function in the processing pipeline. 

## Your Environment

* Graylog Version: 4.0.6

**Comment by bernd** [comment]
@jalogisch I am unable to reproduce this with the following rule:

```
rule "zero and one"
when true
then
  let result = lookup_value(lookup_table: "value", key: to_string($message.serial), default: "2");
  
  debug(result);
end
```

The lookup table is backed by a MongoDB data adapter with the following contents:

![image](https://user-images.githubusercontent.com/461/117669046-ca339e00-b1a6-11eb-83db-32661774f0c7.png)

When I send a message that has a field `serial=zero` I get:
```
2021-05-10 15:41:28,895 INFO : org.graylog.plugins.pipelineprocessor.ast.functions.Function - PIPELINE DEBUG: 0
```
When I send a message that has a field `serial=one` I get:
```
2021-05-10 15:41:40,321 INFO : org.graylog.plugins.pipelineprocessor.ast.functions.Function - PIPELINE DEBUG: 1
```

When I send a message that has a field `serial=foo` (or anything else) I get:
```
2021-05-10 15:42:56,199 INFO : org.graylog.plugins.pipelineprocessor.ast.functions.Function - PIPELINE DEBUG: 2
```

Please provide some more information to allow us to debug this further:

1. The settings for the data adapter
2. An example for the data adapter source data

**Comment by jalogisch** [comment]
just to clarify - the same LUT can be used in the exporter to deliver a result, only in the processing pipeline this is not working.

**Comment by jalogisch** [comment]
I found the real reason behind. 

The name for the Lookup Table was `maintenance ` (with the space at the end) what cause the call without the space to be dropped. 

To be clear, this can be seen as user error. But Graylog should take care that characters like `space` or similar can not be used at the end of a LUT Name.

**Comment by bernd** [comment]
@jalogisch Thanks for the feedback. Please open another issue for the input handling of the lookup table names. Thank you!
