### ISSUE TITLE
LDAP authentication is case sensitive in one version of GL and not in another version

### ISSUE THREAD

**Issue by edward-marrufo** [Graylog2/graylog2-server#10607]
## Expected Behavior

Logging in with LDAP authentication should not create new users and just log in existing users without regard for case.
## Current Behavior

Currently in 4.0, for example user s51000 logs in and out, they have a new account created as S51000 when they already have an existing account.
## Possible Solution

Ignore case.
## Steps to Reproduce (for bugs)

1. See HS-388558636 for more details

## Context

Users are in the system twice. Some admin users are not able to login.
## Your Environment

* Graylog Version: 4.0.6
* Java Version: 1.8.0_202-b08
* Elasticsearch Version: 6.8.8
* MongoDB Version: 3.6.19
* Operating System: RedHat 3.10.0-1160.24.1.el7.x86_64

**Comment by bernd** [comment]
This has been answered in HS-388558636.
