### ISSUE TITLE
Session does not time out on nodes overview page

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#10613]
The Nodes overview page makes periodic requests to the cluster API without setting the
X-Graylog-No-Session-Extension header.
This keeps a session open without any user interaction.

**Comment by HenryTheSir** [comment]
Hi @bernd  and @mpfz0r ,

in the current setup with 4.1 Sessions acutally never timeout regardless on which page the user remains. The Enterprise Feature which got introduced in 4.1 regarding setting custimizable user notifications seams to not set the X-Graylog-No-Session-Extension Header as well:

/api/plugins/org.graylog.plugins.customization/notifications


It does not make any difference if theres an active notification or not, sessions will never timeout.

I am not sure if I should open a new ticket (as its an enterprise feature it would be the wrong repo I guess) or if this can be handled here as well.

best regards

GL 4.1.2 with active Enterprise Subscription and Graylog Enterprise Tarball Installationtype. 
Current Firefox ESR

**Comment by bernd** [comment]
A fix for this is part of the upcoming 4.3.2 release.
