### ISSUE TITLE
Cannot get source IP from messages logged via GELF UDP

### ISSUE THREAD

**Issue by NightElfik** [Graylog2/graylog2-server#10634]
## Expected Behavior
Send a log via GELF UDP and have graylog server add some field that has the sender IP.

## Current Behavior
I could not find sender IP, including in `gl2_remote_ip` "hidden" filed mentioned for example in https://github.com/Graylog2/graylog2-server/issues/3980

## Possible Solution
By omitting the mandatory `host` field in the GELF message, I will get the source IP substituted there, but this generates a lot of warnings in logs since my messages are missing a mandatory field.

Spec: https://docs.graylog.org/en/4.0/pages/gelf.html#gelf-payload-specification

Why is it even mandatory if the system works without it? Can I turn off the warnings? One warning per each log received is not ideal...

## Steps to Reproduce (for bugs)
1. Send a message similar to this:
```json
{
"version":"1.1",
"host":"myApp",
"short_message":"Test message",
"timestamp":1620186027.725,
"level":6
}
```
via code similar to this (C#):
```csharp
void SendMessage(string message) {
  var client = new UdpClient("mygraylogserver.com", port: 12201);
  byte[] messageBytes = Encoding.UTF8.GetBytes(message);
  client.Send(messageBytes, messageBytes.Length);
}
```

2. Message is received by graylog server, but I cannot locate the sender IP

This also reproduces in the Web-based simulator

Note: I cannot send the sender IP as a optional field, since I don't know it when sending the message.

## Context
Some details were already discussed here:
https://community.graylog.org/t/can-i-get-source-ip-from-messaged-logged-via-gelf-udp/19733/11

## Your Environment
* Graylog Version: 4.0
* Operating System: Ubuntu 20.04 LTS

**Comment by AntonEbel** [comment]
@NightElfik can you check the [message processor ordering](https://docs.graylog.org/en/4.0/pages/pipelines/stream_connections.html#the-importance-of-message-processor-ordering) if you use the `$message.gl2_remote_ip` in your pipeline rule.
