### ISSUE TITLE
Grok Extractor, Converter Support

### ISSUE THREAD

**Issue by Tinche** [Graylog2/graylog2-server#1064]
Hi,

when parsing metrics out of our logs, using a Grok extractor is really convenient. However, there's currently no way to apply converters to extracted fields?

It'd be very useful to, for example, be able to attach converters to either fields in the extractor or individual Grok patterns (even better!).

**Comment by Tinche** [comment]
Interestingly, I see java-grok recently got converter support: https://github.com/thekrakken/java-grok/commit/e6cbed4b0c75b90a18e4d4a6f287f651bf0b7817

Maybe helpful? Looks unreleased.

**Comment by kroepke** [comment]
We'll integrate support as soon as we can get a released version of java-grok.
Thanks for pointing this out!

**Comment by Tinche** [comment]
Super!

**Comment by madchap** [comment]
Hi,

I've just updated to 1.1.5 from 1.1.4 (docker allinone), but I still do not see a converter field on the grok extractor page for an existing or new grok extractor. Is that normal?

Thanks,
fred

**Comment by kroepke** [comment]
Not sure what you are looking for, but converters work differently for grok
patterns. Please have a look at our docs:
http://docs.graylog.org/en/1.1/pages/extractors.html#using-grok-patterns-to-extract-data

Best,
Kay

**Comment by madchap** [comment]
Thanks, got it! I was expecting a field similar to the one present in regex, my bad.
