### ISSUE TITLE
Remove `Graceful shutdown` from `Nodes` options in Graylog

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#10668]
## Expected Behavior

As a Graylog user, I want to have tight control over both Graylog and the underlying systems that it runs on. I expect, to that end, that all process management is done by the OS's process manager.

## Current Behavior

Currently, a Graylog admin/user can perform a graceful shutdown of Graylog, bypassing things like systemd. This can lead to confusion and issues when the user who performed the shutdown from the UI doesn't have underlying system permissions. 

![CleanShot 2021-05-18 at 08 58 16@2x](https://user-images.githubusercontent.com/898627/118731240-ecf92e80-b806-11eb-87a9-325b41296ee0.png)

**Comment by kroepke** [comment]
Due to be removed in 4.1, this option makes little sense anymore.

**Comment by boosty** [comment]
Deprecate in API, remove from UI

**Comment by thll** [comment]
The backend part is implemented in https://github.com/Graylog2/graylog2-server/pull/10986 but the UI part is still due.

**Comment by boosty** [comment]
Added @dulanism to assignees as this needs a documentation change. 

I found it on https://docs.graylog.org/en/4.1/pages/configuration/load_balancers.html?#graceful-shutdown, but there might be more places.
