### ISSUE TITLE
Index selection for absolute timeframes

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#1066]
It seems like the index selection for absolute timeframes is only accounting the start date of an index but not the end date. It will look at the start date of the timeframe, select the oldest index that can contain data for this timeframe but then go up until the newest index even though it could stop much earlier (at the end of the timeframe)

*Example:*

    from 2015-01-26 00:00:00.000 +00:00 to 2015-01-27 00:00:00.000 +00:00

This will search in indices from `2015-01-26 00:00:00.000` to `NOW` and not stop at `2015-01-27 00:00:00.000`.

**Comment by joschi** [comment]
> It seems like the index selection for absolute timeframes is only accounting the start date of an index but not the end date.

We're currently only calculating the start date of an index but not the end date. Since this is a larger change, I'm moving this to a later milestone.

**Comment by bernd** [comment]
@joschi Is this fixed with the latest index range changes in master?

**Comment by joschi** [comment]
Yes, that's fixed since the index range refactoring in #1274: https://github.com/Graylog2/graylog2-server/blob/4fed53adc043b9801274535ae454dffd3070d5e2/graylog2-server/src/main/java/org/graylog2/indexer/IndexHelper.java#L111-L113
