### ISSUE TITLE
Graylog dashboard not loading due stream and indices errors

### ISSUE THREAD

**Issue by deepakkumardubey** [Graylog2/graylog2-server#10678]
Hi Friends,

Can you please help me to resolve my graylog dashboard error.

Getting below errors in the logs.

ERROR: org.graylog2.security.realm.LdapUserAuthenticator - LDAP error
org.apache.directory.api.ldap.model.exception.LdapAuthenticationException:

org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Cluster not connected yet, delaying index field type initialization until it is reachable

org.graylog2.periodical.IndexRetentionThread - Elasticsearch cluster not available, skipping index retention checks.

org.graylog2.indexer.cluster.Cluster - Couldn’t read cluster health for indices [graylog_, gl-events_, gl-system-events_, abc-accesslogs-full_, is02_1y_*] (Connection reset)

What could be the reason for above errors and what steps we can perform to resolve this issue.

Regards,
Deepak

**Comment by kroepke** [comment]
Hi!
This looks like your Elasticsearch cluster is not reachable, likely on a network level (Connection reset could mean there's a proxy in between).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like it. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
