### ISSUE TITLE
Make GELF message timestamp overridable by local server time.

### ISSUE THREAD

**Issue by konstantintrushin** [Graylog2/graylog2-server#1067]
Please add possibility to override timestamp of messages comming from GELF input similar to syslog UDP input. This is required because of possibility that some missconfigured server will send message with incorrect timestamp and after index range recalculation takes place this message will break search logic.

**Comment by kroepke** [comment]
Possibly allow this for every input.

**Comment by jalogisch** [comment]
you can overwrite the timestamp from a gelf message using a pipeline function.
