### ISSUE TITLE
Allow a GS to be used as a process node only

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#1068]
I have three Graylog Servers on my environment. One of them is located on an isolated DMZ, and is responsible for only receive the messages and index them on ES (as the old Graylog Radio).

This is working nice, the only problem is that sometimes the environment tries to send the authentication request of some user to this server.

As this Server cannot access our LDAP Server, it receives a timeout and the user have to try again the login on another server.

It would be great if I could determine that this node is used only for message processing, and not to process user requests (received by the Web Interface).

Thanks :)

**Comment by henrikjohansen** [comment]
Related to #1004

**Comment by jalogisch** [comment]
as @henrikjohansen said, this would be solved with a solution for #1004
