### ISSUE TITLE
Implement option for search date time picker to apply changes and execute search.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#10707]
## Description

We should implement the option for the date time picker to not only apply the changes, but also directly execute the search. In a previous version we executed the search automatically when the user changed the search controls (query, stream or time range). But we changes this behaviour because it could be difficult to change multiple controls when the search execution takes long.

We should still not automatically execute the search on every search control change, but offer the user the option to directly execute the search after changing the time range. This would be very useful, because in many cases user just want to quickly change the time range of the current search. 

One possible solution could be displaying another button next to the `Cancel` and `Apply` button.

## Your Environment

* Graylog Version: Current development version for 4.1

**Comment by dennisoelkers** [comment]
We decided to implement #10706 instead to help with the number of clicks required to update the timerange.
