### ISSUE TITLE
Improve throughput rate calculation

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#1071]
Currently the throughput metrics are being calculated and made accessible by custom code, which prevents us from efficiently loading them using the API.

Specifically, the web interface should use the bulk metrics call to update its display of various counters and rates.

Migrate the throughput counters (output and streams) to metrics and also add a global input counter for displaying in the UI.

In a second step also migrate radio's usage of the deprecated Throughput methods.

**Comment by bernd** [comment]
@kroepke What's missing here?

**Comment by kroepke** [comment]
It intended to make it more generic, but it is not strictly required. The current implementation is a bit ad hoc.
You can keep it as for future improvement or close it as it is not really a bug. Up to you :smile:

**Comment by bernd** [comment]
Closing it.
