### ISSUE TITLE
Support MongoDB 4.4 so enable support for ubuntu 20.04 (Focal)

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [Graylog2/graylog2-server#10720]
## What?

mongodb only supports ubuntu 20.04 on version 4.4 but graylog does not currently support 4.4

## Why?

Trying to use latest ubuntu os but have to leave mongodb 4.4 running in 4.2 mode

## Your Environment

* Graylog Version: 3.3.13
* Elasticsearch Version: 6.8.16
* MongoDB Version: 4.4
* Operating System: ubuntu 20.04
* Browser version: chrome latest

**Comment by bernd** [comment]
@jgrammen-agilitypr Do you see any specific issues when running with 4.4? We didn't run into any yet, so it should work. Thanks!

**Comment by jgrammen-agilitypr** [comment]
I have not yet enabled the 4.4 mode, as it isn't officially supported in the documentation, and this is a production environment. Once it is officially supported, I will enable the 4.4 mode in mongodb 4.4 and stop running in 4.2 compatibility

**Comment by bernd** [comment]
@jgrammen-agilitypr Thanks for the feedback! We created an issue in our documentation repository and will adjust the documentation. https://github.com/Graylog2/documentation/issues/1150
