### ISSUE TITLE
DEV: Courchevel accommodation Generic error on Page

### ISSUE THREAD

**Issue by jednaka** [Graylog2/graylog2-server#10735]
Generic error occurs on opening Courchevel Accommodation page
https://online3.dev.citybreak.com/954374224/en/en-us/accommodation

## Expected Behavior

No error

## Current Behavior

ERROR.GENERICERRORMESSAGEHEADER
Error.ErrorCode: 59242650

## Steps to Reproduce (for bugs)

1. Navigate to https://online3.dev.citybreak.com/954374224/en/en-us/accommodation

## Your Environment

Google Chrome Version 90.0.4430.212

![CourchevelAccommodationError](https://user-images.githubusercontent.com/84965032/119963746-beb6e400-bfa8-11eb-8b1d-ddf2b3fc2f63.png)

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
This looks like spam or a phishing attempt. The account joined GitHub 25 Minutes ago. I reported the account.
