### ISSUE TITLE
Problem during license import via api

### ISSUE THREAD

**Issue by jzielke84** [Graylog2/graylog2-server#10733]
When I try to import the license key via api, I always get the following error:
```shell
curl \
************:token \
  --header "Content-Type: ap>   -u ************:token \
>   --header "Content-Type: application/json" \
>   --header "X-Requested-By: cli" \
>   -X POST \
>   -d '{"license"="************"}' \
>   https://graylog.host/api/plugins/org.graylog.plugins.license/licenses
{"type":"ApiError","message":"Unable to use invalid license: Unable to read JSON value: �'\u001E��{\"alg\":\"RS512\"}"}
```

I have checked the license string multiple times for encoding, special characters or anything abnormal without success.
Using the rest api browser the import works fine.

**Comment by bernd** [comment]
@jzielke84 The API endpoint expects the plain license string instead of a JSON object: `curl [...] -d '****'`

Does that fix your problem?

**Comment by jzielke84** [comment]
@bernd Thanks, that helped. I never came up with since since the api webinterface states a `license` parameter rather than the plain string. Maybe this can be fixed in the future to avoid further confusions. By the way: Are there any upcoming plans on making ldap group sync settings available on the api endpoints? When querying the authentication object, the api only shows the user sync parameters.

**Comment by bernd** [comment]
@jzielke84 The group/team sync settings are available in separate endpoints:

![image](https://user-images.githubusercontent.com/461/120829234-775ac580-c55d-11eb-9b8c-5882d4c19127.png)
