### ISSUE TITLE
Bulk indexing failing due to JsonParseException

### ISSUE THREAD

**Issue by jpdstan** [Graylog2/graylog2-server#10741]
## Expected Behavior
We expected writes from `graylog2-server` to Elasticsearch Bulk API to work.

## Current Behavior

For a period of time we were receiving errors in our graylog servers of the form:

```
Caught exception during bulk indexing: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('}' (code 125)): was expecting double-quote to start field name
```

## Possible Solution

It seemed to stop after we removed some extractors, but we're unsure as to what the original message was that caused this error (assuming it's an incoming log message that is indeed improperly formatted), and which extractor was causing the issue. This information might be nice to surface in the error logging.

## Your Environment

* Graylog Version: 4.0.6
* Java Version: OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

* Elasticsearch Version: 6.8

**Comment by bernd** [comment]
@jpdstan We need more log context to be able to debug this. Thank you!
