### ISSUE TITLE
Outgoing traffic count in info graphic is third times bigger than the written data in the indices

### ISSUE THREAD

**Issue by xtruthx** [Graylog2/graylog2-server#10750]
## Expected Behavior
Grahip should not show a outgoing traffic third times bigger than there is written data in the index

## Current Behavior
![outgoing_traffic](https://user-images.githubusercontent.com/2736347/120169456-421e4280-c200-11eb-8979-8d782c2a2149.png)

## Possible Solution
-
## Steps to Reproduce (for bugs)
-

## Context
The graphic on the overview is shoing outgoing traffic thrid times bigger than there is data written into the index. Also does the overview in the license/subscription section. Graylog is complaining about violating the License. What is wrong.

## Your Environment

* Graylog Version: 4.x.x latest
* Java Version: openjdk latest
* Elasticsearch Version: Elasticsearch 7.10-oss
* MongoDB Version: 4.2.x
* Operating System: CentOS 7
* Browser version: all Browser

**Comment by bernd** [comment]
@xtruthx You cannot compare the accounted traffic size with the on-disk size of the Elasticsearch indices. The on-disk size is highly dependent on the type of data and what compression Elasticsearch can use for the on-disk representation.

We have documentation on how the traffic is calculated here: https://docs.graylog.org/en/4.0/pages/enterprise/setup/license.html#details-on-licensed-traffic

I hope that helps.
