### ISSUE TITLE
Using the API externally?

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#1075]
Hi,

I want to use our API externally. We have a Squid proxy in front of our graylog nodes, so it is not working by default (says the popup when i browse to the api-browser page). But when i config the rest_transport_uri, my webinterface stops working. What should i do to fix it?

**Comment by dennusb** [comment]
Anyone?

**Comment by dfch** [comment]
@dennusb I presume you have to rewrite the host headers to make this working. I am not sure this is really a bug or an issue with graylog.
We normally configure this via an F5 (but also tested with HAProxy) and have the uri/host header rewritten. Give this a try and it should work.

**Comment by bernd** [comment]
Closing this now, please re-open if you still have issues. Thank you!
