### ISSUE TITLE
Content of aggregation wizard can disappear (Safari only).

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#10756]
## Current Behavior

In Safari the content of the new aggregation wizard can disappear when interacting with it.

![safari](https://user-images.githubusercontent.com/46300478/120212937-ef11b300-c232-11eb-98fb-903c2fa0a873.gif)

## Your Environment

* Graylog Version: current development version for 4.1

**Comment by dennisoelkers** [comment]
Fixed in #10762.
