### ISSUE TITLE
AlertCondition.CheckResult.getMatchingMessages() does not return expected messages

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1080]
Hello,

Init a stream with a rule matching a `facility`, and a alarm with following condition:

> Alert is triggered when the field level has a lower min value than 1 in the last minute. Grace period: 0 minutes. Including last 1 messages in alert notification. 

So, `checkResult.getTriggeredCondition().getParameters()` looks like

```json
{ "grace" : 0 , "field" : "level" , "time" : 1 , "threshold_type" : "lower" , "backlog" : 1 , "type" : "min" , "threshold" : 1.0}
```

Pushing a hundred messages matching the facility with only one `fatal[0]` level raise the alarm condition, but `checkResult.getMatchingMessages()` returns the 10 messages from the stream matching the facility (not necessary the level).

**Comment by mstipanov** [comment]
I'm getting the same email after every grace period .... always the same messages.
Neither level nor stream rules (facility) are matched. :(

**Comment by razvanphp** [comment]
I had exactly this problem today. Included messages are from a different stream than the one the alert is for. If you need more debug information, please ping me.

**Comment by joschi** [comment]
@pdepaepe @razvanphp Did you encounter the same issue with Graylog 1.2.0?

**Comment by bernd** [comment]
Closing this. Please re-open if you still have this problem with Graylog 1.3 or the upcoming 2.0. Thank you!
