### ISSUE TITLE
Pie charts in GL 4.1 beta no longer display value keys

### ISSUE THREAD

**Issue by H2Cyber** [Graylog2/graylog2-server#10837]
I might be missing the obvious, but it seems that the pie charts in `GL 4.1 beta` no longer display value keys (screenshots below).

Here is my widget configuration :

![image](https://user-images.githubusercontent.com/764189/121772046-ec845700-cb6a-11eb-907e-98b23294b284.png)

And here is the resulting chart after clicking on `Apply Changes` (notice how there are no value keys displayed under the chart) : 

![image](https://user-images.githubusercontent.com/764189/121772053-fad27300-cb6a-11eb-9344-dc5be52057e9.png)

## Environment :

* Graylog Version: 4.1 beta 1
* Java Version: 8u292
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.0.24
* Operating System: Ubuntu Server 20.04

**Comment by dennisoelkers** [comment]
Thanks @H2Cyber for reporting this! We will address this before the GA.
