### ISSUE TITLE
`Copy to Clipboard` button on user tokens overview page is missing.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#10833]
## Expected Behavior

Token list on `/system/users/tokens/[user-id]` should display "Copy to Clipboard"  for each token.

## Current Behavior

Currently there is no way do get / display the value of a token, only the name is visible.

## Possible Solution

Reimplement the copy to clipboard button https://github.com/Graylog2/graylog2-server/pull/9732/files#diff-492af3e3d131b63f1097e7db5e9f4fd7763fc84597e99daf5c8ff8642de2124dL54

## Your Environment

* Graylog Version: Graylog 4.1.0-beta.1

**Comment by edmundoa** [comment]
@linuspahl if I understood this correctly, this is expected since https://github.com/Graylog2/graylog2-server/pull/9746. Tokens are now only displayed once during creation and they can't be copied (or seen) anymore for security reasons.

**Comment by linuspahl** [comment]
@edmundoa Alright! Under these circumstances I will close the issue.
