### ISSUE TITLE
Error upgrading to graylog:4.1.0-1.beta.1: hn.a.setWidgetsToSearch is not a function

### ISSUE THREAD

**Issue by sjivan** [Graylog2/graylog2-server#10838]
I just upgraded from 4.0.7 docker container to graylog:4.1.0-1.beta.1. Upon startup when I access the graylog URL I see this error message below on the home page that displays “Something went wrong”. I am an enterprise license user.

hn.a.setWidgetsToSearch is not a function. (In ‘hn.a.setWidgetsToSearch(r)’, ‘hn.a.setWidgetsToSearch’ is undefined)

Stack Trace:

http://x.x.x.x:9000/assets/app.6031e8161a73cf7d64b4.js:2:277266
cs@http://x.x.x.x:9000/assets/vendor.53480e037b0a599cf54a.js:2:300610
Oc@http://x.x.x.x:9000/assets/vendor.53480e037b0a599cf54a.js:2:319505
http://x.x.x.x:9000/assets/vendor.53480e037b0a599cf54a.js:2:771163
sc@http://x.x.x.x:9000/assets/vendor.53480e037b0a599cf54a.js:2:311007
sc@[native code]
http://x.x.x.x:9000/assets/vendor.53480e037b0a599cf54a.js:2:262724
http://x.x.x.x:9000/assets/vendor.53480e037b0a599cf54a.js:2:771163
Qa@http://x.x.x.x:9000/assets/vendor.53480e037b0a599cf54a.js:2:262670
Va@http://x.x.x.x:9000/assets/vendor.53480e037b0a599cf54a.js:2:262605
nc@http://x.x.x.x:9000/assets/vendor.53480e037b0a599cf54a.js:2:307869
yo@http://x.x.x.x:9000/assets/vendor.53480e037b0a599cf54a.js:2:279681
yo@[native code]
http://x.x.x.x:9000/assets/NewSearchPage.6031e8161a73cf7d64b4.js:1:1621
promiseReactionJob@[native code]

Component Stack:

in em
in Unknown
in Unknown
in hm
in mm
in s
in Unknown
in n
in Unknown
in n
in t
in t
in div
in App__PageContent
in i
in tt
in div
in App__AppLayout
in h
in yt
in t
in t
in c
in t
in lt
in Unknown
in ConnectStoresWrapper[Unknown/Anonymous] stores=streams
in Ne
in L
in mt
in At
in Tt
in Pt
in u
in Lt
in Unknown
in n
in Q
in ConnectStoresWrapper[Q] stores=currentUser,server,sessionId
in Ne
in L
in ce
In the startup logs I see this error

graylog_1 | 2021-06-12 04:12:26,666 ERROR: org.graylog2.periodical.Periodicals - Thread periodical-org.graylog2.periodical.ConfigurationManagementPeriodical-0 failed by not catching exception: java.lang.NoSuchMethodError: org.graylog2.migrations.MigrationHelpers.ensureUser(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/Set;)Ljava/lang/String;.

**Comment by sjivan** [comment]
![image](https://user-images.githubusercontent.com/2387369/121775441-b8eb0200-cb55-11eb-810d-c8ff1ecea68e.png)

**Comment by sjivan** [comment]
![image](https://user-images.githubusercontent.com/2387369/121775456-d61fd080-cb55-11eb-9083-643b47803ec6.png)

**Comment by dennisoelkers** [comment]
Hey @sjivan,

thanks for reporting this! Did you do a full page refresh after updating your docker container?

**Comment by sjivan** [comment]
@dennisoelkers yes, I did a full refresh as well as opened the graylog page in an Incognito Browser but the error persists

**Comment by sjivan** [comment]
![image](https://user-images.githubusercontent.com/2387369/121895484-45c8c380-ccee-11eb-8d5b-af7543ac73e1.png)

As you can see from the debugger tooltip, SearchAction has executeWithCurrentState() but is missing the setWidgetsToSerch(..) function.

I tried this is Brave, Safari, Chrome and Vivaldi after full cache cleans

**Comment by sjivan** [comment]
When I examine the webpack in Chrome I see this function in the ts file but it's missing from the compiled JS file

![image](https://user-images.githubusercontent.com/2387369/121898075-018af280-ccf1-11eb-9a12-9762f9ee7421.png)


<img width="727" alt="image" src="https://user-images.githubusercontent.com/2387369/121897903-d30d1780-ccf0-11eb-855f-bb4a6eefeacc.png">

**Comment by dennisoelkers** [comment]
@sjivan: Which plugins (at which versions) do you have installed?

**Comment by sjivan** [comment]
@dennisoelkers 

In my "plugins" folder :
graylog-plugin-enterprise-4.0.1.jar
graylog-plugin-integrations-4.0.1.jar

Where do I download the enterprise plugin jars for the 4.1 beta?

From the Configuration screen : 
![image](https://user-images.githubusercontent.com/2387369/122015174-dbfff680-cd8d-11eb-8676-7760556bf235.png)

**Comment by HenryTheSir** [comment]
They are available here:
https://downloads.graylog.org/releases/graylog-enterprise/graylog-enterprise-4.1.0-beta.1.tgz
https://downloads.graylog.org/releases/graylog-enterprise-integrations/graylog-enterprise-integrations-plugins-4.1.0-beta.1.tgz

best regards

**Comment by sjivan** [comment]
@HenryTheSir @dennisoelkers Is having older versions of these jars a possibility for the error I'm seeing? Attempting to upgrade, and it not not working needs me to rollback the changes is taking up some of my time so it would help to know if this is a possible cause based on the details I provided.

**Comment by HenryTheSir** [comment]
Chances are very high, but as the release says its a beta, and not even an RC release

**Comment by dennisoelkers** [comment]
@sjivan: This is _most_ probably the cause for the error you are seeing.

**Comment by dennisoelkers** [comment]
@sjivan: Could you please give us some feedback if this solved your issue when you have some time? If yes, we could close the issue.

**Comment by sjivan** [comment]
@dennisoelkers @HenryTheSir sorry for the delay. I upgraded to docker image graylog/graylog-enterprise:4.1.0-1 and got rid of my local plugins and bin directory and it's working without errors. Thanks for the assistance. Closing this ticket
