### ISSUE TITLE
Logging-Messages metrics not updated correctly

### ISSUE THREAD

**Issue by janheise** [Graylog2/graylog2-server#10866]
## Expected Behavior
I expected changes in the metrics/numbers when changing the log-level from info to debug.

## Current Behavior
I can see a number of messages running through the console but the metrics stay the same (see screenshot)
![Screenshot from 2021-06-16 11-19-46](https://user-images.githubusercontent.com/1190735/122193719-05577a00-ce95-11eb-911f-f9543834ff66.png)

## Steps to Reproduce (for bugs)

1. Go to "System->Logging"
2. Press button "Show log level metrics"
3. Change the log-level for a subsystem from info to debug
4.

## Your Environment

* Graylog Version: 4.10-beta1
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by kmerz** [comment]
[Open Requirement in TestQuality](https://web.testquality.com/site/graylog/project/14870?requirementId=14690)
- Test [Total written log messages are correct and updated in real-time per node (bug #10866?)](https://web.testquality.com/site/graylog/project/14870/tests?testId=399570&folderId=130281).

**Comment by thll** [comment]
This came up again when testing the 5.0.0-beta-4.

I'm wondering: are the metrics on this page helpful at all?

**Comment by patrickmann** [comment]
@boosty What do we want to do here? Make sure the numbers are accurate? Or do we need to reconsider which metrics to show here?

**Comment by boosty** [comment]
I would suggest to try fixing the current metrics.

**Comment by gally47** [comment]
This came up again when testing the 5.2.0
