### ISSUE TITLE
Data can be fitted in widget without a scrollbar, yet a scrollbar appears

### ISSUE THREAD

**Issue by H2Cyber** [Graylog2/graylog2-server#10895]
## Current Behavior
When resizing a widget, scrollbars sometime appear "too early", ie when there is no need for a scrollbar. Here is an example (notice how the scrollbar is useless in this case, and how a lot of useless whitespace has to be there for the scrollbar to disappear) : 

https://user-images.githubusercontent.com/764189/122635362-5d7fbd80-d0db-11eb-963c-295b7b507d8b.mp4

## Expected Behavior
Only display a scrollbar when the data cannot be fitted in the widget space.

## Your Environment

* Graylog Version: 4.1 rc1
* Java Version: 8u292
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.0.24
* Operating System: Ubuntu Server 20.04

**Comment by linuspahl** [comment]
Thank you for reporting this @H2Cyber.

We fixed this with https://github.com/Graylog2/graylog2-server/pull/10814 and released the change with 4.2.
