### ISSUE TITLE
Missing required parameter `fields

### ISSUE THREAD

**Issue by reggin** [Graylog2/graylog2-server#1089]
I work with graylog REST API. And I have problem with path `/search/universal/absolute` . I want to get `application/json`, but, seems my request go to second GET url `/search/universal/absolute`, where response type is `text/csv`. I've added `'Content-type', 'application/json'` - doesn't help. How I must to say, what I want to get?

**Comment by joschi** [comment]
You have to add a proper `Accept` header, e. g. `Accept: application/json` to your requests.

It is good practice to always add an `Accept` header with the MIME type you want to receive to requests. You will receive a response with status code 406 (Not Acceptable) if the resource doesn't support the requested MIME type.

**Comment by reggin** [comment]
@joschi thank you so much!
