### ISSUE TITLE
REST response pretty printing no longer works

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#10906]
The `?pretty=true` pretty printing instruction for `graylog-server` REST calls does no longer work. It appears to be ignored entirely.

**Comment by bernd** [comment]
Small update: We identified the issue. It seems to be a dependency problem. We are enabling the pretty-printer with `ObjectWriterInjector` from jackson, but jersey is using an embedded version of that... :woozy_face:
