### ISSUE TITLE
Search query box not centered vertically

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#10945]
## Expected Behavior
The query bar should center the query string.

## Current Behavior
The query string is shifted upwards:
![image](https://user-images.githubusercontent.com/52014/123626525-3c247d00-d811-11eb-8dd2-377b3496cbee.png)
Screenshot from Chrome, but Firefox is affected as well.

This seems to affect non-Windows machines as well, but not as dramatically.

## Steps to Reproduce (for bugs)
1. Enter any text into the query bar.

## Your Environment

* Graylog Version: 4.2.0-snapshot, also on 4.0.7-cloud
* Java Version: n/a
* Elasticsearch Version: n/a
* MongoDB Version: n/a
* Operating System: Windows 10 OS Version 2009 (Build 19043.1081)
* Browser version: Chrome 91.0.4472.114 & Firefox 89.0.2

**Comment by linuspahl** [comment]
This has been fixed with https://github.com/Graylog2/graylog2-server/pull/11906. We released this change with 4.3.
