### ISSUE TITLE
Missing permissions on Log View Aggregation

### ISSUE THREAD

**Issue by Helicube** [Graylog2/graylog2-server#10940]
I recently updated the enterprise version of Graylog from 4.0 to 4.1. I tried to use Log View Widget. I created a Dashboard with the Admin account and it work perfectly. But when I try to watch it with a Viewer account, I saw the windows with the scary monkey face wihch said "Missing Permissions". However, I can watch message table perfectly fine with my Administrator Account.
Is there special permissions for Log View Widget or something I missed ?

## Expected Behavior

See the log view correctly, with any authorized user, like I do with message count and table. 

## Current Behavior

**I see the window with the monkey and this message :**
*Missing Permissions*
*You do not have the required permissions to view this resource.*
*Please contact your administrator and provide the error details.*

*The permissions check for the following request failed,*
*while trying to access /dashboards/60b8c8896f23ff79b03a488e.*
*There was an error fetching a resource: Forbidden. Additional information: Not authorized*

**And also this in the red window in the bottom :**
*Could not retrieve license status information*
*Fetching licenses status failed with status: There was an error fetching a resource: Forbidden. Additional information: Not authorized*

## Possible Solution

I have no ideas.

## Steps to Reproduce (for bugs)

1.Log in with a account with administrator permissions.
2.Create a dashbord
3.In the Create section, under Predefined Aggregation, add a Log View widget.
4.Save the dashboard
5.Share it with a viewer permission to account which have no admin role (don't forget to share a stream)
6.Log out and log in with the non-administrator account
7.Acces to the dashboard
8.The message "Missing permissions" appear

You can also try to create an empty dashboard with a non-administrator user and add a Log View widget. The message should show up too.

## Context

I try to create the most readable dashboard for users. To do that, I had to order messages with 2 fields, to avoid message moving due to the same timestamp. Only Log View widget have this feature for now.

## Your Environment

* Graylog Version: 4.1.0
* Java Version: 1.8.0
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.4.6
* Operating System: Ubuntu 20.04

**Comment by Helicube** [comment]
Still the same with 4.1.1 ...

You can easily reproduce this bug by doing this:
1- Log in with the non-administrator account
2- Go to the search tab
3- Click on the down arrow at the top right of the table
4- Click on "Switch to log view"
Then the Missing Permissions window appears 😥

![2021-07-08_09h53_21](https://user-images.githubusercontent.com/58812897/124884496-9cb27780-dfd2-11eb-8278-897aab7ad9db.png)
![2021-07-08_09h53_44](https://user-images.githubusercontent.com/58812897/124884506-9de3a480-dfd2-11eb-8065-d3338e459f9a.png)

**Comment by dennisoelkers** [comment]
Thanks a lot for reporting this, @Helicube! 

We have created a PR to fix this, which will be part of `4.1.2`. Sorry for any inconvenience this has caused!

**Comment by cfrancis2b** [comment]
Me tope con el mismo error,  se presenta cuando cambie el parametro "root_timezone":

root_timezone = UTC

root_timezone = America/Guayaquil

Una vez retornado se fue el error.
