### ISSUE TITLE
Disable inputs auto starting

### ISSUE THREAD

**Issue by edward-marrufo** [Graylog2/graylog2-server#10955]
## What?

As a Graylog user I would like the inputs to not "auto start" all the time. It would be great to either have a "disable auto start for all inputs" setting or a toggle button where you can select individual inputs from auto starting and select "run with last setting" or something similar.

## Why?

Currently when a node reboots the input will automatically start on that node even if I don’t want it to. In some situations, where we have a surge of messages, the journal may be full and the node will change its status to THROTTLED. While in the THROTTLED state a Kubernetes pod running Graylog will begin to fail the health check against the lbstatus api. When this happens Kubernetes will delete the pod and redeploy another which only makes things worse.

**Comment by kroepke** [comment]
HS 457168430

**Comment by boosty** [comment]
@edward-marrufo Is this mainly about preventing stopped inputs from accidentally starting again on a restart? This has been requested several times in the past and sounds very useful. Or is it also important from your point of view to prevent new inputs from auto starting?

In general when building this, we could introduce a configuration option to still allow the current behaviour, for those who rely on it.

**Comment by edward-marrufo** [comment]
@boosty from my perspective it would be more important to prevent stopped inputs from auto starting again or perhaps even include a toggle switch to "remember" the last state they were in on shutdown/restart.

**Comment by boosty** [comment]
> from my perspective it would be more important to prevent stopped inputs from auto starting again

I agree 👍 

> perhaps even include a toggle switch to "remember" the last state they were in on shutdown/restart.

I think preventing stopped inputs from auto starting should become the new default behavior. But a switch to bring back the old behavior could be useful. I am not immediately sure where we should put such a switch though (in the UI, as a server config, or a startup flag). 

Maybe we should start with a server config option to opt in to the old behaviour and only add a more dynamic switch (UI and/or startup flag) when there is demand for it.

**Comment by edward-marrufo** [comment]
Server config option would be great actually since it doesn't require any changes to the UI.

**Comment by aal5snap** [comment]
I would also like to see this feature.  I have the same problem described above (system is crushed by an input it didn't expect to be running on reboot).

My preferred option would be to prevent stopped inputs form auto-starting on reboot.   I suspect most people would want this behavior.  If someone has taken the step of manually stopping an input, why would they assume (or want) it to automatically start when the system restarts?  If they took the responsibility of manually stopping the input, they should take the responsibility to manually start it again.  My guess is auto-starting is an unexpected behavior 98% of the time.  

That said, I would be fine with a UI toggle labeled "auto-start on reboot".  It should be turned off by default.
