### ISSUE TITLE
API Browser broken - No body and `0` return code

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#10952]
## Expected Behavior

When using the API browser, I expect to see calls return an HTTP code and a JSON body.

## Current Behavior

Currently, all calls return a `0` response code and no JSON body:

![CleanShot 2021-06-29 at 12 47 54](https://user-images.githubusercontent.com/898627/123845783-993c3380-d8e2-11eb-8016-c5a34cd138d2.png)

**Comment by dennisoelkers** [comment]
This is an issue related to #10726. It occurs when the global api browser is used via https.
