### ISSUE TITLE
how to use full_message option

### ISSUE THREAD

**Issue by ovadm** [Graylog2/graylog2-server#1096]
I checked the save message option in the input (udp/514) however, full message is not presented  when selecting this option.
what am  I missing something here?

**Comment by joschi** [comment]
Thanks for reporting this! The link to the Graylog website should explicitly use HTTPS, though.

**Comment by bernd** [comment]
I just tested a Syslog input with `store_full_message` enabled and it works fine.

![j9gbmzigqkn6gaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/461/9195305/1ef94b94-4022-11e5-9556-b903f3108d5f.png)

I am closing this issue. Please re-open with some more details if you still have this problem with 1.1. Thank you!
