### ISSUE TITLE
Simple extractors not firing on syslog udp inputs

### ISSUE THREAD

**Issue by braiam** [Graylog2/graylog2-server#10965]
Creating a simple extractor like the example below, doesn't fire when set to any condition (always, if it matches string or on regex). Different extractors have the same result.

```
{
  "extractors": [
    {
      "title": "Testing stuff",
      "extractor_type": "copy_input",
      "converters": [],
      "order": 0,
      "cursor_strategy": "copy",
      "source_field": "message",
      "target_field": "another_message",
      "extractor_config": {},
      "condition_type": "none",
      "condition_value": ""
    }
  ],
  "version": "4.1.0"
}
```

## Expected Behavior
Extractors should fire on messages that match the condition to extract

## Current Behavior
Extractors are basically inert

## Possible Solution
Pipelines still work, but having to set them seems overkill for something like this.

## Steps to Reproduce (for bugs)

1. Create a Syslog UDP input
2. Add a simple Copy input extractor
3. Copy the message field to another field
4. Save and hit the input with some messages

## Context
This is one of the useful characteristics of having log management, that we can organize information into useful bits. Without extractors, we are forced to use pipelines, which are more complex without offering benefits.

## Your Environment

* Graylog Version: 4.1.0+4eb2147
* Java Version: openjdk version "11.0.11" 2021-04-20
* Elasticsearch Version: 
* MongoDB Version:
* Operating System: Debian stable
* Browser version:

**Comment by thll** [comment]
Thanks for the report @braiam.

I followed the steps you documented but I was unable to reproduce the erroneous behaviour. For me, the copy extractor was working as expected.

When you open the extractor details by navigating to `System` -> `Inputs` -> `Manage Extractors` (of your UDP input) -> `Details`, does it show any invocations of the extractor at all? Could you please post the metrics it shows on that page?

**Comment by braiam** [comment]
@thll forgot to include that from the post on the forum. All values are 0. Meanwhile .incoming messages for that input says 

```
Mean:
    21.62 events/second
1 minute avg:
    21.49 events/second
5 minute avg:
    21.25 events/second
15 minute avg:
    21.32 events/second
```

**Comment by thll** [comment]
@braiam that's really strange. I assume you checked the server log for warnings or errors and can also rule out indexing failures? The messages from the input also show up in search, just that the `another_message` field is missing, right?

If I import the extractor JSON you posted, it works out of the box.

Could you check one more thing and post the `Message Processors Configuration` from `System` -> `Configuration`? It should look similar to this:
![image](https://user-images.githubusercontent.com/886541/124782677-b311f200-df44-11eb-8199-0318934e7aef.png)

**Comment by braiam** [comment]
> I assume you checked the server log for warnings or errors and can also rule out indexing failures? 

Yep, nothing, just a depreciation warning. I created a new input and all, never complained.

> The messages from the input also show up in search, just that the another_message field is missing, right?

Exactly. Messages appear with a `message` field, but not `another_message`.

> Could you check one more thing and post the Message Processors Configuration from System -> Configuration? It should look similar to this

![image](https://user-images.githubusercontent.com/1323412/124785109-92ca3f00-df14-11eb-8382-0de0006864cd.png)

**Comment by thll** [comment]
Extractors run in the `Message Filter Chain` processor. If you enable that again, it should work as expected.
Was there a specific reason to disable the `Message Filter Chain`?

**Comment by braiam** [comment]
@thll No idea. I don't remember having touched that. Either way now the extractors are firing according to the logs and the simple field is appearing. Closing this now.

**Comment by braiam** [comment]
Though, that raises the question, why I wasn't aware that extractors had anything to do with the message filter chain? Shouldn't the UI inform me if a functionality is disabled? Maybe an usability bug there?

**Comment by thll** [comment]
I'm glad that this could be resolved.

> Though, that raises the question, why I wasn't aware that extractors had anything to do with the message filter chain? Shouldn't the UI inform me if a functionality is disabled? Maybe an usability bug there?

That information is indeed buried deeply [in the docs](https://docs.graylog.org/en/4.1/pages/pipelines/stream_connections.html#the-importance-of-message-processor-ordering). Still, I think users will rarely disable the `Message Filter Chain` unless there is a good reason.

**Comment by braiam** [comment]
@thll yeah, the fact that isn't mentioned on the page about extractors but about pipelines. I will try to figure out a way to surface the processors configuration that allows different system to work.
