### ISSUE TITLE
Saved Grok Patterns not usable in Pipelines

### ISSUE THREAD

**Issue by romulus-ai** [Graylog2/graylog2-server#11002]
## What?
In Graylog it possible to store Grok Patterns, in the description of this pattern page is written, that they can be used in extrators. However why only there and not also in Pipelines?

I wanted to use to predefined "SYSLOGBASE" pattern in a Pipeline, after 3 days I realized that it is not possible this way.

## Why?
The possiblity to store those pattern it really nice and would reduce the complexity of rules in the pipelines a lot.

## Your Environment

* Graylog Version: 4.1.0
* Elasticsearch Version: 7.10
* MongoDB Version: 4.0
* Operating System: using your docker image
* Browser version: Chrome Version 91.0.4472.114 (Offizieller Build) (x86_64)

**Comment by l00d3r** [comment]
You can use them in pipelines using the grok and set_fields functions: https://docs.graylog.org/en/4.1/pages/pipelines/functions.html#grok
https://docs.graylog.org/en/4.1/pages/pipelines/functions.html#set-fields

Example rule I'm using to apply grok to nginx error logs:

rule "nginx_error_log_grok_extract_fields"
when

  has_field("is_nginx_error_log")

then

  set_fields(
    grok(
      pattern: "%{NGINX_ERRORLOG}",
      value: to_string($message.message),
      only_named_captures: true
    )
  );

end

**Comment by romulus-ai** [comment]
Already tried exactly that:

```
rule "enrich nginx errorlog"
when
    has_field("filebeat_event_dataset") &&
    contains("nginx.error", to_string($message.filebeat_event_dataset), true)
then
    let message_field = to_string($message.message);
    let parsed_fields = grok(pattern: "AB_NGINX_ERRORLOG", value: message_field);
    set_fields(parsed_fields);
    let date = flex_parse_date(value: to_string(parsed_fields.tx_timestamp), timezone: "Europe/Berlin");
    set_field("timestamp", date);
    set_field("original_message", message_field);
end
```

This is the GROK Pattern behind "AB_NGINX_ERRORLOG":

`(?<tx_timestamp>%{YEAR}[./]%{MONTHNUM}[./]%{MONTHDAY} %{TIME}) \[%{LOGLEVEL:severity}\] %{POSINT:pid}#%{NUMBER:threadid}\: %{GREEDYDATA:message}`

In the resulting messages only the "original_message" field appears.

However if I put this pattern directly in the "grok" function, its working. And the pattern also works in the pattern test within graylog.

**Comment by l00d3r** [comment]
I think the line   ` let parsed_fields = grok(pattern: "AB_NGINX_ERRORLOG", value: message_field);`
Should be    ` let parsed_fields = grok(pattern: "%{AB_NGINX_ERRORLOG}", value: message_field);`

**Comment by bernd** [comment]
@romulus-ai Please check if @l00d3r 's answer works for you. It should. :slightly_smiling_face:
