### ISSUE TITLE
Streams ignore floating point numbers when using numeric rules

### ISSUE THREAD

**Issue by mmcguinn** [Graylog2/graylog2-server#1101]
I set up a stream where one of the conditions was that the field 'cost' was greater than 0. I then sent messages that had a cost of 0.1. None of these messages went into the stream. I then tried sending message that had a cost of 1, all of which went into the stream. Finally, I sent messages that had a cost of 1.1, none of which went into the stream.

In summary:

stream rule is cost must be > 0
cost: 0.1 -> not accepted
cost: 1 -> accepted
cost: 1.1 -> not accepted

Are floating point values not accepted here? as far as I can tell float work everywhere else (graphs and statistics).

This is with version 1.0.1

**Comment by kroepke** [comment]
I think, without checking the code right now, that the field is indeed an
integer.

That needs to be corrected since it shouldn't break existing behavior.
Will schedule for 1.1.

**Comment by bernd** [comment]
This has been fixed in #1178.
