### ISSUE TITLE
Syslog TCP input with client authentication not working for CentOS 7 after upgrade to 4.1

### ISSUE THREAD

**Issue by l00d3r** [Graylog2/graylog2-server#11025]
After upgrade to Graylog 4.1(.1) the TLS client authenticated syslog input no longer works as CentOS 7 machines are unable to connect to graylog with rsyslog saying:

unexpected GnuTLS error -28 in nsd_gtls.c:1840: Resource temporarily unavailable, try again.  [v8.24.0-57.el7_9.1 try http://www.rsyslog.com/e/2078 ]

## Expected Behavior

Logs should reach graylog server

## Current Behavior

rsyslog on CentOS 7 shows error: unexpected GnuTLS error -28 in nsd_gtls.c:1840: Resource temporarily unavailable, try again.  [v8.24.0-57.el7_9.1 try http://www.rsyslog.com/e/2078 ] 

## Possible Solution

Allow manual override of ciphers supported by graylog

## Steps to Reproduce (for bugs)

1. Input config:
```
allow_override_date: true
bind_address: 0.0.0.0
expand_structured_data: false
force_rdns: false
max_message_size: 2097152
number_worker_threads: 4
override_source: <empty>
port: 1514
recv_buffer_size: 1048576
store_full_message: false
tcp_keepalive: false
tls_cert_file: /etc/graylog/cert.crt
tls_client_auth: required
tls_client_auth_cert_file: /etc/pki/ca/ca.crt
tls_enable: true
tls_key_file: /etc/graylog/cert.key
tls_key_password:********
use_null_delimiter: false
```

2. rsyslog config (/etc/rsyslog.d/graylog.conf)
```
   $PreserveFQDN on
   $DefaultNetstreamDriver gtls
   # certificate files
   $DefaultNetstreamDriverCAFile /etc/pki/ca-trust/source/anchors/internal-ca.crt
   $DefaultNetstreamDriverCertFile /etc/graylog/cert.crt
   $DefaultNetstreamDriverKeyFile /etc/graylog/cert.key
*.*  action(
   Action.resumeInterval="10"
   RebindInterval="10000"            # cycling TCP connections allows for load balancing
   Queue.Size="100000"
   Queue.DiscardMark="97500"
   Queue.HighWaterMark="80000"
   Queue.Type="LinkedList"
   Queue.FileName="rsyslogqueue"
   Queue.CheckpointInterval="100"
   Queue.MaxDiskSpace="2g"
   Action.ResumeRetryCount="-1"
   Queue.SaveOnShutdown="on"
   Queue.TimeoutEnqueue="10"
   Queue.DiscardSeverity="0"
   type="omfwd"
   target="log.server.test"
   protocol="tcp"
   port="1514"
   template="RSYSLOG_SyslogProtocol23Format"
#   StreamDriver="gtls"
   StreamDriverMode="1" # run driver in TLS-only mode
   StreamDriverAuthMode="x509/name"
   StreamDriverPermittedPeers="log.server.test"
#   gnutlsprioritystring="SECURE192:-VERS-ALL:+VERS-TLS1.2" #Graylog version < 4.1 required this for centos 8 
)

```

## Context

Unable to send syslog to graylog using encrypted and authenticated connection

## Your Environment

* Graylog Version: Graylog 4.1.1+27dec96
* Java Version: java-1.8.0-openjdk-headless-1.8.0.292.b10-1.el8_4.x86_64
* Elasticsearch Version: elasticsearch-oss-6.8.17-1.noarch
* MongoDB Version: mongodb-org-server-4.2.14-1.el8.x86_64
* Operating System: CentOS Linux release 8.4.2105
* Browser version:

**Comment by mpfz0r** [comment]
Try configuring
`enabled_tls_protocols=TLSv1.1,TLSv1.2,TLSv1.3`

See https://github.com/Graylog2/graylog2-server/pull/10985 for details

**Comment by l00d3r** [comment]
That does not help.

I tried with graylog version 4.0.9 and saw that my centos 7 rsyslog (version 8.24.0-57.el7_9.1.x86_64) is using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 so I tried with graylog 4.0.9 and got this working string for rsyslog cipherlist: 
`gnutlsprioritystring="NONE:+VERS-TLS1.2:+ECDHE-RSA:+AES-128-GCM:+SIGN-RSA-SHA256:+AEAD:+COMP-NULL:+CURVE-SECP256R1"`
After reverting back to 4.1.1 this string did not work again but with testssl.sh I see that the same cipherlist should be supported on graylog 4.1.1

I also took a packet trace using both graylog versions, if you'd like to see them I can send them.

I don't fully understand why but I see that rsyslog is closing the connection without specifying why...

This is what  rsyslog to graylog version 4.1.1 initial handshake packet trace looks like
![image](https://user-images.githubusercontent.com/45118187/125795493-dba49042-8bfe-47fb-80c4-60a67d17e953.png)

And this is rsyslog to graylog 4.0.9:
![image](https://user-images.githubusercontent.com/45118187/125795716-dfe4e3cd-d613-4324-9d88-2e7e8a225a22.png)

It kind of looks like graylog 4.1.1 tries to speed things up and rsyslog does not like that

**Comment by mpfz0r** [comment]
@l00d3r okay thanks. I'll try to investigate. In the meantime, does it help if you configure
`transport_netty_tls_provider = jdk` ?

**Comment by l00d3r** [comment]
No, it didn't help :(

**Comment by mpfz0r** [comment]
@l00d3r I couldn't reproduce this using CentOS7 docker with the exact same versions.

Is there an error logged in your graylog server.log?

**Comment by l00d3r** [comment]
Yes, that is logged over and over again for each syslog server I have:

```
2021-07-19T22:12:11.997+03:00 WARN  [AbstractTcpTransport] Client auth configured, but no authorized certificates / certificate authorities configured for input [Syslog TCP/5f7fff0a19add81f5e265024]
2021-07-19T22:12:12.017+03:00 ERROR [AbstractTcpTransport] Error in Input [Syslog TCP/5f7fff0a19add81f5e265024] (channel [id: 0x16366857, L:0.0.0.0/0.0.0.0:1514 ! R:/x.x.x.x:42286]) (cause java.io.IOException: Connection reset by peer)
```

**Comment by mpfz0r** [comment]
So that error indicates that your `tls_client_auth_cert_file` does not exist:

```
tls_client_auth: required
tls_client_auth_cert_file: /etc/pki/ca/ca.crt
```
Could you try to provide a proper cert under `/etc/pki/ca/ca.crt`?

**Comment by l00d3r** [comment]
Actually the file already is over there and that error message was there on the previous version also...

I also tried a centos7 docker image and got the same gtls errors, how did you set the docker images up? I created an centos image with systemd, installed rsyslog and had to start it with dockers `--privileged` option to get any rsyslog errors...

**Comment by mpfz0r** [comment]
> Actually the file already is over there and that error message was there on the previous version also...

But it's likely the cause for the error. 
With 4.1.1 and that file missing I get the following rsyslog error:
`Jul 20 13:52:28 79fe59c5e1da rsyslogd: unexpected GnuTLS error -12 in nsd_gtls.c:1840: A TLS fatal alert has been received.  [v8.24.0-57.el7_9.1 try http://www.rsyslog.com/e/2078 ]`

The code claims it should work without it, but maybe that might have gotten broken with 4.1? :thinking: 
Can you try to provide a valid cert first?

**Comment by l00d3r** [comment]
I have the same CA cert file and same client certificate files for Beats input but Beats input does not give this error :(. The certificate files are all valid and client certs are issued from that CA.

Moreover the input still works with rsyslog on CentOS 8, so I don't think this warning is the issue here...

Also the error code from my rsyslog is not -12 (GNUTLS_E_FATAL_ALERT_RECEIVED) it's -28 (GNUTLS_E_AGAIN).

**Comment by l00d3r** [comment]
The screenshots of the packet capture I posted earlier look as if graylog tries to do a TLS1.3 handshake not TLS1.2, maybe gnutls does not know how to handle that?

**Comment by l00d3r** [comment]
Disregard my previous comment I don't think this is it..

I tested rsyslog with openssl instead of gnutls and it worked so I think it maybe a bug in gnutls librarys handling of encrypted handshake message.

I think the problem right now is that graylog responds to `Client Hello` with a single `Server Hello, Certificate, Server Key Exchange, Encrypted Handshake Message` and I believe the client certificate is asked in the `Encrypted Handshake` message which is the part that rsyslog-gnutls can't handle...  

I wish there would be a way to turn it off from graylogs side as in prior versions graylog responded to `Client Hello` with a `Server Hello, Certificate, Server Key Exchange` and then in a separate packet it sent a `Certificate Request, Server Hello`.

Why I believe it needs to be configurable on graylogs side is because rsyslog-openssl is not available from CentOS repos and I don't think it is a good idea to change some core packages to one that is not tested by OS maintainers.

**Comment by mpfz0r** [comment]
> I have the same CA cert file and same client certificate files for Beats input but Beats input does not give this error :(.
> The certificate files are all valid and client certs are issued from that CA.

Weird, but do these inputs also share the same key?
Is your beats input also running with `tls_client_auth: required`?

However, I'm still not able to reproduce this with Centos7 and rsyslog-gnutls.

Maybe we should ignore rsyslog for now.
Does it work if you use `gnutls-cli` like this?

```
# gnutls-cli --x509cafile=/etc/ca.crt --x509certfile=/etc/client.crt --x509keyfile=/etc/client.key  -p 2514 172.16.1.1   
Processed 1 CA certificate(s).
Processed 1 client X.509 certificates...
Resolving '172.16.1.1'...
Connecting to '172.16.1.1:2514'...
- Certificate type: X.509
- Got a certificate list of 1 certificates.
- Certificate[0] info:
 - subject `CN=beatsinput', issuer `CN=MPF-CA', RSA key 2048 bits, signed using RSA-SHA256, activated `2020-04-23 15:38:34 UTC', expires `2024-04-23 15:38:34 UTC', SHA-1 fingerprint `0f5d694cd2b6552fcc07d5b2aca662a265002f9f'
        Public Key ID:
                3a718f77806bd43c03922e30bc2c96321833a6c9
        Public key's random art:
                +--[ RSA 2048]----+
                |                 |
                | .     .         |
                |+.+   o .        |
                |=*.+ . . =       |
                |BEo . o S *      |
                |oo   . = + +     |
                |      o + o .    |
                |       o . .     |
                |                 |
                +-----------------+

- Status: The certificate is trusted. 
- Successfully sent 1 certificate(s) to server.
- Description: (TLS1.2)-(ECDHE-RSA-SECP256R1)-(AES-128-GCM)
- Session ID: 40:68:0C:BB:CA:CF:C2:21:89:5F:6C:45:4F:59:10:08:3F:FE:09:98:37:02:27:7E:C0:1E:2E:EE:BF:31:BC:92
- Ephemeral EC Diffie-Hellman parameters
 - Using curve: SECP256R1
 - Curve size: 256 bits
- Version: TLS1.2
- Key Exchange: ECDHE-RSA
- Server Signature: RSA-SHA256
- Client Signature: RSA-SHA256
- Cipher: AES-128-GCM
- MAC: AEAD
- Compression: NULL
- Options: safe renegotiation,
- Handshake was completed

- Simple Client Mode:
```

**Comment by l00d3r** [comment]
Yes the Beats input is using the same key and client_auth is required:

```
bind_address: 0.0.0.0
no_beats_prefix: false
number_worker_threads: 4
override_source: <empty>
port: 5044
recv_buffer_size: 1048576
tcp_keepalive: false
tls_cert_file: /etc/graylog/cert.crt
tls_client_auth: required
tls_client_auth_cert_file: /etc/pki/ca/ca.crt
tls_enable: true
tls_key_file: /etc/graylog/cert.key
tls_key_password:********
```

Yes gnutls-cli does work like this.

Can I assist you in getting rsyslog working on CentOS 7 dockerized version?
Can you get logs from your CentOS 7 to graylog at all?

**Comment by mpfz0r** [comment]
> Can I assist you in getting rsyslog working on CentOS 7 dockerized version?
> Can you get logs from your CentOS 7 to graylog at all?
Yes I do.
I basically did the following:

`docker run -i -t --rm centos:7 /bin/bash`

Inside I ran:
`yum install rsyslog`
`yum install rsyslog-gnutls`

I've changed the following in the rsyslog.conf:
```
# Turn off message reception via local log socket;
# local messages are retrieved through imjournal now.
#$OmitLocalLogging on
```
And I've commented out `/etc/rsyslog.d/listen.conf`
```
#$SystemLogSocketName /run/systemd/journal/syslog
```

The `/etc/rsyslog.d/graylog.conf` reads similar to yours:
```
$DefaultNetstreamDriver gtls
$DefaultNetstreamDriverCAFile /etc/ca.crt
$DefaultNetstreamDriverCertFile /etc/client.crt
$DefaultNetstreamDriverKeyFile /etc/client.key

*.* action(
  type="omfwd"
   Action.resumeInterval="10"
   RebindInterval="10000"            # cycling TCP connections allows for load balancing
   Queue.Size="100000"
   Queue.DiscardMark="97500"
   Queue.HighWaterMark="80000"
   Queue.Type="LinkedList"
   Queue.FileName="rsyslogqueue"
   Queue.CheckpointInterval="100"
   Queue.MaxDiskSpace="2g"
   Action.ResumeRetryCount="-1"
   Queue.SaveOnShutdown="on"
   Queue.TimeoutEnqueue="10"
   Queue.DiscardSeverity="0"
   target="172.16.1.1"
   protocol="tcp"
   port="2514"
   template="RSYSLOG_SyslogProtocol23Format"
   StreamDriver="gtls"
   StreamDriverMode="1" # run driver in TLS-only mode
   StreamDriverAuthMode="x509/name"
   StreamDriverPermittedPeers="beatsinput"
)

```

With that I was able to run `logger foobar` and see the messages within graylog.

**Comment by l00d3r** [comment]
rsyslog config looks as it is for me but I believe your graylog input config differs from mine, specifically you don't have `tls_client_auth: required` 
When I changed it to `tls_client_auth: disabled` then rsyslog was able to send logs to my graylog, but this is not what I want, I'd like all client connections to be authorized by their certificate.

**Comment by mpfz0r** [comment]
> rsyslog config looks as it is for me but I believe your graylog input config differs from mine, specifically you don't have `tls_client_auth: required`

Well, I do have `tls_client_auth: required`

> When I changed it to tls_client_auth: disabled then rsyslog was able to send logs to my graylog, but this is not what I want, I'd
> like all client connections to be authorized by their certificate.

Yeah, that changes the behavior related to that error:
`2021-07-19T22:12:11.997+03:00 WARN  [AbstractTcpTransport] Client auth configured, but no authorized certificates / certificate authorities configured for input [Syslog TCP/5f7fff0a19add81f5e265024]`

**Comment by mpfz0r** [comment]
Are you using multiple nodes? maybe one of them doesn't have the certificate file(s)?

**Comment by l00d3r** [comment]
If you set  `tls_client_auth: disabled` then the node no longer does certificate based authentication so that's why the warning goes away. 
This warning has nothing to do with the error I receive as the warning is there even if the connection is actually working when using rsyslog-openssl or previous versions of graylog.

I only have one node

**Comment by l00d3r** [comment]
Sorry I argued and wasted your time, the problem was missing permissions on a path to my ca.crt file.

Maybe it would be possible to add some logging for inputs for when the file can't be read or a hard fail if the file defined by `tls_client_auth_cert_file:` can't be read and `tls_client_auth:` is set to `required`?

Again, I'm sorry for wasting your time, I'm closing the issue.

**Comment by l00d3r** [comment]
Did some more digging and looks like rsyslog-gnutls fails because graylog uses some fallback default cacerts file and since it has quite many CA DNs it could not handle the size of it and failed.

**Comment by mpfz0r** [comment]
> Did some more digging and looks like rsyslog-gnutls fails because graylog uses some fallback default cacerts file and since it has quite many CA DNs it could not handle the size of it and failed.

yeah, that makes sense.
And if it weren't for that bug, it would've failed later trying to verify `$DefaultNetstreamDriverCAFile /etc/pki/ca-trust/source/anchors/internal-ca.crt`

I'm still curious, if there was anything introduced with Graylog 4.1, that caused this change of behavior...
