### ISSUE TITLE
Search created by user for shared stream with output incorrectly states missing dependency when shared

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#11021]
## Current Behavior

When a user creates a search that references a stream shared with the user which has an output attached, the share button for that search when opened by the admin user incorrectly states a missing dependency for the output.

![image](https://user-images.githubusercontent.com/41929/125608791-56d96781-d17f-43d8-846f-303873f41e8b.png)

## Steps to Reproduce (for bugs)

1. Create stream
2. Attach output to stream
3. Share stream with user
4. Log in as User
5. Save search referencing stream
6. Open search as admin
7. Open "Share" dialog

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
@dennisoelkers Which Graylog version are you running? This was supposed to be fixed in https://github.com/Graylog2/graylog2-server/pull/10443 and was released in 4.0.7.

**Comment by mpfz0r** [comment]
@bernd customer says `4.0.9`
