### ISSUE TITLE
Widget name doesn't change when editing the widget name

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#11076]
## Expected Behavior

When editing the widget name, I expect that the widget's title on the dashboard reflects the change. 

## Current Behavior

In the image below, I've edited the widget's name. 

<img width="502" alt="CleanShot 2021-07-27 at 14 46 49" src="https://user-images.githubusercontent.com/898627/127210770-3e799e9a-9d46-4007-959c-84a8ff2a855f.png">

However, after saving the widget, the title doesn't seem to reflect the change. 

<img width="403" alt="CleanShot 2021-07-27 at 14 46 58" src="https://user-images.githubusercontent.com/898627/127210809-ab68da1d-7de2-4cca-a323-5698af7aa517.png">

## Your Environment

* Graylog Version: 4.1.1

**Comment by linuspahl** [comment]
@asachs01 Hey Aaron, it looks like you are just renaming the metric. Metics can have their own name, but it will not be displayed, when using the single number widget. We should probably hide this input, when the visualization type is "single number". Can you please rename the issue if you have no objections?

With a bar chart the name will be displayed in the chart legend:
![image](https://user-images.githubusercontent.com/46300478/128005054-1f00c0c8-d840-4b5b-a182-9e4660290ad3.png)

If you want to rename a widget, you can double click on the title:
![image](https://user-images.githubusercontent.com/46300478/128005152-1223b239-b9a9-4347-a030-d4c2f6e9d3e6.png)
We plan to make this option more obvious in the future.

**Comment by asachs01** [comment]
Ah! Yep--that's on me. I didn't realize that you could edit the title by clicking on it. 🙇
