### ISSUE TITLE
ES floodgate check needs to take non-data nodes into account

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#11074]
## Description

The `IndexerClusterCheckerThread` service checks if all Elasticsearch nodes have enough available disk space based on the low/high/floodgate settings in Elasticsearch.

The current implementation doesn't take ES master-only nodes into account. A cluster of 10 ES nodes might have 7 data-only nodes and 3 coordinator nodes. Usually the non-data nodes only have a fraction of the disk space that the data nodes have.

Since the current disk space check doesn't take the node status into account, Graylog might trigger a low/high/floodgate notification. This is most likely to happen when using absolute values for the limits instead of percentages.

So we need a way to handle the disk space check in ES clusters where not all nodes have the same roles. 

HS-492248755
HS-497898143

## Your Environment

* Graylog Version: 4.1.1

**Comment by boosty** [comment]
YVCC also reported this problem now: HS-497898143
