### ISSUE TITLE
/users api fails to add user without first_name and last_name defined

### ISSUE THREAD

**Issue by juliohm1978** [Graylog2/graylog2-server#11077]
## Expected Behavior
I would expect the `/users` API to create a new user with the following payload

```json
{
  "email": "user@example.com",
  "password": "123",
  "permissions": [
      "users:edit:testuser"
  ],
  "roles": [
      "Reader"
  ],
  "username": "testuser"
}
```

The provided information about it tells me that `first_name` and `last_name` are optional

![image](https://user-images.githubusercontent.com/4145456/127253097-5d053a87-87d0-469c-acef-76c6088766db.png)

... but the API fails with the error:

```json
{
  "type": "ApiError",
  "message": "Cannot construct instance of `org.graylog2.rest.models.users.requests.CreateUserRequest`, problem: Null firstName\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 11, column: 1]"
}
```

## Possible Solution
Adding both `first_name` and `last_name` to the payload is a workaround.

## Your Environment

* Graylog Version: Docker image 4.1.1+27dec96

**Comment by bernd** [comment]
@juliohm1978 This is a bug in the API browser. It marks all fields as optional. The first and lastname fields are actually required.

**Comment by bernd** [comment]
Related issue: https://github.com/Graylog2/graylog2-server/issues/10367
