### ISSUE TITLE
Bottom part of widgets cuts off letters

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#11093]
## Current Behavior

In the example below, all j's p's, etc. are cut off

![CleanShot 2021-07-30 at 15 45 43](https://user-images.githubusercontent.com/898627/127704538-1ce51cfc-c2d0-45c7-a173-895943f5c05d.png)

The widgets should expand or allow for the full letters to be displayed.

**Comment by linuspahl** [comment]
@asachs01 Can we have a look at this problem together? I tried to reproduce it, but when I create a chart with that many elements in the chart legend, I always see a scroll bar (for the legend).
