### ISSUE TITLE
Stream URL is not showing correctly in alert mail

### ISSUE THREAD

**Issue by phlegx** [Graylog2/graylog2-server#1109]
Setting an email alert on a stream does send me an email with the wrong Stream (base) URL Stream, i.e. 

```URL: http://50b9398ad1c8/streams/5524e1bce4b08a3e18bd3c3c/messages?rangetype=absolute&from=2015-04-13T13:08:24.867Z&to=2015-04-13T13:09:24.867Z&q=*```

**Comment by joschi** [comment]
Please check that `transport_email_web_interface_url` is set to the correct URL in your Graylog configuration, see https://github.com/Graylog2/graylog2-server/blob/1.0.1/misc/graylog2.conf#L338-340 for reference.

**Comment by vp-spoiraud** [comment]
I just set transport_email_web_interface_url in my conf.
thx
