### ISSUE TITLE
Add option to GROK import to skip duplicates

### ISSUE THREAD

**Issue by xbb** [Graylog2/graylog2-server#11109]
Importing a GROK pattern file in Grok patterns while selecting "Replace all existing patterns?" removes
all existing patterns.

## Expected Behavior
Selecting "Replace all existing patterns?" should replace only the patterns with the same name.

## Current Behavior
It deletes all the existing patterns and imports the one in the file.

I'm not sure if this is intended..., also not selecting the option it will fail if pattern with the same name exist.

## Steps to Reproduce (for bugs)
1. Have default GROK patterns installed
2. Import a GROK pattern file selecting "Replace all existing patterns"
   ```
   DATA .*?
   ```

## Your Environment

* Graylog Version: 4.1.2
* Java Version: openjdk 1.8.0_292
* Elasticsearch Version: 6.8.18-1
* MongoDB Version: 3.6.23
* Operating System: CentOS 7

**Comment by bernd** [comment]
@xbb We renamed the title and converted the issue to a feature request for an option to ignore existing patterns on import.

**Comment by ihe-nu** [comment]
![image](https://user-images.githubusercontent.com/74296413/154983410-33025d15-e809-45b4-bca4-91491f9e3812.png)
To me, the text "Replace all existing patterns" could be both:

- purge the database from existing Groks and only take those from this new file
- if a grokpattern from this file already exists replace the one in Graylog with the one from the file
Both variants are very different and it is from my point of view not clear for a user what happens.

I agree on @xbb that this is a bug, at least it is highly misleading. If you are looking with the expectancy of the second possibility you will clear your grok-collection (as it just happened to me) and be frustrated.

For the short therm I'd suggest to make the adjust the text to a more specific description to what really happens. Having both options would be a feature request for the long therm.

**Comment by tellistone** [comment]
This impacted a customer under HS-787535168, caused them to accidentally delete all their patterns.

Renaming the text "Replace all existing patterns" to "drop all existing 
patterns before import" would be much clearer.
