### ISSUE TITLE
Add option to disable sharing with everybody or single users

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#11112]
In a Graylog setup with many users and teams, where teams ensure users only get access to data they are allowed to see, the options to share an entity with everybody or with single users are not helpful. Selecting one of those may end up in users getting access to an entity but not other entities it depends on (as described in https://github.com/Graylog2/graylog2-server/issues/9339), and it results in users having long lists of entities they can't access and additional administration complexity.

## What?
Add configuration options to set whether sharing with everyone and sharing with users should be available or not.

## Why?
In some situations sharing with everyone or with single users is not helpful. See HS-507433390.

## Your Environment
* Graylog Version: 4.1.2

**Comment by mburni** [comment]
We have more than 400 users in our Graylogcluster. This will help us very much.

**Comment by boosty** [comment]
This should be backported to 4.1 and 4.2.

**Comment by boosty** [comment]
Assigned @dulanism for documentation (once this is done)

**Comment by dulanism** [comment]
I'll add a mention in the permission management guide. Since this is closed adding details to our tech writing Asana board cc @annie-zempel.
