### ISSUE TITLE
TLS support over the TCP input

### ISSUE THREAD

**Issue by mundrusatish** [Graylog2/graylog2-server#1111]
Greetings,

As per the web interface configured the private kay and the corresponding self signed certificate for the tcp over ssl logs transportation.

Got the below error message 
ERROR: org.graylog2.inputs.transports.TcpTransport - Error creating SSL context. Make sure the certificate and key are in the correct format. cert=X.509 key=PKCS#8

Based on this I have created proper files, still facing the same issue.

Can you please point out the possiable causes of this issue.

Thanks

**Comment by bernd** [comment]
Your private key is probably not in PKCS#8 format. Try the following command to convert your private key into the correct format.

```
$ openssl pkcs8 -topk8 -inform pem -in your-private.key -outform pem -nocrypt -out output-key.pem
```

**Comment by mundrusatish** [comment]
Thanks much. I get the things done.
