### ISSUE TITLE
Default Elasticsearch settings are problematic

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#11135]
# Summary of Issue
It's come to light in recent months through support and community that the default Elasticsearch settings in the config file we ship are problematic (see https://github.com/Graylog2/graylog2-server/blob/master/misc/graylog.conf#L282-L359). The net result of these settings being configured the way that they are is that users and customers end up taking the default without much evaluation as to whether or not those options are indeed the way to go. This leads to clusters often being oversharded, which in turn impacts Graylog's performance and gives users and customers a pretty 💩 experience.

I'd propose that we change the existing default configuration options from:
```
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 4
elasticsearch_replicas = 0
```

To

```
rotation_strategy = time
elasticsearch_max_time_per_index = 1d
elasticsearch_max_number_of_indices = 14
retention_strategy = delete
elasticsearch_shards = 2
elasticsearch_replicas = 0
```

This way, we can more easily communicate that:

1. Graylog is configured by default to keep 2 weeks of your data
2. The default index set, if not configured for anything else, will create 28 shards, which means that Elasticsearch should be configured to have at least 2GB heap

This would mean, though, that we'd need to make sure that we communicate that accepting the defaults when you're ingesting greater than 80GB a day could have performance implications. However, changing the defaults to a strategy that's easier to reason about in terms of data retention, as well as lowering the default amount of shards should help alleviate situations resulting in oversharding.

**Comment by dennisoelkers** [comment]
Hey @asachs01,

thanks for the recommendation. There are actually two things in here:

1.) Changing the default rotation from 20 indices of 20 million messages (both numbers seem arbitrary to me, they are the result of just picking something at some point in history) to 14 indices of 1 day of messages. That change makes perfect sense to me, is easy to communicate and understand.

2.) Reducing the default number of shards from 4 to 2. I have no opinion on this. It possibly reduces the footprint of Graylog's default instand and may work for some users, but may not work for users or degrade their performance. It can be overridden in the index set settings though of course and should not have an impact on existing index sets. How can we make sure that while this might improve performance for new users, this does not make things worse for a larger number of users running fine with a 4 shard default setting?

**Comment by asachs01** [comment]
@dennisoelkers for 2.) the end goal here is to reduce the potential for oversharding. From my vantage point, this change shouldn't have an impact on existing users running with the 4 shard setting. The only impact would occur *if* they decide to overwrite their existing configuration when upgrading Graylog. I'm also making the assumption that folks are exercising enough foresight to back up their existing configuration before deciding to overwrite it.

What I am curious about though, is what would happen if someone had a multi-node cluster and the configuration files don't match (we've seen this before). What would be the impact of having mixed values for shards in the cluster? My guess is that it would really depend on how folks have their clusters configured. If they're behind a reverse proxy, they could ostensibly be routed to a cluster member with 4 shards or 2 shards arbitrarily, which could create some confusion. What would be your thoughts on that?

As for overriding the settings in the index set creation wizard, I'm hoping that folks take the time to evaluate their data and do just that. However, that seems more like an education problem and less of a product problem, no?

**Comment by bernd** [comment]
> What I am curious about though, is what would happen if someone had a multi-node cluster and the configuration files don't match (we've seen this before). What would be the impact of having mixed values for shards in the cluster? My guess is that it would really depend on how folks have their clusters configured. If they're behind a reverse proxy, they could ostensibly be routed to a cluster member with 4 shards or 2 shards arbitrarily, which could create some confusion. What would be your thoughts on that?

@asachs01 The rotation/retention settings in the config file are only used to configure the default index sets on the first server startup. After that the defaults from the UI components are used. So when Graylog nodes have different rotation/retention settings in their configuration file, only the settings of the master node **at first boot** are used. After that it doesn't make a difference.

**Comment by boosty** [comment]
With https://github.com/Graylog2/graylog2-server/pull/13018 we are changing the index set defaults to end up with 30 GB per shard per default (which is right in the middle of the recommended 10-50 GB range).

The following defaults will be used:
- Shards: 1
- Rotation Strategy: Size: 30GB

Refs:
- https://www.elastic.co/guide/en/elasticsearch/reference/7.10/size-your-shards.html#shard-size-recommendation
- https://docs.aws.amazon.com/opensearch-service/latest/developerguide/sizing-domains.html#bp-sharding
