### ISSUE TITLE
Global inputs only start on a single node

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#1116]
When choosing "global" as the target, the inputs actually only start on a single node.

One different to other setups might be that I have two masters configured.

**Comment by kroepke** [comment]
This indeed is a problem when multiple masters are configured in the cluster, the web interface checks whether the server is master (but this check only takes into account if the node is _configured_ as master, not if it actually is master).

This line https://github.com/Graylog2/graylog2-server/blob/master/graylog2-rest-client/src/main/java/org/graylog2/restclient/models/InputService.java#L209-209 contains the check.

I think until we refactor the cluster-wide event handling for inputs we can safely live with this issue.

**Comment by bernd** [comment]
The input handling changed for 2.0 and this is no longer an issue.
