### ISSUE TITLE
Event Definition with Aggregation does not work any longer after updating

### ISSUE THREAD

**Issue by elmarsievers** [Graylog2/graylog2-server#11193]
## Expected Behavior
Aggregation definition should just work.

## Current Behavior
If I select Aggregation of results reaches a threshold in event definition and use count > 0 there is not coming any notification and the error ERROR [PivotAggregationSearch] Aggregation search query <streams-query-1> returned an error: Elasticsearch exception [type=illegal_argument_exception, reason=maxSize must be >= 0 and < 2147483631; got: 2147483647].
is written in server.log.

## Possible Solution
Configuration recommondation or hotfix?

## Steps to Reproduce (for bugs)
If I use any aggregation definition like that above it does not work anymore.

## Context
After updating the system.

## Your Environment
* Graylog Version: 4.1.3-1
* Java Version: 1.8.0.302.b08-0.el7_9
* Elasticsearch Version: 7.14.0-1
* MongoDB Version: 4.4.8-1.el7
* Operating System: CentOS 7.9.2009
* Browser version: Edge Chromium current

**Comment by HenryTheSir** [comment]
Hi,
just for the record, ES Version 7.14 is not supported right now.
https://docs.graylog.org/en/4.1/pages/configuration/elasticsearch.html#elasticsearch-versions

**Comment by elmarsievers** [comment]
HI HenryTheSir,

oh thats hard. ES version 7.14 was coming with the already installed stream.

So can't rollback right now and have to wait for a fix from graylog.

Kind Regards
Elmar
