### ISSUE TITLE
Investigate solution to ClusterBlockException on ES reconnect

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#1120]
```
[99]: index [graylog2_4], type [message], id [94e566e0-e4f5-11e4-9f00-629a1beea700], message [ClusterBlockException[blocked by: [FORBIDDEN/8/index write (api)];]]
2015-04-17 13:33:35,990 ERROR: org.graylog2.indexer.messages.Messages - Failed to index [100] messages. Please check the index error log in your web interface for the reason. Error: failure in bulk execution:
```

probably only needs checking for present blocks in es monitor plugin

**Comment by vp-spoiraud** [comment]
thank you

**Comment by kroepke** [comment]
This is a problem with a restarting ES node, where shard recovery isn't complete, but we already try to check the deflector state.

**Comment by bernd** [comment]
Moving to 1.2.0 milestone. There will be some work on the deflector and index rentention/range stuff.

**Comment by bernd** [comment]
@joschi Is this fixed since the server can start without ES now?

**Comment by joschi** [comment]
@bernd Not that I'm aware of since it's not really related, in my opinion. It might have been fixed by our efforts to make index rotation more robust, though.

Unfortunately we can't say for sure, since this issue is lacking some information, like whether there had been some errors regarding deflector cycling or if writes were deliberately blocked in the `graylog2_4` index.

**Comment by kroepke** [comment]
I believe this happened when the deflector cycled, but a an in-progress bulk index request targeted the previous target index. AFAIK the alias is resolved before the actual indexing, but since we set the index to read only, the request will fail.

Read only indices are implemented as "cluster level blocks" by Elasticsearch, so we could in theory work around this. I'm not sure this has anything to do with being able to start without a Elasticsearch connection.

**Comment by bernd** [comment]
Starting with Graylog 2.3, we are using the HTTP transport for indexing into Elasticsearch. Errors like this will trigger a failed bulk request now and the retry logic kicks in. Until we have a better retry/re-queue system for outputs, this is the best we can do. Closing this issue now.
