### ISSUE TITLE
Bar chart graph shows total value when it shouldn't

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#11201]
## Expected Behavior

When dashboarding values in Graylog, I expect to see the unique values in a bar chart using an overlay style, not that I would see the total count of the value in addition to the unique values.

## Current Behavior

Presently, I see the total value + the unique values, which makes reading the chart less than ideal:

![CleanShot 2021-08-24 at 13 44 52](https://user-images.githubusercontent.com/898627/130665649-4a19c971-858f-427d-952b-99f876fe2b51.png)

## Possible Solution
Not quite sure what the implementation would look like, but having the dash show just the unique values would be stellar.

## Your Environment

* Graylog Version: 4.1.3
* Java Version: 1.8
* Elasticsearch Version: 7.10
* MongoDB Version: 4.2
* Operating System: Ubuntu 20.04
* Browser version: https://www.whatsmybrowser.org/b/OL01S

**Comment by HenryTheSir** [comment]
Hi @asachs01,
under group by disable the 'Rollup Columns' Checkbox. 
best regards

**Comment by asachs01** [comment]
🤦 Thanks for pointing that out @HenryTheSir .
