### ISSUE TITLE
 Required parameter retention_strategy not found

### ISSUE THREAD

**Issue by sarojdongol** [Graylog2/graylog2-server#1121]
Getting This error. How could i solve it 
```
2015-04-18 22:26:56,267 WARN : com.github.joschi.jadconfig.JadConfig - Required parameter retention_strategy not found
Exception in thread "main" com.github.joschi.jadconfig.ParameterException: Required parameter "retention_strategy" not found.
        at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:99)
        at com.github.joschi.jadconfig.JadConfig.process(JadConfig.java:80)
        at org.graylog2.Main.main(Main.java:106)
```

**Comment by joschi** [comment]
Please check that there is a setting named `retention_strategy` with a valid value in your Graylog configuration, see https://github.com/Graylog2/graylog2-server/blob/1.0.1/misc/graylog2.conf#L128-132 for reference.

**Comment by vp-spoiraud** [comment]
My conf
# Decide what happens with the oldest indices when the maximum number of indices is reached.
# The following strategies are availble:
#   - delete # Deletes the index completely (Default)
#   - close # Closes the index and hides it from the system. Can be re-opened later.
retention_strategy = close

**Comment by joschi** [comment]
This looks valid. Please check that this setting is indeed in the correct configuration file and that Graylog is allowed to read it. Also check that there are no additional characters trailing this line, e. g. strange whitespace characters. You can check this with `cat -v path/to/graylog.conf`.

Which version of Graylog are you using and how did you install it (e. g. manual installation, OS packages, OVA images, Docker image…)?

**Comment by vp-spoiraud** [comment]
I check my file /etc/graylog2.conf. There are no additional characters.
I have a manual install  graylog2 v0.20.5 (Oracle Corporation 1.7.0_21)

**Comment by joschi** [comment]
@sarojdongol While you are running a rather old version of Graylog2 and you should upgrade to Graylog 1.0.1, this still should work.

Could you please upload your `graylog2.conf` file somewhere? You can and should remove passwords and sensitive data before, but leave it pristine otherwise.

**Comment by vp-spoiraud** [comment]
# If you are running more than one instances of graylog2-server you have to select one of these
# instances as master. The master will perform some periodical tasks that non-masters won't perform.
is_master = true

# The auto-generated node ID will be stored in this file and read after restarts. It is a good idea
# to use an absolute file path here if you are starting graylog2-server from init scripts or similar.
node_id_file = /etc/graylog2-server-node-id

# You MUST set a secret to secure/pepper the stored user passwords here. Use at least 64 characters.
# Generate one by using for example: pwgen -s 96

password_secret =xxxxxx

# the default root user is named 'admin'
# root_username = admin
# You MUST specify a hash password for the root user (which you only need to initially set up the
# system and in case you lose connectivity to your authentication backend)
# Create one by using for example: echo -n yourpassword | shasum -a 256
# and put the resulting hash value into the following line
root_password_sha2 =xxxxxxxxxx

# Set plugin directory here (relative or absolute)
plugin_dir = plugin

# REST API listen URI. Must be reachable by other graylog2-server nodes if you run a cluster.
rest_listen_uri = http://127.0.0.1:12900/
# REST API transport address. Defaults to first non-loopback IPv4 system address and port 12900.
# This will be promoted in the cluster discovery APIs and other nodes may try to connect on this
# address. (see rest_listen_uri)
#rest_transport_uri = http://192.168.1.1:12900/

# Embedded elasticsearch configuration file
# pay attention to the working directory of the server, maybe use an absolute path here
elasticsearch_config_file = /etc/graylog2-elasticsearch.yml

elasticsearch_max_docs_per_index = 10000000

# How many indices do you want to keep?
# elasticsearch_max_number_of_indices*elasticsearch_max_docs_per_index=total number of messages in your setup
elasticsearch_max_number_of_indices = 5

# Decide what happens with the oldest indices when the maximum number of indices is reached.
# The following strategies are availble:
#   - delete # Deletes the index completely (Default)
#   - close # Closes the index and hides it from the system. Can be re-opened later.
retention_strategy = close

# How many ElasticSearch shards and replicas should be used per index? Note that this only applies to newly created indices.
elasticsearch_shards = 5
elasticsearch_replicas = 0

elasticsearch_index_prefix = graylog2

# Do you want to allow searches with leading wildcards? This can be extremely resource hungry and should only
# be enabled with care. See also: http://support.torch.sh/help/kb/graylog2-web-interface/the-search-bar-explained
allow_leading_wildcard_searches = false

# settings to be passed to elasticsearch's client (overriding those in the provided elasticsearch_config_file)
# all these
# this must be the same as for your elasticsearch cluster
elasticsearch_cluster_name = es-xxxxxx

# you could also leave this out, but makes it easier to identify the graylog2 client instance
elasticsearch_node_name = xxxxxxx

# we don't want the graylog2 server to store any data, or be master node
#elasticsearch_node_master = false
#elasticsearch_node_data = false

# use a different port if you run multiple elasticsearch nodes on one machine
#elasticsearch_transport_tcp_port = 9350
# we don't need to run the embedded HTTP server here
#elasticsearch_http_enabled = false

#elasticsearch_discovery_zen_ping_multicast_enabled = false
#elasticsearch_discovery_zen_ping_unicast_hosts = xxxxxxxxx:9300


# Analyzer (tokenizer) to use for message and full_message field. The "standard" filter usually is a good idea.
# All supported analyzers are: standard, simple, whitespace, stop, keyword, pattern, language, snowball, custom
# ElasticSearch documentation: http://www.elasticsearch.org/guide/reference/index-modules/analysis/
# Note that this setting only takes effect on newly created indices.
elasticsearch_analyzer = standard

# Batch size for all outputs. This is the maximum (!) number of messages an output module will get at once.
# For example, if this is set to 5000 (default), the ElasticSearch Output will not index more than 5000 messages
# at once. After that index operation is performed, the next batch will be indexed. If there is only 1 message
# waiting, it will only index that single message. It is important to raise this parameter if you send in so
# many messages that it is not enough to index 5000 messages at once. (Only at *really* high message rates)
output_batch_size = 5000

# The number of parallel running processors.
# Raise this number if your buffers are filling up.
processbuffer_processors = 5
outputbuffer_processors = 5

# Wait strategy describing how buffer processors wait on a cursor sequence. (default: sleeping)
# Possible types:
#  - yielding
#     Compromise between performance and CPU usage.
#  - sleeping
#     Compromise between performance and CPU usage. Latency spikes can occur after quiet periods.
#  - blocking
#     High throughput, low latency, higher CPU usage.
#  - busy_spinning
#     Avoids syscalls which could introduce latency jitter. Best when threads can be bound to specific CPU cores.
# processor_wait_strategy = blocking
processor_wait_strategy = sleeping


# Size of internal ring buffers. Raise this if raising outputbuffer_processors does not help anymore.
# For optimum performance your LogMessage objects in the ring buffer should fit in your CPU L3 cache.
# Start server with --statistics flag to see buffer utilization.
# Must be a power of 2. (512, 1024, 2048, ...)
ring_size = 1024

# MongoDB Configuration
mongodb_useauth = true
mongodb_user = xxxxxx-user 
mongodb_password = xxxxxxxxx
mongodb_host = xxxxxxx
#mongodb_replica_set = localhost:27017,localhost:27018,localhost:27019
mongodb_database = xxxxxxx 
mongodb_port = xxxxx

# Raise this according to the maximum connections your MongoDB server can handle if you encounter MongoDB connection problems.
mongodb_max_connections = 100

# Number of threads allowed to be blocked by MongoDB connections multiplier. Default: 5
# If mongodb_max_connections is 100, and mongodb_threads_allowed_to_block_multiplier is 5, then 500 threads can block. More than that and an exception will be thrown.
# http://api.mongodb.org/java/current/com/mongodb/MongoOptions.html#threadsAllowedToBlockForConnectionMultiplier
mongodb_threads_allowed_to_block_multiplier = 5

# Drools Rule File (Use to rewrite incoming log messages)
# See: http://support.torch.sh/help/kb/graylog2-server/custom-message-rewritingprocessing
# rules_file = /etc/graylog2.drl

# Email transport
transport_email_enabled = true
transport_email_hostname = xxxxxxxxx
transport_email_port = 25
transport_email_use_auth = false
transport_email_use_tls = false
transport_email_use_ssl = false
transport_email_auth_username = you@example.com
transport_email_auth_password = xxxx
transport_email_subject_prefix = [pp-xxxxxx]
transport_email_from_email = noreply@xxxxx.com

# Specify and uncomment this if you want to include links to the stream in your stream alert mails.
# This should define the fully qualified base url to your web interface exactly the same way as it is accessed by your users.
#

transport_email_web_interface_url = http://xxxxxxxxxxxxx

**Comment by joschi** [comment]
Please upload the file somewhere and post a link to it. Don't just copy and paste the contents (and leave out important information in the process).

**Comment by joschi** [comment]
@sarojdongol I'm closing this issue now. Please add a comment if the problem persists.
