### ISSUE TITLE
Simplify Search API to make it usable with minimal request

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#11234]
Ideally we want users to have an easy time operating our API for scripting purposes.

Right now the search API (`/api/views/search/sync`) requires a rather big request to generate a response. Validation and error handling is not ideal supporting a user trying to write a request from scratch.

Ideally we should:

  - try to write a search request from scratch (starting with an empty body)
  - identify missing validations/assertions
  - implement handling of parameters which can be optional so they can be left out

**Comment by todvora** [comment]
If we remove the need to provide UUIDs for different parts of the requests, we can go as simple as 

```
{
   "queries":[
      {
         "query":{
            "type":"elasticsearch",
            "query_string":""
         },
         "timerange":{
            "type":"relative",
            "from":300
         },
         "search_types":[
            {
               "type":"messages"
            }
         ]
      }
   ]
}
```

without any additional assumptions or rewrites, in order to get latest messages. Seems like a good start.

**Comment by bernd** [comment]
@dennisoelkers @todvora Have you considered creating separate endpoints for simpler searches? For example having search type specific endpoints that take query parameters for configuration.

**Comment by kroepke** [comment]
We also have to consider API compatibility. Even though we haven't promised stability, I know that some users depend on running queries this way and we should be careful not to break their usage if possible.

**Comment by todvora** [comment]
@bernd @kroepke This change is fully backwards-compatible. It just removes the unnecessary complexity if you want to start with the API. But it won't prevent you to use the full request, with all IDs, all time-ranges and full-blown queries.
