### ISSUE TITLE
Report Scheduling with addition frequency option, i.e., "Hourly." 

### ISSUE THREAD

**Issue by makstock** [Graylog2/graylog2-server#11240]
## What?

Some users may have a requirement that they want to send reports on an hourly basis. Also, we can add "Daily frequency options" with "every hour" default check box or "Select time (If they want to send every two, three, four ... hours)."

![image](https://user-images.githubusercontent.com/62546449/131998225-c5a0a3b2-248d-4903-a3ec-b3777b3e37bd.png)

## Why?

This feature might give users the flexibility to send reports on an hourly basis if they want to monitor any specific assets or devices.

## Your Environment

HS-541081939

* Graylog Version: 4.0.8 
* Elasticsearch Version: NA
* MongoDB Version: NA
* Operating System: NA
* Browser version: NA

**Comment by dennisoelkers** [comment]
This is a duplicate. Closing this in favor of #8591.
