### ISSUE TITLE
Can't set facility as string with pipeline rule

### ISSUE THREAD

**Issue by pepperoni-pi** [Graylog2/graylog2-server#11259]
## Expected Behavior

Using a Raw/Plaintext UDP input, I am trying to set the "facility" field with a pipeline rule to its string value such as local0, local7, etc.

## Current Behavior

Currently, the "facility" field is only accepting integer values. When I set it as a string like local0, local7, etc, the messages stop appearing in the stream. I was unable to set it with a pipeline rule using the "set_field" command, renaming another field to "facility" with the "rename_field" command, or with an extractor.

## Possible Solution

Allow the facility field to be set as a string with a pipeline/extractor.

## Steps to Reproduce (for bugs)

1. Raw/Plaintext UDP input.
2. Create pipeline and attach to stream.
3. Create rule to set "facility" as string with the "expand_syslog_priority_as_string" command. (i.e. local0, local7, etc)

```
rule "priority parsing"
when
  true
then
  set_fields(grok(pattern: "<%{NONNEGINT:facility_num:int}>", value: to_string($message.message), only_named_captures: true)); 
  let priority_integer = expand_syslog_priority(to_long($message.facility_num));
  let priority_string = expand_syslog_priority_as_string(to_long($message.facility_num));
  set_fields({facility_num: priority_integer.facility, level: priority_integer.level, facility: priority_string.facility});
end
```
4. Stream will no longer display messages.

## Context

This value is used by LibreNMS when integrating through the Graylog API. Graylog Community converstion [here](https://community.graylog.org/t/pipeline-rule-to-set-facility-and-log-level-categories/21100).

## Your Environment

Graylog Version: 4.1.3+9d79c05
Java Version: 1.8.0_292
MongoDB Version: v4.0.26
Elasticsearch Version: 7.10.2
Operating System: Ubuntu 20.04

**Comment by bernd** [comment]
@pepperoni-pi Looking at the community conversation, it looks like your issue is solved?

**Comment by pepperoni-pi** [comment]
@bernd I think we can close this one. In the end, it was more of an issue about me learning how Graylog works than it was an issue with the application. Graylog community conversation can be found [here](https://community.graylog.org/t/pipeline-rule-to-set-facility-and-log-level-categories/21100).
