### ISSUE TITLE
JSON body in HTTP alarm callback is too verbose

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#1127]
The http alarm callback is just serializing the stream object and check result objects to be included in the callback's body. This includes information which is unneccessary and potentially harmful, like the complete information about the stream's outputs. It is also pretty much unstructured and there is no concise information about its structure available for potential consumers.

A potential fix might include beside stripping away unneeded information the definition of a DTO that is consumable in other applications, so it should be part of the plugin interface module.

**Comment by bernd** [comment]
This will be fixed in the upcoming 3.1 release.
