### ISSUE TITLE
Redirect to Loginpage

### ISSUE THREAD

**Issue by rakinzon** [Graylog2/graylog2-server#1129]
After some clicks in the Webinterface I get redirected to the loginpage with the message: Sorry, those credentials are invalid. 
After a server reboot, i can login successfully and after some clicks in the interface I get again redirected.
I use graylog-web-interface-1.0.1 and graylog-1.0.1

**Comment by kroepke** [comment]
This usually happens when the server is completely overloaded. The cookie auth times out. Please check if you server hardware and settings are sufficient.
