### ISSUE TITLE
Enforce message size limit

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#1131]
Right now you can crash graylog server if you write a very big (100+ MB) to graylog. This is a security problem, an attacker could overwhelm graylog and stop any further logging of his activites. Futhermore misconfigured logstash agents (with a wrong multiline filter) can easily write very long message too.

A server / input wide limit to enforce the message size would help here.

**Comment by jalogisch** [comment]
closing in favour of #2948
