### ISSUE TITLE
How can I remove default message field when use json extractor extract all sub-field

### ISSUE THREAD

**Issue by missyoyo** [Graylog2/graylog2-server#11310]
## What?
My log is pure json log,When I extract all sub-field in message,message field is no need any more. So how can I remove it form elasticsearch and not show in graylog when search?
## Why?
Do not need message field and save disk useage.

## Your Environment

* Graylog Version:Graylog v4.1.5+01c9198
* Elasticsearch Version:7.10.1
* MongoDB Version:v4.0.27
* Operating System:Ubuntu 20.04
* Browser version:Firefox 92.0

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
