### ISSUE TITLE
Investigate inverted stream rules for field presence (field message)

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#1133]
During development I've seen messages being routed into a stream with the single rule "field message must not be present", even though the field was present.

Might be a display bug or a bug in the stream router.

**Comment by dennisoelkers** [comment]
I tried to reproduce this and failed. Is there a way that you know of how to reproduce this? Is there any hard evidence/sample data set/reproducible way that this is really bug?

**Comment by kroepke** [comment]
No, I just remember seeing this happen at some point and didn't want to
ignore it outright.
If you cannot reproduce it, then I'd say let's close it and not spend too
much time :)

Thanks for looking into it!
