### ISSUE TITLE
Lookup Table Data Adapter - Add URL Whitelist

### ISSUE THREAD

**Issue by kyleknighted** [Graylog2/graylog2-server#11345]
## Expected Behavior

To be displayed the entire list of Whitelisted URLs

## Current Behavior

Potential race condition, on occasion while trying to add a URL to the Whitelist from the Data Adapter page, you will get a modal with no other URLs in it, just the new one you're adding now

![image](https://user-images.githubusercontent.com/122591/134684277-7e7ec8d5-b60d-48d6-925b-a765e4adf747.png)

![image](https://user-images.githubusercontent.com/122591/134683895-40b62189-ebbe-4466-bd8f-d203f4b5196d.png)
![image](https://user-images.githubusercontent.com/122591/134684239-54a6bb4d-0858-4867-ac1b-c640b1b14f17.png)

**Comment by edmundoa** [comment]
It seems that the internal component state is resetting while editing the URL in the form input. That part of the code changed in https://github.com/Graylog2/graylog2-server/pull/9171 but this may have been broken before that.
