### ISSUE TITLE
Graylog startup behaviour

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1136]
Currently when a server node starts and finds issues with the Elasticsearch cluster it refuses to complete the startup process - with the introduction of the journaling subsystem in 1.0 I find this behaviour a bit problematic since it could mean loosing messages.

I would like to suggest that server nodes **always** start regardless of the ES cluster status (and thus can buffer messages in it's journal) - the web interface could then inform the user that ES has a problem that needs investigating to avoid confusion.

**Comment by runningman84** [comment]
+1

**Comment by pkoraca** [comment]
+1

**Comment by gstimac** [comment]
+1

**Comment by packs** [comment]
```c
++$votes;
```
