### ISSUE TITLE
Add configurable global user timeout configuration setting

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#11379]
## What?

Currently, the session timeout is configurable for each user on the Users > Edit page in the Sessions Timeout field. 

![image](https://user-images.githubusercontent.com/3423655/135312610-441cdd2b-f7ae-484d-aaca-7c40d7f7ba54.png)

A customer is requesting the ability to edit the timeout globally for all users at once.

## Why?

A configurable global timeout would prevent the work required to edit and maintain the session timeout for individual users.

Ticket reference: HS-579202485

**Comment by danotorrey** [comment]
Perhaps we could consider adding a `server.conf` property to control the global timeout currently specified in a code constant here: 
https://github.com/Graylog2/graylog2-server/blob/e5b9889231588273dca8644bf77de60d87da46fe/graylog2-server/src/main/java/org/graylog2/users/UserImpl.java#L113

**Comment by patrickmann** [comment]
Instead of adding an entry to the `server.conf` file which needs to be kept in sync across all nodes, we will make this a new runtime configuration setting.
