### ISSUE TITLE
Selecting time range by dragging over message histogram doesn't update params in the URL

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#11388]
If you select an absolute time range by dragging over the messages histogram the times in the selector are updated but the change is not reflected in the URL

## Expected Behavior
Both time range selector and URL should be updated

## Steps to Reproduce (for bugs)
1. Select any absolute time range by dragging over the messages histogram
2. Verify that the times are changed in the time range selector
3. URL is not updated

## Your Environment

* Graylog Version:Graylog 4.2.0-SNAPSHOT+1c99273

**Comment by patrickfunke** [comment]
I'd love to see this fixed as well. With a search that grows more complex and/or a few panels for analysis when drilling down on an issue, page loads will even time out when jumping back to the initial larger timeframe. Also, this breaks the very helpful feature of having the search history accurately in the browser. Also, sharing a URL to a complex search is no longer straightforward.

Thank you @coffee-squirrel for the workaround, I can confirm that it works.
