### ISSUE TITLE
Keyword time range selector failing with HTTP 400

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#11385]
## Expected Behavior
Search -> time range should handle keyword time ranges like `Last five minutes`

## Current Behavior
The keyword parsing request fails:
REQ: GET /api/tools/natural_date_tester?string=Last%20five%20minutes&timezone=Europe%2FLondon
RES: `{"type":"ApiError","message":"No serializer found for class org.graylog2.rest.resources.tools.AutoValue_NaturalDateTesterResource_NaturalDateResponse and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)"}`

![image](https://user-images.githubusercontent.com/4102775/135411677-da9f6907-7ca6-4340-bbd1-ca13e05b4a05.png)

## Your Environment

* Graylog Version: Graylog 4.2.0-SNAPSHOT+1c99273
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by janheise** [comment]
adding `@JsonAutoDetect` to the class and `@JsonCreator` to the create method fixed it for me

**Comment by todvora** [comment]
Looking good to me!
