### ISSUE TITLE
Message timestamps in Alerts / Notifications are UTC only

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#11418]
There should be a way to select the timezone for notifications.

Either it could be the `root_timezone` or a separate setting for each notification.

[HS #543459648]

**Comment by tellistone** [comment]
I'd suggest that it should be optinally set at notification level, defaulting to root_timezone.

**Comment by tellistone** [comment]
https://community.graylog.org/t/email-alert-has-wrong-timestamp-in-the-timestamp-field/21898/16

**Comment by tmacgbay** [comment]
+1

**Comment by boosty** [comment]
I don't think `root_timezone` should be used as a default. The root user's time zone is unrelated to the recipients' time zones. 

But I agree that we should make the time zone more obvious and configurable, while keeping UTC as the default.

Ideas:
1. Try if the template language could be used to render a different time zone: https://help.ultradox.com/en/guides/templates/rendererreference.html#dateAndTime 2. If yes, our default templates should include that (using UTC by default).
2. If not, introduce an optional time zone setting per notification, similar to the time zone setting in a user profile (also using UTC by default).

**Comment by boosty** [comment]
I'll assign @diesaulov as well to keep him in the loop regarding documentation for this.

**Comment by thll** [comment]
> 1. Try if the template language could be used to render a different time zone: https://help.ultradox.com/en/guides/templates/rendererreference.html#dateAndTime (this seems to be the best documentation for the JMTE template language that we are using). If yes, our default templates should include that (using UTC by default).

If I'm not mistaken, the referenced documentation is for a system that uses JMTE with a lot of custom extensions. The date formatting options are not part of core JMTE. We would have to design and build something similar and also document it. I don't think we should go that route at this point.

> 2. If not, introduce an optional time zone setting per notification, similar to the time zone setting in a user profile (also using UTC by default).

#11982 implements this for email notifications now. If we are happy with the solution, we can think about adding a time zone setting to other notifications in the same fashion. Candidates would be:
- PagerDuty Notifications
- Slack Notifications

I would expect that the following types of notifications are not required to be human-readable, so I think we can leave them be:
- HTTP Notifications
- Script Notifications

I also wouldn't touch the "Legacy Alarm Callbacks"

**Comment by boosty** [comment]
> The date formatting options are not part of core JMTE. We would have to design and build something similar and also document it. I don't think we should go that route at this point.

Thanks for checking. I think you are right, adding template engine features would extend the scope of this quite a bit.

**Comment by boosty** [comment]
> #11982 implements this for email notifications now. If we are happy with the solution, we can think about adding a time zone setting to other notifications in the same fashion. 

Cool! Email was the initial motivation for this. But it would indeed be nice to support others, if we have time left for this in the current cycle.

**Comment by mpfz0r** [comment]
> > #11982 implements this for email notifications now. If we are happy with the solution, we can think about adding a time zone setting to other notifications in the same fashion.
> 
> Cool! Email was the initial motivation for this. But it would indeed be nice to support others, if we have time left for this in the current cycle.

@boosty did we create a second issue for adding it to other notifications as well?

**Comment by boosty** [comment]
@mpfz0r Not yet. I will create an issue for the Slack and MS Teams notification types.

**Comment by boosty** [comment]
@r4ndomir Please follow https://github.com/Graylog2/graylog2-server/issues/13421 regarding Slack.
