### ISSUE TITLE
Unable to get structured data in logged messages even after adding mmpstrucdata and mmrfc5424addhmac?(RFC5424)

### ISSUE THREAD

**Issue by LilyChadha** [Graylog2/graylog2-server#1144]
I am trying to log messages with structured data . But it is showing null value for structured data. I am working with rsyslog 8.9.0.Can someone tell me either i need to load some module or modify source to get structure data SD-IDs in logged message.

#Template:
"<%PRI%>%TIMESTAMP:::daterfc3339%%HOSTNAME%%syslogtag%%APPNAME%%PROCID% %MSGID% %msg% %STRUCTURED-DATA%\n”

getting message format as below:
<142>  2015-01-29T06:43:53.081641-05:00 localhost login[2116]: login 2116 -  [2116 : 2116 INFO]SERIAL Login from IP:127.0.0.1 user:admin -

#configuration file --rsyslog.conf:

$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support (previously done by rklogd)
$ModLoad mmpstrucdata
$ModLoad mmrfc5424addhmac

GLOBAL DIRECTIVES

$ActionFileDefaultTemplate RSYSLOG_DebugFormat
*.* /var/log/debugfmt.log;RSYSLOG_DebugFormat

After loading   mmpstrucdata and mmrfc5424addhmac i am getting structured data null.

**Comment by joschi** [comment]
Please refer to the official rsyslog support channels ([discussion forum](http://kb.monitorware.com/rsyslog-f40.html), [mailing list](http://lists.adiscon.net/mailman/listinfo/rsyslog)) for questions about the configuration and usage of rsyslog.
