### ISSUE TITLE
How mmpstrucdata and mmrfc5424addhmac works?

### ISSUE THREAD

**Issue by LilyChadha** [Graylog2/graylog2-server#1145]
I am trying to log messages with structured data . But it is showing null value for structured data. I am working with rsyslog 8.9.0.Can someone exlain me how these two modules mmpstrucdata and mmrfc5424addhmac will be effected?

**Comment by joschi** [comment]
Please refer to the official rsyslog support channels ([discussion forum](http://kb.monitorware.com/rsyslog-f40.html), [mailing list](http://lists.adiscon.net/mailman/listinfo/rsyslog)) for questions about the configuration and usage of rsyslog.
