### ISSUE TITLE
Error sending email

### ISSUE THREAD

**Issue by illogicalextend** [Graylog2/graylog2-server#1147]
Are there requirements for certain email variables to have a value for basic email (sending to MTA) to function?

In the web UI, I get the following after adding in a single email address as a recipient of an alert/alarm on a stream (and it's definitely a full email with no whitespace):

An error occurred while trying to send an email! 
The Graylog server encountered an error while trying to send an email. This is the detailed error message: org.apache.commons.mail.EmailException: javax.mail.internet.AddressException: Illegal address in string ``'' (javax.mail.internet.AddressException: Illegal address in string ``'')

My settings in/opt/graylog/conf/graylog.conf look like: 
```
# Email transport
transport_email_enabled = true
transport_email_hostname =
transport_email_port = 25
transport_email_use_auth = false
transport_email_use_tls = true
transport_email_use_ssl = true
transport_email_auth_username =
transport_email_auth_password =
transport_email_subject_prefix = [graylog]
transport_email_from_email =
```

/etc/graylog/graylog-settings.json (which were populated from the conf file, by the looks of things) [redacted current and last address]
```
{
  "timezone": "Etc/UTC",
  "smtp_server": "",
  "smtp_port": 25,
  "smtp_user": "",
  "smtp_password": "",
  "smtp_from_email": true,
  "smtp_no_tls": false,
  "smtp_no_ssl": false,
  "master_node": "127.0.0.1",
  "local_connect": true,
  "current_address": "x",
  "last_address": "x",
  "enforce_ssl": false,
  "rotation_size": 1073741824,
  "rotation_time": 0,
  "indices": 10,
  "journal_size": 1,
  "node_id": false
}
```

**Comment by joschi** [comment]
> Are there requirements for certain email variables to have a value for basic email (sending to MTA) to function?

You need to provide a working SMTP server, some credentials for it (if authentication is required), and a valid email address which is being used as sender (From) in all generated emails.

> In the web UI, I get the following after adding in a single email address as a recipient of an alert/alarm on a stream

Could you please check the logs of graylog-server during that time? Those should contain more details about the problem.

**Comment by illogicalextend** [comment]
Hm error message was less than ideal but ok. I'm only looking for something minimally viable so I suppose I'll fill out 127.0.0.1 in server and put a from address and go from there.

Thanks and I'll close this issue.
