### ISSUE TITLE
Inconvenient sidebars

### ISSUE THREAD

**Issue by Uporaba1** [Graylog2/graylog2-server#11480]
I have already created one topic about this issue, but in forum thread, I will repeat here.

Hello. In the old version of graylog, there were very convenient scroll bars, all data was ordered from top to bottom. In the new version, the scroll bar is not very convenient and it needs to be stretched, so that it would be beautiful like in the old version, and then all the data does not fit and it turns out a very not beautiful design. How can I fix this? Or should developers fix it? If so, when will it be fixed?

**Version 3.2.4:** 
![image](https://user-images.githubusercontent.com/32709525/137585042-fc15fcfb-d5dd-4cf5-9679-6db3a185fe1e.png)

**Version 4.1.6:**
![image](https://user-images.githubusercontent.com/32709525/137585046-59a1d69a-347a-4e1e-a470-822d44c4ec03.png)

I would also like to note that if there is a lot of data on the dashboard, they do not come out and become all in one line

**Comment by Emy-01** [comment]
@linuspahl @dennisoelkers I think we could close this ticket, in my opinion the width of the sidebar is acceptable in the current version. I didn't see any issue there. Was there a reason to keep this ticket open?
