### ISSUE TITLE
Query Input Assistance: validating a query

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#11490]
A user needs to know the data model (not only fields and their types, but also common field values) when writing a query. First step is to validate that the entered query may be executed.

## What to verify?

- [ ] syntax is correct (field names, operators, values, parenthesis)
- [ ] fields exist (with this ticket we only check if they exist in elastic search. With https://github.com/Graylog2/graylog2-server/issues/11502 we are checking if they exist in the selected streams)
- [ ] field types match operators (problems like string value for an int type)

Caution: all of it needs to be able to work across several indices!

## Why?
Increasing user satisfaction by reducing time-to-value. Helping user to understand that the query may be wrong and provide hints to correct the query

## Pointers:

- Validation API in  Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-validate.html 
- http://localhost:9200/graylog_0/_validate/query?rewrite=true&q=http_response_code:200&lenient=false
- http://localhost:9200/graylog_0/_validate/query?rewrite=true&q=http_response_code:A&lenient=false

## Steps:
- [ ]  Create own API endpoint, which uses the ES validation API (use custom separated DTOs) (link an API issue/PR here). The request payload needs to include the query string and time range.
- [ ] Implement frontend validation hints - background color? Warning sign? Error message? Highlighting? (link an FE issue/PR here)
- [ ] Implement backend, use the ES client and native support from ES, clean separation of native ES classes and DTOs used in the API  (link an BE issue/PR here)

**Comment by coffee-squirrel** [comment]
It would be nice if `and`, `or`, and `not`, as standalone terms in a query, were marked as potential issues.  Not having those in uppercase has been a source of confusion for some users (particularly those just starting out).

**Comment by todvora** [comment]
@coffee-squirrel good point! 

The default elasticsearch validation endpoint recognizes the problem, but the error message is not exactly helpful in that case (it's not clear that the `AND` token should be uppercase, it just fails to parse it)

![image](https://user-images.githubusercontent.com/4102775/138033480-d35ec5d2-70af-4735-bde5-5be252248cca.png)
