### ISSUE TITLE
Search API versioning

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#11508]
## Why?
Making breaking changes to our Search API is not easy, because it requires all clients to be updated in order to use the new version. 

## Approach
We should a) decouple our serialization/deserialization (e.g. REST requests/responses) from our internal representations. This way, REST resources become pure mappers of DTOs to internal representations and can use single entry points for our search engine. Having this kind of decoupling allows us to create different abstractions (multiple versions of the same Search API) as well as different APIs for similar functionality (scripting, frontend, anomaly detection).

## Challanges
We need to decide which way the version for an API is selected: path or header.

**Comment by dennisoelkers** [comment]
Fixed in #11594, #11646, #11666, #11751.
