### ISSUE TITLE
Query Input assistance: validate if fields in query exist in selected streams

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#11502]
## Description

With https://github.com/Graylog2/graylog2-server/issues/11490 we are improving the search query validation. We are already checking if a query field exists in elastic search. We also want to validate that fields exist in the selected streams.

Steps
[] Also provide streams filter in validation request payload
[] Extend backend query validation by checking if fields exist in the stream

**Comment by todvora** [comment]
Already implemented in the existing version. Closing now.
