### ISSUE TITLE
Query Input Assistance: validate spelling mistakes in field values

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#11503]
## Description

With https://github.com/Graylog2/graylog2-server/issues/11491 we are extending the query suggestions. Additionally we should check if the defined field values contain spelling mistakes and include the spelling suggestions in the completion dropdown.

Elastic search already provides logic to detect spelling errors:
![image](https://user-images.githubusercontent.com/46300478/138243424-fc82fb5d-a393-4319-b6b7-c99145173abb.png)

**Comment by todvora** [comment]
Suggestions/corrections for values already implemented. Do we want to follow with this issue and try to fix the key (=field name) suggestions as well? This would most likely require a FE implementation. Thoughts @linuspahl @dennisoelkers ?

**Comment by linuspahl** [comment]
@todvora and I just discussed that we will create another issue for the validation of spelling mistakes in field names and that we are adjusting the description of this issue. Before this change the issue was about spelling mistakes in general, now it is only about spelling mistakes in field values.

**Comment by linuspahl** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/pull/11949 and https://github.com/Graylog2/graylog2-server/pull/11974
