### ISSUE TITLE
OIDC claim support missing in Graylog Enterprise

### ISSUE THREAD

**Issue by cicigee** [Graylog2/graylog2-server#11528]
It does not appear to be possible to require a certain user claim to be present in a **userinfo**/**tokeninfo** payload for Google sign-ins to Graylog Enterprise with OIDC sign-in enabled.
## What?
It should be possible to specify that a certain claim must be present when configuring an OIDC service. (such as hd:example.com (hd means hosted domain) or requiring a certain **acr** value to force secure logins with one-time passwords with some identity providers)

## Why?
Organizations using Google Workspace need to be able to specify that the **hd** claim should be present and equal to a certain value. Otherwise anyone can sign in with regardless of their organization if they have a Google account.

https://www.oauth.com/oauth2-servers/signing-in-with-google/verifying-the-user-info/

## Your Environment
* Graylog Version: 4.2.0+5adccc3

**Comment by boosty** [comment]
I checked the Google documentation regarding the `hd` field, just to confirm:

> If you want to restrict access to only members of your G Suite domain, verify that the ID token has an `hd` claim that matches your G Suite domain name.

Source: https://developers.google.com/identity/gsi/web/guides/verify-google-id-token?hl=en

**Comment by cicigee** [comment]
Yes, that is indeed the claim I referred to. 👍

**Comment by boosty** [comment]
We have a customer request for this to be backported to 4.3.

**Comment by boosty** [comment]
@ousmaneo @patrickmann We also need to backport this to 4.2, where generic OIDC support was first introduced.
