### ISSUE TITLE
allow bulk import / multiple messages input for http gelf  and  add web base authentication

### ISSUE THREAD

**Issue by macaty** [Graylog2/graylog2-server#11523]
## What?

allow bulk import / multiple messages in request for http gelf input

## Why?

I use it to collect h5/web base app logs, it use ajax POS to message. Web browser need more efficient way to handle post message.

1、I hope ajax js agent can post message like：

Single Message /gelf

{"version": "1.1", "host": "..."}

List of Messages /gelf/bulk

[
  {"version": "1.1", "host": "..."},
  {"version": "1.1", "host": "..."},
  {"version": "1.1", "host": "..."}
]

2、 hope the gelf http can supoort webase authentication like ：
1、HTTP Basic Authentication
2、HTTP secrect token/key Authentication in url or head or payload

## Your Environment

* Graylog Version: 4.2
* Elasticsearch Version: 7.10
* MongoDB Version: 4.2
* Operating System: centos 7.9
* Browser version: chrome

**Comment by danotorrey** [comment]
This was implemented and released in the recent Graylog. 4.3 release. 
https://www.graylog.org/post/announcing-graylog-v4-3-graylog-operations-graylog-security

Usage docs are available here: 
https://docs.graylog.org/docs/ingest-gelf
