### ISSUE TITLE
Invalid data on HTTP alarm callback

### ISSUE THREAD

**Issue by dfateyev** [Graylog2/graylog2-server#1153]
There is an issue with HTTP alarm callback notification on the latest graylog 1.0.2. Some messages mentioned in the backlog don't belong the source stream, and their count doesn't reflect alert condition settings: there are always 10 messages in the backlog, no matter how many previously set in the condition.

Recently discussed it with @dennisoelkers , also provided the steps how to reproduce it.

**Comment by dennisoelkers** [comment]
Fixed this in f0b5f397212c5bb65cdf66260b80b6de704279ae  for 1.0.x and a8c6a40fd192cd5692c550a3311db004535cd0a6 for 1.1.x.
