### ISSUE TITLE
full_message value truncated to message value when forwarding GELF messages

### ISSUE THREAD

**Issue by brandongalbraith** [Graylog2/graylog2-server#1154]
I'm currently performing testing by sending GELF UDP messages to a primary Graylog server, and then using a stream (that constraints to all messages that have a timestamp attribute) to forward all of the received GELF UDP messages to a secondary Graylog server using the GELF TCP inputs/outputs.

It appears that `full_message` is truncated to the value of `message` when its processed on the secondary Graylog server. Is this expected behavior?

**Comment by joschi** [comment]
Thanks for reporting this! That behavior is definitely a bug and will be fixed in Graylog 1.1.0.

**Comment by brandongalbraith** [comment]
Thank you for the fix @joschi!
