### ISSUE TITLE
Alert emails should contain complete message text

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#1156]
Currently the alert emails generated by `FormattedEmailAlertSender` are using the [string representation of `Message`](https://github.com/Graylog2/graylog2-server/blob/1.0.2/graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/Message.java#L199-223), which truncates the message text to 225 characters.

Since log messages might contain important information in their `message` attribute, it should be printed in full length. The `full_message` attribute, which might contain large quantities of text, should still be omitted.

Related mailing list topic: https://groups.google.com/d/topic/graylog2/3EHjJKduRmo/discussion

**Comment by henrikjohansen** [comment]
@joschi When shipping Windows eventlogs using the nxlog gelf output module the message field only contains a fraction of the entire log ... here full_message is required in order to view the entire event.

**Comment by kroepke** [comment]
see https://github.com/Graylog2/graylog2-web-interface/issues/1355 for a possible workaround.

**Comment by bernd** [comment]
I created a pull request to document the objects in the email template here: https://github.com/Graylog2/documentation/pull/22

Closing this now because people are now able to customize this based on their requirements.

Please re-open if this should still be fixed in the code.
