### ISSUE TITLE
Alert emails should include alert description

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#1158]
Our alert emails are not including the nice alert description that the web interface shows. We have that information in a complete string already so adding it to the email should be easy(tm).

> Stream received messages matching source:"example.org" (Current grace time: 2 minutes)

**Comment by lennartkoopmann** [comment]
Thanks! This seems to only affect the alarm callback and not the normal email though. (I mean the email that users who subscribed to the alert get)

**Comment by dennisoelkers** [comment]
No, actually the default email sender when no alarm callback has been defined is using the formatted email sender with a default template/subject (to which I added the alert description now) too.

**Comment by lennartkoopmann** [comment]
Ha! This is also very helpful for #1163

Will check later. Thanks!
