### ISSUE TITLE
csv export aggregated search results, including aggregate field (like IPv4) and count

### ISSUE THREAD

**Issue by kkplein** [Graylog2/graylog2-server#11598]
There seems to be no way to export the results of an aggregated search, including the count (for number of occurrences of the aggregated field)

Example: I create a search for "failed authentication" over the last 60 minutes, including remote IPv4 address. The aggregated IPv4 search results look like this in my graylog dashboard:

| IPv4        | Count() |
|-------------|-------|
| 1.2.3.4     | 534   |
| 5.6.7.8     | 423   |
| 9.10.11.12  | 123   |
| 13.14.15.16 | 70    |

I would like to export those results (so only the IPv4 address and the count) to csv. But there is no 'export' button in the actions dropdown menu, see:
![graylog export](https://user-images.githubusercontent.com/5812542/140780248-dcff6faa-c060-4d79-bcdd-22888555254e.jpg)

It would be very convenient for the actions menu to include the "export" option.

**Comment by tmacgbay** [comment]
+1 :)

**Comment by HungryHowies** [comment]
@kkplein  I agree that would be nice to have. I tried a couple ways but was unable  to get the count results.

**Comment by lucas-garcia-rubio** [comment]
This feature would be nice. I have to download all the messages I want by slices of time (because I don't have memory enough for so many messages) and aggregate them in my script. It takes too long, but unfortunately it is the only way I found.

**Comment by lucas-garcia-rubio** [comment]
I found a way out to this problem: inspect your page (F12 on Mozilla), go to network, clean requests, change the timerange on graylog and make the search again. It has to appear a "execution" request. This is the request that Graylog does to populate the tables. Click with the right button and copy the cURL. Paste in somewhere else and analyze the request. You can mimic it in your code and work with the response as a json or a dict.

**Comment by riskersen** [comment]
+1 I would really appreciate this feature. It doesn't make much sense to prepare nice dashboards and aggregration just to redo them again in Excel after the download.

Imagine also that proxy logs from a specific source might contains millions of rows but I'm only interested in the count per host... I have to download tons of rows just to do the count again.

**Comment by szimmer-dap** [comment]
+1 for this feature request. Given that the dashboard widgets lack basic functionality like rounding, it makes sense to be able to export aggregated data to another tool.

**Comment by fredsilvas** [comment]
+1. This would be a really nice feature.

**Comment by janheise** [comment]
Sorry all that it seems there hasn't been much progress with this ticket. Maybe for some, the new scripting API that exports csv is the solution? 
https://go2docs.graylog.org/5-1/making_sense_of_your_log_data/simple_search_scripting_api.htm?tocpath=Searching%20Your%20Log%20Data%7C_____5

**Comment by alex3ller** [comment]
+1

**Comment by drewmiranda-gl** [comment]
Noting that it looks like this is roadmapped for Graylog 6.1.

**Comment by sen-den** [comment]
+1

**Comment by dennisoelkers** [comment]
This has been implemented for 6.1, which is about to be released in October. Closing this issue. Thanks everyone for your input!

**Comment by kkplein** [comment]
Much appreciated! :-)
