### ISSUE TITLE
The alert condition tests are all ignored and fail

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#1159]
The alert condition tests for `org.graylog2.alerts.types` are all ignored using the `@Ignore` annotation. When enabling them, they fail with `java.lang.NoSuchMethodException` and other runtime errors.

**Comment by kroepke** [comment]
It's missing an Searches.class instance to perform the actual searching. Should be simple to mock.

**Comment by kroepke** [comment]
And in fact the service in use is relying on tons of mongodb specifics. :/

**Comment by lennartkoopmann** [comment]
Thanks! :)
