### ISSUE TITLE
Syslog gets not parsed properly

### ISSUE THREAD

**Issue by kaelumania** [Graylog2/graylog2-server#1161]
I configured the rsyslog client via udp as shown in the docs http://docs.graylog.org/en/1.0/pages/sending_data.html#rsyslog

But it seems, that graylog is not parsing it correctly. Here is an example message:
`<14>0 2015-05-20T07:57:51.366179+00:00 f382af4884f3 logger - - -  Hello Info 3`

When this message gets parsed by graylog, two of the three dashes are shown in the message field, e.g. ` - -  Hello Info 3`

(I am using the graylog docker image https://github.com/Graylog2/graylog2-images/tree/master/docker)

**Comment by bernd** [comment]
Thank you for the report. I created #1176 and Graylog2/syslog4j-graylog2#4 to fix this.

This will be in the upcoming 1.1.0 release. (probably >= beta.3)
