### ISSUE TITLE
Plugin loaded successfully however does not appear in UI

### ISSUE THREAD

**Issue by mindcurv-vishnu** [Graylog2/graylog2-server#11612]
Plugin loaded successfully however does not appear in UI

## Expected Behavior

Loaded plugin should appear in the UI

## Current Behavior

`2021-11-09 08:14:06,385 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: OpsGenie Alarm Callback 1.3.15-RELEASE [com.opsgenie.plugin.graylog.OpsGenieAlarmCallback]`
Logs shows the plugins are loaded, however it does not appear in the UI

Plugins loaded in the plugins directory after restart do not appear in the UI

## Steps to Reproduce (for bugs)

1. pull docker image graylog/graylog-sso:3.3.6 
2. Download the plugin https://github.com/opsgenie/opsgenie-graylog-plugin jar and run the container mounting the plugin directory
3. Check the logs of the container to see the plugins loaded
4. Check the UI configuration to see if the plugin appears

## Your Environment

* Graylog Version: graylog/graylog-sso:3.3.6
* Java Version: 
* Elasticsearch Version: 6.8.13
* MongoDB Version: mongo:4.0.20
* Operating System: Ubuntu 18
* Browser version: Chrome 95.0.4638.69

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
