### ISSUE TITLE
PagerDuty Webhooks are changing

### ISSUE THREAD

**Issue by tellistone** [Graylog2/graylog2-server#11614]
In case this hasn't reached Engineering, PagerDuty emailed support today to inform Graylog that they are making changes to their webhooks. Can we please investigate and confirm whether we need to make adjustment for this. The message:

Re: Your integration with PagerDuty built with PagerDuty's APIs and webhooks

Just wanted to email you to let you know the following changes will be happening in the near future. Please forward this to the team that is responsible for the development of the integration.

1. CHANGES TO WEBHOOKS: We are happy to launch our v3 webhooks utilized to build a native integration.   In addition, we wanted to let you know that we are deprecating our v1 webhooks and v2 webhooks at the end of November 2021 (v1 webhooks) and March, 2022 (v2 webhooks).  Please review your current integration listed on the PagerDuty Directory and upgrade your integration to v3 webhooks before November, 2021.

Resource Links for webhooks:

https://support.pagerduty.com/docs/webhooks

https://support.pagerduty.com/docs/webhooks#migrating-from-v1v2-generic-extensions-to-v3-webhook-subscriptions 

Integration Documentation: Please also review your integration documentation and make any changes needed. Let us know if there are changes to your documentation.  Go to the PagerDuty Integration Directory

2. INCIDENT AND ALERT ID CHANGES: We are also making changes to the Incident and Alert ID.  The Incident and Alert ID are being increased in character length to 14 in place of the current 7 characters to support the increasing storage capacity of our systems starting in the month of October, 2021.  We will first roll this out to our EU service region on October 5, 2021, followed by a rollout to the North American service region on October 12, 2021.

If you have a custom integration or your own code that makes use of PagerDuty’s API, you should review that code at this time to ensure that it will continue to function with the new identifiers. Specifically, you should confirm that your code does not rely on the existence of a P prefix for incident identifiers, nor make assumptions that they are of a certain length.

If you have any questions, please email Apps@pagerduty.com.

PagerDuty Integrations Team

**Comment by waab76** [comment]
Engineering has looked at the PagerDuty webhooks change and this should not impact the official Graylog PagerDuty integration.  

PagerDuty's APIs allow Graylog to send data to PagerDuty.  The webhooks would allow PagerDuty to send data back to Graylog.  In its current state, the PagerDuty notification only uses the APIs to send data to PagerDuty.  We do not use PagerDuty webhooks to receive callbacks from PagerDuty.

Also, we should not be impacted by the Incident and Alert ID changes PagerDuty is implementing.

**Comment by bernd** [comment]
As @waab76 said, we are not affected. Closing this issue. Thanks for the heads-up! :+1:
