### ISSUE TITLE
to_ip() function not working, "Infinite recursion (StackOverflowError)"

### ISSUE THREAD

**Issue by williamtrelawny** [Graylog2/graylog2-server#11622]
Trying to set the data type of a IPv4 address string to `ip`, but it does not work. It throws an infinitely repeating StackOverflow error in server.log, even after I remove the offending Pipeline Rule (see attached server.log sample). 

[graylog to_ip() bug.txt](https://github.com/Graylog2/graylog2-server/files/7522859/graylog.to_ip.bug.txt)

## Expected Behavior
Use `to_ip()` function as described [here](https://github.com/Graylog2/graylog2-server/issues/4498#issuecomment-359416724) to convert a dot-notated IPv4 address string to `ip` data type, and set it as the value for a field.

Another reference to this same error is [here](https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/199), but the OP said his issue was with IPv6 addresses, which does not pertain to me because I'm only using IPv4 addresses.

## Steps to Reproduce (for bugs)

Example pipeline rule below (this is also the exact rule that generated the attached server.log output):
```
rule "to_ip() function bug demo"
when
    is_string($message.source_ip)
then
    debug(is_string($message.source_ip));
    let x = to_ip($message.source_ip);
    set_field("source_ip", x);
end
```
This proves in two ways that `$message.source_ip` is indeed a string to begin with, so there's no doubt about that.

I tried passing `$message.source_ip` in a few different ways, to no avail:
`set_field("source_ip", to_ip($message.source_ip))`
`set_field("source_ip", to_ip(to_string($message.source_ip)))`
`set_field("source_ip", to_ip("$message.source_ip"))`

## Context
Trying to convert IPv4 addresses to `ip` data type for analytics.

## Your Environment

* Graylog Version: 4.2.0+5adccc3
* Java Version: Debian 11.0.13 on Linux 4.19.0-12-amd64
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.2.10
* Operating System: Debian 11

**Comment by williamtrelawny** [comment]
Found [this post](https://community.graylog.org/t/changing-a-field-type-from-string-to-numeric-and-mid-setup-and-past-string-values/3297/4) suggesting to rotate the active write index to refresh the index mappings, but I have tried this and it did not work.

**Comment by boosty** [comment]
It seems this was fixed by https://github.com/Graylog2/graylog2-server/pull/11736 in the meantime
