### ISSUE TITLE
ossec logs not seen in graylog

### ISSUE THREAD

**Issue by HSVK** [Graylog2/graylog2-server#1162]
Hi, OSSEC logs are being pushed to graylog using syslog udp, i can see the messages landing in the graylog server with the help of tcpdump. Also i can query for those ossec messages in elasticsearch. So i believe graylog is processing the messages but they are not shown in the Graylog sources/searches nor do i see any issues in graylog logs. Can you please help.

OSSEC.conf file
```
  <remote>
    <connection>secure</connection>
  </remote>
 
  <alerts>
    <log_alert_level>1</log_alert_level>
    <email_alert_level>7</email_alert_level>
  </alerts>
  
  <!-- Files to monitor (localfiles) -->
 
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/messages</location>
  </localfile>
 
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/authlog</location>
  </localfile>
 
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/secure</location>
  </localfile>
 
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/xferlog</location>
  </localfile>
 
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/maillog</location>
  </localfile>
 
  <localfile>
    <log_format>apache</log_format>
    <location>/var/www/logs/access_log</location>
  </localfile>
 
  <localfile>
    <log_format>apache</log_format>
    <location>/var/www/logs/error_log</location>
  </localfile>

  <syslog_output>
    <server>graylog.server ip</server>
    <port>Graylog server port</port>
  </syslog_output>
  <syslog_output>
   <server>server1 IP</server>
  </syslog_output>
<syslog_output>
  <server>server2 IP</server>
  <port>server2 port</port>
  <format>cef</format>
</syslog_output>
 
</ossec_config>
```
Thanks, Hema

**Comment by joschi** [comment]
If the messages have been indexed into Elasticsearch, they are definitely there and can be queried with the Graylog web interface. This sounds more like a timezone issue with the messages.

Please try to widen the search time range (also into the future). The indexed messages might have a timestamp in the future, if the detected timezone is off (e. g. UTC+02:00).

**Comment by HSVK** [comment]
Hi Joschi,
   Thank you very much, That really helped, i searched for last day and i got the results but later graylog stops with "internal error"

- How do i sort this out in UI w.r.t timestamp. 
- If it is a future message, should i search with "Next 1 Hour" instead of "Last 1 Hour"
- If this was the timestamp issue, doesn't the 'Source' in UI show the source name. 
- Also apart from that, in the elasticsearch query the message field has this entry after the host name and alert level "Non Standard Syslog Message (Size too large)" and rest of the messages. Does this matter to graylog or will it cause any issue?

The timestamp that i see in the current indice for that source is 2015-05-20 08:38:43.000

The timestamp that i see in the graylog UI is, 
User : 2015-05-20 11:55:13.452 +00:00
Web browser: 2015-05-20 17:25:13.964 +05:30
Default JDK/JRE: 2015-05-20 05:55:13.452 -06:00
Graylog web interface: 2015-05-20 11:55:13.452 +00:00
Graylog master server: 2015-05-20 05:55:13.453 -06:00
 
- Does graylog takes the User timestamp from the above for searches?

Thanks, Hema.

**Comment by joschi** [comment]
Please check if the syslog messages contain a valid timestamp including a timezone. If there is no timezone given in the syslog message, Graylog will assume UTC.

> Does graylog takes the User timestamp from the above for searches?

Yes, Graylog is using the user's configured timezone for searches. You can configure the timezone for normal users in the web interface at System -> Users and the timezone for the admin user in the Graylog configuration file: https://github.com/Graylog2/graylog2-server/blob/1.0.2/misc/graylog2.conf#L28-30

> […] but later graylog stops with "internal error"

Please check the logs of Graylog for error messages and exception stack traces.

**Comment by zexxon** [comment]
Closed issue due to inactivity. Please reopen if you have more information.
Thanks.
