### ISSUE TITLE
Add group sync to AzureAD authentication provider

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#11621]
Currently, setting up AzureAD uses our generic OIDC authentication backend, which does not support group sync. Since group syncing is not part of the OIDC standard, it is unlikely that we can have a single authentication backend to fit all services supporting OIDC. This means that we may need to implement a specific AzureAD authentication backend, or an AzureAD group sync mechanism.

## What?
Have a way of syncing the AzureAD groups in Graylog.

## Why?
This would allow users of AzureAD and Graylog to sync their groups into teams and grant permissions through them. See an example of that in HS-652156025.

## Your Environment

* Graylog Version: 4.2

**Comment by patrickmann** [comment]
Fixed by Graylog2/graylog-plugin-enterprise#5767
