### ISSUE TITLE
Alert email mentions backlog even if no backlog was set

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#1163]
Alert emails are mentioning a backlog even if no backlog was configured:

> Last messages accounting for this alert:
> /end of email

You can reproduce this by triggering an alert email with backlog set to 0 in alert condition.

**Comment by joschi** [comment]
Could you please check the template being used for that alert? The default template should only print this line ("Last message […]") if the backlog contains at least 1 message: https://github.com/Graylog2/graylog2-server/blob/1.1.0-beta.2/graylog2-server/src/main/java/org/graylog2/alerts/FormattedEmailAlertSender.java#L46-52

**Comment by lennartkoopmann** [comment]
Thanks! Will check later today.

**Comment by dennisoelkers** [comment]
Fixed in fdcd77ac2110b9d5a5710164213e650eb84fa4b0.
