### ISSUE TITLE
Graylog 4.2 + Java 11 = WARNING: sun.reflect.Reflection.getCallerClass is not supported.

### ISSUE THREAD

**Issue by chi-miel** [Graylog2/graylog2-server#11634]
## Expected Behavior
Unsupported classes should not be used.

## Current Behavior
Running Graylog 4.2 with Java 11 generates following Warning

```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/usr/share/graylog-server/graylog.jar) to constr>
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

## Steps to Reproduce (for bugs)
1. Upgrade Graylog to 4.2 with Java 11
2. Start service
3. Check service status

## Your Environment

* Graylog Version: 4.2
* Java Version: openjdk version "11.0.13" 2021-10-19 LTS
* Operating System: CentOS Linux release 8.4.2105

**Comment by chi-miel** [comment]
Seem same problem : 
https://github.com/Graylog2/graylog2-server/issues/9802
https://github.com/Graylog2/graylog2-server/issues/7223

**Comment by bernd** [comment]
@chi-miel This is just a warning message and shouldn't cause any problems. In this case this is related to the retrofit library. The warning will disappear when the library fixes the reflective access.

**Comment by maktas** [comment]
The warning message is still being shown in Graylog 5 with default java version in that package:
openjdk 17.0.6

Aug 24 11:30:03 *** systemd[1]: Started Graylog server.
Aug 24 11:30:04 *** graylog-server[11733]: WARNING: sun.reflect.Reflection.getCallerClass is not supported. >
