### ISSUE TITLE
Read more about licenses in the documentation - 404 error

### ISSUE THREAD

**Issue by yliya1991** [Graylog2/graylog2-server#11638]
Enterprise / Licenses  - Licenses - Read more about licenses in the documentation-  by clicking the offline documentation page https://docs.graylog.org/en/4.0/pages/enterprise/licenses.html - 404 error.   Installed graylog-plugin-enterprise-4.2.0.jar .
<img width="1430" alt="Снимок экрана 2021-11-16 в 15 38 05" src="https://user-images.githubusercontent.com/38718724/141995504-8e0a0acb-eb89-4808-a7d5-dc88c3780692.png">

* Graylog Version:4.0; 4.2
* Elasticsearch Version:7.10.2
* MongoDB Version:4.0
* Operating System: Linux
* Browser version:Chrome v. 95.0.4638.69, (x86_64)

**Comment by bernd** [comment]
@dulanism Can you take a look at this? Thank you!

**Comment by linuspahl** [comment]
Although the mentioned URL still does not work, it looks like the link on the Enterprise / License page has been fixed.
