### ISSUE TITLE
Breaking API Change not in release notes regarding /api/system/pipelines/pipeline

### ISSUE THREAD

**Issue by HenryTheSir** [Graylog2/graylog2-server#11645]
## Expected Behavior

API Changes which are not compatible to previous versions should be documented as breaking API Change in Release Notes

## Current Behavior

API Change not documented
## Possible Solution

Document API Change
## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Context

This PR (https://github.com/Graylog2/graylog2-server/pull/11092) introduces a new option to allow further processing in the pipeline if no rule matches in current stage. The implementation is a breaking Change in the needed fields of the API. 

If Content Packs created in previous versions are affected as well was not tested for this issue, but seams possible as in the PR no downgrade compatible options are implemented. 
## Your Environment

* Graylog Version: 4.2

**Comment by bernd** [comment]
> The implementation is a breaking Change in the needed fields of the API.

@HenryTheSir Can you elaborate on how this breaks the API compatibility regarding required fields? Thank you!

**Comment by HenryTheSir** [comment]
Prev 4.2 the JSON Field was named match_all with an boolean value. Since 4.2 the field needs to be "match" with a String Value. 
![grafik](https://user-images.githubusercontent.com/11004513/142859810-51b82355-2057-4242-88b9-35a275f69acb.png)

Deploying Configuration fails if the field is not existing in 4.2 (via Custom Configuration Management/Staging Process). 
As mentioned above: It is not about the change itself, just a missing API Change docu in the release docs. 


```
2021-11-22 13:27:22,723 ERROR: Updating not successfull {'X-Graylog-Node-ID': 'xxxx', 'Content-Type': 'application/json', 'Connection': 'close', 
'Content-Length': '385'}400b'{"type":"ApiError","message":"Cannot construct instance of `org.graylog.plugins.pipelineprocessor.rest.StageSource`, problem: Null match\\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 764] (through reference chain: org.graylog.plugins.pipelineprocessor.rest.PipelineSource[\\"stages\\"]->java.util.ArrayList[0])"}'
```

A serverside stacktrace gets not written

**Comment by bernd** [comment]
@HenryTheSir Thanks for the update! We updated the upgrade notes to include a section for this change. https://docs.graylog.org/docs/graylog-4-2

Thank you! :pray:
