### ISSUE TITLE
/api/views/search/messages returns 200 even if Graylog is logging a lexical error

### ISSUE THREAD

**Issue by riskersen** [Graylog2/graylog2-server#11662]
Take following query for a custom mapping type:ip field to /api/views/message
```
{
  "query_string": {
    "type": "elasticsearch",
    "query_string": "test_client_ip:(192.168.178.0/24)"
  },
  "timerange": {
    "type": "relative",
    "range": 86400
  },
  "chunk_size": "500",
  "streams": [
    "5f218679a45add539817c246",
    "5f218612a45add539817c1cc"
  ],
  "limit": "500",
  "fields_in_order": [
    "client_ip",
"url"
  ]
}
```

## Expected Behavior
API should return http code 422 or 400 with providing a useful hint.

## Current Behavior
Response is 200 and no content. Checking the logs, you will see a big stack trace coming from elasticsearch
```
Caused by: org.graylog2.indexer.ElasticsearchException: ElasticsearchException[Failed to execute Search After request]; nested: ElasticsearchException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]; nested: ElasticsearchException[Elasticsearch exception [type=tok
en_mgr_error, reason=token_mgr_error: Lexical error at line 1, column 31.  Encountered: <EOF> after : "/24"]];
```

## Possible Solution
Catch Exception during API call and return a proper, human-readable error message as an API error

## Steps to Reproduce (for bugs)
Feed the API with broken/invalid syntax search string

## Context
Trying to make use of slashes in REST query

Just for the note, correct syntax needs to include two backslashes, one for espacing the backslash which will esacpe the slash:
`  "query_string": {
    "type": "elasticsearch",
    "query_string": "test_client_ip:(192.168.178.0\\/24)"
  },`

## Your Environment

* Graylog Version: 4.2
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.2
* Operating System: Ubuntu 20.04
* Browser version: Edge

**Comment by todvora** [comment]
Hello @riskersen, 
Thank you for the feedback. Error handling during a chunked output is quite tricky. In the moment we detect the problem with invalid query, we can't anymore respond with a correct HTTP code. 

There are two approaches we have implemented to make the handling better:

1. If an exception happens during the chunked output, we will terminate the output and the last message will be the error message itself. It's a bit clumsy, but there is nothing more we can do in that stage.
2. Additionally, we have integrated a query validation, which will happen before any processing. If this validation detects an invalid query, like in your case, it will indeed respond with a proper 4XX http code and error message

![image](https://user-images.githubusercontent.com/4102775/146337925-926f0f0a-1452-4a6f-916e-aa405e459f7a.png)

This should cover all problems and no error should happen unnoticed. 

Best regards, 
Tomas

**Comment by riskersen** [comment]
Thanks all. The fixes seem reasonable and will surely help. Parsing the syntax is indeed quite tricky.. I'm currently building an UI which makes use of the search API for some of our internal customers, who may be overwhelmed with the power of Graylog and elastic search, so I also need to build some query validation before Graylog does that as well ;)

I will test the fix in the next weeks.
