### ISSUE TITLE
API endpoint /count/total gone after upgrade to GL 4.1

### ISSUE THREAD

**Issue by pdcemulator** [Graylog2/graylog2-server#11673]
I just upgraded my test system from Graylog 3.3.14 to 4.1.7 on CentOS Stream 8 with Java 1.8.0_312.

Now I noticed that the API endpoint /count/total is no longer available and the removal is not mentioned in the docs. Is this a bug in the current release or an issue in the docs?

## Expected Behavior
API endpoint /count/total is available and useable.

## Current Behavior
API endpoint /count/total is no longer available.

## Possible Solution
Re-add API endpint /count/total in GL.
Or fix docs (https://docs.graylog.org/en/4.0/pages/upgrade/graylog-4.0.html#api-endpoint-deprecations and https://docs.graylog.org/docs/changelog)

## Steps to Reproduce (for bugs)

1. Call API /count/total

## Context
I use this with my monitoring system checkmk to get the number of messages from Graylog.
There are two threads about this issue in the forum without a valid answer whether its an issue in graylog or in the docs.
What would be the best alternative to retrieve the number of messages from graylog?

## Your Environment
Graylog 4.1.7 on CentOS Stream 8 with Java 1.8.0_312

**Comment by dennisoelkers** [comment]
Hey @pdcemulator,

thanks for reporting this!

The removal of the Counts API is included in the changelog for 4.0.0: https://docs.graylog.org/docs/changelog#graylog-400 - See "Removed" -> "Remove legacy counts API". We should have included it in the API endpoint deprecations though, to make it clearer.
