### ISSUE TITLE
/system/inputs and metrics per node (1.1-beta1)

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1168]
In 1.0 it was possible to see the throughput for each node running a given input - that was very, very useful when running behind load-balancers so I would like to see this resurrected in 1.1

**Comment by kroepke** [comment]
Agreed!

Wie initially thought of adding it as a drop down on the global throughput display in the menu bar.
Not sure if that would be enough. Thoughts?

**Comment by henrikjohansen** [comment]
I'd really like to see this per input - sometimes we need to adjust our LB rules to ensure that traffic is placed on all nodes evenly and that feature in 1.0 was priceless for that :)

**Comment by kroepke** [comment]
Ah input! I somehow read node!

**Comment by kroepke** [comment]
For reference, it is this one in global inputs:
![screenshot](https://cloud.githubusercontent.com/assets/52014/7767103/0641e3dc-0070-11e5-8369-0a2fefaced3b.png)

**Comment by henrikjohansen** [comment]
Exactly - the 'Show details' feature :)

**Comment by bernd** [comment]
This got fixed in Graylog2/graylog2-web-interface#13333 and will be in the next 1.1.0-beta release.
