### ISSUE TITLE
Being able to use the latest Elasticsearch version

### ISSUE THREAD

**Issue by FlorinPeter** [Graylog2/graylog2-server#11686]
## What?

Currently the docs are stating that only ES 7.10 is supported but it is disappointing not to be able to upgrade the ES cluster from security point of view. It would be helpful if the ES version blocker could be released.

## Why?

Mainly security and bug fixes are the driver behind this request

## Your Environment

* Graylog Version: 4.2.1

**Comment by FlorinPeter** [comment]
@bernd any news about that?

**Comment by kroepke** [comment]
We will announce a plan shortly with regards to Elasticsearch compatibility and support going forward.
Thanks for your patience.

**Comment by user29835461** [comment]
Just a quick observation. I hope the announcement is that ES 7.16+ will be fully supported, because in the last week due the critical log4j vulnerabilities 99% of Graylog users have just upgraded to 7.16.1 and/or 7.16.2.... Other kind of announcements will be mostly seen as amusing at this point.
