### ISSUE TITLE
Users with reader permissions cannot use the "Quick Values feature" (1.1-beta1)

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1169]
Whenever a read-only users presses the quick value button on a field he / she get a red error stating "Error loading ... Internal Server Error"

**Comment by kroepke** [comment]
fixed in https://github.com/Graylog2/graylog2-web-interface/commit/5ce4a02681156561aede5177c687bf384a64e344

referenced the wrong repo :(

**Comment by bernd** [comment]
Closed in Graylog2/graylog2-web-interface@5ce4a02. Will be in the next 1.1-beta.

Thank you for the report!
