### ISSUE TITLE
Questions: Why hourly cpu peaks ?

### ISSUE THREAD

**Issue by NoxInmortus** [Graylog2/graylog2-server#11727]
Hello, I have 5 graylogs servers running on virtual machines on different hypervisors. Each Graylog have a single Input defined and receive logs without stop. Server will have a cpu peak every hour, coming from a ~5% cpu usage and peaking to ~25/35% cpu usage:
![image](https://user-images.githubusercontent.com/12948248/144390401-5b030a22-c986-4a0d-a340-f4d45f25e96a.png)

The VMs have these specs:

Debian 10 64bits
6 CPU / 8G RAM
MongoDB standalone 4.2.17
Single node Elasticsearch-OSS 7.10.2 (-Xms2g -Xmx2g)
Graylog 4.1.7 using these importants parameters:
```
rotation_strategy=time
elasticsearch_max_time_per_index=1d
elasticsearch_max_docs_per_index=20000000
retention_strategy=delete
elasticsearch_shards=1
```

I'm wondering why is there those hourly CPU peaks, what could be done to not have thoses (or a least decrease their intensity), and if there is some maintenance option/configuration that could be changed related to this ?

Thanks for reading.

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
