### ISSUE TITLE
Processing Messages stopped after OOM on elasticsearch Cluster

### ISSUE THREAD

**Issue by nycoon** [Graylog2/graylog2-server#1174]
Hey 
if one of the data nodes from elasticsearch runs in an OutOfMemory exception and the cluster status goes to yellow, graylog-server will store all new incoming messages to the local journal. (y)
But now if the nodes comes back and the cluster status comes back to green i´ve to restart the graylog-server nodes for "processing" the stored messages. 

UnavailableShardsException[[graylog2_12][2] [2] shardIt, [0] active : Timeout waiting for [1m], request: org.elasticsearch.action.bulk.BulkShardRequest@41aee44b]
RemoteTransportException[[Kingo Sunen][inet[/x.x.x.x:9300]][bulk/shard]]; nested: OutOfMemoryError[Java heap space];

elasticsearch Cluster setup: three master nodes and two data nodes.

Versions: 
graylog-server-1.0.2-1.noarch
graylog-web-1.0.2-1.noarch
elasticsearch-1.4.5-1.noarch

**Comment by zexxon** [comment]
Please upgrade to Graylog 1.1 and ES 1.6, we believe the issue may have been resolved in the newest versions of Graylog and ES.
