### ISSUE TITLE
Wildcard search is broken

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-server#1175]
1.1-beta-3 snapshot wildcard search gives no result.

**Comment by joschi** [comment]
Could you please give an example query.

**Comment by kroepke** [comment]
Using the random http input:

controller:Posts*

Results in no hits for me, too.

**Comment by kroepke** [comment]
Actually this never really worked...

For specific fields, that aren't analyzed, wild card searches won't work.
The fields message, full_message and source are analyzed, so wildcards work there.

Also searching in all fields works, too.
Just not in specific fields.

So it's not actually a bug, but hugely confusing.
