### ISSUE TITLE
[Question] Memory footprint of graylog

### ISSUE THREAD

**Issue by jay11ca39** [Graylog2/graylog2-server#11762]
I have browsed through internet, but could not find answer for following answers: 

- What is memory footprint of graylog? 
- Any benchmarking is done with other alternatives fluentd/fluentbit, rsyslog or logstash ?

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
