### ISSUE TITLE
Support AWS DocumentDB

### ISSUE THREAD

**Issue by OneWithTheCore** [Graylog2/graylog2-server#11780]
Looking to leverage AWS DocumentDB as a service for the MongoDB related tasks, but DocumentDB doesn't support capped collections. When trying to create a collection with "capped:true", I get the error `"errmsg" : "Feature not supported: capped:true"` which is the same error I get when running Graylog against DocumentDB.

Similar to issues #3866 (DynamoDB Support) and #5927 (DocumentDB support), but adding it as a new feature request with different details and ideas.

## What?
Looking to get DocumentDB to work with Graylog looks to only require the option of not setting the "capped" feature against MongoDB. While I understand the benefits that having a capped collection provides, I'm sure there are valid use cases users to not have the collection capped.

The only change, from my preliminary understanding, is to add a configuration value `mongodb_col_capped = true/false` with it defaulting to "true" as most instances will not want this changed.

From what I have seen, the capped setting is the only thing that is preventing the usage of DocumentDB, but I could be wrong.

## Why?
With companies making the push to the cloud and pushing for leveraging SaaS solutions, even over marketplace applications and other managed EC2 services, being able to use DocumentDB would be greatly advantageous to moving to the cloud. 

We are already using the AWS Elasticsearch service (haven't moved to/tested OpenSearch) and are seeing phenomenal results with it.

It would be greatly preferred that AWS supported capped collections in DocumentDB, that's a request that's been in place for years with nothing to show for it.

## Your Environment
* Graylog Version: 4.0.5
* Elasticsearch Version: 7.9
* MongoDB Version: 4.2.11
* Operating System: RHEL 8
* Browser version: Firefox

**Comment by bernd** [comment]
@OneWithTheCore AWS DocumentDB is also missing support for GridFS, so we cannot support it now.

MongoDB Atlas could be an option if you are looking for a hosted MongoDB solution.

**Comment by OneWithTheCore** [comment]
Unfortunately my employer is very particular about how the cloud is leveraged and may take issue with MongoDB Atlas, but I appreciate you looking into this and providing an update on it.
