### ISSUE TITLE
Please take a look to gflog as replacement for log4j

### ISSUE THREAD

**Issue by eabykov** [Graylog2/graylog2-server#11796]
## What?

Could you try using gflog instead of log4j to increase logging performance 

- both gflog and log4j are configured in a similar way, so the transition will not be a big problem
- gflog also supports sending logs directly to Graylog
```xml
    <appender name="gelf" factory="deltix.gflog.appender.TcpAppenderFactory" host="graylog" port="12201">
        <layout factory="deltix.gflog.layout.GelfLayoutFactory">
            <additional-fields>
                <entry key="app" value="${app.name}"/>
            </additional-fields>
        </layout>
    </appender>
```

## Why?
Because gflog is a highly efficient garbage-free logging framework for Java 8+.
Here is a link to the comparison: https://github.com/epam/GFLog/wiki/Performance

## Your Environment

* Graylog Version: 4.2.3
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.2.17
* Operating System: Amazon Linux 2
* Browser version: Google Chrome 96.0.4664.93

**Comment by bernd** [comment]
@eabykov Thanks for the suggestion, but we will stay with log4j2 for now.
