### ISSUE TITLE
How to send cisco devices (switches/routers) logs to display on graylog console.

### ISSUE THREAD

**Issue by Rahul25814834** [Graylog2/graylog2-server#11811]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 4.2.3-1
* Java Version: java-1.8.0-openjdk-headless.x86_64
* Elasticsearch Version: 7.10.2-1
* MongoDB Version:  4.2.17-1.el7
* Operating System: Centos 7
* Browser version: Google Chrome Version 96.0.4664.93 (Official Build) (64-bit)

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
