### ISSUE TITLE
can anyone share the document for configuration of graylog and getting the log of network devices on graylog web.

### ISSUE THREAD

**Issue by Rahul25814834** [Graylog2/graylog2-server#11824]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
