### ISSUE TITLE
Unable to login to cluster after upgrade from v3.3.8 to v4.2.3

### ISSUE THREAD

**Issue by robotparty** [Graylog2/graylog2-server#11836]
When I upgrade one node of our Graylog cluster to the official docker container for v4.2.3, attempts to login with the local graylog admin account show a message `We are preparing Graylog for your use...` and then the login form is presented again after a few seconds. 

## Expected Behavior
I would be logged in and redirected to the search page as usual.

## Current Behavior
Attempts to login with the local graylog admin account show a message `We are preparing Graylog for your use...` and then the login form is presented again after a few seconds. 

## Possible Solution
 ¯\_ (ツ)_/¯ wish I knew...

## Steps to Reproduce (for bugs)
1. Run a 3 node cluster on `3.3.8+e223f85, codename Sloth Rocket` using the official graylog container
2. Upgrade a single container to 4.2.3
3. Attempt to log in.
4. If you shut down the 3.3.8 containers, leaving the 4.2.3 node up, the home page is blank.

## Context
Graylog is unusable after upgrade to v4.2.3

## Your Environment

* Graylog Version: Container 4.2.3: https://hub.docker.com/r/graylog/graylog
* Java Version: 
```
/usr/local/openjdk-8/bin/java -version
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```
* Elasticsearch Version: 6.8
* MongoDB Version: 3.4.20 (mongo containers)
* Operating System: Docker host = Amazon Linux 2 
* Browser version:  Chrome Version 96.0.4664.93 (Official Build) (x86_64)

**Comment by dennisoelkers** [comment]
Hey @robotparty,

thanks for reporting this! When you are trying to log in to your instance after upgrading it, is there any log output in your browser's JS console that you can share with us?
