### ISSUE TITLE
Include node name on the 'Oops, an error occured' error page

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1184]
When you're faced with the 'Oops, an error occured' exception page it would be very beneficial to include the node name on which the exception occurred ... otherwise you need to check the logs on all nodes behind your load balancer (yes, this one falls in the category of nice-to-have but still ... )

**Comment by bernd** [comment]
I believe this is not an issue anymore since Graylog 2.0. Closing this now.
