### ISSUE TITLE
Problem with 'Quick values' on common field names in streams (1.1-beta1)

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1185]
When using the quick values feature for a common field name such as 'source' the breakdown includes a global view of the 'source' field - ie. the result is not limited to the stream you are operating in ....

I am not sure if this is related to #1169 and thus already fixed?

**Comment by kroepke** [comment]
Looks like it, yes. Will double check before the next beta.

**Comment by henrikjohansen** [comment]
I can no longer reproduce after upgrading to 1.1-beta3 ... closing this issue.
