### ISSUE TITLE
Pipeline Rule Function substring() utilizes Keyword "end"

### ISSUE THREAD

**Issue by tbenu** [Graylog2/graylog2-server#11868]
When creating a pipeline rule, using the substring() function, there is no way to explicitely state the parameter names (i.e. value:, start:, end:) when using an value for end. The "end:" is interpreted in the same way as the "end" finishing the rule (including syntax highlighting), which leads to the rule no longer be saveable (without any error indicator, which led to some confusion on my side).

## Expected Behavior
Pipeline rules utilizing substring() while explicitely stating parameter names should be working.

## Current Behavior
When using substring() with explicit stating of parameter names including "end:", the rule can no longer be saved, without any error indication. There also is no syntax error shown when using the function this way. Only the syntax highlighting gives a hint to the problem.

## Possible Solution
Rename the "end:" parameter to something else which is not a reserved keyword. Alternatively: change the behavior of the pipeline rule editor to not fail due to usage of explicit parameter names.

## Steps to Reproduce (for bugs)
1. create a new pipeline rule
2. use the substring() function with all parameters explicitely stated
`let result = substring(value:"some text here", start:3, end:5);`
3. try to save the rule

## Context
This problem occured while creating a lengthy text manipulation rule with multiple usages of the substring() function, while still keeping up the readability (by explicitely stating parameter names). Although not using parameter names fixes the problem, this does not help keeping the rule readable and understandable.

## Your Environment
* Graylog Version: 4.2.4+b643d2b

**Comment by mpfz0r** [comment]
The simple fix for this is that we change the function parameter name to something else than `end`.

@kodjo-anipah did that already for the `substring` function. The other one we need to fix is `join`
