### ISSUE TITLE
Not splitting values of fields when using Quick values

### ISSUE THREAD

**Issue by elej** [Graylog2/graylog2-server#1188]
When we have for instance field Message which contains values:
"Session: start"
"Session: end"
"Application: start"
"Application: end"

And then we want to analyse the number of occurrences of ends of session we cant get it using Quick values. Because it split messages into session, application, start and end.

Or mayby there are any reasons for doing this that way?

**Comment by kroepke** [comment]
Quick values only work on "terms" and the standard way of analyzing incoming data will split on whitespace and strip out punctuation.

We will see if we can support this in a future version, I'll leave it open for now.

**Comment by hc4** [comment]
You can extract this values to another field and set "index":  "not_analyzed" mapping for that field.
How to setup mapping read [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html)

Also you can use [multi-field](https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html) feature of ES, I you need both analyzed and not analyzed access to same field. But it is not fully supported by graylog (you'll need to manualy modify query for charts)

**Comment by danielo515** [comment]
I'm also affected by this issue. It will be very useful to configure which terms should be included

**Comment by joschi** [comment]
@danielo515 You have to use another analyzer (or tokenizer) for the relevant message fields.

See these links for details:

* https://www.elastic.co/guide/en/elasticsearch/reference/2.4/analysis-analyzers.html
* https://www.elastic.co/guide/en/elasticsearch/reference/2.4/analysis-tokenizers.html
* http://docs.graylog.org/en/2.1/pages/configuration/elasticsearch.html#custom-index-mappings

**Comment by jalogisch** [comment]
this can be solved with a pipeline.
