### ISSUE TITLE
Grok extractors not working

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1192]
Reported on the mailing list. See following link for details: https://groups.google.com/forum/#!topic/graylog2/8OsBpvnHeyU

**Comment by kroepke** [comment]
This works as expected in 1.1.0-RC.1.

**Comment by kroepke** [comment]
Let's test it on 1.0.2 (the version it was originally reported against), but from the patterns and input there's no indication why it shouldn't work there as well.

**Comment by bernd** [comment]
The issue from the mailing list post was a wrong timestamp in the messages so the messages showed up later. The grok extractor was working just fine.
