### ISSUE TITLE
Support for flexible alert rule conditions

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1193]
I would like to be able to combine the 3 different alert conditions using flexible AND / OR rules.

The use case for us would be to get alerts when x number of messages (Message Count) matching "Field value condition" and / or matching a "Field content condition" ie. :

Alert me when there are more than 10 messages with the 'severity' field set to critical or when more than 20 messages have a std_deviation value of the 'response_time' field higher than x.

**Comment by zexxon** [comment]
I've copied your feature request over to our ideas portal: https://graylog.ideas.aha.io/ideas/GL2E-I-385
