### ISSUE TITLE
Serializing org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress causes infinite call stack recursion

### ISSUE THREAD

**Issue by jrunu** [Graylog2/graylog2-server#11932]
Having a message field with a org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress as type, causes a infinite call stack recursion that locks up the graylog.  This happens during the serialization to json in the es output batching. 

## Expected Behavior
Serialize the fields vontent into a string with dotted-decimal-notation.

## Current Behavior
Locks up the processing.

## Steps to Reproduce (for bugs)

1. Create a rule with folliwing content
```
rule "ipz4days"
when
  true
then
  set_field("ipz4days",to_ip("3.13.31.214"));
end
```
2. Insert into a pipline attached to all mesages
3. Ingest logs

## Context

The actual exception:
`2022-01-10T15:35:41.587Z ERROR [Messages] Caught exception during bulk indexing: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]->org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]->org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]->org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]->org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]->org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]->org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]->org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]->org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]->
[... ommited about 10k characters]
org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]->org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]->org.graylog.plugins.pipelineprocessor.functions.ips.IpAddress["anonymized"]), retrying (attempt #13).`

Please note that the "anonymized" is from the actual log, it was not replaced by us.

This Works as expect:
```
rule "ipz4days"
when
  true
then
  set_field("ipz4days",to_string(to_ip("3.13.31.214")));
end
```

## Your Environment
* Graylog Version: Graylog 4.2.4+b643d2b

**Comment by bernd** [comment]
@jrunu This has been fixed and released in 4.2.5. (https://github.com/Graylog2/graylog2-server/pull/11847)
