### ISSUE TITLE
Validate field value types while writing a search query.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#11973]
## Description

With https://github.com/Graylog2/graylog2-server/pull/11534 we are now validating the search query.

We can extend the validation logic by validating field value types as well. For example we can validate when a user defines a:
- float for a field with type long
- wrong decimal separator
- string for e.g. a field with type long
- invalid timestamp for field with type date

**Comment by todvora** [comment]
Implemented in https://github.com/Graylog2/graylog2-server/pull/12088
