### ISSUE TITLE
Significant Outward Processing Performance Drop with 1.1-rc1 Upgrade

### ISSUE THREAD

**Issue by packs** [Graylog2/graylog2-server#1197]
Last night I upgraded from `graylog-server-1.0.2` to `graylog-server-1.1-rc1` using the Graylog repositories. Immediately following the upgrade my graylog-server instance started having backlog issues writing to ElasticSearch. Prior to the upgrade this server would peak out at writing outbound messages at approximately 8000-10,000 per second. After upgrading the maximum rate that I have observed is closer to 800-1000, with 400-500 being typical. As of this writing I have a resultant backlog of approximately 19 million messages.

 | |
------------ | -------------
OS | Ubuntu Server 14.04.2 LTS 
CPU | 8 vCPU at 2.6GHz 
RAM | 16GB (8GB assigned to GL)
Graylog-Server Package | graylog-server 1.1.0-4.rc.1 
Java | IcedTea 1.7.0_79

**Comment by kroepke** [comment]
We at least need to document this.
It's unlikely that we find a fix, but should advise people to upgrade ES  to 1.5 in their clusters.

**Comment by joschi** [comment]
@kroepke Do you think the ES 1.5.x client in Graylog would perform better with an ES 1.5.x cluster?

**Comment by packs** [comment]
Following Henrik's advice I updated my ES cluster to 1.5. That seemed to solve my low performance issues. If this is truly a pure ES client/server version issue can we get the ES client version used by Graylog in the release notes or in the install/upgrade portion of the docs?

For posterity's sake the system metrics as requested by @joschi are in https://gist.github.com/packs/71ac09ae77cb7e346ed8

**Comment by bernd** [comment]
Documentation has been updated, closing this now.
