### ISSUE TITLE
Different result from parameter set

### ISSUE THREAD

**Issue by Nurfarahin23** [Graylog2/graylog2-server#11984]
## Expected Behavior

The api result should load based on parameter timerange set.

## Current Behavior

The api result not load based on parameter timerange set.

![image](https://user-images.githubusercontent.com/80515780/150061907-37f91e91-ef76-4b30-bab3-e091af9f7fd7.png)

## Steps to Reproduce (for bugs)

Click System/Nodes --> Cluster Global API browser --> Legacy/Search/Absolute : Message search -->GET /search/universal/absolute (Response Content Type text/csv) --> Fill the parameter

## Your Environment

* Graylog Version: 4.0.15
* Java Version: java-1.8.0-openjdk-headless.x86_64
* Elasticsearch Version: elasticsearch-oss-6.8.14-1.noarch
* MongoDB Version: 4.0.7-1.el7.x86_64
* Operating System: Red Hat, Inc. 1.8.0_312 on Linux 3.10.0-1160.6.1.el7.x86_64

**Comment by dennisoelkers** [comment]
Hey @Nurfarahin23,

thanks for reporting this! Unfortunately your Graylog version is rather old. Can you try with the most recent one and see if the error still exists?

**Comment by Nurfarahin23** [comment]
> Hey @Nurfarahin23,
> 
> thanks for reporting this! Unfortunately your Graylog version is rather old. Can you try with the most recent one and see if the error still exists?

Hey @dennisoelkers ,

4.0.15 is latest release for version 4.0 which on 16 December 2021. You refer most recent one so means we need to install 4.2 ?

**Comment by bernd** [comment]
> > Hey @Nurfarahin23,
> > thanks for reporting this! Unfortunately your Graylog version is rather old. Can you try with the most recent one and see if the error still exists?
> 
> Hey @dennisoelkers ,
> 
> 4.0.15 is latest release for version 4.0 which on 16 December 2021. You refer most recent one so means we need to install 4.2 ?

Yes. Version 4.0 is EOL. We only released 4.0.15 because of the log4j security issue. Please update to the latest 4.2 release. Thank you!

**Comment by Nurfarahin23** [comment]
> > > Hey @Nurfarahin23,
> > > thanks for reporting this! Unfortunately your Graylog version is rather old. Can you try with the most recent one and see if the error still exists?
> > 
> > 
> > Hey @dennisoelkers ,
> > 4.0.15 is latest release for version 4.0 which on 16 December 2021. You refer most recent one so means we need to install 4.2 ?
> 
> Yes. Version 4.0 is EOL. We only released 4.0.15 because of the log4j security issue. Please update to the latest 4.2 release. Thank you!

Hi @bernd @dennisoelkers ,

We already upgrade to 4.2.6 but still face the same problem

![image](https://user-images.githubusercontent.com/80515780/152280796-88a834d7-4934-4215-98bf-9c31b1d88ec0.png)

![image](https://user-images.githubusercontent.com/80515780/152280891-9af7f769-7978-497c-bccc-de49113a6f49.png)

**Comment by Nurfarahin23** [comment]
Got other problem too when using **Legacy/Search/Absolute (application/json)**

![image](https://user-images.githubusercontent.com/80515780/152306515-75fe8f73-84c6-4c12-96ee-4ba732eefb48.png)

**Comment by luk-kaminski** [comment]
Hi @Nurfarahin23,
Have you tried recalculating your index range, as mentioned in the "details" part of response body?
It's under System->Indices->pick [Your index set]->Maintenance.

**Comment by Nurfarahin23** [comment]
> Hi @Nurfarahin23, Have you tried recalculating your index range, as mentioned in the "details" part of response body? It's under System->Indices->pick [Your index set]->Maintenance.

Hi @luk-kaminski,
Already do as you suggest but not working. But finally able to solve after run `db.index_ranges.drop()` based on https://community.graylog.org/t/could-not-execute-search-index-not-found-for-query/11344/5. Thank you.
