### ISSUE TITLE
Throughput calculation wrong by factor 2x on /system/nodes ?

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1199]
This one is weird ... the throughput calculation jumps to 2x the value when navigating to /system/nodes?

Screenshot from our test cluster ... the upper topmenu is from /search .. the lower is from /system/nodes (using overlaying windows) :

![screen shot 2015-06-01 at 13 02 13](https://cloud.githubusercontent.com/assets/1473308/7911531/2f2569b2-085f-11e5-9459-4e82cdaad0af.png)

**Comment by kroepke** [comment]
Thanks, will take a look!

**Comment by henrikjohansen** [comment]
I checked all other pages btw - /system/nodes is the only place where this happens ....

**Comment by kroepke** [comment]
Will be in the next RC. Thanks for the update, that helped a lot :)

**Comment by dennisoelkers** [comment]
Is this issue solved? If yes, can it be closed?

**Comment by kroepke** [comment]
It hasn't been merged into master yet, that's why the ticket is still open.
