### ISSUE TITLE
Index selection for relative searches uses an ancient index ?

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#1200]
Poking around our test cluster I found something odd when searching for messages in the last 5,15 and 30 minutes :

Indices used for this search:
graylog2_820
graylog2_821
graylog2_118

graylog2_118 is ancient :

![screen shot 2015-06-01 at 14 01 28](https://cloud.githubusercontent.com/assets/1473308/7912358/f9292d1e-0866-11e5-8eb2-ef056bd7ea6a.png)

**Comment by kroepke** [comment]
@henrikjohansen could you attach the content of the ```index_ranges``` mongodb collection, please?

e.g. with ```mongoexport -d graylog2 -c index_ranges```

Thanks!

**Comment by henrikjohansen** [comment]
@kroepke sorry for the delay ... I've been swamped :(

The mongo data is here : 

https://gist.github.com/henrikjohansen/a3cdb138fa04eb534175

**Comment by kroepke** [comment]
Thanks!

That data validates our suspicion. That index contains a message with a future date (in your case it's 2015-12-31 23:59) and the index selection currently does not limit the upper bound of indices it looks into.

There's an issue for this in the web interface repo: https://github.com/Graylog2/graylog2-web-interface/issues/1238
We will be looking to resolve that in an upcoming bug fix release.

**Comment by kroepke** [comment]
I'll leave this one open until we've fix the linked issue.

**Comment by zexxon** [comment]
Please see the linked issue: #1208
