### ISSUE TITLE
build jar files for web interface

### ISSUE THREAD

**Issue by srf68** [Graylog2/graylog2-server#1201]
Hi
I clone the web interface from the github and then apply my needed changes to its java, JAVASCRIPT and CSS files. Now I want to build the graylog-web-interface.graylog-web-interface-version.jar and graylog-web-interface.graylog-web-interface-version-assets.jar files to replace them in lib directory of web interface project to run and test my changes.
The question is how can build that jar files with IntellijIDEA or any other way?

**Comment by kroepke** [comment]
Please refer to https://github.com/Graylog2/graylog2-web-interface for a guide on how to build the web interface project.

**Comment by srf68** [comment]
Thanks, I did all steps and any thing was done successfully, but I cannot find any jar file there. Where should I search for jar files. In fact I think that the steps run another server and a new instance of web interface, but this is not good for me. I want to compile my code and build new jar files then replace new jar files with old files in my current web interface project.

**Comment by joschi** [comment]
After running `sbt build` (or `activator build`) you will find the build result in the `target` directory.

I'm locking this issue now. If you have any questions, please use the [mailing list](https://groups.google.com/forum/?hl=en#!forum/graylog2) or the [IRC channel on Freenode](https://webchat.freenode.net/?channels=%23graylog).
