### ISSUE TITLE
Graylog Input kafka with ssl not work

### ISSUE THREAD

**Issue by ly123-liu** [Graylog2/graylog2-server#12024]
graylog version: use docker image (graylog:4.2.5-jdk8)
mongo: 5.0.3
elasticsearch: 7.10.1

we use graylog collect log from kafka, kafka is build with ssl 

1) login to graylog
2) choose kafka raw input
3) set properties and add custom properties:
custom_properties:
ssl.keystore.location=/usr/share/graylog/data/config/certs/ying99_prome_exporter.keystore.jks
ssl.keystore.password=xxx
ssl.key.password=xxx
ssl.truststore.location=/usr/share/graylog/data/config/certs/ying99_prome_exporter.truststore.jks
ssl.truststore.password=xxx
security.protocol=ssl

when we start this inputs, inputs show running, but graylog log shows error:
2022-01-24 02:53:14,832 WARN : org.graylog.shaded.kafka09.utils.VerifiableProperties - Property security.protocol is not valid
2022-01-24 02:53:14,832 WARN : org.graylog.shaded.kafka09.utils.VerifiableProperties - Property ssl.key.password is not valid
2022-01-24 02:53:14,832 WARN : org.graylog.shaded.kafka09.utils.VerifiableProperties - Property ssl.keystore.location is not valid
2022-01-24 02:53:14,832 WARN : org.graylog.shaded.kafka09.utils.VerifiableProperties - Property ssl.keystore.password is not valid
2022-01-24 02:53:14,832 WARN : org.graylog.shaded.kafka09.utils.VerifiableProperties - Property ssl.truststore.location is not valid
2022-01-24 02:53:14,832 WARN : org.graylog.shaded.kafka09.utils.VerifiableProperties - Property ssl.truststore.password is not valid

kafka consumer groups show nothings ,seems graylog is not collectlly connect to kafka , is there error in my config ? can someone help me ? thanks 

inputs config:
bootstrap_server: k8s-dqnew-d01.int.frontnode.net:9092,k8s-dqnew-e01.int.frontnode.net:9092
custom_properties: ssl.keystore.location=/usr/share/graylog/data/config/certs/ying99_prome_exporter.keystore.jks
ssl.keystore.password=xxx
ssl.key.password=xxx
ssl.truststore.location=/usr/share/graylog/data/config/certs/ying99_prome_exporter.truststore.jks
ssl.truststore.password=xxx
security.protocol=ssl
fetch_min_bytes: 5
fetch_wait_max: 100
group_id: infra-log-dev-prome-exporter-test
legacy_mode: true
offset_reset: smallest
override_source: <empty>
threads: 2
throttling_allowed: true
topic_filter: ^infra-log$
zookeeper: k8s-dqnew-d01.int.frontnode.net:32181

**Comment by mpfz0r** [comment]
@ly123-liu it looks like you're using `Legacy mode` which doesn't support TLS and has other problems

**Comment by bernd** [comment]
@ly123-liu Can you please try to disable the "Legacy mode" checkbox, as @mpfz0r mentioned? Thank you!

![image](https://user-images.githubusercontent.com/461/151162704-76cb6851-dfab-4d96-b945-c2b23c5c0028.png)

**Comment by ly123-liu** [comment]
yes，we close legacy mode， and works fine，graylog search from es，but es index rate is not that quik ,can graylog search from its own log files  those stored in journal director ？

**Comment by bernd** [comment]
@ly123-liu Thanks for the feedback!

Graylog cannot search in its own log files by default. But you could configure a log shipper to ingest the logs.
