### ISSUE TITLE
GET /api/sidecars/all requires admin privileges. Should it ?

### ISSUE THREAD

**Issue by filviu** [Graylog2/graylog2-server#12044]
I'm building an internal dashboard and need data reported by `/api/sidecars/all` Naturally I wanted to use a user with minimal permisions for this API endpoint. By trial and error (couldn't find a definitive list of roles and privileges required by api endpoints) I realised that only the "Admin" role grants enough permisions to read this endpoint.

## Expected Behavior

I expected that the reader role should be enough to do `GET` on `/api/sidecars/all` The next obvious (to me) role to try was "Sidecar System (Internal)" but again no luck. I added roles one by one and retried but the only role that granted me access was "admin"

## Current Behavior

I get 
```json
{
  "type": "ApiError",
  "message": "Not authorized"
}
```
with any available role other then "Admin" indiferent if I use a token or user/pass authentication.

## Possible Solution

- add a "sidecar reader" role
- grant the "Sidecar System (Internal)" role permisions to this endpoint

## Steps to Reproduce (for bugs)

1. Create a user. Assign all the roles but admin - including the one you would expect to work: Sidecar System (Internal)
2. Use that user to GET `/api/sidecars/all`
3. Fail

## Context

I'm a strong believer in using the minimum required permissions to accomplish a task. In case of dashboards, status and monitoring I always want "reader users" i.e. users that can get data and status but can't perform changes. Currently having  admin credentials sitting on the dashboard system is not ideal. 

## Your Environment

* Graylog Version: 4.2.5+59802bf (official docker)
* Java Version:  1.8.0_312
* Elasticsearch Version: 7.10.2 (official docker)
* MongoDB Version: latest 4.2 (official docker)
* Operating System: official docker image
* Browser version: Firefox 96.0.2

**Comment by bernd** [comment]
Location of the "Sidecar System (internal)" role: https://github.com/Graylog2/graylog2-server/blob/3cb826f2231906ebaf0c967be90291fa0092151e/graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180323150000_AddSidecarUser.java

Link to the resource: https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java#L122
