### ISSUE TITLE
Fix Issue with V20211221144300_GeoIpResolverConfigMigration

### ISSUE THREAD

**Issue by roberto-graylog** [Graylog2/graylog2-server#12060]
## Expected Behavior
IF the field **db_vendor_type** is MAXMIND_CITY (old value), it should be updated to MAXMIND; otherwise, no change should be made.

## Current Behavior
The field **db_vendor_type** is updated to MAXMIND on every execution--writing over any user supplied value.

## Possible Solution
Update the migration to include a filter for the field value before updating.

## Steps to Reproduce (for bugs)

1. Update the **Geo-Location Processor** configruation to **IPInfo** vendor type.
2. Restart the server and revisit the configuration--the vendor type will be MaxMind

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by kingzacko1** [comment]
Looks like this issue was already taken care of. Closing.
