### ISSUE TITLE
format_date() pipeline function starts to output wrong results today

### ISSUE THREAD

**Issue by Elix-g** [Graylog2/graylog2-server#12072]
## Expected Behavior
Extract date and time from a timestamp field properly

## Current Behavior
Since today, format_date() outputs 32.02.2022 instead of 01.02.2022

## Steps to Reproduce (for bugs)
run the following rule against a field which contains a timestamp like "2022-02-01 10:37:47.000"

```
rule "Generic split timestamp"

when
    has_field("timestamp")
then
    let tstamp = to_date($message.timestamp);
    let map = {
        Date: to_string(format_date(tstamp, "DD.MM.YYYY")),
        Time: to_string(format_date(tstamp, "HH:mm:ss", "+01:00"))
    };
    set_fields(map);
end
```

## Your Environment

* Graylog Version: Graylog 4.2.5+59802bf
* Java Version: 1.8.0_312

**Comment by bernd** [comment]
@Elix-g The `DD` pattern is the day of the **year** and not the day of the month. Using `dd` will format the day of the month.

See: https://www.joda.org/joda-time/key_format.html
