### ISSUE TITLE
the data is not sent in a graylog output

### ISSUE THREAD

**Issue by dcantos1** [Graylog2/graylog2-server#12078]
Configure a graylog output to send the logs to an external server, first configure it to send in GELF graylog format, but I don't have traffic in the external server's TCPDUMP, I don't have anything blocked, it's a local network and the external server does. works with other local fonts without problems.
![imagen](https://user-images.githubusercontent.com/80493416/152034666-b978ae2f-f8fe-415c-8e85-43caed00ed2e.png)

![imagen](https://user-images.githubusercontent.com/80493416/152034720-49f51103-747b-4ddc-ac98-b86b8bdae83c.png)

![imagen](https://user-images.githubusercontent.com/80493416/152034806-69e02c63-b765-4064-92cc-4e7a4bb61e93.png)

Additionally, I integrated a plugin to transform the output to syslog but with the same result, the output does not work, can you help me.

* Graylog Version: 4.2.5
* Java Version: 
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
