### ISSUE TITLE
Blacklist improvement

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#121]
As I already mentioned in the google group the blacklist in v0.10.0 doesn't seem to work for me.

I record apache access and error logs in graylog2. We have nagios and collectd running and doing some performance checks. In order to supress these messages I have a blacklist like this:

.*collectd/5.1.0.git.*
.*GET /server-status?auto HTTP/1.1 200.*

It would be great to have some advanced blacklisting like

http_useragent ~ collectd
http_response_code != 200

and

http_request ~ "/server-status.*"
http_response_code != 200

So the blacklist should look like the message stream feature just for dropping messages.

**Comment by runningman84** [comment]
any news here?

**Comment by bernd** [comment]
This can be done using the blacklist feature in Graylog 1.1. You have to use the API directly because there is no UI yet. (on our roadmap) Closing this issue.
