### ISSUE TITLE
Improvements for query validation logic

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#12128]
## Description
We recently started validating the defined search query. There are some cases where the validation is not returning the expected result:

- _exists_
  - Example query: `_exists_:field_name`
  - Result: unknown field `_exists_` warning
- Unknown field in combination with (x OR y)
  - Example query: `unknown_field:(x OR y)`
  - Result: ApiError
- Unknown field and exact match which includes a space
  - Example query: `unknown_field:"x y"`
  - Result: ApiError
- Unknown field and escaped characters
  - Example query: `unknown_field:\/posts\/45326`
  - Result ApiError
- regular expression
  - Example query: `/ethernet[0-9]+/`
  - Result: unknown field warning for field _default_

**Comment by todvora** [comment]
All of the issues fixed in the #12130 PR, thanks for the example queries. It was easy to convert them into tests and fix afterwards!
