### ISSUE TITLE
Upgrade from 1.02 to 1.1 - lost all callback settings

### ISSUE THREAD

**Issue by zidvbelju** [Graylog2/graylog2-server#1214]
Hey Team, 

Just upgraded to 1.1 from 1.02. Lost all callback settings across all streams. Not sure if this is a bug, but I figure it's worth opening an issue about. Will update later with more info, on the road right now.

**Comment by zidvbelju** [comment]
Quick update - nothing strange in the logs from  the initial startup after the upgrade, other than graylog complaining about using a deprecated  mongodb conf call (which is now corrected on my end). 

I have confirmed that all callbacks were missing, not just email (I use email and slack callbacks). 

The callback receivers and alert configuration were still there, only thing missing was the actual callbacks themselves.

If you need more information, let me know. I've seen recreated all of the callback settings and everything is back to normal.

**Comment by bernd** [comment]
Thank you for the report! We found the issue and will provide a fix ASAP.

The problem is that the MongoDB collection name for alarmcallback configurations was called `alarmcallbackconfigurations` in 1.0 and got renamed to `alarmcallbackconfiguration` (missing `s`) by accident in 1.1.
