### ISSUE TITLE
Graylog can not show event Definitions on web

### ISSUE THREAD

**Issue by ducna96** [Graylog2/graylog2-server#12156]
1. Describe your incident:
i just run command " sudo -u graylog echo ‘db.scheduler_triggers.remove({})’ | mongo graylog " to remove scheduler_triggers on mongodb , but afer I run command , on graylog web i can not create new event definitions, how can i do to fix that?

Logs: ERROR [AnyExceptionClassMapper] Unhandled exception in REST resource
java.lang.NullPointerException: null

2. Describe your environment:
OS Information: ubuntu 18.04
Package Version: Graylog 4.2.6+0210617

Thanks
1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
