### ISSUE TITLE
Visualization mode help is not displayed

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#12166]
When editing a widget the "Visualization" section has a "?" icon for the "Mode" option. Hovering or clicking on the icon has no effect.

https://user-images.githubusercontent.com/461/154735479-fb5dea09-066d-4af2-a936-58c18af7a222.mp4

I suppose it should show some information about the different mode options.

## Steps to Reproduce (for bugs)

1. Edit a widget
2. Hover or click the "?" icon next to "Mode" in the "Visualization" section

## Your Environment

* Graylog Version: 4.3.0-SNAPSHOT (rev 7aee4be)

**Comment by linuspahl** [comment]
This will be fixed with https://github.com/Graylog2/graylog2-server/pull/12150
