### ISSUE TITLE
Using "Add to query" field option opens value suggestion

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#12165]
When using the "Add to query" field option to modify the query, an overlay with a field value suggestion pops up. It stays in a fixed position when scrolling and only disappears when clicking into the search bar.

Example:

https://user-images.githubusercontent.com/461/154734773-1bbfa5fe-ce13-4bc2-bfae-d448c252c60f.mp4

## Steps to Reproduce (for bugs)

1. Open message details
2. Select "Add to query" on a message field value
3. Wait and observe the value suggestion popping up

## Your Environment

* Graylog Version: 4.3.0-SNAPSHOT (rev 7aee4be)

**Comment by linuspahl** [comment]
I am reopening this issue because this problem still exists when the query is empty.

**Comment by coffee-squirrel** [comment]
I overlooked this and opened #15664 last week.  Copying some of that content:

> Selecting `Add to query` results in the search query being updated appropriately, however it also triggers field value suggestions for the associated field (not restricted by the value that was just added) if the input cursor is at the start of the search query.  This does not occur if the cursor is not at the start of the search query.
> 
> ![image](https://github.com/Graylog2/graylog2-server/assets/19417721/ee59c5c0-2e70-45fc-a8a4-4857a097ea78)
> 
> Additionally:
> * the suggestions pop-up can't be dismissed without focusing on the search query input
> * ~if the search query input is not fully in view (e.g. you're scrolled down to look at a message table) the suggestions pop-up will barely show up at the top of the window~ (only saw this once and haven't been able to reproduce since)

**Comment by drewmiranda-gl** [comment]
Absolutely incredible! thank y'all so much! I'm overjoyed.
