### ISSUE TITLE
contains() passing false positive when field not present on message

### ISSUE THREAD

**Issue by tellistone** [Graylog2/graylog2-server#12177]
## Expected Behavior
Encountered what appears to be a severe bug around the contains() function in the pipeline language.
The following rule:

rule "route to a stream"
when
contains("devel-posttrade", to_string($message.application_name))
or contains("qa-pt", to_string($message.application_name))
or contains("lts-pt", to_string($message.application_name))
or contains("stg-pt", to_string($message.application_name))
or contains("prod-pt ", to_string($message.application_name))
then
route_to_stream(NewStream);
end 

**Should** route messages to NewStream if any of the listed values match the content of $message.application_name

It should **not** route messages to NewStream where the message does not have the field $message.application_name

## Current Behavior
For the pipeline rule above, if the $message.application_name field is not present, the rule is routing messages to route_to_stream(NewStream). It should not be doing that.

This isn't specific to the $message.application_name field. You can change this to $message.nonsense_name and get the same effect.

It also doesn't prevent this to add an And clause.

Eg.

rule "route to a stream"
when
contains("devel-posttrade", to_string($message.application_name))
or contains("qa-pt", to_string($message.application_name))
or contains("lts-pt", to_string($message.application_name))
or contains("stg-pt", to_string($message.application_name))
or contains("prod-pt ", to_string($message.application_name))
and has_field($message.application_name)
then
route_to_stream(NewStream);
end 

This still triggers when field $message.application_name is missing.

It looks like contains() is returning a false positive if the field listed is not on the message.

## Steps to Reproduce (for bugs)

1. create new stream "Test"
2. attach the following pipeline to all messages 

rule "route to a stream"
when
contains("string, to_string($message.nonsense_field))
and has_field("nonsense_field")
then
route_to_stream("Test");
end 

3. Observe messages landing in Test.

## Context

Discovered in HS-757049191
## Your Environment
Graylog 4.2.0

**Comment by bernd** [comment]
@tellistone This doesn't look like a bug but more like the wrong usage of the `contains()` function.

`contains("devel-posttrade", to_string($message.application_name))`

In words, this means: "Check if the string value of `application_name` is contained in `devel-posttrade`"

If the `application_name` field doesn't exist, `to_string()` returns an empty string. Checking if an empty string is contained in `devel-posttrade` returns true.

To fix this, the argument order needs to be reversed:

`contains(to_string($message.application_name), "devel-posttrade")`

In words: "Check if the `devel-posttrade` substring is contained in the string value of `application_name`"

Checking if `devel-posttrade` is contained in an empty string returns false.

See also the function documentation in the product for the correct argument order:

![image](https://user-images.githubusercontent.com/461/156188850-98b35409-6783-4357-ad55-80b82f47584f.png)
