### ISSUE TITLE
Can't log in with "sessions do not timeout" option

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#12220]
Can't log in if I configure the _sessions do not timeout_ option. When I re-activate the session timeouts again all is working as expected. 

![image]( https://user-images.githubusercontent.com/4102775/156360739-af9fc12a-1891-4051-a55c-af02111d3216.png)

## Expected Behavior
I should be able to log in and the session should be valid forever. 

## Current Behavior
Login is not possible

## Steps to Reproduce (for bugs)
1. Go to user administration
2. Check the session do not timeout checkbox 
3. Logout
4. Try to log-in again.

## Your Environment

* Graylog Version: Graylog 4.3.0-SNAPSHOT+01253df on server (Eclipse Adoptium 17.0.2 on Linux 5.11.0-1028-aws)

**Comment by linuspahl** [comment]
It looks like `valid_until` in the response of `/api/system/sessions` always equals the current date in this case.

**Comment by linuspahl** [comment]
We had another look and we were already returning the same value for `valid_until` with 4.2, because we set the value for the session timeout is `-1` in this case. Which means we probably changes the logic which is processing this information.

**Comment by todvora** [comment]
The never expiring session is not possible to reflect fully in cookie-based auth. Every cookie has to have a `maxAge` configured. We can fake the maxAge for "never expiring" session, but it will be rather a hack than real proper solution.
