### ISSUE TITLE
Mention IPinfo in addition to Maxmind

### ISSUE THREAD

**Issue by boosty** [Graylog2/graylog2-server#12237]
## Expected Behavior

Since we support IPinfo files for GeoIP lookups in addition to Maxmind, we should also mention this properly in the UI and the documentation.

## Current Behavior

Being able to use IPinfo files is mostly hidden. You will only find it when selecting Maxmind.

<img width="1793" alt="Screenshot 2022-03-07 at 11 22 52" src="https://user-images.githubusercontent.com/4270/157014153-f5cd4b85-5a78-4f8e-ac7d-0a46ef7fa35f.png">

<img width="897" alt="Screenshot 2022-03-07 at 11 23 26" src="https://user-images.githubusercontent.com/4270/157014161-43bd82a1-14c2-405d-b781-3ca1ab7ca840.png">

## Possible Solution

- Rename Data Adapter Type from `Geo IP - MaxMind™ Databases` to `Geo IP - MaxMind™ or IPinfo Databases`
- Rename form help text `The path to the Maxmind™ database file.` to `The path to the database file.`
- Rename form help text `If enabled, the MaxMind™ database file is checked for modifications and refreshed when it changed on disk.` to `If enabled, the database file is checked for modifications and refreshed when it changed on disk.`
- Update the docs at https://docs.graylog.org/docs/geolocation and https://docs.graylog.org/v1/docs/lookuptables (there might be more places)

## Context

- https://github.com/Graylog2/graylog2-server/pull/10183
- https://www.graylog.org/post/ipinfo-announces-partnership-with-graylog

**Comment by Devamparikh** [comment]
Hey, I'll like to make my first move towards open source contribution. So I want to work on issue which I can complete. That is what I think. Therefor selecting this issue to work on. 

I have few questions such as:

[1] The document in https://github.com/Graylog2/[documentation](https://github.com/Graylog2/documentation) says "This repository has been archived by the owner. It is now read-only." Will I be able to make changes to contribute?
[2] If yes, where can I find these documentation in Graylog2 forked repo?
[3] what files we must change in order to make a contribution?

Thanks for your time,
I'm grateful for any help and response of yours.
here to learn.

**Comment by boosty** [comment]
Hi @Devamparikh,

thanks for your message and the willingness to contribute 👍 

Unfortunately you cannot contribute to the documentation directly. Updates are centrally managed by @dulanism and his team. 

Therefore I think this issue is not a good candidate for external contributors.

Thanks,
Sebastian

**Comment by Devamparikh** [comment]
Hi @boosty 
Let me know if I understood you correctly.
This is open source project but only members of @dulanism can contribute.
To contribute to any open source project first we need to be team member of that project.!?
And also how can one be member of @dulanism's team or any other team like this.

**Comment by dulanism** [comment]
Hi @Devamparikh the team that writes docs for both Graylog open source and enterprise are employees. When we migrated docs to our new platform we ask our open source users to post issues in our community (See[ Documentation Campfire](https://community.graylog.org/c/documentation-campfire/30)). No need to duplicate this request in the community. We'll take care of it and let you know. However, going forward feel free to post in the aforementioned community. (Be sure it's properly tagged under Documentation Campfire, as you contribute to docs related content). Cheers!

**Comment by Gaya** [comment]
Updated the text in the application here: https://github.com/Graylog2/graylog2-server/pull/12466
Someone should update the documentation though.

**Comment by boosty** [comment]
Hi @annie-zempel,

as Dulani has left, could you or someone from your team take care of changing the docs accordingly?
