### ISSUE TITLE
Create Index Set page randomly selects rotation strategy

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#12246]
Every time I open the _Create Index Set_ page, the _Index Rotation Configuration_ gets randomly selected from provided 3 options. 
 
## Expected Behavior
One default strategy should be pre-selected.

## Current Behavior
Every time random strategy is selected

## Steps to Reproduce (for bugs)
1. Open the System -> Indices page
2. Click on the _Create Index Set_ button
3. Verify which rotation strategy is selected
4. Refresh the page and verify again what strategy is pre-selected now

## Your Environment

* Graylog Version: Graylog 4.3.0-SNAPSHOT+4d97241

**Comment by luk-kaminski** [comment]
Ok, I will try to add this change to the PR.
