### ISSUE TITLE
"timestamp" field in Enterprise Reports not respecting "root_timezone" in server.conf

### ISSUE THREAD

**Issue by jtbisaha** [Graylog2/graylog2-server#12251]
## Expected Behavior
"timestamp" field in PDF reports should respect the "root_timezone" in the config file like it does in the dashboard

## Current Behavior
"root_timezone" is respected in the dashboard, but when generating an enterprise report from the dashboard the timestamp field is in UTC

## Possible Solution
Make enterprise reports respect the "root_timezone" directive

## Steps to Reproduce (for bugs)
1. Set "root_timezone" to "America/New_York" in server.conf
2. Create a dashboard with a message table (timestamp will be in local time)
3. Create an enterprise report with the dashboard and send it (timestamp will be in UTC)

* Graylog Version: 4.2.6+0210617
* Java Version: openjdk 11.0.14
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.2.18
* Operating System: Debian 11 Buster
* Browser version: Chrome 9.0.4844.51

**Comment by janheise** [comment]
We discussed/decided that the `root_timezone` is not supposed to be used like that. The user's timezone is taking into consideration when creating a new report and we'll add an issue that the the frequency consideration maybe should also default to the user's timezone instead of UTC.
