### ISSUE TITLE
Creating stream: description required but not highlighted

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#12256]
When creating a new stream, the description is mandatory but that is neither mentioned nor highlighted. When pressing the save button, nothing happens. When manually removing `required` attribute, the save works.

![image](https://user-images.githubusercontent.com/4102775/157825334-51dfd528-ffcd-4f2e-ae17-f3cb77837e47.png)

## Expected Behavior
Either remove the required flag or adapt validation so it's telling what's wrong

## Steps to Reproduce (for bugs)

1. Go to streams page
2. Create new stream
3. Leave description blank
4. Try to save the stream

## Your Environment

* Graylog Version: Graylog 4.3.0-beta.1+a752232

**Comment by dennisoelkers** [comment]
I would be really happy if we could just make the description optional. It is bugging me for years now and I do not see a reason why it should be required at all.
