### ISSUE TITLE
Role:assign user interface out of sync

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#12259]
The user selector is out of sync with the underlying data structures sometimes:

![user_roles](https://user-images.githubusercontent.com/4102775/157854740-4e2d66b6-36a5-4609-bc83-566a69a5a83c.gif)

## Expected Behavior
After assigning users to the role, they should either disappear from the selector or should stay there and be available for repeated assigning.

## Current Behavior
The users stay in the selector but are not really recognized when I try to assign them again.

## Steps to Reproduce (for bugs)
1. Select an user from the dropdown
2. Assign the user to the role
3. Remove the user from the role
4. Try to assign the aleady selected user again

## Your Environment

* Graylog Version: Graylog 4.3.0-beta.1+a752232 on server
* Browser version:

**Comment by Gaya** [comment]
Fixed in: https://github.com/Graylog2/graylog2-server/pull/12293

**Comment by Gaya** [comment]
Fixed by: https://github.com/Graylog2/graylog2-server/pull/12297
