### ISSUE TITLE
Graylog 1.1.1 memory usage unstable with low throughput

### ISSUE THREAD

**Issue by LordMike** [Graylog2/graylog2-server#1225]
Hi,

I just booted up an instance of GL 1.1.1 (893e8e7) (Senatsbock) and put a few servers to send data. With a throughput of <20 messages/second (spikes at 40/sec every 2 minutes), GL seems to be very unstable in its memory usage.

When looking at the Nodes list, the memory usage bounces from 250 MB (low) to 550 MB (high), every 1-2 seconds. When it hits 500 MB, it immediately jumps down to 250 MB and then repeats the process.

I'm worried it may indicate some excessive Garbage collection or object instantiation - is this normal?

- Mike

**Comment by kroepke** [comment]
This is a normal behavior of Java's garbage collection.

Do you experience performance problems? If not, then this is not a bug :)

**Comment by LordMike** [comment]
None yet (although I only have the 10-40 messages/second).
Just worried as it indicates massive amounts of object instantiation.

A way to combat this is typically to use Object Pools so that objects aren't orphaned.. But I know more about this in C# than I do in Java, so I can't speculate on the performance/abilities of it.

Good product though :).
