### ISSUE TITLE
Delete team without enterprise license fails

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#12258]
It's not possible to edit a team without an enterprise license. The edit button is not present. Unlike a delete button, which is there, is active and may be triggered. But the actual delete fails anyway with an error displayed in the overlay:

![image](https://user-images.githubusercontent.com/4102775/157854071-d5bc13a4-3bd2-484e-8d4f-2f9f1006997a.png)

## Expected Behavior
Delete button shouldn't be visible or active.

## Current Behavior
The delete button is available even without a license but fails to work properly.

## Steps to Reproduce (for bugs)
1. Create a team with a valid enterprise license
2. Remove the license
3. Go to the teams page
4. Try to delete a team

## Your Environment

* Graylog Version: Graylog 4.3.0-beta.1+a752232 on server

**Comment by Gaya** [comment]
@boosty in the code it looks like the "delete" button wasn't hidden on invalid license deliberately. Is this something that should be disabled, or fixed in the backend?

**Comment by boosty** [comment]
@Gaya Thanks for looking into this. Are there any hints on why the delete button was not disabled?

I think it is strange to offer a button that does not work. So my gut feeling tells me to hide it, similar to the edit button.

Maybe @bernd or @kroepke know more?

**Comment by Gaya** [comment]
There is a PR for the change if you want the delete button hidden:

https://github.com/Graylog2/graylog-plugin-enterprise/pull/3320

**Comment by bernd** [comment]
@boosty I think this was an oversight. There are probably more buttons for teams that don't work with no valid Enterprise license.

**Comment by boosty** [comment]
@bernd Thanks! Yes, I can imagine 😉 

@Gaya Please go ahead with the PR 👍
