### ISSUE TITLE
Roles select on create user page is not being cleared after assigning roles.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#12265]
## Expected Behavior

Roles select on create user page (`/system/users/new`) should be cleared after assigning roles.

## Current Behavior

The selected roles are still part of the select input after assigning the roles.
![image](https://user-images.githubusercontent.com/46300478/157897683-3f824271-7359-4f5c-9ada-b9766fc702a3.png)
The same problem exists for the collaborator select in the "share entity" modal. Maybe the bug is related to the `Select` component.

## Steps to Reproduce (for bugs)

1. Go to `/system/users/new`
2. select roles
3. assign these roles

## Your Environment

* Graylog Version: 4.3 beta

**Comment by Gaya** [comment]
Fixed in: https://github.com/Graylog2/graylog2-server/pull/12293

**Comment by Gaya** [comment]
Fixed by: https://github.com/Graylog2/graylog2-server/pull/12297
