### ISSUE TITLE
It is not possible to filter the event definitions list by id.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#12266]
## Expected Behavior

The search syntax help of the event definitions filter mentions it should be possible to filter the list by id (`id:the-id`).

![image](https://user-images.githubusercontent.com/46300478/157900443-6a570780-b1d8-4184-a2e6-159720412b2e.png)

## Current Behavior

Currently this does not work and all event definitions will be returned, no matter what id a users searches for.

## Steps to Reproduce (for bugs)

1. go to `/alerts/definitions`
3. search for `id:anything` in the search input of the event definitions overview
4. it will return all event definitions

## Your Environment

* Graylog Version: 4.3

**Comment by patrickmann** [comment]
The bug description is not quite accurate. Search by Id does _not_ always return all events. It works fine, when a valid Id is specified. Given an invalid Id, the server encounters an error and the UI is not updated. So it may look like the search returned something, but it is really just whatever was already on the screen.

The fix addresses this by surfacing the error message. But there is no change to the actual search behavior.
