### ISSUE TITLE
natural language parser can't parse 100 as value

### ISSUE THREAD

**Issue by fadanner** [Graylog2/graylog2-server#1226]
Using the natural language parser keywords containing "100" aren't parsed correctly.
This is in rest-api and in the web-interface (even in the Preview text)

Example:
* last 99 days  : *Preview:2015-03-01 09:24:41 to 2015-06-08 09:24:41* **correct**
* last 100 days: *Preview:2015-06-08 10:00:00 to 2015-06-08 09:26:35* **bug**
* last 101 days: *Preview:2015-02-27 09:26:49 to 2015-06-08 09:26:49* **correct**

Same with 999, 1000 and 1001 days. or with minutes as keyword

**Comment by kroepke** [comment]
lgtm

**Comment by kroepke** [comment]
closed the wrong one…

**Comment by bernd** [comment]
Isn't this fixed by #1227?
