### ISSUE TITLE
Default Sidecar collector in configuration for stateless clients? – features request

### ISSUE THREAD

**Issue by vigo332** [Graylog2/graylog2-server#12279]
Hi, Developers,

New to Graylog.
I managed to get a cluster of 500 stateless CentOS 7 nodes installed with graylog-sidecar and filebeat. The feature I would like to have is a default sidecar collector when a new node joins, and persistent node-id:

Eg, when a node reboot, it will boot to the image, and start afresh, and it will rerun the graylog-sidecar -service install and get the new node-id. It will connect to the server, but with a new node-id, so I have to configure it to use the collector, it still shows two entries in the sidecar lists with new and old/inactive node-id, they should be merged. I have 500+ stateless clients, when they all reboot, they are all treated new(new node-id). 

So two functions needed:
A: retain the node-id when a node-id file is polluted or lost,
B: ability to set a default sidecar collector config on the server, so nodes will work after reimaging and retained the logs.

I checked around briefly, a close request is issue #10454 but don’t find a track of work immediately. Apologies if I missed it. But it is a year from the previous issue. 

Thanks,

2. Describe your environment:

OS Information: CentOS 7.9 3.10.0-1160.45.1.el7.x86_64

Package Version:
graylog -4.2-repository-1-4.noarch

graylog -server-4.2.6-1.noarch

filebeat -8.0.0-1.x86_64

graylog -sidecar-1.1.0-1.x86_64

graylog -sidecar-repository-1-2.noarch

Service logs, configurations, and environment variables:
NA
3. What steps have you already taken to try and solve the problem?
NA

4. How can the community help?
A: retain the node-id when a node-id file is polluted or lost,
B: ability to set a default sidecar collector config on the server, so nodes will work after reimaging and retained the logs.

**Comment by mpfz0r** [comment]
Hi, 

Graylog 5.0 and Sidecar 1.3 will have support for tagged assignments again.
https://github.com/Graylog2/graylog2-server/pull/13433

Regarding your stateless setup, you can also define the `node-id` yourself directly in the `sidecar.yml`.
It does not have to be a file (which is the default).
The only importance is that it is unique. So you could even use your hostname, for instance.

HTH
