### ISSUE TITLE
[proposed documentation] No documentation available for Natty (Natural Language Processor)

### ISSUE THREAD

**Issue by Sirclicksalot** [Graylog2/graylog2-server#12307]
The documentation at https://docs.graylog.org/docs/time-frame-selector references the site http://natty.joestelmach.com/ for documentation. This site has been reporting a 503 error for months now. In searching the web, I have been unable to find any mirrors of the docs.

**Comment by linuspahl** [comment]
Thanks for the hint! Until we find or provide a solution, the latest version in the Web Archive will may help you?
http://web-old.archive.org/web/20210613081734/http://natty.joestelmach.com/

**Comment by linuspahl** [comment]
I am closing this issue, because it is related to the documentation. For future suggestions for the documentation please use the [Documentation Campfire](https://community.graylog.org/c/documentation-campfire/30) in the community. Thanks!
