### ISSUE TITLE
Import Grok Pattern upload button does nothing 

### ISSUE THREAD

**Issue by ousmaneo** [Graylog2/graylog2-server#12314]
Selecting a file containing GROK patterns and clicking submit does nothing 
![grok](https://user-images.githubusercontent.com/1381455/158998379-8670f014-1d98-4ccd-89d0-42e11142a764.gif)

## Steps to Reproduce (for bugs)

1. Go to Grok Page 
2. Click on "Import Pattern file"
3. click "Upload"
4.

## Your Environment

* Graylog Version: 4.3-beta2

**Comment by thll** [comment]
My first thought was that this is related to https://github.com/Graylog2/graylog2-server/pull/12174. However, if I revert that PR, the button is still not functional.

**Comment by ousmaneo** [comment]
I did some tests and somehow the submit is not triggered with `formProps={{ onSubmit: this._onSubmit }}` and adding `onSubmitForm={this._onSubmit}` fixed it. I will provide a PR.
