### ISSUE TITLE
Cardinality in aggregation is wrong but sort on it is correct

### ISSUE THREAD

**Issue by ArnY** [Graylog2/graylog2-server#12313]
## Expected Behavior
When creating an aggregation (in my case, the list of IPs for each user) with a cardinality metric (on the IP field in my case)  I'm expecting the cardinality metric to be the number of IP each user used.

## Current Behavior
However the card(IP) metric is 1 no matter how many IPs there is. If I add a sort on the card(IP) metric the sort actually works as expected so while the displayed value is wrong, the metric is actually calculated correctly.

## Steps to Reproduce (for bugs)

1. add a new aggregation
2. add 2 field in the group (user and ip, in my case)
3. add a new metric using the cardinality function on the IP field
4. add a sort on the card(IP) metric, descending. The values are properly sorted on the cardinality while the card(IP) column is only filled with 1.

## Your Environment

* Graylog Version: 4.2.5
* Java Version: openjdk version "1.8.0_312"
* Elasticsearch Version: 6.8.15
* MongoDB Version: 4.0.27
* Operating System: debian 9.13
* Browser version: Firefox 98.0 on Linux

**Comment by janheise** [comment]
Hi @ArnY , I'm looking into this. I tried to reproduce your use case, but was unable to do so.  Can you please be more specific on how to reproduce this?
- what type of input are you using?
- maybe a screenshot of the aggregation-configuration?
- can you reproduce it with e.g. the "Random HTTP Input"?
thx

**Comment by ArnY** [comment]
Hello,

I'd like to apologize for forgetting about this issue. 

I'm using a simple syslog input. I'm attaching a screenshot: 
![Screenshot from 2023-01-02 17-30-12](https://user-images.githubusercontent.com/138363/210258334-a647666e-60a9-444c-ba06-62236a9f9812.png)

As you can see, even though the card(username) column is always 1, the actual ordering works (first ip has 5 usernames, second ip has 3, third ip has 2, etc.). I was expected the card(username) to match the number of username per ip and to be only listed once, on the ip line... 

Thanks,

**Comment by janheise** [comment]
Hi @ArnY! sorry for the delay, I didn't realise this ticket got reopened. In the beginning, your question was about cardinality on the IP - in your comment with the screenshot, you do it on the username. Can you please clarify?
IMHO - you just have to remove the username in the group by. Also, there are now two ways to specify the group by. see my attached screenshot for an example.
<img width="1203" alt="Screenshot 2023-06-29 at 15 39 11" src="https://github.com/Graylog2/graylog2-server/assets/1190735/9991c9bd-d024-458e-89e4-4586d17dce15">
