### ISSUE TITLE
Can't load system/enterprise page for non-admin user

### ISSUE THREAD

**Issue by maxiadlovskii** [Graylog2/graylog2-server#12330]
## Current Behavior
When non-admin users try to load the `system/enterprise` page there is an error page appears. And there is no way to add an enterprise license 

https://user-images.githubusercontent.com/10741557/159268455-aee80571-c4f4-494e-942d-8ea4d02562b4.mp4

## Steps to Reproduce (for bugs)

1. Loggin as a non-admin user. F.e. with dashboard creator role.
2. In chrome dev tools turn on Slow 3G network 
3. Go to `system/enterprise`  
4. You will see how the page loaded but then error page appear
5. There is no way to add enterprise license 

* Graylog Version: 4.3.0-beta

**Comment by thll** [comment]
@maxiadlovskii: good find!
I can reproduce this and also found out that we once had this fixed but it got broken again. Applying the same fix again does the trick.
