### ISSUE TITLE
Create QA plugin

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#1234]
As discussed with Kay, it would make sense having a QA plugin that helps testing the frontend with all the possibilities that may be found.

**Comment by joschi** [comment]
What would such a plugin do specifically?

**Comment by edmundoa** [comment]
Nothing special, just having an input, output and a callback with different input types would be enough I think. I was just looking for an output plugin with a password on it, but couldn't find any. It would also make life easier for @florianvolle while testing :)

**Comment by kroepke** [comment]
The idea is to have a plugin that implements the various plugin points we support in the product:
 - [ ] configurable transport/codec with all configuration fields types
 - [ ] customizable message generator with number of fields, length of field values, message rates
 - [ ] alarm callbacks  with all configuration fields types
 - [ ] outputs with all configuration fields types
 - [ ] rest endpoint for access in the API browser (and to control some of the plugin's classes)
 - [ ] MessageFilter

This is mainly to aid testing by @florianvolle as well as being able to generate unusual field counts and values for testing the UI.

**Comment by dennisoelkers** [comment]
What is the REST endpoint supposed to control?

**Comment by bernd** [comment]
I think this is kind of done? Closing this, please re-open if this is still relevant.
