### ISSUE TITLE
Summarize log messages when skipping offsets in corrupted journal

### ISSUE THREAD

**Issue by patrickmann** [Graylog2/graylog2-server#12379]
Journal reader will skip over invalid offsets in a corrupted journal, emitting a log message for every skipped offset.
This may lead to excessive logging (see Graylog2/graylog2-server#11795).
```2021-11-23T11:09:46.536-06:00 WARN [LocalKafkaJournal] Couldn't read any messages from offset <10372709> but journal has more messages. Skipping and trying to read from offset <10372710>```

Summarize these log messages to handle high volume more gracefully. E.g. summarize the results every 50, 100 or 500 log messages with a final "x messages were skipped due to possible journal corruption" at the end.

**Comment by bernd** [comment]
I added your suggestion to https://github.com/Graylog2/graylog2-server/issues/11795.
