### ISSUE TITLE
Upgrade to v1.1.1, no alerts triggering

### ISSUE THREAD

**Issue by zidvbelju** [Graylog2/graylog2-server#1239]
Hey Team,

Upgraded to v1.1.1 after losing the mongodb alert callback settings. I had previously re-created all of the alert callback settings prior to the upgrade to v1.1.1 (at v1.1). Post upgrade, all callback settings stayed the same; as expected - no mongodb migration commands were run. 

Since upgrading, no alerts are triggering. Streams are showing no triggered alerts in the past 3 days, but when I search within a stream itself, there are plenty of entries. The actual trigger mechanism seems to be broken/configured incorrectly. Has anything changed in regards to message count conditions? The below logic doesn't seem to be functional anymore.

"Alert is triggered when there are more than 0 messages in the last minute. Grace period: 0 minutes. Including last 10 messages in alert notification."

See attached image for alert conditions, callbacks, receivers, and triggered alerts.

![graylog_callbacks](https://cloud.githubusercontent.com/assets/5816964/8083173/9f499bbc-0f50-11e5-8232-fdc863f8f333.jpg)

Thanks,
Z

**Comment by bernd** [comment]
I just tried to reproduce this but it works fine for me.

![stream-alerts](https://cloud.githubusercontent.com/assets/461/8109131/773af14c-1055-11e5-96b3-b30c046e57b2.png)

Can you show us the output of the following MongoDB commands?

```
db.streams.find().pretty()
db.alarmcallbackconfigurations.find().pretty()
```

You can also write an email with that if you cannot post that here. (bernd(at)graylog.com)

**Comment by zidvbelju** [comment]
Email sent, thanks Bernd.

**Comment by zidvbelju** [comment]
After upgrading to v1.1.2, this issue is no longer present.

**Comment by joschi** [comment]
Thanks for the update! I'm closing this issue, please feel free to add a comment if the problem comes up again.
