### ISSUE TITLE
Unable to set password policy

### ISSUE THREAD

**Issue by gaikwadn7914** [Graylog2/graylog2-server#12406]
Currently Graylog does not support password length which got caught in our vulnerability analysis. Is there any way to configure password length & complexity?

Graylog version 4.2.5

**Comment by HungryHowies** [comment]
Hello,
There are no settings to adjust the amount of characters for local user/s. I’m not saying it impossible but it might take research on HowTo with that.

If you want strong password enforcement for your users, I’d recommend doing that in a central place and use external authentication (e. g. LDAP or AD) for Graylog.
Hope that helps

**Comment by bernd** [comment]
Thank you for the report! This is a duplicate of https://github.com/Graylog2/graylog2-server/issues/5283. Feel free to subscribe to that issue for updates.
