### ISSUE TITLE
Graylog2, grok not working.

### ISSUE THREAD

**Issue by jzellar** [Graylog2/graylog2-server#1241]
So i had a graylog server running with a bunch of grok filters i wrote.  I have started up a new VM on the most recent version.  I imported all the grok filters, but they do not appear to be working.  Any one else seeing this?

**Comment by kroepke** [comment]
What exactly have you tried?

Grok patterns should work correctly, and without a specific example we have no way of verifying whether this is a bug or not.

**Comment by jzellar** [comment]
Here are some pics. to Show, i have Grok patterns, Grok filters, and then a pic to show the lack of all the fields.   For the sake of brevity. I did not include pics of all the filters, patterns, and logs.

http://imgur.com/a/SC7vv

**Comment by zexxon** [comment]
In order for us to reproduce the issue, we will need a specific Grok patterns and messages that show this issue.

**Comment by jzellar** [comment]
This is happening for all messages, and all grok statements as you can see in the above attached photos

**Comment by jzellar** [comment]
I just spun up a second gray log server via the OVA.  I installed. ran sudo graylog-ctrl reconfigure
logged in.  added the grok patterns. imported the grok filters.  waited for logs to come in, and same result.  No added fields defined in grok statements.

am i doing this wrong?

**Comment by joschi** [comment]
@jzellar Please provide your actual Grok patterns and some example messages so that we can reproduce the issue. We certainly won't start to copy the Grok patterns and messages from those screenshots…

**Comment by jzellar** [comment]
Just looked at the input again, and checked the box to store the full message.  and just like that all my fields showed up just fine.  Some filters are working some are not.  I will just rewrite the ones that dont work.

**Comment by joschi** [comment]
Closing this issue now.

If you decide to provide the Grok patterns and some sample messages, please just comment on this issue.
