### ISSUE TITLE
Alarm on receiveBufferSize not trigered on Gelf Udp input

### ISSUE THREAD

**Issue by rlanore** [Graylog2/graylog2-server#1243]
When you start an GELF UDP input there are no alarm like GELF TCP input:

2015-06-10T11:50:54.161Z WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for [id: 0xe574613f, /0.0.0.0:12202] should be 1048576 but is 131071.

it's important to identify problem for event lost

and they are no documentation this.

Graylog installed from deb package must doing this

sysctl -w net.core.rmem_max=1048576

**Comment by bernd** [comment]
Sorry, we cannot execute sysctl commands when installing a package. If you run network software with different protocols, you have to be aware of tuning the network stack of your machines.
We cannot decide which settings are correct for your setup and it's also just not nice of a package to change system settings on your machine.

**Comment by bernd** [comment]
@rlanore There will be a warning for UDP inputs as well in the upcoming version.

**Comment by lxf1992521** [comment]
Get the same warning log like this:
————————————————————————————————————————————————
WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input RawTCPInput{title=Nginx Json log, type=org.graylog2.inputs.raw.tcp.RawTCPInput, nodeId=null} should be 1048576 but is 229376.
————————————————————————————————————————————————

Maybe graylog should “warning message” in input modal when setting SO_RCVBUF >= net.core.rmem_max.
