### ISSUE TITLE
elasticsearch configuration for graylog action.auto_create_index: false throwing error

### ISSUE THREAD

**Issue by shreyaspandey** [Graylog2/graylog2-server#12440]
## Expected Behavior

I am trying to install elasticsearch and add graylog specific configuration to it.

sudo tee -a /etc/elasticsearch/elasticsearch.yml > /dev/null <<EOT
cluster.name: graylog
action.auto_create_index: false
EOT

But action.auto_create_index: false this configuration is not working and elasticsearch fails with the error thats its too restrictive.
Its throwing error.

When I am removing action.auto_create_index: false the elasticsearch is starting normally.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 4.2
* Java Version: 1.8.0
* Elasticsearch Version: 7.10.0
* MongoDB Version: 4.2
* Operating System: Centos 8.4
* Browser version:

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
