### ISSUE TITLE
Allow customizing "default_index" and "default_search" analyzers from graylog.conf

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-server#1247]
It's great that we can customize the "message" and "full_message" analyzers from graylog.conf.  But that alone at the index level misses custom analyzers at the _all level and from the search direction (and it would be great if they could be set distinctly, i.e when indexing and searching require different analyzers -- our current setup).

To get around this we set our analyzers at the node level (quick and dirty), but it would be great if they could be set by Graylog on an index level as new indices are created so we don't have global settings at the ES node level.

Not sure how overriding default_index and default_search would work from an application setting a different distinctly named analyzer... Maybe the route is to set the index_analyzer and search_analyzer analyzers on the type "message"?

**Comment by joschi** [comment]
You can create a custom [index template](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) for indices created and used by Graylog with your custom field mappings.

**Comment by joschi** [comment]
Duplicates #903.
