### ISSUE TITLE
Output ID

### ISSUE THREAD

**Issue by adi-f** [Graylog2/graylog2-server#1248]
Using the REST API, the ID-field of an `Output` has two different names:
* using GET `/streams`, the output's ID-field is named '`_id`'  (streams contains outputs if an output is assigned to a stream)
* using GET `/streams/{streamId}`, the output's ID-field is named '`_id`'
* using GET `/system/outputs` ,the ID-field is named '`id`'

Version: Graylog 1.1.1 (893e8e7)

**Comment by kabl** [comment]
+1

**Comment by kabl** [comment]
+1
