### ISSUE TITLE
Index Sets page performance improvements

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#12498]
When a large number of indexes are present (or a few very large indexes are present), the Indices and Index Sets page and the details page for each index seem to be slow. The following requests are from a customer support ticket where there were about 100 index sets present.

## Indices & Index Sets page improvements
* A searchbar would be really nice.
* An option to enable/disable the index Set details regarding total doc, size and index set docs and size. Default should be that this stats are not shown and are only shown when needed. Background: We have clusters with ~1PB Storage totally ingested and this querys are quite expensive and the benefit not always given

## Index details page improvements
Can an option be added to enable/disable the index Set details regarding total doc, size and index set docs and size. Default should be that this stats are not shown and are only shown when needed. Background: We have clusters with ~1PB Storage totally ingested and this querys are quite expensive and the benefit not always given, and are not necessary if just an index needs to be cycled manually.

HS859116385

## Your Environment

* Graylog Version: 4.2.7
* Elasticsearch Version: elastic 7.10.2
* MongoDB Version: 4.4.12

**Comment by damianharouff** [comment]
@bernd just wondering if there was an approximate ETA or planned release version for this customer issue?

**Comment by bernd** [comment]
@damianharouff Please talk to product management about this. Thank you.

**Comment by damianharouff** [comment]
Adding @kroepke and/or @boosty for product

**Comment by kroepke** [comment]
There's no current ETA for this, no.

**Comment by boosty** [comment]
Will bring this up for the next cycle for the Core Team, but no promises yet. 

@dennisoelkers Just pinging you here in case you have capacity left in the next cycle for the Search Team, and want to take over? 😉
