### ISSUE TITLE
The syslog parser analyzes badly the logs

### ISSUE THREAD

**Issue by arugifa** [Graylog2/graylog2-server#125]
Hi,

I have a problem with the syslog parser. For exemple, with the following log :

`<46>Mar 20 15:22:38 host_srv01 rsyslogd: [origin software="rsyslogd" swVersion="4.6.4" x-pid="8767" x-info="http://www.rsyslog.com";] (re)start`

graylog2-web-interface displays "Mar" as the host source of the log (so it displays the name of the month instead of the host name).

But when I active the DNS lookup (RNDS) in graylog2-server, graylog2-web-interface displays the correct host name "host_srv01".

I don't know how graylog2 find the host source of the log (log analysis or retrieval from the ip source of the tcp/udp datagram).

Looking the source code, in SyslogProcessor.java, I see:

if (remoteAddress == null) {
            remoteAddress = InetAddress.getLocalHost();
        }

So theorically, graylog2 should use in the worst case the IP of the localhost. Maybe the problem is in SyslogDispatcher.java (a wrong IP address is sended to SyslogProcessor.java?):

InetSocketAddress remoteAddress = (InetSocketAddress) e.getRemoteAddress();
...
this.processor.messageReceived(new String(readable), remoteAddress.getAddress());

Thanks.
Best Regards.

**Comment by piesu** [comment]
I just encoutered this issue in graylog  2.0.0-beta.1.
Shouldn't source by default have ip instead of trying to extract from syslog msg?
