### ISSUE TITLE
Outgoing traffic utilisation shows data table for different duration

### ISSUE THREAD

**Issue by makstock** [Graylog2/graylog2-server#12502]
Outgoing traffic utilization should show the data table customization with the Last 30 days, Last 90 days, Last 180 days, and last 365 days.

## What?

The outgoing traffic utilization shows the Last 30 days by default, and if we add some customization, users can look back on their utilization by selecting options here.  

Option Should Look:
Last 90 Days 
Last 180 Days 
Last Year or Last 365 days

Default:
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/62546449/164439961-4d1eb338-3d62-488c-a0e4-99d3a70ab73e.png">

## Why?

This will give more concrete information regarding utilizing the customer Enterprise license usage for a specific duration.

##Context
HS-877554336
## Your Environment

* Graylog Version: *
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by kodjo-anipah** [comment]
Existing endpoint can be used to implement this:
`/system/cluster/traffic?days=30&daily=false`
while daily is set to false by default and controls whether the traffic should be aggregate to daily values.

**Comment by mnin** [comment]
Done in https://github.com/Graylog2/graylog2-server/pull/13545
