### ISSUE TITLE
Graylog-server container start consuming high cpu and auto recovers in evening  

### ISSUE THREAD

**Issue by kcgochar** [Graylog2/graylog2-server#12507]
We are using Graylog 3.3.15 and it's running as docker-compose.  From last month every Tuesday 5:30 AM we see high cpu usage on server which auto recovers at evening.  This is happening only on every Tuesday. 

Any clue or leads from where to start looking in the issue.  and what could be reason behind it.

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
