### ISSUE TITLE
No data put into graylog with logstash

### ISSUE THREAD

**Issue by apaul030515** [Graylog2/graylog2-server#1253]
Hi,

I wrote a conf file in logstash in order to put the data to graylog with gelf output.But when I running the logstash,I didn't see any data in Graylog web interface,and there has a error info in Graylog log.
Could someone tell me the reason?

Here is the error log in graylog.
2015-06-18 17:09:03,158 ERROR: org.graylog.plugins.usagestatistics.UsageStatsNodePeriodical - Error while uploading anonymous usage statistics

Here is the logstash conf:
input { 
  file { 
    path => [ '/tmp/3.txt' ] 
    type => 'test'
       } 
      } 

filter {
    mutate {
        split => ["message", "#"]
        add_field => [ "start_time", "%{[message][0]}" ]
        add_field => [ "db_host", "%{[message][1]}" ]
        add_field => [ "username", "%{[message][2]}" ]
        add_field => [ "sourceIP", "%{[message][3]}" ]
        add_field => [ "query_time", "%{[message][4]}" ]
        add_field => [ "lock_time", "%{[message][5]}" ]
        add_field => [ "rows_sent", "%{[message][6]}" ]
        add_field => [ "rows_examined", "%{[message][7]}" ]
        add_field => [ "db", "%{[message][8]}" ]
        add_field => [ "sqlquery", "%{[message][9]}" ]
       }

}

output {
  gelf   {
    host => '127.0.0.1'
    port =>  12203
    
     }
       }

Here is the data exsample:
2015-06-18 11:29:07#10.43.1.2#root[root] #  [172.18.3.11]#2#0#24#847052#boss#SELECT f1.seq_no AS seqNo,      f1.create_seq_no A
S createSeqNo,      f1.creator,      f1.payer,      f1.payee,      f1.app_para AS appPara,      f1.money,      f1.spec,      f1
.create_time AS createTime,      f1.pay_time AS payTime,      f1.pz_time AS pzTime,      f1.expires,      f1.bill_type AS billT
ype,      f1.merGoods,      f1.bankGroup,      f1.merchantId,      f1.channelId,      f1.state,      fb.bankName,      case whe
n f1.payee like '1_204%' then fm.merchantName else fp.proname  end AS 'merchantName',       substring(f1.payee,1,5) AS busType 
      FROM froadbill.bill f1 left join froadmall.ft_bankinfo fb on f1.bankGroup = fb.bankGroup      left join froadmall.ft_merc
hant fm on fm.merchantId = f1.merchantId      left join froadmall.transaction ft on f1.seq_no = ft.SPID      left join froadmal
l.trangoods ftg on ft.ID = ftg.TranID      left join froadmall.provider fp on ftg.providerID=fp.ID      where 1=1              
            and         date(f1.create_time) >= '2015-06-18'            and         date(f1.create_time) <='2015-06-18'        
              order by f1.create_time desc limit 60,30

**Comment by kroepke** [comment]
The error in the log message is unrelated, it is about not being able to send anonymous statistics about Graylog, not incoming messages.

Please direct questions about Graylog to our Google Group https://groups.google.com/forum/?fromgroups=#!forum/graylog2
We use Github Issues for tracking bugs only.

Thank you!
