### ISSUE TITLE
Capacity Requirement

### ISSUE THREAD

**Issue by HSVK** [Graylog2/graylog2-server#1254]
Hi, 
Our environment is setup as such,
2 graylog servers with 4 Cpu and 8 GB Ram / node, where the allocated heap is 4GB/node
3 Elasticsearch servers with 8 Cpu and 30 GB Ram / node, where the allocated heap is 20 GB / Node.
1 mongodb and graylog web server with 2 cpu and 4 GB Ram.

Our policy is to have 90 days worth logs, which i am maintaining with 12 hr /indice and max of 190 open indices. Currently we have 15,325,513,506 docs stored and it is supposed to increase to 25,...... And our message per minute will be around 200k min to 700k max. 

We did not have any problem until we had 120 indices, now there seem to be many error messages occurring because of out of memory when the searches are performed, but not when the messages are being stored. And when we have high message incoming while performing the search, i think Graylog writes the data to journal and processes it later. In order to prevent the node crash in ES, i have set the circuit breaker so even if the search are huge the environment does not come down but the search results are affected. 

We are using graylog 1.0 with ES 1.44. We are planning to upgrade to graylog 1.1.2 by next week end. 

Can  you please advise on the capacity that each boxes should have to have a better performance.  Or how do i calculate the server capacity requirement in order to judge the current and future logging. 

Thanks, Hema

**Comment by kroepke** [comment]
Please direct questions about Graylog to our Google Group https://groups.google.com/forum/?fromgroups=#!forum/graylog2
We use Github Issues for tracking bugs only.

Thank you!
