### ISSUE TITLE
System notification should inform via Email alerts to admin role users.

### ISSUE THREAD

**Issue by makstock** [Graylog2/graylog2-server#12555]
The system notification is shown in System/Overview informs admin role users 
## What?

The specific/admin group of users should get notified of those trigger notifications via Email

Here are the sample notification:
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/62546449/165729561-e86baf4c-e914-4475-9dd5-8f4230487128.png">

## Why?

It will not require a login each time to take necessary actions on such System notifications. The notified user can take action according to the urgency of the notification.

##Context
HS-887267106/HS-880186036

## Your Environment

* Graylog Version: ALL
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by boosty** [comment]
This is a bit similar to https://github.com/Graylog2/graylog-plugin-enterprise/issues/2776, where we added support for receiving traffic notifications via email.

**Comment by patrickmann** [comment]
Instead of building another custom email notification we will tie this into the existing Event subsystem. We get to re-use that code and users can leverage the familiar notification types. 
System events will also be persisted to the System Events Stream; though this is not a requirement in the first step.

**Comment by coffee-squirrel** [comment]
@patrickmann Would that approach rely on everything being functional enough to write those events to an index in ES/OS?  Just wondering if certain types of severe situations (e.g. blocked indices) would still need to be dependent on something external for notifications.
