### ISSUE TITLE
Very slow Graylog output rate

### ISSUE THREAD

**Issue by AaronSoto** [Graylog2/graylog2-server#1255]
Hello, 
I'm trying to set up a Graylog server in an Amazon m3.large EC2 instance. Since I can't read server logs in real time, first, I have to download them from my Amazon instance, decompress them, and finally send them to Graylog with logstash. The normal size of a log file is about 1 GB., using 30 workers with logstash the input transfer rate is between 1000-1500 messages/second. The trouble comes when graylog outputs the messages to my streams; the output transfer rate is 300 messages/second (max), which I think is very slow because I have to download logs from 5 servers each day. 

Is there a way I can maximize the output transfer rate? Now I have 24 streams with two regex each one.

I'm new trying to set up a production environment with Graylog, any help will be greatly appreciated, thank you.

**Comment by joschi** [comment]
What kind of stream output are you using and where does it send the messages to?

**Comment by bernd** [comment]
I am closing this now. Please re-open if you still have problems. Thank you!
