### ISSUE TITLE
The list of fields should only show fields that are present in selected streams.

### ISSUE THREAD

**Issue by luk-kaminski** [Graylog2/graylog2-server#12572]
The list of fields should only show fields that are present in selected streams.
(seems like a duplicate of #9397)

## What?
Now it works like that:
![Screenshot 2022-04-29 at 13-29-43 Graylog - Unsaved Search](https://user-images.githubusercontent.com/100699120/165936451-bc991147-e0ff-4087-86c1-a4e281b416a0.png)

It should work like that:
![Screenshot 2022-04-29 at 13-30-21 Graylog - Unsaved Search](https://user-images.githubusercontent.com/100699120/165936468-bc28034a-1a47-473c-ad60-acd85705d825.png)

As you see in the example, only 4 fields are present in the "Czech stream", other fields come from other streams, and should not be visible.

## Why?
It will be simpler for a user to identify proper fields.

## Technical considerations

The main approaches include:
1. Using search engine to provide proper fields for streams.
1.1. Ad hoc - each time it is needed. 
1.2. Periodically, with storage in Mongo of stream-fields mapping.

(Draft PR is available to demonstrate both approaches combined :  #12613)

Main con: The more fields client uses, the more slow or even unreasonable may be the usage of this approach.

2. Identification of streams-fields relation during message ingestion and publishing. 

Main con: May be more difficult to implement, may influence ingestion speed...

## Your Environment
Feature is missing on all environments.
Change is needed for all search engine versions(ES6, ES7, Opensearch)

**Comment by H2Cyber** [comment]
Also see https://github.com/Graylog2/graylog2-server/issues/9397
