### ISSUE TITLE
Time stamps wrong

### ISSUE THREAD

**Issue by joshuascott** [Graylog2/graylog2-server#1258]
Ok this is a little weird. I have a Sourcefire IPS that's set to send all messages as Syslog to my Graylog server. I am located in the Pacific Time Zone (PDT) which is currenty UTC-7. The messages that are sent by Sourcefire do not show up for 7 hours. When looking at the timestamps on the Sourcefire everything looks correct. I can see the messages coming into my Graylog server when I run a packet capture from the command line of the server itself. But messages sent from the Sourcefire server at 13:00 hours (20:00 UTC) will not show up in Graylog searches until 20:00 PDT. (UTC - 7) 

Somehow Graylog is reading the time being sent not as UTC time but as local time and holding the messages and not sending any alerts from matching streams until 7 hours after the message is sent to Graylog.

**Comment by joschi** [comment]
That sounds like your Sourcefire IPS isn't sending valid syslog messages (i. e. with timestamps containing timezone information) to Graylog.

Please check if the logs can be normalized with some extractors: http://docs.graylog.org/en/1.1/pages/extractors.html#normalization
