### ISSUE TITLE
Dashboard timerange override is lost after save

### ISSUE THREAD

**Issue by patrickmann** [Graylog2/graylog2-server#12590]
## Expected Behavior
By default, the dashboard timerange is set to the last 5 minutes. After modifying the timerange and saving the dashboard, this timerange override should be applied whenever I open the dashboard.

## Current Behavior
When I re-open the dashboard after saving, the timerange has been reset to the default 5 minutes.
Interestingly, the timerange change persists if it is set within a widget. 

## Steps to Reproduce (for bugs)
1. Open a dashboard
2. Set global timerange to 60 minutes
3. Save
4. Re-open the dashboard
5. Observe that timerange is back to 5 minutes

## Context
https://community.graylog.org/t/saving-the-time-range-in-dasboard-does-not-work/23682

## Your Environment

* Graylog Version: 4.3

**Comment by patrickmann** [comment]
There’s an argument to be made either way. Maybe there could be a radio button you can select, if you want the global setting to persist.

**Comment by maltris** [comment]
Strange, how would I make any widget in the dashboard apply the global default if a time-range had been specifiied prior?

**Comment by T100D** [comment]
To us, when creating widgets in a dashboard one can specify the searchtime and that is set with the widget, should be set on every widget and can be overidden on top of the dashboard if wanted.
