### ISSUE TITLE
search with "*" seems not to show all messages

### ISSUE THREAD

**Issue by plt-sun** [Graylog2/graylog2-server#1261]
I'm running graylog from a ova image with latest update (v1.1.3). i used the following inputs: syslog tcp (port 514), syslog udp (port 514), gelf tcp (port 12201). also i'm running a collector (v0.2.2) on one linux machine since last 4 days.
now, when i'm searching in search line with "`*`", i get only messages from my syslog inputs, not from my gelf input. 
searching to "gl2_source_collector:(gelf collector)" or searching to "gl2_source_input:(gelf input)" shows my logged messages from collector.
don't know, why i can't see all messages from all inputs while searching with "`*`" ?

**Comment by bernd** [comment]
Is this still a problem with the latest Graylog (1.1.6) and the latest collector (0.4.0)?

I am closing this issue, please re-open if you still have problems with the latest versions. Thank you!
