### ISSUE TITLE
Support for OpenSearch 2.0

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#12612]
## What?

OpenSearch 2.0 is in RC right now. We do not support it out of the box, so we need to make the required changes in order to operate with it.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by todvora** [comment]
Hey @janheise, let me know if I can help you with that :pray:

**Comment by janheise** [comment]
more findings: Lucene has to be bumped to 9.1.0

**Comment by KlavsKlavsen** [comment]
Here's hoping this isn't far off :)

**Comment by KlavsKlavsen** [comment]
It seems this has already been merged here: https://github.com/Graylog2/graylog2-server/pull/13340 ? But I don't see it in changelog of graylog releases yet?

**Comment by dennisoelkers** [comment]
Hey @KlavsKlavsen,

it is not officially supported in the recently released Graylog 5.0.

Therefore, I am closing this in issue.

Fixed in #13340.
