### ISSUE TITLE
HTTP Headers key value row not visible on dark mode

### ISSUE THREAD

**Issue by ousmaneo** [Graylog2/graylog2-server#12633]
When editing `HTTP JSONpath` data adapters the `HTTP Headers` field odd rows text are not visible in Dark mode. 
![image](https://user-images.githubusercontent.com/1381455/167632538-b1eb353e-7621-463d-acd5-3c260ed2f232.png)

## Steps to Reproduce (for bugs)

1. Goto System -> Lookup Table 
2. Click on Data Adapters 
3. Create an `HTTP JSONpath` Data adapters
4. Add some rows to the `HTTP Headers` field

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by mnin** [comment]
This issue is fixed in https://github.com/Graylog2/graylog2-server/pull/1262

![Screenshot 2022-06-08 at 16 07 21](https://user-images.githubusercontent.com/92227/172637579-e9d18116-64d8-4749-ab48-aa5d786c711b.png)
4
