### ISSUE TITLE
Search shows latest logdata only partial

### ISSUE THREAD

**Issue by HolgerOpenSource** [Graylog2/graylog2-server#1264]
In Graylog we see indexed documents not always in realtime. A search shows latest logdata only partial, but after a delay from up to 1 hour all logdata is visible. We index 10.000 msg/sec and have an elasticsearch setup with 6 data-nodes. Indices are defined with 6 primary shards und 1 replica. The environment runs stable without an indication for any delayed processing.

our versions:
Graylog 1.0.2
elasticsearch 1.4.2 
mongoDB 4.6.7

From Graylog Sourcecode
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
we see that Graylog is using elasticsearch setting
request.setReplicationType(ReplicationType.ASYNC);
for bulk index api-calls. This setting can lead to delayed replication from primary-shards to replica-shards, if the elasticsearch-cluster is overloaded in some way. Searches can't find all logdata until the documents are fully replicated to the replica-shards.
https://www.elastic.co/guide/en/elasticsearch/reference/1.4/docs-index_.html#index-replication

What do you think? Does that make sense?
Should Graylog better use the default setting "SYNC" as replication type? In elasticsearch the ASYNC setting is already deprecated!
https://www.elastic.co/guide/en/elasticsearch/reference/master/_async_replication.html

Best regards,
       Holger

**Comment by rcord02** [comment]
+1
I run a similar Graylog setup, same version and also ca. 10.000 - 15.000 (partly long) messages per secoud. From time to time I have the described delay between pushing messages to elasticsearch and getting them visible in the webinterface of graylog. Is this a known issue?

**Comment by joschi** [comment]
If your Elasticsearch cluster is fine and processing messages quickly, this could also be caused by broken timestamps in the messages. You can check that by searching messages "in the future", e. g. in 2 hours from the current time.

The Graylog web interface is querying Graylog directly which in turn queries Elasticsearch directly without any cache in-between. So if the messages have been indexed and the indices have been refreshed (https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html), the messages will be found and display by the web interface.

**Comment by HolgerOpenSource** [comment]
Our "index.refresh_interval" is at the default value 1 second.
We look for a given timeframe, e.g. from "2015-07-02 12:00:00.000 +02:00" to "2015-07-02 12:01:00.000 +02:00".
First we see for instance 200.000 msg. After a few minutes we see for the same timeframe 300.000 msg! An additionel few minutes later we see the correct number 350.000 msg.
We suspect, that we have this behaviour because a search uses also data from replica shards. If the elasticsearch shards replication process isn't in sync (How can we check this?), logdata is missing in search.
