### ISSUE TITLE
Stream rule permission

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1267]
Hello,

In some circumstances, i think it will be very helpful to hide the rules used to make streams to other users.

Maybe something like 

"streams:read:5515xA48e4b0894687dab22e"
"rules:hide:5515xA48e4b0894687dab22e"

Thanks.

**Comment by joschi** [comment]
Could you please elaborate on a use case for this?

**Comment by pdepaepe** [comment]
My use case also requires to mute globally from queries this specific field (as your "streams" one), which is today impossible, no?

**Comment by joschi** [comment]
The "hidden" message fields (usualy with a "gl2_" prefix) are currently hard-coded.

What's the use case for hiding certain fields (that still occur on the indexed messages) in your setup?

**Comment by dennisoelkers** [comment]
I think the point is to be able to hide stream rules from users which are able to read the stream. This also implies that the fields the rules of this stream are matched against would need to be hidden as well. I am struggling to come up with a reasonable use case for this that legitimizes the effort to do this properly.
