### ISSUE TITLE
Unable to send message to docker hosted graylog instance

### ISSUE THREAD

**Issue by GregClifford** [Graylog2/graylog2-server#1268]
I've installed the graylog docker image on a CentOS 7 vm but I am currently unable to get it to receive any messages. I can browse to the WebUI but when I try to send a message to the server using netcat I get connection refused on the port I specified when starting the container (default 12201). When I shell in to the container and do netstat -l there's no indication that anything is listening on 12201.

Have I missed something?

**Comment by mariussturm** [comment]
Did you start a GELF TCP input through the webUI? You can find it under
System->Inputs.

On 26 June 2015 at 12:56, GregClifford <notifications@github.com> wrote:

> I've installed the graylog docker image on a CentOS 7 vm but I am
> currently unable to get it to receive any messages. I can browse to the
> WebUI but when I try to send a message to the server using netcat I get
> connection refused on the port I specified when starting the container
> (default 12201). When I shell in to the container and do netstat -l there's
> no indication that anything is listening on 12201.
>
> Have I missed something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Graylog2/graylog2-server/issues/1268>.
>



-- 
Developer

Tel.: +49 (0)40 609 452 077
Fax.: +49 (0)40 609 452 078

TORCH GmbH - A Graylog Company
Steckelhörn 11
20457 Hamburg
Germany

https://www.graylog.com <https://www.torch.sh/>

Commercial Reg. (Registergericht): Amtsgericht Hamburg, HRB 125175
Geschäftsführer: Lennart Koopmann (CEO)

**Comment by GregClifford** [comment]
Thanks, that solved it.
