### ISSUE TITLE
user roles... need more roles.

### ISSUE THREAD

**Issue by cybermedi** [Graylog2/graylog2-server#1271]
I need more roles than administrator and user. User must have access to global search but not access to creating and managing other user. Currently I have graylog full of admins.

**Comment by edmundoa** [comment]
As a workaround while we work on this, you can use the server REST API to assign more granular permissions to users. These are all available permissions that you could use: https://github.com/Graylog2/graylog2-server/blob/master/graylog2-shared/src/main/java/org/graylog2/shared/security/RestPermissions.java

**Comment by bernd** [comment]
Please track issue #1321 and #1322 for progress on roles support. This is planned for 1.2.0.

I am closing this issue now.
