### ISSUE TITLE
Query parsing error in WildcardQuery. Graylog 4.3.0 Update

### ISSUE THREAD

**Issue by chalfling** [Graylog2/graylog2-server#12741]
## Expected Behavior

I'm expecting wildcardquery to works as working in 4.2.9 version.
As per doc: https://docs.graylog.org/docs/query-language#parse-exception
source:\*.org
source:exam?le.org
source:exam?le.\*

## Current Behavior

Got error:
![Screenshot_20220526_144545](https://user-images.githubusercontent.com/9088569/170546380-8b094e17-394e-4f3d-a465-c0bca42a0069.png)

## Your Environment

* Graylog Version: 4.3.0
* Java Version: 11
* Elasticsearch Version: 7.10
* MongoDB Version: 4.2
* Operating System: FreeBSD 12.2

**Comment by dennisoelkers** [comment]
Hey @chalfling, thanks for reporting this!

The issue has been fixed in #12727 already and will be part of the next patch release (`4.3.1`) which will come out soon.
