### ISSUE TITLE
How to get the number of nodes in a Graylog cluster from prometheus_exporter？

### ISSUE THREAD

**Issue by ap0806109** [Graylog2/graylog2-server#12766]
How to get the number of nodes in a Graylog cluster from prometheus_exporter？

**Comment by kroepke** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like it. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by kroepke** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
