### ISSUE TITLE
Intelligently add "lowercase_expanded_terms: false" to appropriate queries

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-server#1276]
Until Elasticsearch implements something mentioned in this issue -- https://github.com/elastic/elasticsearch/issues/3922 -- there's annoying issues with uppercase and wildcards/regexes in field searches on not_analyzed fields.

Which you guys probably realized due to source being an analyzer_keyword:

https://github.com/Graylog2/graylog2-server/blob/1.0/graylog2-server/src/main/java/org/graylog2/indexer/Mapping.java
// to support wildcard searches in source we need to lowercase the content (wildcard search lowercases search term)
properties.put("source", analyzedString("analyzer_keyword"));

Any way to quickly scan the search query at the graylog-server layer and scan for field searches with Uppercase mixed with wildcards or regex?  And if detected, add to the query "lowercase_expanded_terms": "false"?

Not sure how bad having that set in specialized cases would break other previously working queries...  Maybe if implemented, give the option to enable this functionality on ES search queries like leading wildcards?

**Comment by jalogisch** [comment]
@NickMeves is this still relevant for you? 

From our end it looks like Elastic had fixed this issue. Please open a new issue if this needs our attention again.
