### ISSUE TITLE
Unable to use Filter in REST API

### ISSUE THREAD

**Issue by vapost** [Graylog2/graylog2-server#1278]
Hi, I am trying to put a filter in the REST API but I am getting 

```{
  "type": "ApiError",
  "message": "Not allowed to search with filter: [method:book]"
}```

This is how my request looks like:

http://example.com/search/universal/relative?query=booking&range=3000&limit=100&filter=method%3Abook&fields=message

I am trying to use Swagger interface

Does someone know how to pass filters to this method? For example, I want to get all messages where the field X is equal to Y

**Comment by joschi** [comment]
You can simply add the "method:book" part to your query and get the result you want: http://example.com/search/universal/relative?query=booking%20method%3Abook&range=3000&limit=100&fields=message

**Comment by carlvine500** [comment]
curl -uadmin:admin 'http://server:9000/api/search/universal/absolute?query=xxxx&from=2020-9-15%2015%3A00%3A00&to=2020-9-15%2021%3A00%3A00&decorate=true'
