### ISSUE TITLE
"Copy to clipboard" actions for message field names and values

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#12824]
## What?

There should be "copy to clipboard" actions for message field names and values (message table, message permalink page, etc.), and a Message-level "Copy to JSON" action (for quick and easy copying of an entire Message).

## Why?

Copying message contents is a common task, but there are some minor annoyances (when working with a message table):
* If you double-click a message field's name or value (for a quick Ctrl+C) you get popping in and out of the associated Actions dropdown/menu
* Double-clicking a field's value and copying _sometimes_ results in 4 leading spaces (not exactly sure what the trigger is for that)
* Copying large values (e.g. a big multiline message) can be tedious, and can result in the Actions dropdown/menu popping up (inconsistent)
* If you try to copy the `message` content at the table row level (i.e. not yet expanded Message row) the row is always expanded and the highlighted text is unmarked (an issue if you didn't Ctrl+C before unclicking).
  * If a message has many fields and you just want to do a quick copy of something in `message`, this is preferable to expanding the row and locating `message` field.
  * This one is a bit different from the rest, but I'm including it since it's a message copying annoyance

As mentioned above, it'd also be nice to have a quick and easy way to copy an entire Message to JSON in the UI, without the need to open up dev tools, using the API, etc.

## Your Environment

* Graylog Version: 4.3.0
* Operating System: Windows 10
* Browser version: Firefox 101, Chrome 102

**Comment by dennisoelkers** [comment]
Refs #4673.
