### ISSUE TITLE
Escape brackets in HTML email alerts

### ISSUE THREAD

**Issue by inventor96** [Graylog2/graylog2-server#12854]
## What?

Currently, if a field is included in the HTML portion of an alert email, and that field contains open and close angle brackets (`<` and `>`), email clients treat everything within those brackets as HTML elements, and so the contents within them isn't accessible by the reader of the email. See this thread in the Graylog forum for more specifics and examples: https://community.graylog.org/t/brackets-not-escaped-in-alert-emails/24201

The feature request is that brackets within fields could be escaped, or changed into their HTML-friendly versions (e.g. `<` to `&lt;` and `>` to `&gt;`).

## Why?

A temporary work-around is to not use HTML in the email template at all, but that can make emails much harder to read. If we could escape these special HTML characters, we could continue to use the HTML part of the email template where we can lay out the necessary data for better readability.

## Your Environment

* Graylog Version: 4.3.1
* Elasticsearch Version: 7.10.2
* MongoDB Version: 4.2.20
* Operating System: Rocky Linux 8.6
* Browser version: n/a

**Comment by zhu** [comment]
With #12792 , you can use `${message;htmlsafe}` to escape the message.

**Comment by inventor96** [comment]
Awesome! I'm looking forward to that getting merged in. 👍

**Comment by boosty** [comment]
Fixed via https://github.com/Graylog2/graylog2-server/pull/14286
