### ISSUE TITLE
Export/Import API for Extractors JSON format does not match Create Extractor Request API json format

### ISSUE THREAD

**Issue by RonneGisun** [Graylog2/graylog2-server#12856]
ExtractorSummary JSON should match CreateExtractorRequest JSON definition, but instead has a different label for the same data element. This prevents retrieving an Extractor, saving the message, and then loading the same message without alteration for a create API call.

## Expected Behavior
org.graylog2.rest.models.system.inputs.extractors.requests.CreateExtractorRequest JSON Model Schema format is defined as:
`{
source_field (string, optional),
target_field (string, optional),
extractor_config (object, optional),
extractor_type (string, optional),
condition_type (string, optional),
condition_value (string, optional),
converters (object, optional),
title (string, optional),
cut_or_copy (string, optional),
order (integer, optional)
} `
Code generated by the Extractor Export functionality should use the above Schema format to describe all elements.
Code generated by the export/display current functionality, should be reusable in the import/create functionality without any need to alter the contents.

## Current Behavior
org:graylog2:rest:models:system:inputs:extractors:responses:ExtractorSummary JSON Model Schema format is defined as:
`{
creator_user_id (string, optional),
source_field (string, optional),
condition_type (string, optional),
converter_exceptions (integer, optional),
title (string, optional),
type (string, optional),
cursor_strategy (string, optional),
exceptions (integer, optional),
target_field (string, optional),
extractor_config (object, optional),
condition_value (string, optional),
converters (array[object], optional),
id (string, optional),
metrics (ExtractorMetrics, optional),
order (integer, optional)
}`
Using the above exported code JSON Schema format with a direct call to the Create Extractor Request API produces this error:
`{"message": "Cannot construct instance of `org.graylog2.rest.models.system.inputs.extractors.requests.CreateExtractorRequest`, problem: Null cutOrCopy\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 346]", "type": "ApiError"}`

Is seems not only is 'cut_or_copy' not optional, it is not interchangeable with 'cursor_strategy'. Both 'cut_or_copy' (from API Create Extractor) and 'cursor_strategy' (from API Extractor Summary) are used to define exactly the same data element. Ideally, only one or other of the labels should be used consistently across all JSON Schemas.

## Possible Solution
Change one or both JSON Model Schemas to use the same labels to describe data elements.

## Steps to Reproduce (for bugs)

The error message is displayed
1. Go to the GUI System/Inputs list page.
2. Select "Manage Extractors", click "Actions/Export extractors".
3. Copy and paste the json and save to a file or elsewhere.
4. Do not use "Actions/Import extractors" button from GUI page, instead load json from file or elsewhere and post to directly to Create Extractor Request API.
5. A HTTP 400 error code is returned with the error message: "Cannot construct instance of `org.graylog2.rest.models.system.inputs.extractors.requests.CreateExtractorRequest`, problem: Null cutOrCopy\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 346]", "type": "ApiError"

## Context
Being able to export content from one environment and import into another, is important when managing different releases between pre-production and production environments. This bug makes that task more difficult/complex than it needs to be, involving additional time and effort unnecessarily.

Ideally, having consistent data element definitions (and labels) makes automating this release process using direct calls to the APIs take less effort, reducing the payback time required for automating what was previously a manual task.

## Your Environment
* Graylog Version: 4.3.1-1
* Java Version: openjdk version "11.0.15" 2022-04-19
* Elasticsearch Version: 7.10.2-1 
* MongoDB Version: 4.4.14-1
* Operating System: CentOS Linux release 7.9.2009 (Core)
* Browser version: Firefox 101.0

**Comment by jasonrberk** [comment]
this is *not* the only place where payload fields magically change....SO FRUSTRATING!!!
