### ISSUE TITLE
Blank page after logging out

### ISSUE THREAD

**Issue by snghoshi** [Graylog2/graylog2-server#12894]
Since upgrading to version 4.2.x and now at 4.3.1. My Graylog server works find until i logout then the browser just display a blank page. The only way to login via the browser is to restart the graylog service again then it will work (display the page) until i log out.
Running on Ubuntu.

**Comment by dennisoelkers** [comment]
Hey @snghoshi,

do you see anything in your browser's JS console when you try to login/seeing the blank page?

**Comment by snghoshi** [comment]
Hi @dennisoelkers,

I get the following:



Uncaught SyntaxError: expected property name, got '&'
config.js:6:2
GEThttps://10.10.x.x/assets/plugin/org.graylog.aws.AWSPlugin/plugin.org.graylog.aws.AWSPlugin.a365ae42c6adc7b2e522.js
[HTTP/1.1 200 OK 0ms]

GEThttps://10.10.x.x/assets/plugin/de.irgendwr.TelegramNotificationPlugin/plugin.de.irgendwr.TelegramNotificationPlugin.45b2a68657d722b1f0d2.js
[HTTP/1.1 200 OK 0ms]

GEThttps://10.10.x.x/assets/app.3ce412862026e2958937.js
[HTTP/1.1 200 OK 0ms]

Uncaught TypeError: undefined is not a valid argument for URI
    i URI.js:54
    joinPaths URI.js:961
    <anonymous> webpack-entry.js:26
    <anonymous> index.jsx:72
    <anonymous> index.jsx:72
URI.js:54:14
Uncaught TypeError: undefined is not a valid argument for URI
    i URI.js:54
    joinPaths URI.js:961
    <anonymous> webpack-entry.js:9
    <anonymous> index.jsx:60
    <anonymous> index.jsx:60
URI.js:54:14
Uncaught TypeError: undefined is not a valid argument for URI
    i URI.js:54
    joinPaths URI.js:961
    <anonymous> webpack-entry.js:25
    <anonymous> index.jsx:51
    <anonymous> index.jsx:51
URI.js:54:14
Uncaught TypeError: undefined is not a valid argument for URI
    i URI.js:54
    joinPaths URI.js:961
    <anonymous> webpack-entry.js:25
    <anonymous> index.jsx:87
    <anonymous> index.jsx:87
URI.js:54:14
    i URI.js:54
    joinPaths URI.js:961
    <anonymous> webpack-entry.js:25
    <anonymous> index.jsx:87
    <anonymous> index.jsx:87
Uncaught TypeError: undefined is not a valid argument for URI
    i URI.js:54
    joinPaths URI.js:961
    <anonymous> webpack-entry.js:25
    <anonymous> index.jsx:119
    <anonymous> index.jsx:119
URI.js:54:14
Uncaught TypeError: undefined is not a valid argument for URI
    i URI.js:54
    joinPaths URI.js:961
    <anonymous> webpack-entry.js:25
    <anonymous> index.jsx:28
    <anonymous> index.jsx:28
URI.js:54:14
Uncaught TypeError: e is undefined
    exports vendor.3b152b3d9c1d8273aa7e.js:2
    exports vendor.3b152b3d9c1d8273aa7e.js:2
    U8HBYKER punycode.js:2
    Webpack 10
vendor.3b152b3d9c1d8273aa7e.js:2:4948
Uncaught TypeError: undefined is not a valid argument for URI
    i URI.js:54
    joinPaths URI.js:961
    <anonymous> webpack-entry.js:26
    <anonymous> index.jsx:56
    <anonymous> index.jsx:56
URI.js:54:14
GEThttps://10.10.x.x/assets/favicon.png
[HTTP/1.1 200 OK 0ms]

​

**Comment by dennisoelkers** [comment]
Hey @snghoshi,

thanks for getting back to me. Can you do the following and post the output?

```
curl -v https://10.10.x.x/config.js
```
(Please replace the ip with the one of your Graylog server)

**Comment by snghoshi** [comment]
Hi @dennisoelkers , thanks for your reply.
Please find requested info below (please note i masked the IP details):

*   Trying 10.10.x.x:443...
* TCP_NODELAY set
* Connected to 10.10.x.x (10.10.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: self signed certificate
* Closing connection 0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by dennisoelkers** [comment]
Can you try it like this (with an additional `-k`)?

```
curl -kv https://10.10.x.x/config.js
```

**Comment by snghoshi** [comment]
Hi @dennisoelkers , alright cool, here below:


ubuntu@graylog:/etc/nginx$
ubuntu@graylog:/etc/nginx$ curl -kv https://10.10.x.x/config.js
*   Trying 10.10.x.x:443...
* TCP_NODELAY set
* Connected to 10.10.x.x (10.10.x.x) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=NA; ST=Khomas; L=whk; O=IT; OU=NC; CN=graylog; emailAddress=snghoxx@nc.com.na
*  start date: Jun  2 19:51:16 2020 GMT
*  expire date: Jun  2 19:51:16 2021 GMT
*  issuer: C=NA; ST=Khomas; L=whk; O=IT; OU=NC; CN=graylog; emailAddress=snghoxx@nc.com.na
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /config.js HTTP/1.1
> Host: 10.10.x.x
> User-Agent: curl/7.68.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.18.0 (Ubuntu)
< Date: Mon, 20 Jun 2022 13:06:53 GMT
< Content-Type: application/javascript
< Content-Length: 296
< Connection: keep-alive
< X-Graylog-Node-ID: 0055c923-e395-4515-8c9c-4a625892dad7
<
window.appConfig = {
  gl2ServerUrl: '/api/',
  gl2AppPathPrefix: '/',
  rootTimeZone: 'Etc/GMT-2',
  pluginUISettings: {
  &quot;org.graylog.plugins.customization.theme&quot; : { },
  &quot;org.graylog.plugins.customization.notifications&quot; : { }
},
  isCloud: false,
  featureFlags: { },
};
* Connection #0 to host 10.10.x.x left intact
ubuntu@graylog:/etc/nginx$

**Comment by dennisoelkers** [comment]
Okay, that looks good. I am suspecting the telegram notification plugin to be the culprit, as it is probably outdated. Can you try removing the plugin and see if it still happens?

**Comment by snghoshi** [comment]
Hi @dennisoelkers , thanks a lot for your help.

I upgraded to version 4.3.2 and also the Telegram to version 2.3.9 and now it seems all is fine again.

Appreciated.
