### ISSUE TITLE
geoip resolver strips geoip fieldnames of "_ip" if fieldname containing ip address is source_ip, destination_ip or host_ip

### ISSUE THREAD

**Issue by jjkoster** [Graylog2/graylog2-server#12904]
To align with the Graylog Information Model schema we rename source and destination ip address fieldnames as source_ip and destination_ip.

Since version 4.3.x it appears that the geoip resolved fields strip the "_ip" from the resulting fieldnames.

Example: for CheckPoint messages we use a Copy Input extractor to cut the field sourceAddress into the field source_ip.

The expected resulting geoip fields would be:
source_ip_geo_country
source_ip_geo_country_iso

The actual resulting geoip resolved fields look like the below:
source_geo_country
source_geo_country_iso

This is inconsistent with the behaviour if the fieldnames are not source_ip, destination_ip or host_ip. It's also inconsistent with the way that pipeline lookups work if configuring geoip lookups separately. It looks like this might be by design (snippet below), but it causes some overwrite problems other fields named source or destination, or host exist. 

Is this by design, and will this behaviour be permanent?

public class GeoIpResolverEngine {
private static final Logger LOG = LoggerFactory.getLogger(GeoIpResolverEngine.class);

/**
* A mapping of fields (per the Graylog Schema) that to search that contain IP addresses. When the user opts to
* enforce the Graylog Schema ONLY these fields will be checked; otherwise, all message fields will be checked.
* to see if they have valid Geo IP information.
*
* <p>
* The mapping is <b>field name</b> -> <b>new message field prefix</b>, where field_name is the field name expected in the message
* which will be searched in the GeoIP database, and the new message field prefix is the prefix for the new field with the GeoIP data
* that will be inserted into the message.
* </p>
*/
private final Map<String, String> ipAddressFields = new ImmutableMap.Builder<String, String>()
.put("source_ip", "source")
.put("host_ip", "host")
.put("destination_ip", "destination")
.build();

**Comment by waab76** [comment]
The Geo-Location Processor has a new `Enforce default Graylog schema` option.  

When that option is off, the processor should behave as it has in the past.  It scans all fields in the message looking for IP addresses and adds the `_geo` fields for each IP field it finds.  When operating in this mode, it does follow the naming convention of using the field name as the prefix for the newly added geo-location fields.  So if you are running with this option disabled, an IP in the `source_ip` field will result in the addition of a `source_ip_geo_country` field.

When the `Enforce default Graylog schema` option is on, the Geo-Location processor only looks for the fields `source_ip`, `host_ip`, and `destination_ip` and the added geo-location fields follow the Graylog Information Model schema as specified in our [Graylog Schema documentation](http://schema.graylog.org).  So if you are running with this option enabled, an IP in the `source_ip` field will result in the addition of a `source_geo_country` field as specified by the [GIM Source Fields schema](https://schema.graylog.org/en/stable/schema/entities/source.html).

Are you running with the `Enforce default Graylog schema` option enabled or disabled?

**Comment by jjkoster** [comment]
Hi Rob, thanks for the response. We are running with the enforce default Graylog schema off.

**Comment by waab76** [comment]
Talked to the developer who worked on this and he confirmed that there is a bug causing the behavior that you're observing.  Thanks for letting us know.

**Comment by H2Cyber** [comment]
@waab76 here is another observation which might be related : https://github.com/Graylog2/graylog2-server/issues/12788#issuecomment-1146396627
