### ISSUE TITLE
Alerts -  Event Definitions Link: opens edit page rather than summary page

### ISSUE THREAD

**Issue by jjkoster** [Graylog2/graylog2-server#12910]
I'm not sure if anyone else agrees with me, but clicking on an event title in the Event Definitions page should go to the "Edit" page rather than the "Summary" page. If that is changed, the "Edit" button could then be changed with a "Summary" button on the right of the page. In my experience the Edit page is used almost exclusively over the Summary page. The Summary page does not tell you too much more than the actual Events Definition page, so it has a much lower level of usefulness.
Others may have got used to this, but I just keep finding myself having to press back and then having to search for the event definition again. In the end I now just append /edit to the summary page URL.

Thanks,

Jeremy

**Comment by bernd** [comment]
We will probably keep the current behavior consistent with other UI pages. But we can add an "Edit" button to the overview page to make it easier to go to the edit page.
