### ISSUE TITLE
Allow option for "doc_values" for all not_analyzed fields beyond just timestamps

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-server#1291]
Since ES 2.0 might be making doc_values=true the default setting for not_analyzed fields, is it worth getting ahead of the curve and defining not_analyzed fields within Graylog indices as doc_values=true?

Or at least giving the option in the config file like you do with timestamps?

**Comment by joschi** [comment]
We currently do not plan to add a configuration setting for making all fields doc values.

If you absolutely want to store all fields as doc values, I recommend creating an Elasticsearch index template (https://www.elastic.co/guide/en/elasticsearch/reference/1.6/indices-templates.html) for the time being.

**Comment by bernd** [comment]
Closing this, please re-open if needed. Thank you!
