### ISSUE TITLE
Improve data table usability

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#12923]
This issue is bundling feedback for improving general data table usability. They can be addressed separately or in a bundle:

- [x] #11675
- [x] #10936
- [x] #9998
- [x] Graylog2/graylog-plugin-enterprise#3499

**Comment by maxiadlovskii** [comment]
https://github.com/Graylog2/graylog2-server/issues/11675 
https://github.com/Graylog2/graylog2-server/issues/10936
https://github.com/Graylog2/graylog-plugin-enterprise/issues/3499
was fixed with this PR
https://github.com/Graylog2/graylog2-server/pull/13384
