### ISSUE TITLE
Api/search/universal/relative/histogram HTTP 404 Not Found

### ISSUE THREAD

**Issue by gianluca-valentini** [Graylog2/graylog2-server#12935]
Hi i’m using Graylog 4.1.6.
It is an upgrage from an older version.
I used in my previous java rest client the route **api/search/universal/relative/histogram** than now is no longer available.

What I should use to have the same old response?

I don’t find any remove o api changes in the graylog upgrade docs ([Upgrading to Graylog 3.0.x - Upgrading Graylog](https://docs.graylog.org/docs/graylog-3-0)

Thanks

**Comment by patrickmann** [comment]
This was deprecated in 3.3 in favor of the views API.
https://github.com/Graylog2/graylog2-server/pull/8323
