### ISSUE TITLE
more informational log messages regarding extractor errors

### ISSUE THREAD

**Issue by maniel** [Graylog2/graylog2-server#1297]
when getting extractor related errors like
>MapperParsingException[failed to parse [timestamp]]; nested: MapperParsingException[failed to parse date field [Jul 3 2015 09:03:57.018], tried both date format [yyyy-MM-dd HH:mm:ss.SSS], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: "Jul 3 2015 09:03:57.018"];

it's hard to backtrack the specific extractor generating that error, in this case i know there is some date extractor with bad timestamp format to parse, that's all, tailing logs directly i can see failing extractor id, but it's hard to find it either, because extractors are input specific, with some mongodb query i was able to find related input but it **shouldn't be the case**, the log messages should indicate broken extractor or at least point at input to which said extractor belongs, or ideally link to  them

it would be very beneficial when having larger numbers of inputs/extractors

**Comment by bernd** [comment]
This is actually an error message from Elasticsearch and is not related to extractors. It means that Elasticsearch is unable to parse the date.

You can use an extractor converter to convert the timestamp to something Elasticsearch can parse. http://docs.graylog.org/en/1.1/pages/extractors.html#the-flexible-date-converter

Hope that helps. Closing this issue now, please re-open if needed. Thank you!
