### ISSUE TITLE
Remove API code for legacy alerting management pages.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#12988]
## Description

A while ago we rewrote the alerting UI. With [this PR](https://github.com/Graylog2/graylog2-server/pull/12987) we removed the related legacy UI code. The next step is removing the related backend code.

Here is an overview of the no longer needed API routes.

```
/streams/${streamId}/alerts/conditions
/streams/${streamId}/alerts/conditions/${alertConditionId}
/streams/${streamId}/alerts/sendDummyAlert
/streams/${streamId}/alerts/conditions/${conditionId}/test
/alerts/conditions/types
/alerts/conditions
/streams/alerts/${alertId}
/streams/${streamId}/alerts
/streams/alerts/paginated
/streams/alerts
```

Please note we still want to support legacy alarm callbacks, until the next major release.

## Your Environment

* Graylog Version: 4.3

**Comment by boosty** [comment]
Sounds like a candidate for removal in 5.0.

**Comment by mpfz0r** [comment]
We can also remove all the stream related alerting logic:
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/streams/StreamService.java#L65-L83

**Comment by patrickmann** [comment]
For those less familiar (like myself): This issue only aims to remove backend code that relates to stream-based alerting. It does not remove legacy alarm callbacks. Eventually we would want to remove those too; but that will require migration code to ensure that 3rd party plugins don't break.
