### ISSUE TITLE
"Edit Index Set" not working on Index Set detail page 

### ISSUE THREAD

**Issue by moesterheld** [Graylog2/graylog2-server#12997]
Clicking on "Edit Index Set" on the detail page of an index leads to a "Loading component failed: Cannot read properties of null (reading 'indexSet')" error in the latest SNAPSHOT version. (see video)
Clicking on "Edit" in the index set list works.

## Steps to Reproduce (for bugs)
1. List index sets
2. Click on any index set
3. Click on "Edit Index Set"

https://user-images.githubusercontent.com/33032967/177190780-15230ea2-c2b5-4ef1-968c-a984fb1b4b67.mov
![Bildschirmfoto 2022-07-04 um 18 08 13](https://user-images.githubusercontent.com/33032967/177190795-db5c7480-0daf-47bf-82b6-be76b17fa232.png)

## Your Environment
Latest GL Snapshot (locally & smd), bug not reproducible in 4.3

**Comment by HungryHowies** [comment]
Having the same issues as shown here for GL 4.3.3, CentOS 7 , ES 7.10 and Mongo 4.4.

https://community.graylog.org/t/edit-index-set-t-state-is-null-in-graylog-4-3-3/24721

**Comment by mpfz0r** [comment]
> bug not reproducible in 4.3

That's not (entirely) correct. I've seen this bug on 4.3.3
And I created a backport: https://github.com/Graylog2/graylog2-server/pull/13119
