### ISSUE TITLE
remoteAddress.getAddress().getHostAddress() error 

### ISSUE THREAD

**Issue by Archer1003** [Graylog2/graylog2-server#13008]
1、Deploy graylog in a docker container, write a custom plugin, and get the HostAddress exception after accepting the log；

remoteIp should be the ip of the host sending the log, but occasionally the gateway ip of the graylog container is obtained code show as below:

The code is as follows:

```
@Override
@Nullable
public Message decode(@Nonnull RawMessage rawMessage) {
    String msg = new String(rawMessage.getPayload(), StandardCharsets.UTF_8);
    LOG.info("decode msg is:{}",msg);
                   
    final ResolvableInetSocketAddress address = rawMessage.getRemoteAddress();
    final InetSocketAddress remoteAddress= address.getInetSocketAddress();

    String  remoteIp = remoteAddress.getAddress().getHostAddress();
    LOG.info(" remoteIp is :{}",remoteIp);
}
```
2、System environment:
CentOS 7.9
Docker 20.10.3
Graylog 3.3
mongo 3
Elasticsearch - oss 6.8.14

3、Solutions that have been taken:
Uninstall the container, reinstall the deployment solution

4、How can the community help:
Ask if any developers in the community have responded to this problem, and if so, how to completely solve this problem. If not, is there any suggestion that can solve this problem.

Finally, thanks to the graylog team and its developers

**Comment by bernd** [comment]
@Archer1003 The `RawMessage#getRemoteAddress` method can return `null`. We cannot ensure that there is always a value for the remote address, and we also cannot ensure that the value will always be the remote address of the log sender. What value is present and how "good" the value is depends on the input type.
Each input is responsible for adding the remote address value to the `RawMessage`.

**Comment by Archer1003** [comment]
@bernd  OK，think you
