### ISSUE TITLE
Index Time rotation strategy: Add option to skip rotation on empty index sets

### ISSUE THREAD

**Issue by boosty** [Graylog2/graylog2-server#13028]
## What?

When using the _Index Time_ rotation strategy, we should add an option to skip rotation when the index set contains 0 messages.

## Why?

Especially with Illuminate we see a lot of index sets being created, but not all of them might be used. When using a time based rotation (e.g. daily), this can lead to huge number of empty indexes / shards being created, which require system resources.

The _Index Message Count_ and _Index Size_ rotation strategies naturally do not have this problem.

## Your Environment

* Graylog Version: 4.3

**Comment by boosty** [comment]
@kodjo-anipah Could you please backport this to 4.3?

**Comment by kodjo-anipah** [comment]
@boosty yes on it
