### ISSUE TITLE
Garbage collect empty indexes in unused index sets

### ISSUE THREAD

**Issue by boosty** [Graylog2/graylog2-server#13031]
## What?

Add an optional periodic job to clean up empty indexes in unused index sets.

The job should write information about deleted empty indexes to the system log.

## Why?

For example when using Illuminate, many index sets get created, but not all of them might actually be used. When using a time based rotation strategy (e.g. daily rotation), we can end up with a lot of empty indexes, with a lot of empty shards.

With too many indexes, it is possible to run into 413 HTTP errors on Elasticsearch queries. With too many shards, the Elasticsearch/OpenSearch performance will suffer.

We created a separate issue to optionally prevent rotation of empty index sets in the first place, but this will only help with newly created indexes, not existing ones: https://github.com/Graylog2/graylog2-server/issues/13028

## Your Environment

* Graylog Version: 4.3

**Comment by boosty** [comment]
I thought about this a bit more and would only give it a low priority, or actually close it.

The reasons:
- We are finishing https://github.com/Graylog2/graylog2-server/issues/13028 right now, which will help preventing empty indexes from being _rotated_ in the first place
- If empty indexes exist already, they will usually be deleted at some point by their _retention_ config 
- Users already have the choice to manually delete empty indexes (via the UI or API)

**Comment by patrickmann** [comment]
Closing this based on @boosty comments above.
Makes sense to me - no need to have this lingering in the backlog.
