### ISSUE TITLE
MapperParsingException NumberFormatException

### ISSUE THREAD

**Issue by rockaut** [Graylog2/graylog2-server#1306]
`MapperParsingException[failed to parse [Duration]]; nested: NumberFormatException[For input string: "1.1406483"];`
and
`MapperParsingException[failed to parse [Duration]]; nested: NumberFormatException[For input string: "1,1406483"];`

I get this message under "System \ Indexer Errors" since Update 1.1.3 ( from 1.0.1 ). Before the update it worked - and i don't see the problem.

I managed to workaround the problem by - you guessed it - not sending the value as a string ... but i think it should work nonetheless.

**Comment by joschi** [comment]
Could you please check the logs of your graylog-server instance(s) for this error message and post the surrounding messages? Especially stack traces would be very useful.

**Comment by joschi** [comment]
No reply since 18 days. Closing issue.
