### ISSUE TITLE
Single command for backing up/restoring graylog server data

### ISSUE THREAD

**Issue by micahhausler** [Graylog2/graylog2-server#1310]
I'm having a tough time getting mongo and Elasticsearch backed up in tandem, having to learn the backup/restore procedures for both products. It would be awesome to have a `graylogctl backup --out /some/dir` and `graylogctl restore /path/to/backup`

**Comment by bernd** [comment]
Please open a feature request in our ideas portal for this. Thank you very much!

https://www.graylog.org/product-ideas/
