### ISSUE TITLE
Show Title of dashboard on page

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#13116]
## What?

When working with dashboards, I run into the issue where there isn't any visible indication of what dashboard you are looking at

The page title does show the dashboard title, but it would be very helpful from a UX perspective to see this a the top of the page.

## Why?

Dashboard Title: When working across with multiple dashboards at once (either multiple tabs in the same browser window, or multiple browser windows), it's difficult to keep track of which dashboard is which.

## Your Environment

* Graylog Version: Graylog 4.3.3+86369d3
* Elasticsearch Version: Opensearch 1.3.4
* MongoDB Version: 4.4.15
* Operating System: Ubuntu Server 20.04
* Browser version: Chrome 103

**Comment by H2Cyber** [comment]
Another nice to have: being able to copy an entire page from one dashboard to another.

**Comment by dennisoelkers** [comment]
Hey @drewmiranda-gl,

those are valid points, thank you for submitting this! We are tracking the tab ordering issue in #7470 already though, can you please reduce this issue to be only about displaying the dashboard title?

**Comment by drewmiranda-gl** [comment]
> 

Done!
