### ISSUE TITLE
Edit graylog-internal template

### ISSUE THREAD

**Issue by hebval** [Graylog2/graylog2-server#13133]
Hi,

I would like to edit the graylog-internal template, and add an "index.mapping.total_fields.limit" row.

- Is this possible ?
- Will this new setting be applied on the next rotation ?
- How could I do it ? Something like this ?

curl -X PUT localhost:9200/_template/graylog-internal -H 'Content-Type: application/json' -d'{ "index.mapping.total_fields.limit": 1100 }'

Thanks for your help!

**Comment by bernd** [comment]
We have documentation on custom index templates: https://docs.graylog.org/docs/elasticsearch#custom-index-mappings

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
