### ISSUE TITLE
Boolean fields are not automatically extracted as it happens for other types

### ISSUE THREAD

**Issue by PaoloBoniNektan** [Graylog2/graylog2-server#1315]
I'm using Graylog2 with Fluentd.
Fluentd is sending the following message to Graylog:
```
{
    "datetime": "******************",
    "thread": "ForkJoinPool-1-worker-3",
    "method": "POST",
    "user": "******************",
    "path": "******************",
    "secure": true,
    "remote_address": "******************",
    "user_agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36",
    "elapsed_time_ms": 89,
    "response_status": 200,
    "latitude": ******************,
    "longitude": ******************,
    "city": "******************",
    "country_name": "******************",
    "country_code3": "******************",
    "region": "******************"
}
```
As you can see "secure" is a boolean value. This field is the only one that is not extracted as available message field in Graylog.
I tried adding other boolean fields and the behaviour is always the same, boolean fields are not extracted.
Is this something related to Graylog?

**Comment by joschi** [comment]
Thanks for bringing this up!

The GELF specification (1.0 and 1.1) currently only supports string and numeric values in GELF messages: https://www.graylog.org/resources/gelf

Graylog accordingly ignores boolean message attributes in the current implementation (https://github.com/Graylog2/graylog2-server/blob/1.1.4/graylog2-inputs/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java#L186-201).

As a workaround you'll have to include those boolean values as a string or as a number (e. g. 0 = false, 1 = true) in your GELF messages.

**Comment by PaoloBoniNektan** [comment]
Thank you! :)
