### ISSUE TITLE
API users problem when new graylog server joins the cluster

### ISSUE THREAD

**Issue by Ghilteras** [Graylog2/graylog2-server#1316]
I noticed that when I create a new graylog server and I join it to an existing clusters then I cannot query its local API using the users (ldap and local) that are granted to access the web interface. Is there a way to work around this?

**Comment by joschi** [comment]
Do all Graylog nodes share the same MongoDB database and have the same `password_secret` (https://github.com/Graylog2/graylog2-server/blob/1.1.4/misc/graylog2.conf#L9-11)?

**Comment by bernd** [comment]
Closing this, please re-open if you still have problems. Thank you!
