### ISSUE TITLE
Couldn't get Grok to extract metadata

### ISSUE THREAD

**Issue by Kanshiroron** [Graylog2/graylog2-server#1317]
Hello,

I installed Graylog2 yesterday from version 1.1 on Debian/Docker, and I was trying to configure it to extract data from logs with Grok patterns.
When I try the pattern in the edit view, it actually extracts everything fine but not with live input...

___________________

Here is an exemple:
172.16.52.3 - - [21/Jul/2015:23:01:04 +0000] "POST /api/space/5dVHZR_qKwaEOc7eOtAYihcj_k85KwyyKABLkv5OyMg/user_certificates HTTP/1.1" 200 3989 

%{IPV4:ip} - - \[%{JAVADATE: javadate}\] "%{TEXT: http_verb} %{URL: url} HTTP\/%{NUMBER: http_version}" %{NUMBER: http_status} %{NUMBER: process_time}

The result :
http_status     200
http_verb       POST
http_version  1.1
javadate        21/Jul/2015:23:01:04 +0000
process_time 3989
url                  /api/space/5dVHZR_qKwaEOc7eOtAYihcj_k85KwyyKABLkv5OyMg/user_certificates
BASE10NUM 3989
ip                   172.16.52.3

![test](https://cloud.githubusercontent.com/assets/5125105/8822714/bbed460a-3067-11e5-9b73-f3bd1fc51830.jpg)

__________________

But when I test it with live input, it only extracts the ip:

application_name       logger
BASE10NUM              3989
facility                         user-level
gl2_remote_ip            172.19.128.8
gl2_remote_port        43274
ip                                172.16.52.3
level                            5
message                    172.16.52.3 - - [21/Jul/2015:22:59:49 +0000] "POST /api/space/5dVHZR_qKwaEOc7eOtAYihcj_k85KwyyKABLkv5OyMg/user_certificates HTTP/1.1" 200 3989 
source                        6e9448acfcec

![input](https://cloud.githubusercontent.com/assets/5125105/8822721/c31c0b00-3067-11e5-8fbe-7737577df43c.jpg)

Also, where does the "BASE10NUM" come from, it looks to be linked to the process_time property, but how/why it poped-up? (I mean, the name BASE10NUM, is part of the Grok pattern but I don't know why it shows up)
Thanks for your help and feedback

**Comment by edmundoa** [comment]
Hi,

Your Grok pattern is sometimes using spaces between the pattern name and the field name and that is creating the issue, at the same time that explains why the IP gets extracted but not other fields. Please ensure you don't use spaces after colons and see if it works.

Regarding the `BASE10NUM` field, it comes out of your grok patterns. Please edit the `NUMBER` pattern in System -> Grok Patterns, and add `:UNWANTED` to the patterns it uses, i.e. `%{BASE10NUM:UNWANTED}`.

**Comment by Kanshiroron** [comment]
Hello edmundoa, thanks for your time and help, it's an awesome answer!
Best,
