### ISSUE TITLE
Support MongoDB versions greater than 4.4

### ISSUE THREAD

**Issue by Nothing4You** [Graylog2/graylog2-server#13199]
## What?
Similar to #10720.
Graylog should support current MongoDB versions.

## Why?

Graylog currently only supports MongoDB versions up to 4.4.
In the meantime, MongoDB versions 5.0 and 6.0 have been released.
New installations of MongoDB already default to version 6.0.

Version 5.0 still allows compatibility with 4.4 by setting the appropriate `featureCompatibilityVersion`, however, version 6.0 drops support for 4.4 compatibility.

Note that MongoDB 4.4 is still supported until February 2024:
https://www.mongodb.com/support-policy/lifecycles

MongoDB already only supports MongoDB 5.0+ on Debian 11, which may also be the case for Ubuntu 22.04 when MongoDB starts supporting it:
https://www.mongodb.com/docs/manual/administration/production-notes/#platform-support-matrix

On MongoDB 5.0 with 4.4 compatibility I already see the following warning in the logs after starting up Graylog:
```json
{
    "attr": {
        "clientInfo": {
            "driver": {
                "name": "mongo-java-driver|legacy",
                "version": "3.12.1"
            },
            "os": {
                "architecture": "amd64",
                "name": "Linux",
                "type": "Linux",
                "version": "5.18.16-arch1-1"
            },
            "platform": "Java/Oracle Corporation/1.8.0_345-b01"
        },
        "op": "query"
    },
    "c": "COMMAND",
    "ctx": "conn1",
    "id": 5578800,
    "msg": "Deprecated operation requested. For more details see https://dochub.mongodb.org/core/legacy-opcode-compatibility",
    "s": "W",
    "t": {
        "$date": "2022-08-07T18:53:19.354+00:00"
    }
}
```

## Your Environment

* Graylog Version: 4.3.3+86369d3
* Elasticsearch Version: N/A
* MongoDB Version: 5.0.9
* Operating System: N/A
* Browser version: N/A

**Comment by kto2038** [comment]
Please update the system requirements.
https://docs.graylog.org/docs/installing
