### ISSUE TITLE
Graylog2 CPU Usage

### ISSUE THREAD

**Issue by sebyfrancis** [Graylog2/graylog2-server#132]
Hi Lennart,

I'm using the latest version of graylog2. Initially the CPU was more than 100% and when set the "processor_wait_strategy" to blocking brought down the CPU usage less than 60% even without no inputs/messages. 

Is this a known issue? Can you please help me to fix it?

Thanks,
Seby.

**Comment by mhipo1364** [comment]
Hi, I just installed graylog, but my CPU usage is 100%, I'm using java version "1.7.0_79" . when  I start graylog-server or graylog-web, CPU gets crazy

**Comment by joschi** [comment]
@mhipo1364 Please use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or our [IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general questions around Graylog.
