### ISSUE TITLE
Graylog improperly handling timestamps

### ISSUE THREAD

**Issue by joshuascott** [Graylog2/graylog2-server#1320]
I have a Cisco FireSIGHT that is sending logs to Graylog. Graylog is parsing the messages improperly and seting adding 7 hours to the timestamp. Even if it is assuming UTC because it cannot determine the time zone how is it that its adding 7 hours when I live in PDT which is minus 7 hours from UTC?

See an example message below

<118>Jul 22 15:53:51 btsdefense SFIMS: [119:15:1] http_inspect: OVERSIZE REQUEST-URI DIRECTORY [Impact: Potentially Vulnerable] From "btsips1" at Wed Jul 22 15:53:50 2015 UTC [Classification: Pornography was Detected] [Priority: 2] {tcp} 10.107.5.116:60603->10.106.240.176:9004

The message clearly has the UTC timezone in it. I have other devices that call out timezone the same way and they get tagged properly.

I have tried playing around with extractors to see if they will work but so far nothing has been successful.

All of my timestamps are set to PDT. Including the server that Graylog is installed on as well as Graylog config files.

![capture](https://cloud.githubusercontent.com/assets/3880830/8839650/983ac528-308c-11e5-96db-f1363c63046c.PNG)

**Comment by edmundoa** [comment]
Hi,

If I understood it correctly, you are referring to an extracted timestamp from the log message, not to the default timestamp value in the syslog message. Could you please share the configuration of the extractor you use to get the date? It's hard to debug this issue otherwise.

**Comment by joshuascott** [comment]
Yes correct the timestamp that is being sent by the device contains the correct timestamp. Graylog extracts the timestamp then adds 7 hours to it. The timestamps being sent by my device are set to UTC. I live in PDT which is UTC -7 so I do not get alerts until 7 hours AFTER the fact, and they do not show up in my dashboard. I can find the message if I set the time to include messages that are at least 7 hours in the future though.

I guess I am confused as to why graylog wouldn't just tag the message with timestamp that matches when the message was received by the server itself if it cannot determine the timestamp of the message.

Here is the details from the extractor I configured.

Configuration:

  *   regex_value: ([a-zA-Z]{3}\s[a-zA-Z]{3}\s[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}\s[0-9]{4}\sUTC)
Converters

  *   date
     *   date_format: eee MMM dd HH:mm:ss YYYY zzz

**Comment by joschi** [comment]
The [`DateConverter`](https://github.com/Graylog2/graylog2-server/blob/1.1.4/graylog2-server/src/main/java/org/graylog2/inputs/converters/DateConverter.java) is indeed using the locally configured timezone as timezone for the converted dates.

We've changed that in Graylog 1.1.x for the flexible date converter (https://github.com/Graylog2/graylog2-server/blob/1.1.4/graylog2-server/src/main/java/org/graylog2/inputs/converters/FlexibleDateConverter.java), so you might use that as a workaround for now.

**Comment by joshuascott** [comment]
Using the flexible date converter seems to have fixed my issue. Thanks!
