### ISSUE TITLE
ERROR: The Elasticsearch cluster state is RED which means shards are unassigned. This usually indicates a crashed and corrupt cluster and needs to be investigated. Graylog will shut down.

### ISSUE THREAD

**Issue by roshan3133** [Graylog2/graylog2-server#1323]
Why this happening. I checked the today morning the graylog-server and graylog-webinterface both down. i checked in graylog server logs i found these logs. i have try to start graylog to but in logs said org.graylog2.periodical.IndexRetentionThread - Elasticsearch cluster not available, skipping index retention checks 
then i restarted elasticsearch and then i start graylog and now it's working fine.
Why this happen.

**Comment by joschi** [comment]
Kindly use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or our [IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general support requests.
