### ISSUE TITLE
Legacy Search Keyword - "message": "must not be empty"

### ISSUE THREAD

**Issue by alexlansovich** [Graylog2/graylog2-server#13249]
Legacy Search Keyword dont work after upgrade to Graylog 4.3.5+32fa802

when make api request
query - any
keyword - last monday(for example)

got response

[
  {
    "message": "must not be empty",
    "message_template": "{javax.validation.constraints.NotEmpty.message}",
    "path": "KeywordSearchResource.searchKeyword.arg2",
    "invalid_value": null
  }
]

Version:
4.3.5+32fa802, codename Noir
JVM:
PID 15315, Red Hat, Inc. 1.8.0_342 on Linux 3.10.0-1160.59.1.el7.x86_64

**Comment by janheise** [comment]
`fields` and `timezone` are two more required parameters that are missing from the request (at the time of the ticket, probably only `fields`, `timezone` was added later) - but for reference with current graylog versions.

The required parameters can be checked using the api browser (from system/nodes)
