### ISSUE TITLE
Hide/Show UI elements in pipelines based on permissions.

### ISSUE THREAD

**Issue by AntonEbel** [Graylog2/graylog2-server#13252]
## What?

Hide or show UI elements such as Delete, Create, and Edit in the Pipeline view, depending on permissions.

## Why?

Currently, these UI elements are displayed regardless of user permissions, and when a user clicks the "Delete" button, for example, a "Missing Permission" error page is displayed.

**Comment by bernd** [comment]
We talked about the topic in the triage and figured that disabling (grey out) the buttons is preferable to removing the buttons.
