### ISSUE TITLE
otx_lookup_domain returns nothing if OTX API rate limit is reached

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/graylog2-server#13288]
For at least `otx_lookup_domain`, the pipeline function will fail if OTX API returns an unexpected result, such as 429 Too Many Requests. 

## Expected Behavior
If `otx_lookup_domain` experiences a successful connection to the OTX API but a failure return code, return either something in message processing, or in Processing and Indexing Failures pipeline, or any other visible and parseable failure that customer can use to understand when/why their OTX domains are failing. This way, customer has awareness they've hit an API rate limit and need to do something about that, instead of just having no expected threat data on their messages. 

## Current Behavior
If `otx_lookup_domain` experiences a successful connection to the OTX API but a failure return code, nothing apparent happens in the web UI. It is noted that `otx_lookup_domain` logs to `server.log` which is how this situation was discovered, but if e.g. customer hits the API limit, the function returns nothing, they will lose the threat intel data in their messages, and additionally have no visibility for this situation, other than manually looking into `server.log` to find out why their expected data is missing from their messages.

## Steps to Reproduce (for bugs)
1. Get OTX API key set to default limits
2. Set up `otx_lookup_domain` in a pipeline to query up threat data
3. Send a LOT of queries to OTX. Anecdotal Google searching suggests that this is a rate that would be >10000 queries per hour, but OTX's rate limiter seems to operate on velocity, so a large number in a short period of time produces the same outcome.
4. Confirm API rate limit messages in `server.log`, see messages no longer have threat data OR a failure on them. 

## Context
HS-1025869412

## Your Environment
Seen in the wild in Graylog Cloud, but would extend to Graylog in general.

**Comment by patrickmann** [comment]
This is the same issue as Graylog2/graylog-plugin-cloud#1046.
Closing this as duplicate.
