### ISSUE TITLE
Create aggregation of log data into new summary log files

### ISSUE THREAD

**Issue by eeurope** [Graylog2/graylog2-server#1328]
I want to use graylog to anaylise the performance of our applications. The applications can delivers log data in JSON. The individual logs are not very useful for evaluation though, but aggregated data of these logs are!

Is there a way to evaluate data in log files, aggregate this information by using specific rules und write a kind of summary log file with this data. The summary log data should then be used for evaluation and alerts.

Example:
The log files contain infomation about domains inside the JSON e.g. "domain": "abc.com"
I would like to check all logs in a timeframe of 24 hours, define the number of unique domain names within this period and write this into a new log file using the new variable "unique domains".

In the dashbord the history of uniqeu domains per day shall be visualized then.

For alerting my idea is to calculate the average number of unique domains per day within the last 20 days including the standard deviation und then test the current value of unique domains per day against this. Only if the number of unique domains per day is deferring too much (say more than double standadr deviation) from the last 30 day average a noticiation should take place.

I would appreciate it vey much if somebody could help me for the realization. Since the GREFT format would suit us perfectly I would like to use graylog to achieve this, but I do not see how to do it at the moment.

Volker

**Comment by jalogisch** [comment]
we are not planing to implement this. if you still have this issue you would need to write some script against the graylog api to get your data.
