### ISSUE TITLE
More options in the Event Definitions "Show" drop down list

### ISSUE THREAD

**Issue by H2Cyber** [Graylog2/graylog2-server#13305]
When managing hundreds of Event Definitions, the UI defaults to displaying the first 10 (user choice is not persisted), and the maximum display limit of 50 is too low.

Therefeore, the purpose of this feature request is to add more options in the Event Definitions Show drop down list, for example "100", "200" and ideally a "Display all" option as well. 
 
![Event Definitions Dropdown List](https://user-images.githubusercontent.com/764189/186917065-cd222b60-ea04-4023-886f-6a59c72ba309.png)

## Your Environment
* Graylog Version: 4.3.5

**Comment by H2Cyber** [comment]
I will aslo add that the available options (10, 25, 50) are inconsistant with other menu areas in Graylog (Dashboards, Streams, etc.) which offer the options 10, 50 and 100.

**Comment by mnin** [comment]
We have discussed this internally and agreed to adjust the options here to 10, 50 and 100.
