### ISSUE TITLE
CPU performance issues with Graylog 4.2.12 + Java 17

### ISSUE THREAD

**Issue by giangi** [Graylog2/graylog2-server#13306]
## Expected Behavior

The performance of Graylog 4.2.12 running on Java 17 (suggested by installation docs) should be comparable to what observed running on Java 8.

## Current Behavior

For a more extensive discussion see the community thread: [High CPU usage after upgrade from Graylog 4.1 + Java 8 to Graylog 4.2 + Java 17 ](https://community.graylog.org/t/high-cpu-usage-after-upgrade-from-graylog-4-1-java-8-to-graylog-4-2-java-17/25432)

After upgrading an installation from Graylog 4.1.14 + Java 8 to 4.2.12 to Java 17 I observed a noticeable (~4x) increase in CPU usage. Graylog and Java were the only updated parts of the installation.

Replacing Java 17 with Java 8 brought back CPU usage to the levels observed before the upgrade.

This was previously observed in a very similar way running Graylog 4.1.11 + Java 11. The performance drop vanished when switching to Java 8. The issue was curiously absent on 4.1.1 + Java 11. See community thread: [Graylog 4.1.x high CPU usage after updating for log4j](https://community.graylog.org/t/graylog-4-1-x-high-cpu-usage-after-updating-for-log4j/22294).

## Possible Solution

I suspect, though I lack the expertise to support my claim, that some change introduced between 4.1.1 and 4.1.9 influences performance when running on Java > 8, and that this change is still in effect in 4.2.12.

Apart from the obvious reproduction and fix, which would be ideal if this is confirmed to be a non-local issue, clarify the supported and suggested version of Java in the docs, and that it may have an effect on the final performance.

## Steps to Reproduce (for bugs)

1. Run a load test on a Graylog 4.2.12 + Java 17 installation, observing CPU usage
2. Run the same on a Graylog 4.2.12 + Java 8

## Context

Normal operation of a Graylog cluster mainly ingesting UDP and TCP RFC5424 Syslog, running pipelines to enrich messages with fields (GROK, JSON, regular expressions) and a few alerts.

## Your Environment

* Graylog Version: 4.2.12
* Java Version: 17 and 8
* Elasticsearch Version: OSS 7.10.2
* MongoDB Version: 4.2
* Operating System: Debian 10 buster
* Browser version: Not relevant

**Comment by janheise** [comment]
Hi @giangi, which hardware platform are you using? I'm guessing Intel but just want to make sure.

**Comment by giangi** [comment]
> Hi @giangi, which hardware platform are you using? I'm guessing Intel/AMD but just want to make sure.

Hi @janheise , the `graylog-server` nodes are 4 vCPU VMs running on an on-premises libvirt/KVM cluster of physical hypervisors with Intel(R) Xeon(R) Gold 5118 CPUs.

**Comment by mpfz0r** [comment]
@giangi  I tried to reproduce this with 4.3.8 using Java 8 and 11 but couldn't. (Actually I've been also benchmarking Graylog 5.0 with Java 17 but that's not related)
Is this still an issue for you? Could you try to figure out which Graylog thread is responsible for the CPU consumption?

You could be running something like `top -n 1 -H -p $(cat /tmp/graylog.pid)` while the spike occurs.
The output would look somewhat like this:
```
Threads: 224 total,  11 running, 213 sleeping,   0 stopped,   0 zombie
%Cpu(s): 80,6 us, 18,8 sy,  0,0 ni,  0,6 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
MiB Mem :  64059,5 total,  17253,8 free,  29197,4 used,  17608,3 buff/cache
MiB Swap:  67540,0 total,  64477,7 free,   3062,3 used.  32476,9 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                              
 475357 marco     20   0    9,9g   3,7g  30492 R  94,1   5,9   0:05.71 inputbufferproc                                                                                                                                                      
 475402 marco     20   0    9,9g   3,7g  30492 R  70,6   5,9   0:09.65 processbufferpr                                                                                                                                                      
 475422 marco     20   0    9,9g   3,7g  30492 R  70,6   5,9   0:12.46 LocalKafkaMessa                                                                                                                                                      
 475403 marco     20   0    9,9g   3,7g  30492 R  58,8   5,9   0:09.24 processbufferpr                                                                                                                                                      
 475400 marco     20   0    9,9g   3,7g  30492 R  47,1   5,9   0:09.31 processbufferpr                                                                                                                                                      
 475401 marco     20   0    9,9g   3,7g  30492 R  47,1   5,9   0:09.24 processbufferpr                                                                                                                                                      
 475355 marco     20   0    9,9g   3,7g  30492 S  35,3   5,9   0:03.33 inputbufferproc                                                                                                                                                      
 475356 marco     20   0    9,9g   3,7g  30492 S  35,3   5,9   0:03.16 inputbufferproc                                                                                                                                                      
 475404 marco     20   0    9,9g   3,7g  30492 R  35,3   5,9   0:09.47 processbufferpr                                                                                                                                                      
 475393 marco     20   0    9,9g   3,7g  30492 S  23,5   5,9   0:03.99 outputbufferpro                                                                                                                                                      
 475394 marco     20   0    9,9g   3,7g  30492 S  23,5   5,9   0:04.00 outputbufferpro                                                                                                                                                      
 475392 marco     20   0    9,9g   3,7g  30492 S  17,6   5,9   0:04.01 outputbufferpro                                                                                                                                                      
 476806 marco     20   0    9,9g   3,7g  30492 R  17,6   5,9   0:01.85 netty-transport                                                                                                                                                      
 476807 marco     20   0    9,9g   3,7g  30492 R  17,6   5,9   0:01.87 netty-transport                                                                                                                                                      
 476808 marco     20   0    9,9g   3,7g  30492 S  17,6   5,9   0:01.85 netty-transport                                                                                                                                                      
 475530 marco     20   0    9,9g   3,7g  30492 S  11,8   5,9   0:00.86 outputbuffer-pr                                                                                                                                                      
 475531 marco     20   0    9,9g   3,7g  30492 S  11,8   5,9   0:00.88 outputbuffer-pr                                                                                                                                                      
 476809 marco     20   0    9,9g   3,7g  30492 S  11,8   5,9   0:01.83 netty-transport                  
```

Thanks :)

**Comment by giangi** [comment]
Hi @mpfz0r 

> Is this still an issue for you? Could you try to figure out which Graylog thread is responsible for the CPU consumption?

I did not make any further change to the cluster on which I was experiencing the issue, since performance was a concern being in production. I also admit that when @janheise initially replied, I took a very naive look at some his work and other code (e.g. [the POM for 4.2.12](https://github.com/Graylog2/graylog2-server/blob/4.2.12/pom.xml)) which made me thing that since the source/target was Java 8, maybe 4.2 was really never meant to be run reliably on higher Java versions. My sentiment since then has been that if this issue helped the developers to correct some compatibility issue early on, it was fine, but otherwise using Java 8 was fine until there was at least some security support for it and there was no benefit in pushing for higher versions.

Anyway, I could be able to sneak in a switch back to Java 17 on just one of the production nodes, just to briefly see the thread performance is different between a Java 8 and Java 17 node, but cannot give any guarantee due to the production nature.

May I ask if in your opinion this could be of any real help with current development or real installations? I am asking this because due to what I already said and given the [announcements about Graylog 5.0 targeting Java 17](https://www.graylog.org/post/announcing-graylog-5-0-beta-1/) I admit my plan was to be very conservative by doing:

* Update to 4.3 + Java 8, not expecting significant performance changes
* Update to 5.0 + Java 17, crossing all available appendages not to see any issue due to the more "official" support for Java 17

tackling issues only when no workaround was available.

**Comment by mpfz0r** [comment]
Hello @giangi 

> since the source/target was Java 8, maybe 4.2 was really never meant to be run reliably on higher Java versions

That's the Java byte code target. Newer Java versions can run older byte code without problem.
We also documented that running with Java 11 was possible. So yeah, even 4.2 should work just fine with newer Java versions.

> May I ask if in your opinion this could be of any real help with current development or real installations?

It might be. Knowing the thread that is responsible will however only give us a first clue.
Depending on how quickly you can provoke that issue, we would need more details from your setup
and probably more debugging iterations.

What we could also do, is that you remember to get us the `top` Graylog threads, the next time you hit this issue, and we take it from there. Which is hopefully never :crossed_fingers:

**Comment by mpfz0r** [comment]
Hi @giangi thanks for taking the time. Much appreciated. 
`netty-transport` narrows this down to certain Inputs. The processing (pipelines, extractors, etc.) are not concerned.

Can you tell us a bit more about your setup? Which inputs are you running and how are they configured? Which one is receiving the most traffic? Is the traffic equally distributed between the two nodes?

**Comment by giangi** [comment]
> Can you tell us a bit more about your setup? Which inputs are you running and how are they configured? Which one is receiving the most traffic? Is the traffic equally distributed between the two nodes?

The cluster is running global (all nodes) UDP and TCP syslog inputs.

<details><summary>Syslog UDP</summary><p>

```txt
allow_override_date: true
bind_address: 0.0.0.0
expand_structured_data: true
force_rdns: false
number_worker_threads: 4
override_source: <empty>
port: 1514
recv_buffer_size: 4194304
store_full_message: false
```

</p></details>

<details><summary>Syslog TCP</summary><p>

```txt
allow_override_date: true
bind_address: 0.0.0.0
expand_structured_data: true
force_rdns: false
max_message_size: 2097152
number_worker_threads: 4
override_source: <empty>
port: 1514
recv_buffer_size: 4194304
store_full_message: true
tcp_keepalive: false
tls_cert_file: <empty>
tls_client_auth: disabled
tls_client_auth_cert_file: <empty>
tls_enable: false
tls_key_file: <empty>
tls_key_password: ********
use_null_delimiter: false
```

</p></details>

Regarding traffic:

* It is overwhelmingly dominated by UDP (~99%)
* UDP balancing is message-per-message round-robin via IPVS
* TCP balancing is connection-oriented round-robin via HAProxy (TCP tunnel)
* UDP seems to achieve near-perfect balancing
* TCP can be unbalanced due to being used by only a few clients, but It never feeled concerning due to the low traffic

Each node during the test was processing ~700 messages/s. Here is a graph showing input rates and CPU usage for the whole test for the three nodes.

![Screenshot 2022-11-16 at 16-37-43 Graylog - Grafana](https://user-images.githubusercontent.com/1782060/202230261-0bc3e9d2-c442-40f2-9337-d55a6df70f5e.png)

Let me know if there is some other interesting detail you would like to know!

**Comment by mpfz0r** [comment]
Hi @giangi 
Thanks for the debugging infos. It actually helped me to find the issue. Working on a fix now :sweat_smile:
