### ISSUE TITLE
Change mlockall to true

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#1330]
It looks like the embeded elasticsearch component doesn't set mlockall to true. For ES it is recommended to have this enabled....

```
      "process" : {
        "refresh_interval_in_millis" : 1000,
        "id" : 21177,
        "max_file_descriptors" : 65536,
        "mlockall" : false
      },

```

**Comment by joschi** [comment]
The Elasticsearch node client being used inside Graylog usually* doesn't index or store any data nor does it coordinate cluster coordination, so activating mlockall in Graylog doesn't have the same effect as activating this setting for the Elasticsearch master and data nodes.

If you absolutely want to activate the setting, you can simply add [`bootstrap.mlockall: true`](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/setup-configuration.html#setup-configuration-memory) to the Elasticsearch configuration file for the Elasticsearch node client inside Graylog, specified by the [`elasticsearch_config_file`](https://github.com/Graylog2/graylog2-server/blob/1.1.5/misc/graylog2.conf#L87) setting in the Graylog configuration file.

This being said, we might add a similar option for Graylog in the future, but it's not clear if this really helps performance or just introduces another non-portable dependency in this specific case.

*: Configuration can be changed to index and store data as well, but this is very rarely being activated and only useful for quick test setups…
