### ISSUE TITLE
 Error executing action `run` on resource 'ruby_block[add node to server list]

### ISSUE THREAD

**Issue by plt-sun** [Graylog2/graylog2-server#1331]
After upgrade from v 1.1.4 to 1.1.5 and reconfiguring graylog, i got the failure decribed above:
 
 ruby_block[add node to server list] action run
    ================================================================================
    Error executing action `run` on resource 'ruby_block[add node to server list]'
    ================================================================================

    Errno::ECONNREFUSED
    -------------------
    Connection refused - connect(2) for "127.0.0.1" port 4001

    Cookbook Trace:
    ---------------
    /opt/graylog/embedded/cookbooks/graylog/libraries/registry.rb:17:in `set_master'
    /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:81:in `block (2 levels) in from_file'

    Resource Declaration:
    ---------------------
    # In /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb

     79: ruby_block "add node to server list" do
     80:   block do
     81:     $registry.set_master
     82:     $registry.add_gl_server(node['ipaddress'])
     83:     $registry.add_es_node(node['ipaddress'])
     84:   end
     85: end

    Compiled Resource:
    ------------------
    # Declared in /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:79:in `from_file'

    ruby_block("add node to server list") do
      action "run"
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      block_name "add node to server list"
      declared_type :ruby_block
      cookbook_name :graylog
      recipe_name "graylog-server"
      block #<Proc:0x000000042ee4e8@/opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:80>
    end

Running handlers:
[2015-07-31T10:00:16+02:00] ERROR: Running exception handlers
Running handlers complete
[2015-07-31T10:00:16+02:00] ERROR: Exception handlers complete
[2015-07-31T10:00:16+02:00] FATAL: Stacktrace dumped to /opt/graylog/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 6 resources updated in 5.707804974 seconds
[2015-07-31T10:00:16+02:00] ERROR: ruby_block[add node to server list] (graylog::graylog-server line 79) had an error: Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 4001
[2015-07-31T10:00:16+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by dennisoelkers** [comment]
It looks like you are having an issue with the chef cookbook. Could you please open an issue in [the corresponding project](https://github.com/Graylog2/graylog2-cookbook)?
