### ISSUE TITLE
Remove support for Elasticsearch 6

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#13317]
## What?

In version 5.0, we want to remove support for Elasticsearch 6, for the following reasons:

  - To limit the complexity of our Elasticsearch support code
  - To be able to remove [Jest](https://github.com/searchbox-io/Jest) which is currently blocking our jackson update

The scope of this issue contains removing the driver module and related code (e.g, version-specific index templates).

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by todvora** [comment]
ES6 removed from the whole codebase.
