### ISSUE TITLE
Very slow process message

### ISSUE THREAD

**Issue by dangmocrang** [Graylog2/graylog2-server#1334]
Hi,
My server: 64G RAM (32 for elasic and 32 for OS)
I have around 300~1200 msgs/s (with over 100 streams, each filter with gl2_remote_ip, no wildcard used). it has been a few days since my process buffer got increased to 100% utilized with ring_size is 65536 and the process buffer always keep at 100%, "the message been read in the last second" is very low about 20~500 msgs/s.
So with this speed of message processed, my journal keep increase and now I have 23 Mil unprocess messages. 
At first I use graylog version 1.1.3 and elasticsearch 1.6.0. I upgrade to 1.1.5 and elastic 1.6.1 this morning since I thought they could fix this problem but not, it still the same as previous version.
I must increase size of journal to 50GB to keep my logs. but with this rate it will be full soon.
I also tried to change processbuffer_processors to 10, 15, 20 but the problem not fix

The strange thing is when I restart graylog. before the process buffer is filled up. The output read from  journal is very high up to 10,000 msgs but when it comes to 100% utilized, it slow down

What should I do now ?

**Comment by dangmocrang** [comment]
I found the problem. I remove my extractor then the processed message increase. So this may because of extractor... but with the this power machine ? some extractor can slow down it ?

**Comment by joschi** [comment]
If you're using the Regular Expression or Grok extractors, you can easily create expressions (e. g. using a lot of backtracking) which will run very slowly or even never complete at all.

Could you share the extractor in question?

**Comment by dangmocrang** [comment]
Oh dear... All my extractor are Grok and Regular at all. How can I deal with this ? Use other type like "split/index" or "subtring" ?
Is there anyway to speed up if I still want to use grok and regular expression?

**Comment by joschi** [comment]
Not every regular expression or grok pattern is slow, but if you add lots of those to a single input, processing speed naturally takes a hit.

I'm closing this issue now because it's neither a bug report nor a feature request. Please use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or our [IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general questions around Graylog.

Related mailing list post: https://groups.google.com/d/msg/graylog2/ywNR7CGPAi0/R4E53NsAHwAJ

**Comment by zez3** [comment]
We have found that by increasing the processbuffer and outputbuffer helps 
"
# The number of parallel running processors.
# Raise this number if your buffers are filling up.
processbuffer_processors = 20
outputbuffer_processors = 15
"
I must say that we have a lot of grok and regex patterns configured. We cannot just drop them.
We have increased x3 the buffers and saw an expected major increase in the cpu and output for the time that it still had millions in queue(journal). After this it's pretty much idle-ing and no accumulation is happening anymore.
