### ISSUE TITLE
Enable doc_values for source and meta gl2_* fields

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#1335]
To allow fielddata-friendly aggregations on these fields, we should enable doc_values in the default mapping, as we do for timestamp.

**Comment by joschi** [comment]
> Doc values can be enabled for[…] and for `not_analyzed` string fields.

Source: https://www.elastic.co/guide/en/elasticsearch/guide/current/doc-values.html#_enabling_doc_values

Since `source` should still be analyzed to enable wildcard searches, we cannot store it as a doc value.
