### ISSUE TITLE
Broken "create" page for lookup tables

### ISSUE THREAD

**Issue by thll** [Graylog2/graylog2-server#13361]
The "create" page for lookup tables (`/system/lookuptables/create`) cannot be rendered. It fails with the following error: 

`Loading component failed: Cannot read properties of undefined (reading 'toUpperCase')`

![image](https://user-images.githubusercontent.com/886541/188445033-37dc1028-9189-4dfb-93fc-2e8ac913287f.png)

## Your Environment

* Graylog Version: `master`
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by mnin** [comment]
Fixed in https://github.com/Graylog2/graylog-plugin-cloud/pull/1051
