### ISSUE TITLE
Grok parse every pattern to separate field...

### ISSUE THREAD

**Issue by cybermedi** [Graylog2/graylog2-server#1338]
Hi, I am working on extractor for haproxy. I decided to do my own using GROK. Frankly speaking I am new in grok and maybe I am wrong with my approach. So please correct me if I am wrong. I understand GROK as readable form for parsing logs. It can easily help me to create parser for different logs by using same components. I will place here just short example:
I need to parse IP address:
1) I use definition of the pattern and import them into grayling

IPV6 ((([0-9A-Fa-f]{1,4}:){7}([0-9A-Fa-f]{1,4}|:))|(([0-9A-Fa-f]{1,4}:){6}(:[0-9A-Fa-f]{1,4}|((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){5}(((:[0-9A-Fa-f]{1,4}){1,2})|:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3})|:))|(([0-9A-Fa-f]{1,4}:){4}(((:[0-9A-Fa-f]{1,4}){1,3})|((:[0-9A-Fa-f]{1,4})?:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){3}(((:[0-9A-Fa-f]{1,4}){1,4})|((:[0-9A-Fa-f]{1,4}){0,2}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){2}(((:[0-9A-Fa-f]{1,4}){1,5})|((:[0-9A-Fa-f]{1,4}){0,3}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(([0-9A-Fa-f]{1,4}:){1}(((:[0-9A-Fa-f]{1,4}){1,6})|((:[0-9A-Fa-f]{1,4}){0,4}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:))|(:(((:[0-9A-Fa-f]{1,4}){1,7})|((:[0-9A-Fa-f]{1,4}){0,5}:((25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)(\.(25[0-5]|2[0-4]\d|1\d\d|[1-9]?\d)){3}))|:)))(%.+)?

IPV4 (?<![0-9])(?:(?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2}))(?![0-9])

IP (?:%{IPV6}|%{IPV4})

My Extractor looks like:

%{IP:myVeryNiceIp}

I suppose that I will see just one new item fields. The new item with name myVeryNiceIp but I can see another two with name "IP" and "IPV6". Which make useless mess in fields. I can imagine the workaround to create a huge massive regexp to avoid useless fields but I think the magic of GROK disappear.

**Comment by kroepke** [comment]
Hi!

Please have a look at our documentation http://docs.graylog.org/en/1.1/pages/extractors.html#using-grok-patterns-to-extract-data

Specifically the use of "UNWANTED" in patterns, to skip the subpatterns.

Please note that we use github Issues only for tracking bugs, not for community support. To ask questions kindly use our Google Group at https://groups.google.com/forum/?fromgroups=#!forum/graylog2

**Comment by cybermedi** [comment]
Thank you! Very much! I understand it as bug/feature request but for next time I will start at google groups.
