### ISSUE TITLE
Upgrading...

### ISSUE THREAD

**Issue by ftroot** [Graylog2/graylog2-server#1343]
Hi there,

Sorry but I simply cannot find any documentation on how to upgrade my Graylog instance (1.0 to 1.1.x).
Is it really too easy to desserve any guide line ?
Thanks if someone could take me in those few steps. 
Cheers.

**Comment by joschi** [comment]
Upgrading from Graylog 1.0.x to 1.1.x is pretty straight forward and usually can be done by just replacing the binaries and updating the configuration file. You can find details about the upgrade process at https://www.graylog.org/graylog-1-1-is-now-generally-available/

Please use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or our [IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general support questions around Graylog.
