### ISSUE TITLE
ASK - Graylog Load MySql data

### ISSUE THREAD

**Issue by ivangerard** [Graylog2/graylog2-server#1344]
Hi Everyone, 

I'd like to ask,

Does Mysql data can be Import into Graylog Server and analyze transaction log from Graylog web interface?

**Comment by joschi** [comment]
Please use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or our [IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general questions about Graylog.
