### ISSUE TITLE
some document reference need to be updated?

### ISSUE THREAD

**Issue by somethingGoneWrong** [Graylog2/graylog2-server#13478]
hi, i try to setup graylog with docker, [i follow this guide](https://docs.graylog.org/v1/docs/docker), i just find some issue with the **CUSTOM CONFIGURATION FILES**  documentation, below is the part i think needs to be updated:
```
wget https://raw.githubusercontent.com/Graylog2/graylog-docker/{{SERVER_VERSION}}/config/graylog.conf
wget https://raw.githubusercontent.com/Graylog2/graylog-docker/{{SERVER_VERSION}}/config/log4j2.xml
```
is this the correct link for the conf files?
conf -> https://raw.githubusercontent.com/Graylog2/graylog2-server/master/misc/graylog.conf
log4j2 -> https://raw.githubusercontent.com/Graylog2/graylog2-server/master/graylog2-server/src/main/resources/log4j2.xml
thx.

**Comment by bernd** [comment]
@somethingGoneWrong Yes, the links you posted are correct.

This in an error in our documentation. Thanks for the heads-up!

**Comment by okwute419** [comment]
@bernd, updated the doc. Pls, take a look when you can.

**Comment by bernd** [comment]
@okwute419 Looks good, thank you! :+1:
