### ISSUE TITLE
Remove Getting Started guide in 5.0

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#13477]
## Expected Behavior
The getting started guide is no longer shown for new installs or new minor releases.

## Current Behavior
The product shows getting started information.

## Context
The getting started guide is constantly outdated and not properly maintained. Instead of showing useless content, we'd like to remove it for the time being.

## Your Environment

* Graylog Version: 4.3/main
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
What should we start with when logging in to the product and no start page is configured for the user? The search page?

**Comment by kroepke** [comment]
Sorry, missed the notification. I'd say yes to the search page, but let me do another round of feedback with a few folks

**Comment by Abhishekverma2002** [comment]
Hello, I want to contribute to this project. Can you guys tell what are the prerequisites to  contribute to this project or understand it. I know core java and willing to learn more stuffs. Would like to hear from you guys. And if you have any work for me in this project.

**Comment by dennisoelkers** [comment]
This is fixed in #13970.
