### ISSUE TITLE
JAX-RS Resources from plugin in Graylog's API browser

### ISSUE THREAD

**Issue by gangadharr** [Graylog2/graylog2-server#1352]
Hi

  I would be very helpful if the JAX-RS Resources from plugins are also shown in Graylog API browser, by adding this feature users get to know if the service is running. 

Thanks
-Gangadhar

**Comment by kroepke** [comment]
Good point!

**Comment by bernd** [comment]
This got fixed in f73f1eb and will be in Graylog 2.0.
