### ISSUE TITLE
key=value tokenizer doesn't handle single quotes

### ISSUE THREAD

**Issue by voodoodrul** [Graylog2/graylog2-server#1359]
A simple Copy Input extractor with Key=Value tokenzier. Given this input:

`[1234] <warning>  reason=watchlist.hit type=event process_guid=0000001d-0000-0004-01d0-fd901a135bc4 segment_id=254 host='example.com' comms_ip='' interface_ip='' sensor_id=5 watchlist_id=4 watchlist_name='Non-System Filemods to system32' timestamp='1439845806.62' start_time='2015-08-03T00:05:32.105Z' group='FileServers' process_md5='' process_name='ntoskrnl.exe' process_path='' last_update='2015-08-17T20:57:18.688Z'`

This will extract up to the first space
`watchlist_name:'Non-System`

Also note that the single quote is included in the field value. Ideally if a field is wrapped in single or double quotes, the entire field would be extracted and the quotes removed.

**Comment by joschi** [comment]
Closed by merging #1360.
