### ISSUE TITLE
Search result field headers cannot be reordered

### ISSUE THREAD

**Issue by artiomello** [Graylog2/graylog2-server#13619]
Hi. There seems to be no way to reorder field headers in search result tables other than adding the fields to the table in a specific order. That would be fine for entries with just a handful of fields, but completely unusable when there are more fields to choose from:

![image](https://user-images.githubusercontent.com/102314521/194276004-14b51070-3580-4c9e-b5e0-1d8a8de4bfe8.png)

I've found a number of issues related to this topic, all of which are closed as fixed, but it's still not working for me:
[#692](https://github.com/graylog-labs/graylog2-web-interface/issues/692) #6808 #7496 #7501

## Expected Behavior
1. Fields should be easily reordered by dragging/rearranging them in a table.
2. Fields should be easily reordered by dragging/rearranging them in the _fields_ section when editing a table.

## Current Behavior
Currently fields are only arranged in the exact order they are selected to show up in a table.

## Steps to Reproduce (for bugs)
1. Run any search on a stream/input
2. Add a few fields to the table
3. Try to rearrange them

## Context
The ability to create a meaningful results table with optimally structured information.

## Your Environment

* Graylog Version: 4.3.3+86369d3
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Graylog installed on Ubuntu 22.04 LTS
* Browser version: MSE 106.0.1370.34 / Chrome 105.0.5195.127

**Comment by dennisoelkers** [comment]
Hey @artiomello,

thanks for reporting this. You can reorder fields by clicking on the field in the "Fields" box and dragging it in the desired order.

Does that help you?

**Comment by artiomello** [comment]
Hey,

Aaaah, now I get it. I've tried it one more time and it does work but the implementation is rather... confusing or misleading I should say. 

You have to loooong click on a field name in order for it to become draggable. When did that become a thing when using a mouse, I wonder. And even then it works like half of the time, at best. Moreover, when you click on a fieldname, almost every single time the fieldname dropdown opens up, suggesting that there's no more functionality there.

This is just confusing and not very user-friendly, to be honest. 

And it's not possible to rearrange the fields by dragging the columns in the table itself. If I remember correctly, it worked quite well in ELK/Kibana. Would be nice to see this implemented for Graylog as well.

Either that or this long click with dropdowns every time needs to be revised. Current implementation is just bad.

Thanks for the tip though.

**Comment by dennisoelkers** [comment]
Hey @artiomello,

thank you very much for your honest feedback, it is really helpful.

I do agree with you on the usability of the select control, I also think that there are better ways to do this. We will try to replace it rather sooner than later with a more straight-forward approach. E.g. the control we are using on the `System` -> `Configurations` -> `Message Processors Configuration` dialog?

![image](https://user-images.githubusercontent.com/41929/194379005-df6ffa9f-3732-455f-829b-b6591d8e2204.png)

**Comment by artiomello** [comment]
Hi @dennisoelkers,

That would definitely be much better, yes. 

And still, perhaps you could also consider adding an option to rearrange the columns in the table itself. It already has a context menu where an additional option, e.g. _rearrange_, could be added that would toggle this behavior on/off. Just a thought.

**Comment by artiomello** [comment]
And then there's this:
![image](https://user-images.githubusercontent.com/102314521/195096743-01076e80-8a64-4b82-ae35-c0d3edb84ce5.png)

**Comment by LouisAtGH** [comment]
Reorganizing fields is practical impossible. An absolute drama !!!!!

**Comment by dennisoelkers** [comment]
This will be fixed in https://github.com/Graylog2/graylog2-server/pull/14725 - you can expect this in `5.1`.

**Comment by dennisoelkers** [comment]
Refs #14795.

**Comment by dennisoelkers** [comment]
Fixed in #14725.
