### ISSUE TITLE
Input/node ID is nowhere to be found

### ISSUE THREAD

**Issue by artiomello** [Graylog2/graylog2-server#13628]
When a new input is created it gets assigned an ID that is used by Graylog for all configurations related to it, but it's not displayed anywhere in the input's configuration/info. The only way to find the input ID for a configured input that I could manage to find is to go to Inputs > find an input > click on _Show received messages_ which will then run a search with a **gl2_source_input** field that contains the actual input ID. 

And the worst part of it is that Graylog will refer to your inputs by that same ID, that is nowhere to be found otherwise, in various configurations or messages such as this one:
![image](https://user-images.githubusercontent.com/102314521/194514213-0615cf9e-5b9d-42aa-a703-f37ba8e3e0d3.png)

This error appeared after updading to the latest Graylog version (4.3.8) and I have two inputs that have failed to start. Now, granted, in the Inputs menu I do see a_failed_ flag next to an input:
![image](https://user-images.githubusercontent.com/102314521/194514687-e6476f0d-3b9f-4c4a-b7b9-8e44280c064b.png)
but no input ID. So, in order for me to find out the exact input ID that this error message (or any other message, error or config for that matter) is referring to, I need to:
- go through all the inputs one by one
- run _Show received messages_ on each one
- note down the input IDs from the search tables somewhere next to the actual input name
- go back to the error message (or some config, for that matter)
- find the actual input that is being referred to
- do whatever steps next

And the same goes for the node ID. Each node has a name, yet it's referred to by its ID that is found only under System > Nodes > go figure which one if you have more than one * > click on Details > another longread opens up > search for System > Node ID.

*Because only a part of the ID is being displayed, next to the **actual node name**:
![image](https://user-images.githubusercontent.com/102314521/194517899-1795fb26-3586-42e4-b205-923a14035f31.png)

While using unique IDs is indeed more convenient than parsing each person's take on a proper object name, hiding the actual names results in an unwarranted and tedious quest game everyone can do witout.

## Expected Behavior
1. Inputs and nodes are referred to by either their unique name or name/ID pair.
2. Both Inputs and Nodes have their full IDs visible (preferably next to their name) on the same page where they are defined/configured.

## Current Behavior
Input and Node IDs are inconveniently hard to find in the depths of Graylog menus and configs, as described above.

## Possible Solution
See expected behavior. 

## Steps to Reproduce (for bugs)
See description.

## Context
Hiding object IDs while referring to same objects by their IDs is not .. helpful.

## Your Environment

* Graylog Version: 4.3.8+8c4705e
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System: 22.04 LTS
* Browser version: MSE 106.0.1370.34

**Comment by H2Cyber** [comment]
Related : https://github.com/Graylog2/graylog2-server/issues/13346
