### ISSUE TITLE
Question: Graylog Radio Input (AMQP)

### ISSUE THREAD

**Issue by haricharan123** [Graylog2/graylog2-server#1365]
this is more of a question rather than a feature. Currently my data is simple JSON which i'm logging over rabbit MQ. I use Graylog Radio Input (AMQP) to consume data from the message broker.Further i find that  messages are being consumed from the queues,. How ever i find that message don't show up on the web  interface. My questions are.

1) what would be the correct approach if my data is a JSON and not GELF (Not possible to transform it to gelf as of now) logged over RabbitMQ.

2) JSONPATH; JSON path is available only from HTTP API, can JSON Path be used as an extractor of some sort, if my data is JSON.

Here is the JSON:

{
	"Severity" : 20,
	"ExceptionFull" : "text",
	"ExceptionType" : "text",
	"ExceptionMessage" : "text",
	"Content" : "text",
	"EventSequence" : 0,
	"EventTime" : "2015-04-10T00:00:00",
	"Application" : "ECC",
	"Message" : "Hello world",
	"MachineName" : "text",
	"Category" : 0,
	"Type" : "MQ.BaseMessages.LogMessages.ErrorMessage"
}

**Comment by joschi** [comment]
Discussion on the mailing list: https://groups.google.com/forum/#!topic/graylog2/133YsHtZNjk
