### ISSUE TITLE
Entering `[`character in grok filter pattern field crashes UI

### ISSUE THREAD

**Issue by jzielke84** [Graylog2/graylog2-server#13670]
When entering a `[` character in the Filter pattern field, the UI immediately throws an error, discarding the whole work spent so far on creating a new pattern, so you have to start all over again:

> Something went wrong.
It seems like the page you navigated to contained an error.

**Comment by dennisoelkers** [comment]
Hey @jzielke84,

I am trying to reproduce this issue, but was unable to do so yet. What I tried was:

1. Going to `System` -> `Grok Patterns`
2. Click on `Create Pattern`
3. Enter a single `[` in the `Pattern` textbox
4. Also tried entering a `[` in the `Filter pattern` box

What am I missing? Do you see any errors/stack traces in your browser's JS console? Can you provide a screen recording/screen shot?

**Comment by vanduc1102** [comment]
Hi @jzielke84 ,
I am new to graylog2 and want to work on the issue.
I dont know how to add an extractor, could you help?

**Comment by jzielke84** [comment]
@vanduc1102 This shouldn't be discussed here but in the [Graylog community](https://community.graylog.org/).

**Comment by dennisoelkers** [comment]
Hey @jzielke84,

I can verify this, thank you! This is still an issue for `4.3.x`, but will be fixed in the upcoming 5.0 through #12929.

**Comment by jzielke84** [comment]
Thank you 🙏
