### ISSUE TITLE
Search in all messages only works after recalculating index ranges

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-server#1370]
`graylog-1.2.0-rc.2-SNAPSHOT-20150825104939.tar.gz`

When searching for `all messages` I get this error message. After recalculating index ranges search works

![bildschirmfoto 2015-08-25 um 14 24 32](https://cloud.githubusercontent.com/assets/6331205/9466593/2f5e885e-4b36-11e5-8077-b4934a620042.png)

**Comment by bernd** [comment]
We are now migrating the MongoDB based index ranges to Elasticsearch based ones since https://github.com/Graylog2/graylog2-server/pull/1378.

That means search should work after starting with the new version.

**Comment by florianvolle** [comment]
works :)
