### ISSUE TITLE
ES reduced durability feature request

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#1372]
Right now we have a big elasticsearch cluster (8+ data nodes) with 1 replicas and 100 indices (which allous us to look 1 week back).

Our on premise elasticsearch servers have a raid10 instead of raid0 storage because we do not want to replace a harddisk (we are going to have 100+ disks) every week and hope that the elasticsearch replication will restore our data. Because this leads to performance problems during the recovery.

Lets image graylog would be able to have two types of indices ha indices (with replica factor of 1 or more) and reduced durability indices (with replica factor of 0).

This would allow us to setup this:

20 ha indices
160 reduced durability indices

=> almost 2 weeks of rention without any additional hardware costs.
=> a crash of an elasticsearch node would not stop indexing becase the latest indices are ha
=> a crash of an elasticsearch node would stop us from search old messages (this is not a problem because a restart of the corresponding server will most lilkely recover the data)

**Comment by SjonHortensius** [comment]
This is already possible by going to e/s directly, it's perfectly fine to update the `replica` settings of your graylog indices. Have a look at https://www.elastic.co/guide/en/elasticsearch/guide/master/replica-shards.html

**Comment by runningman84** [comment]
Yes but we want Graylog to be the manger for our elasticsearch cluster. Imagine our script would stop working... in this case the Graylog would fill up the cluster up to 100%.

**Comment by jalogisch** [comment]
with the upcoming version 2.2 it will be possible to have different retention times for different indices.

**Comment by runningman84** [comment]
@jalogisch does 2.2 also include different replica settings of different indices?

**Comment by joschi** [comment]
@runningman84 Yes.
