### ISSUE TITLE
Ability to freeze top row in tables

### ISSUE THREAD

**Issue by artiomello** [Graylog2/graylog2-server#13753]
## What?

Would be really nice to have the ability to freeze the top row of a table so that when you scroll down you always see what you're looking at, same as you can in Excel, for instance.

Top:
![image](https://user-images.githubusercontent.com/102314521/197207207-b877f9ee-d303-4bb5-810b-a34335872dab.png)

When you scroll down you still see the table name, but not the column names:
![image](https://user-images.githubusercontent.com/102314521/197207652-40269d37-f408-442e-a95c-a4eda4250bbf.png)

## Why?

You might have columns with similar information and be forces to scroll up and down to double check what was it that you were looking at. Can be quite annoying. Especially the further you get from the top.

## Your Environment

* Graylog Version:  4.3.8+8c4705e 
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Ubuntu 11.0.16 on Linux 5.15.0-48-generic
* Browser version: Latest MSE

**Comment by dennisoelkers** [comment]
This has been implemented in `5.0`.
