### ISSUE TITLE
Query Validation "bulb icon" does not lead to exact place in documentation

### ISSUE THREAD

**Issue by luk-kaminski** [Graylog2/graylog2-server#13822]
## Steps to Reproduce:
1. Click on the validation warning/error "bulb icon".
![Screenshot 2022-10-28 at 13-42-51 Graylog - Unsaved Search](https://user-images.githubusercontent.com/100699120/198580034-3c4ab6ec-c335-4a0a-83ab-f6714e411f10.png)

2. It will lead you to the link which looks more or less like that: https://docs.graylog.org/docs/query-language#unknown-field
3. It will show the top of "Search query language" page, without moving you to the part documenting "unknown field" error type.

## Solution suggestion:
Documentation should contain the links matching the links generated from the GL UI.

**Comment by luk-kaminski** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/graylog/project/14870?defectId=12351)
- Test [Query Input validates search query (please test with complex search queries)](https://web.testquality.com/site/graylog/project/14870/runs/171283?resultId=3015011) in Run [Łukasz testing Query input](https://web.testquality.com/site/graylog/project/14870/runs/171283) (linked to Cycle [Query Input](https://web.testquality.com/site/graylog/project/14870/cycles/27707)).

**Comment by linuspahl** [comment]
I talked about it with the Docs team and since the "Error Types" section is so small, we will just link to the section instead of the specific error. In reality this will not make a difference for the user. We still need to make this change though.
