### ISSUE TITLE
Mark synced users as "disabled" after disabling related authentication service.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#13823]
## Description
When using an authentication service like LDAP related users will be displayed as "enabled" in the users overview and the user details page. When the authentication service is being disabled, related users are no longer able to login.

In my opinion it makes sense to display the related users as "disabled" after disabling the authentication service.

## Your Environment

* Graylog Version: 5.0

**Comment by moesterheld** [comment]
setting the disabled flag after deactivating the backend was the wrong approach.

see https://github.com/Graylog2/graylog2-server/pull/16088 for the agreed upon approach.
