### ISSUE TITLE
Field type refresh interval is NaN seconds on Indicies page

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/graylog2-server#13868]
Noted in `5.0.0-beta.2`, Field type refresh interval is NaN seconds on the Indicies page: 

![image](https://user-images.githubusercontent.com/2953243/199612594-94869f51-055e-41a5-9ee6-3220006ab95e.png)

Observed in my 5.0 lab, also noted in the test instances.

Lab: Graylog 5.0.0-beta.2+d576a3d on gl50alpha-lab (Debian 17.0.4 on Linux 5.10.0-19-amd64)
Test instance: Graylog 5.0.0-SNAPSHOT+d406c2e on server (Eclipse Adoptium 17.0.4.1 on Linux 5.15.0-1019-aws)

**Comment by dennisoelkers** [comment]
It looks like the index sets endpoint of the API is now returning the `field_type_refresh_interval` as a `Duration`, serialized to a `String`. On `4.3`, the `Duration` was serialized as a number in milliseconds. Maybe related to #13541?
