### ISSUE TITLE
Results preview in stream rules management is wrong when no rules have been defined

### ISSUE THREAD

**Issue by patrickmann** [Graylog2/graylog2-server#13916]
The results preview in stream rules management does not show the correct result when no stream rules have been defined.
This is a regression from 4.3.

## Expected Behavior

Information about whether a message would be routed to the current stream should be accurate. 

## Current Behavior

When no rule is defined, preview shows that message would NOT be routed to the stream, even though the message was already routed to that stream.

![Screenshot from 2022-11-08 14-31-44](https://user-images.githubusercontent.com/12073930/200581782-6259abfa-f9b2-4879-b227-3066abd4b863.png)

Result appears to be correct when there is at least 1 rule already defined.

## Steps to Reproduce (for bugs)

1. Select Test message against stream and select the stream that the message was routed to. The stream should not have any rules yet.
2. Observe that the preview indicates that message would NOT be routed to the stream

## Your Environment

* Graylog Version: 5.0.0-beta2
* Java Version:
* Elasticsearch Version: OS 1.3.6
* MongoDB Version: 5.0.13
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Hey @patrickmann, thanks for reporting this!

If no stream rules are defined, no messages will be routed to the stream. So the output of the stream rule matching preview is correct. It probably requires a bit more explanation/help text for this specific case.

**Comment by patrickmann** [comment]
@dennisoelkers you are right. I accidentally had a stream with a rule when checking 4.3. It behaves the same on 4.3 and 5.0. 
A bit of additional explanatory text would be helpful though to the novice :)
