### ISSUE TITLE
Grok date converter creates bad timestamp field

### ISSUE THREAD

**Issue by awhatley** [Graylog2/graylog2-server#1394]
For the following example message:

    [03/Sep/2015:06:32:07 +0000]

Using the following grok pattern:

    \[%{HTTPDATE:timestamp;date;dd/MMM/yyyy:HH:mm:ss Z}\]

In the extractor interface, the date is successfully parsed out, and shows:

    timestamp
    Thu Sep 03 06:32:07 UTC 2015

However, when a message actually comes in and is routed through the extractor, it fails when trying to write to the index with the following exception:

    WriteFailureException; nested: MapperParsingException[failed to parse [timestamp]]; nested: 
    MapperParsingException[failed to parse date field [2015-09-03T06:32:07.000Z], tried both date 
    format [yyyy-MM-dd HH:mm:ss.SSS], and timestamp number with locale []]; nested: 
    IllegalArgumentException[Invalid format: "2015-09-03T06:32:07.000Z" is malformed at
    "T06:32:07.000Z"];

It seems like the grok converter is turning it into an ISO 8601 date string, and graylog is failing when trying to parse that into a timestamp field.

The only workaround I've found is to first use a RegEx extractor with a date converter to pull out the timestamp, and then use the grok pattern on the rest of the message, adding an UNWANTED tag to the HTTPDATE pattern.

**Comment by kroepke** [comment]
Many thanks for the detailed bug report! The fix should be in the next 1.2 RC.
