### ISSUE TITLE
MongoDB 5.0 requires AVX CPU extensions. Is this documented and tested?

### ISSUE THREAD

**Issue by loganmarchione** [Graylog2/graylog2-server#13950]
I’m testing Graylog 5 beta and MongoDB 5. 

I’m following [this](https://docs.graylog.org/docs/upgrade-mongodb-4x-5x) document to upgrade from MongoDB 4.4 to 5.0.

When starting MongoDB I’m getting an error about MongoDB 5 and higher requiring AVX CPU support. My hypervisor (Proxmox) doesn’t pass this CPU instruction through by default, so I need to update my VM config. 

Below is some documentation from Mongo and Docker about this. Apparently MongoDB 5 and higher requires AVX instructions, which are generally available in Sandy Bridge (2nd Gen) and higher CPUs.

* https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
* https://github.com/docker-library/mongo/issues/485#issuecomment-891991814

However, hypervisors don't always expose the "host" CPU to the VM. In the case of Proxmox, it's a generic "kvm64" CPU, which lacks AVX. 

You may want to add a warning to Graylog’s MongoDB upgrade docs about MongoDB’s AVX requirements with the 5.x and higher releases. I can imagine people running Graylog/Mongo in virtual machines that don’t expose specific CPU instructions (like me) will need to know this. Has anyone else encountered this?

**Comment by boosty** [comment]
Related: 
- https://github.com/Graylog2/graylog2-server/issues/14167
- https://github.com/Graylog2/graylog-docker/issues/241

**Comment by boosty** [comment]
A note regarding AVX has been added to our docs: https://go2docs.graylog.org/5-0/planning_your_deployment/upgrading_to_mongodb_5.x_and_6.x.htm

**Comment by loganmarchione** [comment]
Thanks! You can close this out!
