### ISSUE TITLE
Multi-sort on aggregations does not work

### ISSUE THREAD

**Issue by luk-kaminski** [Graylog2/graylog2-server#13957]
Multi-sort on aggregations does not work.

![Screenshot 2022-11-14 at 14-41-31 Graylog - Unsaved Search](https://user-images.githubusercontent.com/100699120/201676164-bd495a77-2561-48a6-9c9a-914a94ee12d9.png)

## Expected Behavior
If there are multiple sorts configured for aggregation, they are all used. Secondary sorting should be used inside single grouping only.

## Current Behavior
It seems that only the first sort is used.

## Steps to Reproduce (for bugs)
The screenshot shows them.

## Your Environment

* Graylog Version: 5.0.0
* Java Version: 17

**Comment by janheise** [comment]
@luk-kaminski OpenSearch2? Elasticsearch 7? Or both?

**Comment by janheise** [comment]
@luk-kaminski ok, I just tested with OpenSearch2, looks like there is the same problem. Wanted to make sure that it's not obviously related to the part that's different between our handling of Elasticsearch 7/OpenSearch 2

**Comment by luk-kaminski** [comment]
The bug is caused by the introduction of multi-terms/scripted-terms aggregations, where buckets are composed from multiple field values. There is no easy mechanism to sort on parts of those complex buckets. We will continue to search for a workaround...
