### ISSUE TITLE
Allow copying widgets from dashboard to dashboard

### ISSUE THREAD

**Issue by kodjo-anipah** [Graylog2/graylog2-server#13958]
## What?

It should be possible to copy widgets from dashboard to other dashboards. At the moment its only possible to copy them from site to site.
![image](https://user-images.githubusercontent.com/98284293/201693882-ee7c4a1e-58c1-4057-b524-20967946db54.png)

 The same functionality is available for widgets created in the search interface. See example img bellow: 
![image](https://user-images.githubusercontent.com/98284293/201693455-bbe99592-9d99-495a-ade4-15cc74af1745.png)

## Why?

This would allow faster creation of dashboards containing widgets from different other dashboards.

**Comment by kroepke** [comment]
duplicates #13890
