### ISSUE TITLE
Preserve "Max number of indices" value when changing index retention strategy

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#13975]
## What?

If a non-[def](https://github.com/Graylog2/graylog2-server/blob/3cb826f2231906ebaf0c967be90291fa0092151e/graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/ClosingRetentionStrategyConfig.java#L32)[ault](https://github.com/Graylog2/graylog2-server/blob/dba006b663632f6265882328d3134c7cb03c3456/graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/DeletionRetentionStrategyConfig.java#L32) "max number of indices" has been set in the index retention config, that value should be preserved when the index retention strategy gets changed.

For example:  if I have an index set's retention strategy set to "Archive" with a "max number of indices" of 90 and change the strategy to "Delete", I would expect the "max number of indices" to remain at 90 (rather than "changing" to the default of 20).

## Why?

If an admin doesn't notice the "max number of indices" gets reset, it could unintentionally result in indices getting archived, deleted, etc.

## Your Environment

* Graylog Version: 4.3.9
* Browser version: Firefox 106

**Comment by danotorrey** [comment]
Verified. Example of the issue:

![Nov-16-2022 13-49-53](https://user-images.githubusercontent.com/3423655/202280053-001c3d08-cc28-4f4c-86ec-5cf820b8aced.gif)
