### ISSUE TITLE
Take a look at the matcher code on GitHub

### ISSUE THREAD

**Issue by aanriot** [Graylog2/graylog2-server#1398]
Hello,

When being on the "Edit Stream Rule" menu, the link "Take a look at the matcher code on GitHub" has this target:

<code>
https://github.com/Graylog2/graylog2-server/tree/@Version.VERSION.getBranchName/graylog2-server/src/main/java/org/graylog2/streams/matchers
</code>

so it leads to a 404 error.

I'm using official packages of Graylog 1.1.6.

Thanks.

**Comment by joschi** [comment]
Thanks for reporting this! The issue has been fixed in the upcoming Graylog 1.2.0.
