### ISSUE TITLE
Dashboard is not select default stream and widgets fails with an error message

### ISSUE THREAD

**Issue by ashish1099** [Graylog2/graylog2-server#13999]
Dashboard is not select default stream and widgets fails with an error message

## Expected Behavior

Widget should work with default stream (without selecting the stream)

## Current Behavior

I have to manually select the stream and then widget shows up fine

## Possible Solution

No idea

## Steps to Reproduce (for bugs)

1. Just install graylog 4.3.9
2. 
3.
4.

## Your Environment

* Graylog Version: 4.3.9
* Java Version:
* Elasticsearch Version: opensearch 1.3.6
* MongoDB Version: 4.4.1
* Operating System: Ubuntu 20.04
* Browser version: Chrome

**Comment by dennisoelkers** [comment]
Hey @ashish1099,

thanks for reporting this! What is the actual error message you are seeing? Can you add more steps how to reproduce the issue?

**Comment by ashish1099** [comment]
![image](https://user-images.githubusercontent.com/2697494/202695192-5684d8fb-586e-42e7-99ce-85fbda38962d.png)

We simply restored the opensearch and updated graylog from 4.2.7 to 4.3.9 and ended up seeing this

**Comment by dennisoelkers** [comment]
Hey @ashish1099,

have you been running Graylog 5.0 on the same MongoDB?

**Comment by ashish1099** [comment]
@damianharouff nope, graylog5 was with mongodb 5.0.13 (had to get it removed)

**Comment by dennisoelkers** [comment]
The stack trace clearly indicates that your MongoDB contains documents which were created by Graylog 5.0. Can you please double-check? Maybe there are mixups with the URL/your containers/volumes/etc.

As this does not look like a bug in Graylog, I am closing this issue. If you have additional information showing that it is in fact one, feel free to reopen it.
