### ISSUE TITLE
Use GeoIP databases to assign countries to IP adresses

### ISSUE THREAD

**Issue by LordMike** [Graylog2/graylog2-server#1402]
Somehow determine if a field is an IP address (configuration, auto-detection, ..), an then add a country field which contains the country code. In the UI, use this field and display a flag for it.

In the search, it should be possible to define common sets of countries, such as EU, US, Africa, Asia or individual countries. This allows us to both gain insight into who's talking to who on a firewall, and to quickly show only suspicious traffic.

**Comment by bernd** [comment]
Please open an idea for this in our [product ideas portal](https://www.graylog.org/product-ideas/) so the community can vote on it. This existing one sounds related:

https://graylog.ideas.aha.io/ideas/GL2E-I-364

Thank you!
