### ISSUE TITLE
JSON path input should run only on leader node when global is enabled

### ISSUE THREAD

**Issue by AntonEbel** [Graylog2/graylog2-server#14074]
## Expected Behavior

The "JSON path value from HTTP API" input should only run on the leader node if "global" is enabled.

## Current Behavior

Currently, the "JSON path value from HTTP API" input runs on all nodes when "global" is enabled.

## Possible Solution
Override the `onlyOnePerCluster` method in `JsonPathInput` and return `true`.

* Graylog Version: 5.0.0

**Comment by AntonEbel** [comment]
@boosty Should we backport the corresponding PR?

**Comment by boosty** [comment]
@AntonEbel I think since this is a bugfix, we should backport it to 5.0 and 4.3 indeed. Thanks 👍
