### ISSUE TITLE
Graylog nodes should report an error when configured to individual MongoDB databases

### ISSUE THREAD

**Issue by dcarastan** [Graylog2/graylog2-server#1408]
Weird things happen when working on automatic cluster deployment and the nodes are mistakenly configured to local non-clustered MongoDB nodes. ES shows a green cluster and the indices are green but only one node can be seen, sometimes no nodes are detected at all. The logs are cryptic about it. It would be quite useful for the novice to be notified when such broken setup is detected. Something within the lines of the multiple master node validation error would suffice. Thank you!

**Comment by jalogisch** [comment]
this can only happen if you did not follow the installation documentation.

For the Graylog Server it is impossible to detect that type of misconfiguration.
