### ISSUE TITLE
Lookup Tables UI runs over table width on smaller screens

### ISSUE THREAD

**Issue by kingzacko1** [Graylog2/graylog2-server#14099]
System > Lookup Tables list of lookup tables overflows outside of the container at 100% zoom on smaller screens. 
## Expected Behavior

List of lookup tables is contained within its container at normal zoom levels
## Current Behavior

Table overflows outside of container to the right at 100% zoom
![image](https://user-images.githubusercontent.com/91903901/204922352-5b9d9d08-4c37-4db0-9e3c-dad0478c58e0.png)
![image (1)](https://user-images.githubusercontent.com/91903901/204922908-5a6fc68e-e412-4a5c-af24-53c82ddc8c3b.png)

## Possible Solution

Fix styling of the table
## Steps to Reproduce (for bugs)

1. Open the System > Lookup Tables page on a smaller resolution screen (I did not see the problem on a large monitor until 150%+ zoom on the page)

## Your Environment

* Graylog Version: 5.0GA
* Browser version: Latest Chrome and Firefox

**Comment by kroepke** [comment]
#14100 is related
