### ISSUE TITLE
Current page in list pagination is not being reseted when calling `resetPage` from `usePaginationQueryParameter`.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#14108]
## Description

For some paginated lists we are storing the pagination in the URL, to preserve it after a reload. When searching for an item in a list we reset the pagination. Currently the URL query param `page` will be `1`, but the pagination state seems to stay the same.

Steps to reproduce:
1. Go to the streams overview.
3. Navigate to page 2
4. Click on the search button

The URL query param `page` will be `1`, the list will display the results for the first page, but the pagination will display page `2` as active.

* Graylog Version: 5.0

**Comment by zeeklop** [comment]
PR ready for review: [PR 14141](https://github.com/Graylog2/graylog2-server/pull/14141)

**Comment by linuspahl** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/issues/14108
