### ISSUE TITLE
garylog startup error tips  caused by: org.graylog.shaded.elasticsearch7.org.elasticsearch.client.ResponseException: 

### ISSUE THREAD

**Issue by duzengjie** [Graylog2/graylog2-server#14119]
garylog  version 4.3.8
es version 7.5.2

caused by: org.graylog.shaded.elasticsearch7.org.elasticsearch.client.ResponseException: method [GET], host [http://136.1.5.249:9200]/, URI [/_cat/indices/graylog_*?format=json&h=index%2Cstatus&s=index%2Cstatus&expand_wildcards=all], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/_cat/indices/graylog_*] contains unrecognized parameter: [expand_wildcards]"}],"type":"illegal_argument_exception","reason":"request [/_cat/indices/graylog_*] contains unrecognized parameter: [expand_wildcards]"},"status":400}

**Comment by duzengjie** [comment]
MANUAL SETUP  method

**Comment by dennisoelkers** [comment]
It looks like your Elasticsearch version is too old. Can you update to 7.10.2 and try again?

**Comment by duzengjie** [comment]
> 

7.10.2 is ok Thanks

**Comment by HungryHowies** [comment]
My 2 cents, Graylog not Gary  😆 
```
garylog startup error tips caused by
```

**Comment by duzengjie** [comment]
> My 2 cents, Graylog not Gary 😆
> 
> ```
> garylog startup error tips caused by
> ```

sorry I made a mistake :smile:
