### ISSUE TITLE
Syslog input timezone behavior not documented, requires that graylog server and log source both use same timezone

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#14112]
Currently the way the Graylog Syslog input handles timezones is not intuitive and leads to many timestamp issues unless one is incredibly careful.

Based on some testing it appears the only proper way to have graylog parse syslog rfc3164 timestamps is to ensure both the Graylog Server (specifically the server operating system) and the log source are using the same timezone. Otherwise timestamps will be incorrect.

This requirement isn't documented anywhere that i could find (e.g. https://docs.graylog.org/docs/en/syslog ) and it doesn't make sense that i need to configure the server timezone in order to instruct graylog to process syslog messages with a given timezone.

## Expected Behavior

Graylog Syslog input assumes the log source is UTC (or provides the ability to explicitly configure what timezone graylog syslog input expects)

## Current Behavior

Graylog Syslog input uses the timezone of the server operating system and requires all syslog rfc3164 devices to use the same timezone as the graylog server. Otherwise timestamps will not be set correctly.

If the graylog server is set to a negative timezone (e.g. UTC-6), but the syslog message is sending a UTC time, graylog will silently drop the message without any warnings or logging. This is not desired behvaior.

## Possible Solution

https://github.com/Graylog2/graylog2-server/issues/3853

## Steps to Reproduce (for bugs)

1. Set the timezone of the OS where graylog-server runs to something other than UTC (e.g. UTC-6, or America/Chicago)
2. Send a syslog message to graylog using UTC timestamp
3. Observe that Graylog Syslog input doesn't log the message but instead drops it without notice or warning

## Context

I've run across many postings on the internet as well as github issues where users struggle with this behavior. Fixing this would greatly improve the experience of logging syslog messages to graylog.

## Your Environment

* Graylog Version: Graylog 4.3.9, Graylog 5.0.1

**Comment by drewmiranda-gl** [comment]
The only current work around is to change the timezone of the graylog server operating system, which IMO is not desirable.

**Comment by drewmiranda-gl** [comment]
FYI For easy testing, can send a one off syslog message to a TCP syslog input via

```
nc -w0 127.0.0.1 5140 <<< "<34>Dec 01 20:31:46 acme-dmzouter-fw1 %ASA-6-302016: Teardown UDP connection 44444 for inside:192.168.92.30/6060 to outside:213.154.64.1/53 duration 0:00:00 bytes 200"
```

**Comment by drewmiranda-gl** [comment]
Evan pointed out the Palo inputs already support this so hopefully not a huge level of effort. Would give a massive quality of life improvement to syslog :)

![image](https://user-images.githubusercontent.com/107503402/205162271-308a5471-9bda-481c-835b-2c4efdf75eae.png)

**Comment by drewmiranda-gl** [comment]
If this is something that can't be roadmapped, would it be possible to at least add a note when creating a Syslog input? Again, having the correct timezone on the linux server is crucial for successful syslog ingestion.

![image](https://user-images.githubusercontent.com/107503402/214127644-920124fa-dca3-4317-b7ac-878b30970565.png)

**Comment by boosty** [comment]
@drewmiranda-gl I think we should support a default timezone, as suggested in https://github.com/Graylog2/graylog2-server/issues/3853. Will propose this for the next dev cycle.

**Comment by drewmiranda-gl** [comment]
Closing this as we can now specify a timezone on syslog inputs. Great work y'all!
