### ISSUE TITLE
Use graylog-server as forwarder only

### ISSUE THREAD

**Issue by razvanphp** [Graylog2/graylog2-server#1413]
Hello.

In our setup, we use a hybrid hosting solution, in 2 completely different data-centers. What we want is to have our old graylog where it is now, and have a new one in the new location, with it's own elasticsearch cluster. The goal is to have a buffer (local kafka cluster) when our VPN goes down for example, plus TLS encription and TCP connection between the graylog servers.

The plan looks good, I can forward the messages from the old one to the new one, but there is one feature missing, and that is, I cannot prevent a message to be stored in the first graylog ES cluster. What we need is actually just the forwarder, without storing. Currently we can only forward streams, and this means the message is already stored.

What would be cool to have (maybe it's complicated and you can suggest something else) is to have an option to mark inputs as forwarder only. So in this case, I would just set the inputs that needs to be forwarded and others I will allow to be stored locally. Another idea would be to have this possibility in the graylog-collector, but then you don't have the kafka cluster as failover.

The tricky part in this is to decide when to clean up the messages from the kafka cluster, so that he knows the message was forwarded to the output and this is fine, without filling up the local storage.

We are open for suggestions, if what we want is not currently possible please take this as a feature request.

Thank you for your great job!

**Comment by jalogisch** [comment]
closing this in favor of #1004.
