### ISSUE TITLE
Sort for paginated saved searches API endpoint not working as expected.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#14140]
## Description

When defining a sort when fetching the paginated saved searches the resulting list does not have the expected sort.
It looks like it only works with 'created_at' but not 'title', 'description', 'summary' and 'owner'.

## Your Environment

* Graylog Version: 5.0

**Comment by luk-kaminski** [comment]
We decided with Linus to implement 1 and 2, and leave 3 for now because of #14290.
