### ISSUE TITLE
Cursor in Ace editor component is hard to see

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#14190]
## Description

The cursor in our Ace editor component is currently quite hard to see.

https://user-images.githubusercontent.com/461/207070613-6404cbac-57a3-4784-b855-bedd6e6c0ff0.mp4

https://user-images.githubusercontent.com/461/207071289-bae92eef-f1e3-42ed-9165-d9c04c76bf66.mp4

This affects all editor components. (pipeline, Sigma rules, etc.)

## Steps to Reproduce (for bugs)

1. Open a page that uses the Ace editor component (e.g., edit a pipeline rule)
2. Use the editor and try to find the cursor position

## Your Environment

* Graylog Version: 5.0.0
* Browser version: Google Chrome 108.0.5359.98 on Ubuntu 20.04 LTS

**Comment by ousmaneo** [comment]
I tested this on the current master on a different browser and couldn't reproduce it.
@bernd, can you confirm that it's fixed?

**Comment by bernd** [comment]
> I tested this on the current master on a different browser and couldn't reproduce it. @bernd, can you confirm that it's fixed?

@ousmaneo Aye, the cursor is visible now in light and dark mode. :+1: 

The syntax color on a highlighted line is quite difficult to see, though. (light mode) Should I create a new issue for that?

![image](https://github.com/Graylog2/graylog2-server/assets/461/847a829b-c424-4807-b282-2ba84e3c1801)

**Comment by ousmaneo** [comment]
@bernd yes, please create an issue for that I will have a look at it.
Thank you!

**Comment by bernd** [comment]
> @bernd yes, please create an issue for that I will have a look at it. Thank you!

@ousmaneo Aye, will do! Closing this issue now.

**Comment by bernd** [comment]
@ousmaneo Follow up issue: https://github.com/Graylog2/graylog2-server/issues/18847
