### ISSUE TITLE
Dangerous graylog.conf default

### ISSUE THREAD

**Issue by voodoodrul** [Graylog2/graylog2-server#1420]
'retention_strategy'
Chef defaults this to 'delete'. That means in an otherwise clean environment, a `graylog-ctl reconfigure` can cause data loss as it immediately restarts graylog-server and may start deleting indices. Suggest that this option be moved to be configurable from /etc/graylog/graylog-settings.json

**Comment by joschi** [comment]
Closed in favor of Graylog2/omnibus-graylog2#18-
