### ISSUE TITLE
Update AWS image

### ISSUE THREAD

**Issue by citosid** [Graylog2/graylog2-server#1421]
We are using an image from graylog in our production server. Is there any way to update to 1.2? I don't want to rebuild the whole box...

**Comment by joschi** [comment]
The AMIs are using the [Graylog omnibus package](https://github.com/Graylog2/omnibus-graylog2) for which you can find upgrade information at http://docs.graylog.org/en/1.2/pages/installation/graylog_ctl.html#upgrade-graylog
