### ISSUE TITLE
RecieveBufferSize for GELFUDPInput

### ISSUE THREAD

**Issue by Knechtruprecht81** [Graylog2/graylog2-server#1422]
Hi,

after upgrade to 1.2GA ive found this log message in server.log:

2015-09-16T11:20:05.480+02:00 WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input GELFUDPInput{title=General UDP Source, type=org.graylog2.inputs.gelf.udp.GELFUDPInput, nodeId=xxxx-xxx-xxx-xxx-xxxxx} should be 1048576 but is 131071.

But the Input if configuered with this:
![buffersize](https://cloud.githubusercontent.com/assets/12628820/9901134/c4a9c56e-5c65-11e5-92c2-667b2ef455f2.PNG)

**Comment by bernd** [comment]
The default max UDP buffer setting in Linux is 131071. You have to increase the max buffer size via `sysctl`.

```
sysctl -w net.core.rmem_max=1048576
```

**Comment by bernd** [comment]
Closing this, please re-open if you still have problems after increasing the UDP buffer setting. Thank you!

**Comment by Knechtruprecht81** [comment]
Perfect. Thank you.
