### ISSUE TITLE
Unable to delete lookup table cache

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#14238]
## Expected Behavior

Deleting a lookup table cache should remove it.

## Current Behavior

A error notification is shown with a cache id of `undefined`.

![image](https://user-images.githubusercontent.com/41929/208108364-2917ade0-a253-4ea7-bb20-92735a18d60b.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by Mnchstrcityblues79** [comment]
I am still seeing this issue:
Graylog Version: 5.0.3+a82acb2
Java Version:
Opensearch Version: 2.0.1
MongoDB Version: 6.0.4
Operating System: Debian 5.19.6-1
Browser version: Version 109.0.5414.120 (Official Build) (64-bit)

**Comment by spyhuntergenral** [comment]
Seeing the same on:

Graylog Version:  5.0.3+a82acb2
elasticsearch-oss:7.10.2
MongoDB Version: 5.0.13
Operating System: Official Docker Image (latest)
Browser version: Firefox Version 110.0 (Official Build) (64-bit)

also when browsing to the lookup table:
![image](https://user-images.githubusercontent.com/41215704/220466754-416213b4-3434-4de9-9cdb-925232cb0e3c.png)
