### ISSUE TITLE
API Browser for PUT `/cluster/system/loggers/{loggerName}/level/{level}`returns HTTP 500

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#14256]
`/cluster/system/loggers/{loggerName}/level/{level}` returns an error, HTTP 500

```
{
  "type": "ApiError",
  "message": "HTTP 500 Internal Server Error"
}
```

## Expected Behavior

API to change logger logging level work as expected and not return an error status.

## Current Behavior

- `/cluster/system/loggers/{loggerName}/level/{level}`works but returns HTTP 500

## Steps to Reproduce (for bugs)

![image](https://user-images.githubusercontent.com/107503402/208520130-119a5593-4ca7-4cbf-b941-a4506a47bd14.png)
![image](https://user-images.githubusercontent.com/107503402/208520221-11ec17a5-33c8-4f3a-988c-2bc9bfc6f15b.png)

## Context

Researching and troubleshooting an issue related to Alert Notification grace period.

## Your Environment

* Graylog Version: Graylog 5.0.1
* Java Version: 17.0.5
* Elasticsearch Version: OpenSearch 2.4.1
* MongoDB Version: 5.0.14
* Operating System: Ubuntu Server 20.04 LTS
* Browser version: Chrome 108.0.5359.124

**Comment by dennisoelkers** [comment]
Hey @drewmiranda-gl,

there are two different issues here:

  1. You are getting a 404 on `PUT /system/loggers/subsystems/...` because you are using a logger name where the name of a subsystem is expected. You can do a `GET /system/loggers/subsystems` to list available subsystems
  2. Can you check your server log if you see anything related to the 500 you are getting when using the cluster endpoint?

**Comment by drewmiranda-gl** [comment]
oh my :( i misread and was using the wrong endpoint 🤦 . I can fix the title so its not misleading or confusing.

Regarding the 500 error, it appears the api-browser is sending the [REQ] as `Content-Type: text/plain;charset=UTF-8`

Here is the error in `server.log`

```
ERROR [WriterInterceptorExecutor] MessageBodyWriter not found for media type=text/plain, type=class java.util.HashMap, genericType=java.util.Map<java.lang.String, org.graylog2.shared.rest.resources.ProxiedResource$CallResult<java.lang.Void>>
```

If i use postman to set the `Accept: application/json` header, i do get HTTP 200:

![image](https://user-images.githubusercontent.com/107503402/208733520-15757203-9f36-490d-b9b6-3ed814e8b1be.png)

**Comment by danotorrey** [comment]
A similar issue is described with a workaround in https://github.com/Graylog2/graylog2-server/issues/11408#issuecomment-934208332.
