### ISSUE TITLE
Inconsistent sorting of indexes on index set page 

### ISSUE THREAD

**Issue by boosty** [Graylog2/graylog2-server#14280]
## Expected Behavior

The indexes on an index set page should be sorted from newest to oldest, with the current write index being the first entry.

## Current Behavior

<img width="1576" alt="Screenshot 2022-12-21 at 13 29 44" src="https://user-images.githubusercontent.com/4270/208905407-481f72c2-fc60-438a-8868-f5f202ea3771.png">

<img width="881" alt="Screenshot 2022-12-21 at 13 29 54" src="https://user-images.githubusercontent.com/4270/208905427-92d8f964-7843-493d-944f-e6a6f9426563.png">

## Steps to Reproduce (for bugs)

I noticed this on a Graylog Cloud demo instance

## Your Environment

* Graylog Version: Graylog Cloud 5.0.1 (319)
* Browser version: Safari Version 16.1 (18614.2.9.1.12)

**Comment by luk-kaminski** [comment]
Indices seem to be sorted on the FE side. I'll have a chat in the team to figure out if we want to change FE sorting, or move sorting to the BE.
