### ISSUE TITLE
Memory leak when using Docker conatiner graylog2/allinone

### ISSUE THREAD

**Issue by mulyoved** [Graylog2/graylog2-server#1430]
On Ubuntu 14.04, Azure, Just starting the to container, only special option

  environment:
    GRAYLOG2_REST_ENABLE_CORS: true

Send logs in a rate of about 150 messages a minute
Seem some memory leak from Java 

![graylog-memory](https://cloud.githubusercontent.com/assets/2309907/9961693/97163f8a-5e2a-11e5-8c06-43888c90ade9.png)

**Comment by mariussturm** [comment]
Hi Muly,
I wouldn't consider this as a memory leak, the container simply consumes
more ram while building up the index for the incoming messages. In case the
service stops working we can debug the situation.

Cheers,
Marius


On 18 September 2015 at 16:31, Muly Oved <notifications@github.com> wrote:

> On Ubuntu 14.04, Azure, Just starting the to container, only special option
>
> environment:
> GRAYLOG2_REST_ENABLE_CORS: true
>
> Send logs in a rate of about 150 messages a minute
> Seem some memory leak from Java
>
> [image: graylog-memory]
> <https://cloud.githubusercontent.com/assets/2309907/9961693/97163f8a-5e2a-11e5-8c06-43888c90ade9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Graylog2/graylog2-server/issues/1430>.
>



-- 
Developer

Tel.: +49 (0)40 609 452 077
Fax.: +49 (0)40 609 452 078

TORCH GmbH - A Graylog Company
Steckelhörn 11
20457 Hamburg
Germany

https://www.graylog.com <https://www.torch.sh/>

Commercial Reg. (Registergericht): Amtsgericht Hamburg, HRB 125175
Geschäftsführer: Lennart Koopmann (CEO)

**Comment by mulyoved** [comment]
Will close this for now, will keep monitoring
