### ISSUE TITLE
Charset and encoding

### ISSUE THREAD

**Issue by Mykolaichenko** [Graylog2/graylog2-server#1431]
Hi, all!
I have a problem with charset or encoding. First of all, I wish to make grok pattern to my logs. I had written the regular expression, added it to grok pattern. 
When I try it in online decoders, it works perfectly. But when I try it to use in my GrayLog - it doesn't work. 
For my opinion, it doesn't work because when I want to create extractor, I have bad encoding: 
![image](https://cloud.githubusercontent.com/assets/10963524/9969334/8eb74eb6-5e56-11e5-94e7-dcfdc575b515.png)

But at the same time, in Search it looks pretty good. 
![image](https://cloud.githubusercontent.com/assets/10963524/9969356/bbc0d616-5e56-11e5-822b-7d9579afe684.png)
I know that Graylog Collector that I installed on my Windows Server had default UTF-8 charset, I changed it to Windows-1251, but it also didn't help. At the screen with bad charset shows KOI8 charset (I'm from Ukraine and logs sometimes have Cirrilic characters). 

Can anyone help me with my problem? 

Thanks, a lot.

**Comment by Mykolaichenko** [comment]
Morning, I have some additional part of information. I made query directly to elasticsearch, and have right results. No troubles with the charset or other problems. WTF? 
![screen shot 2015-09-19 at 10 33 14 am](https://cloud.githubusercontent.com/assets/10963524/9975159/5aff032a-5eba-11e5-9d27-f198664163ca.png)

Thanks for a help.

**Comment by dennisoelkers** [comment]
Is it possible that your MongoDB instance has a weird charset configured?

**Comment by bernd** [comment]
No feedback in a long time, please re-open if this is still an issue with a recent release. Thank you!

**Comment by ameyrk18** [comment]
This is a stupid humanoid error.  I also got the same error. This was caused because I had configured RAW/plaintext UDP input plugin when my output plugin in Fluentd was gelf. Deleted the RAW/plaintext UDP input plugin and recreated a new GELF UDP input plugin in gray log solved the issue.
