### ISSUE TITLE
Difference between field analyzed and not analyzed in Elastic Search

### ISSUE THREAD

**Issue by Mannoj87** [Graylog2/graylog2-server#1432]
I get below as the mapping description for the field requestInfo. I see index is not analyzed but fields having analyzed and type in string.

Does it analyze and store or just stores?
```
{
"requestInfo" : {
            "properties" : {
              "URI" : {
                "type" : "string",
                "index" : "not_analyzed",
                "fields" : {
                  "analyzed" : {
                    "type" : "string"
                  }
                }
              },
}
```

**Comment by joschi** [comment]
By default, only the following attributes are being analyzed: `source`, `message`, and `full_message` (see https://github.com/Graylog2/graylog2-server/blob/1.2.0/graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java).

If you want to use a custom mapping for your messages, you'll have to create an appropriate index template with the schema of your data: https://www.elastic.co/guide/en/elasticsearch/reference/1.7/indices-templates.html
