### ISSUE TITLE
Update PaloAltoParser field to accept strings

### ISSUE THREAD

**Issue by giveen** [Graylog2/graylog2-server#14363]
`ERROR [PaloAltoTypeParser] Error parsing field application_response_time, auto is not a valid numeric value`

## Possible Solution
Parser should probably be changed to expect a string now as well for that field as it looks like Palo Alto changed their field formats in syslog

* Graylog Version: 5.0.2+59d96f8
* Java Version: Eclipse Adoptium 17.0.5
* Opensearch Version: 2.3.0
* MongoDB Version: 6.0.3"
* Operating System: Redhat 8

**Comment by bernd** [comment]
@giveen What PaloAlto version are you using? Thanks!

**Comment by giveen** [comment]
> @giveen What PaloAlto version are you using? Thanks!

Device: PA-5450
Software Version: 10.1.7


The logs I feed to graylog are my threat, url filtering, and globalprotect logs, but what is weird is I cant find the application_response_time in the syslog fields report from Palo Alto for those logs

https://docs.paloaltonetworks.com/pan-os/10-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/url-filtering-log-fields

https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-admin/monitoring/use-syslog-for-monitoring/syslog-field-descriptions/globalprotect-log-fields/globalprotect-log-fields-for-pan-os-913-and-later-releases#id5795bd71-1dc5-4f82-872d-a9ba6cb7cedf

I'm leaning toward an issue in URL Filtering, but completely unsure
_Content Type (contenttype) | Content type of the HTTP response data. Maximum length 32 bytes._

**Comment by giveen** [comment]
Submitted a pull for this
https://github.com/Graylog2/graylog-plugin-integrations/pull/1283
