### ISSUE TITLE
Multiple Widgets Error: OpenSearch exception type=null_pointer_exception

### ISSUE THREAD

**Issue by jivepig** [Graylog2/graylog2-server#14386]
Previously on V4.3 these widgets were loaded with empty widgets with no data.  Some for the data captured worked.  Now in V5 Multiple widgets are displaying an error:

While retrieving data for this widget, the following error(s) occurred:
    OpenSearch exception [type=null_pointer_exception, reason=Cannot invoke "org.opensearch.search.aggregations.InternalAggregations.getSerializedSize()" because "reducePhase.aggregations" is null].

## Expected Behavior
Graylog with no logs or Graylog with Logs should not have this error.

## Current Behavior
Dashboards and widgets impacted:
- Fortigate Overview -DNS Overview Tab-> DNS Messages by Severity Over Time Widget
- Fortigate Overview -Application Control Overview Tab-> Application Control Messages by Severity Over Time widget
- SonicWall NGFW Overview -Overview Tab->Messages by Severity Over Time Widget
![image](https://user-images.githubusercontent.com/77077803/211344346-7f943e00-7fd4-450b-b32c-2c117564155f.png)

![image](https://user-images.githubusercontent.com/77077803/211344381-da285539-7b16-4201-9c61-11fe98083cef.png)
![image](https://user-images.githubusercontent.com/77077803/211344403-110be4a1-ea95-4b45-a318-af7777545e6d.png)

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
As noted

## Context
Failed widget load

## Your Environment

* Graylog Version:V5.02
* Java Version: V17
* Elasticsearch Version: 2.4 & V1.3
* MongoDB Version:6
* Operating System:Ubuntu/Docker
* Browser version:/na

**Comment by jivepig** [comment]
Illuminate V3.1 is installed.

**Comment by janheise** [comment]
@jivepig Hi, just for clarification can you confirm: in v4.3 this worked with OpenSearch 1.3?

**Comment by jivepig** [comment]
Yes It worked in my instance on V4.3 and it running Opensearch V1.3

**Comment by janheise** [comment]
thx.

**Comment by janheise** [comment]
If there are no results from the query, the following in OpenSearch returns without "aggregations":

https://github.com/opensearch-project/OpenSearch/blob/8c9481a2ca5f172157ba7ce30dd03324b0527428/server/src/main/java/org/opensearch/action/search/SearchPhaseController.java#L465-L467

Which creates the NPE further along in OpenSearch at:

https://github.com/opensearch-project/OpenSearch/blob/8c9481a2ca5f172157ba7ce30dd03324b0527428/server/src/main/java/org/opensearch/action/search/QueryPhaseResultConsumer.java#L163-L165

1. Still have to investigate if this is only "multi-term" related 
2. find out how to file a proper bug issue with OpenSearch

**Comment by janheise** [comment]
@jivepig Sorry to ask again: I could not reproduce the problem with GL5 and OpenSearch 1.3. Was this a combination that you had tested?

**Comment by janheise** [comment]
Michael confirmed that it started with using 2.x

**Comment by janheise** [comment]
The changes in aggregations made for 5.x were modified and backported to 5.0 so that the old logic is in place again. These errors should no longer occur. The new logic is still available for aggregations, but in a way to not crash existing widgets.

**Comment by jivepig** [comment]
Currently Graylog V5.0.3 and OpenSearch V2.5, I do not see these errors now.
