### ISSUE TITLE
Update Community Support page to point to FR page

### ISSUE THREAD

**Issue by mike-csis** [Graylog2/graylog2-server#1438]
Hi,

I was just about to leave a FR here, but read the guidelines in the last minute. The guidelines contradict what's written here: https://www.graylog.org/community-support/, where it says (in bold): "The issue trackers also a great place to leave feature requests.".

You should update this page and point to the FR portal instead, at:
https://www.graylog.org/product-ideas/

**Comment by joschi** [comment]
True, we'll update the text. Thanks for reporting!
