### ISSUE TITLE
Error sending messages with multiple LDAP mail values

### ISSUE THREAD

**Issue by tillo** [Graylog2/graylog2-server#1439]
# Situation
I have *inetOrgPerson* LDAP users mapped into Graylog.

# Behaviour
When a user has multiple values within the *mail* field, messages are not sent and the following error message is shown:

```
The Graylog server encountered an error while trying to send an email. This is the detailed error message: org.apache.commons.mail.EmailException: javax.mail.internet.AddressException: Illegal address in string ``tillo@tillo.ch, martino@dellambrogio.ch'' (javax.mail.internet.AddressException: Illegal address in string ``tillo@tillo.ch, martino@dellambrogio.ch'')
```

# Expected behaviour
I guess it should use an array instead of a comma to set multiple recipients, seems to be compatible with both org.apache.commons.mail and javax.mail.internet. I expect to have the message delivered to both recipients.

# Debug information
I'm running  latest **graylog-server** **1.2.0-5** on latest **Debian stable** **8.2** with latest **Oracle JDK** **1.7.0_80**.

# Additional comment
As org.apache.commons.mail is bundled into graylog.jar I don't know what version it is.
It really shouldn't be bundled, neither should 99% of the code in there, but I understand it's difficult to keep up with various distributions dependencies.

**Comment by bernd** [comment]
This will be fixed in the upcoming Graylog 1.2.2 release. Thank you for the report!

See #1492 for details.
