### ISSUE TITLE
Error occurs when creating grouping for fields in event streams.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#14404]
## Description

When creating an aggregation for e.g. the `All events` stream, which includes a grouping for a field which only exists in the stream, like `priority`

<img width="520" alt="Screenshot 2022-09-22 at 12 29 32" src="https://user-images.githubusercontent.com/108661699/191735629-4a6f2952-02b6-4f6a-b9f3-d2a0d543f1a1.png">

the widget creation is not possible. When changing the field for an existing grouping to `priority` there is an error.

<img width="1130" alt="Screenshot 2022-09-22 at 12 29 46" src="https://user-images.githubusercontent.com/108661699/191736099-e81fe17d-4213-4915-b6af-30d8792067c5.png">

## Your Environment

* Graylog Version: 5.0

**Comment by BBruce-Graylog** [comment]
Following up on the status of this issue. @linuspahl

**Comment by linuspahl** [comment]
@BBruce-Graylog This has been fixed with https://github.com/Graylog2/graylog2-server/pull/14387, sorry I forgot to close the issue. We released the bugfix with 5.0.3 and 4.3.12.
