### ISSUE TITLE
Alert http callback  body are to large causing failed in v2.3.2?

### ISSUE THREAD

**Issue by kwangsing3** [Graylog2/graylog2-server#14411]
### Platform - ubuntu 20.04

---
Hi, there 
I made a web service to catch graylog POST callback triggered from streams and it works fine in **past version**.

Recently, I build a new Graylog runs on v2.3.2
but POST alerts callback are always failed and return 500,  **I directly tried cURL POST on command line from the same machine and my service runs fine**, 
so maybe there are some issues in this part ??

by the way, how could I debug the message that Graylog trigger out with the POST callback ? 
Even I could recive the body Graylog sent to me,  but want to know what graylog actually sent out.

![image](https://user-images.githubusercontent.com/18378969/211745506-e01ec7ce-a0a8-4067-907e-a39b9acbd1b6.png)

This case is new install, but another one instance  **updated from older version** to the same version would trigger successfully, is there anyone know any the possible reason cause this situation?

**Comment by kwangsing3** [comment]
I found "tcpdump" tool to capture what I got, and it shows me very very very large request body.

Here's  another info I have:
```
PayloadTooLargeError: request entity too large
```

how it possible ?

**Comment by kwangsing3** [comment]
update:
I  pull up the size of my buffer pool, and could recived the callback, but need to up to "500mb", the reason cause it beacuse my stream are import from **Content Pack** (other graylog).    and the callback will reapeat all the alert rules once on what stream I hit, then it cause me bunch of stuff.  ( I got more than 300+ keywords on one streams).

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/).

Thank you!
