### ISSUE TITLE
Graylog 4.x repository broken

### ISSUE THREAD

**Issue by mika** [Graylog2/graylog2-server#14413]
We're using graylog-server 4 on Debian and apt started to complain today:

```
Err:9 https://packages.graylog2.org/repo/debian stable Release
  404 Not Found [IP: 188.114.96.3 443]
```

Looking at the documentation at https://go2docs.graylog.org/4-x/downloading_and_installing_graylog/debian_installation.html it also seems to be broken:

```
% wget https://packages.graylog2.org/repo/packages/graylog-4.4-repository_latest.deb
--2023-01-11 07:40:55--  https://packages.graylog2.org/repo/packages/graylog-4.4-repository_latest.deb
Resolving packages.graylog2.org (packages.graylog2.org)... 172.67.153.95, 104.21.88.209, 2606:4700:3035::ac43:995f, ...
Connecting to packages.graylog2.org (packages.graylog2.org)|172.67.153.95|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-11 07:40:56 ERROR 404: Not Found.
```

**Comment by bernd** [comment]
@mika Thank you for the report! :pray:  We had a DNS issue for the repository service, which is fixed now. The repository should work again.

The documentation needs to be corrected. There is no 4.4 Graylog release. We will get that fixed as well.

**Comment by mika** [comment]
@bernd thanks for the fast response! :+1:
