### ISSUE TITLE
AMPQ Inputs should support AMPQ v1.0

### ISSUE THREAD

**Issue by exabrial** [Graylog2/graylog2-server#1441]
AMPQ Inputs should support AMPQ v1.0.

Sorry if this is a dupe, but I searched and couldn't find any related issues.

**Comment by joschi** [comment]
Graylog is currently using the RabbitMQ Java client which only supports AMQP 0.9.1, so support for AMQP 1.0 in the near future is rather unlikely.

This being said, there's [Apache Qpid Proton](https://qpid.apache.org/proton/) which could be used to implement a AMQP 1.0-compatible plugin.

**Comment by exabrial** [comment]
Have an example of how to write an input plugin? I'm not sure how scary it is, but I'd at least like to take a  look...

**Comment by joschi** [comment]
Documentation about writing plugins is a little bit sparse. You can use http://docs.graylog.org/en/1.2/pages/plugins.html as a starting point and peek into some of the input plugins we've open sourced, e. g. https://github.com/Graylog2/graylog-plugin-mqtt or https://github.com/Graylog2/graylog-plugin-zeromq

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
