### ISSUE TITLE
graylog-server should allow the use of alternative source field

### ISSUE THREAD

**Issue by exabrial** [Graylog2/graylog2-server#1442]
graylog-server should allow the use of alternative source field. 

I wrote a customer bridge that takes JMS messages and calls a TCP input on GrayLog, but graylog will not respect the source field in the GELF message. Graylog should allow the user to defeat the reverse DNS lookup, or look at another field in the GELF message to specify the traffic source.

**Comment by joschi** [comment]
You can use another name than `source` in your GELF message and then apply an extractor to copy the contents of that custom field into the `source` field.

**Comment by exabrial** [comment]
Oh duh... Well there's no point for this ticket then. Closing!
