### ISSUE TITLE
Filter out weak TLS ciphers 

### ISSUE THREAD

**Issue by kodjo-anipah** [Graylog2/graylog2-server#14428]
[HS-1353100664](https://app.hubspot.com/contacts/8267556/ticket/1353100664/)
## Expected Behavior

Using graylog as a server & client, negotiating with weak ciphers and establishing a TLS connection should not be possible unless this is intentionally enabled via `enabled_tls_protocols`. 

## Current Behavior

Currently following ciphers are not filter out : `TLS 1.2 ciphers: TLS_RSA_WITH_AES_128_GCM_SHA256 TLS_RSA_WITH_AES_256_GCM_SHA384`

## Possible Solution

Suggestions: weaker ciphers should by default be filtered out. 

## Steps to Reproduce (for bugs)

1. Run graylog with configured TLS
2. Check allowed ciphers

## Your Environment

* Graylog Version: v4.3
* Java Version: 1.8, 11
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
Heads up: we need to take backwards compatibility with clients into account.
