### ISSUE TITLE
Graylog cant see some indicies.

### ISSUE THREAD

**Issue by mishapolitaev** [Graylog2/graylog2-server#1444]
I want run graylog as root user and get fall down))

Change "setuid" and "setgid" in "/etc/init/graylog-server.conf" and "/etc/init/graylog-web.conf" to "root". After I change back to "graylog" and "graylog-web" respectively.

But now, if i run search, graylog cant see my indicies for last week. I see only new entries, which received after i back up setuid/setgid settings. Additionaly, i cant see entries for last week and can see older data, it depend on how graylog been install. Up to 16 september he run manual, from tar folder. After 16 september i install it from deb packages. How way of install depend on which data i can see i dont know.

My question is: 
How i tell graylog do search in all indicies? Lost for one week entries not very good way. How i can include in search that data which he exclude from search query.

Also my "rotation_strategy" was "time" and set in 1 day. With this setting I see strange time range of indicies. I see "Contains message up to 46 years ago" in that index which been rotate yesterday and consist messages only for 1 day.

Now i change "rotation_strategy" to "count". With it no have this problem.

Thank for answer to all.

**Comment by joschi** [comment]
Please use [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or [our IRC channel #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) to discuss general problems with Graylog.
