### ISSUE TITLE
New Ldap multiple email detection breaks email alerting

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1445]
Hello,

Since 1.2, Graylog find multiple email to an ldap account and record it like:

email: "email1@corp, email2@corp"

When you associate this account to an alert, it raise following image:

The Graylog server encountered an error while trying to send an email. This is the detailed error message: org.apache.commons.mail.EmailException: javax.mail.internet.AddressException: Illegal address in string ``email1@corp, email2@corp'' (javax.mail.internet.AddressException: Illegal address in string ``email1@corp, email2@corp'')

**Comment by edmundoa** [comment]
Duplicated of #1439
