### ISSUE TITLE
When creating an extractor, "host" is not an field that's able to be selected.

### ISSUE THREAD

**Issue by exabrial** [Graylog2/graylog2-server#1446]
When creating an extractor, "host" is not an field that's able to be selected.

https://www.graylog.org/resources/gelf/

The standard GELF format includes a "host" field. However, when you go to create an extractor, you cannot use it:
![screen shot 2015-09-23 at 12 11 57 pm](https://cloud.githubusercontent.com/assets/1392297/10052400/4f7b8264-61ec-11e5-8e29-d158b1f9b0de.png)

Use case: I'm attempting to override the source field with an extractor. I would like to use the host field, so that way I can attribute the source with the original host that created the log message, not the source address of the TCP connection into graylog.

**Comment by joschi** [comment]
I agree that this is a little bit confusing.

The `host` field of a GELF message is being stored in the `source` attribute in Graylog. Also the `short_message` field of a GELF message is being stored in the `message` attribute.

**Comment by exabrial** [comment]
Joschi, I don't mean to press, but here's the issue we're seeing. We have a TCP GELF listener setup in graylog. There is a separate program that is taking messages off a AMPQ v1 queue and pushing them into graylog. The `Host` field of these messages is set correctly, however it's being overwritten by graylog with the reverse DNS of the message listener, instead of reflecting the original host that sent the message.

It would be nice to have a way to disable reverse DNS lookup so the value that's pushed in by the GELF input stays in the source field. Currently there seems to be no workaround. 

Thanks!

**Comment by joschi** [comment]
I'd recommend adding a message field (e. g. `original_source`, `original_host`, or `forwarded_for`) to the GELF message your custom client which consumes the messages via AMQP and forwards them to Graylog.

If you think this is a feature absolutely missing from Graylog, please add an entry to our [product ideas portal](https://www.graylog.org/product-ideas/).

**Comment by exabrial** [comment]
sounds good, thanks
