### ISSUE TITLE
Extractor to apply math expression on a field

### ISSUE THREAD

**Issue by sivasamyk** [Graylog2/graylog2-server#1450]
Currently there are extractors to convert a field to numeric by parsing it. It would be great if we can have an extractor to apply math expression on an existing/converted numeric field. User can specify the expression like {max.heap.mem}/1024 in the converter and create a new field or overwrite existing field.

**Comment by cdino** [comment]
+1

**Comment by joschi** [comment]
@sivasamyk This will be possible with next version of the [Pipeline Processor Plugin](https://github.com/Graylog2/graylog-plugin-pipeline-processor), see Graylog2/graylog-plugin-pipeline-processor#111
