### ISSUE TITLE
graylog 5 - "Trusted Header Authentication" news users are not created if missing

### ISSUE THREAD

**Issue by ITJamie** [Graylog2/graylog2-server#14501]
## Expected Behavior
we have Trusted Header Authentication enabled. if a user does not already exist in graylog's user db i expect that user to get created with no roles assigned

## Current Behavior
user browses to graylog web ui and is prompted with a login screen, even though our sso system is handing us the correct "Remote-User" header

## Possible Solution
update graylog to auto-create users

## Steps to Reproduce (for bugs)
1. setup graylog and front it with nginx or other reverse proxy
2. force a header with "Remote-User" set to a username that does not exist in graylog
3. user will be prompted with a login screen

## Context
If a user has passed auth with a reverse proxy the system behind it should accept that the user presented in the the Remote-User variable as correct and create a user if missing

## Your Environment

* Graylog Version: 5.0.2 ce docker container

**Comment by bernd** [comment]
Please check the comment here: https://github.com/Graylog2/graylog2-server/issues/9714#issuecomment-744439535
