### ISSUE TITLE
4.3.x to 5.0.2 upgrade migrations fail due to invalid timezone

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/graylog2-server#14517]
Per https://github.com/Graylog2/graylog-plugin-enterprise/issues/4311 it's noted that it's possible to set timezones that are valid in the web UI, but apparently not valid for the greater operation of Graylog. 

Worked with customer via HS-1392488743 which would die during initial start of 4.3.x -> 5.0.2:

Report migration:
![image](https://user-images.githubusercontent.com/2953243/214727019-815119f4-2198-4105-96a2-ab232ddb4221.png)

It looks like my screenshot of the user migration did not save, but was similar in message. MongoDB document: 
![image](https://user-images.githubusercontent.com/2953243/214727430-5e051017-a718-44a2-baf0-93c1b2171a1d.png)

This looped until fixed:

Fixed user migration by modifying the _users_ document in place to change the timezone from EST to America/Toronto: `db.users.updateOne({"_id" : ObjectId("the object id")}, {$set: {"timezone" : "America/Toronto"}})`

Fixed reports migration by, with permission of the customer, emptying the _reports_ collection. Customer acknowledges they will need to set up their reports again. 

Graylog then started without further issue.

**Comment by patrickmann** [comment]
Fixed by Graylog2/graylog-plugin-enterprise#4658, Graylog2/graylog2-server#14605 and backported to 4.3 and 5.0.
