### ISSUE TITLE
Rest API not accessible for user with role Reader

### ISSUE THREAD

**Issue by rbrindl** [Graylog2/graylog2-server#1454]
* I created a new user with built-in role "Reader"
* with curl, run the following query: "http://rta-services.dynatrace.vmta:12900/search/universal/relative?query=*&range=180&fields=source%2Cmessage"
* running curl with -v returns: HTTP/1.1 403 Forbidden ... {"type":"ApiError","message":"Not authorized"}```

If I change the role of my user to Admin, above query works. If I change it back to Reader, I get the same result as above (403).

The possibilities of User Roles administration do not match the power of the REST API. I guess that's the reason why only Admin role is allowed to access it.

**Comment by joschi** [comment]
The "Reader" role is only allowed to certain streams but not to use the universal search (which would allow querying all messages). While you can create the required permissions via the Graylog REST API, I wouldn't advise to do so but rather create a stream which matches the wanted messages.
