### ISSUE TITLE
Decorators configuration UI unclear

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#14546]
## Expected Behavior
It should be clear what the dropdown in the decorator section does.

## Current Behavior
![image](https://user-images.githubusercontent.com/52014/215080926-37f5c35a-aaab-4319-a310-40f99eab7571.png)
As seen above, the default selection is an ID whose purpose is not immediately obvious.

If the intention is to show the current configuration, we should show the entire config for all streams on the page, as currently, this is the only section that requires the user to make a selection to see the current state.

If there are decorators in the non-default stream, then it's not immediately obvious that some configuration is active, which is confusing.

## Possible Solution
Show a concise overview of the entire configuration, e.g. for all streams, show the number of configured decorators if there are any, instead of requiring a selection by the user.

This allows a quick check of whether any default decorators are active. This is important because some decorators can have a significant performance impact on searches.

## Steps to Reproduce (for bugs)
1. Navigate to System/Configuration
2. Look at Decorators Config section

## Context
Trying to find a slowdown on the default search page, that didn't happen in a stream search. The cause was a slow whois decorator, but it wasn't immediately obvious that any where configured.

## Your Environment

* Graylog Version: 5.0.1 (but applies to versions since Dec 2019)

**Comment by boosty** [comment]
Related:
- https://github.com/Graylog2/graylog2-server/issues/13467
- https://github.com/Graylog2/graylog2-server/issues/13465
