### ISSUE TITLE
Unable to perform search query: [1:293] [bool] unknown field [disable_coord].

### ISSUE THREAD

**Issue by chaeyan** [Graylog2/graylog2-server#14554]
I can't do anything in Graylog, all I get is this error below.
`Unable to perform search query: [1:293] [bool] unknown field [disable_coord].`

I'm on Ubuntu 18.04 and I followed the docs from Graylog.

![image](https://user-images.githubusercontent.com/32681723/215129515-2d869d30-adb2-4342-8238-38b3fe81264d.png)

**Comment by linuspahl** [comment]
Hey @chaeyan, this is most likely not an issue with graylog. Did you had a look at similar community posts, like https://community.graylog.org/t/after-elasticsearch-upgrade-7-15-2-unable-to-perform-search-query-1-608-bool-unknown-field-disable-coord/22085?

Please provide information like your Elasticsearch / OpenSearch version when opening an issue. Thank you.

**Comment by linuspahl** [comment]
Since this is most likely not a graylog bug, I am closing this issue. If you had a look at related community posts and you still think this is a bug, feel free to reopen the issue.
