### ISSUE TITLE
Roles field not updated after PUT on REST API

### ISSUE THREAD

**Issue by paulbakker** [Graylog2/graylog2-server#1456]
Creating users, including setting roles works. 
Updating users also works, but setting roles doesn't seem to have any effect. The online REST docs do show "roles" as a field for PUT on /users/{username}.

There are no errors in the logs. When setting other fields besides roles, the other fields get updated successfully.

**Comment by bernd** [comment]
Thank you for the report. This bug will be fixed in the upcoming Graylog 1.2.2 release.
