### ISSUE TITLE
Legacy/Search/Absolute offset parameter not effect any more

### ISSUE THREAD

**Issue by stevehogo** [Graylog2/graylog2-server#14571]
After i upgrade version from 4.2.6 to 4.3.9 the offset parameter didn't effect on the search result.

Before version 4.2.x, when i change the offset on query parameter, the result will be changed base on this parameter. But from version 4.3.x and above,  when i change that parameter value, the search result just response data from offset 0.

* Graylog Version: 4.3.0 and above

**Comment by janheise** [comment]
@stevehogo Hi, can you please be a bit more specific? What other parameters do you set on that call? Do you have a complete example? Also, which Elasticsearch version are you using?

**Comment by stevehogo** [comment]
@janheise here is my request uri & parameter: /api/search/universal/absolute?query=ctxt_log_type%3Auser_activity_log&from=2022-11-01+00%3A00%3A00&to=2023-01-31+23%3A59%3A59&limit=20&offset=20&sort=timestamp%3Adesc&fields=ctxt_breadcrumb%2Cctxt_product%2Cctxt_action_type%2Cip%2Ctimestamp%2Cuser%2Cctxt_file_url

If i switch graylog back to  version 4.2.6 , that api will return data from offset 20.

I'm using  image opensearchproject/opensearch:1, here is Opensearch information

{
  "name" : "os-node1",
  "cluster_name" : "os-cluster",
  "cluster_uuid" : "RcU9cPCuSY6Pgw2_CBef9g",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "tar",
    "build_hash" : "db18a0d5a08b669fb900c00d81462e221f4438ee",
    "build_date" : "2022-12-07T22:59:20.186520Z",
    "build_snapshot" : false,
    "lucene_version" : "8.10.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}

**Comment by janheise** [comment]
@stevehogo thanks for the clarification, I can now see the problem - but am not sure when/how it's going to get resolved.

**Comment by janheise** [comment]
Problem description: `AbsoluteSearchResource.searchAbsolute():103` parameter `offset` is no longer referenced/taken into consideration.
Also, `AbsoluteSearchResource.searchAbsoluteChunked():134` parameter offset is a problem here because since ES6, offset in a scroll command fails validation.
Both Problems seem to be in `KeywordSearchResource` and `RelativeSearchResource`

**Comment by janheise** [comment]
@stevehogo the fix made it into 4.3.12 - let me know if it's working again for you.
