### ISSUE TITLE
DataNode: copy/rewrite graylogctl script

### ISSUE THREAD

**Issue by janheise** [Graylog2/graylog2-server#14582]
needs to be changed significantly for the datanode

**Comment by bernd** [comment]
@janheise We don't need all the features in that script. I think we can use something similar to the forwarder script: https://github.com/Graylog2/forwarder/blob/main/forwarder/bin/graylog-forwarder.sh

**Comment by janheise** [comment]
TODO: default config params for IntelliJ crash with an empty conf file
