### ISSUE TITLE
Graylog V5.0.3 Lookup Tables  UI frame larger than window

### ISSUE THREAD

**Issue by jivepig** [Graylog2/graylog2-server#14583]
When viewing Data Adapters, the UI window is wider than the frame 
## Expected Behavior
This should align like Data Adapters and Cache

## Current Behavior
UI Bug

## Possible Solution
Re-align the UI to match  Data Adapters and Cache UI window.

## Steps to Reproduce (for bugs)
Graylog V5.0.3 and Opensearch

## Context
This was a previous bug reported and fixed in 5.0.2, but has come back in 5.0.3

* Graylog Version: 5.0.3
* Java Version: 17
* Elasticsearch Version: 2.5
* MongoDB Version: 6
* Operating System: N/A
* Browser version: Firefox latest

**Comment by kroepke** [comment]
@zeeklop could you prepare a backport for this into 5.0 as well, please?

**Comment by zeeklop** [comment]
> @zeeklop could you prepare a backport for this into 5.0 as well, please?

Backport PR
https://github.com/Graylog2/graylog2-server/pull/14899
