### ISSUE TITLE
Feature request: Stream rules based on input source instead of field content?

### ISSUE THREAD

**Issue by joakimlemb** [Graylog2/graylog2-server#1459]
Would like to see a feature which can create a stream rule based only upon which input it arrived on, instead of fields/content in the message entry.

As of 1.2.1 the stream rules does not seem to support this.

**Comment by joschi** [comment]
@joakimlemb You can use the "internal" message field `gl2_source_input` for this. The `gl2_source_input` field contains the ID of the input the respective message was received with.

**Comment by joakimlemb** [comment]
Thanks. (Probably should have searched a little harder before posting: https://github.com/Graylog2/graylog2-web-interface/issues/682)

Follow up question, in the web interface where can I find the ID?
It's not very obvious at the overview page /system/inputs if that info exists there.

**Comment by joschi** [comment]
@joakimlemb It's totally fine. This information isn't exactly well documented at the moment…

You can find the input ID if you click on "Show received messages" on the System -> Inputs page.
