### ISSUE TITLE
Multiple system menu failures after upgrade to 5.0.3

### ISSUE THREAD

**Issue by giveen** [Graylog2/graylog2-server#14593]
`Loading component failed: Loading chunk faaea0bb-xxxxxx failed`

```
system/nodes
system/inputs
system/index_sets
system/users
system/outputs
```

Probably more but I didnt check. I did restart the services.

* Graylog Version: 5.0.3-1
* Java Version: 17
* OpenSearch Version: 2.3
* MongoDB Version: 7
* Operating System: RH 8

**Comment by bernd** [comment]
@giveen Can you please do a full page reload or restart your browser and see if that fixes it?

**Comment by giveen** [comment]
> @giveen Can you please do a full page reload or restart your browser and see if that fixes it?

I had restarted graylog-server service and that didnt resolve the issue.

A full reboot resolved the issue, so this can be closed now.
