### ISSUE TITLE
Doc for v5, incorrect for flatten_json

### ISSUE THREAD

**Issue by BenoitPoulet** [Graylog2/graylog2-server#14596]
flatten_json doc is wrong.

https://go2docs.graylog.org/5-0/making_sense_of_your_log_data/functions_descriptions.html#flattenjson

According to this : https://github.com/Graylog2/graylog2-server/pull/13947

There is a 3rd parameter : stringify

The doc doesn’t talk about it.

**Comment by bernd** [comment]
I handed this over to the documentation team. Thanks for the report!

**Comment by lingfish** [comment]
The documentation *still* doesn't reflect this parameter.
