### ISSUE TITLE
Amazon ES Support

### ISSUE THREAD

**Issue by mfowlewebs** [Graylog2/graylog2-server#1461]
Amazon launched a managed ElasticSearch, however it does not support ES's native streaming API's. We instead have to go through one of their other managed services. It would be divine if Graylog2 gained support for streaming from one of these sources (S3, DynamoDB, Kinesis, or CloudWatch).

Some existing ideas:
https://graylog.ideas.aha.io/ideas/GL2E-I-447

**Comment by runningman84** [comment]
I could image that you are not allowed to join an manged ES cluster on AWS.

Maybe it would make sense to use HTTP transport anyway. The recent benchmark of logstash showed quite low penalties for this:

https://www.elastic.co/blog/logstash-2-0-0-beta1-released

**Comment by jalogisch** [comment]
upcoming versions of graylog will use the http transport, but the elasticsearch stack of amazon might be to outdated in functionality to be used.
