### ISSUE TITLE
Legacy /search/universal/relative sort does not works with empty enviroment

### ISSUE THREAD

**Issue by gianluca-valentini** [Graylog2/graylog2-server#14646]
Hi,
I'm using Graylog 4.3.10+6cb2860 on graylog-plus-599477f5-g2vk5 (Eclipse Adoptium 11.0.17 on Linux 5.15.0-60-generic).
Currently my enviroment have no data ingested.

In Swagger API module I’m using the **/search/universal/relative**
![image](https://user-images.githubusercontent.com/3224592/218083597-c46cb561-7444-4ade-b3b5-48ff19056748.png)

but when I set the sort param (@timestamp:desc) I have an error message
![image](https://user-images.githubusercontent.com/3224592/218083763-d75a9af5-765f-4504-a2e1-08c6c489cebf.png)
If I remove the sort operation the rest return 200 and it works fine

When I test the same rest api on an enviroment **where the data are incoming** in the system, the API works fine with the sort param set.

It seems to be a problem with empty elastic search
I hope that you wll be able to fix it as soon as it is possible or can give me a workaround

Gianluca

**Comment by gianluca-valentini** [comment]
Hi, any news about it?

**Comment by janheise** [comment]
I tried to reproduce the error with current 6.0 - even without the sort field, an error occurs. Quite simple: the index can not be found (the database is empty). We might want to change the result from a 500, though.
