### ISSUE TITLE
A lot of LDAP groups and no paging :)

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#1467]
So, here is my issue:

I have something like 5000 LDAP groups. Did configured Graylog to use them, but when I try to map the roles to the groups I'm not able, as graylog spends a lot of time searching and displaying those groups.

It would be nice if I could enable or disable some kind of feature that looks for the group while I type it's name, instead of trying to cache and display them all on the main page :)

**Comment by runningman84** [comment]
We have a similar problem, furthermore our group names are quite long like
APP_ALADIN_USA_NY_FRONTEND_DEV_TEAM_A
In the case the last part is truncated in the list.

Gathering the list takes same time aswell, so I think a cache of the whole list within graylog would make sense...

**Comment by bernd** [comment]
This has been implemented in 4.0.
