### ISSUE TITLE
The new Graylog login page does not appear on the TV in the built-in browser

### ISSUE THREAD

**Issue by tojeroman** [Graylog2/graylog2-server#14677]
After upgrading from Graylog 4 to Graylog 5, the login screen has changed. I use an LG TV to display web pages for a surveillance system (Librenms, Zabbix, GLPI and others). Unfortunately, after upgrading to Graylog 5, the dashboard stopped showing and the TV can't even display the login page (probably the integrated browser is bothered by one of the JAVASCRIPTs). Unfortunately, if I share the dashboard to everyone, I see in the log that instead of opening the dashboard, the TV wants to open the Graylog login page for me to enter data. It would be appropriate if the login page was modified to be compatible with other browsers, or if there was an option to display the dashboard on the TV without having to enter login data into Graylog.

* Graylog Version: Graylog 5.0.3+a82acb2 on graylog (Eclipse Adoptium 17.0.6 on Linux 5.15.0-1031-azure)
* Java Version:
* Elasticsearch Version: 
* MongoDB Version:
* Operating System: 
* Browser version:

**Comment by dennisoelkers** [comment]
Hey @tojeroman,

many thanks for reporting this. We will take a look into this and try to fix it as soon as possible. Which LG TV (model) are you using?

**Comment by tojeroman** [comment]
Thanks for the quick response, this is the LG 55UP75003LF

**Comment by tojeroman** [comment]
> Hey @tojeroman,
> 
> many thanks for reporting this. We will take a look into this and try to fix it as soon as possible. Which LG TV (model) are you using?

Thanks for the quick response, this is the LG 55UP75003LF

**Comment by tojeroman** [comment]
Hi @dennisoelkers 

Thanks for the quick response, this is the LG **55UP75003LF**

**Comment by dennisoelkers** [comment]
Thanks! What do you use on the TV for browsing?

**Comment by dennisoelkers** [comment]
And: Are you running the latest webOS-version for your model? Are there any updates for the browser available by any chance?

**Comment by dennisoelkers** [comment]
I guess you are right, I think we are too restrictive when it comes to the browser versions we are building for. Can you check which webOS-version you are using exactly? You find instruction on how to do this [here](https://webostv.developer.lge.com/develop/specifications/web-api-and-web-engine).

From then on, it is a matter of supporting more older browser versions in our build. Once we have done this, we can include the change in our next 5.0.x release and you should be good to go afterwards.

**Comment by tojeroman** [comment]
Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.79 Safari/537.36 SmartTV/10.0 Colt/2.0

**Comment by dennisoelkers** [comment]
@tojeroman: We are releasing `5.0.4` today, which should fix the issue you are seeing. It would be great to get some feedback from you if it resolves the issue for you!

**Comment by tojeroman** [comment]
@dennisoelkers Thanks a lot, I'm using the apt repository on ubuntu, I'll have to wait for version 5.0.4 to appear in the repository and upgrade. I'll be sure to let you know right away. Thank you

**Comment by tojeroman** [comment]
@dennisoelkers:
I updated to 5.0.4 today, unfortunately still the white screen. If I open the url address http://IP_ADRESA/dashboards/5d5090bd6fef2803601521b9, the graylog login page opens. Most likely, there will be a problem in rendering the page using javascript. I am looking for an alternative, such as sending a header via node-red to automatically log in or to display the dashboard without logging in. This might temporarily solve my not showing problem.
![image](https://user-images.githubusercontent.com/6218723/222366479-3a1ff468-a510-45da-8cbc-78b240dbdd5f.png)

**Comment by dennisoelkers** [comment]
Hey @tojeroman! Great to hear it is working again now. Thanks for all your help finding and fixing this.

Right now the dashboard cannot be displayed without being logged in, we do not want to expose any information without proper authentication. We have a feature request in our backlog for generating a URL that also includes authentication information, but this is currently not planned for the near future.
