### ISSUE TITLE
Could not delete lookup table data adapter

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#14679]
When attempting to delete an 'Active Directory User Lookup' data adapter, i receive the following error:

> Could not delete lookup table data adapter "62a7985ef323837077b252b1"
> 
> Deleting lookup table data adapter failed: The adapter is still in use, cannot delete.

![image](https://user-images.githubusercontent.com/107503402/219083088-456ee383-202f-4bd5-9692-8e204907a9a7.png)

This message is not accurate however, as there are no lookup tables that reference it. There is no further text in`server.log` and no indication given why this occurs.

## Expected Behavior

Data Adapters can be deleted.

## Current Behavior

Unable to delete 'Active Directory User Lookup' data adapter

## Steps to Reproduce (for bugs)
Unclear what conditions led up to this or how it could be reproduced

## Context

I run my VMs on a desktop and commonly shutdown some of the VMs when not in use to conserve power and energy. However, recently graylog (i think starting with 5.0.3) has started flooding `server.log` if it cannot reach the Domain Controller. See https://github.com/Graylog2/graylog2-server/issues/14660

This has previously never been a problem for the past 9 months or so. I'm attempting to remove any reference to this domain controller to troubleshoot CPU usage issues with graylog but got stuck on this one.

## Your Environment

* Graylog Version: 5.0.3
* Java Version: Bundled JDK
* Elasticsearch Version: OpenSearch 2.4.1
* MongoDB Version: 5.0.14
* Operating System: Ubuntu 20.04 LTS
* Browser version: Chrome 110.0.5481.77

**Comment by patrickmann** [comment]
@drewmiranda-gl I could not repro this error on current master (5.2); but the relevant code has not changed since 2017.
Prior to deleting an adapter we query the DB to see if there is any lookup table that references it (field `data_adapter`). I can only assume that your DB was in an inconsistent state. 
If you can repro it, please reactivate and share contents of your DB tables `lut_tables`, `lut_data_adapters`.
