### ISSUE TITLE
Reordering of extractors does not work in 5.0.3

### ISSUE THREAD

**Issue by H2Cyber** [Graylog2/graylog2-server#14693]
## Expected Behavior
Reordering of extractors should work (using the button `Sort extractors`).

## Current Behavior
Reordering of extractors does not work: the new chosen order is not applied. The following message appears in server.log :
```
2023-02-16T15:06:19.538+01:00 INFO  [ExtractorsResource] Updated extractor ordering of input <persist:redacted>.
2023-02-16T15:09:38.634+01:00 INFO  [ExtractorsResource] Updated extractor ordering of input <persist:redacted>.
```

## Steps to Reproduce

1. Select an input
2. Click on `Manage Extractors`
3. Click on `Sort extractors`
4. Make any change to the order of the extractors
5. Click save
6. Click on `Manage Extractors` on the same input, and notice how the new order is not applied

## Your Environment

* Graylog Version: 5.0.3 (upgraded recently from 4.3.17)

**Comment by H2Cyber** [comment]
Hey @boosty, let me know if there is any information which I can provide to confirm the bug.

**Comment by boosty** [comment]
@H2Cyber Thanks for the report! 

I will let the development team have a first look and hopefully reproduce it. They will surely ask for more information if needed.

**Comment by patrickmann** [comment]
@H2Cyber I am unable to reproduce the issue. The code is quite straightforward and hasn't been updated in a long time, so I am uncertain what is happening on your end. 
The log message you pasted indicates that the operation completed without exceptions. Are there any other log messages preceding that, which look relevant?
Are you able to validate that the order is updated as expected in MongoDB?
![image](https://user-images.githubusercontent.com/12073930/220079150-6f66ba71-9773-493e-ae97-9d29989e3f99.png)

**Comment by H2Cyber** [comment]
It seems there was a change in Extractor-related code not so long ago : https://github.com/Graylog2/graylog2-server/issues/13898

I'll try and check if reordering is updated as expected in MongoDB.

**Comment by H2Cyber** [comment]
Update: the issue is reproducible on other Graylog instances, just try to update sorting of any input with 10+ extractors. 

 
[Screencast from 02-21-2023 08:31:46 PM.webm](https://user-images.githubusercontent.com/764189/220441334-ec44f696-7f70-40b1-9a30-6d41c43cdbe9.webm)

**Comment by patrickmann** [comment]
Thanks for the additional details. I can also reproduce it now. My earlier comment about code not having changed was focused on the backend. This appears to be a pure frontend issue:
The API call `system/inputs/<input id>/extractors` returns the correct ordering, but the frontend ordering is not updated. Looks like the frontend store is out of sync. 
Stay tuned ...
