### ISSUE TITLE
HTTP Notification: support API key as header (in addition to query string)

### ISSUE THREAD

**Issue by patrickmann** [Graylog2/graylog2-server#14691]
## What?
HTTP Notification can be configured with an API key. This is transmitted in the query string (though we don't expicitly state this).
Users should be able to choose whether to send the API key in the request or in the header.

## Why?
Some APIs expect the key to be provided as a header (e.g. AWS). 
https://community.graylog.org/t/http-notification-api-key/27730

## Your Environment
GL 5.01

**Comment by dieguinsss** [comment]
Hi Patrick,
But It does not make sense that Graylog send api-keys as query parameter…
That is not secure…
