### ISSUE TITLE
New "Replace" Extractor needed

### ISSUE THREAD

**Issue by razvanphp** [Graylog2/graylog2-server#1469]
Hello,

Sometimes logs received by graylog have errors in them, and it's very hard, if not impossible, to fix them at the generation side.

For example, we have some messages in JSON format that contain `\xc3\xbc` characters in them, that is the UTF-8 hex representation of `ü`, and because of this, JSON Extractor fails.

I was multiple times in the situation when I wanted to replace something in all the messages of that input, without really extracting to a new attribute, for example when I have "null" as string in a numeric attribute, I want to replace it with 0, so I don't get this kind of ES error:

````
MapperParsingException[failed to parse [ctxt_deductibles_value]]; nested: NumberFormatException[For input string: "null"]; 
````
Is this a good idea for a new extractor?

Thank you!

**Comment by razvanphp** [comment]
Ok, I might found some clue about what happens here, the offending messages look like this:

````
{"host":"server4","message":"GET http://www.aboutyou.de/frauen/schuhe/stiefel/boots?sort=2 HTTP/1.1","level":6,"remote_addr":"123.456.789.100","request_time":"[13/Oct/2015:16:19:29 +0200]","request_domain":"www.aboutyou.de","request_path":"/frauen/schuhe/stiefel/boots?sort=2","request_verb":"GET","http_version":"HTTP/1.1","http_referer":"http://www.aboutyou.de/frauen/schuhe/stiefel/schnuerstiefel?gclid=COWB7ObRv8gCFQw6GwodLkAGoQ&C_ID=194972915&AdG_ID=19126798235&KW=damen%20schn\xc3\xbcrstiefel&ef_id=RwdOixNvkFIAAIl5:20151013141758:s&sort=2","response_bytes":65759,"response_status":200}
````

Note `\xc3\xbc` inside the message, that is the UTF-8 hex representation of `ü`, so probably the message cannot be extracted by the first graylog JSON extractor (I tried it manually) but the message is still sent to the output unmodified. There is still a mystery why this message is not stored in this first graylog.

Is there a way (extractor) to just replace characters in messages, z.B. decode them prior to JSON extractor?

**Comment by razvanphp** [comment]
@bernd any change we get this soon?

Is it faster to make the Numeric converter accept "null" as a string and convert it to 0 or a real null, so that ES does not throw this exception?

Anything is better than now, since the message is completely lost...

**Comment by bernd** [comment]
Sorry, I can't give you a date on this. You can put it into our feature portal to allow others to vote on this.

https://graylog.ideas.aha.io/

**Comment by bernd** [comment]
@razvanphp This will be in the upcomint 1.3: https://github.com/Graylog2/graylog2-server/pull/1485

Would this help?

**Comment by razvanphp** [comment]
Ahh, yes, great, you guys rock!
