### ISSUE TITLE
Redesign Graylog configuration page to have a sidebar menu.

### ISSUE THREAD

**Issue by ousmaneo** [Graylog2/graylog2-server#14735]
## What?

The current Graylog configuration page shows the configuration options on a single-page grid, forcing users to search for a configuration option.

We propose redesigning the Graylog configuration page with a sidebar menu navigation similar to the search page sidebar. 

This will allow showing a single config information and easy navigation between the configuration option.

Update:
After a discussion with @dennisoelkers  the suggestion is to turn the page into a more linear form with sections contributed by each component, but not as a grid, with separate boxes and individual edit buttons/forms (see user Edit form as an example).
It should be one big form where settings are editable in place. A sidebar would also be great to show the general structure of the page and be able to jump to individual sections.
We are fetching each configuration for each section on the backend side. Instead, we should bundle up the configuration keys and retrieve the complete configuration in one go.

**Comment by grotlue** [comment]
I had a look at the current situation and the suggestions mentioned in this and I think the best solution would be:

- Have a sidebar
  - so the user can easily see what they can configure
  - so the user can find the section/option they want to configure fast
- Show only the active section of the sidebar as a whole form so the user can edit the options directly (ne extra click needed)
- With this layout that there is no need for a new API request fetching all configuration data which would mean we would fetch a lot of data we don't need
- We can either save the available sections in the frontend and fetch data for each section or have one call just returning available configuration sections and another returning the form for each section

Please find more details on what advantages/disadvantages I discovered for each option as well as user scenarios for this page in this overview:
[canvas_configurations-page-230310_1135.pdf](https://github.com/Graylog2/graylog2-server/files/10941594/canvas_configurations-page-230310_1135.pdf)

What do you think @kroepke @dennisoelkers @ousmaneo?

What would be the advantages in having one big form?

**Comment by grotlue** [comment]
I had a first look and tried adding a sidebar. This is the result and what I would go with. There is a sidebar with entries for each section and for plugins, we can have a sub-sidebar with entries for each plugin.
On top of that, I'd remove the modal functionality, meaning instead of showing the configuration data and an edit button which opens a modal we show the configuration data as a form which can be edited right away.



https://user-images.githubusercontent.com/3169354/224938784-8307a74a-2f10-4d71-993b-8f400bccff55.mp4

**Comment by ousmaneo** [comment]
> 
> What would be the advantages in having one big form?

Hi @grotlue, My first thought was to have something similar to what you have in the screenshot above.
I don't have a strong opinion about this way or having a form-like display with navigation allowing access to a section of the page, but I think data loading wise it's always better to do fewer calls to the API than more.

**Comment by grotlue** [comment]
I will go and see how it looks like to have a form directly.

Regarding the API request, why is it better in this case?

In general, I agree with reducing the number of API requests as much as possible, but at the same time, I think it also needs to make sense. In this case, I see the different configurations as independent from each other. Meaning, the user might want to change e.g. the sidecar configuration several times, but never update the search configuration. In this case having one big form request will make it much harder to maintain - the API as well as in the frontend.

**Comment by ousmaneo** [comment]
> Regarding the API request, why is it better in this case?

The advantages would be making fewer requests to fetch configuration.
But in general, there needs to be more clarification on how this should work. The idea is not to have a single form managed as a single object. But something similar to the user edit page. A page with sections editable individually.
Maybe @dennisoelkers can explain what he meant better than I do.
