### ISSUE TITLE
Field autocomplete makes using the enter/return key to search difficult and cumbersome

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#14793]
## What?

When performing search in graylog using the search box, it is very convenient to use the enter/return key to execute the search. However, the same key also inserts suggested autocomplete values for field names and creates a frustrating user experience when you are trying to search for something but your text is replaced with the autocomplete value.

IMO enter/return should not be used to select an autocomplete value (i understand there seems to no true standardization on how autocomplete works with a keyboard, some implementations do use enter/return to select and use the autocomplete value, others use tab) because of the above described issue making it very difficult to quickly perform searches.

https://videos.graylog.com/watch/AefLudH6dvWHvCFjBbocbA?

## Why?

As noted above, trying text in the search box and then pressing enter/return to search causes unexpected behavior because of how field autocomplete works and because the autocomplete value is selected/inserted using the same key as you use to execute search.

## Your Environment

* Graylog Version: 5.0.3
* Operating System: Ubuntu 20.04 LTS
* Browser version: Chrome 110.0.5481.100

Let me know if there are any questions or you wish to discuss further.

**Comment by dx034** [comment]
Are there any plans to fix this in the foreseeable future? Since this behavior started, searching for custom values has become much more cumbersome.

**Comment by linuspahl** [comment]
Thank you for the feedback. I tried to describe the context for this behaviour and implement a fix for it in https://github.com/Graylog2/graylog2-server/pull/16162

The library we use for the query input (the ace editor) has no native support for adjusting the autocomplete keybindings. I had to implement a workaround, it was the only solution I found.
