### ISSUE TITLE
Reordering fields in the message table widget is buggy and difficult to use

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#14795]
Attempting to reorder fields in a message table widget, such as on the search page, is very difficult and buggy to where its difficult to get the sort the way you want it.

The only thing that helps is making the windows as large as possible so you have more room in the `fields` box to drag and reorder.

http://videos.graylog.com/watch/GH8MoyYq5CU7RCE2JnLCx7

## Expected Behavior

Changing field order should be clear and easy to do and should work as expected. Fields should't take an unexpected sort order that you didn't intend and fields shouldn't just around when trying to reorder them.

## Current Behavior

It is difficult (near impossible) to reliably reorder fields in an expected way. Fields may jump to the beginning of the field list unexpectedly and its difficult to correctly grab and drag the field.

## Possible Solution

?

## Steps to Reproduce (for bugs)

1. Edit a message table widget
2. Reorder fields

## Context

It is very common to add fields to a message table and want these fields to appear in specific order. Currently its much easier to just remove all the fields and then re-add them back in the intended order.

## Your Environment

* Graylog Version: 5.0.3
* Java Version: Bundled
* Elasticsearch Version: OpenSearch 2.4.1
* MongoDB Version: 5.0.14
* Operating System: Ubuntu 20.04 LTS
* Browser version: Chrome 110.0.5481.100

**Comment by dennisoelkers** [comment]
Hey @drewmiranda-gl! Thanks for reporting this. We have been aware of this for a while and are currently working on replacing the control to configure the fields and their order: https://github.com/Graylog2/graylog2-server/pull/14725 - you can expect this landing in 5.1.
