### ISSUE TITLE
Remove Max number of indices field for Index Time Size Optimizing strategy (UI)

### ISSUE THREAD

**Issue by AntonEbel** [Graylog2/graylog2-server#14845]
We should remove the "Maximum number of indices" field in the user interface when using the "Index Time Size Optimizing" strategy. There are at least two pages where we need to change this. The list view of the indices 

![image](https://user-images.githubusercontent.com/25727579/222453535-eee4e607-dff0-4242-9df9-525ab7cb8017.png)

and the detail view of the index set.

![image](https://user-images.githubusercontent.com/25727579/222453036-baa4555f-cd24-4ea1-950c-d38caa957977.png)

* Graylog Version: 5.1.0-SNAPSHOT

**Comment by tellistone** [comment]
upvoting this, its both confusing and alarming!
