### ISSUE TITLE
Plugin with (complex) configuration modals loads additional chunks from incorrect path 

### ISSUE THREAD

**Issue by jrunu** [Graylog2/graylog2-server#14852]
## Expected Behavior / Current Behavior

Building a custom plugin for Graylog 5.x produces incorrect loading paths in JavaScript files for the web interface, causing loading chunk failed errors and non-functioning modals. It should produce a functioning build, like it does with 4.3.x builds.

## Details

Since only auto-generated files are involved the files names change on each build run. The file names involved are generated by `graylog2-server/graylog2-web-interface/webpack/UniqueChunkIdPlugin.js` and start with 4 hexadecimal encoded bytes followed by a minus sign and a numeric id.  This makes them somewhat distinctive from the rest:

Excerpt from a build process.
```
[INFO] WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
[INFO] This can impact web performance.
[INFO] Assets: 
[INFO]   3b8b51248b6aa0474a02a6c352d1caa1.js (488 KiB)
[INFO]   b76ff0f203825dcdefb649d98de32f5b.js (493 KiB)
[INFO]   52c9726f9e52ed3a57c0634718366029.js (313 KiB)
[INFO]   6aa13e92b5cf7d479e73acdc7c05abf3.js (499 KiB)
[INFO]   8efee5c45bbfdd52eec7a8a0eec72ec3.js (1.52 MiB)
[INFO]   plugin.de.netuse.graylog.context_collector.NetusePlugin.dbf03304193170546870.js (1.84 MiB)
[INFO]   86b13953-379.b368bd0c68ce6e80d812.js (583 KiB)
[INFO]   86b13953-168.62fb46bad8aff5091ad3.js (1.1 MiB)
[INFO] 
[INFO] WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
[INFO] Entrypoints:
[INFO]   plugin.de.netuse.graylog.context_collector.NetusePlugin (1.84 MiB)
[INFO]       plugin.de.netuse.graylog.context_collector.NetusePlugin.dbf03304193170546870.js
[INFO] 
[INFO] app (webpack 5.74.0) compiled with 2 warnings in 67004 ms
```

The resulting jar file then was loaded into a Graylog. Opening the System->Configuration and then opening the Plugins going thru the different configurations until the affected modal is reached, causes the web interface to load:

`http://graylog:9000/assets/86b13953-168.62fb46bad8aff5091ad3.js`

This returns a 404 error, which subsequently breaks the modal. The correct path to load from is

`http://graylog:9000/assets/plugin/de.netuse.graylog.context_collector.NetusePlugin/86b13953-168.62fb46bad8aff5091ad3.js`

## More Context
I'm not positive that this is a regression per se. On 4.x builds the web interface does not load anything beyond the entrypoint `plugin.de.netuse.graylog.context_collector.NetusePlugin.*.js` because everything it needs seems to fit in it. On 4.x and 5.x all public available plugins seem to have simple enough configuration modals, so they don't load any "UniqueChunkID" files either.

The only plugins which does load additional files this way, is the enterprise plugin. I happen to not have access to its source at this time, so I can't tell if its configuration differs with regard to webpack and the like. Our plugin matches the configuration described in `graylog2-web-interface/packages/graylog-web-plugin/README.md` 

## Your Environment

* Graylog Version: 5.0.2
* Java Version: 1.17

**Comment by dennisoelkers** [comment]
Hey @Jrunu!

Thanks for reporting this! Quick question: do you have a module in your plugin which is setting up the load path for webpack?

You can see how it is wired up in the integrations plugin. In its major entrypoint, we are importing a module named `webpack-entry`:
https://github.com/Graylog2/graylog-plugin-integrations/blob/master/src/web/index.jsx#L17

`webpack-entry` looks like this:
https://github.com/Graylog2/graylog-plugin-integrations/blob/master/src/web/webpack-entry.js

What this is doing, is setting up the path prefix for all chunks which are loaded dynamically afterwards.

Does this help you?

**Comment by jrunu** [comment]
Hey @dennisoelkers,

no, I hadn't had it set up that way. Much like the aws and threatintel plugin I used `import webpackEntry from 'webpack-entry';` But I have now, and it now loads the chunks correctly, so thank you very much.
