### ISSUE TITLE
Add `AmbientCapabilities=CAP_NET_BIND_SERVICE` to `graylog-server.service` to allow binding to port <1024

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#14867]
## What?

Add configuration to Graylog's service file that allows the Graylog-Server processes to bind to ports below 1024.

Adding

```
AmbientCapabilities=CAP_NET_BIND_SERVICE
```

to `/usr/lib/systemd/system/graylog-server.service` (validated and tested on Ubuntu Server) resolves these issues perfectly.

## Why?

Graylog-Server has 2 primary legitimate reasons for needing or wanting to do this:

1. use a standard web server port such as TCP 80 (HTTP) or TCP 443 (HTTPS)
2. create a syslog input on its default port of 514

Currently Graylog-Server cannot do this without some modifications.

## Your Environment

* Graylog Version: 5.0.5
* Elasticsearch Version: OpenSearch 2.4.1
* MongoDB Version: 5.0.14
* Operating System: Ubuntu Server 20.04 LTS
* Browser version: Chrome 110.0.5481.177

**Comment by drewmiranda-gl** [comment]
I wish i could take credit for this but found this via https://graylogdocumentation.atlassian.net/wiki/spaces/PS/pages/2459369479/SSL.SH+deprecated

**Comment by bernd** [comment]
Done in https://github.com/Graylog2/fpm-recipes/pull/130.
