### ISSUE TITLE
Grok extractor: Allow returning only named captures

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#1486]
The Grok extractor currently returns all matches for a grok pattern, e. g. also alternatives for the chosen pattern.
![Graylog 1.2.x Grok extractor](https://cloud.githubusercontent.com/assets/43951/10482477/b2f94a96-7278-11e5-864e-454e742f7c90.png)

It should be possible to only return named captures with the Grok extractor, similar to the [Logstash Grok filter](https://www.elastic.co/guide/en/logstash/1.5/plugins-filters-grok.html#plugins-filters-grok-named_captures_only) and the [Grok Debugger](https://grokdebug.herokuapp.com/).
![Grok Debugger](https://cloud.githubusercontent.com/assets/43951/10481335/42a84966-7270-11e5-97fc-cf4450c4f3ba.png)

**Comment by runningman84** [comment]
please include this feature in 1.3 this seems to be a quite small change...

**Comment by joschi** [comment]
@runningman84 This won't make it into Graylog 1.3.x.

**Comment by fractal76** [comment]
This seems to be a pretty major shortcoming!? Any plans to include this in upcoming releases?

**Comment by manishjhawar** [comment]
+1 Any plans for 2.0?

**Comment by unicorn42** [comment]
:+1: :100: please add this feature, i would really appreciate that!

**Comment by mightydok** [comment]
+1 for this issue

**Comment by runningman84** [comment]
@kroepke can you add this to 2.1?

**Comment by kroepke** [comment]
@runningman84 That greatly depends whether the grok library we use actually supports the "named captures only" feature. Otherwise we can't differentiate the matches.
We'll investigate.

**Comment by w4-sglim** [comment]
+1

**Comment by bernd** [comment]
This will be in the upcoming Graylog 2.1. See #2500 for details.
