### ISSUE TITLE
no such index [.opendistro-anomaly-detectors] 

### ISSUE THREAD

**Issue by edward-marrufo-graylog** [Graylog2/graylog2-server#14917]
When using Graylog I expect it to work without throwing errors.
## Expected Behavior

When using Docker compose we are hoping to see no errors within the Graylog server log.
## Current Behavior

Currently when using Docker compose we are seeing the following error:
`no such index [.opendistro-anomaly-detectors] `

## Possible Solution

I have seen this error in the past when installing Graylog via OS package managers such as rpm and deb.

On HS 1300914789 we got rid of a similar error by inserting the following:

```
 action.auto_create_index: .watches, .triggered_watches, .watcher-history-*, security-auditlog-*

plugins.security.audit.type: internal_opensearch 
```

## Steps to Reproduce (for bugs)

Currently it is unclear what exact steps were taken, however it was upon the upgrade from Graylog 4.3.2 to Graylog 5.x definitely. 

## Context

We have some concerns the Graylog instance will be affected performance wise. Of note is that we did try to change some of the environment variables within the docker compose file. Specifically we tried to introduce the following:

```
- "action.auto_create_index=.opendistro-anomaly-detectors, .watches, .triggered_watches, .watcher-history-*, security-auditlog-*"
- "action.auto_create_index=false"

```
Regarding the above, we did not perform them at the same time since they are at odds with each other. We performed each step individually.

We have also attempted to upgrade the customer to different versions where I did not receive the error and customer still continued to receive the error.

For additional context please see HS 1423260805

* Graylog Version: 4.3.2
* Opensearch Version: 1.3.7
* MongoDB Version: 5
* Operating System: Ubuntu 18.04

**Comment by moesterheld** [comment]
@ryan-carroll-graylog 
Hey Ryan, this is the issue we just talked about. `anomalyPluginInstalled()` should return false or it should be ensured that the index actually does get created on install.
Thanks, Matthias

**Comment by kroepke** [comment]
Let's backport this to 4.3/5.0 as well, please.

**Comment by ryan-carroll-graylog** [comment]
> Let's backport this to 4.3/5.0 as well, please.

Will do!
