### ISSUE TITLE
Sidecar administration pagination broken if collector selected

### ISSUE THREAD

**Issue by moesterheld** [Graylog2/graylog2-server#14924]
On the sidecar administration page, selecting a collector and then using a pagination link in the page in the list leads to an error:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/33032967/224920938-9d08b4ba-b07a-405b-9332-aeee8b5b39e8.png">

## Expected Behavior
Pagination should work as expected

## Steps to Reproduce (for bugs)
1. Open sidecar administration page with more than one page of sidecars
2. Check a collector in at least one of the sidecars
3. Click pagination link of list
4. Error is displayed

* Graylog Version: 5.0.x

References HS-1494095433

**Comment by damianharouff** [comment]
@moesterheld will this be backported into 5.x releases?
