### ISSUE TITLE
Alerts & Events sub navigation performs wrong permission checks

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#14940]
## Expected Behavior
Non-admin users should be able to see the Event Definition and Notification pages under Alerts & Events.

## Current Behavior
Even if a user has one of the roles "Event Definition Creator" or "Event Notification Creator" they cannot see the respective pages.

## Possible Solution
Remove the permission checks from the navigation elements on that page. The individual pages will perform permission checks for shared items already, and the "create" buttons are gated by the aforementioned roles, so no explicit permission check should be necessary.

## Steps to Reproduce (for bugs)
1. Create a reader user.
2. Assign "Event Definition Creator" and "Event Notification Creator" roles to the user.
3. Log in as that user and navigate to "Alerts & Events"
4. The event definition and notification pages are not visible despite having permissions to create new entities.

## Context
https://community.graylog.org/t/user-cant-see-event-definitions-and-notifications-section-when-role-alerts-manager-isnt-assigned/28103

https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/components/events/EventsPageNavigation.tsx#L25-L26

## Your Environment

* Graylog Version: 5.0 (possible earlier, too)

**Comment by linuspahl** [comment]
Had a quick look at the implementation. In `5.0` we have this permissions check for the sub navigation on every related page, in `4.3` we have it on the `EditEventNotificationPage`, `CreateEventNotificationPage`, but not on the `EventDefinitionsPage`, `EventNotifications` and `EventsPage`.
