### ISSUE TITLE
Automatically configure and start certain inputs on first install

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#1496]
Users often struggle with getting data into Graylog when they first start using the product.

To help these setups to get successful quicker, we want to add the option of automatically starting common input types with default configuration during the first setup.

- [ ] Identify input types to start

**Comment by kroepke** [comment]
Discuss whether to do this for non-appliance versions.

**Comment by joschi** [comment]
In my opinion this is only useful for the virtual machine and Docker images. People using other installation methods (OS packages, manual install) usually want to customize their setups anyway and can use the content pack loader to do so.

**Comment by kroepke** [comment]
not doing so for the non-appliance builds
