### ISSUE TITLE
Implement first start detection

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#1497]
To support welcome splash pages and taking actions only on a first deployment of a Graylog system we need to be able to detect that a system is new.

Additionally we want to register actions that should run at that point, so that a user can rerun them if needed:
- [x] Add database support for first start actions and detection
- [x] Decide on format for first start action serialization
- [x] Expose REST endpoints for UI implementation of first start splash page

**Comment by joschi** [comment]
>  Add database support for first start actions and detection

This can simply be done with the existing `ClusterConfigService`. On first start we either create an explicit configuration or we check if `ClusterId` exists (it's being generated on the first start of the first node of a cluster).
