### ISSUE TITLE
Improved Graphite metrics

### ISSUE THREAD

**Issue by jaxxstorm** [Graylog2/graylog2-server#150]
The graphite metrics are great for the stream counts and messages counts, but they don't really provide anything over the graphs inside graylog other than a longer time period.

It would be great it we could tailor make graphs some how. Some examples might be:

Create a graph of all Err. level logs and then break down based on a field (such as hostname)
Pie chart of messages per field (hostname again, for example)

Essentially, some control over the graphite metrics from mongodb would be a fantastic addition.

**Comment by DanyC97** [comment]
+1

**Comment by florianvolle** [comment]
Closing this as this issue should be solved by either https://github.com/Graylog2/graylog-plugin-metrics https://github.com/Graylog2/graylog-plugin-metrics-reporter

Thanks!
