### ISSUE TITLE
Request to host authbind rpm on graylog repository

### ISSUE THREAD

**Issue by tjyang** [Graylog2/graylog2-server#1506]
Hi 
I am a new comer. From reading the online thread looks like autbind is almost a  must-have rpm for running graylog2 on RPM based OS.  Why not include it in graylog repo ?

References:
1. https://packages.graylog2.org/el/7/1.2/x86_64
2. https://groups.google.com/forum/#!searchin/graylog2/authbind/graylog2/L-Zag1e0ob4/Izn1reGIAMgJ

**Comment by joschi** [comment]
Using `authbind` is *one* way to allow non-privileged processes to bind privileged ports but it's not the only one and it's not the only way to for example ingest syslog messages on the well-known ports (514/udp, 514/tcp).

At this point we don't want to impose the burden of maintaining an `authbind` package on us.
