### ISSUE TITLE
Index not found for query while using Graylog REST Api

### ISSUE THREAD

**Issue by Marco-Zheng** [Graylog2/graylog2-server#15102]
I just send below restful api  request to graylog server
curl --location --request GET 'http://10.16.78.65:9000/api/search/universal/relative?query=request_id:cffb3de2-c368-4470-a29f-ed150be20b23' \
--header 'Authorization: xxxxxxxxx'

## Expected Behavior

Get expect message as below
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/52538259/228785559-d6d65637-c8ab-4644-8541-2419129610fa.png">

## Current Behavior

Get reponse as below 
```
{
    "type": "DetailedError",
    "message": "Unable to perform search query[flightintl-booking_117]\n\nIndex not found for query: flightintl-booking_117. Try recalculating your index ranges.",
    "details": [
        "Index not found for query: flightintl-booking_117. Try recalculating your index ranges."
    ]
}
```

## Your Environment

* Graylog Version: 4.2
* Java Version: 1.8

**Comment by dennisoelkers** [comment]
Hey @Marco-Zheng,

thanks for reporting this. Did you try recalculating your index ranges for the index set that the index `flightintl-booking_117` belongs to?

**Comment by Marco-Zheng** [comment]
@dennisoelkers 
Thanks for your quickly reply, actually we don't have index of flightintl-booking_117, below is all relative index for flightintl-booking
![image](https://user-images.githubusercontent.com/52538259/229006031-c14d3ef1-9e0c-401d-88f8-2812ea79a30d.png)
I have tried to add "range" value "50" and got the different error like this 
![image](https://user-images.githubusercontent.com/52538259/229006374-299cb912-4270-4059-956b-3bb0e8461db8.png)
It show that Index not found for query: job-center_109, here is all job-center index
![image](https://user-images.githubusercontent.com/52538259/229006482-0ab1c353-0800-453f-95aa-b6bafaa908c8.png)
I confused why a non-existent index will be searched.

**Comment by dennisoelkers** [comment]
Hey @Marco-Zheng,

it is surprising that it is trying to use a non-existent index. Usually it happens when there is still an index range for an index which has been removed. My suggestion is to try triggering a recalculation of index ranges for the affected index sets. It would be interesting to see if it works afterwards.

On a side note: You are running Graylog 4.2, which is rather outdated. Is there a reason why you are not updating to 5.0?
