### ISSUE TITLE
Index ranges can get out of sync when manually deleting ES indices

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1511]
When the Graylog server is not running and an index gets deleted from Elasticsearch, the index ranges get out of sync. Even manually recalculating index ranges does not remove the stale entries from MongoDB.

This can break searches when Graylog thinks an index exists but in reality it does not. As of 1.2.2, there is no way to fix this besides manually deleting the stale documents from MongoDB.

**Comment by joschi** [comment]
Fixed in 9fa2f0c1ad6893b84267b39554bc99c8daf888fe.
