### ISSUE TITLE
Updating LDAP settings deletes group mappings

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1513]
If a user updates the LDAP settings, all group mappings are gone.

This is probably because the LDAP settings page does not include anything about the group mappings and thus the mappings are overwritten when the new LDAP settings are saved.

**Comment by aanriot** [comment]
Thanks Bernd.

**Comment by joschi** [comment]
Fixed in Graylog2/graylog2-web-interface@fe5dbc4f3d89384458214d0dcf7074323718e6b6.
