### ISSUE TITLE
Decorated fields have an incorrect name in the fields section when editing a table

### ISSUE THREAD

**Issue by artiomello** [Graylog2/graylog2-server#15164]
When decorating a couple of strings and adding it as a table column - that new field's name is somehow corrupted in the table editor.
I have two IDs that I want to combine into a decorated field, like so:
![image](https://user-images.githubusercontent.com/102314521/230389935-0e69516d-8012-4bf0-ab8c-c4c80a177347.png)

In the table itself the new column (`ID`) is displayed properly:
![image](https://user-images.githubusercontent.com/102314521/230390158-7bd40e5f-9bc1-4027-89a0-413a71fa6a35.png)

But when I edit the table and want to, say, rearrange the fields - that particular decorated field looks like this:
![image](https://user-images.githubusercontent.com/102314521/230390476-555d6404-ecd5-40f7-aef3-240b8ea5a234.png)

This happens for both existing decorations and for newly created ones.

## Expected Behavior

Decorated fields should have the same name you assign to them. In my example - `ID`.

## Current Behavior

Currently, decorated fields have a confusing random composite name that consists of existing field names along with the one you actually created, mingled up somewhere inside:
![image](https://user-images.githubusercontent.com/102314521/230391730-0d4a4142-b0f0-4396-ac3f-8fa51d97ebdb.png)

## Possible Solution

Decorated fields should have the same name you assign to them. In my example - `ID`. In case that's not possible, decorated fields can have a prefix/suffix such as `dec_ID` or `ID_dec` or something similar.

## Steps to Reproduce (for bugs)

1. Set up a table with some data
2. Create a decorated field
3. Look at its name in the `fields` section when editing a table

## Context

Obviously this is very confusing and unproductive.

## Your Environment

* Graylog Version: 5.0.5+d61a926
* Java Version:
* Elasticsearch Version:
* MongoDB Version: 5.0.+
* Operating System: Ubuntu 22.04 LTS
* Browser version: Latest MS Edge

**Comment by linuspahl** [comment]
We changed the layout for the field configuration at some point, it looks like this fixed the issue.

![image](https://github.com/Graylog2/graylog2-server/assets/46300478/06864643-5681-46eb-8971-a615ac601b0a)
