### ISSUE TITLE
Deleting rule does not remove rule until page change

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/graylog2-server#15172]
Observed in 5.0.6: when deleting a pipeline rule from Pipelines -> Manage Rules, the rule doesn't remove from the list until something causes a page update, e.g. trying to delete the rule again, or reloading the page.

Short video: [https://link.cekkent.net/863d94f4-b7e5-42e3-a176-877f43ac3f8c](https://link.cekkent.net/863d94f4-b7e5-42e3-a176-877f43ac3f8c)

## Steps to Reproduce (for bugs)

1. Go to Pipelines -> Manage Rules
2. Delete a rule
3. Confirm the "do you really want to delete this rule" pop-up box
4. Nothing appears to happen
5. Trying to delete the rule again causes a red banner at the bottom that the rule can't be found, then the rule disappears from the list.  Or, reloading the page also shows that the rule has been deleted. 

## Your Environment

* Graylog Version: Graylog 5.0.6+51f2df8 (Eclipse Adoptium 17.0.6 on Linux 5.10.0-21-amd64)
* Java Version: embedded
* Elasticsearch Version: 2.6
* MongoDB Version: 6.0
* Operating System: Debian 11
* Browser version: Version 111.0.5563.146 (Official Build) (arm64)

**Comment by damianharouff** [comment]
Not noted in Graylog 5.1.0-SNAPSHOT+5be589f  (Eclipse Adoptium 17.0.6 on Linux 5.10.165-143.735.amzn2.x86_64)

**Comment by gally47** [comment]
Tested it, it is already fixed so I will close it.
