### ISSUE TITLE
Primary ldap group of user not correctly recognized

### ISSUE THREAD

**Issue by renedj** [Graylog2/graylog2-server#1519]
With graylog 1.2.2 ldap groups are recognized correctly via the memberuid attribute, thx for that.
However the primary group of the ldap user (gidnumber) is not correctly recognized as group of the logged in user.
Through this ldap group mapping of users can't be used as we would like to.

**Comment by kroepke** [comment]
Currently we only support group mapping via searching for them.

**Comment by bernd** [comment]
This should be fixed with the latest 4.0 release.
