### ISSUE TITLE
Provide a script to rename ElasticSearch indices

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#152]
Renaming indices is not possible with ElasticSearch. We should have a script that scans (actually using a scan query) all messages of an index and writes them to a new one.

This is useful in cases where the deflector alias has gone mad and we need to make a proper production index out of it to not lose messages.

**Comment by bernd** [comment]
Is this still an issue with Graylog 1.0.0? Please re-open if so. Thank you!
