### ISSUE TITLE
Feature Request: Extractor tag support

### ISSUE THREAD

**Issue by clausa** [Graylog2/graylog2-server#1523]
Hi,

To optimize searching it would be nice to be able to add a 'tag' to each message according to their extractor. 

Typically you have a number of different extractors on any given input. For instance the PANOS content pack currently comes with 5 extractors (Grok Pattern) related to Palo Alto devices. Add to that a number of Cisco ASA related extractors, Unix and Microsoft services, and so forth.

If I want to search for all Palo Alto related messages, having a tag called 'panos' added according to the extractors would be really helpful. Likewise for ssh, sudo, cron, puppet, Cisco ASA, AD related messages.

So the extractor configuration should allow you to specify an 'extractor tag' that will be added to any message matched and handled by that extractor.

/Claus

**Comment by henrikjohansen** [comment]
@clausa We currently use the "Add static field" option on our inputs for this - we basically route different types of logs (PANOS, ASA, etc) to different inputs where the messages get tagged accordingly ... this in turn makes sure our extractors run efficiently since we only need to match a simple string and not a complex regex.

**Comment by clausa** [comment]
What I'm imagining is actually a more fine grained tagging mechanism, so we can tag (enrich) individual logs. 

Being able to tag all logs related to some kind of successful authentication with "authentication","successful" - even though neither of the two words exist in the log message - would allow for even stronger correlations. 

Example: ```Accepted password for <user> from <src_ip> port <src_port> ssh2``` would be a candidate for the tags "authentication" and "successful". 

Likewise ```FAILED SU (to <target_user>) <login> on pts/0```, would qualify for "authentication" and "failure" tags.

**Comment by rfdrake** [comment]
What I do right now is something like this in a grok pattern:

    (?<authentication_successful>Accepted password) for %{WORD:user} ...

This creates a tag of authentication_successful with a value of "Accepted password" so you can then search for messages logged with _exists_:authentication_successful

It's not ideal.  Some data has nearly 100% dynamic content so you might only have words like "of" or "from" to key off.  But, short of rewriting the parser in drools or using pipelines to add a field, I figured this was the only way to accomplish this.

**Comment by florianvolle** [comment]
Since Graylog 2.1 this can be solved using pipelines. http://docs.graylog.org/en/2.1/pages/pipelines/pipelines.html?
