### ISSUE TITLE
Deleting input does not always release port

### ISSUE THREAD

**Issue by eoinmullan** [Graylog2/graylog2-server#1524]
Running graylog from docker container
```
➜  ~  docker inspect graylog2/allinone
   "Id": "cb3f1e6ca08a36c61784f186b52c651bef915eb80fe2ebf503f718f0d0dffb2f",
   "Created": "2015-10-27T10:34:46.488406555Z"
```
Command to run the container
```
docker run -t -p 9000:9000 -p 12201:12201 graylog2/allinone
```
Now if I continuously add and remove an input on the same port it will eventually fail to start with the message "Error starting this input: Address already in use".

![image](https://cloud.githubusercontent.com/assets/5641649/10879135/127447ac-814a-11e5-8aba-6500f3b592ad.png)

Sometimes this happens the second time I try to start the input, sometimes it can take 5+ times. It seems to be more likely to happen if I switch between different types of input e.g. GELF TCP, then GELF UDP, but i don't have much data to support this.

**Comment by kroepke** [comment]
Does this happen only when quickly deleting/starting inputs?
