### ISSUE TITLE
GELF TCP is not working

### ISSUE THREAD

**Issue by colttt** [Graylog2/graylog2-server#1525]
Hello, 
i try the following example from here: https://www.graylog.org/resources/gelf/
```
colttt@graylog ~ # echo '{"version": "1.1","host":"example.org","short_message":"A short message that helps you identify what is going on","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}' | nc -w 1 syslog.example.de 12200
```
that is working correctly with i got a message and i can see the message, if i do the same with TCP

```
colttt@graylog ~ # echo '{"version": "1.1","host":"example.org","short_message":"A short message that helps you identify what is going on","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}' | nc -w 1 syslog.example.de 12200
```
i dont see a message (and yes i create a GELF TCP with the correct port)

the metrics show following from GELF TCP:

 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.incomingMessages
Meter
Total:
0 events
Mean:
0 events/sec
1 minute avg:
0 events/sec
5 minute avg:
0 events/sec
15 minute avg:
0 events/sec
 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.open_connections
Gauge
Value:
1
 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.org.graylog2.inputs.transports.TcpTransport.worker.executor-service.completed
Meter
Total:
0 events
Mean:
0 events/sec
1 minute avg:
0 events/sec
5 minute avg:
0 events/sec
15 minute avg:
0 events/sec
 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.org.graylog2.inputs.transports.TcpTransport.worker.executor-service.duration
Timer
95th percentile:
0μs
98th percentile:
0μs
99th percentile:
0μs
Standard deviation:
0μs
Mean:
0μs
Minimum:
0μs
Maximum:
0μs
 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.org.graylog2.inputs.transports.TcpTransport.worker.executor-service.running
Counter
Value:
8
 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.org.graylog2.inputs.transports.TcpTransport.worker.executor-service.submitted
Meter
Total:
8 events
Mean:
0.57 events/sec
1 minute avg:
1.47 events/sec
5 minute avg:
1.57 events/sec
15 minute avg:
1.57 events/sec
 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.rawSize
Meter
Total:
0 events
Mean:
0 events/sec
1 minute avg:
0 events/sec
5 minute avg:
0 events/sec
15 minute avg:
0 events/sec
 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.read_bytes_1sec
Gauge
Value:
0
 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.read_bytes_total
Gauge
Value:
14,532
 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.total_connections
Gauge
Value:
5
 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.written_bytes_1sec
Gauge
Value:
0
 org.graylog2.inputs.gelf.tcp.GELFTCPInput.563746fee4b074c2a0d05c70.written_bytes_total
Gauge
Value:
0

a RAW-Input as attachment, that means the messages arrives graylog.
![image](https://cloud.githubusercontent.com/assets/10084871/10882115/5fbd3294-8168-11e5-9970-2c2c52961763.png)

**Comment by joschi** [comment]
@colttt I don't see a difference between the first and the second command you've posted.

**Comment by colttt** [comment]
@joschi: damn, you right..
the first command that works is
```colttt@graylog ~ # echo '{"version": "1.1","host":"example.org","short_message":"A short message that helps you identify what is going on","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}' | nc -w 1 -u syslog.example.de 12200 ```

**Comment by joschi** [comment]
@colttt GELF via TCP requires messages to be terminated by a null character (`\0`). I agree that this is badly (or rather not at all) documented and we'll fix that.

Example:
```
# echo -e "{\"version\": \"1.1\",\"host\":\"example.org\",\"short_message\":\"A short message that helps you identify what is going on\",\"level\":1}\0" | nc 127.0.0.1 12201
```
