### ISSUE TITLE
User with only dashboard:read permission has access to dashboard delete button

### ISSUE THREAD

**Issue by ousmaneo** [Graylog2/graylog2-server#15261]
When a dashboard is shared with a user as a viewer, they can see and click the shared dashboard delete button.
Confirming the deletion show the error below:
 `Deleting view [dashboard-2] failed with status: FetchError: There was an error fetching a resource: . Additional information: Unable to delete dashboard <643e4f6a21a9c031ea50799e>.`

## Steps to Reproduce (for bugs)

1. Create a dashboard as a user (user1) with admin role
2. Share the dashboard with another user (user2)
3. log in as user2 and try to delete the dashboard

**Comment by janheise** [comment]
@ousmaneo do you remember which roles etc. user2 has so this problem occured?

**Comment by ousmaneo** [comment]
Hi @janheise, I updated the issue because confirming the deletion is not successful, with the request returning the error I added in the description. user2 had the `Reader` role

**Comment by janheise** [comment]
thx!
