### ISSUE TITLE
Expanding message via message table causes the widget to jump all the way to the top of its scroll position

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#15278]
When using a message table widget, expanding/collapsing a message causing the scroll position of the widget to jump all the way to the top/beginning.

http://videos.graylog.com/watch/fVvdAgwnRp4LLLm7Y4p29w?

## Expected Behavior

Scroll position of message table widget is not changed when expanding/collapsing a message.

## Current Behavior

Scroll position of message table widget jumps to top when expanding/collapsing a message.

## Steps to Reproduce (for bugs)

1. https://demo.graylog.cloud/search
2. Scroll down a bit in the message table
3. Expand a message

## Your Environment

* Graylog Version: Graylog Cloud 5.1.0 (373)
* Browser version: Google Chrome Version 112.0.5615.121 (Official Build) (arm64)

Please let me know if there are any questions or if there is any additional testing or information i can help provide.

**Comment by dennisoelkers** [comment]
Hey @drewmiranda-gl,

`demo.graylog.cloud` is running on an outdated version and I cannot reproduce this on more recent deployments (neither on 5.0). Can you try to reproduce this on a cloud setup with the most recent build?

**Comment by drewmiranda-gl** [comment]
> Hey @drewmiranda-gl,
> 
> `demo.graylog.cloud` is running on an outdated version and I cannot reproduce this on more recent deployments (neither on 5.0). Can you try to reproduce this on a cloud setup with the most recent build?

I don't, but i understand demo.graylog.cloud is being updated to 5.1 beta 1 end of week? I can test again after that. I agree though, i'm pretty certain this is related to other bugs/issues we've already reported and likely no longer an issue.

**Comment by drewmiranda-gl** [comment]
I believe this has been corrected.
