### ISSUE TITLE
Not possible to get an exact match when searching an analyzed field such as 'message'

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#15292]
When searching an analyzed field, such as `message`, the search result will return results where the search term is contained in, even when using double quotes (`"`) or a regex query.

To clarify "analyzed" field:

```json
"message": {
    "type": "text",
    "analyzer": "standard"
}
```

For example, you have 2 messages in graylog. The message field for each is as follows:

```
message: `key: value`
message: `key:`
```

When attempting to match only `key:`, both of the messages are returned.

Attempts to query this as an exact string:

```
message:"key:"
```

```
message:/key:/
```

Other fields do return expected results. A cursory internet search for "elasticsearch analyzed field exact match" returns similar questions from other who have had this same issue. Some of the suggestions involve either modifying the lucene query executed against elasticsearch/opensearch, OR changing how the field is indexed/analyzed.

## Expected Behavior

It is possible to search any field for an exact match.

## Current Behavior

Its not possible to search analyzed fields and search for an exact match.

## Steps to Reproduce (for bugs)

1. https://demo.graylog.cloud/search?q=source%3Agraylog%5C-ubu+AND+message%3A%22key%3A%22&rangetype=relative&relative=0
    * `source:graylog\-ubu AND message:"key:"`

## Context

In some cases (although not best practice), the data you need to search and filter on only exists in the 'message' field.

## Your Environment

* Graylog Version: 5.0.6
* Java Version: Bundled JDK
* ~~Elasticsearch~~ OpenSearch Version: 2.6.0
* MongoDB Version: 6.0.5
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 112.0.5615.121 (Official Build) (arm64)

**Comment by luk-kaminski** [comment]
@drewmiranda-gl @bernd @dennisoelkers 
I do not agree that it is a bug. The contents of the field of type `text` are tokenized and stored as a separate terms in inverted index. You do not have a way to query for exact match.

You can check how text is tokenized with a proper query:
![image](https://github.com/Graylog2/graylog2-server/assets/100699120/59b3b377-1ce8-42a2-9007-550920a2b0f3)

You can notice that with standard analyzer even `:` char is completely thrown away and does not appear in any token! And it is intended to be like that.

The only idea I have would be to index message twice, as both `text` and `keyword` (i.e. with multi-fields: https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-fields.html). It would significantly increase disk usage however, and would still require clients' awareness that `message` and `message.raw` are different variants of different type, and conscious decision to pick proper field when quering, depending on the need.
(Not to mention `ignore_above` problems we may need to consider as well for long messages...)

So, personally, I'd vote for "Won't Do" resolution of this ticket.

**Comment by drewmiranda-gl** [comment]
Understood. This likely came from a community question or similar. I do agree it is working as designed as intended so not sure why i used the bug label.

IMO the "graylog way" is to parse out anything you need to query exact matches on into its own field.
