### ISSUE TITLE
User permissions not updated on GET /roles/{rolename}/members

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1529]
Hello,

Graylog 1.2.2. Steps to reproduce it:

- Add a new dashboard.
- Create a new role which allow read access

On API, call 

PUT http://xxxxxxx/roles/{role}/members/{someone}

Now call users member list

GET http://xxxxxxx/roles/{role}/members

=> someone is on the list, but he doesn't have the 

"dashboards:read:55f9ea31e4b0ed002512d90f"

In its permissions array

Now call GET http://xxxxxxx/users/{someone}

=> permission

"dashboards:read:55f9ea31e4b0ed002512d90f"

is available on its permission array.

**Comment by bernd** [comment]
Thank you for the report! This will be fixed in the next Graylog version.

**Comment by bernd** [comment]
This will be in Graylog 1.2.3.
