### ISSUE TITLE
Graylog should log which packaging was used to install it

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#1530]
We want to be able to more easily see from log files which packaging option (rpm, deb, OVA, tarball, docker etc) was used to install Graylog to assist in common tuning and config issues.

Proposal is that the packages and other pre-made deployment options write an extra file next to the config file which will contain the string identifying the method used to install Graylog.

**Comment by joschi** [comment]
I'd suggest simply setting a string configuration value via environment variable.

Since every flavor of our distribution packages come with a specific start/stop script, this is more straight forward and will even work if people change their setup "source" during the lifetime of a cluster (e. g. from tarball to DEB package).

**Comment by bernd** [comment]
This also needs to work for all of the different appliances, not only operating system packages. (OVA, OpenStack, Docker) We also want information about the different appliance deployment methods.

Can this be incorporated into the appliance builds? /cc @mariussturm 

For the manual setup via tarball we add this to the `graylogctl` script?

If that works, go ahead. Good idea! :+1:

**Comment by joschi** [comment]
> Can this be incorporated into the appliance builds?

We can override configuration settings via environment variables, so this shouldn't be a problem for the Docker image or or the OVA.

> For the manual setup via tarball we add this to the graylogctl script?

Yes, simply set an environment variable there.
