### ISSUE TITLE
World Map Visualizatin Does Not Load Map Image Tiles - 5.1

### ISSUE THREAD

**Issue by gormanbj** [Graylog2/graylog2-server#15344]
## Expected Behavior
When viewing a World Map widget, the map images should load as you zoom in and out.

## Current Behavior
When viewing a World Map widget, the map images do not load.  The images are accessible via a direct call, however.

![image](https://user-images.githubusercontent.com/97004026/234290700-a9aa7a16-a5c4-4867-a986-6ad5c919bde1.png)

## Possible Solution
Cookie policy?

## Steps to Reproduce (for bugs)
1. Load any previous World Map widget or create a new one.

## Context
Without the images, the World Map widget provides no value.

## Your Environment

* Graylog Version: 5.1-beta
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Windows
* Browser version: Firefox/Chrome/Edge

**Comment by patrickmann** [comment]
Turns out this is due to the `img-src` value in CSP, not `content-src`.

_Note: to test in development, start the server with `DEVELOPMENT=false` and navigate to `localhost:9000` instead of 8080._
