### ISSUE TITLE
Decorator not creating fields in 5.1.0 beta

### ISSUE THREAD

**Issue by kpointer** [Graylog2/graylog2-server#15362]
I've got a decorator that does a reverse dns lookup of an IP and puts the hostname in a new field. The decorator works fine in 4.3.14 and 5.0.6, but in 5.1.0 beta 2 and beta 3, the new field is not created.

Example decorator:

    lookup_table_name:
     hostname lookup
    source_field:
     src_ip
    target_field:
     src_host

## Expected Behavior
The above decorator should do a reverse dns lookup up of the ip from src_ip and put the returned hostname in src_host. In the beta the src_host field is not created.

## Your Environment

* Graylog Version: 5.1.0 beta 3
* Java Version: openjdk 17
* Elasticsearch Version: 7.10.2
* MongoDB Version: 6.0.5
* Operating System: Ubuntu 22.04
* Browser version: Firefox 112

**Comment by dennisoelkers** [comment]
Hey @kpointer,

thanks for reporting this! I have just been trying to reproduce this, but was unable to do so in the most recent version. Can you give me a list of steps allowing me to reproduce it reliably?

**Comment by kpointer** [comment]
I figured out what I was doing wrong. I was trying to recreate something that got broken with the id deserialization bug in beta 1 and wasn't doing something right.
