### ISSUE TITLE
Allow defining additional sources for CSP directives

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#15370]
## What?

Currently our content security policy is rather lax. In order to tighten it down, specifying `self` is not sufficient for some directives, due to 3rd party dependencies making use of external sources, which we cannot infer. Therefore, we need to be able to define additional sources in the code. This could happen e.g. through a resource file declaring source patterns and their types (`img`, `connect`, `style`, `script`, ...). These declarations would be merged with our general policy and returned as part of the CSP header.

Ideally it would be maintained in a single (resource) file which is easy to parse, so we can also make use of in `webpack-dev-server` to return CSP headers in development which are as close as possible to the ones in production.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by patrickmann** [comment]
@dennisoelkers Will this format of settings work for FE?

> default.default-src='self'
> default.style-src='self' 'unsafe-inline'
> default.script-src='self' 'unsafe-eval'
> default.connect-src=*
> default.img-src=*
> 
> swagger.style-src='self' 'unsafe-inline'
> swagger.script-src='self' 'unsafe-eval' 'unsafe-inline'
> swagger.connect-src=*
> swagger.img-src=*
>

**Comment by patrickmann** [comment]
Completed with final merge of #15439
