### ISSUE TITLE
Map widget base layer not appearing in 5.1 beta 3

### ISSUE THREAD

**Issue by waab76** [Graylog2/graylog2-server#15393]
We've noticed in 5.1 beta 3 that map widgets are properly displaying the data points, but they are appearing on a gray background rather than on a map.

![Screenshot 2023-05-01 at 3 36 11 PM](https://user-images.githubusercontent.com/6466251/235517162-015beae1-5f3b-46ec-975f-64f12134cdee.png)

**Comment by kroepke** [comment]
Probably fixed by https://github.com/Graylog2/graylog2-server/issues/15344
