### ISSUE TITLE
Monitor server health and display on health page

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#154]
Folks often have problems sizing the heap sizes of both ES and graylog2.
Help them make better decisions by monitoring heap size usage and GC times and add simply warnings on the health page.
Also expose this via the standard metrics endpoints.

Possibly extend this to ES cluster health monitoring as well, such as disk usage etc. Sigar is already part of ES so we can easily get to the data.

**Comment by edmundoa** [comment]
As mentioned in #2497, I'm closing the issue as it is not easy to display some meaningful information about GC, and it's not such a common case that it is really necessary to do so.
