### ISSUE TITLE
Search page sometimes fails to load a search with a 404 error

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#15435]
## Description

The search page sometimes fails to load successfully after a server restart. The loading spinners don't go away and I can see the following message in the browser console.

![image](https://user-images.githubusercontent.com/461/236419995-6dee5d70-3862-4666-9448-46605e6454ac.png)

```
FetchError: There was an error fetching a resource: Not Found. Additional information:
No search found with id <6454c7a6dbbfd056d1c200d6>.
```

![image](https://user-images.githubusercontent.com/461/236419847-e1602c1a-f33b-4473-95ca-a6089dd9e715.png)

## Steps to Reproduce (for bugs)

1. Close any open browser tabs for the server
2. Restart the server
3. Open the server URL (`/`) to navigate to the welcome page
4. Click on "Search" in the top navigation bar
5. Observe page behavior

It sometimes takes a few restarts until the error shows up.

## Your Environment

* Graylog Version: 5.1.0-rc.1, 5.2.0-SNAPSHOT

**Comment by dennisoelkers** [comment]
Can reproduce it locally. Search creation works with a 200. Search execution fails with 404, although search id returned by creation matches the one being executed.

**Comment by T100D** [comment]
Experiencing something similar when opening configured alerts. A page refresh solves it.

Graylog 4.3.14.

**Comment by dennisoelkers** [comment]
@T100D: This is most probably unrelated. Can you open a separate issue for this? Is there a reason you are still on 4.3 and not on 5.0?
