### ISSUE TITLE
Aggregation field limits on older dashboards reset to 0

### ISSUE THREAD

**Issue by miwent** [Graylog2/graylog2-server#15509]
## Expected Behavior
Aggregation field limits on dasbhoard widgets imported from content packs developed on older versions should retain the original value.

## Current Behavior
Aggregation field limits on dashboards developed in older versions, at least for dashboards imported from content packs that were built in versions of Graylog < 5.0.3, are set to 0.

## Steps to Reproduce (for bugs)
Using a Graylog system < 5.0.2, build a dashboard with aggregation that has a top X limit. Export this dashboard in a content pack then load it on a more recent version (tested with 5.1.0 RC1). View the dashboard field limit.

This is the original dashboard widget configuration on a 5.0.0 system:
![image](https://github.com/Graylog2/graylog2-server/assets/61566003/b76c9dce-c875-44d8-98be-54bb985eb03e)

After creating a content pack and importing it into a 5.1.0 RC1 system:
![image](https://github.com/Graylog2/graylog2-server/assets/61566003/04739585-831d-45f0-b2ce-130f7cca3597)

## Context

Dashboards do not display data as originally intended

## Your Environment

* Graylog Version: 5.1.0 RC1
* Java Version: 17.0.6
* Elasticsearch Version: Opensearch 1.3.6
* MongoDB Version: 5.0.14
* Operating System: Ubunut 20.04.5 LTS
* Browser version: Firefox 112.0.2

**Comment by todvora** [comment]
Could we add a test for that, please?
