### ISSUE TITLE
Content pack auto load only works if the content pack has not been installed yet

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1551]
Content packs that are listed in the `content_packs_auto_load` config option are only applied automatically if the content pack has not been installed yet.

If the user decides to enable the auto load of a content pack at a later point, it does not work because it will be skipped.

**Comment by joschi** [comment]
Unfortunately that's not as easy as it sounds as there are lots of corner cases to handle:

* File containing the content pack has changed on disk (SHA-256 check sum changed) &rarr; should we apply the already loaded but probably different content pack?
* File containing the content pack hasn't changed, content pack has already been loaded but changed in Graylog itself &rarr; should we the apply the different content pack?
* File containing the content pack hasn't changed, content pack has already been loaded and applied in Graylog &rarr; should we apply the already applied content pack?

**Comment by bernd** [comment]
If we cannot fix this in a sane way, we should at least document it.

**Comment by bernd** [comment]
This doesn't apply to the new content pack system anymore.
