### ISSUE TITLE
Deleted/inaccessible entities should not show up in "Last Opened" of Welcome page

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#15524]
## Expected Behavior

When 

## Current Behavior

When a saved search/dashboard was deleted, it should not show up in "Last Opened" anymore.

![image](https://github.com/Graylog2/graylog2-server/assets/41929/ba49f9fa-28e9-450c-bbbb-27ba88c6b7bd)

## Steps to Reproduce (for bugs)

1. Create Dashboard
2. Open it
3. Delete it
4. Navigate to Welcome page

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by luk-kaminski** [comment]
Hi @dennisoelkers,
I cannot reproduce the problem.

In Jan's code we have the following method:
```
    @Subscribe
    public void removeLastOpenedOnEntityDeletion(final RecentActivityEvent event) {
        // if an entity is deleted, we can no longer see it in the lastOpened collection
        if (event.activityType().equals(ActivityType.DELETE)) {
            final var grn = event.grn().toString();
            final var query = new BasicDBObject(LastOpenedForUserDTO.FIELD_ITEMS + "." + LastOpenedDTO.FIELD_GRN, grn);
            final var modifications = new BasicDBObject("$pull", new BasicDBObject(LastOpenedForUserDTO.FIELD_ITEMS, new BasicDBObject(LastOpenedDTO.FIELD_GRN, grn)));
            db.updateMulti(query, modifications);
        }
    }
```

and it seems to remove entries from `last_opened` collection correctly.

Maybe you have some very old items in `last_opened`, removed before this piece of code was introduced?

**Comment by luk-kaminski** [comment]
The only way to reproduce the problem for me was to remove a dashboard from Mongo DB, manually.
I've implemented a quick solution that addresses this rare scenario.
