### ISSUE TITLE
Dashboard widgets no longer "fit" to slots after upgrade from 5.0.7 -> 5.1.0

### ISSUE THREAD

**Issue by hermo** [Graylog2/graylog2-server#15538]
After upgrading to 5.1.0 my dashboard, which previously worked fine has now problems with widgets refusing to go to their assigned places.

## Expected Behavior
This is what the dashboard previously looked (Simulated here by keeping the mouse button pressed while taking the screenshot).
![expected_scaled](https://github.com/Graylog2/graylog2-server/assets/25127/43db8d03-9df7-485b-99f2-88a353a663fd)

## Current Behavior
After the upgrade, the dashboard bumps the "Syslog events by host" widget below the large heatmap widgets and will not allow the widget to be moved up.
![actual_scaled](https://github.com/Graylog2/graylog2-server/assets/25127/7da68fa6-b249-4f1e-b2dc-648e8f7c7e74)

When dragging a widget, the placeholders appear as before but after dropping the widget, the UI freezes for a second or two and then bumps the widget down again.
![drag_scaled](https://github.com/Graylog2/graylog2-server/assets/25127/a2cbdf7d-4d24-47ad-ace1-45c97324e4eb)

I *am* able to drag the widget to the top left corner and it stays put but then everything below it starts acting up again.

I attempted to resize and move every widget in the dashboard to see if that might help fix the issue but it didn't.

## Steps to Reproduce
1. Create a dummy dashboard similar to the image.
![dummy_before_scaled](https://github.com/Graylog2/graylog2-server/assets/25127/9d1f4741-1f1a-415a-b75c-bdf1e22417b6)
2. Resize a component in the middle to be taller than the one on the left.
![dummy_drag_scaled](https://github.com/Graylog2/graylog2-server/assets/25127/fc423fea-5ae8-4be2-8956-937d73ddafc5)
3. Observe that the left side widgets have dropped.
![dummy_after_scaled](https://github.com/Graylog2/graylog2-server/assets/25127/f4383c4e-46fc-420e-9b13-23a4cc89ef45)

Note that resizing the middle widget back to it's original size also returns the other widgets to their expected positions.

## Context
This issue will likely affect many dashboards, making them difficult to read and there seems to be no workaround.

## Your Environment
* Graylog Version: Graylog 5.1.0+14ba491 on [redacted] (Eclipse Adoptium 17.0.6 on Linux 5.10.0-23-amd64)
* Java Version: Bundled
* OpenSearch Version: 2.7.0
* MongoDB Version: 6.0.6
* Operating System: Windows 11
* Browser version:  Firefox 113.0.1, Edge 113.0.1774.50

Please let me know if I can provide more information!

**Comment by dennisoelkers** [comment]
Hey @hermo!

Thanks for reporting this. We have an issue which most probably related to this (#15308). We are already looking into this and will provide a fix soon.
