### ISSUE TITLE
User start page can be set to `Search` without specifying a search

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#15578]
## Expected Behavior

If I set a user's start page type to `Search`, don't specify a search, and click `Update Settings`, I'd expect:
1. `New Search` to be used, or
2. the UI to mark the search field as required

## Current Behavior

The UI doesn't require specifying a search when the user start page type is set to `Search`, resulting in a `PUT` with a body like `{"timezone":"America/Chicago","session_timeout_ms":28800000,"startpage":{"type":"search"},"service_account":false}`.  The missing `id` leads to https://github.com/Graylog2/graylog2-server/blob/011b6fcad981cad29f490961631abae98f8008a2/graylog2-server/src/main/java/org/graylog2/users/UserImpl.java#L405-L419 clearing the start page config.

## Possible Solution

* Default to `New Search` if the startup page type is set to `Search`.
* Require a value for the startup page `id`.

## Steps to Reproduce (for bugs)

1. Go to a user profile page
2. Set the start page type to `Search`
3. Click `Update Settings`
4. Refresh the page and note the start page config was cleared
5. Go to `/` and note the start page is still the new Welcome page

## Context

I was trying to figure out how to get the old default behavior back (`New Search`), and happened to find #14669.

## Your Environment

* Graylog Version: 5.1.0
* Browser version: Firefox 113.0.1

**Comment by janheise** [comment]
validation of the selection of an option is missing for all three types.
