### ISSUE TITLE
View/edit user fails if user has last_opened history

### ISSUE THREAD

**Issue by dmz-uk** [Graylog2/graylog2-server#15574]
Trying to view users in the Graylog 5.1 release, it appears both view and edit are failing with:

`Loading component failed: Can't find route for type: last_opened`

Looking into this a bit further, any users that have entries in `last_opened` are failing.

**Comment by dennisoelkers** [comment]
Hey @dmz-uk,

thanks for reporting this! We will take a look into this asap and keep you updated. Can you provide a complete stack trace from your browser's JS console?

**Comment by dennisoelkers** [comment]
I just tried to reproduce it, but failed to do so. Can you provide exact steps how to trigger this error?

**Comment by dmz-uk** [comment]
[debug.log](https://github.com/Graylog2/graylog2-server/files/11578541/debug.log)

Hi, apologies for the delay there. I'm afraid there are no additional steps. It's literally from login, System -> Users & Teams, scroll down to Users, and either clicking the username or Edit button will generate the error. 

As I've been looking at this to provide details, I note that this isn't a direct single-system install - it's behind a load balancer connecting via http on the backend and presenting https at the front. Additionally this error is seen at login, which looks like it may be related - which is to say http_external_uri is set, but http_enable_cors is **disabled**:

`Content Security Policy: The page's settings blocked the loading of a resource at data: ("default-src"). [users](https://(site redacted)/system/users)
unreachable code after return statement
[redux-toolkit.esm.js:321:4](webpack://graylog-web-interface/node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js)
unreachable code after return statement
[redux-toolkit.esm.js:426:4](webpack://graylog-web-interface/node_modules/@reduxjs/toolkit/dist/redux-toolkit.esm.js)
Some cookies are misusing the recommended “SameSite“ attribute 3`

I won't be able to look at this until next week now, but it may be a problem with the installation settings.

**Comment by dmz-uk** [comment]
Update - unfortunately not, the error does not vary with CORS enabled.

**Comment by dennisoelkers** [comment]
Hey @dmz-uk,

it is unrelated to CORS and an error in our code. We are currently preparing a fix for it.
