### ISSUE TITLE
retention_strategy = snapshot

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1558]
Hello,

I think it should be great to have snapshot action when number of indice is reached:

https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html

Thanks!

**Comment by bernd** [comment]
Graylog Enterprise has an archive feature that can do similar things. Since retention strategies are now pluggable, it's possible to implement something like ES snapshots as a plugin. I am closing this because we are most probably not going to implement this in Graylog server.
