### ISSUE TITLE
Have deflector validity checks

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#156]
There are several ways a deflector can run out of sync. Use the `DeflectorManagerThread` to check:

  - [x] There is a deflector alias
  - [x] The deflector alias is not actually an index called *graylog2_deflector*
  - [ ] The deflector is pointing to the newest index
  - [ ] Alias [graylog2_deflector] has more than one indices associated with it

**Comment by bernd** [comment]
Closing this because there have been lots of changes to the index rotation in 1.1 and the upcoming 1.2. Please re-open if this is still a problem with the latest releases. Thank you!
