### ISSUE TITLE
Altering user session timeout should invalidate current cookie

### ISSUE THREAD

**Issue by neddy0graylog** [Graylog2/graylog2-server#15609]
When altering a users session timeout policy from "sessions do not time out" to use the global timeout policy, the original cookie is not revoked and thus that user will remain logged in until they decide to logout. Once logged back in the correct timeout is reflected within the cookie.

Is it possible to revoke cookies or alter cookies at the point the setting is changed or will the user always needs logout and back in. If not possible, would it be possible to bounce the user out automatically upon changing the setting?

**Comment by ihe-nu** [comment]
as there is no possibility to revoke all cookies / logout all users I would treat this as a security issue.

**Comment by dennisoelkers** [comment]
The key here would be to update the timeout of existing sessions for a user when the user's timeout setting is changed. When this is performed, the cookie expiration date will be refreshed too, upon the next action of the user.

Generally, the lifetime of the session in the backend is relevant here. The cookie's expiration is not a trusted information, it just limits the time the cookie is stored in the browser, it can in no way be used to extend the user's session beyond the configured lifetime.
