### ISSUE TITLE
Remove "free" and "open-source" from project description

### ISSUE THREAD

**Issue by Doctor-love** [Graylog2/graylog2-server#15620]
The current Github repository description is "Free and open source log management" and the README file begins with "Welcome! Graylog is an open source log management platform".

The SSPL, which Graylog transitioned to about two years ago, is incompatible with both [OSI's "Open Source Definition"](https://opensource.org/osd/) and [FSF's "Free Software Definition"](https://www.gnu.org/philosophy/free-sw.html). While you may define these terms differently, I would claim that these organizations describe the de-facto accepted definitions.

In order to avoid miscommunication, I suggest changing the project/product description.

**Comment by marclaporte** [comment]
@kroepke A few more: https://github.com/search?q=repo%3AGraylog2%2Fgraylog2-server+%22open+source%22&type=code

**Comment by marclaporte** [comment]
There are still a few more: https://github.com/search?q=repo%3AGraylog2%2Fgraylog2-server+%22open+source%22&type=code

**Comment by marclaporte** [comment]
Please re-open.
