### ISSUE TITLE
Error: Can't find route for type: last_opened

### ISSUE THREAD

**Issue by patrickmann** [Graylog2/graylog2-server#15638]
Unable to view details of specific users.

## Current Behavior
On test-dev.graylog.cloud running version 5.1.1 (384):
- open system/users
- click on `Zacks Testuser`
- Observe that UI goes blank with just this error message: `Loading component failed: Can't find route for type: last_opened`
- Console shows this:

> Error: Can't find route for type: last_opened
>     at r (getShowRouteForEntity.ts:20:9)
>     at a (getShowRouteForEntity.ts:48:14)
>     at m (GRN.ts:34:10)
>     at ve (SharedEntitiesOverviewItem.tsx:41:17)
>     at Tt (vendor.8a712d83b311029bb0b6.js:672:50782)
>     at Rs (vendor.8a712d83b311029bb0b6.js:674:8409)
>     at ys (vendor.8a712d83b311029bb0b6.js:674:891)
>     at Xs (vendor.8a712d83b311029bb0b6.js:674:816)
>     at Gi (vendor.8a712d83b311029bb0b6.js:672:87282)
>     at vendor.8a712d83b311029bb0b6.js:672:37228

`Edit` works fine - only details view seems affected.

* Graylog Version: 5.1.1 (384)

**Comment by dennisoelkers** [comment]
Fixed in #15658.
