### ISSUE TITLE
Kafka Input...read on input restart

### ISSUE THREAD

**Issue by robyOggio** [Graylog2/graylog2-server#1565]
Dear Graylog community,
I am using Graylog last version, on a Linux machine where a Kafka server is running which produces some messages, that I read from the kafka console consumer.
In Graylog, I create a Kafka Input, which connects to the same Zookepeer Server and it writes the messages to Elastic Search server. Infact, on the Graylog web interface, I noticed that average indicator of read messages. It starts with (about) 200 msg/second and it speedly decreases to zero, even if the kafka producer is  writing messages. It seems that Graylog reads all messages in one time, and it doesn't continue to read.  I must restart the kafka input, in order to read the new messages.
I reported the Kafka Input configuration

![image](https://cloud.githubusercontent.com/assets/4353477/11185301/60b60792-8c7c-11e5-85fc-969357a4ad1b.png)

Thanks for your attention.

Best regards!
Bye

**Comment by robyOggio** [comment]
Hi! I tried to change the settings of Kafka Input, but it doesn't resolve the problem.

![image](https://cloud.githubusercontent.com/assets/4353477/11185750/8d595c2a-8c7e-11e5-9e65-ffc9a07e4302.png)

**Comment by jalogisch** [comment]
please update to the latest version, we can't verify this issue.
