### ISSUE TITLE
AD authentication backend cannot sync users in 5.1

### ISSUE THREAD

**Issue by patrickmann** [Graylog2/graylog2-server#15652]
https://community.graylog.org/t/active-directory-authentication-not-working-in-5-1/28929

> I’m running Graylog with Active Directory Authentication since at least version 4.2. A few days ago I upgraded to version 5.1 (from 5.0). After that I can not login anymore using a user from the AD. Users not associate with the AD can login.
> 
> Using the login form the error message is:
> Error - the server returned: 503 - There was an error fetching a resource: Service Unavailable. Additional information: Authentication service unavailable
> 
> Using the “Test Server connection” in System/Authentication the message is:
> 
> There was an error fetching a resource: Bad Request. Additional information: Unable to map property email_attributes. Known properties include: servers, verify_certificates, user_search_base, transport_security, type, user_name_attribute, user_search_pattern, system_user_dn, system_user_password, user_full_name_attribute
> false

## Possible Solution

5.1 introduced configurable email attribute for LDAP. Since AD shares some of the code with LDAP, this included changes to AD authentication backend. Guessing the problem is this:
https://github.com/Graylog2/graylog2-server/blob/e3b1f04db87ea81347b07fc7f1039038ced5130f/graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java#L153

## Context

Users can no longer log in after upgrading to 5.1

## Your Environment

* Graylog Version: 5.1

**Comment by patrickmann** [comment]
`emailAttributes` is a new mandatory field in `UnboundLDAPConfig`.  Due to code re-use, AD now also needs to provide an attribute value, even though we are not making it user configurable for AD. Thus, it needs to be set to the hard-coded value we used through 5.0: `mail`.
Current behavior is that an empty list is passed, which then defaults to the dummy value `unknown@unknown@invalid`

**Comment by rkmbaxed** [comment]
Error still exists in v5.1.2.

**Comment by drewmiranda-gl** [comment]
> Error still exists in v5.1.2.

What error are you getting? Are you able to remove/readd the Active Directory authentication service in graylog?

Screenshots from my testing to confirm this is working with 5.1.2.

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/68d2c436-de19-4c6a-987e-50c1c5de1c30)
![image](https://github.com/Graylog2/graylog2-server/assets/107503402/7a451945-5118-43fd-ada4-1d66edd4e668)
![image](https://github.com/Graylog2/graylog2-server/assets/107503402/6a50ba11-fbbf-4296-885b-75484243a6c7)

**Comment by drewmiranda-gl** [comment]
To clarify my previous post:

* Testing greenfield (new cluster install, no upgrades): works fine, no issue
* Testing with a cluster that has been upgraded from past versions: issues

Initially i got an error in server log that bind info (e.g. user/pass) must be set. I attempt to set and then to test server connection, but error:

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/e737ed46-3ecb-4835-8954-ca114f2a62cb)

> There was an error fetching a resource: Bad Request. Additional information: Unable to map property email_attributes. Known properties include: servers, verify_certificates, user_search_base, transport_security, type, user_name_attribute, user_search_pattern, system_user_dn, system_user_password, user_full_name_attribute
false

**Comment by rkmbaxed** [comment]
I can confirm that an existing auth service throws still the error after update to v5.1.2
![image](https://github.com/Graylog2/graylog2-server/assets/33449202/7c9f958e-d055-4dfe-82ba-8bf66682708f)

I can also confirm that while I add a new auth service all things works as  expected.

**Comment by patrickmann** [comment]
@rkmbaxed Thanks for the update about 5.2.

When logging in with the existing AD auth service, did you encounter the 503 error you initially reported? 
I have only been able to reproduce the _unable to map_ error by clicking `test server connection` or `test user login` on the auth service edit form.

**Comment by rkmbaxed** [comment]
Oh, I wasn't the reporter with the 503 error.
https://community.graylog.org/t/active-directory-authentication-not-working-in-5-1/28929

The only error I see when the error ocurrs: {"type":"ApiError","message":"HTTP 405 Method Not Allowed"}
![image](https://github.com/Graylog2/graylog2-server/assets/33449202/963d3cf8-7486-4cb2-ac46-38a3e0813ea2)

**Comment by patrickmann** [comment]
The root cause is a FE problem with group sync. When enabled, the FE sends an empty `email_attributes` array in the AD config. When disabled, the error does not occur. It makes no difference whether the auth backend was pre-existing or newly defined - they behave the same way. 

This means AD group sync is broken for all users of 5.1 and above, so it is urgent to fix this.
