### ISSUE TITLE
"Add to query" triggers suggestions if cursor is at the start of the search query

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#15664]
## Expected Behavior

`Add to query` (e.g. narrowing down to a specific `source`) should not trigger field value suggestions (e.g. values for `source`).

## Current Behavior

Selecting `Add to query` results in the search query being updated appropriately, however it also triggers field value suggestions for the associated field (not restricted by the value that was just added) if the input cursor is at the start of the search query.  This does not occur if the cursor is not at the start of the search query.

![image](https://github.com/Graylog2/graylog2-server/assets/19417721/ee59c5c0-2e70-45fc-a8a4-4857a097ea78)

Additionally:
* the suggestions pop-up can't be dismissed without focusing on the search query input
* ~if the search query input is not fully in view (e.g. you're scrolled down to look at a message table) the suggestions pop-up will barely show up at the top of the window~ (only saw this once and haven't been able to reproduce since)

## Steps to Reproduce (for bugs)

1. Have a `5.1.1` environment with some messages in it
2. Have an empty search query (or ensure the cursor is at the start of the search query input)
3. For one of the `source` values in a widget, select `Add to query`
4. Note the `source` field value suggestions
5. Note that you have to click in the search input before the suggestions pop-up goes away

## Context

UI annoyance

## Your Environment

* Graylog Version: `5.1.1`
* Browser version: Firefox 113, Chrome 114

**Comment by drewmiranda-gl** [comment]
I thought i had opened an issue for this, but i couldn't find it. this one has been on my mind for a long while!

**Comment by coffee-squirrel** [comment]
Closing this, since it appears to be a duplicate of #12165 (opened by @bernd in February 2022).
