### ISSUE TITLE
Same log multiple times

### ISSUE THREAD

**Issue by gbaltrons** [Graylog2/graylog2-server#1567]
Hi, i've just started with this github account cause i've an issue that i can't fix. We are starting with graylog and we have got only a node with seven inputs, everyone with its output. Every input is obtaining from a different server and six of them work correctly. The fact is that the other one show us the same message multiple times. It appears sometimes up to 3,000,000 times on graylog and it fulls indices fastly. When we look the log file from the server path to see traces, we see that every message is unique. Somehow when arrives at graylog server it gets multiplied. I would appreciate you're help cause we are novice with this software and we don't know what's the matter with this problem.

I insert an example which "only" gets multiplied 300,000 times.

- Search log:
![captura2](https://cloud.githubusercontent.com/assets/15869621/11180793/cd24c8e2-8c5d-11e5-8aad-dd761e6643c1.PNG)

- Same log multiple times:
![captura1](https://cloud.githubusercontent.com/assets/15869621/11180857/1cdaffbe-8c5e-11e5-99ab-38f833ff331e.PNG)

- Trully unique trace on log file:
![captura](https://cloud.githubusercontent.com/assets/15869621/11180784/c0848c26-8c5d-11e5-9e92-f078f6b1115c.PNG)

**Comment by joschi** [comment]
The fact that the search queried 9 indices indicates that the message simply comes in that many times. Since the displayed time is most probably the timestamp included in the message, it's probably some rogue client that sends the same message multiple times (continuously).

**Comment by gbaltrons** [comment]
I've checked the log file collected and it seems the client send the message once. Now i've seen that if i stop the stream associated to the client, the message isn't send multiple times. Moreover, if i stop the output associated to the stream (with active stream), the message doesn't get multiplied. How can it be possible?  Now i'm trying to trigger an alert to my mail but i get too many mails.

**Comment by joschi** [comment]
Did you send the stream messages back into the same Graylog server with the configured output?

**Comment by gbaltrons** [comment]
Omg, you're so right! The fact was that stream resend the message again to the graylog server configured at output. Since i have a server for graylog (one node) i think i don't need an output at streams. I had set stream's output with field hostname as server's name. Thank you so much!

**Comment by joschi** [comment]
You're welcome.
