### ISSUE TITLE
Favorite not removed after ContentPack removal, "Unknown Entity" remains in list on StartPage

### ISSUE THREAD

**Issue by janheise** [Graylog2/graylog2-server#15672]
## Expected Behavior

If you remove a ContentPack, former references to Favorites and LastOpened items are removed from the lists on the StartPage.

## Current Behavior

Ugly "Unknown Entity:id" entries remain.

## Steps to Reproduce (for bugs)

1. Upload/install a Content Pack with a Dashboard
2. Mark a Dashboard from the Content Pack as Favorite
3. Uninstall/remove the ContentPack
4. go to StartPage

## Your Environment

* Graylog Version: 5.1.1 and 5.1.2-dev
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by luk-kaminski** [comment]
@janheise - it does not happen anymore.
Content-pack-favorite disappears from all parts of the start page after Content Pack is uninstalled in the system.
Probably fixed by https://github.com/Graylog2/graylog2-server/pull/15779.
