### ISSUE TITLE
Improve time to load for Last Opened list on new start page, takes several seconds to load

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#15697]
## What?

I noticed that when using the new start page for graylog (Last Opened, Favorite Items) 'favorite items' loads very quickly, while 'last opened' can take 2-3s to load.

Is it possible to optimize this?

## Why?

Improving load time would improve user experience.

## Your Environment

* Graylog Version: Graylog 5.1.1+ef1b993
* ~~Elasticsearch~~ OpenSearch Version: 2.6.0
* MongoDB Version: 6.0.6
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 114.0.5735.90 (Official Build) (arm64)

**Comment by janheise** [comment]
@drewmiranda-gl it's interesting that you see a difference - because both collections and queries are structured the same (down to the use of indices etc). but I'll take a look

**Comment by coffee-squirrel** [comment]
Quick and dirty check (Graylog `5.1.1`, MongoDB `5.0.14`, ES `7.10.2`):
* `/api/startpage/lastOpened?page=1&per_page=5`: 526ms
* `/api/favorites?page=1&per_page=5`: 37ms
* `/api/startpage/recentActivity?page=1&per_page=5`: 54ms

Roughly the same on subsequent requests.  I'm not seeing 2-3 seconds, but it is consistently slower.

**Comment by drewmiranda-gl** [comment]
> @drewmiranda-gl it's interesting that you see a difference - because both collections and queries are structured the same (down to the use of indices etc). but I'll take a look. do they differ significantly in size? is this on a machine you have access to mongoDB?

I do have access to mongodb. Its my home lab. Arguably not the best hardware :( 

4 core - Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
32GB ram

Querying `last_opened` via mongo returns a result fairly quickly (near instant)

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/7460b25d-5c2b-445b-ba19-48919af8d11c)

**Comment by luk-kaminski** [comment]
I'll have a closer look, but it seems that BE collects titles of all items, despite presenting only 5 of them and that may be the reason of poor performance.

**Comment by luk-kaminski** [comment]
https://github.com/Graylog2/graylog2-server/pull/15771 PR should improve the situation, let's wait for a review.
@drewmiranda-gl , @coffee-squirrel  - Thank you very much for finding the issue and for a great input data - it was much easier to spot the problem with all your discoveries and measurements!

**Comment by luk-kaminski** [comment]
Hi @drewmiranda-gl !
The fix has been merged! Do you have a way (and time!) to check if it helped?

**Comment by dennisoelkers** [comment]
Fixed in #15771, I can see a huge improvement locally. @drewmiranda-gl, feel free to reopen if the problem still persists for you.

**Comment by drewmiranda-gl** [comment]
Thank you! I'll test when its released.

**Comment by luk-kaminski** [comment]
@drewmiranda-gl - FYI, https://github.com/Graylog2/graylog2-server/pull/15830 should improve the performance even more.
With those two improvements the situation should be much better.

We may want to improve the performance even more in the future, but that would require a significant refactoring...
I'll inform you if it happens soon.
