### ISSUE TITLE
Replay replay-search page doesn't have initial highlights for aggregation conditions

### ISSUE THREAD

**Issue by maxiadlovskii** [Graylog2/graylog2-server#15715]
On the replay search page for the event, alerts, and event definition with aggregation, we have a logic that generates random colors to highlight passed values in the data table. It looks like this logic was somehow broken. 

Step to reproduce. 

1. Create an aggregation event definition with conditions.
2. wait for the event 
3. run a replay search for the event (or run a replay search for event definition)
4. Investigate the Search info bar. There are aggregation conditions but highlight colors are not defined initially 

![Image](https://github.com/Graylog2/graylog2-server/assets/10741557/624f047d-e6f7-436a-9f55-06fd71241851)

**Comment by linuspahl** [comment]
I tested this with event definitions, events and alerts, but I was not able to reproduce the bug. @maxiadlovskii can you please check if you are able to reproduce it snd reopen the issue in this case?
