### ISSUE TITLE
Track and display "last triggered" time for event definitions

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#15751]
## What?

Each event definition should have a "last triggered" date value that tracks the last time its criteria matched.  This value should be searchable on the `Event Definitions` page (similar to `created`, `from`, `to` for archives).

## Why?

When there are many event definitions, it can be difficult to determine which are no longer providing value (e.g. existed for years but has never triggered an alert).  Being able to identify these event definitions can help reduce unnecessary load in the environment (removal, frequency adjustment, etc.).

## Your Environment

* Graylog Version: `5.1.2`
* Elasticsearch Version: `7.10.2`
* MongoDB Version: `5.0.14`

**Comment by bernd** [comment]
Thanks! I think we should name this "last matched" or similar. Our job scheduler is using the "trigger" terminology to determine when an event definition job should run.

**Comment by patrickmann** [comment]
Backend now adds/updates the `matched_at` field for all event definitions (except system notification).
Still need to expose it on the UI.
