### ISSUE TITLE
Syslog Input freeze after extractor definition

### ISSUE THREAD

**Issue by sgrunt91** [Graylog2/graylog2-server#1575]
Hi everyone,

I'm trying to send Apache log to a Graylog2 (1.2) instance via Syslog.
My Apache logs are in the default combined format to use predefined grok patterns.

I added a new Syslog TCP input with default values, and I see my messages coming, cool!
Then I want to add an extractor on the message field and type "Grok Pattern".
My pattern is:
> %{IPORHOST} %{SYSLOGPROG}: %{COMBINEDAPACHELOG}

And works great when I'm using the "Try" button.

But once I save the extractor, no more messages are received by the input.
I don't know what happens, or where to find info, errors...
It's like a freeze of the input.

If I remove the extractor, messages input work again.

Can you help me with that ?

Regards

**Comment by sgrunt91** [comment]
The default GROK pattern use field "timestamp" which is a default one for Graylog (GELF?). 
Solved by changing the default Apache pattern from
> (?:%{IPORHOST:clientip}|-) %{USER:ident} %{USER:auth} \[%{HTTPDATE:timestamp}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-)

to
> (?:%{IPORHOST:clientip}|-) %{USER:ident} %{USER:auth} \[%{HTTPDATE:received_time}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-)

**Comment by jneureuther** [comment]
@sgrunt91 thank you for the solution, exactly this has been my problem to.

I think this should be fixed, so why not reopen the issue?
