### ISSUE TITLE
Unable to edit search filters in dashboard widgets that are imported from content packs

### ISSUE THREAD

**Issue by miwent** [Graylog2/graylog2-server#15841]
Users are unable to edit search filters used in dashboard widgets that are imported as part of a content pack.

## Expected Behavior

Users should be able to edit the search filters

## Current Behavior

Editing the filter generates an error
![filters_error](https://github.com/Graylog2/graylog2-server/assets/61566003/63afaae2-4e65-4588-932b-40679b09f942)

## Steps to Reproduce (for bugs)

1. Create a dashboard with widgets that rely on search filters
2. Export this dashboard in a content pack and remove the test dashboard
3. Import the content pack and install 
4. Attempt to edit the filters in the test dashboard widgets

## Context

This would limit the ability of users to customize content after it was imported from the content pack. For Illuminate this would mean the filters could only be edited on the system they were originally generated on, as long as those widgets were never removed.

## Your Environment

* Graylog Version: 5.0.3/5.1.2
* Java Version: openjdk version "17.0.7" 2023-04-18
* Elasticsearch Version: Opensearch 1.3.6
* MongoDB Version:
* Operating System: Ubuntu 20.04.6 LTS
* Browser version: Firefox 114.0.1 (64-bit)

**Comment by dennisoelkers** [comment]
The underlying issue is that even though the search filter has a type of `referenced`, it is not actually persisted to the `search_filters` collection when the content pack is installed.
