### ISSUE TITLE
"Unknown Entity" on personal start page is un-actionable 

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/graylog2-server#15852]
On the personal start page, displaying Unknown Entity for deleted or missing items negatively impacts the customer experience by contributing to customer confusion and reducing customer confidence:

![image](https://github.com/Graylog2/graylog2-server/assets/2953243/afdc3b51-057e-4069-94f3-0b291ece90d7)

In this context, it's because I disabled Illuminate spotlights. I now have "Unknown Entity" showing up, which I cannot remove, and when I click, shows the party gorilla: 

![image](https://github.com/Graylog2/graylog2-server/assets/2953243/6b3fc453-b940-4477-a886-6574f6013133)

* Graylog Version: Graylog 5.1.2+d970230
* Java Version: Eclipse Adoptium 17.0.6 on Linux 6.1.0-9-amd64
* Elasticsearch Version: 2.4
* MongoDB Version: 5.x
* Operating System: Debian 12
* Browser version: Version 114.0.5735.198 (Official Build) (arm64)

**Comment by dennisoelkers** [comment]
Fixed in #15779.
