### ISSUE TITLE
OR operator not working

### ISSUE THREAD

**Issue by serversteam** [Graylog2/graylog2-server#15859]
I am running graylog over docker.

graylog:5.1.2
mongo:latest
elasticsearch:7.12.0

I am facing issue with search query. I  have query **message:"HTTP/1.0\" 401" OR message:"HTTP/1.1\" 401"** which will show messages for both HTTP 1.0 and HTTP 1.1. But its only showing for 1 that one we have defined at  first place. ie
message:"HTTP/1.0\" 401" OR message:"HTTP/1.1\" 401"  it will shows only HTTP/1.0 messgaes
message:"HTTP/1.1\" 401" OR message:"HTTP/1.0\" 401"  it will shows only HTTP/1.1 messgaes

Can you please let me know what i am missing. 

Thanks in advance.

**Comment by dennisoelkers** [comment]
This does not seem to be an issue with Graylog. Closing it. Please reopen if you have additional information indicating that this is actually a bug.
