### ISSUE TITLE
Searches are counted twice

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1587]
Searches are counted twice per search.

See: https://github.com/Graylog2/graylog-plugin-anonymous-usage-statistics/pull/13#issuecomment-159650181

It looks like `GlobalTimeoutClient#search()` is called twice per search requests and thus breaks the total count.

**Comment by kroepke** [comment]
I think that is the request for the histogram on the search result page, and I'm not sure if we don't want to count that.
