### ISSUE TITLE
Message body not showing on notifications

### ISSUE THREAD

**Issue by ed-graylog** [Graylog2/graylog2-server#15886]
## Expected Behavior

When attempting to setup notifications for Graylog, any time we use the event.message option our expectation is that it should output the entire message.

## Current Behavior

Currently it is outputting the title to the notification only. Using any other setting also does not provide the expected results.

## Steps to Reproduce (for bugs)

1. Using Graylog 5.1 go to create a notification for example you can setup a Slack notification. When you set it up and it fires you will see the title of the notification only and not the entire message body as expected.
2.
3.
4.

## Context

We just want something straightforward to show the message body.

## Your Environment

* Graylog Version: 5.1.2
* Java Version: java-17-openjdk-headless
* OpenSearch Version: 2.5.0
* MongoDB Version: 6.0
* Operating System: RPM based

**Comment by mpfz0r** [comment]
`${event.message}` is not the message that triggered an event, but the descriptive "message" of the event itself.

An event can be triggered by one ore more messages (aggregation event definitions) or even not messages at all, but 
other events. (correlation event defintions).

To access the desired message, you'd need to use the `backlog` of messages with the notification.
