### ISSUE TITLE
Calculating widget values returns 404

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#1588]
On 1.3, getting dashboard values from the server returns 404, resulting in: Graylog2/graylog2-images#99

Looking a bit around, it looks like this is related to #1542. @dennisoelkers did some changes in c697c5eb0b421afcc0eceeb92bf5bc396dac4831 to fix that problem in master, that we could merge if we don't want to revert it.

**Comment by dennisoelkers** [comment]
Has been fixed in c697c5eb0b421afcc0eceeb92bf5bc396dac4831 on master, needs backport to 1.3 (due to usage of Java 8 idiom).

**Comment by edmundoa** [comment]
Fixed on 8336a8d973b177b574948b704d4756f284f49166.
