### ISSUE TITLE
Regression: Unable to edit definition of System Notification Events

### ISSUE THREAD

**Issue by patrickmann** [Graylog2/graylog2-server#15949]
Error message when attempting to update the System Notification Events definition (SNED).

## Expected Behavior

SNED is special: most tabs are not modifiable, with the exception of notifications. I should be able to add a notification.

## Current Behavior

Error message when attempting to save the updated definition: 

> ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
> java.lang.IllegalArgumentException: Cannot disable system notification events
> 	at org.graylog.events.processor.EventDefinitionHandler.unschedule(EventDefinitionHandler.java:190) ~[classes/:?]

in response to this FE request:
> PUT	http://localhost:8080/api/events/definitions/649d83e3801701298471e3ed?schedule=false

which results in the call to `EventDefinitionHandler.unschedule`. However, SNED cannot be disabled.

## Your Environment

* Graylog Version: 5.2.0
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by gally47** [comment]
Just confirmed with @ousmaneo. It was intentional that the event fields of system notification event definitions cannot be edited. The changes were done in this PR: https://github.com/Graylog2/graylog2-server/pull/13833
