### ISSUE TITLE
Secure the DataNode REST interface after successful certificate generation

### ISSUE THREAD

**Issue by janheise** [Graylog2/graylog2-server#15990]
After certificate creation, we also have to secure the REST api with this new certificate. 

also, see https://github.com/Graylog2/graylog2-server/pull/15925#pullrequestreview-1536742113

**Comment by todvora** [comment]
Implemented in https://github.com/Graylog2/graylog2-server/pull/16058. The jersey service now uses the same http certificate that opensearch uses for the rest api.
