### ISSUE TITLE
Raw AMQP not creating exchange binding

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#1599]
Starting some tests with RabbitMQ + Graylog, after creating a raw/plaintext AMQP input I've noticed that Graylog doesn't create the exchange => queue binding.

It creates the queue succesfully, but the queue has empty bindings, shown on the attached images.

![glogos1](https://cloud.githubusercontent.com/assets/7182341/11532178/40670dfa-98e9-11e5-8b2a-2e5e5c7664b9.png)
![glogos2](https://cloud.githubusercontent.com/assets/7182341/11532180/426cde04-98e9-11e5-9282-aa68e60e31dc.png)
![glogos3](https://cloud.githubusercontent.com/assets/7182341/11532182/450a6aaa-98e9-11e5-9104-6ea86bce8226.png)

EDIT: This way, I do have to manually bind the exchange with the log queue.
Forgot to mention, I'm using Graylog Server 1.2.2.

**Comment by bernd** [comment]
@rikatz Thank you for the report! We created a PR in #1633 to fix this.

**Comment by bernd** [comment]
@rikatz This will be fixed in the upcoming Graylog 1.3.1.

**Comment by rikatz** [comment]
Great \o/
