### ISSUE TITLE
Allow formatting text values

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#16003]
## What?

Add the ability to format the value of a graylog field. For example, format as a percentage, or convert bytes to megabytes.

My thinking on how this could work: it could behave as a decorator for now, and some fields (such as graylog fields or GIM fields) could have predefined (but user editable) rules.

## Why?

Currently there isn't any easy way to format text values in graylog. While you can somewhat accomplish this with things like pipelines and decorators, its difficult to setup and not very flexible.

Some fields would be much easier on the eyes when formatted. Things like percentages (for example the anomaly detector fields such as anomaly_confidence and anomaly_grade) and unit conversations, such as bytes to megabytes.

## Your Environment

* Graylog Version: 5.1.3
* OpenSearch Version: 2.8.0
* MongoDB Version: 6.0.7
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 115.0.5790.98 (Official Build) (arm64)

**Comment by dennisoelkers** [comment]
This has been mentioned a couple of times, e.g. in #6587, #8110, #9864. Closing this as duplicate.
