### ISSUE TITLE
Move "Preset times" next to "Save Preset" button, optimize wording

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#16000]
Now with the removal of the redundant time range preview (#15961), we can move the "Preset Times" button there, next to the "Save preset" button. Both buttons would benefit from an improvement of their caption. Maybe something like "Load Preset" / "Save as Preset"?

**Comment by linuspahl** [comment]
We can also unify the naming by changing "quick access" to "preset"

![image](https://github.com/Graylog2/graylog2-server/assets/46300478/6aa84f13-4be9-447b-a3fa-3481f45d8b36)
