### ISSUE TITLE
Unable to Update existing roles - API

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#16019]
While the Graylog UI doesn't provide a way to manage roles (e.g. create roles, edit permissions of roles), the graylog api provides this functionality and it works very well.

However, managing the permissions in a role can be quite cumbersome, especially when using trial and error to test how different permissions behave and what the minimum required permissions may be to perform something in graylog.

My understanding is the `[PUT] /roles/{rolename}` endpoint is mean to help with this, however, i've not been able to get this endpoint to work. The defined schema appears to be identical to the one for creating a role. However when using the same json/schema an error is returned:

```json
{
  "type": "ApiError",
  "message": "Cannot construct instance of `org.graylog2.rest.models.roles.responses.RoleResponse`, problem: Null name\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 3, column: 1]"
}
```

I believe this to be a bug. The only work around is to delete the role and recreate it. This is cumbersome and also removes all users that were assigned to the role.

## Expected Behavior

Using the api endpoint to update a role works without error.

## Current Behavior

Endpoint to update a role returns an error.

## Steps to Reproduce (for bugs)

Using the api browser `/api/api-browser/`

1. Find and expand the `Roles : User roles` section
2. Expand `PUT /roles/{rolename}`
3. Input json body that conforms with defined schema, such as:

```json
{
"read_only": false
}
``` 

## Context

This is probably not a commonly used endpoint since its not exposed in the UI. I would expect this to be a low priority but wanted to report nonetheless since these api endpoints are provided in the context of a workaround for not being able to manage roles within the UI.

## Your Environment

* Graylog Version: 5.1.3
* Java Version: Bundled
* OpenSearch Version: 2.8.0
* MongoDB Version: 6.0.8
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 115.0.5790.98 (Official Build) (arm64)

**Comment by patrickmann** [comment]
The `name` field in the JSON body is required. I am able to successfully update a role if I provide it.

It appears you cannot trust Swagger to tell you whether fields in the body are optional or required - everything shows up as optional. But the error message is pretty clear about what is missing.

**Comment by drewmiranda-gl** [comment]
I see now that you have explained it. The message was pretty difficult to read because of formatting. Can swagger be fixed to indicate the correct required fields? It appears the true required fields are:

* name (which i assume is just "rolename"?)
* permissions
