### ISSUE TITLE
In ApiClientImpl, log the exception creating "Unhandled error condition" message

### ISSUE THREAD

**Issue by rblumen-desk** [Graylog2/graylog2-server#1603]
https://github.com/Graylog2/graylog2-server/blob/1.2/graylog2-rest-client/src/main/java/org/graylog2/restclient/lib/ApiClientImpl.java#L437

If an exception is thrown but not caught in one of several catch blocks, a new IllegalStateException is thrown with the message throw "Unhandled error condition in API client".  The root cause exception that was not caught is not logged.  We are seeing this message in error logs.  It would be helpful to know the exception that was not caught at that point.

**Comment by bernd** [comment]
This class is gone in Graylog 2.0 and the communication between web and server is completely different.
Closing this issue.
