### ISSUE TITLE
Multi-tenancy support

### ISSUE THREAD

**Issue by felipegs** [Graylog2/graylog2-server#1605]
Hi,
We loved to use graylog, but we have some problems here.

We have more than one products, clients and the way that graylog is designed is very difficult to achieve
Multi-tenancy. We have a lot of products and clients, it became a mess. We would like to use one cluster of graylog for all of our products and clients.

I would be nice if we can create every "struct"(indices, streams, extractors and so on..) of graylog by an "organization".

**Comment by dls314159** [comment]
This, and also if anyone reading knows of best multi-tenancy practices/accomodations around Graylog2 (or links to discussions about them), it would be appreciated.

**Comment by sio4** [comment]
+1 :-)

**Comment by florianvolle** [comment]
Closing this in favor of #1004
