### ISSUE TITLE
Absolute Datetime picker jump to previous day when we click on beginning of the day

### ISSUE THREAD

**Issue by ousmaneo** [Graylog2/graylog2-server#16096]
When selecting Absolute date for the search, the selected day jumps to the previous day when we click the "`Beginning of the day`" Hourglass icon. All subsequent day selections afterward also jump to the previous day. (See below)

![Absolute-time-issue](https://github.com/Graylog2/graylog2-server/assets/1381455/5e9e1294-236a-4af5-a55c-7131fbb23728)
 

## Steps to Reproduce (for bugs)

1. Go to search
2. Select absolute datetime
3. Click on the hourglass icon for `from` or `to`
4.

## Your Environment

* Graylog Version:
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by linuspahl** [comment]
It looks like this error also occurs for the date time picker in the sigma rules overview.

![image](https://github.com/Graylog2/graylog2-server/assets/46300478/99ac92a8-65b9-4576-b8ce-04f3b29ec332)
