### ISSUE TITLE
Dropdown to change time range types in Firefox 42.0 not working correctly 

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-server#1611]
Using 'graylog-1.3.0-beta.3-SNAPSHOT-20151130161327.tar.gz' and Firefox 42.0

When performing a search and changing the time range type via dropdown one has to click the search button to perform the search instead of pressing enter. In Chrome and Safari this is working.

**Comment by dennisoelkers** [comment]
This has been fixed in the meantime.
