### ISSUE TITLE
Need flag, opensearch yes / no (common use of graylog and *beats)

### ISSUE THREAD

**Issue by StefanSa** [Graylog2/graylog2-server#16167]
## What?
Need flag, opensearch yes / no:
`opensearch_storage = true`

## Why?
i already know that there is an automatic detection if the storage is Elastic or Opensearch.
However, there are situations in which you have to specify this manually.

Simple example:
filebeat works only with the `compatibility.override_main_response_version: true` option switch and opensearch correctly,
but graylog does not. (simulates an ES 7.10.2 version to the client.)

In order for graylog to work with openserach despite this parameter, you would have to have this flag, for example: 
`opensearch_storage = yes`
graylog would understand that despite the Storagge info, i am ES 7x compatible, it should use opensearch as backend.

So you could use *beats and graylog together with opensearch, which is currently not possible.

**Comment by bernd** [comment]
You can set `elasticsearch_version` to `1` or `2`, depending on your OpenSearch version. There is no need for a separate flag.
