### ISSUE TITLE
Opensearch in datanode transport communication hostname

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#16219]
When opensearch in the datanode tries to build a cluster from a one-node configuration, it somehow autodetects the hostname used to communicate with its self. This hostname is (at least locally for me) resolved to `localhost`. The problem arises when the communication uses SSL certificates - the hostname is verified in the certificate and the verification usually fails, because we don't generate certificates with `localhost` in the SAN. 

I assume that the hostname could be configured somehow, maybe as `network.publish_host`. So far I was unable to reliably set it, so I don't get the SSL verification errors. 

As a naive and probably dangerous workaround, the `plugins.security.ssl.transport.enforce_hostname_verification` can be disabled (=false value), which will hide the problem. We should remove this option as soon as we know better how to deal with the hostname configuration and its autodetection.

## Expected Behavior
Opensearch does not autodetect hostname and uses the one we configure. Hostname verification is enabled. `plugins.security.nodes_dn` contains a regex that matches expected SSL certs.

## Current Behavior
The hostname verification is disabled since this PR: https://github.com/Graylog2/graylog2-server/pull/16194/

## Steps to Reproduce (for bugs)
1. Enable hostname verification  `plugins.security.ssl.transport.enforce_hostname_verification` 
2. Start datanode with SSL certificates
3. Observe SSL errors when opensearch tries to form a cluster

**Comment by janheise** [comment]
I think we should reproduce this again - we do't use the setting `discovery.type=single-node` any more in any of our setups and as far as I understood the docs, this setting is largely to make sure that you have a single node that binds to `localhost` and overrides stuff- so maybe it's not an issue any more.
