### ISSUE TITLE
The file org.graylog.plugins.pipelineprocessor.parser.RuleLangParser cannot be found in the source code

### ISSUE THREAD

**Issue by sinchey** [Graylog2/graylog2-server#16242]
## Expected Behavior
This file is included in the source code and the project can be successfully packaged

## Current Behavior
The file org.graylog.plugins.pipelineprocessor.parser.RuleLangParser cannot be found in the source code.
Failed to import dependencies into the org/raylog/plugins/pipelineprocessor/parser/PipelineRuleParser.java file

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:5.1
* Java Version:17
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
This file is generated through ANTLR during the build. Please run `mvn compile` for it to be generated.

This is not an issue in Graylog, therefore I am closing it. If you have additional information, please reopen it.
