### ISSUE TITLE
Graylog-server fails after update from 1.2 to 1.3 (using rpm's repos )

### ISSUE THREAD

**Issue by lfacchinelli** [Graylog2/graylog2-server#1626]
Hi guys : 
Today i updated my graylog-server from 1.2 to 1.3 (updating through yum) 
My VM runs Centos 7 and after the upgrade, when i start graylog-server this messages outputs in /var/log/messages : https://paste.fedoraproject.org/299624/44977323/.

The process starts, but no ports are in use ( 12900 for example ) .

Did i something wrong ?

**Comment by joschi** [comment]
@lfacchinelli Which version of Elasticsearch are you running?

**Comment by lfacchinelli** [comment]
@joschi 1.7.3 , installed from elasticsearch repo (rpm)

**Comment by joschi** [comment]
@lfacchinelli Please check that the Graylog artifact or the RPM package is not corrupted. The mentioned class definitely exists in the original JAR file.

**Comment by joschi** [comment]
I can't reproduce the problem. All required class files are contained in the JAR file.
