### ISSUE TITLE
add /ping to web interface

### ISSUE THREAD

**Issue by ismaelpuerto** [Graylog2/graylog2-server#1627]
Add "/ping" to web interface for check load balancer with "200". Currently check "/" get "HTTP/1.1 303 See Other"

**Comment by bernd** [comment]
Please see our documentation for load balancer integration. There is an API endpoint for this already.
http://docs.graylog.org/en/1.3/pages/load_balancers.html

**Comment by ismaelpuerto** [comment]
This doc is for check the graylog-server, but I would like check graylog-web

**Comment by joschi** [comment]
@ismaelpuerto We're merging the Graylog web interface and Graylog server node for the Graylog 2.0.0 release, so there won't be a separate web interface anymore.
