### ISSUE TITLE
Reimplement subscriptions

### ISSUE THREAD

**Issue by infernix** [Graylog2/graylog2-server#163]
In graylog2 0.9.6, the subscription feature which consolidates a number of messages in a stream and sends them all out over email was one of the reasons for implementing graylog.

I've upgraded to 0.12.0 and have been unable to regain this functionality; the alarm callback exec plugin seems unable to do this either due to the inability to consolidate multiple messages.

It is invaluable to us, and for certain streams sending out one email per message is simply not possible due to the large number of messages that are generated when an incident occurs.

Can we have this feature back into the main code?

**Comment by infernix** [comment]
Are there still no plans to reimplement this?

**Comment by lennartkoopmann** [comment]
An email output is already scheduled and will follow soon. Compatible to Graylog v1.0 (first beta is out already)

**Comment by infernix** [comment]
I'm going over the docs but I am not seeing this yet. As far as I can tell from http://docs.graylog.org/en/latest/pages/streams.html the "Email Alert Callback
" does not aggregate multiple emails, or does it?

**Comment by florianvolle** [comment]
Closing this as this can be solved with Outputs.

Thanks!

**Comment by infernix** [comment]
@florianvolle you closed this, but can you point me towards the documentation where I can configure an output that aggregates alerts as subscriptions did in 0.9.6? I don't see it in the docs?
