### ISSUE TITLE
Time Size Optimizing rotation: hide max number of indices on ui 

### ISSUE THREAD

**Issue by kodjo-anipah** [Graylog2/graylog2-server#16307]
In case  `Time Size Optimizing` rotation strategy is selected, we should hide the `Max number of indices`  information on the general Index Set Overview page and the specific index set overview page
![image](https://github.com/Graylog2/graylog2-server/assets/98284293/4b19b90d-800a-4445-847b-bed44139a469)

**Comment by drewmiranda-gl** [comment]
I believe this is a duplicate of https://github.com/Graylog2/graylog2-server/issues/14845
