### ISSUE TITLE
Show Timefilter option in Dashboard panel

### ISSUE THREAD

**Issue by gugansankar** [Graylog2/graylog2-server#1630]
It would be great if time filter option is available in Dashboard panel. As I created demo account to my  customer and set to view only dashboards of their own details. 

Problem is ,there are unable to review the historical data. Is there any temporary work around solution available to enable timefilter in dashboard panel ?.

**Comment by jalogisch** [comment]
I would like to push this - we need the ability "time picker" in dashboards!

**Comment by elisiariocouto** [comment]
+1!

**Comment by Comradin** [comment]
I fought with the same problem, I have some large dashboards with quite a few widgets. If I could _move_ them around in in time with a global time picker element, that would be awesome. I would not have to duplicate all the the widgets for ${today, yesterday, last week, ...} which is a tiring work.

**Comment by P1eX** [comment]
+1

**Comment by Comradin** [comment]
@jalogisch is there a way to vote for this issue? Its close to its first anniversary.

**Comment by mayantec** [comment]
Yes, it would be such a great idea, please consider.!!!! +1

**Comment by zgfh** [comment]
any update?

**Comment by dennisoelkers** [comment]
This is now implemented starting with version 3.2.0.
