### ISSUE TITLE
SSL connection between server and elasticsearch

### ISSUE THREAD

**Issue by Wuuuz** [Graylog2/graylog2-server#1634]
Hi @ all,

I'm building a graylog-infrastructure and I have the problem to set up a secure connection between the elasticsearch and the graylog server. Is this possible?
Now I'm working with STunnel. So i configured 
elasticsearch_discovery_zen_ping_unicast_hosts = 127.0.0.1:9500 (my STunnel Port)
But am I right with thinking graylog-server is only discovering the elasticsearch through the STunnel and after this not over the Stunnel?
So, do anyone know a solution to set up a secure connection?

**Comment by joschi** [comment]
The Elasticsearch node embedded in Graylog needs to communicate bidirectionally with the Elasticsearch cluster, so you probably have to update the [`elasticsearch_network_publish_host `](https://github.com/Graylog2/graylog2-server/blob/1.3.0/misc/graylog2.conf#L182) setting in your Graylog configuration to a port wrapped in stunnel.

In general, please use [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or [join #graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general support questions about Graylog.
