### ISSUE TITLE
Add Keepalive on Gelf over HTTP Input

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#1637]
So this is a feature request: add the keepalive option on the Gelf over HTTP input, so the connection keeps open even if there is a firewall dropping connections between the sensors and the Graylog Server 

Thanks in advice!

**Comment by mikkolehtisalo** [comment]
The HTTP Keep-Alive is used to keep connection open for further requests. As far as I can see that is already implemented, as it you can use one TCP connection to send several messages. I tested it today on my setup with Gelf over HTTP, and it worked.

The HTTP Keep-Alive does however not by default include pinging method for keeping the firewalls from closing the inactive TCP connections. This would require either a non-related functionality called TCP keepalive which sends a special frame, or adding a special keep-alive message to the Gelf spec.

TCP keepalive can be enabled by OS [configuration](http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html) [settings](http://blogs.technet.com/b/nettracer/archive/2010/06/03/things-that-you-may-want-to-know-about-tcp-keepalives.aspx).

**Comment by bernd** [comment]
The GELF HTTP input has a keep-alive option that can be enabled. Closing this, please re-open if there is something else that we can implement that helps with your use case. Thank you!
