### ISSUE TITLE
Alerts & Events search modifies query while typing

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#16388]
## Expected Behavior

The `Alerts & Events` (`/alerts`) page does not modify the search query content.

## Current Behavior

When typing a search query in the `Alerts & Events` input multiple `POST /api/events/search` are fired off, and it seems that upon completion of those requests the content of the input is reverted to the associated `query` value.  The result is that you may be typing a word and keep seeing the last character get "deleted".

## Possible Solution

* Debounce
* Only submit the search on `Enter`
* Don't modify the input content

## Steps to Reproduce (for bugs)

1. Have a `5.1.4` environment with some alerts/events generated
2. Navigate to `/alerts`
3. Open the Network tab of your browser's dev tools
4. In the search input, start typing a long word (somewhat slowly).  As you type, note:
  a. Multiple `POST /api/events/search` get submitted as you type
  b. Upon completion of requests the content of the query input gets modified

## Context

This issue (and other issues with this specific search, e.g. #15260) make searching for alerts/events annoying.

## Your Environment

* Graylog Version: 5.1.4
* Browser version: Firefox 117, Chrome 116

**Comment by moesterheld** [comment]
I would suggest migrating the table to the new entity data table which would resolve both this issue as well as #15260
