### ISSUE TITLE
Incorrect apt repository in the Ubuntu Installation docs

### ISSUE THREAD

**Issue by yuuki0xff** [Graylog2/graylog2-server#16380]
## What?
The MongoDB section in the [Ubuntu Installation](https://go2docs.graylog.org/5-1/downloading_and_installing_graylog/ubuntu_installation.html) docs seems to be incorrect. I request to update docs.

I posted it here because I couldn't find a place to report documentation error. Please guide me if a better place exists.

## Why?
The MongoDB section in the [Ubuntu Installation](https://go2docs.graylog.org/5-1/downloading_and_installing_graylog/ubuntu_installation.html) docs instructed me to add MongoDB's apt repository for **Debian Bullseye**. It causes installation failure due to dependency problems.

Compared with Graylog's docs and MongoDB's docs, some differences exist. I think that Granlog docs should be updated to the official installation procedure of MongoDB.

```bash
# From Graylog documentation:
# Suite name is bullseye/mongodb-org/6.0. It is not suitable for the Ubuntu 22.04.
# https://go2docs.graylog.org/5-1/downloading_and_installing_graylog/ubuntu_installation.html
sudo wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/mongodb-keyring
echo "deb [signed-by=/usr/share/keyrings/mongodb-keyring] http://repo.mongodb.org/apt/debian bullseye/mongodb-org/6.0 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list

# From MongoDB documentation:
# Suite name is jammy/mongodb-org/6.0. It correct.
# https://www.mongodb.com/docs/v6.0/tutorial/install-mongodb-on-ubuntu/
curl -fsSL https://pgp.mongodb.com/server-6.0.asc | \
   sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg \
   --dearmor
echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
```

## Your Environment

* Graylog Version: Problem occurred before install Graylog.
* OpenSearch Version: Problem occurred before install OpenSearch.
* MongoDB Version: Problem occurred during installing MongoDB 6.x
* Operating System: Ubuntu 22.04
* Browser version:

**Comment by etgraylog** [comment]
I just submitted Asana request to Docs-team w/the correct instructions (scraped from https://www.mongodb.com/docs/v6.0/tutorial/install-mongodb-on-ubuntu/).

**Comment by yuuki0xff** [comment]
It seems to be fixed. Thanks.
