### ISSUE TITLE
Search result count widget not caching

### ISSUE THREAD

**Issue by boosty** [Graylog2/graylog2-server#1640]
First of all I want to say thank you for Graylog! You know that it took us a while to set it up properly for our use case at XING, but we now reached a pretty stable state :smile: 

We found one small issue when using search result count widgets: The number seems to get recalculated every minute or so, even though the cache time has been set to 3600s.

We see this not only by the number frequently changing, but also the corresponding metric ("calculations") increasing quickly.

Any ideas?

![screen shot 2015-12-17 at 18 25 59](https://cloud.githubusercontent.com/assets/4270/11876887/35a77346-a4ec-11e5-89c9-2d5c41a23d76.png)
![screen shot 2015-12-17 at 18 26 27](https://cloud.githubusercontent.com/assets/4270/11876888/35a9a42c-a4ec-11e5-8d3b-285571378b67.png)

**Comment by boosty** [comment]
Btw.: We are using 1.3.0.

**Comment by jfmarquet** [comment]
Hello,

I have the same issue with version 1.3.0, the widget cache time is configured to 3600 but it seems like there is no cache at all. The values are refreshed every time they are requested.
The same configuration was working fine with version 1.2.2. Do you have any update on this topic?
Thanks

**Comment by kroepke** [comment]
This should not have changed and is a bit weird, since all widgets run through the same cache.
However the cache is per server process, so unless you happen to hit the same server on each request, it will have to recalculate it up to the number of servers you are running.

We do not have cluster-wide caches yet.

**Comment by jfmarquet** [comment]
Hello,
Thanks for your reply. The current configuration is running on a single machine with only one graylog-server process so I don't think we face a cluster issue here. Would there be anything to check on our side, any log or info we could provide you to help finding the issue?
Thank you.

**Comment by kroepke** [comment]
In fact we have just determined that this is a bug introduced in 1.3, we will be working on a fix for this problem in a bugfix release.

**Comment by boosty** [comment]
Cool, thanks a lot!

**Comment by joschi** [comment]
Fixed by merging #1681.
