### ISSUE TITLE
Stream invalidation should be disabled by an option

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1642]
Hello,

Today, graylog have a system to protect itself when rules set on stream are too expensive to process.

When it occurs, it raise an alert like:

````
Processing of a stream has been disabled due to excessive processing time. (triggered 8 hours ago)
The processing of stream xx has taken too long for 3 times. To protect the stability of message processing, this stream has been disabled. Please correct the stream rules and reenable the stream.
````

On my infrastructure, i have a dozen graylog server nodes consumming kafka topics. One of them (of course in the middle of the night) get sick (hardrive corrupted). Handling process became a problem, and it starts to invalidate all stream because of timeout. This action penalize all cluster, other nodes were unable to route logs to appropriate streams as they were disabled by seek node.

It's probably a kind of race condition, but i think the stream invalidation as it, is very dangerous, and should be disabled by an option.

Thanks

**Comment by joschi** [comment]
The stream processing (and specifically automatically disabling streams) can be fine-tuned in the Graylog configuration file: https://github.com/Graylog2/graylog2-server/blob/1.3.2/misc/graylog2.conf#L293-L301

**Comment by pdepaepe** [comment]
I know theses settings, but please re-read my use case.
Set 3 hours timeout on it will probbaly not change the fact that my seek graylog node disable the stream for bad reason (corrupted drive) and so impact all other healthy nodes to do it's job (route logs to appropriate streams).

**Comment by joschi** [comment]
The timeout is being checked for every message. If one(!) message takes three hours to be processed by that node, you should really take it behind the barn and shoot it (that's the job of your monitoring system).
