### ISSUE TITLE
Firefox warns about missing SameSite cookie attribute

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#16428]
## Description

I see the following warning in the browser console when using Graylog with the Firefox browser.

![image](https://github.com/Graylog2/graylog2-server/assets/461/643e9ced-5253-40b3-8150-b93d05dea01b)

```
Cookie “authentication” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite”
attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in
third-party contexts. If your application depends on this cookie being available in such contexts, please add
the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute,
read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

## Steps to Reproduce (for bugs)

1. Open the browser console in Firefox and navigate to a Graylog setup
2. Check the `SameSite` warnings

## Context

To fix this issue, we need to update the Jersey dependency to at least version "3.x". Previous versions don't support setting the `SameSite` cookie attribute. See: https://github.com/jakartaee/rest/pull/868

## Your Environment

* Graylog Version: 5.1.5

**Comment by dabbabi** [comment]
Hi, please correct me if I'm wrong, I think that it will be better, in jakarta.ws.rs.core.NewCookie class, to substitute 
```
public enum SameSite {
   NONE,
   LAX,
   STRICT
}

```by 
```
public enum SameSite {
   None,
   Lax,
   Strict
}

```
