### ISSUE TITLE
/system/indices page: could not get indices.

### ISSUE THREAD

**Issue by 2fa** [Graylog2/graylog2-server#1644]
Hello.
After upgrading graylog from version 1.2.2-1 to 1.3.0-3 (bug present in 1.3.1-1 and 1.3.2-1 too) i cannot get indices information from /system/indices page.

Some information from page:

> Oh no, something went wrong!
> (You caused a org.graylog2.restclient.lib.APIException. API call failed GET  http://@x.x.x.x:12900/system/indexer/indices)
> 
> Reason: Could not get indices. We expected HTTP 200, but got a HTTP -1.

> **Stacktrace**: 
>org.graylog2.restclient.lib.ApiClientImpl$ApiRequestBuilder#execute (ApiClientImpl.java:463)
org.graylog2.restclient.models.IndexService#allIndicesInfo (IndexService.java:69)
controllers.IndicesController#index (IndicesController.java:79)
Routes$$anonfun$routes$1$$anonfun$applyOrElse$61$$anonfun$apply$631#apply (routes_routing.scala:2126)
Routes$$anonfun$routes$1$$anonfun$applyOrElse$61$$anonfun$apply$631#apply (routes_routing.scala:2126)
play.core.Router$HandlerInvokerFactory$$anon$4#resultCall (Router.scala:264)
play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1#invocation (Router.scala:255)
play.core.j.JavaAction$$anon$1#call (JavaAction.scala:55)
play.GlobalSettings$1#call (GlobalSettings.java:67)
play.mvc.Security$AuthenticatedAction#call (Security.java:44)
play.core.j.JavaAction$$anonfun$11#apply (JavaAction.scala:82)
play.core.j.JavaAction$$anonfun$11#apply (JavaAction.scala:82)
scala.concurrent.impl.Future$PromiseCompletingRunnable#liftedTree1$1 (Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable#run (Future.scala:24)
play.core.j.HttpExecutionContext$$anon$2#run (HttpExecutionContext.scala:40)
play.api.libs.iteratee.Execution$trampoline$#execute (Execution.scala:46)
play.core.j.HttpExecutionContext#execute (HttpExecutionContext.scala:32)
scala.concurrent.impl.Future$#apply (Future.scala:31)
scala.concurrent.Future$#apply (Future.scala:485)
play.core.j.JavaAction$class#apply (JavaAction.scala:82)
play.core.Router$HandlerInvokerFactory$JavaActionInvokerFactory$$anon$15$$anon$1#apply (Router.scala:252)
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5#apply (Action.scala:130)
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5#apply (Action.scala:130)
play.utils.Threads$#withContextClassLoader (Threads.scala:21)
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4#apply (Action.scala:129)
play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4#apply (Action.scala:128)
scala.Option#map (Option.scala:145)
play.api.mvc.Action$$anonfun$apply$1#apply (Action.scala:128)
play.api.mvc.Action$$anonfun$apply$1#apply (Action.scala:121)
play.api.libs.iteratee.Iteratee$$anonfun$mapM$1#apply (Iteratee.scala:483)
play.api.libs.iteratee.Iteratee$$anonfun$mapM$1#apply (Iteratee.scala:483)
play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1#apply (Iteratee.scala:519)
play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1#apply (Iteratee.scala:519)
play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14#apply (Iteratee.scala:496)
play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14#apply (Iteratee.scala:496)
scala.concurrent.impl.Future$PromiseCompletingRunnable#liftedTree1$1 (Future.scala:24)
scala.concurrent.impl.Future$PromiseCompletingRunnable#run (Future.scala:24)
akka.dispatch.TaskInvocation#run (AbstractDispatcher.scala:41)
akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask#exec (AbstractDispatcher.scala:393)
scala.concurrent.forkjoin.ForkJoinTask#doExec (ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue#runTask (ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool#runWorker (ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread#run (ForkJoinWorkerThread.java:107)

> **Request information**
**Method**
GET
**Query**
**Upgrade-Insecure-Requests**
1
**Referer**
http://x.x.x.x:9000/system/indices
**Connection**
keep-alive
**Accept**
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
**Accept-Language**
en-US,en;q=0.8,ru;q=0.6
**Accept-Encoding**
gzip, deflate, sdch
**User-Agent**
Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
**Host**
x.x.x.x:9000

**System information**:
>**Linux**:
Linux rainbow1-23 3.19.0-26-generic #28~14.04.1-Ubuntu SMP Wed Aug 12 14:09:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
**Java**:
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
**MongoDB**:
db version v3.0.8
git version: 83d8cc25e00e42856924d84e220fbe4a839e605d
**Affected graylog versions**:
1.3.0-1, 1.3.1-1, 1.3.2-1

In our ElasticSearch we have 400 indices, 24GB each, so i think that problem lies with it.
I can get indices by API call, it takes long time (about 12 seconds), but it works (i actually think that it is problem with timeout settings on web interface (5 seconds?))

**From /system/indexer/indices API call**:
>**Response Code**
200
**Response Headers**
{"X-Graylog-Node-Id":"7f9f62e8-3fa7-4a12-9f98-0db7160e0284","X-Runtime-Microseconds":"12254050","Transfer-Encoding":"chunked","Content-Type":"application/json"}

**Comment by 2fa** [comment]
I think i'm found the issue:
`allIndicesInfo()` tries to execute API call to */system/indexer/indices*, but doesn't set operation timeout, which by default is 5 second (from graylog2.restclient.lib.Configuration):
`private static final Integer DEFAULT_TIMEOUT = 5;`

Here's implementation:

```javascript
public Map<String, IndexInfo> allIndicesInfo() throws APIException, IOException {
        final AllIndicesInfo allIndicesInfo = api.path(routes.IndicesResource().all(), AllIndicesInfo.class).execute();

        return ImmutableMap.copyOf(allIndicesInfo.indices());
    }
```

Possible solution:

```javascript
public Map<String, IndexInfo> allIndicesInfo() throws APIException, IOException {
        final AllIndicesInfo allIndicesInfo = api.path(routes.IndicesResource().all(), AllIndicesInfo.class)
                                               .timeout(apiTimeout("all_indices_info", 30, TimeUnit.SECONDS))
                                               .execute();

        return ImmutableMap.copyOf(allIndicesInfo.indices());
    }
```

**IndicesController** also must be fixed:

```javascript
public Result index() {
        BreadcrumbList bc = new BreadcrumbList();
        bc.addCrumb("System", routes.SystemController.index(0));
        bc.addCrumb("Indices", routes.IndicesController.index());

        try {
            ESClusterHealth clusterHealth = clusterService.getESClusterHealth();
            DeflectorInformationResponse deflector;
            DeflectorConfigResponse deflectorConfig;
            ClosedIndicesResponse closedIndices;
            ClosedIndicesResponse reopenedIndices;
            Map<String, IndexInfo> allIndicesInfo;
            try {
                deflector = indexService.getDeflectorInfo();
                deflectorConfig = indexService.getDeflectorConfig();
                closedIndices = indexService.getClosedIndices();
                reopenedIndices = indexService.getReopenedIndices();
                allIndicesInfo = indexService.allIndicesInfo();
            } catch (APIException e) {
                if (Tools.rootCause(e) instanceof TimeoutException) {
                    return ok(views.html.system.indices.index_cluster_unavailable.render(
                            currentUser(),
                            bc,
                            clusterHealth
                    ));
                }
                throw e;
            }

            final HashSet<String> reopenedSet = Sets.newHashSet(reopenedIndices.indices);

            return ok(views.html.system.indices.index.render(
                    currentUser(),
                    bc,
                    indexService.all(),
                    allIndicesInfo,
                    closedIndices.indices,
                    reopenedSet,
                    clusterHealth,
                    deflector.currentTarget,
                    deflectorConfig
            ));
        } catch (Graylog2ServerUnavailableException e) {
            return ok(views.html.system.indices.index_cluster_unavailable.render(
                    currentUser(),
                    bc,
                    null
            ));
        } catch (APIException e) {
            String message = "Could not get indices. We expected HTTP 200, but got a HTTP " + e.getHttpCode() + ".";
            return status(504, views.html.errors.error.render(message, e, request()));
        } catch (IOException e) {
            return status(504, views.html.errors.error.render(ApiClient.ERROR_MSG_IO, e, request()));
        }
    }
```

Here I dragged `allIndicesInfo()` into inner 'try' block, so it should be catched with TimeoutException and return appropriate view:

```javascript
return ok(views.html.system.indices.index_cluster_unavailable.render(
                            currentUser(),
                            bc,
                            clusterHealth
                    ));
```

I hope this will help.

**Comment by jandoe88** [comment]
There is a (maybe new) Parameter in /etc/graylog/web/web.conf
> # Global timeout for communication with Graylog server nodes; default: 5s
> #timeout.DEFAULT=5s

Changed it to 10s and now it works.

**Comment by 2fa** [comment]
How did i missed it... (it's hidden and not presented in web.conf by default, at least in mine, but nevertheless)

```
timeout.DEFAULT=15s
```
did the trick
@jandoe88, thanks a lot!
