### ISSUE TITLE
GROK extractor COMMONAPACHELOG overrides timestamp with incompatible value

### ISSUE THREAD

**Issue by mishak87** [Graylog2/graylog2-server#1647]
GROK `${COMMONAPACHELOG}` overrides `timestamp` field with badly formatted value resulting in an error.

`Graylog 2.0.0-20151217162713`

``` json
{"request":"/","MONTH":"Dec","agent":"curl/7.38.0","COMMONAPACHELOG":"172.17.0.6 - - [22/Dec/2015:14:51:51 +0000] \"GET / HTTP/1.1\" 403 381","docker_name":"/clever_blackwell","HOUR":"14","auth":"-","gl2_remote_ip":"10.42.19.191","ident":"-","gl2_remote_port":36239,"BASE10NUM":"381","source":"2e9bc6ef2102","gl2_source_input":"5679495ce4b04887915b4780","INT":"+0000","YEAR":"2015","clientip":"172.17.0.6","COMBINEDAPACHELOG":"172.17.0.6 - - [22/Dec/2015:14:51:51 +0000] \"GET / HTTP/1.1\" 403 381 \"-\" \"curl/7.38.0\"","USERNAME":"-","gl2_source_node":"f65bd405-369c-47f2-9432-0b86cb740c05","MINUTE":"51",
"timestamp":"22/Dec/2015:14:51:51 +0000",
"IP":"172.17.0.6","IPV4":"172.17.0.6","streams":[],"verb":"GET","TIME":"14:51:51","message":"172.17.0.6 - - [22/Dec/2015:14:51:51 +0000] \"GET / HTTP/1.1\" 403 381 \"-\" \"curl/7.38.0\"","USER":"-","version":"1.1","referrer":"-","docker_container":"0621eb14e4bd3e3e2e76080436baf63a6a2cfccffccc302f0c72e8114d4f0c3d","bytes":"381","response":"403","SECOND":"51","httpversion":"1.1","QUOTEDSTRING":"curl/7.38.0","MONTHDAY":"22","docker_image":"php:5.6-apache"}
```

`ES 2.1`

```
failed to parse [timestamp]]; nested: IllegalArgumentException[Invalid format: "22/Dec/2015:14:51:51 +0000" is malformed at "/Dec/2015:14:51:51 +0000"
```

**Comment by joschi** [comment]
This also happens in Graylog 1.3.x since the grok pattern `HTTPDATE` (https://github.com/Graylog2/graylog2-server/blob/1.3.2/misc/contentpacks/grok-patterns.json#L274-L277) tries to store a malformed string in the "timestamp" field.

**Comment by fobalili** [comment]
Quick fix for the impatient, I modified COMMONAPACHELOG to include timestamp format that parses without errors:

%{IPORHOST:clientip} %{HTTPDUSER:ident} %{USER:auth} \[%{HTTPDATE:timestamp;date;dd/MMM/yyyy:HH:mm:ss Z}\] "(?:%{WORD:verb} %{NOTSPACE:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-)

**Comment by juiceman84** [comment]
Consider me impatient!  Fobalili's fix worked for me.  After modifying the grok pattern for %{commonapachelog} pattern, my apache logs were indexed properly into graylog.

Thanks for the quick fix fobalili!

**Comment by bronius** [comment]
Hi - I think I'm experiencing the same issue, but the recommended "impatient" fix didn't seem to do it for me.  As I understand it, with the fix or with latest version, I should be able to use either the common or combined apache grok pattern, and the extracted timestamp in the apache log should be used in place of Log Time on the record.

I see that in the "get recent message" extractor manager interface, the parsed date fields are correct (parsed from the log message), and the timestamp at the bottom of that interface also reflects the same date.  However, in the messages stream, the application logged timestamp is parsed correctly for the date fields, but the Log Time timestamp is still the moment I've logged the message.

Am I misunderstanding expectations?  Doing something incorrectly?

I'm on Graylog v2.3.1+9f2c6ef according to the Help.
