### ISSUE TITLE
graylog output from stream using tls to other graylog node fails

### ISSUE THREAD

**Issue by deanilenko** [Graylog2/graylog2-server#1651]
Hello!
Does anyone use this feature? Because i tried use self-signed and normal certifications and keys in different options, like:
- certifications PEM/DER/PKCS#7;
- keys PKCS#8/PKCS#12;
- trusted key chain PEM/DER/PKCS#7.
And in every option I had an error WARN  [AbstractNioSelector] Failed to initialize an accepted socket.
java.io.IOException: overrun, bytes = 1196 with different count of bytes. 

graylog-server version: 1.2.2
java on 1st node:
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

java on 2nd node:
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.2) (7u65-2.5.2-3~14.04)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

Help me, please, to solve this problem!

**Comment by joschi** [comment]
What's the exact configuration of the GELF Output?

**Comment by deanilenko** [comment]
hostname: domain_name_of_main_node
protocol: TCP
connect_timeout: 1000
reconnect_delay: 500
port: 12203
tcp_no_delay: false
tcp_keep_alive: false
tls_trust_cert_chain: /etc/graylog/server/cert_own/ca-bundle.pem
tls_verification_enabled: true

where ca-bundle.pem is chain of client cert, server cert, root cert. it looks like this:

-----BEGIN CERTIFICATE----- 
( Client certificate) 
-----END CERTIFICATE----- 
-----BEGIN CERTIFICATE----- 
( Intermediate certificate) 
-----END CERTIFICATE----- 
-----BEGIN CERTIFICATE----- 
( Root certificate) 
-----END CERTIFICATE-----

is it correct? or i`ve done mistakes?

**Comment by joschi** [comment]
@deanilenko The protocol needs to be `TCP+TLS` in order to use the encrypted transport.

**Comment by deanilenko** [comment]
Ok, thanks for help! But after protocol was changed to TCP+TLS i had the same issue...

configuration of OUTPUT:


hostname:  domain_name_of_main_node
protocol: TCP+TLS
connect_timeout: 1000
reconnect_delay: 500
port: 12203
tcp_no_delay: false
tcp_keep_alive: false
tls_trust_cert_chain: /etc/graylog/server/cert_own/ca-bundle.pem
tls_verification_enabled: false

INPUT:

logsFrom********** (GELF TCP) running
On node  *******************************

port: 12203
tls_enable: true
tls_client_auth: disabled
override_source:
bind_address: 0.0.0.0
use_null_delimiter: true
tls_cert_file: /etc/graylog/server/cert_own/server.pem
tls_client_auth_cert_file:
recv_buffer_size: 1048576
tls_key_password: *******
max_message_size: 2097152
tls_key_file: /etc/graylog/server/cert_own/server.key.p8

any suggestion?

**Comment by joschi** [comment]
@deanilenko Please post your problem and the relevant information to [the mailing list](https://groups.google.com/forum/#!forum/graylog2).
