### ISSUE TITLE
alert on multiple conditions/fields

### ISSUE THREAD

**Issue by ovadm** [Graylog2/graylog2-server#1652]
hi,

I want to create a rule that will look into combination of few cisco switch ip addresses and specific ports for each switch address. something like:

switch_ip=1.1.1.1 and port=e100/1/5 (rule1)
OR
switch_ip=121.2.2 and port=e111/2/3 OR e2/2 (rule2)
OR...

The problem is that ip address is a different field from the port and I don't know how to combine them together. something like: Filed=gl_remote_ip OR switch_interface (which already extracted)

though I can create multiple streams I prefer not doing so because they all related to specific alert

Thanks,
Ovad

**Comment by florianvolle** [comment]
We think this can be solved using pipelines. 
Please reopen if this is not helping.

Thanks!
