### ISSUE TITLE
Title text in new warnings style is hard to read

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#16521]
## Description

The new warning style makes the title text in a warning hard to read.

![image](https://github.com/Graylog2/graylog2-server/assets/461/e4154f0b-c068-458e-84c6-f1bac5c2e4cf)

## Your Environment

* Graylog Version: 5.2.0-SNAPSHOT (rev cc3a8bb)

**Comment by mpfz0r** [comment]
similar issue on the systems overview page in dark mode

![image](https://github.com/Graylog2/graylog2-server/assets/3034831/af2c71b4-01ee-40e6-b2c4-63914b4260de)
