### ISSUE TITLE
Web UI: Make contents of imported content packs inspectable

### ISSUE THREAD

**Issue by 2ion** [Graylog2/graylog2-server#1653]
Expanding on https://github.com/Graylog2/graylog2-web-interface/issues/1396.

As of 1.3, there is no way to inspect the contents of an imported content pack other than looking at its title/description/source code which makes managing them unnecessary tedious.

I suggest to display a tree representation or similar of all contained inputs, outputs, streams, etc.

**Comment by bernd** [comment]
This will be in the upcoming 3.0 release. Closing this issue now.
