### ISSUE TITLE
Web UI: Dependency tracking for Grok patterns

### ISSUE THREAD

**Issue by 2ion** [Graylog2/graylog2-server#1654]
An aspect of https://github.com/Graylog2/graylog2-web-interface/issues/1396 but goes further. Reporting against 1.3.
- Grok patterns used in the extractor chains of a given input should be automatically selected when the input is selected to be included into a content pack.
- Warn when deleting or block the deletion of named Grok patterns from the library when they are used in a Grok extractor pattern.
- When using a named Grok pattern in an extractor definition, check if it is present in the library and if not, prompt for its creation.

Implementing the above suggestions would make working with Grok patterns, as they are scattered over all kinds of different inputs, much more simpler and convenient.

**Comment by kmerz** [comment]
Fixed with Content Pack re-write.
