### ISSUE TITLE
Web UI: Improve UI for pattern composition

### ISSUE THREAD

**Issue by 2ion** [Graylog2/graylog2-server#1655]
Reporting against 1.3.

Obviously, when creating complex Grok or regex patterns, a single-line input of limited width even on large screens, no wrapping, which uses a proportional font cannot be considered optimal or even usable -- I tend to write 2500-character Grok patterns in an external editor rather than the single line input.

I suggest to rework editor/input component of extractors where it is relevant, for example the regex and Grok extractors.

**Comment by kmerz** [comment]
Fixed by https://github.com/Graylog2/graylog2-server/pull/4809
