### ISSUE TITLE
Grok extractor: Support flexdate for timestamp conversion

### ISSUE THREAD

**Issue by 2ion** [Graylog2/graylog2-server#1656]
Reporting against 1.3.

I am parsing a timestamp from a log message which is missing the year as documented [here](http://docs.graylog.org/en/1.3/pages/extractors.html#using-grok-patterns-to-extract-data),
think:

```
%{PATTERN:timestamp;date;MMM' 'dd' 'HH:mm:ss.SSS}
```

The resulting timestamp has the year set to 1970. In order to fix this, I am passing this through an additional `copy input` extractor with attached `flexdate` converter.

It would be nice if either the implicit date conversion in Grok would assume the current year if the year has not been specified, or if Graylog would support running the Grok capture through flexdate if the current behaviour is actually desired, e.g.

```
%{PATTERN:timestamp;flexdate}
```

**Comment by florianvolle** [comment]
We think this can be solved using pipelines. http://docs.graylog.org/en/2.1/pages/pipelines/pipelines.html?

Please reopen if this is not working. 
Thanks!
