### ISSUE TITLE
Field Value Condition Alert, does not permit decimal values.

### ISSUE THREAD

**Issue by leftyb** [Graylog2/graylog2-server#1657]
When I try to set an "Field Value Condition", alert using a decimal value, an error notice appears, that the only possible values are 0 or 1. Meaning that only integer values can be set, but the field that I want to monitor and trigger an alert, is a double field between 0.0,1.0. I need to set a threshold 0.7 value to trigger an alert if exceeded  but not possible.

Thank you.

**Comment by leftyb** [comment]
Hi @joschi 

Is it possible to add this issue at the latest milestone please.

Thank you.

**Comment by joschi** [comment]
Fixed in Graylog2/graylog2-web-interface@f2008386d2cbb8cc098b586023f0f8d0d31f7d9d
