### ISSUE TITLE
/system/deflector not accessible by user with Reader role

### ISSUE THREAD

**Issue by madchap** [Graylog2/graylog2-server#1659]
Hello,

While writing a zabbix monitoring template, I realized that the /system/deflector endpoint was not readable by a user with "Reader" role; getting a 401 Unauthorized error. It works well however when logging in with an admin user.

Should not this endpoint be accessible to a "Reader" user like the other endpoints?

Thank you.
Best and thanks for the great software.

**Comment by joschi** [comment]
> Should not this endpoint be accessible to a "Reader" user like the other endpoints?

No, since this is clearly system-level information (with a GET request) and can trigger system-level actions (with a POST request). I don't see why a normal user (having the "Reader" role) should ever access that information.

**Comment by madchap** [comment]
I would clearly agree on the POST part definitely. I can GET /system/jobs with a Reader user or /system/inputs which both have associated POST endpoints, yet they work. Could you please explain the difference? Thank you for your time.

**Comment by joschi** [comment]
@madchap The "Reader" role is intended to be applied to users which should only be able to read log messages (i. e. have access to one or more streams and be able to run search queries on them). Having access to system-level information (i. e. inputs, running jobs, deflector information) is not in the scope of this role.

Would you mind to elaborate on your specific use case?

**Comment by madchap** [comment]
Sure. I have recently worked on a zabbix monitoring template -- https://github.com/madchap/graylog2-zabbix, and to monitor all >30 items at the moment, all I needed was a "monitoring" user with the Reader role. The only issue I faced was for the /system/deflector.
