### ISSUE TITLE
Quick Values does not display all the details in the widget

### ISSUE THREAD

**Issue by HSVK** [Graylog2/graylog2-server#1661]
Hi, 
When we use the Quick values in the widget, it displays only about 50 items in the value the rest of the details are not shown, when the search query is changed ignoring few patterns of the current values, we get to see the rest of the missing items. 
Does the Widget has the limitations to display only 49 to 50 entries or is there a setting to change it. Please assist.

Thanks, Hema

**Comment by edmundoa** [comment]
Hi,

We limit the number of quick values to 50 in the code, as it is an expensive calculation when there are many logs or many different values for the field. I'd recommend using restrictive searches to limit the number of results and then calculate quick values over the interesting fields.

We use Github for bug tracking, kindly ask in our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or [#graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for further questions about this.

**Comment by HSVK** [comment]
Hi Edmundoa, 
  Can they be made customized, by providing the option in the graylog web/server conf file.  

https://groups.google.com/forum/#!topic/graylog2/7ErGpm0IkpM

Thanks, Hema.

**Comment by edmundoa** [comment]
Hi Hema,

Sure, I created the linked issue to make it a bit cleaner, please track its progress to know when the feature is coming :)
