### ISSUE TITLE
LDAP settings with multiple instances failed

### ISSUE THREAD

**Issue by Dainii** [Graylog2/graylog2-server#1662]
I have a configuration with 1 graylog web server, 2 server and 2 elasticsearch node

I have configured LDAP settings with the web interface. I check the configuration, all works well. But a strange thing is when I go back on "Configure LDAP" sometimes I have the settings I set but sometimes I have nothing. Same thing when I try to log in the web interface, sometimes it works, sometimes not. 

I have check my LDAP log and I have seen that the ldap request is sent by the server node and not the web one. So I think my second server node don't have the settings for LDAP authentication. I have tried an "sudo graylog-ctl reconfigure", but it doen't work.

My master node is the server node with the working configuration for ldap (I have seen his IP address in my LDAP server logs).

I doesn't find anything about that in the documentation. Have I missed something in my configuration ?

Thx a lot

**Comment by joschi** [comment]
Make sure that both Graylog server nodes are using the exact same `password_secret` (which is being used to encrypt the LDAP settings in MongoDB).

**Comment by Dainii** [comment]
thx, it was that ;)

So the ldap authentication request is randomly send by one of the server node ?

**Comment by joschi** [comment]
> So the ldap authentication request is randomly send by one server who run the server role ?

The web interface sends requests to the configured backends in a round-robin fashion.

**Comment by Dainii** [comment]
Ok thx a lot for the information ;)
