### ISSUE TITLE
Can we change/add the type of "Static fields" to numeric ?

### ISSUE THREAD

**Issue by lxf1992521** [Graylog2/graylog2-server#1664]
I find the type of "Static fields" in input is strings, even if  you set it's value to "1".

so can we change this behavior toautomatic translator or give us a button to change it manually ?

please have a look.

**Comment by florianvolle** [comment]
We are not planning to implement this. Please try using a pipeline http://docs.graylog.org/en/2.1/pages/pipelines/pipelines.html?
