### ISSUE TITLE
Email transport to support self-signed TLS certs

### ISSUE THREAD

**Issue by aberenyi** [Graylog2/graylog2-server#1668]
Hi,

This is more like a feature request. It would be nice to have an option in `server.conf` alongside with `transport_email_use_tls = true` that will allow one to use self-signed TLS certs, e.g. `transport_email_tls_self_signed_okay = true`.

Currently an exception is thrown
`Caused by: javax.mail.MessagingException: Could not convert socket to TLS; nested exception is:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

If there is any workaround I'd be thrilled to know.

Cheers

**Comment by mikkolehtisalo** [comment]
IMHO this should be WONTFIX, because a switch for allowing all unchecked CAs would be somewhat dangerous. Instead should add the self-signed certificates as *trusted CAs* like suggested in the documentation proposal.

It is not a much of an issue as long as the behavior is documented somewhere.

**Comment by florianvolle** [comment]
We agree with @mikkolehtisalo hence I am closing this issue.
