### ISSUE TITLE
How to set classpath when starting graylog2-server?

### ISSUE THREAD

**Issue by quantonganh** [Graylog2/graylog2-server#1670]
I'm trying to use [raven-log4j](https://github.com/getsentry/raven-java/tree/master/raven-log4j) to send GL2's exception to the Sentry.

The problem is I got the following error when starting GL2:

```
graylog-server-upstart: log4j:ERROR Could not create an Appender. Reported error follows.
graylog-server-upstart: java.lang.ClassNotFoundException: net.kencochrane.raven.log4j.SentryAppender
```

Looking at the upstart file:

```
  exec $GRAYLOG_COMMAND_WRAPPER ${JAVA:=/usr/bin/java} $GRAYLOG_SERVER_JAVA_OPTS \
    -jar -Dlog4j.configuration=file:///etc/graylog/server/log4j.xml \
    -Djava.library.path=/usr/share/graylog-server/lib/sigar \
    /usr/share/graylog-server/graylog.jar server -f /etc/graylog/server/server.conf -np \
    $GRAYLOG_SERVER_ARGS
```

So, it uses `-jar` and we cannot specify a classpath using `-cp` (all *.jar files in `/usr/share/graylog-server/lib` are ignored).

The first thing I tried:

`java -cp /usr/share/graylog-server/graylog.jar:/usr/share/graylog-server/lib/*:/usr/share/graylog-server/lib/sigar/* org.graylog2.bootstrap.Main`

```
usage: graylog <command> [<args>]

The most commonly used graylog commands are:
    help      Display help information
    journal   Manage the persisted message journal
    radio     Start the Graylog radio
    server    Start the Graylog server
    version   Show the Graylog and JVM versions

See 'graylog help <command>' for more information on a specific command.
```

the second:

```
java -cp '/usr/share/graylog-server/graylog.jar server -f /etc/graylog/server/server.conf':/usr/share/graylog-server/lib/*:/usr/share/graylog-server/lib/sigar/* org.graylog2.bootstrap.Main
Error: Could not find or load main class org.graylog2.bootstrap.Main
```

So, I have 2 questions:

1. How to specify the options for .jar file? (`server -f /etc/graylog/server/server.conf`)
2. Why it cannot find or load the main class? Is it a correct name? How to determine?

**Comment by bclermont** [comment]
@quantonganh as you can't use both `jar` and `-cp` together, just invoke GL2 server with only `-cp`.

Instead of use `java jar /usr/share/graylog-server/graylog.jar` you can use `java -cp /usr/share/graylog-server/graylog.jar org.graylog2.bootstrap.Main`

in your case, to include that `lib` directory you can simply: `java -cp "/usr/share/graylog-server/lib/*:/usr/share/graylog-server/graylog.jar" org.graylog2.bootstrap.Main`

**Comment by quantonganh** [comment]
@bclermont OK, thanks.

The problem is we cannot specify the `.jar` options like this:

```
java -cp '/usr/share/graylog-server/graylog.jar server -f /etc/graylog/server/server.conf':...
```

We have to move it to the end, after the main class:

```
java -cp /usr/share/graylog-server/graylog.jar:/usr/share/graylog-server/lib/*:/usr/share/graylog-server/lib/sigar org.graylog2.bootstrap.Main server -f /etc/graylog/server/server.conf
```

And now it's working fine:

```
Jan  7 04:49:14 u142 graylog-server-upstart: log4j: Class name: [net.kencochrane.raven.log4j.SentryAppender]
Jan  7 04:49:14 u142 graylog-server-upstart: log4j: Setting property [dsn] to [{PROTOCOL}://{PUBLIC_KEY}:{SECRET_KEY}@{HOST}/{PATH}{PROJECT_ID}].
Jan  7 04:49:14 u142 graylog-server-upstart: log4j: Setting property [levelMin] to [WARN].
Jan  7 04:49:14 u142 graylog-server-upstart: log4j: Adding filter of type [class org.apache.log4j.varia.LevelRangeFilter] to appender named [sentry].
Jan  7 04:49:14 u142 graylog-server-upstart: log4j: Adding appender named [sentry] to category [root].
```
