### ISSUE TITLE
Import to eclipse

### ISSUE THREAD

**Issue by githubusing** [Graylog2/graylog2-server#1671]
I have two problems
+when I download source code I don't see web-interface,when I checkout,I can see it
+How to import source code to eclipse to customize UI login form

**Comment by edmundoa** [comment]
Hi,

We use Github for bug tracking, so I kindly ask you to use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or [#graylog on Freenode](https://webchat.freenode.net/?channels=%23graylog) for general questions about Graylog.

Thank you
