### ISSUE TITLE
Search with absolute-time shows no message, relative shows them

### ISSUE THREAD

**Issue by renapu** [Graylog2/graylog2-server#1672]
Hi,

When i perform a search with absolute time-stamps it shows a found messages value but didn't display anything. Only with relative time-stamps i get the messages.

It looks like i can only get the messages out of the last closed index.
http://i.imgur.com/6AnvTF6.png http://i.imgur.com/v1EXGhT.png

System:
Graylog 1.3.2 (e7c49b6) (Hansa)

**Comment by joschi** [comment]
@renapu Could you please post the list of used indices for both query types?

**Comment by renapu** [comment]
relative 1d : graylog_175, graylog_186, graylog_185
absolute 2016-01-06 00:00:00.000 +01:00 - 2016-01-07 09:31:00.000 +01:00 : graylog_175, graylog_184, graylog_185

**Comment by joschi** [comment]
@renapu Thanks! Could you additionally please provide the calculated index ranges for those indices? You can retrieve that information from MongoDB with the following commands in the [MongoDB shell](https://docs.mongodb.org/getting-started/shell/client/):
```
# mongo
> use graylog
switched to db graylog
> db.index_ranges.find({"index_name":"graylog_175"})
> db.index_ranges.find({"index_name":"graylog_184"})
> db.index_ranges.find({"index_name":"graylog_185"})
> db.index_ranges.find({"index_name":"graylog_186"})
```

**Comment by renapu** [comment]
Is the Mongo shell normally installed? bcs i don't want to install additionally 100MB with apt-get install mongo-clients

**Comment by joschi** [comment]
@renapu If you have a running MongoDB instance on the system, the MongoDB shell should be installed with it.
