### ISSUE TITLE
Index display and search failure since New-Year

### ISSUE THREAD

**Issue by renapu** [Graylog2/graylog2-server#1673]
Hi,

after the new-year we encountered a display and search problem with our indices:

first the text is wrong: http://i.imgur.com/odZiUME.png
secondly: every search, even "last 5 minutes" hits the old index: http://i.imgur.com/ebzx5qE.png

System:
Graylog 1.3.2 (e7c49b6) (Hansa)
Index rotation: time-based 24h

**Comment by joschi** [comment]
@renapu Are you sure that "graylog_175" doesn't contain a message with a "broken" timestamp, i. e. which was dated in the future?

You can check this by running the following curl command (replace "localhost" with the actual hostname or IP address of one of your Elasticsearch nodes):
```
# curl -d '{"aggregations":{"min":{"min":{"field":"timestamp"}},"max":{"max":{"field": "timestamp"}}}}' http://localhost:9200/graylog_175/_search?pretty
```

**Comment by renapu** [comment]
Hi,

i get some messages with this curl command, but the timestamps are always around 2015-12-31 08:07:44  until 2015-12-31 08:08:44

**Comment by joschi** [comment]
@renapu Please post the output of the curl command (or at least the last part with the result of the aggregations "min" and "max").

**Comment by renapu** [comment]
OH, ok in the aggregations is the future date.... sry!

how can i fix it?

 "aggregations" : {
    "min" : {
      "value" : 1.420066801E12,
      "value_as_string" : "2014-12-31 23:00:01.000"
    },
    "max" : {
      "value" : 1.483225196E12,
      "value_as_string" : "2016-12-31 22:59:56.000"
    }
  }
}

**Comment by joschi** [comment]
So as far as I see that's not a bug in Graylog but the messages you've received simply contained vastly different timestamps (with a span of roughly 2 years). So the information about the index range is completely correct.

You can't really "fix" this as there's nothing (obviously) broken. There was simply some producer which sent in messages with probably incorrect timestamps. This can have many reasons, from bugs in the client software up to wrong system clocks on the host machines.
