### ISSUE TITLE
RestPermissions.READER_BASE_PERMISSIONS should be configurable

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1674]
Hello,

Permissions for Reader role chosen as default are for me a problem.

Two isolation concerns:
- fieldnames:read: which allow to toggle all fields.
- savedsearches:\* which allow to see globally all saved searches

"Hacking" mongo document to set read_only flag to true, changing permissions on "Reader" through the API works until next Graylog restart due to:

https://github.com/Graylog2/graylog2-server/blob/2da26f446e6f099f3c505d1d10df5885a379bcc4/graylog2-server/src/main/java/org/graylog2/users/RoleServiceImpl.java#L84

Removing "Reader role" membership to someone works until next sign in, which check/set Reader.

For me, read_only flag on Reader role should be a server.conf option, with appropriate warns about this.

Thanks

**Comment by florianvolle** [comment]
Closing this as there is a workaround by creating a user role for this. Please take a look at our documentation http://docs.graylog.org/en/2.1/pages/users_and_roles/system_users.html?
