### ISSUE TITLE
Weak encryption schemes used with the session cookie

### ISSUE THREAD

**Issue by Shmes1978** [Graylog2/graylog2-server#1675]
Graylog uses a combined authentication and session cookie scheme from the Play network.

For the sessionid part only 16 first characters of application.server is used as key. For instance with the default virtual machine appliance this automatically generated password is a hexadecimal string. 16^16 possible combinations equals roughly 2^64. In short, the key used for AES-128 has commonly only 64-bits of entropy. This is a bad practice. 

Situation is slightly better if someone uses a better scheme with larger character space for generating the password, but the real problem is not using the whole length. Instead that password should be probably fed into some hash function like PBKDF2 or BCRYPT to utilize the whole length and its entropy.

The use of ECB in encrypting the contents of the cookie is a mortal sin. The contents flow usually to 3 blocks, causing the security issues related with the ECB realize.

The encryption algorithms used (AES-128, HMAC-SHA1) do not conform to present federal encryption guidelines. It would be advisable to bump these to at least AES-256 and HMAC-SHA512.

This may be blocker level issue for companies and govt organizations that have encryption guidelines in place.

**Comment by bernd** [comment]
The cookie encryption will change in Graylog 2.0 because the old web interface is gone. We will check this in the new web interface. Thank you!

**Comment by kroepke** [comment]
This functionality is completely gone in 2.0 and we will not be releasing any more feature versions of 1.3.

I'll close this issue.

Thanks!
