### ISSUE TITLE
Could not apply extractor [..] NullPointerException

### ISSUE THREAD

**Issue by nilsmeyer** [Graylog2/graylog2-server#1676]
For an input I have the following extractor:
<img width="741" alt="screen shot 2016-01-07 at 16 09 46" src="https://cloud.githubusercontent.com/assets/3716250/12173787/23e43b3a-b559-11e5-888b-a101c1071edf.png">

A certain message then causes a NullPointerException:
>2016-01-07T15:58:34.489+01:00 ERROR [ExtractorFilter] Could not apply extractor ctxt_response extractor (id=795f7120-b48b-11e5-a7f3-00163e97248b)
>java.lang.NullPointerException
>	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
>	at com.google.common.base.Joiner.toString(Joiner.java:433)
>	at com.google.common.base.Joiner$MapJoiner.appendTo(Joiner.java:365)
>	at com.google.common.base.Joiner$MapJoiner.appendTo(Joiner.java:393)
>	at com.google.common.base.Joiner$MapJoiner.join(Joiner.java:419)
>	at com.google.common.base.Joiner$MapJoiner.join(Joiner.java:408)
>	at com.google.common.base.Joiner$MapJoiner.join(Joiner.java:330)
>	at org.graylog2.inputs.extractors.JsonExtractor.parseValue(JsonExtractor.java:121)
>	at org.graylog2.inputs.extractors.JsonExtractor.extractJson(JsonExtractor.java:104)
>	at org.graylog2.inputs.extractors.JsonExtractor.run(JsonExtractor.java:81)
>	at org.graylog2.plugin.inputs.Extractor.runExtractor(Extractor.java:191)
>	at org.graylog2.filters.ExtractorFilter.filter(ExtractorFilter.java:62)
>	at org.graylog2.buffers.processors.ServerProcessBufferProcessor.handleMessage(ServerProcessBufferProcessor.java:97)
>	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.dispatchMessage(ProcessBufferProcessor.java:82)
>	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:61)
>	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:35)
>	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:138)
>	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
>	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>	at java.lang.Thread.run(Thread.java:745)

Unfortunately I don't know what the data in ctxt_response looks like. The aforequoted message repeats a few times every seconds and the journal is filling up with entries.

**Comment by joschi** [comment]
Fixed in #1677.
