### ISSUE TITLE
graylog_host variable not used in Ready-to-use sidecar configurations

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#16804]
While reviewing [Ready-to-use sidecar configurations](https://github.com/Graylog2/graylog2-server/pull/15571) Joel noticed that the `hosts` value is hardcoded to `192.168.1.1:5044` instead of `${user.graylog_host}:5044`

This appears to be the case for all Ready-to-use sidecar configurations except `auditbeat-linux-default`

**Comment by drewmiranda-gl** [comment]
A but confused at this one. Latest snapshot on a fresh install does NOT have this issue yet success.secdev.torch.sh does have this issue 🤔

**Comment by kodjo-anipah** [comment]
@drewmiranda-gl this change was added with 5.2.0 any chance that success.secdev.torch.sh was running on an older version?

**Comment by drewmiranda-gl** [comment]
its possible. i think we can close this for now.

**Comment by kodjo-anipah** [comment]
🤝
