### ISSUE TITLE
Sidecars System Configuration Update interval Failure

### ISSUE THREAD

**Issue by gally47** [Graylog2/graylog2-server#16829]
![Screenshot 2023-10-05 at 11 40 29](https://github.com/Graylog2/graylog2-server/assets/106236152/068f7a59-f0d5-4f31-b1f4-675f9dde5225)

## Expected Behavior

- No Default Field Error for Update interval
- Changes to Update interval Field should be saved on update configuration click

## Current Behavior

- Persistent Error in Update interval Field
- Changes to Update interval Field are not saved on update configuration click

## Steps to Reproduce (for bugs)

1. go to /system/configurations/Sidecars
2. click edit configuration

## Your Environment

* Graylog Version: Graylog 5.2.0

**Comment by patrickmann** [comment]
This is because we are using boolean values in a comparison, when numeric values are expected:

https://github.com/Graylog2/graylog2-server/blob/06d071db9d45434cbfbeccf692852fe618486ad8/graylog2-web-interface/src/components/configurations/SidecarConfig.tsx#L90-L97
