### ISSUE TITLE
Keyboard shortcuts overview cannot be opened with ctrl+?

### ISSUE THREAD

**Issue by luk-kaminski** [Graylog2/graylog2-server#16827]
## Your Environment

test-dev-ng.dev.graylog.cloud

* Graylog Version: 5.2.0
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by linuspahl** [comment]
I mentioned the wrong keyboard shortcut in the test plan. It should be `shift` + `?`. I updated the test plan. Can you please test it again?
