### ISSUE TITLE
Make number of terms in quick values widget configurable

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#1684]
From the mailing list:

> Hi,
>   When we use the Quick values in the widget, it displays only about 50 items in the value the rest of the details are not shown, when the search query is changed ignoring few patterns of the current values, we get to see the rest of the missing items. 
> 
> https://github.com/Graylog2/graylog2-server/issues/1661#issuecomment-168781738
> 
> It seems they are configured in the code to act so, can you please have this values to be customisable by giving an option to change in the conf file. 
> 
> Thanks, Hema.

**Comment by dennisoelkers** [comment]
This has been implemented in OSS since `3.1.0`.
