### ISSUE TITLE
DataNode: OpenSearch Hostname verification creates SSL exception

### ISSUE THREAD

**Issue by janheise** [Graylog2/graylog2-server#16876]
## Current Behavior

If we have Hostname verification enabled like `plugins.security.ssl.transport.enforce_hostname_verification = true`, we get the following SSL exceptions when OpenSearch tries to resolve the Hostnames when connecting between nodes on the transport port:

`Caused by: javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)`

`Caused by: javax.crypto.BadPaddingException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)`

A quick search on the internet gave the result that this is indeed a JDK bug and/or connected to the bouncycastle org library version used in OpenSearch. 

People have noticed that adding the IP-Address to the SANs solved it for them.

A follow-up problem is, that binding OpenSearch to `0.0.0.0` leads to a `unknown_certificate` error because the lookup is against `localhost` instead of the `hostname` or `node_name`.

The demo certificates from OpenSearch and also from Elasticsearch contain the loopback IP-Addresses and also `localhost` in the SANs. This is considered to be bad practice everywhere on the internet. The inclusion is probably to facilitate an easy demo SSL setup on single node clusters and the contents of the certificates are not meant to be a good example at all.

Trying to setup a local cluster following the guide at https://opensearch.org/docs/latest/install-and-configure/install-opensearch/tar/

results in the follwing exception:
`Caused by: java.security.cert.CertificateException: No subject alternative names matching IP address 192.168.xxx.yyy found`

Research items:
https://forum.opensearch.org/t/enforce-hostname-verification/9233
https://opensearch.org/docs/latest/troubleshoot/tls/#check-san-hostnames-and-ip-addresses
https://github.com/opensearch-project/security/issues/2054

https://github.com/opensearch-project/security/issues/3299
https://bugs.openjdk.org/browse/JDK-8227651
https://bugs.openjdk.org/browse/JDK-8221218

Following chain of events/results from tests:
- according to the docs and one link from above, we have to add the IP address of the node to the cert to fix the padding error
- this works but leads, with our default config, to the unknown_host certificate error because it checks for `localhost` 
- which is, because we bind against `0.0.0.0` per default
- if I bind to the same IP that's in the certificate, our current config/creation of cluster.initial_master_nodes fails
- we currently create this from every active node hostname
- which created problems because of duplicate hostnames in the list when you start more than one node on the given host
- I changed it to include the transport port, to make it unique
- which did not work
- I had to explicitly set this to my hostname *once* and leave out any ports
 - which seems counterintuitive because it seems there is no way now to explicitly link to the nodes (e.g. you want a third node on this single machine that is not supposed to take part into cluster forming) and if you run OpenSearch on ports that are not part of the autodetection
- and also, we still might want to bind to `0.0.0.0` - and if it's only because it simplifies the default config e.g. running inside docker

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by janheise** [comment]
fixed with #17022 #16957

**Comment by Thrallix** [comment]
Also having this issue using latest tag.
Note that this rule is off:
plugins.security.ssl.transport.enforce_hostname_verification: false

And i am using proper plugins.security.nodes_dn settings.
