### ISSUE TITLE
Graylog-server/web error

### ISSUE THREAD

**Issue by m1cka** [Graylog2/graylog2-server#1689]
HI, i moved vm with graylog-server/web+elastic+mongo into other hyper-v machine. whet i started vm, i recieve messages
in web UI / source 
Could not load histogram data
Loading of histogram data failed with status: Bad Request
 in graylog-server logs
```
 WARN  [SearchResource] Unable to execute search: Failed to execute phase [query], all shards failed; shardFailures {[smdaBx2qRN2IjW2ll7tPQA][graylog2_9][0]: RemoteTransportException[[srgraylog2][inet[/172.16.92.172:9300]][indices:data/read/search[phase/query]]]; nested: ClassCastException[org.elasticsearch.index.fielddata.plain.PagedBytesIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]; }{[smdaBx2qRN2IjW2ll7tPQA][graylog2_9][1]: RemoteTransportException[[srgraylog2][inet[/172.16.92.172:9300]][indices:data/read/search[phase/query]]]; nested: ClassCastException[org.elasticsearch.index.fielddata.plain.PagedBytesIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]; }{[smdaBx2qRN2IjW2ll7tPQA][graylog2_9][2]: RemoteTransportException[[srgraylog2][inet[/172.16.92.172:9300]][indices:data/read/search[phase/query]]]; nested: ClassCastException[org.elasticsearch.index.fielddata.plain.PagedBytesIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]; }{[smdaBx2qRN2IjW2ll7tPQA][graylog2_9][3]: RemoteTransportException[[srgraylog2][inet[/172.16.92.172:9300]][indices:data/read/search[phase/query]]]; nested: ClassCastException[org.elasticsearch.index.fielddata.plain.PagedBytesIndexFieldData cannot be cast to org.elasticsearch.index.fielddata.IndexNumericFieldData]; }
```
but in elastic head plugin i see that msg is increasing.
have some ideas how to fix it? manual cycle deflector not helping ;/

**Comment by joschi** [comment]
Which exact version of Graylog (server and web interface) are you using?
Could you please post the output of the following curl command against the Elasticsearch HTTP API (replace "localhost" with the actual host name or IP address of one of your Elasticsearch nodes):
```
curl -i -X GET 'http://localhost:9200/graylog_*/_mapping?pretty&size=100'
```
You might also need to replace "graylog_*" with "graylog2_*", depending on your configured Elasticsearch index prefix in the Graylog configuration file.

**Comment by m1cka** [comment]
graylog-web 1.3.2; server 1.3.2
graylog2_1/2/3 was good data
[Uploading New Text Document (3).txt…]()

**Comment by m1cka** [comment]
my mistake, i was changed graylog-internal  name, so new created index was wrong
