### ISSUE TITLE
Have a quickstart script

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#169]
Have a script that starts `graylog2-server` with a (yet to be implemented) `--es-data` flag and also the new `graylog2-web-interface` pointing to the started server instance already.

The `--es-data` flag enables data storage of the embedded ElasticSearch node and allows a quick setup. Show a warning in the web interface, saying that at least one node is running in quickstart mode and point to a support page that explains why this works but usually is a bad idea for production.

This would allow you to start using Graylog2 in just a few seconds on any system that has a JRE installed.

**Comment by bernd** [comment]
We have a quick-setup application and virtual machine images now. I think this can be closed. Please re-open if we still want to do this. Thank you!
