### ISSUE TITLE
Content pack install shows latest version installed when selecting and installing different version

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/graylog2-server#16913]
When installing a different version of a content pack, the content pack page shows the latest version is installed, even though the version you selected is the content pack seems to be the one actually installed. 

https://github.com/Graylog2/graylog2-server/assets/2953243/12eb63de-578d-403a-ac7d-d4f72d13ec49

## Your Environment

* Graylog Version: Graylog 5.2.0-beta.2+33d72dd
* Java Version: embedded
* OpenSearch Version: 2.9.0
* MongoDB Version: 5.0.18
* Operating System: Debian 12.2
* Browser version: Arc Version 1.11.0 (42160) - Chromium Engine Version 117.0.5938.149

**Comment by ryan-carroll-graylog** [comment]
Testing and looking at the DB, it appears the latest revision is always being installed regardless of the revision selected.
Looks like this is due to the requests coming in from the front end always having the latest revision, so looping in @zeeklop @simonychuang
