### ISSUE TITLE
API Browser displays wrong Request URL

### ISSUE THREAD

**Issue by renapu** [Graylog2/graylog2-server#1691]
Hi,

When only one API call gets triggered from the API-Browser it shows the right request URL, but if you let the view opened and you trigger another API-Call from another section, the latest Request URL will show in all old Operation-Windows. Here is a screenshot for better understanding: http://i.imgur.com/16MRn6j.png

**Comment by bernd** [comment]
Thank you for the report! This got fixed in https://github.com/Graylog2/graylog2-server/commit/73456773b312a8d3b14774dbd82a6db30e0b340e and will be in Graylog 2.0.
