### ISSUE TITLE
Udp lost package

### ISSUE THREAD

**Issue by victoryxs** [Graylog2/graylog2-server#1695]
flume send udp package to graylog2-1.01, the speed rate is 2500/s, the package size is not over 8k and the ping is 0.3ms. Sometimes graylog2 don't lose anything,but sometime lose rate is 0.01. I trace the metrics allover, find lose package from NettyTranspot, but i use tcpdump to gelf the package and find package no lost.

**Comment by kroepke** [comment]
Without more details we really cannot answer this question, I'm sorry.
tcpdump will show the message because it is seeing it before it is delivered to Graylog. Most likely your server is too slow (or you have debug mode enable, see the other issue).
