### ISSUE TITLE
Cannot set custom log level using API

### ISSUE THREAD

**Issue by moesterheld** [Graylog2/graylog2-server#16961]
In 5.2, it is not possible to set the log level for a logger which hasn't been defined in `log4j2.xml` using the `cluster/system/loggers` endpoint

This is caused by a change introduced when switching to log4j 2.20.0 (introduced in 2.17.2, works fine in 2.17.1).
Here, the root logger is created with `additivity=false`, leading to newly created loggers missing the appenders of the root logger because we create them with the additivity of the root logger.

see https://logging.apache.org/log4j/log4j-2.4/manual/configuration.html#Loggers
"The root logger does not support the additivity attribute since it has no parent."

Thus, we shouldn't rely on the additivity attribute of the root logger

## Your Environment
* Graylog Version: 5.2
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by mpfz0r** [comment]
nice catch! I consider this a blocker. Having this debugging capability is important to us
