### ISSUE TITLE
Search in the last index returns "searched in 0 indices", "used_indices": []

### ISSUE THREAD

**Issue by renapu** [Graylog2/graylog2-server#1696]
When a search is performed against the last Index, the response contains no Index:
And in the Web-gui it will be shown as "searched in 0 indices"

This can lead to massive problems with some scripts which build on the "used_indices" value from the API.

```
"query": "*",
  "built_query": "{\"from\":0,\"size\":150,\"query\":{\"filtered\":{\"query\":{\"match_all\":{}},\"filter\":{\"bool\":{\"must\":{\"range\":{\"timestamp\":{\"from\":\"2016-01-15 09:15:44.259\",\"to\":\"2016-01-15 09:20:44.259\",\"include_lower\":true,\"include_upper\":true}}}}}}},\"sort\":[{\"timestamp\":{\"order\":\"desc\"}}]}",
  "used_indices": [],
  "messages": [
    {

````

Version: 1.3.3 (0fda9dc) (Hansa)

**Comment by joschi** [comment]
@renapu Make sure that there's a (dummy) index range for the current deflector target (see `http://localhost:12900/system/indices/ranges`). This index range information is usually created during index cycle, but you can also specifically recreate this information at `http://localhost:12900/system/indices/ranges/$INDEX_NAME/rebuild`.

**Comment by renapu** [comment]
Hi,
after the Upgrade to 1.3.3 the active Index was buggy, after cycling it all is now working normally.
At the moment we cycled the active and buggy index we faced some "Journal utilization is too high" Problems, that we've never had before. But at the moment we are in a good condition!
