### ISSUE TITLE
Cannot delete a dashboard page/tab if it is the first page/tab

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#16964]
When deleting a dashboard page/tab that is the first one, an error is displayed:

`Loading component failed: Cannot read properties of undefined (reading 'widgets')`

See http://videos.graylog.com/watch/Qwud1ppAsAZKMshgCBcncA?

## Expected Behavior

You can successfully delete the first dashboard page/tab without error

## Current Behavior

Unable to delete the first dashboard tab/page and an error is shown.

## Steps to Reproduce (for bugs)

See video above.

## Your Environment

* Graylog Version: 5.1.6
* Java Version: Bundled
* OpenSearch Version: 2.11.0
* MongoDB Version: 6.11
* Operating System: Ubuntu 22.04 LTS
* Browser version: Google Chrome Version 118.0.5993.70 (Official Build) (arm64)

A usable workaround is to reorder the pages/tabs so that the first entry is no longer the first entry and then delete it

**Comment by williamtrelawny** [comment]
Customer raised this exact same issue: [HS-2020537755](https://app.hubspot.com/contacts/8267556/record/0-5/2020537755)
