### ISSUE TITLE
Space in Value of simulated message in source code pipeline rules editor breaks parsing

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#16983]
## Expected Behavior

I can specify a message to be simulated with key-value pairs like this:

```
message: test
source: unknown
transaction_date: 2023-05-01 00:00:00
```

## Current Behavior

When I specify this message for simulation, the complete content of the input is used for the message field:

![image](https://github.com/Graylog2/graylog2-server/assets/41929/006078c1-a9b3-4115-b797-3cfe0f152f43)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by moesterheld** [comment]
This isn't caused by the space, but the colon. I am going to take a look into that.
