### ISSUE TITLE
GET /system/gettingstarted is broken

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1700]
Hello,

GET /system/gettingstarted returns 500 with following log entry

2016-01-18T15:16:34.164Z ERROR [WriterInterceptorExecutor] MessageBodyWriter not found for media type=text/xml, type=class org.graylog2.rest.models.system.AutoValue_DisplayGettingStarted, genericType=class org.graylog2.rest.models.system.DisplayGettingStarted.

**Comment by joschi** [comment]
Please post the complete HTTP request you're sending to this resource.

**Comment by pdepaepe** [comment]
As graylog administrator, GET on http://graylog-master:12900/system/gettingstarted

Status 500 Internal Server Error
Time 119 ms

Body response:
```
{
  "type": "ApiError",
  "message": "HTTP 500 Internal Server Error"
}
```

**Comment by joschi** [comment]
Try setting an `Accept` header in your HTTP request.

```
# curl -u admin:admin -i -H 'Accept: application/json' 'http://graylog-master:12900/system/gettingstarted'
HTTP/1.1 200 OK
X-Graylog-Node-ID: cd03ee44-b2a7-4824-be16-bb7456149dbd
Content-Type: application/json
Date: Mon, 18 Jan 2016 16:10:17 GMT
Content-Length: 14

{"show":false}
```
