### ISSUE TITLE
Content pack download is not working on Firefox

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/graylog2-server#1701]
Issue: Tested with snapshot 2.0.0-SNAPSHOT-20160118140636, the actual download of a content pack is not working with Firefox 43.

Steps to reproduce: Go to System->Content Pack, fill in name, description and category, select at least a one item for the content pack. Click on Download. Only a the green notification bar appears but no file download.

**Comment by edmundoa** [comment]
Fixed in 2fac2b201e80db915d7aadb33171491fabf112ad
