### ISSUE TITLE
Messages not processing into all streams the message matches

### ISSUE THREAD

**Issue by Spikeophant** [Graylog2/graylog2-server#1709]
We are using graylog for our system and application logs, and as a way to allow others in our organization outside the IT dept to have insight into logs needed to perform their functions.  I needed to create alerting for a stream that was based on x number of messages in the last y minutes from a specific source.  I was unable to find a way to do this on a stream that has messages from multiple sources, so I decided to create a stream per source, as well as the master stream that users would look at.  When I create the additional streams and test against a message the web gui tells me my messages will match.  However when I start the stream no messages are visible in it, and therefore I cannot create alerting based on this.  I let the stream run for a while, then tested a message I had expected to appear in it against it's rules in the web ui and it says it will match, however still no messages in my new streams.  I'm using Graylog 1.2, but do plan to update in the near future.

**Comment by Spikeophant** [comment]
I restarted the graylog-server service on both of my graylog servers and all streams now function properly, I'm curious if anyone knows why this would be the case?

**Comment by dennisoelkers** [comment]
Non-reproducible issue, closing. Please reopen if it happens again and you have more information.
