### ISSUE TITLE
System/Inputs page broken after each server restart

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1710]
I am getting "Fetching Input Types failed with status: TypeError: Cannot read property 'xxxx' of undefined" when I try to access System/Inputs after a Graylog server restart. A full page reload fixes the problem and it does not show up until I restart the Graylog server.

The backtrace in the console does _not_ always happen. This might be something different.

![screenshot from 2016-01-21 11 23 33](https://cloud.githubusercontent.com/assets/461/12477906/7bd5f250-c032-11e5-9bb1-26999e1b1696.png)

**Comment by edmundoa** [comment]
Fixed in 5613210dd83673fca92728e028232cdd24688369.
