### ISSUE TITLE
Update user unlink role membership

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#1714]
Hello,

From web interface, edit a user, then click on "Update User" button.
Go back on user list page, user edited have no more roles.

**Comment by dennisoelkers** [comment]
Hey @pdepaepe, which version of the graylog are you using?

**Comment by pdepaepe** [comment]
1.3.x

**Comment by edmundoa** [comment]
This form was completely rewritten in 2.0, please reopen if this is still an issue in that version.
