### ISSUE TITLE
2 Header Badges

### ISSUE THREAD

**Issue by gally47** [Graylog2/graylog2-server#17156]
![Screenshot 2023-11-03 at 15 15 32](https://github.com/Graylog2/graylog2-server/assets/106236152/5d2cb00c-c061-4973-89d6-bf6f5dc36206)

## Expected Behavior
1 Header Badge

## Current Behavior
2 Header Badges one on the top right side the other on the top left.

**Comment by kmerz** [comment]
Hey @gally47, we could not verify that problem. Could it be that it is only in your development branch? Could you please verify that?

**Comment by gally47** [comment]
Problem not happening anymore on my development branch. So I will close the issue.
