### ISSUE TITLE
DataNode: Migration by Remote Reindexing

### ISSUE THREAD

**Issue by janheise** [Graylog2/graylog2-server#17154]
After some preliminary work, it was established, that remote re-indexing works from

- ES 6.8
- ES 7.10
- OS 1.3

into OS2.10.0
OS2 -> OS2 was not tested but I assume it works.

Next up: Tests with larger amount of data.

TODO: how to migrate `index templates`
TODO: how to include a `migration assistant` that checks for all necessary steps before actually starting any migrations that could make your setup useless

Migration path:
- stop existing GL, keep ES/OS(-cluster) running
- if necessary, upgrade MongoDB to 5.0
- upgrade GL (if needed stepwise) to >5.2
- remove `elastic-url` from config, if it exists
- start GL in preflight mode (rename it to migration? add another param with that name but which works like preflight in this case?)
- configure your DataNodes
- before resuming, after successful provisioning, add a `migrate existing data` button
- specify the `reindex.remote.whitelist:` parameter (can be set/unset on a running DataNode(-cluster))
- add remote credentials for the old cluster if necessary
- after successful migration by reindexing, make the resume button available
- resume GL startup

Links:
https://www.elastic.co/guide/en/elasticsearch/reference/8.0/docs-reindex.html#reindex-from-remote
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/reindex-upgrade-remote.html
https://opensearch.org/docs/2.11/api-reference/document-apis/reindex/#url-parameters
https://stackoverflow.com/questions/61780191/how-to-migrate-index-from-old-server-to-new-server-of-elasticsearch

**Comment by kroepke** [comment]
Is there a way to remove the downtime requirement for all scenarios except elasticsearch 6.8? (Because it's not supported from Graylog 5.0 upwards.)
Or is the intention that data ingest can resume relatively quickly in parallel with remote-reindexing?

**Comment by janheise** [comment]
First: my intention was, that it's the fallback & also with a new setup. Migration without downtime would be more the second, rolling upgrade migration. 
It's no big deal to start remote-reindexing and afterwards resume the graylog start, but I am concerned about events & reporting (and maybe other stuff I forgot about now) that might create wrong results while the reindexing has not finished
