### ISSUE TITLE
DataNode: add migration step to preflight UI

### ISSUE THREAD

**Issue by janheise** [Graylog2/graylog2-server#17157]
For the migration during preflight, we need another step after the provisioning but before resume.
maybe as an additional button next to resume for those users, that want to migrate data from an existing cluster.

The migration page needs the following input fields:
- user/password credentials to the existing cluster
-  a textfield for the `reindex.remote.whitelist:` parameter

and a button "migrate data" + also the "resume start" button that can be pressed when migration finished
maybe also add a "cancel" button later to stop a running migration?

see #17154 for the full migration path

**Comment by grotlue** [comment]
As we decided that the reindexing migration won't be available in preflight this issue can be closed.
