### ISSUE TITLE
Unable to click "Create configuration" when creating new sidecar

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#17185]
When creating a new sidecar [collector] configuration, the workflow asks for a name as the first input box, however if you input a name BEFORE filling out the configuration text area box, you will be unable to save the collector configuration.

See https://videos.graylog.com/watch/6z99h7gFMPasMqNnSyJHVd

## Expected Behavior

Sidecar collector configuration can be created when inputting the configuration AFTER inputting the name.

## Current Behavior

Unable to click "Create configuration" when creating new sidecar if name is input BEFORE the configuration.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 5.1.7
* OpenSearch Version: 2.4.1
* MongoDB Version: 6.0
* Operating System: Docker
* Browser version: Google Chrome Version 118.0.5993.117 (Official Build) (arm64)

Please let me know if there are any questions!

**Comment by drewmiranda-gl** [comment]
Confirmed this also happens on 5.2.0

**Comment by kroepke** [comment]
If this is actually rendering the form useless, please also create a backport for 5.1, thanks!
