### ISSUE TITLE
Alerts & Events drop down issue

### ISSUE THREAD

**Issue by r4msd** [Graylog2/graylog2-server#17199]
In the GUI, when going to Alerts & Events section, there's is a drop down menu on the right hand side which doesn't seem to work like intended. It never shows more than 10 entries even if you try select a higher view option.

## Expected Behavior
When selecting 25, 50, 100, this should show more than 10 entries. 

## Current Behavior
When selecting 25, 50, 100, it ignores the option, it should show more than 10 entries

## Possible Solution
UI issue to be fixed

## Steps to Reproduce (for bugs)
1. Go to Alerts & Events
2. Select a higher view than 10
3. You will see it doesn't show higher amount

## Your Environment

* Graylog Version: Cloud version 5.1.8 / Local version 5.1.5
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by coffee-squirrel** [comment]
Seeing the same in `5.1.7`, but it appears to be fixed in `5.2.0`.

**Comment by kroepke** [comment]
@Graylog2/core Could we find the commit that fixed and backport to 5.1 please?

**Comment by grotlue** [comment]
@gally47 and me found the PR that fixed this issue for 5.2 https://github.com/Graylog2/graylog2-server/pull/15357.
Backporting it 1-to-1 is not straight forward so I just extracted the fix in https://github.com/Graylog2/graylog2-server/pull/17342.
