### ISSUE TITLE
absence of graylog-web-interface.conf prevents graylog-web-interface from working

### ISSUE THREAD

**Issue by ShalbafZadeh** [Graylog2/graylog2-server#1720]
i've installed graylog-web and graylog-server (1.3.3-1 of both) from apt repository
and configured elasticsearch and mongodb
i successfully started graylog-server but when i start graylog-web is says service is started but nothing was at localhost:9000
i tried to run graylog-web from /usr/share/graylog-web/bin 
and i got this error
```bash
$ sudo ./graylog-web-interface 
Play server process ID is 24666
16:28:34.966 [main] ERROR lib.Global - Your configuration should be at /usr/share/graylog-web/conf/graylog-web-interface.conf but does not exist, cannot continue without it.
Oops, cannot start the server.
java.lang.IllegalStateException: Missing configuration file /usr/share/graylog-web/conf/graylog-web-interface.conf
```
its because graylog-web-interface.conf is not generated but default buts its needed 
this issue could be resolved by coping web.conf and rename it to graylog-web-interface.conf
```bash
$ cp /usr/share/graylog-web/conf/web.conf /usr/share/graylog-web/conf/graylog-web-interface.conf   
```
then you can start graylog-web and its work on http://localhost:9000
```bash
$ sudo ./graylog-web-interface 
Play server process ID is 25408
[info] play - Application started (Prod)
[info] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
```

**Comment by joschi** [comment]
The start scripts for the Graylog web interface (SysV init, Upstart, systemd; see https://github.com/Graylog2/fpm-recipes/blob/1.3/recipes/graylog-web/files/graylog-web.sh) already provide the correct path to the configuration file.

If you're not using those provided scripts, you're on your own and have to either provide the path to the configuration file when starting the web interface or place the configuration file in the correct location.

**Comment by ShalbafZadeh** [comment]
@joschi thanks!
i was not aware of existence of them
they have not mentioned in official documentation
thanks for your help :+1:

**Comment by joschi** [comment]
@ShalbafZadeh You're welcome.

FWIW, the startup commands are listed in the documentation about the operating system packages: http://docs.graylog.org/en/1.3/pages/installation/operating_system_packages.html

**Comment by ShalbafZadeh** [comment]
@joschi 
sorry again 
i checked http://docs.graylog.org/en/1.3/pages/installation/operating_system_packages.html but i couldn't find any link to these scripts
https://github.com/Graylog2/fpm-recipes/blob/1.3/recipes/graylog-web/files/graylog-web.sh

**Comment by joschi** [comment]
@ShalbafZadeh The script you've linked to is being executed by all of the provided startup scripts.

Please move the discussion to [the mailing list](https://groups.google.com/forum/#!forum/graylog2) or to [https://webchat.freenode.net/?channels=%23graylog](#graylog on Freenode) if you feel that something is still unclear.
