### ISSUE TITLE
Illuminate pack for NGinx logs

### ISSUE THREAD

**Issue by r4msd** [Graylog2/graylog2-server#17219]
There is no illuminate pack to process NGinx logs. NGinx is a web server like Apache, I would like to extract the fields as in the example.

## What?
Nginx access log :
192.168.0.1 - - [02/Nov/2023:14:15:36 +0100] "POST /api/cluster/metrics/multiple HTTP/1.1" 200 915 "[http://serv-monitoring-graylog-01/streams/as0536asfgrg0565sad/search](https://link.edgepilot.com/s/afdeddcc/njim_Hs3FEmpJiEmczVocQ?u=http://serv-monitoring-graylog-01/streams/as0536asfgrg0565sad/search)" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0" "-"
Nginx error log :
2022/05/14 19:55:51 [error] 6689#6689: *16764375 FastCGI sent in stderr: "PHP message: PHP Warning: Division by zero in /var/www/html/my.php on line 438" while reading upstream, client: 10.1.1.1, server: [mytest.com](http://mytest.com/), request: "GET /my.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "[my.test.com](http://my.test.com/)"

Grok pattern example for nginx access log :
%{IPV4:source_ip} - - \[%{HTTPDATE:event_created}\] "%{HTTPMETHOD:http_request_method} %{UNIXPATH:http_request_path} HTTP/%{BASE10NUM:http_version}" %{BASE10NUM:http_reponse_code} %{BASE10NUM:http_response_bytes;int} %{QS:http_uri} %{QS:http_user_agent} "-"

## Your Environment

* Graylog Version: 5.1.2
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by r4msd** [comment]
HS #2052201543

**Comment by kroepke** [comment]
Illuminate 4.0 added a nginx content pack. Please reopen this issue if that does not address it.
