### ISSUE TITLE
Graylog2 0.20.3 Could not successfully connect to ElasticSearch.

### ISSUE THREAD

**Issue by RootR90** [Graylog2/graylog2-server#1723]
Please help me! For a long time I can not understand. Can not connect to the "ElasticSearch". Can not run "Graylog2", ElasticSearch up and running, the status of green! Here are my "graylog2.txt" and "elasticsearch.txt", in "log.txt" evident error.

[elasticsearch.txt](https://github.com/Graylog2/graylog2-server/files/104628/elasticsearch.txt)
[graylog2.txt](https://github.com/Graylog2/graylog2-server/files/104629/graylog2.txt)

[log.txt](https://github.com/Graylog2/graylog2-server/files/104630/log.txt)

**Comment by joschi** [comment]
@RootR90 Please upgrade to the latest stable version of Graylog (version 1.3.3 at the time of writing). Graylog2 0.20.x or 0.90.x isn't supported anymore.

**Comment by RootR90** [comment]
@joschi Thank you!!
this version can not be configured?
