### ISSUE TITLE
graylog GRAYLOG_HTTP_PUBLISH_URI has bug

### ISSUE THREAD

**Issue by pycgo** [Graylog2/graylog2-server#17230]
## Current Behavior

if i add env GRAYLOG_HTTP_PUBLISH_URI: http://172.16.86.128/graylog/  ; there logs is like
`2023-11-09 15:12:45,644 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Failed to call API on node <2874d194-0329-4dbf-a866-effd02aa2573>, cause: timeout (duration: 1001 ms)
2023-11-09 15:12:46,198 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Failed to call API on node <2874d194-0329-4dbf-a866-effd02aa2573>, cause: timeout (duration: 5001 ms)
2023-11-09 15:12:47,632 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Failed to call API on node <2874d194-0329-4dbf-a866-effd02aa2573>, cause: timeout (duration: 1001 ms)
2023-11-09 15:12:49,625 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Failed to call API on node <2874d194-0329-4dbf-a866-effd02aa2573>, cause: timeout (duration: 1001 ms)
2023-11-09 15:12:51,223 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Failed to call API on node <2874d194-0329-4dbf-a866-effd02aa2573>, cause: timeout (duration: 5001 ms)
2023-11-09 15:12:51,612 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Failed to call API on node <2874d194-0329-4dbf-a866-effd02aa2573>, cause: timeout (duration: 1001 ms)
2023-11-09 15:12:53,628 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Failed to call API on node <2874d194-0329-4dbf-a866-effd02aa2573>, cause: timeout (duration: 1001 ms)`

## Steps to Reproduce (for bugs)

1. docker-compose file
```shell
version: '2.2'
services:
  mongodb:
    image: registry.aliyuncs.com/linkflow/mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
      - mongo_configdb:/data/configdb
    environment:
      - TZ=Asia/Shanghai
    networks:
      - graylog
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"
  
  opensearch:
    image: registry.aliyuncs.com/linkflow/opensearch:2.5.0-fix
    container_name: opensearch
    restart: always
    volumes:
      - /data/graylog/opensearch:/usr/share/opensearch/data
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - cluster.name=graylog
      - node.name=graylog
      - network.host=0.0.0.0
      - action.auto_create_index=false
      - "OPENSEARCH_JAVA_OPTS=-Xms2G -Xmx2G"
    networks:
      - graylog
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"
  
  graylog:
    image: registry.aliyuncs.com/netflow/graylog:5.2
    container_name: graylog
    restart: always
    volumes:
      - graylog:/usr/share/graylog/data
    environment:
      - TZ=Asia/Shanghai
      - GRAYLOG_ROOT_TIMEZONE=Asia/Shanghai
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=482071d7d7ea9dca86a5e6ed5044c7e23d4dd891da25887844a55b639cc00133  # admin Sjtu403c@#%
      - GRAYLOG_PROCESSBUFFER_PROCESSORS=3
      - GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE=20gb
      - GRAYLOG_MESSAGE_JOURNAL_MAX_AGE=24h
      - GRAYLOG_HTTP_PUBLISH_URI=http://172.16.86.128/graylog/
      - GRAYLOG_HTTP_EXTERNAL_URI=http://172.16.86.128/graylog/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh
    depends_on:
      - mongodb
      - opensearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      # beats
      - 5044:5044
    networks:
      - graylog
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "1"
  
networks:
  graylog:
    name: graylog
    ipam:
      driver: default
      config:
        - subnet: "189.20.0.0/24" 
volumes:
  graylog:
    name: graylog
  mongo_data:
    name: mongo_data
  mongo_configdb:
    name: mongo_configdb
``` 
2. input not runing
![企业微信截图_601fdcfe-ff81-495b-b49f-5fa79dbef9b7](https://github.com/Graylog2/graylog2-server/assets/55949132/b6dd8164-1956-4a69-ac53-e9535e3aaa7f)
 
3. 
    when i delete env  GRAYLOG_HTTP_PUBLISH_URI and alter GRAYLOG_HTTP_EXTERNAL_URI  it works fine
  ```shell
delete 2 line
      - GRAYLOG_HTTP_PUBLISH_URI=http://172.16.86.128/graylog/
      - GRAYLOG_HTTP_EXTERNAL_URI=http://172.16.86.128/graylog/
and one line
      - GRAYLOG_HTTP_EXTERNAL_URI=http://172.16.86.128/
  ```
5.  then input will work fine
![image](https://github.com/Graylog2/graylog2-server/assets/55949132/ac7b1a51-8a53-4917-b4d9-f87ed764227e)
 

## Your Environment

* Graylog Version: 5.2
* Java Version:
* OpenSearch Version: 2.5.0
* MongoDB Version: 6
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Seems like it is working as designed. `GRAYLOG_HTTP_PUBLISH_URI` is used as URL for the node to be reached from other nodes (including itself). When the node cannot reach itself using that URL, the errors you are seeing will occur.

Do you still think this is a bug? If yes, please provide additional information helping us to understand why. If not, please close this issue.

**Comment by pycgo** [comment]
> Seems like it is working as designed. `GRAYLOG_HTTP_PUBLISH_URI` is used as URL for the node to be reached from other nodes (including itself). When the node cannot reach itself using that URL, the errors you are seeing will occur.
> 
> Do you still think this is a bug? If yes, please provide additional information helping us to understand why. If not, please close this issue.

Thank you. I didn't know it needed to access itself before。

**Comment by pycgo** [comment]
The domain name in k8s （has slb ）has been resolved, but it doesn't work。The k8s domain name has been resolved, but it does not work. Can't we separate the address we need from the address we access externally?
