### ISSUE TITLE
Geo-ip processor programmatically cannot be enabled using ReST api

### ISSUE THREAD

**Issue by gianluca-valentini** [Graylog2/graylog2-server#17317]
Hi,
I'm, using Graylog 4.3.
There should be  the possibility to enable the geolocation processor using ReST API but I don't find anything in the Node API web page

![image](https://github.com/Graylog2/graylog2-server/assets/3224592/88a16238-789d-421a-ba02-f8a2c55b71ea)

In my scenario the customer could not share the possibility to use the gui so I 'd need to change it using API. 
Is there the possibility to enable it as graylog setup? 
Thanks
Gianluca Valentini

**Comment by drewmiranda-gl** [comment]
I'm not sure I would consider this a bug. Our community forum may be a more appropriate place to discuss: https://community.graylog.org/

But to answer your question: i am automating this using the following:

URL: /api/system/cluster_config/org.graylog.plugins.map.config.GeoIpResolverConfig

json payload:

```json
{
    "enabled": true,
    "enforce_graylog_schema": true,
    "db_vendor_type": "MAXMIND",
    "city_db_path": "/etc/graylog/server/GeoLite2-City.mmdb",
    "asn_db_path": "/etc/graylog/server/GeoLite2-ASN.mmdb",
    "refresh_interval_unit": "MINUTES",
    "refresh_interval": 10,
    "use_s3": false
}
```

I don't have a 4.3 cluster ready to test on so your milage may vary.

You should be able to grab a sample web request using your browsers "developer tools" (commonly f12) and inspecting the payload.

**Comment by gianluca-valentini** [comment]
Thanks a lot
Gianluca
