### ISSUE TITLE
Collect metrics from Opensearch and Data Node

### ISSUE THREAD

**Issue by moesterheld** [Graylog2/graylog2-server#17403]
Collect metrics from the running Opensearch process and the data node in an Opensearch index.

These should include:
OS metrics:
- Disk health (% free space on OpenSearch partition), S.M.A.R.T. data (disk I/O speed, failure count, predictive failure, estimated time to failure if possible)
- CPU health (utilization, iowait)

DN metrics:
- Heap usage

**Comment by janheise** [comment]
done
