### ISSUE TITLE
Do Graylog 'Group Search Patterns' accomodate AND/OR expressions?

### ISSUE THREAD

**Issue by jroland2** [Graylog2/graylog2-server#1740]
Currently my Group Search Pattern is set to (which works):
(&(objectClass=group)(cn=graylog*))

What if I wanted to search between two different cn's?
Ie. cn=graylog* OR cn=other*

Tried this, but didn't work:
(&(objectClass=group)(cn=graylog*)||(cn=other*))

Is there documentation somewhere on supported syntax for Graylog Seach Patterns?  (my searching the Graylog docs and the web returned little that was useful)

Thanks much.

**Comment by kroepke** [comment]
Graylog simply passes the filters on to  whatever LDAP server is used and therefore uses standard LDAP syntax.
I believe you are looking for a query like this: `(&(objectClass=group)(|(cn=graylog)(cn=other)))`

Compare with http://www.ldapexplorer.com/en/manual/109010000-ldap-filter-syntax.htm

**Comment by jroland2** [comment]
Thanks so much! That's exactly what i needed.
