### ISSUE TITLE
telemetry api_key leak

### ISSUE THREAD

**Issue by macaty** [Graylog2/graylog2-server#17455]
There is a telemetry api_key leak here, there is an information security leak, how do I remove him?

* Graylog Version: Graylog 5.1.7+fcde74a on server (Eclipse Adoptium 17.0.8.1 on Linux 3.10.0-1160.95.1.el7.x86_64)

![image](https://github.com/Graylog2/graylog2-server/assets/16797633/7f2093f8-14a5-438d-8c6e-f53eb550b6f9)

**Comment by dennisoelkers** [comment]
Hey @macaty,

thanks for reporting this. The telemetry API key is included in the clear on purpose, as we do require it to report telemetry to that endpoint. Therefore, I do consider this a non-issue and I am closing it. If I misunderstood your issue or you have additional information, feel free to reopen it.
