### ISSUE TITLE
PGP Public Key for Linux Pakcages?

### ISSUE THREAD

**Issue by sarciszewski** [Graylog2/graylog2-server#1749]
Hi,

I was interested in setting up graylog2 on my virtual machine but I don't see a public key anywhere associated with the project in the download instructions here: http://docs.graylog.org/en/latest/pages/installation/operating_system_packages.html#debian-8

Am I missing something? Thanks

**Comment by joschi** [comment]
@sarciszewski The public key for Graylog's package repository will be automatically installed by the "repository" package (https://packages.graylog2.org/repo/packages/graylog-1.3-repository-debian8_latest.deb).

You can also fetch it directly from https://packages.graylog2.org/repo/debian/pubkey.gpg to verify it first.

**Comment by sarciszewski** [comment]
Okay, this is the fingerprint I see:

http://pgp.mit.edu/pks/lookup?search=0x28AB6EB572779C2AD196BE22D44C1D8DB1606F22&op=index&fingerprint=on

I don't see any signatures from any other developers. I'm not sure if I should trust it :(

**Comment by joschi** [comment]
If you don't trust the public key you've downloaded from the same server over an encrypted transport that also hosts the packages themselves (https://packages.graylog2.org/), I can't really help you.

**Comment by sarciszewski** [comment]
Well, that's sort of the problem: The host that serves both the packages and the public key is a single point of failure. If someone compromised the server, they could substitute both.

What strikes me as odd is [the existence of this key in particular](https://pgp.mit.edu/pks/lookup?op=vindex&fingerprint=on&search=0x26B2C114209DC497).

**Comment by sarciszewski** [comment]
Okay, thanks.

(By the way, [be careful with 32-bit PGP key IDs](https://evil32.com).)
