### ISSUE TITLE
Relative search delivers not the correct Timerange

### ISSUE THREAD

**Issue by renapu** [Graylog2/graylog2-server#1751]
We face a problem with query building the timerange with the relative search, if we search relative 60 seconds it results in:
from":"2016-02-01 14:59:49.842","to":"2016-02-01 15:00:49.842

but the actual time was: Mon Feb  1 15:00:39 2016
So it starts 60 secs ago to 120 secs ago and not 0 secs ago to 60 secs ago.
We also can see some drift in this range, its not always 60-120s.
When we use the keyword search we always get the correct timerange, with searches like "60 sec ago".

System: 1.3.3 (0fda9dc) (Hansa)
NTP-Stratum lvl 2

**Comment by joschi** [comment]
As swiftly pointed out on IRC (https://botbot.me/freenode/graylog/2016-02-02/?msg=59190910), the relative time range is using the local system time of the Graylog server node answering the request as end of the calculated time range. It's literally from "X seconds ago" until "now".

I also cannot reproduce the problem with a local setup of Graylog and with one running on AWS.

The only explanation I have is that either the client time is off or that the request to Elasticsearch took a certain time to process. The relative time range is calculated at the beginning of the request processing by the Graylog server node.
