### ISSUE TITLE
Sidecars: invalid path settings in filebeat collector and default config

### ISSUE THREAD

**Issue by thll** [Graylog2/graylog2-server#17526]
## Expected Behavior

The path settings in the default config and default collector config should configure the included filebeat to use the intended paths for logs and data.

## Current Behavior

The path settings for filebeat are broken in both the new default config and also the collector config. If applied, filebeat will log to `/usr/lib/graylog-sidecar/logs`, which is not intended.

At the moment the path settings look like this:

![image](https://github.com/Graylog2/graylog2-server/assets/886541/fd735d09-5b17-4053-921a-96bf60131839)

But I think they need to look like this:

![image](https://github.com/Graylog2/graylog2-server/assets/886541/55a0ddeb-6f44-473d-acd1-fd0e4ab38c5a)

## Possible Solution

Fix the config. Maybe it also makes sense to include a setting for `path.home` while we are at it.

## Context

[HS-2105922109]

## Your Environment

* Graylog Version: 5.2.1

**Comment by patrickmann** [comment]
Adding some more detail to above description: 
There are several types of defaults in sidecar configuration:
- default configurations: these reside in `sidecar_configurations` and are identifed by `tag` = `default`
- default templates: in `sidecar_collectors`

Filebeat path settings appear in the following locations in Mongo DB:
- `sidecar_collectors`: `executable_path` in filebeat entries for linux, freebsd, darwin
- `sidecar_collectors`: `default_template`
- `sidecar_configurations`: template in entries `filebeat-`linux`-default`, `filebeat-freebsd-default`, `filebeat-darwin-default` 

We do not want to replace entries that have been customized by the user. How do we know?
- `sidecar_collectors`: `executable_path` 
We won't touch this - it is complicated and error-prone to figure out if this needs updating. Users will need to manually update; or create a new collector based on the updated default configuration
- `sidecar_collectors`: `default_template`
Update, if CRC indicates that it has not been manually updated
- `sidecar_configurations`: 
Update, if CRC indicates that it has not been manually updated. We can use the CRC stored in `sidecar_collectors` `default_template_crc`
