### ISSUE TITLE
1.3.3 - Extractor management: 'load another message' not working

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#1753]
This used to work fine; but if I now use this to load a message, the error message doesn't disappear and the message isn't loaded.

> Could not load an example of field 'xxx'. It is not possible to test the extractor before updating it.

I do see the AJAX request in my console, and it works fine; it loads the right message and the server returns it as well

**Comment by joschi** [comment]
Do you see any error messages in the development console of your browser?

* Firefox: https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console
* Chrome: https://developer.chrome.com/devtools/docs/console

**Comment by SjonHortensius** [comment]
When the page loads I see something that looks like debug messages:

```
Object { form_field: <select#converter_date_time_zone.timezone-select>, options: Object, is_multiple: false, default_text: "Pick a time zone", results_none_found: "No results match", click_test_action: AbstractChosen</AbstractChosen.prototype.set_default_values/this.click_test_action(), activate_action: AbstractChosen</AbstractChosen.prototype.set_default_values/this.activate_action(), active_field: false, mouse_on_container: false, results_showing: false, 28 more… } Arguments { 0: <select#converter_date_time_zone.timezone-select>, 1: Object, 2: Object, 3: "chosen", 3 more… } form-combat.js:1:2115
Object { form_field: <select#converter_flexdate_time_zone.timezone-select>, options: Object, is_multiple: false, default_text: "Pick a time zone", results_none_found: "No results match", click_test_action: AbstractChosen</AbstractChosen.prototype.set_default_values/this.click_test_action(), activate_action: AbstractChosen</AbstractChosen.prototype.set_default_values/this.activate_action(), active_field: false, mouse_on_container: false, results_showing: false, 28 more… } Arguments { 0: <select#converter_flexdate_time_zone.timezone-select>, 1: Object, 2: Object, 3: "chosen", 3 more… }```

After clicking the button nothing else is logged.

It seems related to the fact that no message is loaded by default for this extractor. Another extractor that shows a matching message when loading the page works fine when loading another

**Comment by joschi** [comment]
@SjonHortensius Which browser are you using?

FWIW, I can't reproduce the issue using Graylog 1.3.3 and Google Chrome 48.0.2564.97 (64-bit).
Keep in mind that this specific screen only works with messages that actually contain the processed message field ('xxx' in your example). If that field isn't part of the provided message, testing the extractor won't be possible. So please double check, that the message actually contains the field being operated on by that specific extractor.

**Comment by SjonHortensius** [comment]
Thanks, that explains it. The extractor specified the incorrect field to extract the message from, which was why the error was (still) shown. The fact that nothing changed (the error remained) made me feel like nothing was happening. Maybe the message could flash in this case, that probably would have prevented me from reporting this issue

Sorry for the noise.
