### ISSUE TITLE
Setting email config via graylog-ctl does not seem to work

### ISSUE THREAD

**Issue by wingZero21** [Graylog2/graylog2-server#1756]
Hi,

I am attempting to amend the email config for graylog, however when running the below command it does not seem to be working.

Can you advise what might be causing this, I have had to manually amend the config for now.

Details:

```
graylog-ctl set-email-config SMTP-SERVER [--port=25] –no-tls –no-ssl
```

**Comment by mariussturm** [comment]
Did you run `graylog-ctl reconfigure` afterwards?

**Comment by bernd** [comment]
Closing this due to lack of feedback. Please re-open if you still have that issue. Thank you!
