### ISSUE TITLE
Alerts configuration is not saved when creating a content pack for a stream. 

### ISSUE THREAD

**Issue by leftyb** [Graylog2/graylog2-server#1758]
Hi,
In graylog 1.3.3  I am using almost 15 Streams, and I created a content pack out of those streams.
When I tried to load the content pack, to a freshly installation graylog server, 
I realized that all configuration of the streams for the alerts are not contained at the content pack.

 The configuration that I am referring are: 
- Configured alert conditions
- callbacks
- Receivers

Need to add this at the stream content pack creation, or some how to be able to save the alerts configuration for each stream.
Thank you,

**Comment by kroepke** [comment]
Afaik the alert configuration was never part of the content packs. We'll see if we can add it in a later version.

**Comment by leftyb** [comment]
Thank you @kroepke 

It will be more complete if alerts configuration is added to the content pack as well.

**Comment by jschram** [comment]
Any updates on this issue? The Alerts (conditions and notifications) still aren't saved in 2.2.3.

Is there any option to define conditions and notifications for alerts when provisioning a new graylog server instance? We're using docker image: graylog2/server:2.2.3-1

**Comment by joschi** [comment]
> Is there any option to define conditions and notifications for alerts when provisioning a new graylog server instance?

You could use the Graylog REST API to create them.

**Comment by jschram** [comment]
Doing that right now, but was hoping it could fit in the content pack since it's already being used for provisioning.

**Comment by etienne-napoleone** [comment]
Any news on that? This is the only thing I'm missing in the content pack.

**Comment by bernd** [comment]
@etienne-napoleone This will be part of the upcoming 3.0 release.
