### ISSUE TITLE
Graylog isn't accessible via browser - OVA template 1.3.3

### ISSUE THREAD

**Issue by jammon88** [Graylog2/graylog2-server#1760]
Hi

I've deployed the ova template version 1.3.3. After that I configured a static ip-address and tried to connect to graylog. No chance, graylog isn't working... IE says "This page can't be displayed".

Can anyone have a look at that?

Thanks and regards

Jammon

**Comment by joschi** [comment]
Please try restarting the virtual machine. If the Graylog web interface isn't starting again, please check the logs inside the virtual machine (`/var/log/`).
