### ISSUE TITLE
Message loss issues with "timestamp" parsing - why are timestamp fields "parsed" at all?

### ISSUE THREAD

**Issue by norandom** [Graylog2/graylog2-server#1761]
Hi,

I have a bug with Graylog2, which causes message loss and exceptions. 

**Issue:**
I forward JSON "strings" to Graylog2 to the GELF or Syslog Input. Both inputs work fine for multiple sources already. I configure a JSON extractor for the message field.

If there is a field with the following timestamp format, the message is thrown away and exceptions are logged at the server. The result is, that there are indexing errors. This is because the timestamp cannot be mapped. The logs for this are below.

`{"timestamp":"2016-02-01T15:31:02.000699+0000", ...`

If I extract attributes with the JSON extractor and there is a timestamp field like this, the messages are thrown away as well. 

The weird issue is that either way - directly via GELF as a populated field, or via JSON as an extracted field - the messages are thrown away due to the exceptions this causes. This is in-transparent because no more messages get received, once the extractor has been defined. 

I know now that the timestamp cannot be parsed by Graylog this way. I didn't ask Graylog2 to convert the timestamp at all. It does it automatically once such a field is present via extractor or input directly. I also cannot change the timestamp, because I only log the application.

**Affected versions:**
I am running the official Graylog2 appliance - a single Ubuntu Server VM - in a non-redundant test setup:

```
dpkg -l | grep graylog
ii  graylog                              1.3.2-1                          amd64

```

**Logs:**
> [graylog_347][1] failed to execute bulk item (index) index {[graylog_deflector][message][4188ff13-c8f8-11e5-99cc-0050568d61f9], source[{"gl2_remote_ip":"10.1.1.148","gl2_remote_port":35611,"streams":[],"source":"10.1.1.148","message":"{\"timestamp\":\"2016-02-01T15:27:07.729824+0000\",\"flow_id\":51872432,\"in_iface\":\"eno1\",\"event_type\":[...] gl2_source_node":"85b372be-c894-4f2c-a693-b88ee163ea5c","_id":"4188ff13-c8f8-11e5-99cc-0050568d61f9","dest_port":53,"timestamp":"2016-02-01T15:27:07.729824+0000"}]}
> org.elasticsearch.index.mapper.MapperParsingException: failed to parse [timestamp]

> at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:411)
>         at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:706)
>         at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:497)
>         at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
>         at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
>         at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:493)
>         at 

> org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:409)
> >         at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:148)
>  at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase.performOnPrimary(TransportShardReplicationOperationAction.java:574)
>         at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1.doRun(TransportShardReplicationOperationAction.java:440)
>         at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:36)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:745)

> Caused by: org.elasticsearch.index.mapper.MapperParsingException: failed to parse date field [2016-02-01T15:27:07.729824+0000], tried both date format [yyyy-MM-dd HH:mm:ss.SSS], and timestamp number with locale []
>         at org.elasticsearch.index.mapper.core.DateFieldMapper.parseStringValue(DateFieldMapper.java:617)
>         at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:535)
>         at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:239)
>         at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:401)

**Proposed fix:**
Make timestamp conversion optional, especially for extractors. Include the conversion in the extractor testing so that the message loss issue becomes transparent to users.

Best,
Marius

**Comment by joschi** [comment]
The `timestamp` field in messages needs to be in a [specific format](https://github.com/Graylog2/graylog2-server/blob/1.3.3/graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/Tools.java#L65) so that it can actually be stored as a date in Elasticsearch (which in turn allows certain operations on this type which it doesn't allow on strings for example).

There are a few "reserved" fields for messages in Graylog which should be tampered with, see https://github.com/Graylog2/graylog2-server/blob/1.3.3/graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/Message.java#L68-L91 for details. I agree that these aren't documented very well outside of the code.

This being said, it isn't a bug in Graylog but expected behavior to reject messages with an invalid `timestamp` field (in the end Elasticsearch rejects those messages but the result is the same). The workaround for this is to rename the field in your JSON payload.

**Comment by norandom** [comment]
What about escaping the field instead of discarding the message? The real issue here is the exception handling. Or renaming fields, in which this doesn't work, before storing it into Elasticsearch?

**Comment by joschi** [comment]
@norandom We currently don't have plans to do this in Graylog. This being said, you could use Drools to rewrite the message accordingly (at the cost of a moderate performance hit).
