### ISSUE TITLE
2.0 - favicon broken

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#1765]
`    <link rel="shortcut icon" href="/favicon.png">` Doesn't work, but the original `/assets/images/favicon.png` still works fine, so I think that should be moved or it's reference updated

**Comment by dennisoelkers** [comment]
The favicon is accessible via `/favicon.png` in the web interface for sure. Could you please make sure you are accessing the web interface of the alpha, clear your browser caches and retry?

**Comment by SjonHortensius** [comment]
you are right. I'll check why my browser won't display it but it is indeed there
