### ISSUE TITLE
2.0 Web-interface now contacts :12900 directly, breaking f/w and https wrapper

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#1766]
I think merging graylog with web-interface is a good move; but it has a few undocumented consequences:

* The webinterface now directly contacts the graylog node on port 12900; meaning the firewall needs to allow this (previously you didn't need access to this port from the client)
* I use nginx with proxy_pass to serve interface over https; this breaks now that the interface contacts graylog directly, it throws: `Blocked loading mixed active content "http://xxx:12900/system/sessions"` when attempting to login

**Comment by dennisoelkers** [comment]
Thanks. We will continue to improve the documentation and include necessary steps for setup/migration.
For your nginx setup you need to make sure that the REST API is using SSL if your nginx is. Configured `rest_enable_tls`, `rest_tls_cert_file`, `rest_tls_key_file` and `rest_tls_key_password` as well as switching `rest_transport_uri` to https in your graylog config file should do this.

**Comment by SjonHortensius** [comment]
Nginx makes it a lot easier to secure Graylog; so I'll document my final solution:

```
server
{
	listen		443 ssl spdy;
	server_name	example.org;

	location /api
	{
		proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header	Host $http_host;
		proxy_pass		http://localhost:12900;
	}

	location /
	{
		proxy_set_header	X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header	Host $http_host;
		proxy_pass		http://127.0.0.1:9000;
	}
}
```
in my graylog.conf:
```
rest_listen_uri = https://example.org:12900/api
rest_transport_uri = https://example.org:443/api
```

This also removes the need to open up port 12900 for clients as they'll use this proxy instance. Thanks for pointing me in the right direction.

**Comment by dennisoelkers** [comment]
That's another way of doing it. I would generally recommend to secure the communication all the way using SSL (including the transport between nginx and the graylog server), but I understand that this way it's much easier for you.

Thanks much for sharing your nginx config with us. We will include it in our documentation.

**Comment by SjonHortensius** [comment]
Changing rest_transport_uri also makes other nodes use this proxy, which might not be desirable
