### ISSUE TITLE
add more info to the docs/readme regarding startup/restarts after preflight

### ISSUE THREAD

**Issue by mako42** [Graylog2/graylog2-server#17702]
if you finished preflight etc. and want to stop/start the installation (especially running docker) we should make sure that the datanodes are started before the graylog nodes. this should be included (if it is not already) in the docker startup files

**Comment by todvora** [comment]
This will be obsolete and fixed with https://github.com/Graylog2/graylog2-server/pull/17758. The graylog server will wait till a datanode is available.

**Comment by janheise** [comment]
done
