### ISSUE TITLE
Different Time configuration

### ISSUE THREAD

**Issue by ggkrona** [Graylog2/graylog2-server#1772]
Hi, I’m deploying Graylog for the first time and I found that the incoming message have a incorrect timestamp. 

I already update the Graylog OS time zone, but in the Overview tab I still see one hour of difference. 
Could you helpme, sorry I’m newbie with Graylog.

Best Regards.
![time conf](https://cloud.githubusercontent.com/assets/17068603/12845398/c22cfbfc-cc05-11e5-8d63-67828f9a3e43.png)

**Comment by joschi** [comment]
You can set the timezone for the Graylog web interface using the `timezone` setting (see https://github.com/Graylog2/graylog2-web-interface/blob/1.3/misc/graylog-web-interface.conf.example#L14-L17) and for the "admin" user in general using the `root_timezone` setting for Graylog server (see https://github.com/Graylog2/graylog2-server/blob/1.3.3/misc/graylog2.conf#L28-L31).

In general, please post support questions about Graylog to [our mailing list](https://groups.google.com/forum/#!forum/graylog2) or join [#graylog on freenode](https://webchat.freenode.net/?channels=%23graylog) as we try to use GitHub issues exclusively for bug reports and feature requests.
