### ISSUE TITLE
Time size optimizing range picker overlaps itself with short retentions

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/graylog2-server#17727]
When attempting to set a short-range retention range for Time Size Optimizing, the values can easily overlap each other, making it difficult to accurately set them, or adjust them in the future. 

In this screenshot, I've set a 7-10 range on this index:

![image](https://github.com/Graylog2/graylog2-server/assets/2953243/ae2b95c2-5d41-4961-9584-08df33b77fd0)

It would be worthwhile to set this slider bar to "zoom" on shorter ranges, or have additional text boxes that can type the days in, rather than having the user try to grab and slide a dot to target specific days. While anything is possible, it's not expected that customer would need to retain e.g. 111 to 127 days, so individual day adjustment is likely not necessary. The bar should still be retained as a visual reinforcement that it's a range. 

## Your Environment

* Graylog Version: Graylog 5.2.2+8eab621
* OpenSearch Version: 2.9
* MongoDB Version: 5
* Operating System: Debian 12
* Browser version: Chrome Version 120.0.6099.109 (Official Build) (arm64)

**Comment by tellistone** [comment]
This UI component is going to be legacy in 6.0

**Comment by damianharouff** [comment]
Fixed in newer versions with a different UI layout

![Image](https://github.com/user-attachments/assets/648cf433-4823-4fb0-9f0b-0be62dfd9fb2)
