### ISSUE TITLE
Expose Logs of OpenSearch

### ISSUE THREAD

**Issue by moesterheld** [Graylog2/graylog2-server#17730]
Make the logs of the data node's OpenSearch available in the UI.
This should also include the logs for remote reindexing in the migration wizard.

**Comment by todvora** [comment]
Currently the datanode provides https://localhost:8999/logs/stdout and https://localhost:8999/logs/stderr by default. See https://github.com/Graylog2/graylog2-server/blob/master/data-node/src/main/java/org/graylog/datanode/rest/LogsController.java. We just need a proxy or access to the datanode REST from the graylog server to access these.

**Comment by todvora** [comment]
Both stdout and stderr now available through the datanode proxy:

http://localhost:9000/api/datanodes/rest/logs/stdout
http://localhost:9000/api/datanodes/rest/logs/stderr
