### ISSUE TITLE
Graylog 2.0.0 alpha OVA `sudo graylog-ctl reconfigure` fails on installing tzdata

### ISSUE THREAD

**Issue by EraYaN** [Graylog2/graylog2-server#1776]
Sadly due to the way my VMWare tty works I can't copy the output but I can screen capture it.

So here it is: 
Page1: http://imgur.com/zoAnxQX
Page2: http://imgur.com/JllUsgf

It blocks changing the default admin password (Or anything really)

Version: Graylog 2.0.0-alpha.1 (2db6b2e) on graylog-beta (Oracle Corporation 1.8.0_66 on Linux 3.19.0-25-generic)

**Comment by mariussturm** [comment]
Is the VM connected to the internet? It tries to install a standard Ubuntu package, which failes in your case. In doubt run `sudo apt-get update` manually before the reconfigure.

**Comment by EraYaN** [comment]
It is connected to the internet, it even receives logs already.

The package tzdata is already installed. (The OVA I'm using is the one provided by this project).

And as reference the non beta OVA it DOES work.

They run in VMWare Workstation (12) on a Windows 10 machine with bridged networking.

**Comment by mariussturm** [comment]
Could you please run `sudo apt-get update` followed by `sudo graylog-ctl reconfigure` to see if the problem is persistent?

**Comment by EraYaN** [comment]
Here is the video of it working, it seems like it is an issue, that only crops up just after install. Now (as you can see in the video it DOES update itself on the apt-get-update-periodic task.

https://erayan.com/shared/2016-02-08_17-53-33.mp4

So it seems something is off with the timing on time of install.

**Comment by mariussturm** [comment]
This will be improved in the next alpha!
