### ISSUE TITLE
How do I migrate 2 graylog servers into one? 

### ISSUE THREAD

**Issue by nensto** [Graylog2/graylog2-server#1779]
I wish to migrate 2 Graylog servers and their corresponding local ES, Mongo nodes into one server. 
What is the best practice to do, having in mind that data (their Graylog indices) could overlap, in terms of creation date, but not value ?

**Comment by joschi** [comment]
Please move this discussion to [the public mailing list](https://groups.google.com/forum/#!forum/graylog2) or to [#graylog on freenode](https://webchat.freenode.net/?channels=%23graylog). We try to use GitHub issues exclusively for bug reports and feature requests.
