### ISSUE TITLE
Compiling graylog 

### ISSUE THREAD

**Issue by weird-oecophylla** [Graylog2/graylog2-server#17850]
Compiling graylog 5.1.9 and using the compiled graylog.jar (without any code modification)

## Expected Behavior
I am trying to compile graylog 5.1.9. I would like to use the compiled graylog.jar to replace the graylog.jar obtained from the manual installation from deb package (https://go2docs.graylog.org/5-0/downloading_and_installing_graylog/ubuntu_installation.html).

## Current Behavior

I encounter no error during the compiling process.
Once graylog.jar replaced in /usr/share/graylog/, graylog-server cannot start anymore.Here are the graylog-server service logs:

```
janv. 02 13:33:57 DEV-X systemd[1]: Started Graylog server.
janv. 02 13:33:58 DEV-X graylog-server[110224]: Exception in thread "main" java.lang.NoClassDefFoundError: com/github/rvesse/airline/Cli
janv. 02 13:33:58 DEV-X graylog-server[110224]:         at org.graylog2.bootstrap.Main.main(Main.java:29)
janv. 02 13:33:58 DEV-X graylog-server[110224]: Caused by: java.lang.ClassNotFoundException: com.github.rvesse.airline.Cli
janv. 02 13:33:58 DEV-X graylog-server[110224]:         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
janv. 02 13:33:58 DEV-X graylog-server[110224]:         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
janv. 02 13:33:58 DEV-X graylog-server[110224]:         at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
janv. 02 13:33:58 DEV-X graylog-server[110224]:         ... 1 more
janv. 02 13:33:58 DEV-X systemd[1]: graylog-server.service: Main process exited, code=exited, status=1/FAILURE
janv. 02 13:33:58 DEV-X systemd[1]: graylog-server.service: Failed with result 'exit-code'.
```

## Possible Solution
I am sure there is something I miss when compiling / integrating the freshly compiled graylog.jar. But I can't find what.

I confirm the missing class com.github.rvesse.airline.Cli indicated in logs is present in project when compiled.

## Steps to Reproduce (for bugs)

- Install graylog 5.1.9 following the manual instruction from : https://go2docs.graylog.org/5-0/downloading_and_installing_graylog/ubuntu_installation.html

- git clone https://github.com/Graylog2/graylog2-server.git
-  checkout to 5.1.9 tag
- mvn compile
- Replace original /usr/share/graylog/graylog.jar with the freshly compiled ./graylog2-server/target/graylog.jar
- Restart graylog-server service
- sudo journalctl -n 1000 -u graylog-server -f

## Context
In a testing purpose context, I want to evaluate the complexity of recompiling graylog. However, I did not even succeed recompiling it from the original github project.

## Your Environment
* Graylog Version: 5.1.9

**Comment by dennisoelkers** [comment]
Hey @weird-oecophylla,

thanks for reporting this! Just a quick question before, why are you using your own compiled Graylog instead of precompiled packages/images?

**Comment by weird-oecophylla** [comment]
Hi @dennisoelkers,

I'm trying to experiment some modifications in the context of developing a configurable CSP setting (according to my previous issue: https://github.com/Graylog2/graylog2-server/issues/17060)

**Comment by janheise** [comment]
@weird-oecophylla I did not run your steps to reproduce it, but can you run a `mvn package` and look into the target folder again? There should be more than one jar and you have to use the jar that also contains the dependencies.

**Comment by weird-oecophylla** [comment]
Hi @janheise,

I tried `mvn package` and 3 jars were created:
- graylog2-server-5.1.9-shaded.jar  
- graylog.jar  
- graylog-tests.jar

I used the shaded version as graylog.jar and everything worked perfectly ! 

I should have guessed it because mvn outputs during compilation trace the inclusion of the libraries inside graylog2-server-5.1.9-shaded.jar :

`[INFO] Including x.x.x in the shaded jar.`

By comparison, we see the graylog.jar is 46M and graylog2-server-5.1.9-shaded.jar is 165M.

Thanks for your support !
