### ISSUE TITLE
Datanodes not coming up after reboot (Docker / Docker-Compose)

### ISSUE THREAD

**Issue by fvjb** [Graylog2/graylog2-server#17851]
After a reboot the different nodes of a Datanode cluster don't come up as expected but get stuck with a TLS/SSL issue.  

## Expected Behavior

Datanode getting ready after ~30 seconds

## Current Behavior

Datanode completely stuck, no option to get it back to life

## Steps to Reproduce (for bugs)

1. Use my docker-compose file
2. Install and Configure Graylog
3. Stop the Cluster
4. Start the Cluster

## Your Environment

* Graylog Version: 5.2.3
* Datanode Version: 5.2.3
* MongoDB Version: 6.0
* Operating System: Ubuntu 22.04

Logs: 
* Datanode1: [_graylog-security-datanode1-1_logs.txt](https://github.com/Graylog2/graylog2-server/files/13844011/_graylog-security-datanode1-1_logs.txt)

* Datanode2: [_graylog-security-datanode2-1_logs.txt](https://github.com/Graylog2/graylog2-server/files/13844013/_graylog-security-datanode2-1_logs.txt)

* Datanode3: [_graylog-security-datanode3-1_logs.txt](https://github.com/Graylog2/graylog2-server/files/13844015/_graylog-security-datanode3-1_logs.txt)

Docker-Stack: [docker-compose.yml.txt](https://github.com/Graylog2/graylog2-server/files/13843965/docker-compose.yml.txt)

**Comment by janheise** [comment]
Hi @fvjb can you please specify exactly which commands you use to stop/start? You already have a `hostname` in your `docker-compose.yml` which was the solution for other users with the same problem. But you also should only `docker compose start/stop` your services and not `up/down` them because that changes the network config.

**Comment by janheise** [comment]
fixed by adding static IPs
