### ISSUE TITLE
401 Unauthorized response from API for single node in cluster

### ISSUE THREAD

**Issue by allenderj** [Graylog2/graylog2-server#17894]
## Expected Behavior

When the API endpoint is queried the same authentication token should be able to be used against all nodes in a cluster. This way the API can be put behind a load balancer for API resiliency. 

## Current Behavior

Single node in cluster is returning a 401 when presented with a token that works on other nodes in the same cluster. This behavior is seen in sidecar logs as well. 

## Steps to Reproduce (for bugs)

1. 3 node cluster running. 
2. curl faulty node for api endpoint that requires auth. 
`curl -kv -u supersecretkey:token http://10.8.204.6:9000/api/cluster`
4. Receive 401
5. curl functional node api endpoint that requires auth
`curl -kv -u supersecretkey:token http://10.8.204.7:9000/api/cluster`
6. Receive 200 and response data

## Context

Attempting to connect sidecar to the Graylog front end via a nginx load balancer. The faulty node is the first in the upstream list so it is being used. The behavior is present when querying the nodes directly as well. I can set the sidecar to use a functional backend with no issue but this is not resilient to node failures.

## Your Environment

* Graylog Version: 5.2.3
* Java Version: Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
* OpenSearch Version: 2.9.0
* MongoDB Version: 7.0.1
* Operating System: Debian GNU/Linux 11 (bullseye)
* Browser version: curl and whatever library is used by sidecar. Works fine with standard browser via the reverse proxy/lb.

**Comment by bernd** [comment]
@allenderj Can you check if the `password_secret` value in the Graylog server config is set to the same value on all nodes? Thanks!

**Comment by allenderj** [comment]
@bernd Ya know what. They were not the same. I modified the node returning the 401 and its working now. Major oversight on my part. Thank you for the help.

**Comment by bernd** [comment]
> @bernd Ya know what. They were not the same. I modified the node returning the 401 and its working now. Major oversight on my part. Thank you for the help.

Thanks for the update! :pray: I am glad it's working now.
