### ISSUE TITLE
key_value function: parameter allow_dup_keys/handle_dup_keys missbehaving/wrong documentation

### ISSUE THREAD

**Issue by ihe-nu** [Graylog2/graylog2-server#17892]
## Expected Behavior
I do use the key_value()-function from the ruleset to evaluate KV-pairs in messages. About the two parameters from this case the documentation from the quick lookup in Graylog states:
```
allow_dup_keys	Boolean		Whether to allow duplicate keys, defaults to true
handle_dup_keys	String		How to handle duplicate keys: 'take_first': only use first value, 'take_last': only take last value, default is to concatenate the values
```
I would expect:
* allow_dup_keys to always be true by default. If I don't set any additional parameters I would not loose information
* handle_dup_keys to be configurable to either take the first or last value, or to concatenate them all.
## Current Behavior
*  allow_dup_keys seems to be false by default, only if  handle_dup_keys  is set it changes by magic to true
*  handle_dup_keys: my input becomes the delimiter for values.

## Possible Solution
* update documentation
* allow handle_dup_keys to add the values to an array as another option (maybe feature-request?)

## Context
We are parsing messages from Check Point with layered rules. The same key appears with different values.

## Your Environment

*  Graylog Version: 5.2.2

**Comment by bernd** [comment]
Ref: HS-2253230414

**Comment by kodjo-anipah** [comment]
@ihe-nu  Thank you for bringing this issue to our attention. It's important to note that a pipeline function is limited to a single return type. Specifically, in the case of the `key_value` function, the expected return type is a `Map<String, String.`

If there is a requirement to transform certain fields into arrays, one potential approach is to utilize multiple functions within the pipeline. For instance, you could employ the split function to achieve the desired array transformation.

**Comment by ihe-nu** [comment]
Hi @kodjo-anipah 
Thank you for bringing the fix for the documentation on the way!
I agree, that a second step in the processing with the split-function could do the job. In my case I do know what values to expect and I should be able to find an delimiter which will never appear in the logs. But that will not be always the case and therefore a general solution would be great. Can a Map with several fields never contain a single field with an array as a content?

**Comment by kodjo-anipah** [comment]
@ihe-nu the only possibility here would be to create a string representation of the array and store it in the the map. If I use the set_fields function afterwards in hope of getting this array set properly lets say, all I get really is a string that actually makes it more difficult to query for results.
