### ISSUE TITLE
Need to import maven dependencies for lucene, carrotsearch and scala

### ISSUE THREAD

**Issue by sachingsachin** [Graylog2/graylog2-server#1791]
While trying to build graylog2 using 'Apache Maven 3.3.9' and Oracle JDK version "1.8.0_71", maven complains about several missing types and imports.

They are resolved by importing the relevant dependencies into the pom.xml files as shown in the attached patch.

[pom-dependencies.patch.txt](https://github.com/Graylog2/graylog2-server/files/123948/pom-dependencies.patch.txt)

**Comment by joschi** [comment]
I'm pretty sure there's something broken with your development setup. The current project builds fine locally (on every developer's machine), on Travis CI, and on Jenkins CI without modification of the Maven POM.

All those dependencies you've mentioned are transitive dependencies and should be pulled in automatically by Maven's dependency resolution mechanism.

Please understand that we don't have the resources to help you debug your development setup.
FWIW, you can take a look at the [`.travis.yml`](https://github.com/Graylog2/graylog2-server/blob/master/.travis.yml) file (which describes a working build) and work your way from there.

**Comment by sachingsachin** [comment]
I have built several open source projects in my environment including Solr, Avro and Hive and they all built just fine, not to mention several projects from other teams in my company.

My environment:

1. Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T08:41:47-08:00)

2. java version "1.8.0_71"
Java(TM) SE Runtime Environment (build 1.8.0_71-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.71-b15, mixed mode)

3. OS is OS X Yosemite (10.10.5)

If it works for you on a Mac, please share the above details.

Thanks!

**Comment by joschi** [comment]
The Maven build is working on my machine using the following Java environment:
```
$ mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_72, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.3", arch: "x86_64", family: "mac"
```
Since Travis CI and Jenkins CI also work, I still suspect a locally broken development environment on your end.
