### ISSUE TITLE
2.0 web_enable_tls + rest_transport_uri - Rest service still uses http

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#1792]
I've enabled web_enable_tls and updated my rest_transport_uri

```
web_enable_tls = true
rest_transport_uri = https://xxx:12900/
```

but it doesn't seem to work:

```
org.graylog2.shared.initializers.RestApiService - Started REST API at <http://xxx:12900/>
```

The Rest API still doesn't use TLS meaning my browser only throws an error when trying to login:

`Blocked loading mixed active content "http://xxx:12900/system/sessions"`

**Comment by joschi** [comment]
If you want to enable TLS for the Graylog REST API, you'll have to use [`rest_enable_tls `](https://github.com/Graylog2/graylog2-server/blob/2.0.0-alpha.1/misc/graylog.conf#L56-L59) and related settings. The Graylog REST API and the embedded web interface are two different internal services.
