### ISSUE TITLE
Flaky UI for bulk actions for event definitions 

### ISSUE THREAD

**Issue by patrickmann** [Graylog2/graylog2-server#17970]
UI for bulk actions on the event defintions page is flaky:
- nothing happens after clicking confirm button
- confirm dialog keeps popping up when I try to select a different bulk action from the drop down

It's not completely consistent but happens very frequently.

GL version: 6.0

**Comment by linuspahl** [comment]
@patrickmann I noticed this too and fixed it with https://github.com/Graylog2/graylog2-server/pull/17936
