### ISSUE TITLE
no way to customize index mapping in graylog 5.2.3 

### ISSUE THREAD

**Issue by macaty** [Graylog2/graylog2-server#17983]
After upgrading to the latest version graylog5.2.3, there is no way to customize index mapping through the opensearch API after the original opensearch becomes datanode.
![image](https://github.com/Graylog2/graylog2-server/assets/16797633/6a957b2e-0c8a-4013-8e44-0952ed0401d2)

reference document:
https://go2docs.graylog.org/5-2/setting_up_graylog/elasticsearch.htm?tocpath=Setting%20up%20Graylog%7CGetting%20Started%7CInitial%20Configuration%20Settings%7C_____6
![image](https://github.com/Graylog2/graylog2-server/assets/16797633/11ba2399-85b7-4842-b8f1-38478315fdad)

Environment
install file :https://github.com/Graylog2/docker-compose.git
* Graylog Version:graylog/graylog:5.2.3
* Java Version:
* OpenSearch Version: graylog/graylog-datanode:5.2
* MongoDB Version: mongo:5.0
* Operating System: docker

**Comment by janheise** [comment]
Hi @macaty , thx for reporting this. You try using port 9200, correct? This is no longer possible with the DataNode because of changes in security/auth mechanisms. We created a proxy to facilitate changes like that via the graylog port. I have to check if it's in 5.2 or only in our current master. If it's only in the master, we'll backport it into into the next bugfix release.

**Comment by macaty** [comment]
Yes，thx，we are expecting your latest solution

**Comment by luk-kaminski** [comment]
Hi @macaty,
I've noticed your problem and just wanted you to know that from version 5.2.0 you can change field type using the GL interface, without a need to do it on ES/OS directly.

Maybe this new functionality solves your problem already?


![Screenshot 2024-03-27 at 10-16-37 Graylog - Unsaved Search](https://github.com/Graylog2/graylog2-server/assets/100699120/09d87601-6342-4815-bae8-78fd8ce8ba6b)


![Screenshot 2024-03-27 at 10-16-58 Graylog - Unsaved Search](https://github.com/Graylog2/graylog2-server/assets/100699120/7cdd1942-3d08-46d4-a259-7b62e5f13e71)

**Comment by macaty** [comment]
Thast's great feature and has solved the problem!

**Comment by luk-kaminski** [comment]
Great to know! :)
In that situation I am closing the ticket. :)
