### ISSUE TITLE
Geo subdivisions in pipeline no longer work

### ISSUE THREAD

**Issue by smwinn** [Graylog2/graylog2-server#18017]
## Expected Behavior
I expect this line within a pipeline rule to work without errors like in previous versions.

## Current Behavior
The line now gives an error and cannot be saved. I can see the subdivisions information when examining the geo data manually.
![Screenshot 2024-01-22 131237](https://github.com/Graylog2/graylog2-server/assets/58242686/4b21c771-aad2-4e15-8872-ab9f51b90895)

## Steps to Reproduce (for bugs)
Create a pipeline rule that attempts to access the geo subdivisions data.

## Context
I'm trying to use the subdivisions field within geo location data.

## Your Environment
* Graylog Version: 5.2.3
* Java Version: 17.0.9+9
* OpenSearch Version: 2.11.1
* MongoDB Version: 5.0.24
* Operating System: Ubuntu 22.04.3 LTS
* Browser version: Any

**Comment by sethgraylog** [comment]
What previous version did you see this syntax work correctly?

**Comment by smwinn** [comment]
I believe it broke when I went from 5.1 to 5.2.

**Comment by patrickmann** [comment]
This is due to #16196. While that flags some bad syntax, it was too broad and now prevents legal expressions. 
I commented out those 3 lines and was able to extract the geoIP data successfully.

**Comment by drewdin** [comment]
I am still having this same issue in 6.2
