### ISSUE TITLE
2.0 - pagination doesn't work

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#1802]
When attempting to view more then 1 page of messages, the count (under *Search Results*) looks good, as does the histogram. However, the actual messages are wonky:

* Selecting a different page results in a different page-number being selected, but messages don't really change (I effectively cannot view messages past page one).
* Number of pages is incorrect (eg, 300 Results / 10-per-page results in 3 pages?)

**Comment by kroepke** [comment]
This is a know issue and will be fixed in alpha.2.

Please see #1775 

Thanks for your report!
