### ISSUE TITLE
Graylog 2.0.0 alpha conf/log4j.xml does not work for org.graylog2.rest.accesslog

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/graylog2-server#1804]
The following log4j configuration used to work for 1.3, but on 2.0.0 alpha it does not enable [RestAccessLog](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/shared/rest/RestAccessLogFilter.java)'s debug logging. 

```
    <!-- Appenders -->
    <appender name="accesslog" class="org.apache.log4j.FileAppender">
        <param name="File" value="/var/log/graylog/server/access.log" />
        <param name="Append" value="true" />
        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern" value="%t %-5p %c{2} - %m%n"/>
        </layout>
    </appender>
    <!-- Application Loggers -->
    <logger name="org.graylog2.rest.accesslog">
        <level value="debug"/>
        <appender-ref ref="accesslog"/>
    </logger>
```

I checked also /system/loggers, and there is no effect.

**Comment by joschi** [comment]
Graylog 2.x has switched to [Log4j 2](https://logging.apache.org/log4j/2.x/) while previous versions have been using [Log4j 1.2](https://logging.apache.org/log4j/1.2/).

Please refer to the [Log4j Migration Guide](https://logging.apache.org/log4j/2.x/manual/migration.html) for information how to update your configuration.

**Comment by mikkolehtisalo** [comment]
Btw, the /opt/graylog/conf/log4.xml that is loaded with -Dlog4j.configuration=file:///opt/graylog/conf/log4j.xml parameter is still in Log4j 1.2 format, at least in the Graylog v2.0-alpha.2 OVA.

**Comment by joschi** [comment]
@mikkolehtisalo Thanks for the hint! We'll fix that in the next version of the virtual appliances.
