### ISSUE TITLE
Index Set: Default index set Loading

### ISSUE THREAD

**Issue by budim88** [Graylog2/graylog2-server#18088]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 4.2
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by sethgraylog** [comment]
No content found, please resubmit the issue if this persists

**Comment by luk-kaminski** [comment]
No content submitted, closing the issue.
