### ISSUE TITLE
event 4740 on domain controllers

### ISSUE THREAD

**Issue by Malzbier2** [Graylog2/graylog2-server#1809]
Hello,

we use graylog 1.3 to collect security events on our domain controllers.
Especially event 4740 (locked domain accounts) is interesting for us.
We created a stream "Active Directory" that sends us an E-Mail when event 4740 is recorded on a DC.

The problem is that in the E-Mail the locked account is not displayed completely. Only the first 3 or 4 letters are displayed. The rest is shortened with "(...)".

Here is an example of such an E-Mail:
---   snip  ---
##########
Alarm Beschreibung: Stream received messages matching <event_id:"4740"> (Current grace time: 0 minutes)
Datum mit Uhrzeit: 2016-02-12T13:39:40.099Z
betrifft: Active Directory
Beschreibung: Active Directory Domain Controllers
dc1.abc.intra
Stream URL: Please configure 'transport_email_web_interface_url' in your Graylog configuration file.

ausgeloeste Aktion: 9adfcfd8-f591-4c84-8c5f-dfc8838810e3:FIELD_CONTENT_VALUE={field: event_id, value: 4740}, stream:={569df019e4b0abec540cc1fb: "Active Directory"}
Bitte im DC Active Directory im Sicherheits-Eventlog für naehere Infos nachschauen.
##########

Last messages accounting for this alert:
source: dc1.abc.intra | message: Ein Benutzerkonto wurde gesperrt.

Antragsteller:
Sicherheits-ID:S-1-5-18
Kontoname:DC1$
Kontodomäne:abc
Anmelde-ID:0x3e7

Gesperrtes Konto:
Sicherheits-ID:S-1-5-21-222171947-1810310173-184960113-501
Kontoname:Gastko (...) { event_record_number: 312509132 | gl2_remote_ip: 1.2.3.4 | gl2_remote_port: 49346 | event_source: Microsoft-Windows-Security-Auditing | event_time_generated: 2016-02-12T13:39:10.000Z | gl2_source_input: 55910b04e4b0f99e40c86311 | event_time_written: 2016-02-12T13:39:10.000Z | event_type: 8 | event_category_string: (13824) | event_log_name: Security | gl2_source_node: f2e033c9-c3a4-4f17-8b88-f880dd912b1a | event_type_string: Success Audit | timestamp: 2016-02-12T13:39:10.000Z | gl2_source_collector: f0878d10-9fa9-4da7-9cda-333be370032d | level: 6 | streams: [569df019e4b0abec540cc1fb] | event_category: 13824 | version: 1.1 | gl2_source_collector_input: win-eventlog-security | event_id: 4740 | _id: 03484fa1-d18e-11e5-9425-005056b852b7 | event_computer_name: dc1.abc.intra }
---   snap  ---

As you can see the account name (Kontoname) is displayed as "Gastko (...)".
We need the complete account name displayed ("Gastkonto" ) and not shortened with "(...)".

How can we modify the E-Mail to display the complete account name?

mfg
Matthias

**Comment by joschi** [comment]
The default template for the email alert callback is using the `toString` method of the [`Message`](https://github.com/Graylog2/graylog2-server/blob/1.3.3/graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/Message.java#L212-L236) class.

You can add any message field completely to the generated email, e. g. `message.message` for the complete message text. See http://docs.graylog.org/en/1.3/pages/streams.html#email-alert-callback for details.

If you have more general questions about Graylog, please post them to [the mailing list](https://groups.google.com/forum/#!forum/graylog2) or [join the discussion in #graylog on freenode](https://webchat.freenode.net/?channels=%23graylog).

**Comment by Malzbier2** [comment]
Hello Joschi,

thank you for your quick answer.
Your hint with "http://docs.graylog.org/en/1.3/pages/streams.html#email-alert-callback" solved our problem.

We made the following change in "Editing Alarm Callback":

we replaced the line
"${foreach backlog message}${message}"
with
"${foreach backlog message}${message.message}"

and that was it.


Now the message looks like this:
--- snip ---
##########
Alarm Beschreibung: Stream received messages matching <event_id:"4740"> (Current grace time: 0 minutes)
Datum mit Uhrzeit: 2016-02-15T07:29:40.099Z
betrifft: Active Directory
Beschreibung: Active Directory Domain Controllers
dc1.abc.intra
Stream URL: Please configure 'transport_email_web_interface_url' in your Graylog configuration file.

ausgeloeste Aktion: 9adfcfd8-f591-4c84-8c5f-dfc8838810e3:FIELD_CONTENT_VALUE={field: event_id, value: 4740}, stream:={569df019e4b0abec540cc1fb: "Active Directory"}
Bitte im DC Active Directory im Sicherheits-Eventlog für naehere Infos nachschauen.
##########

Last messages accounting for this alert:
Ein Benutzerkonto wurde gesperrt.

Antragsteller:
	Sicherheits-ID:		S-1-5-18
	Kontoname:		DC1$
	Kontodomäne:		abc
	Anmelde-ID:		0x3e7

Gesperrtes Konto:
	Sicherheits-ID:		S-1-5-21-222171947-1810310173-184960113-501
	Kontoname:		Gastkonto

Weitere Informationen:
	Aufrufcomputername:	PC42915
--- snap ---

This doens't only solve the problem that the locked account "Gastkonto" wasn't displayed completely it also makes the E-Mail look much better and makes it more readable. It now looks like the event log message in the original windows event.

Perhaps this could be a suggestion for the developers to produce better E-Mail messages for windows events.

mfg
Matthias
