### ISSUE TITLE
Export Functionality Error in Graylog 4.3.15 with Elasticsearch Exception

### ISSUE THREAD

**Issue by artur-akh** [Graylog2/graylog2-server#18115]
## Expected Behavior

The export logs feature in Graylog should successfully download the filtered logs without any errors.
## Current Behavior

In Graylog version 4.2.13, attempting to export logs with specific filters resulted in downloading an empty file. Since upgrading to Graylog 4.3.15, the export logs feature encounters an Elasticsearch exception related to gl2_message_id and text field optimization for aggregations and sorting.
## Possible Solution

Seeking solutions that do not involve modifying the mapping of gl2_message_id to keyword or setting fielddata=true. Alternative methods for resolving this, possibly by excluding gl2_message_id from the export query, would be preferred.
## Steps to Reproduce (for bugs)

Upgrade from Graylog 4.2.13 to 4.3.15.
Apply specific filters in the export logs feature.
Attempt to export logs.
Encounter the Elasticsearch exception.

## Context

This issue hinders the effective use of the export feature, which is essential for log analysis and management in our operations.
## Your Environment

* Graylog Version: 4.3.15

**Comment by artur-akh** [comment]
`ElasticsearchException[Elasticsearch exception [type=illegal_argument_exception, reason=Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [gl2_message_id] in order to load field data by uninverting the inverted index. Note that this can use significant memory.]]`

**Comment by dennisoelkers** [comment]
Hey @artur-akh,

thanks for reporting this! 4.2.x is not supported anymore, so we fix issues only if they are security-related or cause data loss. Is there a reason why you are not on 5.2.x yet?

**Comment by artur-akh** [comment]
I successfully resolved the issue by manually adding the gl2_message_id field to my index, and everything is now functioning correctly on version 4.3.15. Thank you!

**Comment by artur-akh** [comment]
```
resource "elasticsearch_component_template" "haproxy" {
  name = "haproxy-index-template"
  body = <<EOF
{
  "template": {
    "mappings": {
      "properties": {
        "gl2_message_id": {
          "type": "keyword"
        }
      }
    }
  }
}
EOF
}
```

**Comment by dennisoelkers** [comment]
I am wondering why this is necessary, it should be set up by Graylog itself during index rotation. Did you modify the index mappings/templates before?
