### ISSUE TITLE
v2.0.0-alpha.2: Add to search query

### ISSUE THREAD

**Issue by roland-hill** [Graylog2/graylog2-server#1813]
The "Add to search query" does not function in the v2.0 alpha 2 release.

That is, when I have created a "Quick Values" graph, clicking on the hour-glass for the "Add to search query" doesn't do anything.

Browser is Google Chrome Version 48.0.2564.109 (64-bit) on Ubuntu 15.10, 64bit.

**Comment by bernd** [comment]
This was also reported in #1797 and has already been fixed in 4303bd8 so it will be in the next alpha.

Thank you for testing alpha.2 and reporting this! :smiley:
