### ISSUE TITLE
Allow read-only access to the datanode for applications such as Grafana

### ISSUE THREAD

**Issue by Pearson-k** [Graylog2/graylog2-server#18145]
## What?
Allow read-only access to the data within the indices in the data node so that it can be leveraged by other tools which can hook into OpenSearch.

## Why?
Currently, the data node doesn't allow any third-party access to the data within Graylog. However, it is a common use case to leverage tools such as Grafana to leverage the data within Graylog in a different way without the need to ingest that data twice in both tools.

**Comment by kroepke** [comment]
Nothing is fundamentally preventing 3rd party clients from accessing data node-managed Opensearch clusters. However, it exclusively uses certificates to manage access.
Thus, especially for CLI usage, Graylog needs to support generating certificates for that use case. As long as Grafana's datasource allows using certs there should be no issue.

**Comment by janheise** [comment]
client certs should work according to the docs, but we need to create the process/test https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

**Comment by janheise** [comment]
done
