### ISSUE TITLE
v2.0.0-alpha.2: elasticsearch_node_name not displaying

### ISSUE THREAD

**Issue by roland-hill** [Graylog2/graylog2-server#1814]
The elasticsearch_node_name does not appear to be parsed to elasticsearch. In ES (v2.2.0) I use the kopf plugin to view my cluster and nodes.

The node summary page looks like this:

![selection_001](https://cloud.githubusercontent.com/assets/17213829/13026887/c79c5634-d29d-11e5-88eb-bef2ccc0c3f5.png)

The top 2 nodes are graylog nodes. Note they don't display their node name.

When I view their node stat's I see their name is not populated, refer below:

![selection_002](https://cloud.githubusercontent.com/assets/17213829/13026890/f90a7426-d29d-11e5-9db5-b6bf6ce7c2ff.png)

On an ES node it is populated, and the view node stat's looks like this:

![selection_003](https://cloud.githubusercontent.com/assets/17213829/13026893/0e6513a8-d29e-11e5-8b92-36935af6a3d2.png)

Finally I have set "elasticsearch_node_name" in the server.conf file.

System is:
graylog v2 alpha2
ES 2.2.0
Ubuntu 64bit, 15.10

**Comment by joschi** [comment]
This seems to be a regression introduced in Elasticsearch 2.1.1. The node name is properly used in Elasticsearch 2.1.0. I'll investigate further.
