### ISSUE TITLE
v2.0.0-alpha.2 RestAccessLogFilter logs session id in place of username

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/graylog2-server#1815]
[RestAccessLogFilter](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/shared/rest/RestAccessLogFilter.java) logs some kind of session id (?) in place remoteUser, for example:

`2016-02-13_21:01:38.35149 2016-02-13 21:01:38,351 DEBUG: org.graylog2.rest.accesslog - 192.168.122.1 6ef0f337-7073-4be9-80ca-bb641f506944 [-] "POST cluster/1f7effbb-e6f4-4d97-a00d-ce7fc20fcf01/metrics/multiple" Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.103 Safari/537.36 200 -1`

where `6ef0f337-7073-4be9-80ca-bb641f506944` should be `admin`. The id value should be decoded automatically into proper username, for audit purposes. 

Generally audit logs should be self-sufficient, and users should be recognizable even after the user has been deleted from system. This is common requirement when you have longer data retention times than the actual system.

**Comment by kroepke** [comment]
Good point, the UI now uses the REST API directly and thus the session id shows up instead. We'll see if we can translate it.

**Comment by mikkolehtisalo** [comment]
One solution:

https://github.com/Graylog2/graylog2-server/pull/1918
