### ISSUE TITLE
Link on import/export extractors page points to a non-existent page on the Graylog website

### ISSUE THREAD

**Issue by alias454** [Graylog2/graylog2-server#1817]
When logged into the web interface; navigate to https://host.domain.tld/system/inputs/
Select "Manage Extractors"
From the Actions drop down, select either "Import Extractors" or "Export Extractors"
The link at the end of the displayed text, points to a non-existent page => "Exported extractors ... from the extractor directory on the Graylog website."

The link points to https://www.graylog.org/resources/data-sources/, which results in a 404.

Regards,
Brandon

**Comment by joschi** [comment]
Thanks for reporting this!
