### ISSUE TITLE
Dashboard shows incorrect mean values graph

### ISSUE THREAD

**Issue by zvonden** [Graylog2/graylog2-server#1818]
v1.3.3

Here is how graph looks at the search results screen:
![image](https://cloud.githubusercontent.com/assets/17200741/13045718/44002088-d3d5-11e5-80f1-c68821dc1be1.png)

Here is what is seen when it is added to a dashboard
![image](https://cloud.githubusercontent.com/assets/17200741/13045691/20c0bb32-d3d5-11e5-81ee-e422ca9315c4.png)

Could be division by 0?

**Comment by edmundoa** [comment]
Hi,

Could you please also share with us the data the widget is drawing?
You could do that by querying the REST API directly with the dashboard and widget ID. You can use the API browser Graylog includes (http://<your-graylog-server-host>:12900/api-browser), and the resource is `/dashboards/{dashboardId}/widgets/{widgetId}/value`.

If it's easier for you, you could also open your browser's developer tools, go to the network tab, and capture the response the web interface sends to the browser for that widget.

Thank you!

**Comment by zvonden** [comment]
{"result":{"1454544000":{"total_count":5019,"count":4924,"min":0.11,"max":548.56,"total":19680.44999999996,"mean":3.9968419983752965,"cardinality":0},"1454630400":{"total_count":12882,"count":12882,"min":-86399.75,"max":589.5,"total":-63533.67000000032,"mean":-4.931972519795088,"cardinality":0},"1454716800":{"total_count":12135,"count":12135,"min":0.09,"max":120.35,"total":4743.900000000051,"mean":0.3909270704573589,"cardinality":0},"1454803200":{"total_count":12194,"count":12194,"min":0.09,"max":24.23,"total":2966.4999999999623,"mean":0.24327538133507973,"cardinality":0},"1454889600":{"total_count":12598,"count":12598,"min":-86398.75,"max":607.28,"total":-62340.88000000063,"mean":-4.948474361009734,"cardinality":0},"1454976000":{"total_count":12701,"count":12701,"min":0.09,"max":498.32,"total":23517.169999999853,"mean":1.8515998740256556,"cardinality":0},"1455062400":{"total_count":12777,"count":12777,"min":0.1,"max":446.56,"total":22149.649999999983,"mean":1.7335563903889788,"cardinality":0},"1455148800":{"total_count":12637,"count":12637,"min":0.09,"max":598.11,"total":23789.199999999983,"mean":1.882503758803512,"cardinality":0},"1455235200":{"total_count":12987,"count":12987,"min":0.09,"max":607.5,"total":31577.319999999967,"mean":2.431456071456069,"cardinality":0},"1455321600":{"total_count":12198,"count":12198,"min":0.09,"max":34.13,"total":3118.7599999999684,"mean":0.2556779799967182,"cardinality":0},"1455408000":{"total_count":12255,"count":12255,"min":0.09,"max":20.42,"total":2575.6699999999746,"mean":0.210172990616073,"cardinality":0},"1455494400":{"total_count":8002,"count":8002,"min":0.09,"max":109.55,"total":3946.480000000003,"mean":0.49318670332416936,"cardinality":0}},"took_ms":80,"calculated_at":"2016-02-15T11:09:52.437Z","computation_time_range":{"from":"2016-01-15T12:09:52.355+01:00","to":"2016-02-15T12:09:52.355+01:00"}}

**Comment by zvonden** [comment]
Was trying to find out if there are any negative latencies reported, but found another bug:
Query
source:(sbssrv014) AND env:(PROD) AND logger:(obs.latency) and LatencyS<0
shows the positive LatencyS

**Comment by zvonden** [comment]
So, I found 2 big negative values in the log, so the bug is actually about search screen graph, dashboard one is correct.

**Comment by edmundoa** [comment]
Your query is not using the right syntax: the last `and` should be in uppercase, and it should use `LatencyS:<0` to look for negative values. You can see more about the search query syntax here: <http://docs.graylog.org/en/1.3/pages/queries.html#search-query-language>.

**Comment by zvonden** [comment]
yep, I have already found that, thanks. Pls see my other comment.

**Comment by dennisoelkers** [comment]
Due to the consolidation of search & dashboard graphs in `3.2.0`, this is considered to be fixed. If it is not, please reopen the issue.
