### ISSUE TITLE
Cannot remove alert receiver when user has been deleted

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#1819]
When a stream alert has email receivers configured for a user, but the user has been deleted from the system in the meantime, we cannot remove the alert receiver anymore.

Steps to reproduce:
1) create user with an email address
2) create a stream
3) create an alert
4) add user created in step 1 as alert receiver
5) remove the user in system/users
6) try to remove the user from the alert receiver section
7) an error message appears "cannot remove user"
8) user is still listed as alert receiver

**Comment by dennisoelkers** [comment]
Good catch!

**Comment by dennisoelkers** [comment]
I tried to reproduce this, but removing a previously deleted user which is listed as alert receiver works fine. Can you verify that it's still an issue for you? Closing it for now, please reopen if it's still a problem.
