### ISSUE TITLE
GROK Parser silently fails when using caret (^) at the beginning

### ISSUE THREAD

**Issue by dmuensterer** [Graylog2/graylog2-server#18238]
## Expected Behavior

When using the caret operator (^), it should function as per the GROK specifications.
E.g. by using a GROK like:
`^<%{NONNEGINT:priority}>%{NONNEGINT:version} %{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME:host} (?<application>[\w\/]+) (?<procid>\d+|-) (?<msgid>\d+|-) (?<struct_data>(\[.*\])|-) %{GREEDYDATA:syslog_message}
`
## Current Behavior

When using the caret operator in a GROK syntax, the whole parser silently fails. It doesn't produce any error messages but doesn't parse the log.

## Steps to Reproduce (for bugs)

1. Create new GROK Extractor
2. Add e.g. the following pattern: `^<%{NONNEGINT:priority}>%{NONNEGINT:version} %{TIMESTAMP_ISO8601:timestamp} %{HOSTNAME:host} (?<application>[\w\/]+) (?<procid>\d+|-) (?<msgid>\d+|-) (?<struct_data>(\[.*\])|-) %{GREEDYDATA:syslog_message}`
3. Supply any log that matches the GROK expression, e.g. `<33>1 2024-02-13T13:52:57.474642+01:00 pfSense.main.company.net snort 41943 - - [1:2033078:4] ET INFO Session Traversal Utilities for NAT`

## Your Environment

* Graylog Version: 5.2.1-1
* Java Version: 11.0.16+8-1
* MongoDB Version: 5.0.23
* Operating System: Debian 11

**Comment by nzedler** [comment]
I can confirm this issue

**Comment by dmuensterer** [comment]
A restart of graylog fixed the problem.
