### ISSUE TITLE
JSON path from HTTP API

### ISSUE THREAD

**Issue by tiagodias90** [Graylog2/graylog2-server#1825]
Hi Experts,

I'm trying to create an JSON path from HTTP API input. But I don't receive the messages.

My Settings:
headers:
path: $.user_id
target_url: http://jsonplaceholder.typicode.com/posts/1
interval: 30
override_source:
source: id
timeunit: SECONDS

What is the problem? 

One question? It is possible to receive and process various messages in a single request?

**Comment by kroepke** [comment]
If the answer I get from that URL is exactly what you used, then your json path itself is b0rked.
You are selecting `user_id` but the response contains `userId`.

Best regards,
Kay
