### ISSUE TITLE
Data Node: Start up data nodes in a configured cluster

### ISSUE THREAD

**Issue by moesterheld** [Graylog2/graylog2-server#18289]
## Expected Behavior
New data nodes joining a configured cluster should automatically be provisioned and started.

## Current Behavior
Since introducing the PREPARED state, new nodes joining after preflight will be configured, but not started any more.

## Possible Solution
rework the logic on when to trigger startup. needs to consider preflight, reindexing migration and rolling migrations.

**Comment by janheise** [comment]
done
