### ISSUE TITLE
Filter exported extractors

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#1832]
On the current master, exporting extractors include fields like `exceptions` or `metrics` that should not be exported or required to import new extractors.

**Comment by flanders301** [comment]
Clarification: <code>exceptions</code> and <code>metrics</code> are not required to import extractors.

**Comment by joschi** [comment]
The extractor import/export functionality is currently kind of a big hack and should probably be replaced with content packs completely.

@Graylog2/engineers Any opinions on removing the import/export extractor functionality?

**Comment by edmundoa** [comment]
I think content packs are the best way of doing this for the future, but there are still quite a few extractors out there that will need to be changed. I would vote for keeping the import functionality in place, but removing the export, so from now on only content packs could be exported.

**Comment by edmundoa** [comment]
This was fixed in https://github.com/Graylog2/graylog2-server/pull/1937
