### ISSUE TITLE
Parameter to disable quick values for analyzed fields

### ISSUE THREAD

**Issue by ldormoy** [Graylog2/graylog2-server#1834]
### Problem description

When using quick values on the message field, elasticsearch's fielddata cache reaches instantly the fielddata circuit breaker, which causes this error:

> [2016-02-18 10:08:53,897][WARN ][indices.breaker          ] [es_node1] [FIELDDATA] New used memory 19381320387 [18gb] from field [level] would be larger than configured breaker: 19327352832 [18gb], breaking

This has the consequence that many quick values results (also from other fields) are not displayed, until the cache gets cleaned.

An idea to circumvent this problem would be to disable quick values usage on analyzed fields, in Graylog's specific case on the message field. I was told I can edit some Graylog internal template to do this by myself, but it's quite a lot of work and I think that an "official" parameter for this would be better.
### Environment
- Graylog Version: 1.3.3
- Elasticsearch Version: 1.7.2
- MongoDB Version: 3.0.8
- Operating System: Ubuntu 14.04

**Comment by bernd** [comment]
Recent Graylog versions don't allow terms queries on analyzed fields anymore.
