### ISSUE TITLE
Keyword search: natural date tester returns 422

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#1837]
### Steps to reproduce the problem
1. Open search page in web interface
2. Change time range to "Keyword"
3. Open Browser console
4. Enter any text in keyword input
### Result

Endpoint used to validate natural date specification returns HTTP code 422, no validation is performed.
### Environment
- Graylog Version: 2.0-alpha.3-SNAPSHOT
- Elasticsearch Version:
- MongoDB Version:
- Operating System:

**Comment by dennisoelkers** [comment]
Found out that this is on purpose. We should change this to return a 200 and give back a proper response payload. Therefore leaving it open. Also invalid date specifications should be indicated.

**Comment by bernd** [comment]
The 422 response is okay, the payload should be improved.

**Comment by bernd** [comment]
This has been fixed in https://github.com/Graylog2/graylog2-server/pull/5351
