### ISSUE TITLE
JSON extractor adds "." in field names of nested JSON objects

### ISSUE THREAD

**Issue by the-Pretender** [Graylog2/graylog2-server#1841]
### Problem description
JSON extractor adds "." in field names of nested JSON objects. This is a problem as it is not supported by elasticsearch 2.* hence the fields are missing.

### Steps to reproduce the problem

1. Create a Syslog TCP input and send a message containing {"test": {"foo":"bar"}}
2. JSON extractor preview shows "desired" output, but field is never created.

### Environment

* Graylog Version: 2.0.0 alpha 3
* Elasticsearch Version: 2.2.0
* MongoDB Version: not applicable
* Operating System: not applicable

**Comment by joschi** [comment]
@the-Pretender Thanks for reporting this. We've changed the default value for the JSON extractor in d07f06f295fe9db7bfec5ef83f599ea9355dd1e5 but it seems that we forgot to update the front end part (https://github.com/Graylog2/graylog2-server/blob/2.0.0-alpha.3/graylog2-web-interface/src/components/extractors/extractors_configuration/JSONExtractorConfiguration.jsx#L27-L30).
