### ISSUE TITLE
Bug: HTTP Basic authentication works, but does not create a session

### ISSUE THREAD

**Issue by rbroemeling** [Graylog2/graylog2-server#1843]
### Problem description

We have Apache setup as a reverse proxy in-front of graylog's web interface. Apache is setup to enforce SSL and HTTP Basic authentication. The usernames are identical to the account names in Graylog, so the expectation is that a user authenticated against Apache will not have to re-log-in to Graylog.

This works -- the user authenticates against Apache and no graylog login screen is shown.

However, after the user is logged in, AJAX requests fail (so for instance the "In X / Out Y msg/s" counter fails to load in the top right, just spinning forever). After a lot of diagnostics with regards to this, we've tracked it down to clients that login via HTTP Basic authentication do not receive a session cookie from the backend, and thus don't send a session cookie with their AJAX requests -- as a result the AJAX requests fail, even though they are "authenticated" via the standard HTTP Basic authentication.

We've worked around this problem by including "RequestHeader unset Authorization" in our Apache configuration, which effectively disables the Graylog HTTP Basic auto-login and forces everyone to go through the standard Graylog login process (which properly creates them a session/sends them a session cookie), after which everything works.
### Steps to reproduce the problem
1. Have a Graylog server online, with username "foo"/password "bar".
2. Put an apache reverse proxy in front of Graylog.
3. Add apache HTTP basic authentication to the reverse proxy, require username "foo"/password "bar".
4. Access Graylog through this reverse proxy, logging in via HTTP basic authentication.
5. You'll now have access to Graylog, but anything in the Graylog UI that requires AJAX will fail.
### Environment
- Graylog Version: 1.3.3
- Elasticsearch Version: 1.7.5
- MongoDB Version: 3.2.2
- Operating System: Debian 7.9 (x64)

**Comment by bernd** [comment]
This should be solved since Graylog 2.0. Please re-open the issue if you still have this problem with Graylog 2.2. Thank you!

You also might want to look at the [SSO](https://github.com/Graylog2/graylog-plugin-auth-sso) plugin.
