### ISSUE TITLE
Feature request: Please make the "Search Result"-Element on the left side hideable

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#1844]
### Problem description

Most of the Time we have logs that are long and the readability is not good when they have a break in the graylog UI. We mainly use Full-HD screens so we wont change to a higher resolution. And a multi-screen-setup is also not really practicable for reading logs.

It would be nice if there's a way to hide the "Search Result"-Element on the left side.

The Element i mean:
![businessworkflowenablement](https://cloud.githubusercontent.com/assets/15243394/13196116/e6688e2a-d7c5-11e5-982f-d3717da4264d.png)

Thank you

**Comment by runningman84** [comment]
https://github.com/Graylog2/graylog2-web-interface/issues/1657

**Comment by mvfcva** [comment]
+1
