### ISSUE TITLE
Navigation links broken if `http_external_uri` contains a path

### ISSUE THREAD

**Issue by thll** [Graylog2/graylog2-server#18463]
## Expected Behavior

Navigation links should keep working when Graylog is hosted under a separate path.

## Current Behavior

If the `http_external_uri` contains a path, or if the `X-Graylog-Server-URL` is set to a URL that contains a path, that path is duplicated in the Navigation links which renders them broken.

## Possible Solution

Remove the duplication ;)

## Steps to Reproduce (for bugs)

1. Set up a reverse proxy to serve Graylog at http://localhost/graylog/
2. Either configure Graylog with a `http_external_uri = http://localhost/graylog/`, or make sure that all requests reach Graylog with the `X-Graylog-Server-URL` set to `http://localhost/graylog/`
3. Notice e.g. the `Search` link in the navigation bar to point to the wrong URL http://localhost/graylog/graylog/search

## Your Environment

* Graylog Version: 6.0.0-SNAPSHOT
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by nsyring** [comment]
Hello,
I have exactly the same issue and currently driving the 6.0.1.
Was this fixed in the 6.0.1 milestone?

Cheers
Niko

**Comment by groundhog2k** [comment]
I agree.. 6.0.2 is also broken. It looks like the bug that already existed in 3.0.0 and was fixed with 3.0.1 (https://github.com/Graylog2/graylog2-server/issues/5702)

**Comment by nsyring** [comment]
Yes, I agree too. Seems like nothing changed.
In the Milestones for 6.0.1 this bug is also still unfixed.
