### ISSUE TITLE
Visibility issue with inactive dashboard tab titles in dark mode

### ISSUE THREAD

**Issue by miwent** [Graylog2/graylog2-server#18512]
## Expected Behavior

All dashboard tabs & titles are clearly visible in both light mode and dark mode.

## Current Behavior

In dark mode the tabs are barely visible and the text is unreadable:

![image](https://github.com/Graylog2/graylog2-server/assets/61566003/c531519f-2b4f-4dae-bde2-b711b3a91c4c)

For comparison, light mode on the same system:

![image](https://github.com/Graylog2/graylog2-server/assets/61566003/2bfdb824-cae0-48ba-8e2c-bb426b630a10)

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

* Graylog Version: Graylog 6.0.0-alpha.2
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System: Ubuntu 22.04.6 LTS
* Browser version: Firefox 122.0.1

**Comment by linuspahl** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/pull/18558
