### ISSUE TITLE
Create stream rule from field SourceName

### ISSUE THREAD

**Issue by phoeneous** [Graylog2/graylog2-server#1851]
### Problem description

Unable to create stream rule based on field SourceName

### Steps to reproduce the problem

1.  Go to Streams
2.  Create stream from known working host
3.  Create stream rule from field SourceName
4.  Click on Stream
5.  See no results

If I can search against field SourceName why cant I create a stream rule for it?

**Comment by joschi** [comment]
Streams are only populated with new incoming messages. Existing messages will not be put into a newly created stream.

If newly arriving messages are not categorized into the stream you've defined, something might be wrong with your stream rule(s) and you should post them here along with some example messages.

**Comment by phoeneous** [comment]
Here are the messages that I'm trying to add to a stream.  In windows eventvwr, the column Source has the value that I'm looking for, MSCRMEmail.  In the detailed view of the same event it says the field is Provider Name.  When I search for MSCRMEmail in graylog, it shows the value of MSCRMEmail being in the SourceName field.  See attached screenshots.

![mscrmemail_eventvwr](https://cloud.githubusercontent.com/assets/16694745/13328589/443c30b0-dba4-11e5-8559-deda066596bf.png)

![mscrmemail_details](https://cloud.githubusercontent.com/assets/16694745/13328597/4c0dff94-dba4-11e5-87ad-82329c1cd62a.png)

![graylog_mscrmemail_stream](https://cloud.githubusercontent.com/assets/16694745/13328605/5a697442-dba4-11e5-93b0-0fe5f29030bf.png)

**Comment by phoeneous** [comment]
Bump?

**Comment by kroepke** [comment]
Your field name in the stream rule seems to include the `:` which it shouldn't.

**Comment by phoeneous** [comment]
Tried that, still nothing found in stream.

**Comment by jalogisch** [comment]
@phoeneous please update to the latest Graylog Version. This issue should be fixed.
