### ISSUE TITLE
Field types lookup does not resolve alias fields

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#18526]
Using `FieldTypesLookup#getType()` for a field that is of `type` `alias`
should return the type of the alias' target (known as `path`).

The alias field type is shown as a question mark in the UI, and when used for sorting, 
creates a broken query, because the type is copied into an `unmapped` sort order.

* Graylog Version: 6.0.0-SNAP

**Comment by luk-kaminski** [comment]
@mpfz0r - it seems that the issue related to field aliases is bigger than just solving type problems.
Even if we correct type information, the search response by definition does not contain field aliases values. We would need to translate our search responses to include aliased fields, without that we end up with smth like this (`act` is an alias for `action`):
![Screenshot 2024-03-22 at 14-14-13 Graylog - Unsaved Search](https://github.com/Graylog2/graylog2-server/assets/100699120/cae17618-f499-4b25-854a-371fbb456892)
As you see on the screenshot, sorting does not break anymore, but... we have no data for `act` alias field anyway!

A completely different approach could be to ignore aliases. Users won't know anything about their existence. If they are stubborn enough to use them, they would see the warnings, but the queries would still work:
![image](https://github.com/Graylog2/graylog2-server/assets/100699120/9603aca7-f72a-47c4-925f-e7259524fbfa)
