### ISSUE TITLE
Too many established connections with client

### ISSUE THREAD

**Issue by meghbrume** [Graylog2/graylog2-server#1856]
Hi, 
I am running graylog server 1.3 and have configured a tcp input to receive log. And I have around 12 window nxlog clients sending data to this tcp input. But the number of active connections on this single input goes quite high around 1300 which keeps on increasing. Is this expected behavior?
If no then how to close unused connections from either graylog or nxlog? Is there any setting?

**Comment by joschi** [comment]
@meghbrume 1300 active connections sound wrong for a number of 12 clients. Could you please check the number of open connections created by nxlog on each Windows system? TCP connections should usually be closed, once they're not needed anymore.

You can use `netstat` (see [View current TCP/IP protocol and connection statistics](https://technet.microsoft.com/en-us/library/cc736437(v=ws.10).aspx)) or [TCPView](https://technet.microsoft.com/en-us/sysinternals/tcpview.aspx) for this.

**Comment by meghbrume** [comment]
I will get it checked on window server but on my linux graylog server there are about 113 connections each. 
I am using GELF TCP input and have not set keepalive option. Is there anything I could add as a config to close tcp connections on graylog server?

**Comment by joschi** [comment]
@meghbrume There's no idle-connection check in Graylog for TCP-based inputs.

Please share the configuration of your GELF TCP input in Graylog (see System &rarr; Inputs in the Graylog web interface) and the configuration of nxlog on your Windows machines.

**Comment by meghbrume** [comment]
On client it is showing only one connection.

Below is my graylog input config:-
    port: 514
    tls_client_auth: disabled
    override_source:
    bind_address: 0.0.0.0
    tls_cert_file:
    tls_client_auth_cert_file:
    recv_buffer_size: 10485760
    tls_key_password: *******
    max_message_size: 2097152
    tls_key_file:

Below is my nxlog config
## This is a sample configuration file. See the nxlog reference manual about the
## configuration options. It should be installed locally and is also available
## online at http://nxlog.org/nxlog-docs/en/nxlog-reference-manual.html
 
## Please set the ROOT to the folder your nxlog was installed into,
## otherwise it will not start.
 
#define ROOT C:\Program Files\nxlog
define ROOT C:\Program Files (x86)\nxlog
 
Moduledir %ROOT%\modules
CacheDir %ROOT%\data
Pidfile %ROOT%\data\nxlog.pid
SpoolDir %ROOT%\data
LogFile %ROOT%\data\nxlog.log
 
<Extension gelf>
                Module xm_gelf
</Extension>
 
<Extension syslog>
                Module xm_syslog
</Extension>
 
<Input in>
# Use 'im_mseventlog' for Windows XP, 2000 and 2003
Module im_msvistalog
ReadFromLast    True
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WINEVT\Channels
                # HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\eventlog\System
                #
                # <Select Path='Key Management Service'>*</Select></Query>\
                # <Select Path='Internet Explorer'>*</Select></Query>\
                # <Select Path='HardwareEvents'>*</Select></Query>\
                #
                #<Select Path="Application">*[System[(Level=1 or Level=2 or Level=3)]]</Select>\
                #[System[(EventID='1')]]
                # Uncomment the following to collect specific event logs only
Query <QueryList>\
<Query Id="0">\
<Select Path="Application">*[System[(Level=1 or Level=2 or Level=3)]]</Select>\
<Select Path="System">*[System[(Level=1 or Level=2 or Level=3)]]</Select>\
<Select Path="Security">*</Select>\
</Query>\
</QueryList>
</Input>
 
<Input asa>
    Module            im_tcp
    Host  0.0.0.0
    Port   1514
    Exec  parse_syslog_bsd();
    Exec  if ( $Message =~ /^\: \%(ASA|PIX)-(\d)-(\d\d\d\d\d\d)\: (.*)$/ ) \
                { \
                   $CiscoSeverityNumber = $2; \
                   $CiscoMessageNumber = $3; \
                   $Message = $4; \
                } \
                else log_warning("does not match: " + $raw_event);  
                 
</Input>
 
<Output out>
                Module om_tcp
                Host x.x.x.x
                Port 514
                OutputType GELF_TCP
</Output>
 
<Output outasa>
                Module om_tcp
                Host x.x.x.x
                Port 515
                OutputType GELF_TCP
</Output>
 
<Route r>
Path in => out
</Route>
 
<Route r2>
Path       asa => outasa
</Route>

**Comment by meghbrume** [comment]
What can I do to solve my problem?

**Comment by meghbrume** [comment]
Can anyone help me with this one?

**Comment by jalogisch** [comment]
@meghbrume would you please update to the most latest version of nxlog and graylog and return if the issue is still present.

thank you.

**Comment by gruselglatz** [comment]
Sry for reopening this old Issue, but i see the same behaviour on the newsest Community Edition of NXLog.

Nothing special in my Config, only reading from a file and sending via TLS to Graylog.
Should i activate the Keep Alive Packages?
