### ISSUE TITLE
Issue installing Collector service on Server 2012

### ISSUE THREAD

**Issue by MattRLA2016** [Graylog2/graylog2-server#1858]
### Problem description
I can't install the collector service on Server 2012
When trying I get the below:

c:\graylog-collector-0.4.2\bin>graylog-collector-service.bat install GraylogCollector
Installing service for Graylog Collector

Service name: "GraylogCollector"
JAVA_HOME:    "C:\Program Files\Java\jdk1.8.0_73\"
ARCH:         "x64"

ERROR: Failed to install service: GraylogCollector

### Steps to reproduce the problem

1. ...

### Environment
Server 2012

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:

**Comment by kira8565** [comment]
have you try to run the jar directly？

**Comment by MattRLA2016** [comment]
Hi,
Im not sure how you mean by trying the jar directly?

I have run this command:
bin\graylog-collector.bat run -f config\collector.conf 
This works fine which is how i'm using it at the moment but it isn't ideal because I have to manually run that command if the CMD window is closed or the server is rebooted

**Comment by mikkolehtisalo** [comment]
I tested this on 2012 STD x64, same collector and Java version, and it worked. Is this a vanilla server, or is it part of domain, and is it receiving for example some kind of security hardening group policies?

Couple pointers:

- Do the files in associated logs directory contain more information? 
- Do the Windows Event Logs contain more information?

**Comment by jalogisch** [comment]
The collector is deprecated.

Please use [Graylog Sidecar](http://docs.graylog.org/en/2.1/pages/collector_sidecar.html).
