### ISSUE TITLE
Don't store generated one-shot client certificates

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#18587]
As discussed in https://github.com/Graylog2/graylog2-server/pull/18522#discussion_r1521735048, we currently store generated client certificates in a secure location on the local file system with other CA/PKI-related files.

As that is node-local, that file is not necessarily available for requests to be read in a cluster.
In this case, we only intend for a user to download this certificate with third-party clients, e.g., `curl,` dashboards like Grafana, or other custom applications requiring direct OpenSearch access.
Arguably, we don't need to store this particular certificate at all.

**Comment by todvora** [comment]
The actual file was needed just for the certificate signing process. We could replace it with an in-memory implementation that doesn't store anything in the FS while keeping the very same functionality.
