### ISSUE TITLE
collector.file.FileObserver - Too many changes occurred when watching files, we lost updates.

### ISSUE THREAD

**Issue by zivgabel** [Graylog2/graylog2-server#1859]
### Problem description
I get the following error: collector.file.FileObserver - Too many changes occurred when watching files, we lost updates.
### Steps to reproduce the problem
Happens on my system

### Environment

* Graylog Version: graylog collector 0.4.2
* Operating System: windows

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
