### ISSUE TITLE
Install graylog 2 under SLES12 (SuseLinux Enterprise Server)

### ISSUE THREAD

**Issue by j-n-s-k-n-r** [Graylog2/graylog2-server#1861]
### Problem description

Hey guy,

i need your help again.

For my work i have to install graylog on SLES 12 SP1.

But in the offical dokumention stands, that only Ubuntu, CentOs and Debain were offical supported.
Google gives my only tutorial for install on SLES 11 SP3.

Is there a workaround or a tutorial to install this on SLES?.
Or is this inpossible?

 Thank you in advance for your help

Jonas

### Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Suse Linux Enterprise Desktop 12 SP1 (SLES 12)

**Comment by joschi** [comment]
@j-n-s-k-n-r Please post general questions about Graylog to [our public mailing list](https://groups.google.com/forum/#!forum/graylog2) or [join #graylog on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).
