### ISSUE TITLE
Configuration cannot handle TimeUnit values

### ISSUE THREAD

**Issue by patrickmann** [Graylog2/graylog2-server#18645]
`Configuration` does not support type `TimeUnit`. Code should not be trying to add a `TimeUnit` value to a configuration.

## Expected Behavior

There should not be an error message when creating `SalesforceDriver`.

## Current Behavior

`SalesforceDriver` attempts to add this `TimeUnit` value to the configuration: `request.accessTokenExpiryTimeUnit()`

https://github.com/Graylog2/graylog-plugin-enterprise/blob/0d609902b67f922f6ca21e4ed40fba10737a9254/enterprise/src/main/java/org/graylog/enterprise/integrations/salesforce/api/SalesforceDriver.java#L75

This results in the following error log:

> 2024-03-11 12:15:31,671 ERROR   [Configuration] - Cannot handle type [java.util.concurrent.TimeUnit] of plugin configuration key <access_token_expiry_time_unit>. - {}
> 2024-03-11 12:15:31,689 INFO    [SalesforceDriver] - New Salesforce input created. id [65eef5e39d03297db469ab02] request [SalesforceCreateInputRequest{clientId=***, clientSecret=***, instanceName=haufe--fcs, name=hg-salesforce, throttlingAllowed=false, pollingInterval=60, pollingTimeUnit=MINUTES, logTypes=[REST_API_EVENT_TYPE, LOGIN_EVENT_TYPE, REPORT_EXPORT_EVENT_TYPE], accessTokenExpiresIn=24, accessTokenExpiryTimeUnit=HOURS}] - {}

## Possible Solution

Looks like this should have been `request.accessTokenExpiryTimeUnit().name()`

## Your Environment

* Graylog Version: 6.0.0 alpha 3

**Comment by trentgashi1** [comment]
Hi, is there any update on this case? it's been a while since it was assigned but no progress has been made since. Customer is chasing for an update and progress. Thanks

**Comment by patrickmann** [comment]
The issue is understood. Somebody needs to make the 1 line fix and ship it in a Bugfix .

@sethgraylog can you raise priority on this?

**Comment by patrickmann** [comment]
Re-open for backport to 6.0

**Comment by trentgashi1** [comment]
@patrickmann when will this be available to the customer? will it be as part of 6.1?

**Comment by patrickmann** [comment]
It is in 6.1.
It was also merged back to 6.0 on June 19. So it was included in 6.0.4
