### ISSUE TITLE
Unable to Configure Webhooks for Microsoft GCC for TeamsEventNotification's

### ISSUE THREAD

**Issue by kodjo-anipah** [Graylog2/graylog2-server#18651]
## Current Behavior

When attempting to configure a webhook with a .office365.us host endpoint within TeamsEventNotificationConfig, a validation error is thrown. This limitation prevents the configuration of notifications for Microsoft GCC environments.

## Possible Solution

Remove or improve host matching with keyword `office`i s encountered.

## Steps to Reproduce (for bugs)

Create a new  TeamsEventNotification and try to configure  a webhook url ending with .office365.us. 

## Your Environment

* Graylog Version:
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by BBruce-Graylog** [comment]
@waab76 Requesting a status update on this issue.

**Comment by kingzacko1** [comment]
@BBruce-Graylog @kodjo-anipah apologies for the delay on this one. However, it would seem that Microsoft has forced our hand a bit on the Teams Notification front. They are [retiring O365 Connectors on October 1st](https://devblogs.microsoft.com/microsoft365dev/retirement-of-office-365-connectors-within-microsoft-teams/) in favor of Workflows, so starting then the current implementation of the Graylog Microsoft Teams Notification will be completely broken, regardless of your URL being valid. But we already have a new [notification type PR](https://github.com/Graylog2/graylog2-server/pull/19983) up to be released by the September maintenance release into 5.2.x and 6.0.x. This will resolve both the invalid URL checks and Microsoft's retiring of connectors.

In the meantime, if this environment is on Graylog 6.0.x the new Custom HTTP Notification can be configured to feed Teams Notifications. If you would like some help getting that going, I'd be happy to help out.
