### ISSUE TITLE
Search results count can be 0 when adding events widget.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#18675]
## Description

The total result count in the top right corner of the search page can be 0 after adding an events overview widget.

this does not seems to be the case every time when adding a widget.

* Graylog Version: beta for 6.0

**Comment by janheise** [comment]
In `ExecutionInfo.tsx` we have the line: `  const total = result?.searchTypes && Object.values(result?.searchTypes)?.[0]?.total;`

In case, we have the events overview, it can contain an empty result set, even if the other widgets have results. And if it's the first item `[0]` in the results, we render a `0`.
