### ISSUE TITLE
As a user with Reader role, I should not be able to see System/Forwarder in the menu.

### ISSUE THREAD

**Issue by mako42** [Graylog2/graylog2-server#18689]
## Description

As a user with Reader role (only), I should not be able to see System/Forwarder in the menu. Since I do, I can click it and will be shown an awesome party gorilla. 

![image](https://github.com/Graylog2/graylog2-server/assets/111427981/43c87f79-5aec-4287-91e6-b143a1ee546f)

Upon click, I get redirected to ./notfound: 

![image](https://github.com/Graylog2/graylog2-server/assets/111427981/74ecbb05-caa0-46ac-9483-90c444d7b228)

I should not see the forwarders page in the menu, since I have no rights to do anything there as a Reader. 

## Your Environment

* Graylog Version: Graylog Cloud 6.0.0 (425) 
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by patrickmann** [comment]
Resolved by Graylog2/graylog-plugin-enterprise#6960
