### ISSUE TITLE
Override IS_MASTER with env variable

### ISSUE THREAD

**Issue by GEverding** [Graylog2/graylog2-server#1868]
### Problem description
Using docker/kubernetes to deploy graylog cluster. Need to set one of my graylog servers as master and one as slave. I have 2 containers one with a config with is_master=true and is_master=false. I'd like to be able to configure this with an env variable.

### Environment

* Graylog Version: 1.3.x
* Elasticsearch Version: 1.7.x
* MongoDB Version:
* Operating System: docker/ubuntu

**Comment by joschi** [comment]
You can override any configuration setting of Graylog using environment variables with the prefix `GRAYLOG2_`, so you can simply use the environment variable `GRAYLOG2_IS_MASTER` to do what you described.

**Comment by GEverding** [comment]
Where is that documented??

Garrett




On Sun, Feb 28, 2016 at 6:48 AM -0800, "Jochen Schalanda" <notifications@github.com> wrote:












You can override any configuration setting of Graylog using environment variables with the prefix GRAYLOG2_, so you can simply use the environment variable GRAYLOG2_IS_MASTER to do what you described.

**Comment by joschi** [comment]
> Where is that documented??

Currently only in code and in occasional mailing list/GitHub issues comments.

Feel free to write a section about it in the documentation: https://github.com/Graylog2/documentation :wink:

**Comment by GEverding** [comment]
Is this the same for graylog-web? I'm trying to override ```graylog2-server.uris``` ?

**Comment by joschi** [comment]
@GEverding The old Graylog web interface (pre-Graylog 2.0.0) does not support such overrides.
