### ISSUE TITLE
Search can't be exported after upgrade to `6.0.0-beta.2`

### ISSUE THREAD

**Issue by thll** [Graylog2/graylog2-server#18697]
## Expected Behavior

Exporting search results into CSV/JSON/etc. should work after upgrading to version `6.0.0-beta.2`

## Current Behavior

For indices existing prior to an upgrade to `6.0` exporting search results produces files that contain only a message like the following:
```
[graylog_0/V9jKmE0nQ6ep37RaJAfmJw] ElasticsearchException[Elasticsearch exception [type=query_shard_exception, reason=No mapping found for [gl2_second_sort_field] in order to sort on]]
```

## Possible Solution

@mpfz0r suggested the following fix:
```
diff --git graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/export/SearchAfter.java graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/export/SearchAfter.java
index 2866e7ff09..625c9bf1c0 100644
--- graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/export/SearchAfter.java
+++ graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/export/SearchAfter.java
@@ -23,6 +23,7 @@ import org.graylog.shaded.opensearch2.org.opensearch.action.search.SearchRequest
 import org.graylog.shaded.opensearch2.org.opensearch.action.search.SearchResponse;
 import org.graylog.shaded.opensearch2.org.opensearch.search.SearchHit;
 import org.graylog.shaded.opensearch2.org.opensearch.search.builder.SearchSourceBuilder;
+import org.graylog.shaded.opensearch2.org.opensearch.search.sort.SortBuilders;
 import org.graylog.shaded.opensearch2.org.opensearch.search.sort.SortOrder;
 import org.graylog2.plugin.Message;
 
@@ -59,8 +60,8 @@ public class SearchAfter implements RequestStrategy {
     }
 
     private void configureSort(SearchSourceBuilder source) {
-        source.sort("timestamp", SortOrder.DESC);
-        source.sort(DEFAULT_TIEBREAKER_FIELD, SortOrder.DESC);
+        source.sort(SortBuilders.fieldSort("timestamp").order(SortOrder.DESC));
+        source.sort(SortBuilders.fieldSort(DEFAULT_TIEBREAKER_FIELD).order(SortOrder.DESC).unmappedType("keyword"));
     }
 
     private Object[] lastHitSortFrom(List<SearchHit> hits) {
```

## Steps to Reproduce (for bugs)

1. Start Graylog in version 5.2
2. Ingest messages and make sure that they can be searched
3. Upgrade to Graylog 6.0.0-beta.2
4. Search for messages and then export the messages into a CSV
5. Examine the resulting CSV and confirm that it contains above mentioned error message

## Context

Probably introduced with https://github.com/Graylog2/graylog2-server/pull/18527

## Your Environment

* Graylog Version: 6.0.0-beta.2
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by mpfz0r** [comment]
Since my change caused this, I can take a look to fix this, of course.

**Comment by mpfz0r** [comment]
A test for this will be added with https://github.com/Graylog2/graylog2-server/pull/18787
