### ISSUE TITLE
Index set deletion modal doesn't close automatically

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#18693]
## Expected Behavior

The modal to delete an index set should close after clicking "Delete".

## Current Behavior

The modal stays open after deleting an index set.

[Screencast from 19.03.2024 14:02:33.webm](https://github.com/Graylog2/graylog2-server/assets/461/e158d111-134d-41b9-9682-16a733d7b4cf)

## Steps to Reproduce (for bugs)

1. Navigate to "System / Indices"
2. Click "More Actions" and then "Delete" on an index set
3. Click "Delete" in the modal
4. Observe modal not closing automatically

## Your Environment

* Graylog Version: 6.0.0-beta.2

**Comment by ousmaneo** [comment]
Fixed with #19294
