### ISSUE TITLE
Search query input in event definition form is removing its value while typing.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#18700]
## Description

The query input in the event definitions "Filter & Aggregation" step is currently removing its value while typing a query.

![query](https://github.com/Graylog2/graylog2-server/assets/46300478/a3a7f832-8877-4d47-a9e4-6e6fbbcf2775)

* Graylog Version: 6.0 beta2

**Comment by danotorrey** [comment]
I noticed the same. Behaves the same for me.

**Comment by coffee-squirrel** [comment]
Looks similar to what was happening with #16388.
