### ISSUE TITLE
Better error handling in Data Node Migration

### ISSUE THREAD

**Issue by luk-kaminski** [Graylog2/graylog2-server#18710]
## Expected Behavior
In case of errors, I can easily reset migration.

## Current Behavior
I've reached an error, without any information in the server log.

![Screenshot 2024-03-20 at 11-07-33 Graylog](https://github.com/Graylog2/graylog2-server/assets/100699120/9a2a9935-44b2-439a-a2bf-463be1a43d96)

![Screenshot 2024-03-20 at 11-10-00 Graylog](https://github.com/Graylog2/graylog2-server/assets/100699120/6b42e465-23e1-4c8b-a40f-09953f57dfcc)

The only way for me to recover from it was to remove the following document from MongoDB `cluster_config` collection:
```
{
    _id: ObjectId('65fab5bf52233252b0d8de4d'),
    type: 'org.graylog.plugins.views.storage.migration.state.persistence.DatanodeMigrationConfiguration',
    payload: {
        current_state: 'CA_CREATION_PAGE'
    },
    last_updated: ISODate('2024-03-20T10:09:49.116Z'),
    last_updated_by: 'dcae52e4-777e-4e3f-8e69-61df7a607016'
}
```

## Possible Solution
A user should always have a clean way to reset migration.

## Steps to Reproduce (for bugs)

1.  Download, install, start OS locally.
2.  Run GL.
3.  Run data-node, configure it via preflight UI.
4.  Set opensearch_data_location=/var/lib/opensearch/
5.  Go through migrations steps and follow instructions.

## Your Environment

* Graylog Version: 6.0-beta2
  * OpenSearch Version: 2.12
  * Operating System: Linux

**Comment by janheise** [comment]
Only fyi: we have a reset button on the top-right which I think would solve the issue. But in this case the FE rendering breaks the page.

**Comment by luk-kaminski** [comment]
I know, but this button is unreachable after this error occurs...

**Comment by janheise** [comment]
Ok, I wrote my reply because of the `In case of errors, I can easily reset migration.` at the top - because I think it's fair to say that you can easily reset it, unless the whole FE becomes broken :)

**Comment by todvora** [comment]
I think this has been solved during one of many refactorings we have done for the migrations. Haven't seen such problem since. Closing now, we'll reopen the issue if the problem occurs again.
