### ISSUE TITLE
Graylog Timestamps 24 Hours In The Past

### ISSUE THREAD

**Issue by ckbuckley** [Graylog2/graylog2-server#1871]
### Problem description

Following the leap day on 29/02/2016, while logs continue to get ingested by Graylog, the 'timestamp' field appears to be 24 hours in the past (logs ingested on 01/03/2016 and dated as such in the log message are instead stamped with 29/02/2016). As such, logs from today are not searchable based on time, breaking dashboards and making log analysis very difficult.

Can be observed as follows:
The following syslog message:
`Mar  1 14:57:56 quickapp uwsgi: <Greenlet at 0x7f5b14dc6410: <bound method AsyncRequest.send of <grequests.AsyncRequest object at 0x7f5b14de33d0>>(stream=False)> failed with ValueError`

Following ingestion appears with the following 'timestamp' field in Graylog:
`2016-02-29 14:57:55.000`

All timezones on servers, etc, have been checked - all are set to Australia/Brisbane and appear to be functioning without any issues.

### Steps to reproduce the problem

1. Ship messages to a standard Graylog GELF UDP input.
2. Messages ingest correctly until 23:59:59.999 on 29/02/2016
3. Messages ingested after 00:00:00.000 on 01/03/2016 are incorrectly timestamped 24 hours in the past.

### Environment

* Graylog Version: 1.3.0 (04201bb) (Hansa)
* Elasticsearch Version: 1.6.1
* MongoDB Version: 3.0.4
* Operating System: Amazon Linux 2015.03

**Comment by edmundoa** [comment]
Hi,

Could you please also include the time information you can find in System -> Overview?

**Comment by ckbuckley** [comment]
Hi Edmundo,

No worries - time information is here:

```
User admin: 2016-03-01 20:50:04.318 +10:00
Your web browser: 2016-03-01 21:50:08.577 +11:00
Web interface default JDK/JRE: 2016-03-01 20:50:04.318 +10:00
Web interface configuration: 2016-03-01 20:50:04.318 +10:00
Graylog master server: 2016-03-01 20:50:04.318 +10:00
```

**Comment by ckbuckley** [comment]
Hi guys,

We've actually traced this to an issue with rsyslog v8.16 - it appears it's the culprit, feeding incorrect Unix timestamps to Graylog in the 'timestamp' field. As such, I'm confident there's no issue with Graylog. Thank you for your time!

**Comment by joschi** [comment]
@ckbuckley Thanks for the update! Do you have more details on this issue with rsyslog? It might be interesting for other people as well.

**Comment by ckbuckley** [comment]
Hey @joschi absolutely - I submitted it over on their Github earlier today (Australia time) and it's being worked on now by the rsyslog guys. The issue is here: https://github.com/rsyslog/rsyslog/issues/830

The core of the issue looks like that when timestamps are taken by rsyslog and converted into Unix format, the conversion process is short by 24 hours (due to this years' leap day).

**Comment by joschi** [comment]
@ckbuckley Awesome. Thanks!
