### ISSUE TITLE
Graylog TCP GELF input message ingestion failure when sending via tcp socket

### ISSUE THREAD

**Issue by bhnedo** [Graylog2/graylog2-server#1875]
We have a very simple C binary that emits a GELF compatible JSON string to TCP input. On the input page we do observe traffic activity as well as packet arriving via `tcpdump` , but the message never gets indexed. Doing the same thing from `nc` ends up indexing the message correctly.

`echo -e '{"version": "1.1","host":"example.org","short_message":"A short message that helps you identify what is going on","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}\0' | nc -w 1 -v graylog 12201`

C code:

```
#include <stdio.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <string.h>
#include <arpa/inet.h>
#include <stdio.h>
#include <strings.h>
#include <unistd.h>
#include <errno.h>

int main(int argc, char* argv[]) {

  struct sockaddr_in addr;
  int err = 0;
  memset((char *) &addr, 0, sizeof(addr));
  int received = 0;

  addr.sin_family = AF_INET;
  addr.sin_port = htons(12201);
  inet_aton("192.168.1.5", &addr.sin_addr);

  int fd = socket(AF_INET, SOCK_STREAM, 0);

  if (connect(fd,
             (struct sockaddr *)&addr,
             sizeof(addr)) < 0) {
           printf("Erorr connecting graylog");
  }

  char *gelf = "{\"version\": \"1.1\",\"host\":\"example.org\",\"short_message\":\"A short message that helps you identify what is going on\" \
        \"full_message\":\"Backtrace here\n\nmore stuff\",\"level\":1,\"_user_id\":9001,\"_some_info\":\"foo\",\"_some_env_var\":\"bar\"}\r\n";

  err = write(fd,
            (const void *)gelf,
            strlen(gelf));
  if (err < 0) {
     printf("Error sending graylog");
  }

   close(fd);
}

```
### Environment

* Graylog Version: 1.2.1
* Elasticsearch Version: 1.7.2
* MongoDB Version: 2.4.14
* Operating System: Linux Centos 6.6

**Comment by joschi** [comment]
GELF TCP message must be terminated with a `\0` character (just as the example with netcat shows). Your C code snippet is terminating the GELF payload with newline characters (`\r\n`).

Since this is not very clear in the GELF specification, I've created Graylog2/documentation#58 to follow up on the issue.

**Comment by bhnedo** [comment]
Terminating the JSON string with \0 doesn't seem to fix the issue. Is there a way to enable logging on the input when the message is received? NOTE: Using the UDP GELF input and sending the messages over UDP works as expected.

**Comment by joschi** [comment]
@bhnedo You're probably running into an off-by-one error with the [`strlen(3)`](http://www.manpagez.com/man/3/strlen/) function and the terminating `\0` character.
> The strlen() function returns the number of characters that precede the terminating NUL character.

**Comment by bhnedo** [comment]
Thank you @joschi. That fixed the problem. I bet there might be a more elegant solution, but this works for me:

```
int len = strlen(gelf);
char *buffer = malloc(len + 1);

strcpy(buffer, gelf);
buffer[len + 1] = '\0';

err = write(fd,
                (const void *)buffer,
                len + 1);
```
