### ISSUE TITLE
Data Nodes not coming up after reboot (Docker / Docker-Compose) 

### ISSUE THREAD

**Issue by fvjb** [Graylog2/graylog2-server#18756]
## Expected Behavior

Data Nodes getting configured and secured in Preflight Mode. No interdependency to docker/k8s-managed IP Addresses. 

## Current Behavior

Data Nodes getting configured and secured in Preflight Mode. However, after restarting the Container(s), the Containers don't start but crash (=> reported in #17851)

## Possible Solution

Workaround from #17851: Assigning fixed IP Addresses; however, this is not a sustainable solution, as it takes away flexibility from working with Data Node Containers. 
The reason for the behaviour seems to be the following: 
`
2024-03-22T14:26:27.987Z INFO  [OpensearchSecurityConfiguration] Opensearch HTTP certificate has following alternative names: 127.0.0.1, localhost, 0:0:0:0:0:0:0:1, 0:0:0:0:0:0:0:1, datanode1, 172.20.0.103
`
Removing the additional ip-based SAN from the Opensearch HTTP certificate would represent a much better solution as flexibility in Docker would be maintained. 

## Steps to Reproduce (for bugs)

1. see #17851 

## Your Environment

Docker-Compose on Ubuntu 22.04

* Graylog Version: 6.0.0-beta.2-1
* Data Node Version: 6.0.0-beta.2-1
* MongoDB Version: 6.0.13

**Comment by janheise** [comment]
@fvjb The OpenSearch guides actually recommend adding the IP address to the SAN - and it was not working without IPs for me because of some issues with cluster building etc. that always came up. Do you have a running docker/k8s setup for OpenSearch with manually generated certs without the IPs in the SANs to look at/as a reference?

**Comment by drewmiranda-gl** [comment]
> The OpenSearch guides actually recommend/ask you to add the IP address to the SAN - and it was not working without IPs

Hi @janheise , can you clarify if this refers only to docker or opensearch certificates in general?

**Comment by janheise** [comment]
@drewmiranda-gl it's been some time, I'll re-read the OpenSearch docs and I'm wrong - no mention of IPs. AFAIR, most of the problems with certs were only relevant with docker networking.

**Comment by kroepke** [comment]
This is likely the corresponding section: https://opensearch.org/docs/2.13/troubleshoot/tls/#check-san-hostnames-and-ip-addresses
