### ISSUE TITLE
Assign opensearch node attribute to tie datanode instance with opensearch instance

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#18776]
Bind datanodes opensearch health check to specific opensearch process instance. It may happen that the management of the process fails but the underlying opensearch still runs fine. Then a watchdog restarts the process and meanwhile the healtcheck sees a healthy opensearch. This opensearch is not the currently managed one. It then confuses the watchdog, restarting its error counters, causing infinite restart loop.

**Comment by moesterheld** [comment]
@todvora sounds reasonable. that should work
