### ISSUE TITLE
2.0a4 How should I remove "legacy, individual permissions"?

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#1881]
Graylog warns me _Setting individual permissions is deprecated, please consider migrating to roles instead._

Removing the permissions (I had previously manually specified a few streams the user could Read) and clicking save seems to work. However, when reloading the page these permissions are back?

I have also removed all other roles for this user, so they are not indirectly granted permissions.

Not sure if related, but when editing this user, my console says:

> unreachable code after return statement plugin.org.graylog.plugins.map-widget.MapWidget.ddd103b678992ca86b75.js:24142:5
> mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create plugin.org.graylog.plugins.map-widget.MapWidget.ddd103b678992ca86b75.js:9906:416
> unreachable code after return statement plugin.org.graylog.plugins.map-widget.MapWidget.ddd103b678992ca86b75.js:24142:5
> unreachable code after return statement app.3ae8b0a28a3bb071fe6d.js:4773:4
> unreachable code after return statement app.3ae8b0a28a3bb071fe6d.js line 12 > eval:4773:4
> Warning: Failed propType: Required prop `username` was not specified in `EditUsersPage`. Check the render method of `ReactProxy`.

**Comment by edmundoa** [comment]
This has been fixed in #2012, please reopen if it's still happening in 2.0.0-beta.2.
