### ISSUE TITLE
Datanode Initial Setup page layout is missing top of main content

### ISSUE THREAD

**Issue by robertrea-graylog** [Graylog2/graylog2-server#18813]
The top of the main content is hidden under the top menu bar.  There is a Welcome image and additional text.

<img width="1588" alt="Pasted Graphic 3" src="https://github.com/Graylog2/graylog2-server/assets/118305846/5757c611-75d7-4286-83de-20bace7395fd">

<img width="865" alt="image" src="https://github.com/Graylog2/graylog2-server/assets/118305846/13834353-6e37-4c2c-8244-291a3a8e6abf">

## Expected Behavior
Should see Welcome image and top of main text.

## Steps to Reproduce (for bugs)
1. Go to Datanode Initial Configuration Page in Chrome

## Your Environment
* Graylog Version: 6.0.0-beta.3
* Browser version: Chrome Version 123.0.6312.59 (Official Build) (arm64)

**Comment by rich-graylog** [comment]
This is happening in Chrome and Safari.
