### ISSUE TITLE
Grok extractor expects "Store as field"  in 2.0 alpha-4

### ISSUE THREAD

**Issue by jekelundh** [Graylog2/graylog2-server#1883]
### Problem description
Grok input extractor expects "Store as field" meaning only one field per extractor can be extracted.
### Steps to reproduce the problem
1. Add input extractor from search ->message->grok
2. Apply grok pattern

### Environment
Java: OpenJDK 64-Bit Server VM (build 25.71-b15, mixed mode)
* Graylog Version: 2.0 Alpha-4
* Elasticsearch Version: elasticsearch-2.1.0-1.noarch
* MongoDB Version: mongodb-org-3.0.9-1.el7.x86_64
* Operating System: CentOS Linux release 7.1.1503 (Core)

**Comment by jekelundh** [comment]
Forgot Java version:
OpenJDK Runtime Environment (build 1.8.0_71-b15)

**Comment by kroepke** [comment]
The UI is a little misleading, the grok extractor should create multiple fields, even though the interface suggests otherwise.
Are you sure the extractor is actually broken?

**Comment by jekelundh** [comment]
Hi Kay,
The extractor works (even with multiple extractions)  but the "Store as
field" field is not populated. In 1.3.3 there is no such field so that
piece of code must have been accidentally copied from a similar function ?.
1.3.3
[image: Infogad bild 1]
2.0a4


//Johan[image: Infogad bild 2]
2016-03-04 14:16 GMT+01:00 Kay Roepke <notifications@github.com>:

**Comment by kroepke** [comment]
Ah I see, yes, then that's probably a bug when we ported the code over. Thanks!

**Comment by 123dev** [comment]
I was hoping it would allow us to extract a regex portion into the field specified in "Store as field".
For example with the following log data
kernel: DROP IN=br0 OUT=vlan2 SRC=10.1.1.15 DST=8.8.8.8
kernel: ACCEPT IN=br0 OUT=vlan2 SRC=10.1.1.15 DST=8.8.8.8

Grok pattern
kernel: (.*) IN=%{DATA:IN} OUT=%{DATA:OUT} SRC=%{IP,src} DST=%{IP,dst}

Hope to see DROP or ACCEPT in the field specified by Store as field.
I guess it was not meant to be.

Sorry to ask this question here, but it touches the grok patterns
Is it possible to do conditional match with GROK in graylog
Let say the log might or might not contain MACSRC before SRC

Thanks

**Comment by edmundoa** [comment]
@123dev, please create a new issue if you want to submit a feature. Otherwise this will become real messy :)
