### ISSUE TITLE
2.0a4 Create user / Full Name required by backend, not by frontend

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#1885]
Whey trying to create a new user, unless specifying a Full name, the submit will fail with an unclear error `Failed to create user!`. It seems to me the frontend can mark this field as required, or the backend could generate a better error. Currently it returns `HTTP/1.1 400 Bad Request` without a body

**Comment by edmundoa** [comment]
This still needs a bit more work, reopening.

**Comment by edmundoa** [comment]
Fixed in e438784, 061132d, and 4729683.
