### ISSUE TITLE
Remove "Enable index stats" button from system/indices

### ISSUE THREAD

**Issue by patrickmann** [Graylog2/graylog2-server#18877]
This button was a band-aid to deal with a performance issue (see Graylog2/graylog-plugin-enterprise#6100).
The performance problem was fixed in Graylog2/graylog2-server#18564 so we should now remove this button, as it is no longer needed.
If we want to play it safe: keep the button for now, but change it to default ON and persist user choices (see also #17145).

## Expected Behavior

Always show index stats

## Current Behavior

Index stats are off by default and only shown after clicking the `enable stats` button.

## Your Environment

* Graylog Version: 6.0.0 beta 4

**Comment by HenryTheSir** [comment]
Hello, 

please dont. In large Clusters the Index Page otherwise is not usable. 

Best regards

**Comment by patrickmann** [comment]
@HenryTheSir Have you installed 6.0 RC with the improved stats and are still having issues?

**Comment by HenryTheSir** [comment]
As its "only" an RC we did not deploy the version. 

But replaying the changes in the PR "manually" by accessing the endoints in our cluster we observe only changes in reponse size but not response time.  The response time for _cluster/stats is 4 seconds (_stats is also 4 seconds) which means that the index sets page needs (if the cluster is not in an unhealthy state) atleast 4 seconds to load. If the cluster is in trouble the time adds up and the index page gets unusable again for manually cycling indices etc.

**Comment by patrickmann** [comment]
Thanks for clarifying. We fixed the problem with excessive response size - response time wasn't mentioned in that issue.
In that case I agree we should keep the ability to toggle stats on/off.
