### ISSUE TITLE
Graylog generates a log message for a typed Grok pattern that is extracted as null

### ISSUE THREAD

**Issue by miwent** [Graylog2/graylog2-server#18883]
## Expected Behavior

No log is emitted by Graylog.

## Current Behavior

Using a Grok pattern is defined that includes a data type, such as `%{NONNEGINT:packets:int}`, and that field is extracted as `null`, leads to Graylog 6.0.0 emitting a log message `org.graylog2.plugin.Message - Ignoring invalid or reserved key packets:long for message`.

This does not impact processing, the remaining fields are assigned if the value is null and when the field (`packets` in the previous example) is extracted it functions properly and no log is emitted.

This behavior did not exist prior to Graylog 6.0.0. Adding the `clean_fields: true` option to `set_fields` will eliminate the log message.

## Possible Solution

Change the `set_fields` option `clean_fields` default to true.

## Steps to Reproduce (for bugs)

1. Create a Grok pattern with a typed extraction and provide a log that leads to a `null` value for that extraction
2. Use set_fields with the resulting map
3. Review the Graylog server log

## Context

This has the possibility of generating some log spam, but does not impact the functionality of Graylog.

## Your Environment

* Graylog Version: 6.0.0-beta.5
* Java Version:openjdk version "17.0.10" 2024-01-16
* OpenSearch Version: 2.12
* MongoDB Version: 7
* Operating System: Ubnutu 22.04.4 LTS
* Browser version:

**Comment by bernd** [comment]
@miwent Can you provide us with a rule and message example for this? I am unable to reproduce it.

The `Ignoring invalid or reserved key packets:long for message` message is logged on DEBUG, so it might be there for longer than 6.0. Do you have DEBUG logging enabled?

But still, the message field `packets:long` seems wrong.

**Comment by bernd** [comment]
> The log level is INFO - `2024-04-03 22:00:10,704 INFO : org.graylog2.plugin.Message - Ignoring invalid or reserved key packets:long for message 8a770c00-f205-11ee-942b-525400435439`

You are right. I confused myself.

Thanks for the detailed rule and data! :pray:

**Comment by bernd** [comment]
@miwent FYI: We can reproduce the issue in a unit test.

**Comment by bernd** [comment]
The same issue exists in 5.2 and earlier. (verified with the unit test in #18898) We just didn't log it on INFO before 6.0. (only DEBUG)

**Comment by bernd** [comment]
@miwent In 6.1 and the next 6.0 bug fix release will fix the Grok field extraction.
