### ISSUE TITLE
Getting started guide does not show up

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-server#1891]
### Problem description

When login to Graylog for the first time the Getting-started guide does not show up. Reloading startpage shows Getting-started guide

### Steps to reproduce the problem

1. I login to Graylog after building the QA box
2. When login in I expect the Getting-started guide but page is not loading
3. After new logout/ login I am getting directed to /search instead of /getting-started
4. After page reload the Getting-started guide shows up

### Environment

* QA Setup
* `graylog-2.0.0-alpha.5-SNAPSHOT-20160302193709-graylog-server-tarball.tar.gz`
* I am using Firefox 44.0.2

**Comment by dennisoelkers** [comment]
I think we are missing some steps to reproduce this, either before or after step 1.

**Comment by florianvolle** [comment]
Added information

**Comment by edmundoa** [comment]
I couldn't reproduce this in the current `2.0.0-alpha.6` in different browsers (Chrome, Firefox, Firefox ESR in Windows, and Safari).
@florianvolle: Could you please verify this is still an issue?

**Comment by florianvolle** [comment]
Works for me in different browsers. Closing this now.

**Comment by dennisoelkers** [comment]
I can reproduce this easily now. Just load the web if and execute this in your javascript console: `localStoreage.sessionId='"foobar"'` and refresh the page afterwards. After logging in, the Getting Started Guide will not load.
