### ISSUE TITLE
in 6.0 RC1 the global pipeline simulator appears to not work as expected

### ISSUE THREAD

**Issue by Pearson-k** [Graylog2/graylog2-server#18932]
## Expected Behavior

![working simulater 5 2](https://github.com/Graylog2/graylog2-server/assets/28361907/96299ec3-8834-4b68-a647-bbfcf8fea971)

## Current Behavior

![simulator broken](https://github.com/Graylog2/graylog2-server/assets/28361907/cbdf81c8-4459-4fd0-85b6-274a6df129c6)

## Steps to Reproduce (for bugs)

1. Go to system/pipelines/simulate
2. Input any GELF message as the message
3. Chose GELF Codec
4. Load Message

## Context

The simplest use case is validating a GELF message without actually ingesting it.

## Your Environment

* Graylog Version: 6.0 RC1 (Graylog Cloud)
* Operating System: MacOS 14.4.1
* Browser version:  Google Chrome 123.0.6312.87

**Comment by patrickmann** [comment]
@Pearson-k Can you add some more details about expected versus observed behavior? Is a rule not being executed? Is it being executed but not producing the same results? Is the pipeline set up identically on the 5.2 and 6.0 system? Looking at the 6.0 screen capture, it could just be a misconfigured pipeline stage; or it could be any number of things going wrong, from stream matching to rule execution.

**Comment by Pearson-k** [comment]
@patrickmann, this is the global simulation page, not the individual rule simulations; in this case, there aren't even any custom pipelines. I just wanted to see if a GELF message would parse out into fields or not using the GELF codec, where you should be able to see the results preview to see what the message will look like. The simulation trace to see what pipeline rules the message would have hit; in 5.2, this works fine as expected; in 6.0, this functionality doesn't work at all; clicking anything on that drop-down doesn't change the screen which is the expected behaviour as seen in the first GIF.

**Comment by patrickmann** [comment]
I don't see any difference in the backend. Hitting `Load message` issues a call to `system/pipelines/simulate`, which returns with the same JSON as in 5.2.

However, the dropdown `More results` seems broken. E.g. in 5.2 when I click `Simulation trace`, I can hit a breakpoint in _SimulationTrace.jsx_. In 6.0 I do not hit that breakpoint.

**Comment by drewmiranda-gl** [comment]
Ran into this today trying to troubleshoot pipelines :(

None of these from the "More Results" menu do anything. You click on them but the simulation results do not change. This makes it impossible to view the Simulation trace.

![image](https://github.com/Graylog2/graylog2-server/assets/107503402/f0c4fec1-17ad-4bac-98b3-20a008ba227f)
