### ISSUE TITLE
Expand all messages needs improvment

### ISSUE THREAD

**Issue by florianpopp** [Graylog2/graylog2-server#1893]
### Problem description

When expanding all messages in search I get a warning: Unresponsive script
### Steps to reproduce the problem
1. Perform a search
2. Click "Expand all messages
3. You receive a warning, messages expand. We should improve performance here
### Environment
- QA Setup
- `graylog-2.0.0-alpha.5-SNAPSHOT-20160302193709-graylog-server-tarball.tar.gz`

**Comment by edmundoa** [comment]
Sorry, wrong reference!

**Comment by bernd** [comment]
This should be fixed with the new search page implementation.
