### ISSUE TITLE
Sharing of event definition not working

### ISSUE THREAD

**Issue by todvora** [Graylog2/graylog2-server#18998]
I have created an event definition and shared it with another user:

![image](https://github.com/Graylog2/graylog2-server/assets/4102775/7bd83e77-71e5-44af-83a8-a045f17105d3)

The event definition itself (notice that no stream is assigned):

![image](https://github.com/Graylog2/graylog2-server/assets/4102775/896126a3-49c6-41a6-aa6c-7ee190174a01)

 

The other user doesn't see the definition. Additionally, the paging is still displaying pages for all the definitions that are hidden:

![image](https://github.com/Graylog2/graylog2-server/assets/4102775/5d36f239-cb60-49b0-90fd-d2b1ff9f059b)

Here the roles configuration of the receiving user:

![image](https://github.com/Graylog2/graylog2-server/assets/4102775/ea3c7420-f9e2-435c-9217-42ea843f6adf)

 

## Steps to Reproduce (for bugs)
1. Create event definition
2. Share it with a non-admin user
3. Log in as the non-admin user and visit event definitions page
4. Check that there is no definition available and paging is still displaying all pages for all hidden definitions

## Your Environment

* Graylog Version: Graylog Cloud 6.0.0 (431)
* Browser version: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0

**Comment by kmerz** [comment]
Checking, that nothing serious is broken. Otherwise we will fix it for the next patch...

**Comment by patrickmann** [comment]
Verified that shared event is now visible on 6.0 RC4.
Paging is still broken (based on all events, instead of those visible to user)

**Comment by patrickmann** [comment]
I created a separate issue for the paging problem: #19323
Closing this one, since sharing issue is resolved.
