### ISSUE TITLE
Alerts & events search input is removing input values while typing

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#19009]
## Description

When typing in the events and alerts input some values are being removed.

![events search](https://github.com/Graylog2/graylog2-server/assets/46300478/5e4f2a33-fe1d-4dfc-a43c-c24aadbd4ea0)

* Graylog Version: 6.0.0 rc2

**Comment by linuspahl** [comment]
This seems. to be the same issue like https://github.com/Graylog2/graylog2-server/issues/16388, but I am keeping this one open for better visibility. cc @gally47

**Comment by linuspahl** [comment]
@tellistone not sure if you are the right contact person for this, but since the core team has worked on this before (https://github.com/Graylog2/graylog2-server/pull/17987) maybe they can have another look and try to fix it for the other pages as well?

**Comment by tellistone** [comment]
Yeah we'll pick this up

**Comment by kmerz** [comment]
To make sure that this is still relevant, I tested it.

This is still an issue.

**Comment by coffee-squirrel** [comment]
Since this issue was closed with only one search input "fixed", I've opened #20529 to cover fixing the issue elsewhere.
