### ISSUE TITLE
Event definitions pagination does not seems to consider permissions when calculating total amount.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#19007]
## Description

In my case I see 121 pages of event definitions as an admin including every event definition. With a simple reader user, who has no access to any of these event definitions, I do not see any entry, but the pagination still shows 121 pages.

<img width="755" alt="image" src="https://github.com/Graylog2/graylog2-server/assets/46300478/735a6da7-3fa0-41df-960b-9e99a7acd6de">

* Graylog Version: 6.0.0 rc2

**Comment by mpfz0r** [comment]
This is likely caused by https://github.com/graylog2/graylog2-server/pull/17879

Before that change `PaginatedDbService#findPaginatedWithQueryFilterAndSort()` was used, which takes the filter into account
