### ISSUE TITLE
V6.0 and OpenSearch Docker compose file configurations are not in GitHub

### ISSUE THREAD

**Issue by jivepig** [Graylog2/graylog2-server#19016]
We are supporting OpenSearch as well as Data Node new deployments.  Currently there are no tested, approved Docker compose files on Github for deploying Graylog with OpenSearch.

## Expected Behavior
The Documentation covers this however any changes to configuration required in the Docker Compose files to indicate changes for new installs.

## Current Behavior
Missing Files for Docker Compose with Graylog V6.0 and OpenSearch

## Possible Solution
n/a

## Context
Many new environment variables get added as new options become available when new versions exist for Graylog as well as OpenSearch.  We should have these to indicate what configuration items need to be added.

## Your Environment

* Graylog Version:V6.0
* Java Version:V17
* OpenSearch Version:V2.6 and V2.12
* MongoDB Version: V5 and V6
* Operating System:n/a
* Browser version:n/a

**Comment by sethgraylog** [comment]
Docker compose images will be posted at or just prior to GA.
