### ISSUE TITLE
Clicking on submit button in create / update event notification form shows confirm dialog.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#19014]
## Description

When you create or update an event notification, you will see the following confirm dialog on submit. Tested with an http notification.

![image](https://github.com/Graylog2/graylog2-server/assets/46300478/11c3a650-d1e8-4804-ba90-b497a5de7fb7)

Seems to be related to https://github.com/Graylog2/graylog2-server/issues/19008

* Graylog Version: 6.0

**Comment by kmerz** [comment]
Duplicate of  #18771 the PR needs a backport (#18880)

**Comment by zeeklop** [comment]
This solution was applied to 6.0rc on the this PR https://github.com/Graylog2/graylog2-server/pull/18900

**Comment by linuspahl** [comment]
@zeeklop The PR looks event definitions related, should it also fix the problem for the notifications form?

**Comment by linuspahl** [comment]
@kmerz it looks like the issue you mentioned is about event definitions, but I had this problem with the event notifications form.

**Comment by zeeklop** [comment]
> @zeeklop The PR looks event definitions related, should it also fix the problem for the notifications form?

@linuspahl This is only taking care of the issue on Event Definitions form.
