### ISSUE TITLE
"Loading component failed: unknown format:" when loading Sidecar page

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/graylog2-server#19012]
When loading the Sidecar page in 6.0 rc-2:

![image](https://github.com/Graylog2/graylog2-server/assets/2953243/2d4787fb-231d-4806-8c4c-bd31b4975cd8)

I'm not seeing any issues on the network tab:

![image](https://github.com/Graylog2/graylog2-server/assets/2953243/a423cf19-d6e9-4502-adcc-d727f89ad2ed)

There's nothing that appears in server.log when loading the Sidecar page too. I've tried the usual front-end tricks like reloading without cache, trying a different browser, etc.

## Your Environment

Graylog Version: Graylog 6.0.0-rc.2+9b62575
Java Version: Embedded
OpenSearch Version: 2.13.0
MongoDB Version: 7.0.6
Operating System: Debian 12
Browser version: Chrome Version 123.0.6312.107 (Official Build) (arm64)

**Comment by kmerz** [comment]
@damianharouff could you please check, if the issue still exists? 

Could someone else check if that is a problem, then this would be a blocker!

**Comment by mpfz0r** [comment]
removing the blocker label. no one else has seen this issue so far

**Comment by macorpage** [comment]
Same problem in version 6.0 rc-3. Any suggestion?

**Comment by mpfz0r** [comment]
@macorpage  we are still having troubles reproducing this. which browser are you using? does ctrl-shift-reload help?

**Comment by macorpage** [comment]
Hi @mpfz0r I am using Firefox 124.0.2. I tried ctrl-shift-reload and it opens a new tab and I can see Sidecar Overview but when I change view (eg I click on Streams) and go back to Sidecar Overview I have the same problem. I tried also with Chrome and Edge, same problem and ctrl-shift-reload does not work at all.

Red Hat Enterprise Linux release 9.3
elasticsearch-oss.x86_64                         7.10.2-1                         
graylog-server.x86_64                            6.0.0-11.rc.3               
mongodb-org.x86_64                               6.0.15-1.el9

**Comment by mpfz0r** [comment]
@macorpage Sorry, I meant using the keyboard combination `ctrl-shift-r` which reloads the entire page in your browser without using cached frontend assets.

**Comment by macorpage** [comment]
Hi @mpfz0r, same problem.

**Comment by drewmiranda-gl** [comment]
For what its worth @mcdowellster also reported this but not sure if he still has the issue.

**Comment by dennisoelkers** [comment]
Hey @macorpage, is this reproducible right now for you?

**Comment by drewmiranda-gl** [comment]
I was able to reproduce based off of what ethan said about the sidecar being offline.

1. Install sidecar on an endpoint and start it
2. observe the sidecar appears in `/system/sidecars` and shows online
3. stop the sidecar service on the endpoint
4. wait for the timeout to occur, once offline the page shows the error

See http://videos.graylog.com/watch/dkPmuRVqur4r2g6ayAJd8o?

**Comment by luxzg** [comment]
@linuspahl or someone else, is there a way to "patch" this, or apply some other workaround until RC4 or final receives? We've experienced the same thing, and despite restarting the sidecar on the endpoint, we still can't open the page, even after restarting graylog-server. We are on RC3 that was released about 3 weeks ago, the fix for sidecar was accepted 2 weeks ago, but I can't find any plans for following milestones. And we'd like to continue testing and adding new devices to this test environment, without having to reinstall everything, or waiting another few weeks in limbo. Thanks in advance!

**Comment by linuspahl** [comment]
Hi @luxzg, thank you for testing the Graylog RC!
It looks like our release page is not yet up to date, but we released the 6.0 GA yesterday, which includes the fix for this bug.

**Comment by luxzg** [comment]
> Hi @luxzg, thank you for testing the Graylog RC! It looks like our release page is not yet up to date, but we released the 6.0 GA yesterday, which includes the fix for this bug.

Awesome news @linuspahl and thanks for the heads up! We'll be looking to update tomorrow morning when we get back to office. Congratulations everyone on 6.0 GA !
