### ISSUE TITLE
Add beta banner to data node

### ISSUE THREAD

**Issue by moesterheld** [Graylog2/graylog2-server#19038]
After discussion with product/management, a beta banner containing the text 
"Data Node is currently in beta. Feel free to check it out and tell us about your experience!"
should be added to both preflight UI and the data node overview page.

**Comment by coffee-squirrel** [comment]
With Data Node being considered beta, it might be good to also update [Graylog2/docker-compose](https://github.com/Graylog2/docker-compose) so (Graylog2/docker-compose#39).

**Comment by moesterheld** [comment]
@coffee-squirrel Thanks for the comment. Since the docker-compose project is meant for testing and demoing purposes, we have decided to keep data node as the search backend.
