### ISSUE TITLE
Add cache headers to http endpoint serving web interface assets

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#1905]
### Problem description

Right now all web interface assets are refetched each time due to missing cache headers.

### Environment

* Graylog Version: 2.x

**Comment by joschi** [comment]
Dropwizard has the `@CacheControl` annotation which might be useful to use as an inspiration for this.

* https://github.com/dropwizard/dropwizard/blob/v0.9.2/dropwizard-jersey/src/main/java/io/dropwizard/jersey/caching/CacheControl.java
* https://github.com/dropwizard/dropwizard/blob/v0.9.2/dropwizard-jersey/src/main/java/io/dropwizard/jersey/caching/CacheControlledResponseFeature.java

**Comment by dennisoelkers** [comment]
Fixed in 515c3a242a3fdff1dcb3a4a2fece8351d0060c02
