### ISSUE TITLE
"Manage extractors" button adds extra "/undefined/"

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-server#19111]
Hello,

Clicking on "Manage extractors" from existing input, adds "/undefined" into URI.
URL looks following: `https://XXXXXX/system/inputs/undefined/45234234ff78ba51b7d16ac4/extractors` and nothing is shown in the browser window.

Removing "/undefined" from URL show extractor page correctly.

* Graylog Version: 6.0.0-11.rc.3
* Java Version:
* OpenSearch Version: 2.13.0
* MongoDB Version: 6.0.15
* Operating System: Ubuntu 22.04.4 LTS
* Browser version: Chromium: 124.0.6367.60

**Comment by bernd** [comment]
@timukas Thanks for the report!

Addition: This happens for "Local inputs". For "Global inputs" the "Manage extractors" link works correctly.

This is a new issue in 6.0. I can't reproduce it in 5.2.

**Comment by patrickmann** [comment]
Looks like ${nodeId} is undefined here:
https://github.com/Graylog2/graylog2-server/blob/33c0f843ff0b450ed2ef7ab98121b52f3a0ed1f6/graylog2-web-interface/src/routing/Routes.ts#L278
