### ISSUE TITLE
How to turn the value of a link to a hyperlink

### ISSUE THREAD

**Issue by 123dev** [Graylog2/graylog2-server#1914]
### Problem description

Not sure if I'm asking this in the right area, mods, please kindly move this if it is in the wrong area.

We use Graylog across multiple applications, our data crosses multiple systems, and all our logs include a custom field: correlation_id
This id is carried over when data flows from one application to another, so that we can easily find and correlate log entries.
This has proven to be extremely important to our operations and can't imagine working efficiently without it.

The way we currently use this is copy the text field
open another graylog browser window
search for correaltion_id:<copied_value>
to get to the list of log entries with the matching id.

We'd like to take this to the next level and have a smooth navigation and are looking for guidance on how we can  turn this specific field value into a hyperlink
We have created an application (kind of url shortener / mapper) that takes this in simple form
https://123hub/?cid=C58MyDc
and redirects to:
https://graylog/search?rangetype=relative&fields=source%2Ccorrelation_id%2Chttp_status%2Clevel%2Cmessage%2Curi_stem&width=1465&relative=0&q=correlation_id%3AC58MyDc#fields=source%2Ccorrelation_id%2Chttp_status%2Clevel%2Cmessage%2Curi_stem

This is of-course customizable and can be used with different keywords.

So all we're looking for is a way to turn a field value to a hyperlink.

Has something similar have already been done?
by a plugin? or do we need to modify the graylog source and build it oursleves?

Any guidance is greatly appreciated.
Thanks for an awesome product.
### Environment
- Graylog Version: 1.3.2 (AWS Image)

**Comment by kroepke** [comment]
Hi, yes, this is the right place to ask :)

Currently Graylog does not support this kind of plugin yet, but we are looking into it and are planning to support this in the future.
However, it will likely not make it into 2.0.
If you have more requirements, please feel free to either file additional feature requests or add details to this issue if they are relevant to hyperlinks.

I'll leave this open until the time we are spec'ing out the feature.

Thanks,
Kay

**Comment by 123dev** [comment]
Thank Kay for the follow up.
Happy to hear that there is interest in supporting this in the future.

I will definitely not hesitate to filing other feature requests or adding details to this if our requirements change.

Would this ticket be updated when this feature is supported? so that we get to be notified?

In the meantime, if you can think of recommending any other mechanism (browser addons or anything) that we can use / code to get a temporary solution would be welcome.
Would making changes to this code be in the right area?
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/components/search/MessageTableEntry.jsx#L28

Thanks again

**Comment by kroepke** [comment]
Yes, we will be updating this ticket one we start the work.

That's the correct place to look at the markup being generated, yes, all data should flow through there.

**Comment by 123dev** [comment]
Thanks Kay

**Comment by 123dev** [comment]
Kay,

One other thing we can think of that relates to this (somehow) is that we currently have about 30 days of retention of data, (based on volume / cost and other factors)
However we often find ourselves referencing a correlation_id in task/bug tickets that have gone out of graylog (> 30)

It would be awesome if there was a way to pin / save any log message manually so that it is not subjected to rotation policy and would be available irreseptive of time / messages passed.
Manual adding and removing pinned items is more than enough.

Thanks

**Comment by 123dev** [comment]
Hi,

Can this be accomplished with the use of decorators?
I took a stab at adding Format String decorator, which changed the field value to and http query
the decorated value comes up ok, but it's not linkified.
Any way to achieve that with a the decorators?

Here's the decorator
![decorator](https://cloud.githubusercontent.com/assets/13109154/19447164/3f22380c-946a-11e6-8f78-8cab29e87a18.png)

And here's how it shows up
![decorated](https://cloud.githubusercontent.com/assets/13109154/19447180/56cf774e-946a-11e6-8b36-1f4bdc6f212e.png)

Thanks

**Comment by edmundoa** [comment]
This will be possible in 3.0 thanks to @pbr0ck3r! 🎉
