### ISSUE TITLE
Unable to create an index set in graylog open 6-rc4

### ISSUE THREAD

**Issue by keeshoekzema** [Graylog2/graylog2-server#19205]
While playing around with a new test install of Graylog 6 (open) i ran into a few issues.

## Expected Behavior
On the page /system/index_sets/create i should be able to create a new index set

## Current Behavior
When posting this page (even when editting an existing index) it fails with

failed with status: Unable to map property archive_before_deletion. Known properties include: index_lifetime_min, type, index_lifetime_max

## Steps to Reproduce (for bugs)
Create or edit a new index and try to post it

## Your Environment
* Graylog Version: Graylog 6.0.0-rc.4+062ad58
* Java Version: 17.0.10
* OpenSearch Version: 2.13.0
* MongoDB Version: 7.0.9
* Operating System: Debian 12
* Browser version: Firefox 125.0.3

**Comment by bernd** [comment]
@keeshoekzema Thank you very much for the report! :pray:

**Comment by bernd** [comment]
Some more context. This only happens when "Data Tiering" is selected for rotation and retention. When selecting "Legacy (Deprecated)", the index set can be created.

![image](https://github.com/Graylog2/graylog2-server/assets/461/63e0552b-92ec-4083-8073-1fb35f48b70b)

**Comment by bernd** [comment]
@keeshoekzema Thanks for the report again. The issue will be fixed in the next 6.0 release candidate.
