### ISSUE TITLE
when I Use Input Chinese to the Search input，The Content is mess

### ISSUE THREAD

**Issue by kira8565** [Graylog2/graylog2-server#1920]
### Problem description

   when I Use Input Chinese to the Search input，The Content is in a mess
### Steps to reproduce the problem
1. type Chines to Search Input on Mac
2. the search input is mess liek this :  zzhzhozhonzhongzhong'wzhong'wezhong'wen中文
   ### Environment
- Graylog Version: Graylog2-Alpha-6
- Elasticsearch Version:ES2.1.0
- MongoDB Version:Mongo3.2
- Operating System: Ubuntu14.04

**Comment by edmundoa** [comment]
Hi,

Could you please confirm that other inputs are working as expected? If so, please try disabling the search auto-completion for your user account. You can do it in the menu bar, by clicking in your user name -> Edit profile -> User preferences, and setting `enableSmartSearch` to `false`.

**Comment by kira8565** [comment]
English is Work fine，Only Input Chinese is mess ,Windows is Work fine too .... ,I think is the Problem is the Input software On Mac Not Working Well With React TypeAhead

**Comment by bernd** [comment]
The search page has been rewritten in the mean time and should now properly support this. Please open a new issue if this is still an issue. Thank you!
