### ISSUE TITLE
email-callback error on certain field

### ISSUE THREAD

**Issue by Dainii** [Graylog2/graylog2-server#1922]
I have an input created with the 'SNMP' plugin. I've try to creat an email callback with not all the informations contains in the snmp trap, but only selected fields, but it doesn't work.

This is a message exemple: 
'source: switch.domain | message: SNMP trap 181 { snmp_clogHistTimestamp: 21949095830 | snmp_frDLCIStatusChange: 1.3.6.1.4.1.9.9.41.2.0.1 | gl2_remote_ip: xxx.xxx.xxx.xxx | snmp_clogHistFacility: LINK | gl2_remote_port: 55025 | streams: [56cf0bede4b084cf1203c361, 56e288abe4b0af8fca657461] | gl2_source_input: 56d03ebce4b0c2356b350343 | port: GigabitEthernet1/0/1 | snmp_request_id: 181 | snmp_clogHistMsgName: UPDOWN | gl2_source_node: 4d300f6f-019e-4a41-8613-2c31a406b778 | _id: f3a39490-e797-11e5-9ba1-0050569f7da0 | snmp_trap_type: TRAP | snmp_sysUpTimeInstance: 21949095840 | snmp_clogHistSeverity: 4 | timestamp: 2016-03-11T14:45:51.832Z | snmp_clogHistMsgText: Interface GigabitEthernet1/0/1, changed state to up | status: up }'

I've created the 'port' and 'status' field with an extractor based on the field 'snmp_clogHistMsgText'

The ${message.source} works

Now, I want to access the 'port' field. ${message.port} doesn't work because it doesn't find any root field called 'port' (Error while parsing 'message.port') and ${message.message.port} doesn't work because it doesn't search in the { } (You can not make property calls on string 'SNMP trap 181!')

Is there a way to access these fields in an email callback ?

Thx

### Environment
* Graylog Version:  1.3.3-1 
* Elasticsearch Version: 1.7.5-1
* MongoDB Version: 3.2.3-1.el6
* Operating System: CentOS release 6.7

**Comment by joschi** [comment]
You'll have to use `${message.fields.port}` to access the (non-standard) `port` attribute of your messages.

See http://docs.graylog.org/en/1.3/pages/streams.html#email-alert-callback for details.

**Comment by Dainii** [comment]
Thx a lot
