### ISSUE TITLE
2.0 Alpha5 WebConsole not seeing Server REST API

### ISSUE THREAD

**Issue by tehpanta** [Graylog2/graylog2-server#1927]
### Problem description
Web Console not working with an error (skinned in graylog theme, just a message saying:
> We are experiencing problems connecting to the Graylog server running on http://SERVER_REST_API_IP:SERVER_REST_API_PORT//. Please verify that the server is healthy and working correctly.

### Steps to reproduce the problem
GrayLog Server configuration:
```
rest_listen_uri = http://SERVER_REST_API_IP:SERVER_REST_API_PORT/
rest_enable_cors = false
rest_enable_gzip = true

web_enable = true
web_listen_uri = https://WEB_CONSOLE_IP:WEB_CONSOLE_PORT
web_enable_cors = true
web_enable_gzip = true

web_enable_tls = true
web_tls_cert_file = pathtocer
web_tls_key_file = pathtokey
web_tls_key_password = password
#web_max_header_size = 8192
#web_max_initial_line_length = 4096
#web_thread_pool_size = 16
```
### Environment

* Graylog Version: 2.0 Alpha 5
* Elasticsearch Version: 2.2
* MongoDB Version: 2.6.7
* Operating System: RedHat 6.2
* Browser version: Any

EDIT:
This is the end of server logfile. After trying to access the web console from a browser, nothing is added to the active logfile.
```
2016-03-14 13:59:44,521 INFO : org.glassfish.grizzly.http.server.NetworkListener - Started listener bound to [WEB_CONSOLE_IP:WEB_CONSOLE_PORT]
2016-03-14 13:59:44,523 INFO : org.glassfish.grizzly.http.server.HttpServer - [HttpServer] Started.
2016-03-14 13:59:44,524 INFO : org.graylog2.initializers.WebInterfaceService - Started Web Interface at <https://WEB_CONSOLE_IP:WEB_CONSOLE_PORT/>
2016-03-14 13:59:46,668 INFO : org.glassfish.grizzly.http.server.NetworkListener - Started listener bound to [SERVER_REST_API_IP:SERVER_REST_API_PORT]
2016-03-14 13:59:46,668 INFO : org.glassfish.grizzly.http.server.HttpServer - [HttpServer-1] Started.
2016-03-14 13:59:46,668 INFO : org.graylog2.shared.initializers.RestApiService - Started REST API at <http://SERVER_REST_API_IP:SERVER_REST_API_PORT/>
2016-03-14 13:59:46,670 INFO : org.graylog2.shared.initializers.ServiceManagerListener - Services are healthy
2016-03-14 13:59:46,670 INFO : org.graylog2.shared.initializers.InputSetupService - Triggering launching persisted inputs, node transitioned from Uninitialized [LB:DEAD] to Running [LB:ALIVE]
2016-03-14 13:59:46,671 INFO : org.graylog2.bootstrap.ServerBootstrap - Services started, startup times in ms: {InputSetupService [RUNNING]=4, OutputSetupService [RUNNING]=13, MetricsReporterService [RUNNING]=52, BufferSynchronizerService [RUNNING]=63, KafkaJournal [RUNNING]=68, JournalReader [RUNNING]=93, PeriodicalsService [RUNNING]=154, IndexerSetupService [RUNNING]=3624, WebInterfaceService [RUNNING]=6662, RestApiService [RUNNING]=8880}
2016-03-14 13:59:46,675 INFO : org.graylog2.bootstrap.ServerBootstrap - Graylog server up and running.
```

**Comment by joschi** [comment]
@tehpanta Try enabling CORS on the Graylog REST API (set `rest_enable_cors = true`, which is the default setting).

**Comment by tehpanta** [comment]
I have tried both gzip and cors enabled/disabled on REST API with no change in behaviour, sadly.

**Comment by joschi** [comment]
@tehpanta CORS needs to be enabled on the Graylog REST API. Otherwise most (all?) browsers won't allow requests to that URL.

**Comment by dennisoelkers** [comment]
@tehpanta is this still an issue? If yes, please reopen the issue and add the contents of the javascript console of your browser to this issue, please.

**Comment by tehpanta** [comment]
Issue is still there with the Beta1 release.

This is in the browser console
Blocked loading mixed active content "http://10.244.204.19:11999/system/cluster/node"

When I try to access the content directly from the same browser though, I will get seemingly correct response:
{"cluster_id":"4f7cb07a-0102-417b-a3d9-75116f6e3357","node_id":"4d253537-eba9-499f-8c80-99058e300e80","type":"server","transport_address":"http://10.244.204.19:11999/","last_seen":"2016-03-31T18:29:40.000Z","short_node_id":"4d253537","hostname":"s1s003bk","is_master":true}

**Comment by tehpanta** [comment]
Btw I cannot reopen the issue. I am not a collaborator.

**Comment by tehpanta** [comment]
Problém probably lies in enabled HTTPS on the web console. When I try to run the server on HTTP only, the login page loads up correctly.

**Comment by dennisoelkers** [comment]
@tehpanta: You seem to be running the web interface on HTTP but the backend API on HTTPS. This is not possible with current browsers (for good reasons), so you need to enable SSL for the endpoint serving the web interface assets too.

**Comment by tehpanta** [comment]
Its the opposite way around. I have https enabled on web console, but disabled on server rest api. I will change both to ssl then and try it out. 

As a side note...working in banking environment, the change of web console in the way you did (mandatory network firewall rules to acces both rest api of the server AND web console), is causing quite a bit of a stirr. From the security standpoint, REST api should be hidden away and not accessible from client workstations at all. Thats what console is for basically.

Thank you for the help though. I will reconfigure as mentioned and report back here with results.

**Comment by jam0** [comment]
I was having this same problem and am now having it with beta2 also. If I set _web_enable_tls = true_ then no matter what else I set regarding the REST api (including tls), I get the same response as above. If I disable tls, then everything works fine. I'm not sure what else to try at this point.

**Comment by edmundoa** [comment]
I believe this is in the end a misconfiguration. As @dennisoelkers mentioned, if you use HTTPS for the web interface, you also need to run the REST API in HTTPS.

Please ensure your `rest_enable_cors` is set to `true`, and modify your `rest_listen_uri` or `rest_transport_uri` to use `https`. You may also need set the options to configure HTTPS for the REST API (`rest_enable_tls`, `rest_tls_cert_file`, `rest_tls_key_file`, and `rest_tls_key_password`).

**Comment by tehpanta** [comment]
It is partly misconfiguration, partly absence of any documentation regarding this and partly a functional flaw in new GrayLog web interface.

1. REST api should NOT be visible directly to the whole network. Even through SSL.
2. There is no option to use separate truststore for graylog instance. Hence we are forced to put our internal CAs to default Java Truststore, which is also far from ideal.

On the other hand, those are issues for another issue/suggestion rather than this one. I will close this issue as a miscofiguration issue (which it is, just like you said).

Thank you all for help!
