### ISSUE TITLE
Getting server logs

### ISSUE THREAD

**Issue by sikendermd** [Graylog2/graylog2-server#1928]
Hello all,

I have  a linux server with "shd01vbld01:8080" . I want to access logs from this linux server into graylog . I made some config changes to file "/etc/rsyslog.conf" by adding 
" *.* @graylog.example.org:514;RSYSLOG_SyslogProtocol23Format"

Where graylog.example.org is the IP Address of my graylog server I provided. 

And then I restaretd the rsyslog; 

Then I created input syslog_UDP. But I didn't find any logs coming from my linux server??

DO we need to provide bind address and port of linux server in graylog when we create input or else the same default bind address (0.0.0.0) and port (514) are fine to see the logs in server.

CAn you please tell me when am I going wrong in this. 

Thank you 
Sam

### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@sikendermd Please post this kind of question to the [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the discussion in [#graylog on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).
