### ISSUE TITLE
Custom HTTP Notification -> API Secret should not be required if API Key is used

### ISSUE THREAD

**Issue by TimmiORG** [Graylog2/graylog2-server#19338]
## What?
Currently Graylog requires a API secret in case API key is used. 
But the AbuseIPDB API does not require the API secret.
https://docs.abuseipdb.com/#introduction

Please remove the dependency of the API secret so that API Key could be used without it.

## Why?
I'm trying to push events via the new custom HTTP notification feature of Graylog 6.0 to AbuseIPdb.com.
https://community.graylog.org/t/graylog-6-custom-http-notification-abuseipdb/32396/3

## Your Environment

* Graylog Version: 6.0.1
* OpenSearch Version: Elastic Search 7.10.2
* MongoDB Version: 6.0.15
* Operating System: Rocky Linux 9.4
* Browser version: FF 125

**Comment by TimmiORG** [comment]
Hi @kingzacko1 ,

thank you very much for the good explanation. This clarifies it very well.
So I guess we can close this ticket than.

**Comment by kingzacko1** [comment]
@TimmiORG you're welcome! I will go ahead and close this one out. Let us know if you run into any other issues and I'll be happy to take a look!
