### ISSUE TITLE
Search field contents does not work in alpha5

### ISSUE THREAD

**Issue by aseques** [Graylog2/graylog2-server#1934]
### Problem description
I am trying to filter the messages that have a field with an specific text, but no matter what I do, I see the full list of messages.

### Steps to reproduce the problem
To create the query I just selected the input and after expanding a message with the field value I am looking for, I clicked on the magnifier, then I get a query like this
> gl2_source_input:56d82de1f8fe7e034a8da1be levelname:WARN" 

Or in json form (it looks good)
https://gist.github.com/aseques/48ebc8b03327076166ba

The same happens if I do a filter for the msg field
> gl2_source_input:56d82de1f8fe7e034a8da1be msg:"WARN"

Instead, if I search for the value without specifying a field it just works, like in the query below
> gl2_source_input:56d82de1f8fe7e034a8da1be "WARN"

### Environment

* I am using the vmware OVA (alpha4 updated to alpha5)
* Graylog Version: 2.0 alpha5
* Browser version: firefox

**Comment by kroepke** [comment]
This query is doing an "OR" query, which means that you will find all messages from that input.

There should be an "AND" in the generated query, for me this works in alpha.5.
Can you please verify what the query looks like right after clicking the magnifier icon?

**Comment by aseques** [comment]
Duh, you are totally right, I started looking for the syntax and haven't realized this. Thank you for the reply
