### ISSUE TITLE
Can´t Login with Reverse Proxy 

### ISSUE THREAD

**Issue by florian-ald** [Graylog2/graylog2-server#19350]
## Expected Behavior

Graylog Login-Page should redirect to Dashboard when credentials are ok
## Current Behavior

After entering the correct login data a error message appears that it could not load streams and go back to login
## Possible Solution

Within chrome developer tools i see after login a 401 unauthorized error. Attached the HAR file.
[graylog.ald-vt.de.har.zip](https://github.com/Graylog2/graylog2-server/files/15316900/graylog.ald-vt.de.har.zip)

## Steps to Reproduce (for bugs)

1. Installed the system several times with different ubuntu version
2. Graylog works when not using nginx as proxy
3.
4.

## Your Environment

* Graylog Version: 6.0.1-1
* Java Version: Graylog builtin
* OpenSearch Version: 2.14.0
* MongoDB Version: 6.0.15
* Operating System: Ubuntu 22.04.4 LTS
* Browser version: chrome 124.0.6367.156
* nginx version: 1.18.0-6ubuntu14.4

**Comment by drewmiranda-gl** [comment]
Can you share your reverse proxy configuration? Can you verify that the reverse proxy is also preserving cookies?

**Comment by florian-ald** [comment]
Hi,
i use the standard configuration as described in the instructions.

```
server
{
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name graylog.ald-vt.de;
    location / {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Graylog-Server-URL https://$server_name/;
      proxy_pass http://127.0.0.1:9000;
    }
}
```
Unfortunately, I can't answer your question about the cookie because I don't know how to check it.
I have tested with different browsers in normal or incognito mode. 
Only the login process does not work. If I configure the graylog server with an IP and not with localhost and thus bypass the proxy, the login works. If I now configure everything back again and use the proxy again, graylog works as long as I remain logged in.

**Comment by drewmiranda-gl** [comment]
I was able to reproduce the issue as you describe. I found the issue is with the following line:

```
proxy_set_header X-Graylog-Server-URL https://$server_name/;
```

Because nginx is not using TLS/HTTP, the web browser is rejecting setting the authentication cookie:
![image](https://github.com/Graylog2/graylog2-server/assets/107503402/0956513a-1a36-4f7e-88c7-028ff3662bb2)

If you chance
```
proxy_set_header X-Graylog-Server-URL https://$server_name/;
```

to (note `https` is changed to `http`)
```
proxy_set_header X-Graylog-Server-URL http://$server_name/;
```

The issue is resolved.

**Comment by florian-ald** [comment]
You made my Day. I totally overlooked this. 

That's what happens if you only follow the instructions strictly, just copy&paste and don't look at the code carefully.

Thanks a lot Miranda
