### ISSUE TITLE
Graylog maven build error : Could not find artifact org.graylog:graylog-storage-elasticsearch7:jar:tests:5.2.7 in central

### ISSUE THREAD

**Issue by KuoKaiNi** [Graylog2/graylog2-server#19386]
## Current Behavior

[ERROR] Failed to execute goal on project full-backend-tests: Could not resolve dependencies for project org.graylog:full-backend-tests:jar:5.2.7: The following artifacts could not be resolved: org.graylog:graylog-storage-elasticsearch7:jar:tests:5.2.7 (absent), org.graylog:graylog-storage-opensearch2:jar:tests:5.2.7 (absent), org.graylog2:data-node:jar:tests:5.2.7 (absent): Could not find artifact org.graylog:graylog-storage-elasticsearch7:jar:tests:5.2.7 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

I can not find graylog-storage-elasticsearch7 and graylog-storage-opensearch2 data in maven repository.
https://repo.maven.apache.org/maven2/org/graylog/

## Possible Solution

I can not found any mirror repository for those two modules.

## Steps to Reproduce (for bugs)

1. check out graylog2-server source code from github and using branch 5.2.7
2. execute the command: mvn clean install -Dmaven.test.skip=true

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Graylog Parent POM 5.2.7:
[INFO] 
[INFO] Graylog Parent POM ................................. SUCCESS [  4.508 s]
[INFO] Graylog Project Parent POM ......................... SUCCESS [  0.043 s]
[INFO] Graylog ............................................ SUCCESS [16:08 min]
[INFO] Graylog Plugin Parent POM .......................... SUCCESS [ 40.028 s]
[INFO] graylog-storage-elasticsearch7 ..................... SUCCESS [ 56.623 s]
[INFO] graylog-storage-opensearch2 ........................ SUCCESS [01:01 min]
[INFO] DataNode ........................................... SUCCESS [04:29 min]
[INFO] full-backend-tests ................................. FAILURE [  0.889 s]
[INFO] Graylog Plugin with Web support Parent POM ......... SKIPPED
[INFO] graylog-plugin-archetype ........................... SKIPPED
[INFO] Graylog Binary Distribution Tarball ................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23:21 min
[INFO] Finished at: 2024-05-19T18:37:01+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project full-backend-tests: Could not resolve dependencies for project org.graylog:full-backend-tests:jar:5.2.7: The following artifacts could not be resolved: org.graylog:graylog-storage-elasticsearch7:jar:tests:5.2.7 (absent), org.graylog:graylog-storage-opensearch2:jar:tests:5.2.7 (absent), org.graylog2:data-node:jar:tests:5.2.7 (absent): Could not find artifact org.graylog:graylog-storage-elasticsearch7:jar:tests:5.2.7 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

## Your Environment

* Graylog Version: 6.6.1
* Java Version: 
openjdk 17.0.6 2023-01-17 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-3.el8_7) (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-3.el8_7) (build 17.0.6+10-LTS, mixed mode, sharing) 
* OpenSearch Version: None
* MongoDB Version: None
* Operating System: RHEL 8.8 x86_64
* Browser version: None

**Comment by janheise** [comment]
@KuoKaiNi when you skip the tests with `-Dmaven.test.skip=true` you also skip the build of those `jars`. Can you run it again without skipping the tests. Otherwise, it would make sense to also skip the integration tests, too.
