### ISSUE TITLE
Cannot read property 'surrounding_timerange_options' of undefined

### ISSUE THREAD

**Issue by kira8565** [Graylog2/graylog2-server#1946]
### Problem description
When I Click Permalink On Search Result Table，It throw an error :Cannot read property 'surrounding_timerange_options' of undefined
### Steps to reproduce the problem

1. ...Click the Search Result table and expland it 
2.Click the Permalink

### Environment

* Graylog Version: Alpha6
* Elasticsearch Version:2.1.0
* MongoDB Version: 3.1
* Operating System:Mac
* Browser version: Chorm48.0

**Comment by joschi** [comment]
@kira8565 Graylog 2.0.0-alpha.6 hasn't been released yet. How exactly did you build and start Graylog?

**Comment by kira8565** [comment]
i found the pom.xml has 2.0.0-alpha.6-SNAPSHOT
i merge the feature [surround search button] last day ,i think the problem is this  (｡･ω･)ﾉﾞ

**Comment by joschi** [comment]
I'm closing this issue as it's an unsupported custom build of Graylog and the PR in question hasn't been merged yet into `master`.

**Comment by bernd** [comment]
This is actually a bug in master that needs to be fixed. Re-opening issue.
