### ISSUE TITLE
change error message for bad LDAP service account password

### ISSUE THREAD

**Issue by jhaar** [Graylog2/graylog2-server#1953]
### Problem description

We did a password change on a range of accounts and forgot that graylog was configured to use such an account. So when users tried to log in, they got a "bad password" error. However, it wasn't their password that was bad - it was the service account graylog uses
### Steps to reproduce the problem
1. change LDAP password for service account
2. try to log into graylog using an normally working username/password. 

When this started happening, I looked at the graylog-server logs and saw errors like

2016-03-20T22:45:07.888Z WARN  [SessionsResource] Unable to log in user user@ad.domain
org.apache.shiro.authc.AuthenticationException: No account information found for authentication token [org.apache.shiro.authc.UsernamePasswordToken - user@ad.domain, rememberMe=false] by this Authenticator instance.  Please check that it is configured correctly.

That's entirely correct - but I couldn't put two and two together. I was off thinking we've got some kind of LDAP or TLS problem. 

How about changing "Please check that it is configured correctly" to "The 'name.of.service.account' that is used for LDAP checks is not working - please check the username/password is correct and configured correctly". It's more explicit and would hammer the admin on the head with the cause ;-)
### Environment
- Graylog Version: 1.3
- Elasticsearch Version: 1.7
- MongoDB Version:
- Operating System:
- Browser version:

**Comment by bernd** [comment]
This should not be an issue anymore in Graylog 4.0. Please open a new issue if you still see the problem. Thank you!
