### ISSUE TITLE
Can't download graylog OVA appliance

### ISSUE THREAD

**Issue by RetOI** [Graylog2/graylog2-server#1955]
I can't download graylog OVA appliance (stable branch 1.3.4).
I run the like but the downloading never begin, he was blocked 
Anyone know why ?

### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by mariussturm** [comment]
Which link did you use?
This one here should work: https://github.com/Graylog2/graylog2-images/tree/1.0/ova

**Comment by RetOI** [comment]
I use this one : https://packages.graylog2.org/releases/graylog-omnibus/ova/graylog-1.3.4-1.ova

But I have a white page

**Comment by RetOI** [comment]
have you an another like ?

**Comment by RetOI** [comment]
Have you an another link ?

**Comment by mariussturm** [comment]
That's the correct link, please try another browser or something like wget to fetch the image.
