### ISSUE TITLE
Cannot replace content with linebreak in additional fields

### ISSUE THREAD

**Issue by Spitfire1900** [Graylog2/graylog2-server#1956]
### Steps to reproduce the problem

1. Have non-standard field with the content: `","`
2. Create a "Replace with regular expression" extractor against the field
3. Replace `","` with `\n` or `<br />`
4. Click "Try"
5. Extractor preview and content of new messages include `n` and `<br />` instead of linebreaks.

### Environment

* Graylog Version:v1.3.3
* Elasticsearch Version:1.7.4-1
* MongoDB Version:3.2.1-1.el7
* Operating System:RHEL 7.2; Linux 3.10.0-327.3.1.el7.x86_64
* Browser version:FF 47.0a2

**Comment by bernd** [comment]
This is intentional because we don't allow the injection of HTML tags.

For the `\n` you have to escape the newline in the replacement like this: `\\n`

**Comment by netoht** [comment]
It maybe may works for you: https://github.com/Graylog2/graylog2-server/issues/5971#issuecomment-572264835
