### ISSUE TITLE
[1.3] Field graphs are only available for numeric fields.

### ISSUE THREAD

**Issue by kkamkou** [Graylog2/graylog2-server#1958]
Hi guys. I have checked some tickets around, and it looks like the feature is working in general. Somehow it doesn't work in my particular case. The problem I have right now is that I can't create a simple `Field graph` with floats (I assume that for GL `float` is a valid numeric type).

Env:
 - 1.3.3
 - GELF with node ([node-gelf-pro](https://github.com/kkamkou/node-gelf-pro))
  - sent as js float: `{"_example5": 3.3}`

Also tried Gork and Regexp, asked question in IRC. Thank you.

Logs:
```
ERROR [SearchResource] Field histogram query failed. Make sure that field [example5] is a numeric type.
```

Examples (completely new messages with a new key-name):
1. Default view (3 results):
![2016-03-21-53e1e6d](https://cloud.githubusercontent.com/assets/305739/13933557/0878c9bc-efae-11e5-93ce-b572bdf612b0.png)

2. Quering (1 result):
![2016-03-21-fb1777f](https://cloud.githubusercontent.com/assets/305739/13933610/5cb9ce54-efae-11e5-8e21-282b882c5b46.png)

3. `Field graph`
![2016-03-21-c4ef650](https://cloud.githubusercontent.com/assets/305739/13933674/b2ea3f3e-efae-11e5-873d-ae823c0da5c7.png)

3. Stats
![2016-03-21-997ce68](https://cloud.githubusercontent.com/assets/305739/13933827/5b554fce-efaf-11e5-84f1-5928ae3c3070.png)

**Comment by joschi** [comment]
@kkamkou Try using another GELF client library. It looks like gelf-pro is converting any additional field into a string (which obviously is not a number): https://github.com/kkamkou/node-gelf-pro/blob/0.6.1/lib/gelf-pro.js#L93

**Comment by kkamkou** [comment]
@joschi, thx for the support. I'll check/fix it and close the current ticket if needed.

**Comment by kkamkou** [comment]
Not a problem of gelf or graylog itself.
