### ISSUE TITLE
Field Statistics Widget should refresh according to global refresh settings

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#1961]
### Problem description

The Field Statistics Widget includes an own control do enable/disable automatic refresh. Instead it should be controlled by the global refresh controls which are part of the search bar.

### Steps to reproduce the problem

1. Add Field Statistics widget to search
2. See "Reload automatically"-button

### Environment

* Graylog Version: 2.0.0-alpha.5
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by edmundoa** [comment]
The same happens with quick values, and I think it makes sense that those two have separate controls for that. You may want to see updated statistics or quick values without having to refresh all search results.

Probably we could make them refresh when using their own control or when the global refresh is enabled.
