### ISSUE TITLE
Copy functionality (Copy message, copy id, copy token, copy scratchpad) does not work over http but does work over https

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#19643]
Copy functionality (Copy message, copy id, copy token, copy scratchpad) does not work over http but does work over https.

This appears to have been introduced starting with graylog 6.0.

See also https://github.com/Graylog2/graylog2-server/issues/18788

## Expected Behavior

Copy buttons provided in the UX copy text (at the very least show an error to let the user know the copy failed)

## Current Behavior

Copy buttons do not work when accessing a graylog node via http

## Possible Solution

@a-zombie (Rick) theorizes this is a result of the copy function only working via HTTPS: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard#browser_compatibility

## Steps to Reproduce (for bugs)

Access graylog via http

## Your Environment

* Graylog Version: 6.0.3
* Browser version: Version 125.0.6422.142 (Official Build) (arm64)

**Comment by ryan-carroll-graylog** [comment]
Also see slack discussion for more details: https://graylog.slack.com/archives/C036LC4K744/p1718375050321429

**Comment by ValiDrv** [comment]
Confirmed I used **http** to access GrayLog (vpn, internal network), Under Ubuntu 22.04.3 LTS, and Chrome/Firefox/Edge.
