### ISSUE TITLE
Inconsistent data in web application and plugins stores

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#1965]
### Problem description
When a plugin uses a store from the web interface, or a component that uses them, the state of that store may become inconsistent with the web interface store, resulting in different problems.

### Steps to reproduce the problem
1. Open the log-in page of the web interface, with some UI plugins loaded
1. Reload, to ensure the stores get the same (initial) state
1. Log-in with your user
1. Go to a plugin page, and see how requests are loading all the time. The reason for this is that the `FetchProvider` instance used in the plugin, is not seeing that you logged-in, as the `SessionStore` was instance not updated

### Environment

* Graylog Version: 2.0.0-beta.2-SNAPSHOT

**Comment by dennisoelkers** [comment]
Fixed in #1967.
