### ISSUE TITLE
Plugins increase scheduled requests

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#1966]
### Problem description
Adding a plugin to the web interface may end up duplicating the number of scheduled requests. Some stores use `setInterval` to refresh their data, and that interval may also be set in plugins using that same store, as they get new instances.

### Steps to reproduce the problem
1. Remove all plugins from the server
1. Log into the web interface and open the network requests on your web-developer tools
1. See that the nodes information is loaded once every 5 seconds
1. Add a UI plugin to the server
1. Reopen the previous page
1. See that the nodes information is loaded twice every 5 seconds

### Environment

* Graylog Version: 2.0.0-beta.2-SNAPSHOT

**Comment by dennisoelkers** [comment]
Fixed in #1967.
