### ISSUE TITLE
Generic HTTP input

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#197]
A generic HTTP input is accepting every JSON as HTTP body. Very useful for all kinds of webhooks.

The config dialog should require to define a `source` and a `short_message`. The JSON will be parsed into fields. Also think about nested arrays and hashes.

**Comment by aarvee11** [comment]
Has this been implemented. GELF has a very limited scope as we dont expect Github and Bitbucket send us HTTP Body in GELF Format, instead a generic JSON over HTTP inout will be the best
