### ISSUE TITLE
Plugin JS is not minified in production builds

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1973]
### Problem description

The plugin JS is not minified in production builds.
### Steps to reproduce the problem

1. Check `/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.13b20ba5173e9b333c6a.js` for example.

### Environment

* Graylog Version: Graylog 2.0.0-beta.2-SNAPSHOT (c0846cf)

**Comment by dennisoelkers** [comment]
Wrong repository -> closed in favor of Graylog2/graylog-plugin-archetype#6
