### ISSUE TITLE
Create cluster metrics endpoint that can return metrics for multiple nodes

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#1974]
### Problem description

In a multiple node cluster the web interface does one HTTP call for every node in the cluster to fetch the metrics every 2 seconds.

### Steps to reproduce the problem

1. Setup multi node cluster
2. See multiple HTTP requests in the network tab of the developer tools every 2 seconds

### Proposal

Implement a new REST endpoint that takes a list of node ids and returns the metrics for them.

### Environment

* Graylog Version: Graylog 2.0.0-beta.2-SNAPSHOT (c0846cf)

**Comment by kroepke** [comment]
Rather an "improvement" but since it's a regression to 1.3 we are liberal with the "bug" label.
