### ISSUE TITLE
DataNode: In-place migration doesn't work for OpenSearch 1.x

### ISSUE THREAD

**Issue by vvasylenko** [Graylog2/graylog2-server#19749]
User is not able to use In-Place migration, if OpenSearch version is 1.x

## Expected Behavior
User can use with OpenSearch 1.x In-Place migration

## Current Behavior
Error occurs while migration

## Steps to Reproduce (for bugs)
1. Run OpenSearch 1.3.x
2. Go to System -> Data Nodes
3. Open Migration tab
4. Generate certificates
5. Select In-Place migration

## Your Environment
* Graylog Version: 6.1.0-alpha.2
* Java Version:
* OpenSearch Version: 1.3.0
* MongoDB Version:
* Operating System:
* Browser version:
* *

**Comment by moesterheld** [comment]
@vvasylenko 
can you describe the exact error? I cannot reproduce it.

**Comment by vvasylenko** [comment]
@moesterheld, yep, you are right. Now it's gone
