### ISSUE TITLE
ElasticsearchException - events are lost

### ISSUE THREAD

**Issue by jerrybb** [Graylog2/graylog2-server#19837]
Hi, we are sending application logs in GELF format using Fluentbit to Graylog Server.
There are occasional some errors logged such as:
- failed to parse field [line] of type [long]
- failed to parse field [source_timestamp] of type [date]
- Document contains at least one immense term in field=\"param\" (whose UTF8 encoding is longer than the max length 32766

We are fixing such issue by changing field types or formatting source data to fix these issues. 

But these logs events are lost until fix is applied for each occurrence. We are wondering if there is any way to store such message in any way to prevent data loss? Even if the content would not be indexed.

**Comment by tellistone** [comment]
Hi Jerrybb

If you install the enterprise plugin, you should be able to access failure processing.

<img width="1387" alt="image" src="https://github.com/Graylog2/graylog2-server/assets/85873295/2fe3d125-3b6b-4b58-98e2-da9dfebf456a">

This writes any message that fails to process to a dedicated stream:

<img width="1387" alt="image" src="https://github.com/Graylog2/graylog2-server/assets/85873295/b96a847a-abb3-4141-b01a-1f8625658325">

Index templates or pipeline rules for the purpose of forcing data type to fields will also help you prevent this issue.

For specifics/troubleshoting, you might raise this with Enterprise Support (if you have an Enterprise license) or the Graylog Community.

**Comment by jerrybb** [comment]
Thank you @tellistone, appreciated.
