### ISSUE TITLE
User can't update time zone

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#1984]
### Steps to reproduce the problem

1. Log into Graylog as a user.
2. Go to "Edit profile" page.
3. Change timezone.
4. Click "Update User".

Expected result: The new settings (i. e. the changed time zone) will be saved.
Actual result: Error message in Javascript console:
```
UserForm.jsx:127 Uncaught TypeError: Cannot read property 'getValue' of undefined(anonymous function)
 @ UserForm.jsx:127_updateUser
 @ UserForm.jsx:126
```

### Environment

* Graylog Version: Graylog 2.0.0-beta.1
* Browser version: Chrome 49.0.2623.108

**Comment by roland-hill** [comment]
FYI, the suggested workaround "_to change the user's time zone as admin user on the System -> Users page_" also doesn't work (in case this information assists). Thanks for raising the bug report Jochen.
