### ISSUE TITLE
Changing input deletes all extractors for this input

### ISSUE THREAD

**Issue by piesu** [Graylog2/graylog2-server#1988]
### Problem description

After change to input (setting it as local/global) all extractors for this input are gone

### Steps to reproduce the problem

1. Create Input
1. Create some extractors for this input
1. Go to http://graylogserver/system/inputs
1. Click "more actions" for your input, follow with "edit input"
1. Check/uncheck "global"
1. Save
1. Now this input doesn't have any extractor

### Environment

* Graylog Version:  2.0.0-beta.1 
* Elasticsearch Version: 2.2.1
* MongoDB Version: 2.4.10
* Operating System: Debian Jessie
* Browser version: Iceweasel 44.0.2

**Comment by dennisoelkers** [comment]
Thanks for reporting this. A fix for this will be included in the next beta release.
