### ISSUE TITLE
JSON Extractor preview problem

### ISSUE THREAD

**Issue by matthgyver** [Graylog2/graylog2-server#1992]
### Problem description
When I create a JSON extractor, whatever the contents of the separator configuration fields, when I click on "Try" I get always same result in Extractor preview.

### Environment

* Graylog Version: 1.3.4
* Operating System: CentOS 6

**Comment by bernd** [comment]
I am unable to reproduce this with Graylog 2.x. Please re-open if you still see this with Graylog 2.x. Thank you!
