### ISSUE TITLE
2.0b1 - Link to specific message not working for Reader

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#1993]
### Problem description

A link to a specific message `../messages/graylog2_0/hash` doesn't work due to some permission problem (for a non-admin user)

### Steps to reproduce the problem

* Find a message via a stream, click the message-id.

Result: `Loading message information failed with status: Error: cannot GET http://host:12900/messages/graylog2_0/hash (403)` and an eternal spinner (as reported in #1985)

There is however no such log in the console, the only 403's are for `/system` and `/jvm`?

### Environment

* Graylog Version: 2.0b1
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version: 45.0.1

**Comment by edmundoa** [comment]
Hi,

As you described the issue, I understand the regular user clicked on a message link in the stream search result and couldn't load that message, is that correct? If so, I was unable to reproduce the issue.

Would you be so kind as to answer some questions to know more about the problem?

- Is the user coming from LDAP or AD?
- Was the user created through the web interface?
- Did you assign permissions to the user through the REST API?
- Was the user created with the beta version?

It would also help us to better understand the problem if you could share the user information from MongoDB (check in the `user` collection).

Thank you!

**Comment by SjonHortensius** [comment]
We have this consistently on multiple installs;

* users are created locally
* through the web-interface, yes
* yes; because I needed to fix #1887
* no, but I'll try to create another user to see if that fixes things

**Comment by SjonHortensius** [comment]
Okay, I've deleted and recreated the user and that fixes this issue

**Comment by edmundoa** [comment]
Thank you for your feedback @SjonHortensius!
