### ISSUE TITLE
Graylog keeps disabling streams

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#1996]
Graylog keeps disabling streams. When i check the logs i see this : 

> server.log.1:2016-03-17T23:04:04.048+01:00 WARN  [StreamFaultManager] Processing of stream <55816b2fe4b0a709fb8ab7cc> failed to return within 2000ms.
> server.log.1:2016-03-18T22:25:29.781+01:00 WARN  [StreamFaultManager] Processing of stream <55816b2fe4b0a709fb8ab7cc> failed to return within 2000ms.
> server.log.1:2016-03-23T23:04:14.574+01:00 WARN  [StreamFaultManager] Processing of stream <55816b2fe4b0a709fb8ab7cc> failed to return within 2000ms.
> server.log.1:2016-03-23T23:16:15.176+01:00 WARN  [StreamFaultManager] Processing of stream <55816b2fe4b0a709fb8ab7cc> failed to return within 2000ms.
> server.log.1:2016-03-24T17:11:11.677+01:00 WARN  [StreamFaultManager] Processing of stream <55816b2fe4b0a709fb8ab7cc> failed to return within 2000ms.
> server.log.1:2016-03-24T17:45:14.987+01:00 WARN  [StreamFaultManager] Processing of stream <55816b2fe4b0a709fb8ab7cc> failed to return within 2000ms.
> server.log.1:2016-03-24T21:26:49.515+01:00 ERROR [StreamFaultManager] Processing of stream <55816b2fe4b0a709fb8ab7cc> failed to return within 2000ms for more than 3 times. Disabling stream.

But what i can't find is why it's taking > 2000ms to process the stream. Is ES slow? Is Graylog slow? How can i fix this? Because it is pretty annoying that it keeps disabling streams..

**Comment by joschi** [comment]
@dennusb Streams are completely processed by Graylog. Usually that hints to too few hardware resources for given load.

You can also check the metrics for those streams to find out which rule is slow (see System &rarr; Nodes &rarr; Metrics and the metrics below ` org.graylog2.plugin.streams.*`).

**Comment by dennisoelkers** [comment]
Created follow up ticket to add functionality which should help debugging cases like this. Closing ticket for now as no further action is possible from our side.
