### ISSUE TITLE
Allow user to choose 'Browser' as a valid timezone option

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#19979]
## What?

Allow user to choose 'Browser' as a valid timezone option

## Why?

Currently we require the user to explicitly choose a timezone. We also default this timezone to UTC (i think? or the timezone of the graylog server) which requires the user to understand this and to explicitly change their timezone.

I've noticed that some web apps have the ability to choose "browser" which [detects what timezone the browser is using](https://webbrowsertools.com/timezone/) and uses that. With this option, and as a default, viewing graylog would default to the proper timezone. If the user needed or wanted, they could still override it by choosing an explicit timezone as they do today.

**Comment by janheise** [comment]
@drewmiranda-gl Just as a comment: we save the timezone per user. if you make "browser" an option, the user's timezone could change often. E.g. the user has different browsers on different computers, and each of them es configured differently? (maybe not on purpose) This could create a lot of bugs.

**Comment by linuspahl** [comment]
Currently when the user does not select a time zone, we are using the browser time zone.

<img width="773" alt="image" src="https://github.com/user-attachments/assets/f5a81b8e-9090-4864-ad65-4b4fa4d4edb3">

"system's default" is referring to the browser time zone. I like the idea of making this an explicit option.

**Comment by drewmiranda-gl** [comment]
Wow thats great! "system's default" is ambigious so this is helpful to know. I just removed the timezone and found it worked as expected. Do you know why cloud seems to explicitly fill in UTC vs leaving this blank? Maybe thats a separate GH issue.

**Comment by drewmiranda-gl** [comment]
UPDATE: it appears this functionality already exists and works out of box.

Suggestions for improvement:

* Improve the language and UX to be more clear:
    * Instead of system say something like browser time
    * Allow 'browser' to be a selectable item
* Fix bug where Graylog Cloud forces this value to be UTC when a new user logs in.

**Comment by kmerz** [comment]
The only thing left is that @drewmiranda-gl found this to be a problem in the cloud. This is probably because the user is synced from a third party, and the default is set to UTC instead of leaving it empty.

**Comment by drewmiranda-gl** [comment]
Revisiting this, noting that Graylog Cloud for some reason always forces a newly created Graylog User to use UTC time despite graylog having the ability to default to the user's browser timezone.

**Comment by tellistone** [comment]
Raised https://github.com/Graylog2/graylog-plugin-enterprise/issues/9452 to track Graylog Cloud not using "system's default" as default.

Raised https://github.com/Graylog2/graylog-plugin-enterprise/issues/9453 to track the need for better UI copy to describe what system default actually entails

Closing this issue
