### ISSUE TITLE
Map widget not bound to a stream

### ISSUE THREAD

**Issue by 123dev** [Graylog2/graylog2-server#1999]
### Problem description
When you add a map widget to a dashboard, the stream information is lost (not bound).
When you edit a map widget, the query is not visible / editable.

### Steps to reproduce the problem

- Start from a stream that shows a subset of all the logs,
- View World Map
- Add it to dashboard
- Check dashboard
- You'd see that the map shows for all logs (not just the stream logs)
- If you check the widget info, you see: _Widget is **not** bound to a stream._

Incidentally, if you try to edit the widget, neither the query string nor the stream association is visible or editable.

### Environment

* Graylog Version: Graylog 2.0.0-beta.1
* Elasticsearch Version: 2.2.1
* MongoDB Version: 3.2.4
* Operating System: Ubuntu 14.04
* Browser version: Firefox 44.03

**Comment by tmacgbay** [comment]
This is still an issue in GL 3.0 (for me) but it was closed without comment..  Could you leave a note on why it was closed?
