### ISSUE TITLE
Adding map widget to a dashboard fails

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-server#2001]
### Problem description

When I try to add a map widget to a dashboard I receive the error message "could not create widget". This happens in both search and streams.

![bildschirmfoto 2016-03-30 um 18 21 11](https://cloud.githubusercontent.com/assets/6331205/14149508/ca3191e0-f6a4-11e5-9577-9fe7e622555f.png)

### Steps to reproduce the problem

1. Perform a search
2. Click on a field that contains geo data and create map
3. Add widget to a dashboard and you receive the error message that can be seen in the screenshot.

### Environment
 
* QA setup 
* Graylog Version: Graylog-2.0.0-beta.2
* Browser version: Firefox 45.0.1 also happens in Chrome 49.0.2623.110

**Comment by edmundoa** [comment]
I just tested the changes in the demo setup and it seems to work fine again.
