### ISSUE TITLE
Styling issue with map widget

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-server#2003]
### Problem description

When having a long list of dashboards and adding a map widget to a dashboard the dashboardlist and the map are overlapping. This needs styling.

### Steps to reproduce the problem

1. Perform a search
2. Click on a field that contains geo data and create map
3. Add widget to a dashboard. If you have a long list of dashboards it is overlapping with the map itself

### Environment

* QA setup
* Graylog Version: Graylog-2.0.0-beta.2
* Browser version: Firefox 45.0.1

**Comment by edmundoa** [comment]
Fixed in https://github.com/Graylog2/graylog-plugin-map-widget/commit/94a79782f7e3e50f3f6bd41c9a89ace978387893
