### ISSUE TITLE
You are running an outdated Graylog version

### ISSUE THREAD

**Issue by wangxingzhen** [Graylog2/graylog2-server#20055]
<!      --- Provide a general summary of the issue in the Title above -->
I have two servers with graylog6.0.3 and 6.0.4-1 deployed using docker-compose.      Why do I get the message that this version is out of date
```
You are running an outdated Graylog version
(triggered a month ago)
The most recent stable Graylog version is 6.0.3 (Noir) released at 2024-06-05T00:00:00.000Z. See what's new in the [Open](https://docs.graylog.org/docs/changelog) and [Operations](https://docs.graylog.org/docs/changelog-graylog) changelogs!
```
## Current Behavior
<!      --- If describing a bug, tell us what happens instead of the expected behavior -->
<!      --- If suggesting a change/improvement, explain the difference from current behavior -->

## Possible Solution
<!      --- Not obligatory, but suggest a fix/reason for the bug, -->
<!      --- or ideas how to implement the addition or change -->

## Steps to Reproduce (for bugs)
this is my docker-compose.yml:
datanode:
image: "${DATANODE_IMAGE:-graylog/graylog-datanode:6.0.4-1}"
graylog:
hostname: "server"
image: "${GRAYLOG_IMAGE:-graylog/graylog:6.0.4-1}"

* Graylog Version:6.0.4-1
* Java Version:
* OpenSearch Version:6.0.4-1
* MongoDB Version:5.0
* Operating System:
* Browser version:

**Comment by janheise** [comment]
@wangxingzhen Hi, just for confirmation: if you are logged into the frontend, you should see the version in the footer line at the bottom of the page. Can you confirm that it's actually the expected version? Also, check for environment variables that override your setting in `docker-compose.yml`

**Comment by wangxingzhen** [comment]
Maybe it's because I imported the graylog5.2 mongo config. This hint doesn't bother me. Here's the version in the bottom footer of my page:Graylog 6.0.4+9759bc7 on server (Eclipse Adoptium 17.0.11 on Linux 5.10.134-16.3.al8.x86_64),Thank you for your reply. I will close this issue
