### ISSUE TITLE
INPUTs imported from json don't honour "global" : true,

### ISSUE THREAD

**Issue by qfissler** [Graylog2/graylog2-server#2006]
### Problem description
With clustered Graylog servers, imported global input specs fail to apply to all nodes.

### Steps to reproduce the problem

1. 
    },
    "type" : "org.graylog2.inputs.gelf.udp.GELFUDPInput",
    "global" : true,
    "extractors" : [ {
      "title" : "Extract key-value pairs",
      "type" : "COPY_INPUT",
      "configuration" : { },
      "converters" : [ {
        "type" : "TOKENIZER",
        "configuration" : { }
      } ],
      "order" : 0,
      "cursor_strategy" : "COPY",
      "target_field" : "full_message",
      "source_field" : "full_message",
      "condition_type" : "NONE",
      "condition_value" : ""
    } ],
    "static_fields" : { }
  }, {

2. Import that in the web ui.

### Environment
Built from 1.3.4 AWS AMI
+ dpkg -E -G -i graylog_latest.deb (1.3.4-2)

* Graylog Version: 1.3.4-2
* Elasticsearch Version: 
* MongoDB Version: 
* Operating System: Ubuntu 14.04.4 LTS
* Browser version: Chrome 49.0.2623.75 (64-bit)

**Comment by joschi** [comment]
@qfissler Please provide the complete content pack that fails to correctly import/apply on your Graylog server.

Also please add a little more detail to your problem description, e. g. what the expected result is.

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
