### ISSUE TITLE
Value not declared, importing content pack would fail - case sensitivity bug

### ISSUE THREAD

**Issue by Norbinsh** [Graylog2/graylog2-server#2011]
### Problem description

Using the GUI to create extractors, and then exporting them into a json file.
Then, when trying to make use of the exported extractors in a content pack, it will fail to load it, complaining it could not be parsed or is in the wrong format.

The syntax I used is perfectly valid, as none of which was written manually. both the content pack, and the extractors, are created by the very same graylog instance, yet they fail to work with one another.

The following error (One of many, depends on the extractor content, it can be things other than just strings that'd fail) would appear in the web logs upon trying to load the content pack, with the extractors exported:

"[error] application - Could not parse uploaded bundle: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not construct instance of org.graylog2.restclient.models.Extractor$ConditionType from String value 'none': value not one of declared Enum instance names: [NONE, STRING, REGEX]"

The solution? go to the very same extractor you just exported, and change "condition_type": "none" to "NONE", same goes for enum instances ("cut", "copy" etc).

### Steps to reproduce the problem

1. Once graylog is running (using the official docker image as described below), you are started off with the default "appliance_content_pack", which works great... before you try to modify it :).
2. Try to create some extractors using the GUI, and export them as json.
3. Edit the content pack file to include some of those exported extractors, in one of the inputs.
4. Try to create new new image with the modified content pack, or just manually import the content pack, you'll notice it fails.
5. Edit the values mentioned above to UPPER case, and everything will work just fine.

### Environment

Using the most recent official graylog docker image:
Graylog (1.3.4) full stack installation

I'll be more than happy to provide more information as needed.

Thank you.

**Comment by Norbinsh** [comment]
I might have mixed the exportation of extractors directly and content packs, since I noticed if i am exporting a content pack (And choosing the input with the extractors) it works just fine and outputs the extractors in upper case. however, I still think this should be applied to when export is made on extractors directly, unless there's a reason for this. Thanks!

**Comment by edmundoa** [comment]
Hi,

The reason why the condition types are exported in lower case in the export extractor page is because it was always like that.

Anyway, I really don't see an issue here. The documents exported from the content packs and the export extractor page are not meant to be edited by hand, and they don't use the same format, so they don't need to be compatible.

**Comment by Norbinsh** [comment]
Fair enough, Keep up the good work!

Thanks!
