### ISSUE TITLE
Process buffer is getting full very fast and once full messages are not getting processed.

### ISSUE THREAD

**Issue by shivakhuba** [Graylog2/graylog2-server#2014]
We have installed whole graylog setup in the production.

Graylog server 1.3.0 running with 12GB Heap
Graylog UI 1.3.3       3GB Heap
Elastic search 1.7.2      5 GB Heap (not indexing the data)
MongoDB 3.0.4  5GB Heap 

Messages are coming 600/sec and average message size is approximately 1 MB.

Each message is getting processed through DRL, wherein we are extracting fields from it. 

We are not indexing in Elastic search, added "m.setFilterOut(true)" this property.

We have increased all the processor and ring also, but still buffer process buffers are getting full.

Once processor buffer is full and graylog stops processing the message. Kafka journal is getting saturated.

Attached DRL file.

Kindly request you to get back with solution asap.
[graylog.zip](https://github.com/Graylog2/graylog2-server/files/199441/graylog.zip)

Thanks and Regards,
Shivakumar Khuba

**Comment by edmundoa** [comment]
Hi,

We use Github for tracking bugs in Graylog itself, but this doesn't look like it. Please post this issue in our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or in the [#graylog IRC channel](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
