### ISSUE TITLE
Report preview not loading

### ISSUE THREAD

**Issue by Emy-01** [Graylog2/graylog2-server#20169]
The preview of the widgets doesn't load. The page stays in an infinite loading mode. 

## Expected Behavior
The widgets are loaded in the preview section

## Current Behavior
The section stays blank with an infinite loader.

## Steps to Reproduce (for bugs)

1. In the smd env, create a report from the dashboard called: A introspective dashboard for Emy
2. 1. see the widgets not loading on preview.

**Comment by dennisoelkers** [comment]
From what I can see, opening the report shows a loading spinner for ~60s and then just shows the cover page of the report, but no widgets. Is it the same for you, @Emy-01?
