### ISSUE TITLE
2.0b2 Webinterface only mode not possible anymore

### ISSUE THREAD

**Issue by wmrichard** [Graylog2/graylog2-server#2021]
### Problem description

Servers can't be configured to webinterface only mode.

### Steps to reproduce the problem

1. Execute graylog-ctl
2. sudo graylog-ctl reconfigure-as-webinterface
3. Command not recognized.

This option does work in the stable version.

### Environment

* Graylog Version:2.0b2 Appliance on VMware
* Elasticsearch Version:Appliance
* MongoDB Version:Appliance
* Operating System:Appliance
* Browser version:NA

**Comment by mariussturm** [comment]
Hi,
this is intended since the web interface moved into the server in Graylog 2.0. So basically there is no single web interface anymore.
