### ISSUE TITLE
ERROR: io.netty.util.ResourceLeakDetector

### ISSUE THREAD

**Issue by HeyITGuyFixIt** [Graylog2/graylog2-server#20262]
I've noticed this error several versions ago, but noticed it still occurs in 6.0.5 and apparently there has been no bug reports. I'm not aware of it causing issues with the usability of Graylog, but it is a logged error nonetheless. Looks like some function/method was not called before an object was garbage-colleted.

## Expected Behavior

Garbage-collection should be handled correctly with no leaks. This error shouldn't occur.

## Current Behavior

```
ERROR: io.netty.util.ResourceLeakDetector - LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
 Recent access records: 
 Created at:
  io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:404)
  io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
  io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
  io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
  io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:120)
  io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75)
  io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:786)
  io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
  io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
  io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
  io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:212)
  java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66)
  java.base/java.lang.Thread.run(Unknown Source)
```

## Possible Solution

Probably should call `ByteBuf.release()` before it's garbage-collected.

## Steps to Reproduce (for bugs)

Honestly not sure how to reproduce.  I see it occur once a day at different times.

## Your Environment

* Graylog Version: Docker container graylog/graylog:6.0.5
* OpenSearch Version: Docker container opensearchproject/opensearch:2.15.0
* MongoDB Version: MongoDB 6.0.16 Community installed on Windows 10 Pro 22H2
* Operating System: Docker containers on Ubuntu Server 24.04 LTS

**Comment by sethgraylog** [comment]
Are there logs in the Graylog Server logs around the time of the garbage collection you can add?
