### ISSUE TITLE
2.0b2 Cannot access REST API

### ISSUE THREAD

**Issue by tr31z** [Graylog2/graylog2-server#2027]
### Problem description
I get a 404 error when trying to access the API
>[root@graylog-server2 ~]# curl http://graylog-server2.mydomain:12900
>{"type":"ApiError","message":"HTTP 404 Not Found"}

Here is the logoutput:

> 2016-04-05T10:33:22.650+02:00 INFO  [node] [graylog-server2] starting ...
> 2016-04-05T10:33:22.653+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.AlertScannerThread] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.654+02:00 INFO  [Periodicals] Starting [org.graylog2.periodical.BatchedElasticSearchOutputFlushThread] periodical in [0s], polling every [1s].
> 2016-04-05T10:33:22.657+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.ClusterHealthCheckThread] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.657+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.ContentPackLoaderPeriodical] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.657+02:00 INFO  [Periodicals] Starting [org.graylog2.periodical.GarbageCollectionWarningThread] periodical, running forever.
> 2016-04-05T10:33:22.657+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.IndexerClusterCheckerThread] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.658+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.IndexRetentionThread] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.658+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.IndexRotationThread] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.658+02:00 INFO  [Periodicals] Starting [org.graylog2.periodical.NodePingThread] periodical in [0s], polling every [1s].
> 2016-04-05T10:33:22.658+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.VersionCheckThread] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.658+02:00 INFO  [Periodicals] Starting [org.graylog2.periodical.ThrottleStateUpdaterThread] periodical in [1s], polling every [1s].
> 2016-04-05T10:33:22.659+02:00 INFO  [Periodicals] Starting [org.graylog2.events.ClusterEventPeriodical] periodical in [0s], polling every [1s].
> 2016-04-05T10:33:22.659+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.events.ClusterEventCleanupPeriodical] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.659+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.ClusterIdGeneratorPeriodical] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.659+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.IndexRangesMigrationPeriodical] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.659+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.IndexRangesCleanupPeriodical] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.659+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.UserPermissionMigrationPeriodical] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.659+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.AlarmCallbacksMigrationPeriodical] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.660+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.ConfigurationManagementPeriodical] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.660+02:00 INFO  [PeriodicalsService] Not starting [org.graylog2.periodical.LdapGroupMappingMigration] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.669+02:00 INFO  [Periodicals] Starting [org.graylog.plugins.usagestatistics.UsageStatsNodePeriodical] periodical in [300s], polling every [21600s].
> 2016-04-05T10:33:22.670+02:00 INFO  [PeriodicalsService] Not starting [org.graylog.plugins.usagestatistics.UsageStatsClusterPeriodical] periodical. Not configured to run on this node.
> 2016-04-05T10:33:22.670+02:00 INFO  [PeriodicalsService] Not starting [org.graylog.plugins.collector.periodical.PurgeExpiredCollectorsThread] periodical. Only started on Graylog master nodes.
> 2016-04-05T10:33:22.735+02:00 INFO  [AbstractJerseyService] Enabling CORS for HTTP endpoint
> 2016-04-05T10:33:22.832+02:00 INFO  [transport] [graylog-server2] publish_address {192.168.0.211:9300}, bound_addresses {192.168.0.211:9300}
> 2016-04-05T10:33:22.839+02:00 INFO  [discovery] [graylog-server2] graylog2/tldxN1SASeest6bTL9O2vg
> 2016-04-05T10:33:23.047+02:00 INFO  [AbstractJerseyService] Enabling CORS for HTTP endpoint
> 2016-04-05T10:33:25.181+02:00 INFO  [NetworkListener] Started listener bound to [graylog-server2.mydomain:9000]
> 2016-04-05T10:33:25.182+02:00 INFO  [HttpServer] [HttpServer] Started.
> 2016-04-05T10:33:25.183+02:00 INFO  [WebInterfaceService] Started Web Interface at <http://graylog-server2.mydomain:9000/>
> 2016-04-05T10:33:25.846+02:00 WARN  [discovery] [graylog-server2] waited for 3s and no initial state was set by the discovery
> 2016-04-05T10:33:25.846+02:00 INFO  [node] [graylog-server2] started
> 2016-04-05T10:33:25.920+02:00 INFO  [service] [graylog-server2] detected_master {elasticsearch1}{2WusI_WBT1q5DXuCGS3TlQ}{192.168.0.207}{192.168.0.207:9300}{master=true}, added {{elasticsearch2}{Gf69W2yjRyq1-05Y3YbvNQ}{192.168.0.208}{192.168.0.208:9300}{master=true},{elasticsearch1}{2WusI_WBT1q5DXuCGS3TlQ}{192.168.0.207}{192.168.0.207:9300}{master=true},{graylog-server1}{k-GFzIfDS3uybDDMNoBMqg}{192.168.0.210}{192.168.0.210:9300}{client=true, data=false, master=false},{elasticsearch3}{P-W-D9zCSFyti2Z0AdEg4A}{192.168.0.209}{192.168.0.209:9300}{master=false},}, reason: zen-disco-receive(from master [{elasticsearch1}{2WusI_WBT1q5DXuCGS3TlQ}{192.168.0.207}{192.168.0.207:9300}{master=true}])
> 2016-04-05T10:33:28.752+02:00 INFO  [NetworkListener] Started listener bound to [graylog-server2.mydomain:12900]
> 2016-04-05T10:33:28.752+02:00 INFO  [HttpServer] [HttpServer-1] Started.
> 2016-04-05T10:33:28.753+02:00 INFO  [RestApiService] Started REST API at <http://graylog-server2.mydomain:12900/>
> 2016-04-05T10:33:28.754+02:00 INFO  [ServiceManagerListener] Services are healthy
> 2016-04-05T10:33:28.756+02:00 INFO  [ServerBootstrap] Services started, startup times in ms: {OutputSetupService [RUNNING]=6, MetricsReporterService [RUNNING]=8, KafkaJournal [RUNNING]=9, BufferSynchronizerService [RUNNING]=13, InputSetupService [RUNNING]=17, PeriodicalsService [RUNNING]=28, JournalReader [RUNNING]=58, WebInterfaceService [RUNNING]=2535, IndexerSetupService [RUNNING]=3320, RestApiService [RUNNING]=6107}
> 2016-04-05T10:33:28.756+02:00 INFO  [InputSetupService] Triggering launching persisted inputs, node transitioned from Uninitialized [LB:DEAD] to Running [LB:ALIVE]
> 2016-04-05T10:33:28.764+02:00 INFO  [ServerBootstrap] Graylog server up and running.
> 2016-04-05T10:33:28.784+02:00 INFO  [InputStateListener] Input [GELF UDP/56587ccbe4b00c9ed99ff8bb] is now STARTING
> 2016-04-05T10:33:28.802+02:00 WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input GELFUDPInput{title=GELF Udp, type=org.graylog2.inputs.gelf.udp.GELFUDPInput, nodeId=null} should be 262144 but is 212992.
> 2016-04-05T10:33:28.809+02:00 INFO  [InputStateListener] Input [GELF UDP/56587ccbe4b00c9ed99ff8bb] is now RUNNING
> 

### Steps to reproduce the problem
I updated graylog 1.3 to 2.0b2 and here are the configurations concerning the api 

> rest_listen_uri = http://graylog-server1.mydomain:12900/
> rest_transport_uri = http://graylog-server1.mydomain:12900/
> rest_enable_cors = true

> rest_enable_gzip = true
> rest_enable_tls = False
> 

> rest_tls_cert_file = /path/to/graylog2.crt
> 
> rest_tls_key_file = /path/to/graylog2.key
> 
> rest_tls_key_password = secret
> rest_max_chunk_size = 8192
> rest_max_header_size = 8192
> rest_max_initial_line_length = 4096
> rest_thread_pool_size = 16 

### Environment

* Graylog Version: 2.0b2
* Elasticsearch Version: 2.3
* MongoDB Version: 2.6.12
* Operating System: Centos 7.2
* Browser version: Firefox 45

**Comment by joschi** [comment]
@tr31z There is simply no resource defined for http://graylog-server2.mydomain:12900, so the response is completely normal and generated by Graylog itself. There also aren't any errors in your logs, so I assume everything is fine.

Do you have any specific problems with the Graylog REST API?

**Comment by tr31z** [comment]
Oh ok, the thing is that I get the following error on the graylog web-interface and I thought the origin of the problem was the API not being reachable
>Server currently unavailable

> Error message
>     Bad request
> Original Request
>     GET http://graylog-server1.mydomain:12900/system/cluster/node
> Status code
>     undefined
> Full error message
>     Error: Request has been terminated
>     Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

**Comment by tr31z** [comment]
Of found it ! Now that the web interface has moved on the server nodes, the client machine needs to have access to the ports 9000 and 12900. I updated my firewall rules and I have now access to the interface.
Thanks for the hint !
