### ISSUE TITLE
Pipeline exception causes pipeline stage to exit, additional rules in same stage do not execute

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#20301]
Pipeline rule exceptions do not appear to be properly isolated. For example, if you have a pipeline stage with 2 rules, and the 1st rule throws an exception (which, if enabled, typically will be logged via the Processing and Indexing Failures stream), the 2nd rule will not execute. This is unexpected behavior.

I observed and tested this using the `otx_lookup_ip` pipeline function:

1. If/when this function returns an exception, such as HTTP 502
    * `In call to function 'otx_lookup_ip' at 17:13 an exception was thrown: OTX IPv4 request for key <IP> failed: 502`
2. A pipeline rule in the same stage that adds a field is never executed

Looking at the 2 fields in aggregate and comparing the difference also shows the discrepancy, meaning the pipeline rules int the same stage following the rule that had an exception were not executed:

<img width="970" alt="image" src="https://github.com/user-attachments/assets/7ce0c3fe-29dd-47b8-ae41-e569e63f0a72">
<img width="668" alt="image" src="https://github.com/user-attachments/assets/ab04079e-9ced-4c30-9c46-eab07b08b43e">

Note the 2 exceptions above match the difference of the count of the 2 fields.

## Expected Behavior

Pipeline rule exceptions do not cause the pipeline stage to immediately exit.

## Current Behavior

Pipeline rule with an exception causes the pipeline stage to exist, no further rules in that stage are evaluated nor processed.

## Possible Solution

Catch exceptions at the pipeline rule level to prevent the pipeline stage from encountering an error/exception

## Steps to Reproduce (for bugs)

I don't have a great way to do this but i imagine if you have a way to easily cause a pipeline rule to throw an exception that should work

## Context

Occasionally see processing errors caused by pipeline rule exceptions.

## Your Environment

* Graylog Version: 6.0.5
* Java Version: Bundled
* OpenSearch Version: 2.15.0
* MongoDB Version: 7.0.14
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 128.0.6613.85 (Official Build) (arm64)

Please let me know if there are any questions.

**Comment by sethgraylog** [comment]
This is working as intended. Exceptions should create a hard exit from the pipeline stage. To avoid this, additional rules should be moved to a separate stage.
