### ISSUE TITLE
Receivers not showing up in Alerts configuration.

### ISSUE THREAD

**Issue by bobpage2** [Graylog2/graylog2-server#2033]
### Problem description
Email alerts are working. Yet, when I enter a username and press the "subscribe" button, nothing happens. I still see "No configured alert receivers." I tried entering an email address directly. The "No configured alert receivers." still shows up.
![graylog-email](https://cloud.githubusercontent.com/assets/18292610/14293171/5e2c0964-fb39-11e5-95ce-6665430592cb.JPG)

### Steps to reproduce the problem

1. Enter a username
2. Press enter or click the "subscribe" button.

Am i doing something wrong?

### Environment

* Graylog Version: Graylog 2.0.0-alpha.5 from OVA
* Browser version: Firefox 45.0.1

**Comment by variable** [comment]
Having exact issue.

**Comment by edmundoa** [comment]
Hi,

I was trying to reproduce this issue using beta 2, but I can. Could you please try in the latest beta and see if it is still happening? If it does, please report any errors you see in your browser's developer console.

Thank you!

**Comment by dennisoelkers** [comment]
Please try again with the recently released 2.0.0-RC.1 and reopen this issue if it still persists.
