### ISSUE TITLE
Extended geoip data.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-server#2034]
Hi,

I've been playing a bit with GL 2.0. Geoip is really nice feature.
I think by adding some additional geoip data like Continent, Country, City etc will give more benefit to the  Graylog.

This fields can be enabled by default or they can be configurable.

regards,

**Comment by jhaar** [comment]
I agree. In particular digging down into a map to a location triggers a popup show the lat/long. However, humans aren't good at reading lat/long - a city name (in particular) would be much more human-friendly :-)

Besides that, I'm liking the maps :-)

**Comment by bernd** [comment]
This can be done with the upcoming Graylog 2.3 and the new lookup tables feature in combination with a pipeline rule.
