### ISSUE TITLE
OVA deployment doesn't load webpage

### ISSUE THREAD

**Issue by ukzerosniper** [Graylog2/graylog2-server#2037]
### Problem description
I downloaded the OVA and deployed it in ESXI with all the default options.

It collects an IP and I can login via console no issue.

I can ping the machine on our LAN.

When I browse the IP address that it collected via DHCP, no website is shown.  This issue does not occur in the ALPHA version.

### Steps to reproduce the problem

1. ...  Install the OVA on ESXI
2.  Collect IP via DHCP
3.  Attempt to browse the website via the IP collected

### Environment

* Graylog Version: 1.3.4
* Elasticsearch Version: 
* MongoDB Version:
* Operating System:
* Browser version: Google Chrome 49.0.2623.110 on Win10

**Comment by mariussturm** [comment]
Do you have some more informations about this problem? Any error from a log file in `/var/log/graylog/*/current` can help.

**Comment by mariussturm** [comment]
Closing this, if the problem still exist please feel free to re-open.
