### ISSUE TITLE
Caching within Graylog Metafile Generation

### ISSUE THREAD

**Issue by codeitdandy** [Graylog2/graylog2-server#2038]
### Problem description
Need to introduce caching within Graylog during Message Rewriting with Drools (DRL)

We are intercepting  and using drools engine within graylog server(drl file) to rewrite our logs and generate key value pairs which we send it to graylog collector for further process. This key value pairs provides us with better understanding of our logs. 
We are invoking properties file within our drl file to create such key value pairs, but to optimize and improve our solution we dont want the properties file to be created within drl each time , rather it should act as singleton resource/cached resource created once when the server is up and running. 

Is there any community guidelines/best practices for caching properties file when accessed from drl resource. We are struggling when trying to invoke third party jars/external classes from drl files and "it fails with cannot be resolved to a type " issues.

**Comment by kroepke** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like it. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
