### ISSUE TITLE
Missing investigation_ids field required in the test case.

### ISSUE THREAD

**Issue by luk-kaminski** [Graylog2/graylog2-server#20403]
## Expected Behavior
From the test case:
```
Expand the message and look for the investigation_ids field.
Expected result:
The field has the IDs of all investigations that the log has been added to as evidence.
```

## Current Behavior
`investigation_ids` does not appear in the UI:
![image](https://github.com/user-attachments/assets/4c2d3212-4cf8-4caf-a31e-43122a525273)

## Possible Solution
?

## Steps to Reproduce (for bugs)
Follow `Delete Shared Evidence` steps from TestQuality.

## Your Environment
https://test-dev-ng.dev.graylog.cloud
Graylog Cloud 6.1.0 (450)

**Comment by ryan-carroll-graylog** [comment]
The `Delete Shared Evidence` test case is no longer relevant sin the changes in https://github.com/Graylog2/graylog-plugin-enterprise/pull/7653.

We were testing that the OS evidence was updated correctly but we are no longer tracking investigation IDs or updating OS evidence once it's added.
