### ISSUE TITLE
OS Transport/HTTP Ports cannot be changed in data node docker image

### ISSUE THREAD

**Issue by moesterheld** [Graylog2/graylog2-server#20408]
## Expected Behavior
OS Ports should reflect the environment variables

## Current Behavior
ports hardcoded to 9200/9300

## Steps to Reproduce (for bugs)

1. start data node docker image
2. try to change opensearch ports using `GRAYLOG_DATANODE_OPENSEARCH_HTTP_PORT` and `GRAYLOG_DATANODE_OPENSEARCH_TRANSPORT_PORT`

## Your Environment

* Data Node Version: 6.1.0-beta-1-1

**Comment by dennisoelkers** [comment]
Fixed in Graylog2/graylog-docker#276.
