### ISSUE TITLE
Search page - Double error/warning icons

### ISSUE THREAD

**Issue by ryan-carroll-graylog** [Graylog2/graylog2-server#20409]
## Description
When there is a warning/error for a search, 2 icons appear in the UI:
![image](https://github.com/user-attachments/assets/27c6edd3-0c58-4445-9a04-7c2893d4fa87)
![image](https://github.com/user-attachments/assets/b8ad2f31-81aa-43a1-a0bf-a8d1e3e0d37c)

## Steps To Reproduce

1. Navigate to search page
2. Enter a bad search query

## Environment

- Graylog Version: 6.1.0-beta.1
- OpenSearch Version:
- MongoDB Version:
- Browser Version: Firefox & Chrome LTS

**Comment by tellistone** [comment]
Marking this as a blocker because it looks _really_ janky

**Comment by grotlue** [comment]
This seems to be a general issue with search validation, it's always shown twice, independent of Data Tiering.
