### ISSUE TITLE
Issue with Grok Filter for TIMESTAMP_ISO8601

### ISSUE THREAD

**Issue by wingZero21** [Graylog2/graylog2-server#2042]
### Problem description
Issue with Grok Filter for TIMESTAMP_ISO8601

### Steps to reproduce the problem

1 Sending data to graylog with Timestamp ISO8601 does not pick up unless the Grok filter has a slight amendment detailed below.

### Environment

* Graylog Version: 1.3.3

Details:
Just need to amend the seconds to the ISO seconds variable to fix this.

Variable ISO8601_SECOND
```
Previous Grok filter 
TIMESTAMP_ISO8601	%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{SECOND})?%{ISO8601_TIMEZONE}?

Updated Grok Filter
TIMESTAMP_ISO8601	%{YEAR}-%{MONTHNUM}-%{MONTHDAY}[T ]%{HOUR}:?%{MINUTE}(?::?%{ISO8601_SECOND})?%{ISO8601_TIMEZONE}?
```

**Comment by bernd** [comment]
This works for me on Graylog 2.1.0-alpha.2.

My `TIMESTAMP_ISO8601` pattern:

![image](https://cloud.githubusercontent.com/assets/461/16956480/df707dce-4dd8-11e6-9bfe-e3b17c576758.png)

My extractor config:

![image](https://cloud.githubusercontent.com/assets/461/16956439/be4d96ae-4dd8-11e6-9c29-c77585f45ab4.png)

The resulting message:

![image](https://cloud.githubusercontent.com/assets/461/16956422/ad0d59ec-4dd8-11e6-8830-62736ab67af4.png)

I am closing this, please re-open if you still have problems with this with Graylog 2.x. Thank you!
