### ISSUE TITLE
Indexing Errors caused by ClusterBlockException[blocked by: [FORBIDDEN/8/index write (api)]]

### ISSUE THREAD

**Issue by jehuty0shift** [Graylog2/graylog2-server#2043]
### Problem description
In our cluster we experience many times, indexing Errors just after the cycling of index deflector.
The Error is the following :
 

> RemoteTransportException[[es-hot-23.XXX.XXX.com][inet[/XXX.XXX.XX.XX:9300]][indices:data/write/bulk[s]]]; nested: ClusterBlockException[blocked by: [FORBIDDEN/8/index write (api)];];

It should be due to the task that make the index ReadOnly. See here 
https://github.com/Graylog2/graylog2-server/blob/b6ae9f62eec6029a31d2cfa70448213bc5ccc616/graylog2-server/src/main/java/org/graylog2/indexer/Deflector.java#L159
Actually, the cluster still tries to write to the previous deflector 2 or 3 minutes after the cycling. So 30 seconds is not sufficient and too optimistic for some clusters. Is it not possible to have a setting  to disable this task or at least make the Delay before firing the task configurable ?  

### Steps to reproduce the problem

1. Have a big ES cluster (40 nodes indexing).
2. Cycle the index during a heavy indexing ( > 100 000 logs by sec). 

### Environment

* Graylog Version: 1.3.3
* Elasticsearch Version: 1.7.5
* MongoDB Version: 3.2
* Operating System: Debian 8
* Browser version: Chromiumv45

**Comment by kroepke** [comment]
This is basically a race condition that is more apparent with large ES clusters due to the huge cluster state size.
We believe that incremental cluster state updates in ES >=2.0 will mitigate the effect.

**Comment by jehuty0shift** [comment]
Hello, thanks for the reply. Indeed this is completely possible that incremental cluster updates, mitigates the problem. As soon as Graylog 2.0 is out. we will test it and report here if the problem disappeared.

**Comment by jehuty0shift** [comment]
This has been fixed in Graylog 2.0.3 with Elasticsearch 2.X
