### ISSUE TITLE
Graylog-WEB don't retrieve all of my messages

### ISSUE THREAD

**Issue by svoron1986** [Graylog2/graylog2-server#2044]
Hi!
I have a graylog server collecting syslog data via Syslog TCP. My elasticsearch base show that it have 2643 messages, and I can see all of them via HQ plugin or via Elasticsearch API. But graylog-web show me only 265 ones! I select "Search in all messages" in my web-ui. What can I do to view all messages what really I have in the my base?

Thank you!!

### Environment

* Graylog Version: graylog-server-1.3.4-1 , graylog-web-1.3.4-1 
* Elasticsearch Version: elasticsearch-1.7.5-1
* MongoDB Version: mongodb-org-server-3.0.10-1
* Operating System: CentOS Linux release 7.1.1503
* Browser version: Firefox 43.0.4

**Comment by joschi** [comment]
@svoron1986 Maybe some of those messages contained a timestamp "from the future". Try running a search with an absolute time range and set the end timestamp a few hours into the future.

**Comment by svoron1986** [comment]
Yess!!  It's working!  Joschi, thank you so much!!
