### ISSUE TITLE
Index Set Templates List - selecting "Custom Config" column breaks the whole list....

### ISSUE THREAD

**Issue by luk-kaminski** [Graylog2/graylog2-server#20460]
## Expected Behavior
"Custom Config" column is not selectable or does not break the UI.

## Current Behavior
See screenshots.

## Possible Solution
?

## Steps to Reproduce (for bugs)
Go to System -> Indices -> Index Set Templates
![Screenshot from 2024-09-17 09-56-28](https://github.com/user-attachments/assets/4e62914b-a36d-4d3d-b85b-687cae080160)
![Screenshot from 2024-09-17 09-53-20](https://github.com/user-attachments/assets/d010d9ac-31bc-42a2-95a5-eb04a7a68e5b)
![Screenshot 2024-09-17 at 09-52-41 Graylog](https://github.com/user-attachments/assets/734123a4-12c4-466e-8335-0cf36e49687f)

## Context
The only way to bring things back to normal that I have found was to... remove corresponding document in `entity_list_preferences` MongoDB collection...

## Your Environment
6.1

**Comment by patrickmann** [comment]
Already fixed by #20449
Unfortunately didn't make the beta2 build.
