### ISSUE TITLE
Message table link to node results in 404

### ISSUE THREAD

**Issue by grotlue** [Graylog2/graylog2-server#20464]
## Expected Behavior
- Link to node details page in message table does not result in a 404

## Current Behavior
- Link to node details page in message table does results in a 404

## Steps to Reproduce (for bugs)

1. Visit `/search/`
2. Open any log in the message table
3. click on the node link
4.

## Your Environment

* Graylog Version: Graylog Cloud 6.1.0 (451)
* Java Version:
* OpenSearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by luk-kaminski** [comment]
Hi @grotlue !
Do you mean `Received by` section link?
![image](https://github.com/user-attachments/assets/bd1cee82-adcf-40a3-9424-75c707f96095)

I am asking because I cannot reproduce this problem, I am brought to proper node page and have never faced 404 there...

**Comment by grotlue** [comment]
Hi @luk-kaminski Yes, exactly, on the cloud testing instance it would redirect to a node details page, but that page resulted in 404.

**Comment by grotlue** [comment]
@luk-kaminski Yes, I think hiding the link on cloud would solve this. 👍
