### ISSUE TITLE
6.1: Event definition -> Event Correlation shows disabled due to no valid license

### ISSUE THREAD

**Issue by damianharouff** [Graylog2/graylog2-server#20475]
In 6.1 beta 2, creating an event definition -> condition -> event correlation shows a box that event correlation is disabled because there is no valid license. This is noted in an install with an Enterprise and Security license.

![image](https://github.com/user-attachments/assets/afb22e0a-d50f-483f-b936-c4fc56b2da49)

My licenses page:

![image](https://github.com/user-attachments/assets/14ac0450-6306-4bb5-a620-c9a2abd12add)

Unsure if event correlations are actually stopped/disabled. 

## Your Environment

* Graylog Version: 6.1.0-beta.2+3f1795e
* Java Version: embedded
* OpenSearch Version: 2.15
* MongoDB Version: 7
* Operating System: Debian 12 on LXC
* Browser version:Browser version: Arc Version 1.60.0 (53678), Chromium Engine Version 128.0.6613.138

Also noted in test-dev-ng: Graylog Cloud 6.1.0 (451)

**Comment by AntonEbel** [comment]
We send `undefined` as subject here:
![image](https://github.com/user-attachments/assets/d82209b7-9b4e-4d51-b9f5-86eb5b90801a)
