### ISSUE TITLE
Add to search not working from Quick values

### ISSUE THREAD

**Issue by jekelundh** [Graylog2/graylog2-server#2047]
### Problem description
Add to search not working from Quick values
### Steps to reproduce the problem
1. From "Fields" column, expand any field and click Quick Values
2. In Quick values click "+"-sign (add to search)
3. Expected behaviour is updated search bar but nothing happens
( _Desired_ behaviour would be updated search bar _and_ search executed but I guess there are tons of feature requests on that one ?)  

### Environment

* Graylog Version: graylog-server-2.0.0-3.beta.2.noarch
* Elasticsearch Version: elasticsearch-2.2.1-1.noarch
* MongoDB Version: mongodb-org-server-3.0.9-1.el6.x86_64
* Operating System: Fedora release 17 (Beefy Miracle) x86_64
* Browser version: FF 45.0.1 (Windows), Chrome 49.0.2623.110 (win) ,IE 11.0.9600.18230

**Comment by edmundoa** [comment]
Hi,

I'm closing this issue, as it is duplicating #2040. Please track the progress on that ticket.

Thank you!
