### ISSUE TITLE
Add the ability to add a series to a stacked chart

### ISSUE THREAD

**Issue by dklotz** [Graylog2/graylog2-server#2049]
### Problem description

After a widget with a stacked chart was added to a dashboard you can edit the different existing series in the widget, but you cannot add a new series to the existing widget through the current web UI. It would be really helpful if the ability to add a new series was added to the UI of editing the series of an existing stacked chart dashboard widget.
### Steps to reproduce the problem
1. Create a stacked chart.
2. Add it to a dashboard.
3. Try to add a new series to this dashboard widget.
### Environment
- Graylog Version: 1.3.3

**Comment by manishjhawar** [comment]
+1
Also a remove option available against series to make it really CRUD :-)

**Comment by dennisoelkers** [comment]
Stacked charts have been changed fundamentally in `3.2.0`. You can now add and remove metrics to any given aggregation, therefore I consider this issue to be fixed.
