### ISSUE TITLE
Think about incrementally building histograms and charts

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#205]
Another `$BIG_COMPETITOR` is building charts incrementally. If you decide to build a graph over longer periods of times, you shouldn't have to wait until the full search has returned. Instead we could query each index step by step (or even iterate in defined hour steps over each index if that is fast enough) and then add more data to the chart every time a search part returned.

cc @kroepke

**Comment by bernd** [comment]
Closing this because. Please re-open if still relevant. Thank you!
