### ISSUE TITLE
Aggregation Unit formatting for Size shows lowercase b, which indicates bits, even though the units are configured for bytes

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#20518]
Aggregation Unit formatting for Size shows lowercase b, which indicates bits, even though the units are configured for bytes

> https://en.wikipedia.org/wiki/Bit
>
> The symbol for the binary digit is either “bit”, per the [IEC 80000-13](https://en.wikipedia.org/wiki/IEC_80000-13):2008 standard, or the lowercase character “b”, per the [IEEE 1541-2002](https://en.wikipedia.org/wiki/IEEE_1541-2002) standard. Use of the latter may create confusion with the capital “B” which is the international standard symbol for the byte.

<img width="828" alt="image" src="https://github.com/user-attachments/assets/c137d342-5e2b-4570-be97-e7d60c415e86">

## Expected Behavior

B = Bytes
kB = Kilobytes
mB = Megabytes
gB = Gigabytes

## Current Behavior

b = Bytes
kb = Kilobytes
mb = Megabytes
gb = Gigabytes

## Steps to Reproduce (for bugs)

1. Create an aggregation widget and configure size units

![image](https://github.com/user-attachments/assets/87d118b0-782c-4b6a-ba97-49a178bb920a)

## Your Environment

* Graylog Version: Graylog 6.1.0-SNAPSHOT+dc307e9

Please let me know if there are any questions.

**Comment by boosty** [comment]
Good catch! 

> Expected Behavior
>
> B = Bytes
> kB = Kilobytes
> mB = Megabytes
> gB = Gigabytes

One tiny remark though: `mB` and `gB` look uncommon to me.

What I usually see are the formats mentioned on https://en.wikipedia.org/wiki/Byte#Multiple-byte_units.

**Comment by systemboogie** [comment]
I came here to state something similar. 🙂 The shorthands for prefixes "mega" and above should be uppercase. So, with bytes, we should show themas MB, GB, TB, ...

https://en.wikipedia.org/wiki/Metric_prefix
