### ISSUE TITLE
2.0.0-beta.2 web interface fails to load due to strict MIME rules

### ISSUE THREAD

**Issue by aberenyi** [Graylog2/graylog2-server#2052]
### Problem description
Web interface fails to load with error `Refused to execute script from 'https://graylog.example.com/config.js' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.` when `X-Content-Type-Options: nosniff` header is present on the request.

### Steps to reproduce the problem

1. Set up nginx to proxy to the Graylog web interface port
2. Add `add_header X-Content-Type-Options nosniff;` to the config

### Environment

* Graylog Version: 2.0.0-beta.2
* Elasticsearch Version: 2.3.1-1
* MongoDB Version: 3.2.3-2
* Operating System: ArchLinux
* Browser version: Chrome

**Comment by dennisoelkers** [comment]
Hey @aberenyi,

thanks for reporting this. This issue has already been fixed and the fix will be included in the next beta which will be released this week.

**Comment by aberenyi** [comment]
@dennisoelkers 🎉
