### ISSUE TITLE
A bug about stream rule

### ISSUE THREAD

**Issue by loveyang2012** [Graylog2/graylog2-server#20548]
When I use the stream rule, I get a problem, when I load a message to test rules, it is fine, but when I actually use it, it just doesn't work, I think there is something wrong about "_".
![672acf01f4ab22b3cf9ce0fe871b819](https://github.com/user-attachments/assets/d9dc2d39-4376-455a-96f1-2aa637aab501)
![37c82fc73c851b13776d2150c5d8a02](https://github.com/user-attachments/assets/dca15af8-1562-48ba-8fa9-c97ea8f6b9d9)
you can see that loading a message to test rules is ok.

![a9bad828b3d41f2c5d403f9842533f6](https://github.com/user-attachments/assets/d99990c9-37e6-4a56-a1a3-3c29dd01cd57)
but, it doesn't work .
I think there is something wrong about "_" of "container_name", so I used field "pod" ,it works
![image](https://github.com/user-attachments/assets/38e2477e-6422-473e-8570-91730d1d276a)

* Graylog Version: 5.2.11 with jvm
* OpenSearch Version: es 7.10.2
* MongoDB Version: 6.x
* Operating System: centos8
* Browser version: google

**Comment by drewmiranda-gl** [comment]
Can you confirm the fields that are sent to graylog contain the underscore? I can't say for certain but typically when these issues occur it has to do with the field name not matching correctly. See https://github.com/Graylog2/graylog2-server/issues/13043

**Comment by loveyang2012** [comment]
> Can you confirm the fields that are sent to graylog contain the underscore? I can't say for certain but typically when these issues occur it has to do with the field name not matching correctly. See #13043
> 
> For example, if a field is set to graylog as `container.name = helloworld` graylog silently changes it to `container_name = helloworld`
> 
> I also recomend considering replacing your stream rules with pipeline rules that perform the `route_to_stream()` action. See https://go2docs.graylog.org/current/making_sense_of_your_log_data/functions_descriptions.html?Highlight=route_to_stream#routetostream

thanks a lot ,when I chaged container_name  to  container.name , it works.
