### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by rooty123** [Graylog2/graylog2-server#2055]
### Problem description

Javascript error on page: dashboards
### Steps to reproduce the problem

Just open the page and see in browser console:

Warning: Failed propType: Invalid prop `dashboards` of type `List` supplied to `DashboardList`, expected instance of `List`. Check the render method of `DashboardListPage`.
 /vendor.js:405
### Environment
- Graylog Version: 2.0 beta2
- Elasticsearch Version: 2.3.1
- MongoDB Version:2.6
- Operating System: Linux
- Browser version: Chrome 48.0.2564.97

**Comment by edmundoa** [comment]
Hi,

Thank you for reporting the issue!

Is there any visible error on the page, other than the warning in the JS console? Also, could you please tell us how you installed Graylog?

**Comment by rooty123** [comment]
Hi, looks like the error doesn't affect any visible functions.
Graylog was installed from deb repo.

**Comment by edmundoa** [comment]
That is a message intended for development, so you shouldn't worry too much about it, at least as long as you don't get any other issues in the page.

Anyway we should take a look, so let's leave the issue open.

**Comment by dennisoelkers** [comment]
Probably never an issue and not anymore due to fundamental code changes.
