### ISSUE TITLE
ISW - Wizard Step: Start Input Step

### ISSUE THREAD

**Issue by grotlue** [Graylog2/graylog2-server#20567]
- When switching to this step, the input and everything else configured in the previous steps will be excuted
- It shows a list of all the steps that have been completed
- It shows errors and error messages of failed steps
- Next Step: https://github.com/Graylog2/graylog2-server/issues/20683

![4748b276-c649-488f-b8df-87271083e97b#media-blob-url=true id=b9b9b4a3-697e-49b0-890f-2ee61c9e5677 contextId=10149 collection=](https://github.com/user-attachments/assets/9604a273-8211-4ea5-ba76-41a0ba66017d)

**Comment by tellistone** [comment]
Maybe we present the text as showing what will be done (eg. Input "my Big Input" will be started!) rather than what is already done

We discussed performing the actions sequentially, and showing user error of which step fails in event of fail

we discussed rolling anything we created here back, in the event of a fail

**Comment by tellistone** [comment]
if the input no longer exists or is not in setup mode when you press OK, handle that exception

**Comment by grotlue** [comment]
# Steps that are executed

## Always
- Start Input

## Option 1 - Use default stream
- Create Pipeline Rule
- Add Pipeline Rule to Pipeline -> TBD: Which Pipeline?

## Option 2 - Use existing stream
- Create Pipeline Rule
- Add Pipeline Rule to Pipeline  -> TBD: Which Pipeline?

## Option 3 - New Stream
- Create Stream
- Create Pipeline
- Connect Pipeline to Stream
- Create Pipeline Rule
- Add Pipeline Rule to Pipeline


Not in scope for this cycle, but with adding the Illuminate flow, we will have more steps here

**Comment by grotlue** [comment]
> Re option 1: What default stream is this referring to? According to https://github.com/Graylog2/graylog2-server/issues/20568, user either selects an existing stream or creates a new one.

Default is: All messages (Default Stream)

Both API options sound fine for me. Both would need the pipeline name (nullable -> which means default) and the input id passed, right?

**Comment by grotlue** [comment]
## Discussion outcome 19.11.2024

- For messages to work with Illuminate, we need them to be in the Default Stream first. That's one of the reasons why we prefer pipeline rules over stream rules.
- We need an immutable pipeline for wizard-related routing (e.g. "built-in" or "system" pipeline)
  - we always add rule to stage 0
  - in this case immutable means:
    - not deletable
    - can't be renamed
    - connections can't be changed
    - rules can be deleted, added, edited
  - Alternative approach: pipeline is deletable, but will be recreated immediately
    - That would lead to users potentially messing up routing that was created by a wizard (we can live with that though)
    - less effort as it won't need UI adjustments
