### ISSUE TITLE
Clicking on zoom icon doesn't affect anything

### ISSUE THREAD

**Issue by rooty123** [Graylog2/graylog2-server#2056]
### Problem description
When clicking on zoom icon at sources page nothing happens. But it should rewrite search string
![screenshot from 2016-04-12 13 31 11](https://cloud.githubusercontent.com/assets/371690/14457425/0f975f90-00b3-11e6-93a5-1fb148604586.png)
 and scroll up.

### Environment

* Graylog Version: 2.0. beta2
* Elasticsearch Version: 2.3
* MongoDB Version:2.6
* Operating System: Linux 
* Browser version: Chrome 48.0.2564.97

**Comment by edmundoa** [comment]
Hi,

I'm closing this issue, as it is duplicating #2040. Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
