### ISSUE TITLE
Create generic data directory for Graylog to use

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#2057]
Graylog needs to store a few things on the local filesystem during its operation, e.g.
- journal
- pid file
- node file
- elasticsearch autogenerated files
- self-generated TLS files

Currently each of these is relative to the CWD of the server, but we don't have a common parent directory.
For simplification of setting Graylog up introduce a default data-dir which the other paths use as a relative base path, unless overridden.

**Comment by joschi** [comment]
> Currently each of these is relative to the CWD of the server, but we don't have a common parent directory.

FWIW, they're only relative if the configuration file contains relative paths. The configuration file can also contain absolute paths.

**Comment by kroepke** [comment]
Yup, that's what I meant, thanks for clarifying :+1:
