### ISSUE TITLE
Graylog supports new versions of Elasticsearch

### ISSUE THREAD

**Issue by ysj2018** [Graylog2/graylog2-server#20668]
Based on the information I've seen, Elasticsearch has returned to being open-source, and there has been further collaboration between Elastic and AWS. This raises the possibility of Elasticsearch and OpenSearch becoming compatible again. Regarding Graylog's future plans, is there any indication that Graylog intends to support newer versions of Elasticsearch?

Currently, does Graylog only support Elasticsearch 7.10 and OpenSearch?

**Comment by sethgraylog** [comment]
As of this time, we have no plans to begin adding support for newer versions of elasticsearch.

**Comment by 8Iue** [comment]
Reviving this topic, as ElasticSearch+Kibana visualizations are key-components for my requirements.

Is there any future plans to support Elasticsearch?

**Comment by sethgraylog** [comment]
Hi @8Iue , I dont understand your question. I am not clear how supporting ElasticSearch as our backend indexer helps you with your Kibana visualization requirements.  As of this time, we still have no plans to add support for new versions of ElasticSearch. We have standardized using OpenSearch. There are multiple visualizations available through Graylog's UI.
