### ISSUE TITLE
Full text search is not working properly (at least base don docs)

### ISSUE THREAD

**Issue by zet-mar** [Graylog2/graylog2-server#20713]
## Expected Behavior
I would expect full-text search to work correctly for any part of the search term (no matter I use rodrigeus or "rodrigeus" or m.rodrigeus or "m.rodrigeus" etc.), returning more or fewer matches depending on the precision of the input. However, the current behavior seems non-standard or erroneous.

## Current Behavior
During a full-text search across all streams, we discovered that it does not work as described in the documentation – [documentation part we follow](https://go2docs.graylog.org/current/making_sense_of_your_log_data/writing_search_queries.html).

We realized this because we have alerts set up in Graylog for our SIRP team. When one of these alerts was triggered, I tried to investigate it by searching the logs for something like: m.rodrigeus (this format).

I entered, rodrigeus, into the full-text search, and set it to search logs from the past X days, but found nothing. I then searched for `rodrigeus` and "rodrigeus," but still got no results. I even used the regex form for the full-text search, yet nothing came up. It only started working when I entered m.rodrig (like this no ", or `), at which point it found the relevant entries across all streams, which I had also expected from the earlier full-text searches.

## Possible Solution
I have no proposal for a possible solution, just maybe have a look and fix the searching part of the product. 

## Steps to Reproduce (for bugs)

1. create logs that will contains something like (this form) - m.rodrigeus
2. create multi-action with the system so logs containing m.rodrigeus will come to the Graylog
3. Go to the search bar, and put there just: rodrigeus or "rodrigeus" or `rodrigeus` - you will see that no match will be found.

## Context
We work in a way that first I try to use a full-text search for all possible cases for a certain person. Then I filter out anything not related based on streams (to which they rely), and this way perform more precise searching and alerting. Based on our approach we will not be able to find those alerts and therefore actions that this person did (it is possible to change our behavior and use m.rodrigeus instead of just rodrigeus, but still it is full-text so it should work or not?). 

## Your Environment

* Graylog Version: 5.2.10  
* Java Version: Ubuntu 17.0.12
* ElasticSearch Version: 7.10.2 
* MongoDB Version: 6.0.17 
* Operating System: MacOS (for where I run query - my computer), but also Linux computer. Graylog is running on this version of OS: ubuntu-20.04-server-amd64-virtio-scsi-20210823
* Browser version: Chrome 129.0.6668.100 (Official Build) (arm64), but also found on different Browsers the same behavior

**Comment by drewmiranda-gl** [comment]
Are you able to post a full example of both your search query and the json message you (e.g. using copy message in graylog) you are expecting to match against?

By default, graylog only returns full text search results for "analyzed" fields, which is the "message" field. If the text you are searching against is in another field you may need to take additional steps to meet your needs, such as parsing the text into its own field.

So far what you describe is working as designed, albeit maybe not in the most intuitive way.

**Comment by zet-mar** [comment]
@drewmiranda-gl Yes of course but the majority of fields have to be blurred due to the nature of the data (sensitivity), but I think still there should be visible that it is not working like expected (at least I think). I took out the field message (even it is blurred almost completely due to the reason above). You can see that there is just one change - I put it into the search field instead of y.zhuvchuk just zhyvchuk and the number of matched messages go to zero 🤷‍♂️ (from above 7000 matches, where I put y.zhyvchuk and it appears in the message field in all cases. 

![SCR-20241016-stf](https://github.com/user-attachments/assets/7d588908-3bbc-4db4-92a3-0235fb4adf23)
![SCR-20241016-spr](https://github.com/user-attachments/assets/3bf8015e-8166-4abd-bace-cba4cc7b9b46)
![SCR-20241016-ssk](https://github.com/user-attachments/assets/a325045c-817f-4bd0-a92d-1f87ab3f4884)

**Comment by drewmiranda-gl** [comment]
I'm assuming that message exists in the default `graylog_` index set and the field is the `message` field.

If those things are true, Graylog (well technically Elasticsearch/OpenSearch) users the [standard analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-standard-analyzer.html) for the message field. You can confirm this by using the following Elasticsearch/OpenSearch API Query:

```
/graylog_94/_mapping?pretty
```

Replace `graylog_94` with the index name that message lives in. You will get a json output but the important part is:

```json
{
    "graylog_94": {
        "mappings": {
            "properties": {
                "full_message": {
                    "type": "text",
                    "analyzer": "standard"
                },
                "message": {
                    "type": "text",
                    "analyzer": "standard"
                }
            }
        }
    }
}
```

I've omitted everything except the mappings for the `full_message` and `message` fields to illustrate these are configured with `"analyzer": "standard"`. Note that an index set other than `graylog_` does not have this behavior.

You can also use the [Analyze API](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html) to simulate how the standard analyzer will split the string into tokens:

```
POST /_analyze
```

```json
{
  "analyzer": "standard",
  "text": "some text nauthuser=\"y.zhyvchukl\" more text"
}
```

This returns:

```json
{
    "tokens": [
        {
            "token": "some",
            "start_offset": 0,
            "end_offset": 4,
            "type": "<ALPHANUM>",
            "position": 0
        },
        {
            "token": "text",
            "start_offset": 5,
            "end_offset": 9,
            "type": "<ALPHANUM>",
            "position": 1
        },
        {
            "token": "nauthuser",
            "start_offset": 10,
            "end_offset": 19,
            "type": "<ALPHANUM>",
            "position": 2
        },
        {
            "token": "y.zhyvchukl",
            "start_offset": 21,
            "end_offset": 32,
            "type": "<ALPHANUM>",
            "position": 3
        },
        {
            "token": "more",
            "start_offset": 34,
            "end_offset": 38,
            "type": "<ALPHANUM>",
            "position": 4
        },
        {
            "token": "text",
            "start_offset": 39,
            "end_offset": 43,
            "type": "<ALPHANUM>",
            "position": 5
        }
    ]
}
```

Which helps illustrate how the Standard Analyzer is tokening the string. We can see that a dot (`.`) character is not used to split words into separate tokens, and `y.zhyvchukl` is maintained as a single token. This means that a text search for `zhyvchukl` will not match `y.zhyvchukl`.

One approach you can take to get the desired result is to use a Processing Pipeline rule to parse out `y.zhyvchukl` into its own field. You can even further parse it, for example splitting on `.` into 2 separate fields:

```
name_part_one: y
name_part_two: zhyvchukl
```

When these fields are present, the text search for `zhyvchukl` matches the field `name_part_two` and returns the result.

I hope this was helpful.

**Comment by kmerz** [comment]
@zet-mar as it seems the question got answered. So I will close this issue. If you think, that this is still a problem, please reopen with a comment.
