### ISSUE TITLE
sidecar-collector will support splunk forwarder?

### ISSUE THREAD

**Issue by rajkumarv3** [Graylog2/graylog2-server#2074]
### Problem description
I am forwarding machine data using splunk forwarder to graylog the new feature sidecar-collector will support to manage splunk forwarder configuration like blacklist, routing ect., also is it possible to create tenant based index by using sidecar+splunk forwarder?

### Environment

* Graylog Version: 1.3.3 in production and 2.0 in testing phase
* Elasticsearch Version: 1.7.2 in production and 2.x in testing phase
* MongoDB Version: 3.2
* Operating System: CentOS 6.6

**Comment by kroepke** [comment]
We have no plans to support Splunk's forwarder at this time. If this is important for you, please enter it on our Ideas portal at https://www.graylog.org/pages/product_ideas

Thanks!
