### ISSUE TITLE
Graylog-datanode stuck in provisioning certificate (step 3)

### ISSUE THREAD

**Issue by mcury1985** [Graylog2/graylog2-server#20757]
I’m trying to migrate from opensearch 2.15.0 to Graylog-datanode
During migration attempt, Graylog-datanode stuck in provisioning certificate (step 3), it never goes beyond this step.

Graylog with SSL is working following the guide below, no problems at all, just can't migrate to graylod-datanode.
[https://graylog.org/post/how-to-guide-securing-graylog-with-tls/](https://graylog.org/post/how-to-guide-securing-graylog-with-tls/)

## Expected Behavior
Migration from opensearch to graylog-datanode should work.

## Current Behavior
It gets stuck in migration step 3, provisioning certificate to data nodes.

## Possible Solution
I noticed that during the migration wizard, the transport address showed doesn't match my CNAME in my certificate, it gets the hostname https://rpi5:9200, already tried to change the hostname in datanode.conf but it doesn't seem to honor that setting.
A possible solution would be for the CNAME in transport address to match the bundled CA that I'm uploading.
Also tried to generate the CA in the Wizard, Graylog CA, but the same problem happens.

## Steps to Reproduce (for bugs)
1. In /etc/graylog/datanode/datanode.conf
Configured using same values as Graylog server.conf for: password_secret, root_password_sha2.
2. In /etc/graylog/datanode/datanode.conf opensearch_data_location I set with the same value of path.data found in /etc/opensearch/opensearch.yml.
3. Run the migration wizard with any certificate settings (generate or upload CA) with the settings above.

## Context
Can't migrate from opensearch 2.15 to graylod-datanode

## Your Environment
* Graylog Version: 6.1.0-15
* Graylog-datanode Version: 6.1.0-15
* Java Version: Temurin-17.0.12+7
* OpenSearch Version: 2.15.0
* MongoDB Version: 6.0.16
* Operating System: Raspberry PI 5 8GB - Raspberry PI OS 64 bits based on Debian GNU/Linux 12 (bookworm) - up to date
* Browser version: Firefox 131.0.3

## Steps have you already taken to try and solve the problem?
Tried to use a self signed CA during the migration attempt.
Also tried to upload my own bundled CA, upload works but there is no improvement, I get stuck in the same step (Provisioning certificate do data nodes).
Tried to in datanode.conf, to set a hostname matching my CA, but it seems that transport address remains the same in the migration page.

**Comment by mcury1985** [comment]
My bad, it was a permission issue in my opensearch data folder.
**chown -R graylog-datanode:graylog-datanode /media/opensearch** fixed the issue.
Thanks

**Comment by vadimax** [comment]
In the line "chown -R graylog-datanode:graylog-datanode /media/opensearch" what is media if I have those:

/etc/default/opensearch
/etc/init.d/opensearch
/etc/opensearch
/etc/sysconfig/opensearch
/usr/share/doc/opensearch
/usr/share/graylog-datanode/dist/opensearch-2.15.0-linux-x64/bin/opensearch
/usr/share/opensearch
/usr/share/opensearch/bin/opensearch
/usr/share/lintian/overrides/opensearch
/run/opensearch
/var/lib/graylog-datanode/opensearch
/var/lib/graylog-datanode/opensearch/config/opensearch
/var/lib/opensearch
/var/log/graylog-datanode/opensearch
/var/log/opensearch
