### ISSUE TITLE
AD Attribute Query Failure on Authentication

### ISSUE THREAD

**Issue by drsharp42** [Graylog2/graylog2-server#2076]
Pardon this first post to Github and Graylog.
## External authentication with AD (2012) fails. Specificly the test user web page provides incomplete sense that test authen. works. 

 :-| User check <green check> Login check 
LDAP attributes of the user
## LDAP Groups of the user

Looking at tcpdump of traffic. The LDAP query includes multiple attributes for the user:
        0x0000:  4500 00e9 cc3a 4000 4006 abde c0a8 2025  E....:@.@......%
        0x0010:  c0a8 2080 bab9 0185 8196 0213 fd6d d66e  .............m.n
        0x0020:  8018 00e5 c2d1 0000 0101 080a 0b81 cdd6  ................
        0x0030:  093e 09a0 3081 b202 0102 6381 ac04 1963  .>..0.....c....c
        0x0040:  6e3d 5573 6572 732c 6463 3d73 6176 6572  n=Users,dc=XXXXX
        0x0050:  732c 6463 3d63 6f6d 0a01 020a 0103 0201  s,dc=com........
        0x0060:  0002 0100 0101 00a0 30a3 1304 0b6f 626a  ........0....obj
        0x0070:  6563 7443 6c61 7373 0404 7573 6572 a319  ectClass..user..
        0x0080:  040e 7341 4d41 6363 6f75 6e74 4e61 6d65  ..sAMAccountName
        0x0090:  0407 2222 2222 2222 7030 4e04 0263 6e04  ..dxxxxrp0N..cn.
        0x00a0:  012a 0402 646e 0403 7569 6404 1175 7365  .*..dn..uid..use
        0x00b0:  7250 7269 6e63 6970 616c 4e61 6d65 0404  rPrincipalName..
        0x00c0:  6d61 696c 040d 7266 6338 3232 4d61 696c  mail..rfc822Mail
        0x00d0:  626f 7804 086d 656d 6265 724f 6604 0a69  box..memberOf..i
        0x00e0:  734d 656d 6265 724f 66                   sMemberOf
The return packet (from AD server) does not contain any results.

The server.log records an error:
2016-04-13T17:48:01.300-07:00 WARN  [SessionsResource] Unable to log in user duXXXXp
org.apache.shiro.authc.AuthenticationException: No account information found for authentication token [org.apache.shiro.authc.UsernamePasswordToken - duXXXXp, rememberMe=false] by this Authenticator instance.  Please check that it is configured correctly.

Using a CLI ldapsearch tool... if I include either "rfc822Mail" or "ismemberOf"; a error is returned from our AD servers. Dropping these attributes, returns values, and group membership.
This works ; 
    ldapsearch search="(&(objectClass=user)(sAMAccountName=duXXXXp))" attrs="uid,mail,distinguishedName,cn,userPrincipalName,memberOf"

Note: in working through the LDAP Group configuration, was able to get graylog to pull our security groups, and create a mapping to roles. So that part of the integration works.
### Steps to reproduce the problem
1. ...
### Environment
- Graylog Version: graylog-server-1.3.4-1.noarch
- Elasticsearch Version: elasticsearch-1.7.5-1.noarch
- MongoDB Version: mongodb-org-server-3.0.11-1
- Operating System: CentOS 7-1511
- Browser version: IE 11

Thank You

**Comment by bernd** [comment]
This should not be an issue anymore in Graylog 4.0. Please open a new issue if you still see the problem. Thank you!
