### ISSUE TITLE
Authentication Service - Keycloak error before login with Graylog 6.1

### ISSUE THREAD

**Issue by logopk** [Graylog2/graylog2-server#20770]
## Expected Behavior
Login Page shows link to Keycloak Authentication Service
## Current Behavior
Error is shown:
![image](https://github.com/user-attachments/assets/c1320be2-d61b-4e90-a2f3-d4186ee46e9b)

Apparently this error is also in the JavaScript Console
![image](https://github.com/user-attachments/assets/6a12312f-c3a2-46df-84b3-0fe88106082f)
There are no errors server side - also no blocks, 403 oder 404 in Apache accesslog

## Steps to Reproduce (for bugs)
1. Install Graylog 6.1 Enterprise

## Context
I can only login using my local admin account and no longer use my keycloak users
## Your Environment

* Graylog Version: 6.1
* Java Version: Eclipse Adoptium 17.0.12
* Operating System: Docker 27
* Browser version: Safari 18, Chrome 130
* Reverse Proxy Apache

>

**Comment by logopk** [comment]
Do you mind to explain what "completed" means?

**Comment by ousmaneo** [comment]
Hi @logopk, The issue is fixed in this new [release](https://go2docs.graylog.org/current/changelogs/operations_changelog.html?tocpath=Changelogs%7C_____2).
