### ISSUE TITLE
Install / upgrade on SUSE - repository is not added

### ISSUE THREAD

**Issue by hilocz** [Graylog2/graylog2-server#20782]
In documentation
https://go2docs.graylog.org/current/downloading_and_installing_graylog/suse_installation.htm
https://go2docs.graylog.org/current/upgrading_graylog/upgrading_graylog_in_suse.htm

one of the installation/upgrade steps is install of repository + PGP key, PGP key is installed, but repository file is put in WRONG folder. 

## Expected Behavior
repo file should be installed in to folder /etc/zypp/repos.d/

## Current Behavior
repo file is installed in to folder /etc/yum.repos.d/

## Possible Solution
place repo file in correct folder 

## Steps to Reproduce (for bugs)
1. sudo rpm -Uvh https://packages.graylog2.org/repo/packages/graylog-6.1-repository_latest.rpm

## Your Environment
* Graylog Version: 6.1
* Operating System: SLES 15 SP5, openSUSE Leap 15.5

**Comment by okwute419** [comment]
@hilocz, thanks for raising this issue. The issue has been addressed in the doc, kindly check and confirm and we can close the issue.
