### ISSUE TITLE
graylog-server.log doesn't seem to have the ability to be rotated or deleted

### ISSUE THREAD

**Issue by drewmmiranda** [Graylog2/graylog2-server#2081]
### Problem description
Graylog-server seems to behave odly with log files. Using logrotate to swap out log files to keep them from growing to large, or even manually deleting and renaming the log files (which seems to be what log rotate is doing?) doesn't work as expected.

Graylog-server will never write to a new log file if the old one was deleted until the process is stopped/started. This makes managing growing log files very difficult and causes hard disk space to be used up.

### Steps to reproduce the problem

1. Have a working graylog environment
2. Have a graylog-server.log file that you wish to rotate or delete because it is large
3. delete graylog-server.log
4. create new blank file for graylog-server to log to
5. log never has any content until graylog-server is stopped and restarted

### Environment

* Graylog Version: 1.2.3
* Elasticsearch Version: 1.7.2
* MongoDB Version: 2.6.11
* Operating System: CentOS 7
* Browser version: N/A

**Comment by joschi** [comment]
@drewmmiranda Graylog 1.x is using Log4j 1.2 for its own logging needs. You can configure the logging subsystem to rotate log files automatically, see https://logging.apache.org/log4j/1.2/manual.html for details and https://github.com/Graylog2/graylog2-server/blob/1.3.4/graylog2-bootstrap/src/main/resources/log4j.xml for the default Log4j configuration file.

If you've been using the OS packages to install Graylog, you might want to take a look at https://github.com/Graylog2/fpm-recipes/blob/1.3/recipes/graylog-server/files/log4j.xml

Please post to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog) to continue this discussion. Thanks!

**Comment by drewmmiranda** [comment]
Awesome! Thank you so much. :)
