### ISSUE TITLE
Accessing Graylog Web Interface using a URI other than `/` returns a frontend error

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#20837]
**Editing to note this appears to only occur with `graylog-enterprise` and not with `graylog-server`**

Accessing Graylog Web Interface using a URI other than `/` returns a frontend error

![image](https://github.com/user-attachments/assets/35185e52-1b9b-490e-8ace-a7d8240ba980)

Note this appears to not occur on the login screen, but does occur on any screen after logging in.

## Expected Behavior

Graylog is [documented](https://go2docs.graylog.org/current/setting_up_graylog/server.conf.html?Highlight=server.conf) to allow publishing its Web Interface at a path other than `/`, however, 6.1 introduces a bug where setting `http_publish_uri` to have a path other than `/` returns an error.

## Current Behavior

Accessing Graylog Web Interface using a URI other than `/` returns a frontend error

## Steps to Reproduce (for bugs)

1. Configure `http_publish_uri = http://$http_bind_address/graylog/` via `server.conf`
2. Browse to the above URI
3. Attempt to login

## Context

Originally reported via https://community.graylog.org/t/unexpected-application-error-after-upgrade-from-6-0-7-to-6-1-1/34016

## Your Environment

* Graylog Version: 6.1
* Java Version: Bundled

**Comment by drewmiranda-gl** [comment]
Confirmed this behavior occurs in 6.1.0 and 6.1.1, Did not observe this behavior in 6.0

**Comment by cbreit** [comment]
6.1.3 seems to fix the problem.
Thanks for the quick reaction :-)

**Comment by NiceRath** [comment]
Just to mention it: I've tried to install Graylog https://hub.docker.com/layers/graylog/graylog/6.1.4/images/sha256-f41bcb74d64980076a498d4850a25dc42ede84e22c0012fa3dfa6ac43c860dce via the official docker image and also got an unusable frontend.
After downgrading to [6.0.9](https://hub.docker.com/layers/graylog/graylog/6.0.9/images/sha256-c5b35a90ec1f35f45de2513fdbc6e9a97abb9915fe4360b5afbbf40de372df70) with the same config - it works like a charm.
