### ISSUE TITLE
Journal usage not refreshing on node overview page

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#2083]
On the System -> Nodes page, the journal usage per node is not refreshing automatically. The node detail page is doing it properly.

**Comment by edmundoa** [comment]
It seems to be working for me:
![nodes](https://cloud.githubusercontent.com/assets/716185/14555292/f761a296-02f1-11e6-9905-cfa7458c13cf.gif)

Which browser are you using, and which Graylog version? Also please share any errors in your JS console :smile:

**Comment by dennisoelkers** [comment]
I also tried to reproduce it - unsuccessfully :/

**Comment by lennartkoopmann** [comment]
The "unprocessed messages" number is not updating for me on the latest Chrome. Try stop message processing and see if the number is changing or not.

**Comment by edmundoa** [comment]
Could reproduce that, looking into it :+1:

**Comment by lennartkoopmann** [comment]
Thank you, sir!
