### ISSUE TITLE
Dashboard widgets do not work until reload of page

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#2084]
If you have two tabs open:

* Search result page
* A dashboard

... and from the search result page you add a widget to the dashboard, then the widget appears on the dashboard immediately but never shows a value. The loading spinner runs forever. You have to reload the whole page for the widget to function properly.

**Comment by edmundoa** [comment]
As a workaround, you can change the `updateUnfocussed` setting to `true` in your user preferences.
