### ISSUE TITLE
sort extractors no longer works in 2.0.0-4.beta.3

### ISSUE THREAD

**Issue by jhaar** [Graylog2/graylog2-server#2086]
### Problem description

I had just discovered the sort extractor feature yesterday and was very happy to see it. However, I upgraded to .3 today and now I discover that when I try to re-order my syslog extractors (about 12 of them), I drag one down the list and it pops back up to where it was before.

One other thing. I *think* when you add a new extractor it shows up at the bottom? Well this one I just added showed up 2nd in the list - and I can't change the order. So I don't know if that indicates a separate/different problem

### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version: graylog-server-2.0.0-4.beta.3.noarch
* Elasticsearch Version: 
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by edmundoa** [comment]
Hi @jhaar,

I have been trying to reproduce the issue on the latest Firefox and Chrome, and it works fine for me. Could you provide some information about your browser/OS, and any error messages that may appear in your browser's developer tools?

Please also be aware that you need to drop the item inside the modal, specially if you are fast with the mouse :)

Thank you!

**Comment by edmundoa** [comment]
I think I managed to reproduce this. In my case, when I sort the extractors they keep the position, but if I wait a few seconds without saving, they reset to the original order. Is that the behaviour you are seeing @jhaar?

**Comment by edmundoa** [comment]
There was indeed a bug in there that was resetting the extractor sort while editing it. I have made a PR to fix it.

Thank you for reporting this issue!

**Comment by mrfreezer** [comment]
there is even more i think.

i witnessed them moving around in - for me - totally random order from second to second.
almost like the sort order changes depending on which extractor was used last.
