### ISSUE TITLE
Graylog v 2.0.x violates GELF spec 1.1

### ISSUE THREAD

**Issue by vladimirfx** [Graylog2/graylog2-server#2087]
Since v 2.0 message fields can't contains dots. But GELF 1.1 directly claims that dot is valid field name character:

http://docs.graylog.org/en/latest/pages/gelf.html

Quote about additional fields: 

>  Allowed characters in field names are any word character (letter, number, underscore), dashes and dots.

As now we have many use cases where additional field contains dots. There is whole class of systems that works on Java and use NDC logging with dot delimited fields. All this fields is simple stripped. Moreover there is no way to "map" this field on Graylog side because of filtering performed in very core part of system - on input plugin, before any extractor or somthing else is called. It seems a very big regression for v 2.0.

Motivation for this regression is strange - main **back-end** storage is dropped support for dots in field names. Graylog is thin wrapper around ES or powerfull production ready log manager? 
OK, Graylog devs do not want  to deal with support of dots on top of ES. 
But GELF can be supported. Or else is just a fiction that can easily be dropped in favor of ES restriction.

I see two main way to fix this issue:
1. Keep support dots in core model of Graylog and perform transparent conversion for ES output in lossless way.
2. Perform configurable conversion on GELF input in way similar to de_dot filter in Logstash.

First way is preferable but complex because conversion should be performed for all search calls in addition to store calls. But for that complexity users get best user experience.

Second way is by far simpler - it only one additional config ops and 5-10 lines of code in GelfCodec. But that conversion usually is data loss. It's add requirement to users to "map" application provided field to search messages in Graylog.

### Environment

* Graylog Version: 2.0-beta2
* Elasticsearch Version: 2.3.1
* MongoDB Version: 3.2
* Operating System: Ubuntu 16.04

**Comment by joschi** [comment]
@vladimirfx Thanks for reporting this! The issue has been resolved and the fix will be included in the next release.

Refs #2078
