### ISSUE TITLE
All pages fail to open with reverse proxy on subdirectory on 6.1.2

### ISSUE THREAD

**Issue by ottorei** [Graylog2/graylog2-server#20899]
## Problem ##
Opening any pages on 6.1.2-1 with reverse proxy fails on the browser. Tested with Firefox, Chrome and Edge. Using direct URL or using nginx without URL prefix seems to work. The same configuration worked fine on 6.0.7 version.

There is an nginx-proxy behind the server which does SSO and forwards all requests destined to /graylog to the server software. This is the relevant part of the configuration:

```
location /graylog/ {
		proxy_set_header Remote-User "";
		auth_request /auth_request/graylog/;
                auth_request_set $auth_remote_user $upstream_http_remote_user;
		proxy_set_header   Host                  $host;
		proxy_set_header   X-Real-IP             $remote_addr;
		proxy_set_header   X-Forwarded-For       $proxy_add_x_forwarded_for;
		proxy_set_header   X-Forwarded-Host      $host;
		proxy_set_header   X-Forwarded-Server    $host;
		proxy_set_header   Remote-User           $auth_remote_user;
		proxy_set_header   X-Graylog-Server-URL  https://company.com/graylog/;
		proxy_pass         http://192.168.10.10:9000/;
}
```

## Expected Behavior
Pages should open without issues. Also, what is that telemetry function anyway? Shouldnt the telemetry be completely disabled with `telemetry_enabled = false`?

## Current Behavior
The browser gives an error message:
![Image](https://github.com/user-attachments/assets/b5e27910-69b0-4516-a8b8-4382de782a06)

On `/var/log/graylog-server/server.log` there is nothing showing on when the error happens.

## Possible Solution
An option to disable generating the telemetry JavaScript to the client or fix the function which breaks, 

## Steps to Reproduce (for bugs)
1. Install 6.1.2-1 and put it behind a reverse proxy in a similar way than in my example configuration.
2. SSO-login a user with the reverse proxy
3. Try to open any dashboards

## Your Environment
* Graylog Version: 6.1.2-1
* Java Version: openjdk-17-jre-headless
* OpenSearch Version: 2.15.0
* MongoDB Version: 7.0.15
* Operating System: Ubuntu 22.04
* Browser version: Edge 130.0.2849.68

**Comment by Littlericket** [comment]
@ottorei AFAIR `telemetry_enabled` has been renamed in previous 2 major versions (I found it somewhere on the graylog forums, but can't find it anymore). My best guess is that it can't be disabled globally anymore.

The telemetry settings moved to the profile settings (stored in mongodb) and is user-specific and enabled by default: https://github.com/Graylog2/graylog2-server/issues/14900#issuecomment-1658323176 

There is an dense documentation level about telemetry. But somehow this error relates to telemetry even if it should be disabled. 
Great that this catches attention. ;)
