### ISSUE TITLE
Regex search for uuid's fails

### ISSUE THREAD

**Issue by avongluck-r1soft** [Graylog2/graylog2-server#2091]
We're seeing a strange issue where searching for a uuid  causes graylog regex searches to fail.

The example is searching our logs for uuid's:

message:/([a-z0-9]{8})\-([a-z0-9]{4}\-){3}([a-z0-9]{12})/

message:/([a-z0-9]{8})\-([a-z0-9]{4}\-){3}([a-z0-9]{12})/g

adding a 'g' onto the end of the query seems to improve the results... although i'm not sure it is matching correctly... also adding a g shouldn't make the results go from 0 matches to tons of matches. (g should match multiple times in a single line I assume and not stop after the first match)

**Comment by joschi** [comment]
@avongluck-r1soft Please provide some example messages.

**Comment by joschi** [comment]
Closing issue because the original author didn't reply.
