### ISSUE TITLE
Unknown condition cause new event definition workflow to fail executing search

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#20925]
@mcdowellster first reported he encountered a strange bug where creating an event definition, Filter & Aggregation, the search always fails. I can replicate this in both sandbox.graylog.cloud and demo.graylog.cloud.

I cannot replicate this myself and suspect it has something to do with MongoDB replicasets.

See video:
https://github.com/user-attachments/assets/014e7f33-cf42-4a17-b520-2ca8ecf681a1

XHR requests:

POST `/api/views/search/672e8980078d854e21b15434/execute` (HTTP 201 Created)

GET `/api/views/search/status/672e89805842237c9efb2434` (HTTP 200 OK)
(for some reason a second subsequent...)

GET `/api/views/search/status/672e89805842237c9efb2434` (HTTP 404 Not Found)

```json
{"type":"ApiError","message":"HTTP 404 Not Found"}
```

## Expected Behavior

When creating an event, the search should work

## Current Behavior

Search for creating an event does not work (see video)

## Steps to Reproduce (for bugs)

1. Go to Alerts
2. Click on Event Definitions "tab"(??)
3. Create event definition
4. Go to condition "tab"(??)
5. Change condition type to "Filter & Aggregation"
6. Observe error

## Your Environment

* Graylog Version: 6.1.1, 6.1.2
* Java Version: Bundled
* OpenSearch Version: N/A
* MongoDB Version: 5.0.28, 6.0.19 (whatever graylog cloud uses)

**Comment by kmerz** [comment]
Are there any entries in the logs for that?

**Comment by mcdowellster** [comment]
Sadly no. Nothing is appearing in the graylog server.log.

Happy to do a zoom session and demonstrate

**Comment by drewmiranda-gl** [comment]
Seems the same as https://github.com/Graylog2/graylog2-server/issues/20474 ?

**Comment by damianharouff** [comment]
> Seems the same as [#20474](https://github.com/Graylog2/graylog2-server/issues/20474) ?

Further to this: at the time I opened #20474 I was running a multi-node Graylog/MongoDB/Opensearch cluster. 

I've since rebuilt into an AIO install, and can confirm that #20474 _**no longer**_ happens in my environment.

**Comment by mcdowellster** [comment]
I can confirm this is affecting live customer environments too. On a call with a customer right now, I cannot setup a new event at all.

**Comment by luk-kaminski** [comment]
In the video from @damianharouff I can see a 404 response code for `...search\status...` endpoint. 
Looks like in multi-node environment ProxiedResource fails to reach proper GL node to retrieve async search status.

**Comment by luk-kaminski** [comment]
Similar issue : https://github.com/Graylog2/graylog2-server/issues/20922
It was declared to be a k8s misconfiguration on the client side.

**Comment by luk-kaminski** [comment]
@drewmiranda-gl - Does it sometimes happen with regular search, on the search page, as well? (in a way it happened with https://github.com/Graylog2/graylog2-server/issues/20922)

**Comment by damianharouff** [comment]
Keeping everything together here in the issue: for me it did not happen with regular search ; it only seems to happen in Event Defintion -> Filter & Aggregation’s second page. I haven’t noted any issues with regular search.

**Comment by mcdowellster** [comment]
I can confirm the same behavior as Drew. Regular search is normal. Only the filter and aggregation search in events appears affected.

**Comment by mcdowellster** [comment]
Was there a change in this process for 6.1? This has been fine for years on my cluster until I upgraded to 6.1

**Comment by grownuphacker** [comment]
Just to clarify the workaround as I understand it - so its not specific to Nginx: 

- Configure Load Balancer / ADC in front of Graylog to use a balancing algorithm other than Round Robin or Least Connections (recommended IP Source based distribution) so that there is a significantly more stable client to node session relationship.  

This reduces the risk to the node going down during the event calculation.
