### ISSUE TITLE
SearchJobs API returns 404 sometimes in cluster rendering dashboard unusable on 6.1.x

### ISSUE THREAD

**Issue by der-eismann** [Graylog2/graylog2-server#20922]
Hey everyone, today we upgraded our system from Graylog 6.0.6 to 6.1.2. Since then the `Search` dashboard won't load most of the time:

![Image](https://github.com/user-attachments/assets/d70b16fb-5eaa-4dfd-b80f-70faeb25113e)

After opening the developer console we can see that requests to the `SearchJobs` API randomly fail from time to time. After some more investigation it seems to always fail when you send a `SearchJobs` request for node `abc` to node `xyz` which will inevitably happen on a Kubernetes cluster or behind any other load balancer. Imagine something like this (metacode, not actual URLs):
```
https://node-abc.cluster.local/api/views/searchjobs/node-abc/672e1f6653e13229b010b3d2/status
=> works
https://node-abc.cluster.local/api/views/searchjobs/node-xyz/672e1f6653e13229b010b3d2/status
=> doesn't work
```

Maybe our values for `GRAYLOG_HTTP_PUBLISH_URI` and `GRAYLOG_HTTP_EXTERNAL_URI` are incorrect? But they worked without any issues until today. We have these:
```
            - name: GRAYLOG_HTTP_EXTERNAL_URI
              value: https://graylog.example.com/ [main ingress]
            - name: GRAYLOG_HTTP_PUBLISH_URI
              value: http://graylog.default.svc.cluster.local:9000/ [kubernetes service]
```

## Expected Behavior
The Search dashboard should keep working as before since there were no related breaking changes in the upgrade guide.

## Current Behavior
The Search dashboard doesn't load most of the time, rendering Graylog unusable.

## Possible Solution
The API should always return a response, regardless which node it is sent to.

## Steps to Reproduce (for bugs)
1. Have a Graylog 6.1.x cluster with 3 nodes behind a load balancer
2. Search dashboard won't work most of the time

## Context
We can't use Graylog at the moment, we were just trying to upgrade

## Your Environment

* Graylog Version: 6.1.2
* Java Version: Bundled Eclipse Adoptium 17.0.13
* OpenSearch Version: 2.15.0
* MongoDB Version: 5.0.25
* Operating System: Official container `graylog/graylog:6.1.2` from Docker Hub
* Browser version: Chrome 130.0.6723.116

**Comment by drewmiranda-gl** [comment]
Do you know if you are using any sort of persistence or stickiness with your load balancer? If not are you able to configure it?

**Comment by der-eismann** [comment]
We are not using stickiness at the moment since it's not necessary, but Traefik should be able to handle this. Will check next week.
Is there a reason why such a breaking change was made without mentioning it? Or were you not aware of that issue? Looks like this was necessary in the past already (https://github.com/graylog-labs/graylog2-web-interface/issues/1435) but atm there is nothing mentioned about sticky sessions in [the docs](https://go2docs.graylog.org/current/setting_up_graylog/web_interface.htm?Highlight=proxy#MakingtheWebInterfaceWorkwithLoadBalancersProxies).

**Comment by der-eismann** [comment]
So it seems what I mentioned was not the root cause of the issue. Even when restricting the web ingress to a single node or activating sticky sessions we get 404s on the SearchJobs API and therefore timeouts on the `Search` dashboard. Also when I'm sending the API requests to the specified node manually I sometimes get 404s, unfortunately there are no logs regarding this although we activated `INFO` level already.
We are out of ideas here, maybe trying to downgrade and never touching it again is the best solution.

**Comment by der-eismann** [comment]
Okay, it seems like it was a configuration issue from our side. A colleague suggested changing the `http_publish_uri` from the k8s service address to the individual pod IPs and now it looks like the issue is solved. From the docs it is now clear that this was the cause, although it somehow worked for at least 5 years this way. This is what we changed in the k8s manifest:
```diff
-        - name: GRAYLOG_HTTP_PUBLISH_URI
-          value: http://graylog.default.svc.cluster.local:9000/
+        - name: POD_IP
+          valueFrom:
+            fieldRef:
+              fieldPath: status.podIP
+        - name: GRAYLOG_HTTP_PUBLISH_URI
+          value: http://$(POD_IP):9000/
```
