### ISSUE TITLE
ldap authentication not working with somewhat creative configuration

### ISSUE THREAD

**Issue by mrfreezer** [Graylog2/graylog2-server#2094]
### Problem description

under a certain circumstance ldap authentication does not work.

but first things first:

we got several machines with a /28 ip-range at a hoster plus an internal lab-network with a static ip (dns name: "internal") and several machines behind it. plus the usual office network which is completely separated from the lab net.

at the hoster there are several webservers, loadbalancers and other stuff.
the graylog server is inside the lab net to keep it physically separated from the machines we are logging, e.g. in case we need the logs for forensics after a break in.

inside the lab net there is also a server running an application collecting metering data therefore port 443 on the public ip is occupied and i can not chance this.

to solve this and make the graylog server available from the office network (and the outside world) we just had a vhost ("graylog") on the loadbalancer at the hoster reverse proxying the graylog server inside the lab net via vpn.

graylog:443 -----(vpn)---->  labmachine:443 

that was with 1.3.4 and earlier. ldap worked fine.

now i am implementing 2.0 beta which among many other brilliant features also changed the way the webinterface works - completely i would say.

we also  need to expose the rest-interface (port 12900) since almost everything happens inside the clients webbrowser now instead of the webinterface-application. not that much of a problem. i installed key, cert and enabled tls, opened up the port and adjusted the _rest_transport_uri_ parameter inside the config to reflect the lab networks public ip plus port. https://internal:12900

worked. graylog itself got served over https://graylog and then accessed the rest interface at https://internal:12900 - to bad we can not access most ports from inside the office lan via https - due to security concerns. ok, lets just try 8443 instead of 12900 - so i changed the portmapping from 12900->12900 to 8443->12900 (without changing the actual port on the graylog server, admins are lazy pigs, we all know it ^^) and also adjusted the _rest_transport_uri_ to https://internal:8443

now it works fine even from the office network. next step is configuring ldap. all is fine, connection check green, even reading the login test works and the groups are being extracted from ldap as well and show up on the group mapping page.

but logging in from the webinterface does not work as soon as you use an ldap account (local users work just fine) and looking into the logs doesnt reveal anything and by this i mean: no log entries when i try to log in with an ldap account. local accounts on the other hand produce a massive amount of loglines (as i set the log level to debug earlier).

inside chromes debugger is saw the following:

internal:8443/system/sessions:1 
POST https://internal:8443/system/sessions 401 (Unauthorized)
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.6a9dfb5….js:13385 
There was an error fetching a resource: cannot POST https://internal:8443/system/sessions (401). 

so i set up a port forwarding on the loadbalancer for port 12900 to the lab network and adjusted _rest_transport_uri_ to https://graylog:12900 because at first i suspected the different IPs of graylog and internal being the problem and it worked.

so now we have:

graylog:443 -----(vpn)---->  labmachine:443 
graylog:12900 -----(vpn)---->  labmachine:12900

and ldap works.

but while writing this i did another check and reverted the port mapping on the labs ip to 12900 and changed _rest_transport_uri_ again, this time to https://internal:12900 which works as well.

what i am going to do now, after i submitted this, is that i will change the whole rest-interface-config including the port forwarding on the lab ip to 8443 and see if it breaks again or if it still works.

i will post the results as soon as i am done with it.

### Environment

* Graylog Version: 2.0.0-beta.3
* Elasticsearch Version: 2.3.1
* MongoDB Version: 2.4
* Operating System: ubuntu 14.04
* Browser version: does not matter

**Comment by mrfreezer** [comment]
ok, i changed the portforwarding, _rest_transport_uri_ to https://internal:8443 als well als the _rest_listen_uri_ to http://<ip>:8443 and ldap works.

seems like is something confused when the transport uri port and the listen uri port differ from each other.

**Comment by mrfreezer** [comment]
moin kay,

does this need any input from ME? or is that an internal thing?

**Comment by joschi** [comment]
@mrfreezer To be honest, I have no idea what problem you're describing. Maybe you could add an "Executive Summary" of your problem to this thread?

**Comment by mrfreezer** [comment]
to put if very, very brief: if you are using port mapping on your router and the input port (on the public ip) is different from the rest.interfaces port on the graylog-machines private ip then ldap does not work.

1.2.3.4:8443 -> 10.0.0.1:8443 works
1.2.3.4:12900 -> 10.0.0.1:12900 works
1.2.3.4:8433 -> 10.0.0.1:12900  does not work

as plain and simple as this.

**Comment by mikkolehtisalo** [comment]
CORS?

**Comment by jalogisch** [comment]
@mrfreezer can you please describe a setting where you are going to use different ports for _rest_transport_uri_ and _rest_listen_uri_.

for me this looks like a very exotic edge case that might need some coverage in the documentation. 

please open a case in the documentation repo https://github.com/Graylog2/documentation/issues or submit some pr that describe the edge case you are faced.

i will close this case - if you feel that this is more than a documentation case please reopen.
