### ISSUE TITLE
Requesting to support newer version of opensearch (since opensearch community patch nodejs by releasing new version)

### ISSUE THREAD

**Issue by nurfarzaana** [Graylog2/graylog2-server#20991]
Requesting to support newer version of opensearch (since opensearch community patch nodejs by releasing new version)

**Comment by dennisoelkers** [comment]
Hey @nurfarzaana,

can you elaborate a bit? What version of Opensearch should be supported? How is this related to node.js?

**Comment by nurfarzaana** [comment]
> Hey [@nurfarzaana](https://github.com/nurfarzaana),
> 
> can you elaborate a bit? What version of Opensearch should be supported? How is this related to node.js?

Hi @dennisoelkers 

to support  version 2.17
for nodejs, it use in opensearch-dashboard. if we upgrade opensearch-dashboard, we should upgrade opensearch as well

**Comment by hydrapolic** [comment]
Graylog 6.0/6.1 seems to work fine for me with opensearch 2.18.0.
