### ISSUE TITLE
AD/LDAP Settings will not save

### ISSUE THREAD

**Issue by dramones-his** [Graylog2/graylog2-server#2099]
### Problem description

Using Active directory  I go through the setup in graylog users and configure the mapping, everything tests good. I go configure LDAP group mappings and it says no LDAP connections configured. 

I go back to the screen where I configured the mapping and nothing is in the fields. 
### Environment

3 Node cluster running all services

Vmware appliance ver. 1.3.4-1

**Comment by joschi** [comment]
@dramones-his Please check and ensure that all 3 nodes use the exact same `password_secret` in their configuration files.

**Comment by dramones-his** [comment]
I've changed the config file to have all of the same `password_secret`

**Comment by dramones-his** [comment]
Attempting to login with AD credentials is inconsistent, sometimes it will let you login, other times it will not.

**Comment by compuvin** [comment]
I am experiencing this too. All the tests work on the page but it will not save.

**Comment by kroepke** [comment]
There was a masked exception before 2.0, please try again with the current 2.0 release to gain more information about the source of the problem.

Thanks!

**Comment by compuvin** [comment]
Kroepke, I started having the issue when I upgraded to 2.0. Here is the current version that I am on (which I believe is the latest):
Graylog 2.0.0 (2dc6c03) on MO-Syslog (Oracle Corporation 1.8.0_91 on Linux 3.13.0-85-generic)

**Comment by edmundoa** [comment]
@compuvin Would you be so kind as to share with us any errors in your browser's developer console and/or Graylog logs? Thank you!

**Comment by compuvin** [comment]
@edmundoa I've attached the log files that you requested. I think I might have discovered the problem though. Here is an entry from the log:

**Graylog does not yet support multiple LDAP backends, but 14 configurations were found. This is a bug, ignoring LDAP config.**

Not sure how to fix this but it appears that it is saving my settings every time I try even though the web interface reverts back to default settings on the LDAP screen.

[Graylog-Logfiles.zip](https://github.com/Graylog2/graylog2-server/files/257342/Graylog-Logfiles.zip)

**Comment by joschi** [comment]
@compuvin As a workaround for now, you can simply delete the `ldap_settings` collection in MongoDB and reconfigure LDAP in the web interface.

* https://docs.mongodb.com/manual/mongo/
* https://docs.mongodb.com/v3.2/reference/method/db.collection.drop/

**Comment by compuvin** [comment]
@joschi That worked perfectly! Thanks for the help.

**Comment by Thomas-1985** [comment]
Hi

I had the same problem with 2.0 and the solution worked. Thanks a lot!!!

**Comment by stdevops** [comment]
ldap_settings does not exists for me any other suggestions?

**Comment by joschi** [comment]
@stdevops If the `ldap_settings` collection in MongoDB doesn't exist, you haven't ever (successfully) saved LDAP settings in the web interface.

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by simonpie** [comment]
I just got the same error with Graylog 2.3.1+9f2c6ef.

**Comment by razumzhiro** [comment]
No issue adding LDAP in instances with single Graylog-Server node, problems appear with multiple Graylog Server frontends.

**Comment by sudovinh** [comment]
Was there a fix for this? I am also having this same issue. I deleted ldap_settings collection and re-added the settings in the web ui. And still does not pull the ldap settings after mongorestore.

**Comment by juliohm1978** [comment]
Still seeing the same error with graylog:3.0.1-1 just after an upgrade.

Dropping the config from mongodb is a workaround, but it's farily annoying. For the record...

Access your primary mongodb instance and login as admin

```
mongo -u admin
## pwd prompt
```

In the mongodb shell, run:

```
use graylog
db.ldap_settings.drop()
```

You might see errors if you are running multiple replicas of mongodb and you are not using the master. This must be done in the primary replica.

**Comment by bernd** [comment]
This should no longer be an issue with 4.0. Please open a new issue if you still see this problem in 4.0 and later. Thank you!
