### ISSUE TITLE
Sorting on additional events attributes

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#21029]
Events should be sortable on additional attributes, which do not allow sorting yet:

On regular events page:

- Description
- Event Definition
- Aggregation Time Range?

On security events page:

- Description
- Type

**Comment by dennisoelkers** [comment]
Sorting based on `Event Definition` is most probably not possible with pagination. The event definition of an event is stored in MongoDB, while the event itself is stored in OpenSearch. We would need to join the two, which does not work with pagination.

**Comment by dennisoelkers** [comment]
Sorting based on `Description` is not possible out of the box, because the `message` field is `text` and not `keyword` by default (this means it is optimized for full text search instead of sorting/aggregating). We could enable `fielddata` on it, but that would increase memory usage significantly.

**Comment by coffee-squirrel** [comment]
Related: #17437

**Comment by dennisoelkers** [comment]
@Emy-01: I am not sure I get the questions correctly. We always need to some kind of pagination, because we don't know how many events we will get back. Under any circumstance we can assume that there will be more than 25/50/100 events in the system, so optimizing for the corner case that there is only a single page of events in order to be able to sort in-memory based on the event definition title does not appear to useful here.
Also, what do you mean with asynchronous job? We are not doing anything asynchronous here when fetching events.
