### ISSUE TITLE
Research doesn't work | lastest Graylog 2.0.0-4.beta.3

### ISSUE THREAD

**Issue by Infolegale** [Graylog2/graylog2-server#2102]
### Problem description
i just come to install graylog 2.0.0-4.beta.3, before i was in 1.3, so i updated all my system and all seemed to work until i try to send data in graylog.
Research doesn't work and i have these errors:

WARN  [SearchResource] Unable to execute search: all shards failed

WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input GELFTCPInput{title=sphinx, type=org.graylog2.inputs.gelf.tcp.GELFTCPInput, nodeId=null} should be 1048576 but is 212992

WARN  [NettyTransport] receiveBufferSize (SO_RCVBUF) for input SyslogTCPInput{title=apache_syslog_combined, type=org.graylog2.inputs.syslog.tcp.SyslogTCPInput, nodeId=null} should be 1048576 but is 212992.

WARN  [SyslogCodec] Syslog message is missing date or date could not be parsed. (Possibly set allow_override_date to true) Not further handling. Message was: õ�^N        !>�(^\^G��[M_�^@^@^L�^S�^T^@/^@5^@

For the last error, allow_override_date is already set to true for syslog inputs.

### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version: 2.0.0-4.beta.3
* Elasticsearch Version: 2.2.0
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@Infolegale Please provide the full and unabbreviated Graylog server logs. Additionally, the "syslog" message in the error message doesn't look like syslog at all.

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
