### ISSUE TITLE
Admin user can not edit password

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-server#2103]
### Problem description

Admin user is not able to edit his password

![bildschirmfoto 2016-04-18 um 17 44 27](https://cloud.githubusercontent.com/assets/6331205/14610381/02a50ac8-058e-11e6-9561-e0d78a5c563e.png)

This is what I have in the web console

`FetchError() FetchProvider.js:54
json/this.request<() FetchProvider.js:122
tryCatcher() bluebird.js:4589
[23]</module.exports/Promise.prototype._settlePromiseFromHandler() bluebird.js:2695
[23]</module.exports/Promise.prototype._settlePromiseAt() bluebird.js:2769
[23]</module.exports/Promise.prototype._settlePromises() bluebird.js:2885
[2]</Async.prototype._drainQueue() bluebird.js:175
[2]</Async.prototype._drainQueues() bluebird.js:185
Async/this.drainQueues()`

### Steps to reproduce the problem

1. Create new user with Admin role
2. Login with that account 
3. Go to edit profile and change password
4. You receive the error message above

### Environment

* Graylog Version: Graylog 2.0.0-beta.4-SNAPSHOT 
* Browser version: Happens in Firefox 45.0.2 and Chrome 49

**Comment by edmundoa** [comment]
I see two problems here:

- We don't display an old password input in the form, that it is required by the server when updating the user's own password
- The server returns a 403 if the old password is missing or invalid, which triggers a redirect in the front-end. This is really annoying from the user perspective, and it's not entirely following what the API endpoint documentation says
