### ISSUE TITLE
can no longer edit some dashboard widgets

### ISSUE THREAD

**Issue by jhaar** [Graylog2/graylog2-server#2107]
### Problem description

Under graylog-v2.0.0-4.beta.3 I have several dashboards. Some work fine, but under one of them if I click the "Unlock/Edit" button, only 2 of the 8 widgets become editable - the others retain their "play" and "info" buttons. The ones that appear editable also do not respond to being clicked on, so they really aren't editable either. 

Once this event happens, I also lose the ability to move off that section. eg clicking on "Search", "Streams", etc doesn't do anything: the URL bar changes to show "/search" - but doesn't actually go there. Simply going into the URL bar and hitting ENTER still works. Once off that "broken" dashboard page, everything works fine again

To reiterate - this works on other dashboards. I also tried on two browsers and it affects both the same way

Firefox console reports the following when I try to click on the Edit button

TypeError: n is null
TypeError: z[e] is undefined

### Steps to reproduce the problem

1. enter dashboard
2. click "Unlock"
3. basically nothing happens

### Environment

* Graylog Version: graylog-v2.0.0-4.beta.3
* Elasticsearch Version: 2.3.1
* MongoDB Version: 2.6.11
* Operating System: CentOS-7
* Browser version: Firefox/45 and Chrome/50

**Comment by edmundoa** [comment]
Hi,

Unfortunately the web interface may get into that error state sometimes. Reloading the page should bring it to a sane state again.

As you said, this issue really depends on the dashboard. I was trying to reproduce it with some dashboards I have, but I couldn't.

Would you be so kind as to share the dashboard with us, so we can try and fix the issue? You can share the MongoDB dashboard object or the result of calling to `/dashboards/<dashboard_id>` in the REST API. In case you don't want to share it here, you can also send it to edmundo@graylog.com.

**Comment by edmundoa** [comment]
@jhaar any news on this? :)

**Comment by dennisoelkers** [comment]
Closing this for now, as discussion has stalled. Please reopen if there is new information.
