### ISSUE TITLE
AlarmCallback does not allow clearing of optional fields with default-value

### ISSUE THREAD

**Issue by magicdude4eva** [Graylog2/graylog2-server#2108]
### Problem description

I noticed this on Graylog v1 and Graylog v2 (2.0.0-beta.3). I am not able to delete the value of an optional field which has a default value.

In the example below the field "MYFIELD" will show the default value of "SOME_DEFAULT_VALUE" when editing the plugin properties. If I delete the value in the web-UI, the config-field will take the default-value of the field.

```
  public ConfigurationRequest getRequestedConfiguration () {
      final ConfigurationRequest configurationRequest = new ConfigurationRequest();
      
      configurationRequest.addField (new TextField (
          "MYFIELD", "MYFIELDLABEL", "SOME_DEFAULT_VALUE", "DESCRIPTION",
          ConfigurationField.Optional.OPTIONAL));
      
      
      return configurationRequest;
  }
```

How can I provide my AlarmCallback with a default-value during configuration, but then also allow the user to delete that value. The only way to make this work at the moment is to ask the user to enter some string which I then identify in the plugin as an empty value (in this case "null"):

```
    String myField = getConfigValue (configuration.getString("MYFIELD"));

    private final String getConfigValue(String x) {
        // Dirty work-around to allow empty content on optional fields with default value
        // We return NULL if the field-value is empty or the user has entered "null"
        return (isNullOrEmpty(x) || x.equals("null") ? null : x);
    }

```

### Steps to reproduce the problem

1. Write a AlarmCallback plugin with an optional field and a default value
2. Edit the callback-plugin and then try to delete the pre-populated default value
3. Save
4. Notice how the default value has overwritten the deleted string

### Environment

* Graylog Version: Graylog 2.0.0-beta.3 (1d03037)

**Comment by edmundoa** [comment]
Hi,

Thank you for reporting this!

It looks like there is a bug in the web interface and it's sending the old value to the server. We will fix it for the next release.

**Comment by edmundoa** [comment]
Changes in #2114 actually create a different problem: default values are not send to the server unless they change. We are working on a fix for it.
