### ISSUE TITLE
Sending a test alert does not show AlarmCallbackException information

### ISSUE THREAD

**Issue by magicdude4eva** [Graylog2/graylog2-server#2109]
### Problem description

When an Alarmcallback plugin throws an exception during a "Send test alert", the web-interface does not display exception information specific to the plugin, but rather a generic message:

```
Sending dummy alert failed!
Unable to send dummy alert for stream »Stream name«: cannot POST http://IP:12900/streams/56fe3ffaf50b69149fb68c4a/alerts/sendDummyAlert (500)
```
### Steps to reproduce the problem
1. Write an Alarmcallback which throws an AlarmCallbackException
2. Send a test alert
3. Notice that the popup-notification does not display any exception information provided by the plugin
### Environment
- Graylog Version: Graylog 2.0.0-beta.3 (1d03037)

**Comment by joschi** [comment]
This has been fixed in Graylog 2.2.0.

<img width="1421" alt="Email Alert Callback test error" src="https://cloud.githubusercontent.com/assets/43951/21388380/574bbd14-c77c-11e6-9293-a6d06d5700c5.png">
