### ISSUE TITLE
Cannot export data from widget if widget name does NOT contain a space, Returns HTTP 404 error

### ISSUE THREAD

**Issue by drewmiranda-gl** [Graylog2/graylog2-server#21128]
When attempting to use the "download" or export button on a widget (for example from a dashboard), all file types fail except for PDF.

Example URL:

```
/api/views/search/pivot/export/Level_2024/-12/-04T14/:44/:57.406Z/-2024/-12/-05T14/:44/:57.406Z.csv
```

I cannot replicate this in a test cluster.

## Expected Behavior

Using the export function on a widget exports data

## Current Behavior

Using the export function on a widget returns HTTP 404

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 6.1.4
* Java Version: Bundled
* OpenSearch Version: 2.15.0
* MongoDB Version: 7.0.14
* Operating System: Ubuntu Server 22.04 LTS
* Browser version: Google Chrome Version 131.0.6778.86 (Official Build) (arm64)

Please let me know if there are any questions.

**Comment by dennisoelkers** [comment]
Hey @drewmiranda-gl!

What is the name of the widget you are trying to export?

**Comment by drewmiranda-gl** [comment]
Recreating the widget does appear to make the error go away and allow the proper export. Unclear why though.

**Comment by drewmiranda-gl** [comment]
Upon further testing, it appears that if i change the widget title to contain a space ` ` the widget export functions without error

**Comment by drewmiranda-gl** [comment]
This is what looks like is happening:

1. The URL sent to the browser for downloading the widget is generated by the frontend
    * Using [exportWidget](https://github.com/Graylog2/graylog-plugin-enterprise/blob/9e6b0c1dfb8c46c9d4425d173241f9cd47514e35/enterprise/src/web/search/ExportWidgetAction/util/WidgetExportUtils.ts#L43)
2. `exportWidget` [calls](https://github.com/Graylog2/graylog-plugin-enterprise/blob/9e6b0c1dfb8c46c9d4425d173241f9cd47514e35/enterprise/src/web/search/ExportWidgetAction/util/WidgetExportUtils.ts#L49C32-L49C38) [getUrl](https://github.com/Graylog2/graylog-plugin-enterprise/blob/9e6b0c1dfb8c46c9d4425d173241f9cd47514e35/enterprise/src/web/search/ExportWidgetAction/util/WidgetExportUtils.ts#L39)
3. `getUrl` [calls](https://github.com/Graylog2/graylog-plugin-enterprise/blob/9e6b0c1dfb8c46c9d4425d173241f9cd47514e35/enterprise/src/web/search/ExportWidgetAction/util/WidgetExportUtils.ts#L39) [qualifyUrl](https://github.com/Graylog2/graylog2-server/blob/be2931024a35fd475d9d999842741a0b29dcb3e2/graylog2-web-interface/src/util/URLUtils.ts#L37)
    * The parameter passed into `qualifyUrl` is `views/search/pivot/export/${escape(fileName)}`
4. [escape](https://github.com/Graylog2/graylog2-server/blob/be2931024a35fd475d9d999842741a0b29dcb3e2/graylog2-web-interface/src/views/logic/queries/QueryHelper.ts#L21) tests if the input contains a space
    * Space YES: returns `"${escapedTerm}"` (This condition works without issue)
    * Space NO: regex replace replaces escapes all occurrences of the following characters
        * `&& || : \ / + - ! ( ) { } [ ] ^ " ~ * ?`
        * For the purposes of the widget download file url, we start with something like
            * `Network Bytes by transport_2024-12-05T19:40:28.776Z-2024-12-05T19:45:28.776Z.csv`
            * Which is then has the above characters escaped leading to:
                * `Network Bytes by transport_2024\-12\-05T19\:40\:28.776Z\-2024\-12\-05T19\:45\:28.776Z.csv`
                    * Note the backslashes above
5. Once our input is "escaped", its [processed by](https://github.com/Graylog2/graylog-plugin-enterprise/blob/9e6b0c1dfb8c46c9d4425d173241f9cd47514e35/enterprise/src/web/search/ExportWidgetAction/util/WidgetExportUtils.ts#L39) [qualifyUrl](https://github.com/Graylog2/graylog2-server/blob/be2931024a35fd475d9d999842741a0b29dcb3e2/graylog2-web-interface/src/util/URLUtils.ts#L37)
    * This creates the [parsedUrl const](https://github.com/Graylog2/graylog2-server/blob/be2931024a35fd475d9d999842741a0b29dcb3e2/graylog2-web-interface/src/util/URLUtils.ts#L38) with what looks like [URI.js](https://github.com/Graylog2/graylog2-server/blob/be2931024a35fd475d9d999842741a0b29dcb3e2/graylog2-web-interface/package.json#L112)
6. The URI.js library Treats both backslash `\` and slash `/` as valid, but [replaces all instances of](https://github.com/medialize/URI.js/blob/46c8ac0c7e6997daad8ff6859784b39f8892fa97/src/URI.js#L557) `\` with `/`
7. The output is passed to the frontend for the browser to init the URL, which ends up something like
    * `Network Bytes by transport_2024/-12/-05T19/:40/:28.776Z/-2024/-12/-05T19/:45/:28.776Z.csv`
    * Because this adds erronous URI parts to the API it becomes an invalid URL since no API endpoint exists at that path

**Comment by dennisoelkers** [comment]
Thanks a lot for the extensive research making our lives really easy, @drewmiranda-gl! I prepared a fix for it, that will most probably make it into the next patch release (`6.1.5`).
