### ISSUE TITLE
Documentation on how to add new messages with drools

### ISSUE THREAD

**Issue by alpha-centauri** [Graylog2/graylog2-server#2115]
### Problem description

It would be helpful if you provided some information on how to insert new messages from within a rule into the drools engine in the docs.
By then, could someone complement my example? I am having a hard time finding this out on the basis of source code :-/

```
import org.graylog2.plugin.Message

rule "Issue new message"
	when
		message : Message( getField("type") == "drools_test" )
	then
		Message newMessage = new Message("This is a new message", message.getSource(), message.getTimestamp());
		insert(newMessage); // how to insert a new fact?
end
```

### Environment

* Graylog Version: 1.3.4
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
> It would be helpful if you provided some information on how to insert new messages from within a rule into the drools engine in the docs.

The simple answer is that this is currently not possible.

The new message processing pipeline introduced in Graylog 2.0.0 will allow generating synthetic messages from within the filters.
