### ISSUE TITLE
Remove reader role possible but not advisible 

### ISSUE THREAD

**Issue by Bendolfc** [Graylog2/graylog2-server#2116]
I may be missing something on my install - 2.0 Beta 3, however the users / roles system isn't entirely intuitive as it is possible to remove the reader role from a user which in essence makes the user unable to do anything unless you have manually added the necessary permissions to a new role.

It would probably make more sense if it were not possible to remove the reader role from a user, or at the very least attempting to do so flagged up a warning.
### Steps to reproduce the problem
1. Create User
2. Remove reader role
3. Attempt to use a stream with new user.

**Comment by kroepke** [comment]
You are correct, this is a bug.
The previous version used Javascript to make sure at least "Reader" was selected.

We'll look at fixing this before the final version. Thanks for the report!
