### ISSUE TITLE
ElasticSearch multi fields not available in search/

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2117]
### Problem description
I have field defined in elastic template like:
```
"name":{
  "index" : "analyzed",
  "analyzer" : "standard",
  "type" : "string",
  "fields" : {
    "key" : {
      "type" : "string",
      "index" : "not_analyzed",
      "doc_values": true
    }
  }
}
```
On search page in list of fields only "name" available.
There is should be also field "name.key", because I want use it for QuickValues chart.

### Environment

* Graylog Version:2.0 beta3
* Elasticsearch Version:2.3.1

**Comment by joschi** [comment]
@hc4 Graylog currently only supports "flat" documents (i. e. no Elasticsearch [multi-fields](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/_multi_fields.html)).

We currently do not plan to support those.

**Comment by barzog** [comment]
Any new updates on this?
