### ISSUE TITLE
AD authentication login check: user check fails, unexpected character

### ISSUE THREAD

**Issue by joncojonathan** [Graylog2/graylog2-server#2121]
### Problem description

When configuring AD authentication and using the "login test" form the output reports "user check" fails ("login check" passes).

The output under the form states:
ERR_04196 Unexpected character ',' at position 49. Excpected start of attributeType descr.

Form is on the ldap configuration page: /system/ldap

Ths may relate to #2099 as LDAP group mapping (/system/ldap/groups) says "No LDAP/Active Directory groups found. Please verify that your LDAP group mapping settings are correct."
### Steps to reproduce the problem

_**Configure AD auth**_

**Server type:** Active directory
**LDAP Server address:** ldaps://adds-dc-01.company.local:636
**SSL:** yes
**Allow self signed certificates:** yes
**System Username:** svc_graylog@company.local
**System password:** _text string, no unusual characters other than !_

Test server connection passes

**Search Base DN:** ou=Users Accounts,ou=ICT,ou=Users,DC-company,dc=local
**User Search Pattern:** (&(objectClass=user)(sAMAccountName={0}))
**Display Name attribute:** displayName
**Group Search Base DN:** ou=App Groups,ou=Groups,DC-company,dc=local
**Group Search Pattern:** (&(objectClass=group)(cn=GraylogUsers))
**Group Name Attribute:** cn
**Default User Role:** Reader

Testing without the optional _group search_  yields the same behaviour via the _login test_ form.

_**Use login test form**_
**User:** jonathan
**Pass:** _secret_

Button _test login_ changes to say _login OK_ if a valid user is specified, even with an invalid password.  The error text is the same in both cases.
### Environment

System Hostname: graylog
Node ID: cd7f8768-de8f-4d88-a91a-b16f93a3fc8e
Version: 1.3.4 (0d67a80) (Hansa)
JVM:PID 1931, Oracle Corporation 1.8.0_66 on Linux 4.2.0-34-generic

graylog-web-interface v1.3.4 (0d67a80) (Oracle Corporation 1.8.0_66 / Linux 4.2.0-34-generic) on graylog
- Graylog Version: 1.3.4
- Elasticsearch Version: ??
- MongoDB Version: 1:2.4.9-1ubuntu2
- Operating System: Windows 10 (client)
  *\* Linux graylog 4.2.0-34-generic #39~14.04.1-Ubuntu SMP Fri Mar 11 11:38:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux (server)
- Browser version: Chrome 50.0.2661.75 m
- Active Directory running on Windows Server 2008r2
  *\* There is Exchange in the environment

**Comment by kroepke** [comment]
From a little bit of research it looks like our LDAP client does not like `,` characters in certain attributes, most likely this is in the CN in your case.
Typically this happens with a "Lastname, Firstname" kind of formatting.

I need to set up an environment to reproduce this first.

**Comment by kroepke** [comment]
Refer to http://social.technet.microsoft.com/wiki/contents/articles/5312.active-directory-characters-to-escape.aspx

**Comment by joncojonathan** [comment]
@kroepke - shouldn't this be labelled as a bug rather than an improvement?

**Comment by kroepke** [comment]
possibly, yes. For 2.1 we will most likely switch LDAP client libraries, though.

**Comment by bernd** [comment]
We properly escape characters in 4.0 now. Please open a new issue if you still see these problems with 4.0. Thank you!
