### ISSUE TITLE
CSV export contains not full data

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2126]
### Problem description
After exporting search result to CSV I've found some "holes" in data.
Interesting thing, is that in search result window all data displayed correctly.
To better illustrate problem i've created sample image from our soft:
![hole](https://cloud.githubusercontent.com/assets/17475270/14735074/79f57590-0877-11e6-888b-6a71b9c4a3e2.png)
The problem is in hole in the left part. In reality there is no such hole in data.
Also data in CSV seems to be unordered (but it is not a big problem for us)
If it matters, request is relative - last 5 minnutes and we have about 5K messages per minnute.

### Environment

* Graylog Version: 2.0 RC1
* Elasticsearch Version: 2.3.1
* Browser version: Yandex Browser 16.3.0.7843

**Comment by hc4** [comment]
Closer look to hole:
![hole2](https://cloud.githubusercontent.com/assets/17475270/14735366/31c3dbf2-0879-11e6-9bad-4c031d95351e.png)
You can see, that data lost by "chunks".

Also I've noticed, that this holes always appears on the left part of timeline.

**Comment by kroepke** [comment]
CSV export is done via a scroll query in elasticsearch, which will iterate over chunks of messages for each shard.
For performance reasons those chunks are not sorted, this might be possible with elasticsearch 2.3.1 but sorting could affect performance too much for now.

Can you estimate how many messages were omitted? Each scroll chunk is 500 messages, so if there are around 500 messages missing, that could indicate that one of them did not return.
Are you using the API directly or the UI?

To see the exact query Graylog is using to export the data, you can set the log level of `org.graylog2.indexer.searches.Searches` to `DEBUG`.

**Comment by hc4** [comment]
I use UI for CSV export.

Tested right now. Search result says "Found 17,397 messages", but in exported CSV only 16,924 messages (473 messages less, than expected).

**Comment by kroepke** [comment]
@hc4 this is indeed a bug, it'll be fixed in the next release

Many thanks for the good report (and I like that chart 👍 )
