### ISSUE TITLE
Output rate very low with graylog 2.0b3

### ISSUE THREAD

**Issue by tr31z** [Graylog2/graylog2-server#2127]
Hi,
I have a problem with my output rate which is very low. My input rate is not very high (200-400 msg/sec) but the output gets stuck at 100msg/sec max. As you can see in the following screenshot, the process and output buffers are at 100% and the journal is pretty full.
I have 2 graylog servers and never have experienced performance issues with graylog 1.x

![graylog](https://cloud.githubusercontent.com/assets/12542108/14742907/dee229e0-089e-11e6-9902-00040ff1b7d3.jpg)
In the logs I can see errors like the following
`ERROR [KafkaJournal] Read offset 91635221 before start of log at 91753414, starting to read from the beginning of the journal.`

### Steps to reproduce the problem
Upgrade of graylog1.3 with graylog2.0b3 

### Environment

* Graylog Version: 2.0b3 (the problem was the same with b2)
* Elasticsearch Version: 2.3
* MongoDB Version: 2.6.2
* Operating System: centos 7.2
* Browser version: Firefox 45

**Comment by joschi** [comment]
@tr31z We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Ideally include any additional information on your setup, e. g. hardware specs for the Graylog node(s) and Elasticsearch node(s), as well number and type of inputs and existing extractors or rules (with the message processing pipeline).

Thank you!
