### ISSUE TITLE
hubot-grafana feature request

### ISSUE THREAD

**Issue by on99** [Graylog2/graylog2-server#2129]
I am sorry that this issue is not following the format, it is a feature request.

I would like to send dashboard in graylog2 to my chatroom just like what [hubot-grafana](https://github.com/stephenyeargin/hubot-grafana) does.

The basic requirement is the server-side rendering ability. Then provide a secure api for external service to get the **rendered** dashboard.

**Comment by jalogisch** [comment]
we see the use-case for this, but this will not be implemented in the core of graylog. 

this should be made possible with a plugin.
