### ISSUE TITLE
Investigate performance impact of long key names in GELF messages

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#213]
Measure performance impact of key name lengths in GELF input.
Many applications send the same key names over and over, and in some applications the total length of the key string lengths exceeds the data size.

What happens to throughput and Heap/GC overhead when we support mapping field names to some fixed, interned set of names? This would be analogous to the currently existing Field Mappers but not only for values, but also for keys.

**Comment by bernd** [comment]
Closing this. Please re-open if this is still relevant. Thank you!
