### ISSUE TITLE
Web UI tries to connect to Internal IP

### ISSUE THREAD

**Issue by sjoerdmulder** [Graylog2/graylog2-server#2130]
### Problem description
Trying out version 2.0.0-rc.1; Running the graylog server inside a docker container but when trying to access the Web-UI through reverse proxy (terminates SSL etc) the browser tries to connect to an internal API endpoint. Showing: We are experiencing problems connecting to the Graylog server running on http://172.17.13.2:12900/. Please verify that the server is healthy and working correctly.

This wasn't the case in 1.3.4, there you could just navigate to the web ui endpoint that itself knew how to connect to the API (through internal proxy probally?) 

### Steps to reproduce the problem

1. Run graylog in a protected environment where not everything is on the same network and not all ports are available for the outside world but the web ui is.

### Environment

* Graylog Version: 2.0.0.rc1
* Elasticsearch Version: 2.3.1
* MongoDB Version: 3.0.11
* Operating System: Ubuntu / Docker
* Browser version: Chrome latest

**Comment by joschi** [comment]
@sjoerdmulder The Graylog web interface has been merged into the server component and is now served as a single-page application directly communicating with the Graylog REST API.

See http://docs.graylog.org/en/2.0/pages/configuring_webif.html for details on how to configure the web interface and usage scenarios with reverse proxies.

**Comment by sjoerdmulder** [comment]
My bad... didn't read the documentation: http://docs.graylog.org/en/latest/pages/configuring_webif.html#nginx

**Comment by sjoerdmulder** [comment]
@joschi Ok, have it working now with the reverse proxy but cannot login? 

```
Error - the server returned: 405 - cannot POST https://logs.example.org/api/system/sessions (405)
```

```
{"type":"ApiError","message":"HTTP 405 Method Not Allowed"}
```

**Comment by sjoerdmulder** [comment]
@joschi Sorry... this is my configuration mistake... consider the previous message not sent :)

**Comment by sjoerdmulder** [comment]
Last comment, opened pull-request for documentation change, was still a trailing slash missing causing the 405 and 404 errors: https://github.com/Graylog2/documentation/pull/70

**Comment by icyground** [comment]
Hi Sjoerd,
can you maybe share how you solved the "cannot POST" error? I'm running into the same issue when I'm follow the graylog doc for apache.

Thanks & Cheers!

**Comment by sjoerdmulder** [comment]
My problem was that i missed a slash and the backend service was actually not running. the cannot POST can mean anything.

**Comment by icyground** [comment]
Ok, thanks for the quick respone - I'll obviously have to investigate this further :)

**Comment by jlarocque88** [comment]
I know this is closed, but I am getting a similar issue when trying to connect the collector sidecar, through ELB and Nginx with web and api on one port config.

**Comment by joschi** [comment]
@jlarocque88 Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
