### ISSUE TITLE
RC.1 OVA API Browser button does not work

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#2131]
### Problem description

Using the 2.0 rc.1 ova, the System/Nodes page's api browser button does not work.
The URL is missing a `/` between port and path.

### Environment

* Graylog Version: 2.0.0-rc.1 beta OVA

**Comment by kroepke** [comment]
<img width="320" alt="screenshot" src="https://cloud.githubusercontent.com/assets/52014/14761691/7e2a9530-0969-11e6-8beb-e31f807baafc.png">

**Comment by kroepke** [comment]
Could be unrelated to the OVA, but I've not seen this using development builds.

**Comment by edmundoa** [comment]
It is unrelated to the OVA, we assume the transport address always have a slash at the end, which may not be true:

https://github.com/Graylog2/graylog2-server/blob/1d5b8e891ef1f9fa34749fa25acaa4bda4528d8d/graylog2-web-interface/src/components/nodes/NodesActions.jsx#L51

**Comment by dennisoelkers** [comment]
Actually we assume that it's _not_ ending with a slash in most other cases, so I would suggest we just add a slash here.

**Comment by joschi** [comment]
@edmundoa @dennisoelkers Didn't we include [URL.js](https://medialize.github.io/URI.js/) at one point which we could leverage to build a valid URL?
