### ISSUE TITLE
Improve Graylog alerting with elastalert from yelp

### ISSUE THREAD

**Issue by renapu** [Graylog2/graylog2-server#2134]
### Problem description
Alerting in Graylog is very limited by its functions, so maybe implement Elastalert as a framework for alerting in Graylog: https://github.com/Yelp/elastalert ?

This would be ah huge improvement for Graylog.

**Comment by joschi** [comment]
@renapu Improving the alerting functionality is on our roadmap for releases following Graylog 2.0.0.

For now, you can certainly use elastalert or Elastic Watcher (and really any other ES-based alerting utility) in addition to Graylog.
