### ISSUE TITLE
Add create/edit role page

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#2135]
### Problem description

In 2.0.0, we use the same page for creating, editing and listing roles, and this presents a couple of problems:
- Clicking the back button in your browser when creating or editing a role, will not take you to the role list as you would expect, but to the previous page
- It is not possible to share a link to a certain role edit page
### Steps to reproduce the problem
1. Visit the search page
2. Go to System -> Roles
3. Click on add new role
4. Press the back button in your browser
5. See that you are in the search page, instead of the role list
### Environment
- Graylog Version: 2.0.0

**Comment by bernd** [comment]
The roles management has been rewritten for the upcoming 4.0.0 release. This will not a problem anymore.
