### ISSUE TITLE
SSL endpoint with Graylog2-beta1

### ISSUE THREAD

**Issue by gallart** [Graylog2/graylog2-server#2137]
### Steps to reproduce the problem

1. Try to activate SSL/TLS on graylog2-beta1-rc1 installation

### Environment

* Graylog Version: 2-beta1-rc1
* Elasticsearch Version: 2.2.0
* MongoDB Version: 2.6.8
* Operating System: Gentoo Linux
* Browser version: Chrome latest

### Details

When trying to enable HTTPS with latest beta version of Graylog2, I can't find any working configuraiton.

1. rest TLS + web TLS : gives 401
2. Nginx reverse proxy : issues with CORS
3. Tried a mix of everything : no luck

What's the recommended configuration for https://graylog-instance ?

Thanks,

Gaëtan

**Comment by joschi** [comment]
@gallart Please take a look at the documentation for the Graylog 2.0.0 web interface: http://docs.graylog.org/en/2.0/pages/configuring_webif.html#ssl-setup

If the information in our documentation doesn't suffice to make a working setup, please post a comment to this issue or open a new issue in the https://github.com/Graylog2/documentation repository.

**Comment by gallart** [comment]
Hello Joschi,

Thanks for the documentation link. But when integrating the nginx proposed configuration (which, btw misses a ";" here) :

```
proxy_set_header    X-Graylog-Server-URL https://graylog.example.org/api
```

The /api/ ressources return 401 with login/popup.

<img width="511" alt="capture d ecran 2016-04-26 a 11 19 34" src="https://cloud.githubusercontent.com/assets/2728195/14813193/eaf6409a-0ba0-11e6-94a5-f0d6b730b4ce.png">

![image](https://cloud.githubusercontent.com/assets/2728195/14813206/f9c4caba-0ba0-11e6-864b-b9ab60eaf6bc.png)

Gaëtan

**Comment by gallart** [comment]
I should indicate that everything works when directly connecting to port :9000
