### ISSUE TITLE
Extractor improvments

### ISSUE THREAD

**Issue by kira8565** [Graylog2/graylog2-server#2140]
### Problem description

Hello, I use the Master version, I have a few feature suggestions
1. The Extractor can be disabled. （Because when I don't need an extractor, I have to delete it from the system）
2. When the extractor causes the service to error, can automatically stop the problem of the extractor
3. Now the alarm function is dispersed, whether there is a unified management and presentation of the page will be better
4. If the Extractor can be displayed on the input list, it will be easier to find and use.
### Environment
- Graylog Version: master
- Elasticsearch Version: 2.3.1
- MongoDB Version: 3.0.0 
- Operating System: Mac
- Browser version: Chorm48

**Comment by jalogisch** [comment]
extractors will be deprecated by pipelines.

thank you
