### ISSUE TITLE
bug when adding count to dashboard

### ISSUE THREAD

**Issue by Infolegale** [Graylog2/graylog2-server#2142]
### Problem description

When we want to add a count to a dashboard, the window to select which dashboard we want is cut; a part is out the window.
![bug_graylog](https://cloud.githubusercontent.com/assets/13556927/14810297/7c45ee6a-0b92-11e6-879a-02a52055a4cc.png)

### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version: 2.0.0-4.rc.1
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version: iceweasel 38.7.1esr-1~deb8u on debian8, firefox and chrome on windows

**Comment by dennisoelkers** [comment]
Thank you for reporting this! This has already been addressed and fixed and the fix will be included in the next version.
