### ISSUE TITLE
Allow scrolling in long dropdowns

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#2145]
### Problem description

Having a long list of dashboards may result in the list not being completely shown in some dropdowns in the search result page:

<img width="417" alt="screen shot 2016-04-26 at 12 12 45" src="https://cloud.githubusercontent.com/assets/716185/14814842/5e3833b8-0ba8-11e6-8e31-20c871709385.png">

As a general rule, we should avoid long dropdown lists, but in this case we should ensure that it is possible to scroll through them.
### Steps to reproduce the problem
1. Add tons of dashboards to your Graylog instance (i.e. import all content packs in the marketplace /cc: @bernd)
2. Go to the search result page and try to add a count to the last dashboard in the list
3. It's not possible to get to the dashboard
### Environment
- Graylog Version: 2.0.0

**Comment by bernd** [comment]
This specific issue with adding widgets to a dashboard is not an issue anymore with the new search page. And I _think_ we are mostly using drop down menus (select component) these days where scrolling works.
