### ISSUE TITLE
set-retention command not understood

### ISSUE THREAD

**Issue by esdraelon** [Graylog2/graylog2-server#2149]
### Steps to reproduce the problem

1. Download Rc-1 candidate from website
2. Perform a vanilla import
3. Follow installation steps in the 2.0 documentation
4. Make no changes to config other than:
sudo graylog-ctl set-retention --size=2 --indices=5

5. Output: "I don't know that command"

### Environment

* Graylog Version: 2.0 RC-1 (April 21)
* Elasticsearch Version: From OVA
* MongoDB Version: From OVA
* Operating System: From OVA
* Browser version: From OVA

**Comment by mariussturm** [comment]
This command is not needed anymore for Graylog 2.0. You can configure the retention settings directly in the web interface under System->Indices.
