### ISSUE TITLE
[graylog2-server.uris v1.3] How to combine Graylog nodes in version 2.0?

### ISSUE THREAD

**Issue by henb** [Graylog2/graylog2-server#2150]
### Problem description
In version 1.3 I see the option [**raylog2-server.uris**](http://docs.graylog.org/en/1.3/pages/installation/manual_setup.html?highlight=uris#downloading-and-extracting-the-web-interface) which comprises a list of graylog-server nodes
> raylog2-server.uris="http://127.0.0.1:12900/"

but in version 2.0, **[I can not understand ](http://docs.graylog.org/en/2.0/pages/installation/manual_setup.html?highlight=uris#downloading-and-extracting-the-web-interface)**how it works and how to combine Graylog nodes.

I looked in the [default config ](https://github.com/Graylog2/graylog2-server/blob/2.0/misc/graylog.conf)and I haven't found the right setting for this

Is it possible to somehow combine Graylog nodes in version 2.0?

#### Graylog Version: 

-  graylog-server-2.0.0-2.beta.1
-  graylog-server-2.0.0-3.beta.2
-  graylog-server-2.0.0-4.beta.3
-  graylog-server-2.0.0-4.rc.1

**Comment by joschi** [comment]
@henb We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
