### ISSUE TITLE
Nested Grok patterns

### ISSUE THREAD

**Issue by benwa** [Graylog2/graylog2-server#2158]
### Problem description
If you use a Grok pattern that includes another (like `USER` including `USERNAME`), an extractor will create multiple fields.

### Steps to reproduce the problem

1. Create an extractor using a Grok pattern that includes another Grok pattern in it
2. Hit Try
3. Notice two fields

Default `USER	%{USERNAME}`
![01](https://cloud.githubusercontent.com/assets/1351571/14890274/f2efb82c-0d2f-11e6-98ba-42d9e010281a.PNG)

Modifed `USER %{USERNAME:UNWANTED}`
![02](https://cloud.githubusercontent.com/assets/1351571/14890279/f412aa66-0d2f-11e6-87c2-c30a9984f223.PNG)

### Environment

* Graylog Version: 2.0
* Elasticsearch Version: 2
* MongoDB Version: 
* Operating System: Linux 4.2.0-35-generic
* Browser version: Chrome 50 x64

**Comment by joschi** [comment]
> If you use a Grok pattern that includes another (like USER including USERNAME), an extractor will create multiple fields.

That's intentional right now. Why do you think it should be different?

You've also already found the workaround (using the `:UNWANTED` specifier in the grok pattern).

**Comment by benwa** [comment]
To me, if I make an extractor, I only expect one field per pattern.
Getting two of the same information doesn't really help me.

On Thu, Apr 28, 2016 at 11:10 AM, Jochen Schalanda <notifications@github.com

**Comment by kroepke** [comment]
This can be solved with the rule pipeline.
Seems duplicated from https://github.com/Graylog2/graylog2-server/issues/1486, so I'll close this issue.
