### ISSUE TITLE
Feature Request - Have a role for an API useraccount

### ISSUE THREAD

**Issue by thepcn3rd** [Graylog2/graylog2-server#2159]
Currently I am trying to ingest from the Graylog REST API into another application.  To allow for that to occur the user account needs to be an administrator instead of a reader.  Can a role be made for just API calls in Graylog?

I am doing a GET on http://<url>:12900/messages/<index>/<messageID>

Thank you,

Graylog Server version 2.0.0
Windows 10
Elastic Search latest version
MongoDB latest version

### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@thepcn3rd You could simply create another admin user in the Graylog web interface (System &rarr; Users). Alternatively, create a stream with the messages you want to query and add a user to Graylog that has access to exactly that stream.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
