### ISSUE TITLE
after upgrade to 2.0, some dashboard problems

### ISSUE THREAD

**Issue by cmock** [Graylog2/graylog2-server#2163]
### Problem description

After the upgrade to 2.0, all of my pre-existing dashboards are broken, some more, some less.

Three of the five are completely empty, that is, no widgets are visible.

The other two do show all widgets; however, most of the "Quick values"-generated data tables are empty, except for those that I've added recently (with graylog 1.3). Their frame and title shows, but there is no table.

The screenshot shows a non-working and a recently added working table.
![graylog](https://cloud.githubusercontent.com/assets/2141141/14923628/7a00192e-0e3e-11e6-9d8c-d94d60fab336.png)

All the charts/histograms do show up fine.

### Environment

* Graylog Version: 2.0.0-5 (debian package)
* Elasticsearch Version: 2.3.2
* MongoDB Version: 2.6.12
* Operating System: Debian Stable (8.4)
* Browser version: Firefox 46.0

**Comment by kroepke** [comment]
Are there any errors in the Javascript console of your browser or any failed requests?

All of the widgets should continue to work in 2.0.

**Comment by cmock** [comment]
Some javascript errors, see attachment; however, none of them occurs after going to an affected dashboard (the log is from a fresh browser session, including login).

Only a single non-200 HTTP code, right at the start of the session, a 401 in response to a request for /api/system/sessions, before logging in.

I didn't change the dashboard, so if you let me know how to export the data from mongo, I'd be happy to share the configuration.

[ffconsole.txt](https://github.com/Graylog2/graylog2-server/files/245654/ffconsole.txt)

**Comment by dennisoelkers** [comment]
Is there anything in your server logs when trying to view an affected dashboard?

**Comment by edmundoa** [comment]
It would also help if you could share with us the configuration of one of the affected widgets. You can use the `/dashboards/<dashboardId>` resource in the REST API to get a dashboard configuration (including its widgets).

**Comment by cmock** [comment]
There's nothing in the server logs.

The API output is attached.
[54a6c996e4b093ce4aac32ae.txt](https://github.com/Graylog2/graylog2-server/files/258701/54a6c996e4b093ce4aac32ae.txt)

**Comment by supfors** [comment]
I've had the same issue. "Fixed" it by deleting the "positions" key sfrom the mongo graylog collection > Dashboards > (id).

**Comment by edmundoa** [comment]
I have been able to reproduce two different issues with the dashboard @cmock kindly shared:
- When the `positions` object does not contain `width` and `height`, the dashboard does not render at all
- Quickvalues widgets created in old Graylog versions (before the pie charts were introduced) will not render neither the data table, nor the pie chart.

**Comment by dennisoelkers** [comment]
Closing this, as it has been fixed now.
