### ISSUE TITLE
Indicies deleted during upgrade from 1.3.x -> 2.0.0

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#2166]
### Problem description
2.0 has removed the rotation_strategy and retention_strategy settings from the configuration file in order to make them configurable from within the web interface - the problem is that when a 2.0 master node starts after an upgrade it applies the default retention / rotation settings which in turn will remove all but the last 20 indicies. It will also apply the default rotation strategy which can cause problems but no data loss. Please change the default retention strategy to 'close' in order to prevent data loss during an upgrade.

### Steps to reproduce the problem

1.Upgrade a Graylog cluster to with lots of indices to 2.0 and start a master node.

### Environment

* Graylog Version: 2.0
* Elasticsearch Version: 2.3.2
* MongoDB Version: 2.6
* Operating System: N/A
* Browser version: N/A

**Comment by joschi** [comment]
I'm closing this issue as it's been addressed in #2171.
