### ISSUE TITLE
Graylog can no longer join an ES cluster that has the ES license plugin installed

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#2167]
### Problem description
When nodes in an ES cluster have the ES license plugin installed (for running Marvel or the commercial Elastic stuff) only nodes with that plugin installed are allowed to join that cluster.

This effectively means that Graylog server nodes no longer can join an ES cluster where nodes have the license plugin installed.

**Comment by evanccnyc** [comment]
Just ran into this as well. Be nice if we could run things like marvel, watcher on our elasticsearch cluster since the plugins help us know the status of our elasticsearch db.

**Comment by marcinkubica** [comment]
Funnily enough if you remove license plugin, graylog will get added, and then you can install license again :]

**Comment by joschi** [comment]
@marcinkubica Until you have to restart Graylog and it has to re-join the Elasticsearch cluster. Fun stuff…

**Comment by jalogisch** [comment]
we had documented this with https://github.com/Graylog2/documentation/commit/8f72337005cc366e47333ba3ef1c323c775fc77f 

but afaik this will not solved without rework the elasticsearch part of graylog.
