### ISSUE TITLE
Apache Commons Daemon

### ISSUE THREAD

**Issue by grafjo** [Graylog2/graylog2-server#218]
Hey guys,

Apache Commons Daemon is pretty helpful to run a java application as a native daemon / service on UNIX and Windows.

Windows requires procrun http://commons.apache.org/proper/commons-daemon/procrun.html and UNIX systems require jsvc http://commons.apache.org/proper/commons-daemon/jsvc.html

Currently nohub is used on UNIX systems - and that's maybe not the best way to run a service like graylog2-server.

I saw that there was already an PR https://github.com/Graylog2/graylog2-server/pull/109 to add Apache Commons Daemon as a service runner to graylog2-server. But this PR was rejected with "We decided that we are not going to use commons-daemons" -  what was the reason for this decision?

**Comment by bernd** [comment]
I am closing this now since we have proper init scripts for the different linux distributions now. Please re-open if this is still relevant. Thank you!

**Comment by grafjo** [comment]
alright
