### ISSUE TITLE
Disable default extraction of Syslog UDP Inputs

### ISSUE THREAD

**Issue by rockaut** [Graylog2/graylog2-server#2180]
### Problem description

If the data provided to an Syslog Input is not Syslog Standard conform the resulting fields by the default extractor will contain wrong data an as such is unuseable.
If an additional manual extractor is provided which is setting the field to correct values, even those get overwritten.

Plaintext inputs aren't a solution always, as they are falling short of features ( message level as example ).

### Example

ESXi Message full_message on Syslog UDP: <30>2016-05-03T13:46:02Z RBESX0802.cloud.local root: vsanObserver.sh: vsantraced is not started - can't start vsanObserver

Fields level, facility, source and timestamp are parsed correctly. But some other default fields are not. application_name ("is ") and process_id ("not ") aren't correctly parsed.

### Proposal

Adding option to disable default extractions from full_message as such but keeping fields like level intact.
Another solution would be to "upgrade" Raw\Plaintext Inputs to also recognize such Syslog fields and rDNS.

### Environment

* Graylog Version: Appliance - Graylog 2.0.0 (2dc6c03) on graylog (Oracle Corporation 1.8.0_77 on Linux 4.2.0-35-generic)

**Comment by joschi** [comment]
@rockaut Please take a look at the [extractors documentation](http://docs.graylog.org/en/2.0/pages/extractors.html). You can simply use a Raw/Plaintext UDP or TCP input to receive the non-standard syslog messages from your ESXi nodes and run extractors to structure the information in any way you like.

If you have more questions about that topic, please post to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by rockaut** [comment]
Well. No. As I stated plaintext Lacks important features. I understand this isn't a bug but it could be a feature.
