### ISSUE TITLE
rules.drl not always updating source field

### ISSUE THREAD

**Issue by 123dev** [Graylog2/graylog2-server#2188]
### Problem description
We have the following Drools code **A** and code **B** working in Graylog 1.3.x
##### Code A
```
// ==================================================================
// Rewrite source and remove .company.com
// ------------------------------------------------------------------
rule "Rewrite remove .company.com from source name"
        when
                m : Message( source matches "(.*)\\.company\\.com" )
        then
                Matcher matcher = Pattern.compile("(.*)\\.company.com",Pattern.CASE_INSENSITIVE).matcher(m.getField("source").toString());
                System.out.println("[.company.com]: Found " + m.getField("source"));
                if (matcher.find()) {
                        m.addField("source", matcher.group(1).toLowerCase());
                        System.out.println("[.company.com]: source updated " + matcher.group(1).toLowerCase());
                }
end
```

###### Code A Output:
```
[.company.com]: Found ABC.company.com
[.company.com]: source updated abc
```

##### Code B
```
// ==================================================================
// Rewrite ip-192-168-1-100 to vm17
// ------------------------------------------------------------------
rule "Rewrite ip-192-168-1-100 host"
        when
                m : Message( source == "ip-192-168-1-100" )
        then
                m.addField("source", "vm17" );
                System.out.println( "[Overwrite ip-192-168-1-100 rule fired] : " + m.toString() );
end
```

With Graylog 2.0, 
Code B is still working fine, however Code A even though the System.out is printing the same messages as 1.3.x, the source field in Graylog is not updated
and is kept as ABC.company.com

quite confused as to why it would work for code B but not code A in Graylog 2.0

### Steps to reproduce the problem

* Enable Drools
* include the Code A and B  in /etc/graylog/server/rules.drl
* Send Windows Event logs from ABC.company.com through nxlog 

### Environment

* Graylog Version: 2.0
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.2.6
* Operating System: Ubuntu 14.04
* Browser version: Chrome

**Comment by alex-mamchenkov** [comment]
Have similar behavior with Graylog 2.0 drools. In my case the rule similar "Code A" sometimes replaces the source and sometimes does not.

One finding though: if I disable all streams and leave messages just in main input stream - it looks like the rule works everytime, but as soon as I start adding messages to different streams (via stream rules), the drools rule works 70-80% of times. 

All same rules used to work 100% on graylog 1.3.4

**Comment by hc4** [comment]
Maybe the same problem as [here](https://github.com/Graylog2/graylog2-server/issues/2119)?

**Comment by alex-mamchenkov** [comment]
Looks like in my case. Adjusted the server configuration and looks fine now. Will wait for a fix in that ticket.
