### ISSUE TITLE
Content Pack rollback does not rollback the Grok  Patterns.

### ISSUE THREAD

**Issue by 123dev** [Graylog2/graylog2-server#2189]
### Problem description

When importing content pack, that runs into trouble, the import process tries to roll back.
It looks like it ignores or doesn't rollback the Grok patterns,
Everything else (Inputs, Extractors, Streams, Dashboards) are all rolled back.
### Steps to reproduce the problem
1. Export content_pack that includes Inputs, Extractors, Grok Patterns, Streams, Dashboards ...
2. On a clean Graylog, make sure you are missing an input type (due to plugin missing, Example AWS CloudTrail plugin, which was one of the inputs exported), and try to import the content_pack
3. You'd get an error that input type was missing, and the process rolls back.
4. Navigate to check Grok Patterns, and see that those were not rolled back.
### Environment
- Graylog Version: 2.0
- Elasticsearch Version: 2.3.2
- MongoDB Version: 3.2.6
- Operating System: Ubuntu 14.04
- Browser version: Chrome

**Comment by joschi** [comment]
Refs #4780

**Comment by bernd** [comment]
This will be fixed in 3.0.
