### ISSUE TITLE
[Feature] send single message to output / trigger alarm for single message

### ISSUE THREAD

**Issue by 123dev** [Graylog2/graylog2-server#2190]
### Problem description

It would be awesome if it was possible to select a message and manually trigger an alarm callback plugin or send to output plugin.

This way one can selectively for example, create a Jira ticket from a message, without it necessarily meeting the stream alert rules.

Alternately send that specific message to another Graylog or Output of a user's choice.
### Steps to reproduce the problem

New Feature request
### Environment
- Graylog Version: 2.0
- Elasticsearch Version: 2.3.2
- MongoDB Version: 3.2.6
- Operating System: Ubuntu 14.04
- Browser version: Chrome

**Comment by 123dev** [comment]
Another option would be to be able to send a message to a stream.

Let's say we create a developer / Contractor stream and grant permissions to that stream only, however no automatic processing is done,
Then a message can be selected and sent to the stream, making it available to the developer / contractor

Obviously group/multi  selection would be a bonus.

This is just another idea, and not a replacement of the above two.
Thanks

**Comment by jalogisch** [comment]
in our opinion this would be part of a plugin ... 

thank you

**Comment by 123dev** [comment]
Thanks Jan.

But how would a plugin integrate with the UI?
Are there such things as UI plugins?
We're talking about manually selecting from UI a single message and sending it to

- Stream
- Alert
- Output

What am I missing here?

**Comment by joschi** [comment]
@123dev
> Are there such things as UI plugins?

Yes, see http://docs.graylog.org/en/2.1/pages/plugins.html#creating-a-plugin-for-the-web-interface

**Comment by 123dev** [comment]
Thanks
