### ISSUE TITLE
Does graylog-server 2.0 work with openjdk-9-jre-headless ?

### ISSUE THREAD

**Issue by LordMike** [Graylog2/graylog2-server#2192]
On a fresh install of `Ubuntu 16.04`, I got `openjdk-9-jre-headless` along with `graylog-server 2.0.0-6` from `https://packages.graylog2.org/repo/debian/ stable 2.0` - and it doesn't seem to work. I changed the settings to define a set of parameters needed (secret and so on), but graylog never proceeded to listen on port `9000`.

The service log says the following, and just keeps repeating the last few lines. Being in the progress of upgrading everything to Ubuntu (from debian), I had another app (rundeck) that had a similar issue with jre9. So I removed that and installed `openjdk-8-jre-headless` - and wham, it worked. 

> 2016-05-05T03:22:42.923+02:00 INFO  [CmdLineTool] Loaded plugins: [Anonymous Usage Statistics 2.0.0 [org.graylog.plugins.usagestatistics.UsageStatsPlugin], Pipeline Processor Plugin 1.0.0-beta.2 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin], Collector 1.0.0 [org.graylog.plugins.collector.CollectorPlugin], MapWidgetPlugin 1.0.0 [org.graylog.plugins.map.MapWidgetPlugin], Enterprise Integration Plugin 1.0.0 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]]
> 2016-05-05T03:22:42.992+02:00 INFO  [CmdLineTool] Running with JVM arguments: -Xms1g -Xmx1g -XX:NewRatio=1 -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -Dlog4j.configurationFile=file:///etc/graylog/server/log4j2.xml -Djava.library.path=/usr/share/graylog-server/lib/sigar -Dgraylog2.installation_source=deb
> 2016-05-05T03:22:50.474+02:00 INFO  [InputBufferImpl] Message journal is enabled.
> 2016-05-05T03:22:50.605+02:00 INFO  [LogManager] Loading logs.
> 2016-05-05T03:22:50.733+02:00 INFO  [LogManager] Logs loading complete.
> 2016-05-05T03:22:50.733+02:00 INFO  [KafkaJournal] Initialized Kafka based journal at /var/lib/graylog-server/journal
> 2016-05-05T03:22:50.772+02:00 INFO  [InputBufferImpl] Initialized InputBufferImpl with ring size <65536> and wait strategy <BlockingWaitStrategy>, running 2 parallel message handlers.
> 2016-05-05T03:22:50.830+02:00 INFO  [cluster] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=5000}
> 2016-05-05T03:22:50.888+02:00 INFO  [cluster] No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, all=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 30000 ms before timing out
> 2016-05-05T03:22:50.947+02:00 INFO  [connection] Opened connection [connectionId{localValue:1, serverValue:5}] to localhost:27017
> 2016-05-05T03:22:50.948+02:00 INFO  [cluster] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[2, 6, 10]}, minWireVersion=0, maxWireVersion=2, maxDocumentSize=16777216, roundTripTimeNanos=796112}
> 2016-05-05T03:22:50.959+02:00 INFO  [connection] Opened connection [connectionId{localValue:2, serverValue:6}] to localhost:27017
> 2016-05-05T03:22:51.283+02:00 INFO  [NodeId] Node ID: 659aef84-500c-4cc2-9510-a02cff4e39e0
> 2016-05-05T03:22:51.440+02:00 INFO  [node] [graylog-659aef84-500c-4cc2-9510-a02cff4e39e0] version[2.3.1], pid[27662], build[bd98092/2016-04-04T12:25:05Z]
> 2016-05-05T03:22:51.440+02:00 INFO  [node] [graylog-659aef84-500c-4cc2-9510-a02cff4e39e0] initializing ...
> 2016-05-05T03:22:51.460+02:00 INFO  [plugins] [graylog-659aef84-500c-4cc2-9510-a02cff4e39e0] modules [], plugins [graylog-monitor], sites []
> 2016-05-05T03:22:53.593+02:00 INFO  [node] [graylog-659aef84-500c-4cc2-9510-a02cff4e39e0] initialized
> 2016-05-05T03:22:53.668+02:00 INFO  [Version] HV000001: Hibernate Validator 5.2.4.Final
> 2016-05-05T03:22:53.843+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:54.301+02:00 INFO  [OutputBuffer] Initialized OutputBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:54.594+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:54.824+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:54.921+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:54.966+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:55.011+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:55.037+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:55.065+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:55.274+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:55.387+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:55.487+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:55.539+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:55.559+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:55.591+02:00 INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
> 2016-05-05T03:22:55.610+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): null returned by binding at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
>  but parameter 2 of org.graylog2.bindings.providers.RulesEngineProvider.<init>() is not @Nullable
> 2016-05-05T03:22:55.611+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): null returned by binding at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
>  but parameter 2 of org.graylog2.bindings.providers.RulesEngineProvider.<init>() is not @Nullable
> 2016-05-05T03:22:55.611+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): null returned by binding at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
>  but parameter 2 of org.graylog2.bindings.providers.RulesEngineProvider.<init>() is not @Nullable
> 2016-05-05T03:22:55.611+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): null returned by binding at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
>  but parameter 2 of org.graylog2.bindings.providers.RulesEngineProvider.<init>() is not @Nullable
> 2016-05-05T03:22:55.612+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): null returned by binding at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
>  but parameter 2 of org.graylog2.bindings.providers.RulesEngineProvider.<init>() is not @Nullable
> 2016-05-05T03:22:55.612+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): null returned by binding at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
>  but parameter 2 of org.graylog2.bindings.providers.RulesEngineProvider.<init>() is not @Nullable
> 2016-05-05T03:22:55.612+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): null returned by binding at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
>  but parameter 2 of org.graylog2.bindings.providers.RulesEngineProvider.<init>() is not @Nullable
> 2016-05-05T03:22:55.613+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): null returned by binding at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
>  but parameter 2 of org.graylog2.bindings.providers.RulesEngineProvider.<init>() is not @Nullable
> 2016-05-05T03:22:55.613+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): null returned by binding at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
>  but parameter 2 of org.graylog2.bindings.providers.RulesEngineProvider.<init>() is not @Nullable
> 2016-05-05T03:22:55.613+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): null returned by binding at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)
>  but parameter 2 of org.graylog2.bindings.providers.RulesEngineProvider.<init>() is not @Nullable
> 2016-05-05T03:22:55.614+02:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): null returned by binding at com.github.joschi.jadconfig.guice.NamedConfigParametersModule.registerParameters(NamedConfigParametersModule.java:80)

### Steps to reproduce the problem

1. Install `openjdk-9-jre-headless` 
2. Install `mongodb` and `elasticsearch` (doubt it is necessary though - the logs do not indicate a connection to elastic before it fails)
3. Install `graylog-server` `2.0`
4. Confirm `graylog-server` starts, but never listens for web connections
5. Stop `graylog-server`, remove `openjdk-9-jre-headless`
6. Install `openjdk-8-jre-headless` 
7. Confirm `graylog-server` starts and works

### Environment

* Graylog Version: `2.0.0-6`
* Elasticsearch Version: `2.3.2`
* MongoDB Version: `1:2.6.10-0ubuntu1`
* Java version: `9~b114-0ubuntu1`

**Comment by kroepke** [comment]
JDK 9 is a pre-release (it is roughly 9 months away from being considered stable, see http://openjdk.java.net/projects/jdk9/ )and not supported right now.
We will address compatibility once it nears GA.
