### ISSUE TITLE
Reconfigure with enforce-ssl not enabling Nginx

### ISSUE THREAD

**Issue by joncojonathan** [Graylog2/graylog2-server#2196]
### Problem description
**Background**
From an OVA running v1.3.4 a _backend only_ server was configured.  This server was then manually upgraded to v2.0.0-2 via the omnibus package.

The original backend only server was moved to be the only server in the environment.

**Configuration**
After running:
> sudo graylog-ctl enforce-ssl
> sudo graylog-ctl reconfigure

nGinx was not automatically configured and appeared to not be enabled in graylog-services.json.  Enabling the service in graylog-services.json and re-running _sudo graylog-ctl reconfigure_ resolved the issue.

### Steps to reproduce the problem

1. Configure OVA 1.3.4 as a backend only server
2. Manually migrate and upgrade to v2.0.0-2

**It is not known if the server being backend only to begin with is a requirement **

### Environment

* Graylog Version: 1.3.4 --> 2.0.0 (2dc6c03)
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Linux 4.2.0-35-generic #40~14.04.1-Ubuntu SMP Fri Mar 18 16:37:35 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* Browser version: Chrome 50.0.2661.94 m

**Comment by kroepke** [comment]
@mariussturm Do we have upgrade documentation available for this scenario?

**Comment by mariussturm** [comment]
The cluster mode was just fixed for 2.0 appliances. Also the documentation is now up to date.
