### ISSUE TITLE
Graylog 2.0, web interface just with one open port ?

### ISSUE THREAD

**Issue by LeDistordu** [Graylog2/graylog2-server#2197]
My infrastructure : 

Haproxy - Port 443
|
Graylog Port 9000 (SSL Offloading)

No problem before 2.0 but after read this : http://docs.graylog.org/en/2.0/pages/configuring_webif.html

I feel that I must to open 12900 ? I try lot of thing with rest_listen_uri / rest_transport_uri / web_listen_uri / web_endpoint_uri but nothing works.

**Comment by mariussturm** [comment]
If you want to combine the API and the web interface port you need to mount port 12900, in your HAproxy configuration, under a sub path like `/api`. Then you can set the header X-Graylog-Server-URL to `https://$host:443/api`.

We use Github for tracking actual bugs, please use our community channles for general help!

Thanks,
Marius
