### ISSUE TITLE
Graylog 2.0.0-6 Failing To Create Admin User  (root_password_sha2 set properly)

### ISSUE THREAD

**Issue by juliovalcarcel** [Graylog2/graylog2-server#2199]
### Problem description
When setting up a brand new instance of Graylog, MongoDB, and Elasticsearch all on the same host I am unable to login to the web interface. I have attached my logs [graylog-server-log-snippet.txt](https://github.com/Graylog2/graylog2-server/files/252931/graylog-server-log-snippet.txt).

I have set the `root_password_sha2` config value by doing the following:
```bash
$ echo -n '1234' | shasum -a 256
03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4  -
```

When using the `mongo` client to view the users collection I get the following:
```bash
MongoDB shell version: 2.6.11
connecting to: test
Server has startup warnings: 
2016-05-06T15:16:10.822-0400 [initandlisten] 
2016-05-06T15:16:10.822-0400 [initandlisten] ** WARNING: Readahead for /var/lib/mongodb is set to 4096KB
2016-05-06T15:16:10.822-0400 [initandlisten] **          We suggest setting it to 256KB (512 sectors) or less
2016-05-06T15:16:10.822-0400 [initandlisten] **          http://dochub.mongodb.org/core/readahead
> use graylog
switched to db graylog
> db.users.find()
> 
```

I have ran through fresh install (reimaged machine) three times now and am at a loss of what to do. Let me know if you need more information from me.

### Steps to reproduce the problem

1. Install a new graylog instance
2. Install a new elasticsearch instance
3. Install a new mongodb instance
4. Configure all above
5. Setting the root_password_sha2
6. Unable to login to the web ui/ Cannot find any users in Mongo

### Environment

* Graylog Version: 2.0.0 Release 6
* Elasticsearch Version: 2.3.2
* MongoDB Version: 2.6.11
* Operating System: Centos 7.2.1511
* Browser version: Google Chrome 50

**Comment by kroepke** [comment]
The root user will not show up in mongodb, that part is fine.
However, to figure out why you cannot log in, could you please post your configuration as well?

Thanks!

**Comment by juliovalcarcel** [comment]
@kroepke 

```
is_master = true
node_id_file = /etc/graylog/server/node-id
password_secret = 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
root_username = admin
root_password_sha2 = '03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4'
root_timezone = America/New_York
plugin_dir = /usr/share/graylog-server/plugin
rest_listen_uri = http://monitor.mydomain.net:12900
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 4
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_node_master = false
elasticsearch_node_data = false
elasticsearch_analyzer = standard
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /var/lib/graylog-server/journal
lb_recognition_period_seconds = 3
mongodb_uri = mongodb://127.0.0.1:27017/graylog
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5
content_packs_dir = /usr/share/graylog-server/contentpacks
content_packs_auto_load = grok-patterns.json
```

**Comment by Myote** [comment]
Hi Julio,
Perhaps it's because you put your password_sha2 between quotes. password_secret don't need quotes too.

**Comment by joschi** [comment]
@juliovalcarcel Yes, @Myote is right. Please remove the single quotes around the values for `password_sha2` and `password_secret` altogether and you should be able to log in as "admin" with the given password.
