### ISSUE TITLE
Graylog Appliance 2.0 elasticsearch status "red" after deploying

### ISSUE THREAD

**Issue by Thomas-1985** [Graylog2/graylog2-server#2202]
### Problem description

I have another problem with my brand new graylog 2.0 appliance. I managed to get it to work but it instantly sais:

Elasticsearch cluster unhealthy (RED) (triggered 31 minutes ago)
The Elasticsearch cluster state is RED which means shards are unassigned. This usually indicates a crashed and corrupt cluster and needs to be investigated. Graylog will write into the local disk journal. Read how to fix this in the Elasticsearch setup documentation.

Some output:
root@graylog:~# curl -XGET http://192.168.1.10:9200/_cluster/health?pretty
{
  "cluster_name" : "graylog",
  "status" : "yellow",
  "timed_out" : false,
  "number_of_nodes" : 2,
  "number_of_data_nodes" : 1,
  "active_primary_shards" : 4,
  "active_shards" : 4,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 4,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 50.0
}

This is a single-server installation

### Steps to reproduce the problem

1. Deploy the 2.0 virtual OVA appliance and set it up.

### Environment

* Graylog Version: 2.0.0
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.2
* Operating System: Ubuntu 14.04.4
* Browser version: Firefox

**Comment by mariussturm** [comment]
This is an alert that happens during startup of the appliance when Graylog is ready before Elasticsearch is available. On a single node the yellow state is normal because there is no replication to a second host.

Please use our community channels for more general questions. We use Github for actual software bugs. Thanks!

**Comment by Thomas-1985** [comment]
Hi

Yes i know that but it says that the status is RED and not yellow.

**Comment by mariussturm** [comment]
It says that the state _was_ red 31 minutes ago, as you can see in your curl output the current state is yellow which is fine. Alerts need to be acknowledged by the user.

**Comment by Thomas-1985** [comment]
Ok sorry my bad.


Cheers

Thomy

Am 09.05.2016 um 11:38 schrieb Marius Sturm:
