### ISSUE TITLE
Converter "Syslog Level from PRI" does not return expected format

### ISSUE THREAD

**Issue by tokred** [Graylog2/graylog2-server#2207]
### Problem description
The message extractor converter "Syslog Level from PRI" does not return the level (severity) in a human-readable format, e.g. `debug`, `notice`, ... (see https://en.wikipedia.org/wiki/Syslog#Severity_level) but returns the (correct) numerical value. This is non-intuitive behaviour as it contradicts the converter "Syslog Facility from PRI" which does return keywords.

**Suspected origin:** `org.graylog2.inputs.converters.SyslogPriLevelConverter` returns `SyslogPriUtilities.levelFromPriority(priority)` instead of using `syslogLevelToReadable(...)` from `org.graylog2.plugin.Tools` ..?

Please align the behaviour of both converters.

### Steps to reproduce the problem

1. Create a new regex message extractor on a raw/plaintext input with Syslog messages.
2. Extract the Syslog PRI field, e.g. with '^<(\d+)>'
3. Apply converter "Syslog Level from PRI".
4. Check processed messages for target field which will contain numeric values instead of readable string values.

### Environment

* Graylog Version: 2.0.0
* Elasticsearch Version: 2.3.1
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by kroepke** [comment]
As this is a breaking change we are unlikely to implement it this way. However you can do this either via Drools or the new message pipeline feature in 2.0.

I'm closing this because there are workarounds.

Thanks,

Kay
