### ISSUE TITLE
ova doesn't work? 

### ISSUE THREAD

**Issue by DreadPirateRob** [Graylog2/graylog2-server#2217]
### Problem description

Gave up on the yum install (cant' get it working, can't even log into web interface) & decided to try the virtual appliance instead. 

Downloaded it and its running. First it picked up an IPV6 address and wanted to use that. 
but I logged into the console and ran
```
sudo graylog-ctl set-external-ip http://<IP>:80/

sudo graylog-ctl reconfigure
```
that completed successfully and I made sure that eth0 had the IP and the route was there. 

So I point my browser to `http://<IP>/` and I get the login screen. So I try to log in and I get an error that says: 
```
"Error - the server returned: 405 - cannot POST http://<IP>/system/sessions (405)" 
```

I used virtualbox and followed the directions here http://docs.graylog.org/en/stable/pages/installation/virtual_machine_appliances.html 
to import the ova appliance. 

any ideas?

**Comment by mariussturm** [comment]
The problem could be the IPv6/IPv4 mixed mode. Could you please assign an IPv4 address only and see if that fix the issue? http://docs.graylog.org/en/2.0/pages/installation/graylog_ctl.html#assign-a-static-ip

**Comment by mariussturm** [comment]
Closing this for now. Feel free to ping us again if the probelm is not solved.

**Comment by tylwright** [comment]
I can confirm - this issue can be resolved by setting the NIC in /etc/network/interfaces and then running a _sudo graylog-ctl reconfigure_.  Everything works now!  Thanks!
