### ISSUE TITLE
Some issues in Collector Plugin

### ISSUE THREAD

**Issue by Myote** [Graylog2/graylog2-server#2218]
### Problem description
1) The Gelf -TCP output for nxlog  is not created in nxlog.conf
![capcol2](https://cloud.githubusercontent.com/assets/12958868/15199002/776ae738-17db-11e6-819b-53f0b3795650.JPG)

2) When we use 2 tags, the first snippet is copied 2 times, before the second snippet,  in the resulting nxlog.conf 
![capcol1](https://cloud.githubusercontent.com/assets/12958868/15199081/d78d93ae-17db-11e6-8221-b131c90e366d.JPG)
[nxlog.txt](https://github.com/Graylog2/graylog2-server/files/260355/nxlog.txt)

3)Tags are case-sensitive , I do not know if it's wanted

### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.2.1
* Operating System: RHEL 6.6
* Browser version:

**Comment by joschi** [comment]
@Myote Thanks for reporting this.

Regarding the first issue, did you upgrade the [Collector Sidecar](https://github.com/Graylog2/collector-sidecar) after you've upgraded Graylog and the [Collector plugin](https://github.com/Graylog2/graylog-plugin-collector)?

**Comment by Myote** [comment]
Hi Joschi,

Oups my bad, I had updated yesterday, juste before ...It's good in CollectorVersion = "0.0.6" for the first  'issue'.
The second issue is still there and it was the case before upgrades.

**Comment by mariussturm** [comment]
The snippet render problem should be fixed in version 0.0.7!
