### ISSUE TITLE
Different field names in extractors (bundles vs extractors)

### ISSUE THREAD

**Issue by tomac** [Graylog2/graylog2-server#2219]
### Problem description

There are some incoherences in the field names when dealing with extractors. For instance, when creating a content pack (bundle), in each extractor we have the following fields (among others):
- type: Needs to be a valid type en capital letters (like GROK, SUBSTRING, etc.)
- configuration: if none, it can be an empty array
- cursor_estrategy: either COPY or CUT in capital letters
- condition_type: NONE, STRING, REGEX but in capital letters

The problem is when querying for extractors for an specific input, that all the fields are similar, except for those above. If I query /system/inputs/input_id/extractors I get a different behaviour in such fields:
- type: it is always in lowercase (grok, substring, etc.)
- configuration: it can be an empty array, but when updating an extractor it cannot be an empty array (Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token\n at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@ddcc9fd; line: 1, column: 133] (through reference chain: org.graylog2.rest.models.system.inputs.extractors.requests.CreateExtractorRequest[\"converters\"])
- cursor_estrategy: its value is always in lowercase
- condition_type: its value is always in lowercase

Or we want just to add a new extractor, the field names are different. Example:
``
{ "source_field": "message",
  "cut_or_copy": "copy",
  "converters": {},
  "extractor_config":
    {"grok_pattern": "Invalid user %{USERNAME:username} from %{IPV4:ip}"},
  "target_field": "username",
  "condition_type": "string",
  "condition_value": "sshd",
  "title": "KK SSH Invalid user login",
  "extractor_type": "grok"}
``

As you can see, we have 'extractor_type' instead of 'type', 'cut_or_copy' instead of 'cursor_estrategy' or 'extractor_config' instead of 'configuration'

### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version: 2.01
* Elasticsearch Version: 2.3
* MongoDB Version: 3.0.9
* Operating System: Debian Jessie
* Browser version:

**Comment by joschi** [comment]
@tomac The description of extractors (and other entities) as parts of content packs are not and were never intended to be identical to their "standalone" equivalents.
