### ISSUE TITLE
Geo-Location gone with 2.0.1 release ?

### ISSUE THREAD

**Issue by rgrey** [Graylog2/graylog2-server#2221]
### Problem description

My GeoIP dashboards are broken since the 2.0.1 release and the System / Configuration Plugins panel has disappeared !

### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.2.6
* Operating System: Linux 3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Browser version: Chrome Version 50.0.2661.94 m

**Comment by rgrey** [comment]
![image](https://cloud.githubusercontent.com/assets/6204867/15215168/f57a2838-1848-11e6-8fa6-b5e95ae99c2a.png)

![image](https://cloud.githubusercontent.com/assets/6204867/15215180/0c6a7ebc-1849-11e6-876b-f719dba87adf.png)

**Comment by joschi** [comment]
@rgrey Make sure that Graylog is allowed to access the directory configured in the `plugin_dir` setting (https://github.com/Graylog2/graylog2-server/blob/2.0.1/misc/graylog.conf#L32-L33) and that this directory contains the required JAR files.

**Comment by rgrey** [comment]
It is/can:

2016-05-12T13:45:25.521+01:00 INFO  [CmdLineTool] Loaded plugins: [Anonymous Usage Statistics 2.0.1 [org.graylog.plugins.usagestatistics.UsageStatsPlugin], Pipeline Processor Plugin 1.0.0-beta.3 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin], Collector 1.0.1 [org.graylog.plugins.collector.CollectorPlugin], MapWidgetPlugin 1.0.1 [org.graylog.plugins.map.MapWidgetPlugin], Enterprise Integration Plugin 1.0.1 [org.graylog.plugins.enterprise_integration.EnterpriseIntegrationPlugin]]

**Comment by rgrey** [comment]
total 13712
drwxr-xr-x 2 root root    4096 May 12 09:07 ./
drwxr-xr-x 6 root root    4096 May 12 09:07 ../
-rw-r--r-- 1 root root 1927936 May 11 15:02 graylog-plugin-collector-1.0.1.jar
-rw-r--r-- 1 root root 1804484 May 11 15:02 graylog-plugin-enterprise-integration-1.0.1.jar
-rw-r--r-- 1 root root 6710666 May 11 15:02 graylog-plugin-map-widget-1.0.1.jar
-rw-r--r-- 1 root root 3095549 May 11 15:02 graylog-plugin-pipeline-processor-1.0.0-beta.3.jar
-rw-r--r-- 1 root root  484490 May 11 15:02 usage-statistics-2.0.1.jar

**Comment by dennisoelkers** [comment]
@rgrey: Do you see any errors in your browser's javascript console?

**Comment by rgrey** [comment]
None. But, Guess what ? A Chrome Browser refresh with Ctrl+F5 and everything is magically back, including the config panel and now also the Dashboards :-)

**Comment by rgrey** [comment]
Thanks for the help.

**Comment by dennisoelkers** [comment]
Thanks for the heads up, @rgrey.

**Comment by rgrey** [comment]
CTRL+F5 might also be the answer to my lack of TLS/proxying as per http://docs.graylog.org/en/2.0/pages/configuring_webif.html !
