### ISSUE TITLE
get the possibility to have a text box inside a widget to change the request of this one without to have to edit the widget.  My case : i'v got a widget which tell for an email if last mails on the last 24H are correctly sent ou bounced. I want to give an access to my support client team to check if client-X or client-Y have received our mail or not.  i think it should be a great feature for simple user/reader of Graylog dashbord to get an really simple way to interact with a widget.

### ISSUE THREAD

**Issue by ChristopheBessonneau** [Graylog2/graylog2-server#2223]
### Problem description
get the possibility to have a text box inside a widget to change the request of this one without to have to edit the widget.
### Steps to reproduce the problem

My case : i'v got a widget which tell for an email if last mails on the last 24H are correctly sent ou bounced.
I want to give an access to my support client team to check if client-X or client-Y have received our mail or not.

i think it should be a great feature for simple user/reader of Graylog dashbord to get an really simple way to interact with a widget.
### Environment

* Graylog Version: last graylog OVA
* Elasticsearch Version: last graylog OVA
* MongoDB Version: last graylog OVA
* Operating System: last graylog OVA
* Browser version: last chrome/firefox

**Comment by mariussturm** [comment]
Thanks for the feature request, we are collecting those ideas in our ideas portal over here: https://graylog.ideas.aha.io

Thanks for contributing!
