### ISSUE TITLE
Stream alerts fail to trigger

### ISSUE THREAD

**Issue by compuvin** [Graylog2/graylog2-server#2225]
### Problem description
I recently migrated to v2.0 and since then none of my Streams seem to be triggering email alerts. I recreated all of my streams from scratch so it is possible that it is something I am missing (or a config setting). For instance, I have a stream for failed Windows admin logins, the stream shows messages if I fail a login, however the alerts page shows "This stream has never triggered an alert."

### Steps to reproduce the problem

I've tried many things, all with the same result. One stream I have configured with:
_Message count condition
Alert is triggered when there are more than 0 messages in the last minute. Grace period: 0 minutes. Including last message in alert notification_.

Another stream I configured with a field value (EventID="4771"). Again, looking at the stream itself shows many messages.

### Environment

* Graylog Version: 2.0.0 (2dc6c03)
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.2.6
* Operating System: Linux 3.13.0-85-generic
* Browser version: Chrome 50.0.2661.94 m

**Comment by joschi** [comment]
@compuvin Please upgrade to Graylog 2.0.0. This problem has been fixed in #2182.
