### ISSUE TITLE
OVA machines under virtualbox.

### ISSUE THREAD

**Issue by zuluechopapa** [Graylog2/graylog2-server#2226]
### Problem description
it seems to me that there's an issue with the ova imports into virtualbox, for the 2 versions I've tried 1.3.0 and 2.0.0-2 (I think?) the VM starts shows starting ntp, never completes startup process and is basically hung, if I alt-f2 to a virtual term and login I find /usr/bin/vmware-checkvm in a seemingly hung state.   if chmod 0 that file and reboot the vm starts up [in what I think is] correctly.

### Steps to reproduce the problem

1. install virtualbox 5.0.20
2. download and import the graylog ova file
3. start the vm, watch the console, note the machine never completes its startup.

### Environment
virtual 5.0.20 on centos hyper, graylog ova 2.0.0-2

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

strace of the process
root@graylog:/var/log# more typescript 
Script started on Thu 12 May 2016 04:15:47 PM UTC
root@graylog:/var/log# strace /usr/bin/vmware-checkvm 
execve("/usr/bin/vmware-checkvm", ["/usr/bin/vmware-checkvm"], [/* 21 vars */]) 
= 0
brk(0)                                  = 0x1ddc000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5
c869e3000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=18612, ...}) = 0
mmap(NULL, 18612, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f5c869d3000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/libvmtools.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\340\261\1\0\0\0\0\0"...,
 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=560864, ...}) = 0
mmap(NULL, 2660416, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f
5c8652b000
mprotect(0x7f5c8659c000, 2097152, PROT_NONE) = 0
mmap(0x7f5c8679c000, 98304, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENY
WRITE, 3, 0x71000) = 0x7f5c8679c000
mmap(0x7f5c867b4000, 2112, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONY
MOUS, -1, 0) = 0x7f5c867b4000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\37\2\0\0\0\0\0"..., 
832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1840928, ...}) = 0
mmap(NULL, 3949248, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f
5c86163000
mprotect(0x7f5c8631e000, 2093056, PROT_NONE) = 0
mmap(0x7f5c8651d000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENY
WRITE, 3, 0x1ba000) = 0x7f5c8651d000
mmap(0x7f5c86523000, 17088, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANON
YMOUS, -1, 0) = 0x7f5c86523000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0po\0\0\0\0\0\0"..., 832) 
= 832
fstat(3, {st_mode=S_IFREG|0755, st_size=141574, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5
c869e2000
mmap(NULL, 2217264, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f
5c85f43000
mprotect(0x7f5c85f5c000, 2093056, PROT_NONE) = 0
mmap(0x7f5c8615b000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYW
RITE, 3, 0x18000) = 0x7f5c8615b000
mmap(0x7f5c8615d000, 13616, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANON
YMOUS, -1, 0) = 0x7f5c8615d000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libglib-2.0.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\300\250\1\0\0\0\0\0"...,
 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1078368, ...}) = 0
mmap(NULL, 3175976, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f
5c85c3b000
mprotect(0x7f5c85d41000, 2093056, PROT_NONE) = 0
mmap(0x7f5c85f40000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYW
RITE, 3, 0x105000) = 0x7f5c85f40000
mmap(0x7f5c85f42000, 1576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONY
MOUS, -1, 0) = 0x7f5c85f42000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/libicui18n.so.52", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \256\t\0\0\0\0\0"..., 83
2) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=2121040, ...}) = 0
mmap(NULL, 4219880, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f
5c85833000
mprotect(0x7f5c85a2b000, 2097152, PROT_NONE) = 0
mmap(0x7f5c85c2b000, 57344, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENY
WRITE, 3, 0x1f8000) = 0x7f5c85c2b000
mmap(0x7f5c85c39000, 1000, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONY
MOUS, -1, 0) = 0x7f5c85c39000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/libicuuc.so.52", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0/\5\0\0\0\0\0"..., 832)
 = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1525776, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5
c869e1000
mmap(NULL, 3639856, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f
5c854b3000
mprotect(0x7f5c85617000, 2093056, PROT_NONE) = 0
mmap(0x7f5c85816000, 73728, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENY
WRITE, 3, 0x163000) = 0x7f5c85816000
mmap(0x7f5c85828000, 14896, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANON
YMOUS, -1, 0) = 0x7f5c85828000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\320\16\0\0\0\0\0\0"..., 
832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14664, ...}) = 0
mmap(NULL, 2109744, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f
5c852ab000
mprotect(0x7f5c852ae000, 2093056, PROT_NONE) = 0
mmap(0x7f5c854ad000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYW
RITE, 3, 0x2000) = 0x7f5c854ad000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260*\0\0\0\0\0\0"..., 83
2) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=90160, ...}) = 0
mmap(NULL, 2186016, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f
5c85093000
mprotect(0x7f5c850a9000, 2093056, PROT_NONE) = 0
mmap(0x7f5c852a8000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYW
RITE, 3, 0x15000) = 0x7f5c852a8000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libpcre.so.3", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260\27\0\0\0\0\0\0"..., 
832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=252032, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5
c869e0000
mmap(NULL, 2347200, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f
5c84e53000
mprotect(0x7f5c84e90000, 2093056, PROT_NONE) = 0
mmap(0x7f5c8508f000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYW
RITE, 3, 0x3c000) = 0x7f5c8508f000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \266\5\0\0\0\0\0"..., 83
2) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=979056, ...}) = 0
mmap(NULL, 3159040, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f
5c84b4b000
mprotect(0x7f5c84c31000, 2093056, PROT_NONE) = 0
mmap(0x7f5c84e30000, 40960, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENY
WRITE, 3, 0xe5000) = 0x7f5c84e30000
mmap(0x7f5c84e3a000, 82944, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANON
YMOUS, -1, 0) = 0x7f5c84e3a000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\20V\0\0\0\0\0\0"..., 832
) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1071552, ...}) = 0
mmap(NULL, 3166568, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f
5c84843000
mprotect(0x7f5c84948000, 2093056, PROT_NONE) = 0
mmap(0x7f5c84b47000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYW
RITE, 3, 0x104000) = 0x7f5c84b47000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/usr/lib/x86_64-linux-gnu/libicudata.so.52", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0p\5\0\0\0\0\0\0"..., 832)
 = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=23512848, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5
c869dc000
mmap(NULL, 25608208, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7
f5c82fd3000
mprotect(0x7f5c8463f000, 2093056, PROT_NONE) = 0
mmap(0x7f5c8483e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYW
RITE, 3, 0x166b000) = 0x7f5c8483e000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5
c869db000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5
c869d9000
arch_prctl(ARCH_SET_FS, 0x7f5c869d9780) = 0
mprotect(0x7f5c8651d000, 16384, PROT_READ) = 0
mprotect(0x7f5c8483e000, 4096, PROT_READ) = 0
mprotect(0x7f5c84b47000, 4096, PROT_READ) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f5
c869d8000
mprotect(0x7f5c84e30000, 32768, PROT_READ) = 0
mprotect(0x7f5c8508f000, 4096, PROT_READ) = 0
mprotect(0x7f5c854ad000, 4096, PROT_READ) = 0
mprotect(0x7f5c85816000, 69632, PROT_READ) = 0
mprotect(0x7f5c85c2b000, 53248, PROT_READ) = 0
mprotect(0x7f5c8615b000, 4096, PROT_READ) = 0
mprotect(0x7f5c85f40000, 4096, PROT_READ) = 0
mprotect(0x7f5c8679c000, 69632, PROT_READ) = 0
mprotect(0x600000, 4096, PROT_READ)     = 0
mprotect(0x7f5c869dd000, 4096, PROT_READ) = 0
munmap(0x7f5c869d3000, 18612)           = 0
set_tid_address(0x7f5c869d9a50)         = 2090
set_robust_list(0x7f5c869d9a60, 24)     = 0
futex(0x7ffd6bd10f70, FUTEX_WAIT_BITSET_PRIVATE|FUTEX_CLOCK_REALTIME, 1, NULL, 7
f5c869d9780) = -1 EAGAIN (Resource temporarily unavailable)
rt_sigaction(SIGRTMIN, {0x7f5c85f499f0, [], SA_RESTORER|SA_SIGINFO, 0x7f5c85f533
40}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f5c85f49a80, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x
7f5c85f53340}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
rt_sigaction(SIGILL, {0x7f5c8656aff0, [ILL SEGV], SA_RESTORER, 0x7f5c86199d40}, 
{SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGSEGV, {0x7f5c8656aff0, [ILL SEGV], SA_RESTORER, 0x7f5c86199d40},
 {SIG_DFL, [], 0}, 8) = 0
rt_sigprocmask(SIG_BLOCK, NULL, [], 8)  = 0
^C--- SIGINT {si_signo=SIGINT, si_code=SI_KERNEL} ---
Process 2090 detached
root@graylog:/var/log# jobs
root@graylog:/var/log# ps -ef | grep vmw
root      2110  2077  0 16:17 pts/0    00:00:00 grep vmw
root@graylog:/var/log# exit

Script done on Thu 12 May 2016 04:17:24 PM UTC

**Comment by mariussturm** [comment]
Thanks for the report! The next version of the appliance will be shipped without openvm-tools pre installed. VMWare users need to install them manually after first boot then.
