### ISSUE TITLE
yum packages don't respect plugin_dir setting

### ISSUE THREAD

**Issue by lasdem** [Graylog2/graylog2-server#2230]
### Problem description
If you use a different directory for your graylog-server plugins than the default and use yum repository to install and update you have to manually update the plugins in your own plugin directory. 

### Steps to reproduce the problem

1. install graylog-server via yum repository
2. set plugin_dir to custom location (eg.: `plugin_dir = /data/graylog/plugin` )
3. update graylog-server via yum

yum will put the new versions of all default plugins into `/usr/share/graylog-server/plugin/` and you have to manually copy them to `/data/graylog/plugin` and remove older versions. 

### Environment

* Graylog Version: up to 2.0.1

**Comment by kroepke** [comment]
Currently our packages do not try to read the changed configuration files and there aren't any plans to support this in the near future.

For now the easiest way to work around this is to use a symlink to your custom plugin directory.

Thanks,
Kay
