### ISSUE TITLE
Inserting strings into a numeric field breaks chart generation

### ISSUE THREAD

**Issue by yatahaze** [Graylog2/graylog2-server#2235]
### Problem description

I started with a numeric string, inserting data, running charts like normal. I accidentally for about a week was inserting the same numbers as strings. I've fixed it, but ever since then, charts won't load (just a spinning refresh icon). Other features don't seem to work well either.

### Steps to reproduce the problem

1. Insert numeric values into numeric field
2. Insert string numbers into numeric field
3. Try to run a chart on that field.

### Environment

* Graylog Version: 1.3.4
* Elasticsearch Version: 1.7.3
* MongoDB Version:  1:2.4.10-5
* Operating System: Debian Jessie amd64
* Browser version: Chrome Latest

**Comment by drewmmiranda** [comment]
I think this is an elasticsearch search issue. I recommend using dedicated fields for numeric values or using an extractor to copy/cut and convert to an integer.

**Comment by dennisoelkers** [comment]
Do you see any errors in your server log or your browser's javascript console?

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
