### ISSUE TITLE
Have a way to easily microbenchmark inputs

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#224]
This idea came up while thinking about a faster (but maybe less flexible) alternative to JSON. It would be great to easily microbenchmark inputs.

Maybe have a CLI flag `--input-benchmark` that is cutting the `ProcessBuffer` off the chain and only counts completely processed messages. Also only starting that one input and not starting any maintenance threads may be a good idea.

**Comment by bernd** [comment]
We have a benchmark output now which can be configured to replace the default Elasticsearch output. Closing this.
