### ISSUE TITLE
Integrated Webinterface can not connect when using docker

### ISSUE THREAD

**Issue by raben2** [Graylog2/graylog2-server#2241]
Since i install from source i use a very limited set of tools but everything seems to be running fine.
Only the Web-IF which is integrated in v. 2.0 can not connect to :12900 
no matter what i configure in graylog or docker.
i tried 0.0.0.0, 127.0.0.1 or i scripted to use the actual docker ip. but nothing works
It makes no difference if the port is exposed by docker or not.

When i run a graylog2-web docker v.1.3.4 the connection is fine but the api calls are bad.

### Environment

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.2
* MongoDB Version: 2.6
* Operating System: centos7/docker/elasticsearch
* Browser version:

**Comment by dennisoelkers** [comment]
Thanks for reporting this.

We have fairly complete [documentation](http://docs.graylog.org/en/2.0/pages/configuring_webif.html) about how to connect the server and the web interface. If you still feel this is a bug in Graylog after reading and verifying this, please reopen the issue and add further information.
