### ISSUE TITLE
Graylog consuming 100% CPU and becoming unresponsive

### ISSUE THREAD

**Issue by freddysdad** [Graylog2/graylog2-server#2245]
### Problem description

Hello,

I've been using Graylog for the last few days and am currently experiencing an issue whereby the Java process for Graylog starts to consume 100% CPU and the REST API becomes unresponsive. The web server is slow to respond but does eventually show that the REST API is unavailable.

I only have 3 Inputs, 3 streams and 1 output. There's approx 400 messages per second (a mixture of snmp traps, netflow data, syslog)

The log file shows the following:

> 2016-05-17T13:45:59.024+01:00 INFO  [SyslogOutput] Creating syslog output udp://10.2.0.200:514, format plain
> 2016-05-17T14:25:20.421+01:00 INFO  [connection] Opened connection [connectionId{localValue:10, serverValue:48}] to localhost:27017
> 2016-05-17T14:25:20.421+01:00 INFO  [connection] Opened connection [connectionId{localValue:11, serverValue:49}] to localhost:27017
> 2016-05-17T14:25:20.425+01:00 INFO  [connection] Opened connection [connectionId{localValue:9, serverValue:47}] to localhost:27017
> 2016-05-17T14:54:00.874+01:00 INFO  [connection] Opened connection [connectionId{localValue:12, serverValue:50}] to localhost:27017
> 2016-05-17T15:02:24.272+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:06:58.681+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:07:43.137+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:08:07.896+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:08:11.384+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:08:19.240+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:08:49.429+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:08:56.590+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:09:02.996+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:09:15.489+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:09:21.468+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:09:30.532+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:09:33.427+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:09:36.618+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:09:46.292+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:10:04.425+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:10:19.331+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:10:29.981+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:10:36.209+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:11:00.426+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:11:03.642+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:11:09.587+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:11:50.538+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:12:05.602+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:12:11.452+01:00 WARN  [ProxiedResource] Unable to call http://10.2.0.216:12900/system/metrics/multiple on node <53782e12-85fb-49ba-9d01-44bccf51c985>, caught exception: Read timed out (class java.net.SocketTimeoutException)
> 2016-05-17T15:12:24.079+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:12:33.199+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:12:51.445+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:12:53.831+01:00 WARN  [ProxiedResource] Unable to call http://10.2.0.216:12900/system/metrics/multiple on node <53782e12-85fb-49ba-9d01-44bccf51c985>, caught exception: Read timed out (class java.net.SocketTimeoutException)
> 2016-05-17T15:13:57.358+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:14:10.314+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:14:47.605+01:00 WARN  [ProxiedResource] Unable to call http://10.2.0.216:12900/system/metrics/multiple on node <53782e12-85fb-49ba-9d01-44bccf51c985>, caught exception: Read timed out (class java.net.SocketTimeoutException)
> 2016-05-17T15:14:47.605+01:00 WARN  [ProxiedResource] Unable to call http://10.2.0.216:12900/system/metrics/multiple on node <53782e12-85fb-49ba-9d01-44bccf51c985>, caught exception: timeout (class java.net.SocketTimeoutException)
> 2016-05-17T15:16:00.861+01:00 WARN  [NodePingThread] Did not find meta info of this node. Re-registering.
> 2016-05-17T15:16:43.475+01:00 INFO  [Server] SIGNAL received. Shutting down.

The first line in the log is the last line shown after the server starts, and the last line is after restarting the service. The problem re-occurs after a short time, in the same manner.

`GRAYLOG_SERVER_JAVA_OPTS="-Xms1g -Xmx1g -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow"`

### Environment

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.2
* MongoDB Version: 2.6.10
* Operating System: Ubuntu 16.04 LTS
* Browser version: Firefox 46 on Ubuntu 16.04 LTS

Any ideas?

**Comment by freddysdad** [comment]
Seems this issue just cropped up again:

> PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                              
> 5921 graylog   20   0 4832568 1.363g  23792 S 100.0 17.5  59:49.23 java

> KiB Mem :  8175228 total,  4049264 free,  2535964 used,  1590000 buff/cache

**Comment by joschi** [comment]
@freddysdad Try providing a little more heap memory to Graylog with the `-Xmx` and `-Xms` JVM flag, e. g. `-Xms2g -Xmx2g`.

Please also attach your complete Graylog log file(s) to this issue.

**Comment by freddysdad** [comment]
Thanks, I updated the flags as requested and will let you know how I get on. Attached is the log file as requested.

[server.log.txt](https://github.com/Graylog2/graylog2-server/files/268672/server.log.txt)

Regards

**Comment by freddysdad** [comment]
OK, this appears not to have solved the issue, I'm just sanitizing the log and then I'll attach it here.

Elasticsearch appears healthy:

> root@flowcollector:~# curl -XGET 'http://localhost:9200/_cluster/health?pretty=true'
> {
>   "cluster_name" : "graylog-production",
>   "status" : "green",
>   "timed_out" : false,
>   "number_of_nodes" : 1,
>   "number_of_data_nodes" : 1,
>   "active_primary_shards" : 4,
>   "active_shards" : 4,
>   "relocating_shards" : 0,
>   "initializing_shards" : 0,
>   "unassigned_shards" : 0,
>   "delayed_unassigned_shards" : 0,
>   "number_of_pending_tasks" : 0,
>   "number_of_in_flight_fetch" : 0,
>   "task_max_waiting_in_queue_millis" : 0,
>   "active_shards_percent_as_number" : 100.0
> }

**Comment by freddysdad** [comment]
[server.log.2.txt](https://github.com/Graylog2/graylog2-server/files/270074/server.log.2.txt)

**Comment by freddysdad** [comment]
> PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
> 7283 graylog   20   0 5895572 2.420g  23608 S 100.3 31.0 880:38.73 java

> strace: Process 7283 attached
> futex(0x7f3f5489d9d0, FUTEX_WAIT, 7284, NULL

It's currently in this state now - I'm happy to leave it for a bit - is there anything I can do to get more information on whats happening?

Regards

**Comment by joschi** [comment]
There are lots of very long GC pauses and `java.lang.OutOfMemoryError` messages in your logs. Provide more heap space to the Graylog process (try 4 GB if 2GB didn't work).

What are the specs of the machine hosting Graylog?

**Comment by freddysdad** [comment]
OK, I'll try that. It's a VM with 8GB RAM & 4 CPUs

**Comment by joschi** [comment]
@freddysdad Any news on this?

**Comment by Nonname123** [comment]
I have some problem with my graylog 2.0.3. I have very little load (10-20 messages in sec), i set -Xmx 4g, but after ~4hours get this error. Node load page in web interface indicate on graylog start 200-300mb memory usage and up to ~1gb, after GC usage return to ~300mb, after 1 hour of working memory usage up to  2-3gb, after 3-4 hours i get java.lang.OutOfMemoryError. This seems like memory leak.
Server settings: 8 core, 8gb RAM. ES 2.3.2 -Xmx 2g, Graylog 2.0.3 -Xmx 4g, debian 8 3.16.0-4-amd64, Mongodb 3.0.12, OpenJDK 64-Bit 1.8.0_91-8u91-b14-1~bpo8+1-b14

**Comment by joschi** [comment]
@Nonname123 We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by joschi** [comment]
Closing this issue because the original author didn't reply within a few months.

**Comment by flapegue** [comment]
sorry, i just understood ...
