### ISSUE TITLE
[WEB] Unhandled rejection TypeError: Cannot read property 'is_valid' of null AND Error - the server returned: 405 - cannot POST /system/sessions (405)

### ISSUE THREAD

**Issue by alexmatveev** [Graylog2/graylog2-server#2248]
### Problem description

Critical bug in web interface, making it not usable.

On page load:
> plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:17752
> Unhandled rejection TypeError: Cannot read property 'is_valid' of null
>     at https://[host]/plugin/org.graylog.plugins.pipelineprocessor.Proce…pipelineprocessor.PipelineProcessorPlugin.ad35acdcb615fa496058.js:86097:20
>     at tryCatcher (https://[host]/plugin/org.graylog.plugins.pipelineprocessor.Proce…pipelineprocessor.PipelineProcessorPlugin.ad35acdcb615fa496058.js:21388:24)
>     at Promise._settlePromiseFromHandler (https://[host]/plugin/org.graylog.plugins.pipelineprocessor.Proce…pipelineprocessor.PipelineProcessorPlugin.ad35acdcb615fa496058.js:19494:32)
>     at Promise._settlePromiseAt (https://[host]/plugin/org.graylog.plugins.pipelineprocessor.Proce…pipelineprocessor.PipelineProcessorPlugin.ad35acdcb615fa496058.js:19568:19)
>     at Promise._settlePromises (https://[host]/plugin/org.graylog.plugins.pipelineprocessor.Proce…pipelineprocessor.PipelineProcessorPlugin.ad35acdcb615fa496058.js:19684:15)
>     at Async._drainQueue (https://[host]/plugin/org.graylog.plugins.pipelineprocessor.Proce…pipelineprocessor.PipelineProcessorPlugin.ad35acdcb615fa496058.js:16974:17)
>     at Async._drainQueues (https://[host]/plugin/org.graylog.plugins.pipelineprocessor.Proce…pipelineprocessor.PipelineProcessorPlugin.ad35acdcb615fa496058.js:16984:11)
>     at Async.drainQueues (https://[host]/plugin/org.graylog.plugins.pipelineprocessor.Proce…pipelineprocessor.PipelineProcessorPlugin.ad35acdcb615fa496058.js:16866:15)

And on login:

> plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:22664 POST https://[host]/system/sessions 405 (Method Not Allowed)Request.end @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:22664(anonymous function) @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:16757tryCatcher @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:21388Promise._resolveFromResolver @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:19467Promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:19057Request.promise @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:16756Request.then @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:16791json @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:16637login @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:86109n @ vendor.js:415r.emit @ vendor.js:409e.exports.trigger @ vendor.js:415(anonymous function) @ vendor.js:415(anonymous function) @ vendor.js:408r.run @ vendor.js:405o @ vendor.js:405
> plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.ad35acd….js:16591 There was an error fetching a resource: cannot POST https://[host]/system/sessions (405). Additional information: HTTP 405 Method Not Allowed

See steps and screenshots below.

### Steps to reproduce the problem

1. Load web interface

![graylog web interface 2016-05-18 11-32-38](https://cloud.githubusercontent.com/assets/1456669/15352541/579fb80e-1ced-11e6-99f9-962e5862b77d.png)

2. Try login

![graylog web interface 2016-05-18 11-34-39](https://cloud.githubusercontent.com/assets/1456669/15352553/61befb06-1ced-11e6-8128-8a276aca6ec4.png)

### Environment

* Graylog Version: 2.0.1-1
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.0.12
* Operating System: Ubuntu 14.04.4 LTS
* Browser version: Google Chrome Mac 50.0.2661.102 (64-bit)

**Comment by dennisoelkers** [comment]
What's your server configuration for the web interface? (all `web_*` / `rest_*` configuration directives)

Do you use a proxy in front of your Graylog server?

**Comment by alexmatveev** [comment]
Yes, i'm using nginx as proxy.

/etc/graylog/server/server.conf:

> web_listen_uri = http://127.0.0.1:9000/
> web_endpoint_uri = http:/[host]/
> rest_listen_uri = http://127.0.0.1:12900/
> 

nginx:

> server {
>         listen 78.46.42.229:80;
>         server_name [host];
>         location / {
>                 proxy_pass http://127.0.0.1:9000;
>                 proxy_redirect off;
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         }
> }

It was https on nginx with self-signed certificate first, now it's http for debug (same result).

**Comment by alexmatveev** [comment]
Yes, i'm using nginx as proxy.

/etc/graylog/server/server.conf:

> web_listen_uri = http://127.0.0.1:9000/
> web_endpoint_uri = http:/[host]/
> rest_listen_uri = http://127.0.0.1:12900/
> 

nginx:

> server {
>         listen [IP]:80;
>         server_name [host];
>         location / {
>                 proxy_pass http://127.0.0.1:9000;
>                 proxy_redirect off;
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         }
> }

It was https on nginx with self-signed certificate first, now it's http for debug (same result).

**Comment by alexmatveev** [comment]
Just tried to run without nginx, same result

**Comment by dennisoelkers** [comment]
Any errors in your server log?

From what I can see, communication from the web interface to your Graylog server does not work, either because it is connecting to the wrong destination or something in between is messing with the requests/response.

You are using `web_endpoint_uri` to define the destination for the web interface, but I would recommend setting the `X-Graylog-Server-URL`-http-header in your nginx server config, which is a more flexible solution.

Can you try 
  * setting it to the publicly (as in: from your client's web browsers) accessible URL and 
  * make sure that the URL is really accessible by doing a `curl  -v -XPOST <url>/system/sessions`? It should response with a 400, but not a 405.

**Comment by alexmatveev** [comment]
Same results:

> $ curl -v -XPOST 127.0.0.1:9000/system/sessions
> * Hostname was NOT found in DNS cache
> *   Trying 127.0.0.1...
> * Connected to 127.0.0.1 (127.0.0.1) port 9000 (#0)
> > POST /system/sessions HTTP/1.1
> > User-Agent: curl/7.35.0
> > Host: 127.0.0.1:9000
> > Accept: */*
> > 
> < HTTP/1.1 405 Method Not Allowed
> < Allow: GET,OPTIONS
> < X-Graylog-Node-ID: 1ec60faa-de23-45e4-aee1-8f22bd57f4bb
> < Vary: Accept-Encoding
> < Content-Type: application/json
> < Date: Wed, 18 May 2016 09:49:37 GMT
> < Content-Length: 59
> < 
> * Connection #0 to host 127.0.0.1 left intact
> {"type":"ApiError","message":"HTTP 405 Method Not Allowed"}


Setting X-Graylog-Server-URL in nginx with proxy_set_header didn't change anything.
And I also tried to launch Graylog2 without nginx as a proxy, no success.

**Comment by edmundoa** [comment]
@alexmatveev The request to `/system/sessions` should go against the REST API (port 12900), and not the web interface (port 9000). Please take into account that both the web interface and the REST API should be accessible from your browser.

**Comment by alexmatveev** [comment]
@edmundoa I just found this. At first look, this means that REST API must be accessible from internet. I'll read about this in docs, thanks.

**Comment by edmundoa** [comment]
@alexmatveev That highly depends on your setup, for many people it is enough to make it available in an internal network.
