### ISSUE TITLE
Alert when many new fields are created

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#225]
Performance of indexing decreases rapidly when almost each new message contains previously unseen fields, due to ElasticSearch having to update the mappings all the time.

We can detect newly generated mappings on the fly and alert the user based on some running average thresholds.
This is mostly an issue for users using misconfigured logstash instances sending data.

**Comment by bernd** [comment]
Closing this because we didn't implement this in 3 years and I don't see an urgent need for something like this.
