### ISSUE TITLE
Webinterface behind Apache httpd - order is relevant

### ISSUE THREAD

**Issue by mayrstefan** [Graylog2/graylog2-server#2252]
### Problem description

Login behind Apache reverse proxy fails with HTTP 405 Method Not Allowed

### Steps to reproduce the problem

1. Configure Graylog2 Webinterface behind Apache as described in http://docs.graylog.org/en/2.0/pages/configuring_webif.html
2. Try to Login: Result POST to /api/system/sessions is denied with HTTP 405: 

> {"type":"ApiError","message":"HTTP 405 Method Not Allowed"}

### Steps to fix the problem

Change the order in the configuration: move /api/ before /
```
    <Location /api/>
        ProxyPass http://127.0.0.1:12900/
        ProxyPassReverse http://127.0.0.1:12900/
    </Location>
    <Location />
        RequestHeader set X-Graylog-Server-URL "https://graylog.example.org/api/"
        ProxyPass http://127.0.0.1:9000/
        ProxyPassReverse http://127.0.0.1:9000/
    </Location>
```

### Environment

* Graylog Version: 2.0.1
* Operating System: SLES11 SP4, Apache 2.2.12

**Comment by dennisoelkers** [comment]
Thanks for reporting this! I have corrected the passage in the documentation.

**Comment by edmundoa** [comment]
@jalogisch and I were trying to use the updated configuration (`/api/` before `/`) with Apache 2.4, and run exactly into this problem: requests to the REST API were going to the web interface instead, therefore the 405s.

**Comment by jalogisch** [comment]
we update the documentation to be a little more specific in [apache versions](http://docs.graylog.org/en/2.0/pages/configuring_webif.html#apache) - should be clear now
