### ISSUE TITLE
405 Error with SSL

### ISSUE THREAD

**Issue by moonmeister** [Graylog2/graylog2-server#2257]
Whether adding SSL through the server.conf or through an apache proxy I get an error on login that says:

`Error - the server returned: 405 - cannot POST `

OS: Ubuntu 16.04
Manual Install 

Apache config:

```
Listen 443
<VirtualHost *:443>
        ServerName log.example.net
        ServerAlias log.example.net

         # SSL Config
        SSLEngine on
        SSLProtocol ALL -SSLv2 -SSLv3
        SSLHonorCipherOrder On
        SSLCipherSuite ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS
        SSLCertificateFile /etc/ssl/graylog/example.net.crt
        SSLCertificateKeyFile /etc/ssl/graylog/example.net.key

<Location /api/>
        ProxyPass http://127.0.0.1:12900/
        ProxyPassReverse http://127.0.0.1:12900/
    </Location>
    <Location />
        RequestHeader set X-Graylog-Server-URL "https://log.example.net/api/"
        ProxyPass http://127.0.0.1:9000/
        ProxyPassReverse http://127.0.0.1:9000/
    </Location>
</VirtualHost>
```

For both configs I followed: 
http://docs.graylog.org/en/2.0/pages/configuring_webif.html#apache

First with the configuration options then with the reverse proxy. Both caused this error.

Let me know if you need any more info. Thakns

**Comment by dennisoelkers** [comment]
Can you do a `curl -XPOST -v http://127.0.0.1:12900/system/sessions` on the host itself? Does it work?

If yes, try doing a `curl -XPOST -v https://log.example.net/api/system/sessions` on the machine your browser is running on. Does it work too?

**Comment by rompic** [comment]
same here

**Comment by edmundoa** [comment]
@rompic maybe you can answer the questions @dennisoelkers was asking, just saying "same here" doesn't help to fix the issue :)

**Comment by rompic** [comment]
seems as if apache blocks the POST call from my local machine
curl -XPOST -v https://graylog.example.com/api/system/sessions
*   Trying 11.11.11.11...
* Connected to graylog.example.com (11.11.11.11) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.example.com
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> POST /api/system/sessions HTTP/1.1
> Host: graylog.example.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 405 Method Not Allowed
< Date: Thu, 19 May 2016 14:45:47 GMT
< Server: Apache/2.4.7 (Ubuntu)
< Allow: GET,OPTIONS
< X-Graylog-Node-ID: ff623421-590a-46ac-9435-481688e4c05d
< Vary: Accept-Encoding
< Content-Type: application/json
< Content-Length: 59
< 
* Connection #0 to host graylog.example.com left intact
{"type":"ApiError","message":"HTTP 405 Method Not Allowed"}

**Comment by rompic** [comment]
apache access log:
11.11.11.11 - - [19/May/2016:16:49:20 +0200] "POST /a/metrics/643/5ed44j45/xhr?t=1463669360316 HTTP/1.1" 405 469
11.11.11.11 - - [19/May/2016:16:49:22 +0200] "GET /a/metrics/995/gp00jw5l/jsonp?c=_jp.a23vccp HTTP/1.1" 200 835
11.11.11.11 - - [19/May/2016:16:49:23 +0200] "GET /a/metrics/643/j4e2w0gq/jsonp?c=_jp.aydzjjw HTTP/1.1" 200 835
11.11.11.11 - - [19/May/2016:16:49:24 +0200] "GET /a/metrics/info?t=1463669364766 HTTP/1.1" 200 835
11.11.11.11 - - [19/May/2016:16:49:24 +0200] "POST /a/metrics/085/zswi2o2b/xhr?t=1463669364778 HTTP/1.1" 405 469
11.11.11.11 - - [19/May/2016:16:49:24 +0200] "GET /a/metrics/iframe.html HTTP/1.1" 200 835
11.11.11.11 - - [19/May/2016:16:49:24 +0200] "GET /config.js HTTP/1.1" 200 496
11.11.11.11 - - [19/May/2016:16:49:25 +0200] "GET /api/system/sessions HTTP/1.1" 200 835

**Comment by joschi** [comment]
@rompic Please post your Apache httpd configuration. Take note that the order of the `<Location>` directives is important in this context and the one with `<Location /api>` **must** be first.

**Comment by rompic** [comment]
[vhost.txt](https://github.com/Graylog2/graylog2-server/files/272840/vhost.txt)
i also tried with the settings from the docu

**Comment by rompic** [comment]
curl from server:

```
curl -XPOST -v http://127.0.0.1:12900/system/sessions
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 12900 (#0)
> POST /system/sessions HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:12900
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Vary: Accept
< Vary: Accept-Encoding
< X-Graylog-Node-ID: ff623421-590a-46ac-9435-481688e4c05d
< Content-Type: text/plain
< Date: Thu, 19 May 2016 16:39:12 GMT
< Connection: close
< Content-Length: 79
< 
may not be null (path = SessionsResource.newSession.arg1, invalidValue = null)
* Closing connection 0
```

**Comment by moonmeister** [comment]
curl -XPOST -v http://127.0.0.1:12900/system/sessions

```
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 12900 (#0)
> POST /system/sessions HTTP/1.1
> Host: 127.0.0.1:12900
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 400 Bad Request
< Vary: Accept
< X-Graylog-Node-ID: a18959ec-ec44-4262-b64a-29c86ac00db1
< Content-Type: text/plain
< Date: Thu, 19 May 2016 16:47:23 GMT
< Connection: close
< Content-Length: 79
< 
may not be null (path = SessionsResource.newSession.arg1, invalidValue = null)
* Closing connection 0
```

curl -XPOST -v https://log.example.net/api/system/sessions


```
*   Trying 10.80.30.19...
* Connected to log.example.net (10.80.30.19) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: *.example.net
* Server certificate: Go Daddy Secure Certificate Authority - G2
* Server certificate: Go Daddy Root Certificate Authority - G2
> POST /api/system/sessions HTTP/1.1
> Host: log.example.net
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 405 Method Not Allowed
< Date: Thu, 19 May 2016 16:48:42 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Allow: GET,OPTIONS
< X-Graylog-Node-ID: a18959ec-ec44-4262-b64a-29c86ac00db1
< Vary: Accept-Encoding
< Content-Type: application/json
< Content-Length: 59
< 
* Connection #0 to host log.example.net left intact
{"type":"ApiError","message":"HTTP 405 Method Not Allowed"}

```

**Comment by moonmeister** [comment]
Here's the server.conf config I'm using when trying to not use apache if that's helpful. 

```
rest_listen_uri = https://10.80.30.19:12900/
rest_transport_uri = https://log.example.net:12900/
rest_enable_tls = true
rest_tls_cert_file = /etc/graylog/server/certs/example.net.crt
rest_tls_key_file = /etc/graylog/server/certs/example.net.key

web_listen_uri = https://10.80.30.19:9000/
web_endpoint_uri = https://log.example.net:9000/
web_enable_tls = true
web_tls_cert_file = /etc/graylog/server/certs/example.net.crt
web_tls_key_file = /etc/graylog/server/certs/example.net.key
```

error:

`Error - the server returned: 405 - cannot POST https://log.example.net:9000/system/sessions (405)`

Here's the full error from when I use apache:

`Error - the server returned: 405 - cannot POST https://log.singlemindconsulting.net/api/system/sessions (405)`

I'm realizing there is something weird with these errors. Being that when you are using a proxy it's trying to talk to through the /api/ to access 12900 but when you aren't using apache it's trying to talk directly to 9000 and not the api at 12900 which is the web not the api. Maybe I just don't understand something or this has nothing to do with our current problem.

**Comment by rompic** [comment]
mine are
```
rest_listen_uri = http://127.0.0.1:12900/
web_listen_uri = https://127.0.0.1:9000/
```

others not set, tls disabled

**Comment by moonmeister** [comment]
@rompic if you're trying to not use apache and have HTTPS then you have to at least enable TLS. the listen uri only affects where  it listens, I don't think the http/https affects anything.

**Comment by rompic** [comment]
i have the impression that the requests are not getting routed correctly.

**Comment by moonmeister** [comment]
Does this have anything to do with: #2130 ?

**Comment by moonmeister** [comment]
Here are some detailed error logs...you can see in the middle when I request /api/ url it does not referer it on to 12900 but to 9000. Look wrong.

```
[Thu May 19 13:16:21.041340 2016] [ssl:info] [pid 31878:tid 139919615809280] [client 10.80.25.72:59915] AH01964: Connection to child 77 established (server log.singlemindconsulting.net:443)
[Thu May 19 13:16:21.041618 2016] [ssl:debug] [pid 31878:tid 139919615809280] ssl_engine_kernel.c(2096): [client 10.80.25.72:59915] AH02043: SSL virtual host for servername log.singlemindconsulting.net found
[Thu May 19 13:16:21.041667 2016] [core:debug] [pid 31878:tid 139919615809280] protocol.c(1891): [client 10.80.25.72:59915] select protocol from , choices=h2,spdy/3.1,http/1.1 for server log.singlemindconsulting.net
[Thu May 19 13:16:21.041698 2016] [ssl:debug] [pid 31878:tid 139919615809280] ssl_engine_kernel.c(2096): [client 10.80.25.72:59915] AH02043: SSL virtual host for servername log.singlemindconsulting.net found
[Thu May 19 13:16:21.043989 2016] [ssl:debug] [pid 31878:tid 139919615809280] ssl_engine_kernel.c(2023): [client 10.80.25.72:59915] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
[Thu May 19 13:16:21.085038 2016] [ssl:debug] [pid 31878:tid 139919615809280] ssl_engine_kernel.c(354): [client 10.80.25.72:59915] AH02034: Initial (No.1) HTTPS request received for child 77 (server log.singlemindconsulting.net:443), referer: https://log.singlemindconsulting.net/api/
[Thu May 19 13:16:21.085132 2016] [authz_core:debug] [pid 31878:tid 139919615809280] mod_authz_core.c(835): [client 10.80.25.72:59915] AH01628: authorization result: granted (no directives), referer: https://log.singlemindconsulting.net/api/
[Thu May 19 13:16:21.085179 2016] [proxy:debug] [pid 31878:tid 139919615809280] mod_proxy.c(1160): [client 10.80.25.72:59915] AH01143: Running scheme http handler (attempt 0), referer: https://log.singlemindconsulting.net/api/
[Thu May 19 13:16:21.085206 2016] [proxy:debug] [pid 31878:tid 139919615809280] proxy_util.c(2160): AH00942: HTTP: has acquired connection for (127.0.0.1)
[Thu May 19 13:16:21.085239 2016] [proxy:debug] [pid 31878:tid 139919615809280] proxy_util.c(2213): [client 10.80.25.72:59915] AH00944: connecting http://127.0.0.1:9000/api/system/cluster/node to 127.0.0.1:9000, referer: https://log.singlemindconsulting.net/api/
[Thu May 19 13:16:21.085287 2016] [proxy:debug] [pid 31878:tid 139919615809280] proxy_util.c(2422): [client 10.80.25.72:59915] AH00947: connected /api/system/cluster/node to 127.0.0.1:9000, referer: https://log.singlemindconsulting.net/api/
[Thu May 19 13:16:21.087710 2016] [proxy:debug] [pid 31878:tid 139919615809280] proxy_util.c(2175): AH00943: http: has released connection for (127.0.0.1)
[Thu May 19 13:16:21.386865 2016] [ssl:debug] [pid 31878:tid 139919607416576] ssl_engine_kernel.c(354): [client 10.80.25.72:59915] AH02034: Subsequent (No.2) HTTPS request received for child 78 (server log.singlemindconsulting.net:443), referer: https://log.singlemindconsulting.net/
[Thu May 19 13:16:21.386951 2016] [authz_core:debug] [pid 31878:tid 139919607416576] mod_authz_core.c(835): [client 10.80.25.72:59915] AH01628: authorization result: granted (no directives), referer: https://log.singlemindconsulting.net/
[Thu May 19 13:16:21.387004 2016] [proxy:debug] [pid 31878:tid 139919607416576] mod_proxy.c(1160): [client 10.80.25.72:59915] AH01143: Running scheme http handler (attempt 0), referer: https://log.singlemindconsulting.net/
[Thu May 19 13:16:21.387030 2016] [proxy:debug] [pid 31878:tid 139919607416576] proxy_util.c(2160): AH00942: HTTP: has acquired connection for (127.0.0.1)
[Thu May 19 13:16:21.387075 2016] [proxy:debug] [pid 31878:tid 139919607416576] proxy_util.c(2213): [client 10.80.25.72:59915] AH00944: connecting http://127.0.0.1:9000/api/system/cluster/node to 127.0.0.1:9000, referer: https://log.singlemindconsulting.net/
[Thu May 19 13:16:21.387138 2016] [proxy:debug] [pid 31878:tid 139919607416576] proxy_util.c(2422): [client 10.80.25.72:59915] AH00947: connected /api/system/cluster/node to 127.0.0.1:9000, referer: https://log.singlemindconsulting.net/
[Thu May 19 13:16:21.388295 2016] [proxy:debug] [pid 31878:tid 139919607416576] proxy_util.c(2175): AH00943: http: has released connection for (127.0.0.1)
[Thu May 19 13:16:26.294952 2016] [ssl:debug] [pid 31878:tid 139919515096832] ssl_engine_io.c(1016): [remote 10.80.25.72:59915] AH02001: Connection closed to child 78 with standard shutdown (server log.singlemindconsulting.net:443)
```

**Comment by moonmeister** [comment]
I FIXED IT!!!

```
        ProxyRequests Off
        <Proxy *>
          Order deny,allow
          Allow from all
        </Proxy>

        ProxyPass /api/ http://127.0.0.1:12900/
        ProxyPassReverse /api/ http://127.0.0.1:12900/

        RequestHeader set X-Graylog-Server-URL "https://log.singlemindconsulting.net/api/"
        ProxyPass / http://127.0.0.1:9000/
        ProxyPassReverse / http://127.0.0.1:9000/
        ProxyPreserveHost On
```

Every url I we to I always ended up back at the homepage...including /api/ this didn't seem right. I'm use to proxying like above and that's what several how to proxy articles indicated. I don't know if the other syntax is outdated or what, but it wasn't working. This syntax works. The documentation for apache needs to be update and include the modules that need to be enabled. Thanks gents.

**Comment by moonmeister** [comment]
this doesn't explain the identical behavior when configuring https in the server.conf. So maybe someone wants to try and figure that out, I don't know if the built in web server is misconfigured or if the settings I was using as posted above were wrong but it needs to be better documented either way.

**Comment by rompic** [comment]
works like a charm. thanks for digging deeper. i had the same observations yesterday but couldn't find a good way to verify them.

**Comment by edmundoa** [comment]
Good to hear that you managed to fix the configuration issue 👍 

@moonmeister: Regarding your issue when not using a proxy, I think it boils down to using a wrong `web_endpoint_uri` in your configuration, making all requests to the REST API go to the web interface instead. [That setting](http://docs.graylog.org/en/2.0/pages/configuring_webif.html#configuration-options) is meant to point to the server, not the web interface: 

>This is the external address of the REST API of the Graylog server. Web interface clients need to be able to connect to this for the web interface to work.

I'm leaving this issue open, I think improving the documentation on this topic would be helpful.

**Comment by jalogisch** [comment]
we update the documentation to be a little more specific in [apache versions](http://docs.graylog.org/en/2.0/pages/configuring_webif.html#apache) - should be clear now

**Comment by f0o** [comment]
I'd like to reopen this issue.

I'm using NGINX as reverse proxy for both Web and REST.

graylog is listening to the default ports on the loopback address of the server and my nginx config is taken from the documentation page of graylog.

I've also added a location block to include /api/ to proxy to port 12900

entire config:
```
server
{
    listen      443 ssl spdy;
    server_name syslog.local;
    ssl_certificate        /etc/nginx/ssl/syslog.local.crt;
    ssl_certificate_key    /etc/nginx/ssl/syslog.local.key;
    ssl_protocols  TLSv1.2;
    ssl_ciphers    HIGH:!aNULL:!MD5;

    location /api/
    {
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    Host $http_host;
        proxy_pass          http://127.0.0.1:12900;
    }
    location /
    {
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    Host $http_host;
        proxy_set_header    X-Graylog-Server-URL https://10.135.0.74/api;
        proxy_pass          http://127.0.0.1:9000;
    }
}
```

I can verify that the response from `https://syslog.local/api/system/sessions` is identical to the response of `http://127.0.0.1:12900/api/system/sessions` on the server itself.

Yet when I attempt to login using the UI it reports a 404. With curl and GET, I get a 200. which curl and POST (empty body) I get a 404.

Any ideas? do I need to strip the `/api/` path off the proxied request?

**Comment by joschi** [comment]
@f0o We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by f0o** [comment]
Fair enough, FYI I solved it by stripping the /api from the backend request. all good now.
