### ISSUE TITLE
Roles not in alphabetical order on LDAP Group Mapping page

### ISSUE THREAD

**Issue by supahgreg** [Graylog2/graylog2-server#2258]
### Problem description

When mapping LDAP groups to roles the roles in the dropdowns/selects are not listed in alphabetical order.
### Steps to reproduce the problem
1. Import "graylog-2.0.1-1.ova"
2. Verify you can log into Graylog after startup
3. Install OpenLDAP and create some users and groups
4. Configure Graylog to use the LDAP server and its users and groups
5. Create four or so new Graylog roles (e.g. "Team {A-D} - Reader")
6. Navigate to "/system/ldap/groups" and the roles listed in the dropdowns for each LDAP group are in no discernible order (e.g. "None", "Team C - Reader", "Team A - Reader", "Admin", etc.).
### Environment
- Graylog Version:  2.0.1  ("graylog-2.0.1-1.ova")
- Elasticsearch Version:  2.3.1
- MongoDB Version:  3.2.5
- Operating System:  Ubuntu 14.04.4 (x86_64)
- Browser version:  Firefox 46

This has also been observed in an Active Directory / Chef-installed environment with the same versions.

**Comment by bernd** [comment]
This is fixed in 4.0. Thank you!
