### ISSUE TITLE
Allow to delete data by query

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#226]
Even though deleting data from indices has a huge negative performance impact due to data fragmentation you sometimes just need to delete some stuff dynamically.

We should have a way to do that without telling the user to query ElasticSearch directly. Let's put it in the system section of the web interface to make sure that this should not be a regular operation. Let the user query something, show the number of message he'd delete and then provide a button to actually delete. Trigger a systemjob with following index optimize.

Note that you might have to temporarily allow writing to already cycled indices in that case.

**Comment by bernd** [comment]
Graylog 1.0.0 has several index retention options. I am closing this issue. Please re-open if this is still needed. Thank you!
