### ISSUE TITLE
Single esxi host shows up as multiple hosts under source

### ISSUE THREAD

**Issue by joemsanchez** [Graylog2/graylog2-server#2265]
### Problem description
Recent installation of graylog.  We have windows servers reporting event logs which is working out nicely.  We wanted to have esxi hosts send syslog messages to graylog as well.  For testing purposes we configured one esxi host to send messages to graylog, but it ends up showing each syslog reporting section of the esxi host as a source.  

### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version: 2.0.0
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Ubuntu 14.04 LTS
* Browser version:

**Comment by hc4** [comment]
As I understand, graylog expects specific syslog format.
Did you configured syslog as described in [docs](https://github.com/Graylog2/graylog-guide-syslog-linux)?

**Comment by joemsanchez** [comment]
I see your point.  I thought it would work a little better out of the box with esxi and syslog.  Its worked great with linux and Cisco so far as well with syslog.  I did find this article as well [syslog-info-from-vmware-hosts-to-graylog-are-not-collecting-correctly](http://serverfault.com/questions/557613/syslog-info-from-vmware-hosts-to-graylog-are-not-collecting-correctly)  Which describes my issue.

**Comment by hc4** [comment]
And in this article written, how to fix ESXi syslog format to meat graylog requirements :)
Actualy they created special log template for graylog. But they also involve some magic with resending by UDP.
```
echo '$template GRAYLOG2,"<%PRI%>1 %timegenerated:::date-rfc3339% %FROMHOST% %syslogtag% - %APP-NAME%: %msg:::drop-last-lf%\n"' | tee /etc/rsyslog.d/32-graylog2.conf
echo '$ActionForwardDefaultTemplate GRAYLOG2' | tee -a  /etc/rsyslog.d/32-graylog2.conf
echo '$PreserveFQDN on' | tee -a  /etc/rsyslog.d/32-graylog2.conf
echo '*.info @localhost:10514' | tee -a  /etc/rsyslog.d/32-graylog2.conf
```

I think this magic with resending is unnecessary.
Just create /etc/rsyslog.d/32-graylog2.conf with single line:
`*.* @@graylog.example.org:514;RSYSLOG_SyslogProtocol23Format`

**Comment by hc4** [comment]
Or you can enable CK_STORE_FULL_MESSAGE option in Syslog input and parse unstructured syslog data with custom pipeline :)

**Comment by hc4** [comment]
It seems the main problem is that ESXi uses syslogd, which have no ability to set message pattern.
So in specified article described solution, which involves resending messages from syslog to rsyslog, which will convert them to apropriate format for graylog.

There is also easier solution: just enable CK_STORE_FULL_MESSAGE in Syslog input and create custom GROK (or regex) extractor for ESXi syslog message format.

**Comment by joschi** [comment]
> There is also easier solution: just enable CK_STORE_FULL_MESSAGE in Syslog input and create custom GROK (or regex) extractor for ESXi syslog message format.

Or use a Plaintext/Raw input in the first place to avoid the overhead of parsing (invalid) syslog messages.
http://docs.graylog.org/en/2.0/pages/extractors.html

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
