### ISSUE TITLE
Integer overflow in metrics.entriesUncommitted?

### ISSUE THREAD

**Issue by rompic** [Graylog2/graylog2-server#2266]
### Problem description

The journal contains **-67,826,402** unprocessed messages in 1 segment
### Steps to reproduce the problem

My graylog was down for a long time. this seems like the metric is overflown though?
### Environment
- Graylog Version: 2.0.1
- Elasticsearch Version: 2.3.3
- MongoDB Version: 3.0.11
- Operating System: ubuntu 14 lts
- Browser version: firefox 46.01

**Comment by bernd** [comment]
This is part of #5868 so I am closing this issue. (see the following comment for an explanation of the negative numer: https://github.com/Graylog2/graylog2-server/issues/5868#issuecomment-522024212)
