### ISSUE TITLE
changing a users roles does not reflect inside user information

### ISSUE THREAD

**Issue by mrfreezer** [Graylog2/graylog2-server#2268]
### Problem description

after changing a users role(s) this does not reflect inside the "user information" pane unless you reload the page.
### Steps to reproduce the problem

edit user
add new role 
update role
(inside "change user role" pane)

observe the not-changing streams and dashboard permissons

this might be "as designed" or a "won't fix" but since i don't know if this is on purpose i thought i would at least mention it ;)
### Environment
- Graylog Version: 2.0.1
- Browser version: google chrome latest version

**Comment by dennisoelkers** [comment]
The idea of the user update dialog is that the single streams/dashboard permission controls are separate from the roles and stream/dashboard permissions which are implicitly granted by assigning a role to a user are not reflected in the single permission controls. I guess what you want is that streams/dashboards a user is permitted to read/edit implicitly through the possession of a role should also show up in the single permission controls.

While I understand that desire, it is currently out of our scope and is some kind of a UI challenge. I am gonna leave the issue open, but move it out of the 2.2 milestone, so it might be implemented in a future version.

**Comment by dennisoelkers** [comment]
I think I was wrong in my last comment. Actually, in current master the form shows the effective accumulated permissions for streams and dashboard gathered through roles in the corresponding controls. Updating the roles also navigates back to the user list, so editing the user again shows the correct, updated information. Closing this issue.
