### ISSUE TITLE
Ability to send Graylog Notifications by email

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2269]
### Description

Just want to get notifications from graylog by email (eg about ES unavailability), to be able to react faster on problem.

**Comment by mikkolehtisalo** [comment]
@hc4 In case you are content with [quick'n'dirty Python script](https://gist.github.com/mikkolehtisalo/18f6b90418a635c9a3c11c3ff3f6706a), .... It's ugly, and meant to be used with cron, and may cause a lot of spam, but it sends you the notifications :cow:

**Comment by jalogisch** [comment]
you should integrate the notification into your monitoring tool. 
the count and content of the notifications is available via API.
