### ISSUE TITLE
RELP input

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#227]
http://en.wikipedia.org/wiki/Reliable_Event_Logging_Protocol

**Comment by hc4** [comment]
The task exist from 2013.
Is there some expectation, when it will be implemented.

**Comment by joschi** [comment]
@hc4 Since RELP isn't too complicated and it's not really a widely used protocol (unfortunately), this should better be implemented as a 3rd party plugin instead of adding it to the Graylog core.

http://docs.graylog.org/en/2.0/pages/plugins.html

**Comment by hc4** [comment]
RELP is default reliable protocol for rsysylog, which is default logging daemon for Ubuntu.
So I think everybody, who uses Ubuntu will benefit from this plugin.
Also there is only FrameDecoder should be implemented, as I understand.

**Comment by joschi** [comment]
@hc4 Feel free to start a 3rd party plugin or ask the maintainer of the old RELP input plugin (https://github.com/h0nIg/graylog2-input-relp) to update the project for Graylog 2.x.

**Comment by florianvolle** [comment]
Exists in marketplace.

**Comment by hc4** [comment]
Can't find RELP input :(

**Comment by lennartkoopmann** [comment]
@hc4 https://github.com/h0nIg/graylog2-input-relp (it looks unmaintained though)

**Comment by hc4** [comment]
I knpw this plugin, but it is not marketplace :)
