### ISSUE TITLE
idea/wish: permit role on saved query

### ISSUE THREAD

**Issue by mrfreezer** [Graylog2/graylog2-server#2270]
back from the days when i was using splunk i remember the posibility to save a query and enable a user to execute this query.

i know about enabling users for streams and for dashboards, first idea i had was adding a textual output of the query to the dashoard, which isn't possible as far as i found out.

solution for now would be creating another stream with the apropriate rights but the other solution might be nicer for certain scenarios (which in this case would be showing a user log-entries from "sftp-internal" for review from a machine he otherwise has no access to)

**Comment by jalogisch** [comment]
the idea: bind saved searches to streams should be possible.

**Comment by bernd** [comment]
Searches can now be shared in the upcoming 4.0.0 release. I think that's the feature request here. If this is not the case, please re-open the issue. Thank you!
