### ISSUE TITLE
Feature request: Specify application.context

### ISSUE THREAD

**Issue by danieljamesscott** [Graylog2/graylog2-server#2271]
As noted in the docs,

> Please take note that the application.context configuration parameter present in Graylog 1.x (and earlier) is not existing anymore. The web interface can currently only be served without a path prefix.

Can this feature be added into V2? We depend heavily on this functionality, and are unlikely to upgrade until it's back.

**Comment by shakalandy** [comment]
We deploy all our internal application via one portal resource (One URL as entry point in a lb/reverse proxy setup) and therefore would like to have a comeback of the "application.context" parameter. In our environment we cannot block the use of the root context for one application.

**Comment by kroepke** [comment]
This will be in 2.1.0
