### ISSUE TITLE
CentOS 7 and 2.0 upgrade

### ISSUE THREAD

**Issue by drsharp42** [Graylog2/graylog2-server#2273]
Upgrade documentation provides sample nginx and apache configuration for 
https for both web and rest url.

http://docs.graylog.org/en/2.0/pages/configuring_webif.html

1: httpd
adding "Listen 443" line to /etc/httpd/conf/http.conf result in 

(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:443

CentOS has "/etc/httpd/conf.d/ssl.conf" file that already contains the "Listen 443" .
Removed "Listen 443" from main httpd.conf; starts ok.

2: SELINUX and httpd
After  successful start of httpd, web interface fails "https://x.x.x.x/api//system/cluster/node"
with status 503.
Checking '/var/log/audit/audit.log" find http process failure to connect to port 12900.

type=AVC msg=audit(1463780364.990:29671): avc:  denied  { name_connect } for  pid=32370 comm="httpd" dest=12900 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:unreserved_port_t:s0 tclass=tcp_socket

Fix with:
          sudo semanage port -a -t http_port_t -p tcp 12900

Web interface now works.

### Environment

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.0.11
* Operating System: CentOS 7.2.1511
* Apache (http) : 2.4.6-40
* Browser version: IE 11 and Chrome

**Comment by mikkolehtisalo** [comment]
SELinux has also a boolean for allowing httpd's network connections:

`sudo /usr/sbin/setsebool -P httpd_can_network_connect 1`

**Comment by joschi** [comment]
Fixed by merging Graylog2/documentation#103.
