### ISSUE TITLE
Need help on 3 node Graylog Cluster

### ISSUE THREAD

**Issue by hasifm2010** [Graylog2/graylog2-server#2274]
Hi All,

Please help me to create a 3 node Graylog cluster. All Instances are running on CentOs 6.5.

Node 1:-

Graylog 2.0.1
Elasticsearch 2.3.1
MongoDB replica Set

Elastic config file:-

cluster.name: graylog2

 discovery.zen.ping.multicast.enabled: false
 discovery.zen.ping.unicast.hosts: ["graylog1.local:9300", "graylog2.local:9300", "graylog3.local:9300"]
 discovery.zen.minimum_master_nodes: 2
 network.host: 192.168.1.128

Graylog config:-

rest_listen_uri = http://0.0.0.0:12900/
web_listen_uri = http://0.0.0.0:9000/
elasticsearch_cluster_name = graylog2
elasticsearch_discovery_zen_ping_unicast_hosts = graylog1.local:9300, graylog2.local:9300, graylog3.local:9300
elasticsearch_discovery_zen_ping_multicast_enabled = false
elasticsearch_network_host = 192.168.1.128
mongodb_uri = mongodb://graylog1.local:27017,graylog2.local:27017,graylog3.local:27017/graylog2

Node 2:-

Graylog 2.0.1
Elasticsearch 2.3.1
MongoDB replica Set

Elastic config:-
cluster.name: graylog2

 discovery.zen.ping.multicast.enabled: false
 discovery.zen.ping.unicast.hosts: ["graylog1.local:9300", "graylog2.local:9300", "graylog3.local:9300"]
 discovery.zen.minimum_master_nodes: 2
 network.host: 192.168.1.129

Graylog config:-

rest_listen_uri = http://0.0.0.0:12900/
web_listen_uri = http://0.0.0.0:9000/
elasticsearch_cluster_name = graylog2
elasticsearch_discovery_zen_ping_unicast_hosts = graylog1.local:9300, graylog2.local:9300, graylog3.local:9300
elasticsearch_discovery_zen_ping_multicast_enabled = false
elasticsearch_network_host = 192.168.1.129
mongodb_uri = mongodb://graylog1.local:27017,graylog2.local:27017,graylog3.local:27017/graylog2

Node 3:-

Graylog 2.0.1
Elasticsearch 2.3.1
MongoDB replica Set

Elasitc config:-
cluster.name: graylog2

 discovery.zen.ping.multicast.enabled: false
 discovery.zen.ping.unicast.hosts: ["graylog1.local:9300", "graylog2.local:9300", "graylog3.local:9300"]
 discovery.zen.minimum_master_nodes: 2
 network.host: 192.168.1.130

Graylog config:-

rest_listen_uri = http://0.0.0.0:12900/
web_listen_uri = http://0.0.0.0:9000/
elasticsearch_cluster_name = graylog2
elasticsearch_discovery_zen_ping_unicast_hosts = graylog1.local:9300, graylog2.local:9300, graylog3.local:9300
elasticsearch_discovery_zen_ping_multicast_enabled = false
elasticsearch_network_host = 192.168.1.130
mongodb_uri = mongodb://graylog1.local:27017,graylog2.local:27017,graylog3.local:27017/graylog2

ES Status when all three nodes are UP.

[root@graylog1 ~]# curl -X GET 'http://192.168.1.130:9200/_cluster/health?pretty=true'
{
  "cluster_name" : "graylog2",
  "status" : "green",
  "timed_out" : false,
  "number_of_nodes" : 6,
  "number_of_data_nodes" : 3,
  "active_primary_shards" : 8,
  "active_shards" : 8,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 0,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 100.0
}

i am trying to create HA cluster, but my problem is, if any one node goes down my elasticsearch status showing RED and throwing below error in log file.

[2016-05-21 07:29:21,165][WARN ][transport.netty          ] [Bi-Beast] exception caught on transport layer [[id: 0x445de109]], closing connection
java.net.NoRouteToHostException: No route to host
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Status when any node goes down:-

[root@graylog1 ~]# curl -X GET 'http://192.168.1.130:9200/_cluster/health?pretty=true'
{
  "cluster_name" : "graylog2",
  "status" : "red",
  "timed_out" : false,
  "number_of_nodes" : 5,
  "number_of_data_nodes" : 2,
  "active_primary_shards" : 5,
  "active_shards" : 5,
  "relocating_shards" : 0,
  "initializing_shards" : 0,
  "unassigned_shards" : 3,
  "delayed_unassigned_shards" : 0,
  "number_of_pending_tasks" : 0,
  "number_of_in_flight_fetch" : 0,
  "task_max_waiting_in_queue_millis" : 0,
  "active_shards_percent_as_number" : 62.5
}

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.1
* MongoDB Version:3.2.6
* Operating System:CentOS 6.5
* Browser version: Chrome 50

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
