### ISSUE TITLE
Do not set "chunked" encoding for 204 responses

### ISSUE THREAD

**Issue by paulbakker** [Graylog2/graylog2-server#2276]
### Problem description
Some responses in the REST API, like `streams/[streamid]/resume` return a 204 response. The `Transfer-Encoding` is set to `chunked` however, which is strange for a 204. This seems harmless, but some HTTP clients really don't like this. For example, see this Vert.x issue: https://github.com/eclipse/vert.x/issues/1433

### Environment

* Graylog Version: 1.3.4

**Comment by kroepke** [comment]
Is this still the case with 2.0? The `netty-jersey` hack wasn't the nicest when it came to HTTP chunking.

**Comment by paulbakker** [comment]
I don't have 2.0 running yet, so can't test that right now. Will migrate soon-ish though.

**Comment by kroepke** [comment]
Thanks, I guess @dennisoelkers can test that easily for now, too.

**Comment by dennisoelkers** [comment]
This is not the case for 2.0. We will probably not do this for 1.3 anymore, so I am closing this issue.
