### ISSUE TITLE
search for surrounding message from a message permalink redirects to streams selection.

### ISSUE THREAD

**Issue by oboukili** [Graylog2/graylog2-server#2279]
### Problem description

Executing a search for "surrounding messages" (any value) redirects to streams selection for non-administrator roles from a message permalink.
### Steps to reproduce the problem

Share a message permalink to another user having access to streams which the message is routed into.
Any non-administrator role searching for surrounding messages is redirected to the streams page (as the permalink doesn't specify which stream it is routed into?).
### Environment
- Graylog Version: 2.0.1
- Elasticsearch Version:  2.3.2
- MongoDB Version: 3.2.6
- Operating System: CentOS 7.2
- Browser version: Firefox 46.0.1

**Comment by kroepke** [comment]
At the moment the only thing we can do is to hide the "surrounding messages" button on that page for non-admin users as we cannot find out which stream the permalink was for in the general case.

**Comment by oboukili** [comment]
Alright, bummers. Thanks for the reply.

**Comment by magixx** [comment]
Any updates on this or a workaround?

**Comment by DuckOfDoom** [comment]
This really frustrated me and a lot of my colleagues until I found this issue. Maybe at lease place a warning near "show surrounding" button in this case?

**Comment by mwysokin** [comment]
Somewhere along the way the issue changed. We're running 2.4.3 and now users see 404 page after clicking the button. Would it be possible to also hide the button for messages viewed using a permalink?

**Comment by AD7six** [comment]
> Any updates on this or a workaround?

I hit this problem every day, my workaround is
* Click surrounding messages
* Press escape as soon as the url changes
* Copy the generated url or search term
* Go look at a stream you have access to and expect to find the message in
* Fudge the url or use the search term

**Comment by schuettec** [comment]
...last action on 21. Jun 2018 :cry:

**Comment by dennisoelkers** [comment]
This has been fixed by hiding the "Show surrounding messages" button.
