### ISSUE TITLE
High CPU Usage in Dashboards

### ISSUE THREAD

**Issue by STRML** [Graylog2/graylog2-server#2281]
### Problem description

CPU Usage in Chrome is roughly 60-80% while idle with just a few chart widgets.

### Steps to reproduce the problem

1. Add a few chart widgets with many datapoints to a dashboard.
2. Profile.

### Environment

* Graylog Version: 2.0.1 (81e0187)
* Operating System: OS X 10.11.4
* Browser version: Chrome 50.0.2661.102 

### Profiles

The following profile was taken shortly after loading. The pattern from 5s onward continues into perpetuity.

![screen shot 2016-05-24 at 3 46 51 pm](https://cloud.githubusercontent.com/assets/1197375/15519457/300e9a42-21c7-11e6-8c45-964c7f73cb33.jpg)
![screen shot 2016-05-24 at 3 47 19 pm](https://cloud.githubusercontent.com/assets/1197375/15519458/3016d400-21c7-11e6-89ca-e0bfc0c450c2.jpg)

[CPU-20160524T154645.cpuprofile.zip](https://github.com/Graylog2/graylog2-server/files/280506/CPU-20160524T154645.cpuprofile.zip)

**Comment by STRML** [comment]
The majority of the usage is a result of the render of https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/components/visualizations/StackedGraphVisualization.jsx, which does not compare props with prevProps. We could probably get a decent boost with `shouldComponentUpdate`, a bit more by checking deep equality of the last `dataPoints` before rendering, and perhaps more by appending only the new bars.

I'm not particularly familiar with c3/d3 in react, but I do see a large number of wrapper components. Perhaps they could do some of that work for us?

**Comment by bernd** [comment]
@STRML Thank you very much for the detailed information! I will move this to the 2.2.0 milestone, we weren't able to work on this for 2.1 unfortunately.

**Comment by edmundoa** [comment]
Actually, let's move it back into 2.1.0. I have found a couple of issues with the update that can at least mitigate the issue.
