### ISSUE TITLE
Unable to edit saved search

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2287]
### Problem description
If I modify search query and click "Update search criteria" - it says that criteria was updated, but actualy nothing happend. And if I click "search" after query modification, Update button disapears, and there is only button "Save" like for first search. And I can't save new query with old name.

### Environment
* Graylog Version:2.0.1

**Comment by hc4** [comment]
something strange just happened to github.
Task was not created, but then it appears to be created.
Closing as duplicate of https://github.com/Graylog2/graylog2-server/issues/2285

**Comment by joschi** [comment]
@hc4 See https://twitter.com/githubstatus/status/735494040939073536
> We're investigating reports of delayed notifications and delayed inbound commit processing.
