### ISSUE TITLE
Cannot reverse proxy Graylog 2.0 web interface to HTTPS

### ISSUE THREAD

**Issue by eroji** [Graylog2/graylog2-server#2293]
### Problem description
I have a 5 server setup with:
- 2 ES data nodes
- 1 Graylog input/collector server that is only handling inputs
- 1 MongoDB server hosting the database backend
- 1 Graylog web interface server that is only hosting the frontend and connecting to collector URI

By default the web interface starts up as HTTP on port 9000, and that connects to the cluster file. I am able to log in and browse around. However, if I try to bind the web interface to 127.0.0.1:9000 on the server then reverse proxy using Apache over HTTPS, it suddenly stops working.

Error message

```
Bad request
Original Request
GET http://10.2.110.36:12900/system/cluster/node
Status code
undefined
Full error message
Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
```

### Steps to reproduce the problem

1. Change "web_listen_uri" to bind to 127.0.0.1
2. Restart Graylog on the web interface server

### Environment

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.2
* Operating System: CentOS 6.7
* Browser version: Chrome 50.0

**Comment by dennisoelkers** [comment]
Can you supply the relevant parts of your reverse proxy config?

**Comment by eroji** [comment]
Sure


```
ProxyPreserveHost On
ProxyPass  /excluded !
ProxyPass / http://127.0.0.1:9000/
ProxyPassReverse / http://127.0.0.1:9000/

<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteCond %{HTTP_HOST} !^mydomain.com$
  RewriteRule ^(.*)$ https://dr-log-viewer.mydomain.com$1 [R=301]
</IfModule>
```

**Comment by dennisoelkers** [comment]
For 2.0 you need to expose the REST port as well. Please see [the docs](http://docs.graylog.org/en/2.0/pages/configuring_webif.html#making-the-web-interface-work-with-load-balancers-proxies) for further information and configuration help. If you still feel there is an error with Graylog and not your config, please reopen the issue.

**Comment by eroji** [comment]
It is open and enabled on both servers.

Input/Collector
`tcp        0      0 :::12900                    :::*                        LISTEN      10102/java`

Web interface
`tcp        0      0 :::12900                    :::*                        LISTEN      1964/java`

In /etc/graylog/server/server.conf for both
`rest_listen_uri = http://0.0.0.0:12900/`
