### ISSUE TITLE
Cannot reverse proxy Graylog 2.0 web interface to HTTPS

### ISSUE THREAD

**Issue by eroji** [Graylog2/graylog2-server#2294]
### Problem description
Would not let me re-open the issue #2293. I do have REST ports open and enabled on both servers.

> It is open and enabled on both servers.
> 
> Input/Collector
> `tcp        0      0 :::12900                    :::*                        LISTEN      10102/java`
> 
> Web interface
> `tcp        0      0 :::12900                    :::*                        LISTEN      1964/java`
> 
> In /etc/graylog/server/server.conf for both
> `rest_listen_uri = http://0.0.0.0:12900/`

I have a 5 server setup with:
- 2 ES data nodes
- 1 Graylog input/collector server that is only handling inputs
- 1 MongoDB server hosting the database backend
- 1 Graylog web interface server that is only hosting the frontend and connecting to collector URI

By default the web interface starts up as HTTP on port 9000, and that connects to the cluster file. I am able to log in and browse around. However, if I try to bind the web interface to 127.0.0.1:9000 on the server then reverse proxy using Apache over HTTPS, it suddenly stops working.

Error message

```
Bad request
Original Request
GET http://10.2.110.36:12900/system/cluster/node
Status code
undefined
Full error message
Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
```

### Steps to reproduce the problem

1. Change "web_listen_uri" to bind to 127.0.0.1
2. Restart Graylog on the web interface server

### Environment

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.2
* Operating System: CentOS 6.7
* Browser version: Chrome 50.0

**Comment by joschi** [comment]
@eroji The issue was closed for a reason.

Please read http://docs.graylog.org/en/2.0/pages/configuring_webif.html very closely and make sure to use HTTP or HTTPS for both, the Graylog REST API and the web interface. Otherwise your web browser will deny requests due to its mixed content policy (see https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content for more information).

**Comment by Berndinox** [comment]
Run into the same issue, are there any examples available on how to enable a reverse proxy setup with SSL Termination. Thanks!

**Comment by joschi** [comment]
@Berndinox http://docs.graylog.org/en/2.1/pages/configuration/https.html

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
