### ISSUE TITLE
Index Range Recalculation job progress does not autorefreshes

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2296]
### Problem description
Index Range Recalculation job progress does not autorefreshes on Overview page (System Jobs part)
Only refreshed after F5.

![image](https://cloud.githubusercontent.com/assets/17475270/15608500/ea73bb58-2422-11e6-9758-c1807b261d75.png)

### Environment
* Graylog Version: 2.0.1

**Comment by hc4** [comment]
Why this issue labeled as improvement?
Autorefresh worked earlier.
It's just broken somewhere during 2.0

**Comment by edmundoa** [comment]
Then you could just say it was working before, and won't be labelled as such. I wasn't even aware of that ;)

**Comment by hc4** [comment]
cool fix :)

**Comment by edmundoa** [comment]
Thank you for all the bug reports!
