### ISSUE TITLE
Add Extractor condition (run don't run) based on other message fields

### ISSUE THREAD

**Issue by bagobones** [Graylog2/graylog2-server#2303]
In many cases I am collecting multiple logs from one server and while I have added fields that indicate which log is from a specific service, the extractor conditions only act on the same field being extracted.

I would love to write a very simple extractor on the message field but only have it run if the logsource field match MySQL or something.

In some cases it can be very difficult to make patterns that don't clobber each other.

**Comment by joschi** [comment]
@bagobones This can be implemented in Graylog 2.0.0 and later using the new message processing pipelines: http://docs.graylog.org/en/2.0/pages/pipelines.html

Please continue this discussion on our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
