### ISSUE TITLE
extractor condition timer not in metrics

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2311]
### Problem description

extractor conditions are not count in the internal metrics.
### code

https://github.com/Graylog2/graylog2-server/blob/c20874ec9dae79ca71794f114df4170d3ecd8292/graylog2-server/src/main/java/org/graylog2/plugin/inputs/Extractor.java#L185-L185

**Comment by joschi** [comment]
Duplicate of #2959.
