### ISSUE TITLE
Output processing is slower than expected

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2313]
### Problem description
Output speed is limited by `output_batch_size*8` messages per second
It is unclear why.

For example my ES node (I use single node) can process up to 6k messages per second.
But if I setup output_batch_size=100 and outputbuffer_processors=4, then I can get only 800 output messages per second.
With output_batch_size=1000 it will output 5-6k messages per second as expected.

### Environment
* Graylog Version: 2.0.2
* Elasticsearch Version: 2.3.3

**Comment by hc4** [comment]
Just checked with 2 processors and 100 queue size - output speed approximately the same (800 msg/s).
So the formula isn't fully correct...

**Comment by joschi** [comment]
@hc4 Yes, the two settings `output_batch_size` (max. number of messages sent to Elasticsearch in a batch) and `outputbuffer_processors` (number of threads working on the output buffer) have direct influence on the throughput of messages to Elasticsearch.

Do you have any specific question about that?

**Comment by hc4** [comment]
why is it capped?
I don't understand why I can't send 10 bulks by 100msg in one second?

Checked with 8 processors and bulkd size =100. Speed remains the same ~800msg/s.
What is bottleneck? ES bulk processing or some graylog internals?

**Comment by dennisoelkers** [comment]
I think you're raising valid questions, @hc4. Could you please supply the following metrics of your Graylog server for the different scenarios:

```
org.graylog2.outputs.BlockingBatchedESOutput.batchSize
org.graylog2.outputs.BlockingBatchedESOutput.bufferFlushes
org.graylog2.outputs.BlockingBatchedESOutput.bufferFlushesRequested
org.graylog2.outputs.BlockingBatchedESOutput.processTime
```

Comparing them would be of great help validating your concerns and possibly improving the throughput.

**Comment by hc4** [comment]
For 100x4:
![image](https://cloud.githubusercontent.com/assets/17475270/15675672/a64a961e-274b-11e6-9966-b52e82707bef.png)

For 2000x4:
![image](https://cloud.githubusercontent.com/assets/17475270/15675790/385ab462-274c-11e6-9481-c7f8d56ad741.png)

In second case actual output speed:
![image](https://cloud.githubusercontent.com/assets/17475270/15675806/4c14d988-274c-11e6-84be-ae91027787b1.png)

**Comment by hc4** [comment]
There is still label `needs-input`.
Should I provide more info?

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
