### ISSUE TITLE
Improve source page performance

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2314]
### Problem description

Sources page shows messages groupped by source.
Field source is defined in ES templae as:

```
          "source" : {
            "analyzer" : "analyzer_keyword",
            "index" : "analyzed",
            "type" : "string"
          },
```

So then aggregation query started, ES generates FieldData for **source** field. The **source** field exists in every message, and so fielddata for it consumes a lot of memory.
Furthermore, ESdefault behaviour is to not limit FieldData cache size. so at some point it will just refuse any aggregation query for analyzed string field.

The problem could be solved by modifing source field template:

```
            "source" : {
                "analyzer" : "analyzer_keyword",
                "index" : "analyzed",
                "type": "string",
                "fields": {
                    "key" : {
                        "type": "string",
                        "index": "not_analyzed"
                    }
                }
            }
```

In that case query for Sources page should be changed to use **source.key** field for aggregation.
More info is available in [ES docs](https://www.elastic.co/guide/en/elasticsearch/guide/current/aggregations-and-analysis.html).
### Environment
- Graylog Version: 2.0.2
- Elasticsearch Version: 2.3.3

**Comment by renapu** [comment]
This would be also very helpfull for all standard analyzed fields from Graylog.

So it is way better in RAM-consumption when we build graphs with the source field.

**Comment by dennisoelkers** [comment]
As this is related to the old sources pages which has been replaced by a dashboard, I am closing this issue.
