### ISSUE TITLE
node id does not allow ec2-instance id

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#2321]
I have configured this node id (/etc/graylog/server/node_id):
i-0bf83885e189a6673

But the web interface shows "i" as the node id. It would be cool if we could use the ec2-instance ids here...

**Comment by joschi** [comment]
The node ID is implicitly a [UUID](https://en.wikipedia.org/wiki/Universally_Unique_Identifier) and it will lead to all sorts of funny errors if it's not in that format (and a valid UUID).

**Comment by runningman84** [comment]
A custom id would be really useful.

**Comment by jalogisch** [comment]
if you leave out the `-`you will be able to use whatever string you like.

but that is not supported and we recommend to only use UUIDs.
