### ISSUE TITLE
Log incoming message size

### ISSUE THREAD

**Issue by eroji** [Graylog2/graylog2-server#2324]
### Problem description
I am trying to log the size of the incoming message size. We are currently using UDP GELF inputs and some of these log messages may be unusually large and I'd like to track that down. ElasticSearch has a plugin called mapper-size which allows indexing of size value of the log messages. However, I cannot find any means of modify the mapping for Graylog.

### Environment

* Graylog Version: 2.0.2
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.2
* Operating System: CentOS 6.7
* Browser version: Chrome 50

**Comment by joschi** [comment]
@eroji You're probably referring to https://www.elastic.co/guide/en/elasticsearch/plugins/2.3/mapper-size-usage.html.

You can use the normal Elasticsearch index templates (https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-templates.html) for adding a custom index mapping (https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-put-mapping.html).

Please continue this discussion on our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
