### ISSUE TITLE
Updating user information of default `admin` user failed

### ISSUE THREAD

**Issue by nartamonov** [Graylog2/graylog2-server#2327]
### Problem description

I have installed Graylog server in docker containers according to [instruction](https://hub.docker.com/r/graylog2/server/). Immediately after installation I logged in with default `admin:admin` credentials and tried to edit profile (`Full name` and `E-mail` fields). Then I clicked `Update user` button and following error occured: `Updating user failed Could not update the user. Please check your logs for more information.`. But there are no any information in logs about this error :-(

### Environment

* Graylog Version: graylog2/server:2.0.2-1
* Elasticsearch Version: elasticsearch:2.3.3
* MongoDB Version: mongo:3.3.6
* Operating System: Debian 8.3
* Browser version: Chrome 50.0.2661.102

**Comment by joschi** [comment]
@nartamonov The admin user can (by definition) not be changed in the web interface. You can change the administrator's email address with the [`root_email`](https://github.com/Graylog2/graylog2-server/blob/master/misc/graylog.conf#L24-L26) configuration setting.

**Comment by nartamonov** [comment]
Ok, thanks! ) Error message are rather unclear in that case.

**Comment by edmundoa** [comment]
The user form for the admin user should not be editable, I'm reopening the issue so we can fix that.

**Comment by edmundoa** [comment]
This got fixed in #2485

**Comment by UlaganathanNamachivayam** [comment]
Hi All,
Is it fixed. we are running a 2.2.X version of graylog & wanted to disable this default Admin user or to modify the Full name in the uer form in UI. Unfortunately couldn't do that. Any help/suggestions will be much appreciated !

**Comment by joschi** [comment]
@UlaganathanNamachivayam The admin user cannot be edited in the web interface and it cannot be disabled.

The only thing you can do is editing the details (username, email, timezone) in the Graylog configuration file.
https://github.com/Graylog2/graylog2-server/blob/9f2c6ef5c1c0f8b77e73d1298d57c7223087eedf/misc/graylog.conf#L57-L74

Please continue this discussion in our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
