### ISSUE TITLE
enable rsync protocol for packages.graylog2.org

### ISSUE THREAD

**Issue by schlitzered** [Graylog2/graylog2-server#2329]
### Problem description
cannot clone the repo via rsync
### Steps to reproduce the problem

1.
rsync rsync://packages.graylog2.org

### Environment

* Graylog Version: *
* Elasticsearch Version: *
* MongoDB Version: *
* Operating System: *
* Browser version: *

**Comment by joschi** [comment]
@schlitzered The package repository is currently backed by Amazon S3 which makes it hard and quite unlikely to ever support rsync or other mechanisms than HTTP(S) for retrieving packages.

**Comment by schlitzered** [comment]
this is bad, i do not like to manually sync those repositories. at some (many) companies it is not allowed for server systems to connect to any resource on the internet, so a private mirror is needed :-/

**Comment by joschi** [comment]
@schlitzered By chance we're currently working on some documentation on how to install Graylog in on an offline system. Stay tuned and subscribe to our [documentation repository](https://github.com/Graylog2/documentation).
