### ISSUE TITLE
documentation: repo not visible in browser

### ISSUE THREAD

**Issue by schlitzered** [Graylog2/graylog2-server#2330]
### Problem description
cannot browse rpm repository https://packages.graylog2.org/repo, which should be possible

other, maybe deprecated, paths are browse able 

### Steps to reproduce the problem

1. visit https://packages.graylog2.org/repo in the browser

### Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@schlitzered Please use https://packages.graylog2.org/ for interactively browsing the package repository.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
