### ISSUE TITLE
Crashed docker server can't restart

### ISSUE THREAD

**Issue by martinheidegger** [Graylog2/graylog2-server#2340]
### Problem description
When the docker container crashes for some reason and you try to restart it, there will still be the /tmp/graylog.pid available and thus prevent the server from restarting.

### Steps to reproduce the problem

1. create a graylog server in a docker environment
2. kill that server
3. restart that server

### Environment

* Graylog Version: Graylog server 2.0.1
* Operating System: Debian GNU/Linux 8 (jessie) (debian)

**Comment by mariussturm** [comment]
Hi,
this commit should fix this https://github.com/Graylog2/graylog2-images/commit/aac16a84974ba0c04d992b979c54cc7657712a57
It's available in the Graylog2/server image version 2.1.0-beta.2-2 and above.
