### ISSUE TITLE
GeoIP plugin does not work on extracted fields

### ISSUE THREAD

**Issue by gallart** [Graylog2/graylog2-server#2341]
### Problem description

No geoip detection done on extracted Ipv4 fields.

### Steps to reproduce the problem

1. Create a "customer_ip" filed with extractor from Beats message.
2. Even if this field is an IPv4 address, geoip detection is not done (field not added).

![image](https://cloud.githubusercontent.com/assets/2728195/15895770/5f4bfec2-2d8d-11e6-8a5f-f95933f47716.png)

### Environment

* Graylog Version: 2.0.2
* Elasticsearch Version: 2.2.0
* MongoDB Version: 2.6.8
* Operating System: Linux
* Browser version: Chrome Latest

**Comment by joschi** [comment]
@gallart Please check (and post) the order of message processors in the web interface at System &rarr; Configurations &rarr; Message Processors Configuration. The processor "GeoIP Resolver" should be last in that list.

**Comment by edmundoa** [comment]
Hi,

This sounds like https://github.com/Graylog2/graylog-plugin-map-widget/issues/8

Please ensure your message processor ordering is right: http://docs.graylog.org/en/2.0/pages/geolocation.html#configure-the-message-processor

Thank you!

**Comment by gallart** [comment]
You are right, moving GeoIP in last position did the trick.

Thanks for feedback, missed this part of documentation.

Gaëtan
