### ISSUE TITLE
Wrong total index count on Indices page

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2359]
### Problem description
![image](https://cloud.githubusercontent.com/assets/17475270/16109788/4f544a20-33b3-11e6-8225-06c559855fb4.png)

Displayed total 195, but should be 146.
And total value increased as Shards count grows on second line.

### Environment

* Graylog Version: 2.0.2
* Elasticsearch Version: 2.3.3

**Comment by joschi** [comment]
@hc4 Please provide the output of `curl 'http://localhost:9200/_cat/indices?v` and a screenshot of the index stats in Graylog taken at the same time.

**Comment by hc4** [comment]
[elastic_cat.txt](https://github.com/Graylog2/graylog2-server/files/318026/elastic_cat.txt)
![image](https://cloud.githubusercontent.com/assets/17475270/16111322/ae74b466-33ba-11e6-8a1c-376dd6f4d171.png)

**Comment by dennisoelkers** [comment]
@hc4 Could you also please provide the output of `curl -u admin:$password http://$graylog:$port/system/indexer/indices\?pretty\=true`?

**Comment by hc4** [comment]
http://elastic:9200/system/indexer/indices?pretty

```
{
  "error" : {
    "root_cause" : [ {
      "type" : "index_not_found_exception",
      "reason" : "no such index",
      "resource.type" : "index_expression",
      "resource.id" : "system",
      "index" : "system"
    } ],
    "type" : "index_not_found_exception",
    "reason" : "no such index",
    "resource.type" : "index_expression",
    "resource.id" : "system",
    "index" : "system"
  },
  "status" : 404
}
```

**Comment by joschi** [comment]
@hc4 You have to run it against the Graylog REST API, not against the Elasticsearch HTTP API.

**Comment by hc4** [comment]
[graylog-rest.txt](https://github.com/Graylog2/graylog2-server/files/318160/graylog-rest.txt)

**Comment by dennisoelkers** [comment]
Thanks! Could you also please supply the response from `/system/indexer/overview`?

**Comment by hc4** [comment]
[overview.txt](https://github.com/Graylog2/graylog2-server/files/318386/overview.txt)
