### ISSUE TITLE
Graylog spawning large amounts of child processes

### ISSUE THREAD

**Issue by fvluijn** [Graylog2/graylog2-server#2363]
Our sysadmin is complaining about memory usage caused by a large number (170) of child processes created by Graylog.

I'm not sure whether this is expected behavior, related to configuration or a problem with terminating child procs.

We're processing a very small amount of messages, avg of 0 messages per minute. Here's a screengrab from htop:

![screenshot from 2016-06-15 15-50-53](https://cloud.githubusercontent.com/assets/3234179/16116246/09f3f700-33cc-11e6-8301-eca41f1f36d2.png)

And the output of /system/threaddump/*node-hash* has a large number of web- and rest-workers in the waiting status:

```
rest-worker-1 id=212 state=WAITING
    - waiting on <0x6da0f126> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    - locked <0x6da0f126> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
    at sun.misc.Unsafe.park(Native Method)
```

Let me know if you require any additional info.

Our setup:
Graylog 2.0.2 (4da1379)
Elasticsearch 2.3.2
Mongo 2.4.9
Java: Oracle Corporation 1.8.0_91 on Linux 3.13.0-76-generic
Ubuntu 14.04.4 LTS

**Comment by joschi** [comment]
@fvluijn Your `htop` is showing threads spawned the Java process running Graylog. That in itself isn't strange, as for example the Graylog REST API and the web interface are spawning 16 threads each by default.

Most of the thread pools in Graylog are tunable, so you can reduce the number of threads being used (if you really need to).

Did you encounter a specific problem or is it just a general feeling that these are "too many threads"?

**Comment by fvluijn** [comment]
@joschi thanks for the response, the specific problem stems from our sysadmin claiming this caused an increase in memory usage, which triggered some alerts. We've noticed a steady increase in memory usage since Graylog went up over the course of a month. Memory usage was increasing steadily for the first 3 weeks, but recently the rate of increase increased, presumably after I added a stream. I've now removed the Stream, seeing if this effects the memory usage in any way.

So to answer your question, a bit of both, increasing memory usage and a lot of threads.

**Comment by joschi** [comment]
@fvluijn Do you have any hard numbers (ideally including some history of those metrics) about the increasing memory consumption? Is the number of threads also increasing?

**Comment by fvluijn** [comment]
This is a graph starting at may 17th when we installed Graylog. The server does host other applications and the 4G is very low (it's our test and dev-machine), but the increasing memory usage (most notable in the swap) is the strange part.

![memory-pinpoint 1463500113 1466037973](https://cloud.githubusercontent.com/assets/3234179/16135028/1b86b1ce-3421-11e6-9cde-40ef7b9060e5.png)

**Comment by fvluijn** [comment]
@joschi and no, there does not seem to be an increase is threads - the number remains the same after a restart of the graylog service.

**Comment by joschi** [comment]
@fvluijn Do you have any stats for the Java process running Graylog? The system memory usage isn't really useful in this case.

Additionally, are you running only Graylog on this machine or also MongoDB and Elasticsearch?

**Comment by joschi** [comment]
Closing because of the original author didn't reply within 2 weeks.

**Comment by Novitoll** [comment]
+1 What is the reason of spamming threads? It leads to OOM GC
