### ISSUE TITLE
Any way to set these fields in graylog-settings.json 

### ISSUE THREAD

**Issue by 123dev** [Graylog2/graylog2-server#2369]
### Problem description
We're using AWS images, and each time we do graylog-ctl reconfigure, we have to go back and edit graylog.conf and elasticsearch.yml to update some of the settings which we don't know if they are possible to predefine in graylog-settings.json

We've already managed to figure out how to set some of the fields.
Looking at https://github.com/Graylog2/omnibus-graylog2/blob/2.0/files/graylog-cookbooks/graylog/attributes/default.rb
For example 
```
  "custom_attributes": {
    "graylog-server": {
      "allow_highlighting": "true",
      "allow_leading_wildcard_searches": "true",
      "rules_file": "/etc/graylog.drl"
    }

```

The ones that we're seeking assistance for are the following

#### in elasticsearch.yml
- node.name
- node.tag
- discovery.zen.ping.unicast.hosts
We find that discovery.zen.ping.unicast.hosts is dynamically picking up running nodes at reconfigure time, however if a node is not running at that time, the values not added.
It would be great if we can set these

#### in graylog.conf
- root_email
- elasticsearch_node_name
- elasticsearch_discovery_zen_ping_unicast_hosts (similar to the above)
- stream_processing_timeout
- stream_processing_max_faults
- Any custom settings used by plugins; Example:

    _dns_resolver_enabled = true_
    _dns_resolver_run_before_extractors = true_
    _dns_resolver_timeout = 2s_

### Steps to reproduce the problem
set any of the above settings
do graylog-ctl reconfigure
the settings are lost
Need to manually fix

### Environment
AWS Image
* Graylog Version: 2.0.2

Thanks in advance

**Comment by jalogisch** [comment]
All Attributes found [here](https://github.com/Graylog2/omnibus-graylog2/blob/1.3/files/graylog-cookbooks/graylog/attributes/default.rb) can be overwritten

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by 123dev** [comment]
Thanks jalogisch

I appreciate your response, and was actually hoping that you would consider this request as a enhancement / feature request.

As you may have noticed, I have already stated in the ticket that we used the reference (actually 2.0 version) you provided as an input to figure out and set all the attributes that we could (shown above).

What we're asking above is about fields that can't be set by using that document as the only reference.

With Graylog-ctl, the graylog.conf, elasticsearch.xml and other settings are auto-generated
It would be great convenience if all fields that are part of that generated document are possibly configurable pre-generation to influence the generated code.

Obviously many are already, and what we listed above are some examples that are not.

Of course if you don't think that this adds value to the product, you can dismiss it.
Thanks for your consideration.

**Comment by mariussturm** [comment]
@123dev if you want to fully customize your installation we recommend to use our Chef cookbook. It's a little bit more work but there are far more attributes configurable. The appliance focus is on ease of installtion and not so much on advanced configuration settings.

**Comment by 123dev** [comment]
Thank you Marius
