### ISSUE TITLE
Problem starting one of the graylog-server nodes

### ISSUE THREAD

**Issue by 123dev** [Graylog2/graylog2-server#2370]
### Problem description
We've upgraded our production system (AWS images) from 1.3.x to 2.0.2
On the primary server the Graylog Server is fully operational 
whereas on the secondary server, the process is running, but it's not writing anything to the logs
and it does not appear in the UI as a node.

On the trouble server
`sudo graylog-ctl status` shows

```
run: elasticsearch: (pid 1036) 480s; run: log: (pid 1032) 480s
run: etcd: (pid 1033) 480s; run: log: (pid 1028) 480s
run: graylog-server: (pid 1029) 480s; run: log: (pid 1024) 480s
run: nginx: (pid 1025) 480s; run: log: (pid 1022) 480s
```

As seen graylog-server is running with pid 1029

But if we check the processes with pid 1029
`ps -elf | grep 1029`
This is what we get

```
0 S root      1029  1018  0  80   0 -  1110 -      21:26 ?        00:00:00 /bin/sh ./run
0 S root      1039  1029  0  80   0 -  2154 -      21:26 ?        00:00:00 timeout 600 bash -c until curl -s http://127.0.0.1:27017; do sleep 1; done
0 S ubuntu    2638  2524  0  80   0 -  2616 pipe_w 21:35 pts/0    00:00:00 grep --color=auto 1029
```
Which clearly is not the graylog-server process

On the primary server where everything is working ok,
`sudo graylog-ctl status` shows

```
run: elasticsearch: (pid 12071) 1318s; run: log: (pid 1037) 333246s
run: etcd: (pid 12090) 1317s; run: log: (pid 1035) 333246s
run: graylog-server: (pid 12125) 1312s; run: log: (pid 1038) 333246s
run: mongodb: (pid 12132) 1311s; run: log: (pid 1036) 333246s
run: nginx: (pid 12134) 1311s; run: log: (pid 1039) 333246s
```

`ps -elf | grep 12125`
This is what we get

```
4 S graylog  12125  1031 28  80   0 - 1169685 -    21:13 ?        00:06:14 /opt/graylog/embedded/jre/bin/java -Xms1g -Xmx1500m -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -jar -Dlog4j.configurationFile=file:///opt/graylog/conf/log4j2.xml -Djava.library.path=/opt/graylog/server/lib/sigar/ -Dgraylog2.installation_source=unknown /opt/graylog/server/graylog.jar server -f /opt/graylog/conf/graylog.conf
0 S ubuntu   17847  1419  0  80   0 -  2615 pipe_w 21:35 pts/1    00:00:00 grep --color=auto 12125
```

Is there an issue with the graylog-ctl script or graylog-runsvdir
If this is not an potential bug, I'll be happy to take it to google discussions.

### Steps to reproduce the problem

Start graylog processes using
`sudo graylog-ctl start`
Node does not appear in UI

sudo graylog-ctl status shows that it is running
yet the process is not

### Environment
AWS Image

* Graylog Version: 2.0.2

Thanks in advance

**Comment by jalogisch** [comment]
Hej @123dev did you check your Logfiles?

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by 123dev** [comment]
Thanks Jan

I will take this to the discussion group.
to answer your question, as mentioned in the ticket.

> but it's not writing anything to the logs and it does not appear in the UI as a node

We're checking graylog-server logs,
Is there a higher level log that shows why graylog-ctl start even though it thinks it started it, failed to start?

**Comment by 123dev** [comment]
As suggested, I took this to the discussion group [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/graylog2/UQVJL0ZidUI/YoCEgE5jCQAJ)

And with Jan's assistance was able to narrow it down to the offending code that is causing the problem.

Even though in graylog.conf we have this setting
`mongodb_uri = mongodb://10.20.1.229:27017/graylog`

The script at
`/opt/graylog/service/graylog-server/run`
is starting the watchdog to localhost mongodb and waiting 10 minutes.

```
#!/bin/sh
exec 2>&1

umask 077

if [ -f "/opt/graylog/embedded/share/graylog/installation-source.sh" ]; then
    . "/opt/graylog/embedded/share/graylog/installation-source.sh"
fi

export JAVA_HOME=/opt/graylog/embedded/jre
export GRAYLOG_SERVER_JAVA_OPTS="-Xms1g -Xmx1500m -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow"

# check if mongodb is up
timeout 600 bash -c "until curl -s http://127.0.0.1:27017; do sleep 1; done"
exec chpst -P -U graylog -u graylog /opt/graylog/embedded/bin/authbind $JAVA_HOME/bin/java $GRAYLOG_SERVER_JAVA_OPTS -jar -Dlog4j.configurationFile=file:///opt/graylog/conf/log4j2.xml -Djava.library.path=/opt/graylog/server/lib/sigar/ -Dgraylog2.installation_source=${GRAYLOG_INSTALLATION_SOURCE:=unknown} /opt/graylog/server/graylog.jar server -f /opt/graylog/conf/graylog.conf

```

Changing 127.0.0.1 to the address of the primary MongoDB fixes the issue.
It would be best if this script used the value defined in graylog.conf to avoid such problems.

Thanks
