### ISSUE TITLE
export extractors does not include order

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2373]
If you export your extractors from _System > Inputs > Extractors of Input > Actions_ this will not include the extractor order.
When you import them on another input they are unsorted and you need to sort them again in the right order. 

### Steps to reproduce the problem

1. export extractors from one input
2. import extractors on other input

### Environment

* Graylog Version: 2.0.2
* Browser version: Safari Version 9.1.1 (11601.6.17)

**Comment by joschi** [comment]
@jalogisch I couldn't reproduce the problem on Graylog 2.1.0-beta.3-SNAPSHOT.

The "order" element of extractors is exported correctly. When importing those extractors into a new input, the order is correct.

Please re-open if the problem still exists in the latest version of Graylog.
