### ISSUE TITLE
json extractor - fields missing and KeySeparator changes

### ISSUE THREAD

**Issue by profhase** [Graylog2/graylog2-server#2375]
### Problem description
When using the json extractor fields with keys that have spaces are not extracted:
    
    {"my key": "bla bla"}

One can see in preview (when clicking on the `try` button on the `create extractor` page), that the field is recognized, but in messages it is not extracted
### Steps to reproduce the problem

1. send this message:

> {"Source" : "Myserver#DS","Observer" : {"Account" : {"Domain" : "MYDOMAIN","Name" : "CN=domain,OU=service,O=org,C=DE"},"Entity" : {"SysAddr" : "123.123.123.123","SysName" : "dir"}},"Initiator" : {"Account" : {"Domain" : "Domain"},"Entity" : {"SysAddr" : "0.0.0.0:0"}},"Target" : {"Data" : {"Attribute Name" : "Purge Vector","Attribute Value" : "Seconds: 1466090058, Replica Number: 3, Event: 1","ClassName" : "Organizational Unit","Syntax" : "19"},"Account" : {"Domain" : "Domain","Name" : "OU=myOrg,O=org,C=DE","Id" : "34621"}},"Action" : {"Event" : {"Id" : "0.0.0.2","Name" : "DISABLE_ACCOUNT","CorrelationID" : "eDirectory#0#6b2c7a3d-a223-19da-85ad-3d7a1c6b82a3","SubEvent" : "DSE_ADD_VALUE"},"Time" : {"Offset" : 1466090106},"Log" : {"Severity" : 7},"Outcome" : "0","ExtendedOutcome" : "0"}}

2. Configure json extractor on that message.
3. In Preview you will see:

> ...
Target_Data_Attribute Name
    Purge Vector

4. Save the extractor and resend this message
5. You will not find the field `Target_Data_Attribute Name` anywhere in fields

### Environment

* Graylog Version: 2.0.1-2
* Elasticsearch Version: 2
* MongoDB Version: 3
* Operating System: graylog2/server:2.0.1-2 Docker container
* Browser version: Firefox 45

**Comment by joschi** [comment]
@profhase I couldn't reproduce your problem and added a unit test for it in 8dbb7d94ccaf09d84d1f77a96a11c18798bc03a7.

**Comment by profhase** [comment]
Thank you so far, I do not know much where the error might be (or what the test checks)

I looked up one example message in the restApi, and posted it below. You will find the json in `message.fields.messageJson` and you will find all the fields from there extracted except for `Target_Data_Attribute Name`
Have you got any idea?


> {

    "message": {
        "fields": {
            "Action_Event_Name": "MODIFY_ROLE",
            "gl2_remote_ip": "xxx.xxx.xxx.xxx",
            "Action_Event_CorrelationID": "eDirectory#0#4d3000df-084e-4e2b-7e9b-df00304d4e08",
            "gl2_remote_port": 43562,
            "source": "xxx.xxx.xxx.xxx",
            "Observer_Account_Domain": "XXX_DIT",
            "gl2_source_input": "57518e564cedfd0001c7fc44",
            "Source": "eDirectory#DS",
            "Target_Data_Syntax": "9",
            "Initiator_Entity_SysAddr": "0.0.0.0:0",
            "Action_Outcome": "0",
            "Initiator_Account_Domain": "XXX_DIT",
            "Target_Data_Name": "OU=ICT,O=XXXXXXX,C=DE",
            "gl2_source_node": "705d12ac-a99b-4dac-a501-ead2e0b109c1",
            "Observer_Account_Name": "CN=dirint,OU=Services,O=XXXXXXX,C=DE",
            "Data_Attribute_Name": "Transitive Vector",
            "Observer_Entity_SysAddr": "xxx.xxx.xxx.xxx",
            "timestamp": "2016-06-17T13:14:47.095Z",
            "Action_ExtendedOutcome": "0",
            "level": -1,
            "streams": [
                "576299ab4cedfd0001f3d89d"
            ],
            "ProductID": "eDirectory",
            "Action_Event_Id": "0.0.8.5",
            "message": "eDirectory: INFO {\"Source\" : \"eDirectory#DS\",\"Observer\" : {\"Account\" : {\"Domain\" : \"XXX_DIT\",\"Name\" : \"CN=dirint,OU=Services,O=XXXXXXX,C=DE\"},\"Entity\" : {\"SysAddr\" : \"xxx.xxx.xxx.xxx\",\"SysName\" : \"dirint\"}},\"Initiator\" : {\"Account\" : {\"Domain\" : \"XXX_DIT\"},\"Entity\" : {\"SysAddr\" : \"0.0.0.0:0\"}},\"Target\" : {\"Data\" : {\"Attribute Name\" : \"Transitive Vector\",\"Attribute Value\" : \"5656521131977342976\",\"ClassName\" : \"Organizational Unit\",\"Name\" : \"OU=ICT,O=XXXXXXX,C=DE\",\"Syntax\" : \"9\"}},\"Action\" : {\"Event\" : {\"Id\" : \"0.0.8.5\",\"Name\" : \"MODIFY_ROLE\",\"CorrelationID\" : \"eDirectory#0#4d3000df-084e-4e2b-7e9b-df00304d4e08\",\"SubEvent\" : \"DSE_ADD_VALUE\"},\"Time\" : {\"Offset\" : 1466169367},\"Log\" : {\"Severity\" : 7},\"Outcome\" : \"0\",\"ExtendedOutcome\" : \"0\"}}",
            "Action_Event_SubEvent": "DSE_ADD_VALUE",
            "Target_Data_ClassName": "Organizational Unit",
            "Observer_Entity_SysName": "dirint",
            "Action_Log_Severity": 7,
            "Action_Time_Offset": 1466169367,
            "_id": "76e23c71-348d-11e6-a99f-0242ac110004",
            "facility": "Unknown",
            "messageJson": "{\"Source\" : \"eDirectory#DS\",\"Observer\" : {\"Account\" : {\"Domain\" : \"XXX_DIT\",\"Name\" : \"CN=dirint,OU=Services,O=XXXXXXX,C=DE\"},\"Entity\" : {\"SysAddr\" : \"xxx.xxx.xxx.xxx\",\"SysName\" : \"dirint\"}},\"Initiator\" : {\"Account\" : {\"Domain\" : \"XXX_DIT\"},\"Entity\" : {\"SysAddr\" : \"0.0.0.0:0\"}},\"Target\" : {\"Data\" : {\"Attribute Name\" : \"Transitive Vector\",\"Attribute Value\" : \"5656521131977342976\",\"ClassName\" : \"Organizational Unit\",\"Name\" : \"OU=ICT,O=XXXXXXX,C=DE\",\"Syntax\" : \"9\"}},\"Action\" : {\"Event\" : {\"Id\" : \"0.0.8.5\",\"Name\" : \"MODIFY_ROLE\",\"CorrelationID\" : \"eDirectory#0#4d3000df-084e-4e2b-7e9b-df00304d4e08\",\"SubEvent\" : \"DSE_ADD_VALUE\"},\"Time\" : {\"Offset\" : 1466169367},\"Log\" : {\"Severity\" : 7},\"Outcome\" : \"0\",\"ExtendedOutcome\" : \"0\"}}"
        },
        "streams": [ ],
        "source_input_id": null,
        "filter_out": false,
        "journal_offset": -9223372036854775808,
        "timestamp": "2016-06-17T13:14:47.095Z",
        "source": "xxx.xxx.xxx.xxx",
        "message": "eDirectory: INFO {\"Source\" : \"eDirectory#DS\",\"Observer\" : {\"Account\" : {\"Domain\" : \"XXX_DIT\",\"Name\" : \"CN=dirint,OU=Services,O=XXXXXXX,C=DE\"},\"Entity\" : {\"SysAddr\" : \"xxx.xxx.xxx.xxx\",\"SysName\" : \"dirint\"}},\"Initiator\" : {\"Account\" : {\"Domain\" : \"XXX_DIT\"},\"Entity\" : {\"SysAddr\" : \"0.0.0.0:0\"}},\"Target\" : {\"Data\" : {\"Attribute Name\" : \"Transitive Vector\",\"Attribute Value\" : \"5656521131977342976\",\"ClassName\" : \"Organizational Unit\",\"Name\" : \"OU=ICT,O=XXXXXXX,C=DE\",\"Syntax\" : \"9\"}},\"Action\" : {\"Event\" : {\"Id\" : \"0.0.8.5\",\"Name\" : \"MODIFY_ROLE\",\"CorrelationID\" : \"eDirectory#0#4d3000df-084e-4e2b-7e9b-df00304d4e08\",\"SubEvent\" : \"DSE_ADD_VALUE\"},\"Time\" : {\"Offset\" : 1466169367},\"Log\" : {\"Severity\" : 7},\"Outcome\" : \"0\",\"ExtendedOutcome\" : \"0\"}}",
        "id": "76e23c71-348d-11e6-a99f-0242ac110004",
        "field_names": [
            "Action_Event_Name",
            "gl2_remote_ip",
            "Action_Event_CorrelationID",
            "gl2_remote_port",
            "source",
            "Observer_Account_Domain",
            "gl2_source_input",
            "Source",
            "Target_Data_Syntax",
            "Initiator_Entity_SysAddr",
            "Action_Outcome",
            "Initiator_Account_Domain",
            "Target_Data_Name",
            "gl2_source_node",
            "Observer_Account_Name",
            "Data_Attribute_Name",
            "Observer_Entity_SysAddr",
            "timestamp",
            "Action_ExtendedOutcome",
            "level",
            "streams",
            "ProductID",
            "Action_Event_Id",
            "message",
            "Action_Event_SubEvent",
            "Target_Data_ClassName",
            "Observer_Entity_SysName",
            "Action_Log_Severity",
            "Action_Time_Offset",
            "_id",
            "facility",
            "messageJson"
        ],
        "complete": true,
        "validation_errors": "",
        "fields_entries": [
            {
                "Action_Event_Name": "MODIFY_ROLE"
            },
            {
                "gl2_remote_ip": "xxx.xxx.xxx.xxx"
            },
            {
                "Action_Event_CorrelationID": "eDirectory#0#4d3000df-084e-4e2b-7e9b-df00304d4e08"
            },
            {
                "gl2_remote_port": 43562
            },
            {
                "source": "xxx.xxx.xxx.xxx"
            },
            {
                "Observer_Account_Domain": "XXX_DIT"
            },
            {
                "gl2_source_input": "57518e564cedfd0001c7fc44"
            },
            {
                "Source": "eDirectory#DS"
            },
            {
                "Target_Data_Syntax": "9"
            },
            {
                "Initiator_Entity_SysAddr": "0.0.0.0:0"
            },
            {
                "Action_Outcome": "0"
            },
            {
                "Initiator_Account_Domain": "XXX_DIT"
            },
            {
                "Target_Data_Name": "OU=ICT,O=XXXXXXX,C=DE"
            },
            {
                "gl2_source_node": "705d12ac-a99b-4dac-a501-ead2e0b109c1"
            },
            {
                "Observer_Account_Name": "CN=dirint,OU=Services,O=XXXXXXX,C=DE"
            },
            {
                "Data_Attribute_Name": "Transitive Vector"
            },
            {
                "Observer_Entity_SysAddr": "xxx.xxx.xxx.xxx"
            },
            {
                "timestamp": "2016-06-17T13:14:47.095Z"
            },
            {
                "Action_ExtendedOutcome": "0"
            },
            {
                "level": -1
            },
            {
                "streams": [
                    "576299ab4cedfd0001f3d89d"
                ]
            },
            {
                "ProductID": "eDirectory"
            },
            {
                "Action_Event_Id": "0.0.8.5"
            },
            {
                "message": "eDirectory: INFO {\"Source\" : \"eDirectory#DS\",\"Observer\" : {\"Account\" : {\"Domain\" : \"XXX_DIT\",\"Name\" : \"CN=dirint,OU=Services,O=XXXXXXX,C=DE\"},\"Entity\" : {\"SysAddr\" : \"xxx.xxx.xxx.xxx\",\"SysName\" : \"dirint\"}},\"Initiator\" : {\"Account\" : {\"Domain\" : \"XXX_DIT\"},\"Entity\" : {\"SysAddr\" : \"0.0.0.0:0\"}},\"Target\" : {\"Data\" : {\"Attribute Name\" : \"Transitive Vector\",\"Attribute Value\" : \"5656521131977342976\",\"ClassName\" : \"Organizational Unit\",\"Name\" : \"OU=ICT,O=XXXXXXX,C=DE\",\"Syntax\" : \"9\"}},\"Action\" : {\"Event\" : {\"Id\" : \"0.0.8.5\",\"Name\" : \"MODIFY_ROLE\",\"CorrelationID\" : \"eDirectory#0#4d3000df-084e-4e2b-7e9b-df00304d4e08\",\"SubEvent\" : \"DSE_ADD_VALUE\"},\"Time\" : {\"Offset\" : 1466169367},\"Log\" : {\"Severity\" : 7},\"Outcome\" : \"0\",\"ExtendedOutcome\" : \"0\"}}"
            },
            {
                "Action_Event_SubEvent": "DSE_ADD_VALUE"
            },
            {
                "Target_Data_ClassName": "Organizational Unit"
            },
            {
                "Observer_Entity_SysName": "dirint"
            },
            {
                "Action_Log_Severity": 7
            },
            {
                "Action_Time_Offset": 1466169367
            },
            {
                "_id": "76e23c71-348d-11e6-a99f-0242ac110004"
            },
            {
                "facility": "Unknown"
            },
            {
                "messageJson": "{\"Source\" : \"eDirectory#DS\",\"Observer\" : {\"Account\" : {\"Domain\" : \"XXX_DIT\",\"Name\" : \"CN=dirint,OU=Services,O=XXXXXXX,C=DE\"},\"Entity\" : {\"SysAddr\" : \"xxx.xxx.xxx.xxx\",\"SysName\" : \"dirint\"}},\"Initiator\" : {\"Account\" : {\"Domain\" : \"XXX_DIT\"},\"Entity\" : {\"SysAddr\" : \"0.0.0.0:0\"}},\"Target\" : {\"Data\" : {\"Attribute Name\" : \"Transitive Vector\",\"Attribute Value\" : \"5656521131977342976\",\"ClassName\" : \"Organizational Unit\",\"Name\" : \"OU=ICT,O=XXXXXXX,C=DE\",\"Syntax\" : \"9\"}},\"Action\" : {\"Event\" : {\"Id\" : \"0.0.8.5\",\"Name\" : \"MODIFY_ROLE\",\"CorrelationID\" : \"eDirectory#0#4d3000df-084e-4e2b-7e9b-df00304d4e08\",\"SubEvent\" : \"DSE_ADD_VALUE\"},\"Time\" : {\"Offset\" : 1466169367},\"Log\" : {\"Severity\" : 7},\"Outcome\" : \"0\",\"ExtendedOutcome\" : \"0\"}}"
            }
        ],
        "field_count": 32,
        "stream_ids": [
            "576299ab4cedfd0001f3d89d"
        ],
        "is_source_inet_address": true,
        "inet_address": "xxx.xxx.xxx.xxx"
    },
    "index": "graylog_0"

}
