### ISSUE TITLE
Graylog2 API HTTP 404 Not Found with Graylog server 2.0.2

### ISSUE THREAD

**Issue by Buzut** [Graylog2/graylog2-server#2376]
### Problem description
The API always return `{"type":"ApiError","message":"HTTP 404 Not Found"}`, I tried with curl:

    $ curl http://10.2.41.205:12900 
    {"type":"ApiError","message":"HTTP 404 Not Found"}

Obviously, when going to the web interface, its says graylog server is unreachable. 

### Steps to reproduce the problem
1. Tried rest listen uri with both `0.0.0.0`, `localhost`, `127.0.0.1`, private and public ips

`rest_listen_uri = http://10.2.41.205:12900/`

Nothing seems wrong in the logs:

    2016-06-17T11:31:26.889Z INFO  [NetworkListener] Started listener bound to [10.2.41.205:12900]
    2016-06-17T11:31:26.890Z INFO  [HttpServer] [HttpServer-1] Started.
    2016-06-17T11:31:26.891Z INFO  [RestApiService] Started REST API at <http://10.2.41.205:12900/>
    2016-06-17T11:31:26.894Z INFO  [ServiceManagerListener] Services are healthy

### Environment

* Graylog Version: 2.0.2
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.2.7
* Operating System: Ubuntu 16.04
* Browser version:

**Comment by dennisoelkers** [comment]
There is no handler for `/`. Try `/api-browser` in your web browser to see which resources the REST API has to offer. The reason why your web interface is not working is probably something else.

**Comment by Buzut** [comment]
All right, thank you for your reactivity!

It was a CORS problem. Anyway, may I suggest that `/` return a HTTP 200 with `status ok` or something like that? It would be more straightforward.
