### ISSUE TITLE
Remove import/export extractors

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#2386]
The import/export extractors functionality has been deprecated for a while now and is still the source of funny errors.

The functionality has been superseded by the content packs since Graylog 0.90.x and should be removed from the codebase.

**Comment by jalogisch** [comment]
when this feature is added, the _content pack_ need to be extended to have _extractors_ as an option too. without this we would loose a well used feature.

**Comment by joschi** [comment]
@jalogisch How often do people really use the import/export extractor feature? There are virtually only content packs on the Graylog Marketplace and no extractors, as far as I see.

**Comment by jalogisch** [comment]
@joschi i notice that people that have a lab use this regular during the setup and build process - when they add new inputs and first stream them to the lab to insert them later in the production environment and have all messages parsed from the very beginning.

**Comment by joschi** [comment]
@jalogisch But that's exactly what content packs are for: Create the configuration (e. g. inputs with extractors) in one Graylog instance, export them in a content pack, import it in another Graylog instance, and apply that content pack to get an identical configuration (e. g. inputs with extractors).

**Comment by jalogisch** [comment]
Just for notice - currently I notice that most ppl use this function to have the same set of extractors on different inputs on the same setup. With the current function of the content packs that kind of work is not possible.

**Comment by STRML** [comment]
We use it as well as a convenient way of synchronizing configurations among multiple nodes, and to just keep our extractor config in version control. Our use case could easily be converted to content packs, it's just not as straightforward. That said, it is rather annoying to use import, as the existing extractors remain so they must be deleted first.

**Comment by bernd** [comment]
Closing this because the new content pack system will be shipped in 3.0.
