### ISSUE TITLE
Disable alerts during a specific timeframe not working

### ISSUE THREAD

**Issue by bobpage2** [Graylog2/graylog2-server#2389]
### Problem description
For one of my streams, I'm trying to disable alerts happening between 4:00:00 and 5:00:00 universal time.

I created this rule:
 timestamp must match regular expression .*([0|1|2|3|6|7|8|9]:..:..\.).*

When I load the specific log message, I get this message:

> This message would not be routed to this stream.

However, when I look at the log message, I can see that it has been routed into the stream. And I do get an email alert.

What am I doing wrong?

### Environment

* Graylog Version:  ova 2.0.2 
* Browser version: firefox 47.0

**Comment by joschi** [comment]
@bobpage2 The `timestamp` field doesn't contain a normal string but a special object with which the regular expression doesn't seem to work.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
