### ISSUE TITLE
Multiple node info is the same

### ISSUE THREAD

**Issue by triggert** [Graylog2/graylog2-server#2390]
### Problem description
The nodes listed in graylog.example.org/system/nodes is populating the same information.

### Steps to reproduce the problem
Basic setup and configuration following doc.graylog.org using apache httpd.

# REST interface
rest_listen_uri = http://127.0.0.1:12900

# Web interface
web_enable = true
web_listen_uri = http://127.0.0.1:9000
web_endpoint_uri = https://servername.example.com:12900

<VirtualHost *:80>
    ServerName graylog.example.org
    ProxyRequests Off
    <Proxy *>
        Order deny,allow
        Allow from all
    </Proxy>
    <Location /api/>
        ProxyPass http://127.0.0.1:12900/
        ProxyPassReverse http://127.0.0.1:12900/
    </Location>
    <Location />
        RequestHeader set X-Graylog-Server-URL "http://graylog.example.org/api/"
        ProxyPass http://127.0.0.1:9000/
        ProxyPassReverse http://127.0.0.1:9000/
    </Location>
</VirtualHost>

### Environment
* Graylog Version: 2.0.3
* Elasticsearch Version: 2.2.0
* MongoDB Version: 3.2.6
* Operating System: RHEL 6.8
* Browser version: Chrome Version 51.0.2704.84 (64-bit)

**Comment by joschi** [comment]
@triggert Make sure that [`rest_transport_uri`](https://github.com/Graylog2/graylog2-server/blob/2.0.3/misc/graylog.conf#L39-L46) is configured to contain the publicly accessible URI of each Graylog node. This URI is being used to query all other nodes in the Graylog cluster and if it has been set to `http://127.0.0.1:12900` (if unset, it's the value of `rest_listen_uri`), the calling node will always only query itself.

**Comment by triggert** [comment]
Added the reset_transport_uri to the server.conf:
`rest_transport_uri = http://sl1spdglp01.spdc.net:80`

The node no longer provides information in the GUI and the server is throwing this error.
2016-06-21 10:57:13,066 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Unable to call http://servername.example.com/system/metrics/multiple on node <d3fd974a-bfcb-4b78-a019-a6e726fcfdf6>, result: Method Not Allowed

**Comment by joschi** [comment]
@triggert The `rest_transport_uri` must be accessible by all the other Graylog nodes in the cluster (especially by the master node).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
