### ISSUE TITLE
StreamRouter interval should be configurable

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#2391]
Hello,

With hundreds of streams and dozens of graylog nodes, mongo load starts to be a (big) problem.
Obviously, this is mainly due to the hits done by StreamRouter every second for getting fresh rules.
As you can see on my Ganglia graph, switching this interval from 1 second to 1 minute saves me a lot of Mongo CPU.

![mongo](https://cloud.githubusercontent.com/assets/11463691/16229257/1b8f5902-37bc-11e6-8957-f3a26196c79e.png)

I'm aware that this is introducing a minute of lag between stream creation and real routing and so probably need an explicit configuration directive in server.conf

**Comment by bernd** [comment]
@pdepaepe We will remove the polling for updates in the upcoming 2.1 release so we do not need options to tweak the interval. See #2496
