### ISSUE TITLE
graylog 2.0.3 footer still shows version 2.0.2

### ISSUE THREAD

**Issue by scottbob09** [Graylog2/graylog2-server#2392]
graylog 2.0.3 footer still shows version 2.0.2

### Steps to reproduce the problem

wget https://packages.graylog2.org/releases/graylog-omnibus/ubuntu/graylog_latest.deb
sudo graylog-ctl stop
sudo dpkg -G -i graylog_latest.deb
sudo graylog-ctl reconfigure

### Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: ?
* MongoDB Version: ?
* Operating System: Linux Ubuntu
* Browser version: firefox

**Comment by joschi** [comment]
@scottbob09 Please empty your browser cache and try again.

Also make sure that you have indeed downloaded the correct version of the Omnibus package: https://packages.graylog2.org/releases/graylog-omnibus/ubuntu/graylog_2.0.3-1_amd64.deb

**Comment by dennisoelkers** [comment]
And please make sure that your Graylog server was properly restarted.

**Comment by dennisoelkers** [comment]
Closing this, as it was not possible to reproduce it.
