### ISSUE TITLE
user preferred timezone not saved

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2393]
### Problem description
if you create a user and set the timezone from UTC to something else and update the user the message "user has updated" was shown in green bar, and it is displayed on the page. 

But after reload or leaving the side it is switched back to UTC

### Steps to reproduce the problem

1. create user
2. set timezone to something other than etc
3. "update user"
4. reload the page

### Environment

* Graylog Version: 2.0.3 (OVA)

**Comment by joschi** [comment]
I can reproduce this neither in Graylog 2.0.3, nor on current `master` (2.1.0-SNAPSHOT).

**Comment by edmundoa** [comment]
It took me a while to reproduce it, apparently it only happens for some time zones in the `etc` section. This is the error message in the server logs:
```
2016-06-21 18:25:48,636 ERROR: org.graylog2.shared.rest.resources.RestResource - Invalid timezone 'Etc/EST', ignoring it for user new.
```

**Comment by joschi** [comment]
The correct one according to http://joda-time.sourceforge.net/timezones.html would be `EST` instead of `Etc/EST`.

**Comment by edmundoa** [comment]
Also regarding https://en.wikipedia.org/wiki/List_of_tz_database_time_zones, currently we store all time-zones that don't belong to an area into Etc.
