### ISSUE TITLE
graylog not able to search for messages with ":"

### ISSUE THREAD

**Issue by ricard0ff** [Graylog2/graylog2-server#2396]
### Problem description
graylog not able to search for messages with ":"
### Steps to reproduce the problem

1. create a message  like the following
"localhost foo-bar: 172.24.23.59 - - [22/Jun/2016:10:33:47 +0000] "DELETE /sds/597"
"localhost foo-bar 172.24.23.59 - - meh"
2. search exactly "foo\-bar\:"
3.  shows both messages, it does not filter the messages as it should

### Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: 2.3.1
* MongoDB Version:
* Operating System: linux 
* Browser version: firefox 45.2.0

**Comment by joschi** [comment]
@ricard0ff There are some characters like `:` which need to be escaped in queries.

Please take a look at http://docs.graylog.org/en/2.0/pages/queries.html#escaping for further details.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by ricard0ff** [comment]
Hey @joschi but yeah i used "foo\-bar\:" still no cigar...

**Comment by joschi** [comment]
@ricard0ff I've added the exact message you've provided in your initial post and had success with the simple query `"foo-bar:"`.

<img width="1415" alt="screenshot" src="https://cloud.githubusercontent.com/assets/43951/16266144/a1091736-3883-11e6-89ac-db34e578f962.png">

**Comment by ricard0ff** [comment]
@joschi okay now look at my use case:
![screen shot 2016-06-22 at 13 46 21](https://cloud.githubusercontent.com/assets/17491850/16267080/e42b42e0-387f-11e6-8f18-738e8ad7a828.png)

**Comment by joschi** [comment]
@ricard0ff That's because of how Lucene analyzes and stores the `message` field, e. g. some stop words and characters are trimmed.

See https://www.elastic.co/guide/en/elasticsearch/reference/2.3/analysis-analyzers.html and https://www.elastic.co/guide/en/elasticsearch/guide/2.x/analysis-intro.html for details and click on "Show terms of message" for the `message` field (next to the magnifying glass).
