### ISSUE TITLE
Snort content pack upload issue.

### ISSUE THREAD

**Issue by Rajeshunix13** [Graylog2/graylog2-server#2398]
### Problem description
HI, 
This is Rajesh, im very new to Graylog, recently we started to deploy Graylog with snort extractor to find NIDS.
but we failed to upload the the snort extractor with help of content packers.

its asking for a file, after press the upload button graylog-web not responding.

can some one assist me to fix the issue, even we tried input/mange extractors but not reflecting in search Fields, i want to use this snort Fields in search.
 
### Steps to reproduce the problem

1. ...

### Environment
Graylog 2.0.3 OVA 
* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by edmundoa** [comment]
Hi Rajesh,

After reading your issue, I still have a doubt: do you have troubles uploading a snort extractor or content pack?

Either way, would you be so kind as to tell us which browser and OS you are using?

Please also include in your issue any errors you may find in your Graylog server logs and browser's developer console while trying to upload the file. If you need more help getting started with your browser's developer tools, this link may help if you use Chrome, but the proceeding is similar in other browsers: https://developers.google.com/web/tools/chrome-devtools/

Thank you!

**Comment by Rajeshunix13** [comment]
Thanks for the reply,  sorry to say i really don't know the difference B/W extractor or content pack.
but my target is have to use snort extractors in search Fields but its not showing.

windows 7/chrome
![image](https://cloud.githubusercontent.com/assets/20088282/16267786/3494a45a-38a9-11e6-9bb0-81293a2f0ed2.png)

![image](https://cloud.githubusercontent.com/assets/20088282/16267813/53c04708-38a9-11e6-9577-3eeafb4dd308.png)

**Comment by edmundoa** [comment]
Content packs were made to make easy to share sets of inputs, streams, dashboards, and extractors. Extractors basically apply to an input, and can be imported/exported only on that input. You can read more about both in the [documentation](http://docs.graylog.org/)

Looking at your second message, it looks like your issue has nothing to do with uploading an extractor or content pack, as you described first, it appears that your extractors are already in place.

Which extractors or content pack did you upload into Graylog? The URL from where you downloaded it would suffice.

**Comment by Rajeshunix13** [comment]
HI Edmundoa,

I have downloaded the snort extractor from https://marketplace.graylog.org/, successfully imported appliance-syslog-udp. as per my understand, All my snort extractors are pointing to system/input-> appliance-syslog-udp ->  manage extractors - > Source field : messages and i  have to use that search -> Fields ->message filter.
am i correct?.  
 
If yes, i want to use separate search -> Fields ->snort_message or snort_ip .. etc , what i have to do.

**Comment by edmundoa** [comment]
So, for what I can understand, this is not really an issue with Graylog, it looks like your messages are not being extracted by the extractors you are using. Therefore I am closing the issue.

A quick search in the marketplace only returned the [snort extractors](https://marketplace.graylog.org/addons/1f17a29d-babf-433d-9caa-b5ec29cb0d6a) content pack, which I guess is the one you are using. You need to understand that most content in the Graylog Marketplace were not created by us, it is content provided by the community.

I would recommend you to try to debug your extractors by looking at what they try to extract from the messages and compare it to the messages you send. You could alternatively ask the author of those extractors for help with your issue, or even write in our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog) to see if anybody can help.
