### ISSUE TITLE
startpage settings not cleaned on stream delete

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#2400]
### Steps to reproduce the problem

1. Create a stream with a admin account
2. Mark it as startpage with a user account
3. Logout user
4. Delete stream
5. Login as user

=> Graylog will redirect indefinitely from home to streams.

Not tested with dashboards.

### Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: 2.2.3

**Comment by edmundoa** [comment]
As a workaround, you can reset the user start page in the user edit page: Users -> Edit -> Reset custom startpage
