### ISSUE TITLE
Consolidate behaviour on modal close / cancel

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#2406]
### Problem description

Looking into https://github.com/Graylog2/graylog2-server/pull/2399, there's a lot of inconsistency in the way we treat data when modals are closed, you can see that in the discussion of that PR we didn't really reach an agreement.

What we should do nevertheless, is to apply it consistently in all components using modals. At the moment most of them reset the data when the modal is closed or cancelled, and all should do that.
### Steps to reproduce the problem
1. Go to the streams page, click on create stream, add a title, close the modal
2. Click on create stream again, the title is gone
3. Go to the dashboards page, click on create dashboard, add a title, close the modal
4. Click on create dashboard again, the title is there
### Environment
- Graylog Version: Graylog 2.0.x

**Comment by linuspahl** [comment]
@edmundoa Can this issue be closed? The modals I had a look at reset their data consistently.

**Comment by edmundoa** [comment]
@linuspahl I don't know, this is ancient. We worked on that at some point, so I guess we can close it, yes. We can always reopen if this is still a problem 👍
