### ISSUE TITLE
Field automapping

### ISSUE THREAD

**Issue by schwatvogel** [Graylog2/graylog2-server#2414]
### Problem description

with Key=value converters Graylog generates field mappings for elasticsearch indices after some time, based on the content of the field over time(guessed), these mappings are not visible or changeable in the gui, so if the content changes type, messages dont get indexed because of parsing exception in elasticsearch

### Steps to reproduce the problem

1. create a copy field extractor
2. use key=value converter
3. send lots of messages into graylog, one field only containing numbers
4. wait for index cycle
5. test mapping:

    curl -s -X GET 'http://elastic01:9200/graylog2_1087/_mapping?pretty'|grep -A1 durat
              "duration" : {
                "type" : "string",
    curl -s -X GET 'http://elastic01:9200/graylog2_1090/_mapping?pretty'|grep -A1 durat
              "duration" : {
                "type" : "long"`

### Environment

* Graylog Version: 2.0.2 (4da1379) 
* Elasticsearch Version: 2.3.3
* MongoDB Version: v3.2.4
* Operating System: Ubuntu 14.04

**Comment by kroepke** [comment]
The per-index mappings are read only. Therefore it's important to convert the fields into their correct data types.

One option is to set index templates to force data types for the known good types: http://docs.graylog.org/en/2.0/pages/configuration/elasticsearch.html#custom-index-mappings

Thanks!

**Comment by schwatvogel** [comment]
Hi,
 thanks for the info. I use the mappings quite a lot, for fields i need to analyze.
The Problem is, that the mapping function in graylog has a quirk:

if you send in mixed data (integers and strings) your field gets mapped to
"String - not analyzed"
if you then have a period where only numerical data is send into the field it gets mapped to "long"
and you're not able to send in strings ever again.

Since you don't recieve a warning about the system failing to index some logline due to casting exceptions, you'll loose loglines.
The only way to find out about them is to analyse the elasticsearch logs.

So maybe when creating the mappings in graylog, taking more indices into account would help

 creating an alert for casting errors,
or a page showing all the mappings (or all the fields with the possibility to self set mappings)
would be great.

btw thanks for the great work

best regards
S
