### ISSUE TITLE
Questions on graylog usage

### ISSUE THREAD

**Issue by prabhakar349** [Graylog2/graylog2-server#2416]
1)Background: Each Microservice expresses it needs of monitoring/alerting on alert thresholds for different kind of Errors that it generates.  So here is the plan how to use graylog
Create a Stream for each of the ErrorId that each microservice can error out.Attach a alerting rule to this stream

**Question**: Is this idea good  as our microservices grow in number so is our ErrorID's  and hence we will end up having few hundreds of streams.  I think this might have impacts from graylog's performance , because it needs to run through all these rules in order to identify the stream it belongs to ?

2) Background: We need have different alert conditions and the existing out of the box conditions might not be enough for us 

Question: With the analysis I have done so far on graylog , there is no easy way to add new alert conditions ? Please correct me if I am wrong?

3)Background: We need high availability log aggregation / alerting tool .

QuestIon: I know we can have a graylog cluster  for high availability , but  right now not sure on how graylog handles of not sending duplicate alertswith multiple instances having the same periodical Alert checks running.

**Comment by kroepke** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like it. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
