### ISSUE TITLE
Unable to delete closed index

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2419]
### Problem description
There is no button Delete for closed index:
![image](https://cloud.githubusercontent.com/assets/17475270/16372325/95964624-3c54-11e6-8f00-a90affcd8e66.png)

Normal index have Delete button:
![image](https://cloud.githubusercontent.com/assets/17475270/16372372/d950919e-3c54-11e6-8ed7-e1a3e1144330.png)

### Environment

* Graylog Version: 2.0.3

**Comment by kroepke** [comment]
Pending investigation why there is no delete button (maybe it cannot be deleted via the API?) I'll put this into 2.1 since it seems like a simple thing.

**Comment by hc4** [comment]
[ES GUI](https://github.com/jettro/elasticsearch-gui) allows to delete closed index.
So it is for sure possible :)

**Comment by hc4** [comment]
This command successfully deleted closed index:
`curl -XDELETE "http://elastic:9200/graylog2_0?pretty"`
