### ISSUE TITLE
tls_key_password of input displayed for all users

### ISSUE THREAD

**Issue by Earest** [Graylog2/graylog2-server#2421]
If you activate tls for input and add a tls_key_password, you can see it when you browse the input page.

1. Create a input with tls password
2. Create a new user without any specific right
3. Now click on the menu "System" > "nodes" 
4. on the new page click on "details" 
5. Scroll down and click on the button "manage input" (in the "Available input types" part)

### Environment

* Graylog Version:2.0.0-6
* Elasticsearch Version: 2.3.2
* MongoDB Version: 2.4.10-5
* Operating System: Debian 8
* Browser version: All

**Comment by dennisoelkers** [comment]
Please update to 2.0.3 and try again, this issue was [fixed already](https://github.com/Graylog2/graylog2-server/commit/2394efc032bd6ea717a481d6474e2dc103cbee69).
