### ISSUE TITLE
Configuring colors for specific data in pie charts and other diagrams

### ISSUE THREAD

**Issue by L3oV1nc3** [Graylog2/graylog2-server#2426]
### Problem description

Want to decide which section gets which color in pie charts and other diagrams like data tables (Quick values)
for example:
ERROR -> red
WARN -> orange
DEBUG -> green
### Environment
- Graylog Version: 2.0.2
- Elasticsearch Version: 2.3.3
- MongoDB Version: 3.2.6
- Operating System: SUSE Enterprise Linux 11 SP3
- Browser version: Chrome 51

**Comment by dennisoelkers** [comment]
Fixed in 79cf5bb366579cb17b1fe438e36c5381f2cb02dc.
