### ISSUE TITLE
Does not work on AWS

### ISSUE THREAD

**Issue by joshua-paddle** [Graylog2/graylog2-server#2427]
### Problem description

I tried setting up graylog myself. It doesn't work. I followed the instructions on the aws installation page. Also not working. I don't know the exact problem, because I can't find any error reports, but I believe what is happening is that graylog is trying the use the same url to query the api via javascript, as it uses from the server. This doesn't work, because AWS assigns a public ip (which javascript should connect to) separately to the private ip (accessible within the vpc). Javascript can only access the public one, the server can only access the private one, but graylog does not appear able to distinguish them, and it seems that it has to be able to do both.

### Steps to reproduce the problem

1. Follow these instructions: http://docs.graylog.org/en/2.0/pages/installation/aws.html

2. Visit the frontend page and try to log in. It does not work, producing one of the following errors, depending on which ip address (public or private) is set in which place:

  a. "We are experiencing problems connecting to the Graylog server"

  b. HTTP 405, POST not allowed

  c. Page freezes, eventually causing the browser to fail due to an infinite loop in the javascript

**Comment by mariussturm** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
