### ISSUE TITLE
Elasticsearch Red cluster state triggered by index rotation under some conditions. 

### ISSUE THREAD

**Issue by jehuty0shift** [Graylog2/graylog2-server#2429]
### Problem description

When a node of the Elasticsearch cluster is down, A simple index rolling can put the cluster in red 

-  One Elasticsearch node is down (on scheduled maintenance for example), so the cluster turns Yellow. Shard reallocation is delayed (with  index.unassigned.node_left.delayed_timeout) since node is expected to return.  
-  The cluster cycle one index so delete a previous one.  
-  The node comes back and import the previous index that is now a dangling index. 
-  The cluster turns to red, unable to retrieve previous shards that have been deleted. 

### Steps to reproduce the problem

To reproduce this problem, so the following 

-   delay re-allocation of shards by using this index setting on the earliest index created : 

`{ "settings" : {"index.unassigned.node_left.delayed_timeout" :  "15m" } }`

-  stop one ES node with some shards of this index on it. 

-  Cycle the index. It will delete the earliest index if max number of index is reached 

-  Restart the ES node, it will import its cluster index, turning the cluster to Red.
 
### Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.2.7
* Operating System: Ubuntu 14.04
* Browser version: Chromium Version 50.0.2661.102 Ubuntu 15.10 (64-bit)

#### Additionnal Informations 

- The setting index.unassigned.node_left.delayed_timeout is very useful when you want to do maintenance on some nodes or in case of temporary failure (It will happen when you have a big ES cluster.), This prevent unneccesary reallocation of replicas, when you know that your node will come back. And If i recall correctly, in ES 2.x the default value is now 1 minute. 
- The real problem is that Elastic removed one setting from ES 2.0  : 
*gateway.local.auto_import_dangled*
Now all the indices are forcefullty imported (see this issue [https://github.com/elastic/elasticsearch/pull/10016](https://github.com/elastic/elasticsearch/pull/10016)). 

- The issue could be mitigated by implementing this feature:  #2371 and by alerting the administrators of the real state of the cluster.

**Comment by kroepke** [comment]
This sounds very reasonable to me and the first glance looks like it should be relatively easy to implement.
Scheduling for 2.1.

**Comment by bernd** [comment]
This has been implemented in #2477 and will be part of the upcoming Graylog 2.1. Thank you for the report!
