### ISSUE TITLE
Output buffer dont read from input buffer (Process buffer)

### ISSUE THREAD

**Issue by romotta** [Graylog2/graylog2-server#2431]
Hi,

im using Graylog with 2 server, the multi-vm-setup on amazon(ec2), one is configured as 

`sudo graylog-ctl reconfigure-as-server`

and the other as

`sudo graylog-ctl reconfigure-as-datanode`

at the first it was working normally, but some hours late the Process buffer begins to fill and never empty (Output buffer).

print: https://ctrlv.cz/p1B4

The problem is with the amazon? i need to configure something else?

Thanks!

**Comment by mariussturm** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
