### ISSUE TITLE
suppress alerts based on uniq identifier

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2432]
today it is only possible to suppress alarm over time. it should be possible to have a uniq identifier to suppress alerts.

if you have a large amount of devices sending information and you have an alarm activated it is not useful if you can't fix the reason in the time until the next message arrives.

giving the example of a network switch that send every 30 sec heartbeat with the status. If a switch fails it will send every 30 second "not ok, hardware failure" and trigger the alarm message. if you suppress the alarm by time you will not get noticed if the same failure happen to another switch until the time of suppress is over.

**Comment by mazhead** [comment]
This could be still useful in 2020, any ideas on that?

**Comment by bernd** [comment]
This is possible with the new events and alerts system by using an aggregation and group by field. In the switch use case above, you would group by the source. A configured grace period will always take the group key into account. That means if switch A is sending errors every few seconds, the grace period will make sure to not send tons of notifications. When switch B is also starting to send errors, it's not affected by the grace period of switch A.
