### ISSUE TITLE
Web plugin clarification

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#2439]
Hello,

I just followed your web plugin documentation: http://docs.graylog.org/en/2.0/pages/plugins.html and i have two remarks about it.

**graylog-server install**

> In this file you can customize some of the parameters of the build. There is one mandatory parameter named web_src_path which defines the absolute or relative location to a checkout of the Graylog source repository.

A checkout is not enough. You also need to build graylog-server at least once, because the plugin package.json will not be able to compile unavailable resources.

> [INFO] ERROR in ../graylog2-server/graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx
> [INFO] Module not found: Error: Cannot resolve module 'react' in /xxx/graylog2-server/graylog2-web-interface/src/components/bootstrap

**graylog-project dependency**

About 

> git clone git@github.com:Graylog2/graylog-project.git

It currently also pull (for a not very clear reason) **graylog-plugin-anonymous-usage-statistics** on bootstrap.
Problem: on first mvn clean package of your fresh plugin, it stuck until your remove 
https://github.com/Graylog2/graylog-project/blob/master/pom.xml#L24

**Comment by jalogisch** [comment]
@pdepaepe we have improvements on our todo list - this will be addressed after our next release.

**Comment by bernd** [comment]
We improved the plugin documentation for the upcoming 2.2 release. Closing this.
