### ISSUE TITLE
import extractors fail

### ISSUE THREAD

**Issue by wuweiliang1** [Graylog2/graylog2-server#2442]
Hello,
     I try to import a custom extractor via import extractors link in inputs-manage extractors page. However when I submit the json code, nothing happened. I open the console and received a message as follow:
```
16:04:50.173 TypeError: extractors is undefined
_import() plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.db131ceb5a3c95f59b0d.js:27811
_import() self-hosted:753
__vendor</e.exports.listen/n() vendor.js:415
__vendor</r.prototype.emit() vendor.js:409
__vendor</e.exports.trigger() vendor.js:415
__vendor</e.exports.triggerAsync/<() vendor.js:415
__vendor</</t.setImmediate</<() vendor.js:408
__vendor</r.prototype.run() vendor.js:405
o() vendor.js:405
1 plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.db131ceb5a3c95f59b0d.js:27811:6
```

### Steps to reproduce the problem

1. click System/inputs----Inputs, choose one inputs and click Manage extractos
2. click Actions----- Import extractors
3. submit arbitrary content, you will receive a TypeError message.

### Environment
(the vmware ova distribution)
* Graylog Version:2.0.0-rc.1 (f098ffa) 
* Elasticsearch Version:2.3.1
* MongoDB Version:
* Operating System:Windows 7
* Browser version: Firefox 46.0.1, Chrome 49.0.2623.110 m

Any suggestion will be appreciated!
[content_pack.json.txt](https://github.com/Graylog2/graylog2-server/files/343127/content_pack.json.txt)

**Comment by joschi** [comment]
@wuweiliang1 Please attach the file you're trying to upload.

Additionally please upgrade to the latest stable version of Graylog (version 2.0.3 at the time of writing) to rule out any bugs that have been fixed since the release Graylog 2.0.0-rc.1.

**Comment by wuweiliang1** [comment]
@joschi  Thank you for your attention.
I have attached the file now. I follow the upgrade instruction in your provided document. It seems that the above link does not correctly redirect to the latest version of graylog (in my case, i got graylog of version 2.0.0-2)
Any guidance for upgrading graylog via tgz file?

**Comment by joschi** [comment]
@wuweiliang1 I've just verified that https://packages.graylog2.org/releases/graylog-omnibus/ubuntu/graylog_latest.deb does indeed deliver the latest stable version of the omnibus package. Make sure that no (transparent) proxy server is interfering with your downloads.

Additionally the file you've attached is a content pack and not an extractor definition. You need to import and apply the content pack on the System &rarr; Content Packs page.
