### ISSUE TITLE
LDAP Group Mapping is truncated when you have too many LDAP groups

### ISSUE THREAD

**Issue by mayrstefan** [Graylog2/graylog2-server#2455]
### Problem description

We have too many LDAP groups (flat OU with 2000+ groups). When we want to use the LDAP Group Mapping page the list overflows the page. You cannot reach all groups and most of the groups have no mapping.
### Suggestion

As we will have way less Group Mappings than LDAP Groups it would be more comfortable if we had the list of all configured mappings and a button to add a new mapping. It could show a drop down list of available LDAP groups as it exists for the roles they are mapped to. That would be consistent with many other dialogs where we can find an add button, too.
### Environment
- Graylog Version: 2.0.1
- Elasticsearch Version: 2.3.2
- MongoDB Version: 3.2.6
- Operating System: SLES11 SP4
- Browser version: FF 46

**Comment by coffee-squirrel** [comment]
I do agree the "LDAP Group Mapping" page could use a bit of attention.

Would filtering the groups be an option?  For example, we set "Group Search Pattern" to something like:

`(&(objectClass=group)(|(cn=Group Name Explicit)(cn=Some Common Prefix - *)))`

This results in only group "Group Name Explicit" and any group with "Some Common Prefix - " as a prefix appearing in Graylog.

**Comment by mayrstefan** [comment]
Using a filter and group names with a defined prefix is already in place as a workaround. At the moment this requires us to duplicate some groups to match the filter.

**Comment by jeefy** [comment]
Couple thoughts since I'm dealing with similar trouble with too many LDAP groups (over a thousand)

1) Would be nice to do the inverse and assign LDAP groups to Roles (through the role view)
2) It'd be cool to create 1:1 mappings between a Graylog Role and an LDAP Group.

**Comment by bernd** [comment]
Group mapping works differently now in 4.0 so this is no longer an issue.

See the following links for more details:

- Announcement: https://www.graylog.org/post/announcing-graylog-v4-0
- Upgrade notes: https://docs.graylog.org/en/4.0/pages/upgrade/graylog-4.0.html
- Background information regarding group changes: https://github.com/Graylog2/graylog2-server/issues/9392#issuecomment-733892973
