### ISSUE TITLE
Improve a role configuration

### ISSUE THREAD

**Issue by ochanism** [Graylog2/graylog2-server#2458]
### Problem description

I need to create an account with a restricted write role.
To put into perspective, I want to provide an account for someone, who can create dashboard for a specific input, but cannot access system menu.
Currently, Graylog does not support this feature.
### Environment
- Graylog Version: graylog 2.0

**Comment by bernd** [comment]
This should work with the sharing feature in the upcoming Graylog 4.0.0 release. To make this work, the messages from that specific input must be routed into a separate stream. An admin can then share the stream with a user and also assign the "Dashboard Creator" role to that user.
