### ISSUE TITLE
reverse quick values/Bottom-N

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2459]
### Problem description

if you look into your data with quick values ( http://docs.graylog.org/en/2.0/pages/queries.html#quick-values ) you only get the top values.

it would be very useful to get the bottom as an option ( lowest count in given time ) and output them as list.

**Comment by kroepke** [comment]
Essentially we need to expose the order parameter of the terms aggregation to support ascending and descending sorting.

**Comment by GambitK** [comment]
Yes, ordering ascending and descending would also help in searching for rare occurrences of events.

**Comment by lennartkoopmann** [comment]
This will be handled in #4082,
