### ISSUE TITLE
Can't configure server behind firewall with port forwarding and TLS

### ISSUE THREAD

**Issue by PaulDMendoza** [Graylog2/graylog2-server#2463]
@joschi I realize now why I'm stuck but still not sure how to proceed. From my other bug about TLS I'm now stuck at this part.

My server isn't directly exposed to the internet. I'm using port forwarding to forward the request to the server. The IP address of the server is X but the external IP address is actually Y. When I configure the IP address X which is the internal IP, I can get to the web server but the web application thinks it should be hitting X:12900 instead of Y:12900 or better yet it should really try to be hitting mydomain.com.

Any ideas on how to solve this?

**Comment by PaulDMendoza** [comment]
I figured it out. I had to put the URL in one of the fields and the IP addresses in the listen URLs.

**Comment by joschi** [comment]
@PaulDMendoza We are using GitHub issues for tracking bugs in Graylog itself. Please post such issues to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
