### ISSUE TITLE
frontend: design breaks if choosing more fields (on search) than fits to browser

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2464]
### Problem description

If you choose for example **show all fields** in the search and the fields did not fit into your current browser width the design is broken and no horizontal scrollbars are present. 

This should be handled better to improve the usability. Additional it does confuse users.

### Steps to reproduce the problem

1. Go to the Search Page
2. resize your Browser Window
3. Choose "show all fields"

### Environment

* Graylog Version: 2.xx

**Comment by edmundoa** [comment]
@jalogisch I am not exactly sure what is broken, the sidebar seems to be working fine for me when selecting all fields. Could you please add which browser you use, and also some screenshots of the problem?

Thank you!

**Comment by syprisgraylog** [comment]
@edmundoa I have attached a screen shot below using the newest version of Chrome. This is also a problem in Internet Explorer and newest version of Firefox. Any ideas?
![image](https://cloud.githubusercontent.com/assets/20243400/16653999/c0ed0ab8-4421-11e6-9086-622ad451c413.png)

**Comment by edmundoa** [comment]
@syprisgraylog Thank you for the details! That is not what I was looking for in the first place, and I can confirm it happens when many fields are selected in the sidebar.

**Comment by syprisgraylog** [comment]
@edmundoa  Thank you for taking the time to look at the post. :) I wasn't sure if this was happening only to us or not. Is this a bug or too early to tell?

**Comment by edmundoa** [comment]
@syprisgraylog Yes, I would say it's a bug, specially since you can't reach fields on the right. Do you need to have so many fields in the table, by the way? :)

**Comment by syprisgraylog** [comment]
@edmundoa When we first starting messing with Graylog, we were interested in what information was in all the fields. That is when we found the bug. The workaround was just exporting to CSV. It isn't serious, just annoying, haha.

Thanks for the confirmation!
