### ISSUE TITLE
Multiline support for Grok extractor

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#2465]
The Grok extractor currently only supports single line matches which makes it hard to match log messages containing stack traces or other multiline content.

Logstash's implementation of Grok supports multiline matches by using the `(?m)` modifier in the pattern, but Graylog's Grok implementation doesn't.

**Comment by pramodanarase** [comment]
+1

**Comment by alex48151623** [comment]
+1

**Comment by areynolds77** [comment]
This also affects the pipeline grok function.

**Comment by Nemchin** [comment]
I use different modifier **(?s)** in my pipeline functions to handle multi-line messages. It works well on 2.1.2.

**Comment by areynolds77** [comment]
That works perfectly, thanks @Nemchin!

**Comment by EvertMDC** [comment]
(?s) does not seem to work in the extractors.
There does not seem to be a lot of momentum to close this, which I find curious. May I know an estimation of when this will be fixed?

I would have assumed that any enterprise using Java will run into this. Or is it a better practice to use the pipelines?

**Comment by joschi** [comment]
@EvertMDC There are GELF appenders for virtually every Java logging framework which can be used to send log messages including multiline stack traces directly to Graylog, so there's no need to read these messages line-by-line from a file and merge them again at a later point.

**Comment by aliasmee** [comment]
+1

**Comment by danvaida** [comment]
I agree with @EvertMDC, this should definitely **not** be the concern of the application.
It'd be nice to have GELF supporting this natively.

**Comment by rcny** [comment]
Same problem as above. Is there any workaround for the Grok extractor or right now the only solution is to use pipelines for the extraction?

**Comment by afaqbabar** [comment]
Hi all, I want to extract fields from modsecurity audit log, which is multiline log with sections A,B,..Z. I can merge multiline messages of a single event using multiline feature in Graylog input. 
How can I extract fields of all sections of a single event of a modsecurity log?

**Comment by jayakumar-ml** [comment]
+1

**Comment by matiza5** [comment]
+1

**Comment by alexandervasylev** [comment]
+1

**Comment by jmacku** [comment]
+1

**Comment by albertMkhitaryan** [comment]
+1

**Comment by jzandbergen** [comment]
+1

**Comment by pericajakimov-sng** [comment]
+1

**Comment by xtruthx** [comment]
Dear Graylog Team,

it would be nice if this could be find a way into graylog.

Thx

**Comment by patrickmann** [comment]
`(?m)` works fine for me in a Grok extractor. Below is the Grok pattern definition in the extractor; and a message showing the successfully extracted field `atest`.
As a sanity check I removed the `(?m)`. This causes the extractor to fail, as expected.

Am I missing something?

![image](https://user-images.githubusercontent.com/12073930/218713645-a7f28783-664c-47de-a229-2da3df79675e.png)

![image](https://user-images.githubusercontent.com/12073930/218712793-42f83f4f-da2b-47e4-b2a2-923c13c99813.png)

**Comment by patrickmann** [comment]
Works as expected and last comment was 3 years ago.

**Comment by patrickmann** [comment]
Works as expected and last comment was 3 years ago.
