### ISSUE TITLE
No way to configure the Graylog Collector Sidecar to use TLS

### ISSUE THREAD

**Issue by PaulDMendoza** [Graylog2/graylog2-server#2467]
### Problem description
I can configure an Gelf TCP Input with TLS but I can't configure the Sidecar through the web application to send log entries using TLS encryption. Is this going to be supported in Graylog 2.1? 

### Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: Whatever version came with 2.0.3
* MongoDB Version: Whatever version came with 2.0.3
* Operating System: Ubuntu 16.04

**Comment by mariussturm** [comment]
Yes, the next release will support TCP/TLS outputs for nxlog collectors.
