### ISSUE TITLE
No way to install Elasticsearch plugins

### ISSUE THREAD

**Issue by tehdeadone** [Graylog2/graylog2-server#2473]
### Problem description

No way to install Elasticsearch plugins. The [documentation ](http://docs.graylog.org/en/2.0/pages/configuration/graylog_ctl.html#install-elasticsearch-plugins) says there is, but "elasticsearch/bin/plugin" is not part of graylog2 installs/tarballs.

### Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: 2.3.2

**Comment by mariussturm** [comment]
Your are referring to the documentation for the Graylog appliances, please keep in mind that a manual tar-ball installation has different directory structures. When you setup Elasticsearch by hand there should also be the `plugin` program for doing the same, maybe in a different directory.

**Comment by tehdeadone** [comment]
To give more context to my issue, I'm trying to install a plugin into the embedded Elasticsearch client in Graylog, so I can get it to connect to my existing Elasticsearch cluster.

Installing plugins into a normal Elasticsearch instance is well documented in Elasticsearch documentation.

**Comment by kroepke** [comment]
@tehdeadone In case you are trying to load elastic's commercial plugins, please be aware that this is currently impossible due to changes by elastic in how they load plugins.
Also see https://github.com/Graylog2/graylog2-server/issues/2167 and https://github.com/Graylog2/documentation/commit/8f72337005cc366e47333ba3ef1c323c775fc77f

**Comment by kroepke** [comment]
Alternatively you can set the graylog config option in graylog.conf:

elasticsearch_config_file = /etc/graylog/server/elasticsearch.yml

This file is then used to configure the internal client node. However, plugin loading has changed in elasticsearch 2.x to check for duplicate classes, which basically prevents loading JVM plugins into client nodes. There's currently no easy fix for this on our side.

**Comment by tehdeadone** [comment]
@kroepke I did try that approach (Re: elasticsearch_config_file), and it didn't work. 

It's not a commercial plugin I'm trying to install. I've built a ES cluster on top of kubernetes, using a kubernetes cloud plugin. Inferring from your answer, I guess what I'm trying to do is not really possible.
