### ISSUE TITLE
make geo ip settings editable via config / api

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2474]
### Problem description

Build and run Graylog full automated is not possible because the Geo IP Plugin can not be configured via API or config file.

Make the settings available would solve some pain during the setup (no need for insert the values into mongodb direct)

### Environment

* Graylog Version: 2.x

**Comment by joschi** [comment]
@jalogisch AFAIK the Map Widget plugin is configurable via ClusterConfig: [`GeoIpResolverConfig`](https://github.com/Graylog2/graylog-plugin-map-widget/blob/1.0.3/src/main/java/org/graylog/plugins/map/config/GeoIpResolverConfig.java)

**Comment by jalogisch** [comment]
you are right - using the following call you can enable/disable the Plugin and set the Database Path

```bash
curl -u admin:admin -H "Content-Type: application/json" -XPUT 'http://localhost:12900/system/cluster_config/org.graylog.plugins.map.config.GeoIpResolverConfig' -d '{
  "enabled": true,
  "db_type": "MAXMIND_CITY",
  "db_path": "/opt/graylog/conf/geo/GeoLite2-City.mmdb"
}'
```
