### ISSUE TITLE
search result highlighting color similar to white

### ISSUE THREAD

**Issue by davengyn** [Graylog2/graylog2-server#2480]
Hello, 

i got a problem with the "search result highlighting".
The parameter was set to true in 
`/etc/graylog/server/server.conf 
`
And it works! But the highlighting color (#fffcb0) is similar to the background color(#ffffff). I wanted to solve this problem by editing a css file graylog.less

`.result-highlight-colored 
{
  background-color: #fffcb0;
}`

but since i use Graylog2 the webinterface was implement as an module...
I can't find file graylog.less in my server.

I mark this as an issue, because barely seeable highlighting is not useful.

### Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: 2.3.4
* MongoDB Version: 3.2
* Operating System: CentOS-7-x86_64
* Browser version: Chrome 51.0.2704.103 (64-bit)

**Comment by edmundoa** [comment]
Hi,

Thank you for creating this issue!

This is a very subjective matter, but I agree it is not too visible. There should be a compromise between highlight and annoyance. And it should still be easy to read.

I have been playing a bit with it and I think `#ffec3d` could be a better colour for it. What do you think about it? Here is a comparison of both highlight colours:
![highlight](https://cloud.githubusercontent.com/assets/716185/16845726/3d5499ae-49ea-11e6-8df6-bcba008ee886.png)

**Comment by davengyn** [comment]
Hi, thanks for your response

i thought about using `fffb03` for highlighting, it's very similar to`#ffec3d`!
As long as it's more "highlighting" it would be a improvement.

Is there someway to change it by myself?

**Comment by edmundoa** [comment]
Nice, I will make the change and it will be available on 2.1.

I'm afraid that applying the change to your local environment is not that easy: you would need to checkout the code, modify the less file, and build the project.
