### ISSUE TITLE
Display of absolute start and end datetimes for indices

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#2486]
### Problem description
When viewing the Indices page ("/system/indices") I occasionally want to see the specific date+time range a given index contains.  Currently we have a relative statement like "Contains messages from 5 days ago up to 3 days ago" or "Contains messages from a month ago up to a month ago" ([graylog2-web-interface/src/components/indices/IndexSummary.jsx#L58](https://github.com/Graylog2/graylog2-server/blob/907025cf3ae4e26143ccdb78aa6ce0ed07eda49e/graylog2-web-interface/src/components/indices/IndexSummary.jsx#L58)).  It would be handy to have the true start and end values as alternate/title text.

### Environment
* Graylog Version: 2.0.3
* Elasticsearch Version:  2.2.0
* MongoDB Version:  2.6.12
* Operating System:  Red Hat Enterprise Linux Server release 6.7
* Browser version:  Firefox 47

**Comment by kroepke** [comment]
closing, #2549 has a PR attached.

Thanks for reporting this!
