### ISSUE TITLE
Alert Receivers section not visible to non-admin

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#2502]
### Problem description

We delegate configuration of stream alerts to other teams, granting `Allow reading` and `Allow editing` to various streams via roles associated with LDAP groups.  For these non-admin users the "Receivers" section of the Alerts configuration page is not visible in the Web UI.

Please note that this is occurring in both 2.0.3 and 2.1.0-alpha.2+e565536 (the latter tested via "graylog-pre-2.1.0-alpha.2-1.ova").  This may be somewhat related to #2352 and #2353 .
### Steps to reproduce the problem
1. Log in to a Graylog environment as an admin
2. Ensure there are streams defined
3. Pick a stream `Foo Stream` and add an alert with an e-mail callback, specifying usernames and/or e-mail addresses
4. Create a user `bob` in Graylog
5. Create a role `Stream Editor` that has `Allow reading` and `Allow editing` on `Foo Stream`
6. Associate user `bob` with role `Stream Editor`
7. Open a clean browser session and log in as `bob`
8. Note that `bob` can see `Foo Stream`
9. Click `Manage Alerts` for `Foo Stream`
10. Note that the `Receivers` section does not appear at all
11. Note `bob` has access to the alert receiver info via http://1.2.3.4:12900/streams/foo_stream_guid_here
### Environment
- Graylog Version: 2.0.3 and 2.1.0-alpha.2+e565536
- Elasticsearch Version:  2.2.0
- MongoDB Version:  2.6.12
- Operating System:  Red Hat Enterprise Linux Server release 6.7
- Browser version:  Firefox 47, Chrome 51.0.2704.106m

**Comment by bernd** [comment]
The problem here is that the `Receivers` UI component requires the `users:list` permission to build the auto-complete list for the user receivers.

This is nothing we can change for 2.1 unfortunately, removing it from the milestone.

**Comment by coffee-squirrel** [comment]
@bernd So under 2.0.x and 2.1.x the options are for the "editor" to view and modify alert receivers through the REST API or an admin to act as a go-between?

**Comment by bernd** [comment]
@coffee-squirrel Yes, unfortunately. I put this into the 2.2 milestone so we can improve this in the next release.

**Comment by coffee-squirrel** [comment]
@bernd Okay, thanks!

**Comment by dennisoelkers** [comment]
This should be fixed properly once #3303 is merged. Alert receivers are now generic parameters for alarm notifications (formerly known as callbacks), so they are shown and edited along the other parameters of a notification.

**Comment by dennisoelkers** [comment]
FIxed in #3303.
