### ISSUE TITLE
Search with incorrect escape (/ vs \) can cause search to hang

### ISSUE THREAD

**Issue by jsmccombs** [Graylog2/graylog2-server#2506]
### Problem description
Queries with incorrect escape sequence can cause GL WebUI to "spin"..

### Steps to reproduce the problem

1. Log data with the following received by the Filebeats plugin, field data:
  command: /tmp/start.sh
  container_id: 7ecfeb5514e8d22951527e185933e45c1ad9c24875a096360a5194cef7a04132
  container_name: myappContainer9_admin_1
  created: <Date/timestamp>
  image_id: sha256: edfe0c438401b82c34c21857527be2ae64c6b0a8a42bf68c57b35ba8289a2b07
  image_name: dtr.dr-staging.myhost.com/somewhere/myappContainer_admin:1.0.21
  level: 6
  message: Errors deploying container.
  source: dock006.dr-stageapp.myhost.com
  tag: 7ecbdfd
  timestamp: <Date/Timestamp>

2. Query for the following:
   **source:dock006.dr/-stageapp.myhost.com**

RESULT: "Loading..." message just spins..

3. Query for the following:
  **source:dock006.dr\-stageapp.myhost.com** 

RESULT: no issue.

-- looks like incorrect escape sequence (/ instead of \) causes the JS client or GL backend to choke.

### Environment

* Graylog Version: 2.0.2
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.2.6
* Operating System: RHEL6
* Browser version: Any.

**Comment by edmundoa** [comment]
Hi @jsmccombs,

I believe this issue is the same as #2372, can you see any errors in your Graylog server logs when the issue occurs?

You could also take a look at the latest alpha release and see if this issue is fixed in there, here is the link to the release: https://www.graylog.org/blog/59-announcing-graylog-v2-1-0-alpha-2

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
