### ISSUE TITLE
process buffer full after vmotion

### ISSUE THREAD

**Issue by andreaconsadori** [Graylog2/graylog2-server#2511]
### Problem description
when i move graylog vm with vmotion in vmware v6 the process buffer raise the 100% and stop elaborating the messages

to fix this i've to stop graylog server and manually flush journal files

* Graylog Version:2.0.3
* Elasticsearch Version:2.3.2
* MongoDB Version:2-6-12
* Operating System:Debian 3.16.7-ckt25-2 (2016-04-08) i686 GNU/Linux
* Browser version:

**Comment by kroepke** [comment]
Can you try to stop processing before you use vmotion to migrate the host and then, after the migration is done turn the processing back on?
It could very well that Graylog needs a restart after being migrated this way.

**Comment by mikkolehtisalo** [comment]
I would suspect this is an issue with the VMotion setup. It should be completely imperceptible to the virtual machine being moved. It stops the VM for < 5s, when the move is finalized, and might have a small performance impact on the source and target hosts while data is being transferred. 

If there was an issue within Graylog, it could probably be reproduced by pausing a VM (for example the OVA) while having some load for couple seconds?

**Comment by andreaconsadori** [comment]
after some test i see is not vmotion relate,
sometimes i found process buffer full and the only way to unlock is to stop graylog server and manually flush buffer files

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
