### ISSUE TITLE
Input running but showing no messages

### ISSUE THREAD

**Issue by tharasavio** [Graylog2/graylog2-server#2512]
### Problem description
Input is shown as  running but showing no messages
### Steps to reproduce the problem

1. ...

### Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
https://groups.google.com/forum/#!topic/graylog2/vJ5aH1Lkbuw
