### ISSUE TITLE
Embed Graylog to an existing site

### ISSUE THREAD

**Issue by sega-yarkin** [Graylog2/graylog2-server#2513]
### Problem description
I need to make Graylog working under `/graylog/` path prefix. I've tried to play with `web_endpoint_uri` parameter, but it didn't help.

For example, when the index page is loading as `http://somesite/graylog/` it's trying to load `http://somesite/config.js`, how can I configure it to load this file as `http://somesite/graylog/config.js`? Also configure API to work under `http://somesite/graylog/api/` prefix.

In previous version (1.x) we used parameter `application.context` in `web.conf` file for that purpose.

Thanks.

### Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: 2.3.4
* MongoDB Version: 3.0.6
* Operating System: CentOS 6.7
* Browser version: Chrome 51

**Comment by joschi** [comment]
@sega-yarkin The Graylog 2.0.x web interface doesn't support running in another resource context at the moment, please see http://docs.graylog.org/en/2.0/pages/upgrade.html#web-interface-config-changes for details.

This being said, the upcoming Graylog 2.1.0 *will* support this again, see #2440.

**Comment by sega-yarkin** [comment]
@joschi Thanks for your help, I've updated to 2.1.0-alpha2 and it works fine!
P.S. We're waiting for #2446 to work without any additional reverse-proxy.

**Comment by joschi** [comment]
@sega-yarkin Thanks for your feedback! We might add this to Graylog 2.2.x.
