### ISSUE TITLE
Node-id permission in debian packages

### ISSUE THREAD

**Issue by tomrade** [Graylog2/graylog2-server#2514]
### Problem description

I installed graylog-server with the debian packages, the server would not start due to being unable to create the file /etc/graylog/server/node-id

I created this file, then used chown to give it to the graylog user, and everything is fine now. however might be worth confirming that deb packages should really do this themselves?

ubuntu 16.04 64bit , minimal virtual machine install
elasticsearch from official deb
openjdk-8

**Comment by joschi** [comment]
@tomrade How exactly did you install Graylog (please provide each step) and were there any error or warning messages during the installation?

I'm asking, because the official DEB package does create the `/etc/graylog/server` directory and the `node-id` file so Graylog doesn't have to: https://github.com/Graylog2/fpm-recipes/blob/2.0/recipes/graylog-server/files/post-install#L40-L48

**Comment by tomrade** [comment]
From the apt log
Start-Date: 2016-07-22  11:25:24
Commandline: apt-get install apt-transport-https openjdk-8-jdk-headless --no-install-recommends
Requested-By: context (1000)
Install: ca-certificates-java:amd64 (20160321, automatic), libgssapi3-heimdal:amd64 (1.7~git20150920+dfsg-4ubuntu1, automatic), libcups2:amd64 (2.1.3-4, automatic), libdbus-1-3:amd64 (1.10.6-1ubuntu3, automatic), libwind0-heimdal:amd64 (1.7~git20150920+dfsg-4ubuntu1, automatic), libpcsclite1:amd64 (1.8.14-1ubuntu1, automatic), libsasl2-modules-db:amd64 (2.1.26.dfsg1-14build1, automatic), libnss3-nssdb:amd64 (2:3.23-0ubuntu0.16.04.1, automatic), libldap-2.4-2:amd64 (2.4.42+dfsg-2ubuntu3.1, automatic), liblcms2-2:amd64 (2.6-3ubuntu2, automatic), libheimntlm0-heimdal:amd64 (1.7~git20150920+dfsg-4ubuntu1, automatic), libxrender1:amd64 (1:0.9.9-0ubuntu1, automatic), libavahi-common-data:amd64 (0.6.32~rc+dfsg-1ubuntu2, automatic), libavahi-common3:amd64 (0.6.32~rc+dfsg-1ubuntu2, automatic), libheimbase1-heimdal:amd64 (1.7~git20150920+dfsg-4ubuntu1, automatic), libsasl2-2:amd64 (2.1.26.dfsg1-14build1, automatic), fontconfig-config:amd64 (2.11.94-0ubuntu1, automatic), openjdk-8-jdk-headless:amd64 (8u91-b14-0ubuntu4~16.04.1), librtmp1:amd64 (2.4+20151223.gitfa8646d-1build1, automatic), libxtst6:amd64 (2:1.2.2-1, automatic), libxi6:amd64 (2:1.7.6-1, automatic), fonts-dejavu-core:amd64 (2.35-1, automatic), libhcrypto4-heimdal:amd64 (1.7~git20150920+dfsg-4ubuntu1, automatic), libjpeg8:amd64 (8c-2ubuntu8, automatic), libfontconfig1:amd64 (2.11.94-0ubuntu1, automatic), libjpeg-turbo8:amd64 (1.4.2-0ubuntu3, automatic), openjdk-8-jre-headless:amd64 (8u91-b14-0ubuntu4~16.04.1, automatic), libnss3:amd64 (2:3.23-0ubuntu0.16.04.1, automatic), libroken18-heimdal:amd64 (1.7~git20150920+dfsg-4ubuntu1, automatic), libasn1-8-heimdal:amd64 (1.7~git20150920+dfsg-4ubuntu1, automatic), libkrb5-26-heimdal:amd64 (1.7~git20150920+dfsg-4ubuntu1, automatic), x11-common:amd64 (1:7.7+13ubuntu3, automatic), apt-transport-https:amd64 (1.2.12~ubuntu16.04.1), libavahi-client3:amd64 (0.6.32~rc+dfsg-1ubuntu2, automatic), libhx509-5-heimdal:amd64 (1.7~git20150920+dfsg-4ubuntu1, automatic), java-common:amd64 (0.56ubuntu2, automatic), libnspr4:amd64 (2:4.12-0ubuntu0.16.04.1, automatic), libcurl3-gnutls:amd64 (7.47.0-1ubuntu2, automatic)

Start-Date: 2016-07-22  11:26:39
Commandline: apt-get install mongodb
Requested-By: context (1000)
Install: libsnappy1v5:amd64 (1.1.3-2, automatic), libboost-program-options1.58.0:amd64 (1.58.0+dfsg-5ubuntu3.1, automatic), mongodb:amd64 (1:2.6.10-0ubuntu1), libboost-filesystem1.58.0:amd64 (1.58.0+dfsg-5ubuntu3.1, automatic), libv8-3.14.5:amd64 (3.14.5.8-5ubuntu2, automatic), libboost-thread1.58.0:amd64 (1.58.0+dfsg-5ubuntu3.1, automatic), libboost-system1.58.0:amd64 (1.58.0+dfsg-5ubuntu3.1, automatic), mongodb-server:amd64 (1:2.6.10-0ubuntu1, automatic), libtcmalloc-minimal4:amd64 (2.4-0ubuntu5, automatic), libgoogle-perftools4:amd64 (2.4-0ubuntu5, automatic), libunwind8:amd64 (1.1-4.1, automatic), libpcap0.8:amd64 (1.7.4-2, automatic), mongodb-clients:amd64 (1:2.6.10-0ubuntu1, automatic), libpcrecpp0v5:amd64 (2:8.38-3.1, automatic), libyaml-cpp0.5v5:amd64 (0.5.2-3, automatic)
End-Date: 2016-07-22  11:26:55

(here I used dpkg to install the graylog repo deb)

Start-Date: 2016-07-22  11:30:33
Commandline: apt-get install graylog-server
Requested-By: context (1000)
Install: graylog-server:amd64 (2.0.3-1)
End-Date: 2016-07-22  11:30:37


EDIT

I figured it out 

[WARNING] uuidgen not available! Please execute 'uuidgen > /etc/graylog/server/node-id' once it's installed.

Should this be a dependency ? I used a bare Ubuntu virtual machine guest installed (from the server iso) and it is pretty cut down (not even man), so that would be why i might be different to typical ubuntu users which might have it

**Comment by joschi** [comment]
@tomrade Thanks for your feedback!

@bernd Might it make sense to generate a "random UUID" with something like this?
```bash
printf "%08X-%04X-%04X-%04X-%012X" $RANDOM$RANDOM $RANDOM $RANDOM $RANDOM $RANDOM$RANDOM$RANDOM
```
Alternatively create the `/etc/graylog/server` directory and set the correct ownership/permissions so that Graylog can create the node ID file itself.

**Comment by bernd** [comment]
The packages are creating the node id file if uuidgen is installed. Otherwise a warning will be shown.

See: https://github.com/Graylog2/fpm-recipes/blob/master/recipes/graylog-server/files/post-install#L40-L48

**Comment by joschi** [comment]
@bernd As far as I see, we could reasonably safely depend on the `uuid-runtime` package:
* https://packages.debian.org/wheezy/uuid-runtime
* https://packages.debian.org/jessie/uuid-runtime
* https://packages.debian.org/stretch/uuid-runtime
* http://packages.ubuntu.com/trusty/uuid-runtime
* http://packages.ubuntu.com/trusty-updates/uuid-runtime
* http://packages.ubuntu.com/xenial/uuid-runtime

**Comment by bernd** [comment]
Sorry, I didn't read the previous comments carefully enough.

@joschi What about RPM based distributions like RedHat, CentOS, SuSE?

I would like to avoid adding the dependency if possible. Maybe we just go with the `printf` method or are there any serious drawbacks?

**Comment by mikkolehtisalo** [comment]
Could also use [java.util.UUID](http://docs.oracle.com/javase/8/docs/api/java/util/UUID.html) to generate the UUID...

**Comment by joschi** [comment]
@mikkolehtisalo We're already doing this in Graylog itself. The problem is, that Graylog doesn't have sufficient permissions to write into the `node_id_file` in the OS packages.

**Comment by mikkolehtisalo** [comment]
@joschi I meant, you can whip up a tiny Java based "uuidgen" utility to be available at the installation phase... (Or add to some already existing jar, it's not mandatory to start the default class from a jar iirc)

**Comment by bernd** [comment]
Fixed for Debian in https://github.com/Graylog2/fpm-recipes/pull/70
