### ISSUE TITLE
Alert content value condition triggered only on exact match

### ISSUE THREAD

**Issue by dannyz29** [Graylog2/graylog2-server#2517]
### Problem description

I've configured an alert on a non-analyzed field content value. When I set the condition to match the exact value of the field - alert is triggered.

I'm unable to trigger an alert when the condition checks for a strings contained in the field but isn't an exact match.

For example, I'm trying to match content value:  `Error occurred while update app`, when the whole field value is `abc Error occurred while update app - some other text`.

Tried to specify wildcards and regex in the condition - but it didn't work for me.
For example the next regex expression didn't work for me:
`.*Error occurred while update app.*`

How do I create a condition that triggers an alert when the field **contains** a certain string and is not an exact match?
### Environment
- Graylog Version: 2.0.1

**Comment by kroepke** [comment]
The alert condition is translated to a Lucene query. On non-analyzed fields this will probably not be able to run regex searches. Can you try with regular wildcards (i.e. without `.`) and see if that matches anything?

**Comment by joschi** [comment]
Related ES documentation: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-query-string-query.html#_regular_expressions

**Comment by chainkite** [comment]
`/.*Error.*/` didn't work for me as well

**Comment by dannyz29** [comment]
I ended up using stream rules with regex to create streams that contain only the messages I wanted and created a message count alerts on the stream.

**Comment by 06chaynes** [comment]
@chainkite I know this is old but I thought I would share my experience. I needed to send an alert based on the string `error` being in the full_message field. My regex (working) looks like this:
\*:(error)

**Comment by chainkite** [comment]
Great, thank you a lot. @06chaynes
