### ISSUE TITLE
Synthetic fields remain in message table after decorators are removed

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#2518]
### Problem description

Selected fields linger after a decorator that added them is removed.

### Steps to reproduce the problem

1. Add a pipeline decorator that adds a simple static field to messages.
2. Select the field to show in the message table.
3. Remove the decorator from the result.
4. The field is still show as a table column.

### Environment

* Graylog Version: 2.1.0-SNAPSHOT
* Elasticsearch Version: n/a
* MongoDB Version: n/a
* Operating System: n/a
* Browser version: n/a

**Comment by kroepke** [comment]
known bug from #2499

**Comment by edmundoa** [comment]
I could not reproduce this in the current master, please reopen if the issue still exist.

**Comment by kroepke** [comment]
yup, i think it's reloading properly now.
