### ISSUE TITLE
Add more permissions to roles UI

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#2520]
### Problem description

It would be helpful to let user grant some useful set of permissions in the roles UI. One example is to grant permissions to reader users to do global searches (Graylog2/graylog2-web-interface#620).
### Environment
- Graylog Version: 2.0.3 / 2.1.0-alpha.3

**Comment by Comradin** [comment]
Hi, this would be an awesome improvement for my users. As they use the dashboards "Replay Search" to further drilldown into a given topic/problem whatever you would like to name it. Currently they need to have the admin role, to be more than just simple dashboard viewers.

**Comment by tokred** [comment]
It would be helpful to be able to differentiate between the rights to edit stream alerts and to edit stream rules. There are use cases where it makes sense for users to customize alerting of "their" stream while not being able to access other sensitive messages outside their stream (by editing the stream rule criteria). Currently, the admin is not able to differentiate.

**Comment by coffee-squirrel** [comment]
I think increased flexibility in this area would be great.  The current permission system is somewhat constraining when a central admin team needs to delegate management of certain things (e.g. stream alerts) while retaining control over others (e.g. stream rules that govern who can see what).

**Comment by Comradin** [comment]
Not sure, if this is the _correct_ issue for this, but it would be great to map the Administrator role to some group from an external authentication source like LDAP/Active Directory.

**Comment by coffee-squirrel** [comment]
@Comradin :  That's already possible through LDAP group mappings and the "Admin" role.

**Comment by Comradin** [comment]
@coffee-squirrel you're right, that ldap group mappings link is very well hidden in the ldap configuration page, and I have to admit, that I did not expected the mappings button in the ldap config page and thus overlooked it.

Thanks for showing me the correct direction.

**Comment by bernd** [comment]
We improved this in the upcoming Graylog 4.0.0 release by introducing a entity sharing system. Also the new search page allows users to search in all streams they have access to.

I am closing this issue. Please open a new one if you still have problems with this once Graylog 4.0.0 has been released. Thank you!
