### ISSUE TITLE
Add monitoring role / make metrics public

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#2521]
I would like to monitor graylog using some sensu / own plugins. Right now I have to configure the graylog admin password in the monitoring calls. It would be cool if I could just add a user with minimal rights or an option to allow metrics call without credentials from localhost.

**Comment by joschi** [comment]
The `/system/metrics` resource can be accessed by any user with the permission "metrics:readall".

Additionally, existing users can generate a unique access token (see the `/users/{username}/tokens/` resources in the Graylog REST API) which can be used to access those protected resources without having to provide the actual user name and password (or an expiring session token).
