### ISSUE TITLE
User Admin Page broken, when having many roles assinges to one or more users

### ISSUE THREAD

**Issue by schlitzered** [Graylog2/graylog2-server#2526]
### Problem description
when having many roles assigned to a single user, it is no longer possible to reach the "Delete" or the "Edit" button via the user admin page in the Web interface. this is because all roles are listed in the role column, and the "Delete" and "Edit" buttons are simply not visible anymore.

### Steps to reproduce the problem

1. create many roles
2. assign the roles to a single user, until the "$URI/system/users" 
3. visit the systems/user page
4. you wont be able to reach the Delete or Edit buttons

### Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.2
* Operating System: CentOS 7
* Browser version: Firefox 47.0

**Comment by jfachal** [comment]
The problem already exists from prior versions of Graylog (e.g. graylog-web-interface v1.3.4)
