### ISSUE TITLE
Cannot update user information

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#2528]
### Problem description
Logged in as a user with the admin role, I cannot edit my information. When changing the form and clicking on "Update user", I get a 400 error and this error in the browser's console:

```
There was an error fetching a resource: cannot PUT http://127.0.0.1:12900/users/hans (400). Additional information: Unable to map property read_only.
Known properties include: startpage, permissions, timezone, full_name, email, session_timeout_ms, roles
```

Nothing else is shown on the server logs.

### Steps to reproduce the problem

1. Log in as a user with the admin role
2. Go to Your user -> Edit profile
3. Change some information, i.e. time zone
4. Press on "Update user" and see the error

### Environment

* Graylog Version: 2.1.0-alpha.3 (d189efdd6ccdbc5aebd3b7afae6c6ba264a1f53c)
* Browser version: Chrome 52

**Comment by bernd** [comment]
Please check if this is still an issue, thanks!
