### ISSUE TITLE
Stores always extend user session

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#2537]
### Problem description

Background requests which stores schedule on a timer currently always extend the user's session.

### Steps to reproduce the problem

1. Log in
2. Wait for session expiration
3. Also wait for Godot.

The problem is that stores cannot distinguish between interactive usage and interval refresh requests anymore. This basically renders session timeouts useless as even the NodesStore keeps the session active.

### Environment

* Graylog Version: 2.1.0-beta.1
* Elasticsearch Version: n/a
* MongoDB Version: n/a
* Operating System: n/a
* Browser version: n/a

**Comment by bernd** [comment]
Closing this because this behavior is okay.

We talked about this, but didn't came to a consensus whether this is wanted or not.
