### ISSUE TITLE
Indicate which users have an active session and show their client ip

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#2540]
To pinpoint users which cause expensive traffic or otherwise impact stability, show which users are active (i.e. have a non-expired session), their last activity and their client IP address in the user list, if available.

**Comment by gruselglatz** [comment]
Maybe consider adding a "kick-out" or "close session" feature?

**Comment by kroepke** [comment]
It's pretty late in the release cycle (even to add this change) but I'll bring it up with the team.
Originally we wanted to build a more complete interface for each of the authenticators, including a session management page, but simply ran out of time.

**Comment by kroepke** [comment]
We've had a discussion offline and the majority was against pulling it into the release this late. I'll move it to a future release and open a separate issue for this.

Thanks!
