### ISSUE TITLE
How to monitor Tomcat log

### ISSUE THREAD

**Issue by vanhung89** [Graylog2/graylog2-server#2547]
I need to moniror Tomcat log, can you help me configure? If you have an example, I will be easy to confiure. Thanks

**Comment by edmundoa** [comment]
Hi,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
