### ISSUE TITLE
import content pack need to be seperated

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2553]
The option for import a content pack is not very user friendly placed. 

![graylog_web_interface](https://cloud.githubusercontent.com/assets/404238/17173756/fa469b90-53fc-11e6-959d-eb1e9d655a59.png)

it should be moved to the right (where the action for the last content pack that was used still visible) or this should be an additional point next to create a content pack
### Environment
- Graylog Version: 2.1 beta

**Comment by bernd** [comment]
This will be fixed in 3.0.
