### ISSUE TITLE
Can't Change User Time Zone

### ISSUE THREAD

**Issue by kpointer** [Graylog2/graylog2-server#2558]
### Problem description

Attempting to set user time zone on two different Beta 1 deployment. One is a new install using LDAP, the other is an older install upgraded to Beta 1 and using a local account. 

On the local account, the time zone is currently correct, but I get the same error that the new deploy gives if I try and change the time zone.

The error:

Updating user failed
Could not update the user. Please check your logs for more information.

No obvious errors in the debug log.

Switching back to 2.0.3 I can set Time Zone.

### Steps to reproduce the problem

1. Edit profile
2. Change the Time Zone 
3. Select Update User

### Environment

* Graylog Version: 2.1.0 Beta 1
* Elasticsearch Version: 2.3.4
* MongoDB Version: 3.2.8
* Operating System: Ubuntu 16.04.1
* Browser version: Firefox 48.0b10

**Comment by edmundoa** [comment]
Hi,

I'm closing this issue, as it is duplicating #2528. Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!

**Comment by slitmengheang** [comment]
Hi All,
i want to ask your help to solve my issue, i am testing graylog and see timezone not correct just only admin user, so do you have any support
Thanks

**Comment by joschi** [comment]
@slitmengheang 
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
