### ISSUE TITLE
Extend api browser generator

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#257]
It would be great to simplify the annotations used to document rest resources.

A lot of information can be gathered from the jaxrs annotations already, such as the name.
Making some other annotations such as `@Optional`, `@Required` or `@Notes` could make the annotation list much easier to read, too.

We should also extend it to support success return codes and somehow figure out how to document the various maps or json structures we accept and return.

**Comment by bernd** [comment]
We are more likely to switch to the standard swagger generator than extending our own generator which is quite buggy. Closing this.
