### ISSUE TITLE
Landing page greets with 2.0 in 2.1

### ISSUE THREAD

**Issue by Comradin** [Graylog2/graylog2-server#2579]
### Problem description
The landing page of a fresh installed 2.1beta installation greets its users with the following message:

"Getting Started - Graylog v2.0"

### Steps to reproduce the problem

1. Install the current 2.1beta1
2. Open the browser and surf to the /gettingstarted page

### Environment

* Graylog Version: 2.1beta1

**Comment by bernd** [comment]
Thank you for the report, this will be fixed in the next beta!
