### ISSUE TITLE
Broken link to API browser in main menu

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2586]
### Problem description
![image](https://cloud.githubusercontent.com/assets/17475270/17328869/a24fa334-58c8-11e6-916f-8dc5e655da39.png)

### Environment
* Graylog Version: 2.1.0-beta1

**Comment by joschi** [comment]
@hc4 Could you please post your `rest_listen_uri`, `rest_transport_uri`, `web_listen_uri`, and `web_endpoint_uri` settings?
Are you using the `X-Graylog-Server-URL` request header?

**Comment by hc4** [comment]
rest_listen_uri = http://0.0.0.0:12900/
rest_transport_uri not set
web_listen_uri = http://127.0.0.1:80/
web_endpoint_uri  not set

headers
```
GET / HTTP/1.1
Host: graylog
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.111 YaBrowser/16.3.0.7843 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: ru,en;q=0.8
```

**Comment by edmundoa** [comment]
Thank you for reporting this issue!

I have been trying to reproduce this behaviour, but it seems it was fixed in #2564.
We will release another beta shortly, I'll close the issue, please take a look on beta 2 and reopen it if you still see the problem.

**Comment by edmundoa** [comment]
Sorry, my bad, the linked issue didn't fix this.

**Comment by bernd** [comment]
Fixed via https://github.com/Graylog2/graylog2-server/pull/2587
