### ISSUE TITLE
UI issues when decorator replaces field value

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#2591]
### Problem description

There are some issue when using a decorator that is replacing a field value.

![graylog](https://cloud.githubusercontent.com/assets/461/17357361/7b08aa3e-595c-11e6-9175-e1004e046a79.png)

1. The field name entry sidebar does not indicate that the value has been modified
1. The message details still show the magnifier to search for the value and the actions menu

When you click the magnifier icon, the changed value will be added to the search bar. This will not work because the value will not be found in ES.

### Steps to reproduce the problem

1. Configure and add a decorator that replaces a field value (i.e. pipeline decorator with a pipeline and rule that overwrites a field)
1. Check the field in the sidebar: there is no indication that it's generated/modified
1. Check the message details: the field name has the modified marker, but it's still possible to search for this value and run other actions from the action menu

### Environment

* Graylog Version: 2.1.0-beta.2-SNAPSHOT (581eb1f)
* Browser version: Chrome 52

**Comment by edmundoa** [comment]
Fixed in #2654
