### ISSUE TITLE
Meaningless error message in rest api browser

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2594]
### Problem description

![image](https://cloud.githubusercontent.com/assets/17475270/17359100/c7801bd4-596d-11e6-9711-8afb2376ab54.png)

The default port for http 80, so both addresses are equivalent
### Environment
- Graylog Version: 2.1.0-beta2

**Comment by bernd** [comment]
This should be solved since we refactored the HTTP config settings in 3.0.
