### ISSUE TITLE
Web UI starts on port 9000 despite what docs say

### ISSUE THREAD

**Issue by shishkin** [Graylog2/graylog2-server#2606]
## Expected Behavior
According to https://github.com/Graylog2/graylog2-server/blob/2.1.0-beta.2/UPGRADING.rst#web-interface-listener the web UI listener should start on http://0.0.0.0:12900/web by default.

## Current Behavior
Web UI listener starts on port 9000.

## Possible Solution
This can be overridden with the `web_listen_uri` config property as documented.

## Steps to Reproduce (for bugs)
Start Graylog docker image `graylog2/server:2.1.0-beta.2-1` as described at https://hub.docker.com/r/graylog2/server/.

**Comment by joschi** [comment]
@shishkin The Docker image is configured differently than the "vanilla" Graylog. See https://github.com/Graylog2/graylog2-images/blob/2.0/docker/config/graylog.conf for details.
