### ISSUE TITLE
Provide ability to bulk import data with GELF API

### ISSUE THREAD

**Issue by vangheem** [Graylog2/graylog2-server#2607]
## Expected Behavior
To be able to push more than one log entry at a time from the GELF API.

## Current Behavior
No able to do so.

## Possible Solution
Provide ability to bulk push entries with GELF endpoint.

## Context
Pushing data could be faster if bulk allowed.

**Comment by joschi** [comment]
@vangheem What specifically do you mean with "GELF API"?

**Comment by vangheem** [comment]
http://docs.graylog.org/en/2.0/pages/gelf.html#example-payload

**Comment by kroepke** [comment]
We currently are not planning to update the GELF spec.

**Comment by haizaar** [comment]
Hi guys,

Just to confirm - there is currently no way to send multiple log messages in a single [HTTP POST](http://docs.graylog.org/en/2.4/pages/sending_data.html#gelf-via-http), right?

**Comment by joschi** [comment]
@haizaar Correct.

**Comment by haizaar** [comment]
I see.

Did you ever consider introducing it? May be through a dedicated API endpiont, e.g.

```
POST /gelf/_bulk
{"short_message": "first_message"}
{"short_message": "second_message"}
{"short_message": "third_message"}
...
```

(Apologies if this is not the right place to discuss this)

**Comment by bernd** [comment]
@haizaar Please open a separate feature request issue for this. Thank you!
