### ISSUE TITLE
Unable to delete empty saved searches 

### ISSUE THREAD

**Issue by JulioQc** [Graylog2/graylog2-server#2608]
## Expected Behavior
The delete/modify button should still be displayed even if no result is returned.

## Current Behavior
No button to modify/delete the saved search is displayed if no result is returned. 

## Possible Solution
Add a button or option to delete the empty saved search easily.

## Steps to Reproduce (for bugs)
1- Make a search and save it
2- Return to the saved search knowing no return will be returned
3- Try to find a way to delete/modify it...

## Context
Made some modifications to an input thus needing to modify a previously saved search. Since the modification was made a while ago and the saved search is limited to 1day, no result is returned making it impossible to delete the saved search or modify it with the new criteria. 
See screenshot: http://imgur.com/0tw0YcL 

## Your Environment
* Graylog Version: 2.0.3 (OVA template)
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by edmundoa** [comment]
Closing, as this was fixed in #2253, and will be available in Graylog 2.1.0. Feel free to take a look at the latest beta and provide some feedback if you like.
