### ISSUE TITLE
Bad url generated in Alert email

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2611]
## Expected Behavior
Alert Email should contain correct URI:
Stream URL: http://graylog/web/streams/...

## Current Behavior
Stream URL: http://graylog/streams/...

## Context
I have configured rest and web to same addr. and web at "/web"
Maybe the cause is that I have empty(relative) web_endpoint_uri.

## Your Environment
* Graylog Version: 2.1.0-beta2

**Comment by joschi** [comment]
@hc4 Make sure to set [`transport_email_web_interface_url `](https://github.com/Graylog2/graylog2-server/blob/2.1.0-beta.2/misc/graylog.conf#L467-L469) correctly.

**Comment by hc4** [comment]
Ok. Thanks.
It should be described in config for web_listen_url parameter
