### ISSUE TITLE
Stream description and Stream URL are joined on same line in email

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2612]
## Current Behavior
Alert email contains description and url on same line:
`Stream description: *** Stream URL: ***`

## Expected Behavior
Should be splitted:
```
Stream description: ***
Stream URL: ***
```

## Your Environment
* Graylog Version: 2.1.0-beta2

**Comment by joschi** [comment]
@hc4 I can't reproduce that. What's the raw source code of the email you've received?

You can also use a custom email template: http://docs.graylog.org/en/2.0/pages/streams.html#email-alert-callback

**Comment by hc4** [comment]
Found the problem.
This is [feature](http://blog.beezix.com/2012/03/16/outlook-2010-give-me-back-my-plain-text-line-breaks/) of Outlook :)
