### ISSUE TITLE
More customization options for dashboard widgets

### ISSUE THREAD

**Issue by rikmer** [Graylog2/graylog2-server#2615]
I am using graylog mainly for Windows security auditing. It would be great to have more flexible visualization options for dashborad widgets. For example would it be great to be able to combine quick values in one quickvalue widget that one can visualize, for example, the user who did not log in correctly and next to it the IP-adress, etc. . In short I would like to have the possibility to combine data fields (not only numerical ones) in one widget. This would be great.

**Comment by rikmer** [comment]
Just adding a quick explanation to the feature request ...
All in all it would be great to have a better data correlation and visualization (even if already great :) ) capability.

**Comment by lliknart** [comment]
Hi,

Add the capability to create a table (data chart) would be great.
For example, I want to visualize the TOP 10 of external IPs which generate the most of events and for each of them, the associated AS number.

Currently I need to "quick value" on IP field and for the first 10 IPs, make a research and make a "quick value" again on "AS number" field.

Thank you

**Comment by alias454** [comment]
+1
We use JIRA for issue management and there is a 2d results widget. Something like that would be an excellent addition to the dashboard plugin options.

Regards,
Brandon

**Comment by pdepaepe** [comment]
+1 This is one of the widget available in Grafana 

[http://docs.grafana.org/img/docs/v2/elastic_aggregations.png](http://docs.grafana.org/img/docs/v2/elastic_aggregations.png)

**Comment by mayantec** [comment]
It would be great if after widget creation, you can change all parameters (Recustomize all parameters), like query, field, etc. Not all widgets support all fields, you have to export a content pack, modify by hand and reimport.

**Comment by jalogisch** [comment]
as this issue does not contain a specific idea or use case we will close this for now. 

if you can describe your use case and idea briefly, please open a new issue.

**Comment by lliknart** [comment]
The idea is to be able to build a table with more than one value.
For example, I can create a Dashboard containing the following data
Query: group:vpn
Quick Value: user

I get a table containing the following column:  `user   %   Count`

I would like to include the field src_ip  in the the table like below: 
`user   src_ip   %   Count`

src_ip could be the first (top value) or the last value (last event) in case where the same user have multiple src_ip.

It could be useful to track VPN connection for example.

Currently, we need to
1:  Quick Value `user`
2: for each of them, a "Quick Value" of src_ip

**Comment by jalogisch** [comment]
this is covered already by some other issues. For example: https://github.com/Graylog2/graylog2-server/issues/2715

Please follow that issue if you need to be updated on that.
