### ISSUE TITLE
Total message count doesn't always match the sum of separate counts

### ISSUE THREAD

**Issue by JesseC42** [Graylog2/graylog2-server#2616]
## Expected Behavior
We have a dashboard to count messages for a client. We measure the overall count, however also the separate entities of the company. The total count should always match the sum of the separate counts 

## Current Behavior
In most months the total count matches with the sum of the separate counts. But, in 4 of the last 12 months there is a difference and the total doesn't match. IP addresses are all checked and the same, so there shouldn't be difference. 

## Steps to Reproduce (for bugs)
https://dashboard.plannerstack.org/dashboards/559e47a3e4b0be325df25baa 
Check for instance the month August of 2015 

## Context
We can't make the right counts for our customers.

## Your Environment

* Graylog Version: graylog-web-interface v1.3.3 (0fda9dc) 
* Elasticsearch Version: 1.5.0
* MongoDB Version:
* Operating System: OSX El Capitan 10.11.5
* Browser version: Chrome Versie 51.0.2704.103 (64-bit)

**Comment by joschi** [comment]
@JesseC42 Please also add the versions of Graylog and Elasticsearch to your bug report.

**Comment by kroepke** [comment]
@JesseC42 Please check if this problem still occurs in Graylog 2.0. We do not plan to release another 1.3 update.
If the problem persists please re-open this bug report.

Thank you!
