### ISSUE TITLE
Many identical XHR request generated, when previous not finished

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2625]
![image](https://cloud.githubusercontent.com/assets/17475270/17472950/75260190-5d56-11e6-9e7e-4d8d20e3d28f.png)

## Expected Behavior
No new requests should be sent, until previous finished
I even had cases, when xhr returned result but too late.

## Current Behavior
New requests generated by timer regardles of state of preious.

## Your Environment
* Graylog Version: 2.1.0-beta2

**Comment by dennisoelkers** [comment]
I guess the best strategy here would be to do something like this in the store actions (pseudoish code):

```
  if (promise === undefined) {
    promise = fetch(...);
    promise.finally(() => { this.promise = undefined; });
  }

  return promise;
```

 So we are kinda caching the promise and return it if it still exists (which would mean the promise was not resolved yet), instead of generating a new one.
