### ISSUE TITLE
Make "Bound to Stream" for Widgets changeable

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#2629]
## Expected Behavior

The bounded stream on dashboard widgets should be changeable.
## Current Behavior

If you import a Content-Pack where Dashboard-Widgets are bound to a certain stream, the id afterwards is broken and the Dashboard(-Widget) is dead.

So you have to delete the Widget and create it new.
## Possible Solution

Add a Bounded Stream setting in the edit function.
## Steps to Reproduce (for bugs)
1. go to a stream
2. create a widget out of them
3. delete stream
4. create new stream for same usecase (or import contentpack...)
5. widget is dead
## Context

We use the Streams mainly for the usermanagement and when the user clicks on the replay button in the dashboard, it should bring you into the correct stream. So we are forced to use bounded Widgets.

After the uprgade to 2.0 we imported our old settings via a content pack.
## Your Environment
- Graylog Version: 2.0.3
- Elasticsearch Version: -
- MongoDB Version:-
- Operating System:-
- Browser version:-

**Comment by mayantec** [comment]
This happens also with Inputs, the hash name of the input after importing the content pack also breaks the dashboards and streams.

Perhaps named inputs or named streams will be a solution, or when importing/exporting, keep the hashes.

**Comment by jalogisch** [comment]
this issue should be fixed with #3416 - this is available in Graylog Version 2.2.
