### ISSUE TITLE
feature request: rare values

### ISSUE THREAD

**Issue by sam72** [Graylog2/graylog2-server#2631]
hi graylog team,

first of all: thank you for making such a great product, graylog is awesome!

i am using it for different purposes, but the main use is to have a good overview of what my firewall is doing. i am getting all sort of information out of it which i did not know about before and am able to turn it into actionable requests for my team, we are talking about a few hundred thousand messages per minute -  **as i said: awesome!**

basically i am just reacting on values i get by doing some regex (where i already know parts of what to expect eg. "alert" or "dropped" ), but now i'd like to go a bit further and get this one in a million rare message where i do not know what content will have. 

example (strongly simplified) output of a search:
## 

```
msg: "message text sd29g43tnj" count: 34217
msg: "message text vb43bg78x" count: 18923
msg: "exception text vf35gaagfxf"  count: 4    <-----
msg: "message text c3490ghs2" count: 36495
msg: "message text 02789fh3c" count: 2554
msg: "message text 9jbgs3dfg5" count: 6545
msg: "exception text 3h7vtr45"  count: 1    <-----
```
## 

i'd like graylog to have an option where instead of choosing "quick values" i can choose "rare values"
and it will give me the marked two ones.

the problem is that the message text is defined by an external source (can think of it as in pattern / definition updates) and therefore can not be foreseen (parts of it are are security detection patterns so if there is a new security threat with some new fancy name such as "HeartBleed" the system will also refer to it with the given name in the log-messages).

i am not a programmer and therefore have not a good idea of what the implications are of what i am asking for, maybe it can be done easily with some sort of reversing the sorting of "quick values", maybe its rocket-science.

thanks in advance for any kind of response!

best regards,
sam

**Comment by kroepke** [comment]
The only issue I see with using the terms aggregation and sorting on `_count` ascending is that it can dramatically increase the error in the returned counts.
This error will be higher the more shards the index has and the more "rare" values the field contains. The reason for this is that elasticsearch runs the query (and aggregation) for each shard individually and then merges the result.
In the case where shards contain many different values that occur only very few times, the size of the long tail and the amount of buckets elasticsearch uses to find the rare values can cause the different shards to return different candidates and thus produce large errors in the result.

In general the document counts are approximations, for a more detailed discussion please see [elastic's terms aggregation docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#search-aggregations-bucket-terms-aggregation-approximate-counts).

**Comment by dennisoelkers** [comment]
It is possible to generate aggregations returning bottom-N widgets for a while now, at least with 3.1.0.
