### ISSUE TITLE
Indexing failures not reported

### ISSUE THREAD

**Issue by JulioQc** [Graylog2/graylog2-server#2633]
## Expected Behavior
Indexing errors are reported and somehow handled.

## Current Behavior
Even if current Graylog logs is filled with MapperParsingException errors, the "Indexer failures" dashboard under "Overview" isn't reporting any failures. 
Logs: http://imgur.com/N1jIeKc
No error: http://imgur.com/Ikpyko9

## Possible Solution
No idea.

## Steps to Reproduce (for bugs)

Can really say, just noticed something was wrong on Monday morning.
Root cause was a poorly made input extractor and this got out of control really quick. 
Had to remove the extactor, cycle deflector, manually clear disk journal and some internals logs, reboot the box. 

## Context

Message Processing stopped
Disk Journal filled to max
Input/Output buffer filled to max
Some logs (/var/log/graylog/elasticsearch/graylog.log.*) grew exponentially (8GB+ each although configure for rotation at 200MB...) eating up disk space thus making the problem even worst by filling the disk to max.
No warning or display of indexing failure
Only warning was when disk was close to max

## Your Environment

* Graylog Version: 2.0.3 (OVA image)
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by tommymonk** [comment]
I believe that we encountered the same issue last week.
Our symptoms were the pipeline processing coming to a halt, a [thread](http://pastebin.com/raw/Ud3CebSG) from the dump showed the Elasticsearch bulkindex thread blocked.

It turned out that one of the Elasticsearch nodes was misconfigured and had thrown an OOM exception in response to a heavy query. This caused the bulkindex to fail.

The failure of the bulkindex seems to have permanently blocked processing.

**Comment by JulioQc** [comment]
Where did you get this dump? Maybe I can check on my side

**Comment by tommymonk** [comment]
Whilst graylog was 'stuck' processing message, I used the "Actions > Get Thread Dump" feature on the "System > System/Nodes > Details" page.

The snipped I linked to was the interesting thread from the full dump that I retained.

**Comment by JulioQc** [comment]
Ok thanks I got it :)
It's filled with info so I'm not sure what to make of it... will likely need to read on the matter.

**Comment by bernd** [comment]
@JulioQc This will be fixed in the upcoming 2.1 release. Thank you for the report!

**Comment by JulioQc** [comment]
Always a pleasure to help :)
