### ISSUE TITLE
How can I import graylog web interface pages by iframe?

### ISSUE THREAD

**Issue by HzMomO** [Graylog2/graylog2-server#2640]
Hi,everyone. I got a request to import graylog web interface pages into our platform by iFrame. We didn't implements ldap yet, so I tried to imitate same http request like login page . I did it successfully and web server returned session_id. But on the next step, Chrome opended the graylog2 ,and it still showed the login page.
Is any way there to do login by javascript without LDAP?

**Comment by mariussturm** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
