### ISSUE TITLE
Line-break is jumping on Nodes page

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/graylog2-server#2655]
The metrics summary text on the Nodes page is jumping back and forth when the page auto-updates the counter for journal metrics.
## Expected Behavior

The metrics counter should update without adding a line break in the middle of the page
## Possible Solution

Make use of the empty space and dont line break in the middle of the page
## Steps to Reproduce (for bugs)

1. Open the Nodes page (you need some constant changing input rate)
2. Watch the text jump
- Graylog Version: 2.1.0-beta.2
- Elasticsearch Version:
- MongoDB Version:
- Operating System:
- Browser version: FF 47

**Comment by bernd** [comment]
@mariussturm I am unable to reproduce this. Can you please show a screenshot which element is affected?

**Comment by bernd** [comment]
@mariussturm I just talked to @edmundoa and he explained. Sorry for the noise.
