### ISSUE TITLE
LDAP/AD - Permissions reset to default on user login

### ISSUE THREAD

**Issue by jkpaye** [Graylog2/graylog2-server#2658]
Active Directory is configured as an authentication provider.  A default role is configured.  The administrator adds additional permissions to a user which was automatically pulled into graylog from AD.  The next time that user logs in the permissions are reset to the default.

## Expected Behavior
Changes to AD user's permissions should persist once they are set.

## Current Behavior
Changes to AD user's permissions are reset to the default each time that user logs in.

## Steps to Reproduce (for bugs)
1. Configure AD
2. Configure default permissions.  In this case we have the default role configured as "Reader - basic access."  We have an additional default role configured which is called "All_Logs."
3. Have a user, whom is a member of the AD domain, login.  This will cause an account to be generated.
4. Login as the admin user, and edit that user's roles.
5. Have the user login again.
6. Login as admin and observe that the user's roles have been reset to the defaults.

## Your Environment

* Graylog Version: 2.0.2
* Elasticsearch Version: 2.3.5
* MongoDB Version: 2.6.12
* Operating System: RHEL7.2
* Browser version: Chrome Version 43.0.2357.124 m

**Comment by joschi** [comment]
@jkpaye This has been addressed in #2529 and will be fixed in Graylog 2.1.0.
