### ISSUE TITLE
Message Journal retries forever in case of irrecoverable errors

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#2659]
Due to a never stopping retry-strategy in [`JournallingMessageHandler`](https://github.com/Graylog2/graylog2-server/blob/2.0.3/graylog2-server/src/main/java/org/graylog2/shared/buffers/JournallingMessageHandler.java#L49-L59), Graylog will forever retry to write messages into the message journal in the face of an error, even if it's irrecoverable.

Example:
```
2016-08-11T08:41:03.465+02:00 ERROR [JournallingMessageHandler] Unable to write to journal - retrying with exponential back-off
kafka.common.MessageSetSizeTooLargeException: Message set size is 112367208 bytes which exceeds the maximum configured segment size of 104857600. at kafka.log.Log.append(Log.scala:300) ~[graylog.jar:?]
```
The message set is simply too large to fit into one segment of the Kafka Log and thus will always fail. Unfortunately, Graylog will never stop to retry writing those messages and will require a restart to resolve this error.

**Comment by gbu-censhare** [comment]
maybe an option to persist such a message outside would be nice, so if this occurs one could a know what was causing this and possible bugs could be fixed?

**Comment by kroepke** [comment]
The error above happens because Graylog was too aggressive in batching writes. Usually this shouldn't happen and is more of an edge case. The real issue is that it won't stop retrying, which stalls everything, because the error is not recoverable.
