### ISSUE TITLE
Bad url generated for csv export if web_endpoint_uri is relative

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2661]
I have empty web_endpoint_uri in config and my export CSV link looks like:
`***:session@/search/universal/relative/export?query=%2A&range=300&fields=source%2Cmessage`

## Your Environment
* Graylog Version: 2.1.0-beta.3-SNAPSHOT+45cc198

**Comment by joschi** [comment]
@hc4 Please specify the exact version of Graylog you're using.

**Comment by hc4** [comment]
Version:
![image](https://cloud.githubusercontent.com/assets/17475270/17584706/c1e6ca8e-5fc0-11e6-9da3-497f13bd0846.png)

Problem:
![image](https://cloud.githubusercontent.com/assets/17475270/17584692/b17ed042-5fc0-11e6-9f09-ea10789bf07f.png)

I can test latest snapshot.

**Comment by hc4** [comment]
Smae problem with 2.1.0-beta.3-SNAPSHOT+8d14878

**Comment by dennisoelkers** [comment]
Thanks for reporting this, @hc4. Could you please post the result when you fetch `$web_listen_uri/config.js` (i.e. using curl)?

**Comment by hc4** [comment]
```
window.appConfig = {
  gl2ServerUrl: 'http://graylog:80/',
  gl2AppPathPrefix: '/web',
  rootTimeZone: 'UTC',
};
```

**Comment by isador999** [comment]
I it can help : 
With Admin user,  in Search tab,    when generated URI is  
https://host.domainname/a2514976-74b7-4072-9bb0-63b6579a005d:session@/api/search/universal/relative/export?query=%2A&range=300&fields=source%2Cmessage

If I remove the "/a2514976-74b7-4072-9bb0-63b6579a005d:session@"  part of URI,  it asks the authentication, and I can download the CSV.  
But in limited user, I can only do export from "Streams" and in this case, there is no workaround.

**Comment by hc4** [comment]
Sorry, I've realized that switched graylog to absolute endpoint uri.
With relative it is:
```
window.appConfig = {
  gl2ServerUrl: '',
  gl2AppPathPrefix: '/web',
  rootTimeZone: 'UTC',
};
```

**Comment by hc4** [comment]
Why not just use `window.location` for absolute URI generation in [SearchSidebar.jsx](https://github.com/Graylog2/graylog2-server/commit/d7bbcc80a2768f33a660a41ea9a291f2b24d9f86#diff-e62608365581263baaaf86a5560088e0R129)

**Comment by dennisoelkers** [comment]
@isador999: could you please do the same and post the result of fetching `$web_listen_uri/config.js`?

**Comment by isador999** [comment]
```
# curl -X GET 127.0.0.1:9000/config.js

window.appConfig = {
  gl2ServerUrl: 'http://127.0.0.1:12900/',
  gl2AppPathPrefix: '',
  rootTimeZone: 'Europe/Paris',
};
```

**Comment by dennisoelkers** [comment]
@isador999: Which url is generated for the CSV export with this setting?

**Comment by isador999** [comment]
When I want to download CSV in a stream, the following URL is generated :  
https://host.domainname/streams/5729c6e4f8c02d1bbb7620ef/679127f1-f299-414d-ae7d-4060a44b00cd:session@/api/search/universal/relative/export?query=%2A&range=300&filter=streams%3A5729c6e4f8c02d1bbb7620ef&fields=source%2Cmessage

And if I remove the  "streams/5729c6e4f8c02d1bbb7620ef/679127f1-f299-414d-ae7d-4060a44b00cd:session@/"   part or URL,  finally it works,  Graylog need auth by .htaccess prompt and then CSV can be downloaded.

**Comment by dennisoelkers** [comment]
@isador999: are you using the `X-Graylog-Server-URL`-header in your setup? Is there a reverse proxy in front of the Graylog server? Otherwise your generated URL and the `gl2ServerUrl` do not match up. Another thing: which GL version do you use?

**Comment by hc4** [comment]
Added `X-graylog-server-url: http://graylog` header and problem solved.
But still X-graylog-server-url header should not be required for relative endpoint url.

**Comment by isador999** [comment]
I have X-Graylog-Server-URL .  
Here my reverse proxy Apache configuration : 

```
    <VirtualHost *:443>
        ServerName host.domainname

        SSLEngine On
        SSLCipherSuite ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:-SSLv2:+EXP:+eNULL

        SSLCertificateFile /etc/ssl/certs/host.domainname.crt
        SSLCertificateKeyFile /etc/ssl/private/host.domainname.key

        <Location />
            RequestHeader set X-Graylog-Server-URL "/api/"
            ProxyPass http://127.0.0.1:9000/
            ProxyPassReverse http://127.0.0.1:9000/
        </Location>

        <Location /api/>
            ProxyPass http://127.0.0.1:12900/
            ProxyPassReverse http://127.0.0.1:12900/
        </Location>

        ErrorLog /var/log/apache2/host.domainname.error.log
        LogLevel warn
        CustomLog /var/log/apache2/host.domainname.access.log combined
    </VirtualHost>
```

**Comment by dennisoelkers** [comment]
@isador999: please set the value of the `X-Graylog-Server-URL` to an absolute url, in your case it should be `https://host.domainname/api`.

@hc4: relative URLs for the API endpoint are not supported currently.

**Comment by isador999** [comment]
Ok, it works thx :)
