### ISSUE TITLE
Clicking Play icon as user goes to Streams not the Search window

### ISSUE THREAD

**Issue by garbacik** [Graylog2/graylog2-server#2665]
## Expected Behavior
When one, logged in as a user, clicks the play/triangle icon on a dashboard widget, it should take you to the search screen as it does when you are an administrator. 

## Current Behavior
Currently, when clicking on the play/triangle icon as a user it quickly flashes the search screen but then takes you to the streams window. 

## Possible Solution
I'd recommend that the search window always be visible (or can be disabled via the roles). If it is  always visible, add a streams criteria dropdown option (to the right of the time criteria) like we do of the date range.

## Steps to Reproduce (for bugs)
1. Create a dashboard and add saved criteria
2. Log in as a user (local or AD authenticated) and select the dashboard
3. Click the play/triangle icon
4. The searches window briefly flashes but takes you to the streams window

## Context
Workaround: 
1. Click the info icon for the dashboard item and copy the search criteria.
2. Click the streams icon and pick the appropriate stream
3. Paste the search criteria in into the search bar

## Your Environment

* Graylog Version: 2.0.3
* Elasticsearch Version: 2.3.4
* MongoDB Version: 3.2.9-rc0
* Operating System: Redhat 7
* Browser version: Chrome 43, IE 11

**Comment by edmundoa** [comment]
Hi @garbacik,

Would you be so kind as to tell us whether the widget was created inside a stream search? Reader users can't access the "global" search page by default, and I guess that's why you get to the streams page instead.

If you don't know how to find out, clicking on the info icon for the widget should tell you if it's bound to a stream or not.

Thank you!

**Comment by garbacik** [comment]
They are not bound to a stream.

**Comment by edmundoa** [comment]
Thank you for your feedback!

That is easy to miss indeed. I'm closing this issue, as I don't see any bugs in here. By the way, we have another issue that would avoid this situation, by making it easier to grant global search permissions to reader users (#2520).
