### ISSUE TITLE
Unable to generate api token via API browser

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2668]
Trying to create token using api browser.
But error returned:
```
{
  "type": "ApiError",
  "message": "HTTP 415 Unsupported Media Type"
}
```

Looks like the problem is in Content-Type header of request:
`Content-Type:text/plain;charset=UTF-8`

But according to [sources](https://github.com/Graylog2/graylog2-server/blob/920cd37045709d0e1b9b6fb1e8ea73e1914021c4/graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java#L93) Users api consumes json:
```
@RequiresAuthentication
@Path("/users")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
@Api(value = "Users", description = "User accounts")
public class UsersResource extends RestResource {
```
and [generateNewToken](https://github.com/Graylog2/graylog2-server/blob/920cd37045709d0e1b9b6fb1e8ea73e1914021c4/graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java#L443) api doesn't have `consumes` attribute at all.

## Your Environment
* Graylog Version: 2.1.0-beta.3-SNAPSHOT+8d14878

**Comment by joschi** [comment]
@hc4 curl is working: https://gist.github.com/joschi/21bc88207881581099570dd85588f7df

**Comment by hc4** [comment]
Curl works, if you will not add tag Content-Type.
But api browser generates request with content-type plaintext, which brokes api.

This request works fine:
`curl -u ***:session -X POST "http://graylog/users/vv/tokens/surf"`

But this not:
```
curl -u ***:session -X POST -H "Content-Type:text/plain;charset=UTF-8" "http://graylog/users/vv/tokens/surf"
{"type":"ApiError","message":"HTTP 415 Unsupported Media Type"}
```

**Comment by bernd** [comment]
I updated the title and re-opened the issue.
