### ISSUE TITLE
Asset compression does not work when assets are served on REST API listener

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#2670]
## Expected Behavior

The assets served by the web interface should be compressed.

## Current Behavior

The assets are not compressed anymore, this used to work in 2.1.0-beta.2.

![image](https://cloud.githubusercontent.com/assets/461/17597151/e2714124-5ff4-11e6-8672-6767fde2dd8c.png)

![image](https://cloud.githubusercontent.com/assets/461/17597161/f3f1812a-5ff4-11e6-9af0-d81657324a9f.png)

## Steps to Reproduce (for bugs)

1. Open browser developer tools
2. Switch to network tab
3. Visit Graylog web interface
4. Check the size of the `plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.4f85f383a59224cb8447.js` file.
5. Check response headers, there is no `Content-Encoding`

## Your Environment

* Graylog Version: 2.1.0-beta.4-SNAPSHOT+d2363dd
* Operating System: Ubuntu 14.04 LTS
* Browser version: Google Chrome 52.0.2743.116

**Comment by bernd** [comment]
Is this maybe related to https://github.com/Graylog2/graylog2-server/pull/2664 ?

**Comment by joschi** [comment]
@bernd If you've configure the web interface and the Graylog REST API to use the same address and port, everything is being served by the Graylog REST API listener for which gzip compression is disabled by default: https://github.com/Graylog2/graylog2-server/blob/2.1.0-beta.3/misc/graylog.conf#L97-L99

My recommendation would be to simply activate GZIP by default for all listeners.

**Comment by bernd** [comment]
@joschi Yes, we have to enable that, at least for assets. Otherwise the web interface is pretty hard to use over slower connections.

**Comment by dennisoelkers** [comment]
Disabling GZIP for the web listeners per default was a very conservative decision. From my perspective we should enable it per default now, especially now that it's serving the web assets too.
