### ISSUE TITLE
Malformed search query error if ES cluster unavailable

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2679]
If ES cluster unavailable, graylog shows message about malformed query.
![image](https://cloud.githubusercontent.com/assets/17475270/17658813/f05e6610-62d6-11e6-97fe-d13e0401b1cb.png)

## Expected Behavior
Shoud be written, that ES cluster unavailable, because quary actualy correct.

## Context
ES throws exception `org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed`

## Your Environment
* Graylog Version: 2.1.0-beta3

**Comment by mrojas73** [comment]
Just installed 2.1.1 and I see this error when I click on the search tab.

**Comment by edmundoa** [comment]
This has been fixed in #2989.
