### ISSUE TITLE
A lot pending requests to the same URI

### ISSUE THREAD

**Issue by sega-yarkin** [Graylog2/graylog2-server#2681]
When the server has some load and cannot respond in an appropriate time we can see many pending requests to the same URI in browser's network console.

## Expected Behavior
UI waits previous request is done before doing a new one.

## Current Behavior
UI doesn't wait
![graylog_api](https://cloud.githubusercontent.com/assets/1433049/17661252/aed567c4-62e6-11e6-82a4-e8fecd48cde6.PNG)

## Steps to Reproduce (for bugs)
Make server responds slowly, open some page (e.g. system/nodes) and open browser's network console.

## Your Environment

* Graylog Version: 2.1.0-beta.3
* Elasticsearch Version: 2.3.4
* MongoDB Version: 3.0.6
* Operating System: CentOS 6.7
* Browser version: Chrome 51

**Comment by edmundoa** [comment]
Hi,

I'm closing this issue, as it is duplicating #2625. Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
