### ISSUE TITLE
Graylog2 shows different timestamp

### ISSUE THREAD

**Issue by wzczeroxa** [Graylog2/graylog2-server#2689]
## Context

I have install the graylog2 on linux redhat 7,everything is fine but i have a small promble about the 'timestamp'.
I set timezone "root_timezone = Asia/Hong_Kong",then i can see the timestamp shows the correct time in the dashboards,but when i click one log and shows the details of the log,I find that the timestamp are different,the outside timestamp shows the correct time(Asia/Hong_Kong) and there shows a incorrect timestamp(UTC time,not what i want),if i export as csv,the excel show the timestamp is UTC time,I wish both timestamp show the Asia/Hong_Kong time ,but i can't find anyother place can set that.
how can i fixup that?
![timestamp](https://cloud.githubusercontent.com/assets/21035012/17685090/851ce29c-6393-11e6-93ac-5093c930dd82.png)
![setting](https://cloud.githubusercontent.com/assets/21035012/17685099/8fc04c84-6393-11e6-8b3d-80bfdaf2492d.png)
## Your Environment

- Graylog Version:graylog-server-2.0.3-1.noarch
- Elasticsearch Version:elasticsearch-2.3.4-1.noarch
- MongoDB Version:mongodb-org-server-3.2.8-1.el7.x86_64
- Operating System:linux redhat 7
- Browser version:firefox

**Comment by jalogisch** [comment]
@wzczeroxa can you please post:

- the timezone setting of your graylog server conf
- the timezone of your server (os)
- the timezone of your logged in user (as set in graylog)

somewhere in this might be a screw-up

**Comment by wzczeroxa** [comment]
the timezone setting of my graylog server conf:
root_timezone = Asia/Hong_Kong

the timezone of my os:
Local time: 三 2016-08-17 07:54:22 CST
Universal time: 二 2016-08-16 23:54:22 UTC
RTC time: 二 2016-08-16 23:54:22
Timezone: Asia/Shanghai (CST, +0800)
NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
DST active: n/a


the timezone of your logged in user：
I just use admin to login
![timezone](https://cloud.githubusercontent.com/assets/21035012/17719990/1e131206-6451-11e6-9d76-c24f56476ccf.PNG)

**Comment by joschi** [comment]
@wzczeroxa To be honest, I don't see a problem at all.

The timestamp you've labeled as "correct" in your screenshot is identical to the timestamp you've labeled as "incorrect", they simply use a different timezone: Asia/Hong Kong (UTC+8) in the first one, UTC in the second one.

**Comment by wzczeroxa** [comment]
@joschi Thank you,but I wish the second one(UTC) can shows as the first one(UTC+8),because when it trigger an email alert or I export as csv,the timestamp shows the second one(UTC).I wish both of them can shows UTC+8,maybe somewhere should be set and I can't find it.

**Comment by wzczeroxa** [comment]
@joschi so is that timestamp display UTC time is a default configuration,and i should change that configuration somewhere,or i should set an extractor to change the display?

**Comment by eorochena** [comment]
It would be ideal if the timestamp value was inherited from the root_timezone parameter in the server.conf or offer a way in the interface to set the time zone for it

**Comment by LeDOC666** [comment]
Hi, any new, or workaround about this problem ?
I have graylog 2.2.2, and have the same difference when i open popup of timestamp, and real timestamp of a log (or on extract)
