### ISSUE TITLE
Unable to produce graphs from numeric values.

### ISSUE THREAD

**Issue by stevenmcastano** [Graylog2/graylog2-server#2690]
Graylog seems to be unable to create numeric charts.

## Expected Behavior
I have an application logging to the gray via GELF format, I've create an extractor to pull a number from the line and added the converter to numeric at the bottom. 

## Current Behavior
Then do I search and find all the lines with the new "distancetohome" field in them, and click "generate chart", but it still shows all the values on the chart as if they're zero.

## Your Environment
Single server for both graylog and elastic search

* Graylog Version: 2.0.3
* Elasticsearch Version: 2.3.5
* JVM Version: 1.8.0_101
* MongoDB Version: 3.0.12
* Operating System: Ubuntu 14.04
* Browser version: Chrome 51.0.2704.84

**Comment by joschi** [comment]
@stevenmcastano
* What kind of chart are you generating?
* What numbers are present in the `distancetohome` message field?
* What's the current schema of the Elasticsearch indices (see https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-get-mapping.html)?

**Comment by stevenmcastano** [comment]
I'm trying to generate just a simple graph. See the following... this is one that works on my system without a problem:

![screen shot 2016-08-16 at 4 59 11 am](https://cloud.githubusercontent.com/assets/6171444/17693690/32b0c372-636e-11e6-98bb-6d0ec03b7684.png)

Now I've got an application that sends messages in with the full_message like this:

```
APPDEV001 iPhoneLocation(vX.X)[55618]: DEBUG    - Location: Lat: XX.9632098796, Long: -XX.0900643245 (Is Inaccurate: False, Position Type: GPS, Distance From Home: 0.0390048933985 miles)
```
(XX's subbed in for actual data)

And I've got extractors running on the input to grab that number after `Distance From Home:` and it grabs the number fine:

![screen shot 2016-08-16 at 5 02 31 am](https://cloud.githubusercontent.com/assets/6171444/17693771/b5965662-636e-11e6-8ac0-64033a228072.png)

And you can see at the bottom I have it converting to numeric. So basically, I'd like to create a graph just like the first 1 pictured using this newly extracted number.

And here is a screen shot of it as a field showing the extractor is working:

![screen shot 2016-08-16 at 5 04 11 am](https://cloud.githubusercontent.com/assets/6171444/17693838/f51a7d2c-636e-11e6-85f4-ecd0fb71d2b9.png)

Not exactly sure how to grab the schema's you're looking for, when I run any of those commands I get a HUGE amount of output.

**Comment by joschi** [comment]
@stevenmcastano 
> Not exactly sure how to grab the schema's you're looking for, when I run any of those commands I get a HUGE amount of output.

Just attach the complete output (e. g. run `curl -X GET http://127.0.0.1:9200/graylog_deflector/_mapping?pretty > schema.json` and attach the resulting `schema.json` to this issue).

**Comment by stevenmcastano** [comment]
Moving the file from that host is a bit of a hassle, but here's the whole output:

```
{
  "graylog_52" : {
    "mappings" : {
      "message" : {
        "_ttl" : {
          "enabled" : true
        },
        "dynamic_templates" : [ {
          "internal_fields" : {
            "mapping" : {
              "index" : "not_analyzed",
              "type" : "string"
            },
            "match" : "gl2_*"
          }
        }, {
          "store_generic" : {
            "mapping" : {
              "index" : "not_analyzed"
            },
            "match" : "*"
          }
        } ],
        "properties" : {
          "LOAD_AVERAGE_1" : {
            "type" : "double"
          },
          "LOAD_AVERAGE_15" : {
            "type" : "double"
          },
          "LOAD_AVERAGE_5" : {
            "type" : "double"
          },
          "application_name" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "application_runtime" : {
            "type" : "double"
          },
          "application_version" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "asterisk_log_level" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "asterisk_module" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "asterisk_module_line_number" : {
            "type" : "long"
          },
          "connection_id" : {
            "type" : "long"
          },
          "connection_requests" : {
            "type" : "long"
          },
          "distancefromhome" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "ec2app001_application_name" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "error_level_name" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "error_level_number" : {
            "type" : "long"
          },
          "facility" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "file" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "from_asterisk" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "from_nginx" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "full_message" : {
            "type" : "string",
            "analyzer" : "standard"
          },
          "function" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "gl2_remote_ip" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "gl2_remote_port" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "gl2_source_input" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "gl2_source_node" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "hostname" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "http_referer" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "http_user_agent" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "http_version" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "inaccurate" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "lattitude" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "level" : {
            "type" : "long"
          },
          "line" : {
            "type" : "long"
          },
          "longitude" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "message" : {
            "type" : "string",
            "analyzer" : "standard"
          },
          "millis" : {
            "type" : "double"
          },
          "nginx_access" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "pid" : {
            "type" : "long"
          },
          "positiontype" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "process_id" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "process_name" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "remote_addr" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "remote_user" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "request_path" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "request_verb" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "response_bytes" : {
            "type" : "long"
          },
          "response_status" : {
            "type" : "long"
          },
          "source" : {
            "type" : "string",
            "analyzer" : "analyzer_keyword"
          },
          "streams" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "thread_name" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "timestamp" : {
            "type" : "date",
            "format" : "yyyy-MM-dd HH:mm:ss.SSS"
          },
          "virtual_hostname" : {
            "type" : "string",
            "index" : "not_analyzed"
          }
        }
      }
    }
  }
}
```

**Comment by joschi** [comment]
@stevenmcastano 
> ```json
"distancefromhome" : {
  "type" : "string",
  "index" : "not_analyzed"
}
```

The `distancefromhome` field in your Elasticsearch index is not a numeric field. Maybe there have been some string values in it from the start.

Try creating a custom index mapping for that field: http://docs.graylog.org/en/2.0/pages/configuration/elasticsearch.html#custom-index-mappings

**Comment by stevenmcastano** [comment]
I see that, I created a new field for now just to get things moving, I'll read the link on how to update the mapping. Thanks!

**Comment by ecloudbizsolns** [comment]
Similar issue, the Add button next to the numeric field converter isn't obvious that it MUST be clicked, hence when I saved the extractor I now have a field that is a string and cannot find where to change it's type or delete it.  Deleting the extractor doesn't delete the (now broken) field, so it cannot be deleted and recreated correctly either - so once junk goes in, it can't be removed/fixed? Certain I must be missing something obvious...

I have looked at the link above (http://docs.graylog.org/en/2.0/pages/configuration/elasticsearch.html#custom-index-mappings) but it doesn't describe how to change an existing data type, nor how to delete a deflector mapping together with all of it's underlying (corrupt) data. Only how to create (and then delete) a custom mapping.  I don't have a custom mapping, so not sure how that will achieve anything, and the docs are not clear on this.

I would be happy to write such doco to help others.

curl -X GET 'http://10.10.70.25:9200/graylog_deflector/_mapping?pretty'
.....
          "temp_ada0" : {
            "type" : "long"
          },
          "temp_ada0_air" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "temp_ada1" : {
            "type" : "long"
          },
...

**Comment by christrotter** [comment]
Another.  We are using a grok pattern to extract our IIS logs.
`%{DATESTAMP:timestamp} %{IP:s-ip} %{WORD:cs-method} %{URIPATH:cs-uri-stem} %{URIPARAMIIS:cs-uri-query} %{NUMBER:s-port} %{USERNAME:cs-user} %{IP:c-ip} %{NOTSPACE:cs-useragent} %{NOTSPACE:cs-referer} %{NUMBER:sc-response} %{NUMBER:sc-substatus} %{NUMBER:sc-win32-status} %{NUMBER:time-taken:int}`

NUMBER is set for a few of these fields, but when I go to 'Generate chart' for a field (e.g. sc-response), you get this error:
![image](https://cloud.githubusercontent.com/assets/8292406/19327738/7098bf16-909e-11e6-9bdb-2067680795f7.png)
(Could not create field graph - Field graphs are only available for numeric fields.)

**Comment by joschi** [comment]
@christrotter Same solution for you as for everyone else in this issue: Create a custom index mapping.

If you want to discuss this further, please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by christrotter** [comment]
If my grok pattern specifies this as a number, how is that not interpreted as a number?  As a user, I would intuitively guess that if I say 'this field is a number', I would expect it to be interpreted as such...

Having to create a custom index seems like a very complicated way to deal with this problem...?
Kinda like what @ecloudbizsolns said.

**Comment by joschi** [comment]
@christrotter `%{NUMBER}` is only the name of the grok pattern and doesn't imply any data type other than string.

And now please move this discussion to the mailing list or the IRC channel.
