### ISSUE TITLE
REST API port bind on 0.0.0.0 does not behave as expected

### ISSUE THREAD

**Issue by madchap** [Graylog2/graylog2-server#2691]
Using the openstack qcow2 image with Graylog 2.0.3.

The Graylog server has 2 network interfaces: 1 public, and 1 private.

## Expected Behavior

The REST API port should work on both public and private IPs, so that the Web UI can be reached by people, and clients (i.e. graylog-sidecar) on the private network can also register on port 12900.

## Current Behavior

Specifying the rest_listen_uri to http://0.0.0.0:12900 should make it available to both interfaces. However, the Web UI -- accessed via the public IP --  will cease functioning, complaining that the REST API on "private" IP is not reachable.

## Steps to Reproduce (for bugs)

1. Setup an openstack instance with a public IP and a private IP
2. Set the rest api to 0.0.0.0 port 12900
3. Restart graylog
4. After a bit -- or right away -- the web ui will complain it cannot access port 12900 on the private IP, whereas it should indeed reach it on the public IP.

## Context

I am trying to provide access to people on the Web UI via the public IP, while servers on the private IP range should be able to contact the server too (e.g. graylog-sidecar)

## Your Environment

* Graylog Version: Using the QCOW2 image provided by Graylog, 1 instance where everything runs.
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@madchap Please read http://docs.graylog.org/en/2.0/pages/configuration/web_interface.html and set [`web_endpoint_uri`](https://github.com/Graylog2/graylog2-server/blob/2.0.3/misc/graylog.conf#L87-L89) according to your network setup.

**Comment by madchap** [comment]
OK cool. It'd be nice to incorporate this setting directly in the qcow image, so we don't have to fight on where to make the modifications. Cheers!
