### ISSUE TITLE
alerts should send different templates/alerts to different recipients (mail)

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2694]
## Expected Behavior

Subscribe to a stream alert and choose a mail template for the recipient.
## Current Behavior

Alerts / Mail Callbacks are defined and it is only possible to subscribe to them or not. But the content could not be changed on a user base. 
## Possible Solution

Make it possible to create different Mail Templates per Alert and give the Subscriber the ability to choose which template he will get.
## Context

If you want to send your Alerts to an SMS Gateway or Ticket System which has specific design needs or limitations.  But additional send another template to other Recipients.

**Comment by coffee-squirrel** [comment]
In the same spirit as this, I'd suggest it should be possible to have alert conditions associated with different alert callbacks.  For example, I might want "50000 messages / minute" to result in a different callback than "THE SYSTEM IS DOWN!  EVERYONE PANIC!".  Currently, it seems this requires multiple streams.

**Comment by bernd** [comment]
This is now possible with the new alerting in 3.2.
