### ISSUE TITLE
Automatically create chart based on a field value

### ISSUE THREAD

**Issue by paulbakker** [Graylog2/graylog2-server#2696]
**Feature request/idea**

I'm posting JVM stats (cpu/memory usage etc.) to Graylog from each running container. I want to show these stats for each active container in a separate graph. The container id is one of the fields in the message.
Currently this can be done manually by creating a query for each container, and create a graph based on the result. Because (in our environment) containers come and go dynamically this manual process isn't convenient. Ideally you could define a graph "template", which would result in a graph per unique value of a given field.

Grafana has a very nice feature for this, which could be a source of inspiration: http://docs.grafana.org/reference/templating/

This idea is similar, but not the same as #2050.

**Comment by dennisoelkers** [comment]
This has been solved in `3.1.0`, you can now create an aggregation, add a column pivot for the field name where the differing value is in and visualize it using the chart type you want. This creates a trace for each different value in that field.
