### ISSUE TITLE
Index error and 'Indexer failures'

### ISSUE THREAD

**Issue by peterfroehlich** [Graylog2/graylog2-server#2707]
We ran into an index error today. After the defector cycled, a field was given another mapping. 

Before: 
>       "request_id": {
>         "index": "not_analyzed",
>         "type": "string"
>       },

After: 
>       "request_id": {
>         "type": "long"
>       },

That produced some confusion, a lot of lost messages and tons of errors: 

> 2016-08-17T14:54:55.050+02:00 ERROR [Messages] Failed to index [5] messages. Please check the index error log in your web interface for the reason. Error: failure in bulk execution:
> [67]: index [graylog2x_7], type [message], id [cb1fd421-6479-11e6-80b0-001c147e9f54], message [MapperParsingException[failed to parse [request_id]]; nested: N
> umberFormatException[For input string: "7e7bc059-24b3-4a33-b68b-3b05b083a4cc"];]

We fixed the mapping problem by fixing our code and are introducing an index template for elasticsearch with sane defaults. 

**Bug:** 
The 'Indexer failures' part on the Overview page did not react to the error. It stayed green and with the message: ' No failed indexing attempts in the last 24 hours.'

**Improvement:** 
It's really annoying that we lost all these messages. It there some way to drop unprocessable msgs into a file or in some deadletter system? 

* Graylog Version: 2.0.3 / 2 nodes
* Elasticsearch Version: 2.3.2 / 3 nodes
* MongoDB Version: 2.6.11 / 3 nodes
* Operating System: Centos7
* Browser version: Chrome 52.0.2743.116 (64-bit)

**Comment by kroepke** [comment]
Fixed in 2.1 by https://github.com/Graylog2/graylog2-server/pull/2644
