### ISSUE TITLE
On rest api browser page doc not expanding

### ISSUE THREAD

**Issue by avdhoot** [Graylog2/graylog2-server#2710]
On api browser page  when try to click on `show/hide` or `List Operations` page is not expanding. 
## Your Environment

- Graylog Version: 2.1.0-beta.3+b817da4

**Comment by kroepke** [comment]
Could you look at the javascript console and add which browser you are using, please?

This usually happens when either the list of API endpoints could not be loaded (due to `rest_transport_uri` problems), an entry is malformed somehow (often a whitespace character somewhere) or a Javascript exception during loading.

Thanks!

**Comment by avdhoot** [comment]
using firefox 48.0/chrome 52.0.2743.116
i see some errors in console at page load. but that error for api call containg ids like stream/dashboard(check below). after clicking on `List Operations` no error. 

```
Internal Server Error
java.net.URISyntaxException: Illegal character in path at index 53: http://xyz.com:80/api/api-docs/streams/{streamid}/alerts/{alertId}/history
     1: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:491)
     2: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:366)
     3: org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
     4: com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
     5: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     6: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     7: java.lang.Thread.run(Thread.java:745)
Root Cause: java.net.URISyntaxException: Illegal character in path at index 53: http://xyz:80/api/api-docs/streams/{streamid}/alerts/{alertId}/history
     1: java.net.URI$Parser.fail(URI.java:2848)
     2: java.net.URI$Parser.checkChars(URI.java:3021)
     3: java.net.URI$Parser.parseHierarchical(URI.java:3105)
     4: java.net.URI$Parser.parse(URI.java:3053)
     5: java.net.URI.(URI.java:588)
     6: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.getRequestUri(GrizzlyHttpContainer.java:489)
     7: org.glassfish.jersey.grizzly2.httpserver.GrizzlyHttpContainer.service(GrizzlyHttpContainer.java:366)
     8: org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
     9: com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
    10: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        ... 2 more

```

Note: raw doc page is working like `api/api-docs/cluster/metrics`

**Comment by jesperweiland** [comment]
Same issue on 2.1.0 GA

**Comment by kroepke** [comment]
The issue is that for the Stream alarm callback history part of the URL isn't url encoded completely.

Newer browser versions work with this ill-encoded URL, but some older versions reject it (Chrome 53 works, Firefox 49 as well (48 doesn't), Safari 9 also fails).

Until we find a fix, please use a recent browser version to access that section of the API browser.

**Comment by kroepke** [comment]
It appears that after all these years, I am to blame as well: https://github.com/Graylog2/graylog2-server/commit/c5fcccd6d70c8903b738569994cfd202015d2ba2

Needs figuring out whether `encodeURI` still behaves differently across browsers.

**Comment by MathMagique** [comment]
Also does not work with Safari 10 (tries to use URL http://my.host:/api/api-docs, note the colon in the URL). Can confirm it works with Firefox 49.0.
