### ISSUE TITLE
Being able to have a "quick values" showing which fields accumulated the higher values of another numeric field

### ISSUE THREAD

**Issue by Nyanyah** [Graylog2/graylog2-server#2715]
Hello,

Sorry for the (I guess) confusing title. I don't know how to explain what I'm suggesting so I'll be using an exemple.

We have a reverse proxy forwarding its log to graylog. The logs show the requests being done, with the ip address of who did the request, and the bytes consumed in the request.

I have created two extractors, for those two fields.

Right now we can only show how much bytes are being used over time with the "generate chart".

Suggestion : being able to have a "quick values" graph that show which ips used the most bytes in a specific time frame.

Regards.

**Comment by dennisoelkers** [comment]
This would now be able with the new search introduced in `3.1.0` and being the default in `3.2.0`, by creating an aggregation that has a row pivot for the ip field and a metric for the `sum` of the traffic field.
