### ISSUE TITLE
Page stuck on loading if no 'forward to' configured for collector input

### ISSUE THREAD

**Issue by JulioQc** [Graylog2/graylog2-server#2719]
## Expected Behavior

Collector config page load correctly

## Current Behavior

Page hangs at loading when clicking the configuration or accessing the URL directly (https://logs.domain.ca/system/collectors/configurations/57b497a80ae2f1065eb70edd)

## Possible Solution

- Make "Forward to" mandatory field before saving collector input config.
- Manual workaround: edit MongoDB _collector_configuration_ table to manually add the missing value to the _"forward_to" : ""_ field

## Steps to Reproduce (for bugs)

1. Create a collector config,
2. Create output config,
3. Create input (in my scenario, file input) but DO NOT fill the "Forward to" field
4. Save
5. Refresh the page or go back to it by some other mean
6. Page hangs on loading (nginx logs show some infinite loop)

## Context

No real impact if you fix it directly in MongoDB but otherwise troublesome if you need to modify that collector's configuration.
Doesn't stop collector from working (except for the one input without a forward to configured)

## Your Environment

* Graylog Version: 2.0.3 OVA
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version: Latest Chrome and Firefox

**Comment by edmundoa** [comment]
Hi @JulioQc,

Thank you for your bug report. We addressed the issue you described in https://github.com/Graylog2/graylog-plugin-collector/pull/7, and the changes will be released in 2.1.0. [Here](https://www.graylog.org/blog/66-announcing-graylog-2-1-0-beta-4) is a link to the latest beta version, in case you want to try it.

Thank you!

**Comment by JulioQc** [comment]
Alright! Thank you
