### ISSUE TITLE
Api Browser button redirects to 127.0.0.1

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2720]
Api Browser button (both on Nodes and Node page) redirects to 127.0.0.1
![image](https://cloud.githubusercontent.com/assets/17475270/17815347/9c4c06ae-663c-11e6-9819-f07da6a36e53.png)

I have web_endpoint_uri set to relative (will test with absolute uri later).
Also I have web_listen_uri and rest_listen_uri set to 127.0.0.1, and graylog accessed throught reverse proxy

## Expected Behavior
ref should be /api-browser

## Your Environment
* Graylog Version: 2.1.0-beta4

**Comment by hc4** [comment]
I have web_listen_uri and rest_listen_uri set to 127.0.0.1, and graylog accessed throught reverse proxy

**Comment by kroepke** [comment]
We probably need to document the `X-Graylog-Server-URL` header option better.
Changing the swagger code is always a pain.

**Comment by hc4** [comment]
I've added X-Graylog-Server-URL header, but API browser button still redirects to 127.0.0.1
![image](https://cloud.githubusercontent.com/assets/17475270/17851661/cc8445f8-686b-11e6-99b0-580ba32c1082.png)

**Comment by hc4** [comment]
Also checked with absolute web_endpoint_uri - still 127.0.0.1

**Comment by dennisoelkers** [comment]
@hc4: For the nodes browser, Graylog uses the transport address (`rest_transport_uri`) of each node to construct the api browser's address, as it does not know for each node how it is reachable externally, just for the current one. If you want this to work, set your `rest_transport_uri` parameter for the nodes accordingly.
