### ISSUE TITLE
Sources timerange selector changes after link click

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#2721]
## Expected Behavior

Clicking the top Sources link always has the same result, regardless of whether the user is currently on the Sources page.
## Current Behavior

Clicking the Sources link from a different page results in the timerange selector using "Keyword" and "Last Hour".  Clicking the Sources link while already on the Sources page results in the timerange selector changing to "Relative" and "Search in the last 5 minutes".
## Possible Solution

The Sources page fully reloads when the top "Sources" link is clicked.  This was my main intent when clicking the link, since it seemed the most convenient way to get fresh data (but it currently doesn't reload the content, unfortunately).
## Steps to Reproduce (for bugs)

1. Run "graylog-pre-2.1.0-beta.3-1.ova"
2. Log in as admin
3. Click the top "Sources" link
4. Note the timerange selector uses "Keyword" and "Last Hour"
5. Click the top "Sources" link again
6. Note the timerange selector changes to "Relative" and "Search in the last 5 minutes"
## Context

It would be nice to have an easier way to reload Sources page data... perhaps even an auto-update mechanism.  Currently I either refresh the page or navigate to a different page and then back to Sources.
## Your Environment

- Graylog Version:  2.1.0-beta.3+b817da4  (graylog-pre-2.1.0-beta.3-1.ova)
- Operating System:  Windows 7
- Browser version:  Firefox 48

**Comment by dennisoelkers** [comment]
The sources page is now an integrated dashboard.
