### ISSUE TITLE
Allow opening Replay Search from Dashboard in a new tab

### ISSUE THREAD

**Issue by david-sabata** [Graylog2/graylog2-server#2725]
## Expected Behavior
The Replay Search icon which can be found on each Dashboard widget should act as a regular link,
allowing middle-mouse-button click and context-menu item for opening the search in a new browser tab.

## Current Behavior
The only way of opening search in a new tab is Ctrl+click. Other standard methods don't work.

## Possible Solution
Prefer standard `<a>` element to JS events on passive elements

## Your Environment
* Graylog Version: 2.0.2 (4da1379)
* Browser version: Google Chrome 52.0.2743.116 (64-bit)

**Comment by kroepke** [comment]
@edmundoa Didn't you do a similar fix last week?

**Comment by edmundoa** [comment]
@kroepke I did so indeed. Will take this one too 👍

**Comment by edmundoa** [comment]
Fixed in #2726
