### ISSUE TITLE
Provide reasonable default when changing time range from Relative to Absolute or Keyword

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#2731]
## Expected Behavior

Switching the time range selector from Relative to either Absolute or Keyword should populate the new input(s) with the equivalent start and end datetimes (for Absolute) or keywords (for Keyword).  Bonus points for finding the closest Relative option when doing the reverse!
## Current Behavior

Time range inputs are blank (or default for Relative) after switching between modes.
## Steps to Reproduce (for bugs)

1. Log in as an admin and navigate to the Search page
2. Note the time range mode is Relative with "Search in the last 5 minutes" 
3. Change the mode to either Absolute or Keyword
4. Note the time range inputs are blank and need manual input
## Context

I often find myself wanting to tweak the time range a bit outside of what Relative allows after doing an initial search (but not enough to add new time range options).  It would be convenient to have Absolute/Keyword inputs pre-populated so only minor changes are needed for the new search.
### Environment
- Graylog Version: 2.0.3
- Elasticsearch Version:  2.2.0
- MongoDB Version:  2.6.12
- Operating System:  Red Hat Enterprise Linux Server release 6.7
- Browser version:  Firefox 48

**Comment by dennisoelkers** [comment]
This has been implemented in `3.2.0`.
