### ISSUE TITLE
enhancement: (Syslog) UDP Fields in RawText Input

### ISSUE THREAD

**Issue by rockaut** [Graylog2/graylog2-server#2739]
It would be great, if the standard RawText Input UDP could implement some of the addition sent UDP Sections like level or the facility.

With this feature it would also be possible to work around the problem of non-standard log messages are extracted faulty with standard Syslog UDP Inputs.

* Graylog Version: 2.0.3 ( appliance )

**Comment by rockaut** [comment]
Also see #2180

**Comment by joschi** [comment]
@rockaut Thanks for reporting this.

There are Syslog [facility](https://github.com/Graylog2/graylog2-server/blob/2.0.3/graylog2-server/src/main/java/org/graylog2/inputs/converters/SyslogPriFacilityConverter.java) and [level](https://github.com/Graylog2/graylog2-server/blob/2.0.3/graylog2-server/src/main/java/org/graylog2/inputs/converters/SyslogPriLevelConverter.java) converters to use with extractors and functions for the message processor pipelines (see https://github.com/Graylog2/graylog-plugin-pipeline-processor/pull/19) to cover this use case.

Additionally, adding syslog logic to the Raw/Plaintext input would totally defeat its purpose.
