### ISSUE TITLE
Source ip address in a other subnet than graylog server

### ISSUE THREAD

**Issue by thoms27** [Graylog2/graylog2-server#2754]
Hello,

I need your help for a question.

I only received syslog message on Graylog2 when my client is in the same subnet. Is it normal ? My client is a Cisco router and when I configure "logging source-interface" with a IP in an other subnet I can't the messages arrive.

Thanks in advance.

Thomas V.

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
