### ISSUE TITLE
Lack of concurrency in ProxiedResource slows down fetching of metrics in large clusters

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#2764]
## Expected Behavior

The number of total nodes should not influence the round trip times for `ProxiedResource`-based resources dramatically.

## Current Behavior

As the `ProxiedResource` calls other nodes non-parallely and synchronously, having a larger number of nodes increases the round trip time for each request.

## Possible Solution

Do calls in parallel.

**Comment by jalogisch** [comment]
fixed in https://github.com/Graylog2/graylog2-server/pull/2779
