### ISSUE TITLE
After upgrading OVA 2.0.3 to 2.1.0 my agent machine is no longer appearing in Collectors 

### ISSUE THREAD

**Issue by harrywer** [Graylog2/graylog2-server#2767]
After upgrading from OVA 2.0.3 to 2.1.0 my agent machine is no longer appearing in Collectors 

## Expected Behavior
See machine in the Collectors screen after upgrade

## Current Behavior
Cannot see machine in the Collectors screen after upgrade

## Possible Solution
None at the moment.

## Steps to Reproduce (for bugs)
Upgrade from OVA 2.0.3 

## Context
Cannot see machine in the Collectors screen after upgrade

## Your Environment
OVA 2.1.0

* Graylog Version: 2.1.0 OVA
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by jalogisch** [comment]
@harrywer 

Please give us a few more details:

- You have had some Servers in your Sidecar Configured and visible.
- after your Update of Graylog you had updated to the latest Sidecar Version.

What can be found in the Logfiles? What Sidecar Version did you use?

**Comment by harrywer** [comment]
It appears that the collector_sidecar.yml needs to be modified to work with the new version of Graylog.
The server_url setting was http://rclm.rwwaq.com.au:12900 and to get it to work I had to change it to ...
http://rclm.rwwaq.com.au:9000/api/
I now have to change 80 target machines manually to reflect the new url.

**Comment by jalogisch** [comment]
@harrywer sorry to hear that, but this was mentioned in the Upgrade Documentation: http://docs.graylog.org/en/2.1/pages/upgrade/graylog-2.1.html

But good that you find the reason.

**Comment by mariussturm** [comment]
On a side note, @harrywer it's also possible to configure the appliance back to the old value. Only the default for the API changed. With this you can leave the configuration of the Sidecars as they are:
```
sudo graylog-ctl set-listen-address --service rest --address http://0.0.0.0:12900
sudo graylog-ctl reconfigure
```

**Comment by joschi** [comment]
@mariussturm Could you please add this to the upgrade notes at https://github.com/Graylog2/documentation/blob/2.1/pages/upgrade/graylog-2.1.rst? Thanks!
