### ISSUE TITLE
Error 404 search with IE 11

### ISSUE THREAD

**Issue by Alexwii** [Graylog2/graylog2-server#2768]
## Expected Behavior

When we search someone with IE 11, we have a 404 error. Before 2.1, we had not this problem.
![image](https://cloud.githubusercontent.com/assets/3111142/18198149/4eee6950-70fb-11e6-97c9-a3c38ba63cb2.png)

## Steps to Reproduce (for bugs)

1. Search someone
2. Click on search
3. Error 404

## Context

We use IE 11 on production... We know it's not the better browser but it's the most easier update in production.

## Your Environment

* Graylog Version: 2.1
* Elasticsearch Version: 2.3
* MongoDB Version: 3.2.7
* Operating System: RHEL 6.6
* Browser version: IE 11

**Comment by joschi** [comment]
@Alexwii Which URL does your browser try to open?

Please post some details about your Graylog setup.

**Comment by Alexwii** [comment]
any search, exemple :
http://servername.company.com/search?rangetype=relative&fields=message%2Csource&width=1219&highlightMessage=&relative=300&q=source%3Atol007

What's detail you want ?

And I add when we click on next the same error appear.

**Comment by joschi** [comment]
@Alexwii Is http://servername.company.com/ the correct address for your Graylog server?

> What's detail you want ?

The complete Graylog configuration file (excluding sensitive information like `password_secret` and `root_password_sha2`), how you've installed Graylog, if you're using a reverse proxy, and some information about your network setup.

**Comment by Alexwii** [comment]
Yes, it's the correct address, I just changed the name for confidentiality.

Yes, but all is ok when I use Chrome.

Configuration files: 
http://pastebin.com/ke8gP6em

**Comment by edmundoa** [comment]
Hi @Alexwii,

I just tried to repeat the steps you provided to reproduce the issue in IE 11 but it works fine for me.

Looking at your config file, I'm seeing something odd: Your web interface should be available under `http://adressipcorrect:9000/`, but on the link you posted before the port number is gone `http://servername.company.com/search`. Was that a mistake while replacing the server name or is there some proxy in between your browser and Graylog? If there is a proxy, you should check the settings or share them to see if we can catch any mistakes there.

Thank you.

**Comment by Alexwii** [comment]
Hello @edmundoa 

We have add an iptables rules who send all connection on port 80 to port 9000.

The problem is not resolved if we use http://servername.company.com:9000/search

**Comment by edmundoa** [comment]
Now that I think of it, the 404 you are getting is not even coming from Graylog: both the Graylog web interface and the server have custom 404 pages.

By the way, you said the problem occurs when "click on search", what does exactly mean? Also, what is the URL your browser had in the navigation bar at that point?

**Comment by Alexwii** [comment]
So... I will describe in better than I can.

1. I open IE11 and I go to Graylog. I connect with my username.
2. When I am connected, I am on http://servername.company.com/search
3. When I want launch a search, I click on the magnifying glass:
![image](https://cloud.githubusercontent.com/assets/3111142/18206336/74d48606-7126-11e6-9570-d36f23f885d8.png)

3.bis Or if I want go to the next page:

![image](https://cloud.githubusercontent.com/assets/3111142/18206389/c11dfef2-7126-11e6-8d4e-dccaea9ab765.png)
4. After click, I have the error "HTTP 404 Not Found"

Maybe the cause it's my configuration. But we don't use proxy... I don't know, I continu to search...

**Comment by edmundoa** [comment]
Thank you for clarifying that.

To be honest I don't know where the issue is, but it is odd that `http://servername.company.com/search` loads in your browser, but `http://servername.company.com/search?rangetype=relative&fields=message%2Csource&width=1219&highlightMessage=&relative=300&q=source%3Asox007` does not. I tried to load that exact URL (replacing the hostname) in my test IE 11, and the page loaded without a problem.

Can you share the iptables rules you use to redirect the traffic to port 9000? Also, is there something else running in that server that may be getting that request?

**Comment by henrikjohansen** [comment]
@edmundoa We have some users that report the exact same issue ... they get a 404 when clicking on links (pagination, stream name, etc) using IE11. Using Chrome or FF resolves those 404's.

**Comment by tommy13v** [comment]
Hope it's not too simplistic but could it be related to the browser's cache?

**Comment by Alexwii** [comment]
> Can you share the iptables rules you use to redirect the traffic to port 9000? Also, is there something else running in that server that may be getting that request?

@edmundoa 
I don't think it's a problem with Iptables, because all works with Chrome and before with 2.0.3 all was fine. But ok:
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0           tcp dpt:80 redir ports 9000
REDIRECT   udp  --  0.0.0.0/0            0.0.0.0/0           udp dpt:80 redir ports 9000

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
```

And nop, we have just Graylog who use port 80/9000.

> Hope it's not too simplistic but could it be related to the browser's cache?
@tommy13v 
Already does, and don't correct the problem...

**Comment by edmundoa** [comment]
I was able to reproduce this issue by forcing IE 11 to render Graylog in "[Compatibility view](https://support.microsoft.com/en-us/help/17472/windows-internet-explorer-11-fix-site-display-problems-compatibility-view)". @Alexwii, @henrikjohansen could you please try disabling IE's compatibility view for Graylog and see if that helps with the issue? You may need to uncheck the "Display intranet sites in compatibility view" checkbox, depending on your network setups.

**Comment by Alexwii** [comment]
Your tips work, all is ok. But I don't know why we had not this problem before... !

**Comment by edmundoa** [comment]
So far I have seen two issues here: 

- Even when setting the `X-UA-Compatible` header and meta tags for IE to use the latest standards mode (as we did in 2.0, and still do), the page behaves a bit different when clicking around if it is in the compatibility view list
- We changed how we serve the web interface html in the server, and now we only serve the html asset from the URI set in `web_listen_uri` in your Graylog configuration

When the site is in IE's compatibility view list, clicking through the page triggers some extra requests to the Graylog API, that were returning the web interface html asset in 2.0, but now they return a 404. These requests don't happen when the site is not in the compatibility view list, or when using any other browser.

**Comment by Alexwii** [comment]
And you think the problem will be corrected in your future update ?

**Comment by edmundoa** [comment]
Investigating a bit more into the issue, I saw that part of what I said before is not right. We are still delivering the web interface HTML document, but checking the `Accept` header most browsers set to `text/html`. IE 11 running in compatibility mode does not set that header, and therefore doesn't get the HTML, but a 404 page.

I guess we can fix it by relaxing the condition where we deliver the HTML document. I'll keep on looking into it.
