### ISSUE TITLE
Visual Bug: Override lbstatus shows up as dead for every node

### ISSUE THREAD

**Issue by JTabel** [Graylog2/graylog2-server#2769]
Graylog2 webinterface does not show correct node status in the node overview page.

## Expected Behavior
The web interface for the node status should reflect the status of the nodes.

## Current Behavior
I installed graylog 2.1 today on one of our graylog clusters and changed the listen uris to both use the same port. Changing some of the network behaviour i wanted to test, that our loadbalancer still notices when a node goes down. When setting one of 2 graylog servers to override the lbstatus to dead, both showed up as dead in the web interface. The nodes itself behave just like expected, one is dead, one is alive and our loadbalancer notices, that only one node is down as well. After some time both servers showed up as alive, even though one was still dead. Same thing happens when I shutdown one of the servers via the web interface.

I also checked connecting to the marked dead server without the loadbalancer, but it showed both nodes as alive, so it can't be only pulling the settings of the currently used node.

Setting the node alive again however does not seem to work properly.

## Steps to Reproduce (for bugs)

1. at least 2 graylog servers with loadbalancer in front
2. Mark 1 as dead in the LB
3. should display both as dead or both as alive, not the actual status of the cluster

## Context
Since this is only a bug in the webinterface this does not affect anything, but could be confusing to people who don't know about this. Also setting a node alive again not working might possibly be harmful, if you do not know the cluster state from other sources.

## Your Environment

* Graylog Version: 2.1.0+62db7e0, codename Smuttynose (could also happen on other versions, not sure)
* Elasticsearch Version: 2.3.2
* MongoDB Version: 3.0.7
* Operating System: Ubuntu 14.04
* Browser version: Chrome Version 53.0.2785.89 (64-bit)

**Comment by jalogisch** [comment]
@JTabel did you use LB to Balance between the two Web Interfaces?

If I connect without a Loadbalance to a multi Server Setup this does not happen.

Can you please post how your Setup is configured (`rest_listen_uri`, `web_listen_uri`, `rest_transport_uri`) and all other Settings that you made for Web / REST.
Additional how your LB is configured ( round-robin balancing etc. ) and for what to where.

thank you

**Comment by JTabel** [comment]
Yes, we use the LB to load balance between the instances and yes, we use round robin for that. 

> # REST interface
> rest_listen_uri = http://0.0.0.0:9000/api
> rest_transport_uri = https://graylog.example.com:443/api
> 
> # Web interface
> web_enable = true
> web_listen_uri = http://0.0.0.0:9000
> web_endpoint_uri = https://graylog.example.com:443/api

I obfuscated the DNS name, but that is all the settings for web and rest on the graylog server. 

The loadbalancer does SSL offloading and round robin to the pool with the lbstatus as a health check. We currently have 2 servers in the pool for this instance and both have the same priority, so no server is prefered. I could test with changing the priorities of the pool members, if it is better to only use 1 server as main web interface and the other one simply as fallback.

**Comment by jalogisch** [comment]
@JTabel 

This behaviour is driven by your setup. If we test this following HAProxy configuration this can not be reproduced.


```
backend graylog
    description     The Graylog Web backend.
    balance roundrobin
    option httpchk HEAD /api/system/lbstatus
    http-request set-header X-Graylog-Server-URL http://gm-01-u.local/api
    server graylog1 192.168.0.56:9000 maxconn 20 check
    server graylog2 192.168.0.57:9000 maxconn 20 check
    server graylog3 192.168.0.58:9000 maxconn 20 check
```
