### ISSUE TITLE
Search Query Flashes Login Prompt Briefly

### ISSUE THREAD

**Issue by eroji** [Graylog2/graylog2-server#2770]
After upgrading to Graylog 2.1.0, all search queries flashes the login prompt briefly as it reloads the screen with the results.

We are using Graylog on an input server and a web frontend server set as slave and serving only the web interface using Apache proxy to HTTPS. I verified that even with no Apache proxy, the behavior is the same.

## Steps to Reproduce (for bugs)
Click on the magnifying glass or type in parameter to perform the search

## Your Environment
* Graylog Version: 2.1.0
* Elasticsearch Version: 2.0.5
* MongoDB Version: 3.2
* Operating System: CentOS 6.7
* Browser version: Chrome 52 / IE 11.0

**Comment by twgraham** [comment]
I was getting this issue before 2.1, though I think it may be more prominent in 2.1. At first I put it down to latency since I was trying to hit my Graylog cluster on east coast USA from Australia, but now I get it when running as local docker environment too.

**Comment by nilroy** [comment]
I have not seen this issue in 2.0.x but I upgraded to 2.1.0 and getting this issue.

**Comment by edmundoa** [comment]
The flashing is somehow intended when you do a full reload of the page (or there is a redirection that triggers it, like the form that is submitted when searching). Anyway, I think we can mitigate at least part of the annoyance of that flashing:

- Remove the unnecessary redirections or submits we do in the web interface (#2488)
- Change the page we display while validating the user's credentials (responsible of this flashing), so it doesn't look exactly like the login form

I think the second change is small enough that we can put it in a patch release, and it can already avoid some confusion around this.

**Comment by edmundoa** [comment]
This has been fixed in #2802
