### ISSUE TITLE
Loadbalancer Status URL has changed

### ISSUE THREAD

**Issue by mayrstefan** [Graylog2/graylog2-server#2771]
When we upgraded from version 2.0.3 to 2.1.0 we found the loadbalancer status URL changed:

Old: /system/lbstatus
New: /api/system/lbstatus

This change does not match the documentation in http://docs.graylog.org/en/2.1/pages/configuration/load_balancers.html or the upgrade guide

## Expected Behavior

From the merge of web interface and api ports I'd expect an updated documentation and an upgrade notice

## Current Behavior

Undocumented URL change. I did not check what would happen if we run the services on different ports as before

## Possible Solution

Update the documentation chapter for loadbalancing and add an upgrade notice

## Steps to Reproduce (for bugs)

1. curl -v http://localhost:9000/system/lbstatus # failing, JSON API error
2. curl -v http://localhost:9000/api/system/lbstatus # ok

## Context

After an upgrade from 2.0.3 to 2.1.0 our loadbalancer marked graylog as down

## Your Environment

* Graylog Version: 2.1.0

**Comment by joschi** [comment]
@mayrstefan The changed default URIs for the Graylog REST API has been mentioned in the Graylog 2.1.0 upgrade notes: http://docs.graylog.org/en/2.1/pages/upgrade/graylog-2.1.html#web-interface-listener

As for the documentation, we'll update the URI mentioned in the load balancer chapter.
