### ISSUE TITLE
Wrong link to API browser, URL does not work on port 9000

### ISSUE THREAD

**Issue by mayrstefan** [Graylog2/graylog2-server#2773]
Graylog version 2.1.0 links to http://127.0.0.1:12900/api-browser - but graylog does not listen on this port anymore. Manually switching to port 9000 results in a HTTP 404. Using http://127.0.0.1:12900/api/api-browser shows a login form but seems to be broken. This seems to be partial related to #2771 (URL change)

## Expected Behavior

Get a working link and API browser

## Current Behavior

Broken link and unusable API browser. The link also does not respect X-Graylog-Server-URL when accessed behind a loadbalancer or Apache httpd (might be a separate issue).

## Steps to Reproduce (for bugs)

1. Navigate to System / nodes, nodes and click on "API browser"
2. enjoy a monkey face on the 404 error page

## Context

We upgraded from version 2.0.3 to 2.1.0

## Your Environment

* Graylog Version: 2.1.0
* Browser version: FF 46

**Comment by joschi** [comment]
@mayrstefan Please post your complete Graylog configuration file (excluding sensitive information like `password_secret`, `root_password_sha2`, and credentials for MongoDB) and tell us something about your networking setup.

**Comment by mayrstefan** [comment]
The current configuration is a copy of the included graylog.conf.example with the following values changed:
- node_id_file
- password_secret
- root_username
- root_password_sha2
- root_email
- elasticsearch_cluster_name
- message_journal_dir

This means Graylog is bound to localhost. To access the web interface from remote we put an apache httpd in front of it
```
 <Location />
        RequestHeader set X-Graylog-Server-URL "http://graylog.example.org/api/"
        ProxyPass http://127.0.0.1:9000/
        ProxyPassReverse http://127.0.0.1:9000/
    </Location>
````

The server does have DNS resolution but no internet access. 

Today I updated two other instances and we got link to 127.0.0.1:9000/api/api-browser. I tried to cheat with a ssh-tunnel on port 9000. Some of the ressources have a load time >=30s

![graylog rest api browser - mozilla firefox_2016-09-06_22-57-56](https://cloud.githubusercontent.com/assets/16845342/18291037/428035c0-7486-11e6-9865-166ba77fb68a.png)

**Comment by mayrstefan** [comment]
I was confused why one of three servers showed a different link and found a difference: the ones with :9000/api instead of :12900 were restarted a second time after the upgrade. Once I restarted the first server the link changed to http://127.0.0.1:9000/api/api-browser. Now all are showing the same link.

**Comment by joschi** [comment]
@mayrstefan Thanks for your feedback. I'm closing this issue.
