### ISSUE TITLE
DNS and NTP settings reset when I issue the 'sudo reconfigure' command on my OVA installation of Graylog

### ISSUE THREAD

**Issue by harrywer** [Graylog2/graylog2-server#2774]
DNS and NTP settings reset when I issue the 'sudo reconfigure' command on my OVA installation of Graylog

## Expected Behavior
DNS and NTP settings either should be configurable using a graylog-ctl command or the chef file controlling these settings should be documented. 
Preferably the setting should be configurable using a graylog-ctl command 

## Current Behavior
DNS and NTP settings reset when I issue the 'sudo reconfigure' command 

## Possible Solution
Setting should be configurable using a 'graylog-ctl' command 

## Steps to Reproduce (for bugs)

1. Set DNS manually ( /etc/resolv.conf )
2. Issue command 'sudo reconfigure'
3. cat /etc/resolv.conf
4.

## Context
The DNS environment is incorrectly set and when I do an upgrade using the command 'sudo wget https://packages.graylog2.org/releases/graylog-omnibus/ubuntu/graylog_latest.deb' the OVA cannot contact 'packages.graylog2.org' through our proxy server.

## Your Environment

* Graylog Version:
* Elasticsearch Version: OVA 2.0.3 and OVA 2.1.0
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by jalogisch** [comment]
NTP and DNS in the OVA Image is configured via the Omnibus Package. 

To change the configured Server you need to modify the Cookbooks ( /opt/graylog/embedded/cookbooks ) - but they will be overwritten by our defaults on the next update.

Our recommendation would be to Setup your own System that you can change the settings you like to.

**Comment by harrywer** [comment]
For those that want to use the OVA image ...
sudo su - root
cd /opt/graylog/embedded/cookbooks/ntp/recipes
cp default.rb default.rb.old
vi default.rb and replace the 0.pool.ntp.org etc. values
