### ISSUE TITLE
Collectors In Cluster - error for agent - Status is Unknown

### ISSUE THREAD

**Issue by harrywer** [Graylog2/graylog2-server#2775]
After the upgrade from OVA 2.0.3 to 2.1.0 the agent reports Status of 'Unknown' after a number of minutes
## Expected Behavior
Status should be 'Running'

## Current Behavior
After the upgrade from OVA 2.0.3 to 2.1.0 the agent in Collectors in Cluster reports Status of 'Unknown' after a number of minutes. It initially reports 'Running'.
The Collector Status for the agent reports 'Status: At least one backend with errors' and 'Nxlog: Skipping snippet 57be46bb22a0c412e6ce303a till it already exist in configuration.'

## Possible Solution
None.

## Steps to Reproduce (for bugs)
1.
2.
3.
4.

## Your Environment
* Graylog Version: OVA 2.1.0
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by mariussturm** [comment]
You have two snippets with exactly the same content in your configuration. For example when you create two configurations both with the default snippet included. By definition this is a misconfiguration for NXLog. The Sidecar is filtering out those duplicates so the collector is still running but this might or might not be ok. Thats why the status is Unkown.

**Comment by rayterrill** [comment]
@mariussturm what do you mean by the "default snippet"? I'm getting this same error now and I'd like to clean it up.

I have hosts where I'm applying two configurations - for example SQL Server hosts where I'm applying both a default Windows configuration and a more specific SQLServer configuration. They're targeting different areas in the Event Log.

Windows Input configuration:
`<QueryList>\
  <Query Id="0">\
    <Select Path="Security">*</Select>\
    <Select Path="Security">*[System[(EventID=4740 or EventID=4728 or EventID=4732 or EventID=4756 or EventID=4735 or EventID=4724 or EventID=4625 or EventID=4648 or EventID=102)]]</Select>\
     </Query>\
</QueryList>`

SQLServer Input configuration:
`<QueryList>\
  <Query Id="0" Path="Application">\
    <Select Path="Application">*[System[Provider[@Name='MSSQLSERVER' or @Name='MSSQLSERVER$AUDIT']]]</Select>\
    <Suppress Path="Application">*[System[(EventID=852 or EventID=958 or EventID=3014 or EventID=3197 or EventID=3198 or EventID=3406 or EventID=3407 or EventID=3408 or EventID=3421 or EventID=3454 or EventID=6253 or EventID=6290 or EventID=6299 or EventID=8128 or EventID=9666 or EventID=9688 or EventID=9724 or EventID=10981 or EventID=15268 or EventID=17069 or EventID=17101)]]</Suppress>\
    <Suppress Path="Application">*[System[(EventID=17103 or EventID=17104 or EventID=17110 or EventID=17111 or EventID=17115 or EventID=17117 or EventID=17118 or EventID=17125 or EventID=17126 or EventID=17135 or EventID=17136 or EventID=17137 or EventID=17147 or EventID=17152 or EventID=17162 or EventID=17164 or EventID=17176 or EventID=17177 or EventID=17201 or EventID=17573)]]</Suppress>\
    <Suppress Path="Application">*[System[(EventID=17663 or EventID=17811 or EventID=18264 or EventID=18265 or EventID=18453 or EventID=18454 or EventID=18496 or EventID=19030 or EventID=26013 or EventID=26022 or EventID=26048 or EventID=26067 or EventID=26076 or EventID=33090 or EventID=33217 or EventID=33218 or EventID=49903 or EventID=49904 or EventID=49912 or EventID=49916)]]</Suppress>\
    <Suppress Path="Application">*[System[(EventID=49917)]]</Suppress>\
  </Query>\
</QueryList>`

**Comment by harrywer** [comment]
Hi Ray.

The ‘default snippet’ is the ‘Define NXLog Inputs’ section of the collector configuration for your eventlogs.
Assuming you apply both the standard Windows input collector and the SQL input collector to the same machine the standard Windows input collector you would have a ‘Define NXLog Snippet’ standard name/backend item
e.g. something like nxlog-defaults/nxlog
{{if .Linux}}
User nxlog
Group nxlog
Moduledir /usr/lib/nxlog/modules
CacheDir /var/spool/collector-sidecar/nxlog
PidFile /var/run/graylog/collector-sidecar/nxlog.pid
define LOGFILE /var/log/graylog/collector-sidecar/nxlog.log
LogFile %LOGFILE%
LogLevel INFO

<Extension logrotate>
    Module  xm_fileop
    <Schedule>
        When    @daily
        Exec    file_cycle('%LOGFILE%', 7);
     </Schedule>
</Extension>
{{end}}
{{if .Windows}}
Moduledir %ROOT%\modules
CacheDir %ROOT%\data
Pidfile %ROOT%\data\nxlog.pid
SpoolDir %ROOT%\data
LogFile %ROOT%\data\nxlog.log
LogLevel INFO

<Extension logrotate>
    Module  xm_fileop
    <Schedule>
        When    @daily
        Exec    file_cycle('%ROOT%\data\nxlog.log', 7);
     </Schedule>
</Extension>
{{end}}

For the SQL collector the ‘Define NXLog Snippet’ section would be empty because it’s already defined in the standard Windows collector.

Regards,

Harry Werkman

**Comment by jalogisch** [comment]
@rayterrill 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

You need to update the Sidecar Agent to the latest version.


Thank you!

**Comment by rayterrill** [comment]
Thanks @harrywer. @jalogisch - Just asked for clarification on this issue because it exactly matched the issue I have, was easily found, and appeared to have the fix listed (just not in a clear-enough way for me to actually implemented that).
