### ISSUE TITLE
Command 'sudo reconfigure' 'hangs' after message 'execute [apt-get-update-periodic] action run'

### ISSUE THREAD

**Issue by harrywer** [Graylog2/graylog2-server#2776]
Command 'sudo reconfigure' 'hangs' after message 'execute [apt-get-update-periodic] action run'

## Current Behavior

```
ubuntu@graylog:~$ sudo graylog-ctl reconfigure
Starting Chef Client, version 12.6.0
Compiling Cookbooks...
Recipe: graylog::default
  * directory[/etc/graylog] action create (up to date)
  Converging 122 resources
Recipe: apt::default
  * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
  * directory[/etc/apt/apt.conf.d] action create (up to date)
  * cookbook_file[/etc/apt/apt.conf.d/15update-stamp] action create (up to date)
  * execute[apt-get update] action nothing (skipped due to action :nothing)
  * execute[apt-get autoremove] action nothing (skipped due to action :nothing)
  * execute[apt-get autoclean] action nothing (skipped due to action :nothing)
  * execute[apt-get-update-periodic] action run
```

## Possible Solution

Enter control-c and it continues with the following messages;
```
nibus-ctl.rb:172:in `system': Interrupt
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:172:in `run_command'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:279:in `reconfigure'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:366:in `run'
        from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/bin/omnibus-ctl:27:in `<top (required)>'
        from /opt/graylog/embedded/bin/omnibus-ctl:23:in `load'
        from /opt/graylog/embedded/bin/omnibus-ctl:23:in `<main>'
[2016-09-05T10:14:06+08:00] FATAL: SIGINT received, stopping
[2016-09-05T10:14:06+08:00] FATAL: SIGINT received, stopping
ubuntu@graylog:~$ [2016-09-05T10:14:09+08:00] ERROR: execute[apt-get-update-periodic] (apt::default line 84) had an error: SystemExit: exit; ignore_failure is set, continuing

    
    ================================================================================
    Error executing action `run` on resource 'execute[apt-get-update-periodic]'
    ================================================================================
    
    SystemExit
    ----------
    exit
    
    Resource Declaration:
    ---------------------
    # In /opt/graylog/embedded/cookbooks/apt/recipes/default.rb
    
     84: execute 'apt-get-update-periodic' do
     85:   command 'apt-get update'
     86:   ignore_failure true
     87:   only_if { apt_installed? }
     88:   not_if { apt_up_to_date? }
     89:   notifies :touch, 'file[/var/lib/apt/periodic/update-success-stamp]', :immediately
     90: end
     91: 
    
    Compiled Resource:
    ------------------
    # Declared in /opt/graylog/embedded/cookbooks/apt/recipes/default.rb:84:in `from_file'
    
    execute("apt-get-update-periodic") do
      action [:run]
      ignore_failure true
      retries 0
      retry_delay 2
      default_guard_interpreter :execute
      command "apt-get update"
      backup 5
      returns 0
      declared_type :execute
      cookbook_name :apt
      recipe_name "default"
      not_if { #code block }
      only_if { #code block }
    end
```

## Steps to Reproduce (for bugs)

1. sudo graylog-ctl reconfigure

## Your Environment

* Graylog Version: OVA 2.1.0

**Comment by mariussturm** [comment]
During the execution of the reconfigure command the appliance need access to the internet to update certain resources. Is this possible in your environment?

**Comment by harrywer** [comment]
The appliance has access to the internet.
ping iinet.net.au
PING iinet.net.au (203.173.50.151) 56(84) bytes of data.
The /etc/environment file has been set and a .wgetrc file created.
The .deb package can be downloaded.

**Comment by harrywer** [comment]
Previous version had a status line of ...
execute[apt-get-update-periodic] action run (skipped due to not_if)

**Comment by mariussturm** [comment]
In the end it's executing `sudo apt-get update`. You can do the same on the command line and see if you'r getting a quick response or not. It could be that there are problems with the Ubuntu repositories. As you can see, we already set the `ignore_failure` flag. So an unreachable repo server would not interrupt the reconfigure run. But in your case it's connecting but never finish the update. I will check if we can set a timeout for that particular resource.

**Comment by mariussturm** [comment]
There will be a 90 sec timeout for this resource in the next appliance version. https://github.com/Graylog2/omnibus-graylog2/commit/d9ffed88efc07d3e34581277e847c8559f61b88f

**Comment by harrywer** [comment]
Thanks for the quick response.
I also tried running the command 'sudo apt-get update' manually and got the following ..
ubuntu@graylog:~$ sudo apt-get update
0% [Connecting to us.archive.ubuntu.com (91.189.91.23)] [Connecting to security
 ... followed by ...
Err http://us.archive.ubuntu.com trusty InRelease                              
  
Err http://us.archive.ubuntu.com trusty-updates InRelease                      
  
Err http://us.archive.ubuntu.com trusty-backports InRelease
  
Err http://us.archive.ubuntu.com trusty Release.gpg  
  Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable) [IP: 2001:67c:1562::16 80]
Err http://us.archive.ubuntu.com trusty-updates Release.gpg
  Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable) [IP: 2001:67c:1562::16 80]
Err http://us.archive.ubuntu.com trusty-backports Release.gpg
  Cannot initiate the connection to us.archive.ubuntu.com:80 (2001:67c:1562::16). - connect (101: Network is unreachable) [IP: 2001:67c:1562::16 80]
0% [Connecting to security.ubuntu.com (91.189.88.149)]


It looks like the appliance , when using apt-get, is trying to use IPV6.

**Comment by mariussturm** [comment]
The appliance is only using what your local DHCP server is offering. So this should be a local issue only and need to be fixed by the admin of your network.
