### ISSUE TITLE
404 on login with haproxy

### ISSUE THREAD

**Issue by oaudry** [Graylog2/graylog2-server#2778]
hello

following the documentation I got a 404 not found when I try to login.

## Expected Behavior
can login

## Current Behavior
cannot login. Got a 404 on post/get http://log.cortp.org/api/system/sessions

## Steps to Reproduce (for bugs)
here my graylog config
grep -v ^# /etc/graylog/server/server.conf |grep -v ^$ | grep uri
rest_listen_uri = http://192.168.100.92:9000/api/
web_listen_uri = http://192.168.100.92:9000/
web_endpoint_uri = http://log.corp.org:9000/api/

here my haproxy config
backend graylog
 description     The Graylog Web backend.
        acl is_api var(req.api) -m bool true
        http-request set-var(req.api) bool(true) if { path_beg /api/ }
        http-request set-path %[path,regsub(^/api/,/)]
        http-request set-header X-Graylog-Server-URL http://log.corp.org/api unless is_api
        use-server graylog_1_rest if is_api
        use-server graylog_1 unless is_api
        server graylog_1_rest 192.168.100.92:9000/api/ maxconn 20 check
        server graylog_1 192.168.100.92:9000 maxconn 20 check

## Your Environment

* Graylog Version: 2.1.0-9
* Elasticsearch Version: 2.4.0
* MongoDB Version:1:2.4.10-5
* Operating System: debian jessie
* Browser version: iceweasel  45.2.0esr-1~deb8u1

**Comment by jalogisch** [comment]
HAPRoxy is working like we document this: http://docs.graylog.org/en/2.1/pages/configuration/web_interface.html#haproxy-1-6

Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
