### ISSUE TITLE
 Elasticsearch cluster unavailable

### ISSUE THREAD

**Issue by Khaled-AlSaeed** [Graylog2/graylog2-server#2783]
Hi All,
I have this error message:

>  Elasticsearch cluster unavailable (triggered 3 hours ago)

my seeting:

Elasticsearch 1.7.5-1
elasticsearch.yml
```
cluster.name: graylog
network.host: 127.0.0.1
http.port: 9200
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["127.0.0.1", "localhost", "[::1]", "37.58.123.114"]
script.inline: false
script.indexed: false
script.file: false
```

[root@~]# curl -X GET http://127.0.0.1:9200
```
{
  "name" : "Arlok",
  "cluster_name" : "graylog",
  "version" : {
    "number" : "2.4.0",
    "build_hash" : "ce9f0xxx091dd1bc4e9469251181fc55",
    "build_timestamp" : "2016-08-29T09:14:17Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.2"
  },
  "tagline" : "You Know, for Search"
}
```

Graylog v2.1.0+62db7e0
server.conf
```
is_master = true
node_id_file = /etc/graylog/server/node-id
password_secret = xxxxxxxxxxxxxxxxxxxxxxxxx
root_username = xxxxxxxxxxxxxxxxxxxx
root_password_sha2 = xxxxxxxxxxxxxxxxxxxxx
root_email = xxxxxxxxxxxxxxxxxxxxxxxxxx
plugin_dir = /usr/share/graylog-server/plugin
rest_listen_uri = http://37.123.123.123:12900/api/
rest_transport_uri = http://0.0.0.0:12900/
rest_enable_cors = true
web_listen_uri = http://37.123.123.123:9000/
web_enable_cors = true
web_enable_gzip = true
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 1
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_discovery_zen_ping_unicast_hosts = 127.0.0.1:9200
elasticsearch_http_enabled = false
elasticsearch_analyzer = standard
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /var/lib/graylog-server/journal
lb_recognition_period_seconds = 3
mongodb_uri = mongodb://localhost/graylog
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5
content_packs_dir = /usr/share/graylog-server/contentpacks
content_packs_auto_load = grok-patterns.json
mongodb_useauth = false

```

any idea?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: v2.1.0+62db7e0
* Elasticsearch Version: 1.7.5-1
* MongoDB Version: v3.2.9
* Operating System: CentOS Linux release 7.2.1511
* Browser version: Chrome

**Comment by eorochena** [comment]
I think that your elasticsearch version is not supported on Graylog 2.0+ versions [](https://www.graylog.org/blog/55-announcing-graylog-v2-0-ga )

**Comment by joschi** [comment]
@Khaled-AlSaeed As @eorochena already mentioned: Graylog 2.x is not compatible with Elasticsearch 1.x: http://docs.graylog.org/en/2.1/pages/installation.html#system-requirements

**Comment by Khaled-AlSaeed** [comment]
sorry, I fix the version number, (2.4.0-1)  I have the latest version of all software I just install it.

**Comment by joschi** [comment]
@Khaled-AlSaeed We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

This being said, it's possible that the Elasticsearch cluster is available again and you simply haven't closed the old (at least 3 hours old) system notification in Graylog. Check the logs of your Graylog node to verify that Elasticsearch is accessible again.

**Comment by Khaled-AlSaeed** [comment]
where is the Graylog log file?

**Comment by joschi** [comment]
@Khaled-AlSaeed See http://docs.graylog.org/en/2.0/pages/configuration/file_location.html#rpm-package
