### ISSUE TITLE
Search Issue after upgrade to ES 2.4.0 and recalculate indexes

### ISSUE THREAD

**Issue by neope81** [Graylog2/graylog2-server#2785]
After an upgrade of ES cluster from 2.3.5 to 2.4 and a recalculation of indexes done by Graylog web interface. Currently we don't find any records on search based on less 8 hour time frame.

If we do a search for five minutes graylog answer with no document found instead if I search for a time frame of 8 hours I found all messages also the latest received.

* Graylog Version: 2.1.0
* Elasticsearch Version: 2.4.0
* MongoDB Version: 3.2.9
* Operating System: Centos 6.8
* Browser version: Google Chrome

**Comment by joschi** [comment]
@neope81 Are there any error messages in the logs of your Elasticsearch or Graylog nodes?

**Comment by neope81** [comment]
Unfortunately not.

Regards,

Aldo Pellini

Da: Jochen Schalanda [mailto:notifications@github.com]
Inviato: martedì 6 settembre 2016 18:19
A: Graylog2/graylog2-server <graylog2-server@noreply.github.com>
Cc: Aldo Pellini <aldo.pellini@qinet.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [Graylog2/graylog2-server] Search Issue after upgrade to ES 2.4.0 and recalculate indexes (#2785)


@neope81<https://github.com/neope81> Are there any error messages in the logs of your Elasticsearch or Graylog nodes?

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
