### ISSUE TITLE
"Plugin component missing for authenticator" when adding auth plug-in and keeping tab open

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#2786]
## Expected Behavior

Since the newly-installed SSO authentication plug-in appears in the Provider list after a Graylog Server restart I would expect its configuration to appear when the "sso"/"Single Sign-On (SSO)" link is clicked.

## Current Behavior

After placing the SSO auth plug-in (graylog-plugin-auth-sso-1.0.3.jar) in the `plugins` directory and restarting Graylog Server while keeping an existing logged-in tab open, I get [Plugin component missing for authenticator sso, this is an error.](https://github.com/Graylog2/graylog2-server/blob/686ab283f761023ab0bd4343c27b6e01f755b2a9/graylog2-web-interface/src/components/authentication/AuthenticationComponent.jsx#L54).  After doing a full page refresh the SSO auth plug-in's configuration displays as expected.

## Possible Solution

Reload authenticator info after a Graylog Server restart?

## Steps to Reproduce (for bugs)

1. Get a fresh 2.1.0 installation
2. Log in as an admin and keep the tab open on the Search page
3. Place the SSO auth plugin's JAR in the `plugins` directory used by the Graylog Server installation
4. Restart the Graylog Server service and wait for the Web interface to reload
5. Navigate to System --> Authentication
6. Note the provider name link shows up as "sso" rather than "Single Sign-On (SSO)"
7. Click the "sso" link
8. Note the content pane shows "Plugin component missing for authenticator sso, this is an error."
9. Do a full page refresh
10. Note the provider name link is now "Single Sign-On (SSO)"
11. Click the "Single Sign-On (SSO)" link and note the SSO configuration appears in the content pane as expected

## Context

The scenario I described is definitely minor, but I'm reporting it just in case it's an indicator of a larger issue.

## Your Environment

* Graylog Version:  Graylog 2.1.0+62db7e0
* Elasticsearch Version:  2.2.0
* MongoDB Version:  2.6.12
* Operating System:  Red Hat Enterprise Linux Server release 6.7
* Browser version:  Firefox 48.0.2

**Comment by jalogisch** [comment]
dup & fix https://github.com/Graylog2/graylog-plugin-auth-sso/issues/12
