### ISSUE TITLE
Time range inputs not updated when navigating back or forward in history

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#2787]
## Expected Behavior

When navigating back or forward through multiple searches the absolute time range selector's inputs should update.

## Current Behavior

When navigating back or forward through multiple searches the absolute time range inputs only show the latest values from the most recent full page load.  The URL, search query input, Fields, Histogram, and Messages list (i.e. seemingly everything else) are all restored to the expected state.

## Steps to Reproduce (for bugs)

1. Get a new 2.1.0 install
2. Log in as an admin and navigate to the Search page
3. Switch to the Absolute time range selector, enter valid start and end times ("A" and "B"), and submit the first search
4. Note the start and end times are "A" and "B" and review the search results
5. Change the absolute start and end values ("C" and "D") to something new and submit a second search
6. Note the start and end times are "C" and "D" and review the new search results
7. Press your browser's "Back" button
8. Note the start and end times are still "C" and "D" (not "A" and "B" as expected), but the first search's results are displayed

## Context

This is a bit annoying when I want to quickly and easily jump between different searches, but isn't too bad.

### Environment
* Graylog Version: 2.1.0+62db7e0 (also Graylog 2.0.3 (f07c170))
* Elasticsearch Version:  2.2.0
* MongoDB Version:  2.6.12
* Operating System:  Red Hat Enterprise Linux Server release 6.7
* Browser version:  Firefox 48.0.2

**Comment by dennisoelkers** [comment]
Thanks for your extensive bug report. Unfortunately I am not able to reproduce the issue. At step 8 I am back at the search results for the time range A-B. Is the URL changing in your browser when pressing the back button?

**Comment by coffee-squirrel** [comment]
@dennisoelkers :  I need to do some more testing, it seems.  For a little bit I was seeing things update correctly as part of what appeared to be full page reloads, but then back/forward navigation stopped doing full page refreshes (or just completed so quickly it seemed that way) and I saw the aforementioned behavior.

Yes, the URL and everything else changes as expected.

**Comment by coffee-squirrel** [comment]
I can't reliably reproduce this anymore, so it's probably best to close the issue.  If I can identify the cause I'll provide an update.
