### ISSUE TITLE
Question - For each message in Graylog is there a 'sizeof' type variable to display the size of the message.

### ISSUE THREAD

**Issue by harrywer** [Graylog2/graylog2-server#2788]
For each message in Graylog is there a 'sizeof' type variable to display the size of the message.
This is so we can get the amount of data being ingested for various agent machines.
 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@harrywer Graylog doesn't support this directly but you could use the Elasticsearch Mapper Size plugin to get the information you want: https://www.elastic.co/guide/en/elasticsearch/plugins/2.3/mapper-size.html

**Comment by harrywer** [comment]
I downloaded the plug-in 'mapper-size-2.3.1.zip'
I used the command 'sudo /opt/graylog/elasticsearch/bin/plugin install file:/tmp/mapper-size-2.3.1.zip'
to install the plug-in.
To check that the plug-in is installed I issues the command 'sudo /opt/graylog/elasticsearch/bin/plugin list' with the result ...
Installed plugins in /opt/graylog/elasticsearch/plugins:
    - mapper-size
    - kopf

I still don't see the variable created when viewing my messages.

**Comment by joschi** [comment]
@harrywer You have to add a custom index mapping as described in https://www.elastic.co/guide/en/elasticsearch/plugins/2.3/mapper-size-usage.html and http://docs.graylog.org/en/2.1/pages/configuration/elasticsearch.html#custom-index-mappings
