### ISSUE TITLE
Swagger UI may hang on loading external font

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/graylog2-server#2790]
## Expected Behavior

Open api-browser in an environment that has access to internet restricted (DNS probably works, accessing external sites blocked), UI should load properly.
## Current Behavior

It takes 30s before the request to fonts.googleapis.com timeouts, and rendering the page takes place.
## Possible Solution

Disable the loading of external resource, or vendor the font.
## Steps to Reproduce (for bugs)
1. Block http(s) requests to outside
2. Attempt to access api-browser
## Context

Most environments run their own internal DNS, and external DNS is forwarded via internal DNS configuration. That's the common practice, reducing amount of required configuration. However, most servers can not (for security reasons) actually make requests to the Internet unless the primary task of the server requires that.

A font in administrative UI is generally not a good enough reason to enable Internet connectivity for a server.

**Comment by gruselglatz** [comment]
Same here, but our API-Browser need about 2 Minutes to load.
I could provide a Browser Network Timeline dump.

![chrome_2016-09-07_11-08-59](https://cloud.githubusercontent.com/assets/15243394/18306351/b037f476-74eb-11e6-98d6-35822f709c1e.png)

![chrome_2016-09-07_11-12-52](https://cloud.githubusercontent.com/assets/15243394/18306420/111f2e1c-74ec-11e6-8b91-ec51ce0eeafc.png)

console output:
`throbber.gif:1 GET http://192.168.100.20:12900/images/throbber.gif 404 (Not Found)`

**Comment by mikkolehtisalo** [comment]
@gruselglatz I think browsers have different timeout values.

**Comment by tjyang** [comment]
I think this slow response also fail the  nagios-check-graylog2 nagios plugin.
```
[pi@nagios01 nagios-check-graylog2]$ ./nagios-check-graylog2 -insecure -l http://xxx.xxx.184.5:9000/api/api-browser  -u myid -p mypasswd
CRITICAL - Graylog2 API replied with HTTP code 404|time=0.000000;;;; total=0;;;; sources=0;;;; throughput=0;;;; index_failures=0;;;;
[pi@nagios01 nagios-check-graylog2]$
```
But failed with not found 404 error code, not timeout error/warnding(like chrome browser).

**Comment by joschi** [comment]
@tjyang No.

Your check fails because the URL seems to be wrong, see the HTTP response status code (404 - Not Found).

**Comment by tjyang** [comment]
I am able browse using  chrome from http://xxx.xxx.184.5:9000/api/api-browser URL.

I tried both  http://xxx.xxx.184.5:9000/api/api-browser and  http://xxx.xxx.184.5:9000/api all ended with 404 return code. 

Also how exactly I need to change for  "Disable the loading of external resource, or vendor the font."

**Comment by joschi** [comment]
@tjyang This sounds more like your `rest_listen_uri` and/or `web_listen_uri` URIs are different from the defaults of Graylog 2.1.0. Check your configuration files again.

**Comment by tjyang** [comment]
Thanks @joschi , Does following setting look correct to you ?

```
[root@syslog01 server]# egrep '^rest_listen_uri|^web_listen_uri'  /etc/graylog/server/server.conf
rest_listen_uri = http://xxx.xxx.184.5:9000/api/
web_listen_uri = http://xxx.xxx.184.5:9000/
[root@syslog01 server]#
```

**Comment by tjyang** [comment]
Also the slow return of api url was due to version change from 2.0.3 to 2.1.0. 
Can this change be reversed ?

**Comment by jalogisch** [comment]
if you set the `rest_listen_uri` and `web_listen_uri` in your setup correct and maybe add `rest_transport_uri` when working with a proxy setup. I notice that loading `handlebars` creates a delay.

Safari: Version 9.1.3 (11601.7.8)
![graylog_rest_api_browser](https://cloud.githubusercontent.com/assets/404238/18433785/c9608254-78e9-11e6-8c97-6296fc9147e8.png)

In Chrome jquery looks like the problem. 

Chrome: Version 53.0.2785.101 (64-bit)
![chrome_version_53_0_2785_101_api-browser](https://cloud.githubusercontent.com/assets/404238/18433906/60d0cbbc-78ea-11e6-9474-ef593261cde7.png)

So we have two *problems* that have the same behaviour here:
1.  Loading external content when Graylog is not able to connect to the *world*
2. Loading content to display the api-browser takes very long time 

I have this issue in OS Package Setup and the OVA Image! Graylog 2.1 GA

**Comment by jalogisch** [comment]
did a second request with both browsers:

![safari_second_request](https://cloud.githubusercontent.com/assets/404238/18434325/cc15f940-78ec-11e6-9795-fedcbbdcc821.png)
![chrome_second_call](https://cloud.githubusercontent.com/assets/404238/18434331/d13a6e6a-78ec-11e6-935e-bfd2139f5fb5.png)
