### ISSUE TITLE
Search is broken when there is one Index with 0 Messages in them

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#2791]
Delete every message in an index, trigger the timerange-recalc and try to search something.

It will always work until the "Time since last index recalc" is bigger than the "Search Time-range".

So if you recalculated it 30 mins ago, you can search messages and get the newest ones until your Search timerange is bigger than 30 mins.

When the empty index gets deleted, everything works normal.
## Expected Behavior

Search should display Messages.
## Current Behavior

described above
## Possible Solution

delete the index manualy
delete it on index recalc?
keep the old time-range?
## Steps to Reproduce (for bugs)
1. delete all messages in an index, keep the index
2. search
3. see nothing
4. delete index
5. search works again (no msg lost) its only a display bug
## Context

It looks like there are no Messages, but they are there but not displayed.
It comes from our IP-Based Retention script. Normally not every Messages gets deleted, but one time we had this situation.
## Your Environment
- Graylog Version: 2.1.0GA
- Elasticsearch Version: 2.3.5
- MongoDB Version: -
- Operating System: -
- Browser version: Chrome 50+

**Comment by dennisoelkers** [comment]
Could you please add some details, especially about the time ranges of the indices? Deleting all messages from an index is a rather uncommon scenario, but when I just tried to reproduce it, everything worked as expected.

**Comment by gruselglatz** [comment]
@dennisoelkers I know that deleting every message is not the common way, but in our situation it can happen.
Our Setup in detail:
Graylog: 
* Rotate indices every 24h
* Keep 45 indices

Script does the following:

1. Find indices for given deletion action
2. set index block write = false
3. delete by query
4. set index block write = true
5. _optimize?only_expunge_deletes=true
6. system/indices/ranges/rebuild
7. done

Index after delete by query (search is working normal):

![index 0 good](https://cloud.githubusercontent.com/assets/15243394/18380373/4b1160b8-7677-11e6-8210-cae1292a3cd4.png)

Index after optimize to clear space(search is working normal):
![index 0 good after optimize](https://cloud.githubusercontent.com/assets/15243394/18380380/5ca6121a-7677-11e6-8960-11016f2adf3e.png)

Index after range recalc (Search stopped working):
![index 0 bad after rebuild](https://cloud.githubusercontent.com/assets/15243394/18380406/767b1898-7677-11e6-8466-64afaa160366.png)

Search query:
`{
  "from": 0,
  "size": 150,
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": {
        "bool": {
          "must": {
            "range": {
              "timestamp": {
                "from": "2016-09-09 08:16:13.616",
                "to": "2016-09-09 08:21:13.616",
                "include_lower": true,
                "include_upper": true
              }
            }
          }
        }
      }
    }
  },
  "sort": [
    {
      "timestamp": {
        "order": "desc"
      }
    }
  ]
}`

Index Metadata: 
`{
  "index_name": "graylog_16",
  "begin": "1970-01-01T00:00:00.000Z",
  "end": "1970-01-01T00:00:00.000Z",
  "calculated_at": "2016-09-09T08:13:39.702Z",
  "took_ms": 0
}`

To get some results i have to set the search range higher, when i do that i get this:
`Indices used for this search:
graylog_16
graylog_53`

I hope this is helpful.

**Comment by kroepke** [comment]
We'll try to recreate this one more time.

**Comment by compuvin** [comment]
I am having a similar issue after upgrading to Graylog 2.1.1+01d50e5. I don't have any empty indexes however. It is almost like it is not automatically recalculating the index as new messages are coming in. If I manually recalculate the index, messages show up in the "last 5 minutes" search. However, over time, I need to change the search to "last day" to see messages that came in a few seconds ago.

**Comment by compuvin** [comment]
It appears to be working fine for me after manually cycling the deflector

**Comment by dennisoelkers** [comment]
This does not appear to be an issue anymore, therefore I am closing this issue. If it still is, please reopen the issue and we will take a look.
