### ISSUE TITLE
Make possible to change username

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2792]
I need to rename all users to uppercase, to make possible SSO auth.
As I understand graylog internally tracks users by id, not by username.
So it should be safe to change username for user.

## Your Environment
* Graylog Version: 2.1.0 GA

**Comment by jalogisch** [comment]
@hc4 you will need to Edit the Mongo Collection *users* - that is an edge case that Graylog does not need to cover.

You can do this by yourself on the command line.

**Comment by joschi** [comment]
@hc4 
> As I understand graylog internally tracks users by id, not by username.

No, the username and not the internal MongoDB ID is being used in most places, which is why we don't support renaming users once they've been created.
