### ISSUE TITLE
Need help with configuring graylog server with different hostname in openstack setup.

### ISSUE THREAD

**Issue by Abhilash-vaidhya** [Graylog2/graylog2-server#2796]
Hi All,
I have installed a graylog server instance in the openstackset up  with a different instance name graylog_test.
So whenever i do cli login using sshkeys,my hostname looks like this ubuntu@graylog-test:~$
But when i try to run reconfigure command ,the graylog hostname doesnt resolve and  the services fail to start.Below is the screenshot attached.

ubuntu@graylog-test:~$ sudo graylog-ctl reconfigure
sudo: unable to resolve host graylog-test
Starting Chef Client, version 12.4.1
Compiling Cookbooks...
Recipe: graylog::default
  * directory[/etc/graylog] action create
    - create new directory /etc/graylog
    - change mode from '' to '0775'
    - change owner from '' to 'root'
    - change group from '' to 'root'

Please let me know what configuration changes need to be mandated in graylog server if hostname is changed.

Any solutions on this will be much appreciated :-)

Regards,
Abhilash

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
