### ISSUE TITLE
Live reload fires new request without checking if there is an existing one

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#2799]
## Expected Behavior

The live reload should wait for a response before executing another search request to avoid overloading the server and Elasticsearch cluster.

## Current Behavior

The live reload fires new search requests against the server according to the live reload interval even if a previous request didn't return yet. (i.e. caused by an overloaded Elasticsearch cluster or a high latency network connection to the Graylog server)

The following screenshot shows an example of this behavior.

![image](https://cloud.githubusercontent.com/assets/461/18354946/ce616a52-75e7-11e6-80ec-4bdd00037597.png)

## Possible Solution

- The client code should only issue a new search request if the previous one has returned
- It should also ensure to wait according to the selected live reload interval before running the next request

## Steps to Reproduce (for bugs)

1. Enable live reload with a search query that takes longer than the selected live reload interval
2. Open the network tab in the developer console
3. See lots of pending search requests

## Your Environment

* Graylog Version: 2.1.1-SNAPSHOT+6e974b0
* Browser version: 53.0.2785.101

**Comment by dennisoelkers** [comment]
We can solve it similar to #2712. Search is using some really old school code though, so I am gonna check how hard that's gonna be :)
