### ISSUE TITLE
Graylog Search and Streams Pages are really slow (> 13s) with 3000+ streams  

### ISSUE THREAD

**Issue by jehuty0shift** [Graylog2/graylog2-server#2805]
To test Graylog performance i created more than 3000 streams with one rule each, thanks to the API. No problem so far with the creation but some pages related to streams are slow. 

## Expected Behavior
I expect that creation of 3000 stream, could indeed have an impact on Stream Routing but i didn't expect to have any impact on anything else, Stream page, search and everything that is related to streams. In the result, the search page for example becomes really slow (>15s) even when the Elasticsearch cluster returns results in milliseconds. 

## Current Behavior
Actually the call to GET /streams endpoint on API is sufficient to trigger the problem. Since that call is done on Search page (i checked it with the Chrome Console) and on Streams page, they become slow to render (> 15 seconds). That made the whole thing unusable even for an user that has access to only zero or one stream.   

In a simple plugin I trace a call to StreamService.loadALlEnabled() by using this code. 
`           long start = System.currentTimeMillis();
            List<Stream> streamsEnabled = streamService.loadAllEnabled();
            LOG.debug("retrieving Streams took : " + (System.currentTimeMillis() - start) + " ms");
`
that print time ranging from 13000 ms to 16000 ms. 

## Possible Solution
I track the problem down to the way you implemented the retrieving of streams. The Rest API does only call [StreamService](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java#L178). The implementation of [StreamService](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java#L130) is not efficient enough since it caused a call to StreamRuleService that hits the Database for every Rule of every Stream. My mongo DB cluster (3 nodes) [returns a rule result in about 0-2 ms range](https://gist.github.com/jehuty0shift/58b4f82db4f38d6345153c591373cf33) in the mongo console  that leads to at least 6 seconds for (3000+ stream) to retrieve only the rules. Add the network penalty due to every hit, and we spend 15 seconds+ just to retrieve all the rules.
The solution is the following : It should be faster to retrieve all the rules at once and then assign them to their stream by using pure Java Code. 
The worst case of this solution i can see is when you have just a couple of stream with thousands of rules or when you actually only want enabled streams and you have only a few enabled on thousands ones. Theses special cases are unlikely or can be treated separately.

This means to add a global `List<StreamRule> load()` method in both the StreamRuleService interface and the StreamRuleServiceImpl. 

## Steps to Reproduce (for bugs):
1. Create thousands on stream using the APIs
2. Go the Search Page or the stream Page and monitor the call to /streams endpoint. 

## Context
I'm currently testing plain Graylog performance for Enterprise use cases vs Custom solutions.

## Your Environment
* Graylog Version: 2.1.0
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.2.6
* Operating System: Debian Jessie
* Browser version: Chrome version 51

**Comment by Spea** [comment]
We are currently experiencing the same issue with version 2.1.1+01d50e5 , is there any ETA for this?

**Comment by mejje** [comment]
Is it necessary to have the calls to /api/streams on the /search page blocking display of the search result? I can't see any references to the streams on that page.

**Comment by joschi** [comment]
@mejje If you have another problem, please open a new issue.

**Comment by mejje** [comment]
Not really, it's just still very slow. I noticed some more activity by bjoernhaeuser so I guess I'll wait and hope :)

**Comment by aixocm** [comment]
how to slove  this problem  that Graylog Search and Streams Pages are really slow (> 13s) with 3000+ streams
