### ISSUE TITLE
To specify an alternate server AD

### ISSUE THREAD

**Issue by angelsedoy** [Graylog2/graylog2-server#2806]
Good afternoon! Please tell me, is it possible to specify an alternate server AD?

* Graylog Version: 2.0
* Elasticsearch Version: 2.3.4
* MongoDB Version: 3.2.8
* Operating System: ubuntu 14.04
* Browser version: Chrome

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
