### ISSUE TITLE
Login button has no loading indicator

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#2807]
When trying to log in, there is no indicator that the request was actually fired and the system is working on processing the login. This can be very confusing if the login process takes a few seconds and you think no action was triggered after clicking the button.

**Comment by edmundoa** [comment]
Which version are you using? This has been around since 2.1

**Comment by dennisoelkers** [comment]
I just verified it, this is not the case for 2.1.
