### ISSUE TITLE
Extract Kafka transport into plugin

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#2813]
Graylog currently ships support for Apache Kafka in the core distribution and includes a complete Apache Kafka instance ([`org.apache.kafka:kafka_2.11:0.9.0.1`](http://mvnrepository.com/artifact/org.apache.kafka/kafka_2.11/0.9.0.1) as of Graylog 2.1.0).

This is a problem because Graylog itself is using the Kafka Log internally and is prone to changes of the on-disk format, and the used Kafka Scala client isn't backward-compatible to old Kafka brokers (e. g. Graylog 2.1.0 with [Kafka 0.9.0.1 cannot consume messages from Kafka 0.8.2.0 and older](https://groups.google.com/d/msg/confluent-platform/r8xox149Vn4/MQ6ObafvBQAJ)).

Additionally, depending on [`org.apache.kafka:kafka_2.11`](http://mvnrepository.com/artifact/org.apache.kafka/kafka_2.11) pulls in a Scala dependency which is otherwise unused and introduces some inefficiencies when using the Kafka Log (having to convert between Scala and Java collections).

In order to address these issues, we should do the following:
- Write a Java-only version of the Kafka Log (@bernd did this in the past with [Samsa](https://github.com/bernd/samsa), although we should at least update this effort to the latest version of the Kafka Log) – unrelated to this issue.
- Extract the Kafka transport (and thus the Kafka-based inputs) into a plugin and rewrite them using the modern, Java-based Kafka consumer.
## Additional sources
- http://www.confluent.io/blog/tutorial-getting-started-with-the-new-apache-kafka-0-9-consumer-client/
- https://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html
- https://cwiki.apache.org/confluence/display/KAFKA/Client+Rewrite
- https://cwiki.apache.org/confluence/display/KAFKA/Consumer+Group+Example
- https://cwiki.apache.org/confluence/display/KAFKA/0.8.0+SimpleConsumer+Example

**Comment by bernd** [comment]
We solved this by using a shaded version of the old Kafka library for our journal implementation and updated the Kafka client libraries to a recent version.
