### ISSUE TITLE
Cannot generate statistics from numeric field

### ISSUE THREAD

**Issue by harrywer** [Graylog2/graylog2-server#2816]
Cannot generate statistics from numeric field
## Expected Behavior
Statistics should be generated

## Current Behavior
Cannot generate statistics from numeric field  - applied a grok pattern to IIS log file

## Steps to Reproduce (for bugs)
1. Ingest IIS log
2. Apply grok pattern to produce numeric field - (time-taken)
3. Search for message
4. Generate statistics

## Context
Cannot generate appropriate dashboard for end user

## Your Environment
* Graylog Version: 2.1.0 (OVA)
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version: Chrome 52.0.2743.116 m

grok pattern ;
```
%{TIMESTAMP_ISO8601:log_timestamp} %{WORD:s-sitename} %{WORD:s-computername} %{IP:s-ip} %{WORD:cs-method} %{URIPATH:uri-stem} %{DATA:cs-uri-query} %{INT:s-port} %{DATA:cs-username} %{IP:c-ip} %{NOTSPACE:cs-version} %{NOTSPACE:cs_user_agent} %{NOTSPACE:cs_cookie} %{NOTSPACE:cs_refer} %{NOTSPACE:cs-host} %{NUMBER:sc-status} %{NUMBER:sc-substatus} %{NUMBER:sc-win32-status} %{NUMBER:sc-bytes} %{NUMBER:cs-bytes} %{NUMBER:time-taken} %{IP:x-forwarded-for}
```

**Comment by joschi** [comment]
@harrywer 
* Which message field do you want to create a graph for?
* What's the content of this field?
* Are you 100% sure, that this is a purely numeric field? If you want to make sure it is, create a custom Elasticsearch index mapping: http://docs.graylog.org/en/2.1/pages/configuration/elasticsearch.html#custom-index-mappings

**Comment by harrywer** [comment]
Hi Jochen.

The field in question is an grok pattern extracted field from the IIS 8.5 logs (time-taken) which was defined as ‘NUMBER’.
However, it appears that ‘graylog’ treats any extracted field as a string.
I resolved the issue by removing the grok pattern and using the following in an NXlog Snippet for the IIS log ingest.
{{if .Windows}}
<Extension w3c>
Module xm_csv
Fields $date, $time, $s-sitename, $s-computername, $s-ip, $cs-method, $cs-uri-stem, $cs-uri-query, $s-port, $cs-username, $c-ip, $cs-version, $csUser-Agent, $csCookie, $cs-Referer, $cs-host, $sc-status, $sc-substatus, $sc-win32-status, $sc-bytes, $cs-bytes, $time-taken, $x-forwarded-for
FieldTypes string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, string, integer, integer, integer, string
 Delimiter ' '
  QuoteChar '"'
  EscapeControl FALSE
  UndefValue -
</Extension>
{{end}}
… and for the input file of the IIS logs in the Add Verbatim Configuration ..
Exec $size = size($raw_event);
Exec if $raw_event =~ /^#/ drop(); \
else \
{ \
w3c->parse_csv(); \
$EventTime = parsedate($date + " " + $time); \
$EventTime = strftime($EventTime, "%Y-%m-%dT%H:%M:%SZ"); \
$SourceName = "IIS"; \
}

This created the correct collector-sidecar nxlog configuration.

Regards,

Harry Werkman

**Comment by joschi** [comment]
Thanks for the feedback! Since you could resolve the issue, I'm closing this ticket.
