### ISSUE TITLE
External authentication (SSO) requires LDAP

### ISSUE THREAD

**Issue by zagy** [Graylog2/graylog2-server#2817]
When using the SSO plugin, you also need to enable LDAP. Otherwise users are not being logged in. It throws "LDAP authentication is currently disabled." from https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/security/realm/SessionAuthenticator.java#L73

## Expected Behavior

I'd expect Graylog not to prevent other plugins (the SSO plugin here) to authenticate externally even when there is no LDAP configured. 

## Current Behavior

Login via SSO not possible due to error "LDAP authentication is currently disabled". Login form shown. 

It works after LDAP is enabled. In fact it's sufficient that LDAP is enabled, regardless if the configuration is actually working

## Steps to Reproduce (for bugs)

Well …

1. Have SSO capable graylog and appropriate proxy.
2. Turn off LDAP on the LDAP configuration page
3. SSO Login doesn't work.
4.

* Graylog Version: v2.1.0+62db7e0

**Comment by kroepke** [comment]
Thank you for your contribution, we'll see that it gets fixed in 2.1.1.
