### ISSUE TITLE
Date detection with Gelf -> error since update

### ISSUE THREAD

**Issue by jothoma1** [Graylog2/graylog2-server#2819]
Since last update (Graylog & Elasticsearch). I have some indexer failures with a timestamp field, it was working fine before updates

## Current Behavior

Logs comes from apache with a log format in JSON. NXLog parse the file and transfers it in GELF to Graylog. Before the update it worked like a charm and now i have a lot of this _MapperParsingException[failed to parse [httpd_timestamp]]; nested: IllegalArgumentException[Invalid format: "2016-09-13T09:47:18.msec_frac+0200" is malformed at ".msec_frac+0200"];_

## Possible Solution

Is it something with date detection in Elasticsearch ? 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 2.1.0
* Elasticsearch Version: 2.4.0
* MongoDB Version:
* Operating System: CentOS 7
* Browser version:

**Comment by joschi** [comment]
@jothoma1 If there's really the string "msec_frac" in the `httpd_timestamp` field, it's very likely to be an invalid Apache httpd logging configuration.

https://httpd.apache.org/docs/current/mod/mod_log_config.html

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
