### ISSUE TITLE
SSH Streams function is not working (graylog-2.0.3-1 ).

### ISSUE THREAD

**Issue by nanotechz9l** [Graylog2/graylog2-server#2824]
Creating a stream does not parse logs and display messages. 

## Steps to Reproduce (for bugs)
http://stackoverflow.com/questions/29121554/graylog2-ssh-stream-rules

1. Create an ssh stream and call it SSH accepted/failed
2. Then create a rule where you enter
  2.1. field : messages
  2.2. type : match regular expression
  2.3. value for failed: Failed password for.+ from .+

and then create a new rule for the same stream with the value : Accepted password for.+ from .+

The above stream is supposed to collect Failed and Accepted SSH logins but does not work.

Note: If I manually search for ssh logs and test against the stream it does work - however when I click on the stream it does not show any logs/messages.

## Context
This issue affects me because I need to read my accepted/failed ssh logs.

## Your Environment
* Graylog Version: graylog-2.0.3-1 
* Elasticsearch Version:
MongoDB 3.2.5
Ubuntu
Firefox / Chrome latest

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. 

Please post issues to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

I just have checked your rules in my setup and as this is working this looks like a local issue on your setup. If the [documentation](http://docs.graylog.org/en/2.1/) does not help you, please use the above-mentioned options to get assistance.

![issue_2824](https://cloud.githubusercontent.com/assets/404238/18503172/aef7fd3e-7a5b-11e6-858c-76330fc27609.png)

**Comment by nanotechz9l** [comment]
Understood thanks!
