### ISSUE TITLE
CEF UDP Plugin does not handle non-standard (other than Application, Security, System) in post-Vista Windows forwarded by OSSEC Server.

### ISSUE THREAD

**Issue by gjahchan** [Graylog2/graylog2-server#2825]
Windows event logs other than the Application, Security and System logs in post-Vista flavors of Windows are silently dropped by the CEF UDP Plugin in Graylog2.

## Expected Behavior

These events should be logged, much like any other event picked up by the CEF UDP plugin from OSSEC alerts.json file.

## Steps to Reproduce (for bugs)

I will use an AppLocker event as an example:

In OSSEC alerts.json:
<snip>
{"rule":{"level":2,"comment":"Windows - AppLocker allowed program to run.","sidid":18302,"firedtimes":13,"groups":["windows","applocker"],"PCI_DSS":["10.2.2","10.6.1"]},"dstuser":"GJahchan","full_log":"2016 Sep 14 10:44:43 WinEvtLog: Microsoft-Windows-AppLocker/EXE and DLL: INFORMATION(8002): Microsoft-Windows-AppLocker: GJahchan: DESKTOP: Desktop: %SYSTEM32%\\NSLOOKUP.EXE was allowed to run.","id":"8002","status":"INFORMATION","data":"Microsoft-Windows-AppLocker","systemname":"Desktop","decoder":{"name":"windows"},"hostname":"Win10EntDsktp","agentip":"192.168.16.1","timestamp":"2016 Sep 14 10:44:56","location":"WinEvtLog"}
<snip>

In Elasticsearch: (OSSEC alerts.json --> filebeat --> logstash --> elasticsearch)
{
  "_index": "ossec-2016.09.14",
  "_type": "ossec",
  "_id": "AVcnqBakhBmn8wp-jU8U",
  "_score": null,
  "_source": {
    "rule": {
      "sidid": 18302,
      "firedtimes": 13,
      "groups": [
        "windows",
        "applocker"
      ],
      "PCI_DSS": [
        "10.2.2",
        "10.6.1"
      ],
      "description": "Windows - AppLocker allowed program to run.",
      "AlertLevel": 2
    },
    "dstuser": "GJahchan",
    "full_log": "2016 Sep 14 10:44:43 WinEvtLog: Microsoft-Windows-AppLocker/EXE and DLL: INFORMATION(8002): Microsoft-Windows-AppLocker: GJahchan: DESKTOP: Desktop: %SYSTEM32%\\NSLOOKUP.EXE was allowed to run.",
    "id": "8002",
    "status": "INFORMATION",
    "data": "Microsoft-Windows-AppLocker",
    "systemname": "Desktop",
    "decoder": {
      "name": "windows"
    },
    "location": "WinEvtLog",
    "@version": "1",
    "@timestamp": "2016-09-14T07:44:56.000Z",
    "fields": null,
    "offset": 1937063,
    "count": 1,
    "input_type": "log",
    "beat": {
      "hostname": "capricorn",
      "name": "capricorn"
    },
    "source": "/var/ossec/logs/alerts/alerts.json",
    "type": "log",
    "host": "capricorn",
    "tags": [
      "ossec",
      "beats_input_codec_json_applied"
    ],
    "AgentName": "Win10EntDsktp",
    "AgentIP": "192.168.16.1",
    "machine": "false"
  },
  "fields": {
    "@timestamp": [
      1473839096000
    ]
  },
  "highlight": {
    "AgentName": [
      "@kibana-highlighted-field@Win10EntDsktp@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1473839096000
  ]
}

In Graylog2: (OSSEC alerts.json --> OSSEC csyslogd --> Graylog CEF UDP Plugin --> Graylog
Zero Applocker events.

I can confirm that OSSEC csyslogd is indeed forwarding AppLocker events by dumping traffic to udp port 2514:

$ sudo tcpdump -i lo -vvv -nn -p -A udp and port 2514
<snip>
11:11:10.500410 IP (tos 0x0, ttl 64, id 56708, offset 0, flags [DF], proto UDP (17), length 507)
    127.0.0.1.59218 > 127.0.0.1.2514: [bad udp cksum 0xfffa -> 0xc1dc!] UDP, length 479
E.....@.@.]k.........R  .....<132>Sep 14 11:11:09 CEF:0|Trend Micro Inc.|OSSEC HIDS|v2.8|18302|Windows - AppLocker allowed program to run.|2|dvc=capricorn cs2=(Win10EntDsktp) 192.168.16.1->WinEvtLog cs2Label=Location classification= windows,applocker,pci_dss_10.2.2,pci_dss_10.6.1, suser=GJahchan suser=GJahchan msg=2016 Sep 14 11:10:56 WinEvtLog: Microsoft-Windows-AppLocker/EXE and DLL: INFORMATION(8002): Microsoft-Windows-AppLocker: GJahchan: DESKTOP: Desktop: %SYSTEM32%\NSLOOKUP.EXE was allowed to run.
<snip>

1. Activate AppLocker in Audit mode on Windows system with OSSEC Agent installed.
2. Configure agent to collect the AppLocker logs (in /var/ossec/etc/shared/agent.conf on OSSEC server):
<agent_config name="AgentName">
  <localfile>
    <log_format>eventchannel</log_format>
    <location>Microsoft-Windows-AppLocker/EXE and DLL</location>
  </localfile>
  <localfile>
    <log_format>eventchannel</log_format>
    <location>Microsoft-Windows-AppLocker/MSI and Script</location>
  </localfile>
  <localfile>
    <log_format>eventchannel</log_format>
    <location>Microsoft-Windows-AppLocker/Packaged app-Deployment</location>
  </localfile>
  <localfile>
    <log_format>eventchannel</log_format>
    <location>Microsoft-Windows-AppLocker/Packaged app-execution</location>
  </localfile>
</agent_config>

3. Add the following AppLocker-specific rules to /var/ossec/rules/local_rules.xml:
...

<group name="windows,applocker,">
  
  <rule id="18300" level="2">
    <if_sid>18103</if_sid>
    <id>^8000$</id>
    <description>Windows - Application Identity Policy conversion failed.</description>
    <group>pci_dss_10.6.1,</group>
  </rule>

  <rule id="18301" level="2">
    <if_sid>18101</if_sid>
    <id>^8001$</id>
    <description>Windows - AppLocker policy was applied successfully to this computer.</description>
    <group>pci_dss_10.6.1,</group>
  </rule>

  <rule id="18302" level="2">
    <if_sid>18101</if_sid>
    <id>^8002$</id>
    <description>Windows - AppLocker allowed program to run.</description>
    <group>pci_dss_10.2.2,pci_dss_10.6.1,</group>
  </rule>

  <rule id="18303" level="2">
    <if_sid>18102</if_sid>
    <id>^8003$</id>
    <description>Windows - AppLocker allowed program to run in audit mode.</description>
    <group>pci_dss_10.2.2,pci_dss_10.6.1,</group>
  </rule>

  <rule id="18304" level="12">
    <if_sid>18103</if_sid>
    <id>^8004$</id>
    <description>Windows - AppLocker blocked program.</description>
    <group>pci_dss_10.6.1,</group>
  </rule>

  <rule id="18305" level="2">
    <if_sid>18101</if_sid>
    <id>^8005$</id>
    <description>Windows - AppLocker allowed an MSI or script to run.</description>
    <group>pci_dss_10.2.2,pci_dss_10.6.1,</group>
</rule>

  <rule id="18306" level="2">
    <if_sid>18102</if_sid>
    <id>^8006$</id>
    <description>Windows - AppLocker allowed an MSI or script to run in audit mode.</description>
    <group>pci_dss_10.2.2,pci_dss_10.6.1,</group>
  </rule>

  <rule id="18307" level="12">
    <if_sid>18103</if_sid>
    <id>^8007$</id>
    <description>Windows - AppLocker prevented an MSI or script to run.</description>
    <group>pci_dss_10.6.1,</group>
  </rule>

  <rule id="18308" level="2">
    <if_sid>18101</if_sid>
    <id>^8020$</id>
    <description>Windows - Packaged app allowed.</description>
    <group>pci_dss_10.2.2,pci_dss_10.6.1,</group>
  </rule>

  <rule id="18309" level="2">
    <if_sid>18101</if_sid>
    <id>^8021$</id>
    <description>Windows - Packaged app audited.</description>
    <group>pci_dss_10.2.2,pci_dss_10.6.1,</group>
  </rule>

  <rule id="18310" level="12">
    <if_sid>18101</if_sid>
    <id>^8022$</id>
    <description>Windows - Packaged app disabled.</description>
    <group>pci_dss_10.6.1,</group>
  </rule>

  <rule id="18311" level="2">
    <if_sid>18101$</if_sid>
    <id>^8023$</id>
    <description>Windows - Packaged app installation allowed.</description>
    <group>pci_dss_10.2.2,pci_dss_10.6.1,</group>
  </rule>

  <rule id="18312" level="2">
    <if_sid>18101</if_sid>
    <id>^8024$</id>
    <description>Windows - Packaged app installation audited.</description>
    <group>pci_dss_10.2.2,pci_dss_10.6.1,</group>
  </rule>

  <rule id="18313" level="12">
    <if_sid>18102</if_sid>
    <id>^8025$</id>
    <description>Windows - Packaged app installation disabled.</description>
    <group>pci_dss_10.6.1,</group>
  </rule>

  <rule id="18314" level="12">
    <if_sid>18102</if_sid>
    <id>^8027$</id>
    <description>Windows - No packaged app rule configured.</description>
    <group>pci_dss_10.2.2,pci_dss_10.6.1,</group>
  </rule>

</group>
4. Restart OSSEC agent and OSSEC server: 
    $ sudo /var/ossec/bin/ossec-control restart
    $ sudo /var/ossec/bin/agent _control -R <agent_id>

5. Install the CEF Syslog Plugin in Graylog2.

6. Configure the CEF UDP plugin on a specific port (2514 in my case).

7. Activate csyslogd in OSSEC and configure it to forward CEF format events to listener on UDP/2514.
<ossec_config>
  <snip>
  <syslog_output>
    <server>127.0.0.1</server>
    <port>2514</port>
    <format>cef</format>
  </syslog_output>
  <snip>
</ossec_config>

## Context

This is a pilot for a PCI-regulated environment. In the target environment, the inability to bring in event logs other the standard Windows logs precludes the use of Graylog2, which (along with elasticsearch in SIEMonster) otherwise fulfills the majority of organizational security event and information management needs.

## Your Environment

* Graylog Version: 2.0.0-rc1.1
* Elasticsearch Version: 2.2.0
* MongoDB Version: 3.5.3-1
* Operating System: debian jessie/sid
* Browser version: Google Chrome v53.0.2785.101 m (64-bit) on Windows 10

(The machine is a SIEMonster Capricorn that is up-to-date as of the time of this posting).

**Comment by jalogisch** [comment]
This issue was moved to Graylog2/graylog-plugin-cef#10
