### ISSUE TITLE
Graylog with extractors in a high message enviroment long GC pauses and node dies

### ISSUE THREAD

**Issue by rsff** [Graylog2/graylog2-server#2827]
In the last weeks we have been trying to setup a graylog cluster but every time extractors come into play the node will die.

Without any extractors we can output 100Kmsg/s into ES via graylog so I would discard ES as the bottleneck.

## Expected Behavior
When using extractors the performance of the jvm gets affected and leads the GC to die, that should not happen at least not with the amount of extractor in use eg( 1 grok pattern)[3]

## Current Behavior
Graylog should be able to handle message processing with somewhat conservative extractors

## Steps to Reproduce (for bugs)
1. have a extractor eg[3]
2. Throughput / Metrics 1 minute average rate: 6,088 msg/s
3. 
`2016-09-14T13:06:37.868Z WARN  [jvm] [graylog-1743aa7d-c19e-48fa-89fa-f2e619ec0692] [gc][old][661][27] duration [39.8s], collections [1]/[40.7s], total [39.8s]/[15.8m], memory [28.4gb]->[17.7gb]/[28.5gb], all_pools {[young] [12gb]->[2.7gb]/[12gb]}{[survivor] [1.4gb]->[0b]/[1.5gb]}{[old] [15gb]->[14.9gb]/[15gb]}`
4. node dies

## Context
I have:
2x graylogserver{graylog1,graylog2}
4x ES
3x MongoDB 
The graylog's machine  have 32 core and 128GB RAM

JVM settings:

graylog2
`GRAYLOG_SERVER_JAVA_OPTS="-Xms30g -Xmx30g -XX:NewRatio=2 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+DisableExplicitGC -XX:+UseCMSInitiatingOccupancyOnly -XX:+CMSClassUnloadingEnabled -XX:+CMSScavengeBeforeRemark  -XX:CMSInitiatingOccupancyFraction=33 -XX:-OmitStackTraceInFastThrow -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=1m -Xloggc:/tmp/memoryGC.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution"`

graylog1(master)
`GRAYLOG_SERVER_JAVA_OPTS="-Xms30g -Xmx30g -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+UseParNewGC  -XX:-OmitStackTraceInFastThrow -Xloggc:/tmp/memoryGC.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution"`

Using less memory than 30gb also makes the node fail faster, tried 8/16/20

Log files per node https://drive.google.com/open?id=0B0Nb6nX1bFJjWjlQVW5JNDg0cXc

GC garbage collector log
graylogserver graylog server log
Threaddump threaddump log

## Your Environment

* Graylog Version: Graylog 2.1.0+62db7e0
* Elasticsearch Version: 2.3.2
* MongoDB Version:3.2.9[4]
* Operating System: Ubuntu 14.04.5 LTS
* misc: Oracle Corporation 1.8.0_91 on Linux 4.2.0-41-generic

[3]
Configuration

    grok_pattern: `(%{HOSTNAME:client_ip}|-) (%{HOSTNAME:remote_addr}|-) (%{DATESTAMP_SWIFT:datetime})? (%{WORD:request_method})? (%{NOTSPACE:request_path})? HTTP/%{NUMBER:protocol} %{NUMBER:status_int} (%{NOTSPACE:referer}|-) %{NOTSPACE:user_agent} (%{NOTSPACE:auth_token}|-) (%{NUMBER:bytes_recvd}|-) (%{NOTSPACE:bytes_sent}|-) (%{NOTSPACE:client_etag}|-) (%{NOTSPACE:transaction_id})? (%{NOTSPACE:headers}|-) (%{NUMBER:request_time}|-) (%{NOTSPACE:source})? (%{NOTSPACE:log_info})? (%{NUMBER:request_start_time})? (%{NUMBER:request_end_time})?`
    named_captures_only: 

```
Metrics
7,396,271 total invocations since boot, averages: 0, 12.05, 900.49.
Total time

95th percentile:
    6,747μs
98th percentile:
    15,886μs
99th percentile:
    17,805μs
Standard deviation:
    3,562μs
Mean:
    911μs
Minimum:
    35μs
Maximum:
    33,263μs

Converter time

95th percentile:
    0μs
98th percentile:
    0μs
99th percentile:
    0μs
Standard deviation:
    0μs
Mean:
    0μs
Minimum:
    0μs
Maximum:
    0μs
```

[4]
```
db version v3.2.9
git version: 22ec9e93b40c85fc7cae7d56e7d6a02fd811088c
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1404
    distarch: x86_64
    target_arch: x86_64
```

**Comment by jalogisch** [comment]
could you please provide some lines that you try to catch with this grok pattern.

That would make the process to check this out much faster

thank you

**Comment by henrikjohansen** [comment]
@rsff @jalogisch We have done some pretty extensive performance testing recently (up to 1M messages per second) and we have had similar issues when testing single node performance.

Without stream routing, extraction or pipelines Graylog can handle a significant amount of throughput ... but that drops like a cliff as soon as you tax the system by adding the aforementioned (CPU usage, GC stalls, OOM, etc).

The 1M messages per second test was about raw throughput - so no streams, extractors or pipelines.

We figured out that our current setup can handle ~2000 messages per physical core and we allocate ~4GB memory per CPU core. A single physical box is kept at max 20K messages per second (remember that you need have additional capacity for mongo, etc if you run that locally ... which is what I would recommend).

These were the fastest Intel CPU's you can get your hands on so slower CPU's == lower throughput per core (YMMV).

Scaling out is also not without it's challenges but 100k (5 server nodes in my example) is not a problem at all :)

Oh, and if you need raw speed you should skip pipelines for now.

**Comment by jalogisch** [comment]
thank you @henrikjohansen for this comment!

The point @rsff that eats your performance is this monster regex you build. Running this on any Log will eat much of your CPU Cycles.

After internal discussion, this is nothing that looks like a bug. You need to carefully tune your settings and know what you are doing to understand the impact that each setting has.

Just taking what you provide:

> 32 output buffer threads
> 31 process buffer threads
> 7 input buffer threads

```
2016-09-14T08:22:17.879Z INFO  [InputBufferImpl] Initialized InputBufferImpl with ring size <4194304> and wait strategy <BlockingWaitStrategy>, running 6 parallel message handlers.  
2016-09-14T08:22:19.683Z INFO  [ProcessBuffer] Initialized ProcessBuffer with ring size <4194304> and wait strategy <BlockingWaitStrategy>.
2016-09-14T08:22:21.274Z INFO  [OutputBuffer] Initialized OutputBuffer with ring size <4194304> and wait strategy <BlockingWaitStrategy>.
```

That are calculated 4194304 + 4194304 + 4194304 messages in the heap - total _**12.582.912 messages**_. If we calculate 800bytes for each message we are round about 10GB of data in the Heap. That need some time during the **GC** ... 

You are free to get in contact with the Graylog Support Team to talk about Consulting, but this is not an issue that will be discussed or analysed deeper at this location.

**Comment by rsff** [comment]
Hey @jalogisch thanks for the feedback, nevertheless I've also tested it with simple regex and has the same behaviour, gladly is just not me seeing the same behaviour.
Graylog has a lot of raw ingestion performance, I was able to get a 4Xnode elasticsearch rejecting bulk threads, and graylog happily ingesting messages, but that changed when Extractors,grok come into play, I went to grok because was having issues with this type of "monster" regex:

`"regex_value": "(tx[a-zA-Z0-9-]{4,})"`
`"regex_value": "\\d{1,3} ([a-zA-Z0-9-]{3,})"`
`"ERROR with Object server \\d{1,3}.\\d{1,3}.\\d{1,3}.\\d{1,3}\\b:\\d{4}\\/(\\w{3})"`

> The point @rsff that eats your performance is this monster regex you build. Running this on any Log will eat much of your CPU Cycles.

Exactly, CPU not the JVM... and I don't see the node spending more than 30% CPU

> After internal discussion, this is nothing that looks like a bug. You need to carefully tune your settings and know what you are doing to understand the impact that each setting has.

Yeah, since there is no documentation besides the comments on the config file, I try to use a scientific approach, monitoring a blackbox where the outputs where JVM/CPU/etc...  and changing settings at a time, let it run and interpret.
If you have a better idea on how I could do differently without paying for support I'm all for that.

> You are free to get in contact with the Graylog Support Team to talk about Consulting, but this is not an issue that will be discussed or analysed deeper at this location.

True opensource is not all about the code but also the community...

**Comment by henrikjohansen** [comment]
@rsff @jalogisch One way to avoid dealing with this is to hand off the message parsing to the client. Normally you have a lot more clients than Graylog server-nodes which is why this makes sense. Nxlog, Logstash, et al all provide GELF outputs so that extraction is no longer necessary.

Another way is to throttle the ingestion rate by putting something like Kafka in front of your Graylog nodes.

We are moving to a position where dedicated Graylog nodes will ingest message from all kinds of sources, do certain things to them and then output those to several Kafka topics that in turn are consumed by other Graylog nodes to persist that data into ES. Clients that already provide parsed, enriched data will write to Kafka directly thus avoiding resource consumption on the frontend nodes.

Essentially we are building a stream processing pipeline - there are some issue within Graylog that need to be resolved for this to work properly but with some luck enough progress might be made for this to work when 2.2 goes GA.
