### ISSUE TITLE
make <title> of the web interface more dynamic

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2834]
## Expected Behavior

When using the Web Interface I would expect that the Title change if i move from one section to another, so this should be something like:

> Graylog {Version} | [Search|Streams|Dashboards] 
## Current Behavior

The Title only shows _Web Interface_ this way if having multiple Tabs open or create a Bookmark you will get confused fast.
## Possible Solution

Make use of `document.title` and change the title on the sub-page
## Context

Before Version 2 Graylog displays the "Location" where you are in the Web interface. After the switch to 'one site' it only shows the static "Web Interface".

That would be a nice to have.

**Comment by edmundoa** [comment]
This is fixed now, closing the issue.
