### ISSUE TITLE
Custom Field ordering in Graylog Search

### ISSUE THREAD

**Issue by gjahchan** [Graylog2/graylog2-server#2836]
I would like to display the checked fields in a specific order, and save the order along with the search.

I could not find a mechanism for sorting displayed fields (as in Kibana4 for example) -- Graylog sorts alphanumerically by default and I could not find a way to change it (other than naming the extracted fields in the desired display order, which is very consuming to setup and even more to maintain).

Am I missing something?

If not, could Displayed Field Ordering be added to Graylog2 Searches?
- Graylog Version: 2.0.0-rc.1-1
- Elasticsearch Version: 2.2.0
- MongoDB Version: 3.5.3-1
- Operating System: Debian Jessie/SID
- Browser version: Chrome v53.0.2785.113 m (64-bit) on Windows

**Comment by joschi** [comment]
Refs https://graylog.ideas.aha.io/ideas/GL2E-I-515
Refs Graylog2/graylog2-web-interface#595

**Comment by gjahchan** [comment]
Setting/saving the default fields is part of my request. The other part has to do with custom ordering of the displayed fields based on arbitrary criteria, rather than forced alphanumeric field name order, which do not seem to be addressed in the two issues you mentioned.

Replication of what's in Kibana4 would be ideal. From the displayed field order, a field can be removed, or moved left or right. When the search is saved, the fields and their order are saved along with the search.

**Comment by mr6volt** [comment]
This can be done using JQueryUI, and probably loaded/saved in an array. Could this be added using a plugin?

**Comment by Peter2121** [comment]
Any progress on this issue? I'm really interested by this feature too...

**Comment by exevolium** [comment]
Any progress on this issue?

**Comment by rgrellmann** [comment]
Still no progress on this? The first thing that really annoyed me about Graylog is this. Please make it possible to configure the default fields!

**Comment by benoc617** [comment]
Still no progress on this even in 3.0.0 as far as I can see.

**Comment by zhuzhengguang** [comment]
Any progress on this issue?

**Comment by kmerz** [comment]
@zhuzhengguang It was implemented in the new search and is part of the 3.1.0 release.

**Comment by kmerz** [comment]
Fixed with https://github.com/Graylog2/graylog-plugin-enterprise/pull/926
