### ISSUE TITLE
Entire Field Extractor working erratically - Potential Bug.

### ISSUE THREAD

**Issue by gjahchan** [Graylog2/graylog2-server#2837]
Forwarding OSSEC events to Graylog.

The events include OSSEC-specific fields that are ciritcal in our environment:
- rule_sidid
- rule_description
- rule_alertlevel
- rule_firedtimes

I have configured extractors for all of them in order to store/display them with different field names, only the rule_description extractor works, the others are ignored, though all of them are configured in a similar manner.

Have I stumbled on a bug?

* Graylog Version: 2.2.0-rc.1-1
* Elasticsearch Version: 2.2.0
* MongoDB Version: 3.3.5-1
* Operating System: debian jessie/sid
* Browser version: Google Chrome v53.0.2785.113 m (64-bit) on Windows.

**Comment by gjahchan** [comment]
It seems like text fields are extracted, but numeric fields are not.
- rule_description type is text (works)
- rule_sidid, rule_alertlevel, and rule_firedtimes are numeric (do not work).

I have added rule_PCI_DSS which is text, it works.

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by gjahchan** [comment]
CSV Converter does not seem to work.

Field content: ["10.2.5.a","10.6.1"]

CSV Converter set as follows:
- Field names: PCI1,PCI2,PCI3,PCI4
- Separator character: ,
- Quote character: "
- Escape character: \
- Use strict quotes: Checked.
- Trim leading white space: Checked.

Am I doing it wrong, or is this a bug?

**Comment by joschi** [comment]
@gjahchan Please post your issue to the mailing list or join the #graylog IRC channel.
