### ISSUE TITLE
Change the default Message Processing Order

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2838]
## Expected Behavior

![graylog_web_interface](https://cloud.githubusercontent.com/assets/404238/18578409/0e82109c-7bf0-11e6-9a1f-b42a1b09568d.png)
## Current Behavior

![graylog_web_interface 2](https://cloud.githubusercontent.com/assets/404238/18578453/4f502bae-7bf0-11e6-90b6-e4feaed41d4c.png)
## Context

As I notice that the default setting let people struggle with geo_ip or some extractors they would expect to work before the pipelines. The old defaults get people confused. Let's make live for beginners easier!

**Comment by joschi** [comment]
@jalogisch The GeoIP Resolver expects messages to have fields which only contain IP addresses. These usually are only extracted/generated from other fields using extractors or pipeline processor rules and wouldn't be available with your proposed order of message processors.

**Comment by jalogisch** [comment]
@joschi that's why I would prefer to change the default order. Currently, the default order is:

1. GeoIP
1. Pipeline
1. Message Filter

New default should be:

1. Message Filter
1. Pipeline
1. GeoIP

**Comment by joschi** [comment]
@jalogisch Ah, got it. Thought it was the other way round. 😊

**Comment by jalogisch** [comment]
the initial order will not be changed. 

Future Versions might have different order by default.
