### ISSUE TITLE
Add "Loading" indicator on Search page refresh

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2840]
After changing search criteria it is unclear if page already loaded or load is in progress.
It will be good to have some loading indicator after changing search criteria on Search page.

## Your Environment
* Graylog Version: 2.1.1

**Comment by kroepke** [comment]
There is one in the lower right hand corner (I missed it as well, because it's hard to spot).

I'll leave this open for others to discuss whether to put it in a more prominent place.

**Comment by hc4** [comment]
Hm... I see it now :)

**Comment by hc4** [comment]
Maybe search button could be replaced with loading animation?
![image](https://cloud.githubusercontent.com/assets/17475270/18585305/cd85c5b4-7c1e-11e6-85d5-bad2ba2eda61.png)

**Comment by edmundoa** [comment]
The problem I see is that putting it in a more prominent place would annoy a lot when enabling live-reloading.

**Comment by edmundoa** [comment]
@hc4 That doesn't work, because when you scroll down you don't see the search bar.

**Comment by hc4** [comment]
Ok, then here:
![image](https://cloud.githubusercontent.com/assets/17475270/18585339/ffd71888-7c1e-11e6-8f9b-ee9982a3def6.png)

**Comment by pdepaepe** [comment]
I agree with previous comments, new search rendering is great, but indicator by far too much not visible.

Maybe something like bootstrap alert alert-info in LoadingIndicator.css:

```
:local(.loadingIndicator) {
    color: #31708f;
    background-color: #d9edf7;
    border-color: #bce8f1;
    padding: 15px;
    margin-bottom: 20px;
    margin-right:20px;
    border: 1px solid transparent;
    border-radius: 4px;
    position:fixed;
    bottom:0;
    right:0;
    z-index:2000;
}
```
