### ISSUE TITLE
Saved search dropdown is not refreshed after deleting saved search

### ISSUE THREAD

**Issue by kpointer** [Graylog2/graylog2-server#2841]
Getting an error when trying to delete a saved search
## Expected Behavior

The saved search gets deleted.
## Current Behavior

Generates the following error:

Could not delete saved search
Deleting saved search "undefined" failed with status: Error: cannot DELETE https://hades.astro.illinois.edu/api/search/saved/57dbe0003b5257e1eb1818fd (404)

Nothing in the graylog server log.
## Steps to Reproduce (for bugs)
1. Load a saved search
2. Try and delete saved search
## Context

Can't delete saved searches to update the search terms
## Your Environment
- Graylog Version: 2.1.1
- Elasticsearch Version: 2.4.0
- MongoDB Version: 3.2.9
- Operating System: Ubuntu 14.04.5 LTS
- Browser version: Firefox 49

**Comment by joschi** [comment]
@kpointer I can't reproduce that with Graylog 2.1.1.

Are there any error messages in the logs of your Graylog nodes?

**Comment by kpointer** [comment]
No errors in logs. I had restarted graylog and still had the same issue. 

Rolling back to 2.1.0 had it working as expected.

Going back to 2.1.1 has it working again, but I've found I need to force a refresh to get it to clear out the old saved search name before I can save with the same name.

**Comment by joschi** [comment]
@kpointer Thanks for the feedback! It looks like the web interface simply isn't updating the dropdown field with the Saved Searches after deleting one.

![demo](https://cloud.githubusercontent.com/assets/43951/18707777/d624e39e-7ff7-11e6-803d-ce6e4c6ad17b.gif)
