### ISSUE TITLE
Source ip address instead of the hostname

### ISSUE THREAD

**Issue by work-des** [Graylog2/graylog2-server#2844]
## Expected Behavior
Source ip address instead of the hostname

## Current Behavior
Source hostname

## Context
We have a lot of hosts. We prefer to see the host address rather than its name. How to do it?

![source](https://cloud.githubusercontent.com/assets/13961834/18614410/b3ec483e-7d96-11e6-927d-fb3503a74522.PNG)
* Graylog Version: 2.1.1
* Elasticsearch Version: 2.4.0
* MongoDB Version: 3.2.9
* Browser version: Firefox

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
