### ISSUE TITLE
Graylog 2.1 problems connecting to the Graylog server 

### ISSUE THREAD

**Issue by owenccc** [Graylog2/graylog2-server#2845]
## Current Behavior
After setting up new Garylog server following instructions in following URL, problem connecting to the web server. It is a single instance setup, with everying in 1 single centos cloud VM.
http://docs.graylog.org/en/2.1/pages/installation/os/centos.html

Error message
Bad request
Original Request
GET http://xxxxxxxx:9000/api/system/sessions
Status code
undefined
Full error message
Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

when typing http://xxxxxxxx:9000/api/system/cluster/node#, something can be display out

{"cluster_id":"a1a5e3ab-d704-44fc-a445-5de53966534d","node_id":"60c87211-8541-4d63-96ed-be84fc021c11","type":"server","transport_address":"http://xxxxxxx:9000/api/","last_seen":"2016-09-19T04:54:19.000Z","short_node_id":"60b87210","hostname":"xxxxxxxxxx","is_master":true}

## Your Environment
* Graylog Version: 2.1
* Elasticsearch Version: 2.4
* MongoDB Version: 3.2
* Operating System: CentOS 7
* Browser version: Chrome

**Comment by dennisoelkers** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
