### ISSUE TITLE
deleted extractor still present in multinode setup with global inputs

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2848]
## Expected Behavior
Delete Extractor from Global Input will be removed from all Servers/Inputs

## Current Behavior
Running a global UDP Syslog Input, add one extractor (K/V for example) and let this run a time (3 days in my example) when deleting the Extractor Messages coming in still get the K/V extraction.

Even  restart of the Graylog Server does not help.

 
## Steps to Reproduce (for bugs)

1. Setup Multi Node Environment
2. Create Global Input (UDP Syslog)
3. Create extractor in this Input
3. Have some Messages coming in
4. Detele the extractor

## Context
Removing Extractor from Input (and not present in Mongo) still work on Input!

![empty_extractor](https://cloud.githubusercontent.com/assets/404238/18626848/b9e476be-7e57-11e6-9900-cb931d443e93.png)

* Graylog Version: 2.1.1

**Comment by dennisoelkers** [comment]
The extractor was a red herring. The real issue at hand is that for structured syslog the syslog codec is extracting fields [per default](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/inputs/codecs/SyslogCodec.java#L153).
