### ISSUE TITLE
Running graylog2-server completely embedded

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#285]
For testing purposes it would be greatly beneficial to be able to run graylog2-server in an embedded way.

Right now the Travis test setup requires several scripted steps to provide the web interface with a running server, and running the web interface selenium tests locally requires the same thing.

Having the server completely embedded and started/stopped as part of the test setup code, the external dependencies would completely vanish.
When we've added JPA support we could even do without MongoDB for the tests.

**Comment by bernd** [comment]
We can run the server completely embedded if needed. We also use a fake mongodb implementation for our tests already. Closing this.
