### ISSUE TITLE
Feature request: send a placeholder password when displaying LDAP settings

### ISSUE THREAD

**Issue by sixcorners** [Graylog2/graylog2-server#2855]
## Current Behavior

Currently the ldap/ad system password is sent to the browser when the page is shown. It doesn't display because the input box type is password but it can be read in other ways.
## Possible Solution

What should be sent instead is a placeholder password. If that password is sent back to the server the server should not change the password.
## Context

People who can access the Authentication settings can see the system password.
- Graylog Version: Graylog 2.1.1+01d50e5

**Comment by sixcorners** [comment]
Does this password actually have to be stored in the first place?

**Comment by joschi** [comment]
@sixcorners Yes, how would Graylog access the LDAP server otherwise?

Quotes from the Graylog web interface (System / Authentication page):
> The username for the initial connection to the LDAP server, e. g. `uid=admin,ou=system`, this might be optional depending on your LDAP server.

> The password for the initial connection to the LDAP server.

If your LDAP server allows access without these, you don't need to provide these settings. Otherwise they are mandatory.

**Comment by bernd** [comment]
This has been fixed in #4526.
