### ISSUE TITLE
Graylog 2.1 failed to fetch hostname from log messages 

### ISSUE THREAD

**Issue by kunalpatil3017** [Graylog2/graylog2-server#2859]
Hello 

I have setup gelf UDP input and LOGSTASH for filtering the logs 
 i'm able to fetch data but in some messages not able to filter and 
i getting below messges in Sources
Please provide solution
![selection_013](https://cloud.githubusercontent.com/assets/22319145/18669140/248c3fec-7f57-11e6-875e-2d85a799752c.png)

Following are the details 
* Graylog Version:2.1
* Elasticsearch Version:2.4.0
* MongoDB Version:3.2.9
* Operating System:centos 7
* Browser version:

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
