### ISSUE TITLE
Question: Graylog 2.1.1 Delete all messages from specific host

### ISSUE THREAD

**Issue by ps-gm** [Graylog2/graylog2-server#2861]
Is it possible in graylog 2.1.1 deleting all messages from a specific host:

I found this, but it seems that graylog2 is not accepting wildcard in the query...

curl -XDELETE 'http://syslog.contoso.local:9200/graylog2_*/message/_query' -d ' { "query_string" : { "default_field" : "host", "query" : "hostname:" } }'

Help on that would be highly appreciated... Thanks in advance many times!!

**Comment by joschi** [comment]
@ps-gm We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
