### ISSUE TITLE
Manage the Graylog-Server and Graylog-Web separately in Graylog Version 2.1.1

### ISSUE THREAD

**Issue by zaibfridi** [Graylog2/graylog2-server#2865]
I am trying to implemnt the [Graylog Bigger Setup](http://docs.graylog.org/en/2.0/pages/architecture.html#bigger-production-setup)

For This, I separate the graylog server with these settings

Graylog-Server = 192.168.100.80
Graylog-Web = 192.168.100.81

On Graylog-Server

`is_master = true` 
and
`web_enable = false`

and on the Graylog Web 

`is_master = false` 
and
`web_enable = true`

I am attaching the both conf files and the log file of Graylog-Web below if you need the deeper look.
The problem, I am facing, I am not able to browse the web interface.

The good news is that, I can browse the 

http://192.168.100.80:12900/api-browser ( 192.168.100.80 is the graylog server ip )

## Graylog Web Enable Conf File
[graylog-web.txt](https://github.com/Graylog2/graylog2-server/files/484208/graylog-web.txt)

## Graylog Server Conf File
[graylog-server.txt](https://github.com/Graylog2/graylog2-server/files/484206/graylog-server.txt)

## Graylog Web Log File

[graylog-webLog.txt](https://github.com/Graylog2/graylog2-server/files/484201/graylog-webLog.txt)

## My Environment

* Graylog Version: 2.1.1
* Elasticsearch Version: 2.4.0
* MongoDB Version: 3.2.9
* Operating System: ubuntu 14.04

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
