### ISSUE TITLE
Enhance TCP-based Inputs with SSL Support

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#287]
Currently the TCP-based Inputs (Raw, GELF, Syslog) lack SSL Support. To increase the ease of use and get rid of the need to use third party tools like stunnel, I would recommend adding an ssl handler to the pipeline. Ideally, it would not be a separate input plugin type, but a configuration option for the existing ones.

Even better if it would be easily includable in future TCP-based Inputs without having to rewrite the SSL support for each plugin, especially because other functionalities (certificate management in the web interface, probably client auth handling) are associated with this.

**Comment by joschi** [comment]
Implemented since Graylog2 0.92.
