### ISSUE TITLE
Could not load user list

### ISSUE THREAD

**Issue by triggert** [Graylog2/graylog2-server#2876]
After upgrading to Graylog 2.1.1+01d50e5 (Oracle Corporation 1.8.0_65 on Linux 2.6.32-642.1.1.el6.x86_64) I'm receiving an error "Could not load user list" when trying to modify roles.

"Loading user list failed with status: Error: cannot GET https://localhostname:12900/users (500)

server.conf:
REST interface
rest_listen_uri = http://127.0.0.1:12900
rest_transport_uri = https://localhostname:12900

Web interface
web_enable = true
web_listen_uri = http://127.0.0.1:9000
web_endpoint_uri = https://haproxyhostname:443

apache.conf:
VirtualHost localip:12900
    SSLEngine on
    SSLCertificateFile 
    SSLCertificateKeyFile 
    SSLCACertificateFile 

    ServerName localhostname
    ServerAlias haproxyhostname

    ProxyPreserveHost On
    ProxyRequests Off
    <Proxy *>
        Order deny,allow
        Allow from all
    </Proxy>
    <Location />
        ProxyPass http://127.0.0.1:12900/
        ProxyPassReverse http://127.0.0.1:12900/
    </Location>
/VirtualHost

VirtualHost localip:443
    SSLEngine on
    SSLCertificateFile 
    SSLCertificateKeyFile 
    SSLCACertificateFile 

    ServerName localhostname
    ServerAlias haproxyhostname

    ProxyPreserveHost On
    ProxyRequests Off

    <Location />
        RequestHeader set X-Graylog-Server-URL "https://localhostname:12900"
        ProxyPass http://127.0.0.1:9000/
        ProxyPassReverse http://127.0.0.1:9000/
    </Location>
</VirtualHost>

No changes to settings during upgrade.  Previously worked without issue.

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
