### ISSUE TITLE
Latest OVA graylog-2.1.1-1.ova has Ensoniq sound card embedded as a required device

### ISSUE THREAD

**Issue by bubba198** [Graylog2/graylog2-server#2877]
Latest OVA graylog-2.1.1-1.ova has Ensoniq sound card embedded as a required device

## Expected Behavior

Error when deploying using ESXi or any other VM player that happens to NOT have any sound device defined

## Possible Solution

Edit the XML which is a hassle but perfectly legit way to get rid of the error and be able to deploy the OVA

## Steps to Reproduce (for bugs)

1. Attempt to deploy graylog-2.1.1-1.ova on a hypervisor which does NOT have sound card
2.
3.
4.

## Your Environment

ESXi 5.0 custom HP Pro Liant image

* Graylog Version: graylog-2.1.1-1.ova
* Elasticsearch Version: graylog-2.1.1-1.ova
* MongoDB Version: graylog-2.1.1-1.ova
* Operating System: graylog-2.1.1-1.ova
* Browser version: Chrome latest 64 bit

**Comment by joschi** [comment]
This issue was moved to Graylog2/graylog2-images#170
