### ISSUE TITLE
Autocomplete tooltip doesn't dissapears after pressing Enter

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2878]
Start typing search query.
Autocomplete tooltip popups.
![image](https://cloud.githubusercontent.com/assets/17475270/18750528/2b83bad0-80e4-11e6-919d-7e8fbe43a960.png)

Finish typing
Press ENTER

## Expected Behavior
Tooltip disappears.
New serch in progress.

## Current Behavior
Tooltip still there, but new search in progress
![image](https://cloud.githubusercontent.com/assets/17475270/18750540/3ac50cba-80e4-11e6-8dbd-6500267ed86b.png)

## Your Environment
* Graylog Version: 2.1.1

**Comment by hc4** [comment]
Or maybe this behaviour by design?

**Comment by dennisoelkers** [comment]
No, this is a regression because of the search page not doing a full page refresh anymore. Thanks for reporting!
