### ISSUE TITLE
api: invalid value of total stream alerts

### ISSUE THREAD

**Issue by oboukili** [Graylog2/graylog2-server#2879]
Upon monitoring stream alerts using the API, the "total" value of alerts does not change whether results have been filtered out or not using the optional "since" time selector field.

`http://mygraylogcluster/api/streams/57e3968c25444e246eb94884/alerts?since=1374552373`
`http://mygraylogcluster/api/streams/57e3968c25444e246eb94884/alerts`
## Expected Behavior

When using the optional "since" field, the total value should reflect the number of returned alerts.

**filtered**

> {
>   "total": 0,
>   "alerts": []
> }
## Current Behavior

**filtered**

> {
>   "total": 2,
>   "alerts": []
> }
- Graylog Version: 2.1.1
- Elasticsearch Version: 2.3.2
- MongoDB Version: 3.2.6
- Operating System: CentOS7.2

**Comment by dennisoelkers** [comment]
This is on purpose. The total field in this response does not refer to the number of alerts contained in this request, but the number of total alerts. Is there a good reason for us to change this?

**Comment by kroepke** [comment]
I think both numbers are useful and the current behavior is at least surprising. Graylog should return both numbers, if the global total is required in some view.

**Comment by oboukili** [comment]
Thanks for your replies.
My current workaround is to simply count the length of the "alerts" list, so I can live with that, however I only wanted to point out the current behavior was not intuitive.
Cheers,

**Comment by bernd** [comment]
The alerting system has been replaced with events in the meantime. I am closing this issue because this API is no longer in use.
