### ISSUE TITLE
graylog converter does not work on copy input fields

### ISSUE THREAD

**Issue by ricard0ff** [Graylog2/graylog2-server#2884]
## Expected Behavior
When a converter is applied the type should be updated

If you try to use a extractor with conversion on a copy input field it will not work.

## Steps to Reproduce (for bugs)
1. create a grok pattern
2. create a copy input
3. try to use generate chart
4.

## Context
It is not possible to use numerical values if you look ate the mappings from elasticsearch:

```
"request_time_numeric":{"type":"string","index":"not_analyzed"},
 ```

and in graylog
```
"title": "Request Time Extractor numeric",
      "extractor_type": "copy_input",
      "converters": [
        {
          "type": "numeric",
          "config": {}
        }
      ],
      "order": 0,
      "cursor_strategy": "copy",
      "source_field": "request_time",
      "target_field": "request_time_numeric",
      "extractor_config": {},
      "condition_type": "none",
      "condition_value": ""
    }
  ],
  "version": "2.1.0-SNAPSHOT"
}
```

## Your Environment

* Graylog Version: Graylog 2.1.1+01d50e5
* Elasticsearch Version:2.3.5
* MongoDB Version:
* Operating System: Linux 4.2.0-41-generic)
* Browser version:

**Comment by joschi** [comment]
@ricard0ff Thank you for reporting this.

I couldn't reproduce the issue you're describing.

I've created a Copy Input extractor which copies the field `message` to `message_num` and applies a Numeric converter:
```json
{
  "extractors": [
    {
      "title": "message -> message_num",
      "extractor_type": "copy_input",
      "converters": [
        {
          "type": "numeric",
          "config": {}
        }
      ],
      "order": 0,
      "cursor_strategy": "copy",
      "source_field": "message",
      "target_field": "message_num",
      "extractor_config": {},
      "condition_type": "none",
      "condition_value": ""
    }
  ],
  "version": "2.1.1"
}
```
The resulting field `message_num` contains a number and also has a numeric type in Elasticsearch:
```json
$ curl localhost:9200/graylog_deflector/_mapping?pretty
{
  "graylog_1" : {
    "mappings" : {
      "message" : {
        "properties" : {
          "message" : {
            "type" : "string",
            "analyzer" : "standard"
          },
          "message_num" : {
            "type" : "long"
          }
        }
      }
    }
  }
}
```

Make sure that there haven't been any non-numeric values for the `request_time_numeric` field in your data before. The dynamic mapping of Elasticsearch is usually the reason for "mismatching" data types.

You can also create a custom index mapping to force the `request_time_numeric` be a numeric field: http://docs.graylog.org/en/2.1/pages/configuration/elasticsearch.html#custom-index-mappings

As a workaround, you can cycle indices in your Graylog web interface on the System / Indices page using the Maintenance dropdown. This will create a new Elasticsearch index which should have the correct mapping for `request_time_numeric` (if it really only contains numeric values).
