### ISSUE TITLE
Updating extractor regex doesn't update existing fields

### ISSUE THREAD

**Issue by Narayanan170** [Graylog2/graylog2-server#2885]
Once I update the regex of an extractor, I don't see anything update in the previously parsed log messages as seen in figure 1. I've improved my matching so Sent is not taken into account, but nothing happens.

[Figure 1] (https://monosnap.com/file/IcsRFdO0BCgNfhwSdHTAnluwQsAhoB#)

## Expected Behavior
When I update the regex of an extractor, I expect it to run through previously parsed log entries and update the fields, unfortunately that's not the case.

## Current Behavior
Updating the regex of an extractor only functions on messages that have not been "parsed" yet.

## Possible Solution
On extractor change, you have to run all the messages through that extractor again.

## Steps to Reproduce (for bugs)
1. Create a "loose" regex extractor
2. Modify it to be more strict

**Comment by jalogisch** [comment]
@Narayanan170 the extractor runs only on incoming messages.

once the message is stored it is never touched again.

**Comment by Narayanan170** [comment]
Oh, sorry, my bad. 
Is there any documentation that explains that?
Is there any way to run it retroactively?

**Comment by joschi** [comment]
@Narayanan170 You could re-index those messages, e. g. using logstash and its [Elasticsearch input](https://www.elastic.co/guide/en/logstash/2.4/plugins-inputs-elasticsearch.html) and [gelf output](https://www.elastic.co/guide/en/logstash/2.4/plugins-outputs-gelf.html). This will, of course, duplicate messages unless you drop the old indices afterwards.

**Comment by Narayanan170** [comment]
Ty for the quick response!
