### ISSUE TITLE
Display total size of all indices on Indices page

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#2886]
## Expected Behavior

The combined size (in MB/GB/TB) of all indices is displayed in the Indices page's [overview message](https://github.com/Graylog2/graylog2-server/blob/606e32947403d1630c040d83510b15a65062ac1d/graylog2-web-interface/src/pages/IndicesPage.jsx#L108).
## Current Behavior

Individual indices on the Indices page (`/system/indices`) display their respective size (e.g. 4.1GB), and the [overview](https://github.com/Graylog2/graylog2-server/blob/606e32947403d1630c040d83510b15a65062ac1d/graylog2-web-interface/src/pages/IndicesPage.jsx#L108) on the Indices page provides a count of indices and a count of all messages indexed, however the combined size is not displayed.
## Possible Solution

Calculate the total size of indices and display it in the Indices page's [overview message](https://github.com/Graylog2/graylog2-server/blob/606e32947403d1630c040d83510b15a65062ac1d/graylog2-web-interface/src/pages/IndicesPage.jsx#L108).
## Context

This would be a convenient way to see (approximately) how much disk space is being used.  It seems `/system/indexer/overview` is already sending per-index size info.
## Your Environment

- Graylog Version:  2.1.1+01d50e5
- Elasticsearch Version:  2.2.0
- MongoDB Version:  2.6.12
- Operating System:  Red Hat Enterprise Linux Server release 6.8
- Browser version:  Firefox 48

**Comment by hezor** [comment]
This is something I'd like to see too.

**Comment by dennisoelkers** [comment]
This is fixed in #4211.
