### ISSUE TITLE
Collector Sidecar configuration in graylog creates hidden Beats input

### ISSUE THREAD

**Issue by wjrogers** [Graylog2/graylog2-server#2887]
The Graylog Collector Sidecar documentation says (emphasis mine): 
> We have prepared an example how to configure Sidecar in your Browser using the Graylog Webinterface. The assumption is that we will configure the collection of Apache logfiles and ship them with a Filebeat to the **already present Beats input** that is listening on Port 5044 on your Graylog Server.

However, I've found that when I create a Beats input on port 5044, then also configure a Beats output in my collector sidecar configuration, I get errors like this in my log after server restart:
```
Sep 23 22:13:59 genius docker[2023]: 2016-09-23 22:13:59,792 ERROR: org.graylog2.shared.inputs.InputLauncher - The [org.
graylog.plugins.beats.BeatsInput] input with ID <57e4549871ed350001c8f535> misfired. Reason: Address already in use.
Sep 23 22:13:59 genius docker[2023]: org.graylog2.plugin.inputs.MisfireException: org.graylog2.plugin.inputs.MisfireException: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:5044
```
After some troubleshooting, I noticed that graylog's process was listening on port 5044 and I was still getting new messages from my sidecar clients even though my Beats input was FAILED. Is this a documentation or a server bug?

## Expected Behavior
Inputs must be manually configured.

## Current Behavior
Creating a Collector Sidecar configuration causes graylog server to listen on the ports specified in the sidecar output(s).

## Steps to Reproduce (for bugs)
1. Create a Beats input on port 5044
2. Create a Collector Sidecar configuration
3. Create a Beats output targeting port 5044 in the Collector Sidecar configuration
4. Restart the graylog server

## Your Environment
* Graylog Version: 2.1.1
* Operating System: CoreOS 1122.2.0
* Browser version: Google Chrome 53.0.2785.116 m (64-bit)

**Comment by joschi** [comment]
@wjrogers If there's already a Beats input running on Graylog (that's the "already present" part), you don't need to create another one.

In other words, everything is fine. You can delete your duplicate (and unnecessary) Beats input again.

**Comment by wjrogers** [comment]
I don't have a duplicate Beats input. I have zero Beats inputs configured, Graylog still listens on port 5044, and it still receives messages from the collector sidecar.
