### ISSUE TITLE
Organise nodes into node groups to ease simultaneous spawning of multiple inputs

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#289]
Right now there is no way to spawn multiple inputs on all nodes of the cluster. To be able to do this in a consistent way both interface- and backend-wise, structuring the servers nodes in node groups would be helpful. This also allows another level of searching and aggregation (search for all messages in node group "staging", return number of 500s on node group "production")..

**Comment by florianvolle** [comment]
We think this has been solved with Global Inputs. If not please reopen.

thx
