### ISSUE TITLE
Add official Salt configuration management system support

### ISSUE THREAD

**Issue by Talkless** [Graylog2/graylog2-server#2892]
http://docs.graylog.org/en/2.1/pages/installation/config_management_tools.html states: 

> The DevOps movement turbocharged market adoption of the newest generation of configuration management and orchestration tools like **Chef, Puppet or Ansible**. Graylog offers official scripts for **all three** of them

I believe with [Salt](https://saltstack.com/salt-open/) support this statement would be more accurate with *all four* of them :-) .

**Comment by joschi** [comment]
@Talkless Feel free to provide a working solution for setting up Graylog with Salt and add it to the [Graylog Marketplace](https://marketplace.graylog.org/).
