### ISSUE TITLE
Add page about accessing offline REST API documentation in docs.graylog.org

### ISSUE THREAD

**Issue by Talkless** [Graylog2/graylog2-server#2893]
[REST API](http://docs.graylog.org/en/2.1/search.html?q=REST+API&check_keywords=yes&area=default) is mentioned number of times in documentation, but it seems there are no actual REST documentation itself within docs.graylog.org. 

[Some post within google groups](https://groups.google.com/forum/#!msg/graylog2/ncJv8EIulaY/SOcx4FerA6cJ) mentions that offline REST API documentation accessible through  `http://127.0.0.1:12900/api-browser` , so I think it would be useful to have all these `REST API` references in docs.graylog.org link to some page that would mention exactly that. Now it looks kinda hidden from newcomer point of view.

Thanks.

**Comment by jalogisch** [comment]
This issue was moved to Graylog2/documentation#203
