### ISSUE TITLE
Client Address on Authentication Page is always 127.0.0.1

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#2900]
## Expected Behavior
Correct Client Address should be displayed.

## Current Behavior
127.0.0.1 is shown at every user.
![chrome_2016-09-28_10-31-40](https://cloud.githubusercontent.com/assets/15243394/18906188/cba953cc-8566-11e6-9b36-8da4eff0318f.png)

## Possible Solution
?

## Steps to Reproduce (for bugs)
1. log in via browser
2. view at the authentication page

## Your Environment

Graylog 2.1.1+01d50e5 on (Oracle Corporation 1.8.0_102 on Linux 3.10.0-327.22.2.el7.x86_64)
* Browser version: Any modern chrome, firefox or IE were tested

* Graylog runs only behind a nginx Proxy, so maybe this is the problem?

**Comment by joschi** [comment]
@gruselglatz Make sure to have a valid configuration for the [`trusted_proxies`](https://github.com/Graylog2/graylog2-server/blob/master/misc/graylog.conf#L124-L126) setting in your Graylog configuration file.

**Comment by gruselglatz** [comment]
@joschi i dont even have that in my config file, when the proxy is running on localhost, the default values aren't sufficient?

**Comment by joschi** [comment]
@gruselglatz That setting has been added in Graylog 2.1.0 and its default is empty (i. e. don't trust any proxies, even not 127.0.0.1).

**Comment by gruselglatz** [comment]
@joschi thank you, and sorry for the issue, i may have overlooked this in the change-log of 2.1.0 .
Now it's working correctly.
