### ISSUE TITLE
Navigation bar covers input when validation error occurs on "Create a content pack" page

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#2904]
## Expected Behavior

The navigation bar, which covers other page content, is taken into account when jumping up to an invalid form input (displaying "Please fill out this field") on the "Create a content pack" page (`/system/contentpacks/export`).
## Current Behavior

The "Please fill out this field" validation message appears over the navigation bar and the problematic input is not visible.
## Steps to Reproduce (for bugs)

1. Log in as admin
2. Ensure there are enough Inputs, Grok Patterns, Outputs, Streams, and/or Dashboards that you'll have to scroll down on the "Create a content pack" page (and can no longer see the "Name" input
3. Navigate to System --> Content Packs and click "Create a content pack"
4. Scroll down and click "Download my content pack"
5. Note the "Please fill out this field" validation message is shown relative to the Name input, however the navigation bar covers the input.

![untitled](https://cloud.githubusercontent.com/assets/19417721/18919612/77fc77ec-8564-11e6-877c-a009338990db.png)
## Context

Very minor... I was just experimenting with content packs and omitted the Category.
### Environment
- Graylog Version:  2.1.1+01d50e5
- Elasticsearch Version:  2.2.0
- MongoDB Version:  2.6.12
- Operating System:  Red Hat Enterprise Linux Server release 6.8
- Browser version:  Firefox 49.0.1 and Chrome 53.0.2785.116

**Comment by bernd** [comment]
This will be fixed in the upcoming 3.0 release.
