### ISSUE TITLE
New search result does not update quick values

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#2908]
When running a new search (with a different query), the search results table gets updated but the quickvalues analysis is still showing the results of the original (previous) search.

This might happen to other values and analysis results, too.

* Graylog Version: Current `master` (`Graylog 2.2.0-SNAPSHOT+bae655e`)
* Operating System: macOS 10.12 (Sierra)
* Browser version: Chrome 53.0.2785.116

**Comment by edmundoa** [comment]
I just checked and this also affects to 2.1.1.

**Comment by lennartkoopmann** [comment]
@joschi @kroepke This should go into 2.1.2 then, right? That's a very confusing bug I ran into several times already.

**Comment by danlsgiga** [comment]
+1
Having the same issue on 2.1.1. I have few Saved searches and every time I change the search, even though it brings the correct values, the fields of the previous search remains. Doing a browser refresh (F5 or CTRL+F5) seems to fix the issue which might suggest some caching issue on React.js for that specific section.
Please have that on the next point release and thanks for the fantastic work on Graylog.

**Comment by kroepke** [comment]
Yes, we'll fix on 2.2.0 and then backport as necessary to 2.1.2 @lennartkoopmann
