### ISSUE TITLE
[Question] Field type of GeoIP data

### ISSUE THREAD

**Issue by matthgyver** [Graylog2/graylog2-server#2909]
Hi,

I'm using Graylog for most of my repporting but I'using Grafana too for building custom dashboard from multiple datasources and one of this is ES from Graylog
It's work well but it do'nt work with GeoIP. Grafana could build map from ES geo_point data type and I see that Graylog create a string field for this data.
Is it normal ?
I have'nt tested with Graylog 2.1 but changelog don't tell about this.

Thank you

## Your Environment

* Graylog Version: 2.0.3 
* Elasticsearch Version: 2.4.1
* Browser version: Firefox 48.0.1

**Comment by joschi** [comment]
@matthgyver This is a known "issue" (well, it's been designed this way).

Feel free to subscribe to Graylog2/graylog-plugin-map-widget#7 to stay updated about the issue.
