### ISSUE TITLE
graylog2 Aws elb 

### ISSUE THREAD

**Issue by noamgr** [Graylog2/graylog2-server#2916]
Hi 
i try to install graylog+mongo + web ( include in 2.1 ver ) 
and second node only ELK 
this part is working to me fine and i see that the ELK and graylog are connected 

i want to move the graylog server to be under aws elb so if in the future i will have more graylog servers i will connect to the elb instead  direct to the node 

my config is like this 
rest_listen_uri = http://127.0.0.1:12900/api/
web_listen_uri = http://0.0.0.0:9000/

and the ELB is set from 80 to 9000 so the heath check is set to port 9000 ( aws ELB ) , i can see that the elb is "inservice" 

when i go to the graylog webui i get this error 
We are experiencing problems connecting to the Graylog server running on http://127.0.0.1:12900/api/. Please verify that the server is healthy and working correctly.

Error message
Bad request
Original Request
GET http://127.0.0.1:12900/api/system/sessions
Status code
undefined
Full error message
Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

and a quick netstat test show 
tcp4       0      0  xxx.xxx.xxx.xxx.56097    xxx.xxx.xxx.xxx.12900      SYN_SENT 
mean that its not doing revers proxy i think 
and if i change the graylog config the elb is "outofservice" 

so my Q is any one setup graylog + aws elb and can tell how ? 
or this is a bug ?? 

Thanks 

* Graylog Version: 2.1
* Elasticsearch Version: 2.4
* MongoDB Version: 3.2
* Operating System: centos 7
* Browser version: chrom latest

**Comment by joschi** [comment]
@noamgr Please refer to http://docs.graylog.org/en/2.1/pages/configuration/web_interface.html for information about configuring the Graylog web interface (including using reverse proxies for load balancing).

Hint: The Graylog REST API must be accessible for all clients (such as your web browser).

**Comment by sathishdsgithub** [comment]
@joschi 
How to change default graylog port 9000 to 80 

I'm trying to access graylog with different port (80) rather default port 9000. My current environment does not allow me to use default gray log port 9000. How to configure the gray log to use the port 80 rather port 9000.

I have tried port redirect options with IP-tables, xinetd, graylog web interface nothing helped me fix it.

My current web and rest uri are shown below. Please, can someone suggest me the method to use port 80 for the graylog web interface?

web_listen_uri = http://127.0.0.1:9000/

rest_listen_uri = http://127.0.0.1:9000/api/

**Comment by joschi** [comment]
@sathishdsgithub We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by sathishdsgithub** [comment]
@joschi thanks
