### ISSUE TITLE
Wrong log order in CSV export

### ISSUE THREAD

**Issue by btanto** [Graylog2/graylog2-server#2918]
Logs into CSV file exported from Graylog are arranged in a wrong order while on web-interface they are displayed correctly.

Graylog version: 2.1.0+62db7e0

**Comment by marciofoz** [comment]
Hello.
Same issue here, with Graylog 2.2.3+7adc951 (Oracle Corporation 1.8.0_131 on Linux 3.10.0-514.21.1.el7.x86_64)

**Comment by joschi** [comment]
@btanto @marciofoz Graylog is using the virtual `_doc` field to "sort" documents during the CSV export for performance reasons.

> Scroll requests have optimizations that make them faster when the sort order is `_doc`. If you want to iterate over all documents regardless of the order, this is the most efficient option

https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-request-scroll.html

**Comment by Fl4m3Ph03n1x** [comment]
+1 , I am also having this issue with Graylog version 2.4.3-1.

**Comment by chuangtim** [comment]
Hello.
Same issue here, with Graylog 3.1.3
