### ISSUE TITLE
Write proper MessageBodyReaders for REST bodies

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#293]
Currently the POST/PUT REST resources take a String body parameter, that is merely documented as "JSON body".

Afterwards the string is manually deserialized using Jackson, a step which can be done automatically by supplying MessageBodyReader (and possibly ...Writer) for the Request classes.
Apart from saving boilerplate code, the API documentation step can directly gather information about the body type and its fields by analyzing the type of POST and PUT resources, as well as the return types of the various resources.

**Comment by bernd** [comment]
We are slowly converting the code base to DTOs. Closing this issue.
