### ISSUE TITLE
Ossec TO gRaylog

### ISSUE THREAD

**Issue by GlobuleBleu** [Graylog2/graylog2-server#2931]
Hi,

I have a graylog-server 2.1 and ossec on other machine. I have configured ossec to send log to graylog with ossec-cef-plugin... 

On graylog server tcpdump show me the log from ossec server. But when I try to search any log and see nothing...

Anyone could help me?

**Comment by joschi** [comment]
@GlobuleBleu We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
