### ISSUE TITLE
Graylog server memory leak issue

### ISSUE THREAD

**Issue by 4BRobby** [Graylog2/graylog2-server#2932]
## Expected Behavior

Graylog should clean up memory space it is using.

## Current Behavior

When starting up the graylog server java process is using ~ 5%-15% of cpu time while processing web frontend requests and the few messages we have coming in.
Heap Memory usage in the frontend says "The JVM is using  480.9MB of  972.8MB heap space and will not attempt to use more than  1.4GB"

After several night jobs firing some more messages the graylog process seems to have trouble doing a proper garbage collection (see attached screen shot). 
Heap Memory usage in the frontend says "The JVM is using  1.4GB of  1.4GB heap space and will not attempt to use more than  1.4GB".
And even the garbage collection will not free more, so it is stuck with 1.4 GB. The screenshot was made shortly before it will crash with several exceptions including an out of memory exception while the process is running CPU ~ 105%.

The image was shoot after ~2 days running time.

The thing is that graylog should literally die of boredom because NO messages are coming in and only a few since the night. Buffer and journal utilization shows that the qeue is not used at all (see attached screenshot).

To me this looks like a memory leak as used heap space is growing and growing and all garbage collection events free less memory than the one before. So in the end it crashes.

I had the same set up running at a different company with A LOT more messages coming in but it was upgraded to early Graylog 2.0 from Graylog2 and there was never the 2.1 running there. No problems at all.

With this machine there was no tweaking done except raising the ulimits core nofile nproc which did not improve anything. So basically out of the box configuration of the OVA image (2.1.0).

Error:
```
2016-10-09_08:05:41.75311 2016-10-09 10:05:40,492 WARN : org.graylog2.shared.buffers.InputBufferImpl - Unable to process event <invalid>, sequence 66707
2016-10-09_08:05:41.75314 java.lang.OutOfMemoryError: Java heap space
2016-10-09_08:05:45.19320 2016-10-09 10:05:45,192 ERROR: org.graylog2.shared.buffers.JournallingMessageHandler - Unable to convert RawMessageEvent to Journal.Entry - skipping event
2016-10-09_08:05:45.19323 java.lang.NullPointerException
2016-10-09_08:05:45.19323       at org.graylog2.shared.buffers.JournallingMessageHandler$Converter.apply(JournallingMessageHandler.java:138) [graylog.jar:?]
2016-10-09_08:05:45.19324       at org.graylog2.shared.buffers.JournallingMessageHandler$Converter.apply(JournallingMessageHandler.java:120) [graylog.jar:?]
2016-10-09_08:05:45.19324       at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:640) [graylog.jar:?]
2016-10-09_08:05:45.19324       at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) [graylog.jar:?]
2016-10-09_08:05:45.19324       at java.util.AbstractCollection.toArray(AbstractCollection.java:141) [?:1.8.0_101]
2016-10-09_08:05:45.19325       at java.util.ArrayList.<init>(ArrayList.java:177) [?:1.8.0_101]
2016-10-09_08:05:45.19325       at com.google.common.collect.Lists.newArrayList(Lists.java:146) [graylog.jar:?]
2016-10-09_08:05:45.19325       at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:83) [graylog.jar:?]
2016-10-09_08:05:45.19325       at org.graylog2.shared.buffers.JournallingMessageHandler.onEvent(JournallingMessageHandler.java:45) [graylog.jar:?]
2016-10-09_08:05:45.19326       at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129) [graylog.jar:?]
2016-10-09_08:05:45.19327       at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
2016-10-09_08:05:45.19327       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

```

## Steps to Reproduce (for bugs)

After ~ 2 days and ~300.000 messages the heap memory is fully used. Graylog becomes unresponsive.

## Your Environment

The OVA from graylog deployed via Xenserver, the node has 6GB RAM and 2 processors assigned
* Graylog Version: 2.1.1+01d50e5, codename Smuttynose JVM Oracle Corporation 1.8.0_101 on Linux 4.2.0-42-generic
* Elasticsearch Version: 2.3.1
* MongoDB Version: db version v3.2.5
* Operating System: Ubuntu
* Browser version:

* Set up 1 GELF UDP input globally, appliance-gelf-udp and appliance-syslog-udp are running locally.
* JAVA Options
```
1460 ?        Ssl   16:56 /opt/graylog/embedded/jre/bin/java -Xms3g -Xmx3g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Djna.nosys=true -server -Djava.net.preferIPv4Stack=true -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=3333 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=1 -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/opt/graylog/elasticsearch -cp /opt/graylog/elasticsearch/lib/elasticsearch-2.3.1.jar:/opt/graylog/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch start
 1511 ?        Ssl  479:09 /opt/graylog/embedded/jre/bin/java -Xms1g -Xmx1500m -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow -jar -Dlog4j.configurationFile=file:///opt/graylog/conf/log4j2.xml -Djava.library.path=/opt/graylog/server/lib/sigar/ -Dgraylog2.installation_source=ova /opt/graylog/server/graylog.jar server -f /opt/graylog/conf/graylog.conf
```
[graylogdump.txt](https://github.com/Graylog2/graylog2-server/files/515661/graylogdump.txt)
![graylogstatus](https://cloud.githubusercontent.com/assets/22675949/19184105/d5ad7ba2-8c7b-11e6-8bea-c6ffee231dd2.png)

**Comment by jalogisch** [comment]
Hej @4BRobby 

could you please provide your configuration, include the input and extractor configuration. Additional please create and attach an [apollo](https://github.com/Graylog2/apollo) output. 

If we have all Information we can look deeper into this issue.

**Comment by 4BRobby** [comment]
I hope I included everything you need. I noticed the decompress-size option on my own created gelf udp input.

[Graylogconf.zip](https://github.com/Graylog2/graylog2-server/files/519238/Graylogconf.zip)
[graylog_apollo_bundle-2016-10-10T11-45-58.zip](https://github.com/Graylog2/graylog2-server/files/519208/graylog_apollo_bundle-2016-10-10T11-45-58.zip)

**Comment by kroepke** [comment]
I've had a look at the data but couldn't find anything obvious.

A couple of questions:
* Is there anything special about the messages, such as very large messages?
* Does the problem persist if you remove the nginx streams that are installed by default (maybe they case a regex backtracking issue of some sort).
* Can you please enable the garbage collection log for the server, such as [described here](https://developer.atlassian.com/blog/2015/04/Tip-Of-The-Week-Enable-GC-Logging/)

Thanks!

**Comment by 4BRobby** [comment]
- There are large messages. Is there any graylog-built-in possibility to show the average / max size of messages?
- Removed the provided nginx streams.

**Comment by kroepke** [comment]
Ok, very large message can lead to both excessive processing time (e.g. if there is regex backtracking going on) as well as dramatically increase memory consumption, if the internal ring buffer sizes are large.

You can take a look at the per-input `rawSize` metrics in the metric overview for each node. It will show only the internal ID of the input, but the metric name has the corresponding type in its name.
The unit will by shown as "events/second" but in reality is "bytes". There are moving averages which might give you a hint about the distribution. Other than that we don't have a good histogram yet.

As a rough guideline: The maximum heap usage will be proportional to `ring_size * 2 + inputbuffer_ring_size * avg(message size)` in bytes. That is the baseline of what the strings require in memory, plus any additional object overhead and memory used by processing them (regex matches, type conversions etc).
If the ring sizes are large, then your server might use much more than the 1.5gb you have configured. I've seen deployments with large messages needing to run upwards of 20GB heap to be able to cope.
Generally Graylog works better with smaller messages, if you cannot cut down on message size you might want to scale out and add more graylog server nodes to distribute memory load better.

**Comment by 4BRobby** [comment]
I remember seeing that point in the metrics. But the "events" description is really missleading. Is "Total" the size of the ring?
```
Total: 163,970,059 events
Mean: 15,087.17 events/second
1 minute avg: 5.87 events/second
5 minute avg: 323.83 events/second
15 minute avg: 6,906.51 events/second
```
Ring buffer size is this one, corect?
```
org.graylog2.buffers.input.size
Value: 65,536
```
Calculating heap size:
163970059 * 2 = 327940118
15087 * 65536 = 988741632
Total = 1310980118 (1,2 GB)
Is this the correct way to calculate? It might be too much when running nightly jobs.


There are no complex regex matches running only two alerts with a simple stream (level+one field) configured...

I will have to add some more logging statistics to my small logging framework so I can find out detailed the source of the bigger messages and then reduce them.

**Comment by kroepke** [comment]
No, this is the input's traffic since it was started (or Graylog's restart). (Refer to https://github.com/Graylog2/graylog2-server/blob/581eb1f821ff8787f4df156d36a3b17aeb485fb9/graylog2-server/src/main/java/org/graylog2/plugin/inputs/MessageInput.java#L326-L347)

So in total you'd have seen ~163MB on that input, with the 15 minute average message size being just short of 7kb.
That's not what I would consider "large" yet, however if every message is that large it does add up:
```
((65536+65536+65536)*7168) / 1024 / 1024 = 1344
```
That's rough memory usage in MB, which would give your garbage collector a very hard time.
I would lower the ring sizes considerably and see how things improve:
`ring_size = 4096` (this is the value used for processing and output ring buffers)
`inputbuffer_ring_size = 8192` (this is used to get things off the network and into the disk journal)

After that your memory issues should be gone. Most of the time processing speed doesn't suffer, even if that's counter intuitive at first.

**Comment by 4BRobby** [comment]
Thank you a lot for your help! I will reconfigure and run and we will see what happens.
Additionally I have increased XMX to 3GB now.
Nightly jobs will fire tomorrow early morning and we will see the results. 
Thanks again for digging into this!

**Comment by kroepke** [comment]
Great, OOM is always a source of concern, so I'd be more than happy to find out that it is just a tuning thing :)

**Comment by jalogisch** [comment]
@4BRobby did you have any new Information on this issue?

**Comment by 4BRobby** [comment]
@jalogisch 
Jan, the problem seem to be solved. It is running now 10 days without a need to restart.
Summary:
- In graylog.conf set `ring_size = 4096` and `inputbuffer_ring_size = 8192` - Graylog became more responsive and stable
- Increased JVM for graylog server to 3 GB (1,2GB used now - so 2GB might be safe enough).

Thank you for your help @kroepke
