### ISSUE TITLE
Rule with dotted field doesn't work

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#2939]
When you write a stream Rule that checks against a field containing dot in the name, it doesn't work.

This is the case when you use something like Logstash, or even the Docker GELF log driver. The field is sent to Graylog and the dots are replaced to '_' character.

But when writing a rule for that field (like io.kubernetes.pod.namespace, that turns to io_kubernetes_pod_namespace on graylog) the system understands only the original name, not the replaced one.

Although I think this is the right behaviour, this may lead to misconfiguration of rules, as the Rules tester reports that the message is not routed to that stream with that rule.

The attached image shows a stream with routed messages correctly, but the rule tester reporting that no message should be routed.
## Steps to Reproduce (for bugs)
1. Point a Docker Daemon to Log into some Graylog Collector, with the following option: --log-driver=gelf --log-opt gelf-address=udp://graylogserver:12201 --log-opt labels=graylog.test.xpto 
2. Run a container with docker run -l graylog.test.xpto=123change -p 8080:80 nginx
3. Generate some workload against this container (curl http://IP-of-docker-machine:8080)
4. Create a Stream, a Rule, load some message of this source to the Rule Tester, and create a rule that the field 'graylog.test.xpto' must be present. The tester will report that no message is going to be routed there
5. Save the rule, the Stream, generate more workload on NGINX and see the messages appearing there.
6. See that the field have a new name: graylog_test_xpto (due to the ES incompability with '.' name fields)
7. Change the rule to graylog_test_xpto. Now the rule tester will accept some of the messages
8. Generate more workload.
9. No message will be routed anymore from Docker :)
## Context

Trying to log my Kubernetes Cluster Containers to Graylog, routing only messages with the field io.kubernetes.pod.namespace
## Your Environment

Graylog 2.1.1
CoreOS 1192.0.0
Docker 1.12.1 

Elasticsearch Version: 2.4.1
- MongoDB Version: 3.3

**Comment by rikatz** [comment]
@jalogisch I don't think this is a feature, but a bug, as Graylog doesn't interpret field names the same way it's on ElasticSearch.

**Comment by joschi** [comment]
@rikatz Elasticsearch 2.x didn't support dots in field names up until ES 2.4.0 (which re-introduced this): https://www.elastic.co/guide/en/elasticsearch/reference/2.4/dots-in-names.html

Since Graylog 2.x aims to support ES 2.x versions before ES 2.4.0, we won't allow dots in field names in this version line. The next version which might change this again (and that's why it's a "feature"), will be Graylog 3.0.0.

**Comment by rikatz** [comment]
@joschi Yeap, understood. The thing is that the rules generator behaviour differs from what really happens.

When you put some messages with dotted fields, Graylog converts it correctly. But the rule tester doesn't. So, you send to Graylog some messages with dotted fields, tries to write a rule, and it haves a strange behaviour, as it says no message could be routed with the rule containing '.' fields, what in fact doesn't happens (as reproduced on step 4 above).

Anyway, not a big deal with that. Just to inform you that the rules tester/generator differs the behaviour from what really happens, when Graylog receives fields containing dotted fields.

**Comment by rikatz** [comment]
@joschi Just to help. Couldn't test the newer version of Graylog yet, but maybe this is solved there :smile: 

Can someone try to reproduce this in GL 2.3?

**Comment by joschi** [comment]
@rikatz Since Graylog 2.3.x also aims to work with Elasticsearch versions prior to 2.4.0, the same rules apply.
