### ISSUE TITLE
How can i really delete the message in ElasticSearch?

### ISSUE THREAD

**Issue by RistoryWang** [Graylog2/graylog2-server#2941]
## Possible Solution

I hava delete the message by the delete-by-query plugin
but i still can see these messages in the indices which show as “deleted message ：20890980”
best regard

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:2.0.3-1
* Elasticsearch Version:2.3.5
* MongoDB Version:3.2.8
* Operating System:centos 7.0
* Browser version:Chrome 53

**Comment by joschi** [comment]
@RistoryWang Documents in an Elasticsearch index are only marked as deleted, if you "delete" them via the Elasticsearch HTTP API, see https://www.elastic.co/guide/en/elasticsearch/guide/2.x/dynamic-indices.html#deletes-and-updates for details.

You need to force-merge the affected indices if you want to actually remove the documents and free the disk space, see https://www.elastic.co/guide/en/elasticsearch/guide/2.x/merge-process.html and https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-forcemerge.html for details.
