### ISSUE TITLE
PHP-FPM latency when Graylog is running

### ISSUE THREAD

**Issue by joel-lbn** [Graylog2/graylog2-server#2947]
Hello,

We have a server on which graylog-server is installed. This server is also used to host other websites and we use Apache (2.2.15) and PHP-FPM (5.6.5) for those sites.
When I start graylog-server, even though there is no log at all configured for graylog-server to read (I deleted all the inputs), my PHP files (a.php) all take more time to be loaded (around 30sec more on response time), but my HTML files (b.html) are not affected.

Example : 
**When graylog is not running :** 
time curl -Lk "http://mysite/joel.html"
joel
_real    0m 1.34s_
user    0m 0.04s
sys     0m 0.01s
time curl -Lk "http://mysite/joel.php"
joel
_real    0m 2.09s_
user    0m 0.03s
sys     0m 0.04s

**When graylog is running :** 
time curl -Lk "http://mysite/joel.html"
joel
_real    0m 1.57s_
user    0m 0.03s
sys     0m 0.04s
time curl -Lk "http://mysite/joel.php"
_joel_
real    0m 32.62s
user    0m 0.00s
sys     0m 0.04s

Has this issue already been sighted ?
If yes, is there a specific configuration that need to be implemented in Apache or PHP or graylog to solve this ?

* Graylog Version: 2.0.3-1
* Elasticsearch Version: 2.3.3-1
* MongoDB Version: 3.0.12
* Operating System:  CentOS 6.7

Thank you in advance,
Joël

**Comment by joschi** [comment]
@joel-lbn We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
