### ISSUE TITLE
drop messages larger than X (b|MB|GB)

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#2948]
## Expected Behavior

It should be possible to define a maximal size that a message that is processed can have. So big messages will not drop the performance of the server or make it processing of one message for hours.
## Current Behavior

Big messages (coming as GELF) can run up to several hours in the processing if you need to run regex/grok pattern on them and your Graylog Journal will fill with messages because they wait to be processed.

Additional storing them in Elasticsearch will raise additional problems.

This can be used as an internal attack against the central logging infrastructure because the system can't be used and maybe drop messages that are important. 
## Possible Solution

Drop the messages on Input and write a log entry about the drop. 

This Log entry should include:
- source
- input
- size
## Context

If a developer starts to write, log messages direct into graylog, using gelf it could happen that big messages contain several hundred GB of Logdata get into graylog and need to be compressed. If the inputs have expensive regex this can slow down the processing and let messages fall out of the journal.

**Comment by joschi** [comment]
@jalogisch This is basically a duplicate of #1131 but I like the description of this issue better. :wink:

**Comment by jalogisch** [comment]
# Possible Solution
Because of local Laws, it might not be a solution to drop any message. Maybe it would just be possible to drop the **message** field and add another field **trunked_message : yes**

This way you would loose the content of the message but would be able to know that something had happened.

**Comment by jalogisch** [comment]
with the processing pipelines and the newly added field `gl2_message_size` it is possible to create such rules if needed individually. 

You can check the message size in a processing pipeline and create rules that reduce the size of your message or drop certain parts if that is possible. 

It is not likely that Graylog can build a default behavior that fits all needs. All needed parts to solve that are given.
