### ISSUE TITLE
Endless errors while elastic unavailable

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#2949]
Currently found that graylog stopped sending messages to elastic
CPU usage from ganglia:
![image](https://cloud.githubusercontent.com/assets/17475270/19380776/56400926-9201-11e6-876a-a055d22ea372.png)

In logs many erros aboutelastic problems.
## Expected Behavior

Graylog must correctly detect and process unexpected elastic unavailability
## Current Behavior

Graylog enters endless loop of errors
Full log: [server.txt](https://github.com/Graylog2/graylog2-server/files/529038/server.txt)
## Your Environment
- Graylog Version: 2.1.1
- Elasticsearch Version: 2.3.5

**Comment by bernd** [comment]
This issue should be fixed with the upcoming Graylog 2.3 and the switch to the HTTP transport to communicate with Elasticsearch. Please re-open if you still see this. Thank you!
