### ISSUE TITLE
key_value splitting on space

### ISSUE THREAD

**Issue by spejosh** [Graylog2/graylog2-server#2952]
The key_value pipeline function is splitting on spaces and the defined delimiter.

## Expected Behavior
When a specific list of delimiters is defined the function should only split on those items.

## Current Behavior
key_value appears to split on the defined delimiter and also space.

## Steps to Reproduce (for bugs)
I have the following pipeline rule:
```
rule "SymantecParseKeyValue"
when
  has_field("message")
then
  // Try to parse message
  let split_message = key_value(to_string($message.message), ",", ":", true, true, ",", " ", " ");
  set_fields(split_message);
end
```

With the example message:
```
<54>Oct 11 22:27:43 SERVER-NAME SymantecServer: Virus found,IP Address: 192.168.5.234,Computer name: PC-NAME-HERE,Source: Real Time Scan,Risk name: Trojan.Kotver!lnk,Occurrences: 1,C:\Users\Admin123$\AppData\Local\a2c40b\65ac9c.lnk,'',Actual action: Left alone,Requested action: Cleaned,Secondary action: Quarantined,Event time: 2016-10-12 02:25:35,Inserted: 2016-10-12 02:27:43,End: 2016-10-12 02:26:41,Last update time: 2016-10-12 02:27:43,Domain: Default,Group: My Company\Company Users,Server: SERVER-NAME,User: Admin123$,Source computer: ,Source IP: ,Disposition: Reputation was not used in this detection.,Download site: ,Web domain: ,Downloaded by: ,Prevalence: Reputation was not used in this detection.,Confidence: Reputation was not used in this detection.,URL Tracking Status: Off,,First Seen: Reputation was not used in this detection.,Sensitivity: ,MDS,Application hash: AF27F66565846C179788FB4ABCAE6A3B328AEA7B7EC78191B25AC21CF4924D71,Hash type: SHA2,Company name: ,Application name: 65ac9c.lnk,Application version: ,Application type: 127,File size (bytes): 880,Category set: Malware,Category type: Virus
```
I would expect to see the following to be part of the parsed message:
```
IP Address
    192.168.5.234
Source
    Real Time Scan
Risk Name
    Trojan.Kotver!lnk
etc.
```

This is what I get instead:
```
C
    \Users\Admin123$\AppData\Local\a2c40b\65ac9c.lnk
Confidence
    Reputation was not used in this detection.
Disposition
    Reputation was not used in this detection.
Domain
    Default
End
    2016-10-12 02
Group
    My Company\Tekmark Users
Inserted
    2016-10-12 02
Occurrences
    1
Prevalence
    Reputation was not used in this detection.
Server
    ZNJ-IISAPPS-01
Source
    Real Time Scan
User
    Admin123$
```

## Your Environment
* Graylog Version: 2.1.1

**Comment by joschi** [comment]
@spejosh You message isn't composed of distinct key-value pairs but is using a custom format.

I'd recommend using some grok patterns to parse this sort of message.

As far as I see, the `key_value()` function is working as intended.

**Comment by kroepke** [comment]
@joschi I think the message that was pasted simply was the original syslog message for reproduction. AFAICS the `message` field of that syslog message is composed of key values pairs separated by `,`, with a value splitter of `:`.

Unless I misread @spejosh's intention.

**Comment by joschi** [comment]
@kroepke I understood that.

But these parts of the message simply don't fit into the key-value pair schema (with `:` and `,` as separators):
```
Occurrences: 1,C:\Users\Admin123$\AppData\Local\a2c40b\65ac9c.lnk,''
```

```
Inserted: 2016-10-12 02:27:43,End: 2016-10-12 02:26:41
```

**Comment by kroepke** [comment]
@joschi Ah damn, I didn't see that properly in the preview :(

I'll revert the test case commit.

**Comment by kroepke** [comment]
@spejosh As @joschi said, the string isn't composed of proper key/value pairs because of several stray `:` characters.

Also some of the potential new field names contain invalid characters, most notable `IP Address`. Graylog field names cannot contain whitespace.

I guess the underlying issue to address here is better debugging capabilities for rules.

**Comment by spejosh** [comment]
@kroepke understood.  Was hoping to avoid writing a complicated Grok pattern for this since it is basically key value pairs, just not in a compatible format.

Better debugging would be greatly appreciated.  I tried to search logs or find details on what the return value of key_value exactly is, but I couldn't find it.

Thank you for the assistance.
