### ISSUE TITLE
Sort the fucntions quick reference from the pipelines alphabetically

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#2956]
Since we get more and more functions to be able to use in the pipelines ( :tada: ) we need some sorting or search function in the quick reference.

Consider searching or sorting like you know it from your telephone contact list. :iphone: 

Thanks in advance :smile:

**Comment by jalogisch** [comment]
This issue was moved to Graylog2/graylog-plugin-pipeline-processor#113
