### ISSUE TITLE
docker hub documentation error

### ISSUE THREAD

**Issue by FallenRiteMonk** [Graylog2/graylog2-server#2957]
the first example of a compose file on the docker hub documentation still contains: ``` GRAYLOG_ENDPOINT_URI: http://127.0.0.1:9000/api``` which should be as in the second example: ```GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api```

**Comment by joschi** [comment]
@FallenRiteMonk Thanks! I just fixed the `docker-compose.yml` file at https://hub.docker.com/r/graylog2/server/
