### ISSUE TITLE
User with Stream edit permissions can create Alert but they can't edit alert subscribtions

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#2958]
Users with the correct permissions should get the full function set.

## Expected Behavior
users which can alerts should also be able to add someone to the alert.

## Current Behavior
the user have to contact an admin to edit the alert they've made

## Your Environment
Graylog 2.1.1+01d50e5 on (Oracle Corporation 1.8.0_102 on Linux 3.10.0-327.22.2.el7.x86_64)

**Comment by coffee-squirrel** [comment]
I believe this is a duplicate of #2502 , which is currently marked for 2.2.0.

**Comment by gruselglatz** [comment]
@coffee-squirrel you are right. thank you :+1:
