### ISSUE TITLE
Process buffer & journal fills when DNS is down

### ISSUE THREAD

**Issue by JulioQc** [Graylog2/graylog2-server#2963]
## Expected Behavior
Some error is displayed to alert that processing is stalled, at the minimum (only current msg is when journal is full)
A rDNS timeout or a better failover to secondary DNS, aside from the system's mechanism.

## Current Behavior
When the main DNS of the domain went down, the processing stopped working. 
Probably waiting on the query result for all those input configured for reverse DNS.
The system didn't seem to switch to the secondary DNS configured.
The system didn't seem to timeout the query. Msg just stayed in buffer (and journal when buffer full).

## Possible Solution
A rDNS timeout or a better failover to secondary DNS, aside from the system's mechanism.

## Steps to Reproduce (for bugs)
- Configure some input to reverse DNS the IPs,
- Make sure multiple DNS are configured (via DHCP for me, confirmed with 'cat /etc/resolv.conf'),
- Get some logs coming in,
- Make the primary DNS non-responding (in our case, box down for maintenance)
- Observe how the Process Buffer will fill to maximum capacity, followed by the Journal.
- Note that the DecodeTime and ParseTime metrics are crazy high. 

## Context
Our main DNS went down, 
message process stalled, 
rDNS queries did not time out nor used secondary DNS. 

I had no idea the issue was caused by DNS stalling until a colleague advised of an unrelated DNS query issue. Investigating her trouble lead me to fix the DNS server and shortly after, I noticed the processing resumed normally on Graylog. Then I realized the rDNS inputs where the ones not being processed. 

## Your Environment

8 vCPU
16 GB RAM
750 GB SAS SSD

* Graylog Version: 2.1.1 OVA 
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by jalogisch** [comment]
https://github.com/Graylog2/graylog2-server/pull/2964/commits/2013405ac6aa23be5ff6460cb00fda5ea468fe62

problem is solved
