### ISSUE TITLE
Reading in ModSecurity logs using collector-sidecar

### ISSUE THREAD

**Issue by jasonmull** [Graylog2/graylog2-server#2965]
I'm attempting to use collector sidecar to pull in audit files from ModSecurity the root of the log files reside at /var/log/modsec_audit/.  The actual log files are two folders lower, as modsecurity creates the folders that are timestamped by day and then minute.  

Inside my collector input config, I have my logfile path as /var/log/modsec_audit/*, and I have enabled recursive file lookup, but to this point, no modsecurity logs are being picked up.  THe same sidecar instance is grabbing apache logs perfectly fine, however.  I feel like the issue is related to the directory structure, but I'm not seeing an issue with my config.  Any thoughts?

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
