### ISSUE TITLE
Add Tag to log entry

### ISSUE THREAD

**Issue by rklak** [Graylog2/graylog2-server#2974]
Hi, it would be useful to have an ability to tag a log entry in Graylog2. Each day we verify our logs on servers and its hard to find for example last place/log that was analyzed yesterday. Some entries needs to be rembered for further use to verify after talk with someone or marked as a part of some temporary group.
## Expected Behavior

When i click on log - than I would like to have a possibility to add a global tag, so I can search by it later.
## Current Behavior

Its not achiveable.

**Comment by joschi** [comment]
@rklak You can search by the message ID, which uniquely identifies each message.

**Comment by rklak** [comment]
Yes, I can save in my notepad IDs of log entries and group thme there by my Tag but I'm not the only one who is analyzing logs. And my notepad is not open for everyone :)

**Comment by jalogisch** [comment]
In our experience this is some edge use case because most people will not read all log files.

This might be solved on your own building a plugin for Graylog. If more people like to have this feature, please comment below.

**Comment by BlueTeamNinja** [comment]
In the interest of not duplicating - I thought I would add to this.  I highly support the idea of a special 'tag' field.  In logstash (and likewise in the beats collectors many of us use) there is a 'Tag' field, which is actually an array of booleans.  This allows for easy organizing and searching for things that may not be unique enough to warrant a separate stream or pipeline.  A huge amount of security analysis on logs is stacking low-value intelligence into meaningful intelligence.  Tags I would love to use for threat hunting:

- 'New domain'

- 'Top 1Million' 

- 'Suspicious TLD'

- 'Suspicious Activity'

- (IDS / SMTP Direction) 'Incoming/Outgoing' 

The above would make vastly more powerful dashboards and are applicable to a number of my logs.   Concatenating a string is not the same thing or as powerful for visualizing as an array of booleans.  

e.g.  [Search]  hostname:ASSET_NAME AND outgoing AND 'New Domain'

This could easily show IDS logs, Firewall Logs or SMTP logs - but all are communications to recently registered domains and completely essential to long-tail analysis.

I mentioned it in this community forum:  https://community.graylog.org/t/tags-am-i-missing-it/10594/7
