### ISSUE TITLE
no alert

### ISSUE THREAD

**Issue by taoyang987** [Graylog2/graylog2-server#2975]
## Expected Behavior

when a stream get a new message and suite the alert condition ,it should alert
## Current Behavior

when a stream get a new message and suite the alert condition ,it did not alert，and there is no Triggered alerts records。
all my stream did not alert at sametime。

## Possible Solution

i restart the container ，it didn't work。
i delete the old  alert condition，and make new one，it solve the problem of that stream。
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
i can not Reproduce the problem。 it worked well before ，and i did nothing to the stream.(i once created some extractor to some inputs，created some dashboard widgets)
i cheked the docker container logs and found nothing strange

## Your Environment

docker-compose
tag:2.1.1-1
* Graylog Version:2.1.1
* Elasticsearch Version:image: "elasticsearch:2"
* MongoDB Version:image: "mongo:3"
* Operating System:docker in centos7
* Browser version:chrome
i created the containers at tag，2.1.0-1，and upgrade version by version

**Comment by taoyang987** [comment]
update

**Comment by jalogisch** [comment]
Unfortunately the issue is not reproducible in the latest release. Please re-open this issue if it still occurs, ideally with a set of reproducible steps. 

Thanks!
