### ISSUE TITLE
In/Out msg/s count staying around 0/0

### ISSUE THREAD

**Issue by eroji** [Graylog2/graylog2-server#2977]
Web UI inexplicably indicating very low in/out msg/s with errors being logged in server log and system messages repeatedly.

## Expected Behavior
When the UI was displaying correctly, it would typically show 7k-25k msg/s constantly. There is no possibility that we are sending that few messages because all our environments are logging to this cluster.

## Current Behavior
The In/Out msg/s in web UI shows 0/0 most of the time. It occasionally ticks up but goes back to 0/0. The actual amount of messages being logged seems to be correct. We are also seeing a high number of entries in the server log showing "org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering." System messages in web UI also shows "Notification condition [NO_MASTER] has been fixed."

## Steps to Reproduce (for bugs)
Started Graylog and it soon goes into this state.

## Context
I am not entirely sure if this is a display problem or is actually causing messages to be dropped.

## Your Environment
We have a Graylog collector server (master), and a Graylog web UI server (slave), a MongoDB server and 5 ES data nodes. All log messages are being sent to the collector server, and users access Graylog via the web UI server.

* Graylog Version: 2.1.1
* Elasticsearch Version: 2.3.5
* MongoDB Version: 3.2.1
* Operating System: CentOS 6.7
* Browser version: Chrome 53

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
