### ISSUE TITLE
Graylog / Elasticsearch dont Start

### ISSUE THREAD

**Issue by Chief12** [Graylog2/graylog2-server#2979]
<Elasticsearch wont Start>

Graylog: 2.1.1
Elasticsearch: 2.4.1

> :/var/log/elasticsearch# systemctl status elasticsearch.service
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled)
   Active: failed (Result: exit-code) since Mon 2016-10-03 07:25:31 CEST; 5min ago
     Docs: http://www.elastic.co
 Main PID: 1257 (code=exited, status=1/FAILURE)

> Oct 03 07:25:31 S250A030 elasticsearch[1257]: at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:67)
> Oct 03 07:25:31 S250A030 elasticsearch[1257]: at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:45)
> Oct 03 07:25:31 S250A030 elasticsearch[1257]: at org.elasticsearch.common.settings.loader.YamlSettingsLoader.load(YamlSettingsLoader.java:46)
> Oct 03 07:25:31 S250A030 elasticsearch[1257]: at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1080)
> Oct 03 07:25:31 S250A030 elasticsearch[1257]: at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1067)
> Oct 03 07:25:31 S250A030 elasticsearch[1257]: at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:88)
> Oct 03 07:25:31 S250A030 elasticsearch[1257]: at org.elasticsearch.bootstrap.Bootstrap.initialSettings(Bootstrap.java:218)
> Oct 03 07:25:31 S250A030 elasticsearch[1257]: at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:257)
> Oct 03 07:25:31 S250A030 elasticsearch[1257]: at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
> Oct 03 07:25:31 S250A030 elasticsearch[1257]: Refer to the log for complete error details.
> 

I Don´t Know why it not Start.

tailf /var/log/graylog-server/server.log

**[discovery] [graylog-8fb3738a-4550-4bb8-9867-5faf2f5096d1] waited for 3s and no initial state was set by the discovery
2016-10-03T07:27:02.870+02:00 INFO  [node] [graylog-8fb3738a-4550-4bb8-9867-5faf2f5096d1] started
2016-10-03T07:27:07.880+02:00 WARN  [IndexerSetupService] Could not connect to Elasticsearch
2016-10-03T07:27:07.880+02:00 INFO  [IndexerSetupService] If you're using multicast, check that it is working in your network and that Elasticsearch is accessible. Also check that the cluster name setting is correct.
2016-10-03T07:27:07.881+02:00 INFO  [IndexerSetupService] See http://docs.graylog.org/en/2.1/pages/configuration/elasticsearch.html for details.
2016-10-03T07:27:14.316+02:00 INFO  [IndexRangesCleanupPeriodical] Skipping index range cleanup because the Elasticsearch cluster is unreachable or unhealthy**

server.conf excerpt:

rest_listen_uri = http://10.250.20.60:12900/
web_listen_uri = http:/10.250.20.60:9000/
elasticsearch_cluster_name = graylog
elasticsearch_discovery_zen_ping_unicast_hosts = 127.0.0.1:9300
elasticsearch_discovery_zen_ping_multicast_enabled = false

 
elasticsearch.yml excerpt:

cluster.name: graylog
node.master: true
node.data: true
bootstrap.mlockall: true
network.host: 127.0.0.1
discovery.zen.ping.multicast.enabled: false
discover.zen.ping.unicast.hosts: ["127.0.0.1"]

Elasticsearch and Graylog are on the Same Server

**Comment by joschi** [comment]
@Chief12  > ```
Oct 03 07:25:31 S250A030 elasticsearch[1257]: Refer to the log for complete error details.
```

Maybe you should do exactly this, see http://docs.graylog.org/en/2.1/pages/configuration/file_location.html for the location of the Elasticsearch logs.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Chief12** [comment]
/var/log/elasticsearch# ls
root@S250A030:/var/log/elasticsearch#


There are no Files :(
