### ISSUE TITLE
the graylog performance

### ISSUE THREAD

**Issue by zhu312542860** [Graylog2/graylog2-server#2991]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
the single graylog-server can support how much message per second??
I hava the three node graylog-server and elasticsearch node，but when 10000 message per second，my graylog slowly。if i can optimize my graylog-server performance,ths

## Your Environment

* Graylog Version:2.0.1
* Elasticsearch Version:2.3.2
* MongoDB Version:3.2.6
* Operating System:Oracle linux 6.5
* Browser version:

**Comment by mariussturm** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
