### ISSUE TITLE
Search button not functioning on 2.1.1-1

### ISSUE THREAD

**Issue by bsmithyman** [Graylog2/graylog2-server#2994]
When clicking the query button in any search page, I get a JS error and the query does not execute.

## Expected Behavior
Clicking the green query button executes the current search query.

## Current Behavior
Queries do execute properly if triggered by automatic updates. Dashboards, etc. also work fine. This is reproduced in at least Chrome & Safari. See image below.

## Possible Solution
Looks to be a JS bug: `Uncaught TypeError: O.executeSearch is not a function`

## Steps to Reproduce (for bugs)
![iivtaynasj](https://cloud.githubusercontent.com/assets/4269565/19734114/53a247de-9b74-11e6-97d8-88229a87455c.gif)

## Environment
I am running Graylog2 in Docker, with ,  and .
* Graylog Version: `graylog2/server:2.1.1-1`
* Elasticsearch Version: `elasticsearch:2.3.5`
* MongoDB Version: `mongo:3`
* Operating System: Debian Linux (Jessie / 8) & Docker on GCE
* Browser version: Chrome 54, Safari 10, Firefox 48

**Comment by joschi** [comment]
@bsmithyman If you upgraded from an earlier version of Graylog, please prune your browser cache to rule out issues with that.

Other than that, I can't reproduce the issue with Chrome, Safari, or Firefox.

**Comment by edmundoa** [comment]
@bsmithyman in case you upgraded, please also ensure you upgraded all plugins alongside with Graylog. If you are not sure about which plugin versions to use, share the plugin versions you can find in _System -> Nodes -> Node_ in here.

**Comment by bsmithyman** [comment]
Thanks @joschi, @edmundoa:

Sounds like it's an isolated case and that the plugin versions could be the issue; I believe we did upgrade to the 2.1 release from an earlier 2.0 version. I'll try to get some more details and log it here for others who run into something similar.

I appreciate the help!

**Comment by bsmithyman** [comment]
Update: Some cleanup on the plugins seems to have solved this issue. I removed some that were not being used, and updated the builtin plugins.

![image](https://cloud.githubusercontent.com/assets/4269565/19770553/b070aadc-9c2d-11e6-9303-aee278ec3f0f.png)

The non-standard plugins that are installed now include `Slack 2.1.0` and the `HttpMonitorInput 1.0.2`. They seem to work fine with `Graylog2 2.1.1`. From my testing, I think the main culprit was the `DnsResolverFilter` plugin.

Thanks for the help!

**Comment by edmundoa** [comment]
Thank you for the update @bsmithyman! I think the problem was in one of the UI plugins, that's why you could see an error in your browser console, and not in the Graylog logs. Anyway, good to see that you solved it 👍
