### ISSUE TITLE
Graylog 2.1.0 API limit & offset error while searching messages

### ISSUE THREAD

**Issue by onedaywillcome1** [Graylog2/graylog2-server#3005]
We are currently try to get messages via Graylog API for our platform. When we execute absolute or relative search with limit and offset fields, we observed that limit & offset is not working properly.
 
Expected Behavior
When we execute below command, we have to get 5 messages but we are getting whole list of messages between selected timestamps, limit option is not working as shown.

**Command**: curl -XGET --user graylog:123 "http://localhost:12900/search/universal/absolute?query=java&from=2016-10-25T09:53:25.920Z&to=2016-10-28T09:53:25.920Z&fields=message&limit=5

Expected output:

> 1=> "2016-10-27T08:40:31.720Z","Hello there from Java"
> 2 => "2016-10-27T15:07:22.410Z","Hello there from Java"
> 3 => "2016-10-27T15:17:17.741Z","Hello there from Java"
> 4 => "2016-10-27T14:46:01.427Z","Hello there from Java"
> 5 => "2016-10-27T08:41:33.224Z","Hello there from Java"

Current Behavior
It lists whole 15 messages that we don't want.

> 1 => "2016-10-27T08:40:31.720Z","Hello there from Java"
> 2 => "2016-10-27T15:07:22.410Z","Hello there from Java"
> 3 => "2016-10-27T15:17:17.741Z","Hello there from Java"
> 4 => "2016-10-27T14:46:01.427Z","Hello there from Java"
> 5 => "2016-10-27T08:41:33.224Z","Hello there from Java"
> 6 => "2016-10-27T14:34:13.997Z","Hello there from Java"
> 7 => "2016-10-27T14:34:30.354Z","Hello there from Java"
> 8 => "2016-10-27T14:45:32.794Z","Hello there from Java"
> 9 => "2016-10-27T15:09:45.820Z","Hello there from Java"
> 10 => "2016-10-27T15:16:29.293Z","Hello there from Java"
> 11 => "2016-10-27T15:15:54.205Z","Hello there from Java"
> 12 => "2016-10-27T15:07:10.914Z","Hello there from Java"
> 13 => "2016-10-27T15:06:02.160Z","Hello there from Java"
> 14 => "2016-10-27T15:17:05.059Z","Hello there from Java"
> 15 => "2016-10-27T14:32:56.995Z","Hello there from Java"

Note: Same behaviour is same for offset, offset is not working properly when we specify value of offset. We have tested these features via graylog api-browser, again faced same problem. 

Our Environment

Amazon AMI 
Graylog  2.1.0+62db7e0
Linux ip-10-0-26-77 4.4.19-29.55.amzn1.x86_64 #1 SMP Mon Aug 29 23:29:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by edmundoa** [comment]
Hi @onedaywillcome1,

I was trying to reproduce the issue you described in both Graylog 2.1.1 and the current master, but I could not. Could you please upgrade to 2.1.1 and see if that solves the issue?

In case the issue persists after upgrading, please include your ElasticSearch version, as well as any errors that you may see in your Graylog server logs.

**Comment by onedaywillcome1** [comment]
Hi @edmundoa 

I've upgraded Graylog to 2.1.1 and Elasticsearch to 2.4.1. However, I am again getting above problem and there is no error in graylog server log.

**Comment by joschi** [comment]
@onedaywillcome1 Are you using the very URI you've mentioned above or are you using the CSV export of Graylog?

**Comment by joschi** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
