### ISSUE TITLE
Support dropping / removing of fields using extractors

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#301]
For logs that are received in native GELF format it would be beneficial to support the removal of unneeded or duplicated fields directly from within an extractor.

**Comment by sqldiablo** [comment]
+1 - The only way I can see to do this is in a pipeline currently. Even cutting the entirety of a value from a field still leaves the canned message in the field that states it has been cut in its entirety. I'd love it if you could choose whether cut removes the field or not.

**Comment by bernd** [comment]
As mentioned, this is now possible with the processing pipeline. We are most probably not going to extend the old extractors to do that.
