### ISSUE TITLE
Loading field information failed with status: cannot GET <ova install>/api/system/fields (500)

### ISSUE THREAD

**Issue by ziggyM** [Graylog2/graylog2-server#3011]
Inside my graylog console I'm trying to view received messages for an input I've set up as well as the other default inputs
_system>inputs>show received messages_

The page will try loading the messages until it returns this error:
_Loading field information failed with status: cannot GET <ova VM install>/api/system/fields (500)_

I can't find any logs, I've looked in the following location but I get 'permissions denied':
/var/log/graylog/

* Graylog Version: v2.1.1+01d50e5
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Ubuntu
* Browser version: Chrome Version 54.0.2840.71 m

**Comment by edmundoa** [comment]
Hi @ziggyM,

Would you be so kind as to repeat those steps with your browser's JavaScript console open and share with us any errors you may find there? Here there's more information about the console in [Chrome](https://developers.google.com/web/tools/chrome-devtools/console/#opening_the_console).

Thank you.

**Comment by ziggyM** [comment]
Hi edmundoa,

I've added a screen shot of all the errors as some of them change after different attempts to show the received messages. 

![chromeconsoleerrors](https://cloud.githubusercontent.com/assets/12833804/19923901/7912c03a-a0e1-11e6-8c1b-d9c6a884227e.jpg)

Thanks

**Comment by edmundoa** [comment]
By the messages in there (`[SERVICE_UNAVAILABLE/1/state not recovered / initialized]`), it looks like your ElasticSearch cluster is having problems. You should try to take a look at the ES logs for more information. If you can't access the logs, as you mentioned earlier, please try using an administrative account on the server, or contacting somebody that has that kind of access on that server and can help you to get the files.

As this is not a bug in Graylog itself, we kindly ask you to continue the discussion of this issue in our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by ziggyM** [comment]
No worries, thanks for your help, edmundoa
