### ISSUE TITLE
Support translation / dictionary lookup / rewriting in extractors

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#302]
Sometimes it is desirable to enrich certain fields by translating or changing their content - like translating a numerical status code to a corresponding string or rewriting field content.

A hash / array lookup like in LogStash's alter / mutate / translate filter would be awesome to have built-in!

**Comment by bernd** [comment]
This is the same as #644. I referenced this in #644 and am closing this one.
