### ISSUE TITLE
Make the delimiter in the key=value converter configurable 

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#304]
Key-value pairs are often also delimited by ":" or other characters ("|","/","\", etc) so the actual delimiter should be configurable ...

**Comment by bernd** [comment]
There is quie some confusion regarding the "needs-ca" label. This issue does not need a ca, it's not a pull request. The related pull requests are:

* https://github.com/Graylog2/graylog2-server/pull/313
* https://github.com/Graylog2/graylog2-web-interface/pull/381
* https://github.com/Graylog2/graylog2-web-interface/pull/769

**Comment by garybot2** [comment]
From Github via lennartkoopmann:
Thanks for the fix, @kelcecil! Do you have an addition for the web interface, too? There is no place to enter the delimiter char right now. No problem if not - I can also do it.

**Comment by hampsterx** [comment]
*bump* needed this feature today :(

**Comment by spejosh** [comment]
this would be great if in the web interface to do key: value separated by comma.

**Comment by bernd** [comment]
You can use the `key_value()` function of the processing pipeline for this. (since Graylog 2.1) It is highly configurable and should be enough to support this use case.

http://docs.graylog.org/en/2.1/pages/pipelines/functions.html#key-value
