### ISSUE TITLE
Check activity on a define time range only

### ISSUE THREAD

**Issue by sebastien67720** [Graylog2/graylog2-server#3048]
Filtering the logs between specific hours

## Context

Hello everyone,

I actually have a simple need, but it seems to be more difficult to get in place... That's why I request your help :) 

My environnement is working properly and I really like it. 
I'm sending my Windows serveur logs via NXLog (GELF Format) and my linux based OS logs via Rsylog. 

The goal is, in few words, to check if there is log-on and log-off times outside a defined timing ( for example 6h to 22h ). But i don't know how to do that... I tried to apply a filter to my search regarding to the Timestamp, but I don't understand how I get this kind of timestamp : 2016-11-02T12:27:35.553Z
 
It is automatically translated in "YMDH" by the Graylog system, but I can't apply filters on that field like this, because I don't get how it works. 
I was thinking about a syntax like that on the Graylog search query :
timestamp:2016\-11\-02T13\:51\:04.659Z TO 2016\-12\-02T13\:51\:04.659Z 

But the "TO" is not existing, and for sure I don't even know how to apply this range, and how to define it from the timestamp, because of the strange syntax of timestamp for me. 

From a GELF Windows log, i also have the "EventReceivedTime" field, more comprehensive for my human eyes :

EventReceivedTime 
2016-10-21 15:50:33

But this field it not present on my Syslog logs. That's why I wanted to work on the timestamp. 

I hope i'm clear enought for you guys,
let me know if you any idea to solve my issue.

Thank you !
Sébastien 

## Your Environment

* Graylog Version: lastest OVA available on graylog.org 
* Elasticsearch Version: ""
* MongoDB Version: ""
* Operating System: ""
* Browser version: ""

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

PS: Switch your timerange to absolute
