### ISSUE TITLE
Graylog Time on Turkey

### ISSUE THREAD

**Issue by alicengiz** [Graylog2/graylog2-server#3056]
**Key information**

- Joda-Time version
   2.9.4

**Problem description**

Turkey switched from EET/EEST (+02/+03) to permanent +03 and joda-time updated version is released about using tzdata2016i. (https://github.com/JodaOrg/joda-time/releases/download/v2.9.5/joda-time-2.9.5-dist.tar.gz)

How can I import joda-time-2.9.5.jar to graylog2 server (v2.0.3 (f07c170)) installed from rpm tarball?

I need an updated version of graylog-server-2.0.x.rpm.

**Comment by joschi** [comment]
> I need an updated version of graylog-server-2.0.x.rpm.

There will not be a patch release for Graylog 2.0.x. Please upgrade to Graylog 2.1.x (e. g. Graylog 2.1.2 which should be released in the next few days).

**Comment by joschi** [comment]
Related mailing list post: https://groups.google.com/d/msg/graylog2/IKoItKtVl-k/YoFPsoLbAgAJ
