### ISSUE TITLE
All inputs stop working at same time for few minutes and than starting again

### ISSUE THREAD

**Issue by yossiv** [Graylog2/graylog2-server#3065]
Hi Friends i have an issue that started 3 week ago,
my graylog server shows sometimes that all inputs are stopping and than after a few min they are coming back. because of that im lossing very important logs and all my graphs are based on that logs.
i have very hard server 32GB +20Core 
i couldn't find the reason for this . maybe its the logstash 
attaching my log files of the graylog and the elastic 

[Desktop.zip](https://github.com/Graylog2/graylog2-server/files/573761/Desktop.zip)

**Comment by joschi** [comment]
@yossiv There are quite a few problems in your setup.

Mainly Elasticsearch seems to be overloaded and can't keep up with the number of messages it should be indexing. You can see this by the numerous tasks piling up:
```
[2016-11-06 17:22:21,600][DEBUG][action.search            ] [graylog-tng] All shards failed for phase: [query]
RemoteTransportException[[graylog-tng][10.120.54.120:9300][indices:data/read/search[phase/query]]]; nested: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$
4@250e6a1 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@260c6b21[Running, pool size = 31, active threads = 31, queued tasks = 1000, c
ompleted tasks = 15591863]]];
```

This also leads to a lot of back pressure in Graylog, which shows in the numerous (very, very numerous) GC warnings and the long GC runs:
```
2016-10-31T00:49:13.388+08:00 WARN  [jvm] [graylog-tng8952e8fc-8312-466c-9d29-f966dd05dcac] [gc][young][121071][12329] duration [10.6s], collections [1]/[11.5s], total [10.6s]/[1h], memory [6.8gb]->[4.1gb]/[7.6gb], all_pools {[young] [2.8gb]->[57.1mb]/[3.2gb]}{[survivor] [409.5mb]->[404.7mb]/[409.5mb]}{[old] [3.5gb]->[3.6gb]/[4gb]}
```

In general, this looks like your system (at least in the current configuration) is overloaded and needs some tuning and/or more hardware resources.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
