### ISSUE TITLE
Make OptimizeIndexJob timeout configurable

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#3066]
I have slow elastic server and big indexes.
So optimization takes several hours.
This leads to errors in log:
`Unhandled error while running SystemJob <***> [org.graylog2.indexer.indices.jobs.OptimizeIndexJob]

It will be good to be able to configure OptimizeIndexJob timeout

## Your Environment
* Graylog Version: 2.1.2

**Comment by kroepke** [comment]
The default timeout is 1 hour, this should either be unlimited (or much larger than 1 hour) or configurable.
