### ISSUE TITLE
Enable gmail authentication as options    

### ISSUE THREAD

**Issue by sjkeerthi** [Graylog2/graylog2-server#3068]
Today, many companies as integrated there email to gmail so it will be great that if you could add the gmail authentication in graylog will be good under the Authentication Manager 

Under the Authentication Manager 

LDAP / Active Directory / Gmail

**Comment by jhaar** [comment]
This should probably be done via Google's native SAML and/or OPENID-Connect support - which I believe are already open issues? (eg GL2E-I-420)

That way you'd get users logging into Google, and then later on - "wave hands" - they're logged into graylog. That way MFA support is also magically added to graylog - by making some other website responsible for it :-)

**Comment by jalogisch** [comment]
closing this in favor of
https://github.com/Graylog2/graylog2-web-interface/issues/730

**Comment by jhaar** [comment]
OK - but just be aware that OPENID != SAML

In fact, we do a lot of Enterprise SSO to Cloud products and they are 100% SAML - not OPENID. Barely anyone "big" uses OPENID in this space - it's SAML or nothing

(and Google supports both)

**Comment by bernd** [comment]
@jhaar Agreed! We are tracking the SAML feature request over at https://graylog.ideas.aha.io/ideas/GL2E-I-420

**Comment by chainkite** [comment]
@jalogisch Is it feasible for us to implement an openid connect authentication plugin under the graylog 2.1 AuthenticatingRealm?

**Comment by joschi** [comment]
@chainkite Sure, that should be doable. Check out http://docs.graylog.org/en/2.2/pages/plugins.html#writing-plugins for information about writing your own plugins and take a peek at the [SSO plugin](https://github.com/Graylog2/graylog-plugin-auth-sso) for a specific example.

**Comment by chainkite** [comment]
@joschi I still have no idea how to implement the callback endpoint for the openid connect inside a plugin. Could you give me some hint?

**Comment by joschi** [comment]
@chainkite You can add arbitrary HTTP resources in plugins.

See the Anonymous Usage Statistics plugin for an example:

* https://github.com/Graylog2/graylog-plugin-anonymous-usage-statistics/blob/2.2.3/src/main/java/org/graylog/plugins/usagestatistics/UsageStatsModule.java#L58-L59
* https://github.com/Graylog2/graylog-plugin-anonymous-usage-statistics/blob/2.2.3/src/main/java/org/graylog/plugins/usagestatistics/UsageStatsResource.java

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by chainkite** [comment]
@joschi Thank you! I will try to implement it first. If still have problem, I will go to the right place for discussion. Just suppose people who open or enter this issue may also care about my question.
