### ISSUE TITLE
graylog not showing data

### ISSUE THREAD

**Issue by superwolfi** [Graylog2/graylog2-server#3069]
we have two input , one via syslog, one amqp, when i press on search, it just shows "Loading"
when i access the elastic database, i see 20K+ log messages in there 
indices looks good 20K+ and growing

elasticsearch.noarch                                                                 2.4.1-1  
mongodb-org.x86_64                                                                   3.2.10-1.el7        
Graylog v2.1.2+50e449a
Linux version 3.10.0-327.36.3.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Mon Oct 24 16:09:20 UTC 2016

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
