### ISSUE TITLE
Error - the server returned: 404 - cannot POST

### ISSUE THREAD

**Issue by mobidevadmin** [Graylog2/graylog2-server#3070]
after updating apache 2.4 with https support, we received this message on graylog web log in. The apache virtual host config file was made using this sample http://docs.graylog.org/en/2.1/pages/configuration/web_interface.html#apache-httpd-2-x

Here is an apache config
```
<VirtualHost *:80>
        ServerAdmin admin@site.org
        ServerName graylog.site.org
	RewriteEngine On
	RewriteCond %{HTTPS} off
	RewriteRule (.*) https://%{HTTP_HOST}:443%{REQUEST_URI}
        
	<Proxy *>
                Order deny,allow
                Deny from all
                allow from 192.168.0.0/24
        </Proxy>


</VirtualHost>

<VirtualHost *:443>
	ServerAdmin admin@site.org
	ServerName graylog.site.org
	ProxyRequests Off
	SSLEngine on
	SSLCertificateFile /path/to/ssl.crt
	SSLCertificateChainFile /path/to/ssl.pem
	SSLCertificateKeyFile /path/to/ssl.key

	<Proxy *>
		Order deny,allow
                Deny from all
                allow from 192.168.0.0/24
	</Proxy>

	<Location />
        RequestHeader set X-Graylog-Server-URL "https://graylog.site.org/api/"
        ProxyPass http://127.0.0.1:9000/
        ProxyPassReverse http://127.0.0.1:9000/
    	</Location>
</VirtualHost>	
```

* Graylog Version: 2.1.2-1
* Elasticsearch Version: 2.1.1
* MongoDB Version: 2.6.11
* Operating System: Ubuntu 14.04
* Browser version: Firefox 49.0.2

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
