### ISSUE TITLE
Saved searches do not load saved fields in search results (refresh required)

### ISSUE THREAD

**Issue by twgraham** [Graylog2/graylog2-server#3071]
I can't remember if it was 2.1.0 or 2.1.1 that introduced no page refreshes for search (props to the Graylog team), since then however, saved searches don't load the saved fields for that search in the search results component. I can make it work if I refresh the page after selecting the saved search.

## Possible Solution
Reload the search results component when a saved search is loaded.

## Steps to Reproduce (for bugs)
1. From (default) search page, select a saved search that has non default fields saved
2. The search results might update, but the fields do not.

## Context
In the absence of being able to define user preferred search fields (see [feature request](https://graylog.ideas.aha.io/ideas/GL2E-I-515)), we use a few saved searches to quickly select relevant search fields from a massive list. This is a cumbersome process otherwise.

## Your Environment

* Graylog Version: 2.1.1

**Comment by joschi** [comment]
@twgraham Please upgrade to Graylog 2.1.2 and check if the problem still exists there.

**Comment by twgraham** [comment]
Thanks, ill try tomorrow and let you know.

**Comment by twgraham** [comment]
@joschi upgraded to 2.1.2, same issue, selecting a saved search does not load the associated fields.

**Comment by kroepke** [comment]
Most likely the search related stores are being updated, but the fields are not properly propagated.

**Comment by bernd** [comment]
@twgraham Thank you for the report! This will be fixed in the upcoming Graylog 2.2.
