### ISSUE TITLE
systemd dependencies missing

### ISSUE THREAD

**Issue by mhutter** [Graylog2/graylog2-server#3074]
When rebooting a server, it is possible for Graylog2 to crash on boot due to MongoDB not being available yet.

_I would have sent a PR but I could not find the unit file in any of the Graylog Repos._

## Expected Behavior
Graylog starts correctly after a reboot :-)

## Current Behavior
Graylog crashes during start after a reboot

## Possible Solution
in graylog-server.service, add the following:

    [Unit]
    After=mongod.service

## Steps to Reproduce (for bugs)
1. Install graylog
2. reboot system

## Your Environment

* Graylog Version: 2.1.2-1
* Elasticsearch Version: 2.4.1
* MongoDB Version: 3.2.10
* Operating System: Ubuntu 16.04.1 LTS
* Systemd Version: 229-4ubuntu12

**Comment by joschi** [comment]
This issue was moved to Graylog2/fpm-recipes#75
