### ISSUE TITLE
Collector 'Failing' When Not

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog2-server#3083]
## Expected Behavior
When viewing collector status (nxlog based) some are showing as failing within status - "Nxlog: Failed to restart collector"

However we are receiving messages from these collectors fine.  Not sure if this is a bug or if it implies that the collectors are restarted periodically and it was unable to do so?

## Environment
* Graylog Version: Graylog 2.1.2+50e449a

Thanks

**Comment by kroepke** [comment]
Can please you provide logs from both the collector and server when this happens? Without further information there's not much we can do.

**Comment by kroepke** [comment]
@urban-moniker Any input on the above?

**Comment by urban-moniker** [comment]
Sorry - where is the best place to pull this log data from?
I cannot find the location of the collector sidecar logs on the monitored server; and because we're not sure when the collector alert is flagged on Graylog I'm not sure what to look for in the GL logs etc?

Also, just to confuse matters, we've found a collector that was reporting as OK but we noticed that we hadn't seen any new data from it in over 2 days - restarting the Sidecar service poked it back into life and it started reporting again.  This may be a good feature request - email alerts when 1) collector error reported, and 2) no new entries received for a set period.

Thanks

**Comment by mariussturm** [comment]
There is a `log_path` setting in your Sidecar configuration. It defaults to `/var/log/graylog/collector-sidecar` on Linux hosts and to `C:\Program Files\graylog\collector-sidecar` on Windows machines. There you can find the output of each activated collector. The Sidecar itself is writing to syslog.
Please also check if multiple processes of nxlog are running. If you didn't follow the installation instructions correctly it's possible that nxlog starts independently as a system service plus one process spawned by the Sidecar. That would lead to confusing status messages.

**Comment by urban-moniker** [comment]
Thanks very much.  

I have my log path entry set as "log_path: C:\Program Files\graylog\collector-sidecar" but there are no logs in there (at all).  I've tried creating a subdirectory (/logs) and pointing there but no joy.

I've def removed the natively loaded nxlog service, and confirmed that the only nxlog process running is the one loaded by Sidecar.  I'me going to remove and reinstall and correlate against collectors that appear to be working properly to see if I can see any differences (we only have ~5 for testing though).  The missing logs looks suspicious so far as that seems to imply I may have another issue anyway.

**Comment by mariussturm** [comment]
Ok,
let's move this to the mailing list then. Like you said it doesn't look like a clear bug someone can work on, so a GH issue is not the perfect medium.
