### ISSUE TITLE
Getting 404 error trying to login

### ISSUE THREAD

**Issue by tfrohling** [Graylog2/graylog2-server#3085]
Did a upgrade to Ubuntu 16.04 and now I can't login to graylog.

When I put my username and password in on the login page, I get a popup:

Error - the server returned: 404 - cannot POST http://10.9.26.146:9000/system/sessions (404)

Not sure how to proceed. 

Thanks for the assistance.

ted

* Graylog Version:  2.1.2 
* Elasticsearch Version: 2.4.1
* MongoDB Version: 2.6.20-0ubuntu1
* Operating System: Ubuntu 16.04
* Browser version: firefox 49.0.2   Chrome 54.0.2840.100 (64-bit)

**Comment by joschi** [comment]
@tfrohling It looks like the Graylog web interface is trying to connect to the wrong URI. Check your `rest_transport_uri` and `web_endpoint_uri` settings.

There's also a step-by-step guide for installing Graylog on Ubuntu 16.04 LTS: http://docs.graylog.org/en/2.1/pages/installation/os/ubuntu.html

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
