### ISSUE TITLE
Index time based rotation yields inconsistent number of indices per period

### ISSUE THREAD

**Issue by twgraham** [Graylog2/graylog2-server#3087]
Using the Index Time Rotation option set at one rotation per day, I get an inconsistent number of indices each day. i.e. Set at one index per day, I sometimes get one index, I sometimes get two, three, or four indices. Take note of my environment discussed below that might impact the index rotation thread.

![Indices Config](https://cloud.githubusercontent.com/assets/7763403/20289856/68456eac-ab30-11e6-8193-48e2c0a2ed0d.png)

![Indices Created by Rotation Config](https://cloud.githubusercontent.com/assets/7763403/20289863/770a138e-ab30-11e6-9561-225e55adf1e8.png)

## Possible Solution
Perhaps the index rotation thread is running on more than just the master of the of the Graylog cluster (so each node starts rotation)?

## Steps to Reproduce (for bugs)
1. Start a Graylog cluster with a given input (http generator for simplicity)
2. Set index rotation to 'P1D' (for 1 day rotation) 
3. Restart the cluster/add and remove nodes periodically
4. Some indices might be rotated with only a few logs in them 

## Context
A real world use case (like mine 😄 ) would be that you want to guarantee logs are at hand in Graylog for a certain amount of days/weeks/months. Therefore we should be able to create a rotation period of one index per day, and a retention size of x indices (where x is the amount of days you want to keep logs for). 

## Your Environment
I have a Graylog cluster behind a proxy and load balancer. Each instance of Graylog itself is running in a docker container. Graylog instances may be restarted at random during the day, but it should always get the same configuration (mongo, elasticsearch etc), and recover to its most recent state. 

NOTE: all nodes are set to be master, allowing Graylog to assign the first node to startup designate itself as master, and handle automatic demotion of other nodes.

Graylog is in complete control of indices management. We do not manually rotate or do any other management of indices outside of Graylog.

* Graylog Version: 2.1.2
* Elasticsearch Version: 2.2.x
* MongoDB Version: 3.2.x
* Operating System: Ubuntu 16.04 (Custom Docker Image)

**Comment by kroepke** [comment]
@twgraham The master failover does not work like that, unfortunately.
You can only run a single master and need to manually promote a graylog node to master.
What is likely happening is that you have two nodes running the rotation job.

Please configure only one node to be master and check if the behavior persist. If so, please open a new bug.

Thanks!

**Comment by twgraham** [comment]
@kroepke Thanks for the advice. Unfortunately it becomes a bit of a pain for us to manually manage the deployment of our Graylog cluster as we treat Graylog as an ephemeral app in a mesos/marathon deployment, launching our own custom Graylog docker image. Our Elasticsearch/Mongo have dedicated machines however. Considering the nature of this deployment where the cluster could be restarted at anytime, or the master might be killed and come up on a new slave, we have resorted to launching all Graylog nodes as masters - and for the most part this works fine. 

Does the Graylog team have any advice on this kind of deployment? I suppose my confusion comes from the Multi-master alert in Graylog:

> There were multiple Graylog server instances configured as master in your Graylog cluster. The cluster handles this automatically by launching new nodes as slaves if there already is a master but you should still fix this. Check the graylog.conf of every node and make sure that only one instance has is_master set to true. Close this notification if you think you resolved the problem. It will pop back up if you start a second master node again.
