### ISSUE TITLE
Run Graylog2-server and graylog2-web-interface separatly

### ISSUE THREAD

**Issue by pierrick-openIT** [Graylog2/graylog2-server#3088]
Hy guys,

is it possible to run separatly each component on two servers ? Before 2.x yes but now ? I found nothing on wiki.

Thanks for your amazing works !

**Comment by edmundoa** [comment]
Hi,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by joschi** [comment]
@pierrick-openIT What is your use case for this?

Starting with Graylog 2.0.0, the web interface is a single-page application which, once the static assets have been loaded, will run only in the user's web browser.
