### ISSUE TITLE
Export CSV doesn't work on IE\Edge

### ISSUE THREAD

**Issue by jonattta** [Graylog2/graylog2-server#3090]
## Expected Behavior
When i click on Export CSV button it should Export a csv file.

## Current Behavior
When using Microsoft IE or Edge the button does not work.

## Steps to Reproduce (for bugs)
Install Graylog v2.1.1, ensure HTTPS is enabled, try to click on button "Export CSV" using Internet Explorer or Edge.

## Context
Although it works for Chrome, for companies that enforces the use of Microsoft browsers the feature doesn't seem to work.
For instance, last time i tried using Edge, the a tag generated for Export CSV that didn't work was:

`<a tabindex="-1" role="menuitem" href="https://956fda1c-6cc4-4d24-9e12-cb07bfc28518:session@myserver.local.domain:443/api/search/universal/relative/export?query=%2A&amp;range=300&amp;fields=source%2Cmessage" data-reactid=".0.2.1.0.$/=10.0.0.1.0.2.2.0.$/=11.$export/=1$export.0">Export as CSV</a>`

## Your Environment

* Graylog Version: 2..1.1
* Elasticsearch Version: 2.2.0
* MongoDB Version: 3
* Operating System: Ubuntu 14.04 (Graylog server) /Windows 10 (client)
* Browser version: Internet Explorer 11 or Microisoft Edge

**Comment by edmundoa** [comment]
Hi @jonattta,

As you mentioned, the CSV export should work in IE 11 and Edge. Could you please share with us any errors you may find in your IE11 or MS Edge [developer tools](https://msdn.microsoft.com/en-us/library/bg182326(v=vs.85).aspx) while doing the CSV export?

**Comment by jonattta** [comment]
No errors on Developer Tools console, the button simply does nothing, completely inactive.

**Comment by jonattta** [comment]
@edmundoa additionaly, i just tried with Safari Version 10.0 (12602.1.50.0.10) on a MAC OS Sierra and the following warning message has appeared:
![screen shot 2016-11-16 at 09 41 49](https://cloud.githubusercontent.com/assets/18559625/20346219/1cd6da3e-abe2-11e6-8695-1b7110ca67f8.png)

Maybe same sort of security issue makes IE to block any action?

**Comment by eorochena** [comment]
I was able to reproduce the issue on IE 11 but the F12 developer tools are very particular this is the only error that I got

![image](https://cloud.githubusercontent.com/assets/6799455/20349922/8c4fe192-abda-11e6-985b-e588fd1cf847.png)

**Comment by jonattta** [comment]
I confirmed and even standard setup (HTTP) presents the same problem and can't export CSV

**Comment by mikkolehtisalo** [comment]
I can confirm this. 

My guess is Internet Explorer probably does not support user names and passwords in Web site addresses (HTTP or HTTPS URLs). The CSV export coaches the browser to HTTP GET something like

```
https://92dc40b0-ed65-4317-a854-43dcc01fb67d:session@server.localdomain/api/search/universal/relative/export?query=*&range=300&filter=streams:570b
```

and the request gets blocked on low level because of the included authentication information. Nothing will show up on developer console.

**Comment by bbaassssiiee** [comment]
Confirmed. Safari considers this pattern as phishing: https://string:string@hostname
You can switch that off in Safari Preferences: [ ] "Warn when visiting a fraudulent website".

This session parameter however could also be encoded in the url arguments:
https://fc14b091-1600-4c38-9c20-d894e164c145:session@logserver.localdomain/api

**Comment by edmundoa** [comment]
This is indeed a limitation in IE, as described in this Microsoft support page: https://support.microsoft.com/en-us/kb/834489
