### ISSUE TITLE
Wrong yum repo path

### ISSUE THREAD

**Issue by pastukhov** [Graylog2/graylog2-server#3092]
Looks like since 2.1.1 yum repository path is changed

It was 
```
https://packages.graylog2.org/repo/el/stable/2.1/x86_64
```
 but now looks like 
```
https://packages.graylog2.org/el/stable/2.1/x86_64
```

* Graylog Version: 2.1.1

**Comment by joschi** [comment]
@pastukhov The repository URL remained the same.

Please refer to http://docs.graylog.org/en/2.1/pages/installation/operating_system_packages.html#rpm-yum-dnf

**Comment by pastukhov** [comment]
https://packages.graylog2.org/repo/packages/graylog-2.1-repository_latest.rpm also contain wrong path
```
baseurl=https://packages.graylog2.org/repo/el/stable/2.1/$basearch/
```

**Comment by pastukhov** [comment]
Sory, my mistake!
