### ISSUE TITLE
Support Prometheus Metrics

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#3094]
This is a feature request.

It would be great if Graylog Server supports Prometheus, making easier to debug Performance Problems

Thanks!!

**Comment by joschi** [comment]
@rikatz This has been implemented in the [Graylog Metrics Reporter plugins](https://github.com/Graylog2/graylog-plugin-metrics-reporter).

**Comment by rikatz** [comment]
Oh thanks @joschi !! This is new for me!!

Great work :smile:
