### ISSUE TITLE
Create stream button doesnt appear

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#3099]
_From @pierrick-openIT on November 18, 2016 9:17_

Hy guys,

i'm on Graylog 2.1.2+50e449a and when i click on stream menu, i have nothing to create a stream.

<img width="651" alt="capture" src="https://cloud.githubusercontent.com/assets/23313214/20424854/31506e0c-ad78-11e6-9e9e-af66d770d9e2.PNG">

Regards.

_Copied from original issue: Graylog2/graylog2-stream-dashboard#15_

**Comment by joschi** [comment]
@pierrick-openIT Which web browser (exact version and operating system) are you using and are there any error or warning messages in the Web Console (Developer Console, JavaScript Console) of your web browser?

**Comment by kroepke** [comment]
@pierrick-openIT any update on the question?

**Comment by kroepke** [comment]
I'll close this due to inactivity. Please comment again, or open another issue if you have additional information.
