### ISSUE TITLE
When authenticating to graylog the first logon attempt always fails when using active directory

### ISSUE THREAD

**Issue by ryamgithub** [Graylog2/graylog2-server#3107]
## Expected Behavior
Expect it to logon the first time.

## Current Behavior
When authenticating to Graylog  using active directory authentication the first attempt always fails.

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
1. Installed using the virtual appliance.
2. configure for use with active directory using groups for admins.
3. logon using active directory
4. first attempt always fails for me, second and subsequent succeed (as long as I type the correct password)

## Your Environment

* Graylog Version: 2.1.2+50e449a
* Elasticsearch Version: what came with vm
* MongoDB Version:
* Operating System: 
* Browser version: chrome 54.0.2840.99 m

**Comment by joschi** [comment]
@ryamgithub Is there anything LDAP-related in the logs of your Graylog node?

See http://docs.graylog.org/en/2.1/pages/configuration/file_location.html#omnibus-package for the specific location of the log files.

**Comment by ryamgithub** [comment]
Not sure but I will look and let you know.
Thank you!



David Coleman
Rayonier Advanced Materials
904-357-9104 - Office

This message, together with any attachments, is intended only for the use
of the individual or entity to which it is addressed and may contain
information that is legally privileged, confidential, and exempt from
disclosure.  If you are not the intended recipient, you are hereby notified
that any dissemination, distribution, or copying of this message, or any
attachment, is strictly prohibited.  If you have received this message in
error, please notify the originator immediately by telephone or by return
E-mail and delete this message, along with any attachments, from your
computer.


1301 Riverplace Blvd
Suite 2300
Jacksonville, FL 32207



On Mon, Nov 21, 2016 at 12:17 PM, Jochen Schalanda <notifications@github.com

**Comment by Sypris** [comment]
I had this issue awhile back that turned out to be caused from the domain controller.  On login the LDAP connection would try to login from a stack of I think five dc's and most of the time it hit the one DC that was having certificate issues.  Then on second attempt it would hit one of the other dc's and work.  Maybe not your issue but sounded similar to mine.

**Comment by kroepke** [comment]
@ryamgithub Could you verify @Sypris reply, please?

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
