### ISSUE TITLE
World Map visualization does not change on new search

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#3109]
Like the quick values bug we had before, the map visualization is also not refreshing when executing a new search.

## Steps to Reproduce (for bugs)

1. Search for something
2. Open the map visualization
3. Change the search query and execute a new search
4. Notice that the map visualization still shows result of the old search

## Your Environment

* Graylog Version:  v2.1.2

**Comment by kroepke** [comment]
This issue was moved to Graylog2/graylog-plugin-map-widget#24
