### ISSUE TITLE
Stream rules not working for fields with dot in their name

### ISSUE THREAD

**Issue by libby2cm** [Graylog2/graylog2-server#3112]
Created a new stream called docker that will take all messages which have the field docker_container present. Currently using logspout with logspout-gelf module to route messages into graylog.

## Expected Behavior
Using rule of 'docker_container must be present' should cause messages with that field in it to route into stream.

## Current Behavior
Messages are not routed into stream... even though using a sample message passes rule validation for the stream.  As a test, if I set it to 'invert', all messages for everything then come into stream.

## Possible Solution
Only thing I can surmise is that maybe stream rules don't like having underscores in field names.

## Steps to Reproduce (for bugs)
1. Create a stream
2. set a stream rule for a contains rule of field presence with presumably an underscore in name.

## Context
Can route required messages into stream...

## Your Environment

* Graylog Version: 2.1.2
* Elasticsearch Version:  2.4.2
* MongoDB Version:  2.6.11
* Operating System:  oel6
* Browser version:  ie11, chrome55

**Comment by edmundoa** [comment]
Hi,

Would you be so kind as to share some raw messages not going into the stream? It would also be really helpful if you could explain a bit more on how you are sending messages to Graylog, and where the `docker_container` field is being set.

Thank you.

**Comment by kroepke** [comment]
@libby2cm Any update?

**Comment by rgroothedde** [comment]
I have the same problem, it seems to be a problem with the underscore in field names.

**Comment by rgroothedde** [comment]
@kroepke Are you using logspout-gelf ? Actually the fieldname send to graylog is: "docker.container" but this is converted by graylog to "docker_container". 
I think this problem is related to #2939 .

**Comment by kroepke** [comment]
I'm not using anything, I tried to reproduce the bug.
But yes, graylog converts the `.` to `_` very late, right before writing it to elasticsearch.

So if logspout-gelf is sending `docker.container` the stream rule needs to use that field name as well.
However stream alerts need to use `docker_container`, because those operate on saved data.

Unfortunately there's not much we can do, because elasticsearch used to accept `.` in field names, GELF allows it, but elastic changed it at some point (and I think has changed it back somehow).

**Comment by rgroothedde** [comment]
@kroepke Sorry, mistake, I wanted to address @libby2cm . 
But thank you for your explanation.

**Comment by kroepke** [comment]
IOW the only change we can make is backwards incompatible and would most likely break many clients, as the `.` is a common character to separate words visually.
It's just messy right now.

**Comment by libby2cm** [comment]
@kroepke @edmundoa 

Sorry for delayed reply, been crazy at work.  Yes, I am using logspout in this particular case.  However, based on what you said, I changed my stream rule from 'docker_container' to 'docker.container' and the rule works now.  Just odd how the messages are being processed in that I have to use the underscore when doing a regular search, but need to use a '.' for the stream rules.  Since '.''s can't be written in fields to ES anymore, I guess stream rules and the index used for regular searches are processed at a different stage in the pipeline.  

Not a huge deal now that I see what's going on and I got it working, i'll just make a mental note to keep this in mind.

**Comment by joschi** [comment]
@libby2cm FWIW, Elastic reverted the behavior in Elasticsearch 2.4.0, so that dots in field names are allowed again.

We chose to keep the restriction though, in order to stay compatible with Elasticsearch 2.3.x.

This will change again with Graylog 3.0.0 (no scheduled release date yet).

**Comment by mahnunchik** [comment]
Any news?
