### ISSUE TITLE
Inability to install as a single readily available image to the OpenShift

### ISSUE THREAD

**Issue by Avtonom** [Graylog2/graylog2-server#3119]
OpenShift installation offers of ready solutions, one button, used with the docker https://www.openshift.com/features/technologies.html#quickstarts

Establishing documentation ( http://docs.graylog.org/en/latest/pages/installation/docker.html ) of individual images I get an error:
`/docker-entrypoint.sh: line 34: exec: graylog: not found`

I raised the debate in these communities:
- https://groups.google.com/forum/#!topic/openshift/bjp3BpUVGB8
- https://groups.google.com/forum/#!topic/graylog2/ffKvQQDvpc4

It seems to me that the install log as a template would be a good idea.

**Comment by jalogisch** [comment]
We will accept a PR to the Documentation about this topic. https://github.com/Graylog2/documentation/pulls

The Core Team does not have enough OpenShift experience so this can not be provided and needs to be done by the community.
