### ISSUE TITLE
Graylog HTTPS TLS but not on port 443 doesn't seem to work using the graylog-ctl command using 2.1.2 because of a bad nginx config

### ISSUE THREAD

**Issue by PaulDMendoza** [Graylog2/graylog2-server#3125]
I downloaded the Graylog 2.1.2 OVA file. I went through the setup process. My goal was to get Graylog running with a TLS certificate but on a different port than 443. No matter what I do I can't seem to get the graylog-ctl command to correctly configure. Totally not what I expected and I really had to dig through the graylog.conf and nginx.conf files to figure out what was going on. 

## Expected Behavior
I should be able to execute the following commands and everything should bind up correctly according to the documentation.

     sudo graylog-ctl set-external-ip https://mysite.com:9090/
     sudo graylog-ctl set-listen-address --service web --address http://0.0.0.0:9000
     sudo graylog-ctl set-listen-address --service rest --address http://0.0.0.0:9000

http://docs.graylog.org/en/2.1/pages/configuration/graylog_ctl.html

## Current Behavior
The ports and routes get configured wrong and the documentation doesn't match what I'd expect it to do. I'll explain below.

## Possible Solution
The proper commands seem to be

     sudo graylog-ctl set-external-ip https://mysite.com:9090/
     sudo graylog-ctl set-listen-address --service rest --address http://0.0.0.0:9000/api/
     sudo graylog-ctl set-listen-address --service web --address http://0.0.0.0:9000/
     sudo graylog-ctl reconfigure

Notice I added "/api" to one of the lines which wasn't in the documentation and needs to be. 

Then I had to open the nginx file and go to the server section and change the listen port to 9090. I also had to change the "proxy_set_header X-Graylog-Server-URL" line to have "/api/" at the end of it otherwise the web interface doesn't allow me to login. 

## Context
Made is very difficult to get Graylog running and now I can't use graylog-ctl reconfigure without nginx getting all messed up. 

## Your Environment
The OVA file I downloaded off your site. Running in VMWare. I can't run on port 80 or 443. 

* Graylog Version: 2.1.2
* Elasticsearch Version: whatever came with the 2.1.2 OVA
* MongoDB Version: whatever came with the 2.1.2 OVA
* Operating System: whatever came with the 2.1.2 OVA
* Browser version: whatever came with the 2.1.2 OVA

**Comment by mariussturm** [comment]
Port 443 for TLS and port 80 for HTTP is hard wired for the OVA installations https://github.com/Graylog2/omnibus-graylog2/blob/2.1/files/graylog-cookbooks/graylog/templates/default/nginx.conf.erb#L45
Changing it is a rare use case and therefore not supported by the graylog-ctl command. If there is no other way in your environment to changing the default ports please consider a semi-automated installation with our Puppet of Chef recipes. There you can customize all settings.
