### ISSUE TITLE
Hibernate Validator does not work with non-bean accessors (auto-value classes)

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#3127]
Many (all?) of our auto value classes don't use JavaBean conventions for their methods, which breaks Hibernate Validator.

As a result `@Valid` annotations in REST resources don't actually validate any of the properties of those classes, which potentially leads us to accept invalid data.

There are three possible workarounds:
1. Migrate all auto values to using JavaBean style methods
2. Write custom validator classes for each auto value.
3. Write a auto-value extension that generates proper bean-style accessors.

The third option seems the most viable for us right now and has already been prototyped.

**Comment by joschi** [comment]
Related issue in the [Immutables](https://immutables.github.io/) project with similar approaches: https://github.com/immutables/immutables/issues/26

**Comment by bernd** [comment]
This is the prototype I built: https://github.com/bernd/java-tests/blob/master/autovalueextensions/src/main/java/com/github/bernd/javatests/autovalueextensions/WithBeanGetterExtension.java
