### ISSUE TITLE
Extend index ranges to include stream ids

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#3128]
When we added index sets as write target abstraction the problem arose that changing the index set of a stream causes searches to no longer find messages in previously assigned index sets.

This is because the engine filters indices to search in by the currently configured index set per stream, and does not take its history into account.
Rather than storing the entire history and using that to reconstruct the mappings over time, we will extend the index ranges to contain a set of stream ids their index contains data for.
This has several advantages:

* The existing lookup mechanics work without change.
* Restored archives (which live in index sets) can contain multiple streams, but don't necessarily contain all of them.
* When recalculating index sets we can lazily add the stream ids, because we already have to execute expensive min/max timestamp aggregations and can afford the histogram on `stream_ids`.
* The default stream also needs this handling, because otherwise it suffers from the same problem that data before the introduction of the default stream would not be found by its stream search.

The tasks therefore:
 - [x] Extend `IndexRange` to contain a set of streams (which may be missing or empty)
 - [x] Adapt `IndexHelper#determineAffectedIndicesWithRanges` to make use of the set of stream ids during lookup
 - [x] Add migration of the default stream to update index ranges
 - [x] Modify index range recalculation to set stream ids contained in the index.

**Comment by bernd** [comment]
This is done.
