### ISSUE TITLE
UTF-16 encoded text files ingested via NXLog is not parsable or searchable

### ISSUE THREAD

**Issue by drewmmiranda** [Graylog2/graylog2-server#3130]
Having NXLog ingest and character convert a text tile with UTF-16 encoding (specifically tested 'UTF-16 LE with BOM') stores text in a way that it doesn't seem possible to write parsing rules or searching against the text.

Text DOES display as expected when viewing messages from that source server, however, when viewing message terms, it shows each character separated by a space (instead of whole words).

When viewing same message via RestAPI, it displays like this
full_message": "2\u00000\u00001\u00006\u0000-\u00001\u00001\u0000-\u00002\u00008\u0000 \u00001\u00000\u0000:\u00001\u00006\u0000:[....]"

Example NXLOG config. I verified this does adequately convert the character encoding into readable text by outputting to a text file.

```
<Extension charconv>
    Module xm_charconv
    AutodetectCharsets utf-8, euc-jp, utf-16, utf-32, iso8859-2
</Extension>
<Input inCtxPvsConsole>
    Module  im_file
    File    "C:\\programdata\\Citrix\\Provisioning Services\\Log\\Console.log"
    #SavePos FALSE
    #ReadFromLast FALSE
    Exec    $FileName = file_name();
    Exec    $SourceName = 'PVSLogs';
    Exec    $full_message = convert($raw_event,"UTF-16LE","iso8859-2");
</Input>
```

## Expected Behavior

Text is stored in a way that pipelines rules and searches can interact with the text.

## Current Behavior

Pipeline rules fail to match and searches for text contained in fields do not return matches.

## Possible Solution
Allow converting character encoding when storing messages OR to allow a pipeline function to convert it

## Steps to Reproduce (for bugs)

1. Configure NXLog to ingest a 'UTF-16 LE with BOM' encoded text file
2. Review graylog to verify it has ingested log lines
3. View show message terms on "full_message" field

## Context

Attempting to process and parse a text log with a somewhat non standard character encoding

## Your Environment

* Graylog Version: 2.1.1
* Elasticsearch Version: 2.3.3
* MongoDB Version: 2.6.11
* Operating System: CentOS 7
* Browser version: Chrome 54

**Comment by drewmmiranda** [comment]
Example log file here:
https://www.dropbox.com/s/69j37v721p8qala/Console%20-%20Copy.log?dl=0

**Comment by kroepke** [comment]
@drewmmiranda If you are sending GELF the message must be in UTF-8. UTF-16 will not work as you've discovered.
Can you force NXLog to change the encoding?

**Comment by mikkolehtisalo** [comment]
According to the documentation this should convert one field correctly:

`Exec    $full_message = convert($raw_event,"UTF-16LE","UTF-8");`

There is automatic conversion for all fields, but people say it works unreliably:

```
AutodetectCharsets utf-8, euc-jp, utf-16, utf-16le, utf-32, iso8859-2
....
Exec    convert_fields("AUTO", "utf-8");

```

**Comment by drewmmiranda** [comment]
Sorry for the late reply on this!

Doing the following appears to resolve this issue

```
Exec    $raw_event = convert($raw_event,"UTF-16LE","utf-8");
```

Where previously I was doing convert on $full_message instead of raw_event. I now get proper message terms and proper text in the message field.

```
"full_message": "2016-12-29 13:54:48,152 [ADStartupThread] WARN  ADSupport.PublicFunctions - Could not find domain {{redacted}}, Exception = System.Runtime.InteropServices.COMException (0x8007203A): The server is not operational.",
```
