### ISSUE TITLE
CSV Convertor not working properly

### ISSUE THREAD

**Issue by vivred** [Graylog2/graylog2-server#3131]
Hi,

I am reading raw message from kafka with message as '2016-11-24 15:10:59.529' 8 'PUSH_VODAF1_MSG' 'PUSH_VODAF1_MSG [ esmeid and sessions unbind/stopped ]'

i  applied copy extractor on this message with csv convertor, however graylog is failing to create those csv columns.

csv seperator/delim = SYN ("\u0016")
csv quote char = '
csv escape char = \

when the csv separator is "," ,graylog is properly parsing, but it fails whenever we use SYN as a seperator.

ny help would be welcome.

* Graylog Version:2
* Elasticsearch Version:2.4

**Comment by kroepke** [comment]
@vivred Could you supply a concrete message where this fails? It's difficult to debug if we have no actual data.
It would also help to see a screenshot of your extractor/converter config, please?

**Comment by vivred** [comment]
@kroepke 

the issue is resolved. our message has SYN special character as csv seperator. so in the csv convertor fields box we have to seperate field names also with SYN instead of comma(,).

here is code that does it. Instead of using the same csv parser, we should seperate fieldname using comma(,)

https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/inputs/converters/CsvConverter.java#L56

**Comment by joschi** [comment]
@vivred Thanks for the update! I'm closing this issue now.
