### ISSUE TITLE
Unable to find new graylog logo in resolution appropriate for printed matter

### ISSUE THREAD

**Issue by SkyToGround** [Graylog2/graylog2-server#3135]
Posted here seeing as the following is a direct quote from [graylog.org](https://www.graylog.org/community-support): "Do not hesitate to open issues – we’ll just close them if there is nothing to do."

Other than that, I think the title says it all.

**Comment by kroepke** [comment]
I'll reach out to someone either upload some files or get them to you via email.
Could you describe what purpose you would use them for and what format you require?

Thanks!

**Comment by SkyToGround** [comment]
I have now received a version of the logo with a higher resolution. The purpose is for use in presentation material advocating the use of Graylog in our organisation.
