### ISSUE TITLE
Dashboard graphes have invalid timerange

### ISSUE THREAD

**Issue by Xat59** [Graylog2/graylog2-server#3136]
Hi guys,

I'm trying to build a dashboard from an absolute timerange search.
When importing the graph in the dashboard it modifies the timerange I set first when querying.

## Expected Behavior
I want imported graphes in dashboard have the good absolute timerange configured before clicking on 'Add to dashboard'

## Current Behavior
The graph in the dashboard section does not respect the timerange I set before clicking 'Add to dashboard' button.

## Possible Solution
I have no idea how to fix that, I did not find one.

## Steps to Reproduce (for bugs)
- step 1 : I select an input and set a timerange between 2016-11-30 00:50:00 AND 2016-11-30 01:10:00
- step 2 : I select field I want , then 'generate chart'. The chart is built
- step 3 : I click on "Add to dashboard"
- step 4 : I'm going to the dashboard, then I can see my new graph
- step 5 : I click on 'show widget configuration'
- step 6 : 'Timerange' value is different that the one specified at step 1

## Context
I just want to create a dashboard with graphes imported from an input with configured timerange.

## Your Environment
* Graylog Version: graylog-2.0.3
* Elasticsearch Version: elasticsearch-2.3.5
* MongoDB Version: mongodb-org-server-3.0.2
* Operating System: CentOS Linux release 7.1.1503 (Core)  
* Browser version: Version 54.0.2840.71 (64-bit)

Thank a lot.

**Comment by edmundoa** [comment]
Hi @Xat59,

Could you please upgrade to the latest Graylog version (2.1.2) and see if that helps with the issue you are experiencing?

Thank you

**Comment by jalogisch** [comment]
Hej @Xat59 

did you have any  input on this topic? If not we will close this in 7 days.

**Comment by Xat59** [comment]
Hi guys,

I cannot reproduce this bug on 2.1.2 .

Thank a lot .
Regards.
