### ISSUE TITLE
Graylog server disk space filling up. Please let us know what to delete 

### ISSUE THREAD

**Issue by skuppam** [Graylog2/graylog2-server#3141]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by skuppam** [comment]
Below is my directory structure 
root@ip-172-31-9-64:/var/lib/docker# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            2.0G   12K  2.0G   1% /dev
tmpfs           396M  468K  395M   1% /run
/dev/xvda1       40G   29G  9.3G  76% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            2.0G  468K  2.0G   1% /run/shm
none            100M     0  100M   0% /run/user
none             40G   29G  9.3G  76% /var/lib/docker/aufs/mnt/22ca2140434e38e35dbeb906ba3b96cb42a87c6ebeac821fbde52809d3c8392d
shm              64M     0   64M   0% /var/lib/docker/containers/ed220a8e91768c16314fae01bc3e4741241d95b10e01db24852365b079188d12/shm
none             40G   29G  9.3G  76% /var/lib/docker/aufs/mnt/8532e18a93595f7b1b338213e9c164fd5946cc226c88571c18b3079aa4ee2a3d
shm              64M     0   64M   0% /var/lib/docker/containers/5735ec491e60f26a24b4287c9a08982ea3f4c825f9500913313d06974d34456e/shm
none             40G   29G  9.3G  76% /var/lib/docker/aufs/mnt/a00dc2dfb9d23c06a4feefa3052d0cbe92404797ca51d44fe952228405bff358
shm              64M     0   64M   0% /var/lib/docker/containers/e4331d142f52116c24abf54dc7f6c74b526684a150042c0a9b7d32615b44cb37/shm
  and I see disk space as below
root@ip-172-31-9-64:/var/lib/docker/volumes# du -sk * | sort -n
8       750a77537593be4fb6b823913da12b11c96c5df534fea40a798fd7d25c6b2759
8       a7856c644f0a190731c44035f18dcb66f01cd989495976234a6f18ee552d2101
8       b3d48af3b1e59f5e6838beeebf135a5c7c60acd76fe4aa61d3484aa40e2c176c
44      metadata.db
64      3dc41134133b0742137f5a55feb5c25ba4ddacb3e5dd4d73a1b0fde6f3ee9153
68      44768ccb6e48fc4220bad7729645c508b8d2147483633933f43a41661fd1f939
68      56120b11d82a6d6a19cf132f07298067839ff0b7da37ed3669859dd00b105d25
68      6554609a85cbfc6641b33786200f6904423a6a17c1ed81243f7d722eb0245303
68      d2eb0df45f853b647c1cfa9e0194b4691fb0515cd1a1675454dc302b11d2431f
68      e0062ce95ed6c21258274a02fcf4df47ea15c638b816f62edf50d0cf0df00e0d
68      ef2bf73c1cd30652237a72d99762db2cd86dc15f8d51a96752578aa6c0afe213
80      5854be7cba54686bc807bc7c6f1152763fdb5f54c4a73b04ea069afce052b208
80      6bdc276fef54e143afdaa34276fdae468cc027f9f774ee7a49a1754e899d575d
80      be16d49f29a14f1ceb3de860607bba4c6f8d0f08c021e529a3f1949ffb1e7438
80      c73a423e0082d77501882f9dfad0781b1fdbd6da9510372a8080b0adf0210035
80      f6b3b79f170ac2245c407387263c542401974fbf5dce3b02630bd78161a0951c
80      f6e630564f5bfd1da4e98af3e6aef07dad721fa506ba2d782f25288fc55d9654
5244    959fe08f81a29406ca1d2bb05c45d678b6a880a6d6e8b738d9ea53691670e25d
7096    cb79d2b50875fe7b41f6887d83a7686a37e10369c541105eb1633b75c686216d
131116  0f15d93821e3ab06c8c46280a9f7aa578ccd8aed08cf6d679e2785bb54b8b643
309884  86f1c3672ca8bc69e3aa0f443e02577d8bff50ce19e9ed61254054b5e2ef1070
360040  d6b47e2bc8136f33898a75117f7b0165cb49fc015c7e493fd0a1618ae0de1b37
568840  50a78d9aa2adb124a41436a37ae9ee4813ccca7a348e7203a214a4accbcb6507
1255524 21ba636a31fd8808b7c30b094cdede5172085eed29857738aea1675a9de0be6a
1639508 4165ba15d313d152d4ce6a921f62f3697c3eea7569e6133f2a58cb3f40433d18
14454996        7522811ceeb138299bf04b6d9cfb3d53a16e9efdebe77c6624141dcbea7f8310

But even if I delete anything from above volumes I see no difference in disk space

**Comment by skuppam** [comment]
![capture](https://cloud.githubusercontent.com/assets/23110683/20766288/abcd42a6-b6ea-11e6-9e67-2bbfc0ac6303.JPG)

Please see above image for disk space

**Comment by mariussturm** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
