### ISSUE TITLE
Bind mongodb to localhost/127.0.0.1

### ISSUE THREAD

**Issue by thomasegis** [Graylog2/graylog2-server#3158]
Hi,

While securing a Graylog appliance appliance (OVA 2.1.2-1), I noticed that the mongodb server is listening on every network interfaces even though I issued `sudo graylog-ctl local-connect`

## Expected Behavior
Issuing the config command `sudo graylog-ctl local-connect` should setup the system to only use localhost/127.0.0.1 for all backend services (graylog web, elasticsearch, mongodb).
The only services that are binded to public interfaces are : graylog inputs and nginx.

## Current Behavior
After the `sudo graylog-ctl local-connect`, all backend services are binded to localhost but the mongodb server.
```
ubuntu@graylog:/opt/graylog$ sudo netstat --listening -p
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 *:27017                 *:*                     LISTEN      18145/mongod
tcp        0      0 *:37867                 *:*                     LISTEN      18102/java
tcp        0      0 localhost:2380          *:*                     LISTEN      18130/etcd
```
## Possible Solution
To fix the issue I created a config file for the mongodb server as `/opt/graylog/conf/mongodb.conf`. The file contains : 
`bind_ip = 127.0.0.1`

Then, I modified the `/opt/graylog/sv/mongodb/run` to add `-f /opt/graylog/conf/mongodb.conf`. It looks like this now : 
```
#!/bin/sh
exec 2>&1

export LC_ALL=C
umask 077
exec chpst -P -U graylog -u graylog /opt/graylog/mongodb/bin/mongod --dbpath /var/opt/graylog/data/mongodb --smallfiles  -f /opt/graylog/conf/mongodb.conf
```

Restart Graylog server and now, the mongodb server is binded to localhost.
```
ubuntu@graylog:/opt/graylog/sv# sudo netstat --listening -p
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 localhost:27017         *:*                     LISTEN      18655/mongod
tcp        0      0 localhost:2380          *:*                     LISTEN      18614/etcd

```
However, when a `sudo graylog-ctl reconfigure` command is issued, it resets `/opt/graylog/sv/mongodb/run` to its original content. The patch has to be re-applied :(

## Steps to Reproduce (for bugs)

1. install Graylog OVA from https://packages.graylog2.org/releases/graylog-omnibus/ova/graylog-2.1.2-1.ova
2. setup graylog to use local connections with `sudo graylog-ctl local-connect`
3. check that mongod listens on ervery interface with `sudo netstat --listening -p`
4.

## Context

I was trying to secure a single node Graylog installation.

## Your Environment

* Graylog Version: 2.1.2-1 (from OVA)
* Elasticsearch Version: version packaged with Graylog 2.1.2-1 OVA
* MongoDB Version: version packaged with Graylog 2.1.2-1 OVA
* Operating System: Ubuntu packaged with Graylog 2.1.2-1 OVA
* Browser version: NA

**Comment by mariussturm** [comment]
The appliance is made for easily testing out different Grayog setup modes, including multi server setups. The drawback of this is that some services need to be more open than usual. As we point out in the documentation, the user need to understand that and should isolate the appliance in a secured network segment. Firewalls or Iptable rules should be used to secure access to MongoDB, Elasticsearch, Graylog API and etcd. If this is not possible in your environment please consider a manual installation or a Chef/Puppet backed one.

**Comment by mariussturm** [comment]
@thomasegis mongodb will we included in  the local-connect command on the next release: https://github.com/Graylog2/omnibus-graylog2/commit/5227076051227c750e9cf970c23d4e44abdc0a93
