### ISSUE TITLE
Unable to load default stream

### ISSUE THREAD

**Issue by fuegowolf** [Graylog2/graylog2-server#3159]
Hi ! With the latest release (2.2.0-beta.1-1), Graylog is unable to load the default stream, and because of it no processing is done :

`WARN : org.graylog2.bindings.providers.DefaultStreamProvider - Unable to load default stream, tried 11 times, retrying every 500ms. Processing is blocked until this succeeds.`

I've the seen the very new pull request #3152 but i'm not sure it will fix it, so I prefere to tell you.

## Expected Behavior
The default stream needs to be loaded.

## Current Behavior
The default stream is not loaded.

## Possible Solution
I've seen in the DefaultStream class that maybe the DEFAULT_STREAM_ID is wrong, but I'm more confident with the pull request #3152.

## Steps to Reproduce (for bugs)
1. Initiate a clear new Graylog/ES/Mongo stack
2. Import the content pack of nginx
3. Watch logs

## Your Environment

* Graylog Version: 2.2.0-beta.1-1
* Elasticsearch Version: 2
* MongoDB Version: 3
* Operating System: Ubuntu with Docker

**Comment by kroepke** [comment]
Beta.1 is broken which is the reason it wasn't announced.
Among the problems is what you describe. The next beta will contain the fix.

Thanks for your report!
