### ISSUE TITLE
api/cluster/metrics/multiple Returns Inconsistent Results Nodes

### ISSUE THREAD

**Issue by homelinen** [Graylog2/graylog2-server#3161]
## Expected Behavior
On successive requests to `api/cluster/metrics/multiple` the same log totals should be returned for each node.

## Current Behavior
For the `/system/logging` page the log counts for each node seemingly randomly move between all three nodes.

These two screenshots were taken 5 seconds apart and show the value  `26910` move between different nodes, when I suspect this log count is actually on our master:

![screen shot 2016-12-07 at 11 40 33](https://cloud.githubusercontent.com/assets/1014398/20969355/892bfefe-bc80-11e6-9ac9-67ae9b27fb4d.png)

![screen shot 2016-12-07 at 11 40 38](https://cloud.githubusercontent.com/assets/1014398/20969360/8d241622-bc80-11e6-82fc-94f92bba2f5b.png)

HAR Analysis of two `api/cluster/metrics/multiple` POSTs one after the other: https://gist.github.com/homelinen/a8d86923ab037545796df262f33bafcb

Both requests appear to have been from the same Graylog Node but the text contents have different totals for each of the nodes returned.

Specifically from the HAR text contents:

Request 1:
```json
 "5701cfcd-ee82-4f8d-99aa-a6a3b15d7961": {
"total": 3,
"metrics": [
{
"full_name": "org.apache.logging.log4j.core.Appender.all",
"metric": {
"rate": {
"total": 131,
"mean": 0.0007427113726484079,
"five_minute": 9.182450220670794e-7,
"fifteen_minute": 0.000127888274501059,
"one_minute": 2.4992232062755564e-20
},
"rate_unit": "events/second"
},
"name": "all",
"type": "meter"
},
...
```

Request 2:
```json
"5701cfcd-ee82-4f8d-99aa-a6a3b15d7961": {
"total": 3,
"metrics": [
{
"full_name": "org.apache.logging.log4j.core.Appender.all",
"metric": {
"rate": {
"total": 26910,
"mean": 0.15256556809271413,
"five_minute": 0.019955455179798368,
"fifteen_minute": 0.018338136946384587,
"one_minute": 0.028135325328683354
},
"rate_unit": "events/second"
},
"name": "all",
"type": "meter"
},
...
```

## Possible Solution
To me it seems like there is an inconsistency in the mappings of the node IDs and the values for their statistics.

Or perhaps there is a misunderstanding on my part how this should work.

## Steps to Reproduce (for bugs)

1. With more than one graylog cluster behind a load balancer
2. Visit `/system/logging`
3. Observe changes in the log levels

This has not been replicated in a smaller setup but the issue is consistent across our three Graylog clusters.

## Context

This issue means it is hard to diagnose which nodes are doing what. The same behaviour appears to exist on the /system/nodes page but is harder to illustrate than the logging page. This makes it difficult to immediately identify which nodes might have a large journal backlog as we only know _one_ might.

## Your Environment
* Graylog Version: 2.1.2
* Elasticsearch Version: 2.4.1
* MongoDB Version: 2.4.9
* Operating System: Ubuntu 14.04 (Trusty)
* Browser version: Firefox 50.0.2 (MasOS) 

Our cluster is setup with 3 Graylog Nodes behind an AWS ALB (With Stickiness disabled)

Graylog is served behind Nginx, and the API is served from /api/ rather than a separate port:

Nginx config:

```
# MANAGED BY PUPPET
server {
  listen 0.0.0.0:80;
  server_name           graylog-production.east.fdbox.net;
  if ($http_x_forwarded_proto = "http") {
      return 301 https://$server_name$request_uri;
  }

  index  index.html index.htm index.php;

  access_log            /var/log/nginx/graylog.access.log combined;
  error_log             /var/log/nginx/graylog.error.log;

  location / {

    proxy_pass            http://127.0.0.1:9000/;
    proxy_read_timeout    90;
    proxy_connect_timeout 90;
    proxy_redirect        off;
    proxy_set_header      Host $http_host;
    proxy_set_header      X-Forwarded-Host $host;
    proxy_set_header      X-Forwarded-Server $host;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header      X-Graylog-Server-URL https://graylog-production.east.fdbox.net/api/;
  }

  location /api/ {

    proxy_pass            http://127.0.0.1:12900/;
    proxy_read_timeout    90;
    proxy_connect_timeout 90;
    proxy_redirect        off;
    proxy_set_header      Host $http_host;
    proxy_set_header      X-Forwarded-Host $host;
    proxy_set_header      X-Forwarded-Server $host;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
```

**Comment by jalogisch** [comment]
my configuration looks nearly the same:

```nginx
upstream graylog_web_interface {
         server 192.168.0.26:9000;
         server 192.168.0.27:9000;
         server 192.168.0.28:9000;
}
server
{
    listen      443 ssl http2;
    server_name graylog.lab.lan;

    ... SSL Settings ...

    location /
    {
        proxy_set_header    Host $http_host;
        proxy_set_header    X-Forwarded-Host $host;
        proxy_set_header    X-Forwarded-Server $host;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Graylog-Server-URL https://graylog.lab.lan/api;
        proxy_pass          http://graylog_web_interface;
    }
}
```

But for Graylog I'm using [single port](http://docs.graylog.org/en/2.1/pages/configuration/web_interface.html#single-or-separate-listeners-for-web-interface-and-rest-api) configuration and I can't reproduce the error. From what you are describing I would say that your Graylog Nodes can't communicate to each API. So this looks more like a configuration issue to me.

Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by jmcewan127** [comment]
I am seeing the exact same issue on Graylog 2.2.3, exactly as description as above, except I am using a single port configuration as described by @jalogisch. This looks like a bug, and not a configuration issue, unless a configuration issue resolution was found.  @homelinen

**Comment by jekelundh** [comment]
Can confirm the problem still exists in graylog-server-2.4.0-5.beta.3.noarch.
Two node cluster behind load balancer. All metrics are "0" when connected to masternode but visible on slave node.

**Comment by joschi** [comment]
@jekelundh Please post your complete Graylog configuration, the configuration of your load balancer, and some details about your network setup.

**Comment by jekelundh** [comment]
@joschi When I doublecheck the issue description I realize  this might  not be the correct issue for my problem. The metrics I miss are the ones from the extractors. However, the graylog-server-2.4.0-5.beta.3.noarch nodes are behind an F5 load balancer. The clients connects to a VIP that is made up of a round robin sticky pool with two GL servers in another subnet. The F5 is routing back the traffic to the client subnets. Two ES and MongoDB are clustered and there is also a third dataless node used for quorum.
