### ISSUE TITLE
Global (Dashboard-wide) Time frame selector

### ISSUE THREAD

**Issue by P1eX** [Graylog2/graylog2-server#3165]
In order to analyze different timeframes it would be very helpful to select the timeframe not only for one single widget but for the whole dashboard and consequently all active widgets within this dashboard.

Therefore, all widgets should reference to a 'time frame selector' located in the dashboard view. 
In case I want to analyze one single widget with 'replay search', I still want to be able to change the timeframe for that specific query.

Thanks in advance

**Comment by edmundoa** [comment]
Hi,

I'm closing this issue, as it is duplicating #1630. Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
