### ISSUE TITLE
High message rate 'kills' Graylog

### ISSUE THREAD

**Issue by harrywer** [Graylog2/graylog2-server#3168]
When processing a large amount of IIS log traffic the 'processbuffer' fills up and when the buffer is full Graylog grinds to a 'halt'.

## Expected Behavior
With the right settings Graylog should be able to handle a large amount of message traffic.

## Current Behavior
When processing a large amount of IIS log traffic the 'processbuffer' fills up and when the buffer is full Graylog grinds to a 'halt'. The IIS traffic volume is 35,000 per 5 mins at an average message size of 500 bytes.

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
1. Configure collector-sidecar to send IIS log traffic into Graylog
2.
3.
4.

## Context
Cannot deploy Graylog completely into production.
 
## Your Environment
I have 2 x graylog servers, 2 x elastic search servers writing to NFS connected storage using a PureStorage flash array. 

* Graylog Version: 2.1.1
* Elasticsearch Version: as per OVA
* MongoDB Version: as per OVA
* Operating System: as per OVA
* Browser version: Chrome, IE and Firefox

**Comment by harrywer** [comment]
In the file /var/graylog/config/graylog.conf I have changed the 'processbuffer_processors' to 32, the 'outputbuffer_processors' to 8 and the 'inputbuffer_processors' to 4. It was the processbuffer that appeared to be under stress. I will monitor this for a while and report back with the results.

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
