### ISSUE TITLE
pipeline processor not processing messages properly

### ISSUE THREAD

**Issue by vivred** [Graylog2/graylog2-server#3170]
when i use this rule
its properly setting the statediff field to $message.state (example state = 3032) state is an integer.

rule "testing state"
when
    ($message.source == "ngmp_esme_logs")
then
    let x = $message.state;
    set_field("statediff",x);
    route_to_stream("ngmp state difference");
end

but when i use this rule pipeline is not setting the statediff field (actaully not processing the message itself)

rule "testing state"
when
    ($message.source == "ngmp_esme_logs") && ($message.state == 3032)
then
    let x = $message.state;
    set_field("statediff",x);
    route_to_stream("ngmp state difference");
end

## Expected Behavior

when $message.state == 3032  it should process the message

## Your Environment

* Graylog Version: 2.1.1
* Elasticsearch Version: 2.4

**Comment by joschi** [comment]
@vivred You have to use the [`to_long()`](http://docs.graylog.org/en/2.1/pages/pipelines/functions.html#to-long) function to ensure that `$message.state` is a numeric value.

```
rule "testing state"
when
  ($message.source == "ngmp_esme_logs") && (to_long($message.state) == 3032)
then
  // ...
end
```

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog) if you want to discuss this further.

Thank you!

**Comment by joschi** [comment]
For reference: https://groups.google.com/forum/#!topic/graylog2/0qTD7ZXbckA
