### ISSUE TITLE
XSS Vulnerability at Internal Server Error page

### ISSUE THREAD

**Issue by jeremyyap** [Graylog2/graylog2-server#3171]
## Expected Behavior

Cross-site scripting attack should not be possible

## Current Behavior

Cross-site scripting attack is possible through the Internal Server Error page

## Possible Solution

Escape HTML characters in error message

## Steps to Reproduce (for bugs)

1. Install Chrome extension [ModHeader](https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj)
2. Set ModHeader to change 'Accept' header to `<script>alert(1)</script>`
3. Navigate to Graylog home page
4. Internal Server Error page should appear with Alert pop up

## Your Environment

* Graylog Version: 2.1.2
* Elasticsearch Version: 2.4.2
* MongoDB Version: 2.4.9
* Operating System: Ubuntu 14.04.5 LTS
* Browser version: Google Chrome

**Comment by chainkite** [comment]
As 2.2 hasn't released yet, is there a temp work around to fix this bug?

**Comment by joschi** [comment]
@chainkite This hasn't been back-ported to Graylog 2.1.x and there's no workaround, unless you want to fiddle with a proxy server which replaces 5xx replies with `Content-Type: text/html` with a custom error page.
