### ISSUE TITLE
Add an optional field separator to the key=value extractor

### ISSUE THREAD

**Issue by fstern** [Graylog2/graylog2-server#3176]
## Expected Behavior

I want to run an extractor on a field called url_query, which gets extracted by grok. 

I'd like to be able to split something like:
`ptm_source=feed&ptm_context=mp3&ptm_request=1ab4f42b3515&ptm_file=foobar.mp3`
into separate key/value pairs. 

## Current Behavior

The current key=value extractor only splits off the first key and leaves the rest of the string as value. 

## Context

I split these parameters from HTTP requests to determine the source of the request, being it a feed/webplayer/whatever and the currently played media format. 

To do this extraction directly in graylog would save me a logstash instance.

**Comment by joschi** [comment]
@fstern You can use the [`key_value()`](http://docs.graylog.org/en/2.1/pages/pipelines/functions.html#key-value) function in a processing pipeline for this.
