### ISSUE TITLE
Service discovery implementation with Graylog

### ISSUE THREAD

**Issue by dannyz29** [Graylog2/graylog2-server#3177]
I'm looking for some documentation of guidance for an etcd implementation in our setup.

We currently have a group of AWS spot ec2 Graylog instances in our setup (standard setup, not appliance). Our logs are shipped using UDP GELF to the Graylog instances.

We would like to find a way to use service discovery (like etcd), as our spot instances our often outbid and their IP address changing. 

If we were using TCP, I would just use an ELB. As we're using UDP, not supported by ELB, we must have some way to dynamically discover our spot graylog instances. 

* Graylog Version: 2.1.2
* Elasticsearch Version: 2.3
* Operating System: Ubuntu 14

**Comment by joschi** [comment]
@dannyz29 Graylog currently doesn't support etcd or any other similar service, such as Zookeeper or Consul.

**Comment by jalogisch** [comment]
We will not implement such a possibility in the future.
