### ISSUE TITLE
Allow using different alarm callbacks on conditions in the same stream

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#3180]
Right now, all alert conditions in the same stream share the same alarm callbacks, which may not be what users need.

It would be better to allow users to choose which alarm callbacks to use for each alert condition, regardless of what other conditions use. This would also imply that alarm callbacks may be shared among many alert conditions.

**Comment by bernd** [comment]
This is possible with the new alerting in 3.2. Closing the issue.
