### ISSUE TITLE
import grok pattern should support common EOL types

### ISSUE THREAD

**Issue by jesusch** [Graylog2/graylog2-server#3183]
## Expected Behavior
"System -> Grok patterns -> Import pattern file"
Grok import should support different EOL seperators

## Current Behavior
Only Unix LF seems to be supported

## Possible Solution
Support CR (Mac), CR LF (Windows), and LF (Unix)

## Your Environment
* Graylog Version: 2.1.2+50e449a

**Comment by joschi** [comment]
Duplicate of #2465.

**Comment by jesusch** [comment]
Hi @joschi ,

I disagree that this issue is a duplicate of #2465 
This issue is not about multiline extractors but about grok patterns.
I mean "System -> Grok patterns -> Import pattern file"

**Comment by joschi** [comment]
@jesusch Ah, okay. Got it. I'll reopen this issue.

**Comment by joschi** [comment]
@jesusch This time the correct issue: Duplicate of #3003
