### ISSUE TITLE
Cannot stack line charts using same field/value from different searches

### ISSUE THREAD

**Issue by brandonriggs** [Graylog2/graylog2-server#3187]
## Expected Behavior

From the standard search page, I search for a specific error code (e.g. 403). I then click on the "Generate chart" for the field in question (e.g. error_code). The configuration of the chart is as follows:

- Value: Total
- Type: Line
- Interpolation: Cardinal
- Resolution: Hour

With the chart still on the page, I search for a different error code (e.g. 404), click "Generate chart" for the same field, and the second chart appears. I apply the same settings to the second chart.

When I drag the first chart onto the second chart, it should then display a combined chart showing the correct values.

## Current Behavior

When I drag the first chart onto the second chart, one of the values changes from "Total" to "Mean". I have only tested this on charts configured as shown above.

## Possible Solution

I haven't looked through the code personally, so I can't say for certain how this is working on the backend. It seems to me that the charts allow only unique field/value combinations per chart. The field/value combinations should somehow be distinguished by the search from which the chart was generated.

## Steps to Reproduce (for bugs)

1. Search for a specific numeric value in a specific field (e.g. winlogbeat_event_id:20) and generate a chart, using any field that has a static value of "1". Set the value of the chart to "Total".
2. Repeat step one, changing only the numeric value in question (e.g. winlogbeat_event_id:21).
3. Drag chart 1 onto chart 2.
4. Stacked chart's value for one of the charts becomes "Mean".

## Context

I'm creating a chart that contains values for both failed login attempts and kerberos validation failures (using Microsoft event IDs). My goal was to distinguish local and domain failed login attempts. I know I could find a workaround for this particular case, but there have been other situations where having this work as expected would have been tremendously helpful.

## Your Environment

* Graylog Version: 2.1.2+50e449a, codename Smuttynose
* Elasticsearch Version: 2.4.1
* MongoDB Version: db version v2.4.10
* Operating System: Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
* Browser version: Firefox 50.0.2

**Comment by edmundoa** [comment]
Hi @brandonriggs,

In my tests I could reproduce the issue you described, although it looks like the graph itself is right, as the data points are identical to each of the individual graphs. There is an issue with labelling the right statistical function used. Could you please confirm that is also what you are experiencing?

Thank you!
