### ISSUE TITLE
2.2 UX/UI Improvement: Index sets

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#3190]
A few things I noticed when using this for the first time. **This is mostly based on usual questions we get and confusion we see when talking to new users and customers.**

### The _/system/indices_ sub-headline is not accurate anymore.

I think it is still the general text that we used for the index listing before. I suggest changing it to:

> A Graylog stream is always writing log messages into a particular index set. An index set is a configuration for retention, sharding, and replication of the stored data. By letting a stream write into an individual index set, you can, for example, configure Graylog to maintain different retention times per stream.

### Change default index set description

It is currently "The Graylog default index set" and I'd suggest changing it to:

> The default index set. Graylog writes all messages that are not routed into a particular index set here.

### In _Create index set_: Describe _Index prefix_ configuration better

I got stuck here for a moment. Can we have a default prefix? I suspect this has to be a unique prefix but it did not tell me. A lot of questions here. :)

### In _Create index set_: Help with replica and shard configuration

As an experienced Graylog user, I know what replicas and shards are for and what I should set them to, but I can see new users struggle with this. Can we add another sentence of explanation and also link to the docs?

### In _Create index set_: Small changes to retention settings dialog

Change "Graylog uses multiple indices to store documents in. You can configure the strategy it uses to determine when to rotate the currently active write index." to:

> Graylog splits up the stored log data over multiple indices to optimize read and write access. It will determine when to create a new index based on the configuration below.

Change "Graylog uses a retention strategy to clean up old indices." to:

> Graylog can purge or hide old data at a certain point in time. A typical use case is, for example, to automatically delete all data older than 30 days. Graylog will constantly look at home many indices you have in total and then delete those that are in excess. If you wanted to keep 30 days of data, you should configure the rotation period to _1 day_ and the _maximum number of indices_ below to 30. (or, for example,12 hours and 60 indices) With that configuration, Graylog would create a 31st index and delete the oldest. This way you'd be cycling through 30 days of the most recent data and never store more.

**Comment by edmundoa** [comment]
Fixed in #3213
