### ISSUE TITLE
Configured callback block email alert

### ISSUE THREAD

**Issue by avongluck-r1soft** [Graylog2/graylog2-server#3208]
It seems when you configure a callback (OpsGenie in this case) the callback blocks the email notifications.

## Expected Behavior
When callbacks are configured, all alert actions fire.

## Current Behavior
When callbacks are configured, email alerts don't trigger.

## Environment

* Graylog Version:2.1.2

![emaul](https://cloud.githubusercontent.com/assets/12514863/21202561/66311fc6-c214-11e6-9643-e5a7a6613c8b.png)

**Comment by avongluck-r1soft** [comment]
green callback works.  Email in red doesn't.  Removing the callback results in the email to the receivers working.

**Comment by joschi** [comment]
@avongluck-r1soft While that's badly documented, it's the intended result.

If you want to receive emails in addition to the OpsGenie notifications, you'll have to add an Email Alert Callback.

In Graylog 2.2.0, this will be explicit instead of this (quite surprising) behavior.
