### ISSUE TITLE
Let Kafka input support raw, syslog and GELF

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#322]
Right now it's only accepting our own graylog2-radio MessagePack format.

**Comment by maksimlikharev** [comment]
is there any updates on this issue, really make it or break it point for me.
Thanks

**Comment by kroepke** [comment]
We'll see if we can get it into the 1.1 release.

**Comment by joschi** [comment]
This might be especially useful in conjunction with the native rsyslog Kafka output module: http://www.rsyslog.com/doc/v8-stable/configuration/modules/omkafka.html

**Comment by siliconblade** [comment]
It would be great to have Apache Avro Codec (http://avro.apache.org/) support as well. Logstash 1.5.0ga just added it (https://www.elastic.co/blog/logstash-1-5-0-ga-released).

**Comment by huhongbo** [comment]
1.1 release has go into beta.2 ,how about the kafka input

**Comment by bernd** [comment]
@huhongbo Kafka inputs for Syslog, Raw and GELF will be in 1.1.0-beta.3.

**Comment by siliconblade** [comment]
Any chance with Avro? Let me know if I can help.

**Comment by joschi** [comment]
@siliconblade No, Apache Avro won't be supported by Graylog out of the box. The relevant codecs and inputs (e. g. for Kafka and AMQP) could be easily implemented as plugins, though.
