### ISSUE TITLE
Possible file descriptor leak in Graylog Server

### ISSUE THREAD

**Issue by vascop** [Graylog2/graylog2-server#3223]
* Graylog Version: 2.1.2
* Elasticsearch Version: 2.3.5
* MongoDB Version: 3.2.9
* Operating System: Ubuntu 14.04.5

We're running 2.1.2 but the issue was also happening with 2.1.1 at least, updating didn't solve it. This is a one node setup.

We have the same issue as #2823 . I see an steady increase in open fds resulting in an eventual crash until the process is restarted. FWIW most errors we're seeing are not the Elasticsearch health that gitfrederic reported, instead they're mostly:

2016-12-21T10:45:46.176Z ERROR [NettyTransport] Error in Input [GELF HTTP/57b48de2bfa5c34ad4a1eed9] (channel [id: 0xeb609605, /IP:13581 => /IP:12443])
java.io.IOException: Broken pipe

But the end result is the same, ever increasing fds until a crash. Another data point is that the increase isn't monotonic, but it does keep growing as the hours pass.

**Comment by joschi** [comment]
@vascop Please attach a list of the open file descriptors (i. e. the output of `lsof` for the Java process running Graylog).

**Comment by vascop** [comment]
Here's a short excerpt of the output: [http://pastebin.com/ZwgD5HSr](http://pastebin.com/ZwgD5HSr).
After what was pasted what actually follows are around ~20k lines of ESTABLISHED connections to other ips.

**Comment by dennisoelkers** [comment]
@vascop: It looks like the clients logging via GELF HTTP do not properly tear down the connection and reestablish a connection next time instead. Is that correct? If yes, this is not really a problem with the Graylog server, but with the client(s) using it.

**Comment by vascop** [comment]
@dennisoelkers This indeed seems like the problem we're seeing. At the browser clients do not close the connection (and they are not required to) and so the connections just hang there. 

This problem is reduced by setting the keepalive option as true in the Graylog input, as it forces each client to only create 1 connection, although each other new client will then create a new connection for itself.

The next step now would be for us to set a connection keepalive timeout on the graylog server. Is this an option that we missed somewhere? By setting a timeout we could force these hanging connections to close and mitigate the problem.

**Comment by bernd** [comment]
@vascop I created a pull request that introduces a new idle writer timeout for the HTTP GELF input. This fixes the problem for me when testing with Chrome and Firefox.

See https://github.com/Graylog2/graylog2-server/pull/3315
