### ISSUE TITLE
Preflight Options 405 Method not allowed

### ISSUE THREAD

**Issue by hasher** [Graylog2/graylog2-server#3232]
I have an Angular2 webapp which should send logs directly to http://example.tld:5555/gelf/.
This works properly with Postman, however if I try to call the same request through the web application, I receive 405 - Method not allowed. I checked the config file and web_enable_cors is set to true. Also rest_enable_cors is set to true.
My Graylog lives in a docker container and my inputs listen to port 5555.

## Expected Behavior
It should create a log in graylog.

## Current Behavior
An error occurs in the web console indicating that Options method is not allowed

## Steps to Reproduce (for bugs)

1. Create a sample web app
2. Try to create a log sending a post request to  http://graylog.tld:5555/gelf
3. Check the console for errors

## Context
I'm trying to create logs from the web app frontend.

## Your Environment
Chrome Browser

* Graylog Version: Graylog v2.1.2+50e449a
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Windows 10
* Browser version: Version 55.0.2883.87 m (64-bit)

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
