### ISSUE TITLE
Notification details are not reloaded when updated on condition page

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#3235]
## Expected Behavior

When editing the notification settings on the condition details page (e.g. `/alerts/conditions/58458e442f857c314491344e/76f663ac-d5ec-4529-8455-48c63611c89c`) the details of the notification should be updated after saving it.

## Current Behavior

After saving the notification the details for the notification stay the same and are not updated. When editing and saving a notification on the notifications page, the data is reloaded.

## Possible Solution

Reload notification settings after saving them on the conditions page.

## Steps to Reproduce (for bugs)

1. Create condition
2. Create notification
3. Go to the condition details page for the condition
4. Edit and save the settings for the notification
5. Check notification details for the updated values

## Your Environment

* Graylog Version: 2.2.0-beta.4-SNAPSHOT commit 5e28b1fea

**Comment by edmundoa** [comment]
Refs https://github.com/Graylog2/graylog2-server/issues/3195

**Comment by edmundoa** [comment]
Fixed in #3264
