### ISSUE TITLE
Allow to define how many quickterms to show

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-server#3246]
_From @lennartkoopmann on January 15, 2014 11:27_

Currently set to a maximum of 50. 

_Copied from original issue: Graylog2/graylog2-web-interface#505_

**Comment by florianvolle** [comment]
_From @lennartkoopmann on January 20, 2014 21:25_

Also reflect on dashboards.

**Comment by dennisoelkers** [comment]
Fixed in `3.1.0`.
