### ISSUE TITLE
graylog not reading full message through raw/plaintext inputs

### ISSUE THREAD

**Issue by vivred** [Graylog2/graylog2-server#3249]
graylog not reading full message through raw/plaintext inputs when messages starts with control characters.

## Expected Behavior
when a message starts with a control characters such as /u0016 or /u0020  graylog should send the same message to elasticsearch.

## Current Behavior
when a message starts with a control characters such as /u0016 or /u0020 eg: "/u0016hello/u0016vivek"
graylog rawplaintext kafka/tcp input is stripping the first character and sending to elasticsearch as
"hello/u0016vivek" .

## Possible Solution
?

## Steps to Reproduce (for bugs)
send a message that starts with control character to any kafka/tcp raw/plaintext input
`String testmessage = "\u0016" + "hello" + "\u0016" + "vivek";`

## Context
our csv delimiter is "\u0016" , often the first field of the csv message happens to empty which makes the 
message to start with "\u0016" 

## Your Environment
tested graylog 2.1 and 2.2 beta 3.

* Graylog Version:all
* Elasticsearch Version:2.4

**Comment by joschi** [comment]
The problem here is that Graylog is trimming messages on ingest in order to get rid of leading and trailing whitespace characters. This is not restricted to plaintext inputs.

```
java> String s = "\u0016Foo"
java.lang.String s = "Foo"
java> s.length()
java.lang.Integer res1 = 4
java> s.trim().length()
java.lang.Integer res2 = 3
```

**Comment by vivred** [comment]
any reason why you are trimming the message, probably you may want to trim value of other fields 

if I see the code this is where you are trimming the message(not just message filed but any field)
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/plugin/Message.java#L321

Solution would be if the filed/key type is "message"  leave the value as it is, else trim() the value

```
if(FIELD_MESSAGE.equals(trimmedKey))  {
       str = ((String) value).trim();
} else {
       str = ((String) value).trim();
}
```

it would be great if you could commit this and release in 2.2
on a side note: when we send the same message through logstash to elasticsearch it is not trimming the message.

**Comment by joschi** [comment]
@vivred 
> it would be great if you could commit this and release in 2.2

That's rather unlikely.

> when we send the same message through logstash to elasticsearch it is not trimming the message.

Sure, it's Graylog trimming the message fields, why should they be trimmed if you don't use Graylog? 😉

**Comment by edmundoa** [comment]
@vivred The reason for trimming messages is that extractors and stream rules sometimes operate through the whole message, and it's very easy to miss a blank space present at the beginning of the message. It is also hard to debug this issue if that space is not always present (for example, when only one source is adding the space). To be honest, I don't see this changing any time soon unless there's a good reason for it.
