### ISSUE TITLE
Error importing a content pack from a newer version of graylog

### ISSUE THREAD

**Issue by alias454** [Graylog2/graylog2-server#3250]
When importing a content pack from a newer version of graylog (v2.2.0.beta2) the error message **"Could not import content pack Error importing content pack, please ensure it is a valid JSON file. Check your Graylog logs for more information."**  is displayed. I validated the exported json was properly formatted, tinkered with a few other things until eventually, I found that removing this parameter **"default_stream": false** allowed me to import the content pack.

It is possible to import the newer content pack into a v1.3.3 graylog instance without error but not when importing into v2.1.2.

Here is the original content_pack repo
https://github.com/alias454/graylog-fortinet-content-pack

This was the only change I made
https://github.com/alias454/graylog-fortinet-content-pack/commit/121ba75d04f3a39f2b2d9a69d44b4b17f1118b30

## Steps to Reproduce (for bugs)
1. Export a content pack from v2.2.0.beta2
2. Import the content pack into a v1.3.3 ova (it works)
3. Import the content pack into a v2.1.2 ova (it doesn't work)

* Graylog Version: 2.2.0.beta2

Regards,
Brandon

**Comment by edmundoa** [comment]
Hi @alias454 

This is expected, as some of the new features added in Graylog 2.2 add some data to streams that is not recognised by previous Graylog releases. The fact that the import works in 1.3.3 is more a coincidence than anything else.

Having said that, I think we should document this case, as it may not be obvious the reason why this happens.

**Comment by lennartkoopmann** [comment]
Closed in favor of #4220.
