### ISSUE TITLE
[SearchResource] Unable to execute search: all shards failed

### ISSUE THREAD

**Issue by mrigotto** [Graylog2/graylog2-server#3261]
Dear all, 

I just did a fresh install of Graylog / MongoDB / Elasticsearch on a Debian 7 server. 

* Graylog Version:2.1.2-1
* Elasticsearch Version:2.4.3
* MongoDB Version:3.2.11
* Operating System:Debian 7 (SMP Debian 3.16.7-ckt20-1+deb8u1)
* Browser version: Chrome Version 55.0.2883.95 (64-bit)

I created a new input for udp syslog that listens on port 12201. 
I configured a server to forward logs to the graylog server on port 12201. 

When I tested elasticsearch with this:
 curl -X GET http://localhost:9200/graylog_0/_search?q=message:*, 
I am able to see the logs. 

If I try to search for logs in the graylog web interface, I am not able to see anything and I have this line in my /var/log/graylog-server/server.log :
**[SearchResource] Unable to execute search: all shards failed**

What is strange is that if I try to create an extractor for my new input and I load a message, I am able to see the last syslog entry...

I saw that this issue was present with Graylog 2.0.x if we were using elasticsearch 2.4.x but as I am running a graylog version 2.1.x, my version of elasticsearch should be ok, don't you think?

Maybe I am missing something...

Regards,

**Comment by edmundoa** [comment]
Hi,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
