### ISSUE TITLE
Query time range limit- does not show warning if time is out of limits

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#3263]
## Expected Behavior
when you set **Query time range limit** for all searches and you do a query that is not within this limitations. The search will be executed in the limits but the user did not get a proper warning or message about that.

## Current Behavior
To describe the current behavior please look at the image. **Query time range limit** is set to *one day*, the query time is *one week* and the returned data is *one day*.

![last_week_shows_1_day](https://cloud.githubusercontent.com/assets/404238/21523977/e881ea60-cd12-11e6-9a53-ab028943d18f.png)

## Steps to Reproduce (for bugs)
1. limit **Query time range** (1 day)
2. extend your search to one week 
3. search all messages returns one day

## Context
The user should get a proper feedback that the search is limited by configuration. If this feedback is not given the user might thing he get returns for his search range and did not notice that the returned values are limited by the configuration. 

REF: https://github.com/Graylog2/graylog-support/issues/7

## Your Environment
* Graylog Version: Graylog 2.1.2+50e449a

**Comment by dennisoelkers** [comment]
Fixed in #9569.
