### ISSUE TITLE
Quick values in search get auto updated 

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#3269]
## Expected Behavior
If you create quick values at your main search window the values should be only updated if auto refresh is enable or you execute a new search. 

## Current Behavior
quick values will get updated every 5 seconds without doing anything.

![quick_value_update](https://cloud.githubusercontent.com/assets/404238/21539898/44e69272-cdab-11e6-8496-6bc27a3bf29a.png)

## Steps to Reproduce (for bugs)
1. create quick values 
2. watch right to the title (Quick values for ... ) 
3. see the values updated every 5 seconds

## Context
If you just create to have a short overview and forget the widget you can kill your elasticsearch performance (or cluster) just by leaving the widget open. This should only be updated on a dashboard or if auto-update on the search page is enable. 
Or it should be possible to disable.

## Your Environment
* Graylog Version: Graylog 2.1.2+50e449a

**Comment by bernd** [comment]
I think this is the same issue that got fixed in https://github.com/Graylog2/graylog2-server/issues/3086

This will be in 2.2.

**Comment by jalogisch** [comment]
yes this is duplicate will close this as #3086 solve this issue
