### ISSUE TITLE
How can i query by String When this String in the middle of a message?

### ISSUE THREAD

**Issue by RistoryWang** [Graylog2/graylog2-server#3271]
## Steps to Reproduce (for bugs)

I meet a problem,when i want qurey by this string A:
"a539d095b00443cabfcca53c74a65d9e"
in graylog,and my message B in es is like this:
{"ACCESS_V1.0.0":"2016-12-30T16:53:35.984+0800\u001EWAZ163RUYH2CZ5NL1MXE\u001E11\u001Ea539d095b00443cabfcca53c74a65d9e\u001Ea539d095b00443cabfcca53c74a65d9ea539d095b00443cabfcca53c74a65d9e\u001EMozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36

 ps: String A is in the middle of Message and seperated by  ASCII: \u0001E

But i can't get the result in ths query, how can i resolve this problem?
## Your Environment

* Graylog Version:2.0.3-1
* Elasticsearch Version:2.3.5
* MongoDB Version:3.2.8
* Operating System:7.0
* Browser version:Chrome 55

**Comment by jalogisch** [comment]
Hej @RistoryWang you should normalize the message with extractors or the processing pipelines. after that you should be able to query every information from your message.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by RistoryWang** [comment]
tks for reminding me，i will ask for this question with the channels which you metioned！
