### ISSUE TITLE
Dashboard - Support more widgets on screen by removing huge header

### ISSUE THREAD

**Issue by PaulDMendoza** [Graylog2/graylog2-server#3280]
On Dashboards, there is a gigantic header on the dashboard which has the title, the buttons like "Update in Background" and then a thing that says "Drag widgets to any position ..." which isn't needed. The problem is when I put this on a wall board type display, this header takes up a bunch of extra room.

## Possible Solution
Remove the large header at the top of the screen or maybe make it way smaller. 

* Graylog Version: 2.1.2
* Browser version: Chrome

**Comment by joaociocca** [comment]
Considering screen real state, maybe also allow for smaller widgets would be nice too?

**Comment by dennisoelkers** [comment]
Fixed in `3.2.0`.

**Comment by joaociocca** [comment]
ohhh now I have to get back to Graylog and see how this came out!! thanks for it, @dennisoelkers
