### ISSUE TITLE
Dashboard - When clicking "Fullscreen", remove the topmost navigation bar

### ISSUE THREAD

**Issue by PaulDMendoza** [Graylog2/graylog2-server#3281]
On the dashboard when in "Fullscreen" mode, the header at the top of the screen takes up screen real estate which reduces the amount of valuable information I can see in the widgets. It would be great if the header went away when I am in full screen mode. 

* Graylog Version: 2.1.2
* Browser version: Chome

**Comment by dennisoelkers** [comment]
Fixed in `3.2.0`.
