### ISSUE TITLE
File path not escaped properly in Show surrounding messages

### ISSUE THREAD

**Issue by llucenic** [Graylog2/graylog2-server#3287]
Message with a file field value (with absolute path, such as _C:\Program\Folder\Logs\logFile.txt_) cannot be search properly for surrounding messages due to not escaping the path separators.

![obrazok](https://cloud.githubusercontent.com/assets/2933634/21607247/2779c854-d1b5-11e6-8f79-bed32203f778.png)

## Expected Behavior

Messages are shown while having a properly escaped path separators in file field filter condition

![obrazok](https://cloud.githubusercontent.com/assets/2933634/21607341/bbd324fa-d1b5-11e6-9f22-38296b8d6be7.png)

## Current Behavior

No search result due to incorrect filter condition

![obrazok](https://cloud.githubusercontent.com/assets/2933634/21607287/753f0e46-d1b5-11e6-8cb1-d7ca536f24f5.png)

## Possible Solution

Workaround is to manually escape path separators in file field search condition. In general, every character that needs escape, should be escaped in search conditions.

## Steps to Reproduce (for bugs)

1. Have a search result with message that contains a file field with absolute path value
2. In that message's detail (expanded in the list of search results) click on Show surrounding messages
3. The search filter that comes up has unescaped value for file field.

## Your Environment

* Graylog Version: Graylog 2.1.2+50e449a
* Elasticsearch Version: 2.3.5
* MongoDB Version: 2.0.6.-1.1
* Operating System: Linux 3.2.0-4-amd64, Debian 7.9
* Browser version: FF 50.1.0

**Comment by bernd** [comment]
Thank you for the report, this will be fixed in the upcoming Graylog 2.2.
