### ISSUE TITLE
Filter collectors is not showing some working sources

### ISSUE THREAD

**Issue by davibaldin** [Graylog2/graylog2-server#3294]
After configured collectors in cluster, you cannot see some of them in the web UI.

## Expected Behavior
If I use filter collection field for example to filter the word "vivo" I didn't find all working collectors even I hit the "show inactive collectors".  

## Steps to Reproduce (for bugs)
1. Add collects (so far we did 35 times)
2. Open Graylog -> System -> Collectors
3. Hit include inactive collectors
4. Try do find some, example "vivo"
5. Notice that some itens didnt show in the list.
6. Try confirming the collector is sending messages. Clique in sources.
7. Try to find some, example "vivo"
8. Notice that all sources (collectors) shown in the list.

## Your Environment
* Graylog Version:  Graylog 2.1.1+01d50e5
* Elasticsearch Version:  Latest 2.x
* MongoDB Version: Latest
* Operating System: Linux CentOS 7
* Browser version: Latest important (Safari, Chrome and Firefox)

**Comment by jalogisch** [comment]
@davibaldin how long was the collector already not sending messages/was deactivated - as after some time the collectors get cleaned.

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
