### ISSUE TITLE
API url to get the number of `unprocessed massage`

### ISSUE THREAD

**Issue by swdream** [Graylog2/graylog2-server#3296]
hello, 
We are using graylog2 server 1.3.4 (Hansa)

For example, we can get ``throughput`` by querying to this API url:
http://127.0.0.1:12900/system/throughput`.
But I cannot find out the API url to get the information about `unprocessed massage` or any documentation related to it.
so, is there an API url to get the number of `unprocessed massage`?

Thanks a lot.

**Comment by joschi** [comment]
@swdream You can fetch a lot of metrics from the `/system/metrics` resource in the Graylog REST API. Check the API browser (Swagger UI) at http://127.0.0.1:12900/api-browser for details.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by swdream** [comment]
@joschi ok, thanks a lot
