### ISSUE TITLE
Export Dashboards/Searches/Streams/Alerts as PDF

### ISSUE THREAD

**Issue by joeylane** [Graylog2/graylog2-server#3298]
Not sure if this is the correct forum for a feature request, if not please remove.  It would be really nice if we could export our dashboards, search results, streams and alerts in PDF format.  Even cooler if we could automate emailing these PDFs to certain users.

For my particular use case, this is the only thing Graylog lacks when compared to Splunk.

**Comment by dennisoelkers** [comment]
This is currently out of scope for the near term development of Graylog. If you just want to export a web representation of dashboards/streams/... you can use your browser's functionality.
