### ISSUE TITLE
Stream rules match but no messages routed into a stream

### ISSUE THREAD

**Issue by emitev** [Graylog2/graylog2-server#3301]
Hi, 

I am using 
Graylog v2.1.2+50e449a

Experiencing a problem with a setting a stream for Juniper SRX models - 110 210 100

I can see the logs from those devices coming in to graylog (see pics attached). I can do a regular search for source:{NameOfFireWall} and that gets me the results I want. I created a stream for ease of management. The stream matches on field source criteria "must contain" and here I am using the name of the firewall the same name as the one that I use when doing a regular search. 

In the stream tab view in the graylog web interface the stream shows up ok and indicates that it is matching 40-60 msgs/s   [ 73 messages/second, Must match all of the 1 configured stream rule(s). ]

When I click on the specific stream it shows no messages:

 
Nothing found in stream Johannesburg
Your search returned no results, try changing the used time range or the search query.

If I do a search it then finds the relevant messages and I can test a message against the stream it states that this message is a match and it would be routed to the stream but in reality it is not. 

Picture 1 - Here it is showing that it is matching 30+ msgs/sec

![streamoverview](https://cloud.githubusercontent.com/assets/24935708/21678930/03dbdcea-d339-11e6-849d-3e62eff51553.PNG)

Picture 2 - Here is a specific test for an exact message. It states the message would be routed to this stream. 

![streamtest](https://cloud.githubusercontent.com/assets/24935708/21678927/03ad3084-d339-11e6-903f-a19ccc0b158c.PNG)

Picture 3  -  Here again it is showing that it is matching 30+ msgs/sec

![capture-graylog](https://cloud.githubusercontent.com/assets/24935708/21678928/03ae54e6-d339-11e6-8825-deb6281858c7.PNG)

Picture 4  -  Here I did a normal search with the exact same condition Source:{NameOfFirewall} . It is showing all the messages as expected 

![regularsearch](https://cloud.githubusercontent.com/assets/24935708/21678926/03ad15d6-d339-11e6-8892-2fd5a4a0cb7b.PNG)

Picture 5  -  Here is the contents of the stream when I click on it. It shows no messages. 

![stream](https://cloud.githubusercontent.com/assets/24935708/21678929/03b0db8a-d339-11e6-90c6-bda837a92cfe.PNG)

The exact same setup is working fine with juniper Netscreen SSG devices but there is something about the SRX that is different and is not working fine with the streams.

## Expected Behavior

I expect the stream to route messages which match the confired rule inside the stream

## Current Behavior

It shows that it is matching the messages but it is not routing them in the stream. 

## Steps to Reproduce (for bugs)

1. Juniper SRX 210 110 or 100 device UDP Syslog logging port 5140 
2.Pretty standard Graylog deployment. 
3.Try to filter messages into any kind of stream matching on source or other field values 
4.

## Your Environment

* Graylog Version: Graylog v2.1.2+50e449a
* Elasticsearch Version: 
* MongoDB Version:
* Operating System:  Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-57-generic x86_64)

* Browser version:

**Comment by emitev** [comment]
so I left it over night. Did not do anything and this morning it is working fine showing logs routed into the correct streams. It takes a while for graylog to pickup the config i guess. Not sure what the explanation is.

**Comment by dennisoelkers** [comment]
This should not take that long. Can you reproduce the error by creating a new stream, adding a few (matching) rules and checking how long it takes before messages are routed into that stream?

**Comment by jalogisch** [comment]
@emitev can you please check the timezone of your Juniper and your Graylog Setting. What you had written sounds like the time or the time settings are not the same on all devices.

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by edsonmarquezani** [comment]
Having the exact same issue right now. Single message matches but stream is empty, no messages being routed to it. Will wait for a while to see what happens.

**Comment by joschi** [comment]
@edsonmarquezani Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by edsonmarquezani** [comment]
@joschi Ok. Thanks.

**Comment by CMoH** [comment]
This seems like a design bug: all those test rules features should be consistent with this behaviour.

**Comment by joschi** [comment]
@CMoH I agree, but it will stay this way until we drop support for Elasticsearch 2.x, probably around Graylog 3.0.0.

**Comment by edsonmarquezani** [comment]
@joschi Wouldn't it be nice to have it documented somewhere, at least? It would save a lot of people precious time.

**Comment by joschi** [comment]
@edsonmarquezani You mean like in a FAQ section in the documentation?

http://docs.graylog.org/en/2.3/pages/faq.html#my-field-names-contain-dots-and-stream-alerts-do-not-match-anymore

**Comment by edsonmarquezani** [comment]
@joschi Oh, my bad, I had not seen it! That's perfect! Thanks.

**Comment by diranged** [comment]
This bit us as well.. even though its in the FAQ, its not an obvious thing to look for. :/

**Comment by bhoss12** [comment]
@joschi 

can I have few examples how to setup few streams to trigger alert notifications as per streams.
