### ISSUE TITLE
Wrong search query used when search refresh is on

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#3307]
When search auto-refresh is on, typing some content in the search field (without submitting) is changing the search results, as the stores using `RefreshStore` are using the wrong query.

## Expected Behavior
Typing on the search bar while auto-refresh is on has no effect, other than the change in the input field. Search results should be unaffected until the search button is pressed.

## Current Behavior
Typing on the search bar while auto-refresh is on changes the search query to fetch data.

## Steps to Reproduce (for bugs)
1. Perform a search, let's say `*`
2. Start search auto-refresh
3. See the new results coming
4. Type a search query on the search bar that does not return any results, i.e. `lolwut`
5. See the "No search results" page appear

## Your Environment
* Graylog Version: Graylog 2.2.0-beta.4-SNAPSHOT (c69a9242a8daad1d443ae9d265648e341245e6f4)

**Comment by kroepke** [comment]
My initial take on this is that we need to have two versions of the search state:
* the initial state as it came in via the URL (via `pushState`)
* the current state of the search components (chiefly the `SearchBar` etc)

Then when we detect a change from the state that came in via the `pushState` call, we should somehow indicate a non-executed search in the bar, by either highlight something, changing the button color or similar, and only make the changed query/params available after the `executeSearch` method has pushed the state.
