### ISSUE TITLE
Histogram Search Error and Search Rendering

### ISSUE THREAD

**Issue by ambsw-technology** [Graylog2/graylog2-server#3311]
When I try to search, the UI just shows a spinner with "Loading...":

 - I'm running the stock docker image (2.1.2-1)
 - I'm using an nginx (container) as a proxy (for SSL).  I used `web_endpoint_uri` and the UI seems to work fine otherwise.
 - I have a Syslog TCP (also tried UDP) showing Network IO.  I'm using 1514 to avoid permissions issues.  While testing, I exposed this port directly to the host.
 - I have 1 indices with 2452 messages
 - I'm sending messages from the docker host (so presumably no timezone issue)
 - I'm accessing the UI using Chrome (latest)

When I pull up Chrome's developer tools:

 - The call to `relative?query=...` returns a resultset
 - The call to `histogram?query=...` returns `{"type":"ApiError","message":"Unable to fulfill search request"}`
 - I'm seeing related errors in the console:
     - `There was an error fetching a resource: cannot GET https://<graylog>/api/search/universal/relative/histogram?query=gl2_source_input%3A586ec92e4cedfd0001ec4620&range=28800&interval=minute (500). Additional information: Unable to fulfill search request
t @ plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.8cb610e9be38ce39b2d9.js:1`
     - `Unhandled rejection Error: cannot GET https://<graylog>/api/search/universal/relative/histogram?query=gl2_source_input%3A586ec92e4cedfd0001ec4620&range=28800&interval=minute (500)`
 - I think this is a (or the) relevant log entry:  `2017-01-06 13:43:44,529 WARN : org.graylog2.rest.resources.search.SearchResource - Unable to execute search: all shards failed`

It looks like the histogram error is blocking rendering of the resultset.  What else can I provide to assist in replicating?

FWIW I also tried to get next steps on the IRC and will close/update if I get a response.  However, the nature of the issue (error on histogram call and lack of client-side error handling) seems appropriate for a ticket.

**Comment by ambsw-technology** [comment]
I ran into this error while testing deployment scripts.  Inexplicably -- since none of the subsequent changes were intended to affect this -- the problem has resolved itself.

I'm going to leave the issue open because I do believe the histogram error should be gracefully handled, but may not be as helpful in reproducing the underlying search error.

**Comment by jalogisch** [comment]
@ambsw-technology please check your elasticsearch and graylag-server log files if you can find additional entries during the time of the issue.

**Comment by ambsw-technology** [comment]
Unfortunately, I was doing deployment testing for the graylog server when I discovered the issue so we were repeatedly wiping the logs (and repeatedly seeing the issue).  When the issue unexpectedly resolved itself, I lost access to any additional information.

I did skim the graylog log when I snipped that entry and it was occurring repeatedly throughout the log (probably on every 5 sec refresh of the search page).  The reset of the log messages looked like standard maintenance stuff.

I realize that's frustratingly little help, but you should at least be able to simulate the 500 error in the UI code and gracefully handle it.

**Comment by jalogisch** [comment]
@ambsw-technology this does not look like an issue with graylog and more like in your setup.

please open a new issue if you can provide data that we can reproduce.
