### ISSUE TITLE
No web interface search results when (very) many terms used

### ISSUE THREAD

**Issue by BambooVolt** [Graylog2/graylog2-server#3317]
2.1.0 installed from the OVA VM.

Entering a long and complex search query (190+ terms each ending in .*) will result in the page sitting there "loading..." forever. No data is returned and no errors are shown in the GUI or logged by the backends.

## Expected Behavior
Searches must either:
a) return results or
b) produce useful error messages to let the user know why there are no results or
c) there should be something in the logs to explain why the query never returns - eg:a timeout, maximum length exceeded.

## Current Behavior
Run complex search (190+ terms), page sits "loading..." forever, no results returned, no error in GUI, no error in logs.

## Possible Solution
None - it appears that there is a hard coded limit that cannot be exceeded.

Suspected that index.query.bool.max_clause_count: 10240 may need to be set in the config, but we are using query_string not bool (not sure if that matters).

In any event, making that change did not alter the outcome. (Yes, system was restarted after the config file edit)

## Steps to Reproduce (for bugs)
Copy and paste the first query into graylog and click search. You may need to modify the field names to suit your installation.

## Context
We need to query all IP addresses of the whois block eg: 35.128.64.0-35.151.255.255 [which is comprised of an /18, /17, /16, /15, /14 and 2 x /13 netblocks] and also a specific IP (eg:186.29.149.102)

Entering the query terms (we have a spreadsheet generate the netblock expansions) into the search page and hitting the search button results in a "loading..." page that never completes.

It will sit there as long as you leave it running.

ES appears to use some CPU for the first 1-2 seconds (as if the search is running), then ES returns to normal CPU use, but the GUI does not change from "loading...." and no results appear no matter how long it is left (waited 2 hours, no results, no errors).

Other searches with fewer terms continue to work. Removing any of the addresses from the query will allow it to succeed in less than 140ms so cannot see how a timeout is involved. (Surely adding one more entry could not take the response time from 140ms to over 10,000 ms (default maximum I believe), could it? And surely if it did there would be a timeout logged somewhere?)

The below URL is an example that fails in Chromium.

(Before anyone comments that the query can be reduced in size through coalescing some of the expanded subnets, know that we have a lot more subnets to add yet, and we are already stuck at this point.  So reducing the current query by coalescing some into a single address is not going to solve the problem in the long run when the rest of the subnets are added to the query.)

http://graylogserver/search?rangetype=relative&fields=message%2Csource&width=1866&highlightMessage=&relative=86400&q=pf_srcip%3A%2835.128.78.*+OR+35.128.79.*+OR+35.128.80.*+OR+35.128.81.*+OR+35.128.82.*+OR+35.128.83.*+OR+35.128.84.*+OR+35.128.85.*+OR+35.128.86.*+OR+35.128.87.*+OR+35.128.88.*+OR+35.128.89.*+OR+35.128.90.*+OR+35.128.91.*+OR+35.128.92.*+OR+35.128.93.*+OR+35.128.94.*+OR+35.128.95.*+OR+35.128.96.*+OR+35.128.97.*+OR+35.128.98.*+OR+35.128.99.*+OR+35.128.100.*+OR+35.128.101.*+OR+35.128.102.*+OR+35.128.103.*+OR+35.128.104.*+OR+35.128.105.*+OR+35.128.106.*+OR+35.128.107.*+OR+35.128.108.*+OR+35.128.109.*+OR+35.128.110.*+OR+35.128.111.*+OR+35.128.112.*+OR+35.128.113.*+OR+35.128.114.*+OR+35.128.115.*+OR+35.128.116.*+OR+35.128.117.*+OR+35.128.118.*+OR+35.128.119.*+OR+35.128.120.*+OR+35.128.121.*+OR+35.128.122.*+OR+35.128.123.*+OR+35.128.124.*+OR+35.128.125.*+OR+35.128.126.*+OR+35.128.127.*+OR+35.128.128.*+OR+35.128.129.*+OR+35.128.130.*+OR+35.128.131.*+OR+35.128.132.*+OR+35.128.133.*+OR+35.128.134.*+OR+35.128.135.*+OR+35.128.136.*+OR+35.128.137.*+OR+35.128.138.*+OR+35.128.139.*+OR+35.128.140.*+OR+35.128.141.*+OR+35.128.142.*+OR+35.128.143.*+OR+35.128.144.*+OR+35.128.145.*+OR+35.128.146.*+OR+35.128.147.*+OR+35.128.148.*+OR+35.128.149.*+OR+35.128.150.*+OR+35.128.151.*+OR+35.128.152.*+OR+35.128.153.*+OR+35.128.154.*+OR+35.128.155.*+OR+35.128.156.*+OR+35.128.157.*+OR+35.128.158.*+OR+35.128.159.*+OR+35.128.160.*+OR+35.128.161.*+OR+35.128.162.*+OR+35.128.163.*+OR+35.128.164.*+OR+35.128.165.*+OR+35.128.166.*+OR+35.128.167.*+OR+35.128.168.*+OR+35.128.169.*+OR+35.128.170.*+OR+35.128.171.*+OR+35.128.172.*+OR+35.128.173.*+OR+35.128.174.*+OR+35.128.175.*+OR+35.128.176.*+OR+35.128.177.*+OR+35.128.178.*+OR+35.128.179.*+OR+35.128.180.*+OR+35.128.181.*+OR+35.128.182.*+OR+35.128.183.*+OR+35.128.184.*+OR+35.128.185.*+OR+35.128.186.*+OR+35.128.187.*+OR+35.128.188.*+OR+35.128.189.*+OR+35.128.190.*+OR+35.128.191.*+OR+35.128.192.*+OR+35.128.193.*+OR+35.128.194.*+OR+35.128.195.*+OR+35.128.196.*+OR+35.128.197.*+OR+35.128.198.*+OR+35.128.199.*+OR+35.128.200.*+OR+35.128.201.*+OR+35.128.202.*+OR+35.128.203.*+OR+35.128.204.*+OR+35.128.205.*+OR+35.128.206.*+OR+35.128.207.*+OR+35.128.208.*+OR+35.128.209.*+OR+35.128.210.*+OR+35.128.211.*+OR+35.128.212.*+OR+35.128.213.*+OR+35.128.214.*+OR+35.128.215.*+OR+35.128.216.*+OR+35.128.217.*+OR+35.128.218.*+OR+35.128.219.*+OR+35.128.220.*+OR+35.128.221.*+OR+35.128.222.*+OR+35.128.223.*+OR+35.128.224.*+OR+35.128.225.*+OR+35.128.226.*+OR+35.128.227.*+OR+35.128.228.*+OR+35.128.229.*+OR+35.128.230.*+OR+35.128.231.*+OR+35.128.232.*+OR+35.128.233.*+OR+35.128.234.*+OR+35.128.235.*+OR+35.128.236.*+OR+35.128.237.*+OR+35.128.238.*+OR+35.128.239.*+OR+35.128.240.*+OR+35.128.241.*+OR+35.128.242.*+OR+35.128.243.*+OR+35.128.244.*+OR+35.128.245.*+OR+35.128.246.*+OR+35.128.247.*+OR+35.128.248.*+OR+35.128.249.*+OR+35.128.250.*+OR+35.128.251.*+OR+35.128.252.*+OR+35.128.253.*+OR+35.128.254.*+OR+35.128.255.*+OR+35.129.*+OR+35.130.*+OR+35.131.*+OR+35.132.*+OR+35.133.*+OR+35.134.*+OR+35.135.*+OR+35.136.*+OR+35.137.*+OR+35.138.*+OR+35.139.*+OR+35.140.*+OR+35.141.*+OR+35.142.*+OR+35.143.*+OR+35.144.*+OR+35.145.*+OR+35.146.*+OR+35.147.*+OR+35.148.*+OR+35.149.*+OR+35.150.*+OR+186.29.149.102%29

The URL above is 3236 characters long inclusive.

If we remove an IP range and the OR  (eg: the first one is removed "35.28.64.* OR ") then the URL is 3221 bytes long and the query now succeeds and runs in <140ms.

The URL lengths and headers are not being exceeded, as 3300 bytes is well below the maximums in chrome and firefox (tried both).

** Interestingly, firefox allowed 2 more than chrome - so it would appear this _is_ URL/header/?? max length related issue.

Web Developer in Firefox indicates headers are only "3.826kb" - so well below the threshold (the default configs set them to max 8192)

Tried setting headers and URL lengths "very high: in graylog.conf, 65k headers and 40k URL max length.

Bounced both ES and graylog-server.

No change in result.

We can use curl to go direct to ES with the full query without issue and it runs in 1261ms and returns 4 results:
{
  "took" : 1261,
  "timed_out" : false,
  "_shards" : {
    "total" : 4,
    "successful" : 4,
    "failed" : 0
  },
  "hits" : {
    "total" : 4,
...

So ES is happy with the format and complexity of the query, but it appears that graylog is incapable of passing it through for whatever reason, but doesn't tell us why.

curl -XGET http://127.0.0.1:9200/graylog_0/_search?pretty -d '{ "query" : { "query_string" : { "query": "35.128.64.* OR 35.128.65.* OR 35.128.66.* OR 35.128.67.* OR 35.128.68.* OR 35.128.69.* OR 35.128.70.* OR 35.128.71.* OR 35.128.72.* OR 35.128.73.* OR 35.128.74.* OR 35.128.75.* OR 35.128.76.* OR 35.128.77.* OR 35.128.78.* OR 35.128.79.* OR 35.128.80.* OR 35.128.81.* OR 35.128.82.* OR 35.128.83.* OR 35.128.84.* OR 35.128.85.* OR 35.128.86.* OR 35.128.87.* OR 35.128.88.* OR 35.128.89.* OR 35.128.90.* OR 35.128.91.* OR 35.128.92.* OR 35.128.93.* OR 35.128.94.* OR 35.128.95.* OR 35.128.96.* OR 35.128.97.* OR 35.128.98.* OR 35.128.99.* OR 35.128.100.* OR 35.128.101.* OR 35.128.102.* OR 35.128.103.* OR 35.128.104.* OR 35.128.105.* OR 35.128.106.* OR 35.128.107.* OR 35.128.108.* OR 35.128.109.* OR 35.128.110.* OR 35.128.111.* OR 35.128.112.* OR 35.128.113.* OR 35.128.114.* OR 35.128.115.* OR 35.128.116.* OR 35.128.117.* OR 35.128.118.* OR 35.128.119.* OR 35.128.120.* OR 35.128.121.* OR 35.128.122.* OR 35.128.123.* OR 35.128.124.* OR 35.128.125.* OR 35.128.126.* OR 35.128.127.* OR 35.128.128.* OR 35.128.129.* OR 35.128.130.* OR 35.128.131.* OR 35.128.132.* OR 35.128.133.* OR 35.128.134.* OR 35.128.135.* OR 35.128.136.* OR 35.128.137.* OR 35.128.138.* OR 35.128.139.* OR 35.128.140.* OR 35.128.141.* OR 35.128.142.* OR 35.128.143.* OR 35.128.144.* OR 35.128.145.* OR 35.128.146.* OR 35.128.147.* OR 35.128.148.* OR 35.128.149.* OR 35.128.150.* OR 35.128.151.* OR 35.128.152.* OR 35.128.153.* OR 35.128.154.* OR 35.128.155.* OR 35.128.156.* OR 35.128.157.* OR 35.128.158.* OR 35.128.159.* OR 35.128.160.* OR 35.128.161.* OR 35.128.162.* OR 35.128.163.* OR 35.128.164.* OR 35.128.165.* OR 35.128.166.* OR 35.128.167.* OR 35.128.168.* OR 35.128.169.* OR 35.128.170.* OR 35.128.171.* OR 35.128.172.* OR 35.128.173.* OR 35.128.174.* OR 35.128.175.* OR 35.128.176.* OR 35.128.177.* OR 35.128.178.* OR 35.128.179.* OR 35.128.180.* OR 35.128.181.* OR 35.128.182.* OR 35.128.183.* OR 35.128.184.* OR 35.128.185.* OR 35.128.186.* OR 35.128.187.* OR 35.128.188.* OR 35.128.189.* OR 35.128.190.* OR 35.128.191.* OR 35.128.192.* OR 35.128.193.* OR 35.128.194.* OR 35.128.195.* OR 35.128.196.* OR 35.128.197.* OR 35.128.198.* OR 35.128.199.* OR 35.128.200.* OR 35.128.201.* OR 35.128.202.* OR 35.128.203.* OR 35.128.204.* OR 35.128.205.* OR 35.128.206.* OR 35.128.207.* OR 35.128.208.* OR 35.128.209.* OR 35.128.210.* OR 35.128.211.* OR 35.128.212.* OR 35.128.213.* OR 35.128.214.* OR 35.128.215.* OR 35.128.216.* OR 35.128.217.* OR 35.128.218.* OR 35.128.219.* OR 35.128.220.* OR 35.128.221.* OR 35.128.222.* OR 35.128.223.* OR 35.128.224.* OR 35.128.225.* OR 35.128.226.* OR 35.128.227.* OR 35.128.228.* OR 35.128.229.* OR 35.128.230.* OR 35.128.231.* OR 35.128.232.* OR 35.128.233.* OR 35.128.234.* OR 35.128.235.* OR 35.128.236.* OR 35.128.237.* OR 35.128.238.* OR 35.128.239.* OR 35.128.240.* OR 35.128.241.* OR 35.128.242.* OR 35.128.243.* OR 35.128.244.* OR 35.128.245.* OR 35.128.246.* OR 35.128.247.* OR 35.128.248.* OR 35.128.249.* OR 35.128.250.* OR 35.128.251.* OR 35.128.252.* OR 35.128.253.* OR 35.128.254.* OR 35.128.255.* OR 35.129.* OR 35.130.* OR 35.131.* OR 35.132.* OR 35.133.* OR 35.134.* OR 35.135.* OR 35.136.* OR 35.137.* OR 35.138.* OR 35.139.* OR 35.140.* OR 35.141.* OR 35.142.* OR 35.143.* OR 35.144.* OR 35.145.* OR 35.146.* OR 35.147.* OR 35.148.* OR 35.149.* OR 35.150.* OR 35.151.* OR 186.29.149.102", "fields" : [ "pf_srcip","pf_dest_ip","src_ip","dst_ip","nf_src_address","nf_dst_address" ] }}}'

Have checked the nginx config and appears ok wrt header sizes, etc.

## Our Environment
* Graylog Version: 2.1.0 from OVA VM
* Elasticsearch Version: as shipped with vm
* MongoDB Version: as shipped with vm
* Operating System: Ubuntu both desktop and server (latter as shipped)
* Browser version: Chromium and Firefox - both latest versions.

VM is allocated 4 x CPU and 6GB RAM - swap use is rare - currently 0. Plenty of free disk space.

Edits: Minor cosmetic changes, added index.query.bool.max_clause_count details

**Comment by BambooVolt** [comment]
Update: Attached debugger and set breakpoint in .../graylog2-server/graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java at line 242 in the function:

`    public SearchResult search(SearchesConfig config) {...`

 which at line 242 'runs the query':
`    SearchResponse r = c.search(request).actionGet();`

The query that works will break on that line - queries that do not work do not reach this function - so something is preventing the search from getting as far as even trying to run a query.

We fully realise this is a cosmetic bug (at best), and it only manifested when the boss saw us using our python scripts (they dump to terminals) and wanted to see the same results in the GUI.  And as we had been cutting and pasting these queries into the GUI for last several months without any issues, we were surprised (and embarrassed) when 'the system failed' (that's how the boss descibed it - no offense meant or intended).

I guess the 'bug' is really just a failure to check for valid query length and respond immediately to the user "Your query is too long" or similar.

If the max length was documented somewhere easily accessible we would change it to suit our needs, but despite several hours searching in the code, we were not able to locate anything resembling 'max query length' - we did find in the graylog.conf:

```
# The maximal length of the initial HTTP/1.1 line in bytes.
#web_max_initial_line_length = 4096
```

...but we haven't reached 4096 yet [only around 3300], so we cannot see how altering that value would do anything useful - and it's not clear it is relevant to the problem.

At least the data is still searchable via other methods.

**Comment by edmundoa** [comment]
Hi @BambooVolt,

Reading your issue description, I guess you are hitting the limit with your HTTP URL lengths. That would explain why some shorter requests are returning results (and triggering the break point in the code), but the longer ones don't.

The HTTP standard doesn't define any URL length limits and I couldn't find any "official" limits for Chrome or Firefox, but I guess limits in browsers are close to what is mentioned in this StackOverflow answer: https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers/417184#417184.

We could establish some arbitrary URL length limit on AJAX requests, but I would rather convert those GET requests into POST requests, avoiding the issue completely. I just moved an issue we had on the old web interface repository on that regard: #3327

**Comment by BambooVolt** [comment]
@edmundoa
In reference to the linked SO page, it is interesting that removing the referrer header gave so much extra headroom.  We certainly noticed it filling the logs very quickly.  We did actually see that page but in haste stopped reading where it indicated:

Chrome          32779
Firefox          >64k

Further reading of that page revealed the harsh reality of a variety of 'maximums'.

Agreed, changing to a POST seems the sensible thing to do. It will also reduce the referrer logging substantially.

**Comment by edmundoa** [comment]
That's the problem when the limit is not defined in the standards 😕 
I will close this issue in favour of #3327, please track its status and add any missing details in there!

Thank you.
