### ISSUE TITLE
API token different response

### ISSUE THREAD

**Issue by macko003** [Graylog2/graylog2-server#3319]
I created an api token for user, and I got different response with username and token.

## Current Behavior

```
curl -u USER:PASS -H 'Accept: application/json' -X GET 'http://IP:9000/api/users/USER/tokens?pretty=true'
{
  "tokens" : [ {
    "name" : "NAME",
    "token" : "TOKENID",
    "last_access" : "1970-01-01T00:00:00.000Z"
  } ]
}
```

```
curl  http://IP:9000/api/system  -u TOKENID:token
no/empty response
```

```
curl  http://IP:9000/api/system  -u USER:PASS
valid response
```

/api/system/cluster/stats/elasticsearch URL give back the same response with user and woth token.
(also the last_access timestamp doesn't updated.

## Steps to Reproduce (for bugs)

1. Create token
2. get an url with username inder /api/system
3. get tha same with token

## Your Environment

* Graylog Version: 2.1.2
* Elasticsearch Version:
* MongoDB Version:
* Operating System: CentOS Linux release 7.3.1611 (Core)
* Browser version:

**Comment by joschi** [comment]
@macko003 Try adding the `-i` parameter to your curl commands to see the response headers.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by macko003** [comment]
curl  http://IP:9000/api/system  -u TOKENID:token  -i
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="Graylog Server"
X-Graylog-Node-ID: XX
X-Runtime-Microseconds: 490
Date: Mon, 09 Jan 2017 10:58:23 GMT
Content-Length: 0

curl  http://IP:9000/api/system  -u USER:PASS  -i
HTTP/1.1 200 OK
X-Graylog-Node-ID: XX
X-Runtime-Microseconds: 244491
Content-Type: application/json
Date: Mon, 09 Jan 2017 10:58:40 GMT
Content-Length: 402
