### ISSUE TITLE
How do I set stopwords in server.conf

### ISSUE THREAD

**Issue by leizhiyuan** [Graylog2/graylog2-server#3320]
I use elasticsearch_analyzer = standard in my graylog,and I have a message like this
````
2017-01-09 20:02:50,197 [x/x] - [(x,aa.bb,Y,645810f41483963370181610719839,1ms)]
````

## Expected Behavior

expcected all terms like

````
Field terms:  xxx Y 645810f41483963370181610719839 1ms
````

the last comma should spit the last words.

## Current Behavior

````
Field terms:  xxx Y 645810f41483963370181610719839,1ms
````

but last words `645810f41483963370181610719839,1ms` was not splited.
## Possible Solution

maybe I can set stopwords to solve this problem.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:2.1.2
* Elasticsearch Version:2.3.0
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@leizhiyuan We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
