### ISSUE TITLE
"Manage stream rules" required option load from search and schedule 

### ISSUE THREAD

**Issue by rayeesnp** [Graylog2/graylog2-server#3323]
We are looking to schedule search and then alert, if matches the criteria 

Basically, I want to run search query for one day, and it should daily at specific time 

## Expected Behavior

If "Manage stream rules" section,  we can introduce new button button, "load query from search",  if you select this all saved search should load in drop-down list, and select the one you need, in the same windows required one more option to schedule, then based on this schedule search will be executed and send alert if required 

## Current Behavior

There is no option to schedule search in current graylog 

## Possible Solution
Provided above

## Steps to Reproduce (for bugs)

1. Select stream 
2. Create a stream 
3. Select Manage rules
4. Need to provide option to select radio button for "load query from search", [New feature suggested here]

## Your Environment

* Graylog Version         :  Graylog 2.1.2+50e449a 
* Elasticsearch Version:  
* MongoDB Version:
* Operating System: Centos 6.5
* Browser version:    Crome

**Comment by dennisoelkers** [comment]
In general I understand the rationale behind this, but you can already search for the message you want in the general search and test it against a stream by using the message actions menu.
<img width="1080" alt="screen shot 2017-02-16 at 15 36 36" src="https://cloud.githubusercontent.com/assets/41929/23025360/fab82024-f45d-11e6-99f1-b8fcd9c0cafc.png">

Duplicating this functionality in the stream rules editor itself is currently no option, therefore I am closing this issue for now.

**Comment by rayeesnp** [comment]
I was looking for scheduling the search, and generate the  alert if condition matches
