### ISSUE TITLE
Extractor 'Replace with regular expression' seems not to work

### ISSUE THREAD

**Issue by Pinny3** [Graylog2/graylog2-server#3325]
## Expected Behavior
If RegEx is matching write a value to another new field when using GELF UDP.

## Current Behavior
Is not working and the extractor seems to be ignored when using GELF UDP.

## Possible Solution
n/a

## Steps to Reproduce (for bugs)
1. I have got an extractor defined. Look here for details  https://d17oy1vhnax1f7.cloudfront.net/items/1s3L0E0E0u150g2K1T1c/Image%202017-01-10%20at%208.42.18%20AM.png?v=b8af363c
2. Logs coming in and looking like this after they have been imported: https://d17oy1vhnax1f7.cloudfront.net/items/1o1F212X0K1m273N2G1e/Image%202017-01-10%20at%208.48.02%20AM.png?v=3badc2ed
3. There is no additional field called LOG_LEVEL as expected.

## Context
We need this replacement to filter by the LOG_LEVEL since logs coming in with the filed LOG_LEVEL provided. 

## Your Environment
* Graylog Version: 2.1.2+50e449a 
* Elasticsearch Version: 2.4.3
* MongoDB Version: 3.2.11
* Operating System: Ubuntu 16.04
* Browser version: Safari 10.0.2 (Mac)

**Comment by joschi** [comment]
@Pinny3 This is a limitation of Graylog extractor documented at http://docs.graylog.org/en/2.1/pages/extractors.html#graylog-extractors-explained

> Graylog extractors only work on text fields but won’t be executed for numeric fields or anything other than a string.

You could use the [message processing pipelines](http://docs.graylog.org/en/2.1/pages/pipelines.html) to write a rule converting/copying the `level` message field, though.
