### ISSUE TITLE
 Request-URI Too Long Error when drilling down in sources page

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#3327]
From https://github.com/Graylog2/graylog2-web-interface/issues/1463:

When drilling down on the sources page there might be a "Request-URI Too Long" error. I have seen this happen when selecting "others" from the pie chart.

The problem is that we are using a GET request for the "others" query. With lots of sources in "others", the request URI can get too long.

We have to switch to a POST query for this to fix it.

**Comment by dennisoelkers** [comment]
Due to the sources page being a dashboard now, this is not relevant anymore.
