### ISSUE TITLE
Dashboard - Cannot change/drag widget size when hover over the widget

### ISSUE THREAD

**Issue by crylium** [Graylog2/graylog2-server#3328]
## Expected Behavior
On a dashboard, in the "unlocked" mode, when hovering over a widget, I should see that a gray arrow appears in its bottom-right corner. I should be able to use that icon to resize widgets. 

I should also be able to drag widgets to any position I like.

## Current Behavior
No gray arrow appears. I am also unable to drag widgets at all.

## Context
At the moment I have a dashboard with randomly-placed, randomly-sized widgets which require scrolling a lot just to see information. Dashboard is unusable.

## Your Environment

* Graylog Version: 2.1.2
* Elasticsearch Version: 2.4.2
* MongoDB Version: 3.2.11
* Operating System: CentOS 6.8
* Browser version: Chrome 55, Firefox 50

**Comment by edmundoa** [comment]
Hi @crylium,

Would you be so kind as to share any output in your browser's developer console while loading your dashboard and trying to move widgets? That output may help us figuring out the cause of the issue you are experiencing.

Thank you.

**Comment by crylium** [comment]
Hi @edmundoa , sure, I get the following (Chrome --> Inspect --> Console):

<code>vendor.js:36 Warning: Failed propType: Invalid prop `dashboards` of type `je` supplied to `DashboardList`, expected instance of `qt`. Check the render method of `DashboardListPage`.
r @ vendor.js:36</code>

Not sure it helps much. However, I think I found a workaround.

If I click on the weblink that's inside "**Drag widgets to any position you like in unlock / edit mode**.", I am unable to modify widgets, but I can still delete them, so only a partial edit works. 

Now, if I click on the big green button called "**Unlock / Edit**" that's placed in the header of the dashboard, a gray arrow appears in its bottom-right corner, and I can modify the shape of widgets. So this works fully.

When I click on the big gree button "Lock" having modified my widgets, and again click on the weblink inside "**Drag widgets to any position you like in unlock / edit mode**." to edit, I cannot modify anything.

This seems to be consistent, tried on Chrome and Firefox. I didn't notice this behaviour before.

**Comment by edmundoa** [comment]
Thank you for the information @crylium, we will investigate this issue further.

**Comment by edmundoa** [comment]
There is indeed a problem with the unlock link and we will fix it for 2.2. Thank you for reporting this issue!

**Comment by crylium** [comment]
Good news about the fix in 2.2, thank you!
