### ISSUE TITLE
web_endpoint_uri and rest_transport_uri doesn't work for login screen

### ISSUE THREAD

**Issue by ludekvodicka** [Graylog2/graylog2-server#3334]
I'm trying to use Graylog from Docker container. In localhost everything works ok. Unfortunately when I'm trying to access to Graylog from outside the localhost there is a problem on login screen.

This is my ur settings:

```
rest_listen_uri = http://0.0.0.0:9000/api
web_listen_uri = http://0.0.0.0:9000/

rest_transport_uri = http://192.168.0.66:9000/api
web_endpoint_uri = http://192.168.0.66:9000/api

```

But when I access it from other than the local computer, I get the following error:
```

Server currently unavailable
We are experiencing problems connecting to the Graylog server running on http://127.0.0.1:9000/api. Please verify that the server is healthy and working correctly.

You will be automatically redirected to the previous page once we can connect to the server.

Do you need a hand? We can help you.
```

and here are console errors: https://dl.dropboxusercontent.com/u/11355235/ShareX/2017/01/2017-01-11_10-23-17.png

## Expected Behavior

I believe that rest_transport_uri and web_endpoint_uri should also configure a login screen. Without that it's not possible to use Graylog in Docker outside the local computer.

## Your Environment
Latest Docker (on Win10 and also on Ubuntu with same results).

* Graylog Version: graylog2/server:2.1.0-3
* Elasticsearch Version: "elasticsearch:2"
* MongoDB Version: "mongo:3"
* Operating System: Win10 and Ubuntu
* Browser version:  Chrome and Internet Explorer

**Comment by joschi** [comment]
@ludekvodicka Please upgrade to the latest stable version of Graylog (which is Graylog 2.1.2 at the time of writing) and check if the problem still occurs.

**Comment by ludekvodicka** [comment]
Just tried it and unfortunately it's still the same. 

I tried it on latest docker image 2.1.2+50e449a

https://dl.dropboxusercontent.com/u/11355235/ShareX/2017/01/2017-01-11_10-44-11.png

**Comment by joschi** [comment]
@ludekvodicka
> Also, how exactly did you configure these settings?

**Comment by ludekvodicka** [comment]
Ok, My bad ;-(

Just figured it out when copy&pastin docker-compose file for graylog. I completely overlooked GRAYLOG_WEB_ENDPOINT_URI environment settings. Now it's working like expected. Thank you for your answer which point me to solution ;-)

graylog:
    image: graylog2/server:latest
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
>>>>>      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api <<<<<
....

**Comment by holms** [comment]
@ludekvodicka how could something like this help you? webinterface tries to connect to http://127.0.0.1:9000/api so it's obviously won't work for me, because server is running in AWS

**Comment by srihas619** [comment]
@holms try to configure a proxy and open it on your elastic IP or the public IP

**Comment by holms** [comment]
probably this was docker-swarm issue it's running now fine. Here's config with traefik in case anyone is interested: https://stackoverflow.com/questions/45725128/how-to-make-traefik-work-with-graylog2

**Comment by BrijToSuccess** [comment]
@ludekvodicka I am having the same issue, how exactly did you fix it?

**Comment by BrijToSuccess** [comment]
what did you set graylog_web_endpoint_uri to?

**Comment by phuongdh** [comment]
@BrijToSuccess You set it to the actual hostname and port, e.g. mydomain.com:1234, instead of the default 127.0.0.1:9000

**Comment by joschi** [comment]
@BrijToSuccess @phuongdh Please discuss this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
