### ISSUE TITLE
No results displayed in Graylog 2.2.0-beta.4+6f4b4d3

### ISSUE THREAD

**Issue by wouterbudding** [Graylog2/graylog2-server#3343]
Directly after upgrading to Graylog 2.2.0-beta.4+6f4b4d3 (from apt history: graylog-server:amd64 (2.2.0-5.beta.3, 2.2.0-6.beta.4) ) I noticed that results are not displayed anymore. "In 2 / Out 2 msg/s" is changing sometimes, so my syslog input _is_ receiving.

## Expected Behavior
Display results afters search for whatever. Like *.

## Current Behavior
Not displaying results.

## Steps to Reproduce (for bugs)
Login to interface (works) and do a search (not working, no results). 

I checked if all is running, the second is the syslog input:
tcp6       0      0 192.168.12.12:9000      :::*                    LISTEN      2356/java
udp6       0      0 192.168.12.12:1514      :::*                                2356/java
tcp6       0      0 127.0.0.1:9300          :::*                    LISTEN      1421/java

2017-01-12T06:46:15.982+01:00 INFO  [HttpServer] [HttpServer] Started.
2017-01-12T06:46:15.982+01:00 INFO  [JerseyService] Started REST API at <http://192.168.12.12:9000/api/>
2017-01-12T06:46:15.990+01:00 INFO  [ServerBootstrap] Graylog server up and running.
2017-01-12T06:46:15.982+01:00 INFO  [JerseyService] Started Web Interface at <http://192.168.12.12:9000/>
2017-01-12T06:46:16.042+01:00 INFO  [InputStateListener] Input [Syslog UDP/5862347ae987724ab59] is now RUNNING

## Your Environment
* Graylog Version: Graylog 2.2.0-beta.4+6f4b4d3
* Elasticsearch Version: 2.4.3
* MongoDB Version: 2.6.10-0ubuntu1
* Operating System: Ubuntu 16.04.1 LTS
* Browser version: Firefox 50.1.0 and Edge/14.14393

**Comment by joschi** [comment]
@wouterbudding 
* What kind of input are you using and how did you configure it exactly?
* How is your syslog daemon configured?
* Are the messages being indexed and simply not shown or are they dropped before? You can check this in your Elasticsearch indices.

**Comment by wouterbudding** [comment]
I did a complete reinstall (so lost all data, but who cares) and followed the instructions on http://docs.graylog.org/en/2.2/pages/installation/os/ubuntu.html . Only I chose graylog-2.2-repository_latest.deb instead of graylog-2.1-repository_latest.deb.

> What kind of input are you using and how did you configure it exactly?
first UDP/1514 (like always) and later tested with TCP/5140 . no difference. I am sure that data is getting in because I see it with `tcpdump -ni enp0s8 port 5140 -X -s0` AND please see attached picture, the in/out on the top right is showing messages.

> How is your syslog daemon configured?

$template GRAYLOGRFC5424,"<%PRI%>%PROTOCOL-VERSION% %TIMESTAMP:::date-rfc3339% %HOSTNAME% %APP-NAME% %PROCID% %MSGID% %STRUCTURED-DATA% %msg%\n"
*.* @@192.168.12.12:5140;GRAYLOGRFC5424

> Are the messages being indexed and simply not shown or are they dropped before?
> You can check this in your Elasticsearch indices.

I will find out, hang on. (never used Elasticsearch on itself)

![overview](https://cloud.githubusercontent.com/assets/22468456/21887863/13962f8a-d8c2-11e6-871f-3318c128cf30.png)
![search](https://cloud.githubusercontent.com/assets/22468456/21887864/13b0fd6a-d8c2-11e6-87e3-cfedd30441ed.png)
![in-out](https://cloud.githubusercontent.com/assets/22468456/21887865/13b32be4-d8c2-11e6-9638-f247a061021d.png)

**Comment by wouterbudding** [comment]
I'm still looking for a way to check my Elasticsearch indices. Hint please?

This is a command that I just executed:
curl -XGET 'http://localhost:9200/_cluster/health/twitter?level=shards'

and the result:

`{"cluster_name":"graylog","status":"red","timed_out":true,"number_of_nodes":2,"number_of_data_nodes":1,"active_primary_shards":0,"active_shards":0,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0,"indices":{}}

`

**Comment by wouterbudding** [comment]
**FIXED!!!**

I was looking to Elasticsearch as the prog that broke down, but now it seems that after the upgrade to Graylog 2.2.0-beta.4+6f4b4d3 this is not allow anymore! Took me f*cking 6 hours to find out :(.

$template GRAYLOGRFC5424,"<%PRI%>%PROTOCOL-VERSION% %TIMESTAMP:::date-rfc3339% %HOSTNAME% %APP-NAME% %PROCID% %MSGID% %STRUCTURED-DATA% %msg%\n"
*.* @@192.168.12.12:5140;GRAYLOGRFC5424
