### ISSUE TITLE
Email Alerts on Streams work once then stop.

### ISSUE THREAD

**Issue by STI-RIP** [Graylog2/graylog2-server#3347]
## Expected Behavior
I would expect that Email Alerts work every time a stream sees the required message.

## Current Behavior
1. Take action on system that creates event and sent to GrayLog.
2. GrayLog receives message, message is route to stream.
3. Alert occurs once and then no other alerts work.
4. If I restart services on GrayLog server, I can once again receive one alert and then it stops.

## Possible Solution
I need one. :) I cannot seem to find any information that helps resolve this situation and I have no idea where else to turn. If this is not where I should post this, I apologize. However, I cannot find any information on this specific issue anywhere. I would also expect that this type of issue should not be an issue on a product that has been around a while; which is why I'm at a loss as to why I cannot find any solutions.

## Context
I can see the messages reach the GrayLog server, and are Routed to the specific stream. However, no Email Alert is sent. I am able to see this by generating the event, then performing a search in GrayLog. I see the message indeed reached GrayLog and that it was routed to the required stream. However, after the first Alert goes out, no other alerts go out for any of my configured streams.

## Your Environment
GrayLog Server VM Appliance running on XenServer 7. VM is allocated 2 CPU and 4GB of memory.

* Graylog Version: 2.1.2+50e449a
* Elasticsearch Version:?
* MongoDB Version:?
* Operating System:?
* Browser version: Google Chrome v55.2883.87 m (64-bit)

**Comment by dennisoelkers** [comment]
How did you configure the alarm condition for that specific stream?

**Comment by STI-RIP** [comment]
**I originally configured the alert as follows:**
Field content value condition
Trigger Alert when a message arrives that has  the field "EventID"
set to "4725" and then wait at least "1" minute until triggering a new alert.
When sending an alert, include the last "1" messages of the stream evaluated for this alert condition.

**But then I changed the alert configuration to the following:**
Trigger alert when there are "more"
than "1" message in the last "1" minute and
then wait at least "1" minute until triggering a new alert.
When sending an alert, include the last "1" messages of the stream evaluated for this alert condition.

In both cases, I get the alert once and then all alerts stop, and if I restart the graylog services I can receive the one alert again. I'm not sure what else to look at.

Thanks for any suggestions or help you can provide.

**Comment by jalogisch** [comment]
@STI-RIP did you have any useful information inside your logfile?

Without that it looks more like a local problem and not something wrong with Graylog as we do not see this behavior.

**Comment by jalogisch** [comment]
as we did not get any feedback we close this issue. please re-open if you have input on this.

**Comment by marick7** [comment]
I have the same situation. Not every message that comes in a stream triggers an alert

**Comment by joschi** [comment]
@marick7 Please open a new issue and provide as many details as possible and ideally a reproducible test case, if possible.
