### ISSUE TITLE
Generate charts for non-numeric fields does not work

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#3359]
The behaviour while creating field charts on non-numeric fields has changed. Before we always displayed an error when trying to get a graph for a non-numeric field, now we just display an empty graph.

The best solution would be to display the cardinality values for non-numeric fields, as they should be available. In that way that graph could be easily added to dashboards.

## Expected Behaviour
Creating field charts for non-numeric fields displays the cardinality function. If there's a good reason to not do that, it should keep the old behaviour and display an error message.

## Current Behaviour
Creating field charts for non-numeric fields displays an empty graph. The response from the server is always a 200.

## Steps to Reproduce (for bugs)
1. Execute a search
2. Expand a non-numeric field in the search sidebar
3. Select "Generate chart"
4. See that an empty graph is now displayed

## Your Environment
* Graylog Version: Graylog 2.2.0-rc.1-SNAPSHOT (1a5cd0b)

**Comment by kroepke** [comment]
I still get the error message and no graph.
This is the error in the console:
```
FetchProvider.js:56 There was an error fetching a resource: cannot GET http://localhost:9000/api/search/universal/relative/fieldhistogram?query=%2A&range=7200&interval=minute&field=http_method&cardinality=false (400). Additional information: Field histogram query failed. Make sure that field [http_method] is a numeric type.
```
