### ISSUE TITLE
Opening used indices modal resets search bar state

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#3361]
The action of opening the used indices modal in the search sidebar resets the search bar.
![modal](https://cloud.githubusercontent.com/assets/716185/21984989/fc1db352-dbf8-11e6-83b2-c2b7b735babe.gif)

## Expected Behaviour
Opening the used indices modal should not reset anything in the search bar.

## Current Behaviour
Opening the used indices modal resets the query and time range in the search bar.

## Steps to Reproduce (for bugs)
See screenshot above.

## Your Environment
* Graylog Version: Graylog 2.2.0-rc.1-SNAPSHOT (1a5cd0b)
* Browser version: Firefox 52.0a2 (Developer Edition)

**Comment by dennisoelkers** [comment]
I cannot reproduce it with either Firefox nor Chrome. What I am wondering is why the URL in your browser's URL bar is not changing when you enter a search term?

**Comment by edmundoa** [comment]
I was able to reproduce it in Chrome and Safari too. The URL never changes because the search is not executed.
