### ISSUE TITLE
Do we support deploy web interface and backend server into different servers?

### ISSUE THREAD

**Issue by june805** [Graylog2/graylog2-server#3365]
Hi, 

I'm integrating Graylog into my product now. The design is to integrate(reuse) graylog web interface(either punchout or iframe) in my UI part, add a proxy in my system(this proxy mainly do the authentication work) to receive  all the request coming from the graylog web interface, and  forward the request into graylog server backend. I modify backend url into my proxy url in  /graylog2-web-interface/config.js. 

So I'd like to confirm the following questions based on my design:
1. Can graylog web interface deployed separate from the backend? Cause there is no such deployment scenario  mentioned in graylog document.

2. Are all the data used in web interface getting from REST API in graylog server backend? Is there any exception data? If the web interface totally independent with backend, will this feature be supported in future release?

3. Is my design ok for the current and future release in graylog?

Thank you very much!

**Comment by joschi** [comment]
> Can graylog web interface deployed separate from the backend? Cause there is no such deployment scenario mentioned in graylog document.

No.

> Are all the data used in web interface getting from REST API in graylog server backend?

Yes, except for the static assets (images, CSS, JavaScript).

> If the web interface totally independent with backend, will this feature be supported in future release?

Unlikely.

> Is my design ok for the current and future release in graylog?

It should be okay for now, but who knows, what the future brings? 😉
