### ISSUE TITLE
Pipeline Processing 

### ISSUE THREAD

**Issue by petegriggs** [Graylog2/graylog2-server#3391]
Hello,

I have two graylog instances setup (these are separate on separate sites) one works fine the other is a mirror setup however the processing is not working.

This is to extract snort alerts from the syslog message and put into the fields however it just isn't doing this.

Has anyone else experienced issues with the processing pipeline? Or if any one has any ideas?

Centos 7
Graylog v2.1.2+50e449a

Thanks
Pete

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
