### ISSUE TITLE
Enter Server Variable for Callback email alert

### ISSUE THREAD

**Issue by Bsod-d** [Graylog2/graylog2-server#3392]
I am trying to get the source (server in this case) to show when I receive an alert, but the alert has an empty field.

The Call back details are below:

```
##########
Alert Description: ${check_result.resultDescription}
Date: ${check_result.triggeredAt}
Stream ID: ${stream.id}
Server: ${message.fields.source}
Stream title: ${stream.title}
Stream description: ${stream.description}
${if stream_url}Stream URL: ${stream_url}${end}

Triggered condition: ${check_result.triggeredCondition}
##########

${if backlog}Last messages accounting for this alert:
${foreach backlog message}${message}

${end}${else}<No backlog>
${end}
```

However the details in the alert when I do get the alert are below, bearing in mind that this is a test

```
##########
Alert Description: Stream had 260 messages in the last 1 minutes with trigger condition more than 1 messages. (Current grace time: 0 minutes)
Date: 2017-01-19T15:06:19.640Z
Stream ID: 5880d1f5913f7855c558daf9
Server: 
Stream title: Test
Stream description: Test
Stream URL: http://graylog/streams/5880d1f5913f7855c558daf9/messages?rangetype=absolute&from=2017-01-19T15:05:19.640Z&to=2017-01-19T15:06:19.640Z&q=*

Triggered condition: 6165c412-52e5-47cd-b160-a348f613980c:MESSAGE_COUNT={time: 1, threshold_type: more, threshold: 1, grace: 0}, stream:={5880d1f5913f7855c558daf9: "TestBiztalk"} ##########

<No backlog>
```

I would expect to see a server name where "Server: " but it's blank. Am I using the correct variable?

* Graylog Version: Graylog 2.0.3 (f07c170) on graylog (Oracle Corporation 1.8.0_77 on Linux 4.2.0-38-generic)
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Ubuntu
* Browser version: Chrome

**Comment by joschi** [comment]
@Bsod-d There is no global `message` object but always a collection of messages which you have to iterate over (like shown on the bottom of the template and described in http://docs.graylog.org/en/2.1/pages/streams/alerts.html#email-alert-callback).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Bsod-d** [comment]
Sorry, wasn't sure where to post. will try the IRC
