### ISSUE TITLE
Widgets has no way to edit all properties after creation.

### ISSUE THREAD

**Issue by mayantec** [Graylog2/graylog2-server#3394]
## Expected Behavior

When you edit a dashboard, and go to edit button of a widget, it should show all parameters used for creation, like stream hashid, query, used field/fields.

## Current Behavior

Only a few widgets support full editing after creation, like counter. Bar graps added from searches, does not support the edition of the query, and Combined Values, also can not support the change of the field.

## Possible Solution

Allow in the editing dialog box of all widget types, the form fields to edit such values, like field used, or quey in the widgets that does not support it.

## Steps to Reproduce (for bugs)

1. Create a dashboard.
2. Make a query, and add it to the dashboard
3. Try to edit the query from the widget inside the dasboard is not an option.
4. Try the same with other widgets, for example quick values, does not allow to change field.

## Context

You have to destroy widgets and recreate them, if there is a change required, and some times you just can't have the same events in the same time window, so destroy and recreate will not be an option, just will be impossible to recreate the widget. And if you wish to do so, you have to export the dasboard as a content pack, and edit the json file in some editor, and put it back.

## Your Environment

* Graylog Version:  2.1.2 (Smuttynose) released at 2016-11-04
* Elasticsearch Version: 2
* MongoDB Version: 3
* Operating System: All
* Browser version: All

**Comment by hezor** [comment]
I'd like to see this improved too.

**Comment by mayantec** [comment]
For now, the content pack export/Edit/import seems to be the only way of doing so. Now hashes of Inputs and Streams seems to be preserved.

**Comment by nmaludy** [comment]
+1

**Comment by jekelundh** [comment]
+1

**Comment by kkplein** [comment]
+1
Strange this is missing

**Comment by Optimaximal** [comment]
+1

When you import a content pack but your stream doesn't match the one it's expecting, that's a lot of copying and pasting event/regexs into new widgets.

**Comment by 25-pixel** [comment]
+1 
It is very sad when 30 ready-made widgets need to be recreated due to the fact that it is impossible to edit the search query in the histogram

**Comment by skear** [comment]
Experiencing much frustration currently due to the lack of this feature.

**Comment by derehls** [comment]
+1

**Comment by uminac** [comment]
+1

**Comment by dennisoelkers** [comment]
This has been fixed in `3.1.0` by OSSing the views, which are now the default search in `3.2.0`.
