### ISSUE TITLE
Improve Documentation For log4j2.xml

### ISSUE THREAD

**Issue by rightisleft** [Graylog2/graylog2-server#3405]
When looking at bug #2996 - the actions do correct the error. However, Your documentation makes the assumption that you check the server prior to downloading the files.

http://docs.graylog.org/en/2.1/pages/installation/docker.html#settings

http://docs.graylog.org/en/2.1/pages/installation/docker.html#persist-log-data

**Comment by joschi** [comment]
This issue was moved to Graylog2/documentation#256
