### ISSUE TITLE
Save Search should include the selected Fields

### ISSUE THREAD

**Issue by ThomasSchoeller** [Graylog2/graylog2-server#3406]
a save search should include the selected fields.

Graylog 2.1.2+50e449a

Accourding to http://docs.graylog.org/en/2.1/pages/queries.html#saved-searches it should be possible to save the selected fields within the saved search. This is not working for me.

Any hints?

**Comment by edmundoa** [comment]
Hi,

This is a known issue, and as you can see in https://github.com/Graylog2/graylog2-server/issues/3071 it will be fixed in 2.2.0.
