### ISSUE TITLE
[Alert] Field content value condition: accepted expressions in "set to"

### ISSUE THREAD

**Issue by fermano** [Graylog2/graylog2-server#3407]
I'm trying to use an expression value in the "set to" field but it seems that only explicit values are accepted. In my case I'd like to use something like "any" value, or an equivalent regex. I've created different extractors that create the same field "create_jira_ticket", so I'd like to create an alarm for whenever the create_jira_ticket field exists. I couldn't find anywhere a definition of what are the possible values that can be used in the alert conditions.

This is not a bug I think, but it seems to me that it is unclear of what to use and where for the alert condition context. Should I use Lucene expression? Should I use grok? Should I use regex? Should I use only an explicit value? 

I apologize if this is a duplicate of any issue and appreciate any help.

Thanks in advance!
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by edmundoa** [comment]
Hi,

In 2.1.x there are two possibilities when you want to want to trigger an alert from a field:

- Use an explicit value, by choosing the Field content value condition
- Use an aggregation on a field with Field value condition

You can see more about alert conditions in http://docs.graylog.org/en/2.1/pages/streams/alerts.html#alert-condition-types-explained

Starting in 2.2, it will be possible to create new alert conditions via plugins, but out of the box there are no conditions that support regex, grok or similar. This is also kind of tricky, as the checks for alert conditions happen quite often and those expressions are usually expensive to compute, which may affect the performance badly.

I am not sure what you want to achieve exactly, but if all you want to do is to raise an exception when `create_jira_ticket` exist, you may as well add a value to that field, and then use a field content value condition to check for that value.

Please post any further questions to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
