### ISSUE TITLE
Widgets with keyword timerange cannot show trend

### ISSUE THREAD

**Issue by DerPhlipsi** [Graylog2/graylog2-server#3411]
## Expected Behavior

For a Dashboard, we want to display data separated by day. We use the keyword timeranges "from today midnight to tomorrow midnight" or "from yesterday midnight to today midnight" for example. The generated widgets work as expected and show correct results (e.g. Sum or Graphs). The trend arrows for widgets like sums should work properly by comparing the selected 24 hour timerange against the previous 24 hour timerange.

Best case it would work in a smart way and only compare already passed time. Example: 
"from today midnight to tomorrow midnight" This should compare today and yesterday. But it should only compare both days only until the current time, so if it is 13:46, it only compares yesterday 0:00 - 13:46 and today 0:00 - 13:46 to display accurate trends.
## Current Behavior

The trend arrows stay gray and do not display a trend. This would be a handy tool because it allows a quicker glance at the current day in comparison to the last day.
## Possible Solution

This is probably not implemented yet since the keyword timerage system would make this kind of calculations rather difficult (it contains more steps like calculating the current range, calculate the end of the range and then work out the reference timerange from there)
## Steps to Reproduce (for bugs)

1. Create any widget with the trend display and use some valid keyword timerange.
2. Go to the dashboard and be amazed by the shiny gray arrows :D
## Context

This is a minor thing and would only improve the "quickness" of reading the dashboard, since it is created for a wall mounted display in our hallway for a quick glance at today's situation in comparison to the last 3 days. With the arrows you wouldn't need to compare the numbers and could get the current situation by walking by instead of having to stop walking.

## Your Environment

* Graylog Version: Graylog 2.2.0-beta.6 (currently in a test-production'ish-phase, so it is fine for me to use the new beta-features)
* Elasticsearch Version: 2.4.4
* MongoDB Version: v3.2.9
* Operating System: RHEL 7
* Browser version: Firefox/50.1.0 Waterfox/50.1.0

**Comment by edmundoa** [comment]
Hi @DerPhlipsi,

Just want to add some information on this issue: trends are indeed only implemented for relative time ranges, as you can see (even if hard to find) in the documentation for the different widget types: http://docs.graylog.org/en/2.1/pages/dashboards.html#search-result-counts

**Comment by DerPhlipsi** [comment]
Hey @edmundoa ,

thanks for the feedback. I skipped the "with a relative time frame", oops :/
But nonetheless, this would be interesting. I want to start to actively develop Graylog Plugins or even Graylog itself, but this has second priority right now since I have to prepare my final project for my apprenticeship (which actually has Graylog as main topic :D ) That's why I'm not looking into it myself right now and filed this feature request.

**Comment by dennisoelkers** [comment]
Fixed in `3.2.0`.
