### ISSUE TITLE
Dashboard slideshow

### ISSUE THREAD

**Issue by marciofoz** [Graylog2/graylog2-server#3414]
I suggest a new feature: slideshow.

With this new feature, the user create a slideshow, add the dashboards to presentation and dashboards are displayed one after another at set intervals.

**Comment by rompic** [comment]
that is a good idea! we are currently using multiple tabs for that

**Comment by rlogan403** [comment]
How odd - I fully support this, we upgraded Grafana yesterday and it had this. Very nice.

**Comment by jalogisch** [comment]
currently we do not see the use case. This is out of our scope and in the wild are many browser plugins available that can do that for you.
