### ISSUE TITLE
Email subject prefix, from and name: defaults should get used?

### ISSUE THREAD

**Issue by rlogan403** [Graylog2/graylog2-server#3415]
When defining a notification for an alert, the values from the server.conf file are ignored (perhaps deprecated). 

Users cannot be expected to know all of these, for example, we like to prefix 'dev' or 'stage' or 'production' on the subject header, and the from email - an admin contact that varies for each of these.

Previous versions of Graylog let us programmatically alter these .. but this seems to be ignored now.
## Possible Solution

Reinstate the email transport config (examples):
transport_email_subject_prefix = [dev]
transport_email_from_email = dev_admin@bob.com
transport_email_from_name = graylog-dev-alerts

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 2.2.0 beta 6
* Elasticsearch Version: n/a
* MongoDB Version: n/a
* Operating System: n/a
* Browser version: na/

**Comment by joschi** [comment]
@rlogan403 Which version of Graylog have you been using before?

**Comment by rlogan403** [comment]
0.20.6, but as the config parameters are still in the server.conf in the 2.2.0 rpm, I assumed these were working - or meant to.

Otherwise, is there an API endpoint for creating these as defaults?

**Comment by joschi** [comment]
@rlogan403 That's quite a large version jump…

As a matter of fact, the prefix and sender settings from the configuration file have been deprecated some time ago and have no effect whatsoever.

There are no defaults to be set.

Refs Graylog2/documentation#259

**Comment by rlogan403** [comment]
Ok, Ill close this and add a feature request.

**Comment by rlogan403** [comment]
Ok, Ill close this and add a feature request.
