### ISSUE TITLE
MongoDB query for every batch flush in the Elasticsearch output

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#3433]
## Expected Behavior

The server should not query MongoDB for every batch flush in the Elasticsearch output.

## Current Behavior

The `BlockingBatchedESOutput` is calling `Cluster#isDeflectorHealthy()` for every batch flush in `BlockingBatchedESOutput#flush()`. (see [code](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/outputs/BlockingBatchedESOutput.java#L119))

In `Cluster#isDeflectorHealthy()` we call the following:

1. `Cluster#deflectorHealth()` - This calls `MongoIndexSetRegistry#getWriteIndexAliases()` which does a MongoDB query to find all index sets in the database.
2. `MongoIndexSetRegistry#isUp()` - This also does a MongoDB query to find all index sets in the database.

That means we are querying all index sets in MongoDB **twice** per ES output flush.

## Possible Solution

We might cache the list of index sets in the `MongoIndexSetService` and only refresh it when something is changed.

## Steps to Reproduce (for bugs)

1. Start Graylog server with a debugger
2. Set a breakpoint in `MongoIndexSetService#findAll()`
3. Watch the call hierarchy for triggered breakpoints

## Your Environment

* Graylog Version: 2.2.0-rc.1-SNAPSHOT 094a0ed0c

**Comment by dennisoelkers** [comment]
Fixed in #3440.
