### ISSUE TITLE
Restoring db leads to missing Reader role for ldap users

### ISSUE THREAD

**Issue by georgesakhnovsky** [Graylog2/graylog2-server#3436]
on a graylog server with ldap auth:

1. stop graylog server
2. dump db
3. do fresh graylog install on a new host
4. restore previously dumped db on the new host

## Expected Behavior

Roles and permissions are restored to what they were

## Current Behavior

Roles and permissions are not adequately being restored. Specifically the "Reader" role is no longer being auto-assigned as users log in, leading to issues like this:

https://github.com/Graylog2/graylog2-server/issues/2082

The following error is logged when entering the 3. LDAP/Active Directory section in Authentication Management:

2017-01-26T22:15:42.634Z ERROR [LdapSettingsImpl] Unable to load role mapping

A workaround that seems to work is using the "Save LDAP settings" button at the bottom of the 3. LDAP/Active Directory section without actually updating any settings, and having users re-login.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: v2.1.2+50e449a
* Elasticsearch Version:
* MongoDB Version: 3.4.1
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@georgesakhnovsky Have you been using a different [`password_secret`](https://github.com/Graylog2/graylog2-server/blob/2.1.3/misc/graylog.conf#L53-L55) in your new Graylog installation?

**Comment by georgesakhnovsky** [comment]
No @joschi the same. The entire config is identical.

**Comment by bernd** [comment]
This shouldn't be an issue anymore with 4.0. Please open a new issue if you still see the problem in 4.0. Thank you!
