### ISSUE TITLE
Form validation does not work when creating a dashboard on Safari

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#3441]
## Expected Behavior
The "description" field is mandatory for newly created dashboards. When leaving this out, the browser should notify the user that it needs to be entered. This works on Chrome & Firefox.

## Current Behavior
On Safari, when creating a new dashboard and leaving out a mandatory field, no form validation indicator pops up when clicking "Save".

## Steps to Reproduce (for bugs)

1. Use Safari
2. Click on "Dashboards"
3. Click on "Create dashboard"
4. Leave out any mandatory field.
5. Click "Save"

## Your Environment

* Graylog Version: 2.2.0-rc.1-SNAPSHOT
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version: 10.0.3

**Comment by edmundoa** [comment]
I think this is the same as #1942

**Comment by dennisoelkers** [comment]
True. Closing in favor of #1942.
