### ISSUE TITLE
Inconsistent search syntax

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog2-server#3442]
When performing searches we are getting inconsistent results, this looks to be related to the syntax used (or at least my understanding of it).

Example - we are ingesting IPS logs and one of the fields (ThreatID) holds the 'name' of the signature firing and its numeric identifier, example below:-

ThreatID: Metasploit to_exe.asp Template Generation Detection(32309)

I can search for this by performing a freeform search for: **Metasploit**
I can also search for this by searching within the field as: **ThreatID:32309**
However, logically (to me) if the above works this should also work, but does not: **ThreatID:Metasploit**
However, this does: ThreatID:***etasploit***

(note that we have enabled leading wildcard searches).

Rgds

Note: The autoformatting is screwing my examples above - the last one should be _etasploit_ with a leading and trailing *

**Comment by joschi** [comment]
@urban-moniker Please refer to http://docs.graylog.org/en/2.1/pages/queries.html#search-query-language for the documentation about the query syntax.

If "ThreadID: Metasploit" is part of another message field, you have to escape and quote it correctly, so that not only the `ThreadID` message field is being queried.

**Comment by urban-moniker** [comment]
Sorry, I have read the documentation, I'm not seeing what I'm doing wrong:-

ThreatID:32309 is triggering on the substring 32309 within the field, but ThreatID:Metasploit is not?

**Comment by joschi** [comment]
@urban-moniker You can check the message terms to see how the message field was indexed (message detail view &rarr; click on the button next to the magnifying glass of the field).

This being said, GitHub issues is the wrong place to discuss peculiarities of the Lucene query language. Please use IRC or Google Groups.
