### ISSUE TITLE
Storing collection of GELF messages

### ISSUE THREAD

**Issue by jruizaranguren** [Graylog2/graylog2-server#3443]
## Expected Behavior

A collection of GELF messages can be stored in a file as a JSON array, and imported directly from Graylog.

## Current Behavior

GELF specs define the GELF message format, but does not specify a collection of GELF messages for use in file storage.

## Possible Solution

A JSON array with GELF messages is a valid GELF message.
.
## Context

We are interested in generating structured logs using GELF format, but we might not be able to load them directly through (TCP/UDP) calls. So we plan to store them in files using GELF format, that will be loaded (from files) later to Graylog.

**Comment by joschi** [comment]
@jruizaranguren This is already possible with a Plaintext/Raw UDP or TCP input and the JSON extractor and/or some processing pipeline rules.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
