### ISSUE TITLE
Unable to access graylog running inside a virtual box from host

### ISSUE THREAD

**Issue by sridharchalimeti** [Graylog2/graylog2-server#3445]
## Expected Behavior
I would like to access the graylog weburl from outside of the virtualbox i.e. from host system etc
## Current Behavior
Unable to access web url appeared on the startup of the virtualbox from outside, i.e. from host sytem.

## Steps to Reproduce (for bugs)
1. Installed Oracle VirtualBox in mac os
2.Downloaded the graylog 2.1.2 ova file and imported using virtual box as mentioned in the documentation
3. Configured the static IP for virtualbox
4. restarted the virtualbox appleance.
5. Trying to access the web url displayed on startup from host system

## Context
With out resolving this issue, I can not configure the log source for further analyis

## Your Environment
* Graylog Version:2.1.2
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Mac OS 10X
* Browser version:

**Comment by joschi** [comment]
@sridharchalimeti We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
