### ISSUE TITLE
Read the access log

### ISSUE THREAD

**Issue by nicomilieris** [Graylog2/graylog2-server#3450]
Hi! I'm trying to read the access log in my Graylog account and I was wondering how I should do it!

Thanks!

**Comment by joschi** [comment]
@nicomilieris We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
