### ISSUE TITLE
Improve graylog rpm upgrade process on CentOS 7

### ISSUE THREAD

**Issue by tjyang** [Graylog2/graylog2-server#3452]
I was able to successfully upgrade from 2.1.2 to 2.1.3 with following graylog repo config.

```
[graylog]
name=graylog
baseurl=https://packages.graylog2.org/repo/el/stable/2.1/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-graylog
```
## Expected Behavior

yum upgrade -y graylog-server 

## Current Behavior

yum upgrade -y graylog-server 
systemctl daemon-reload
systemctl restart  graylog-server

## Possible Solution

adding daemon-reload and restart steps into spec file's postinstall 

## Steps to Reproduce (for bugs)
see above.

## Context

to automate further 

## Your Environment

* Graylog Version: graylog 2.1.2
* Elasticsearch Version: from graylog 2.1.2
* MongoDB Version:  from graylog 2.1.2
* Operating System: CentOS 7.3
* Browser version:

**Comment by bernd** [comment]
@tjyang Not restarting the server automatically was a deliberate decision. We also do not start the server automatically when you first install it.

Automatic starts/restarts can be problematic if you want to update the package but not restart until you are ready to do it. This comes at the cost of executing more commands to do an update, but is way more safe.

**Comment by tjyang** [comment]
what about "systemctl daemon-reload" command  ? can this be in postinstall script ?

**Comment by bernd** [comment]
@tjyang Do you know why this is needed?

**Comment by joschi** [comment]
@bernd It's required if systemd units have been updated.

**Comment by bernd** [comment]
@joschi Thanks. I guess that's okay to do automatically. I will fix this.
