### ISSUE TITLE
301 answer when trying to receive the messages in the access log

### ISSUE THREAD

**Issue by nicomilieris** [Graylog2/graylog2-server#3453]
I'm doing this request: curl -XGET -u user:password "http://11.44.999.777/search?rangetype=relative&fields=message%2Csource&width=1920&highlightMessage=&relative=28800&q=source%3Aapache%5C-access"

Expecting to receive as an answer the access log, but I obtain:

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.9.14</center>
</body>
</html>

**Comment by joschi** [comment]
@nicomilieris That's a message from nginx, not Graylog.

This being said, it's a problem with your `curl` command missing the `--location` or `-L` parameter.
