### ISSUE TITLE
Wrong export link

### ISSUE THREAD

**Issue by lchanouha** [Graylog2/graylog2-server#3455]
[Sorry for my english]

CSV export link is invalid

## Expected Behavior
When clicking on "Export as CSV" then download, a file should be downloaded

## Current Behavior
The generated download link is not an URI: eg.  
394db25e-9bd7-4490-a142-1ce675f91801:session@/api/search/universal/relative/export?query=%2A&range=300&filter=streams%3A5800b35a0cf215f995d99fa8&fields=source%2Cmessage

## Possible Solution
Correct the link with Graylog's installation FQDN and it works well, the file is dowloaded. Eg.
http://fqdn.fr/api/search/universal/relative/export?query=%2A&range=300&filter=streams%3A5800b35a0cf215f995d99fa8&fields=source%2Cmessa

## Steps to Reproduce (for bugs)
1. Go to a stream
2. Click on More Actions on the left pane
3. Click on Export on CSV
4. Click on the download link: nothing happen

## Context
I have SSO module configured on Graylog. I have the same issue connected with a local or SSO user.

## Your Environment

* Graylog Version: 2.2.0-rc1 (same problem on beta 6)
* Elasticsearch Version: not relevant
* MongoDB Version: not relevant
* Operating System: Debian 8 Jessie / Packaged Graylog version deb https://packages.graylog2.org/repo/debian/ stable 2.2
* Browser version: Chrome 55

```
rest_transport_uri = http://fqdn.fr:12900
web_endpoint_uri = https://fqdn.fr:443
rest_listen_uri = http://[public IP]:12900/
```

My Apache conf file looks like
```
<VirtualHost *:443>
        ServerName fqdn.fr
        ProxyRequests Off
        <Proxy *>
            Order deny,allow
            Allow from all
        </Proxy>
        <Location />
            RequestHeader set X-Graylog-Server-URL "/api/"
            ProxyPass http://127.0.0.1:9000/
            ProxyPassReverse http://127.0.0.1:9000/
                CASAuthNHeader CAS-USER
                CASScrubRequestHeaders On
                AuthType cas
                Require valid-user
                CASCookie comue_cas

        </Location>
        <Location /api/>
            ProxyPass http://[public IP]:12900/
            ProxyPassReverse http://[public IP]:12900/
        </Location>
        CASAttributePrefix CAS-
        Header set Strict-Transport-Security "max-age=15552001"
        SSLEngine On
        SSLCertificateFile    X
        SSLCertificateKeyFile Y
        SSLCertificateChainFile Z
</VirtualHost>
```

Thank you for investigation
Regards,
Louis Chanouha
University Of Toulouse

**Comment by joschi** [comment]
@lchanouha The `X-Graylog-Server-URL` request header has to contain a fully qualified domain name (FQDN), e. g. `https://fqdn.fr/api/` in your case.

**Comment by lchanouha** [comment]
OK it works now. But I don't understand why a full FQDN is needed for theses links.
Thank you for your reactivity.

**Comment by joschi** [comment]
@lchanouha Because that URL is being used to construct other URLs throughout Graylog. That's why it's called X-Graylog-Server-***URL*** and not X-Graylog-Server-***Path***.

Thanks for the feedback!

**Comment by gaieges** [comment]
@joschi - I ran into this issue too .. can I ask why you don't infer that from the page that the browser is on?

**Comment by joschi** [comment]
@gaieges Because the Graylog REST API can run on a completely different host or use a completely different URI than what the Graylog web interface is using (especially if behind a reverse proxy rewriting URIs internally).

**Comment by gaieges** [comment]
I see.  Wouldn't a good default behavior be to infer the api location, and have users override that location if they break apart the api from the web location? 

I'm sure you guys did what you did on purpose, just wondering.
