### ISSUE TITLE
Unable to update, delete or modify Aggregate (plugin) rule

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog2-server#3457]
We are using GL 2.2rc1 with the aggregates plugin and have half a dozen aggregate rules.

One of these cannot be modified - if we try to edit, delete ot disable we get the popup error as below:-

Could not update rule
Updating rule failed with status: cannot POST http://xxx.xxx.xxx.xxx:9000/api/plugins/org.graylog.plugins.aggregates/rules/Repeated%20IDS/IPS%20ThreatID%20Alerts (404)

It looks as if the "\" in the rule name i.e. in the portion "IDS\IPS" was allowed during rule creation but is now being interpreted as a URL character etc.

If correct, this character should be rejected\stripped from the name during creation.

For ourselves, unless this can be done retrospectively we will also need to delete from the config manually (assume by issuing a MongoDB command etc).

**Comment by joschi** [comment]
@urban-moniker Please file a bug report in the repository of the Aggregates plugin: https://github.com/cvtienhoven/graylog-plugin-aggregates/issues

**Comment by urban-moniker** [comment]
Thanks for moving!
