### ISSUE TITLE
User Not authorized. (GET streams/alerts/)

### ISSUE THREAD

**Issue by bert2002** [Graylog2/graylog2-server#3458]
## Expected Behavior
When a user logs in he should see the All stream and can start browsing. 

## Current Behavior
When a user logs in, it shows the log entries for a second and then tries to load https://graylog.srv.company.com:12901/streams/alerts/?since=1486040700 and it fails with following error message:
```
{
{ type: "ApiError", message: "User [user.name] not authorized. (GET streams/alerts/)" }
}
```

## Context
The user has access to Graylog and can open all Streams (including All) when it navigates from Search to Streams. User authentication is LDAP. I already removed the user and it got recreated, but the problem is persistent. 
The problem does not occur for an user with admin rights. 

## Your Environment

* Graylog Version: 2.1.3 (same problem with 2.1.2)
* Elasticsearch Version: 2.4.0
* MongoDB Version: 3.2.7
* Operating System: CentOS release 6.8
* Browser version: Chrome 52.0.2743.82 and 56.0.2924.76-1

**Comment by bernd** [comment]
@bert2002 Thank you for the report! I am able to reproduce this.

When a LDAP user logs into the Graylog UI, we update the user's data from the LDAP to ensure that the database entry in Graylog is up to date. This seems to overwrite the user roles and thus removes access to the streams.

**Comment by bernd** [comment]
@bert2002 Okay, this was a confusion on my part. This isn't really a bug if you are using LDAP groups.

Are you using LDAP groups in your Graylog setup?

If LDAP groups are in use, Graylog will overwrite all manually assigned roles on login. This is intentional to ensure correct LDAP group behavior.

**Comment by bert2002** [comment]
Hi @bernd, yes I am using LDAP groups and the mapping is accordingly configured in Graylog. If I can dump this somehow for you to see, let me know. 

Is there some special permission for streams/alerts/?

**Comment by bernd** [comment]
@bert2002 Okay, do you assign the role that allows access to the stream manually on the user's page, or is that done automatically via the group mapping?

**Comment by bert2002** [comment]
Its done automatically via the LDAP group mapping. We have a Developer Group which is mapped to a Role that has access to the stream "All" with "Allow reading" attribute.

**Comment by bert2002** [comment]
Hi @bernd any other ideas or you need some more data to get an idea whats going on here?

**Comment by bert2002** [comment]
Upgraded to 2.2.1 and problem solved. No idea...
