### ISSUE TITLE
Collector not showing all data from file

### ISSUE THREAD

**Issue by daac87** [Graylog2/graylog2-server#3461]
when i look at the messages coming in they are cut half way... this is probably me not knowing what im doing...im using windows 2012 r2 DNS server...

Example of messge cropped: 
2/2/2017 5:39:44 PM 04C0 PACKET  000000A10C5841D0 UDP Rcv 75.75.

* Graylog Version: 2.1.3 OVA
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by jalogisch** [comment]
@daac87 you include no Information that would give us the possibility to help you. How did you transport the messages from your system over to Graylog. What did you do with them inside of Graylog.

Anyway we are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
