### ISSUE TITLE
Graylog server always collect expired logs, these logs are generated long before , and now the switch has no such logs.

### ISSUE THREAD

**Issue by wayneshow** [Graylog2/graylog2-server#3464]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 1.3.4
* Elasticsearch Version: 1.7.6
* MongoDB Version: mongodb-org-3.2.11
* Operating System: centos 6.5
* Browser version: chrome

Graylog server always collect expired logs, these logs are generated long before , and now the switch has no such logs.
![image](https://cloud.githubusercontent.com/assets/24647716/22615473/4bef9a9a-ead0-11e6-9fc6-16e97d29dc70.png)

The current log's source is 2017, The log whose source is G1-K115-ACC-SW-48  is very early, but the server is collecting now. 

This problem has troubled me for weeks. How to solve this problem?

**Comment by joschi** [comment]
@wayneshow We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
