### ISSUE TITLE
Install from scratch, not working on Debian 8

### ISSUE THREAD

**Issue by Lecraver** [Graylog2/graylog2-server#3465]
Hi,

i installed a Debian 8 OS from scratch with Linux Plesk.
i followed this guide :
http://docs.graylog.org/en/2.1/pages/installation/os/debian.html
But it's still not working. You can see on the image Mongodb and elasticsearch seems to be good but not graylog. 
Is it because of the java version ? I was unable to install version 8 so I installed the 7.

![image](https://cloud.githubusercontent.com/assets/17044641/22643425/b28ee1ae-ec5e-11e6-8f87-a911b330e544.png)

Thank you for helping me !

## Your Environment

* Graylog Version: 2.1
* Elasticsearch Version: 2.x
* MongoDB Version: Last
* Operating System: Debian 8
* Browser version: /

**Comment by bernd** [comment]
Graylog requires Java 8 and will not run with Java 7, sorry. The installation guide also mentions that `openjdk-8-jre-headless` should be installed. That should work on Debian 8 if you follow all instructions on that page.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
