### ISSUE TITLE
Graylog 2.1.2 - Unable to load quick values

### ISSUE THREAD

**Issue by TechGuy10** [Graylog2/graylog2-server#3466]
Hi,

I'm unable to use quick values, I'm getting the following error:
"Could not load quick values
Loading quick values failed with status: Error: cannot GET http://<Server IP>:9000/api/search/universal/relative/terms?query=%22Risk%20name%3A%20WS.Reputation.1%22&range=1209600&field=message (500)"

![image](https://cloud.githubusercontent.com/assets/25608351/22687932/ba6a1fa4-ed32-11e6-855c-f188761f47a3.png)

Please advise.

* Graylog Version: 2.1.2 (The issue persist in version 2.1.3)
* Elasticsearch Version: Don't know
* MongoDB Version: Don't know
* Operating System: win10 x64
* Browser version: FF 51.0.1

**Comment by edmundoa** [comment]
Hi,

Asking for quick values on the message field over the last 14 days is going to take a long time, and most likely putting your ES cluster under a lot of stress, thus the 500 error. What are you trying to achieve?

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please add any further questions to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by TechGuy10** [comment]
Hi,

That's what you see in the screenshot, but it actually doesn't work even for 5 minutes.

![image](https://cloud.githubusercontent.com/assets/25608351/22688943/1e8b3e06-ed37-11e6-8b4b-de7ed46ce32e.png)

So, what do you say?
Is it a bug?

**Comment by edmundoa** [comment]
I don't think it is a bug, otherwise we would have lots of issues opened with this same problem, but send us your Graylog server logs and let's see what we can find in there.

By the way, what are you trying to achieve with that query and how did you install Graylog?
