### ISSUE TITLE
Graylog 2.1.2 - Geo-Location

### ISSUE THREAD

**Issue by TechGuy10** [Graylog2/graylog2-server#3467]
Hi,

I followed http://docs.graylog.org/en/2.0/pages/geolocation.html#configure-geolocation in order to apply the Geo-Location feature.
I tested it with  nc -w0 <graylog_host> 5555 <<< '8.8.8.8' and it worked.

![image](https://cloud.githubusercontent.com/assets/25608351/22688584/9b66a9b2-ed35-11e6-9a92-4c92010353cd.png)

I don't see another logs with "message_geolocation" , even though the database path is configured.

![image](https://cloud.githubusercontent.com/assets/25608351/22688675/f612eaa6-ed35-11e6-9b5b-1fca45d51905.png)

In addition, it's also activate in Message Processors Configuration.

![image](https://cloud.githubusercontent.com/assets/25608351/22688707/208d28b4-ed36-11e6-9572-96583bed303e.png)

Please advise.

* Graylog Version: 2.1.2 (Running on CentOS 7)
* Elasticsearch Version: Don't know
* MongoDB Version: Don't know
* Operating System: win 10 x64
* Browser version: FF 51.0.1

**Comment by joschi** [comment]
@TechGuy10 We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
