### ISSUE TITLE
Wording "edit stream" remove matches from all message stream

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#3471]
## Expected Behavior
![graylog_-_streams](https://cloud.githubusercontent.com/assets/404238/22736733/fc0abad6-edff-11e6-9bd3-8ec4438857e7.png)

When you edit/create a stream and mark "Remove matches from 'All messages' stream" with the current wording I would assume that the messages are not displayed when selecting the "All messages" stream.

## Current Behavior
Currently the messages are still shown in the "All messages" stream but the messages are not stored in the index that is used for the Stream storage.

## Possible Solution
Rework the wording in the message that is visible to the customer.

"Remove messages that match this stream from the 'All messages' stream and do not store them in the default index that is defined for this index. By default every message is assigned and stored in the 'All messages' Stream."

## Context
As this is a new feature we need to be careful with the wording to guide the users.

## Your Environment
* Graylog Version: 2.2.rc1

**Comment by jalogisch** [comment]
when routing messages via pipeline the default 'all messages' is not removed.

That is why I thought this wording was wrong - checked with a stream where the messages got in because of a stream rule and the 'all messages' is removed correct.

**Comment by chrisminett** [comment]
Just ran into this same issue. It seems the wording is still not correct (or maybe the placement of the option is wrong). As the option is part of the stream config, I assumed it would apply to all messages routed to the stream, regardless whether that was via message filter or pipeline.

Perhaps it would be good to clarify the option only applies to messages that match stream rules, and even better, move the option to the stream rules config page.

**Comment by jalogisch** [comment]
@chrisminett 

for clarification:

- if a messages is routed to the stream because of a stream rule the setting "remove from all messages" work as the everyone would think it work.

- if a message is routed by a pipeline to the default is not remove as because of missing *remove_from_stream* function in processing pipelines ( https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/117 ) and the message will be present in default and the additional stream.

**Comment by chrisminett** [comment]
Yup, that's the behaviour.

And because of this, I think it might be a good idea to clarify the wording (or placement) so it's clear the option only applies to messages via stream rules, unlike a general setting like *index set* which applies to messages via pipelines too.

**Comment by joschi** [comment]
@chrisminett I still don't see where you're trying to get at.

Messages routed into a stream with the "Remove matches from 'All messages' stream" setting enabled will be removed from the 'All messages' stream. If a message is not routed into the stream, it's not removed (at least not because of that specific stream).

**Comment by jalogisch** [comment]
@joschi the point that @chrisminett see is that with the current graylog version you can route a message by a stream rule into a stream and by pipeline.

the "not that deep in graylog internals" user does not know that both are fundamental other functions within graylog and are used at different stages of message processing. For the user this check box removes the messages from default stream - without any exception.
