### ISSUE TITLE
HTTP GELF endpoint returns 415 when specifying a charset in the Content-Type header 

### ISSUE THREAD

**Issue by rscullin** [Graylog2/graylog2-server#3477]
When posting to a HTTP GELF endpoint and specifying a charset in the Content-Type header ( `application/json; charset=UTF-8`), Graylog returns a HTTP 415. This seems to be a breaking change as of Graylog 2.2 (`Graylog 2.2.0+d9681cb`); Graylog 2.1 (`Graylog 2.1.3+040d371`) doesn't exhibit this issue.

We are using [Arebis.Logging.GrayLog](https://github.com/codetuner/Arebis.Common/tree/master/Arebis.Logging.GrayLog) in our .NET code, which automatically generates the headers and posts to Graylog via HTTP GELF.

## Expected Behavior
I expect Graylog to accept the message, as it did in 2.1.

## Current Behavior
Graylog responds with a HTTP 415 Unsupported Media Type.

## Possible Solution
Accept valid Content-Type headers.

### To Repro on Graylog 2.2
`Graylog 2.2.0+d9681cb on graylog (Oracle Corporation 1.8.0_101 on Linux 3.13.0-107-generic)`

```
ubuntu@graylog:~$ curl -i -XPOST http://10.2.2.1:12201/gelf -H "Content-Type: application/json; charset=UTF-8" -p0 -d '{"short_message":"Hello there", "host":"example.org", "facility":"test", "_foo":"bar"}'
HTTP/1.0 415 Unsupported Media Type
Content-Length: 0
Connection: close
```

### Unable to Repro on Graylog 2.1.3
`Graylog 2.1.3+040d371 on graylog (Oracle Corporation 1.8.0_101 on Linux 3.13.0-88-generic)`
```
ubuntu@graylog:~$ curl -i -XPOST http://10.2.1.3:12201/gelf -H "Content-Type: application/json; charset=UTF-8" -p0 -d '{"short_message":"Hello there", "host":"example.org", "facility":"test", "_foo":"bar"}'
HTTP/1.0 202 Accepted
Content-Length: 0
Connection: close
```

## Context
With this change to Graylog 2.2, we are unable to ingest log messages from our .NET Clients. We can modify the logging library locally, but this seems like a bug in Graylog's handling of HTTP requests rather than a bug in the client logging library.

## Your Environment
See above.

**Comment by nathanashton** [comment]
Experiencing the same issue on GrayLog 2.2

Returns a 415 error when Content-Type is specified as application/json;charset=utf-8

**Comment by ccapndave** [comment]
We are also experiencing this problem in our application, which uses the Fetch API in the browser to send GELF messages to Graylog (using https://github.com/ccapndave/grayconsole).  This is a bit of a showstopper for us as `fetch` automatically adds a `content-type` which means that we can't do any logging at all.
