### ISSUE TITLE
Swagger interface does not work with AWS appliance

### ISSUE THREAD

**Issue by drinkyouroj** [Graylog2/graylog2-server#3478]
## Expected Behavior

When accessing the Swagger API browser, clicking on links should do something ("Show/Hide" methods, "List Operations," etc.)

## Current Behavior

Clicking any of the links (besides the "Raw" links) on the page does not appear to do anything (besides change the text color to black). Clicking "Raw" either produces an internal server error, or returns a JSON-formatted response, depending on the method. Clicking Raw next to any method that does not require parameters appears to produce the JSON output; methods requiring a parameter (like `Cluster/Node/Metrics`) produce the Internal Server Errors.

## Steps to Reproduce (for bugs)

1. Install Graylog following the documentation here: http://docs.graylog.org/en/2.1/pages/installation/aws.html
2. Configure system using `graylog-ctl` script and `graylog-settings.json`.
3. Open the REST API browser page.
4. Click around; nothing happens.

## Context

We are trying to use the API browser to assist with building external scripts that will access Graylog data via the API.

## Your Environment

> root@aws-gravux01:~# cat /etc/graylog/graylog-settings.json
> {
>   "timezone": "America/Los_Angeles",
>   "smtp_server": "email-smtp.us-west-2.amazonaws.com",
>   "smtp_port": 587,
>   "smtp_user": "XXXXXXXXXXXXXXX",
>   "smtp_password": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
>   "smtp_from_email": "graylog@example.com",
>   "smtp_web_url": "https://graylog.example.com",
>   "smtp_no_tls": false,
>   "smtp_no_ssl": true,
>   "master_node": "127.0.0.1",
>   "local_connect": false,
>   "current_address": "172.30.0.189",
>   "last_address": "172.30.0.189",
>   "enforce_ssl": true,
>   "journal_size": 1,
>   "node_id": "296c16ef-c67a-4e05-b1e0-763897135704",
>   "internal_logging": true,
>   "web_listen_uri": "http://127.0.0.1:9000/",
>   "web_endpoint_uri": false,
>   "rest_listen_uri": "http://127.0.0.1:9000/api",
>   "rest_transport_uri": "https://graylog.example.com/api",
>   "external_rest_uri": "https://graylog.example.com/api",
>   "custom_attributes": {
>     "graylog-server": {
>       "memory": "1800m"
>     },
>     "elasticsearch": {
>       "memory": "4400m"
>     }
>   }
> }

This is all running on an EC2 T2.Large instance, with an Elastic IP mapped.

* Graylog Version: 2.1.2+50e449a
* Elasticsearch Version: 2.1.2
* MongoDB Version: 2.4.9
* Operating System: Ubuntu 14.04.5 LTS
* Browser version: tried current versions of Chrome, Firefox, and Microsoft Edge - all behave the same way.

**Comment by jalogisch** [comment]
@drinkyouroj 

we had fixed some issues with the swagger access and behavior. please update to the latest graylog version and reopen the issue if the problem is still present.

**Comment by drinkyouroj** [comment]
I've updated to the latest graylog version (v2.2.0+d9681cb) according to the instructions located at http://docs.graylog.org/en/2.2/pages/configuration/graylog_ctl.html#upgrade-graylog. The upgrade was successful, but I'm seeing the same behavior in the API Browser as I was seeing before the upgrade.

**Comment by drinkyouroj** [comment]
@jalogisch Please let me know if my comment (above) is enough to "reopen" this ticket, or if I should create a new issue with the updated version information. Thanks!

FWIW, I tried creating an entirely new Graylog instance using the us-west-2 AMI (ami-d5cc48b5) and still see the same behavior.

**Comment by joschi** [comment]
@drinkyouroj Are there any error or warning messages in the Javascript console of your web browser when opening and using the API browser?

https://developers.google.com/web/tools/chrome-devtools/console/
https://developer.mozilla.org/en-US/docs/Tools/Web_Console

**Comment by drinkyouroj** [comment]
@joschi Yes, when I load the page there are a number of errors in the console. I've attached the output from Chrome 56.0.2924.87 (64-bit) on page load. (Warning: the file has unix-style line terminators.)
[graylog.allstardirectories.com-1487096853399.txt](https://github.com/Graylog2/graylog2-server/files/774986/graylog.allstardirectories.com-1487096853399.txt)
When I click around on the page (except for the "Raw" links), the console does not produce any additional output. The "Raw" links always produce an Internal Server Error (if a parameter is required -- e.g., `cluster/node/metrics`), or a response (if no parameter is required - e.g., `cluster/metrics`). Neither type of "Raw" link produces any output in the console.

**Comment by joschi** [comment]
@drinkyouroj This looks related to #3290. Please upgrade to Graylog 2.2.0 and check if the problem persists.

**Comment by drinkyouroj** [comment]
@joschi I upgraded to v2.2.0+d9681cb prior to [this](https://github.com/Graylog2/graylog2-server/issues/3478#issuecomment-279488663) comment and was running that version when I sent over the console output yesterday.

**Comment by drinkyouroj** [comment]
I've upgraded to the latest version (and tried a fresh install from the AMI) and the problem still persists, so I've opened a new issue: https://github.com/Graylog2/graylog2-server/issues/3519
