### ISSUE TITLE
Stream time retention

### ISSUE THREAD

**Issue by ali2night** [Graylog2/graylog2-server#3481]
I want to know if there is any way to increase the retention time for graylogs streams ? 
I use graylog docker image 
Thanks in advance

**Comment by joschi** [comment]
@ali2night Please refer to http://docs.graylog.org/en/2.2/pages/configuration/index_model.html for details about the configuration of Graylog index sets (which are responsible for how messages are stored in Elasticsearch).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
