### ISSUE TITLE
Copy query button does not work

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#3491]
On Graylog 2.2.0, opening the show query modal dialogue and clicking on "Copy query" is not working as expected. This problem is not happening in all copy to clipboard buttons, the one copying the message ID is working.

## Expected Behavior
Clicking on "Copy query" should copy the ES query to the clipboard.

## Current Behavior
Clicking on "Copy query" does not copy anything to the clipboard.

## Steps to Reproduce (for bugs)
1. Open search page
2. Click on _More actions_ -> _Show query_
3. Click on _Copy query_
4. See that the query was not copied to your clipboard

## Your Environment
* Graylog Version: 2.2.0
* Operating System: macOS and Linux
* Browser version: Latest Firefox and Chrome. The issue cannot be reproduced in Safari, though.

**Comment by dennisoelkers** [comment]
Fixed in #3548
