### ISSUE TITLE
Graylog server 2.2 installation is failing with deb package

### ISSUE THREAD

**Issue by rohit01** [Graylog2/graylog2-server#3496]
I maintain a graylog docker image: <https://hub.docker.com/r/rohit01/graylog>
Build is failing for version 2.2. Failure link: <https://hub.docker.com/r/rohit01/graylog/builds/b8jvxvahkmn4fjftlzvvsza/>
Error message while trying it manually. The deb package is not getting installed:
```
# apt-get install -f
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up graylog-server (2.2.0-11) ...
Failed to get D-Bus connection: Unknown error -1
dpkg: error processing package graylog-server (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 graylog-server
E: Sub-process /usr/bin/dpkg returned an error code (1)
#
```

## Expected Behavior

Build should succeed.

## Current Behavior

Installation failure.

## Possible Solution

Maybe some dependency got added which is causing the issue.

## Steps to Reproduce (for bugs)

1. Build docker image: <https://github.com/rohit01/graylog-docker>

## Context

Unable to upgrade to latest version.

**Comment by joschi** [comment]
@rohit01 I'm sorry, but we cannot support custom builds of Graylog.

If you want to run Graylog in a Docker container, please use the official Docker image: https://hub.docker.com/r/graylog2/server/

You can also take a look at https://github.com/Graylog2/graylog2-images/tree/2.2/docker for the relevant sources.

**Comment by rohit01** [comment]
@joschi Agree, but I am asking for help with the debian package of graylog. All I am doing is `dpkg -i graylog-2.2-repository_1-5_all.deb` and then `apt-get install -y graylog-server`.

Rest everything is custom configuration support. I did the debugging but the error message does not look obvious. Give me some pointers, if something changed. I don't like to see the outdated graylog message on my graylog clusters :p

**Comment by jalogisch** [comment]
@rohit01 

that is working on a fresh VM without any issues.

as @joschi already wrote, we do not support custom builds. This is not an issue with the debian package.

**Comment by joschi** [comment]
@rohit01 Try using a proper installation of Ubuntu Linux and not some arbitrarily slimmed down version in your Docker image.

This being said, if you have other questions, please use the other community support channels: https://www.graylog.org/community-support

**Comment by rohit01** [comment]
@joschi Sure, thanks for the quick replies.

Meanwhile, I raised a PR to help myself use the official graylog docker images: https://github.com/Graylog2/graylog2-images/pull/184

I created my image long back when I was not aware of official docker images. I would really appreciate if you could review the changes. I was not able to test the builds (looks like it requires AWS access keys or role based access).

**Comment by rohit01** [comment]
@jalogisch, @joschi: I tried base image as debian, but the error message remained same: 
https://hub.docker.com/r/rohit01/graylog/builds/bi57phksn6k4kezxjjzbtjn/

Just FYI. I am now planning to use the official images.

**Comment by jalogisch** [comment]
@rohit01 when you look at our guides: http://docs.graylog.org/en/2.2/pages/installation/os/debian.html and compare your installed software java is missing ...
