### ISSUE TITLE
Import of Content Packs fails

### ISSUE THREAD

**Issue by ToeiRei** [Graylog2/graylog2-server#3510]
## Expected Behavior

I'd expect the import to work

## Current Behavior

Import button does nothing. 

JS Console shows:
```
plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.3256fc6….js:152Uncaught TypeError: Cannot read property 'forEach' of undefined
    at t.import (https://graylog/assets/plugin/org.graylog.plugins.pipelineproc…pipelineprocessor.PipelineProcessorPlugin.3256fc68b6ac83634199.js:152:8198)
    at r.n (https://graylog/assets/vendor.js:46:10756)
    at r.emit (https://graylog/assets/vendor.js:39:22180)
    at Function.trigger (https://graylog/assets/vendor.js:46:11633)
    at https://graylog/assets/vendor.js:46:11737
    at t.exports (https://graylog/assets/polyfill.72a3039d895480dcd0ed.js:1:18590)
    at y.(anonymous function) (https://graylog/assets/polyfill.72a3039d895480dcd0ed.js:1:25208)
    at Number.g (https://graylog/assets/polyfill.72a3039d895480dcd0ed.js:1:25066)
    at MessagePort.b (https://graylog/assets/polyfill.72a3039d895480dcd0ed.js:1:25088)
import	@	plugin.org.graylog.plugins.pipelineprocessor.PipelineProcessorPlugin.3256fc6….js:152
n	@	vendor.js:46
r.emit	@	vendor.js:39
trigger	@	vendor.js:46
(anonymous)	@	vendor.js:46
t.exports	@	_invoke.js:5
y.(anonymous function)	@	_task.js:31
g	@	_task.js:19
b	@	_task.js:23
```

## Steps to Reproduce (for bugs)

1. Log into Graylog
2. Go to System/Inputs
3. Select an Input
4. Manage Extractors
5. Import Extractor
6. Use JSPN from https://github.com/Graylog2/graylog-contentpack-nginx
7. Press "Add extractors to input"
8. Scratch your head and look clueless
9. Use "inspect" in your browser to get to the JS debugging console and look at the output there

## Your Environment

* Graylog Version:  2.2.0+d9681cb
* Elasticsearch Version: 2.4.4
* MongoDB Version: 2.4.10-5
* Operating System: Debian 8 / x86_64 GNU/Linux
* Browser version:  Chrome 56.0.2924.87

**Comment by edmundoa** [comment]
Hi @ToeiRei,

You are not using the right form to import the content pack. Please go to _System -> Content packs_, from where you should be able to import the content pack you downloaded from the Graylog Marketplace.

Please comment on the issue if you still have problems after using the right page for the import, or feel free to contact us in our [discussion forum](https://community.graylog.org/) or the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog) if you need any help.

Thank you!

**Comment by ToeiRei** [comment]
Hi @edmundoa,

System / Content packs does not allow me to import things. All I see is my content packs imported back then a few versions ago.

![image](https://cloud.githubusercontent.com/assets/5990591/23023867/d00868f8-f457-11e6-9b97-b222849a8e86.png)

**Comment by ToeiRei** [comment]
never mind. I was a blind.
