### ISSUE TITLE
JSON Extractor Separator Change Does Not Take Affect After It Has Been Set for Field

### ISSUE THREAD

**Issue by sre-jon** [Graylog2/graylog2-server#3512]
## Expected Behavior

When I edit a JSON extractor that is configured to use "_" as the separator, I should be able to change the separator to "." and have the new separator appear in search results.

## Current Behavior
I originally experienced the issue on 2.0.3, but it is also happening on 2.1.3. I created a json extractor for a field and used a separator of "_". I then wanted to change the separator to ".", so I edited the extractor and saved the separator as "." (I see that this "." is sent to the server by my browser and I see that the extractor is configured with the "." in mongodb), however search results always show the "_" as the separator. I have tried deleting the extractor and recreating with "." as the separator and the "_" is still used for the separator. I have tried deleting the extractor, cycling the deflector, then creating the extractor again with "." as the separator, but the "_" is still used. I have tried creating an extractor that copies the original field to a new field, then creating a json extractor on the new copied field, and still no luck.

## Steps to Reproduce (for bugs)

1. Create a JSON Extractor for a field.
2. Use "_" as the separator.
3. View the "_" appears as the separator in search results.
4. Edit the extractor, change the separator to ".".
5. View the "_" separator is still used in search results.

## Context

We want to standardize the queries that we write, (and we have key names with underscores in the names, so it makes it hard to read when underscores are used for separators), but we created some extractors with _ separators as tests and have not been able to change them.

## Your Environment

* Graylog Version: 2.1.3
* Elasticsearch Version: 2.3.3-1 
* MongoDB Version:3.2.7-1.el7   
* Operating System: CentOS Linux release 7.2.1511 (Core)
* Browser version: chrome 52.0.2743.116 (64-bit) on mac osx

**Comment by jalogisch** [comment]
the 2.x version of elasticsearch does not allow dots in fields name ( https://www.elastic.co/guide/en/elasticsearch/reference/2.4/dots-in-names.html#dots-in-names )

Please see this issue as reference: https://github.com/Graylog2/graylog2-server/issues/2939

**Comment by kvrobert** [comment]
Hi,
I would like to use this functionality, instead of "_" using "." as key separator in JSON parser to build nested field in elasticsearch. I'm using graylog 2.5 but I have the same behavior also. If I change the separator form "_" to "." and I push the "try" button in the extractor editor I become the correct valaues with "." separated field, but under the search menu it use again the "_" separator. How can I cange this behavior? It is possible to change?
Thank you for the help!
