### ISSUE TITLE
Graylog 2.2 with ssl and behind nginx returns : Error: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

### ISSUE THREAD

**Issue by thlclr** [Graylog2/graylog2-server#3514]
After a new install of graylog, i'm trying to access the web interface t thru a public IP and the following error message is returned:

rror message
Bad request
Original Request
GET http://127.0.0.1:9000/api/system/sessions
Status code
undefined
Full error message
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

## Expected Behavior
Full acess of a working web frontend

## Current Behavior
Full error message
Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.

## Possible Solution
-

## Steps to Reproduce (for bugs)
**1- Graylog Configuration:**
```
is_master = true
node_id_file = /etc/graylog/server/node-id
rest_listen_uri = http://127.0.0.1:9000/api/
web_listen_uri = http://127.0.0.1:9000/

web_tls_cert_file = /etc/nginx/ssl/fullchain.pem
web_tls_key_file = /etc/nginx/ssl//privkey.pem
web_tls_key_password = secret
```

**NGINX configuration:**
```
server {
    listen 443 ssl default deferred;
    server_name  <externalip>;

    include /etc/nginx/conf.d/settings.conf;
    access_log  /var/log/nginx/graylog.access.log  main;

    location / {
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    Host $host;
        proxy_set_header    X-Graylog-Server-URL http://127.0.0.1:9000/api;
        proxy_pass          http://127.0.0.1:9000;
    }
}
```
* Graylog Version: 2.2.0-11
* Elasticsearch Version: 2.4.4-1
* MongoDB Version: v3.2.12
* Operating System: Centos 6
* Browser version: Chrome Version 56.0.2924.87

**Comment by joschi** [comment]
@thlclr Your `X-Graylog-Server-URL` (or `web_endpoint_uri`) is wrong. It has to be the *public* URI of the Graylog REST API, so probably `https://<externalip>/api` in your case.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
