### ISSUE TITLE
wrong sha1 in OVA for graylog 2.2.0-1 donwload

### ISSUE THREAD

**Issue by TiNico22** [Graylog2/graylog2-server#3516]
THe OVA downloaded at https://packages.graylog2.org/releases/graylog-omnibus/ova/graylog-2.2.0-1.ova has an error when importing the OVA (vmplayer)

## Expected Behavior

No trouble during import (no issue with the 2.2.0-beta5 using the same method to import)
## Current Behavior

Error while converting to a virtual machine: SHA1 digest of file graylog-disk1.vmdk does not match manifest.

## Steps to Reproduce (for bugs)

1. download the 2.2.0-1 OVA
2. import in vmplayer 7
3.
4.

## Your Environment

* Graylog Version: 2.2.0
* Elasticsearch Version:
* MongoDB Version:
* Operating System: OVA imported in vmplayer 7.1.4
* Browser version:

**Comment by joschi** [comment]
This issue was moved to Graylog2/graylog2-images#185
