### ISSUE TITLE
Syslog input format 

### ISSUE THREAD

**Issue by mrdun** [Graylog2/graylog2-server#3518]
Hi everyone.

We're using rsyslog and string based RFC5424 [template](http://www.rsyslog.com/doc/v5-stable/configuration/templates.html#string-based-templates) configured similarly to described in the [guide](https://github.com/Graylog2/graylog-guide-syslog-linux).
After upgrade to the latest version syslog input has stopped to parse logs based on template GRAYLOGRFC5424. If this template has removed - messages can be found again in Graylog search but they were parsed incorrectly (no fields application_name, level etc..).
We're also using few other inputs based on syslog and custom extractors but only plain syslog has got the issue.

## Steps to Reproduce

1. Add syslog UDP input.
2. Configure rsyslog accordingly to the [guide](https://github.com/Graylog2/graylog-guide-syslog-linux).
3. Try to find messages in Graylog search.
4. Remove template from rsyslog configuration and now messages can be found.

## Environment

* Graylog Version: Graylog 2.2.0+d9681cb
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.2.12
* Operating System: Oracle Linux Server release 7.3
* rsyslog version: 5.8.10

**Comment by jalogisch** [comment]
hej @mrdun this issue is already fixed in the master ( https://github.com/Graylog2/graylog2-server/pull/3503 ) we will release a bug fix release in the next days.

**Comment by mrdun** [comment]
@jalogisch thanks for the update!
