### ISSUE TITLE
Add the possibility to link condition and notification to each other

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#3522]
It would be nice for our Workflow, if we could bound one or more condition/s and notification/s to each other. Because we need different notifications on different events in the same stream. At the moment we have to create a new stream for every new condition/notification relationship.

As mentioned in the issue #3511 i open a separate issue for that.

## Expected Behavior
Connectors between conditions and notifications should be possible

## Current Behavior
Every condition triggers every notification on the stream.

## Possible Solution
Connectors, and maybe some AND or OR conditions?

## Context
We want to alert with a specific notification "A" when in the stream "STREAM"  a message with the field level:1 occurs. And we also want to alert with the notification "B" when in the stream "STREAM" a message with the field Eventid:12345 occurs.

But at the moment we see no function to realize this without triggering notification "A" and "B" every time one of the conditions are triggering. And we also have different Mail recipients on the notifications.

## Your Environment
Graylog 2.2

**Comment by joschi** [comment]
@gruselglatz Please elaborate a little more on your use cases. What is the current model lacking? Which functionality would you need to implement your use cases?

**Comment by gruselglatz** [comment]
Updated the issue, i hope it clarify my context.

**Comment by SebKiller** [comment]
This feature would be super useful indeed. Is there a way to vote it up?
I don't understand why it has not been implemented from day one.

**Comment by nisiya** [comment]
I agree. It would be very useful to trigger specific alert notifications for specific conditions.

**Comment by nstr10** [comment]
In my case, we have multiple teams using the platform who need different alerts from the same streams. Duplicating streams incurs an ongoing and unnecessary computational cost which we would like to avoid; it would be far better if we could bind notification profiles to alerts, or if there were an additional layer of abstraction other than streams that we could tie both alerts and notification profiles to.

**Comment by bernd** [comment]
This should be possible with the new events and alerts system in 3.2. Closing this issue.
