### ISSUE TITLE
New Index set will not be created if prefix contains upper case letters

### ISSUE THREAD

**Issue by meerkampj** [Graylog2/graylog2-server#3533]
When a new index set is created and the Index Prefix contains upper case letters it will not be created.

I created a new Index set with the Index Prefix "DEV_"
elasticsearch log shows the following : 
[2017-02-22 09:03:03,674][DEBUG][action.admin.indices.template.put] [NODE1] failed to put template [DEV_-template]
InvalidIndexTemplateException[index_template [DEV_-template] invalid, cause [Validation Failed: 1: name must be lower cased;]]
        at [...]
[2017-02-22 09:03:03,684][DEBUG][action.admin.indices.create] [NODE1] [DEV__0] failed to create
[DEV__0] InvalidIndexNameException[Invalid index name [DEV__0], must be lowercase]
        at [...]

Also it would be helpful if it was documented that graylog auto appends a "_$IndexNumber"

## Expected Behavior
a new index set will be created with given prefix "DEV_"

## Current Behavior
no index will be created and log-messages will remain in Disk Journal

## Possible Solution

- convert upper case letter to lovercase

or 
- catch upper case and report error

## Steps to Reproduce (for bugs)
1. Create new Index Set with an Index Prefix with upper case letters

## Your Environment

* Graylog Version: Graylog 2.2.0+d9681cb
* Elasticsearch Version: 2.3.2-1
* MongoDB Version: mongodb-org-server-3.4.1-1.suse11
* Operating System:  SUSE Linux Enterprise Server 11 SP3
* Browser version: Firefox 51.0.1

**Comment by jalogisch** [comment]
this is a dub of https://github.com/Graylog2/graylog2-server/issues/3476 and already fixed in 2.2.1
