### ISSUE TITLE
Stream filtering in alert conditions

### ISSUE THREAD

**Issue by llucenic** [Graylog2/graylog2-server#3535]
I would appreciate the possibility to filter a stream based on some arbitrary condition before the alert condition is evaluated on that stream. For example, I route all performance-related logs from all environments/components of a project into a single stream. It would be great, however, if I could define alert conditions per environment or component, not being forced to multiply the _stream_ into _stream per environment_ set of streams.

There come at least two ways to my mind (from user perspective):
- by adding a "search"-like form field to action conditions or
- by selecting a field (on the very form) for which in a "quick values" fashion a set of "dynamic" alert conditions were created and managed in the background.

The first option would need to define one alert condition per environment (for example) - what still seems to be a better option than multiplying streams. The second option is "conveniently" saving, not so flexible as the former one on the other hand.

**Great job on the rework of the alerting/notifications with 2.2.0. This was exactly something that has helped me with my project!**

**Comment by bernd** [comment]
This is possible with the new alerts system in 3.2. Closing this issue.
