### ISSUE TITLE
Web Interface access issues after upgrading from 2.0.2 to 2.2

### ISSUE THREAD

**Issue by AlexPilon90** [Graylog2/graylog2-server#3539]
Hi there,

We're running Graylog 2.0.2 on a VMWare environment as a Linux Virtual Appliance.

We tried updating to the latest available version yesterday evening, using the Graylog Omnibus package. The update itself went without a hitch, but post-update, we could not access the web interface anymore.

Before the update, we were using https://netlog.domain.com. We did not need to specify any ports or anything else.
After the update, https was not working anymore, and we had to specify port 9000 at the end of the URL or else it wasn't working (http://netlog.domain.com:9000).

The person who configured the application is gone from our enterprise, so we have very little information on how the appliance is configured. 

Is there a fix for this issue, and if so, how would I go about fixing this ?

Thanks,

**Comment by joschi** [comment]
@AlexPilon90 Please refer to http://docs.graylog.org/en/2.2/pages/configuration/graylog_ctl.html#install-custom-ssl-certificates for details about setting up HTTPS on the Graylog virtual machine appliances.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
