### ISSUE TITLE
Implement the Condition Field linking

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#3552]
We have the Problem that we need to link Field Conditions together, like it is possible in the Ruleset of Streams.

## Expected Behavior
Condition Ruleset like that one in the Streams

## Current Behavior
Only one Field can be selected. 

## Possible Solution
Stream like Conditions
Pipeline Rules to allow sending Emails, for complex Condition creations.

## Steps to Reproduce (for bugs)
1. Have 2 fields that should be true to: e.g. sessionID: xy and Action: LoggedIN
2. (At the moment) Create condition that matches whole message field, get many stacktraces in log and so on...
3. Get alerts that worked, or get no alert at all
4. Create a Alert: TRUE field :(

## Context
Field Condition A must be TRUE AND Field Condition B mus be TRUE to trigger this Condition.
We are forced to do something like a Pipeline Condition to add a field Alerting: TRUE if two fields have some specific value and set the alert condition on the field. We do this now but its not how it should be in my opinion.

## Your Environment
Graylog 2.2.0+d9681cb on syslog.local (Oracle Corporation 1.8.0_121 on Linux 3.10.0-327.22.2.el7.x86_64)

**Comment by bernd** [comment]
This is possible with the new alerts and events system.
