### ISSUE TITLE
Graylog doesn't send messages to Elasticsearch

### ISSUE THREAD

**Issue by mm1024** [Graylog2/graylog2-server#3553]
We have a weird problem with Graylog, which first appeared somewhere in September 2016. Several times a day Graylog silently stops sending messages to ES, process buffer is 100% utilized, disk cache grows. Restarting ES doesn't help, but restarting graylog-server does (until the next identical event).

When stuck, there is a minor number of messages (100-200 per minute, instead of 40-80K per minute) processed and shown in the search.

We would be grateful for any advice on this.

![screenshot from 2017-02-28 13-14-12](https://cloud.githubusercontent.com/assets/17710403/23404957/01b42400-fdb8-11e6-9a1b-68889d8ba392.png)

Graylog debug log attached (at line 660 message processing stops, journal grows). There are no indications of any problems in ES or MongoDB logs.
[server.log.zip](https://github.com/Graylog2/graylog2-server/files/806633/server.log.zip)

SERVER.CONF (number of processors / buffers / etc changed with no effect).

is_master = true
node_id_file = /etc/graylog/server/node-id
plugin_dir = /usr/share/graylog-server/plugin
rest_listen_uri = http://127.0.0.1:9000/api/
rotation_strategy = size
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 240
retention_strategy = delete
elasticsearch_shards = 1
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_analyzer = standard
output_batch_size = 1024
output_flush_interval = 1
output_fault_count_threshold = 2
output_fault_penalty_seconds = 30
processbuffer_processors = 8
outputbuffer_processors = 8
processor_wait_strategy = sleeping
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 8
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /var/lib/graylog-server/journal
message_journal_max_age = 24h
message_journal_max_size = 16gb
async_eventbus_processors = 4
lb_recognition_period_seconds = 3
mongodb_uri = mongodb://localhost/graylog
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5
content_packs_auto_load = grok-patterns.json
proxied_requests_thread_pool_size = 32

HARDWARE AND SOFTWARE CONFIGURATION

HW: one node with 48 CPUs, 64 Gb RAM, SSD disks with a plenty of disk space. Graylog is allowed to use 24G of memory. We receive 500...1500 messages/second with no spikes. There are two Syslog TCP inputs with 20-25 GROK-based extractors. We do not use pipelines or any custom outputs yet (except writing to ES).

* Graylog Version: 2.2.1 (and all previous, after 2.0.x)
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.4.2
* Operating System: Debian Stable (8.7) with recent updates
* Java: OpenJDK version "1.8.0_121"
* Browser version: Chromium, Safari

root@server:~# cat /proc/84406/limits 
Limit                     Soft Limit           Hard Limit           Units     
Max cpu time              unlimited            unlimited            seconds   
Max file size             unlimited            unlimited            bytes     
Max data size             unlimited            unlimited            bytes     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max resident set          unlimited            unlimited            bytes     
Max processes             774498               774498               processes 
Max open files            64000                64000                files     
Max locked memory         65536                65536                bytes     
Max address space         unlimited            unlimited            bytes     
Max file locks            unlimited            unlimited            locks     
Max pending signals       774498               774498               signals   
Max msgqueue size         819200               819200               bytes     
Max nice priority         0                    0                    
Max realtime priority     0                    0                    
Max realtime timeout      unlimited            unlimited            us

**Comment by jalogisch** [comment]
Hej @mm1024 I looked into this again and IMHO this might be related that you are running into some ES limitation because of the number of processes you use to push messages to Elasticsearch.

Means you might want to lower the output processors and raise the batch size - just to make use of the resources you have available. You might find [this posting](https://www.graylog.org/blog/74-back-to-basics-from-single-server-to-graylog-cluster) and the Information for tuning in the first section useful.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Additional you might want to think about [professional support](https://www.graylog.org/professional-support) as this looks like a more complex issue.
