### ISSUE TITLE
HTTP Alarm Callback - post requests to the Jabber server

### ISSUE THREAD

**Issue by work-des** [Graylog2/graylog2-server#3555]
We have a Jabber server. We can send him a post requests.

`http://logs%40jabber.fgr.com:12345@jabber.fgr.com:5280/message`
body
`<message to='u168@jabber.fgr.com'><body>TEST</body><html xmlns='http://jabber.org/protocol/xhtml-im'><body xmlns='http://www.w3.org/1999/xhtml'><p></p></body>TEST MESAGE</html></message>`

How can I send a post request through "**HTTP Alarm Callback**" ?

* Graylog Version: 2.1.1

**Comment by joschi** [comment]
@work-des There's no need to hack something with the HTTP Alarm Callback.

There's a Jabber/XMPP plugin for Graylog 2.2.x: https://marketplace.graylog.org/addons/9c44e1d9-4eaa-4f28-8558-4311b636df5d

**Comment by work-des** [comment]
It is compatible with Graylog Version: 2.1.1?

**Comment by joschi** [comment]
@work-des I don't know. It's been built against Graylog 2.2.0, but you might be lucky and make it work with Graylog 2.1.1.

This being said, I'd recommend upgrading to Graylog 2.2.x.

**Comment by work-des** [comment]
Accept self-signed certificates = true
Why did he swears on the certificate?

tailf /var/log/graylog-server/server.log
`java.security.cert.CertificateException: Hostname verification of certificate failed. Certificate does not authenticate jabber.prb.pmr
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.proceedTLSReceived(XMPPTCPConnection.java:754) [graylog-plugin-jabber-1.2.1.jar:?]
	at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$900(XMPPTCPConnection.java:139) [graylog-plugin-jabber-1.2.1.jar:?]
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1001) [graylog-plugin-jabber-1.2.1.jar:?]
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$200(XMPPTCPConnection.java:935) [graylog-plugin-jabber-1.2.1.jar:?]
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:950) [graylog-plugin-jabber-1.2.1.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
`

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Draven13** [comment]
how can I send http alarmback to telegram?

**Comment by joschi** [comment]
@Draven13 Check the [Graylog Marketplace](https://marketplace.graylog.org/addons/5590c29b-8b40-40e2-abfd-bbbb7b758eb3).

**Comment by Draven13** [comment]
funny. checked only 1 plugin, which work not as needed. i asked for methods how can I post the message into telegram. Now, I can only send my own messages, but not the variables or arrays.

**Comment by FelixFV** [comment]
i use python script for same problem
in my case script asks API for finding Messages and send simple  message with some fields to telegram.
Script running every 1 minute by cron

**Comment by Draven13** [comment]
can you share? @Vayde  in telegram.  Appreciate any help with this stuff

**Comment by joschi** [comment]
Please move this discussion to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
