### ISSUE TITLE
docker : do bash script is broke

### ISSUE THREAD

**Issue by beeyeas** [Graylog2/graylog2-server#3558]
I see the coreutils package has to be installed for "readlink" to work and modify line:8 of do with "greadlink -f"

## Expected Behavior

Expected Output :

./do help
usage: do command

This program starts Docker containers with all dependencies required for running Graylog.
It reads its configuration from /Users/v830165/workspace/graylog2-server/docker/config/do.conf and certain environment variables.

Also see docker-compose(1) for details.

COMMANDS:
  up                    Create and start Docker containers
  rm                    Remove the created Docker containers
  ps                    List Docker containers

  mkvol                 Create Docker volumes (graylog-elasticsearch, graylog-mongodb)
  rmvol                 Remove Docker volumes (graylog-elasticsearch, graylog-mongodb)

  start                 Start service(s)
  stop                  Stop service(s)
  restart               Restart service(s)
  kill                  Force stop service

  pause                 Pause service(s)
  unpause               Unpause service(s)

  logs                  Show logs of the running Docker containers

## Current Behavior

Error Output on executing "do"
./do help
./do: line 8: /config/do.conf: No such file or directory

## Steps to Reproduce (for bugs)

1. Checkout code, https://github.com/Graylog2/graylog2-server/tree/master/docker
2. Follow Instruction in README.md, In my example i am on OSX
3. ./do help
4. Bombs with error message "./do: line 8: /config/do.conf: No such file or directory"

Note : 
docker -v
Docker version 1.13.1, build 092cba3

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@beeyeas Thanks for reporting this.

The stuff in the [`docker` subdirectory](https://github.com/Graylog2/graylog2-server/tree/2.2.1/docker) is pretty much unsupported and won't be given too much effort to maintain (it's basically "works for me").

This being said, just install GNU coreutils via Homebrew or similar means on Mac OS X and the script will work.
