### ISSUE TITLE
Attempting to drop messages in certain streams

### ISSUE THREAD

**Issue by CrazyLlama** [Graylog2/graylog2-server#3561]
Hello!

Right now I'm trying my hardest to be able to route messages from the <All messages> stream and onto their own <representative stream> for easier documentation, good practice, and all that good stuff. 

Now that's going all well and dandy _however_ I'm now trying to drop the messages from the <All messages> after they're sent to <representative stream>. **Problem is** that they're being dropped from all streams when I attempt drop_message(); in the following fashion - See my lovely paint diagram here: http://imgur.com/KavC9Wz.png

If anyone's got any ideas on this I'd love the help, or if I'm just going crazy and I shouldn't do this please tell me - Thank you in advance!

**Comment by jalogisch** [comment]
hej @CrazyLlama did you try to *remove_from_stream* in the pipelines?

This is currently not possible, but already on the table https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/117

**Comment by CrazyLlama** [comment]
Aww, that's quite sad. But I'll work around it for now and it should be fine, thank you!
