### ISSUE TITLE
Add to dashboard with long dashboard list

### ISSUE THREAD

**Issue by jothoma1** [Graylog2/graylog2-server#3563]
## Expected Behavior

When we click on the button "Add count to dashboard" we can select in the list the dashboard to add the widget.

## Current Behavior

When we click on the button "Add count to dashboard" we cannot select in the list a dashboard which is at the end of the list as we have a long dashboard list and it it not displayed correctly.
## Possible Solution

Permit to filter the list (like in streams ?)
## Steps to Reproduce (for bugs)

1. Create a lot of dashboard
2. Try to add count to a dashboard which is at the end of the list of dashboards
3.
4.

## Your Environment

* Graylog Version: 2.2.1
* Elasticsearch Version:
* MongoDB Version:
* Operating System: 
* Browser version: Firefox / opera / chrome

**Comment by dennisoelkers** [comment]
This has been fixed in `3.2.0`. Widgets are now created inline on a dashboard instead of being added to an existing one.
