### ISSUE TITLE
Support for categorizing or grouping file for searchability   

### ISSUE THREAD

**Issue by rayeesnp** [Graylog2/graylog2-server#3582]
Currently, to search file you need to provide full path, some of the case like you need to search for multiple file for the same 

eg : To debug the issue with Tomcat, you need to search for both catalina.out, application log and access log, here you need to pass all three files, instead of the if we can provide and way to categorize  or group the file with a name, and search file file that name the process will be simple 

## Expected Behavior

Need option to search for multiple file with tag example 

file : "TOMCAT", internally this should search for "/data/tomcat/logs/catalina.out" and "/data/tomcat/logs/acess_01.log"

## Current Behavior

Currently you need to knw all files path and name to search, this will difficult once the number of files get too much 
 
## Possible Solution

1) Need option to map files with tag 
# TOMCAT ="/data/tomcat/logs/catalina.out","/data/tomcat/logs/acess_01.log"

Should be able to search with tag

eg : file: "TOMCAT"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@rayeesnp You can already add arbitrary message fields (let's call it `category`) on ingestion using the [Message Processing Pipelines](http://docs.graylog.org/en/2.2/pages/pipelines.html).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
