### ISSUE TITLE
get alert id in AlaramCallBack Plugin

### ISSUE THREAD

**Issue by wuweiliang1** [Graylog2/graylog2-server#3586]
Hi everyone. I could't find the way to get alert id when I develop a new plugin implementing AlarmCallback, though I can get the stream_id and condition_id. Is there any way possible way to get this in my own plugin? Thanks for any help!

## Environment

* Graylog Version:2.2.2

**Comment by joschi** [comment]
@wuweiliang1 That's currently not possible.

Please elaborate on your use case and why it requires access to the (internal) ID of the alert.

**Comment by wuweiliang1** [comment]
@joschi thks for your reply.
When an alarm trigger, Our team wants to estimate the match messages that triggered the alerts. So I want to expose a direct link to user to help them click on the link to see what's going on as soon as possible. But if I want to get such a alert link, I have to know the alert id. That's why I'm trying to get this in my own plugin.

**Comment by bernd** [comment]
With the new alerting system, it's possible to build links to the event that triggered a notification.
