### ISSUE TITLE
Update from 2.1.3 to 2.2.2 failed

### ISSUE THREAD

**Issue by dtpest** [Graylog2/graylog2-server#3592]
Hi,

we are using Graylog2 Cluster on two Docker physical nodes.
We have updated already several times without any problems.
But this time updating from 2.1.3 to 2.2.2 failed with an endless loop.
Message:
```
2017-03-08 14:45:21,508 ERROR: org.graylog2.messageprocessors.MessageFilterChainProcessor - Could not apply filter [StreamMatcher] on message <79554b35-0405-11e7-9f98-02420258b064>: 
java.lang.IllegalStateException: index set must not be null! (stream id=57e12510291c9b000125e942 title="bigtest")
        at org.graylog2.streams.StreamImpl.getIndexSet(StreamImpl.java:263) ~[graylog.jar:?]
        at org.graylog2.plugin.Message.addStream(Message.java:418) ~[graylog.jar:?]
        at org.graylog2.plugin.Message.addStreams(Message.java:428) ~[graylog.jar:?]
        at org.graylog2.filters.StreamMatcherFilter.filter(StreamMatcherFilter.java:43) ~[graylog.jar:?]
        at org.graylog2.messageprocessors.MessageFilterChainProcessor.process(MessageFilterChainProcessor.java:100) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.handleMessage(ProcessBufferProcessor.java:119) [graylog.jar:?]
```

## Expected Behavior
It should migrate the data and start Graylog2 again

## Current Behavior
It recreates the Container and ends in an endless loop.

## Steps to Reproduce (for bugs)
1. Stop Docker container and remove it
2. "docker run" new container with Graylog version 2.2.2

## Your Environment
Docker version 1.13.0, build 49bf474
Host-OS: Ubuntu 16.04.1 LTS
Elasticsearch: 2.3.5

**Comment by joschi** [comment]
@dtpest How exactly did you upgrade Graylog?
Which Docker image are you using?
Did you stop all Graylog nodes before creating new containers based on Graylog 2.2.2?
Have you read the upgrade notes at http://docs.graylog.org/en/2.2/pages/upgrade/graylog-2.2.html?

**Comment by dtpest** [comment]
@joschi thanks for your fast response.
I am using docker image from:
https://hub.docker.com/r/graylog2/server/tags/ (Tag 2.2.2-1)
I have stopped and removed the master node and then created the container again with "docker run" on the same host.
I've also set the variable "-e GRAYLOG_INDEX_SET_ID=graylog" with "docker run"

**Comment by joschi** [comment]
@dtpest Were there any other error messages before the one you've included in your first post?

What's the purpose of the `GRAYLOG_INDEX_SET_ID` environment variable? It's not being evaluated by Graylog.

**Comment by dtpest** [comment]
I am not sure, because it was an endless loop - so only this message was displayed all the time.
I have set this variable for testing purposes, because in the upgrade guide is something documented with "index_set_id":
http://docs.graylog.org/en/2.2/pages/upgrade/graylog-2.2.html

**Comment by joschi** [comment]
> I am not sure, because it was an endless loop - so only this message was displayed all the time.

There are usually messages before that. Try to find them in the log file of Graylog (if there is one or if you've recorded the stdout/stderr streams of the Docker container).

> I have set this variable for testing purposes, because in the upgrade guide is something documented with "index_set_id"

Interesting approach, but it doesn't have any effect at all. You might want to re-read the upgrade notes. 😉

**Comment by dtpest** [comment]
I've already read the documentation again, but I am not sure where I have to set this variable.
Can you please tell me a bit more about this variable?

**Comment by joschi** [comment]
@dtpest Which variable?

**Comment by dtpest** [comment]
index_set_id

Maybe it is possible in the Webinterface itself - but the Webinterface isn't available after upgrading to the newest version.

**Comment by joschi** [comment]
@dtpest That's a red herring. The attribute you're referring to is a parameter for the Graylog REST API.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by dtpest** [comment]
Sure it is a bug - because updating isn't possible.
Also I'm unable to change the values in the UI.

**Comment by dtpest** [comment]
Updating isn't possible, so index_set_id does not matter atm

**Comment by tweeks024** [comment]
Did anyone find a solution to this?  I have the same issue after trying to upgrade from 2.1.3 to 2.3.2?

**Comment by tweeks024** [comment]
What seems to have happened is that some streams did not get the "index_set_id" added in their definition in the Streams Collection in mongo.  Here is an example of a bad one:

    {
        "_id" : ObjectId("5a1d6bb2a9b2c72984e24dc0"),
        "creator_user_id" : "admin",
        "matching_type" : "AND",
        "description" : "EU2 Queue Prod",
        "created_at" : ISODate("2017-11-28T13:59:14.546Z"),
        "disabled" : false,
        "title" : "EU2 Queue Prod",
        "content_pack" : null
    }

I was able to add the `"index_set_id" : "59bb08b469d42f3bcfa6f18e"` value in and restore the streams:

    {
        "_id" : ObjectId("5a1d6bb2a9b2c72984e24dc0"),
        "creator_user_id" : "admin",
        "index_set_id" : "59bb08b469d42f3bcfa6f18e",
        "matching_type" : "AND",
        "description" : "EU2 Queue Prod",
        "created_at" : ISODate("2017-11-28T13:59:14.546Z"),
        "disabled" : false,
        "title" : "EU2 Queue Prod",
        "content_pack" : null
    }

**Comment by joschi** [comment]
>  I have the same issue after trying to upgrade from 2.1.3 to 2.3.2?

@tweeks024 What's the complete log of your Graylog (master) node directly after the upgrade?

**Comment by tweeks024** [comment]
@joschi unfortunately I know longer have the original log from the master.  It did go through and update the indices but I believe my mistake may have been that I started a secondary server (that had been upgraded) before this process finished.
