### ISSUE TITLE
Change default for dashboards' update toggle

### ISSUE THREAD

**Issue by f0o** [Graylog2/graylog2-server#3595]
Hi,

it would be nice to have a way to default dashboards to always update in background.

We have a handful of NOC screens that run a mix of applications, sometimes it happens that an application kills the browser and we would restart it, furthermore sometimes it can be forgotten that you need to click the `update in background` button for graylog.

I think having a small boolean config directory should be sufficient for this and wouldnt pose a big impact.

Just our 2 cents :)

**Comment by edmundoa** [comment]
Hi @f0o,

There's a way of doing this per user, although it is not documented (and it needs some attention, to be honest). You can go to the edit user profile page in _Authentication_, click on "User preferences", and set `updateUnfocussed` to `true`. After that, the dashboard should load in the background by default.

I'll leave this issue open, so we add some documentation about this.

**Comment by f0o** [comment]
I couldn't find the option in our install (2.2.2+691b4b7) - does it matter that we use AD as authentication source?

**Comment by edmundoa** [comment]
No, the only user that should not see that button is the admin user (the one defined in the Graylog config file). Just to double-check, here is were the "User preferences" button should be:

![user-preferences](https://cloud.githubusercontent.com/assets/716185/23750411/21ab8cc8-04cd-11e7-8818-fcbd1383762c.png)

**Comment by f0o** [comment]
Oooh totally missed that, sorry

**Comment by dennisoelkers** [comment]
This has been fixed in `3.2.0` with the introduction of the big display mode, which allows to pre-configure auto-refresh settings and generates a sharable URL.
