### ISSUE TITLE
Graylog is not viable

### ISSUE THREAD

**Issue by konradjurk** [Graylog2/graylog2-server#3604]
It eats 2gb of memory and not even one message has been logged. Plus it runs at constantly 150%+ CPU and eats at least (now my drive is full) 13GB of disk space. I am using this docker image: graylog2/server.

If this is it what graylog does, then I am wondering how anyone can seriously run this? Or am I doing something terribly wrong?

Used the gelf docker driver

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
