### ISSUE TITLE
Alert conditions do not appear properly after cloning a stream

### ISSUE THREAD

**Issue by ssriley** [Graylog2/graylog2-server#3608]
When cloning a stream with alert conditions, the alert conditions show up only associated to the newly cloned stream in the web interface. 
## Expected Behavior

I would expect to be able to manage the alert conditions that are associated to with the original stream and the cloned stream.

What should happen is the newly cloned alert conditions have some text appended to the name so it is unique. That may fix the issue? What would be better is if the alert conditions aren't cloned at all with a stream but rather you could create an alert condition(s) under the alerts section, put them in groups, and apply those alert conditions/groups to streams. This would make the alert conditions more modular and reusable. Similar to how you have setup pipelines rules.
## Current Behavior

You do not see the cloned alert conditions associated to both the original stream and the newly cloned stream in the web interface. So the problem is i can't manage the the alert conditions of the original stream in the web GUI because i can't see them. The alert conditions do continue to work with both streams. I think it is because the alert conditions have the exact same name. If I delete the cloned stream, i can then manage the original alert conditions that are tied to the original stream. It seems as though this is a bug. 

## Steps to Reproduce (for bugs)

1.Create a stream with alert conditions
2.Clone the stream
3.Try to independently manage the alert conditions associated with the different streams.
4.

## Context

We want to make stream template that has most alert conditions and rules already setup so we only have to change a few things when setting up a new stream. We don't want to have to setup everything from scratch each time.

Templating. Making creating streams and alert conditions quicker and easier.

## Your Environment

* Graylog Version: Graylog 2.2.2+691b4b7
* Elasticsearch Version: 2.4.4
* MongoDB Version: 2.6.10
* Operating System: Ubuntu 16.04 LTS
* Browser version: Chrome 57.0.2987.98 (64-bit)

**Comment by jalogisch** [comment]
thank you for submitting this bug. 

I can confirm this, please see the images below. GL Graylog 2.2.2+691b4b7

##  one condition
![only_one_condition](https://cloud.githubusercontent.com/assets/404238/23910871/5decacb4-08db-11e7-8190-ab6b4f1395de.png)

## multiple notifications
![alert_interface](https://cloud.githubusercontent.com/assets/404238/23910869/5c5db9e2-08db-11e7-8c08-5f3e37d46f2b.png)

## addition
The conditions are stacked - when you delete the condition you can reload the page and see the alerting stream changed but the condition still present. 

I guess some grouping is done and having the same name and conditions but for different streams does not work currently.
