### ISSUE TITLE
Permission to manage notification rules/notifications sould be independent of edit stream permission

### ISSUE THREAD

**Issue by micw** [Graylog2/graylog2-server#3613]
In Graylog 2.2.2 a user requires "edit"-permissions on a stream to edit notification conditions. Without these permissions, the user gets a 403 error on the POST/PUT api call to create/update a condition.

A user who has edit permissions on a stream can remove rules from that stream and so access "other's" logs. So it would be better to separate these permissions (e.g. "read", "manage notifications", "edit" ).

Use-Case: Give an user access to a stream where he can see "his" logs and edit create his own notifications.

**Comment by gruselglatz** [comment]
#3482

**Comment by bernd** [comment]
This is possible with the new alerting in 3.2 and the upcoming entity sharing in 4.0.
