### ISSUE TITLE
SearchForm component is uncontrolled

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#3618]
## Expected Behavior
The query string should not disappear.

## Current Behavior
When used in conjunction with `PaginatedList` the `SearchForm` component loses its query string when the returned list is empty.
This is because the state is only kept in the DOM element, whose react id changes due to differences in rendering of empty lists.

## Possible Solution
Make the component controlled or completely passive by passing the string as a prop.
Since the pagination information and query string often go together and the search callbacks need to be written anyway, my suggestion is to move the query string into a prop to avoid depending on stable DOM element ids.

## Steps to Reproduce (for bugs)

![peek 2017-03-14 17-30](https://cloud.githubusercontent.com/assets/52014/23949139/68ed3b14-0986-11e7-8bf0-72ddeffb4580.gif)

* Graylog Version: 2.x

**Comment by edmundoa** [comment]
This got fixed in https://github.com/Graylog2/graylog2-server/pull/4685 and https://github.com/Graylog2/graylog2-server/pull/4684
