### ISSUE TITLE
Search syntax error

### ISSUE THREAD

**Issue by jothoma1** [Graylog2/graylog2-server#3624]
## Expected Behavior

When searching an exact query with " " it should return the results

## Current Behavior

When searching :
source:serverX AND "Mar 16 2017 10:10:5" it gives me 0 result

When searching :
source:serverX AND "Mar 16 2017 10:10:58" it gives me 15 résultats with this sort of string "Mar 16 2017 10:10:58 CET"

## Steps to Reproduce (for bugs)

1. Compare 2 equivalent searchs in a context which you are sure to have results :
2. source:serverX AND "Mar 16 2017 10:10:5"
3. source:serverX AND "Mar 16 2017 10:10:58"
4.

## Your Environment

* Graylog Version: 2.2.2
* Elasticsearch Version:
* MongoDB Version:
* Operating System: CentOS
* Browser version: Firefox / Opera / Chrome

**Comment by joschi** [comment]
@jothoma1 You have to use wildcards for this: http://docs.graylog.org/en/2.2/pages/queries.html#search-query-language

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by jothoma1** [comment]
Hi @joschi 
i thing you closed too early :) because i forgot to precise that it didnt work with wildcards too ...

**Comment by jothoma1** [comment]
I updated the bug report

**Comment by joschi** [comment]
@jothoma1 It doesn't look like a bug in Graylog but like a problem with your index mapping or the query itself.

Please move the discussion to the previously mentioned places.

**Comment by jothoma1** [comment]
can you explain me why ? It's a string

**Comment by joschi** [comment]
@jothoma1 Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).
