### ISSUE TITLE
Graylog Index settings wont update after setting on elasticsearch

### ISSUE THREAD

**Issue by ion-storm** [Graylog2/graylog2-server#3644]
I set replicas to 1 in elasticsearch with curl, now I am unable to manage Graylog replicas at all through the graylog interface.  I tried setting replicas to 1,2,0 and the changes do not effect elasticsearch at all.

**Comment by joschi** [comment]
@ion-storm Please describe exactly what you have been doing (e. g. which commands you've executed and what their output was).

**Comment by ion-storm** [comment]
```
curl -XPUT '172.22.1.50:9200/_settings' -d '{
    "index" : {
        "number_of_replicas" : 0
    }
}'
```
and:
```
curl -XPUT '172.22.1.50:9200/_settings' -d '{
    "index" : {
        "number_of_replicas" : 0
    }
}'
```

**Comment by joschi** [comment]
@ion-storm Graylog defines the number of shards and replicas in its default Elasticsearch index template.

If you want to change the configuration, please do so on the System / Indices page in the respective index set.
