### ISSUE TITLE
The output speed to ElasticSearch is very slow

### ISSUE THREAD

**Issue by darouwan** [Graylog2/graylog2-server#3645]
I am working on processing a large amount of logs file with graylog and es. The input speed is about 100k/second， but the output speed to elastic search is just 7000/second. i have test the performance of my es cluster whose processing speed is about 14k/s, where es should not be bottleneck.  

And I have checked the server load, the CPU usage is less than 5%, memory usage and network usage are both quite low. 

I have tried the following potential configure changing:
1. Change output buffer threads core pool size and max pool size to 30 and 90 respectively. 
2. Change output batch size to 2000
3. Change processbuffer processors and outputbuffer processors to 128. 

But unfortunately, there is no observably enhancement. 

So what is wrong with my graylog and how to solve it? 

Hardware:
64 Cores CPU
384GB Memory
6TB SSD

Software Environment:
* Graylog Version: 2.2.0
* Elasticsearch Version: 2.4.3
* MongoDB Version: 3.*
* Operating System: Centos 6.7
* Browser version: Chrome

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
