### ISSUE TITLE
Alert conditions not appearing

### ISSUE THREAD

**Issue by CrazyLlama** [Graylog2/graylog2-server#3646]
I was looking into setting some new alert conditions recently just to keep everything up to date and decided _oof_ I should probably audit the ones we currently have for those best practice reasons - keep everything ship shape and all that - when I noticed that some alert conditions don't seem to be appearing on the alerts webui for **manage conditions** but were still sending alert emails out.

## Expected Behavior
Visit Alerts -> Manage conditions -> all my created and active conditions be happily chugging along :smile: 

## Current Behavior
Visit Alerts -> Manage conditions -> some of my active/created alerts don't seem to appear here even when they are actively working :cry: 

Anyone got any ideas on this? Or is this a genuine bug?

**Comment by dennisoelkers** [comment]
Do you see anything in your browser's javascript console? Can you provide a dump of your `streams` collection in your MongoDB to us?

**Comment by jalogisch** [comment]
@CrazyLlama would you please update us on this.

**Comment by CrazyLlama** [comment]
Sorry about that, not been able to get on the past few days - 

Graylog version is: 2.2.1+4829190
The js console shows no errors in Chrome or IE
And I'll get a dump now :smile: 

Thank you guys!

**Comment by avongluck-r1soft** [comment]
We saw an issue around the OpsGenie plugin for Graylog preventing alerts from firing.  After uninstalling the OpsGenie plugin and restarting Graylog the issue went away.  We've had an issue open to OpsGenie for a week now on it.

**Comment by edmundoa** [comment]
Hi @CrazyLlama,

There were some fixes on that regard in 2.2.2, I would try updating to see if that fixes the issue you are experiencing.

By the way, are you experiencing this issue with a regular or admin user? You should only get alert conditions for streams you have permissions to read and regular users may not have permission to read all streams.

**Comment by CrazyLlama** [comment]
I'll try the update now - and this is with an admin user

**Comment by CrazyLlama** [comment]
Apologies again, yep this certainly cleared it up! 

Thank you everyone :smile:
