### ISSUE TITLE
Message preview : Dynamically changing the number of lines displayed

### ISSUE THREAD

**Issue by sguilly** [Graylog2/graylog2-server#3647]
**Improvement request :**

It should be great to be able to change the number of rows displayed in message preview (see image below)

![image](https://cloud.githubusercontent.com/assets/5059932/24207245/b830dcb8-0f20-11e7-96d2-019a23874ec3.png)

Currently, you see only the first 4 lines of the message.

Of course, you could expand all messages, but there is too much informations... to read messages like a log file.

**Comment by jalogisch** [comment]
In the given example our recommendation would be to extract all information into single fields. Then use the columns to display the information.
