### ISSUE TITLE
"Loading..." on the search page. Unable to execute search: all shards failed (GL 2.2.2-1 / ES 2.4.4)

### ISSUE THREAD

**Issue by Raphux** [Graylog2/graylog2-server#3648]
## Expected Behavior
Search should display some logs.

## Current Behavior
When launching a search, the "Loading..." strings appears, and no result is ever displayed.
In the /var/log/graylog-server/server.log : 

> 2017-03-23T10:55:43.850+01:00 WARN  [SearchResource] Unable to execute search: all shards failed

## Steps to Reproduce (for bugs)
1. Install Debian 9
2. Follow the documentation : http://docs.graylog.org/en/latest/pages/installation/os/debian.html
3. add an input
4. add some logs to the input
5. launch a search and admire the «Loading...» string
6. check the /var/log/graylog-server/server.log for the error mentionned above.

## Your Environment
* Graylog Version: 2.2.2-1
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.2.11-2
* Operating System: Debian 9 (Stretch)
* Browser version: 57.0.2987.110 (64-bit)

**Comment by jalogisch** [comment]
hej @Raphux 

this looks for me like you have some local issues with your Elasticsearch Server and is not a bug in Graylog.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
