### ISSUE TITLE
Allow Cardinality graph for non-numeric fields

### ISSUE THREAD

**Issue by skorhone** [Graylog2/graylog2-server#3649]
Ability of generating cardinality based graphs would allow users to visualize information such as number of active users or number of different error types at given time.

## Expected Behavior

Allow graphs on non-numeric fields and only allow cardinality function to be used

## Current Behavior

Graphs on non-numeric fields are not allowed

**Comment by edmundoa** [comment]
This was fixed in https://github.com/Graylog2/graylog2-server/pull/4182, and will be available in the upcoming 2.4 release.
