### ISSUE TITLE
when searching and selecting "Message" --> "Quick Values" system becomes unresponsive

### ISSUE THREAD

**Issue by ryamgithub** [Graylog2/graylog2-server#3654]
## Expected Behavior
I understand that there would be a lot to sort through, but if there should be a warning or the system should just try to return the results - When this happens I have to re-boot the system

If the query is too large for system to handle it should not allow user to run the query.

## Current Behavior
System response becomes sluggish - error messages start appearing at the bottom of the screen.

## Possible Solution
Code should determine if the query will cause system to become unusable, prevent user from running query.

## Steps to Reproduce (for bugs)

1. Do a search where "message" field is populated with different messages (1000,s of records)
2. Under search results - select Message - then "quick values"
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by ryamgithub** [comment]
Well, this happens in graylog - If I select something that a small # of unique values it works fine, if I select a field that has a lot of non unique values, (like message), then the system basically crashes.
Everything else in the system is working - so not sure why this would not be considered a bug.
