### ISSUE TITLE
graylog not processing

### ISSUE THREAD

**Issue by flapegue** [Graylog2/graylog2-server#3656]
when i see in disk journal metric, the number of unprocessed messages increase and not processing.
I build a new index, and it is empty.

how can i solve this ?

thank for your help

![image](https://cloud.githubusercontent.com/assets/23529050/24333892/9b73ea3c-1260-11e7-8d03-3ce75a6d0fa0.png)

Graylog Version: 2.2.2-1
Elasticsearch Version: 2.4.4
MongoDB Version: 1:2.4.10-5
Operating System: Linux Debian 8.7

**Comment by flapegue** [comment]
when i stop input, the messages processing, but it very very slow.

what i the optimal configuration for i physique host with this caracteristics
4 x Intel(R) Xeon(R) CPU E5-1603 0 @ 2.80GHz
8Gb of RAM

i put ES_HEAP_SIZE=4g in /etc/default/elasticsearch
and GRAYLOG_SERVER_JAVA_OPTS="-Xms2g -Xmx2g -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow" in /etc/default/graylog-server

it is correct ?

**Comment by flapegue** [comment]
finaly, this modification dont change processing, it dont work. however the number of unprocessed message remains fixed

**Comment by jalogisch** [comment]
It looks like your Graylog is not able to connect to Elasticsearch or something else stops processing. Without some Logfiles or more Information about your Setup that questions can't be answered easily.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by flapegue** [comment]
in the overview page, elasticsearch seems to be connected and my configuration is

```
# grep -Pv '^\s*(#|$)' /etc/default/graylog-server
JAVA=/usr/bin/java
GRAYLOG_SERVER_JAVA_OPTS="-Xms4g -Xmx4g -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow"
GRAYLOG_SERVER_ARGS=""
GRAYLOG_COMMAND_WRAPPER=""

```
```
# grep -Pv '^\s*(#|$)' /etc/default/elasticsearch
CONF_DIR=/etc/elasticsearch
DATA_DIR=/var/lib/elasticsearch
LOG_DIR=/var/log/elasticsearch
PID_DIR=/var/run/elasticsearch
ES_HEAP_SIZE=4g
ES_USER=elasticsearch
ES_GROUP=elasticsearch
ES_STARTUP_SLEEP_TIME=5
```
```
# grep -Pv '^\s*(#|$)' /etc/graylog/server/server.conf
is_master = true
node_id_file = /etc/graylog/server/node-id
password_secret = XXXXX
root_password_sha2 = XXXXX
root_timezone = Europe/Paris
plugin_dir = /usr/share/graylog-server/plugin
rest_listen_uri = http://X.X.X.X:9000/api/
rest_transport_uri = http://X.X.X.X:9000/api/
web_listen_uri = http://X.X.X.X:9000/
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 1
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_analyzer = standard
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /var/lib/graylog-server/journal
lb_recognition_period_seconds = 3
mongodb_uri = mongodb://localhost/graylog
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5
content_packs_dir = /usr/share/graylog-server/contentpacks
content_packs_auto_load = grok-patterns.json
proxied_requests_thread_pool_size = 32
```
```
# grep -Pv '^\s*(#|$)' /etc/elasticsearch/elasticsearch.yml
cluster.name: graylog
discovery.zen.minimum_master_nodes: 1
```

**Comment by joschi** [comment]
@flapegue We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Also make sure to check the logs of your Graylog and Elasticsearch nodes: http://docs.graylog.org/en/2.2/pages/configuration/file_location.html

**Comment by flapegue** [comment]
sorry, i just understood
