### ISSUE TITLE
The Time Zone Problem

### ISSUE THREAD

**Issue by tmtbe** [Graylog2/graylog2-server#3661]
"Generate chart"-> "Resulotion"-> "Day" In other time zones is not the start of the day at 0 in the middle of the night.

Hello,I come from China,I chose the Shanghai time zone,When I use the "Generate chart" function and set the interval to the "Day", I found that the start of the day is 00:00:00 UTC, I feel a little problem.

It is displayed: "08:00 +0800"，I think it should be " 00:00 +0800"? Am I right?

* Graylog Version: 2.2.2

And other problem.
"keyword" : "yesterday 00:00 +0800  to today 00:00 +0800",the preview show "2017-03-26 08:00:00 to 2017-03-27 21:17:43" why? It should be "Sat Mar 25 16:00:00 UTC 2017 to Sun Mar 26 16:00:00 UTC 2017".

**Comment by edmundoa** [comment]
Hi @tmtbe,

This issue was already reported in #1830 (therefore, I am closing this issue). The problem here is that Graylog stores internally your logs in UTC and the histogram bucketing is not adjusted to the user's local time zone.

I hope that helps to clarify your question.

**Comment by tmtbe** [comment]
thank you, I found that is not merger to the master, the future version of a better solution?

**Comment by edmundoa** [comment]
No, the pull request opened to fix this issue is not ready, and looking at the amount of changes we need to do to properly support this, the fix will have to wait at least until 3.0, maybe more.
