### ISSUE TITLE
Graylog is not picking Cisco switch logs

### ISSUE THREAD

**Issue by shann1890** [Graylog2/graylog2-server#3678]
## Current Behavior
I setup all my cisco product logs to graylog with tcp connection. Firewall logs only is viewable in graylog.Switches and Routers log traffics could not see in the system/input even the active connection shows there.

If I telnet to a custom tcp port, I can see the message in graylog that input while the telnet session is active.

If I set a default syslog port (udp 514) and direct to rsyslog-Linux then it works but when used custom ports in graylog, it doesn't work properly.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 2.2.2-1
* Elasticsearch Version:2.4.4-1
* MongoDB Version: 3.4.3-1
* Operating System: CentOS 7 Core
* Browser version:

**Comment by joschi** [comment]
@shann1890 Cisco devices unfortunately don't send valid syslog (according to RFC 3164 or RFC 5424).

We will add support for Cisco syslog in Graylog 2.2.3 (which is due next week) but for now you'll have to create a Raw/Plaintext input to receive syslog messages created by Cisco devices.

If you have more questions, please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by shann1890** [comment]
Thanks.

**Comment by Trueffelwurm** [comment]
I'm experiencing the same behavior on Graylog 2.2.3-2: Messages from cisco switches are dropped.
This can be replicated by injecting the following message to syslog:
<133>: TEST
The colon followed by a whitespace after the facillity tag will cause the message to be dropped.
That is exactly the issue joschi described with invalid syslog messages by cisco switches.

**Comment by fontv2** [comment]
Hi all,
Any news on this issue?
Cheers
