### ISSUE TITLE
Messages evaluated are not fit with search

### ISSUE THREAD

**Issue by tal242** [Graylog2/graylog2-server#3680]
Hi
I configured a callback alert that should triggered to slack when the words "ERR" AND "Kafka" are appear on messages.
There is two issues with the alert:
1. When the alert is triggered, the message that caused the alert is not appear.
2. I checked the history of the alert by click on:
Alerts >>  name of the alert (marked as resolved) >> Messages evaluated
But I see another messages except of what I was looking for ("ERR" AND "Kafka"), which is not fit with my search. 
Then I clicked on "Open in search page", in the search-line there is (*), which means I get all the messages that related to the stream, instead of my search. 

Is it bug? or may I did something wrong?
Please assist.

Thanks. 

* Graylog Version: 2.2
* Elasticsearch Version: 2.3.4
* Operating System: 14.04

**Comment by joschi** [comment]
@tal242 What's the exact alert condition you've created?

**Comment by tal242** [comment]
@joschi 
Title: Filebeat-test
Field: message
Value: "ERR" AND "Kafka"
Message Backlog: 1

**Comment by joschi** [comment]
@tal242 That's unfortunately not how it works.

You can only use one value in the alert condition. You alert condition literally searches for `"ERR" AND "Kafka"`.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by tal242** [comment]
@joschi 
I tried to configure one value in the alert as suggested- "Kafka"
but still I get another messages except of what I was looking for.

Messages evaluated:
2017-04-03 15:34:45.517	2017/04/03 12:34:35.524724 client.go:209: ERR **Kafka** (topic=filebeat_dev_logs): dropping too large message of size 1547237.

2017-04-03 15:34:46.140	% Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0 100 12022 0 12022 0 0 2219k 0 --:--:-- --:--:-- --:--:-- 2348k

Should it find only messages with the word "Kafka", right?

**Comment by joschi** [comment]
@tal242 Please move this discussion to the community forums: https://community.graylog.org/
