### ISSUE TITLE
Create Lookup Table domain objects

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#3691]
The lookup table feature needs several new entites:
 - [x] LookupTable
 - [x] CacheProvider
 - [x] DataProvider

This is a placeholder for the necessary commits.

**Comment by davama** [comment]
I see this was moved and closed.
@kroepke sorry for the dumb question but would the now merged #3748 allow for https://github.com/Graylog2/graylog-plugin-map-widget/issues/38 ??

thanks!

**Comment by bernd** [comment]
@davama Yes, lookup tables can be used for that. You need a data adapter that supports DNS lookups, though.
