### ISSUE TITLE
API not working  Graylog 2(v2.2.3) on AWS EC2

### ISSUE THREAD

**Issue by jun283** [Graylog2/graylog2-server#3692]
implemented Graylog using an AWS AMI to install v2.2.2, and update to v2.2.3,
 Everything is working fine, except for the Swagger API browser, 

     GET https://52.53.106.000:9000/api/api-browser net::ERR_TIMED_OUT

my graylog-settings.json:

```
ubuntu@graylog:/etc/graylog$ cat graylog-settings.json
{
  "timezone": "Asia/Singapore",
  "smtp_server": "",
  "smtp_port": 587,
  "smtp_user": "",
  "smtp_password": "",
  "smtp_from_email": null,
  "smtp_web_url": null,
  "smtp_no_tls": false,
  "smtp_no_ssl": false,
  "master_node": "127.0.0.1",
  "local_connect": false,
  "current_address": "172.31.31.46",
  "last_address": "172.31.31.46",
  "enforce_ssl": true,
  "journal_size": 1,
  "node_id": false,
  "internal_logging": true,
  "web_listen_uri": false,
  "web_endpoint_uri": false,
  "rest_listen_uri": false,
  "rest_transport_uri": false,
  "external_rest_uri": "https://52.53.106.000/api",
  "custom_attributes": {

  }
}
```

 Your Environment

* Graylog Version:Graylog 2.2.3+7adc951
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Ubuntu 14.04.5 LTS
* Browser version:

**Comment by joschi** [comment]
@jun283 `52.53.106.000` is not a valid IP address. Double check your network settings.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by jun283** [comment]
sorry, it is not really my server ip,  my my server ip is: 52.53.106.204

**Comment by joschi** [comment]
@jun283 Works for me:
```
$ curl -i --insecure -H 'Accept: application/json' https://52.53.106.204/api/?pretty=true
HTTP/1.1 200 OK
Server: nginx/1.9.14
Date: Fri, 07 Apr 2017 09:32:28 GMT
Content-Type: application/json
Content-Length: 253
Connection: keep-alive
X-Graylog-Node-ID: 3cee548a-5958-4f56-864f-f8d03ff2ffb3
X-Runtime-Microseconds: 300

{
  "cluster_id" : "1180c9e9-2dfc-45af-8376-5b559b4ba6a7",
  "node_id" : "3cee548a-5958-4f56-864f-f8d03ff2ffb3",
  "version" : "2.2.3+7adc951",
  "tagline" : "Manage your logs in the dark and have lasers going and make it look like you're from space!"
}
```
