### ISSUE TITLE
Add hyperlinks to "Quick Values" dashboard widgets

### ISSUE THREAD

**Issue by alias454** [Graylog2/graylog2-server#3694]
Add hyperlinks to "Quick Values" dashboard widgets
## Current Behavior
Currently, there is no mechanism to perform a refined search on specific values from a dashboard. There is only the option of clicking the replay button, which replays the entire search. After a search is performed several additional clicks may have to be performed in order to re-refine the results.

## Possible Solution
When viewing a dashboard widget one would click the specific item's value, which will automatically append that item's value to a more refined search basically adding the item's value to &q= using the widgets "Field" and linked value.

![graylog_dashboard_widget](https://cloud.githubusercontent.com/assets/10768415/24831906/418c19f0-1c69-11e7-8ac3-5d5021db8419.png)

Regards,
Brandon

**Comment by chabou** [comment]
What about using same search icon than in quick values table? 
![capture d ecran 2017-05-11 a 11 19 30](https://cloud.githubusercontent.com/assets/4137761/25942083/0f729646-363c-11e7-8a3d-c8cd0dd715ad.png)

Or maybe better to use a `replay` button at this place on each row?

We really neeeeed this feature 😄 
PR welcome ?

**Comment by dennisoelkers** [comment]
This has been fixed in `3.1.0` by OSSing the views, which are now the default search in `3.2.0`.
