### ISSUE TITLE
Override facility incase _facility is sent as additional field

### ISSUE THREAD

**Issue by n3xus** [Graylog2/graylog2-server#3709]
Some libraries I'm using is sending facility and _facility at the same time. Thus being unable to set facility.

## Expected Behavior
"_facility" should override "facility"

## Current Behavior
deprecated "facility" is overriding "_facility"

## Possible Solution
"_facility" should override "facility"

## Steps to Reproduce (for bugs)
1. Send both "facility" and "_facility" fields

## Context
Legacy systems are not letting us change facility. Thus we are unable to write log in our desired format.

## Your Environment

* Logstash Version: 5.3
* logstash-output-gelf Version: 3.1.2 (https://github.com/logstash-plugins/logstash-output-gelf)
* Graylog Version: 2.2.3
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.4
* Operating System: Windows Server 2012 R2
* Browser version: Chrome 57

**Comment by joschi** [comment]
@n3xus `facility` and `_facility` are both custom fields from the point of view of Graylog.

If you want to overwrite one with the other, you can do so using extractors or processing pipeline rules:

* http://docs.graylog.org/en/2.2/pages/extractors.html
* http://docs.graylog.org/en/2.2/pages/pipelines.html
