### ISSUE TITLE
I have some questions about default field 'source' 

### ISSUE THREAD

**Issue by zhou-mfk** [Graylog2/graylog2-server#3711]
I have some questions about default field 'source' 

I understand the field source is the IP address of the sending message to graylog.
My graylog arch is as follows：
3 nodes graylog as a cluster
3 nodes elasticsearch as a cluster

inputs graylog cluster  use tcp . I use rsyslog sent message to graylog.

I question about field source When I use HAProxy proxy inputs port. The field source value is HAProxy‘s IP .
zls-183 is a hostname use rsyslog sent message to graylog.
10.201.240.3 is haproxy ip.
I think the field source value is hostname/ip(zls-183) don't HAProxy's IP. Is there any way to solve it？
![image](https://cloud.githubusercontent.com/assets/15190461/25167987/5e7f03c0-2514-11e7-9e7d-7156dae8e500.png)

* Graylog Version: 2.0.1
* Elasticsearch Version: 2.2.1
* MongoDB Version: 3.4.2
* Operating System: Centos 7.3
* Browser version: chrome 57

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
