### ISSUE TITLE
Dashboard variables

### ISSUE THREAD

**Issue by skorhone** [Graylog2/graylog2-server#3712]
## Expected Behavior
Dashboards should allow creating widgets containing variables. Variables should be referenceable from other widgets

## Current Behavior
Dashboards queries are static

## Possible Solution
1. Define a syntax for variables e.g. %{variable}
2. Create a new widgets for defining variables (dropdown, datepicker, timespan)
3. Change client side algorithm to send variables with api queries
4. Modify server side caching algorithm for widgets (Cache specific queries instead? This allows cache to be reused in multiple dashboards)

## Context
Currently we have to create multiple similar dashboards (daily, weekly, monthly views, different environments, etc)

**Comment by jalogisch** [comment]
this is similar to https://github.com/Graylog2/graylog2-server/issues/3459

**Comment by joschi** [comment]
Closing in favor of #3459.
