### ISSUE TITLE
Selecting different ranges in Histogram is unusable

### ISSUE THREAD

**Issue by rswestmoreland** [Graylog2/graylog2-server#3714]
Histogram isn't working properly when a range other than Minute is used.  Rather than grouping the bars and labels based on the new range (Hour, Day, Week, Month), it still shows per-minute, so it's just one solid blue bar from left to right, with hundreds of overlapping labels that you can't read.

* Graylog Version:  2.2.3+7adc951
* Operating System:  Windows 10, Windows 7
* Browser version:  Firefox 52.0.2 (32-bit)

**Comment by edmundoa** [comment]
Hi @rswestmoreland,

Would you be so kind as to specify which time range you are using when you see the issue? A screenshot would also help to understand better the issue.

Thank you!

**Comment by rswestmoreland** [comment]
It happens in any of the histogram time selections other than per minute.

**Comment by rswestmoreland** [comment]
How do I send you a screenshot?  I tried to when I opened up this Issue but it didn't work.  I tried to send to you as an attachment when I replied to this via email, and that appears to not have worked either.

**Comment by edmundoa** [comment]
How long is the time range for the search? When you look for less than an hour of time, resolutions lower than minute will most likely return a single data-point, which looks funny but is still correct.

To upload a file, you can use the Github web interface and drag and drop the file from your file browser to the input field (or select them in the link below the text area). More information [here](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/).

**Comment by jalogisch** [comment]
@rswestmoreland can you please give us some feedback that we can look into this issue.

thank you

**Comment by jalogisch** [comment]
@rswestmoreland we will close this issue because of missing feedback. If you have additional Input, please reopen the issue.
