### ISSUE TITLE
specify jdk location?

### ISSUE THREAD

**Issue by yarnping** [Graylog2/graylog2-server#3715]
hello~
I'm using  ``` Graylog v2.2.3 ```
I'm wondering can I specify jdk location? cause I do have Jdk7 application on the server while I'm planing to use graylog with jdk8

**Comment by joschi** [comment]
@yarnping You can use the `JAVA` environment variable in the [Graylog start script](https://github.com/Graylog2/fpm-recipes/blob/2.2/recipes/graylog-server/files/environment#L1-L2) for this.

See http://docs.graylog.org/en/2.2/pages/configuration/file_location.html for the specific file location in which you have to put the JVM settings.

**Comment by yarnping** [comment]
@joschi thanks !

**Comment by yarnping** [comment]
@joschi Im using tar.gz jdk version which is  

``` JAVA=/opt/jdk1.8.0_131/bin/java```
but it's no working, still error

> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/graylog2/bootstrap/Main : Unsupported major.minor version 52.0

how can I make sure the configuration is working?

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by yarnping** [comment]
@joschi 
It's solved. cause ```/etc/sysconfig/graylog-server``` exists!!
thanks a lot
