### ISSUE TITLE
Extractors Split by \n

### ISSUE THREAD

**Issue by heijiu** [Graylog2/graylog2-server#3717]
how to Split by \n in Extractors ?

try to regex_value: \d+\n\d+\n.+?\n.+?\n.+?\n.+?\n\d+\n\d+\n(.+?)\n is slow

thanks

* Graylog Version:current release
* Elasticsearch Version:2.4.4
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
