### ISSUE TITLE
Web UI: Link to API browser in System>Nodes should use web_endpoint_uri

### ISSUE THREAD

**Issue by 2ion** [Graylog2/graylog2-server#3718]
The page System>Nodes links to the individual nodes' API browser page for convenience. This link currently does not point to web_endpoint_uri and thus breaks in certain setups where the web interface is behind a reverse proxy/load balancer.

## Your Environment

* Graylog Version: 2.2.3
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.4.4
* Operating System: Debian Jessie
* Browser version: Firefox 52

**Relevant** settings from server.conf (single-node cluster):

| Key | Setting |
| --- | --- |
| rest_transport_uri | http://127.0.0.1:9000/api/ |
| web_endpoint_uri |  https://SOMEIP:443/api/ |
| web_listen_uri |  http://127.0.0.1:9000 |
| rest_listen_uri | http://127.0.0.1:9000/api/ |

## Expected Behavior

The link in System>Nodes should link to https://SOMEIP/api/api-browser.

## Current Behavior

The link in System>Nodes links to http://127.0.0.1:9000/api/api-browser, which obviously does not work from a remote location.

## Possible Solution

Use `web_endpoint_uri` when presenting the link.

## Steps to reproduce

 * Given a setup as described in Environment, browse to System>Nodes:
 * Follow the API browser link beside a node entry.

## Context

This would also help in the following case where there is more than a single Graylog node in the cluster:

 * SOMEIP is a public IP accessed from the internet
* The Graylog nodes communicate with each other using internal IPs, meaning that `rest_listen_uri`/`rest_transport_uri` are never reachable from the internet and thus should not be used for links in the web interface.

**Comment by joschi** [comment]
@2ion The current behavior is intentional. `web_endpoint_uri` could point to a URI of a load-balancer which talks to a random (and not a specific) Graylog node.

The link to the API browser on the other hand, should open the API browser of a **specific** Graylog node (the one you've clicked on).
