### ISSUE TITLE
Can't find swagger.json for swagger-codegen

### ISSUE THREAD

**Issue by beatcracker** [Graylog2/graylog2-server#3721]
I'd like to make some API calls to Graylog via PowerShell. Since Graylog uses Swagger, I thought that I can save some time by generating C# client library and using it from the PowerShell, rather then poking API endpoints directly.

Unfortunately I can't find a `swagger.json` file that I can feed to [swagger-codegen](https://github.com/swagger-api/swagger-codegen) or [NSwag](https://github.com/NSwag/NSwag). Is it available somewhere or is there another way to achieve this?

**Comment by joschi** [comment]
@beatcracker Graylog's REST API is developed code-first, so there is no defined Swagger definition up-front (it's generated during runtime).

If you want to fetch the Swagger definition from a running Graylog instance, you can do so by fetching `/api-docs` and its sub-resources from the Graylog REST API.
