### ISSUE TITLE
After upgrade to 2.2.3 all my inputs and dashboards are gone

### ISSUE THREAD

**Issue by stevenmcastano** [Graylog2/graylog2-server#3726]
I finally got graylog reinstalled on Ubuntu 14.04 by using the graylog 2.2 repo, and I'm not up and logged in... all my previous data appears to be here except all my input and dashboard configs are done... and they were failed complex. Any idea where to recover them from??

**Comment by joschi** [comment]
@stevenmcastano Make sure to use the same node ID and MongoDB database, e. g. check the contents of your [`node_id_file`](https://github.com/Graylog2/graylog2-server/blob/2.2.3/misc/graylog.conf#L49-L51) and that your upgraded Graylog instance is using the same MongoDB database as the previous one.
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
