### ISSUE TITLE
Single log getting repeated multiple times on graylog2

### ISSUE THREAD

**Issue by rakeshbhatt10** [Graylog2/graylog2-server#3739]
I have setup graylog2 on ubuntu server. Currently i am sending logs using GELF UDP. I had created streams to separate out logs. Graylog is receiving logs at input but same logs are getting repeated multiple times when i see on search and streams. While on original log files the log has occurred only once. 

![selection_005](https://cloud.githubusercontent.com/assets/6121592/25467040/962bd828-2b29-11e7-8171-64130cbf8677.png)

* Graylog Version: Graylog v2.2.3+7adc951
* Elasticsearch Version: 2.3.1
* MongoDB Version: 3.4.3
* Operating System: 16.04

**Comment by joschi** [comment]
@rakeshbhatt10 We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Please also add all necessary details, e. g. how you're shipping logs to Graylog and how you've configured all relevant components.

Thank you!

**Comment by rakeshbhatt10** [comment]
@joschi I had created topic on discussion forum 

Topic link : 
https://community.graylog.org/t/single-log-getting-repeated-multiple-times-on-graylog2/956

I have added additional details there.
Thanks
