### ISSUE TITLE
GELF TCP input should support compression

### ISSUE THREAD

**Issue by mikaelstaldal** [Graylog2/graylog2-server#3741]
## Expected Behavior
GELF TCP input should support compression, just like GELF UDP and GELF Kafka inputs do.

## Current Behavior
When sending compressed GELF (according to [GELF spec](http://docs.graylog.org/en/2.2/pages/gelf.html#compression)), to GELF TCP input, those messages are ignored by Graylog server.

## Your Environment
* Graylog Version: 2.2.3
* Elasticsearch Version: 2.4.4
* MongoDB Version: 2.6.10
* Operating System: Ubuntu 16.04
* Browser version: Firefox 53.0

**Comment by joschi** [comment]
@mikaelstaldal Using compression like Zlib or GZIP for GELF TCP is currently not possible due to the framing mechanism used by GELF TCP.

See https://github.com/Graylog2/graylog2-server/issues/428#issuecomment-34965700.

**Comment by mikaelstaldal** [comment]
What about documenting this?

**Comment by joschi** [comment]
@mikaelstaldal Yes, good idea.

Do you have an idea how to formulate it specifically? https://github.com/Graylog2/documentation/blob/2.2/pages/gelf.rst

**Comment by mikaelstaldal** [comment]
Maybe it should rather be documented here: http://docs.graylog.org/en/2.2/pages/sending_data.html#gelf-sending-from-applications

A new section "GELF via TCP" just above or below the existing "GELF via HTTP":

### GELF via TCP
You can send in uncompressed GELF via a plain TCP socket. Each message need to be delimited with a null byte ('\0'). Compression is not supported.

**Comment by mikaelstaldal** [comment]
You might also want a "GELF via UDP" section there for completeness.
