### ISSUE TITLE
Password leak through LDAP configuration page

### ISSUE THREAD

**Issue by alex3305** [Graylog2/graylog2-server#3763]
On the LDAP/AD configuration page, the LDAP/AD password is actually returned back to the frontend in plain text. This is a minor security leak, since you need administrator privileges to access this page, but can be easily mitigated.

## Expected Behavior
I cannot view the LDAP/AD password in the frontend/web interface of the application.

## Current Behavior
I can view the LDAP/AD password in the frontend/web interface of the application by using the browser's inspector.

## Possible Solution
The LDAP/AD password is not send back or rendered to the frontend, but a normally invalid placeholder is sent, such as "********". When a user saves the configuration, the application can check whether or not the placeholder is present. If the placeholder is present in the form, the LDAP/AD password will not be changed, otherwise it will.

## Steps to Reproduce (for bugs)
1. Open the System > Authentication > LDAP Settings page
2. Fill in the LDAP authentication parameters
3. Save the page
4. Reload the page
5. Open your browser's inspector on the LDAP password field
6. View the password in plain text

## Context
Trying to set up an easy to use and secure logging environment. 

## Your Environment
* Graylog Version: 2.2.1+4829190 
* Elasticsearch Version: 2 (Docker, latest)
* MongoDB Version: 3 (Docker, latest)
* Operating System: Windows 10
* Browser version: Chrome (stable)

**Comment by mikkolehtisalo** [comment]
Related to #1088 and #1087.
