### ISSUE TITLE
Java Exception after rotation (with no impact?)

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#3775]
After Index Rotation i got his message:
```
java.lang.IllegalArgumentException: mapper [bytes] of different type, current_type [long], merged_type [string]
```
I only have one message not indexed, idk what field or which message this was.

## Your Environment
Graylog 2.2.0+d9681cb on syslog.xyz.local (Oracle Corporation 1.8.0_131 on Linux 3.10.0-514.16.1.el7.x86_64)

**Comment by joschi** [comment]
@gruselglatz The field `bytes` doesn't have the type Elasticsearch was expecting when inserting a new document.

See http://docs.graylog.org/en/2.2/pages/configuration/elasticsearch.html#custom-index-mappings
