### ISSUE TITLE
LDAP groups show in UI but not through API

### ISSUE THREAD

**Issue by madchap** [Graylog2/graylog2-server#3779]
I am using an openLDAP backend to create users and groups.

I can see everything OK in the UI, but if I try to GET /system/ldap/settings/groups, I do not see the new group (which sounds really odd).

![image](https://cloud.githubusercontent.com/assets/5468769/25728035/dd116664-312c-11e7-9d16-db5f996a36fe.png)

![image](https://cloud.githubusercontent.com/assets/5468769/25728043/f05f95b0-312c-11e7-896c-e00395a9f45c.png)

## Expected Behavior

With an LDAP backend configured:
- After creating a LDAP group (that matches the LDAP setup fine)
- Adding a new graylog role

I should see the new unmapped role in GET /system/ldap/settings/groups, just like I can see it in the UI.

## Current Behavior

I currently see the unmapped role in the UI, but not via the REST API (incl. swagger or through or python request call).

## Possible Solution

I wish I had the level to offer a possible solution :-)

## Steps to Reproduce (for bugs)

1. Create a new LDAP group (groupOfUniqueNames), add a new user to it.
2. Create a new graylog role
3. Try to fetch the ldap settings group to realize the new role is not there
4. Go the UI, and realize it is shown on the page (set to None as expected)

## Your Environment

* Graylog Version: 2.2.3
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.4.3
* Operating System: CentOS (running graylog stack with docker-compose)
* Browser version: Chrome

**Comment by madchap** [comment]
To add to that, if I manually assign -- in the UI -- an actual group and save, it works. I then can see the new mapping via the REST API.

I have nothing showing up in the logs as-is either.

**Comment by bernd** [comment]
The implementation of this has changed in the upcoming 4.0 version and this shouldn't be an issue anymore. Please open a new issue if you still see problems in the new version. Thank you!
