### ISSUE TITLE
Error: WARN [EqualityExpression] left expression evaluated to null, returning false: $message.SourceUser

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog2-server#3799]
We are seeing the error shown below in our logs.  As far as I can tell this started appearing 3 weeks ago, but am not sure what precipitated it as we are still testing and do not have formal change control around upgrades\changes etc:-

**WARN [EqualityExpression] left expression evaluated to null, returning false: $message.SourceUser**

I'm sure this is to do with one of our processing pipelines\extractors etc, but am not sure how to track the offending setting\entry down.

Can you give any pointers as to where we can look for additional information that could help me identify what is causing this?

Many Thanks

**Comment by dennisoelkers** [comment]
Hey @urban-moniker,

thanks for reporting this. Could you please reopen the issue in the [pipeline processor plugin repository](https://github.com/Graylog2/graylog-plugin-pipeline-processor)? It looks like we need better output that is helping you to find the correct rule to fix.

Other than that, the error seems to come from [here](https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/master/plugin/src/main/java/org/graylog/plugins/pipelineprocessor/ast/expressions/EqualityExpression.java#L50). I would guess that you have a pipeline rule, that is trying to evaluate `$message.SourceUser` while `$message` is `null`.

**Comment by dennisoelkers** [comment]
This issue was moved to Graylog2/graylog-plugin-pipeline-processor#180
