### ISSUE TITLE
Evaluate the performance impact of not using Thrift instead of an ambedded ES node

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#380]
Right now we have the problem that the server has to be running against an ES cluster that speaks a version of the ES binary protocol that is compatible with the one of the embedded ES node that is linked into the server. This helps us to achieve high throughput and low latency but involves the potential to force users to match their ES versions which might not be suitable for many production environments. Thrift might be an option to avoid this.

**Comment by bernd** [comment]
I am closing this because these days (Graylog 1.x and Elasticsearch 1.x) you can use different versions and are not locked to one specific Elasticsearch version.
