### ISSUE TITLE
Compile ERROR for graylog2-server when mvn package

### ISSUE THREAD

**Issue by bj1116** [Graylog2/graylog2-server#3807]
## Expected Behavior
Want to package successful with command "mvn package -Dmaven.test.skip=true"  

## Current Behavior
Have package successful ,but can't display the login page  , and have some error :

[ERROR] clean-webpack-plugin: /opt/graylog2-server-2.2.3/graylog2-web-interface/build/vendor.*.js has been removed.
......
[ERROR] ts-loader: Using typescript@1.8.10 and /opt/graylog2-server-2.2.3/graylog2-web-interface/tsconfig.json

## Your Environment

* JDK Version: 1.8
* Maven Version: 3.2
* Graylog Version: 2.2.3
* Elasticsearch Version: 2.4.5
* MongoDB Version: 3.2.12
* Operating System: CentOS 7.3
* Browser version: Firefox

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
