### ISSUE TITLE
Field aggregation condition Should also support decimal and long values

### ISSUE THREAD

**Issue by ankit511** [Graylog2/graylog2-server#3808]
I am using metricbeat for monitoring system and process stats. The data send by metric beat has CPU and memory utilization in decimal value (.i.e < 1 ) and Filesystem has free space value in long.
Graylog Field aggregation currently only support integer values, due to this we are not able to configure alert.

If we have decimal and long support in field aggregation we can use metricbeat for System and process monitoring and alert.

**Comment by joschi** [comment]
@ankit511 Is the field you're trying to aggregate on a decimal field such as `float` or `double`?
See https://www.elastic.co/guide/en/elasticsearch/reference/2.4/number.html for details.

You can check this in the Elasticsearch index mapping: https://www.elastic.co/guide/en/elasticsearch/reference/2.4/indices-get-mapping.html

**Comment by ankit511** [comment]
Hi Jochen,

I am using Metricbeat 5.3 and its output gives CPU and Memory utilization
in percentage ( i.e. 0.00 to 1.00 )
And for FileSystem output values of diskspace are in Bytes which has
greater value than integer highest value.

To Configure alert for CPU and Memory and FileSystem we need support of
decimal and long value in Field aggregate condition.
Currenlty it support only Integer.

Regards,
Ankit


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by joschi** [comment]
@ankit511 I'm unable to reproduce this.

Make sure that the fields in Elasticsearch have the correct mapping. You can create a custom index mapping for this purpose: http://docs.graylog.org/en/2.2/pages/configuration/elasticsearch.html#custom-index-mappings

If you have more questions, please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

## Example

Type of field `fp` in Elasticsearch (dynamically created by simply sending `3.1415`):
```
# curl -s 'http://127.0.0.1:9200/graylog_deflector/_mapping?pretty' | jq '.[].mappings.message.properties.fp'
{
  "type": "float"
}
```

Response of Graylog REST API query used for graphs:
```
# curl -u user:password -H 'Accept: application/json' 'http://127.0.0.1:9000/api/search/universal/relative/fieldhistogram?query=gl2_source_input%3A5592913ec026f261b8d5ce9a&range=0&interval=day&field=fp&cardinality=false&pretty=true'
{
  "interval" : "day",
  "results" : {
    "1494806400" : {
      "total_count" : 103,
      "count" : 103,
      "min" : 3.1414999961853027,
      "max" : 3.1414999961853027,
      "total" : 323.5744996070862,
      "mean" : 3.1414999961853027,
      "cardinality" : 0
    }
  },
  "time" : 4,
  "built_query" : "{\n  \"query\" : {\n    \"query_string\" : {\n      \"query\" : \"gl2_source_input:5592913ec026f261b8d5ce9a\",\n      \"allow_leading_wildcard\" : false\n    }\n  },\n  \"aggregations\" : {\n    \"gl2_filter\" : {\n      \"filter\" : {\n        \"bool\" : {\n          \"must\" : {\n            \"range\" : {\n              \"timestamp\" : {\n                \"from\" : \"1970-01-01 00:00:00.000\",\n                \"to\" : \"2017-05-15 09:15:43.946\",\n                \"include_lower\" : true,\n                \"include_upper\" : true\n              }\n            }\n          }\n        }\n      },\n      \"aggregations\" : {\n        \"gl2_histogram\" : {\n          \"date_histogram\" : {\n            \"field\" : \"timestamp\",\n            \"interval\" : \"1d\"\n          },\n          \"aggregations\" : {\n            \"gl2_stats\" : {\n              \"stats\" : {\n                \"field\" : \"fp\"\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n}",
  "queried_timerange" : {
    "from" : "1970-01-01T00:00:00.000Z",
    "to" : "2017-05-15T09:15:43.946Z"
  }
}
```

**Comment by gn-ley** [comment]
I have the same issue and I am not able to configure an alert. The GUI is not aware of a field type at this moment but forces me to use integer anyway.

![bildschirmfoto 2017-06-28 um 16 32 02](https://user-images.githubusercontent.com/14089663/27642888-685d0034-5c20-11e7-8370-8d60e64bb21d.png)

`<input type="number" required="" value="0" class="input-xlarge validatable form-control" min="-9007199254740991" max="9007199254740991" data-reactid=".e.1.0.0.1.0.0.0.3:$field_value-threshold.1">`

**Comment by bronius** [comment]
I am seeing this, too, also with percentages.  An idea for a workaround occurred to me that I've not yet thought through nor tested: Maybe instead of Max we use Sum and add values to come up with an integer threshold that wouldn't normally be passed with safe values?
