### ISSUE TITLE
Graylog dont start after extending disk on ova

### ISSUE THREAD

**Issue by kuroboshi** [Graylog2/graylog2-server#3818]
## Expected Behavior
After extending the disk by following the tutorial, graylog will no longer start.
Mongdb is down and i cannot acces log

## Current Behavior
By following the tutorial, when the ova is restarted, graylog does not start anymore.
http://docs.graylog.org/en/2.2/pages/configuration/graylog_ctl.html#extend-disk-space
The same problem recurred when I tested with a new ova.

## Steps to Reproduce (for bugs)
1. Download the lastest ova
2. First configure graylog
3. Stop vm, add disk
4. Use http://docs.graylog.org/en/2.2/pages/configuration/graylog_ctl.html#extend-disk-space
5. Reboot, graylog don't start, mongodb is down

## Context
I use a ova with fortinet, WS DNS and after WS DHCP pack

## Your Environment
I use vsphere 5.5 with vnx5300

* Graylog Version: Lastest OVA
* Elasticsearch Version: Lastest OVA
* MongoDB Version: Lastest OVA
* Operating System: Win 7 Pro
* Browser version: Firefox 52.1.1 ESR

**Comment by joschi** [comment]
@kuroboshi We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Also make sure to include all relevant information, such as the commands you've executed and their output, and the logs of the relevant components (see http://docs.graylog.org/en/2.2/pages/configuration/file_location.html#omnibus-package).

Thank you!
