### ISSUE TITLE
Fail to read message from kafka input

### ISSUE THREAD

**Issue by sayume** [Graylog2/graylog2-server#3837]
Graylog can't read data from plain/text kafka input

## Expected Behavior
plain/text can be read from kafka.

## Current Behavior
It's fail to read topic from kafka
```
2017-5-17 15:28:402017-05-17 07:28:40,818 WARN : kafka.consumer.RangeAssignor - No broker partitions consumed by consumer thread graylog2_1d39f8643da8-1495005827265-2b4787a6-2 for topic xxx
2017-5-17 15:28:402017-05-17 07:28:40,818 WARN : kafka.consumer.RangeAssignor - No broker partitions consumed by consumer thread graylog2_1d39f8643da8-1495005827265-2b4787a6-20 for topic xxx
2017-5-17 15:28:402017-05-17 07:28:40,818 WARN : kafka.consumer.RangeAssignor - No broker partitions consumed by consumer thread graylog2_1d39f8643da8-1495005827265-2b4787a6-3 for topic xxx
2017-5-17 15:28:402017-05-17 07:28:40,818 WARN : kafka.consumer.RangeAssignor - No broker partitions consumed by consumer thread graylog2_1d39f8643da8-1495005827265-2b4787a6-4 for topic xxx
2017-5-17 15:28:402017-05-17 07:28:40,818 WARN : kafka.consumer.RangeAssignor - No broker partitions consumed by consumer thread graylog2_1d39f8643da8-1495005827265-2b4787a6-5 for topic xxx
2017-5-17 15:28:402017-05-17 07:28:40,818 WARN : kafka.consumer.RangeAssignor - No broker partitions consumed by consumer thread graylog2_1d39f8643da8-1495005827265-2b4787a6-6 for topic xxx
2017-5-17 15:28:402017-05-17 07:28:40,818 WARN : kafka.consumer.RangeAssignor - No broker partitions consumed by consumer thread graylog2_1d39f8643da8-1495005827265-2b4787a6-7 for topic xxx
```
## Possible Solution
It's kafka input bug.

## Steps to Reproduce (for bugs)
1. start a kafka cluster with zk
2. start a kafka input to read from zk

## Your Environment

* Graylog Version: 2.2.x
* Elasticsearch Version: 2.2.3
* Kafka Version: 0.10.0.1

**Comment by joschi** [comment]
@sayume What type of Kafka input are you using in Graylog?
How did you configure the Kafka input?
How did you configure Kafka (and the clients producing the messages)?

**Comment by sayume** [comment]
I use plain/text kafka input, and connect it via zookeeper like "hostname:2181"

**Comment by joschi** [comment]
@sayume Please post the exact configuration of the involved components, not just a snippet without context.

**Comment by sayume** [comment]
kafka config:
ADVERTISE_PUB_IP:false
CONFD_INTERVAL: 60
KAFKA_DELETE_TOPICS: false
KAFKA_NUM_PARTITIONS:3
ZK_SERVICE:zookeeper/zk

graylog config:
zookeeper address: zk:2181
topic filter regex: .*?
process threads: 3

These configs are all in the UI, and else are default configs, both kafka cluster and graylog are in docker.

**Comment by sayume** [comment]
To reproduce the issue, install rancher and start a kafka cluster with rancher catalog,  then start a graylog server with a raw/plaintext kafka input type, import some logs into kafka(I use rsyslog), the issue will be reproduce.
I've notice that sometimes the log can reach the graylog, but most of the time it can't.

**Comment by sayume** [comment]
I found many errors in zookeeper, from graylog instance:
2017-5-17 17:09:072017-05-17 09:09:07,392 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@1008] - Closed socket connection for client /0:0:0:0:0:0:0:1:47848 (no session established for client)
2017-5-17 17:10:012017-05-17 09:10:01,380 [myid:1] - INFO  [Snapshot Thread:FileTxnSnapLog@240] - Snapshotting: 0x1c00559995 to /opt/zk/data/version-2/snapshot.1c00559995
2017-5-17 17:10:012017-05-17 09:10:01,392 [myid:1] - INFO  [SyncThread:1:FileTxnLog@203] - Creating new log file: log.1c00559997
2017-5-17 17:10:072017-05-17 09:10:07,395 [myid:1] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxnFactory@192] - Accepted socket connection from /0:0:0:0:0:0:0:1:48249
2017-5-17 17:10:072017-05-17 09:10:07,395 [myid:1] - WARN  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:NIOServerCnxn@357] - caught end of stream exception
2017-5-17 17:10:07EndOfStreamException: Unable to read additional data from client sessionid 0x0, likely client has closed socket
2017-5-17 17:10:07	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:228)
2017-5-17 17:10:07	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:203)
2017-5-17 17:10:07	at java.lang.Thread.run(Thread.java:745)

**Comment by sayume** [comment]
I've solved the problem by rollback to version 2.2.1-1. I tried all the 2.2.x versions and only 2.2.1-1 works, however, the graylog nodes lost re-balancing, only one node can receive the logs, anyway it works now.

**Comment by jalogisch** [comment]
@sayume did you switched to 2.3 and is this working now?

**Comment by Dougoc** [comment]
**Up!** I'm running Graylog V2.2.3 with the same problem: Only one graylog node received the logs through Kafka input. With a flow more than 60k msg/s in production, one node not support for much time. 

## Environment ##
- Graylog Version: 2.2.3
- Elasticsearch Version: 2.4.4
- Kafka Version: 0.11.0.1-1

**Comment by bernd** [comment]
This should be fixed in https://github.com/Graylog2/graylog2-server/pull/7504.
Please open a new issue if you still see this with Graylog 3.3 or the upcoming 4.0 release. Thank you!
