### ISSUE TITLE
Improve multi node setup documentation

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#384]
People are tempted to set up a multi node system with two different mongodb instances to achieve HA.
This will lead to 401 errors, because the sessions won't be available in all nodes, and thus the setup fails.

Make it clearer that a shared mongodb instance is required.

Feel free to move this issue to 0.20.0 final.

**Comment by 123dev** [comment]
Is this still an issue? ie shared mongodb instance is still required?
Based on comments from Marius [here](https://github.com/Graylog2/omnibus-graylog2/issues/30#issuecomment-228346927)
Replica-Set in mongoDB can be setup and utilized.
Though not without problems (at least in our case) which is discussed in [this](https://github.com/Graylog2/omnibus-graylog2/issues/30#issuecomment-228390884) thread.

Thanks

**Comment by jalogisch** [comment]
@123dev you need some kind of shared mongodb - how you solve this is up to you.

**Comment by joschi** [comment]
Closed by Graylog2/documentation#128.
