### ISSUE TITLE
Show the "source" field always on the field selector sidebar

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#3849]
The "source" field is probably the most used field where we apply quickvalues and so on. So we always have to change to "all fields" and filter for "source" to get to our Modifiers.

Maybe it would be usefull to create a third page like a userbased "favourites fields" page?

## Expected Behavior

Such an Important default field should be listed on the default "current page" list. Bcs. it's always on the Current Page ;)

## Current Behavior
"source" field is on the "all fields" page

## Possible Solution
Put the "source" field on the "current page" list, or let us have a favourite fields page

## Context
explaned above

## Your Environment
Graylog 2.2.0+d9681cb on syslog.xyz.local (Oracle Corporation 1.8.0_131 on Linux 3.10.0-514.16.1.el7.x86_64)

**Comment by jalogisch** [comment]
the feature wish would be to have preferences that are shown on the result page.

**Comment by dennisoelkers** [comment]
Regarding the missing `source` field: This was fixed in #3584 / #3585, so upgrading to `2.2.3` will help you.
