### ISSUE TITLE
Lookup Tables is cool

### ISSUE THREAD

**Issue by cdino** [Graylog2/graylog2-server#3855]
Hi,
This is not a bug, but maybe you find this feedback useful. :)
Yesterday I installed the last alpha on a small VM cluster and I'm testing the the Lookup Tables feature, easy and very useful. Great job!

Just wondering if I'm doing it right.

## Context
Forwarding from the main Graylog cluster a small set of messages (around 20 to 500msg/s)

I wrote a small flask RESTful API and added the HTTP JSONPath on Graylog.

This is the code:
```python
from flask import Flask, request
from flask_restful import Resource, Api
from json import dumps
import re

# RESTful API to transform Cray cname to nid
# EXAMPLE: c8-2c0s4n1 correspond to  the node 5393 and nid05393
# Usefull to identify jobs per compute node on slurm logs.

app = Flask(__name__)
api = Api(app)

# Number of XC50 Cabinets in a row
CABINET_ROW = 10

class cname_to_nid(Resource):
    def get(self,cray_cname):
        #checking the cray_cname pattern
        pattern = re.compile('^~?c(\d+)-(\d+)c([0-2])s(\d|1[0-5])n([0-3])')
        if pattern.match(cray_cname):
            #Groupping to extract values
            m = re.search('^~?c(\d+)-(\d+)c([0-2])s(\d|1[0-5])n([0-3])', cray_cname)
            #Calculating the node Number
            nid_calc = (int(m.group(1))*192)+(int(m.group(2))*192*CABINET_ROW)+(int(m.group(3))*64)+(int(m.group(4))*4)+(int(m.group(5)))
            nid = "nid" + str(nid_calc).zfill(5)
            return {'cray_nid' : nid}
        #if the pattern is not a Cray cname just retun None
        else:
            return {'cray_nid' : None}


api.add_resource(cname_to_nid, '/nid/<string:cray_cname>')

if __name__ == '__main__':
    app.run(debug=False,host='0.0.0.0')

```

### org.graylog2.inputs.extractors.LookupTableExtractor.lookup_table.77b04900-3bc4-11e7-895b-005056ac66ea.completeExecutionTime
```
95th percentile: 12,622μs
98th percentile: 13,940μs
99th percentile: 15,391μs
Standard deviation: 4,074μs
Mean: 8,700μs
Minimum: 1,966μs
Maximum: 49,863μs
```
### org.graylog2.inputs.extractors.LookupTableExtractor.lookup_table.77b04900-3bc4-11e7-895b-005056ac66ea.conditionHits
```
Value: 0
```
### org.graylog2.inputs.extractors.LookupTableExtractor.lookup_table.77b04900-3bc4-11e7-895b-005056ac66ea.conditionMisses
```
Value: 0
```
### org.graylog2.inputs.extractors.LookupTableExtractor.lookup_table.77b04900-3bc4-11e7-895b-005056ac66ea.conditionTime
```
95th percentile: 1μs
98th percentile: 1μs
99th percentile: 1μs
Standard deviation: 0μs
Mean: 0μs
Minimum: 0μs
Maximum: 23μs
```
### org.graylog2.inputs.extractors.LookupTableExtractor.lookup_table.77b04900-3bc4-11e7-895b-005056ac66ea.converterExecutionTime
```
95th percentile: 0μs
98th percentile: 0μs
99th percentile: 0μs
Standard deviation: 0μs
Mean: 0μs
Minimum: 0μs
Maximum: 16μs
```
### org.graylog2.inputs.extractors.LookupTableExtractor.lookup_table.77b04900-3bc4-11e7-895b-005056ac66ea.executionTime
```
95th percentile: 12,556μs
98th percentile: 14,251μs
99th percentile: 15,917μs
Standard deviation: 3,732μs
Mean: 8,695μs
Minimum: 1,797μs
Maximum: 62,241μs
```

### org.graylog2.lookup.adapters.HTTPJSONPathDataAdapter.httpRequestErrors
```
Meter
Total: 171,834 events
Mean: 2.18 events/second
1 minute avg: 0.01 events/second
5 minute avg: 0.02 events/second
15 minute avg: 0.01 events/second
```
### org.graylog2.lookup.adapters.HTTPJSONPathDataAdapter.httpRequestTime
```
Timer
95th percentile: 13,833μs
98th percentile: 15,221μs
99th percentile: 16,431μs
Standard deviation: 3,435μs
Mean: 9,016μs
Minimum: 1,321μs
Maximum: 33,992μs
```
### org.graylog2.lookup.adapters.HTTPJSONPathDataAdapter.httpURLErrors
```
Meter
Total: 0 events
Mean: 0 events/second
1 minute avg: 0 events/second
5 minute avg: 0 events/second
15 minute avg: 0 events/second
```

## Your Environment

* Graylog Version: 2.3.0-alpha.2
* Elasticsearch Version: 5.4.0
* MongoDB Version: 3.2.10
* Operating System: CentOS 6.8

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
