### ISSUE TITLE
Unable to create HTTP Lookup Adapter

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog2-server#3856]
Graylog Version: 2.3.0-alpha.2
Elasticsearch Version: 2
Operating System: Ubuntu 16.04

I have successfully created a CSV and Geo lookup adapter, but when trying to create a HTTP adapter I click the 'Create Adapter' button after entering the settings but nothing happens.

As a aside, I am looking to use this feature to create a 'watch list' for IP addresses.  The data will only be a single column of addresses - would this format be supported (i.e. a 'if exist' lookup rather than a 'return' lookup)? If not I can just add a second column and enter a common return value i.e.

1.2.3.4,"True"
2.3.4.5,"True"
3.4.5.6,"True"

Thanks

**Comment by kroepke** [comment]
The single value of an empty lookup will be `null`, so in pipelines it can be checked with an `is_null` function if you need to.
We'll release a beta soon, please test the HTTP adapter again with that. There might've been bugs in the alpha's that we didn't catch before release.

**Comment by kroepke** [comment]
IOW this should work:
```
rule "check_ip_watchlist"
when 
  is_not_null(lookup("ip_watchlist", $message.ip_field))
then
end
```
Then you should be able to use the rule as a gate for later stages of a pipeline.

**Comment by bernd** [comment]
I am unable to reproduce the HTTP lookup adapter creation issue with the latest 2.3.0-alpha.4 snapshot. Please try the upcoming 2.3.0 beta release and re-open this one if you still see the problem. Thank you!
