### ISSUE TITLE
Customized Stream Ordering

### ISSUE THREAD

**Issue by packs** [Graylog2/graylog2-server#3869]
We are using streams to handle differing retention schedules that apply based on the contents and sources of the same classes of log. An example is:

- Messages that match: "EventID: 4634" AND "source: /appsrv[0-9].srv/" AND "TargetUserName: /[a-z][a-z][0-9]+-[0-9]+/" are saved into index set 30day
- All other messages that match: "EventID: 4634" are saved into index set 365day
- All other messages are saved into index set 90day

Crafting stream match rules for these requirements ends up with almost unmaintainable levels of matching rules. A preferable solution would be to specifically define the order in which streams are processed

**Comment by jalogisch** [comment]
@packs you might want to add some kind of identify via pipelines - this way you only need to have 3 streams to match your requirement ...

**Comment by packs** [comment]
@jalogisch That may be possible. I haven't quite wrapped my head around the pipeline system enough to figure out how to use them yet. Maybe this will be my motivating example.

**Comment by joschi** [comment]
@packs 
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
