### ISSUE TITLE
Re-open an index does not work with Elasticsearch 5.x

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#3871]
## Expected Behavior

The user should be able to re-open an index.

## Current Behavior

When I try to re-open a closed index, it does not work and the request sliently fails. (no UI feedback) The browser console shows this error:

```json
{
  "message": "Couldn't update settings of index graylog_20\n\nunknown setting [index.graylog2_reopened] please check that any required plugins are installed, or check the breaking changes documentation for removed settings",
  "details": [
    "unknown setting [index.graylog2_reopened] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
  ]
}
```

## Steps to Reproduce (for bugs)
1. Run Graylog 2.3.0-alpha.3 with an Elasticsearch 5.x node
2. Close an index
3. Try to re-open the closed index

## Context

Graylog is using a custom index setting as an indicator for re-opened indices. (see [Indices.java](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java#L502-L515)) As far as I can see, custom index settings are not supported anymore in Elasticsearch 5.x.

Old indices which have been upgraded from Elasticsearch 2.x moved the `index.graylog2_reopened` setting into the `archived` namespace. (see [AbstractScopedSettings.java](https://github.com/elastic/elasticsearch/blob/5.4/core/src/main/java/org/elasticsearch/common/settings/AbstractScopedSettings.java#L544-L547) in the Elasticsearch source code)

That means Graylog cannot detect existing, re-opened indices anymore and cannot set the indicator when re-opening closed indices.

```json
{
  "graylog_17": {
    "settings": {
      "archived": {
        "index": {
          "graylog2_reopened": "true"
        }
      },
      "index": {
        "routing": {
          "allocation": {
            "total_shards_per_node": "2"
          }
        },
        "number_of_shards": "4",
        "blocks": {
          "write": "true",
          "metadata": "false",
          "read": "false"
        },
        "creation_date": "1465380847575",
        "analysis": {
          "analyzer": {
            "analyzer_keyword": {
              "filter": "lowercase",
              "tokenizer": "keyword"
            }
          }
        },
        "number_of_replicas": "0",
        "uuid": "Sv8V1DFZSpWZIV6LQIedEA",
        "version": {
          "created": "2030199",
          "upgraded": "5040099"
        }
      }
    }
  }
}
```

## Your Environment

* Graylog Version: 2.3.0-alpha.4-SNAPSHOT (7bd4d1482)
* Elasticsearch Version: 5.4.0

**Comment by dennisoelkers** [comment]
I guess for remediation we would need to do two things:

  * enhance the check for a reopened index to include the `archived` namespace
  * persist the `reopened` flag somewhere else (realistically only MongoDB is in question) for future indices, possibly part of the index ranges

**Comment by kroepke** [comment]
I guess moving this information into mongodb is the only sane option, yes.

I would prefer a migration that copies the state contained in the index settings into the index ranges and changing the re-open checks to only using that, to minimize the range of checks necessary, thus old indices as well as new ones would be consistent in their handling

**Comment by dennisoelkers** [comment]
I have implemented a fix that does not move the flag into the `IndexRange` collection, but uses an alias (`<index name>_reopened`) instead. This way we still maintain a complete picture of the index sets in Elasticsearch and can reconstruct its state without requiring the contents of the MongoDB.
