### ISSUE TITLE
Graylog input started running exactly 1 hour behind

### ISSUE THREAD

**Issue by ckozler** [Graylog2/graylog2-server#3879]
This was working entirely fine yesterday. I look today and it appears that the input is running behind
  
The only change done was adding more flow towards this input (SYSLOG UDP port 5542) between yesterday and today. Now, ALL messages to this input are showing up exactly 1 hour later. I have no idea why
  
**tcpdump from the server showing messages coming in with correct time**: http://i.imgur.com/Ns7EM0v.png
  
**confirming my date is right on my router**: http://i.imgur.com/LzA4cJT.png
  
**configuration of the input**: http://i.imgur.com/bS1lmJp.png - overriding of the date stamp is selected in the configuration. However, as noted, this was working before the increased flow. 
  
**time configuration from overview screen**: http://i.imgur.com/MFUf9s3.png
  
I have dedicated one host (my router) to send to this input, and nothing else. After adding the additional flow (RT_FLOW / traffic logs), this input is exactly 1 hour behind

I can confirm its exactly one hour behind because I can select the source (or input) in search, pick "2 hours ago", and then see messages for that source/input. Clicking search again brings up another message exactly 1 hour ago
  
No changes to the graylog server since this was initially setup months ago
  
Any idea on where to look? I am stumped. Should I delete and recreate the input??

Running version Graylog 2.1.3+040d371

All other inputs still operating correctly

**Comment by ckozler** [comment]
This is interesting...I deleted the input and created a new one on same port and same configuration. Now for some reason it is almost 1 hour and 25 minutes behind, so I doubt its any type of time configuration.

The main graylog process is at ~500-600% CPU (so 6 cores) 

The server has 8 vCPU and current load average is ~7 across 1, 5, and 15 interval

Should I add more vCPU? This is a VM running

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

You might have messages in your Graylog Journal that are coming in - you should check that.

Thank you!
