### ISSUE TITLE
Pipeline rule Exception calling function 'clone_message'

### ISSUE THREAD

**Issue by gianluca-valentini** [Graylog2/graylog2-server#3880]
## Expected Behavior
I wrote a rule where I clone the default message using the function **clone_message**.  I expected that the message is cloned so that I can route it to another Stream. 

## Current Behavior
Here my rule:
```
rule "function Route Message"
when
  true
then
 let mess = clone_message();
 set_field(field: "tag", value: "Cloned", message: mess);
 
route_to_stream(name: "MyStream2", message: mess);
end
```
When I use the function clone_message and I simulate it's processing using a pipeline I have the error message below:

> gl2_processing_error
> For rule 'function Route Message': In call to function 'clone_message' at 5:12 an exception was thrown: Cannot cast java.lang.String to org.joda.time.DateTime.

## Steps to Reproduce (for bugs)
1. Write a simple rule that clone the message and route it. I used [ClonedMessage.txt](https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/2.2/plugin/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/clonedMessage.txt) as example to start my rule
2. Add the rule to a pipeline to simulate it's processing
3. The error message is showed

## Your Environment
* Graylog Version:  2.2.3
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Graylog official docker container
* Browser version:

**Comment by bernd** [comment]
@gianluca-valentini We will track this as a bug, because you shouldn't get a cast error when the timestamp is in the wrong format.

The problem here is, that your timestamp in the message object is not an actual timestamp type but a string. You probably use an extractor or another pipeline rule where you extract the timestamp but do not convert it to an actual timestamp object. Converting the timestamp will avoid this error.

**Comment by gianluca-valentini** [comment]
@bernd 
thanks for your answer.  I'm using File Beats as input and in the Stream I can see the event with the timestamp written as below:
**timestamp 2017-06-19T15:33:26.360Z**

And I just apply the pipeline. 
So are you saying that the timestamp that I see in the stream is a String? In this case this could be a File Beat compatibility error?

Thanks

**Comment by joschi** [comment]
@gianluca-valentini 
> So are you saying that the timestamp that I see in the stream is a String?

A string or any other data type (but string is most likely).

> In this case this could be a File Beat compatibility error?

Unlikely, because other people would've noticed by now.
I guess it's some other extractor or rule in your message processing pipeline.
