### ISSUE TITLE
New feature, role permission to create streams

### ISSUE THREAD

**Issue by perbly** [Graylog2/graylog2-server#3882]
Hi

I would be nice to have a role that have create stream permissions. Right now this is only admins that can do and my users aren´t ready to be admin. There´s to much things you can break.

Regards
Per Bly

**Comment by jalogisch** [comment]
Hej @perbly 

you need to use the API to create such a role yourself. One example can be found [in the FAQ](http://docs.graylog.org/en/2.2/pages/faq.html#how-can-i-create-a-restricted-user-to-check-internal-graylog-metrics-in-my-monitoring-system)

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
