### ISSUE TITLE
How to hide or disable system menu for non-admin user?

### ISSUE THREAD

**Issue by jun283** [Graylog2/graylog2-server#3883]
#Graylog 2.2.3+7adc951 on graylog (Oracle Corporation 1.8.0_101 on Linux 3.13.0-115-generic)

**Comment by dennisoelkers** [comment]
There is currently no way to hide the system menu completely. In general, the web interface only shows actions which are executable with the permission set of the current user. The "System" menu does not contain only actions which are executable for admin users, some functions (like the "Overview") also offer reduced versions for non-admin users.

Why do you want to hide the system menu completely?

**Comment by jun283** [comment]
I create a login account for my customer, He can see all system/Input list

I do not want him to see the info that does not belong to him

**Comment by dennisoelkers** [comment]
@jun283: You can create a role without the `inputs:read` permission, in that case the `System/Inputs`  menu action will not be visible/executable.
