### ISSUE TITLE
Missed Alert Triggers for Events Closely Following an Alert Scan

### ISSUE THREAD

**Issue by YoichSec** [Graylog2/graylog2-server#3884]
![alerts](https://cloud.githubusercontent.com/assets/26263951/26741802/bb61b392-478f-11e7-910f-50be3c7733c5.png)
![alertevents](https://cloud.githubusercontent.com/assets/26263951/26741801/bb5e1df4-478f-11e7-93d2-ef536b764a80.png)
[debuglog.txt](https://github.com/Graylog2/graylog2-server/files/1048756/debuglog.txt)

## Expected Behavior

Events matching an alert condition should trigger alerts consistently.

## Current Behavior

Events that immediately follow the AlertScanner fail to properly trigger alerts. This is possibly due to the one-second resolution of events while the AlertScanner does not reach back to the full second prior to the beginning of its search window.
Please see the attached files for an explanation:
debuglog.txt shows the periodic debug output from the AlertScanner. The first and last timeframes trigger an alert.
alertevents.png shows the events sent to graylog that should have triggered an alert. The first and last ones did. The rest were sent within one second of the debug messages showing up in the log. Notice the timestamp of the events would indicate that the events arrived immediately before the AlertScanner ran, though I sent them after. This makes me believe they may have fallen outside of the AlertScanner's search window, thus failing to trigger an alert.

## Possible Solution

Fix the search window for the AlertScanner to ensure that all appropriate events are included. Possibly specify whole-second start and end times.

## Steps to Reproduce (for bugs)

1. Create a field-content alert condition. (Other conditions will likely behave the same)
2. Tail the graylog log with debug output enabled.
3. Send test events matching the alert conditions immediately after the AlertScanner runs.
4. Verify that the events arrive in graylog with timestamps before the timestamps in the debug logs.
5. Verify that the alert fails to trigger.
6. Send the same event, but not immediately after the AlertScanner runs.
7. Verify the alert is triggered.

Doing 2-5, I can consistently get alerts to not trigger when they should. This happens by chance in normal operation.

## Context

Alerts do not trigger consistently when they should. If the diagnosis above is correct, this is worse for smaller alert intervals where near-real-time alerting is required.

## Your Environment

* Graylog Version: 2.1.1, 2.1.3
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Ubuntu
* Browser version:

**Comment by bernd** [comment]
This should be fixed with the new events and alerts system. Please open a new issue if you still see problems. Thank you!
