### ISSUE TITLE
"Found messages" maxes out at 150

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#3886]
Any search result that returns more than 150 messages is showing "Found 150 messages [...]" in the sidebar. I suspect that Elasticsearch 5 started to return the number of returned messages (we return 150 per page) and not the total search result count over all pages.

* Graylog Version: 2.3.0-alpha.2+f24e575
* Elasticsearch Version: 5.3

**Comment by fadenb** [comment]
Is this a duplicate of https://github.com/Graylog2/graylog2-server/issues/3813 ?

**Comment by lennartkoopmann** [comment]
Good catch! It is. :)
