### ISSUE TITLE
All configs are gone

### ISSUE THREAD

**Issue by WoLfulus** [Graylog2/graylog2-server#3887]
We were trying graylog and had setup a graylog server on AWS, several inputs and several streams, nothing too complicated. Added several dashboards, and everything was ok, and all of a sudden, all graylog settings just disappeared, no users, streams, inputs and dashboards.

I restarted the service with `graylog-ctl restart` and after logging into the web interface again, graylog said that I had to rebuild the indexes, I did that and still nothing showing up, though I could see the document count (through graylog web interface).

Any ideas how to bring the configs back? Or why they simply vanished?

* Graylog Version: Graylog 2.2.3+7adc951 on graylog (Oracle Corporation 1.8.0_101 on Linux 3.13.0-115-generic)
* Elasticsearch Version: 2.4.2, Lucene 5.5.2
* MongoDB Version: 3.4.1
* Operating System: Ubuntu 14.04.5 LTS
* Browser version: Chrome 58.0.3029.110 (64-bit)

**Comment by jalogisch** [comment]
@WoLfulus 

did you expose your mongoDB to the world? That sounds like you had opened that and someone just dropped the Database.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
