### ISSUE TITLE
Add automatic update settings to query parameters

### ISSUE THREAD

**Issue by cjbhaines** [Graylog2/graylog2-server#3888]
I have a small feature request for you. When you query Graylog, everything you do gets added to your URL which makes it easy for sharing, that is: search terms, time period, etc. However, the auto refresh settings here are not added to the query URL:

![image](https://cloud.githubusercontent.com/assets/3225747/26765363/8fef8920-4972-11e7-9158-226e7fcb816c.png)

This means that if I refresh the page or send the query to a colleague, then you have to reselect the auto refresh options again which gets a little frustrating. 

Would you be able to add these settings to the query parameters as they are changed please?

As a nice to have:

Perhaps a default could be set for the user account which would apply to all queries. I really like the auto refresh feature so I would ideally like it permanently on by default.

**Comment by darraghjones** [comment]
+1

**Comment by dennisoelkers** [comment]
This has been (partially) fixed in `3.2.0`, by introducing the big display mode feature, which allows you to pre-configure auto-refresh settings and generates a sharable URL, which is super handy for unattended/tv setups.
