### ISSUE TITLE
No ability to set widget position via API

### ISSUE THREAD

**Issue by edgarswed** [Graylog2/graylog2-server#3889]
When creating widgets on dashboard via API there are no possibility to adjust their position via API call. So when trying to automate dashboard creation you will end up with trashed dashboard, which can be sorted only in manual mode via web interface.

## Expected Behavior
Would be nice to have possibility to set widget size/position during creation via API call or adjust it after also via API call.

## Your Environment
* Graylog Version:  2.2.3+7adc951
* Elasticsearch Version: 2.4.5
* MongoDB Version: 1:2.4.10-5+deb8u1
* Operating System: Debian 8.8 4.9.25-1~bpo8+1
* Browser version: Chromium Version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by edmundoa** [comment]
Hi @edgarswed,

All we do in the web interface is using the REST API Graylog provides, so it's already possible to set widgets positions for a dashboard. Take a look at the `/dashboards/{dashboardId}/positions` request in your API browser. You can find more information about the body for that request in here: https://github.com/Graylog2/graylog2-server/blob/5c8db63e2bfacd0bb702b0b9deb7a31aa2daa2c6/graylog2-server/src/main/java/org/graylog2/rest/models/dashboards/requests/WidgetPositionsRequest.java
