### ISSUE TITLE
Cannot install graylog2 ubuntu 16!!

### ISSUE THREAD

**Issue by juanpscotto** [Graylog2/graylog2-server#3900]
I followed this instructions to install graylog 2:

`
$ wget https://packages.graylog2.org/repo/packages/graylog-2.2-repository_latest.deb
$ sudo dpkg -i graylog-2.2-repository_latest.deb
$ sudo apt-get update && sudo apt-get install graylog-server
`

but when I run sudo apt-get update  it does not find the graylog2 package, it points to nothing:

`
Failed to fetch https://packages.graylog2.org/repo/debian/dists/stable/InRelease  Could not resolve host: packages.graylog2.org
`

**Comment by juanpscotto** [comment]
Anybody ?

**Comment by edmundoa** [comment]
Hi,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
