### ISSUE TITLE
Elasticsearch Cluster Unavailable on Graylog version 2.2.3

### ISSUE THREAD

**Issue by ZER0lPT** [Graylog2/graylog2-server#3902]
I've installed what seems to be the newest version (2.2.3) with Elasticsearch  2.4.4 but when I access the web interface I get this annoying error that I've been trying to fix for a while now.

Here is my Elasticsearch log.
https://pastebin.com/S1QGpgdV

And here is the curl result: 
https://pastebin.com/4MvnT8JR

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by ZER0lPT** [comment]
The cluster name is the same for both and it still didn't solve the problem sadly.

**Comment by joschi** [comment]
@ZER0lPT Please continue this discussion in the community forums.
