### ISSUE TITLE
Search completion is slow when there is a lot of fields

### ISSUE THREAD

**Issue by Azenet** [Graylog2/graylog2-server#3912]
I have a lot of fields in my graylog indexes because of pipeline json extraction (in QueryInput.ts, `this.fields.length` is 220898), and that makes typing a search very painful. Below is a screenshot of 1 keypress event, captured in Google Chrome's Inspector performance tab.

![](https://i.imgur.com/dQTD4nD.png)

## Expected Behavior
Typing should not be slow because of search completion when having a lot of fields

## Current Behavior
Typing is very slow because of search completion when having a lot of fields

## Possible Solution
- add a switch to disable search completion altogether
- exclude fields in completion with a regex/a pattern
- use a keyboard shortcut to call completion on an incomplete word like an IDE would

## Steps to Reproduce (for bugs)
1. Have a lot of fields
2. Type a search on the web interface

## Your Environment
* Graylog Version: 2.3.0-alpha.3+c795033 under Docker
* Elasticsearch Version: 5.4.0
* MongoDB Version: 3.4.4
* Operating System: Linux/Debian 8
* Browser version: Chrome 59

**Comment by edmundoa** [comment]
Hi,

Sorry to hear you have troubles with the search completion.

For your information, there's already a user preference to disable it in _Username_ (in the upper right corner) _-> Edit profile -> User preferences_. There you need to set the `enableSmartSearch` to `false` and save the changes. You may need to refresh your browser to actually apply the new configuration option.

I hope that helps.

**Comment by Azenet** [comment]
@edmundoa had no idea, thanks! joschi didn't know about it on IRC which is why I opened the ticket.

**Comment by stephennancekivell** [comment]
FWIW. Im still having this issue in graylog 3.3.4. Turning off the smart search was the best thing I ever did.

**Comment by dennisoelkers** [comment]
This should not happen anymore in the new search. Please reopen if it's still an issue!
