### ISSUE TITLE
Cannot search, log in, anything following upgrade from 2.1.3 to 2.2.3

### ISSUE THREAD

**Issue by wrsuarez** [Graylog2/graylog2-server#3916]
## Expected Behavior

Able to log in and use the interface
## Current Behavior

Can't log in, getting 401 error in an incognito window. Hitting the node api and providing credentials allows me to log in but then I can't search for anything as theres an error message about unable to load saved searches
## Steps to Reproduce (for bugs)

1. Upgrade RPM from 2.1.3 to 2.2.3
2.
3.
4.

## Context

Upgrade from 2.1.3 to 2.2.3
## Your Environment

* Graylog Version: 2.2.3
* Elasticsearch Version: elasticsearch-2.4.1-1.noarch
* MongoDB Version: 3.2
* Operating System: CentOS 7.3
* Browser version: Chrome, Safari, etc

**Comment by wrsuarez** [comment]
![screen shot 2017-06-14 at 10 24 56 am](https://user-images.githubusercontent.com/5407533/27146545-8d5dfe7a-50ee-11e7-8aab-69837bdcb029.png)

**Comment by wrsuarez** [comment]
![screen shot 2017-06-14 at 10 19 18 am](https://user-images.githubusercontent.com/5407533/27146551-96f7c542-50ee-11e7-9897-2acee1336fd3.png)

**Comment by wrsuarez** [comment]
I also cannot get a response from any web page. I can get the data from the API but not from the web interface:
<img width="1023" alt="screen shot 2017-06-14 at 11 54 35 am" src="https://user-images.githubusercontent.com/5407533/27149399-45eb8706-50f8-11e7-8f35-dfdbcb65eb62.png">
<img width="1436" alt="screen shot 2017-06-14 at 11 53 56 am" src="https://user-images.githubusercontent.com/5407533/27149398-45e9c380-50f8-11e7-9505-5aec56db3ac4.png">

**Comment by wrsuarez** [comment]
Curiously dashboards seem to work, So does the Overview page and it does look like the system is indexing new messages correctly so basically the web UI is completely hosed but the APIs are working

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
