### ISSUE TITLE
users timezone is reset to UTC after adding roles

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#3918]
## Expected Behavior
Adding roles to ldap auth users should not change the timezone of the users.

## Current Behavior
When adding roles to Users that are authenticated via LDAP the timezone for this user is set to UTC.

## Steps to Reproduce (for bugs)
1.  A newly logged in LDAP user is set with the correct timezone which is configured in the server.conf file.
2.  While editing the User's Streams and Dashboards permissions, the timezone remains correct.
3.  As soon as roles are added to the user and the Update role button is clicked, the timezone is automatically changed to UT

## Your Environment
* Graylog Version: 2.1.3

**Comment by joschi** [comment]
I could verify that problem, although it has nothing to do with LDAP.

The problem occurs for every user, no matter how the account was created.

Clicking on the "Update role" button in the Graylog web interface (System / Authentication / Users / Edit User) will send an empty user to the Graylog REST API. The other way round, clicking on the "Update user" button, is also broken and sends an empty `roles` list to the Graylog REST API.
