### ISSUE TITLE
Process slowly with low cpu usage

### ISSUE THREAD

**Issue by darouwan** [Graylog2/graylog2-server#3923]
I am setting up a graylog server on a unique machine which has 64 cores E5 2698 CPU and 384GB memory. But the processing speed is not good as my expected. 

I generate a large sum of message with input and fill up the disk journal. As we expected, the process buffer is fully filled, and the graylog server should run in full speed.  

However, the output speed is just about 12000 msg/s at most, while the input speed is 50000msg/s.

If the bottleneck is the computing resource,  the cpu usage should be high. I have checked the system usage , where cpu usage is about 20%, memory used is 20%,  disk writing speed and network io usage is also very low.  So it seems graylog doesn't make full use of my server. 

* Graylog Version: 2.2.0
* Elasticsearch Version: 2.4.3
* MongoDB Version: 3.2
* Operating System: Centos 6.7  64bit
* Browser version: chrome

**Comment by jalogisch** [comment]
@darouwan did you raise the JVM Heap? If yes to what value?

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by darouwan** [comment]
Thanks. I have solved it by change the disruptor strategy to YieldingWaitStrategy
