### ISSUE TITLE
Extractor can't access other fields

### ISSUE THREAD

**Issue by ScreamZ** [Graylog2/graylog2-server#3928]
Hello,

I would like to know if you have a solution for this topic on the deprecated repository
https://github.com/graylog-labs/graylog2-web-interface/issues/798

Or do you have a good pattern to handle that ?

---
One solution could be to apply extractors on stream, or have a reference on others fields in one extractor ?

Best regards

**Comment by jalogisch** [comment]
Hello @ScreamZ 

you should use the processing pipelines: http://docs.graylog.org/en/2.2/pages/pipelines.html

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
