### ISSUE TITLE
Index failures message looks different since 2.3

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#3933]
## Current Behavior

The index failures view looks different since Graylog 2.3:

![image](https://user-images.githubusercontent.com/461/27480287-a02d7f00-5817-11e7-8d6e-e1f4360b787a.png)

The message is a JSON string now.

## Possible Solution

The question is if we want to keep it like this or if we want to change it to make it look similar to previous versions.

## Steps to Reproduce (for bugs)

1. Index something that triggers an index failure
2. Go to "System/Overview" and show index failures

## Your Environment

* Graylog Version: 2.3.0-alpha.4-SNAPSHOT+0c4df85
* Elasticsearch Version: 2.3.5

**Comment by jalogisch** [comment]
we consider that the new output is much more useful and close this.
