### ISSUE TITLE
User from reader role, can delete alerts conditions from stream that had only viewer permission

### ISSUE THREAD

**Issue by fernando360** [Graylog2/graylog2-server#3935]
A user that has only reader permissions on a stream, can delete alerts conditions from this stream.

## Expected Behavior
That user cannot delete alerts conditions from those stream that had reader permission.

## Current Behavior
That user CAN delete alerts conditions from those stream that had reader permission.

## Possible Solution
Remove Delete option from this context.

## Steps to Reproduce (for bugs)

1. From a admin user create a alert condition to a stream.
2.Create a user within reader role
3. Provide reading permission on a stream.
4. Log as these user 
5. Delete those alert condition

## Context
I need a reader user.
Because if is possible to delete the email alerts, that user could hide his tracks.

## Your Environment

* Graylog Version:  2.2.3+7adc951
* Elasticsearch Version: 2.4.5

**Comment by bernd** [comment]
This is due to a wrong permission check in the REST resource. It will be fixed once https://github.com/Graylog2/graylog2-server/pull/3936 gets merged.
