### ISSUE TITLE
Best method for sync mirror

### ISSUE THREAD

**Issue by reflectivedevelopment** [Graylog2/graylog2-server#3939]
It should be relatively easy to sync graylog mirror that hosts RPMs and deb files.

Cannot Rsync or sync via HTTP

Can we sync via Amazon S3?

This is related to #2329

**Comment by jalogisch** [comment]
Currently we do not have any plans to switch away from s3.

The only option you might use would be `wget -r ...` - yes that is not the best solution but currently the only usable.
