### ISSUE TITLE
How to control access to Elasticsearch ports

### ISSUE THREAD

**Issue by TsubasaChin** [Graylog2/graylog2-server#3940]
In Graylog's doc,it says "Since Elasticsearch has no authentication mechanism at time of this writing, make sure to restrict access to the Elasticsearch ports (default: 9200/tcp and 9300/tcp). Otherwise the data is readable by anyone who has access to the machine over network."
My question is if we had added a http authentication mechanism to Elasticsearch to control different users to access Elasticsearch service,how can we make corresponding changes at the Graylog side?Add some configuration?Change the codes?
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by jalogisch** [comment]
Graylog Version 2.2 does not have this option as it does not have the option. With the upcoming 2.3 release this need to be included into the URI please [look at the documentation](http://docs.graylog.org/en/2.3/pages/configuration/elasticsearch.html)

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
