### ISSUE TITLE
2.3 Beta - "Could not retrieve the lookup tables" Error

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog2-server#3945]
Hi,

Have upgraded to: 2.3.0-beta.1+7295064

When I go to the Lookup Tables page I get a red 'pop up' error as below:-

**Could not retrieve the lookup tables
Fetching lookup tables failed: IOException encountered while reading from a byte array input stream**

Rgds

**Comment by bernd** [comment]
@urban-moniker Did you upgrade from a 2.3-alpha release? If so, you have to clear your `lut_tables`, `lut_caches` and `lut_data_adapters` collections in MongoDB. The data format has changed.

**Comment by urban-moniker** [comment]
Thanks.

I did upgrade from the alpha - just to check, I need to do this natively in MongoDB?

Rgds

**Comment by bernd** [comment]
@urban-moniker Yes, you can use the mongo shell for that. Sorry for the inconvenience, but this might happen during alpha releases. :wink:

**Comment by urban-moniker** [comment]
Thanks, no worries.

PS The beta release did fix a closed issue I raised - #3856

**Comment by bernd** [comment]
@urban-moniker Great! Thanks for letting us know. :smiley: 

I am closing this issue now, please let us know if you still have problems. Thank you!
