### ISSUE TITLE
LDAP should use a directory entry for user name instead of the one user types

### ISSUE THREAD

**Issue by jtkkex** [Graylog2/graylog2-server#3946]
With LDAP/AD authentication, Graylog uses the login name user enters as user account name.  With Microsoft AD it is customary to allow users to login with their short account name, userPrincipalName or mail address, and the LDAP query used in Graylog supports a search string that allows this.

The problem is that Graylog creates a different user account for each of these authentication methods.

## Expected Behavior

Graylog should let AD/LDAP authenticate the user and tell Graylog what is the real user login name, instead of the one user enters.  

## Steps to Reproduce (for bugs)

1. add LDAP authentication
2. add a query, such as (&(group=users)(|(userPrincipalName={0})(mail={0})))
3. test with different authentication options, and see how Graylog creates new accounts for each

## Your Environment

* Graylog Version: 2.2.3
* Operating System: CentOS7
* Browser version: Chrome

**Comment by jtkkex** [comment]
Solving this might also solve issue [https://github.com/Graylog2/graylog2-server/issues/1361](url)

**Comment by bernd** [comment]
This will be fixed in the upcoming 4.0 release.
