### ISSUE TITLE
Trying to login with admin user but failed

### ISSUE THREAD

**Issue by eoinkim** [Graylog2/graylog2-server#3947]
## Expected Behavior

After password_secret and root_password_sha2 have been set, admin login would be successful on the web.

## Current Behavior

The web interfaces says 'Invalid credentials, please verify them and retry.'

## Steps to Reproduce (for bugs)

1. I followed this - http://docs.graylog.org/en/2.2/pages/installation/os/debian.html
2.
3.
4.

## Context

At this stage, I want to test if this product is good for our production. However, the very first step is not working. Maybe I am missing something.

## Your Environment

* Graylog Version: 2.2.3-1
* Elasticsearch Version: 2.4.5
* MongoDB Version: 1:2.4.10-5+deb8u1
* Operating System: Debian Jessie - 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux
* Browser version: Firefox 52.0.1 (64-bit) for Ubuntu

**Comment by eoinkim** [comment]
Just tried again from scratch (install OS, follow the steps in documentation) and it works this time. It is strange but I'll say that I forgot something in the first trial.

**Comment by joschi** [comment]
@eoinkim Thanks for the follow-up. I'll close this issue.
