### ISSUE TITLE
Disable Histogram On Search Page

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#3954]
## Expected Behavior
Have the option to disable the default histogram on the search page and only show the message result table.

## Current Behavior
The histogram is always visible. 

## Possible Solution
Have the option on a user level or role level to disable the histogram.

## Context
If the user just like to have the log files for the search, without distraction and to use more of the available screen space having the option to disable the histogram is a valid option.

**Comment by bernd** [comment]
This is possible with the new search page.
