### ISSUE TITLE
Configurable Query For Histogram Widget

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#3955]
## Expected Behavior
All widgets on a dashboard should have the option to edit the query that they are the source of.

## Current Behavior
When you had added the histogram to a dashboard you are not able to edit the query. Instead you need to redo the search manual and then add the histogram again and remove the other.

## Possible Solution
Add the option for the query on histograms in dashboards

## Context
Histograms are only showing the amount of messages over time from a specific search. That is true if that histogram is shown above a result set of a search, but having that widget on a dashboard the user need to be able to edit the search like for any other widget.

**Comment by aremai** [comment]
Hi @jalogisch 

it would also be good to be able to click on the stacked values to see the log events.
When I hover with the mouse over such a stacked graph it shows me "50 messages", however I'm unable to see those 50 messages.

**Comment by edmundoa** [comment]
Testing 3.0.0 I also came to find this issue. The map widget is also missing a query input field.

**Comment by bernd** [comment]
This is now possible with the new search page widgets.
