### ISSUE TITLE
Group By Function For Stacked Charts

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#3956]
## Expected Behavior
Having a group by function to create a chart for the response time of apps (for example), hit `group_by(app_name)` and be done.

## Current Behavior
To have a stacked chart that holds multiple data you need to run the query for the first, create a chart of that response, make a new query and create a chart for that response and stack that. Such you need todo for every line you like to have in that chart.

Having multiple stacked charts on different dashboards makes changes in that a pain.

Every stacked chart need to be created new if something should be removed or got renamed.

## Context
Some information stacked together make it easy to spot abnormal behavior. When the information from log files are used for monitoring it would make this more useful and user friendly.

**Comment by bernd** [comment]
This is possible with the new search page.
