### ISSUE TITLE
SSL/TLS for Kafka inputs

### ISSUE THREAD

**Issue by ghost** [Graylog2/graylog2-server#3960]
Apparently it is not possible to use SSL/TLS for Kafka inputs in latest version or there is not documentation for it.

## Expected Behavior
Kafka inputs should allow SSL for accessing to server. 

## Current Behavior
There is no option related to SSL/TLS in Kafka inputs

## Possible Solution
No Idea :)

## Context
This feature is important when you want to transfer log data across the globe and don't want unwanted access from wiretappers. 

## Your Environment
We have multiple sites in different locations, each site stores all data in a Kafka server and one graylog server connects to each site and reads log data.

* Graylog Version: Graylog 2.2.3

**Comment by tokred** [comment]
Would be highly appreciated to fulfill regulatory and compliance requirements!

Best regards

**Comment by k1-hedayati** [comment]
@tokred sorry I didn't understand what you mean

**Comment by joschi** [comment]
@k1-hedayati I think @tokred simply wants to express some approval of this feature request.

**Comment by k1-hedayati** [comment]
So I guess this doesn't evolve me, ok :)

**Comment by madiTG** [comment]
+1

**Comment by pbr0ck3r** [comment]
@joschi I have worked with a few other devs on upgrading Kafka to 1.0.1 and have it successfully working. This allows users to enable/disable SSL/TLS. As I am looking to make a PR to master branch for this so you all can enjoy the benefits as well. Is backwards capability a requirement? Or is it more of a `it would be nice to have`. From version 9 to 1.01 there was a lot of deprecated API calls, so adding backwards capability may take a lot more work.

**Comment by joschi** [comment]
@pbr0ck3r Unfortunately it's not that easy since Graylog is using Kafka's journal implementation for its own message journal (see [`KafkaJournal`](https://github.com/Graylog2/graylog2-server/blob/2.4.3/graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java)) and Kafka 0.10.x and later broke backwards-compatibility with it.

This being said, keeping Kafka 0.9.x in Graylog and adding a new Kafka transport using the newer Kafka Java client libraries *could* work.

**Comment by pbr0ck3r** [comment]
@joschi I have kafka 1.0.1 working and have modified the KafkaJournal. If I submitted this code in a PR would it be most likely accepted for 3.0?

**Comment by pbr0ck3r** [comment]
@joschi is the only backwards compatibility that you all are looking for is that the new kafka code would be able to read older kafka journals? Currently write now I have kafka on my dev environment is upgraded to 1.0.1 and you can create inputs with SSL and non-SSL and messages flow into GL fine. I am running a kafka 1.0.1 server. Would you expect that when this is merged into graylog that users would need to update their kafka instances? Just looking for what your expectations of backwards compatibility are. Thank you.

**Comment by pbr0ck3r** [comment]
Ability to use SSL is added in https://github.com/Graylog2/graylog2-server/pull/4729
