### ISSUE TITLE
Sidecar Tag/Config Management

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#3963]
## Expected Behavior
The Sidecar Agent only needs to have the Graylog Server URL and optimally authentication configured all other parts should be configurable from within Graylog.

First step could be the possibility to overwrite `tags` with server configuration. 

## Current Behavior
Half configuration need to be done at the Agent and the other half at the Graylog Server.  

## Possible Solution
Minimize the configuration at the Agent to the minimum and get all other settings from the Graylog API

## Context
If you decide to use Graylog to configure your log shippers the amount of work you need todo at the source should be minimal. 
Currently you need to have some kind of configuration Management to be able to configure `tags` and other settings at the Agent and additional do the configuration within Graylog.

**Comment by joschi** [comment]
Duplicates Graylog2/collector-sidecar#191
