### ISSUE TITLE
Searchable Alert Conditions/Notifications

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#3964]
## Expected Behavior
Have the ability to search like it is possible on other pages with pagination (audit log or archive)

## Current Behavior
The page is paginated and manual search and page switching is needed.

## Possible Solution
Have the search option like in other parts of the UI.

## Context
The current alert conditions/notifications page can become hard to navigate once you have a lot of conditions/notifications.

**Comment by bernd** [comment]
This doesn't apply to the new alerts system anymore.
