### ISSUE TITLE
Custom Query For Alert Conditions

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#3966]
## Expected Behavior
Be able to configure the Query for an alert condition. 

## Current Behavior
The Query for an alert condition is `*` on a stream. 

## Possible Solution
Add one additional field to the alert condition that the experienced user is able to make a more specific search on a stream for the alert condition.

## Context
This way it is not needed to create lots of streams just to be able to alert on a certain type of message by adjusting the query that is done.

**Comment by Mattia98** [comment]
I think it is critical that this feature is implemented. I have composed a query that shows me some specific error that I want to get an alert for. The only thing I can do right now is put the query count to a dashboard an monitor it, or have the search window in refresh mode open all the time. But I also need to know about possible matches when I am not in front of a monitor, hence I need to create an alert for a query. I couldn't believe that this wasn't a feature yet. Or is there another way you are supposed to create alerts for a specific error?
