### ISSUE TITLE
Allow users to define multiple ZooKeeper adresses for Kafka inputs

### ISSUE THREAD

**Issue by mwysokin** [Graylog2/graylog2-server#3977]
## Expected Behavior

Be able to define multiple ZooKeeper addresses for ZooKeeper HA cluster setups for Kafka inputs.

## Current Behavior

Only one address can be supplied in the ZooKeeper address input field when creating/editing Kafka input. If more addresses are supplied there is an error message: 

> Input *** has failed to start on node *** for this reason: »Unknown host 'host1:2181,host2:2181 unknown error'.«. This means that you are unable to receive any messages from this input. This is mostly an indication for a misconfiguration or an error. (...)

## Possible Solution

Allow users to define multiple ZooKeeper hosts and apply standard ZooKeeper approach for  Master/Slave handling.

## Steps to Reproduce (for bugs)

1. Start creating new Kafka input.
2. Try to supply several hosts separated by commonly used separators (' ' , ;).
3. Input is created but fails to connect to Kafka.

## Context

Running graylog setup in environment with ZooKeeper HA cluster with Master rotation.

## Your Environment

* Graylog Version:
2.2.3

**Comment by tokred** [comment]
@joschi I think this is not a features request, as Graylog already supports this for a long time. ;-)

@mwysokin Just checked, still works as expected on 2.2.3:
```
zookeeper:
 log-kafka01.domain.com:2181,log-kafka02.domain.com:2181,log-kafka03.domain.com:2181
```

Maybe there is an issue with your environment, e.g. name resolution, firewalling, etc?

Best regards

**Comment by joschi** [comment]
@tokred True, thanks for the pointer!

**Comment by jalogisch** [comment]
@mwysokin do you have any new input that?

**Comment by mwysokin** [comment]
Sorry for the delay. It works great! I guess my problem was caused by a typo. Thanks.

And since we are on the subject do you plan to integrate the newest Kafka approach to not depend on ZK at all for high-level consumer (http://docs.confluent.io/current/clients/consumer.html - paragraph Concepts). 
Or is it also already implemented? :)

**Comment by joschi** [comment]
@mwysokin Thanks for the update! I'll close this issue now.

There are currently no scheduled plans to update the Kafka input in Graylog.
