### ISSUE TITLE
Maintain deflector aliases for the two newest indices, instead of just one

### ISSUE THREAD

**Issue by jimbocoder** [Graylog2/graylog2-server#3979]
## Desired Behavior
The `graylog_deflector` index alias as it currently exists would not change. A second index alias would be added and managed in a similar fashion, except it always points to the index _before_ `graylog_deflector`.  In this thread, I'll call the new index alias `graylog_prev_deflector`. In this way, there are always two aliases with predictable names that span the latest two indices.

## Comparison with Current Behavior
Since we'd just be adding a new alias, it doesn't seem like there would be significant BC concerns. Only new code/clients/features that are aware of the new alias would be impacted (or should I say, benefited?)
  
### Motivation / Possible Solution
Running continuous ES queries against a sliding time interval for recent data, for the purpose of alerting and detecting spikes in logged metrics, has negative performance implications when using a wildcard like `graylog_*`.

(In my use-case, we're using the [ElastAlert](https://github.com/Yelp/elastalert) product from Yelp to monitor metrics over _e.g._ the past 15 minutes.)

A more targeted index set, namely `graylog_deflector`, completely solves the performance issue but introduces discontinuities in the metrics series each time the deflector cycles.

An index set of something like `graylog_deflector,graylog_prev_deflector` would resolve both considerations, if `graylog_prev_deflector` actually existed.

It could be argued that this isn't _truly_ Graylog's problem.  Still, it might benefit "the ecosystem" by easing this type of integration. So the question of whether it's within the project's scope, is unclear to me, which is why I've decided to post this.

Finally, while this is obviously not a support forum, I welcome any thoughts or suggestions about this problem anyone reading this may have, especially w/ regards to a more appropriate "layer" at which to address this alias management, if it is indeed out of scope.

Thanks!

**Comment by lennartkoopmann** [comment]
Hi @jimbocoder,

thank you very much for your detailed request. We will, however, not implement this for now, because this does indeed only affect directly querying Elasticsearch because Graylog handles the index selection automatically.

I understand the problem though. A workaround could be to regularly run a tiny script that maintains your own index aliases. The HTTP API for this is very straightforward.

Thanks, again,
Lennart
