### ISSUE TITLE
GELF UDP not setting gl2_remote_ip?

### ISSUE THREAD

**Issue by BenWoodford** [Graylog2/graylog2-server#3980]
I'm using a GELF UDP input and not getting a `gl2_remote_ip` field set. I may just be doing this wrong, or haven't enabled an option, but I cannot find anything in the docs that references such an option.

## Expected Behavior
`gl2_remote_ip` should be accessible via rules and "All Fields" on the Stream

## Current Behavior
It's not.

## Steps to Reproduce (for bugs)
1. Run Graylog 2.23
2. GELF UDP Input
3. Send some messages
4. Incoming messages don't have the IP set

## Context
These are feeding directly from a desktop application (C#) on user computers, and I'd like to be able to GeoIP Map where it's all coming from.

## Your Environment
Using the AMI for `Graylog 2.2.3+7adc951 on graylog (Oracle Corporation 1.8.0_101 on Linux 3.13.0-119-generic)`

* Graylog Version: Graylog 2.2.3+7adc951 on graylog (Oracle Corporation 1.8.0_101 on Linux 3.13.0-119-generic)
* Elasticsearch Version: Whatever comes with the AMI for the above version
* MongoDB Version: See above
* Operating System: See above
* Browser version: Irrelevant, but Chrome 59.0.3071.115

**Comment by joschi** [comment]
@BenWoodford Thanks for reporting this issue. I could reproduce it and a fix will be included in one of the next versions of Graylog.
