### ISSUE TITLE
Scrolling through search results in Safari skews the page

### ISSUE THREAD

**Issue by gpsalt** [Graylog2/graylog2-server#3983]
When scrolling down on the Search page in Safari the search results (on the right) are suddenly displayed below the "Fields filter" tile on the left, meaning that they are not eligible any more

## Expected Behavior
Page structure remains unchanged when scrolling

## Current Behavior
When scrolling down on the Search page in Safari the search results (on the right) are suddenly displayed below the "Fields filter" tile on the left, meaning that they are not eligible any more

## Possible Solution
Browser related issue

## Steps to Reproduce (for bugs)
Any search that produces a long enough results list so that user has to scroll down. Issue cannot be reproduced on Chrome and Firefox

## Your Environment

* Graylog Version: 2.2.3+7adc951
* Elasticsearch Version:
* MongoDB Version:
* Operating System: MacOS 10.12.5 
* Browser version: Safari 10.1.1

**Comment by edmundoa** [comment]
Hi @gpsalt,

I was trying to reproduce the issue you described but I couldn't. The page looks fine for me.

Part of the behaviour you described should happen on mobile devices, which have a small screen and can't display both columns properly at the same time, but not on a computer screen. Still, the sidebar should not be there at all, so I think that's not what you are seeing.

Do you see any errors in your browser's developer console? It would also be helpful to know the window size you are using, we could try to see if we trigger any bugs then.

Thank you!

**Comment by gpsalt** [comment]
Hi @edmundoa,

I have 1680x1050 resolution on a MacBook. The problem arises at various sizes and there is nothing popping up on the console (that I can spot at least). I uploaded two screenshots here (before, after)
https://www.dropbox.com/s/117mkptxv4i40ak/1.png?dl=0
https://www.dropbox.com/s/6k27leh556ewmyg/2.png?dl=0

**Comment by jalogisch** [comment]
Unfortunately the issue is not reproducible in the latest release. Please re-open this issue if it still occurs, ideally with a set of reproducible steps. 

Thanks!
