### ISSUE TITLE
Change frequency of constant REST calls in Graylog UI

### ISSUE THREAD

**Issue by susanjia** [Graylog2/graylog2-server#3985]
## Expected Behavior
After login to graylog UI, in the web browser, there are some constantly rest api calls to the graylog server, for example:
https:///api/system/cluster/nodes (GET, every 5 seconds)
https:///api/cluster/metrics/multiple (POST, every 2 seconds)
https:///api/system/notifications (GET, every 3 seconds)
https:///api/(GET, every 20 seconds)

Expect: the frequency of the rest API calls can be configured

## Current Behavior
Currently,  the constantly rest api calls to the graylog server can not be changed.

## Possible Solution
N/A

## Context
The constantly REST api in Graylog UI lowers down the performance when a big amount of user log into Graylog UI.

## Your Environment

* Graylog Version:2.2.3
* Elasticsearch Version: 2.2.3
* MongoDB Version: 2.2.3
* Operating System: Linux
* Browser version: Chrome, Fire Fox and IE

**Comment by dennisoelkers** [comment]
Thanks for your input. What is the higher level use case that you want to solve with this?

**Comment by susanjia** [comment]
I expect that in the config file, we can specify the frequency for the REST api calls. 
For example: 
After login, currently every 5 seconds, there will be a GET request https://<GraylogServer>/api/system/cluster/nodes 

I expect we can config the frequency for this call to another value, like 10 seconds.

Similar for the following REST api calls, I expect we can config the frequency to a different value.
https://<GraylogServer>/api/cluster/metrics/multiple (POST, every 2 seconds)
https://<GraylogServer>/api/system/notifications (GET, every 3 seconds)
https://<GraylogServer>/api/(GET, every 20 seconds)

**Comment by gruselglatz** [comment]
I think most of the normal Users dont need the Statistics on the top right corner.

**Comment by susanjia** [comment]
Is there a way to disable it?

**Comment by joschi** [comment]
@susanjia No.

**Comment by dennisoelkers** [comment]
@susanjia why do you expect you can configure that? What is the high level problem you want to solve?

**Comment by dennisoelkers** [comment]
@susanjia: Found it now in the "Context"-section of your original issue.

**Comment by florianvolle** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by Seb35** [comment]
I was also annoyed by such high frequencies for the 4 API requests described in the initial description: I have a small Graylog installation and I consider such high frequencies as a waste of ressources (server and client) and an environmental concern (small, but it is, particularly when high frequencies are not usefull). So I configured the reverse proxy nginx to intercept and change the frequencies. It is a workaround and a more integrated solution would be better.

1. For the 3 requests GET, the Cache-Control header is such that these requests are cached by the browser during a given time, this is a mitigation to avoid server-side overhead:
```
location = /api/system/notifications {
        proxy_pass http://internal-graylog.example.com:9000;
        proxy_set_header X-Graylog-Server-URL "https://public-graylog.example.com";
        proxy_hide_header Cache-Control;
        add_header Cache-Control "private, max-age=3600";
}
```

2. For the request POST `/cluster/metrics/multiple` (2 seconds [defined here](https://github.com/Graylog2/graylog2-server/blob/d375e6f6133df644e33a2cbf80d1a8dfaa5f1500/graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.js#L49)) and the request GET `/system/cluster/nodes` (5 seconds [defined here](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/stores/nodes/NodesStore.ts#L66)), it can be used the module [http_sub](https://nginx.org/en/docs/http/ngx_http_sub_module.html) to slow down the setInterval JS requests:
```
location /assets/builtins. {
        sub_filter 'INTERVAL:5e3' 'INTERVAL:864e5'; # every day ; /system/cluster/nodes
        sub_filter 'INTERVAL:2e3' 'INTERVAL:6e4'; # every minute ; /cluster/metrics/multiple
        sub_filter_types *;
        proxy_pass http://internal-graylog.example.com:9000;
        proxy_set_header X-Graylog-Server-URL "https://public-graylog.example.com";
        proxy_set_header Accept-Encoding "identity"; # seems to be needed, probably because nginx does not ungzip the response for sub_filter
        proxy_hide_header Cache-Control;
        add_header Cache-Control "no-transform, public, max-age=31536000";
}
```

PS: thanks for this great free/Open Source software Graylog!
