### ISSUE TITLE
graylog  analysis  feature

### ISSUE THREAD

**Issue by xuanyuanaosheng** [Graylog2/graylog2-server#3986]
# graylog  analysis 

## Expected Behavior
   when I want to analysis a field of log, the figure is Pie chart， but sometimes I want it to be  a 
 Histogram.  It has the data in the table, so it just transform it to a   Histogram figure.

## Current Behavior
   when selected the field from the left side, when click the  "Quick values" , the graylog will show a Pie chart .

**Comment by jalogisch** [comment]
This does not look like a valid feature request, if you can describe the high level use case for this please re-open the issue.
