### ISSUE TITLE
graylog kafka input can only read the new message ?

### ISSUE THREAD

**Issue by Cloud-Leung** [Graylog2/graylog2-server#3987]
graylog kafka input can't read oldmessage 

## Expected Behavior
i stop the graylog kafka input, then ,i push the message to the kafka, some message were saved in kafka.
when i start the graylog kafka input ,i wan't graylog can read this message.

## Current Behavior
But now graylog can only read the message when push after the input started . old message can't read 

## Possible Solution
i don't know this is myself fault, or design is like this .

## Steps to Reproduce (for bugs)
1. create a graylog gelf kafka input listen the topic 'TEST_KAFKA_INPUT', and stop the input .
2. push some message to the kafka on the topic  'TEST_KAFKA_INPUT'.
3. start the graylog input .
4. search the message , but can't find this message .

## Context
I was thinking that if graylog had pressure, it would cause service to hang up. My messages can be temporarily in Kafka and wait until graylog is restored to consume those messages without losing them.

## Your Environment

* Graylog Version:2.2
* Elasticsearch Version:
* MongoDB Version:3.2
* Operating System:2.4.5
* Browser version:chrome 59.0.3071.115

**Comment by jalogisch** [comment]
This behavior is intentionally. 

If you stop a Kafka input it will continues from the last known point. For new Inputs we will consider adding a "read all previous messages" option to the Kafka input.

**Comment by Cloud-Leung** [comment]
i get it, thank you .
