### ISSUE TITLE
Web-based Key-Value Store as Lookup Table Data Source

### ISSUE THREAD

**Issue by DerPhlipsi** [Graylog2/graylog2-server#3989]
## Expected Behavior
It would be nice to have a data adapter similar to the CSV adapter, but with the possibility to edit the key/value information on the Graylog Web Interface itself. Said simple, a hosted version of the CSV data adapter.

## Current Behavior
Currently you would have to connect to the Graylog Server to edit the CSV or find another solution to edit/update the CSV file(s), which could be a annoying process depending on your system architecture.

## Possible Solution
Maybe use Elasticsearch/MongoDB as a storage for a web-based K/V. Also a simple pass-trough of a CSV file could be a solution.

## Context
For debugging purposes, a simple and fast adaptable K/V-Store is a nice to have feature. I'm currently trying to get all the different mnemonics our Cisco devices are sending to Graylog, which is quite the hassle.
I've got the idea to use Lookup Tables to fill a field like _unknownMnemonic_ with a boolean if the mnemonic of the given message was seen before or not and setup a mail notification that automatically notifies me when a new (unknown) mnemonic is seen. This would get rid of a lot of manual copy, paste, excel, csv, etc. jobs...

Of course I know, this can be done with the CSV data adapter, but this is meant as a convenience thing, or better said a "debug/testing/or anything-that-a-non-cli-guy-like-my-coworker-can-use thing". 😆 

## Your Environment

* Graylog Version: Graylog 2.3.0-beta.1
* Elasticsearch Version: 5.4.3
* MongoDB Version: 3.4.2
* Operating System: RHEL7
* Browser version: Waterfox 54, Firefox 54, Chrome 59

**Comment by bernd** [comment]
This feature is already available in Graylog Enterprise.
