### ISSUE TITLE
Simulating Pipeline Processing with Extracted fields

### ISSUE THREAD

**Issue by sgmorale** [Graylog2/graylog2-server#3992]
The pipeline processing simulation currently is a stand alone deal and while this works it suffers from not being able to fully be used when troubleshooting rules where messages during normal operations will have fields that otherwise will not be available

## Expected Behavior
Simulating a rule it should take into account the existence of fields that might have been created by extractors earlier in the process a given message would normally take when received by an input.

## Current Behavior
Currently the simulation is stand alone. It only takes a raw message string and runs it through the rule with the only known factors affecting the rule being the message content, the stream, a source IP address, and Input.

## Possible Solution
We could have a way to specify custom field/value tuples that the simulation would take into account when going through the rule. Alternatively we could add a way to load existing messages with all their fields. This, however, might pose problems as fields that would be created by the rule might already exist.

## Context
This would be exceedingly helpful when building pipeline rules to quickly troubleshoot rules instead of relying on actual messages to coming through and looking at server logs to find out why or how the rules failed to act on messages to then wait for any particular messages that would be affected by that rule to come through to graylog

## Your Environment
* Graylog Version: 2.2.3+7adc951, codename Stiegl
* Elasticsearch Version: 2.4.4
* MongoDB Version: 2.4.9
* Operating System: 14.04.1-Ubuntu
* Browser version: Chrome 59.0.3071.115

**Comment by florianvolle** [comment]
We are not planning to implement this as extractors will be deprecated at some point in the future. Thank you!
