### ISSUE TITLE
Search from wrong indices

### ISSUE THREAD

**Issue by KongZ** [Graylog2/graylog2-server#3994]
## Expected Behavior
When search a log, it should search from valid indices range.

## Current Behavior
When search a log, it search from empty indices.

## Steps to Reproduce (for bugs)
1. Configure index set to rotate every day.
2. Leave first day empty without sending any log to Graylog.
3. On the second day, send some logs. Now log will goto second index while first index is empty.
4. Search anything from last 5 minutes, the Graylog will search from the first day and second day.

## Context
The index which are empty and it was rotated days ago, should not be included while searching log from today.

## Your Environment

* Graylog Version: 2.2.3
* Elasticsearch Version: 2.4.5
* MongoDB Version: 3.4.6
* Operating System: Ubutu 16.04 LTS

**Comment by joschi** [comment]
@KongZ Do you have any issues if the empty index is being included?

**Comment by KongZ** [comment]
@joschi If it does not impact a performance then It just a trivial bug which would be nice if it works correctly as expected. Because the indices was rotated long time ago so it should not be included in recently search.

**Comment by jalogisch** [comment]
As this does not has an impact on the performance or the function we will close this issue.
