### ISSUE TITLE
Unable to login with hashed pw in RC.1-1

### ISSUE THREAD

**Issue by loknar28** [Graylog2/graylog2-server#400]
Based on my issue I wasn't sure if this was a bug or not, but any help would be appreciated.

Following the Graylog2 server and web interface guides I have successfully installed RC.1-1 on Ubuntu 12.04 LTS. 

However, when I attempt to login using the pwgen –s 96 hashed password that I set for "root_password_sha2 ="    in /etc/graylog2.conf  I receive the error "Sorry, those credentials are invalid."

For example "echo -n password | shasum -a 256" generates the following hash.
5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8  -

 Since, I am unfamiliar with using pwgen –s 96 I wasn’t sure if the ”  
 -“ at the end was supposed to be included, so I tried both and neither work.

 Additionally, should the following line in /etc/graylog2.conf be set to "root_password_sha256"?
 ie… currently
root_password_sha2 = 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8

Thanks

**Comment by Tusharkale123** [comment]
To be able to connect to Graylog you should set rest_listen_uri and web_listen_uri to the public host name or a public IP address of the machine you can connect to. More information about these settings can be found in Configuring the web interface.

not able to configure the above steps, can somebody tell me how to configure it?

**Comment by joschi** [comment]
@Tusharkale123 
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
