### ISSUE TITLE
Exporting and importing extractors messes up their order

### ISSUE THREAD

**Issue by kylenoteboom** [Graylog2/graylog2-server#4018]
Exporting the extractors via JSON, as well as using Content Packs; then reimporting them messes up the order they are in.

## Expected Behavior
Extractors are imported and listed in the same order as they were exported.
The JSON result from exporting should somehow contain information such that it can be reimported, and be result in the same order.

## Current Behavior
Currently, the export appears to be messed up already. It skips from the first to the third Extractor, with the second one coming in somewhere later.
What's funny is that the `order` key inside the JSON appears to be correct.

## Possible Solution
I think the `order` key inside the exported JSON is not taken into account when importing.

## Steps to Reproduce (for bugs)
1. Create an Input with 9 Extractors.

2.  a. Export the extractors to JSON
3. Cleanse the system (`graylog-ctl cleanse`)
3. Import the resulting JSON.

Or

2. b. Export the Input to a Content Pack
3. Cleanse the system (`graylog-ctl cleanse`)
4. Import the resulting Content Pack

## Context
I'm trying to make it easier to get up and running with a new install of Graylog.

## Your Environment
* Graylog Version: 2.2.3+7adc95
* Elasticsearch Version: 2.4.2
* MongoDB Version: 3.4
* Operating System: Linux 4.4.0-71-generic
* Browser version: Mozilla Firefox 54.0.1 (32 bit)

**Comment by kylenoteboom** [comment]
I've done this again multiple times, and couldn't reproduce it.

**Comment by laurogripa** [comment]
Had the same problem with 3.1
Didn't find another issue. Should I open one?
