### ISSUE TITLE
Add option to append data to an existing field

### ISSUE THREAD

**Issue by irgendwr** [Graylog2/graylog2-server#4019]
Hi, I was wondering if would be possible to have an 'append' option to build a more human-readable message out of already extracted fields (from a JSON message for example).
This feature was [previously requested](https://github.com/graylog-labs/graylog2-web-interface/issues/767) in the old repo.

## Environment
* Graylog Version: 2.2.3+7adc951
* Operating System: Linux 4.10.15-1-pve

**Comment by joschi** [comment]
@irgendwr You can already do this with the [Processing Pipelines](http://docs.graylog.org/en/2.2/pages/pipelines.html).

**Comment by irgendwr** [comment]
Thanks, I'm new to graylog and a bit overwhelmed by the amount of settings and features.
Keep up the good work! 😄
