### ISSUE TITLE
Problem query Graylog’s Elasticsearch with Grafana

### ISSUE THREAD

**Issue by LeDistordu** [Graylog2/graylog2-server#4024]
I know I post a Grafana problem but you may be able to help me understand. Maybe some of you have already done.

I have graylog (2.2.3) and i want query its elasticsearch (2.4.4).

I add datasource elasticsearch 2x, i can query but when i query i dont have the same amount of data :

With same query on 5 minutes
From Graylog : 8796 data returned
From Grafana : 57 data returned

Grafana datasource configuration :
Index name : graylog*
Timestamp field name : timestamp
Pattern : no pattern
Version : 2.x

Why do not I get the same results?

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by joschi** [comment]
@LeDistordu You might also want to read up on the Graylog index model: http://docs.graylog.org/en/2.2/pages/configuration/index_model.html
