### ISSUE TITLE
cant send messages to graylog

### ISSUE THREAD

**Issue by Selva163** [Graylog2/graylog2-server#4029]
I'm using Azure ubuntu vm and installed graylog in the vm using docker as mentioned [here](http://docs.graylog.org/en/2.2/pages/installation/docker.html) I'm able to see the web ui in http://xxx.xxx.xxx.xxx:9000 but when I try to send messages, I get the following message

> use@userlogs:~$ curl -XPOST http://x.x.x.x:12201/gelf -p0 -d '{"short_message":"Hello there", "host":"example.org", "facility":"test", "_foo":"bar"}'
>curl: (7) Failed to connect to x.x.x.x port 12201: Connection refused

i'm able to send raw tcp messages in 5555. Also i have opened the ports in Azure portal and port forwarding is done for container.

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
