### ISSUE TITLE
Graylog cannot consume from GELF Kafka input

### ISSUE THREAD

**Issue by aliasmee** [Graylog2/graylog2-server#4030]
## Expected Behavior

When I create a input with GELF Kafka, I should be able to view the received messages. 
## Current Behavior

However, I did not search for anything from the search page.Also, I can see in the Inputs list page the amount of total received after the Network IO. here's a screenshot:
![image](https://user-images.githubusercontent.com/22883562/28499214-eb55cfa4-6fe2-11e7-9a0e-39394903309c.png)

## Possible Solution
No

## Steps to Reproduce (for bugs)

1. Start fluentd, Kafka 's cluster can work properly and receive messages.
2. Now, in the system-inputs page, create a new input 'Gelf Kafka'
3. The fault can be reproduced

## Context

I want to use gelf Kafka as Input,and my fluentd inputs to Kafka topic messages are in JSON format, as follows:
```
{"container_id":"95329f77859f5c084b472d9a8be68923cd0464dd2fe34b4642c338d2b72fba27","container_name":"/web1","source":"stdout","log":"192.168.156.132 - - [23/Jul/2017:20:05:09 +0800] \"GET / HTTP/1.0\" 200 45"}
```
Why Gelf kafka  Input cannot？Help 

## Your Environment

Fluentd collects the logs of docker container as producers, then outputs messages to Kafka in JSON format, and graylog extracts messages from the Kafka as consumer.
* Graylog Version: docker image graylog2/server:latest Graylog 2.2.3
* Elasticsearch Version: docker image elasticsearch:2
* MongoDB Version: docker image mongo:3
* Operating System: ubuntu 16.4
* Browser version: Chrome 59.0.3071.115

other soft version
* Fluentd Version: fluentd-0.12.35
* Kafka Version: kafka_2.11-0.11.0.0

**Comment by jalogisch** [comment]
The message you use in the context is not a GELF message.

You could change it to a RAW Kafka Input and do with pipelines or extractors a json parse on the input.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by aliasmee** [comment]
Thanks，use RAW/plaintext kafka is work。
