### ISSUE TITLE
Stop indexation (but keep input processing alive)

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#4032]
## Expected Behavior

Add a new mode to graylog-server processing to allow 

- to stop ES indexation
- but keep logs ingestion in local (kafka) journal (if enabled).

Such mode will add by definition much more security in term of buffer as it let the time to ES much more time to perform its maintenance.

## Current Behavior

In some case: ES maintenance, shard reallocation, we need to stop indexation (to let ES doing its job in best conditions without indexing pressure).
Stoping node processing currently also involve stop log reception into local kafka journal (and so something before as kafka or client loggers have to "unecessary" buffer).

## Possible Solution

Stop indexation, keep ingestion.

* Graylog Version: 2.2.3
* Elasticsearch Version: 2.4

**Comment by hc4** [comment]
Graylog will collect all incoming data into Disk Journal even if processing is paused.
![image](https://user-images.githubusercontent.com/17475270/28924639-1d7bb44a-786b-11e7-9df9-698e6dce9e54.png)

What do you mean by Kafka journal?

**Comment by florianvolle** [comment]
Closing this for now. If the issue persists please re-open. Thank you!
