### ISSUE TITLE
Inconsistent amount of Messages via API when you use the limit parameter

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#4043]
We need to rely on the given limit for Searches over the API.

## Expected Behavior
limit==10000 should give you a maximum of 10000 Messages in this query.

## Current Behavior
limit seems to be ignored, the query is correct but it gave me an inconsistent number of Messages every time.

## Possible Solution
?

## Steps to Reproduce (for bugs)
1. Fire an API call to Graylog with the limit Parameter set.
2. Count the Results

EXAMPLE:

```
$ http -b --verify=no -j -a USER:PASSWORD GET https://syslog.xyz.local/api/search/universal/relative query=="*" range==1800 sort==timestamp:asc limit==10000 | jq -r '.messages[].message.message' > searchtest.txt 
$ cat searchtest.txt | wc -l
13889
$ http -b --verify=no -j -a USER:PASSWORD GET https://syslog.xyz.local/api/search/universal/relative query=="*" range==1800 sort==timestamp:asc limit==10000 | jq -r '.messages[].message.message' > searchtest.txt
$ cat searchtest.txt | wc -l
11547
$ http -b --verify=no -j -a USER:PASSWORD GET https://syslog.xyz.local/api/search/universal/relative query=="*" range==1800 sort==timestamp:asc limit==10000 | jq -r '.messages[].message.message' > searchtest.txt
$ cat searchtest.txt | wc -l
12728

{"query":"*","built_query":"{
  \"from\" : 0,
  \"size\" : 10000,
  \"query\" : {
    \"bool\" : {
      \"must\" : {
        \"match_all\" : { }
      },
      \"filter\" : {
        \"bool\" : 
{
          \"must\" : {
            \"range\" : {
              \"timestamp\" : {
                \"from\" : \"2017-07-31 12:14:22.797\",
                \"to\" : \"2017-07-31 12:44:22.797\",
     
           \"include_lower\" : true,
                \"include_upper\" : true
              }
            }
          }
        }
      }
    }
  },
  \"sort\" : [ {
    \"timestamp\" : {
     
 \"order\" : \"asc\"
    }
  } ]
}"
```
## Context
While we searching for some possablity to implement a tail -f like api based script for the commandline we encountered this problem.

Maybe somehow related (but not the same, bcs we get not all messges but always more then the limit): #3005

## Your Environment
Graylog 2.3.0+81f8228 on syslog.xyz.local (Oracle Corporation 1.8.0_141 on Linux 3.10.0-514.16.1.el7.x86_64)

ES 5.5

**Comment by bernd** [comment]
@gruselglatz Is it possible that your messages contain newlines? The `-r` flag for jq outputs the unescaped message. So if you messages contain newlines, your line count of all messages via wc will be wrong.

```
$ echo '{"foo":"hello\nworld"}' | jq .foo
"hello\nworld"
$ echo '{"foo":"hello\nworld"}' | jq -r .foo
hello
world
```

**Comment by gruselglatz** [comment]
@bernd yes this was the problem here! Thx and sry for the non-issue!

**Comment by bernd** [comment]
@gruselglatz No worries, I am glad it works for you now! :smiley:
