### ISSUE TITLE
Support HTTP in GELF Output

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#4044]
Graylog currently has a GELF HTTP input, but no GELF HTTP output. The GELF output supports only plain TCP or UDP. There are use cases where forwarding all messages from a stream via HTTP instead of using the HTTP alarm callback makes sense.

**Comment by dennisoelkers** [comment]
Duplicate of #883.

**Comment by sagarinpursue** [comment]
I have written a plugin which supports HTTP output. Please find it here -
https://marketplace.graylog.org/addons/f0e8970f-f1f2-4057-8afe-4befc10b313a
