### ISSUE TITLE
Failing to send email notifications on alerts

### ISSUE THREAD

**Issue by gilad-feelter** [Graylog2/graylog2-server#4047]
We have a GrayLog server on AWS. Configured as in the docs, and customized nginx config to allow GELF HTTP with SSL.

Email configured:
`sudo graylog-ctl set-email-config email-smtp.us-west-2.amazonaws.com --port=587 --user=<AWS SES USER> --password=<AWS SES PASS> --from-email=<AWS SES VERIFIED EMAIL>`
`sudo graylog-ctl reconfigure`
and failed to send test notification.

Then we tried:
`sudo graylog-ctl set-email-config email-smtp.us-west-2.amazonaws.com --port=587 --user=<AWS SES USER> --password=<AWS SES PASS> --from-email=<AWS SES VERIFIED EMAIL> --no-tls --no-ssl`
`sudo graylog-ctl reconfigure`
and failed to send test notification.

Then we tried:
`sudo graylog-ctl set-email-config email-smtp.us-west-2.amazonaws.com --port=587 --user=<AWS SES USER> --password=<AWS SES PASS>`
`sudo graylog-ctl reconfigure`
and failed to send test notification.

all attempts fail with the following:
![graylog](https://user-images.githubusercontent.com/19663631/28867934-78480bda-7780-11e7-8131-7713cb62ccba.png)
> An error occurred while trying to send an email! (triggered a few seconds ago)
> The Graylog server encountered an error while trying to send an email. This is the detailed error message: org.apache.commons.mail.EmailException: Sending the email to the following server failed : email-smtp.us-west-2.amazonaws.com:587 (javax.mail.MessagingException: Could not connect to SMTP host: email-smtp.us-west-2.amazonaws.com, port: 587; nested exception is: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?)

**Comment by dennisoelkers** [comment]
Hello Gilad, it seems like Graylog is trying to use SSL/TLS on a plaintext port. Is the message _really_ the same for the second command, especially the last part? Did you restart Graylog after reconfiguring it?

**Comment by gilad-feelter** [comment]
You are right. Not the same error:

> The Graylog server encountered an error while trying to send an email. This is the detailed error message: org.apache.commons.mail.EmailException: Sending the email to the following server failed : email-smtp.us-west-2.amazonaws.com:587 (com.sun.mail.smtp.SMTPSendFailedException: 554 Message rejected: Email address is not verified. The following identities failed the check in region US-WEST-2: graylog@example.org )

**Comment by gilad-feelter** [comment]
the field 'transport_email_from_email' in '/opt/graylog/conf/graylog.conf' did get set correctly.

**Comment by dennisoelkers** [comment]
For alarm callbacks, the from address is overridden by the "Sender" parameter of the alarm callback configuration. Please check the configuration of the alarm callback you are testing and set the "Sender" parameter correctly.

**Comment by gilad-feelter** [comment]
Thanks, that solves it.

**Comment by SayariMahmoud** [comment]
would let me know how to solve the below issue

Garylog couldn t connect to server smtp.office365.com, connection is failed

please any suggestion thanks

GRAYLOG_TRANSPORT_EMAIL_ENABLED=true
GRAYLOG_TRANSPORT_EMAIL_HOSTNAME=smtp.office365.com
GRAYLOG_TRANSPORT_EMAIL_PORT=587
GRAYLOG_TRANSPORT_EMAIL_USE_AUTH=true
GRAYLOG_TRANSPORT_EMAIL_USE_TLS=true
- GRAYLOG_TRANSPORT_EMAIL_USE_SSL=true
GRAYLOG_TRANSPORT_EMAIL_AUTH_USERNAME=*********************
GRAYLOG_TRANSPORT_EMAIL_AUTH_PASSWORD=***************
GRAYLOG_TRANSPORT_EMAIL_SUBJECT_PREFIX=[graylog]
GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL=*****************

**Comment by joschi** [comment]
@SayariMahmoud Please post your issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
