### ISSUE TITLE
Move the info "a few seconds ago" to the bottom of widget

### ISSUE THREAD

**Issue by iredmail** [Graylog2/graylog2-server#4052]
Graylog shows info like "a few seconds ago" at the head of widget, this makes the widget title name too short. It's better to move this info the bottom of widget.

* Graylog Version: 2.3.0

Please check screenshot for better understanding:

Current widget:

![](http://i.imgur.com/uKsjqeC.png)

After change:

![](http://i.imgur.com/rxweW96.png)

**Comment by billmurrin** [comment]
This can be closed as #4072 was merged.

**Comment by bernd** [comment]
@billmurrin Thank you!
