### ISSUE TITLE
Question: How to integrate grafana?

### ISSUE THREAD

**Issue by huegelc** [Graylog2/graylog2-server#4063]
Hi,

is there a documentation how to integrate graylog with grafana? Thank you

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
