### ISSUE TITLE
Error on yum repo

### ISSUE THREAD

**Issue by mat44444** [Graylog2/graylog2-server#4064]
## Expected Behavior
yum update command should work

## Current Behavior
Yum update return this error:

failure: repodata/repomd.xml from graylog: [Errno 256] No more mirrors to try.
https://packages.graylog2.org/el/stable/2.3/x86_64/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for graylog: Damaged repomd.xml file

Also the documentation refere to a bad repo address:
http://docs.graylog.org/en/2.3/pages/installation/operating_system_packages.html

## Possible Solution
rebuild the repo and correct the documention with the rigth address

## Steps to Reproduce (for bugs)
Add yum repo, and try yum update
## Your Environment
CentOs 7

* Graylog Version: 2.2, trying to go in 2.3
* Elasticsearch Version: 2
* MongoDB Version:
* Operating System: CentOs 7
* Browser version:

**Comment by joschi** [comment]
@mat44444 How exactly did you set up the Graylog RPM repository on your system?

**Comment by mat44444** [comment]
in /etc/yum.repos.d/graylog.repo
[graylog]
name=graylog
baseurl=https://packages.graylog2.org/el/stable/2.3/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-graylog

**Comment by mat44444** [comment]
This the past config for 2.2, that was working in the past, but not now as apparently the repo structure have been modified, if you look the repo folder have been eliminated in you new folder organisation, but changing that not solve the issue

[graylog]
name=graylog
baseurl=https://packages.graylog2.org/repo/el/stable/2.2/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-graylog

**Comment by joschi** [comment]
@mat44444 Please use the configuration form the documentation, which is correct. Your `baseurl` is incorrect.

http://docs.graylog.org/en/2.3/pages/installation/operating_system_packages.html

**Comment by mat44444** [comment]
Ok, that working now strangly can directly acces via browser:

https://packages.graylog2.org/repo/el/stable/2.3 that return a 404 not found..
But as the repo working now, not sur why there other one
https://packages.graylog2.org/el/stable/2.3 working on browser
