### ISSUE TITLE
Fail to Index/Parse messages using Elasticsearch 5.5 

### ISSUE THREAD

**Issue by javrllerenas** [Graylog2/graylog2-server#4066]
## Expected Behavior

When ingesting messages from Beat shippers (metricbeat/packetbeat/etc) with the Beats input, GL should be able to index messages into Elasticsearch.

## Current Behavior

The _Beat Input_ is showing that it is receiving messages/logs from the beats, however, the web-interface raises an Indexing Error with the following note:
`... {"type":"illegal_argument_exception","reason":"Can't parse [index] value [not_analyzed] for field [packetbeat_method], expected [true] or [false]"}`

## Steps to Reproduce (for bugs)

1. Have GL 2.3 and ES 5.5 installed
2. Install Beats Plugin
3. Set up a Beats Input
4. Direct messages from Metricbeat/Packetbeat to the input

## My Environment

* Graylog Version: 2.3
* Elasticsearch Version: 5.5 
* MongoDB Version: 3.4.6
* Operating System: RHEL 7.3

**Comment by joschi** [comment]
@javrllerenas Please post the configuration of the Beats input, the configuration of Metricbeat, and the complete logs of your Graylog and Elasticsearch nodes.

**Comment by hc4** [comment]
Error message looks like bad mapping template in ES.
Mappings was [changed](https://discuss.elastic.co/t/elasticsearch-5-not-analyzed/68411/2) in ES 5+

**Comment by joschi** [comment]
@javrllerenas See what @hc4 wrote.

Are you using any custom index templates/index mappings in Elasticsearch?

**Comment by javrllerenas** [comment]
@joschi here are the inputs you requested:
#### Beats Input
![beats_input](https://user-images.githubusercontent.com/17650062/29294881-5fd9bd20-8106-11e7-9e0a-300bb8e5925a.png)

#### Metricbeat Config
![metricbeat_config](https://user-images.githubusercontent.com/17650062/29294899-68694b5e-8106-11e7-9007-2a0897d750d8.png)

#### Graylog Log
![gl_log](https://user-images.githubusercontent.com/17650062/29294903-6eedc270-8106-11e7-9501-57ba2fda6ff2.png)

#### Elasticsearch Log
![es_log](https://user-images.githubusercontent.com/17650062/29294909-7575de70-8106-11e7-9abf-9838d3f9c40f.png)

#### ------------------------------------------
### Mapping
Regarding Mapping, I did follow the instructions from here: [https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-template.html](url)
I ran the command: 
`$ curl -H 'Content-Type: application/json' -XPUT 'http://<my_ip>:9200/_template/metricbeat' -d@/etc/metricbeat/metricbeat.template.json`

**Comment by hc4** [comment]
Looks like template was created for ES 2.x (which version of metricbeats are you using?)
Anyway, default template in beats is for Kibana.
It is not compatible with Graylog.
You need to modify it. Simpliest way is to remove this mapping from ES and put some beats data into Graylog. After that you'll see actual fields, created by Beats input.

**Comment by javrllerenas** [comment]
@hc4 After deleting the **Metricbeat Template** from Elasticsearch, Graylog shows an indexing failure:

![15_indexing_failure](https://user-images.githubusercontent.com/17650062/29337813-a3a661e0-81c7-11e7-9aa0-7fad2a02b2a0.png)

(The only template ES has is the _graylog-internal_ template)

Should I actually modify the Metricbeat template?

**Comment by hc4** [comment]
Modified template will aply only to newly created indices.
Thus you just need to force index rollover.

**Comment by javrllerenas** [comment]
@hc4 ok cool. I'll try that. Thank you for the explanation! :)
@joschi Thank you for the help too.

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
