### ISSUE TITLE
Documentation for use with docker-compose is wrong

### ISSUE THREAD

**Issue by vpsouza** [Graylog2/graylog2-server#4071]
The documentation for use with docker-compose is wrong. Please, fix it as soon as possible. Add an environment GRAYLOG_ELASTICSEARCH_HOSTS and change the command for the elasticsearch service.

## Possible Solution

version: '2'
services:
  mongo:
    image: "mongo:3"
  elasticsearch:
    image: "elasticsearch:5"
    command: "elasticsearch -Ecluster.name='graylog'"
    ports:
      - "9200:9200"
  graylog:
    image: graylog2/server:2.3.0-1
    environment:
      GRAYLOG_PASSWORD_SECRET: somepasswordpepper
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "5555:5555"

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@vpsouza See documentation#348
