### ISSUE TITLE
Show terms always uses standard analyzer

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#4074]
Show terms option always uses standard analyzer, set for index.
![image](https://user-images.githubusercontent.com/17475270/29212886-75b5b7ca-7ea9-11e7-9c1b-4c0375e2d070.png)

It is not always correct, because different analyzers could be set for fields through custom mappings.
Actualy graylog "analyze" API supports passing custom analyzer, so I could test any text against my custom analyzer.
So problem is not critical.

## Your Environment
* Graylog Version: 2.3.0
* Elasticsearch Version: 5.5.1

**Comment by bernd** [comment]
The new search page doesn't offer the "show terms" feature anymore so this issue can be closed.
