### ISSUE TITLE
Sometime message processing stoping and CPU 100%

### ISSUE THREAD

**Issue by TenGbps** [Graylog2/graylog2-server#4075]
Sometime graylog buffer going full whitout error log output and cpu thread going at 100% and ES load is 0.

## Possible Solution
I think graylog do not like a long message, but i down know how the current processing message id.

## Steps to Reproduce (for bugs)
I have trying to reproduce the bug without success

## Your Environment
 5 Elastic Server (1 Master, 4 Data) 10GbE
 1 Mongo (Master) 10GbE
 2 Graylog Server (20Gb heap) 10GbE

* Graylog Version:  2.2.3+7adc951
* Elasticsearch Version: 2.4.3
* MongoDB Version: 2.6.12
* Operating System: CentOS
* Browser version: Firefox ESR 52.2.1 (x64)

## Screen shot
WebUI
![gray](https://user-images.githubusercontent.com/30792994/29215502-80ad560e-7eab-11e7-9f1c-f8aa24b4dc1c.jpg)
htop
![htop](https://user-images.githubusercontent.com/30792994/29215333-e3422d04-7eaa-11e7-83d8-a0e6a74d13f9.jpg)

**Comment by bernd** [comment]
@TenGbps If you have very large messages and extractors or pipeline rules, your throughput will go down. Without any details about message sizes, extractors, stream rules and pipeline rules, it's hard to debug.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by TenGbps** [comment]
This issue is due to a bad extractor, take to mutch time to execute
