### ISSUE TITLE
Quick Values improvements

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#4082]
- [x] Allow to sort on value, percentage or count
- [x] Allow to build a chart of the values over time. This is important to see how values changed over time. This needs a "Only chart top 10[/30/100] values" to avoid huge charts with too many lines.
- [x] Stacking of data based on another field. For example, you could run a quick values analysis on
a source address field and then select to stack a source address against a destination address. This would then give you the top destination addresses the specific source IP has been talking to. You
could also run this without selecting a source IP first and get all conversation pairs, together with their count.

## Open Tasks

- [ ] Disable stacked field form if Elasticsearch is < 5.x
- [x] Split stacked terms result into key value pairs to fix https://github.com/Graylog2/graylog2-server/issues/4216
  - Use [WORD SEPARATOR MIDDLE DOT](http://www.fileformat.info/info/unicode/char/2e31/index.htm) unicode character to join and split the stacked fields (but also make the character configurable)

**Comment by edmundoa** [comment]
Points 1 and 3 are implemented in #4205
