### ISSUE TITLE
Ship Netflow plugin with Graylog by default

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#4086]
Include the [Netflow plugin](https://github.com/graylog-labs/graylog-plugin-netflow) with our Graylog packages by default and move it out of `graylog-labs`.

**Comment by bernd** [comment]
This is done.

**Comment by joschi** [comment]
@bernd Documentation for the plugin is still missing (probably worth a new issue in the documentation repository).
