### ISSUE TITLE
syslog/GELF inputs: rate limiter

### ISSUE THREAD

**Issue by ralfbergs** [Graylog2/graylog2-server#4087]
## Expected Behavior
It would be great if (these two) input plugins had a means to limit the input rate of incoming messages. As soon as a certain maximum rate is exceeded, the input could be suspended (temporarily or permanently, depending on the configuration of that specific input), or the incoming messages could be throttled (messages discarded that exceed the desired maximum rate).

## Current Behavior
Currently there's no way to limit incoming messages in these two plugins.

## Possible Solution
As the current input rate is being calculated anyway, Graylog (or the input plugin) could be changed to act accordingly as suggested above when the rate limit is hit.

## Context
We had a buggy piece of software that flooded our Graylog, which we only noticed pretty late (before you ask, we will implement monitoring now!), so in the meantime the messages filled our indices and aged out messages we didn't want to expire yet. Rate limiting as a "safety net" would be a nice extra.

## Your Environment

* Graylog Version: Graylog 2.1.2+50e449a

**Comment by jalogisch** [comment]
depending on your setup you might want to add some queues on the road from your log source to graylog.

in addition you might want to update to the latest version to use various indices.

**Comment by ralfbergs** [comment]
@jalogisch Hi Jan, thanks for your response.

I don't see how extra queues in between would have helped? Messages would have been pushed thru all intermediate queues, until they would have arrived in the "ultimate" queue. The same thing would have happened, i. e. messages in the ultimate queue would have aged out.

Or am I missing anything?

What exactly does the latest version offer, compared to the version we're using? What does "use various indices" mean?

**Comment by florianvolle** [comment]
This is something we are currently not planing to implement. Thank you!
