### ISSUE TITLE
In the search bar, select's default value doesn't match correct value.

### ISSUE THREAD

**Issue by yoster0520** [Graylog2/graylog2-server#4089]
I change the search configurations in the web interface's configuration page. I remove `Search in the last 5 minutes` item in the relative configuration.
Then the select of search bar show another item. But the search page show the `Search in the last 5 minutes` result.
![image](https://user-images.githubusercontent.com/13730237/29351560-d67f7ad2-8228-11e7-9db3-37a474706a87.png)
## Expected Behavior
The search page show the result that searched  by select shows configuration.

## Current Behavior
The search page show the result that searched  by `Search in the last 5 minutes`.

## Possible Solution
1 The select change not trigger search actions.
2 The select not match correct item.

## Steps to Reproduce (for bugs)
1. Remove `Search in the last 5 minutes` in the search configuration Modal.
2. Go localhost:8080/search page.
3. The select show `Search in the last 10 minutes`.
4. The page show the result that searched by `Search in the last 5 minutes`

## Your Environment

* Graylog Version: 2.3
* Elasticsearch Version: 5.5
* MongoDB Version: 
* Operating System: linux
* Browser version: chrome

**Comment by jalogisch** [comment]
@yoster0520 maybe you did this, but after you had deleted the 5 minutes slot, with a click on the trash can. Did you scroll down and hit *Save* ?
![screenshot 2017-08-21 14 04 35](https://user-images.githubusercontent.com/404238/29518576-38691e42-867a-11e7-87d1-81bd7b1d97a2.png)

I tried to recreate your issue and this is the only option that is left (for me). 

If you saved everything, could please share your settings and a way how we can recreate that.

thank you

**Comment by jalogisch** [comment]
as no feedback is given, i'll close this.
