### ISSUE TITLE
Very Slow,Process buffer full

### ISSUE THREAD

**Issue by jun283** [Graylog2/graylog2-server#4090]
* Graylog Version:2.3.0
* Elasticsearch Version:
* MongoDB Version:
* Operating System:EC2 Linux 3.13.0
* Browser version:

New install EC2(c3.4xlarge, 16CPU,30GB Memory), 
Graylog V2.3, 
only one input: Raw/Plaintext UDP

message:In: 1200 msg/s,   Out: 170 msg/s
Process buffer: 100%

Very Slow, unbearable

**Comment by lukaspour** [comment]
I can confirm as well - both openstack image (high spec machine) and virtualbox image (my laptop). 

![pasted image at 2017_08_16 01_08 pm](https://user-images.githubusercontent.com/8102576/29360875-36bdc3f2-8285-11e7-9a95-a9656fdc5858.png)

**Comment by jalogisch** [comment]
@jun283 @lukaspour 

that slowness can have multiple reasons. How much processing did you do? What kind of plugins did you have installed? Did you change the default settings? 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
