### ISSUE TITLE
Parameter elasticsearch_hosts must not contain URIs without host or scheme. (found [http://graylog_elasticsearch:9200])

### ISSUE THREAD

**Issue by titansmc** [Graylog2/graylog2-server#4092]
graylog_graylog.1.41j0gklc95dp@dock-test01    | 2017-08-16 12:20:34,028 ERROR: org.graylog2.bootstrap.CmdLineTool - Invalid configuration
graylog_graylog.1.41j0gklc95dp@dock-test01    | com.github.joschi.jadconfig.ValidationException: Parameter elasticsearch_hosts must not contain URIs without host or scheme. (found [http://graylog_elasticsearch:9200])

## Expected Behavior
Recognize http://graylog_elasticsearch:9200 as a valid hostname

## Current Behavior
Doesn't eat the config parameter that defines ES host, it must be passed like http://elasticsearch:9200 which may conflict with another ES instance running on the same swarm network.

## Steps to Reproduce (for bugs)
Setting up 

## Context
When running services in Swarm mode, I can either use http://stack_service as a valid hostname or http://service but when using service only it may conflict with others running on the same network

## Your Environment

* Docker swarm mode Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false

* Graylog Version: graylog2/server:2.3.0-1
* Elasticsearch Version :elasticsearch:5"
* MongoDB Version: mongo:3
* Operating System: Ubuntu 16.04
* Browser version: Firefox 54

**Comment by mariussturm** [comment]
Hi,
underscores are not allowed in hostnames afaik. So I think this is more an issue for Docker-Swarm, they need a mechanism to enumerate multiple service instances, like elasticsearch1, elasticsearch2, ...

**Comment by titansmc** [comment]
Hi,
Thanks. They do have a mechanism to enumerate several instances, but let's say I have ELK stack and Graylog stack in the same network. They both respond to http://elasticsearch but only one will respond to http://elk_elasticsearch and only one to http://graylog_elasticsearch . That is why it is useful to be able to specify the complete hostname to avoid conflicts.

**Comment by mariussturm** [comment]
The parameter `elasticsearch_hosts` is expecting an IP or a hostname, `elk_elasticsearch` is simply not a valid hostname, that's why the validation fails for it. Changing it just for Docker doesn't sound right to me. I bet there are other service discovery options in Swarm. From the Graylog side you can use the configuration file or make use of the environment variable `GRAYLOG_ELASTICSEARCH_HOSTS`. Maybe there is something in Swarm that can set the variable accordingly to the right IP.

**Comment by maxfield-allison** [comment]
For others who find this issue in the future, you can get around it by using docker network aliases in your stack file. 
```yaml
  graylog_mongodb:
    image: mongo:6.0
    hostname: graylog-mongodb
    networks:
      net:
        aliases:
          - graylog-mongodb
```
