### ISSUE TITLE
Can't apply search query on sources page

### ISSUE THREAD

**Issue by hc4** [Graylog2/graylog2-server#4093]
Pressing on "Search" button at Sources page redirects to Search page.

![image](https://user-images.githubusercontent.com/17475270/29367706-77c9b8bc-82a6-11e7-8304-8eb8b7102529.png)

Is it expected behaviour? Then search button have no sense at Sources page.

## Expected Behavior
Search query must be aplied to sources statistic

## Your Environment
* Graylog Version: 2.3.0
* Elasticsearch Version: 5.5.1

**Comment by jalogisch** [comment]
@hc4 everything is a search - the sources page is only a special kind of search/dashboard. 

The searcher is the same you have on top of the search page. You might expect something to search inside the list of sources. That search window is above the list of sources.

I'll close this as I can't find a feature in this. If that is wrong, please elaborate on the feature wish.

**Comment by hc4** [comment]
Currently sources page shows statistic for all incoming data.
The possible feature is to show statistic only for specific data (filtered by search query).
And it seems to me that it was possible in previous versions of Graylog

Also currently non-expected behaviour: if you select some interval on "Messages per minute@ chart, to look closer at it, only search interval will be adjusted, but no way to apply this new search interval, because you'll be redirected to Search page.
![image](https://user-images.githubusercontent.com/17475270/29519315-a6f067e8-8685-11e7-9deb-b639180aea3b.png)
