### ISSUE TITLE
No Messages results in -9,223,372,036,854,775,808 value in Dashboard (cardinality)

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#4097]
Cardinality Value is negative when there is no Message for the search query.

## Expected Behavior
Display 0 When there is nothing to count.

## Current Behavior
Dashboard Widget shows -9,223,372,036,854,775,808
![chrome_2017-08-17_13-35-42](https://user-images.githubusercontent.com/15243394/29410536-224ae02c-8351-11e7-9ce0-6fcbae73dd3e.png)

## Possible Solution
?

## Steps to Reproduce (for bugs)
1. Search
2. Create Cardinality Value
3. Add to Dashboard
4. Dont Send Messages until nothing is in timerange
5. See strange Value

## Context
Widget Infos:
Type: Statistical value, cached for 60 seconds.  Widget is bound to stream 57a1ba4bebe7522e85faef75.

More details:
Widget ID: 50e26c1f-5b54-4d75-9bda-910d84008389
Dashboard ID: 578f35203c2f285cb90b5d53
Timerange: { "type": "relative", "range": 86400 }
Field: unifi_guest_mac
Trend: true
Stream id: 57a1ba4bebe7522e85faef75
Query: _exists_:unifi_guest_mac
Stats function: cardinality
Lower is better: false

## Your Environment
Graylog 2.3.0+81f8228 on syslog.xyz.local (Oracle Corporation 1.8.0_141 on Linux 3.10.0-514.26.2.el7.x86_64)
Elasticsearch: 5.5

**Comment by dennisoelkers** [comment]
That should be fixed in https://github.com/Graylog2/graylog2-server/pull/4046 - please retry when `2.3.1` is out and reopen if the problem still persists.
