### ISSUE TITLE
Problem with elasticsearch behind reverse proxy

### ISSUE THREAD

**Issue by raiblue** [Graylog2/graylog2-server#4098]
Graylog doesn't function properly when one of elasticsearch nodes fails if elasticsearch nodes are behind reverse proxy. This problem occurs when using elasticsearch cluster but the cluster nodes are behind a reverse proxy (mine is nginx) because of some reason (mine is for basic authentication). Even elasticsearch cluster is healthy (only one node is stopped of three-node-cluster with minimum_master_nodes: 2), graylog tries to get a json response from elasticsearch nodes when bulk indexing, and if it gets a response which is not json (behind nginx, it gets a straight http 502 response) it throws an exception and search function doesn't work as shown in screenshot.

![graylog_proxy](https://user-images.githubusercontent.com/11852729/29411745-cf860dfe-835e-11e7-92d6-cd000c20a10b.png)

## Expected Behavior
It should work with elasticsearch behind reverse proxies.

## Current Behavior
I have an elasticsearch cluster of 3 nodes (one is master only, no data). Replication count is 1 in cluster, so 2 data nodes have same shards on them. There is nginx reverse proxy in front of my elasticsearch nodes to provide basic authentication to elasticsearch. In graylog configuration, elasticsearch connection is like this:
```
elasticsearch_hosts = https://admin:password@example.com,https://admin:password@example.com
```

When I stop one of the elasticsearch nodes, graylog fails. Search page and indices pages doesn't work. In that moment logs are like following:

```
2017-08-17T14:21:33.952+03:00 ERROR [Messages] Caught exception during bulk indexing: java.io.IOException: Request POST https://admin:password@example.com.tr/_bulk HTTP/1.1 yielded text/html, should be json: HTTP/1.1 502 Bad Gateway, retrying (attempt #1).
2017-08-17T14:21:33.978+03:00 INFO  [Messages] Bulk indexing finally successful (attempt #2).
2017-08-17T14:21:34.953+03:00 ERROR [Messages] Caught exception during bulk indexing: java.io.IOException: Request POST https://admin:password@example.com.tr/_bulk HTTP/1.1 yielded text/html, should be json: HTTP/1.1 502 Bad Gateway, retrying (attempt #1).
2017-08-17T14:21:34.995+03:00 INFO  [Messages] Bulk indexing finally successful (attempt #2).
```
I think bulk indexing needs to have a json response (positive or negative) from all nodes of elasticsearch_hosts. But when there is reverse proxy between graylog and elasticsearch, the negative response is not json. Is there a workaround for this or maybe a fix in code? Or am i doing something wrong?

## Your Environment

* Graylog Version: 2.3
* Elasticsearch Version: 2.4.6
* MongoDB Version: 3.4
* Operating System: RHEL 7.3

**Comment by joschi** [comment]
@raiblue You have to correctly configure your proxy server to remove dead hosts from its backend rotation.

Currently it's spitting out 502 (Bad Gateway) errors with an HTML page which is in no way useful.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
