### ISSUE TITLE
Feature Request: Support Authentication in HTTPJSONPath DataAdapter

### ISSUE THREAD

**Issue by bangert** [Graylog2/graylog2-server#4099]
## Expected Behavior
Be able to access HTTP JSON resources protected by either digest authentication or token authentication.

## Current Behavior
Currently the only way to authenticate is using the User-Agent header, which is insecure.

## Possible Solution
Add fields and implementation for alternative a) digest authentication or b) token authentication.

**Comment by joschi** [comment]
@bangert This will be fixed by #4094.

**Comment by bangert** [comment]
Awesome. Sorry I missed this.

**Comment by jalogisch** [comment]
I'll then close this issue.
