### ISSUE TITLE
search result cannot highlighting

### ISSUE THREAD

**Issue by xiewei308** [Graylog2/graylog2-server#4101]
Hello,

i got a problem with the "search result cannot highlighting".
The parameter was set to true in
/etc/graylog/server/server.conf(allow_highlighting = true)

Environment

Graylog Version: 2.3.0
Elasticsearch Version: 5.5.1
MongoDB Version: 3.4.6
Operating System: CentOS release 6.5 (Final)
Browser version: Chrome 60.0.3112.101 (64-bit)

**Comment by joschi** [comment]
@xiewei308 Please provide more details about the problem, such as the full error message and the logs of your Graylog and Elasticsearch nodes.

**Comment by dennisoelkers** [comment]
Thanks for reporting this, @xiewei308. We have prepared a fix for this issue (#4103) and will include it in the next version (`2.3.1`) which will be released very soon.
