### ISSUE TITLE
RAW TCP input loses the data after the last 0x0a

### ISSUE THREAD

**Issue by jtkkex** [Graylog2/graylog2-server#4105]
## Expected Behavior
Setting up a RAW TCP input, Graylog uses all lines that are written to the input.

## Current Behavior
Raw TCP input reads a message in whenever there is a newline (0x0a) coming from the input.  The characters between the last 0x0a and closing the TCP connection are discarded.  If a sender opens a separate connection for each log line and does not terminate the connections with a 0x0a, Graylog will not process the log lines.

The total byte count on the inputs page shows the incoming bytes, but they are not processed as messages.

## Possible Solution
When connection closes, read the remaining bytes and process them normally.

## Steps to Reproduce (for bugs)

1. create a RAW TCP input
2. create a script that sends a string to the input, such as "See me\nSee me not" (verify with TCPdump that your script does not silently add a \n to the end of the string).

## Context

Tried to send log lines from Windows with Powershell.

## Your Environment

* Graylog Version: 2.3.0
* Elasticsearch Version: 5.5
* MongoDB Version: 3.4
* Operating System: CentOS 7

**Comment by joschi** [comment]
@jtkkex Thanks for reporting this!

The Raw/Plaintext TCP input expects messages to end with the configured delimiter (`\0`, `\n`, or `\r\n`).

We'll see if we can change that with little effort.

Reference:
* https://netty.io/3.10/api/org/jboss/netty/handler/codec/frame/LineBasedFrameDecoder.html
* https://netty.io/3.10/api/org/jboss/netty/handler/codec/frame/DelimiterBasedFrameDecoder.html

**Comment by bernd** [comment]
Moving this to 2.4.0 so we have a chance to test the fix in #4106 more thoroughly.
