### ISSUE TITLE
What does this mean: Shards: 1 active, 1 unassigned

### ISSUE THREAD

**Issue by ovizii** [Graylog2/graylog2-server#4110]
I have googled far and wide but cannot find any Graylog2 specific answer.

I'm busy giving the Graylog2 appliance a try on VMWare and I kept seeing 4 active shards 4 unassigned. The Graylog docu said the number of shards active should correspond to the number of nodes and since this is the appliance, I edited my current index to be 1 shard only. Now this one is still unassigned, what does that mean and how do I fix it?

Graylog is running fine, I just wanted to know what this means exactly.

## MyEnvironment

* Graylog Version: 2.3.0
* Elasticsearch Version: whatever came with the latest version of the appliance and after an apt-get upgrade
* MongoDB Version: whatever came with the latest version of the appliance and after an apt-get upgrade
* Operating System: whatever came with the latest version of the appliance and after an apt-get upgrade
* Browser version: irrelevant

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by ovizii** [comment]
Thanks for pointing me in the right direction.
