### ISSUE TITLE
Elasticsearch default config for shards and replicas not used in UI 

### ISSUE THREAD

**Issue by marcuslinke** [Graylog2/graylog2-server#4114]
## Expected Behavior
After set `elasticsearch_shards = 5` or `elasticsearch_replicas = 1` in graylog configuration file I expect that these values are show as default values in the UI when creating a new Index Set.

* Graylog Version: 2.3.1-1
* Elasticsearch Version: 5.2.2
* MongoDB Version: 3.0.5
* Operating System: Docker 1.11.2 (Boot2Docker)
* Browser version: -

**Comment by joschi** [comment]
@marcuslinke Please read the upgrade notes of Graylog 2.2.x.
These settings have been moved into the database as part of the index sets configuration.

* http://docs.graylog.org/en/2.3/pages/configuration/index_model.html
* http://docs.graylog.org/en/2.3/pages/upgrade/graylog-2.2.html#default-stream-index-sets
* https://www.graylog.org/blog/88-announcing-graylog-v2-2-0

**Comment by marcuslinke** [comment]
So there is no possibility to change these defaults? We have an elastic cluster with 2 data nodes here and want to have sensible default values for creating new index sets in the UI.
E.g. Create IndexSet with shards=5 and replicas =1 instead of shards = 4 and replicas = 0

 Is this possible somehow?

**Comment by joschi** [comment]
@marcuslinke These defaults are hard-coded in the web interface:
https://github.com/Graylog2/graylog2-server/blob/2.3.1/graylog2-web-interface/src/pages/IndexSetCreationPage.jsx#L33-L34

If you want to create index sets via the Graylog REST API, you have to provide a valid value for the number of primary and replica shards.
