### ISSUE TITLE
Code logic behind the top source IP address

### ISSUE THREAD

**Issue by sathishdsgithub** [Graylog2/graylog2-server#4121]
Can someone help me to identify the source code logic for the below top source IP address table and piechart ?

![image](https://user-images.githubusercontent.com/19161126/29996695-07608ae6-9021-11e7-834d-1ae793d47474.png)

**Comment by joschi** [comment]
@sathishdsgithub It's the [SourceDataTable component](https://github.com/Graylog2/graylog2-server/blob/2.3.1/graylog2-web-interface/src/components/sources/SourceDataTable.jsx).

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
