### ISSUE TITLE
graylog OVA issues and questions

### ISSUE THREAD

**Issue by ovizii** [Graylog2/graylog2-server#4122]
I downloaded and installed the OVA, all worked fine. I then updated to the latest version and still all good. Somewhere along the steps of following http://docs.graylog.org/en/2.3/pages/installation/virtual_machine_appliances.html?highlight=ova and hardening the appliance I ran into the issue that graylog seemed not to be starting anymore. 

so I tried: graylog-ctl reconfigure-as-backend which resulte in these 2 lines in my /opt/graylog/conf/graylog.conf

```
rest_listen_uri = http://0.0.0.0:9000/api

web_listen_uri = 192.168.99.2
```
as I had also run graylog-ctl local-connect before

with the above configuration inside /var/log/graylog/server/current I see 
```

ERROR Invalid Configuration
Parameter web_listen_uri should be an absolute URI (found 192.168.99.2)
```

so I went and changed it to:

web_listen_uri = http://192.168.99.2/ 

which still doesn't give any positive results. graylog-ctl status shows elasticsearch, etcd, graylog-server and mongodb running which indicates nginx is somehow down.

graylog-ctl tail nginx shows this:
![image](https://user-images.githubusercontent.com/837902/30019855-39259ff2-9162-11e7-9c95-c53b0a0142b4.png)
while 192.168.99.2 is graylog's IP and 192.168.99.0 is its gateway and 192.168.0.2 was the client I was connecting from.

**Most important question: is there a command to reset an OVA to its default config?**

## Your Environment

* Graylog Version: latest version after updating the OVA via apt-get
* Elasticsearch Version: latest version after updating the OVA via apt-get
* MongoDB Version: latest version after updating the OVA via apt-get

**Comment by jalogisch** [comment]
Hej @ovizii all commands are listed in the documentation: http://docs.graylog.org/en/2.3/pages/configuration/graylog_ctl.html

I would like to add that the OVA is not recommend for production http://docs.graylog.org/en/2.3/pages/securing.html#securing-graylog 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
