### ISSUE TITLE
Can I cover timestamps? Use the time data in the log as a timestamp

### ISSUE THREAD

**Issue by aliasmee** [Graylog2/graylog2-server#4126]
Is timestamp accuracy adjustable?

## Expected Behavior

Use the time string data in the message as timestamp.

## Current Behavior

Use the time string data in the message as timestamp.
## Possible Solution

1. Try to use Extractors to handle, do not work，example：
```bash
Configuration
regex_value: ([0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{6})
Converters
date
date_format: YYYY-MM-dd'T'HH:mm:ss'Z'
time_zone: Asia/Shanghai
locale:
```
`2017-09-06T20:05:40.804216`
But, The value of timestamp is still the default timestamp precision

## Context

![image](https://user-images.githubusercontent.com/22883562/30110657-67469c42-933d-11e7-9999-a71ba4beb077.png)
Use the time string data in the message as timestamp. As above
## Your Environment

* Graylog Version: 2.3.0
* Elasticsearch Version: 5.5.1
* MongoDB Version: 3.0
* Operating System: linux
* Browser version: Chrome

tks   ^_^

**Comment by joschi** [comment]
> Is timestamp accuracy adjustable?

No, the timestamps used in Graylog are always millisecond precision.

Also see elastic/elasticsearch#10005 for a related issue in Elasticsearch.

**Comment by aliasmee** [comment]
Oh, tks, You are right. Thank you again for your prompt reply,
It turned out to be elasticsearch's not supported.
I wronged graylog..... ^.^
