### ISSUE TITLE
Make Pipelines and Rules a Part of Content-Packs

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#4131]
Make it Possible to Export and Import Pipelines and Rules and their configuration into Content-Packs

## Expected Behavior
Like Streams, Grokpatterns, Inputs and Outputs

## Current Behavior
no Possibility to Backup and Restore Pipelines

## Possible Solution
Content-Packs

## Context
We Use Content-Packs as Form of Backup and Restore for Graylog Config

## Your Environment
Graylog 2.3.1+9f2c6ef on syslog.xyz.local (Oracle Corporation 1.8.0_141 on Linux 3.10.0-514.26.2.el7.x86_64)

**Comment by joschi** [comment]
Similar to Graylog2/graylog-plugin-pipeline-processor#109

**Comment by joschi** [comment]
Duplicates #2507
