### ISSUE TITLE
Allow Create Dashboard for Individual Users

### ISSUE THREAD

**Issue by cessner-nw** [Graylog2/graylog2-server#4133]
## Expected Behavior
When a user that doesn't have admin wants to create dashboards, they should at-least be allowed to create dashboards for themselves. Certain engineers need or want certain things to manage or watch the health of their area of responsibility 

## Current Behavior
Only admins can create dashboards that are shared to everyone via a role as edit or read only of that dashboards contents. This makes allowing users to create their own dashboards, well impossible, without some serious on account creation API call for each user/role assignment to create dashboards, which will pollute the dashboard top level view.

## Possible Solution
Let users create their own dashboards by default. Leave admin dashboards for overall system health to shared or system dashboards.

## Steps to Reproduce (for bugs)
Cant create a dashboard if you're not admin

## Context
We asked our 90 some odd engineers what features they wanted if we moved off our our current log aggregation platform. This is at the top of the list.

## Your Environment
AWS

* Graylog Version: 2.3
* Elasticsearch Version: 5
* MongoDB Version: NA
* Operating System: Ubuntu
* Browser version: Chrome/Firefox

**Comment by joschi** [comment]
@cessner-nw You can create a role with the `dashboards:create` permission and assign that role to the users who should be able to create dashboards.

Please refer to https://github.com/Graylog2/graylog2-server/blob/2.3.1/graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java#L49 and http://docs.graylog.org/en/2.3/pages/users_and_roles.html for details.

**Comment by cessner-nw** [comment]
Hmmm I don't see this option in the UI. Is this a new feature for 2.3.1 or an API only option or did I overlook something?

**Comment by joschi** [comment]
@cessner-nw Permission management is currently only possible via the Graylog REST API as described in the documentation: http://docs.graylog.org/en/2.3/pages/users_and_roles/permission_system.html

**Comment by cessner-nw** [comment]
{
  "name": "Engineer",
  "description": "All Engineers Role",
  "permissions": [
    "dashboards:create",
    "dashboards:read"
  ],
  "read_only": false
}

I get a 200 back and maintain RO on the dashboards that exist, but don't see a create option in the UI for Engineer role member users.

**Comment by cessner-nw** [comment]
So create dashboard via the UI works. The issue I now have is the user that created the dashboard can't create widgets for it.

**Comment by joschi** [comment]
Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog) and include all necessary details, such as the created roles and permissions, the exact error message, and what you've been doing when the error message appeared.

Thank you!
