### ISSUE TITLE
Create certificate

### ISSUE THREAD

**Issue by DodgeCamaro** [Graylog2/graylog2-server#4135]
Please!
Help me with create certificate for htttps-connection.
In your instruction I dont find full steps to create key.
How create key?

**Comment by jalogisch** [comment]
Hej @DodgeCamaro 

our Documentation did have all needed steps, but to easy that process up I had created [this script](https://github.com/jalogisch/bartwickelmaschine/blob/master/create_self_signed_ssl_certs/create_ssl_certs.sh) that generates the certificates.

The manual steps are written in the docs: http://docs.graylog.org/en/2.3/pages/configuration/https.html#creating-a-self-signed-private-key-certificate

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by DodgeCamaro** [comment]
Later I write about script. 
This documentation is not complete.
How I create key (2) without key (1)?
How create two keys in 3-4 command line?
