### ISSUE TITLE
Can't Create Widgets for Role that Has dashboards:create in permissions

### ISSUE THREAD

**Issue by cessner-nw** [Graylog2/graylog2-server#4137]
## Expected Behavior
When i enable the permissions for the role, Engineer to have dashboards:create, the user can then create dashboards. They then however, once creating a dashboard, can't create widgets for their own dashboards. This is unusable behavior.

## Current Behavior
Once the API call is made to enable dashboads:create for the role, the user gets a permissions error trying to add widgets to their own dashboard they created.

## Possible Solution
Any user that is allowed to create a dashboard, should by default be allowed to read/edit that dashboard.

## Context
Users need to not only be able to create their own dashboards, but they should be allowed to edit the ones they create by default.

## Your Environment

* Graylog Version:2.3.1
* Elasticsearch Version:5
* MongoDB Version:
* Operating System:OS X
* Browser version:Chrome

**Comment by jalogisch** [comment]
this will be fixed with: https://github.com/Graylog2/graylog2-server/pull/4155

**Comment by bernd** [comment]
Fixed in https://github.com/Graylog2/graylog2-server/pull/4155
