### ISSUE TITLE
(Stream) Output resources require wrong permissions

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#4142]
## Expected Behavior

The `/system/outputs` and `/streams/{streamid}/outputs` resources should be usable with the right set of permissions, i. e. `outputs:read` for `GET /system/outputs` ("Get a list of all outputs").

## Current Behavior

`GET /system/outputs` only returns successful if the user has the `stream_outputs:create` permission.

## Possible Solution

Fix permissions required for `/system/outputs`, `/streams/{streamid}/outputs`, and related resources.

## Context

Refs https://community.graylog.org/t/permission-role-for-outputs-not-working/2399

**Comment by bernd** [comment]
Moving this into the 3.0.0 milestone.
