### ISSUE TITLE
Copy Dashboard

### ISSUE THREAD

**Issue by yoster0520** [Graylog2/graylog2-server#4144]
I want to copying a existing dashboard. 
## Expected Behavior
In dashboard page, has some button can allow us to copy a dashboard.

## Your Environment

* Graylog Version: 2.3
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@yoster0520 As a workaround, you can create a content pack with your dashboard(s) and apply it again to effectively "clone" the dashboard.

**Comment by yoster0520** [comment]
Thanks.
Jonah Cui




在 2017年9月13日，15:33，Jochen Schalanda <notifications@github.com<mailto:notifications@github.com>> 写道：


@yoster0520<https://github.com/yoster0520> As a workaround, you can create a content pack with your dashboard(s) and apply it again to effectively "clone" the dashboard.

**Comment by KnowMoreIT** [comment]
This doesn't appear to work especially in 3.0-3.1.  What I have found is when you do this the data is the same across all dashboards you install. So if you install the content pack twice but use different search queries (tied mine to a parameter), the dashboard shows data from the last time it loaded. So Dashboard1 will have same data when you go to dashboard 2
