### ISSUE TITLE
Extractor and filter help

### ISSUE THREAD

**Issue by ilyasr** [Graylog2/graylog2-server#4146]
I am logging event & iis logs at the moment but i do get alot of diffrent fields from each. I use nxlog shipper. I want to combine alot of field which are similar and filter the fields i dont need. I am quite new with graylog can some please help? 
## Current Behavior

I use grok patrons but i dont see any difference in the seach tab. 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 2.3
* Elasticsearch Version: 5.5.4
* MongoDB Version: -
* Operating System: Windows server 2012
* Browser version: Chrome 60.0.3112.113

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by ilyasr** [comment]
i did so i am gonna delete this issu thanks for help
