### ISSUE TITLE
Can't open pipelines page

### ISSUE THREAD

**Issue by FelixFV** [Graylog2/graylog2-server#4148]
![pipeline1](https://user-images.githubusercontent.com/7019849/30431178-d335b5c8-996e-11e7-8a31-4563fb54e5dd.PNG)
![pipeline2](https://user-images.githubusercontent.com/7019849/30431179-d3b11f42-996e-11e7-9473-633ebc354aae.PNG)

After update to graylog 2.3 I can't open pipelines' page
There isn't Pipelines in system menu

## Current Behavior

Pipelines works
Pipeline processor is active
Messages routes to streams
New fields creates by rules.
But I cant open / edit / delete it
When I open ip:9000/system/pipelines/ I get 404 error

in logs I saw: 
2017-09-14T15:26:42.719+03:00 INFO  [CmdLineTool] Loaded plugin: Pipeline Processor Plugin 2.2.0 [org.graylog.plugins.pipelineprocessor.ProcessorPlugin]
2017-09-14T15:26:50.070+03:00 INFO  [Periodicals] Starting [org.graylog.plugins.pipelineprocessor.periodical.LegacyDefaultStreamMigration] periodical, running forever.

But in folder I have: /usr/share/graylog-server/plugin/graylog-plugin-pipeline-processor-2.3.1.jar

## Your Environment

* Graylog Version: Graylog 2.3.1
* Operating System: CentOS
* Browser version: Chrome version 51.0.2704.84 m

**Comment by joschi** [comment]
@FelixFV Try cleaning your browser cache.

**Comment by FelixFV** [comment]
I try it with 2 accounts
2 browsers
2 another user sessions
no results :(

**Comment by joschi** [comment]
@FelixFV What plugins are installed in your Graylog environment?
Are you using the root account or a normal user account to check the availability of the menu item?

**Comment by FelixFV** [comment]
On my account I have "admin" role
Installed plugins:

Aggregates 2.0.0
Anonymous Usage Statistics 2.3.1
CEF Input 1.0.0
Collector 2.3.1
Elastic Beats Input 2.3.1
Enterprise Integration Plugin 2.3.1
ExeCommandAlarmCallBack 1.0.0
MapWidgetPlugin 2.3.1
Pipeline Processor Plugin 2.2.0
TelegramAlarmCallback 1.0.0

I'm using browser via windows OS. with Admin's rights

**Comment by joschi** [comment]
@FelixFV The pipeline processor plugin has the wrong version.

Check your plugin directory and remove the old version of the pipeline processor plugin.

**Comment by FelixFV** [comment]
But in folder only 1 file
I wrote about it in start topic:
/usr/share/graylog-server/plugin/graylog-plugin-pipeline-processor-2.3.1.jar
![pipeline3](https://user-images.githubusercontent.com/7019849/30468151-9d20e62e-99fa-11e7-99b1-ef59bf34c3d9.PNG)
I get it with ipdate.
Before update I have version 2.2.3 not 2.2.0 as in logs

**Comment by FelixFV** [comment]
I try to clean this folder and restart service.
there was no information about installed plugins in  logs and web interface
Put back this file - and again version 2.2.0
[graylog-plugin-pipeline-processor-2.3.1.jar.zip](https://github.com/Graylog2/graylog2-server/files/1305543/graylog-plugin-pipeline-processor-2.3.1.jar.zip)

**Comment by joschi** [comment]
@FelixFV The file you've uploaded looks correct and also includes the correct version metadata:
```text
$ unzip graylog-plugin-pipeline-processor-2.3.1.jar org.graylog.plugins.graylog-plugin-pipeline-processor/graylog-plugin.properties
Archive:  graylog-plugin-pipeline-processor-2.3.1.jar
  inflating: org.graylog.plugins.graylog-plugin-pipeline-processor/graylog-plugin.properties
$ cat org.graylog.plugins.graylog-plugin-pipeline-processor/graylog-plugin.properties
# The plugin version
version=2.3.1

# The required Graylog server version
graylog.version=2.3.1

# When set to true (the default) the plugin gets a separate class loader
# when loading the plugin. When set to false, the plugin shares a class loader
# with other plugins that have isolated=false.
#
# Do not disable this unless this plugin depends on another plugin!
isolated=false
```

Remove all 3rd party plugins and see if the problem persists.

**Comment by joschi** [comment]
@FelixFV What's the value of the `plugin_dir` setting in your Graylog configuration file?

**Comment by FelixFV** [comment]
plugin_dir = /usr/share/graylog-server/plugin

**Comment by joschi** [comment]
@FelixFV What's the output of the following commands on the system running Graylog?
```
# ls -laRt /usr/share/graylog-server/plugin
# find /usr/share/graylog-server/plugin/ -type f -exec md5sum "{}" \;
```

**Comment by FelixFV** [comment]
[commands.txt](https://github.com/Graylog2/graylog2-server/files/1305746/commands.txt)
add to attachment

**Comment by joschi** [comment]
@FelixFV Have you tried removing all 3rd party plugins?

**Comment by FelixFV** [comment]
now I remove all 3rd party files from plugin folder
same

**Comment by FelixFV** [comment]
2d17aba935e76b4be204d85fca9b89ba  /usr/share/graylog-server/plugin/graylog-plugin-map-widget-2.3.1.jar
3a08e9f97a9b1e8019c7fb69402ea8ad  /usr/share/graylog-server/plugin/graylog-plugin-input-cef-1.2.0.jar
21cd3d4b45241896e00656188e7eb27d  /usr/share/graylog-server/plugin/graylog-plugin-collector-2.3.1.jar
6a920fde57deef1c9551603997b447a3  /usr/share/graylog-server/plugin/graylog-plugin-beats-2.3.1.jar
52ced05c9e58ab930013e5b3c5fd0d92  /usr/share/graylog-server/plugin/graylog-plugin-anonymous-usage-statistics-2.3.1.jar
26da6d4e0051ddef3ff7310a17a114ad  /usr/share/graylog-server/plugin/graylog-plugin-pipeline-processor-2.3.1.jar

**Comment by joschi** [comment]
@FelixFV Have you cleaned your browser cache after removing the 3rd party plugins?

Also, please post the complete logs of your Graylog node(s) and the contents of the Developer (JavaScript) Console of your web browser.

**Comment by FelixFV** [comment]
I lost one 3rd party plugin
graylog-plugin-input-cef-1.2.0.jar
after remove it 
pipeline appears in menu.
![after](https://user-images.githubusercontent.com/7019849/30475174-f5eefec8-9a16-11e7-930b-c18fe8f4daf1.PNG)
![before](https://user-images.githubusercontent.com/7019849/30475175-f5f2fc58-9a16-11e7-9e3d-cafc8a665d88.PNG)

**Comment by joschi** [comment]
@FelixFV Thanks for providing all the information!

This is a bug in the Graylog CEF plugin which will be fixed in the next version.

**Comment by joschi** [comment]
@FelixFV Try using version 1.2.2 of the plugin:
https://github.com/graylog-labs/graylog-plugin-cef/releases/tag/1.2.2

**Comment by FelixFV** [comment]
@joschi Load it
pipelines presents in menu
right version
and cef plugin  enabled too
