### ISSUE TITLE
Skip TLS verification of elasticsearch hosts

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#4153]
## Expected Behavior
I need a option to disable the tls verification.

## Current Behavior
The connection fails due to:
```
2017-09-14 21:33:33,627 ERROR: org.graylog2.indexer.cluster.Cluster - Couldn't read cluster health for indices [graylog_*] (sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target)
```

## Possible Solution
- Option to disable tls verfification.
- Option to trust certificates stored somewhere

## Steps to Reproduce (for bugs)
Create an elasticsearch cluster with elasticsearch operator in kubernetes
Connect graylog docker container to elasticsearch cluster using GRAYLOG_ELASTICSEARCH_HOSTS

## Your Environment

* Graylog Version: 2.3.1
* Elasticsearch Version: 5.x
* MongoDB Version: 3.x
* Operating System: docker/kubernetes in minikube

**Comment by joschi** [comment]
@runningman84 You can add your self-signed certificates to the JVM trust store as described in the documentation: http://docs.graylog.org/en/2.3/pages/configuration/https.html#adding-a-self-signed-certificate-to-the-jvm-trust-store
