### ISSUE TITLE
Extractor doesn't support plugin.

### ISSUE THREAD

**Issue by yoster0520** [Graylog2/graylog2-server#4154]
I need to add a source field filter in grok extractor, but I found the extractor doesn't support plugin. So I can't do it.

## Expected Behavior
In the grok extractor or regex extractor, I need to use 'source' field filter to filter message, so I can extractor message accurately.

## Current Behavior
The extracotr doesn't support plugin.

## Context
My company has many network facility, I use the 514 port to listener syslog. I need to use source to recognize one facility, but I don't want to create stream, so I want to add a extractor's plugin.

## Your Environment

* Graylog Version: 2.3
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@yoster0520 Extractors can not be added by plugins.

Consider writing a custom processing pipeline function for your use case:
* https://www.graylog.org/blog/71-writing-your-own-graylog-processing-pipeline-functions
* http://docs.graylog.org/en/2.3/pages/pipelines.html
