### ISSUE TITLE
Feature request: loosen field name restrictions

### ISSUE THREAD

**Issue by fadenb** [Graylog2/graylog2-server#4157]
Original post in Graylog community board: https://community.graylog.org/t/fields-shown-in-json-extractor-preview-missing-in-processed-messages/2484

## Expected Behavior
* Send JSON into Graylog
  * Some field names contain parentheses (e.g. ```cs(Host)```)
* Apply JSON extractor
* After processing is complete Graylog should show **all** fields

## Current Behavior
* Send JSON into Graylog
  * Some field names contain parentheses (e.g. ```cs(Host)```)
* Apply JSON extractor
* Graylog silently dropped fields that contain parentheses in their name

## Possible Solution
Loosen field name restrictions as @joschi pointed out in his reply ( https://community.graylog.org/t/fields-shown-in-json-extractor-preview-missing-in-processed-messages/2484/2?u=fadenb )

## Context

This issue came up as we were ingesting CloudFront logs which uses field names like ```cs(Host)```,```cs(User-Agent)```, ```cs(Referer)``` and ```cs(Cookie)```

## Your Environment

* Graylog Version: Graylog 2.3.1+9f2c6ef
* Elasticsearch Version: 5.5.2
* Operating System: 18.03.git.2d0cc81

**Comment by florianvolle** [comment]
Hey @fadenb we are keeping the field names simple on purpose. You could use a Processing Pipeline to extract the JSON and apply different field names.
Thank you!
