### ISSUE TITLE
Key=Value extractor extracts empty values incorrectly

### ISSUE THREAD

**Issue by kiview** [Graylog2/graylog2-server#4164]
The Key=Value extractor does not recognize empty values. This results in messing up following key/value pairs.

## Expected Behavior
I have the following message:
```
NEW CONNECTION:  IN= OUT=enp0s20f3 MAC= SRC=10.20.20.253 DST=153.20.120.120 LEN=74 TOS=00 PREC=0x00 TTL=64 ID=41659 PROTO=UDP SPT=32663 DPT=53 LEN=54 UID=112 GID=118 MARK=0
```
I expect to extract a field `MAC` with empty content and a field `SRC` with content `10.20.20.253`.

## Current Behavior
The extractor will extract a field `MAC` with content `SRC=10.20.20.253`.

## Possible Solution
Allow empty values as valid values. If not easily feasible, simply drop empty keys altogether.

## Steps to Reproduce (for bugs)
1. Configure a key=value pair extractor as [documented](http://docs.graylog.org/en/2.3/pages/extractors.html#automatically-extract-all-key-value-pairs)
2. Insert a message containing an empty value like `X= Y=foo`

## Context
Since our `ulogd` logs have this format, key=value extractor is not usable and we have to rely on Grok pattern extraction.

## Your Environment
Dockerized Graylog deployment

* Graylog Version: graylog2/server:2.3.1-1
* Elasticsearch Version: 5.5.2
* MongoDB Version: 3.5
* Operating System: Ubuntu 16.04.3 LTS

**Comment by joschi** [comment]
Refs #3469

**Comment by bernd** [comment]
@kiview Please check the following comment for an explanation regarding this issue: https://github.com/Graylog2/graylog2-server/issues/3469#issuecomment-278295101
