### ISSUE TITLE
custom graylog dasboards

### ISSUE THREAD

**Issue by mj3018** [Graylog2/graylog2-server#4178]
can i use the graylog-web-interface dasboard page but without the header and footer?can i find a way to do this?

**Comment by mj3018** [comment]
in our application,we want use the graylog-web-interface default dasboards page to view our logs,but we want to hide the header and footer in the default dasboards page,can we do this?is there some quick way to this?

**Comment by bernd** [comment]
There is currently no option to hide the page header and footer and we also don't have this on our roadmap.

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
