### ISSUE TITLE
CSV Export issue

### ISSUE THREAD

**Issue by vladostp** [Graylog2/graylog2-server#4190]
The CSV export fails when I am trying to export a search result from more than 7 indices.

## Expected Behavior

The exported CSV files contains the search result data.

## Current Behavior

The exported CSV file contains only 10 lines

## Steps to Reproduce (for bugs)

1. Make a search in more than 7 indices
2. Try to make an CSV export
3. The exported CSV file will contain only 10 lines

## Context

I am trying to export data to CSV file

## Your Environment

* Graylog Version: 2.3.1+9f2c6ef
* Elasticsearch Version: 5.6.2
* MongoDB Version: 2.4.10
* Operating System: Debian 8.9
* Browser version: Firefox 55.0.2

**Comment by joschi** [comment]
@vladostp Please attach the contents of the "index_ranges" collection in MongoDB (e. g. using [mongoexport](https://docs.mongodb.com/manual/reference/program/mongoexport/)) and some example requests including their complete response which show the problem.

**Comment by vladostp** [comment]
[index_ranges.txt](https://github.com/Graylog2/graylog2-server/files/1343550/index_ranges.txt)

I am really sorry but I can't post any responses of requests cause it contains some sensitive data.

But I tried different type of searches in different set of indices and the behaviour was always the same:
- Search in 7 indices or less => Success
- Search in 8 or more indices => CSV File with 10 lines

**Comment by joschi** [comment]
> I am really sorry but I can't post any responses of requests cause it contains some sensitive data.

You can of course redact the sensitive parts of the requests and responses, but without any details, we'll be unable to reproduce the issue and thus help you.

**Comment by vladostp** [comment]
1) Search in the last 2 days an ip address
     Result: Found 1,267 messages in 6 ms, searched in 5 indices. => Success CSV Export 
[resultgood.csv.zip](https://github.com/Graylog2/graylog2-server/files/1343619/resultgood.csv.zip)
2) Search in the last 5 days an ip address
     Result: Found 2,120 messages in 41 ms, searched in 11 indices => CSV Export Fails (11 lines file)
[resultbad.csv.zip](https://github.com/Graylog2/graylog2-server/files/1343633/resultbad.csv.zip)

**Comment by joschi** [comment]
@vladostp Okay, that's the literal CSV file.

Could you try posting the complete HTTP requests and responses (without the response body) when exporting these? You can find them in the Developer Console of your web browser (or just post the output of curl if you're using that).

**Comment by vladostp** [comment]
Good Request:
```
GET /api/search/universal/relative/export?query=X.X.X.X&range=172800&fields=timestamp HTTP/1.1
Host: graylog.domain.com
Authorization: Basic YwFjYzZzODQtNjhmYS00Z2I3LWE4AZEtnDbjNzUxNTgyMTk2OnNlc3Npb24=
User-Agent: curl/7.55.1
Accept: */*
Connection: close
```

Good Response:
```
HTTP/1.1 200 OK
Date: Fri, 29 Sep 2017 08:48:49 GMT
Server: Apache/2.4.10 (Debian)
Content-Disposition: attachment; filename=graylog-search-result-relative-172800.csv
X-Graylog-Node-ID: 6f4b7833-e1cc-48a4-b8d8-99d02888609a
X-Runtime-Microseconds: 11817
Content-Type: text/csv
Connection: close
Content-Length: 34896

"timestamp"
"2017-09-28T13:36:19.000Z" + 1,291 lines of result

```

Bad Request:
```
GET /api/search/universal/relative/export?query=X.X.X.X&range=432000&fields=timestamp HTTP/1.1
Host: graylog.domain.com
Authorization: Basic YwFjYzZzODQtNjhmYS00Z2I3LWE4AZEtnDbjNzUxNTgyMTk2OnNlc3Npb24=
User-Agent: curl/7.55.1
Accept: */*
Connection: close
```

Bad Response:
```
HTTP/1.1 200 OK
Date: Fri, 29 Sep 2017 08:44:29 GMT
Server: Apache/2.4.10 (Debian)
Content-Disposition: attachment; filename=graylog-search-result-relative-432000.csv
X-Graylog-Node-ID: 6f4b7833-e1cc-48a4-b8d8-99d02888609a
X-Runtime-Microseconds: 55360
Content-Type: text/csv
Connection: close
Content-Length: 282

"timestamp"
"2017-09-28T13:36:19.000Z" + 9 lines of result
```

**Comment by olideakin** [comment]
We're seeing similar, requesting the CSV download through the web interface - for me it's the transition for 15 to 16 indices in the query that causes a 10 record CSV to be returned rather than the 10s of thousands expected.

**Comment by nickpeshek** [comment]
I think I've figured this out:

`New scroll id DnF1ZXJ5VGhlbkZldGNoPAAAAAAAAAw3Fl9yM2FiODFpUUctZTZSSlM2eGgyN3cAAAAAAAAC2RZqNHhnNHRqT1Q4YUhpaWJBM3l4MUp3AAAAAAAADDgWX3IzYWI4MWlRRy1lNlJKUzZ4aDI3dwAAAAAAAAw5Fl9yM2FiODFpUUctZTZSSlM2eGgyN3cAAAAAAAAJcxZROFVmb3lXWlJvbWUzSDFnZC1RS29nAAAAAAAACXQWUThVZm95V1pSb21lM0gxZ2QtUUtvZwAAAAAAAAl2FlE4VWZveVdaUm9tZTNIMWdkLVFLb2cAAAAAAAAJdRZROFVmb3lXWlJvbWUzSDFnZC1RS29nAAAAAAAACXcWUThVZm95V1pSb21lM0gxZ2QtUUtvZwAAAAAAAAw6Fl9yM2FiODFpUUctZTZSSlM2eGgyN3cAAAAAAAAMOxZfcjNhYjgxaVFHLWU2UkpTNnhoMjd3AAAAAAAADDwWX3IzYWI4MWlRRy1lNlJKUzZ4aDI3dwAAAAAAAAw9Fl9yM2FiODFpUUctZTZSSlM2eGgyN3cAAAAAAAAMPhZfcjNhYjgxaVFHLWU2UkpTNnhoMjd3AAAAAAAADD8WX3IzYWI4MWlRRy1lNlJKUzZ4aDI3dwAAAAAAAALaFmo0eGc0dGpPVDhhSGlpYkEzeXgxSncAAAAAAAAC2xZqNHhnNHRqT1Q4YUhpaWJBM3l4MUp3AAAAAAAADEAWX3IzYWI4MWlRRy1lNlJKUzZ4aDI3dwAAAAAAAAxBFl9yM2FiODFpUUctZTZSSlM2eGgyN3cAAAAAAAAMQhZfcjNhYjgxaVFHLWU2UkpTNnhoMjd3AAAAAAAACcgWRkJZenpDbmJTRE9qcW5VZzJEcGtBdwAAAAAAAAnGFkZCWXp6Q25iU0RPanFuVWcyRHBrQXcAAAAAAAAJxxZGQll6ekNuYlNET2pxblVnMkRwa0F3AAAAAAAACckWRkJZenpDbmJTRE9qcW5VZzJEcGtBdwAAAAAAAAxEFl9yM2FiODFpUUctZTZSSlM2eGgyN3cAAAAAAAAC3BZqNHhnNHRqT1Q4YUhpaWJBM3l4MUp3AAAAAAAADEMWX3IzYWI4MWlRRy1lNlJKUzZ4aDI3dwAAAAAAAALdFmo0eGc0dGpPVDhhSGlpYkEzeXgxSncAAAAAAAAMRRZfcjNhYjgxaVFHLWU2UkpTNnhoMjd3AAAAAAAACcsWRkJZenpDbmJTRE9qcW5VZzJEcGtBdwAAAAAAAAnEFkZCWXp6Q25iU0RPanFuVWcyRHBrQXcAAAAAAAAJxRZGQll6ekNuYlNET2pxblVnMkRwa0F3AAAAAAAACcoWRkJZenpDbmJTRE9qcW5VZzJEcGtBdwAAAAAAAAnMFkZCWXp6Q25iU0RPanFuVWcyRHBrQXcAAAAAAAAJzRZGQll6ekNuYlNET2pxblVnMkRwa0F3AAAAAAAADEYWX3IzYWI4MWlRRy1lNlJKUzZ4aDI3dwAAAAAAAAxHFl9yM2FiODFpUUctZTZSSlM2eGgyN3cAAAAAAAAJzhZGQll6ekNuYlNET2pxblVnMkRwa0F3AAAAAAAACc8WRkJZenpDbmJTRE9qcW5VZzJEcGtBdwAAAAAAAAnQFkZCWXp6Q25iU0RPanFuVWcyRHBrQXcAAAAAAAAJeBZROFVmb3lXWlJvbWUzSDFnZC1RS29nAAAAAAAACXkWUThVZm95V1pSb21lM0gxZ2QtUUtvZwAAAAAAAAl6FlE4VWZveVdaUm9tZTNIMWdkLVFLb2cAAAAAAAAC3hZqNHhnNHRqT1Q4YUhpaWJBM3l4MUp3AAAAAAAABYMWZW5xTXhzcDlRaENpWnowTEpWQWpZUQAAAAAAAAWEFmVucU14c3A5UWhDaVp6MExKVkFqWVEAAAAAAAAFhRZlbnFNeHNwOVFoQ2laejBMSlZBallRAAAAAAAABYYWZW5xTXhzcDlRaENpWnowTEpWQWpZUQAAAAAAAAWHFmVucU14c3A5UWhDaVp6MExKVkFqWVEAAAAAAAAJexZROFVmb3lXWlJvbWUzSDFnZC1RS29nAAAAAAAACXwWUThVZm95V1pSb21lM0gxZ2QtUUtvZwAAAAAAAAl-FlE4VWZveVdaUm9tZTNIMWdkLVFLb2cAAAAAAAAJfRZROFVmb3lXWlJvbWUzSDFnZC1RS29nAAAAAAAACX8WUThVZm95V1pSb21lM0gxZ2QtUUtvZwAAAAAAAAmAFlE4VWZveVdaUm9tZTNIMWdkLVFLb2cAAAAAAAAJgRZROFVmb3lXWlJvbWUzSDFnZC1RS29nAAAAAAAACYIWUThVZm95V1pSb21lM0gxZ2QtUUtvZwAAAAAAAAmDFlE4VWZveVdaUm9tZTNIMWdkLVFLb2cAAAAAAAAAHBZkbnJ3dkhEUlFiaUZSN1V5VUJSV0hnAAAAAAAAAt8WajR4ZzR0ak9UOGFIaWliQTN5eDFKdw==, number of hits in chunk: 10`

That scroll ID is ~2500 characters.

https://github.com/searchbox-io/Jest/blob/master/jest-common/src/main/java/io/searchbox/core/SearchScroll.java#L15

The SearchScroll class has an absolute max scroll ID length of 1900, so we parse the initial scroll A-OK, then create the ScrollResult with the scrollID that's too long, it will be left out

**Comment by NickMeves** [comment]
Can confirm -- we are seeing the same thing in our installation after the upgrade to 2.3.1.  Haven't tested how many indices are int he query before this breaks down, but our exports only have 10 lines as well.
