### ISSUE TITLE
Authentication is case-sensitive and creates new user if unexpected case is used

### ISSUE THREAD

**Issue by jbaker10** [Graylog2/graylog2-server#4202]
## Expected Behavior

When logging in with LDAP credentials (I have not tested this with local credentials), the letter case should not matter in the username and the user should be able to authenticate properly and map to the correct user.

## Current Behavior

When logging in with LDAP credentials, if a letter is capitalized that Graylog does not expect to be capitalized, the user is authenticated, but is seen as a different user in Graylog server and is assigned the default Role of Reader.

## Possible Solution

My assumption is that this is not in fact related to authentication but perhaps the database that holds the user information. The user authenticates and the authentication mechanism recognizes the username as being correct one, even if there is a capital letter, but when the info is passed to the database to retrieve what role the user should have, the database sees the capital letter, assumes it is a new user, and assigns the role as such.

## Steps to Reproduce (for bugs)

1. Login with an LDAP account and assign it Admin rights
2. Login with the LDAP account, but this time capitalize the first letter of the username (i.e. bakerjr on the first login, Bakerjr on the second)
3. Under System/Authentication, you will see two separate users, one with the Admin and Reader rights (bakerjr), and one with just the Reader rights (Bakerjr)

## Context

When using a mobile device, capitilzation in form entries is assumed for the first letter. Therefore, unless manually editing the username to _not_ have a capital letter in the beginning, the user could login and be confused as they do not have the proper permissions, even though from their end, they logged in successfully.

## Your Environment

* Graylog Version: 2.3.1
* Elasticsearch Version: 2.4.5
* MongoDB Version: 3.2.15
* Operating System: iOS/macOS/Windows
* Browser version: Chrome/Safari/Internet Explorer

**Comment by joschi** [comment]
Duplicates #1361
