### ISSUE TITLE
Show total size of all Graylog indices on the index sets overview page

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#4204]
Currently, if you want to know how much disk space all indices are taking up together in total, you have to manually add up all the index set sizes you can see on the index sets overview page.

This can become very annoying if you have a lot of index sets and we should display the total size of all indices managed by Graylog on that page.

**Comment by jalogisch** [comment]
could be something like the output from 

```
curl 'http://ELASTICSEARCHIP:9200/_cat/nodes?v&h=n,ip,disk*'
```

**Comment by liberomic** [comment]
@jalogisch 
Do you have a command for specific indexes ? your command is great for all indexes

**Comment by jalogisch** [comment]
@liberomic as this is the **cat api** of Elasticsearch, it can be shifted to the context of [indices](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-indices.html#cat-indices) very easy.

```
curl 'http://ELASTICSEARCHIP:9200/_cat/indices/graylog*?v'
```

might need a little more tuning but you are able to get that information. Please note that this is already visible in Graylog. The feature request is only to show the disk usage in some kind of information/overview.

**Comment by liberomic** [comment]
@jalogisch 
THANKS
Do you have options to sum option for specifix indexes as a first command. I wand send this information in graylog to capture the storage utilizzation for specific source.
