### ISSUE TITLE
Misaligned stacked chart popover on dashboards in Firefox

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#4208]
## Expected Behavior

The popover element for stacked charts on a dashboard should be aligned correctly in the Firefox browser.

## Current Behavior

Firefox looks like this:

![peek 2017-10-05 13-54](https://user-images.githubusercontent.com/461/31225996-ccc93d74-a9d4-11e7-8093-bee828a11dbc.gif)

Chrome looks like this:

![peek 2017-10-05 13-54-1](https://user-images.githubusercontent.com/461/31225998-cf7ecc78-a9d4-11e7-9d5e-7ad684478ba7.gif)

## Steps to Reproduce (for bugs)

1. Use Firefox
2. Create a stacked chart on the search page and add it to a dashboard
3. Navigate to the dashboard and hover over the newly created widget

## Your Environment

* Graylog Version: 3.0.0-SNAPSHOT (rev 41d4e41d3)
* Browser version: Firefox 56.0, Chrome 61.0.3163.100

**Comment by kroepke** [comment]
The data popup is only broken if the widget is not in the first row.
To reproduce create a second widget and position the stacked chart underneath it.

**Comment by kroepke** [comment]
This is likely a problem with C3 referencing the DOM element and react-grid-layout modifying it after C3 saved the y offset.
Since C3 is likely to be replaced in a later version, we'll not address this issue for the moment.

**Comment by bernd** [comment]
@kroepke Thank you. I will remove it from the 2.4 milestone.

**Comment by edmundoa** [comment]
In the current master, I'm also seeing this in Chrome and quick value tooltips (also when the widget is not in the first row). I'll add this issue to the 3.0.0 milestone so that we don't forget to take a look.

<img width="419" alt="screen shot 2018-01-24 at 14 47 03" src="https://user-images.githubusercontent.com/716185/35335317-88d9525a-0115-11e8-86e5-80f9d415b557.png">

**Comment by bernd** [comment]
We are using a new graph library since then so this can be closed.
