### ISSUE TITLE
Re-implement Graphite integration

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#421]

**Comment by marinaturetsky** [comment]
hello 
when this is expected to be resolved ?

**Comment by lennartkoopmann** [comment]
@marinaturetsky This will be released as a plugin soon, but there is no definite date yet.

**Comment by mariussturm** [comment]
A first version can be found here: https://github.com/Graylog2/graylog-plugin-output-metrics/releases/tag/1.0.0

**Comment by bernd** [comment]
Closing this issue now. Please use the metrics output plugin for this. https://github.com/Graylog2/graylog-plugin-output-metrics
