### ISSUE TITLE
Alert Triggered but message is not included (still happening)

### ISSUE THREAD

**Issue by 123dev** [Graylog2/graylog2-server#4210]
Please see the ticket: https://github.com/Graylog2/graylog2-server/issues/2382
for the original issue.

This ticket is to report that the problem is still occurring on Graylog 2.3.1

## Summary
Alerts are properly triggered, however every now and then (not predictable or easily reproducible) the message is not included.

To confirm that this was not due to a plugin, we have setup multiple alert notification plugins (jira, slack)
and when the problem occurs, none of the plugins get the last message.

## Expected Behavior
Message(s) should always be included.

## Current Behavior
Sporadically messages are missing.

## Possible Solution
I don't have any

## Steps to Reproduce (for bugs)
I wish I can provide easy steps to reproduce the issue, it just that every now an then, an alert arrives without the message content.

## Context
With Jira plugin, we get a new issue created that has no useful context
With Slack plugin, we don't see the issue details

## Your Environment

* Graylog Version: 2.3.1
* Elasticsearch Version: 5.5.1
* MongoDB Version: 2.4.9
* Operating System: Linux Debian jessie/sid ( 3.13.0-129-generic x86_64)
* Browser version: Latest Chrome

If there is any additional information we can provide that aids narrowing this down, just let us know.

Thanks

**Comment by bernd** [comment]
The alerting system has been replaced with the new alerts and events system in the meantime. Please open a new issue if you still see this problem. Thank you!
