### ISSUE TITLE
Histogram zoom selection is not cleared upon search time range/query change

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#4213]
## Expected Behavior

When the search histogram on the search results page is zoomed in (making a selection on the graph) and a new search query is submitted afterwards, the ranges of the X axis of the histogram should be reset to the limits of the data returned by the new search query.

## Current Behavior

When a selection is made on the search histogram, a new search that is submitted will not change it, instead the old range is kept. When the new search query does not return data for this timerange, the histogram will be empty.

![screen shot 2017-10-06 at 16 53 12](https://user-images.githubusercontent.com/41929/31283853-11151df8-aab7-11e7-8317-e89e10ec2e12.png)

## Steps to Reproduce (for bugs)

1. Go to the search page
2. Submit a generic search query with a time range of last 5 minutes
3. Make a selection in the histogram
4. Change the search selection to an absolute time range that does not include the last five minutes

## Your Environment

* Graylog Version: 3.0.0-SNAPSHOT
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
This is not an issue anymore with the new search page.
