### ISSUE TITLE
Remove support for Elasticsearch 2.x and add support for 6.x

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#4227]
Let's drop support of ES v2.x and also support v6.x to avoid lagging behind for too long.

**Comment by tangyong** [comment]
looking forward to updating into elasticsearch 6.0 GA very much!

**Comment by ernestgwilsonii** [comment]
Any ETA on Elasticsearch **6**x yet?
RE: _"Graylog 2.4 does not work with Elasticsearch 6.x yet!"_
REF: http://docs.graylog.org/en/2.4/pages/configuration/elasticsearch.html

**Comment by jalogisch** [comment]
@ernestgwilsonii that is placed in the Milestone for 3.0 - what will be the next version of Graylog.

**Comment by ernestgwilsonii** [comment]
@jalogisch Thanks for the update! How can folks follow along with upcoming 3.0 news, features and testing?

**Comment by jalogisch** [comment]
@ernestgwilsonii yes, that are the best ways. Consider the Podcast to be random.

**Comment by ajmulhollan1** [comment]
Is there any likelihood that you'll release a 2.4.X that contains compatibility with Elasticsearch 6? We've already upgraded, and don't really want to revert that upgrade. It seems 3.0 is still a way off.

Graylog is working, but it's using graylog_deflector index and of course building up too quickly.

**Comment by joschi** [comment]
> Is there any likelihood that you'll release a 2.4.X that contains compatibility with Elasticsearch 6?

No, that's entirely unlikely.

**Comment by nemmeviu** [comment]
+1

**Comment by hydrapolic** [comment]
+1

**Comment by jam49** [comment]
ES 5.6 end of life is 2019-03-11. ES 6.0 support will be needed by this time to meet internal security requirements.
