### ISSUE TITLE
allow non-admin user to see all input logs(messages)

### ISSUE THREAD

**Issue by sugun999** [Graylog2/graylog2-server#4228]
Hi,

What roles must be assigned to allow non-admin user to see all show received messages of inputs as similar to admin user?

I created non-admin user with "sources:read" permissions. But on selecting "sources" tab throws below errors.
Could not load histogram data and Could not load sources data

Any help appreciated.

Thanks

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
