### ISSUE TITLE
Wrong spacing with new field analyzer buttons 

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#4230]
## Expected Behavior

There should be consistent spacing between the field analyzer widget buttons.

## Current Behavior

After #4219 went it, there is no spacing between the "Add to dashboard" and "Customize" buttons in the field analyzer widgets. 

QuickValues:
![image](https://user-images.githubusercontent.com/461/31383751-7afb8308-adbc-11e7-950d-1637096a2455.png)

Chart:
![image](https://user-images.githubusercontent.com/461/31383762-82ed68ec-adbc-11e7-8f5d-f3b083fae7ce.png)

## Possible Solution

I guess we want to use a `ButtonGroup` wrapper component to get consistent spacing.

## Steps to Reproduce (for bugs)

1. Create QuickValues widget on the search page
2. Create Chart widget on the search page
3. Create map widget on the search page

## Your Environment

* Graylog Version: 3.0.0-SNAPSHOT (a99ea1d647852ead1f7edaffc4e2f558110d03d5)
* Browser version: 61.0.3163.100

**Comment by joschi** [comment]
@bernd I think that was intentional by @lennartkoopmann.

At least I read it that way in https://github.com/Graylog2/graylog2-server/pull/4219#issue-263610285
> The change to a close icon makes it stand out more and also saves real-estate. A margin to the left helps to identify it quickly and avoids accidental pressing of it.

**Comment by bernd** [comment]
@joschi @lennartkoopmann If it was intentional, the "Customize" and "Add to dashboard" buttons should at least be grouped like before.

![image](https://user-images.githubusercontent.com/461/31386829-864cc878-adc8-11e7-82a7-e081f538b1ce.png)

Now it looks like there is a missing margin.

**Comment by lennartkoopmann** [comment]
You are right, the previous implementation looked a little different with regards to the borders of the two buttons. I guess the `ButtonGroup` styling got messed up by an inline `div` that I added.

I’m okay with moving this out of 2.4 if this is not an easy fix.
