### ISSUE TITLE
Authentication menu

### ISSUE THREAD

**Issue by TenGbps** [Graylog2/graylog2-server#4234]
Menu Authentication dont show when have perm to see it.

Permissions
```
        "roles:edit", 
        "roles:create", 
        "roles:read", 
        "roles:delete", 
        "users:tokencreate", 
        "users:rolesedit:*", 
        "users:edit:*", 
        "users:permissionsedit:*", 
        "users:list", 
        "users:tokenlist", 
        "users:create", 
        "users:passwordchange:*", 
        "users:tokenremove
```

The menu is hidden on dashboard.

* Graylog Version: 2.3.1
* Elasticsearch Version: 5.5.1
* MongoDB Version: 2.6.12
* Operating System: CentOS7
* Browser version: Firefox ESR 52.4

**Comment by joschi** [comment]
@TenGbps I'm not sure what you mean. Maybe you could add a screenshot?

**Comment by TenGbps** [comment]
With
`        "*",`

![allperm](https://user-images.githubusercontent.com/30792994/31438438-6854cd00-ae88-11e7-8428-a073b418869b.png)

With
```
        "roles:edit", 
        "roles:create", 
        "roles:read", 
        "roles:delete", 
        "users:tokencreate", 
        "users:rolesedit:*", 
        "users:edit:*", 
        "users:permissionsedit:*", 
        "users:list", 
        "users:tokenlist", 
        "users:create", 
        "users:passwordchange:*", 
        "users:tokenremove",
```
![without](https://user-images.githubusercontent.com/30792994/31438442-6a30f6f8-ae88-11e7-8ecd-84211bfbffcd.png)

**Comment by joschi** [comment]
@TenGbps In order to see the System / Authentication menu item, users require the following permissions:
* `users:list`
* `roles:read`

Are you sure your user has a role which includes these permissions?

https://github.com/Graylog2/graylog2-server/blob/9f2c6ef5c1c0f8b77e73d1298d57c7223087eedf/graylog2-web-interface/src/components/navigation/Navigation.jsx#L214-L218

**Comment by joschi** [comment]
Ah!

There's a typo in the permissions. It's missing the single quotes between the individual permissions.

@TenGbps Thanks for reporting this!
