### ISSUE TITLE
Correlation of messages

### ISSUE THREAD

**Issue by GambitK** [Graylog2/graylog2-server#424]
Right now graylog2 has the streams where you could define rules to match messages, the thing is that you need to know the specifics of what you are looking for.

There's on feature that I think would make graylog2 really powerful, the ability to correlate messages, example:

Alert01: If field "user" has the same value over a period of N time and field "event=300" give me an alert.

Alert02: If field "host" has the same value over a period of N time and field "event=500" give me an alert.

Alert03: If field "host" has the same value and "event=150" is followed by "event=250" over a period of N time alert me.

The idea is that you could do behavior searches and alerts and not have only alerts based on discrete values. I've used this feature extensively in splunk, the alert would send the messages that triggered the rule. I think that's the main missing piece to bridge the gap between them.

**Comment by bernd** [comment]
As noted earlier, we have an output plugin for riemann now that can be used with riemann to do these things. https://github.com/Graylog2/graylog2-plugin-output-riemann

I am closing this now because we have lots of similar issue open and we know about this topic. :wink: 

Thank you!

**Comment by pramodanarase** [comment]
What is the status of this issue? which one is the correct issue  to monitor ?
Can we use Processing Pipelines to find Correlation of messages ?
Example - Find the start and end time of any process.

**Comment by joschi** [comment]
@pramodanarase See https://github.com/Graylog2/graylog2-server/issues/424#issuecomment-76419510
