### ISSUE TITLE
where only one node can receive message ?

### ISSUE THREAD

**Issue by Cloud-Leung** [Graylog2/graylog2-server#4240]
i have a graylog cluster with two nodes，but only one nodes can receive meesage.

## Expected Behavior
i have a graylog cluster with two nodes，but only one nodes can receive meesage.

## Current Behavior
i have a graylog cluster with two nodes，but only one nodes can receive meesage.

## Steps to Reproduce (for bugs)
1.view the nodes info, looks like only the nodes of RZPT-LOG-2 is receiving the message.
![qq 20171012160952](https://user-images.githubusercontent.com/16982375/31486151-12dc023a-af69-11e7-9849-06caa52759cc.png)
2.view the inputs, it looks like both nodes is running.
![qq 20171012161024](https://user-images.githubusercontent.com/16982375/31486211-3e2c3702-af69-11e7-95c1-c30463f8bf91.png)

## Context
i just don't understand, it is the design or it's had something wrong .

## Your Environment

* Graylog Version: 2.2.3
* Elasticsearch Version: 2.3.3
* MongoDB Version: 3.2.14

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
