### ISSUE TITLE
can i intergrate my application login process with graylog?

### ISSUE THREAD

**Issue by mj3018** [Graylog2/graylog2-server#4242]
## Expected Behavior
while my application has logged in,i want to graylog also has logged in.
now i have put the graylog pages into my application,so i want to integrate the login process with my application,can i do this?

## Current Behavior
the login process are separated.

* Graylog Version:latest
* Elasticsearch Version:latest
* MongoDB Version:latest
* Operating System:latest
* Browser version:latest

**Comment by joschi** [comment]
You could use the [SSO plugin](https://github.com/Graylog2/graylog-plugin-auth-sso/) for this or write your own authentication plugin.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by mj3018** [comment]
ok thanks
