### ISSUE TITLE
Content pack is not evaluating system environment variable

### ISSUE THREAD

**Issue by nicktogo** [Graylog2/graylog2-server#4245]
## Expected Behavior
I created a content pack to add a RabbitMQ Input for graylog and I specified the login credential for RabbitMQ as following (other settings are hidden):
```json
"broker_username":"%{RABBITMQ_DEFAULT_USER}",
"broker_password":"%{RABBITMQ_DEFAULT_PASS}",
```
I setup a docker container for graylog and setup the two system environment variables: `RABBITMQ_DEFAULT_USER` and `RABBITMQ_DEFAULT_PASS`
The expected behavior is that when graylog is loading the content pack, it will evaluate the two environment variables.

## Current Behavior
Graylog simply does not evaluate these two environment variables and then resulted in connection refused due to incorrect login credential

## Your Environment

* Graylog Version: 2.2.3

Is there other way that I can make the content pack to connection to RabbitMQ without explicitly hardcoding the credential in the json file?

**Comment by joschi** [comment]
Duplicates #4224.
