### ISSUE TITLE
FQA url reference to doc is broken

### ISSUE THREAD

**Issue by tjyang** [Graylog2/graylog2-server#4251]
FQA url reference to doc is broken
## Expected Behavior

Be able to click and reach referred section in graylog doc set.
## Current Behavior

![image](https://user-images.githubusercontent.com/378638/31616330-0a46d550-b252-11e7-80b4-6e4e4cc02d4d.png)

## Steps to Reproduce (for bugs)

1.  Read the FAQ link at 
https://github.com/Graylog2/documentation/blob/8da576777e614ef8f5b99889f6b6ff4e9badf8d9/pages/faq.rst#id1
2. in https://github.com/Graylog2/documentation/blob/8da576777e614ef8f5b99889f6b6ff4e9badf8d9/pages/faq.rst#functionality
3. click on ":doc:`data retention features <index_model>`." link

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@tjyang GitHub doesn't render reStructuredText (RST) in the same way [Sphinx](http://www.sphinx-doc.org/) (or [ReadTheDocs.org](https://readthedocs.org/)) does and doesn't resolve references across files.

Please use the official documentation at http://docs.graylog.org/en/2.3/pages/faq.html#can-graylog-automatically-clean-old-data
