### ISSUE TITLE
multiline logs from kafka

### ISSUE THREAD

**Issue by habib-the-sweet** [Graylog2/graylog2-server#4252]
Some service sending multi-line error message to Kafka:

```
2017-10-13T12:30:40.979Z [INFO] $ CurrentRates [listeners/pullData]:  { error: null value in column "touch8" violates not-null constraint
    at Connection.parseE (connection.js:539:11)
    at Connection.parseMessage (connection.js:366:17)
    at Socket.<anonymous> (connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'error',
  length: 230,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (6995353, round, 0.00667472, null, 2017-10-13 12:30:41).',
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: 'public',
  table: 'exchange_rates',
  column: 'touch8',
  dataType: undefined,
  constraint: undefined,
  file: 'execMain.c',
  line: '1699',
  routine: 'ExecConstraints' }
```
I'm expecting than Graylog will show me that error in one event block.
But actual Graylog show every line as new event block (see screenshot)

![image](https://user-images.githubusercontent.com/13257902/31622103-26d42194-b2a4-11e7-8489-b41f3b351887.png)

Graylog 2.3.1+9f2c6ef 
Linux 4.4.0-96-generic
Ubuntu 16.04.3 LTS

**Comment by joschi** [comment]
What input are you using to ingest these messages?
What's the configuration of that input?
Are you using any extractors or pipeline rules to post-process the messages?
Is the example you've posted the actual content of a message in Kafka?

**Comment by habib-the-sweet** [comment]
@joschi I'm using standard "Raw/Plaintext Kafka input" 

Here is the input configuration:

```
fetch_min_bytes: 5
fetch_wait_max: 100
offset_reset: largest
override_source: <empty>
threads: 2
throttling_allowed: false
topic_filter: microservices
zookeeper: zk01:2181
```

I'm not using any extractors for this input right now because before using extractor I need to have normal message block. 

It is the the actual content of a message in Kafka

**Comment by jalogisch** [comment]
@habib-the-sweet 

Graylog itself did not have the option to join the multilines into on message. You would need to submit those multiline messages as one message into kafka. If that multiline messages is submitted as one messages it will show up as single message in Graylog.

How did you submit the messages to Kafka? Did you tried the above already?

**Comment by sujeetbw** [comment]
Hello jalogisch,

I'm pushing modsecurity logs from linux server to gralog in syslog UDP input.

The problem is that I also getting the broken logs in graylog. the same mod-security generates on server.

Can you suggest anything.


![screenshot_1](https://user-images.githubusercontent.com/35889875/35496818-9ad35da8-04ed-11e8-9bba-62708b3d1bcb.png)

**Comment by bernd** [comment]
Graylog doesn't support joining multi-line logs, unfortunately. This needs to be done in the log collector. Sorry.
