### ISSUE TITLE
Multi ES Cluster

### ISSUE THREAD

**Issue by pdepaepe** [Graylog2/graylog2-server#4253]
Hello,

I had a dream. One graylog to rules them all.

## Expected Behavior
One Graylog Master, plenty of graylog servers handling multiple ES clusters.

## Current Behavior
If graylog can handle various index set policies, it relies on only one ES cluster.

## Possible Solution
You are not so far, since:

- You introduced index set per stream notion
- You switched to HTTP transport

## Context
Here, in my company, we use/love graylog a lot. We have dozens of graylog instances speaking to their respectively ES instances, but if we share a common LDAP, switching from a cluster to an other is unnecessary boring.
My dream is to have a single Graylog Endpoint to reach various ES instances.
Main complexity will come from default stream, which at this stage, i'm still not really understanding.

I know it represent lot of works in term of ingestion/query but you are more ready to get there than ever.

**Comment by joschi** [comment]
Refs #4199
Duplicates #3969
