### ISSUE TITLE
Permission search is need for edit extractor

### ISSUE THREAD

**Issue by TenGbps** [Graylog2/graylog2-server#4255]
When user have permission to edit only some extractor, on edit click, graylog use the search permission for load the last message and page dont load.

If searchs perm is set, user can view all logs of all streams & indices.

Permissions
```
        "inputs:edit:59......11c", 
        "inputs:read:59.......11c", 
```

![edit extrator](https://user-images.githubusercontent.com/30792994/31656333-9544112a-b32b-11e7-968d-c8e0eea7b3a9.jpg)

* Graylog Version: 2.3.1
* Elasticsearch Version: 5.5.1
* MongoDB Version: 2.6.12
* Operating System: CentOS7
* Browser version: Firefox ESR 52.4

**Comment by joschi** [comment]
@TenGbps What are the complete permissions of the user?

**Comment by TenGbps** [comment]
```
 "permissions": [
    "users:edit:test",
    "users:passwordchange:test",
    "clusterconfigentry:read",
    "indexercluster:read",
    "messagecount:read",
    "journal:read",
    "messages:analyze",
    "inputs:read",
    "metrics:read",
    "savedsearches:edit",
    "fieldnames:read",
    "buffers:read",
    "system:read",
    "savedsearches:create",
    "jvmstats:read",
    "decorators:read",
    "throughput:read",
    "savedsearches:read",
    "messages:read",
    "roles:edit:59e5....",
    "indexranges:rebuild",
    "inputs:edit:59db....",
    "dashboards:read:59c3....",
    "indexsets:read:59c3....",
    "roles:read",
    "inputs:terminate:59db....",
    "indices:failures:59c3....",
    "streams:read:59e5c....",
    "indexranges:read",
    "roles:edit:59e5....",
    "indices:read",
    "inputs:read:59d....",
    "dashboards:edit:59c...."
  ],
```

**Comment by joschi** [comment]
@TenGbps There's currently no workaround for this.

The message loader on the extractor page needs search permissions.

If the user is not allowed to use the (universal) search, we cannot show any messages because users might see messages they're not supposed to see in the first place.

We won't change how the extractor page is working in the short or midterm, but I've added the "known issue" label to this issue so we can refer to it in the FAQ.

**Comment by TenGbps** [comment]
Maybe just don't load message and let the page load and let user put id. Because the user sees no errors, only be redirect.
