### ISSUE TITLE
Fetching index sets list failed: Couldn't find default index set 

### ISSUE THREAD

**Issue by MikeGlotzkowski** [Graylog2/graylog2-server#4260]
## This is the Bug-Text:
Could not retrieve index sets.
Fetching index sets list failed: Couldn't find default index set <59ae8578a8361d0a943d773b>. This is a bug!

## Expected Behavior
Go to Graylog UI and go to System/Indices:
Indexes should be shown.

## Current Behavior
But this is shown:
![image](https://user-images.githubusercontent.com/10769657/31671846-3810d260-b35b-11e7-8d0c-4199f2af9702.png)

Same for call:
http://xx.xx.xx.xx:9000/api/system/indices/index_sets?skip=0&limit=0&stats=true
Answer:
```javascript
Response Body
{
  "type": "ApiError",
  "message": "Couldn't find default index set <59ae8578a8361d0a943d773b>. This is a bug!"
}
Response Code
500
```

## Your Environment
* Graylog Version: Graylog 2.2.3+7adc951 on graylog (Oracle Corporation 1.8.0_101 on Linux 4.4.0-71-generic)
* Elasticsearch Version: 2.4.2
* MongoDB Version: 3.4.1
* Operating System: ubuntu
* Browser version: 61.0.3163.100 (Offizieller Build) (64-Bit)

**Comment by joschi** [comment]
@MikeGlotzkowski Did you recently upgrade Graylog?
Are there any errors or warnings in the logs of your Graylog node?

The default index set should be created automatically the first time Graylog 2.2.x is being started.

**Comment by MikeGlotzkowski** [comment]
I did not updage Graylog.
I created a new inde set. There is a line that says "A unique prefix used in Elasticsearch indices belonging to this index set. The prefix must start with a letter or number, and can only contain letters, numbers, '_', '-' and '+'". (see picture)
![image](https://user-images.githubusercontent.com/10769657/31928630-1e47e3ee-b899-11e7-8893-4732ab69b7bb.png)
I chose a name with "+++" inside. I think thats the timeframe the began to bug out?!
There are logmessages, but where can i see them? 

Thank you for your help!

**Comment by joschi** [comment]
@MikeGlotzkowski Please post the complete logs of your Graylog node(s).

**Comment by jalogisch** [comment]
@MikeGlotzkowski 

did you create a new index set and set that new created index set as default?

could you please provide the log file as already requested.

**Comment by MikeGlotzkowski** [comment]
From /var/log/graylog/server

[GraylogLogfiles.zip](https://github.com/Graylog2/graylog2-server/files/1449457/GraylogLogfiles.zip)

**Comment by MikeGlotzkowski** [comment]
from var/log/elasticsearch

[elasticsearchLogfiles.zip](https://github.com/Graylog2/graylog2-server/files/1449501/elasticsearchLogfiles.zip)

**Comment by MikeGlotzkowski** [comment]
[elasticsearch from var log elasticsearch.zip](https://github.com/Graylog2/graylog2-server/files/1449561/elasticsearch.from.var.log.elasticsearch.zip)

**Comment by MikeGlotzkowski** [comment]
[elasticsearch from var log elasticsearch.zip](https://github.com/Graylog2/graylog2-server/files/1449563/elasticsearch.from.var.log.elasticsearch.zip)
[elasticsearch from var log graylog elasticsearch.zip](https://github.com/Graylog2/graylog2-server/files/1449564/elasticsearch.from.var.log.graylog.elasticsearch.zip)
[mongodb from var log graylog mongodb.zip](https://github.com/Graylog2/graylog2-server/files/1449565/mongodb.from.var.log.graylog.mongodb.zip)
[mongodb from var log mongodb.zip](https://github.com/Graylog2/graylog2-server/files/1449566/mongodb.from.var.log.mongodb.zip)
[server from var log graylog.zip](https://github.com/Graylog2/graylog2-server/files/1449567/server.from.var.log.graylog.zip)

**Comment by joschi** [comment]
@MikeGlotzkowski How exactly did you install Graylog?

From skipping the log files, it seems like there's a mix of the omnibus package (OVA) and another Graylog (or at least Elasticsearch and MongoDB) installation.

**Comment by MikeGlotzkowski** [comment]
Hi, thanks for your help so far!

I did not install the system myself...but i think there is a complete package with EL and mongoDb (which is not used) and an EL/Mongo installation which is used. 

I forgot to mention, that the server is running on a hyper-v-server. 

Can you advise a follow up action? Is clean install the best option?

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
