### ISSUE TITLE
"Could not execute search" while scrolling through message list

### ISSUE THREAD

**Issue by RalfWenzel** [Graylog2/graylog2-server#4261]
## Expected Behavior

 i run into an error when searching for messages in graylog server 2.2 web frontend.
The query itself is simple, just looking up messages that match two search criteria:

 \_exists\_:some_state AND dev_type:"mydevtype".

Number of messages depending on timeframe selected are as expected, everythink ok so far.

* "Last hour" -> "Found 2,412 messages in 8 ms, searched in 5 indices."
* "Last 2 hours -> "Found 4,742 messages in 8 ms, searched in 5 indices."
* "Last 8 hours -> Found 19,175 messages in 17 ms, searched in 5 indices.

Problems occurs when displaying messages after successfull search.using the control below to navigate between pages::

![image](https://user-images.githubusercontent.com/24491913/31674910-655771b8-b363-11e7-8732-4a17c668da33.png)

This works fine for the 1hour and 2hour results. I can navigate to the last page (thats my usecase, i want to csv export the data and do verification of first/last messages) 

## Current Behavior

When doing the same with the "Last 8hours" result i hit an error when selecting page "70" (see control above).

#### Could not execute search
There was an error executing your search. Please check your Graylog server logs for more information.

***Error Message:***
Unable to fulfill search request: cannot GET http://10.11.12.13:9000/api/search/universal/relativequery=_exists_%3Asome_state%20AND%20dev_type%3A%22mydevtype%22&range=28800&limit=150&offset=10350&sort=timestamp%3Adesc (500)
***Search status code:***
500
  

## Steps to Reproduce (for bugs)

- reproducible  when navigating large message result list.

## Context

- Context: see above
- Note: as said above, i ran into problems because i wanted to verify first and last page of a CSV export. before actually exporting. The CSV export itself works !
- Note 2: The exported file contains a different number of messages as displayed in search result.  I think this is because the query is executed a second time when "csv export" is selected. Because of slightly different timeframes message count in exported csv is not equal to the one shown in search result.
-> Workaround: Use absolute instead of relative timeframes when exporting. 
-> Idea: Maybe this should be clarified in docu also. From user's perspective i would expect same results when exporting after searching.

## Your Environment

* Graylog Version: 2.2
* Elasticsearch Version: 2.4.6
* MongoDB Version:
* Operating System: Ubuntu 16.04 LTS
* Browser version: Chrome 61.0.3163.100 (Offizieller Build) (64-Bit)

**Comment by joschi** [comment]
@RalfWenzel What's in the logs of your Graylog nodes?

This might also be related to #3571.

**Comment by RalfWenzel** [comment]
@joschi with reference to #3571 : possible. I did not narrow search results aronnd 10.000 but can try to reproduce this if it helps. 
Logs: will add info in some minutes.

**Comment by bernd** [comment]
This is related to #3571. Please watch that issue for updates about the problem. Thank you!
