### ISSUE TITLE
Cluster with 2 servers not working

### ISSUE THREAD

**Issue by brokerdavelhr** [Graylog2/graylog2-server#4272]
Tried install of graylog 2.3 cluster on 2 ubuntu 16.04 lts servers using the guide found here:
http://docs.graylog.org/en/2.3/pages/installation/os/ubuntu.html
and
http://docs.graylog.org/en/2.3/pages/configuration/multinode_setup.html

In short, the first server works exactly as it should and was no trouble at all. The second server is the same - everything workin as planned, and even has a slave relationship in elasticsearch with the first (master) server I setup. 

What should happen to all of the DOCs I have read, is that the second server is supposed to join the master servers node with no issues, and be visible in the master main web page. 
However this does not happen:
On Primary:
Graylog cluster
Cluster ID:
E4E41283-91DB-433C-893C-39C51129F5FF
Number of nodes:
1
On Backup:
"Certain operations of Graylog server require the presence of a master node, but no such master was started. Please ensure that one of your Graylog server nodes contains the setting is_master = true in its configuration and that it is running. Until this is resolved index cycling will not be able to run, which means that the index retention mechanism is also not running, leading to increased index sizes. Certain maintenance functions as well as a variety of web interface pages (e.g. Dashboards) are unavailable."
Graylog cluster
Cluster ID:
00000000-0000-0000-0000-000000000000
Number of nodes:
1

 - here is the following elasticsearch/graylog config changes I made:
==================================================================

Changes made in /etc/elasticsearch/elasticsearch.yml:

In master:
---------------
cluster.name: graylog

node.name: myhost1
node.master: true
network.host: myhost1

discovery.zen.ping.unicast.hosts: ["myhost1", "myhost2"]

In Slave:
--------------
cluster.name: graylog

node.name: myhost2
node.master: false
network.host: myhost2

discovery.zen.ping.unicast.hosts: ["myhost1", "myhost2"]

====================================================================

changes made in /etc/graylog/server/server.conf

Master:
---------
is_master = true
password_secret = my secret
root_password_sha2 = encrypted pw
rest_listen_uri = http://ipaddresstomaster:9000/api/
web_listen_uri = http://ipaddresstomaster:9000/

elasticsearch_hosts = http://node01:9200,http://node02:9200

elasticsearch_shards = 5
elasticsearch_replicas = 1

elasticsearch_index_prefix = graylog

Slave:
---------
is_master = false
password_secret = my secret
root_password_sha2 = encrypted pw
rest_listen_uri = http://ipaddresstoslave:9000/api/
web_listen_uri = http://ipaddresstoslave:9000/

elasticsearch_hosts = http://node01:9200,http://node02:9200

elasticsearch_shards = 5
elasticsearch_replicas = 1

elasticsearch_index_prefix = graylog

To my understanding, the node02 should join graylog cluster that the first (master) starts. It does not. 

At first I thought it was because of a possible mongo issue, but you cannot create a replica set (from what I have read), with only 2 servers. So I have nothing there. 

What am I missing? I will attach logs if needed, and thanks ahead of time!

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@brokerdavelhr Make sure that each Graylog node has a *unique* node ID (see `node_id_file` in the Graylog configuration file).
Also make sure that the Graylog nodes have access to the same MongoDB database.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Other than that, please provide the relevant information about your environment (currently left blank) when you post to the forums.

Thank you!
