### ISSUE TITLE
Upgrade The Latest Version- How to

### ISSUE THREAD

**Issue by hanabadler** [Graylog2/graylog2-server#4274]
Hi Graylog Group
i am using graylog and very much enjoy setting new plugins in the system. thank you
my question is
just received a message in web console that a new version was released.
i am using The AWS EC2 image (http://docs.graylog.org/en/latest/pages/installation/aws.html#amis) version 2.3.1 and the message says version 2.3.2 is ready
How to make the upgrade?
i saw some information on this link
https://stackoverflow.com/questions/25438095/how-can-i-upgrade-graylog2-to-a-newer-version
but it will be great if you can point to a full process .
thanks
Hana

**Comment by joschi** [comment]
The Graylog AMI is using the Graylog omnibus package and you can follow the upgrade instructions from the documentation: http://docs.graylog.org/en/2.3/pages/configuration/graylog_ctl.html#upgrade-graylog

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
