### ISSUE TITLE
List Of Pipeline Rules - export for backup

### ISSUE THREAD

**Issue by hanabadler** [Graylog2/graylog2-server#4275]
Hi Team
Question: is there a way to backup and restore all pipeline rules
we have about 50 Rules and wanted to know if it can be exported to some file, and imported later?

thanks
Hana

**Comment by joschi** [comment]
@hanabadler Currently, the pipeline rules can only be exported by dumping the respective collections in MongoDB and restoring them in the MongoDB database used by the new Graylog instance:
* pipeline_processor_pipelines
* pipeline_processor_pipelines_streams
* pipeline_processor_rules

Also see this related issue: #4222
