### ISSUE TITLE
Granular Alert State based on Source field

### ISSUE THREAD

**Issue by jasonkeller** [Graylog2/graylog2-server#4283]
This is more of a feature enhancement request than anything...a short while back stateful alerting was introduced.  In order for it to be a bit more useful, we would like if it could differentiate between different devices and not quell alerts fired from devices that haven't alarmed yet.

For example - 
Stateful alerts are set up on a stream matching messages about a switch stack member failure.  A message comes in from one stack and trips the alert state, but while the alert state is now in alarm, a message comes in from a different switch stack about a failed member.  This one does not trip an alert, as a previous failure has already put the alert state in alarm.

It would be nice if the alert state could be more tracked on a more granular basis (i.e. per source field value).

**Comment by jalogisch** [comment]
@jasonkeller that is some kind of related to: https://github.com/Graylog2/graylog2-server/issues/3966

Currently that would only work if you use a monitoring system that checks a stream and handle the alerts. But not with vanilla Graylog.

**Comment by bernd** [comment]
This is possible with the new alerting in 3.2.
