### ISSUE TITLE
Chart having mouse pointer shifted from actual point

### ISSUE THREAD

**Issue by HarisHashim** [Graylog2/graylog2-server#4286]
1. When checking value at specific position of a line chart. My mouse position is shifted as in attached picture.
![image](https://user-images.githubusercontent.com/1856131/31989622-6db2c43c-b9a5-11e7-9685-59d6bf6d30da.png)

2. Additional question, why non existant value (i.e. at timestamp that is not logged is 0)

My data is very simple and the chart value is "Duration"
"timestamp","source","duration","message","method"
"2017-10-25T08:29:48.175Z","192.168.0.102","140.25","DONE","get_user"
"2017-10-25T08:37:16.214Z","192.168.0.102","190.25","DONE","get_user"
"2017-10-25T08:43:45.625Z","192.168.0.102","180.25","DONE","get_user"

## Expected Behavior

For 1. The value shown must be value at peak as pointed by mouse cursor

For 2. Non existant value shoud not be 0, and the line should extrapolate to connect to each other rather than show wave shape. I.e. because it will go from value to 0 and then to another value

## Steps to Reproduce (for bugs)
1. Add input
2. Have data as above CSV
3. Create line chart using Duration data

## Your Environment
A. Graylog installed in Virtual Box using latest OVA
B. Chrome browser from Windows 10 64 bit

**Comment by tommymonk** [comment]
I also experience this issue but only when using Graylog on my laptop which has very high resolution and DPI scaling.

**Comment by bernd** [comment]
We are now using a new graphing library in the new search page. Please open a new issue if still see this issue with the new version. Thank you!
