### ISSUE TITLE
Add timestamp field to search query through quick values does not work

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#4288]
## Expected Behavior
Using the "add to query" button in quick values to add a timestamp field should add the right date time to the search bar.

## Current Behavior
Using the "add to query" button in quick values to add a timestamp field adds "Invalid date" to the search bar.

## Steps to Reproduce (for bugs)
1. Run quick values analyzer on `timestamp` field
2. Add one of the values to the query by using the "add to query" button
3. Observe that no date or timestamp was added, but "Invalid date"

## Your Environment
* Graylog Version: Graylog 3.0.0-SNAPSHOT (aada4c64b6e8fae20bf972aa40fec330d5686137). I could not reproduce it in two 2.4.0 setups
* Elasticsearch Version: 5.6.2

**Comment by kroepke** [comment]
The issue here is that the `QuickvaluesVisualization` is not properly displaying formatted timestamps like the message table does, but simply displays the unix timestamp.

Adding that back to the query fails, because the search store has special handling for the timestamp field.

**Comment by bernd** [comment]
Moving to 3.0.0 milestone.
