### ISSUE TITLE
Graylog 0.20.0-rc3 startpage behaviour

### ISSUE THREAD

**Issue by suff** [Graylog2/graylog2-server#430]
Hi, 
after upgrading to 0.20.0-rc3 start page is not working everytime when on main graylog url (/). It is showed right after login but when you're entering a graylog2 url with saved cookie in you're redirected to search which is currently available at /

Clicking on Graylog2 logo in the upper left is also not helping. The only way to return to start page is to login again or dig through streams to find the interesting one.

**Comment by bernd** [comment]
There have been lots of changes since 0.20-rc3. I am closing this issue, please re-open if you still have this problem with Graylog 1.1. Thank you!
