### ISSUE TITLE
System -> Indices -> Default index set stuck in “loading” status

### ISSUE THREAD

**Issue by li555li** [Graylog2/graylog2-server#4300]
After upgrading to 2.3.2, when navigating to System -> Indices -> Default index set, the page stuck in “loading” status, never brought back the list of indices. We have over 1000 indices in production. I have reproduced the issue in my lab, with 1MB sized indices. it appears the issue starts to occur when the number of indices gets to over 270. After deleting a few indices using elasticsearch command to drop the total number of indices to below 270, the issue disappeared
## Expected Behavior

When navigating to System -> Indices -> Default index set, it should bring back the list of indices

## Current Behavior

it stuck in "loading" status

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 2.3.2
* Elasticsearch Version: 5.6.3
* MongoDB Version: 3.2.17
* Operating System: Centos 7
* Browser version: tried in latest firefox, chrome, IE, all with the same symptom

**Comment by li555li** [comment]
turned out this isn't a bug. the issue is resolved by setting below config in elasticsearch
http.max_initial_line_length: 32k

**Comment by joschi** [comment]
@li555li I'm reopening this issue as this should also work with the default settings of Elasticsearch.

Refs #4054, #4136

**Comment by kroepke** [comment]
I'm not seeing this anymore with the current 2.4 HEAD, therefore I'll close it as fixed.
