### ISSUE TITLE
Graylog initiating connections with reverse proxy

### ISSUE THREAD

**Issue by ChazSII** [Graylog2/graylog2-server#4303]
While using Graylog setup behind Nginx reverse proxy, the Graylog server is attempting to initiate connections with the reverse proxy, possibly as attempts at replies. This only happens when the Graylog server web page is open.
## Expected Behavior

All traffic should (I think) be routed through the reverse proxy on established connections, and therefore, be ignored by my UFW firewall.
## Current Behavior

When a browser session is open, Graylog sends packets to the reverse proxy that are blocked by the UFW firewall. These packets appear to be replies to established connections, but are originating as initiation attempts and are being blocked by UFW. Chrome is not logging any errors to the console and the webpage appears to operate normally, so I don't see any issues arising from blocked packets.
## Context

Relevant Nginx config:
server {
         # SSL configuration
        listen 443 ssl;
        listen [::]:443 ssl;
...
        location /logs/ {
              proxy_set_header Host $host;
              proxy_set_header X-Forwarded-Host $host;
              proxy_set_header X-Forwarded-Server $host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Graylog-Server-URL https://\<server\>/logs/api;
              proxy_pass       https://192.168.0.222:9000/logs/;
        }
}

Relevant UFW rules:
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

|To                         |Action      |From|
| ------------------ |:-----------:| ----:|
|80,443/tcp (Nginx Full)    |ALLOW IN    |Anywhere|
|80,443/tcp (Nginx Full (v6)) |ALLOW IN    |Anywhere (v6)|

Reverse Proxy: 192.168.0.212
Graylog Server: 192.168.0.222:9000
Sample of UFW log:
Oct 30 12:52:40 webhost kernel: [1561172.860348] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=38070 DF PROTO=TCP SPT=9000 DPT=53742 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:52:59 webhost kernel: [1561191.243316] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=40472 DF PROTO=TCP SPT=9000 DPT=53892 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:53:19 webhost kernel: [1561211.364837] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=42827 DF PROTO=TCP SPT=9000 DPT=54060 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:53:39 webhost kernel: [1561231.323243] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=45160 DF PROTO=TCP SPT=9000 DPT=54224 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:53:59 webhost kernel: [1561251.338606] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=47724 DF PROTO=TCP SPT=9000 DPT=54396 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:54:19 webhost kernel: [1561271.363267] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=50052 DF PROTO=TCP SPT=9000 DPT=54564 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:54:39 webhost kernel: [1561291.325570] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=52638 DF PROTO=TCP SPT=9000 DPT=54726 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:54:59 webhost kernel: [1561311.348484] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=55366 DF PROTO=TCP SPT=9000 DPT=54900 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:55:19 webhost kernel: [1561331.360482] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=58519 DF PROTO=TCP SPT=9000 DPT=55066 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:55:39 webhost kernel: [1561351.340803] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=61640 DF PROTO=TCP SPT=9000 DPT=55230 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:55:59 webhost kernel: [1561371.348313] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=63785 DF PROTO=TCP SPT=9000 DPT=55402 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:56:19 webhost kernel: [1561391.347951] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=893 DF PROTO=TCP SPT=9000 DPT=55560 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:56:39 webhost kernel: [1561411.346933] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=3882 DF PROTO=TCP SPT=9000 DPT=55734 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:56:59 webhost kernel: [1561431.245701] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=6360 DF PROTO=TCP SPT=9000 DPT=55914 WINDOW=0 RES=0x00 RST URGP=0
Oct 30 12:57:19 webhost kernel: [1561451.326091] [UFW BLOCK] IN=ens2 OUT= MAC= SRC=192.168.0.222 DST=192.168.0.212 LEN=40 TOS=0x00 PREC=0x00 TTL=64 ID=9329 DF PROTO=TCP SPT=9000 DPT=56086 WINDOW=0 RES=0x00 RST URGP=0

## Your Environment

* Graylog Version: 2.3.2-1
* Elasticsearch Version:  5.6.3
* MongoDB Version: 1:2.6.10-0ubuntu1
* Operating System: Ubuntu 16.04 on both
* Browser version: Chrome 61.0.3163.100 
* Nginx version: 1.10.3-0ubuntu0.16.04.2

**Comment by ChazSII** [comment]
Looking into it further, it looks like Graylog webserver is issuing TCP RST requests after the connection is closed, so Nginx isn't listening on the established connection and UFW blocks it. 

Is this expected?

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
