### ISSUE TITLE
Beats TLS Exception : java.io.IOException: extra data given to DerValue constructor

### ISSUE THREAD

**Issue by loosi** [Graylog2/graylog2-server#4304]
Already mentioned in issue #3744 but that doesn't see to be the problem.
I recreated key and cert again and again, with or without any options like SAN etc

when using an unencrypted pkcs8 key following error:

```
java.lang.IllegalArgumentException: Unsupported key type: /run/secrets/graylog_pem
```

ok..this is weird, so try the key as pkcs8 encrypted:
````
WARN : org.jboss.netty.channel.socket.nio.AbstractNioSelector - Failed to initialize an accepted socket.
java.io.IOException: extra data given to DerValue constructor
````
and yes, its an encrypted pkcs8 key
````
-----BEGIN ENCRYPTED PRIVATE KEY-----
thats just a freshly generated key...
-----END ENCRYPTED PRIVATE KEY-----
````
freshly generated certs in plain pem
````
-----BEGIN CERTIFICATE-----
MIIHJjCCBQ6gAwIBAgIBAzANBgkqhkiG9w0BAQ0FADCBkTELMAkGA1UEBhMCREUx
J07Doyl9mHTc+A==
-----END CERTIFICATE-----
````
Some weird stuff that java keystore does not like with XCA certs?
I googled the message of "DerValue Constructor" and some people seem to have issues with that on java. Unfortunately i didn't find any useful advices for that. 

Any idea how to debug any further? I reduced the cert to nothing but ip, no san, no extensions, no orgname etc. 

Thanks

## Expected Behavior
Working TLS on Beats Input

## Current Behavior
Crashing with Stacktrace no matter what cert/key combination

## Steps to Reproduce (for bugs)
Create any key/cert in XCA and import it

## Your Environment
* Graylog Version: 2.3.2-1 in docker swarm
* Elasticsearch Version: 5.5.1
* MongoDB Version: does it really matter?
* Operating System: provided by docker image
* Browser version:

**Comment by joschi** [comment]
@loosi 
> Some weird stuff that java keystore does not like with XCA certs?

Possible. Try creating the private key and certificates without XCA.

Refs #2752.

**Comment by loosi** [comment]
It seems a weird problem with either extensions and maybe Copy/Paste. I verified both cert and key locally (i copied it as a secret for docker swarm) and it worked with java keystore and openssl command line. 
Besides that I removed all extensions, CA refs and other more useful features for certs and at some point it worked. 
I cant exactly tell what triggered it, but its some weird behaviour with certs.
I used our own CA as Authority for TLS Clients, that worked like a charm no matter what extensions.

For now I got it fixed and I will probably never ever touch that cert again for a couple of years.
Issue can be closed. Its good to know it basically works but behaves weird sometimes.

**Comment by jmerinen** [comment]
Graylog2 has strict checking for the unencrypted PKCS8 private key format. The file must have one final newline after "-----END PRIVATE KEY-----". Any extra newlines will throw exception "java.lang.IllegalArgumentException: Unsupported key type".

I think the file format pattern in graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/util/KeyUtil.java line 67 should be relaxed to allow extra newlines in the end.
