### ISSUE TITLE
graylog not working with authbind?

### ISSUE THREAD

**Issue by eelsivart** [Graylog2/graylog2-server#4305]
I am testing out a new Graylog v2.3.2+3df951e installation on Ubuntu 16.04 following the instructions in the documentation. I have it working just fine over non-privileged ports, but I can't seem to get it to work with authbind.

I have:
-installed authbind
-added the appropriate ports to /etc/authbind/byport and assigned the appropriate user and permissions
-modified the /etc/default/graylog-server file with authbind in the graylog_command_wrapper section

I tested authbind with a different user and netcat and it worked just fine so authbind appears to be working properly. However, when i try to set the Graylog web server/api port to 80/tcp or when I try to create an input on 514/tcp or udp, or any other non-privileged port, it fails. Am I missing something?

Thanks!

**Comment by joschi** [comment]
@eelsivart Please provide the *exact* changes to `/etc/default/graylog-server` and the complete configuration of authbind.

**Comment by eelsivart** [comment]
Here it the output from /etc/default/graylog-server and the dir listing for /etc/authbind/byport. The only thing I changed in /etc/default/graylog-server was adding "authbind" to GRAYLOG_COMMAND_WRAPPER. I even tried the full path to authbind (/usr/bin/authbind) and that didn't work either.

Thanks!

===================

`$ cat /etc/default/graylog-server
# Path to the java executable.
JAVA=/usr/bin/java

# Default Java options for heap and garbage collection.
GRAYLOG_SERVER_JAVA_OPTS="-Xms1g -Xmx1g -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow"

# Pass some extra args to graylog-server. (i.e. "-d" to enable debug mode)
GRAYLOG_SERVER_ARGS=""

# Program that will be used to wrap the graylog-server command. Useful to
# support programs like authbind.
GRAYLOG_COMMAND_WRAPPER="authbind"`

=======================

`$ ls -la /etc/authbind/byport
total 8
drwxr-xr-x 2 root    root    4096 Nov  2 07:59 .
drwxr-xr-x 5 root    root    4096 Oct 30 13:27 ..
-r-x------ 1 graylog graylog    0 Oct 30 13:28 514
-r-x------ 1 graylog graylog    0 Oct 30 13:26 !514
-r-x------ 1 graylog graylog    0 Oct 30 13:30 80
`

**Comment by Rand72889** [comment]
Please try chmod 755 and a service restart. Worked for me today.

**Comment by eelsivart** [comment]
I tried that and it still doesn't work. This is the error i get in /var/log/graylog-server/server.log:

`Caused by: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:514`

**Comment by Rand72889** [comment]
Strange. Are you sure you modified the .yml correctly ? Maybe you can post excerpts without sensitive information.  Don't know but shouldn't it be 0.0.0.0:514/
Can only say that I am not an expert but I did it today and it worked.

**Comment by eelsivart** [comment]
I didn't modify any .yml files. I just used the web interface to create a new Syslog input on 514/UDP. I tried TCP also with no success. It works just fine when I use a non-privileged port, such as 1514/UDP.

**Comment by Rand72889** [comment]
Okay, I thought you also remapped to Port 80. Therefore you have to modify them. Over read a bit that is only about he input. I've tried it now. Created a TCP Syslog input on port 514. The error message was exactly the same (.../0.0.0.0:514...) so the leading dash is fine. Then I created the !514 in /etc/authbind/byport with chmod 755 / chown and just clicked 'start input' and it worked. So cant help you with that. Sorry I am out :/

**Comment by eelsivart** [comment]
Oh yes, I initially was trying to change the server.conf to change the web server to port 80 from 9000, but since it wasn't working, I just stuck to trying an input afterwards. I tried both TCP and UDP 514 and it never worked. 

Dang it, I wonder what is up with my setup. Weird.

Thanks for checking on your end though!

**Comment by jalogisch** [comment]
@eelsivart 

I double checked on my Debian Box:

Install Authbind, Configure Graylog to Use It

- `sudo apt-get install authbind -y`
- vi /etc/default/graylog-server
 GRAYLOG_COMMAND_WRAPPER="authbind" to the appropriate line of the file

# Add the Ports to Authbind

## Add TCP 514 to Authbind
```
sudo touch /etc/authbind/byport/514
sudo chown graylog:graylog /etc/authbind/byport/514
sudo chmod 755 /etc/authbind/byport/514
```
## Add UDP 514 to Authbind
```
sudo touch '/etc/authbind/byport/!514'
sudo chown graylog:graylog '/etc/authbind/byport/!514'
sudo chmod 755 '/etc/authbind/byport/!514'
```

Restart Graylog and I was able to use Port 514 TCP or UDP. Please verify if you have done all the above.

**Comment by eelsivart** [comment]
Hmm... That is exactly what I had done. What version of Debian is your box? I was testing this on Ubuntu 16.04.3 LTS (updated to latest). Thanks!

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please move this discussion to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
