### ISSUE TITLE
LDAP and group mapping

### ISSUE THREAD

**Issue by resyst-it** [Graylog2/graylog2-server#4308]
Hello,
In my LDAP configuration i specified posixGroup. However when i test an authentification with my user, he has no group. In the logs I see a search on the member attribute and not on the memberUID attribute.

Graylog version : 2.3.2

Thank you.

**Comment by edmundoa** [comment]
Hi @resyst-it,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
