### ISSUE TITLE
Add more Details to Stream Alert E-Mails and/or make them customizable

### ISSUE THREAD

**Issue by moger-xx** [Graylog2/graylog2-server#431]
It would be extremely helpful to have some more Details about the nature of the alert in the body of a stream alert mail. Think of a user who gets an alert to his mobile phone in the middle of the night and this user wants to know with one look if there's need to worry or not.

At least, we should add some basic infos like Stream Name and preferrably a List of the Message Subjects which triggered the Alert or a Link to the stream in graylog to look them up.

In General, these E-Mails should be made configurable or (maybe easier) customizable with a custom template to fit special needs.

**Comment by bernd** [comment]
Email templates got implemented.

**Comment by moger-xx** [comment]
Great work guys!

**Comment by prtomasi** [comment]
here I used this scenario: 

In "Configured alert conditions" I changed "When sending an alert, include the last **1** messages of the stream evaluated for this alert condition." from zero to one.

This way, in the footer of message I have details about the log.

**Comment by gvinodapplift** [comment]
Here I used this scenario, but email notification not getting beats host name
Beats output given directly to GELF TCP input.
Alert notification body is:
###############
${if backlog}Last messages accounting for this alert:
${foreach backlog message}${name}  ${message.message}

${end}${else}<No backlog>
${end}
 #######
Need to get hostname + message, for this what need to be change in body?

**Comment by joschi** [comment]
@gvinodapplift 
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
