### ISSUE TITLE
Question: Gelf format chunking over Udp - Graylog not receiving messages with IpV4 fragmentation

### ISSUE THREAD

**Issue by daningalla** [Graylog2/graylog2-server#4317]
More of a question than a bug report, but will escalate if the issue is in Graylog and not networking protocol. I apologize in advance, I'm a novice with regard to networking.

## Expected Behavior
Graylog supports chunking on large messages sent to Udp. I would expect if a message is under 8192 bytes, we wouldn't have to chunk. Graylog is not receiving messages if the Udp transmission incurs IpV4 fragmentation, even on messages under the Udp datagram size limit. 

## Current Behavior
We had an application reporting stack traces, but Graylog wasn't displaying them. We did the usual obvious process of elimination in the Graylog interface, but we couldn't find the message. We then debugged our application (dotnetcore) and verified the Udp transport mechanism was sending the messages. We finally resorted to wireshark to see if the data was flowing to the Gelf endpoint. We noticed on the messages that were being received by Graylog, the wireshark entry was a clean Udp packet. On the messages Graylog did not receive, we noticed each entry was marked as an IpV4 fragmentation. Note the size of the message we were trying to send was 1405 bytes, well under the Udp threshold size. We adjusted the Gelf logging sink to chunk any messages greater than 1024 bytes and the problem went away, but I'm curious as to why we had to do this.

## Possible Solution
I suspect this is not a Graylog problem, but perhaps a network interface problem in RHEL. Is this related to an MTU setting on the server?  

I just wanted to report this in case others were having this issue with large messages on GELF.

## Your Environment
Clients: Windows 7, Windows Server 2012
Server: RHEL

* Graylog Version: 2.2

**Comment by joschi** [comment]
@daningalla Chunks of GELF messages sent via UDP all have to be received by the same Graylog node.
Missing chunks will cause the message to be dropped eventually.
Most GELF libraries support configuring the chunk size, so you might want to reduce the size in your network if you currently have problems.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by daningalla** [comment]
Yes we only have a single node, which is why I find it strange that the messages are being dropped. Most likely a RHEL issue.
