### ISSUE TITLE
Clean up loading state handling in FieldQuickValues

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#4323]
From https://github.com/Graylog2/graylog2-server/pull/4322#discussion_r149380301

- It is still possible to end up in a "broken" state, where the server returned an error calculating the quick values or quick values histogram of a field, but the web interface will be stuck in a loading state
- We currently duplicate the loading state information in `FieldQuickValues` and `FieldQuickValuesStore`, where only one should be used for that. That may cause some unnecessary re-renderings of the component

## Your Environment
* Graylog Version: Graylog 2.4.0-beta.1

**Comment by bernd** [comment]
That code doesn't exist anymore. Closing the issue.
