### ISSUE TITLE
Java 8 end-of-life is approaching

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/graylog2-server#4327]
Java 8 end of public updates will be at september 2018 (http://www.oracle.com/technetwork/java/eol-135779.html).

Investigate and implement Java 9 or 18.3 update before the deadline.

**Comment by joschi** [comment]
@mikkolehtisalo See the "java9" label: https://github.com/Graylog2/graylog2-server/labels/java9

**Comment by mikkolehtisalo** [comment]
@joschi Thanks. Have you tracked also ElasticSearch's status?

**Comment by braiam** [comment]
Seems that the date changed to January 2019, which is shy 6 months away. It wasn't on the recent dependency update list https://github.com/Graylog2/graylog2-server/pull/4923. Is there a branch that can be tested with Java 9 or 10?

**Comment by mikkolehtisalo** [comment]
Java 11 is supported now and seems to work well enough. This ticket is not valid anymore.
