### ISSUE TITLE
Docker hub questions

### ISSUE THREAD

**Issue by jean-francois-labbe** [Graylog2/graylog2-server#4329]
What's the difference between https://hub.docker.com/r/graylog/ and https://hub.docker.com/r/graylog2 ?

and between graylog2/server and graylog2/graylog?

**Comment by joschi** [comment]
@jean-francois-labbe 

* https://hub.docker.com/r/graylog/ will ultimately replace https://hub.docker.com/r/graylog2 (at some unspecified time in the future).
* [graylog/graylog](https://hub.docker.com/r/graylog/graylog/) and [graylog2/graylog](https://hub.docker.com/r/graylog2/graylog/) are basically the same image (automatically built by Docker Hub, based on https://github.com/Graylog2/graylog-docker).
* [graylog2/server](https://hub.docker.com/r/graylog2/server/) is the "legacy" Docker image for Graylog 2.x (built by our CI infrastructure and pushed to Docker Hub, based on https://github.com/Graylog2/graylog2-images/tree/2.3/docker).
