### ISSUE TITLE
GELF timestamp doesn't process exponential notation

### ISSUE THREAD

**Issue by nathanleyton** [Graylog2/graylog2-server#4338]
Your GELF processor loses precision when using exponential notation in the JSON. There system I am generating the timestamp from is unable to produce such long doubles without using exponential notation. When I use a string instead I get my logs filling up with:-

WARN  [GelfCodec] GELF message  <nnn> (received from <ip:port>) has invalid "timestamp": 1510331274.123  (type: STRING)

## Expected Behavior
I would expect it to either allow the string without a warning and try and parse properly or properly understand double in both notations as both as valid json. Or even better change support timestamp to microseconds long

## Current Behavior
WARNINGS in logs for strings and no precision of time when using exponential notation doubles in json. 

## Your Environment
* Graylog Version: 2.3.2
* Elasticsearch Version: 5.6.4
* MongoDB Version: 3.4.10
* Operating System: RHEL
* Browser version: Chrome

**Comment by joschi** [comment]
> Your GELF processor loses precision when using exponential notation in the JSON.

Do you have an example for this?

> I would expect it to either allow the string without a warning

No, because it's simply not valid GELF: http://docs.graylog.org/en/2.3/pages/gelf.html#gelf-payload-specification

**Comment by nathanleyton** [comment]
I tried to replicate manually and noticed that the actual precision bug is in the client lib not in GrayLog.  I will get this fixed in the client json library. Apologies for the time waste.

**Comment by joschi** [comment]
@nathanleyton No worries. Thanks for reporting this!
