### ISSUE TITLE
Charts are not updating

### ISSUE THREAD

**Issue by dmitry-chisw** [Graylog2/graylog2-server#4339]
When we do searches in Graylog and have some additional charts generated (e.g. response_time -> Generate chart), these charts haven’t get updated after I update the search query. Is that bug or feature?

## Expected Behavior
Charts are updated after update the search query. Graylog 1.x had it working

## Current Behavior
Charts haven’t get updated after updating the search query

## Steps to Reproduce
1. Search for the query1 and generate response time chart
2. Modify query1 to query2, press the search button.
3. Histogram is updated respectively, but chart shows results for the old query1 still. 

## Your Environment

* Graylog Version:  2.2.2+691b4b7
* Elasticsearch Version: 2.x
* MongoDB Version: 3.x
* Operating System: Ubuntu 16.04 LTS, Windows 7
* Browser version: Mozilla for Ubuntu 56.0, Chrome of any version (Windows 7)

**Comment by edmundoa** [comment]
Hi @dmitry-chisw,

That is indeed a feature. The idea is that you can add several of those graphs and compare them or combine them together.
