### ISSUE TITLE
Docker and stack traces.

### ISSUE THREAD

**Issue by omgwtfpwnzor** [Graylog2/graylog2-server#4341]
Hi, guys, thx for your great product. We are using graylog2/server-2.3.2-2 docker image, and now we need to enable stack trace logging of java apps. How to enable it in docker image?

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
