### ISSUE TITLE
Can't Deselect All Grok Patterns When Creating a Content Pack 

### ISSUE THREAD

**Issue by GTownson** [Graylog2/graylog2-server#4344]
When creating a contents pack, you have to select the items to include. In my case I just wanted to export all of my custom grok patterns to import onto a different Graylog instance. At the top of all of my grok patterns, I clicked the 'Select All' button. I then realized that I didn't want to include all of the default grok patterns so I tried to click 'Select All' again to remove all of the selected grok patterns, but it did not deselect them all.

I suggest that you change the 'Select All' button to let it deselect all upon an second click or create a 'Deselect All' button.

1. System/Content packs
2. Create content pack
3. Grok patterns
4. Select All
5. Select All again (Doesn't deselect)

Graylog Version: 2.2.3

**Comment by bernd** [comment]
This will be fixed in 3.0.
