### ISSUE TITLE
Feature request: filebeats exclude_files field

### ISSUE THREAD

**Issue by unamuno** [Graylog2/graylog2-server#4346]
You can't exclude log files in the sidecar-collector configuration by the filebeats exclude_files field.

## Expected Behavior
In the Configure Beats Inputs Section, when you edit or add a Beats Input, you have a field called Exclude Files where you can set the exclude_files from Filebeats.

## Current Behavior
There is no field at all and no possibility to exclude files from the logging procedure that match the regex of included log files.

## Possible Solution
Add that field and add the content to the generated filebeat.yml:
For example `exclude_files: ['\.gz$']`

**Comment by bernd** [comment]
This feature will be in the upcoming 2.4 release. See: https://github.com/Graylog2/graylog-plugin-collector/pull/63
