### ISSUE TITLE
Retire Anonymous Usage Statistics plugin

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#4348]
The Anonymous Usage Statistics plugin served us well but now has to be retired.

- [x] Remove integration with Anonymous Usage Statistics plugin in Graylog (#4349)
- [x] Replace Anonymous Usage Statistics service with "dummy" which doesn't record any data and always returns a successful response
- [x] Retire old Anonymous Usage Statistics service
- [x] Mark https://github.com/Graylog2/graylog-plugin-anonymous-usage-statistics as deprecated (Graylog2/graylog-plugin-anonymous-usage-statistics@fcca43fe16b61b234a061bfc4eabe3b7bc2d7c6b)
- [x] Delete collected data
- [x] Archive https://github.com/Graylog2/graylog-plugin-anonymous-usage-statistics after the last release of Graylog 2.4.x (read-only)

**Comment by bernd** [comment]
Done.
