### ISSUE TITLE
Cursor offset from mouse position in Google Chrome

### ISSUE THREAD

**Issue by sdmonster** [Graylog2/graylog2-server#4354]
## Expected Behavior
I expect the mouse cursor postition and the histogram chart cursor to match.

## Current Behavior
 The 'histogram highlighting bar' or cursor is a few centimeters to the left of my mouse position. 

## Steps to Reproduce (for bugs)
1. Mouse over the histogram chart on the Search page. 

## Context
This means that I can't select a range or get alt text for data at the far right of the chart. 

## Your Environment
* Graylog Version: 2.3.2+3df951e, codename Tegernseer
* Elasticsearch Version: na
* MongoDB Version: na
* Operating System: Windows 10
* Browser version: Google Chrome Version 61.0.3163.100 (Works fine on same computer in Firefox and Opera.)

I have a screenshot I can send if needed.

**Comment by edmundoa** [comment]
Hi,

I'm closing this issue, as it is duplicating #3590. Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
