### ISSUE TITLE
Use Custom index

### ISSUE THREAD

**Issue by wlyu** [Graylog2/graylog2-server#4356]
I do not want to use the index of graylog_0, graylog_1, for example
Is it possible
User's index is user_0
The Order index is order_0

Or is it okay?
User's index will always be graylog_1
Order index will always be graylog_2

**Comment by joschi** [comment]
@wlyu Please refer to http://docs.graylog.org/en/2.3/pages/configuration/index_model.html for information about Graylog's index model and how to create index sets with custom index prefixes.
