### ISSUE TITLE
The _missing_ query does not work

### ISSUE THREAD

**Issue by onyxmaster** [Graylog2/graylog2-server#4362]
## Expected Behavior
When the `_missing_` query is used, it should return the messages that do not have the specified field.

## Current Behavior
Any `_missing_` query does not return any messages.

## Steps to Reproduce (for bugs)
Try searching for messages with `_missing_:non_existent_field` query -- you will get none.

## Context
Surprisingly, `NOT _exists_:...` works.

* Graylog Version: 2.3.2+3df951e
* Elasticsearch Version: 5.6.3
* MongoDB Version: 3.4.7
* Operating System: Irrelevant
* Browser version: Irrelevant

**Comment by indigoid** [comment]
We're experiencing the same behaviour — `_missing_:foo` not working, `NOT _exists_:foo` working — with both 2.3 stable and 2.4 beta

**Comment by joschi** [comment]
@onyxmaster @indigoid The `_missing_` query has been removed in Elasticsearch 5.0:
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/breaking_50_search_changes.html#_deprecated_queries_removed

Either downgrade to Elasticsearch 2.x (don't do that…) or use the negated `_exists_` query.

**Comment by onyxmaster** [comment]
Thanks for the info. I believe the http://docs.graylog.org/en/2.3/pages/queries.html#syntax should be updated also.
