### ISSUE TITLE
cluster.name must be graylog?

### ISSUE THREAD

**Issue by wlyu** [Graylog2/graylog2-server#4364]
elasticsearch       cluster.name：graylog

how can use other  name  such as  " cluster.name：apple "?

**Comment by joschi** [comment]
@wlyu Graylog 2.3.0 and later, which is using the Elasticsearch HTTP API, doesn't require any specific cluster name. You can choose any Elasticsearch cluster name you want.

Graylog versions before Graylog 2.3.0 join the Elasticsearch cluster as a client node and require the same cluster name to be set.
In these versions you can configure the Elasticsearch cluster name Graylog is using with the `elasticsearch_cluster_name` setting.
https://github.com/Graylog2/graylog2-server/blob/7adc951e40b9dcacc3bc60d2b51e8a5e976ca53b/misc/graylog.conf#L268-L271

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by wlyu** [comment]
Graylog 2.3.0
but it happened,like this
===========================
http://192.168.56.102:9000/api/system/fields
===========================

{
    "message": "Couldn't read cluster state for indices graylog_*\n\n{\"error\":\"IndexMissingException[[_cluster] missing]\",\"status\":404}",
    "details": [
        "{\"error\":\"IndexMissingException[[_cluster] missing]\",\"status\":404}"
    ]
}
======================================
