### ISSUE TITLE
Should the reader role be extended by `dashboards:create` permission?

### ISSUE THREAD

**Issue by mariussturm** [Graylog2/graylog2-server#4365]
Since https://github.com/Graylog2/graylog2-server/pull/4155 a non-root user gets automatically read permissions for self created dashboards. So we could extend the default reader role with the `dashboards:create` permission to allow normal users to make use of this feature.

This issue is meant as point for discussion if we want to do a global update of the role or if we want
to keep it as restricted as it is today. An administrator would need to create new roles and apply them to all read users to enable the feature.

**Comment by dennisoelkers** [comment]
The whole point of the "Reader" role is that it allows access to the system, but read-only. Also, accessing dashboards a user created would require the `dashboards:create` permission which the "Reader" role does not have.

I understand your point though and think that we should add more default roles which can be assigned to users, for example a non-admin user being able to create streams/dashboards, but is generally not able to see all streams/dashboards (unlike the admin role).

**Comment by jalogisch** [comment]
We should introduce something like "Editor" Rule that is not just read-only but have limited abilities. what @dennisoelkers said.

**Comment by B3DTech** [comment]
+1 for the Editor Rule.    I can create a role for Dashboard:Create.  Problem is the system doesn't automatically assign edit rights to the dashboard just created.  So now every time we have an engineer that wants to create a dashboard, they need to ask us to give them edit permissions first.  Major inconvenience. 

The simple solution is expose Dashboard:Create to the role creation UI.  Let us check which Streams the users should be allowed to read as always.  But the key is when they have Dashboard:Create, allow users of that role to edit the dashboard they create.

**Comment by bernd** [comment]
With the new sharing system in the upcoming 4.0 release there is a "Dashboard Creator" role that can be assigned to users. Closing this issue.
