### ISSUE TITLE
drools, blacklisting, syslog, DHCP

### ISSUE THREAD

**Issue by vti-uplata** [Graylog2/graylog2-server#4372]
Hello.

I've tried to blacklist messages that come from syslog to input SYSLOG-TCP  and contain "DHCP".

Here's input
![02_graylog_syslog_tcp_input](https://user-images.githubusercontent.com/28108696/33219641-199f0d92-d14c-11e7-94c4-97c6e0ee59dd.png)

Here's one of such messages
![01-dhcp_graylog](https://user-images.githubusercontent.com/28108696/33219606-e958777c-d14b-11e7-9a6f-7b3dfd5b9168.png)

Here's the rule

import org.graylog2.plugin.Message
import java.util.regex.Matcher
import java.util.regex.Pattern

rule "Drop DHCP"
    when
        m : Message( message matches "^DHCP.*(.|\n|\r)*" )
    then
        System.out.println("DEBUG: Blacklisting DHCP message.");
        m.setFilterOut(true);
end

service graylog restart

2017-11-24T18:18:05.339+02:00 INFO  [RulesEngineProvider] Using rules: /etc/graylog/server/rules.drl

I've tried both variants - "^DHCP.*" and  "^DHCP.*(.|\n|\r)*" and new messages arrived to graylog and were not filtered out.

Graylog v2.3.2+3df951e
Ubuntu 14.04.5 LTS
Linux grayloguser 4.4.0-96-generic x86_64
ava(TM) SE Runtime Environment (build 1.8.0_151-b12)

**Comment by joschi** [comment]
@vti-uplata The Drools engine is more or less deprecated in Graylog.

Try using the processing pipeline to drop the DHCP messages, for example with the following rule:
```text
rule "drop-dhcp"
when
  regex("^DHCPREQUEST", $message.message).matches == true
then
  drop_message();
end
```

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by vti-uplata** [comment]
Ok, thank you.
