### ISSUE TITLE
react reflux version question

### ISSUE THREAD

**Issue by mj3018** [Graylog2/graylog2-server#4378]
hello,can you tell me what is the version of react reflux on master branch.when i started the graylog2-web-interface,it tells me Reflux.setPromiseFactory is not defined.

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@mj3018 You can check this in the `package.json` file on the `master` branch.

https://github.com/Graylog2/graylog2-server/blob/ed62a6c4252cadd7bfeac7420c20d7d75387074e/graylog2-web-interface/packages/graylog-web-plugin/package.json#L54
