### ISSUE TITLE
Hard coded keys

### ISSUE THREAD

**Issue by fkangaye** [Graylog2/graylog2-server#4379]
## Current Behavior

![image](https://user-images.githubusercontent.com/12779290/33362202-e1e32b24-d4a0-11e7-952d-8926d7c3259a.png)

## Possible Solution

![image](https://user-images.githubusercontent.com/12779290/33362125-83f43698-d4a0-11e7-82c8-040c35fc6aa7.png)

**Comment by joschi** [comment]
@fkangaye Having hard-coded dictionary keys in the source to look up the actual password is perfectly fine.
