### ISSUE TITLE
Email Alert Condition

### ISSUE THREAD

**Issue by marick7** [Graylog2/graylog2-server#4382]
## Expected Behavior
- Email Alerts should work every time a stream sees the message (Oracle error ORA-) defined in alert condition.

## Current Behavior
1. writing in the alert log of the database: 
```
exec dbms_system.ksdwrt(2, 'ORA-12345');
```
2. Stream displays message and alert is triggered, email sent
3. writing in the alert log of the database: 
```
exec dbms_system.ksdwrt(2, 'ORA-123456');
```
4. Stream displays message but alert is not triggered.

## Context
Stream:
```text
DEV1 Oracle alert logs
0 messages/second. Must match all of the 2 configured stream rules.Hide stream rules
Field file must contain DEV1
Field message must contain ORA-
```

Conditions:
```text
Configuration: Alert is triggered when messages matching <message: "ORA-"> are received. Grace period: 0 minutes. Including last 10 messages in alert notification. Configured to not repeat notifications.
```

Email:
```text
body: ##########
Date: ${check_result.triggeredAt}
Stream title: ${stream.title}
Alert Condition Title: ${alertCondition.title}
##########
${if backlog}
${foreach backlog message}
Actual error message: ${message.message}
Database alertlog: ${message.fields.file}
${end}
${else}<No backlog>
${end}
email_receivers: test@test.test
sender: <empty>
subject: Graylog alert for stream: ${stream.title}
user_receivers: <empty>
```
## Your Environment

* Graylog 2.3.1+9f2c6ef
* Elasticsearch Version: 5.6
* MongoDB Version: db version v3.4.9
* Operating System: Oracle Linux 7.3
* Browser version: Chrome Version 62.0.3202.94 (Official Build) (64-bit)

**Comment by marick7** [comment]
![image](https://user-images.githubusercontent.com/25902853/33417061-6ed0cdc2-d5a8-11e7-8bd4-d8e405466f86.png)
Thanks for quick replay! 

Scan frequency in input is 3m. I got 3 messages in stream and 2 mails. It misses 1 message. 
Some time it misses first message but I can't reproduce the situation. How can I debug?

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
