### ISSUE TITLE
Feature: alternate storage backend to MongoDB

### ISSUE THREAD

**Issue by schlitzered** [Graylog2/graylog2-server#4385]
Our company has banned the AGPL license, therefore we are no longer allowed to use MongoDB. Could you maybe consider to use an alternative storage backend for configuration data? Maybe it would be possible to simply use ElasticSearch for this?

**Comment by bernd** [comment]
@schlitzered This will most probably not happen in the near future, unfortunately.

Switching database backends is a pretty big task with lots of potential for breakage and it also hasn't a high priority for us at the moment. Sorry. :confused:

**Comment by florianvolle** [comment]
@schlitzered Closing this for the reason @bernd pointed out. Sorry!
