### ISSUE TITLE
changing the default index set not visible in all messages stream description

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#4386]
## Expected Behavior
When you change the default index set - that holds the *all messages* stream or any other that use the default index set - it should be visible in the Streams overview.

![indices_view](https://user-images.githubusercontent.com/404238/33443793-c801804e-d5f8-11e7-90cd-a24f60442026.png)

## Current Behavior
The current implementation has hardcoded "default index set" followed by the image "default". As the default index set has exactly the same name it is not visible where messages are stored on the stream page. 

![streams_view](https://user-images.githubusercontent.com/404238/33443811-d2da94ec-d5f8-11e7-8c77-625ff9335891.png)

## Possible Solution
Display the name of the current default index set and not a generic description that the default is used. Which is accidentally the same as the name of the first created index set.

* Graylog Version: 2.3.2

**Comment by flotpg** [comment]
Is this still not possible?
