### ISSUE TITLE
Unresolved "Unknown alert" still appears even when Alert condition was deleted

### ISSUE THREAD

**Issue by a9tm** [Graylog2/graylog2-server#4391]
Deleted 2 alert conditions but there are 2 Unknown alerts still are unresolved.

![](https://i.imgur.com/nPg94LZ.png)

## Expected Behavior

Alerts resolved/deleted

## Current Behavior

Unresolved alerts forever!

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: Graylog 2.3.2+3df951e 
* Elasticsearch Version: 5.6.3
* MongoDB Version: 3.2
* Operating System: CentOS 7

**Comment by joschi** [comment]
Refs #3200, #3265

**Comment by bernd** [comment]
@a9tm Please fill out the "Steps to reproduce" so we can reproduce your issue. Thank you.

**Comment by jalogisch** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by SuperKy3mu4** [comment]
I have the same issue on  Graylog version is 2.4.0 (Wildwuchs) released at 2018-01-03T00:00:00.000Z

**Comment by edmundoa** [comment]
@SuperKy3mu4 please tell us how to reproduce the issue in detail, otherwise is really hard to know how you got into that situation. Thank you!

**Comment by SuperKy3mu4** [comment]
Solved by manually deleting from Mongo alerts collection. Sorry, but i can't try to reproduce it on prod system.
