### ISSUE TITLE
Separate proxy settings for inter-node communication

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#4392]
_From @jekelundh on December 4, 2017 9:39_

When http_proxy is set the GL-nodes tries to connect to each other using proxy meaning everything goes offline.
Is there a way to set nonProxyHost in the "http_proxy" setting ?

Running GL graylog-server-2.4.0-4.beta.2  (with  embeddded threatintel plugin)
Env is Centos 7 with java 1.8.0_151-b12

_Copied from original issue: Graylog2/graylog-plugin-threatintel#74_

**Comment by joschi** [comment]
> Is there a way to set nonProxyHost in the "http_proxy" setting ?

No, that's currently not possible but it sounds like a good idea.

**Comment by jekelundh** [comment]
Without proxy settings the threatintel feature is unusable in a multihost GL setup so in my opinion it's a bug.
