### ISSUE TITLE
Getting Exception in thread "main" java.lang.NoClassDefFoundError: com/github/rvesse/airline/Cli 

### ISSUE THREAD

**Issue by mageshkumarxerago** [Graylog2/graylog2-server#4399]
Getting Exception in thread "main" java.lang.NoClassDefFoundError: com/github/rvesse/airline/Cli 
whenever executing "java -Djava.net.preferIPv4Stack=true -jar graylog.jar -u graylog" from my terminal inside of "graylog2-server" in graylog2-server-2.3. 

* Graylog Version: graylog2-server-2.3.
* Elasticsearch Version:
{
  "name" : "My First Node",
  "cluster_name" : "mycluster1",
  "version" : {
    "number" : "2.3.1",
    "build_hash" : "bd980929010aef404e7cb0843e61d0665269fc39",
    "build_timestamp" : "2016-04-04T12:25:05Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}

* MongoDB Version: MongoDB shell version: 3.2.16
* Operating System: Linux DL3XTEC020 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 
* Browser version: Google CHrome (Version 62.0.3202.94 (Official Build) (64-bit))

**Comment by joschi** [comment]
@mageshkumarxerago We're unable to support custom builds of Graylog (bd980929010aef404e7cb0843e61d0665269fc39 doesn't exist in the official Graylog repository, so I assume it's a custom build).

Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by joschi** [comment]
Ah, `bd980929010aef404e7cb0843e61d0665269fc39` is the build hash of Elasticsearch.

@mageshkumarxerago Which version of Graylog are you using *exactly*?

**Comment by mageshkumarxerago** [comment]
graylog2-server-2.3.

**Comment by mageshkumarxerago** [comment]
"bd980929010aef404e7cb0843e61d0665269fc39" this is Elasticsearch info right? why comparing it with graylog? actually i'm getting "java.lang.NoClassDefFoundError: com/github/rvesse/airline/Cli " excepton. is this because of the "Elasticsearch" ?

**Comment by joschi** [comment]
@mageshkumarxerago Which *exact* version of Graylog are you using? How did you install it?

**Comment by joschi** [comment]
@mageshkumarxerago Okay, then please refer to the community forums.
We won't and can't support custom builds of Graylog.

**Comment by mageshkumarxerago** [comment]
may i know the community forums links?

**Comment by joschi** [comment]
https://community.graylog.org/
