### ISSUE TITLE
Adding extra webpack configuration to plugins does not work

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#4402]
We still offer the possibility for frontend plugin authors to add extra webpack configuration, but that configuration seems to be ignored.

Today @mariussturm and I wanted to add the ability to load markdown files to the collector plugin, so we added some webpack config:

```
module.exports = new PluginWebpackConfig('org.graylog.plugins.collector.CollectorPlugin', loadBuildConfig(path.resolve(__dirname, './build.config')), {
  // Here goes your additional webpack configuration.
  module: {
    rules: [
      { test: /\.md$/, use: ['html-loader', 'markdown-loader'] },
    ],
  },
  resolve: {
    extensions: ['.md'],
  },
});
```

Printing the final webpack configuration into the console does not show any of that custom configuration.

This issue needs more investigation but a quick look pointed me to https://github.com/Graylog2/graylog2-server/pull/2907, which seems to have changed that behaviour, breaking custom webpack config in plugins.

## Expected Behaviour
One of:
- We let plugin authors add extra webpack config
- We don't let them do it, so we remove the docs and code saying that this is possible

## Current Behaviour
The [documentation](http://docs.graylog.org/en/2.3/pages/plugins.html#web-plugin-structure) and archetype [`webpack.config.js`](https://github.com/Graylog2/graylog2-server/blob/0620dee2addd43288cf1d4c9c8d7991c1a2ea89f/graylog-plugin-archetype/src/main/resources/archetype-resources/webpack.config.js#L7) mention that adding custom webpack config is possible, but the configuration you add there is not used, as far as I can see.

## Steps to Reproduce (for bugs)
1. Add some extra webpack configuration to your plugin `webpack.config.js`. For instance a new loader for a file type (see above)
1. Add a `console.log()` to the exported configuration in `webpack.combined.config.js`
1. Restart the dev server
1. See that the extra configuration you added is not used

## Your Environment
* Graylog Version: 3.0.0-SNAPSHOT (3f930e0bdc81f519a7da3030b27f7de14d082423)

**Comment by dennisoelkers** [comment]
Closing due to being outdated. Please reopen if this is still an issue for you!
