### ISSUE TITLE
How to customize login in graylog? 

### ISSUE THREAD

**Issue by mageshkumarxerago** [Graylog2/graylog2-server#4403]
I want to customize login in graylog based on my local DB. And also want to verify with apache syncope. 
May i know how to achieve it? 
What are all classes needed for this to customize based on given username and password?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 2.3.0
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@mageshkumarxerago You can try using the Graylog SSO plugin for that:
https://marketplace.graylog.org/addons/eeeb0704-d50a-4df0-a789-eee29b1bb11d

Other than that, you'll need to write your own authentication provider as a Graylog plugin:
http://docs.graylog.org/en/2.3/pages/plugins.html

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by mageshkumarxerago** [comment]
SSO Expecting ldap url like that. I dont want this type of plugin.
Moreover , i want customize form login service, may i know what are all the classes i need to customize my  login?
