### ISSUE TITLE
 Missing function level access control allows access to pages by unauthorised users

### ISSUE THREAD

**Issue by pimpampeter** [Graylog2/graylog2-server#4407]
**Description**

Some pages of the application can be accessed by unauthorised users.

**Impact**

Currently no sensitive data is available on these pages that can’t be access via another
method. However, access to these pages should be restricted.

The existence of this vulnerability can be verified by navigating to these URL’s 
```text
https://<hostname>/system/authentication/config
https://<hostname>/system/grokpatterns
https://<hostname>/system/logging
```

_Graylog 2.2.0 on Redhat 7_

**Comment by joschi** [comment]
I can confirm that this is still an issue in Graylog 2.4.0-beta.3+a6b18a2.
