### ISSUE TITLE
Weak password policy for local users increases risk of compromised accounts

### ISSUE THREAD

**Issue by pimpampeter** [Graylog2/graylog2-server#4408]
**Description**
In order to prove their authenticity to the application, users must supply both a username and a password. While users can choose their own passwords, Enterprise Webhosting does not enforce the usage of strong passwords.

**Impact**
Some application users will have a weak password and risk a compromised account through password guessing attacks.

**Reproduce**
- Log in to the application using an existing account.
- Browse to the change profile page.
- The resulting page, does not mention any password requirements.
- Enter the current password.
- Choose ‘aaaaaa’ as the new password
- After completing the form, the application will accept the password, indicating that a weak
password policy is in place.

Version: Graylog 2.2.0 on Centos 7

**Comment by joschi** [comment]
@pimpampeter I think this is kind of out-of-context for Graylog.

If you want strong password enforcement for your users, I'd recommend doing that in a central place and use external authentication (e. g. LDAP or AD) for Graylog.
