### ISSUE TITLE
GELFCodec invalid timestamp string warnings on 2.3

### ISSUE THREAD

**Issue by zmyrgel** [Graylog2/graylog2-server#4409]
After upgrading elasticsearch to from 2.x to 5.6 and Graylog from 2.2 to 2.3.2 I started to get following warnings on graylog-server.log:
2017-12-09T13:47:33.941+02:00 WARN  [GelfCodec] GELF message <dd2aca10-dcc0-11e7-9d1d-005056ac8704> (received from <xx.xx.xx.xx:63793>) has invalid "timestamp": 1512810656  (type: STRING)

I'm using rsyslog to forward syslog messages as GELF messges over UDP. I'm using following config with it:
template(name="gelf" type="list") {
    constant(value="{\"version\":\"1.1\",")
    constant(value="\"host\":\"")
    property(name="hostname")
    constant(value="\",\"short_message\":\"")
    property(name="msg" format="json")
    constant(value="\",\"timestamp\":\"")
    property(name="timegenerated" dateformat="unixtimestamp")
    constant(value="\",\"level\":\"")
    property(name="syslogseverity")
    constant(value="\",\"_programname\":\"")
    property(name="programname")
    constant(value="\",\"_facility\":\"")
    property(name="syslogfacility")
    constant(value="\",\"_facility-text\":\"")
    property(name="syslogfacility-text")
    constant(value="\",\"_level-text\":\"")
    property(name="syslogseverity-text")
    constant(value="\"}")
}
*.* @xx.xx.xx.xx:12201;gelf

## Expected Behavior
I'd expect the message processing to succeed.

## Current Behavior
I get the warnings shown above.

## Possible Solution
Not known

## Steps to Reproduce (for bugs)
1. run rsyslog with above config
2. enable gelf udp input on graylog
3. monitor graylog log

## Your Environment
Running the RPM packages from vendors

* Graylog Version: 2.3.2
* Elasticsearch Version: 5.6.5
* MongoDB Version: 3.0.15
* Operating System: CentOS 7 (latest packages)

**Comment by joschi** [comment]
@zmyrgel The warning is perfectly correct, but the message is parsed anyway.

This being said, you should take care that the "timestamp" in your GELF payload is a number *and not a string*; see http://www.rsyslog.com/doc/v8-stable/configuration/templates.html for details.
