### ISSUE TITLE
Permission issues on node-id file lead to not very helpful error messages and exit

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#4410]
The server repeatedly prints an error that no node-id file exists and that it created a new fil before exit if the node-id file cannot be written, **but no error about a file permission issue is printed**. This happened to me on initial setup. 

I moved this into the 2.4.0 milestone for now but am OK with moving it into 3.0.0 if it's hard to fix and if it is not a recent regression.

## Your Environment

* Graylog Version: v2.4.0-beta.4-SNAPSHOT
* Operating System: Ubuntu 17.10

**Comment by joschi** [comment]
@lennartkoopmann Please provide some information how to reproduce the issue.

**Comment by kroepke** [comment]
If the node id file belongs to root and isn't even readable the server correct exits with:

`ERROR: Unable to access file /home/kroepke/local/graylog/server1/node-id`

**Comment by kroepke** [comment]
The problem is that a readable, but not writable node-id file does not throw the expected `AccessDeniedException` (any more?) but instead a generic `IOException`.

**Comment by lennartkoopmann** [comment]
Correct, it happens when the file can't be *written*.
