### ISSUE TITLE
IP addresses displaying as integers in Quick Values

### ISSUE THREAD

**Issue by ryanc** [Graylog2/graylog2-server#4411]
I set up a custom mapping in Elasticsearch so the clientip field (which is extracted from Apache access logs) is stored as the IP address data type in Elasticsearch so I can do range searching. When using the IP data type, the top IP addresses displayed in the quick values table are displayed as long integers instead in dot-decimal notation.

## Expected Behavior

The expected behavior is that the top IP addresses are displayed in dot-decimal notation such as 10.0.0.1.

## Current Behavior
Currently, the IP addresses are displayed as long integers e.g. 10.0.0.1 is displayed as 167772161.

## Steps to Reproduce (for bugs)
Unfortunately, this problem happens in my staging environment, but not my development environment.

1. Create a custom mapping for the ip type in Elasticsearch
2. Store ip addresses in the field with the IP data type mapping.
3. Find the field in Graylog and click the quick values link.

## Context
It diminishes the usefulness of the quick values chart, which we use often in our organization.

## Your Environment

* Graylog Version: 2.3.2
* Elasticsearch Version: 2.4.4
* MongoDB Version: 3.0.15
* Operating System: CentOS 6.9
* Browser version: 57.0.1

Thank you!

**Comment by jalogisch** [comment]
@ryanc thank you for this finding. 

Currently using the ip data type in elasticsearch is not explicit supported, but it works. I personal have checked that in my Lab, but have Elasticsearch 5.6 running together with Graylog 2.4.0 (beta 3) and this combination should does not have this behavior. 

Maybe you can investigate on your end too. As some of the features included in 2.4 will not work on elasticsearch 2.x I would recommended the Update to 5.x before the Graylog update.

**Comment by bernd** [comment]
Refs #4425

**Comment by jalogisch** [comment]
This can't be reproduced in Graylog 2.4 with Elasticsearch 2.x or 5.x.

This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Comment by ryanc** [comment]
Upgrading to Elasticsearch 5 fixed the problem for us. Thank you.
