### ISSUE TITLE
Data Lookup should support authentication

### ISSUE THREAD

**Issue by sparkblaze** [Graylog2/graylog2-server#4413]
When creating a HTTP Data Adapter, if the url is hosted by a website requiring authentication, graylog cannot access the results.

## Expected Behavior
Graylog should be able to return results from a url requiring authentication

## Current Behavior
Currently graylog returns a generic block of JSON and offers little in the way of a reason.

`{
  "single_value": null,
  "multi_value": null,
  "ttl": 9223372036854776000,
  "empty": true
}`

## Possible Solution
When creating a HTTP Data Adapter, there should be options for custom headers to be added, such as 'Authorization', to facilitate authentication to URLs.

When testing a HTTP Data Adapter, returning the HTTP Status Code, as well as the lookup result would be beneficial in troubleshooting HTTP Data Adapter results.

## Context
At present our APIs use authentication to restrict access to certain API functions, with this in mind, graylog is unable to connect to the existing API environment to make use of Lookup Tables

## Your Environment

* Graylog Version: 2.3.2
* Elasticsearch Version: 5.6.4
* MongoDB Version: 3.6.0
* Operating System: Ubuntu 16.04

**Comment by bernd** [comment]
@sparkblaze The HTTP data adapter in Graylog 2.4 supports custom HTTP headers which can be used to set `Authorization` headers.

Can you please open a separate issue for your idea on improving the data adapter testing?

**Comment by bernd** [comment]
Closing this because support for HTTP headers will be included in the upcoming 2.4.
