### ISSUE TITLE
Reader user cannot edit their own information

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#4420]
While testing a PR I tried to edit a reader user information and could not get to the edit page. I got redirected to the not found page and I saw an error saying:
`There was an error fetching a resource: cannot GET http://localhost:9000/api/system/authentication/config (403). Additional information: Not authorized`

## Expected Behaviour
User should be able to see and edit their own information

## Current Behavior
Getting to the user form loads a resource the user is not allowed to load and the user gets redirected to the not found page.

## Steps to Reproduce (for bugs)
1. Create reader user
2. Go to the navigation bar -> name -> edit profile
3. Get redirected to 404 page

## Your Environment
* Graylog Version: Graylog 3.0.0-SNAPSHOT (ca0746da9). Graylog 2.4.0-beta.3-SNAPSHOT+846449b is not affected by this issue.

**Comment by mayrstefan** [comment]
This issue also affects the 2.4.0 release (Graylog 2.4.0+2115a42)
