### ISSUE TITLE
Admin role won't stick to AD user

### ISSUE THREAD

**Issue by dutchman80** [Graylog2/graylog2-server#4421]
## Expected Behavior

When I assign the Admin role to a user who as logged in via Active Directory, they should have that Admin role when they next log in

## Current Behavior

When the user logs in after having the Admin role added to them, their roles default back to whatever the mapping behavior dictates in the LDAP/AD setup.  In other words, the Admin role doesn't stick.

## Steps to Reproduce (for bugs)

1. Log into graylog with an AD user, and log out again to create that user's entry
2. Log into graylog as Admin and then add the Admin role to the AD user's entry, and then log out again
3. Log into graylog with the AD user that should now have Admin access, and see that they don't

## Context

Trying to assign specific AD users as Admins in graylog.  AD Group mapping doesn't help with this task.

## Your Environment

* Graylog Version:  2.3.2+3df951e
* Elasticsearch Version:  2.4.1-1
* MongoDB Version:  3.2.10-1
* Server Operating System:  CentOS 7
* Client Browser version:  Chrome

**Comment by joschi** [comment]
Duplicates #4299
