### ISSUE TITLE
Unable to load index_sets page

### ISSUE THREAD

**Issue by brianwawok** [Graylog2/graylog2-server#4432]
Running Graylog 2.3.2+3df951e 

Load up the index_sets page.. get nothing but javascript error spam

Any tips on where to go?

`
FetchProvider.js:17 There was an error fetching a resource: cannot GET http://hosturl:hostport/api/system/indexer/overview/somehash (500). Additional information: Fetching message count failed for indices [graylog_565, graylog_686, graylog_566, graylog_687, graylog_563, graylog_684, graylog_564, graylog_685, graylog_561, graylog_682, graylog_562, graylog_683, graylog_680, graylog_560, graylog_681, graylog_569, graylog_567, graylog_688, graylog_568, graylog_689, graylog_554, graylog_675, graylog_796, graylog_555, graylog_676, graylog_797, graylog_552, graylog_673, graylog_794, graylog_553, graylog_674, graylog_795, graylog_550, graylog_671, graylog_792, graylog_551, graylog_672, graylog_793, graylog_790, graylog_670, graylog_791, graylog_558, graylog_679, graylog_559, graylog_556, graylog_677, graylog_798, graylog_557, graylog_678, graylog_799, graylog_543, graylog_664, graylog_785, graylog_544, graylog_665, graylog_786, graylog_541, graylog_662, graylog_783, graylog_542, graylog_663, graylog_784, graylog_660, graylog_781, graylog_540, graylog_661, graylog_782, graylog_780, graylog_549, graylog_547, graylog_668, graylog_789, graylog_548, graylog_669, graylog_545, graylog_666, graylog_787, graylog_546, graylog_667, graylog_788, graylog_532, graylog_653, graylog_774, graylog_533, graylog_654, graylog_775, graylog_530, graylog_651, graylog_772, graylog_531, graylog_652, graylog_773, graylog_770, graylog_650, graylog_771, graylog_538, graylog_659, graylog_539, graylog_536, graylog_657, graylog_778, graylog_537, graylog_658, graylog_779, graylog_534, graylog_655, graylog_776, graylog_535, graylog_656, graylog_777, graylog_804, graylog_805, graylog_802, graylog_803, graylog_800, graylog_801, graylog_598, graylog_599, graylog_596, graylog_597, graylog_594, graylog_595, graylog_592, graylog_593, graylog_590, graylog_591, graylog_587, graylog_588, graylog_585, graylog_586, graylog_583, graylog_584, graylog_581, graylog_582, graylog_589, graylog_580, graylog_576, graylog_697, graylog_577, graylog_698, graylog_574, graylog_695, graylog_575, graylog_696, graylog_572, graylog_693, graylog_573, graylog_694, graylog_570, graylog_691, graylog_571, graylog_692, graylog_578, graylog_699, graylog_579, graylog_690, graylog_720, graylog_606, graylog_727, graylog_607, graylog_728, graylog_604, graylog_725, graylog_605, graylog_726, graylog_602, graylog_723, graylog_603, graylog_724, graylog_600, graylog_721, graylog_601, graylog_722, graylog_718, graylog_719, graylog_716, graylog_717, graylog_714, graylog_715, graylog_712, graylog_713, graylog_710, graylog_711, graylog_709, graylog_707, graylog_708, graylog_705, graylog_706, graylog_703, graylog_704, graylog_701, graylog_702, graylog_700, graylog_808, graylog_809, graylog_806, graylog_807, graylog_521, graylog_642, graylog_763, graylog_522, graylog_643, graylog_764, graylog_640, graylog_761, graylog_520, graylog_641, graylog_762, graylog_760, graylog_529, graylog_527, graylog_648, graylog_769, graylog_528, graylog_649, graylog_525, graylog_646, graylog_767, graylog_526, graylog_647, graylog_768, graylog_523, graylog_644, graylog_765, graylog_524, graylog_645, graylog_766, graylog_510, graylog_631, graylog_752, graylog_511, graylog_632, graylog_753, graylog_750, graylog_630, graylog_751, graylog_518, graylog_639, graylog_519, graylog_516, graylog_637, graylog_758, graylog_517, graylog_638, graylog_759, graylog_514, graylog_635, graylog_756, graylog_515, graylog_636, graylog_757, graylog_512, graylog_633, graylog_754, graylog_513, graylog_634, graylog_755, graylog_620, graylog_741, graylog_621, graylog_742, graylog_740, graylog_628, graylog_749, graylog_629, graylog_626, graylog_747, graylog_627, graylog_748, graylog_624, graylog_745, graylog_625, graylog_746, graylog_622, graylog_743, graylog_623, graylog_744, graylog_619, graylog_730, graylog_610, graylog_731, graylog_617, graylog_738, graylog_618, graylog_739, graylog_615, graylog_736, graylog_616, graylog_737, graylog_613, graylog_734, graylog_614, graylog_735, graylog_611, graylog_732, graylog_612, graylog_733, graylog_608, graylog_729, graylog_609]
`

I have roughly 300 indexes, each 3 GB big (so 900 GB of data).

This page totally worked when I had 100 indexes.. but I have also upgrade graylog. Unsure if this is a number of index problem, or related to a recent graylog upgrade.

## Expected Behavior

The index_sets page should load.

## Current Behavior

The index_sets page does not load.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by kpointer** [comment]
https://github.com/Graylog2/graylog2-server/issues/4300

**Comment by brianwawok** [comment]
@kpointer  thank you, that fixed me up!
