### ISSUE TITLE
timestamp overwrite

### ISSUE THREAD

**Issue by broerman** [Graylog2/graylog2-server#4436]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Hi @broerman, I am closing this issue, because it is missing most information required for us to investigate/reproduce/fix a defect. Please provide more information (at least a useful description and some steps to reproduce the phenomenon) and reopen it.
