### ISSUE TITLE
Support quoted keys in key_value function

### ISSUE THREAD

**Issue by ctwise** [Graylog2/graylog2-server#4438]
The key_value function works well but it doesn't support quoted values. Many Go apps log their output as key/value pairs with quoted values, e.g., 

```
time="2017-12-22T13:11:21Z" level=info msg="response completed" go.version=go1.7.6 http.request.contenttype="application/vnd.docker.distribution.manifest.v2+json" http.request.id=755eaa21-887d-49a9-8011-a245d19acc7f http.request.method=PUT  http.request.useragent="docker/17.09.1-ce go/go1.8.3 git-commit/19e2cf6 kernel/4.9.49-moby os/linux arch/amd64 UpstreamClient(Docker-Client/17.09.1-ce \\(darwin\\))" 
```

If there were no spaces in any of the quoted values, it would still work by using the support for removing characters, but values like 'msg="response completed"' turn into 'msg: response'.

The support for quoted characters should handle situations where some values are quoted are others are not.

At the moment I'm limping along by removing the values I know often have embedded strings and then grepping them out.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 2.3.2

**Comment by ptman** [comment]
Does this help: https://dassur.ma/things/regexp-quote/ ?

**Comment by vangourd** [comment]
I am having this problem as well parsing Sonicwall IPS logs which ship a time field with quotations and a stamp. So I can do key_value and strip out the quotations but then I end up with just the time.

**Comment by kroepke** [comment]
Essentially `key_value` needs another option to define what the quote characters are and if they are specified needs to parse the entire thing differently.

The current implementation is based on Guava's `Splitter` class and knows nothing about quoting. Quote balancing requires actual parsing of the input string and cannot done with just splitting, so the implementation needs to switch its parsing strategy if quote handling is required.

After initial key-value pair extraction the rest of the function can proceed as before.

Ideally the current behavior is preserved when no quote characters are given.

**Comment by jalogisch** [comment]
Maybe it would be nice to have the option `key_quote` and `value_quote` when you give that it will work with something like:

```
msg="response completed" 
```

So parsing for the quote character is only needed if that option is used. Because I guess that the parsing is more expensive than the split function.

**Comment by jalogisch** [comment]
[z#844482]

**Comment by Ximmer00** [comment]
Up and +1 for this feature !

Cannot extract k/v from Bastion sessions. Because it stops at first space into the Value, or extract k/v from inside a normal Value.

But as said by @jalogisch it would be more expensive to do this way.

Hope to see this soon.

**Comment by patrickmann** [comment]
The desired result may be achieved using `key_value` parameters `trim_value_chars` and/or `trim_key_chars`.
The following rule
```
rule "key_value_test"
when
    has_field("message")
then
    set_fields(
        fields: 
            key_value(
                value: to_string($message.message),
                trim_value_chars: "\"",
                trim_key_chars:"\"",
                delimiters:",",
                kv_delimiters:"="
            )
    );
end
```
and input value `key1="value1","key2"="value2", "key3"="compound value3"`
will result in the desired new fields:
```
key1
value1
key2
value2
key3
compound value3
```
I'm guessing these parameters were added more recently, since this is quite an old issue. If I missed something, please provide some examples which cannot be handled with the current functionality.
