### ISSUE TITLE
Non-admin user can stop/start an input

### ISSUE THREAD

**Issue by ueokande** [Graylog2/graylog2-server#4439]
Non-admin user (i.e. any user) can stop or start an input by a REST API.

## Expected Behavior

Non-admin users is forbidden to start or stop input.

## Current Behavior

Non-admin user cannot see "Start Input" or "Stop Input" in System/Inputs in a web-interface.
But the user can stop or start input by using a REST API:

    # start
    curl -X PUT -u guest:password "http://example.com/api/cluster/inputstates/${input_id}"

    # stop
    curl -X DELETE -u guest:password "http://example.com/api/cluster/inputstates/${input_id}"

## Possible Solution

In current implementation, [`ClusterInputStatesResource`](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterInputStatesResource.java) does not check whether user have a permission to start or stop an input.  It should check permission `inputs:terminate` for current user.

## Steps to Reproduce (for bugs)

1. Create a non-admin user.
2. Stop input by non-admin user's credential
   ```
   curl -X DELETE -u guest:password "http://example.com/api/cluster/inputstates/${input_id}"
   ```
3. Check input status by admin user.

## Context

I expect that can be a vulnerability.

## Your Environment

* Graylog Version: 2.3.2
* Elasticsearch Version: 5.6.3
* MongoDB Version: 2.6.10
* Operating System: Ubuntu 16.04
* Browser version:

**Comment by bernd** [comment]
@ueokande Thank you for the report. This will be fixed in the upcoming 2.4.1 bug fix release.
