### ISSUE TITLE
Issue with connection

### ISSUE THREAD

**Issue by kieulam141** [Graylog2/graylog2-server#4440]
I have just upgraded our graylog cluster to v2.4. Then I got this error "ERROR [NodeChecker] Error executing NodesInfo!
io.searchbox.client.config.exception.NoServerConfiguredException: No Server is assigned to client to connect"
and "Caused by: java.util.concurrent.ExecutionException: io.searchbox.client.config.exception.NoServerConfiguredException: No Server is assigned to client to connect"

## Your Environment

* Graylog Version: v2.4
* Elasticsearch Version: v5.5.1
* MongoDB Version: 3.4
* Operating System: ubuntu 16.04
* Browser version: google chrome

**Comment by jalogisch** [comment]
ref: https://community.graylog.org/t/graylog-v2-4-issue/3617/6

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
