### ISSUE TITLE
Help neeed -cannot start graylog

### ISSUE THREAD

**Issue by hanabadler** [Graylog2/graylog2-server#4447]
Hi Team

we run the graylog AWS image 
we wanted to upgrade, so we made an ami image.
once the ami image finished, graylog stopped working

when we try to reconfigure we got the following error
``
ubuntu@graylog:~$ sudo graylog-ctl reconfigure
Starting Chef Client, version 12.6.0
Compiling Cookbooks...
Recipe: graylog::default
  * directory[/etc/graylog] action create (up to date)
  Converging 123 resources
Recipe: apt::default
  * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
  * directory[/etc/apt/apt.conf.d] action create (up to date)
  * cookbook_file[/etc/apt/apt.conf.d/15update-stamp] action create (up to date)
  * execute[apt-get update] action nothing (skipped due to action :nothing)
  * execute[apt-get autoremove] action nothing (skipped due to action :nothing)
  * execute[apt-get autoclean] action nothing (skipped due to action :nothing)
  * execute[apt-get-update-periodic] action run (skipped due to not_if)
  * directory[/var/cache/local] action create (up to date)
  * directory[/var/cache/local/preseeding] action create (up to date)
  * template[/etc/apt/apt.conf.d/10recommends] action create (up to date)
  * apt_package[apt-transport-https] action install (up to date)
Recipe: graylog::default
  * directory[/etc/graylog] action nothing (skipped due to action :nothing)
Recipe: graylog::users
  * group[graylog] action create (up to date)
  * user[graylog] action create (up to date)
  * directory[/var/opt/graylog] action create (up to date)
  * template[/var/opt/graylog/.gitconfig] action create (up to date)
  * directory[/var/opt/graylog/data] action create (up to date)
Recipe: graylog::authbind
  * directory[/etc/authbind/byport] action create (up to date)
  * file[/etc/authbind/byport/!514] action create (up to date)
Recipe: runit::upstart
  * cookbook_file[/etc/init/graylog-runsvdir.conf] action create (up to date)
  * execute[initctl status graylog-runsvdir] action run

    ================================================================================
    Error executing action `run` on resource 'execute[initctl status graylog-runsvdir]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of initctl status graylog-runsvdir ----
    STDOUT:
    STDERR: initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
    ---- End output of initctl status graylog-runsvdir ----
    Ran initctl status graylog-runsvdir returned 1

    Resource Declaration:
    ---------------------
    # In /opt/graylog/embedded/cookbooks/runit/recipes/upstart.rb

     29: execute "initctl status graylog-runsvdir" do
     30:   retries 30
     31: end
     32:

    Compiled Resource:
    ------------------
    # Declared in /opt/graylog/embedded/cookbooks/runit/recipes/upstart.rb:29:in `from_file'

    execute("initctl status graylog-runsvdir") do
      action [:run]
      retries 30
      retry_delay 2
      default_guard_interpreter :execute
      command "initctl status graylog-runsvdir"
      backup 5
      returns 0
      declared_type :execute
      cookbook_name :runit
      recipe_name "upstart"
    end

Running handlers:
[2018-01-02T14:13:50+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-01-02T14:13:50+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 01 minutes 01 seconds
[2018-01-02T14:13:50+00:00] FATAL: Stacktrace dumped to /opt/graylog/embedded/cookbooks/cache/chef-stacktrace.out
[2018-01-02T14:13:50+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-01-02T14:13:50+00:00] ERROR: execute[initctl status graylog-runsvdir] (runit::upstart line 29) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of initctl status graylog-runsvdir ----
STDOUT:
STDERR: initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
---- End output of initctl status graylog-runsvdir ----
Ran initctl status graylog-runsvdir returned 1
[2018-01-02T14:13:50+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)`
``
is there anyway to fix it? we have rules written on the system and it huge lose to our company
please help
thanks
Hana

**Comment by edmundoa** [comment]
Hi,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
