### ISSUE TITLE
[DOM] Found 2 elements with non-unique id #input-XXX

### ISSUE THREAD

**Issue by jekelundh** [Graylog2/graylog2-server#4451]
The login form uses the same id for username and password.
While trying to automate screenshots using puppeteer we found that both username and password uses the same random generated input id. Together with the lack of "input name" makes it interesting to find a selector for puppeteer log in.

## Your Environment

* Graylog Version: graylog-server-2.4.0-7.rc.1.noarch
* Elasticsearch Version: elasticsearch-5.6.4-1.noarch
* MongoDB Version: mongodb-org-server-3.2.17-1.el7.x86_64
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Browser version: Chromium linux-515411

**Comment by joschi** [comment]
@jekelundh Thanks for reporting this!

The issue has already been fixed in #4334 (going into Graylog 3.0.0).
