### ISSUE TITLE
Browser window refreshes while configuring a new extractor

### ISSUE THREAD

**Issue by yves-vogl** [Graylog2/graylog2-server#4452]
When trying to configure a new extractor the browser window refreshes and therefore all form fields will be empty.

## Expected Behavior
The browser window should not refresh as there's no obvious reason for refreshing this view.

## Possible Solution
Stop refreshing the browser window.

## Steps to Reproduce (for bugs)
1. Open an input source
2. Load a message
3. Add an extractor (e.g. GROK pattern) and add some text into the form fields
4. Wait a few seconds
5. The browser windows refreshes and your entered data is gone

## Your Environment
* Graylog Version: Graylog v2.4.0+2115a42
* Browser version: Safari Version 11.0.2 (13604.4.7.1.3)

**Comment by edmundoa** [comment]
Hi @yves-vogl,

Have you got any clues on how that page refresh occurs? Any errors in your Graylog server logs or in your browser's JS console may help us to find the cause for the issue you described.

The most likely cause I can think of is a flaky connection between your Graylog web interface and server. That would technically not do a page refresh, but it could still lead to something similar as what you described.

**Comment by yves-vogl** [comment]
Hi @edmundoa,

that's good information as I'm experiencing infact something like a flaky connection. While using Graylog it sometimes looks like it's dropped its connection.

The firewalld seems not to agree with the traffic from the reverse proxy:

```
Jan  4 19:33:17 vm-23a6ccc9 kernel: STATE_INVALID_DROP: IN=eth0 OUT= MAC=52:54:00:10:00:aa:52:54:00:19:db:63:08:00 SRC=10.255.0.4 DST=10.255.0.69 LEN=52 TOS=0x00 PREC=0x00 TTL=63 ID=8103 DF PROTO=TCP SPT=52148 DPT=9000 WINDOW=411 RES=0x00 ACK FIN URGP=0 
Jan  4 19:33:30 vm-23a6ccc9 kernel: STATE_INVALID_DROP: IN=eth0 OUT= MAC=52:54:00:10:00:aa:52:54:00:19:db:63:08:00 SRC=10.255.0.4 DST=10.255.0.69 LEN=52 TOS=0x00 PREC=0x00 TTL=63 ID=8104 DF PROTO=TCP SPT=52148 DPT=9000 WINDOW=411 RES=0x00 ACK FIN URGP=0 
Jan  4 19:33:33 vm-23a6ccc9 kernel: STATE_INVALID_DROP: IN=eth0 OUT= MAC=52:54:00:10:00:aa:52:54:00:19:db:63:08:00 SRC=10.255.0.4 DST=10.255.0.69 LEN=52 TOS=0x00 PREC=0x00 TTL=63 ID=27602 DF PROTO=TCP SPT=52142 DPT=9000 WINDOW=246 RES=0x00 ACK FIN URGP=0 
Jan  4 19:33:56 vm-23a6ccc9 kernel: STATE_INVALID_DROP: IN=eth0 OUT= MAC=52:54:00:10:00:aa:52:54:00:19:db:63:08:00 SRC=10.255.0.4 DST=10.255.0.69 LEN=52 TOS=0x00 PREC=0x00 TTL=63 ID=8105 DF PROTO=TCP SPT=52148 DPT=9000 WINDOW=411 RES=0x00 ACK FIN URGP=0 
Jan  4 19:34:01 vm-23a6ccc9 kernel: FINAL_REJECT: IN=eth0 OUT= MAC=52:54:00:10:00:aa:52:54:00:19:db:63:08:00 SRC=10.100.0.1 DST=10.255.0.69 LEN=64 TOS=0x00 PREC=0x00 TTL=63 ID=0 DF PROTO=TCP SPT=55519 DPT=9000 WINDOW=65535 RES=0x00 CWR ECE SYN URGP=0 
Jan  4 19:34:01 vm-23a6ccc9 kernel: FINAL_REJECT: IN=eth0 OUT= MAC=52:54:00:10:00:aa:52:54:00:19:db:63:08:00 SRC=10.100.0.1 DST=10.255.0.69 LEN=64 TOS=0x00 PREC=0x00 TTL=63 ID=0 DF PROTO=TCP SPT=55520 DPT=9000 WINDOW=65535 RES=0x00 CWR ECE SYN URGP=0 
Jan  4 19:34:02 vm-23a6ccc9 kernel: FINAL_REJECT: IN=eth0 OUT= MAC=52:54:00:10:00:aa:52:54:00:19:db:63:08:00 SRC=10.100.0.1 DST=10.255.0.69 LEN=64 TOS=0x00 PREC=0x00 TTL=63 ID=0 DF PROTO=TCP SPT=55521 DPT=9000 WINDOW=65535 RES=0x00 CWR ECE SYN URGP=0 
```

But it's strange as I've experienced this with Apache httpd as reverse proxy either on the same machine as well as on separate machines.

Is there anything which may cause Graylog to reload internally? 

I'll have a look at the situation and sharing more details as soon as I've time to do so :-)
