### ISSUE TITLE
QuickValue available fields for stack

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#4468]
## Expected Behavior
If you want to stack values via customization of a quick values widget all available fields should be usable (and displayed alphabetical).

## Current Behavior
Not every populated field is present - at least not what is visible in the fields list on the left side. I looks like the stacked fields are loaded from the deflector and only fields that are written to the current index are visible.

The order of the fields looks random.

## Possible Solution
Take the same query result that is taken for the field tree.

* Graylog Version: 2.4
* Elasticsearch Version: 5.6

**Comment by bernd** [comment]
This should be possible with the aggregation builder. Please open a new issue if this is still an issue. Thank you!
