### ISSUE TITLE
get a log counter through REST API for httpjson telegraf agent

### ISSUE THREAD

**Issue by pierrick-openIT** [Graylog2/graylog2-server#4473]
Hi everyone,
on a my dsahboard i have multiple log counter. Is it possible to acces to it from REST API ?
I want to querying graylog from a telegraf agent.

Have a good day ;)

**Comment by jalogisch** [comment]
just use the Graylog Plugin https://github.com/influxdata/telegraf/tree/master/plugins/inputs/graylog
Just choose the metrics/counter you like to have.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
