### ISSUE TITLE
Empty Dashboard Widgets give Impression something is broken

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#4480]
If the search term of a dashboard widget does not result in to any data,
the widget will be displayed empty. This gives the impression the page loading
was broken, or at least the widget is broken.

## Expected Behavior
If no matching stream data can be displayed by a widget a icon or text should
be displayed explaining the user that there is no matching data available. 

## Current Behavior
The widget is rendered empty.

## Possible Solution
Render text where the table is displayed: "No matching data on this stream."

## Steps to Reproduce (for bugs)
1. Add a quick values dashboard data with a no matching search.
2. Go to the dashboard an take a look on the dashboard.

## Your Environment

* Graylog Version: pre 3.0.0
* Elasticsearch Version: 5.6.5
* MongoDB Version: 2.6.10
* Operating System: Ubuntu 16.04
* Browser version: Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by dennisoelkers** [comment]
Fixed in 8a84692172ef3a90e99f6157fe6fe26abb815e64.
