### ISSUE TITLE
Graylog in K8 is giving me Issues with Deflector. 

### ISSUE THREAD

**Issue by mhobotpplnet** [Graylog2/graylog2-server#4482]
## Expected Behavior

N/A
## Current Behavior

Graylog is broken when starts up. Due to index not having a alias.
## Possible Solution

Stop Graylog
Delete Index
Start Graylog with new index.  << This is actually bad because you lose data. 
 
## Steps to Reproduce (for bugs)

1. Crash Graylog (K8 docker) on a node. 

* Graylog Version: 2.4
* Elasticsearch Version: 5.5.4
* MongoDB Version: 3
* Operating System: K8
* Browser version: Chrome

## Error
```
Deflector exists as an index and is not an alias. (triggered 5 days ago)
The deflector is meant to be an alias but exists as an index. Multiple failures of infrastructure can lead to this. Your messages are still indexed but searches and all maintenance tasks will fail or produce incorrect results. It is strongly recommend that you act as soon as possible
```

**Comment by dennisoelkers** [comment]
@mhobotpplnet, thanks for reporting this.

With the current information it will not be possible to reproduce this issue. We need more and detailed descriptions of the situation that lead to your issue. How did Graylog crash? Which indices existed when it crashed and after it started erroneous? How did the related MongoDB collections look like when it was in a faulty state?

**Comment by joschi** [comment]
@mhobotpplnet Try disabling index auto creation in Elasticsearch:
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-index_.html#index-creation

Duplicates #4167.
