### ISSUE TITLE
Can't parse [index] value after Graylog 2.4 upgrade - grok extractor issue?

### ISSUE THREAD

**Issue by pavleec** [Graylog2/graylog2-server#4486]
After Graylog 2.4 some Grok extractors stopped working and are reporting errors in the logfile. 

## Expected Behavior
The message should be properly indexed and stored in ES

## Current Behavior
Message is not saved and dropped by the Graylog

## Steps to Reproduce (for bugs)
1.Define the following Grok extractor:
`RuleName:%{GREEDYDATA:rulename}, State:%{PROG:state}, ?(Metric:%{GREEDYDATA:metric_name}, Value:%{GREEDYDATA:metric_value})?`
2.Testing on the following example message - successful :
`RuleName:Test notification, State:alerting, Metric:High value, Value:100`
3.When you save the extractor and new message is being processed by Graylog the following error message appears in it's logfile (similar to the one in #4066):
`2018-01-17T13:52:18.737+01:00 WARN [Messages] Failed to index message: index=<graylog2_54> id=<3f38f910-fb85-11e7-b00d-000c29b2476d> error=<{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"Can't parse [index] value [not_analyzed] for field [metric_value], expected [true] or [false]"}}`

* Graylog Version: 2.4
* Elasticsearch Version: 5.6.5
* MongoDB Version: 3.2.11
* Operating System: Debian 8

**Comment by joschi** [comment]
@pavleec Try rotating your active write index (System / Indices / Index Set / Maintenance in the Graylog web interface).

**Comment by pavleec** [comment]
@joschi Thanks it helped 👍 Now it's not failing.
