### ISSUE TITLE
Option to change aggregate function on quick value's chart

### ISSUE THREAD

**Issue by tkald** [Graylog2/graylog2-server#4492]
## Expected Behavior
Ability to change aggregation function other than "count" on numerical fileds. Like sum, avg, max ...

## Current Behavior
Quick chart is aggregated by count. 

## Context
I'd like to show netflow traffic bytes by ip address on stacked quick chart histogram. For that I need sum of traffic bytes not count in time.

## Your Environment

* Graylog Version: 2.4
* Elasticsearch Version: 5.6
* MongoDB Version:
* Operating System: Ubuntu 16.04
* Browser version:

**Comment by destroy-everything** [comment]
Yes, options for aggregation is the first thing I looked into after installing the tool. Good tool but useless without this functionality

**Comment by dennisoelkers** [comment]
This has been possible since 3.2.
