### ISSUE TITLE
Progress bars on node and node details page are broken

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#4493]
## Expected Behavior

The progress bars for JVM memory and buffers should show the current values.

## Current Behavior

The progress bars don't change and don't show any values. The metrics response includes the JVM data, though.

![p](https://user-images.githubusercontent.com/461/35096574-f743d580-fc4c-11e7-8ddd-58fdc1210401.gif)

## Steps to Reproduce (for bugs)

1. Navigate to "System / Nodes"
2. Watch JVM memory progress bar
3. Navigate to a node details page
4. Watch the progress bars

## Your Environment

* Graylog Version: 3.0.0-SNAPSHOT+6762727
* Browser version: Chrome 63.0.3239.132

**Comment by bernd** [comment]
I don't see the issue with 2.4.1-SNAPSHOT+956ab33 so the 2.4 branch doesn't seem to be affected.

**Comment by edmundoa** [comment]
Looking into a single JVM metric returned by the server, the type seems to be broken, at least comparing it to other metrics. An example:

```
{
  full_name: "jvm.memory.heap.used",
  metric: {
    value: 318868768
  },
  name: "used",
  type: "memoryusagegaugeset$$lambda$29/489200959"
}
```

**Comment by joschi** [comment]
Dropwizard Metrics 4.x started using Java 8 lambda expressions which our "translation layer" is unable to handle.

https://github.com/dropwizard/metrics/blob/v4.0.2/metrics-jvm/src/main/java/com/codahale/metrics/jvm/MemoryUsageGaugeSet.java#L56
