### ISSUE TITLE
otx_lookup_ip function does not provide threat details

### ISSUE THREAD

**Issue by mudrunkar** [Graylog2/graylog2-server#4495]
otx_lookup_ip pipeline function does not provide any threat identification if an otx lookup is successful.
## Expected Behavior

I would expect the fields otx_threat_ids otx_threat_names to be populated (at least if there are multiple pulses related?) with a threat information in the return value of the fuction.
## Current Behavior

It seems (judging from the plugin description when not shipped with core graylog platform and after very brief skimming of the plugin code) the pipeline fuction otx_lookup_ip shall return threat_id and threat_name information (taken from the pulses) if the lookup is successful and threat is indicated. However, I haven't seen any such detailed information from the function, all I got is the string `{"otx_threat_indicated":true} ` if a theat is indicated.

## Possible Solution

The functions shall return at least the following information in addition:

- Threat Score

- Observed Activity

- Threat ID

- Threat Name

## Steps to Reproduce (for bugs)

I tested the lookup for instance with the following IP's present in the otx threat database: 207.250.29.220, 60.191.49.187, 71.6.165.200.

## Your Environment

* Graylog Version: 2.4.0
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by ion-storm** [comment]
Could add additional threat details from:
https://otx.alienvault.com/api

With a link to the OTX stream URL clickable within Graylog Search.

**Comment by pbr0ck3r** [comment]
Fixed in https://github.com/Graylog2/graylog-plugin-threatintel/pull/99

**Comment by bernd** [comment]
Fixed in https://github.com/Graylog2/graylog-plugin-threatintel/pull/99
