### ISSUE TITLE
Only single instance of Quick Values possible on Search page

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#4497]
## Expected Behavior

It should be possible to create multiple Quick Values widgets on the Search page without having to add them to a dashboard (which lacks search capabilities).

## Current Behavior

The Search page only supports a single instance of the Quick Values widget.

## Steps to Reproduce (for bugs)

1. Create "Quick Values" widget for a specific message field 
2. Create "Quick Values" widget for a different message field.
3. The first "Quick Values" widget for the first message field is replaced by the "Quick Values" widget for the second message field.

## Context

When digging into logs for a specific purpose, it's often useful to have a breakdown of multiple message fields independently via Quick Values.

This is not the same as having "stacked" values in a single Quick Values widget, which only show a combined analysis of the "stacked" message fields.

## Your Environment

* Graylog Version: 2.4.1
* Elasticsearch Version: 5.6.6
* MongoDB Version: 3.x
* Operating System: Ubuntu Linux (in Docker)

**Comment by lennartkoopmann** [comment]
This will be possible with views in Graylog v3.0.0.
