### ISSUE TITLE
anonimyze IPv4 addresses in pipelines

### ISSUE THREAD

**Issue by axinojolais** [Graylog2/graylog2-server#4498]
You can easily anonymize IPv4 addresses in an extractor, using the builtin converter named "Anonymize IPv4 Addresses". The problem with the extractor is that it applies to every single message of an input. If you want to mangle only specific messages from an input, you have to rely on pipelines.

However, there is no way that I found of applying a builtin converter in a pipeline. So I'd like to request the ability to easily anonymize IPv4 addresses in a pipeline. Perhaps a new function to apply a converter ?

Thank you

## Your Environment

* Graylog Version: 2.3.1+9f2c6ef

**Comment by joschi** [comment]
@axinojolais After you've converted your IP address string to an actual IP address object with `to_ip()`, you can use the `anonymized` property to get the IP address with the last octet set to 0.

```text
// Example: $message.client_ip == "10.20.30.42"
let ip_address = to_ip($message.client_ip);
// client_ip_anonymized == "10.20.30.0"
set_field("client_ip_anonymized", ip_address.anonymized);
```

Code reference:
https://github.com/Graylog2/graylog-plugin-pipeline-processor/blob/2.4.1/plugin/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ips/IpAddress.java#L51-L60

If you want to discuss this solution, please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
