### ISSUE TITLE
Dashboard filters

### ISSUE THREAD

**Issue by attrib** [Graylog2/graylog2-server#4501]
## Expected Behavior

Add a search box to the dashboard. The query from this new input is prepended to all widgets.
The query for each widget is then "( {Dashboard search} ) AND ( {widget query} )".

Use case would be to have one general dashboard for all X (e.g. all customers/sources/w/e), which can be refined to only show data for a X (single customer/source/w/e).

## Current Behavior

You have to create for each X (customer/source) a new dashboard and copy all widget. If one widget is edited you need to adjust all dashboards.

## Possible Solution

Add a search box to the dashboard. The query from this new input is prepended to all widgets.

**Comment by manishjhawar** [comment]
+1
I'd also request for a dropdown/textbox to select/enter the "relative time" for the dashboard that overrides the "search relative time" configuration for all the widgets on the page. Thus we would not have to build multiple dashboards for say 1H/4H/1D/7D.. as well :-)

**Comment by dennisoelkers** [comment]
Both requests contained in this issue have been implemented since `3.2.0`.
