### ISSUE TITLE
Error 404 Sharing query with play button on dashboard with reader account

### ISSUE THREAD

**Issue by fab-schn** [Graylog2/graylog2-server#4503]
## Expected Behavior
I have a user (Reader) and when i clicking to the play button on the dashboard i have the issue :

>     Page not found
>     The party gorilla was just here, but had another party to rock.
>     Oh, party gorilla! How we miss you! Will we ever see you again?

The problem is resolved with an admin account. 

## Current Behavior
The issue appear when i have update graylog server 2.3 to 2.4.
My current version : Graylog 2.4.1+0f97411 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: Graylog 2.4.1+0f97411 
* Elasticsearch Version: 5.6.6
* MongoDB Version: :2.6.10
* Operating System: Ubuntu 16.04 
* Browser version: Firefox Quantum 57.0.4

**Comment by dennisoelkers** [comment]
Your  account is missing one or more of the required search/stream permissions to replay the search. The fact that the play button is still shown is a bug, which was [recently addressed](Graylog2/graylog2-server#4483) so it is going to be fixed in the next major release.
