### ISSUE TITLE
Lookup table - enhanced handling of JSON arrays

### ISSUE THREAD

**Issue by jasonkeller** [Graylog2/graylog2-server#4515]
So I've run into an issue with the Infoblox WAPI where it likes to return everything in JSON arrays instead of straight up objects.  For example...

```
[
    {
        "_ref": "network/ZG5zLm5ldHdvcmskMTAuMTEuNjcuMC8yNC8w:10.0.0.0/24/default", 
        "options": [
            {
                "name": "netbios-name-servers", 
                "num": 44, 
                "value": "10.0.0.1,10.0.0.2", 
                "vendor_class": "DHCP"
            }, 
            {
                "name": "Avaya-242", 
                "num": 242, 
                "value": "REDACTED", 
                "vendor_class": "DHCP"
            }, 
            {
                "name": "vendor-class-identifier", 
                "num": 60, 
                "value": "PXEClient", 
                "vendor_class": "DHCP"
            }, 
            {
                "name": "dhcp-lease-time", 
                "num": 51, 
                "use_option": true, 
                "value": "3600", 
                "vendor_class": "DHCP"
            }, 
            {
                "name": "domain-name-servers", 
                "num": 6, 
                "use_option": true, 
                "value": "10.0.0.1,10.0.0.2", 
                "vendor_class": "DHCP"
            }, 
            {
                "name": "domain-name", 
                "num": 15, 
                "use_option": true, 
                "value": "blah.com", 
                "vendor_class": "DHCP"
            }, 
            {
                "name": "routers", 
                "num": 3, 
                "use_option": true, 
                "value": "10.0.0.1", 
                "vendor_class": "DHCP"
            }
        ]
    }
]
```

What I want to absorb as the single field return in the lookup table is the 'value' attribute of the object with the name 'domain-name' (yielding 'blah.com').  However, as this is an unsorted list, the position in the array will be changing per subnet that I query, so I cannot statically set a positional like ```$[0].options.[5].value``` as it will be wrong on others even if it's correct on this one.  I have been attempting to goad the device into only sending the single option I want in the resulting array, however I have been unsuccessful in doing so in this instance.

It would be helpful to be able to reference the array position via the 'name' attribute of the object that I want to pull.  I also cannot loop through it to do it myself in the pipeline rules (and it would be cleaner to add the functionality into data adapters anyway).

Thoughts?

**Comment by dennisoelkers** [comment]
This already works using JSONPath. In your case it would be `$[0].options[?(@.name=="domain-name")].value`. You can find a good JSONPath spec [here](http://goessner.net/articles/JsonPath/index.html#e2).

**Comment by jasonkeller** [comment]
@dennisoelkers thank you for finding what my googling did not; I tried putting this into the Data Adapter and it's in red complaining that "query does not return a single value".  Should I ignore this?

**Comment by dennisoelkers** [comment]
@jasonkeller Thanks for your input, I am glad it helped. I will take a look and check why it does not work for the single value.

**Comment by dennisoelkers** [comment]
@jasonkeller The problem is https://github.com/json-path/JsonPath/issues/272. Unfortunately JSONPath cannot index a filtered array. Big disappointment to me, but unless this is "fixed"/implemented, we cannot do much about it.
