### ISSUE TITLE
Add spaces in quick values title when stacking several fields

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#4518]
There's a tiny cosmetic issue left over from #4509. When a user stacks more than one field into a quick values visualization, the visualization title is not properly divided with spaces after commas:

<img width="582" alt="screen shot 2018-01-24 at 18 20 40" src="https://user-images.githubusercontent.com/716185/35346800-7c85cf38-0133-11e8-9b76-c2d8ca8b9e8e.png">

## Steps to Reproduce (for bugs)
1. Add quick values for a field
2. Go to the configuration and add two other fields to be stacked
3. See that the title is lacking some spaces

## Your Environment
* Graylog Version: Graylog 3.0.0-SNAPSHOT, Graylog 2.4.2

**Comment by dennisoelkers** [comment]
This issue has become obsolete.
