### ISSUE TITLE
CSV Export not in User Timezone

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#4523]
## Expected Behavior
If a user exports the search result to CSV he expects the timestamps to be in his set timezone.

## Current Behavior
The CSV is in the UTC timezone.

## Possible Solution
Using the user setting to convert the timezone to the user set.

## Steps to Reproduce (for bugs)
1. Change timezone of the user to a different as UTC
2. Export you search result to CSV and look at the result.

Related to #2689

## Your Environment
* Graylog Version: graylog pre-3.0.0
* Elasticsearch Version: 5.6.5
* MongoDB Version: 1:2.6.10-0ubuntu1
* Operating System: Ubuntu 16.04
* Browser version: google-chrome 63.0.3239.132

**Comment by edmundoa** [comment]
I thought about looking into this a couple times, but never managed to do it. Anyway, here are a couple of issues to think about when we tackle the problem:

First, we need to ensure the data contains the user time zone in timestamps, as the user may share the exported data with people in other time zones.

Secondly, we need to ensure doing this conversion is not too expensive computationally, since the amount of exported data may be quite big. Maybe we can do that in the `scroll` query we run on ES, but we also need to see how that affects performance.

**Comment by kroepke** [comment]
What is the `timestamp` field in the exported data?
If it is a ISO 8601 string with a timezone indicator, I think the behavior is ok, if it isn't then it probably should be.
My underlying question is: Do we need options for data exports and/or different export formats, too?

**Comment by Justmfree** [comment]
Hello Same issue on 
Graylog 3.2.4 , 

server side GMT +4 :

Time configuration
User admin:
2020-04-30 15:30:30 +04:00
Your web browser:
2020-04-30 15:30:30 +04:00
Graylog server:
2020-04-30 15:30:30 +04:00

when i see report csv file there is GMT timestamp, not GMT + 4 how can i resolve this issue ?

**Comment by juliohm1978** [comment]
Hi,

Exporting to CSV gives us lines in the following format:

```
"2020-11-11T16:17:13.649Z","<SOURCE>","<MESSAGE>"
```

With Z indicating UTC as a standard timezone, client applications can adjust the displayed timestamp according to where they are.

However, I'm not sure the average use case of "Export to CSV" in Graylog's web interface include automated clients expecting that timestamp format. Arguably, most are probably users clicking the export button so they can take log entries somewhere else -- send them by email or keep a local file for reference.

As a human, I I hardly expect ISO-8061 to be useful in this context.

An option to preserve local timezone in the "Export to CVS" will certainly be a welcome addition.

**Comment by Justmfree** [comment]
> Hi,
> 
> Exporting to CSV gives us lines in the following format:
> 
> ```
> "2020-11-11T16:17:13.649Z","<SOURCE>","<MESSAGE>"
> ```
> 
> With Z indicating UTC as a standard timezone, client applications can adjust the displayed timestamp according to where they are.
> 
> However, I'm not sure the average use case of "Export to CSV" in Graylog's web interface include automated clients expecting that timestamp format. Arguably, most are probably users clicking the export button so they can take log entries somewhere else -- send them by email or keep a local file for reference.
> 
> As a human, I hardly expect ISO-8061 to be useful in this context.
> 
> An option to preserve local timezone in the "Export to CVS" will certainly be a welcome addition.

I agree  with you. it will be nice to add user define TimeZone to CSV report...

**Comment by dennisoelkers** [comment]
Fixed in #11734.
