### ISSUE TITLE
Show recent messages for an input never loads

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#4533]
@TheJCamping wrote on https://github.com/Graylog2/graylog2-server/issues/4510#issuecomment-360869685:

On the /system/inputs page selecting "show recent messages" for an input will result in a page that never loads or an error message:
 Error Message: Unable to perform search query Details: Search status code: 500 Search response: cannot GET http://192.168.13.37:12900/search/universal/relative?query=gl2_source_input%3A54863813a78e39c792b058d1&range=0&limit=150&sort=timestamp%3Adesc (500)

In the developer tools for chrome. the network page shows a request to this address: http://graylog-01:12900/search/universal/relative?query=gl2_source_input%3A54863813a78e39c792b058d1&range=0&limit=150&sort=timestamp%3Adesc times out. If I change the range to 3000, I can get that request to load.

**Comment by edmundoa** [comment]
This is a design decision we did in https://github.com/Graylog2/graylog2-server/pull/3725. I guess we need to think about that and decide if we want to revert it or take another measure to mitigate this issue.

**Comment by TheJCamping** [comment]
Could this default to the current behavior and be changeable via the config file or a setting somewhere?

**Comment by edmundoa** [comment]
As different people think the button should behave in different ways, my proposal would be to let people decide what they want without (more) configuration options. I think changing the button into a dropdown with options may help:

<img width="1655" alt="screen shot 2018-01-30 at 11 37 04" src="https://user-images.githubusercontent.com/716185/35561946-2b4e73da-05b2-11e8-998e-c09b23782424.png">

Any opinions? /cc: @lennartkoopmann
