### ISSUE TITLE
LookupResult has no constructor or factory method usable by Jackson

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#4534]
While every property of [`LookupResult`](https://github.com/Graylog2/graylog2-server/blob/2.4.3/graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java) is annotated with a `@JsonProperty` annotation so that instances can be serialized with Jackson, it lacks a suitable constructor or factory method (with `@JsonCreator`) to **deserialize** and create an instance.

This makes it unnecessary hard to use `LookupResult` with anything that needs to serialize and deserialize the actual object graph, e. g. any external cache (instead of Guava Cache).

**Comment by yoster0520** [comment]
How about using the `Map` to store LookupResult's metadata? When cache LookupResult, we use `Map` to cache. when reading value from cache, we can convert `Map` to LookupResult.
