### ISSUE TITLE
multiline logs from syslog udp to graylog

### ISSUE THREAD

**Issue by sujeetbw** [Graylog2/graylog2-server#4536]
Hello,

I'm pushing modsecurity logs from linux server to gralog in syslog UDP input.

The problem is that I also getting the broken logs in graylog. the same mod-security generates on server.

Can you suggest anything.

![image](https://user-images.githubusercontent.com/35889875/35497319-ad563174-04ef-11e8-870a-ff6876fb106e.png)

**Comment by jalogisch** [comment]
@sujeetbw you should change the way of ingest data from your server to graylog - some kind that is able to use multiline.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
