### ISSUE TITLE
Notification test is working but not when triggered by the alerts

### ISSUE THREAD

**Issue by joaopsys** [Graylog2/graylog2-server#4543]
Hi,

I believe you don't provide support for non-official plugins, but I still feel like it could be a graylog issue, or that I simply could get more information by asking this.

I've been trying the command execution alarm callback plugin (https://github.com/nksft/graylog2-plugin-exec) and something weird is happening: When I create a notification and test it, it works without any issues. However when it is triggered by a real alert, I get 

> Error sending notification at 2018-01-30 09:09:20: No class found for type ir.elenoon.ExeCommandAlarmCallBack

**If this isn't something you can answer, I would please ask you to provide me info as to where I can dig into this, where can I find notification logs, etc**

## Expected Behavior
The notification is sent when the alert is triggered, since the test worked flawlessly.

## Current Behavior
Notification test is working, but when triggered by a real alert I get
> 'Error sending notification at 2018-01-30 09:09:20: No class found for type ir.elenoon.ExeCommandAlarmCallBack'

## Steps to Reproduce (for bugs)
1. Install https://github.com/nksft/graylog2-plugin-exec
2. Create a test alert/notification
3. Test notification
4. Trigger the alert

## Context
Trying to make graylog execute a command when an alert is triggered. In this case I want it to communicate with Nagios so that I can integrate this alert with the monitoring system.

## Your Environment

* Graylog Version: Graylog 2.3.2+3df951e
* Operating System: CentOS Linux release 7.4

**Comment by dennisoelkers** [comment]
Hey @joaopsys, thanks for reporting this.

How did you install the plugin? Did you contact the author of the plugin about the issue?

**Comment by joaopsys** [comment]
Hi Dennis,

I downloaded the .jar and moved it to the graylog plugins folder. I didn't contact the author since I assumed it worked, since the test worked.

Would you like me to contact the author instead?

**Comment by joschi** [comment]
> Would you like me to contact the author instead?

Yes. Also, the plugin has been built for Graylog 1.x and isn't guaranteed to work with Graylog 2.x whatsoever.

Please create a bug report in the issue tracker of the plugin:
https://github.com/nksft/graylog2-plugin-exec/issues
