### ISSUE TITLE
Download link in online docs leads to a 404

### ISSUE THREAD

**Issue by alias454** [Graylog2/graylog2-server#4546]
Hello,

When clicking the download link on http://docs.graylog.org/en/2.4/pages/installation/manual_setup.html#prerequisites, the linked downloads page does not exist.

The link from the online documents points to https://www.graylog.org/download. Where the link from https://www.graylog.org/ points to https://www.graylog.org/downloads.

Regards,
Brandon

**Comment by joschi** [comment]
@alias454 Thanks for reporting this! We'll take care of it. 😄 

@lennartkoopmann @taylormrhoades Could you please add a redirect from https://www.graylog.org/download (or generally `/download`) to https://www.graylog.org/downloads?

**Comment by joschi** [comment]
Re-opening the issue because the non-working download link (https://www.graylog.org/download) is being used in various other places such as https://www.youtube.com/watch?v=sNtz4minhK0.

**Comment by joschi** [comment]
```
$ curl -i https://www.graylog.org/download
HTTP/1.1 301 Moved Permanently
Server: openresty
Date: Fri, 02 Feb 2018 14:08:46 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: /downloads
Accept-Ranges: bytes
Via: 1.1 varnish
Age: 0
X-Served-By: cache-iad2124-IAD
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1517580520.621758,VS0,VE17

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
