### ISSUE TITLE
Grok Debugger in web interface

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#4548]
The Graylog web interface should contain a "Grok Debugger" inspired by https://grokdebug.herokuapp.com/ and using the existing Grok patterns in Graylog so that users can play around and test Grok patterns.

The output should be sufficiently detailed so that bugs in Grok patterns or missing Grok patterns can be easily spotted.

**Comment by jalogisch** [comment]
https://www.elastic.co/guide/en/kibana/current/grokdebugger-getting-started.html
