### ISSUE TITLE
Login after session timeout forgets what page you're on

### ISSUE THREAD

**Issue by glajchs** [Graylog2/graylog2-server#4551]
## Expected Behavior
After your session times out, if you hit login again, it should take you to the search page (or whatever page) you were previously on.
## Current Behavior
After your session times out, if you hit login again, you are logged in and brought to the default search page with your search query (or whatever other page you were on) lost.

## Possible Solution
When the 403 redirects you to the login page, that redirect could put the original full page url in a hash, that the login page can then parse and use post-login to redirect you back to.

## Steps to Reproduce (for bugs)
1. Login (in our case, we use github authenticated login)
2. Enter some custom search params and note that the URL persists them
3. Wait until your session times out (or set your system clock ahead enough hours to force a logout due to inactivity)
4. Click on the "authenticate with github" button (and notice that the URL has already lost your search params.
5. You get put on the search page, but without your history

## Context
I have a whole bunch of searches I keep up in tabs, sometimes only a few, and sometimes a lot, depending on what I'm monitoring/investigating.  Every day all these tabs require login, and after login I lose my context.  Luckily I can long-click the refresh page icon in chrome, and get back to a previous page (usually 2 pages ago) that still has the search criteria, but if I let this happen more than once, or through a browser restart, sometimes I lose these searches forever.  It's annoying to have to do this every day, and sometimes unrecoverable.  For important searches I can put it on a dashboard or make a saved search, but I can't do that for every search I'm ever doing.

## Your Environment

* Graylog Version: 2.2.3+7adc951
* Elasticsearch Version: 2.4.0
* MongoDB Version: 3.2.12
* Operating System: Amazon Linux 4.4.41-36.55.amzn1.x86_64
* Browser version: Chrome 64

**Comment by dennisoelkers** [comment]
@glajchs: What do you mean when you are saying 'Click on the "authenticate with github" button'?

**Comment by dennisoelkers** [comment]
Closing due to being outdated. Please reopen if this is still an issue for you!
