### ISSUE TITLE
Option for date in index name

### ISSUE THREAD

**Issue by jamesbeedy** [Graylog2/graylog2-server#4552]
It would be handy to have the option to have the date in the index name (e.g  `graylog_10-22-2018`).

**Comment by joschi** [comment]
@jamesbeedy That's a pretty weird date format…

**Comment by florianvolle** [comment]
We are currently not planning to implement this.

**Comment by markuchi** [comment]
We would also like that the index name have a date format. Maybe UTC date as per the log timestamps.
