### ISSUE TITLE
Unresolved "Unknown alert" still appears even when Alert condition was deleted (same as #4391)

### ISSUE THREAD

**Issue by SuperKy3mu4** [Graylog2/graylog2-server#4556]
I have the same issue on Graylog version is 2.4.0 (Wildwuchs) released at 2018-01-03T00:00:00.000Z
Elasticsearch 5.6.4

**Comment by edmundoa** [comment]
As this is the same as #4391, please use that issue and provide the required details so we can reproduce the issue and fix it.

Thank you!
