### ISSUE TITLE
v0.20.1: Extractor can't rewrite 'timestamp' field

### ISSUE THREAD

**Issue by ghost** [Graylog2/graylog2-server#456]
I tried to add extractor as it was shown in http://www.youtube.com/watch?v=DEReadkHf2Y video.
It adds successfully:

![graylog2_ext_00](https://f.cloud.github.com/assets/1145317/2280256/cc2afaae-9f85-11e3-91c4-7745c338430a.png)

but after that number of incoming messages stops to increase for this source, although
counter in extractor view shows all appropriate messages:

![graylog2_ext_01](https://f.cloud.github.com/assets/1145317/2280271/194ed8fa-9f86-11e3-959a-25f0b86dc161.png)

**Comment by nunofgs** [comment]
I'm having this issue as well in Graylog 2.1.2.

I'm trying to extract the `time` field into the `timestamp` field. No matter which extractor I pick, nothing works.

Here's what it looks like when I choose `timestamp2` field instead.

<img width="204" alt="screen shot 2017-01-23 at 10 57 43" src="https://cloud.githubusercontent.com/assets/92085/22201337/029c3df4-e15b-11e6-99c2-5f706824ed6e.png">

Any thoughts?

**Comment by joschi** [comment]
@nunofgs Please don't hijack old issues.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [public mailing list](https://groups.google.com/forum/#!forum/graylog2) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
