### ISSUE TITLE
Support for mongodb DNS seed-list connection format

### ISSUE THREAD

**Issue by drAlberT** [Graylog2/graylog2-server#4560]
## Expected Behavior

Graylog should allow the DNS seeding format for MondoDB connection string (new in MongoDB 3.6).

See [MongoDB 3.6 docs](https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format) for a detailed explaination.

## Current Behavior

Error message. "Connection string has to be '**mongodb://**'"

## Your Environment

* Graylog Version: 2.4
* Elasticsearch Version: 5.5
* MongoDB Version: 3.6.2
* Operating System: Ubuntu 16.04
* Browser version: not relevant

**Comment by joschi** [comment]
This will automatically be supported when/if we upgrade to MongoDB Java Driver 3.6.0 or later.

Refs https://jira.mongodb.org/browse/JAVA-2611

**Comment by joschi** [comment]
Just an update on the issue:

MongoJack updated to MongoDB Java Driver 3.6.x in version 2.8.1, but Fongo is still not compatible with the latest stable MongoDB Java Driver.

Refs mongojack/mongojack#165
Refs fakemongo/fongo#316
