### ISSUE TITLE
Missing alerts with condition "more than 0 message in 1 min" when Graylog is high loaded 

### ISSUE THREAD

**Issue by Abuleilei** [Graylog2/graylog2-server#4577]
I believe this is the same bug as: https://github.com/Graylog2/graylog2-server/issues/3884
## Expected Behavior
We have a stream with condition "message count: more than 0 message in 1 min", we expect it to trigger alert when this stream receives a message

## Current Behavior
We occasionally miss alerts from this stream, especially when graylog is overwhelmed. We confirm the stream did get the message, but no alert was triggered.  

## Possible Solution
We believe the problem is related with the message receive time and elasticsearch index time are different.
For example, Graylog does alert scan for this stream every minute, it will run at time x, then next one is x+60s, one message arrived Graylog at x-1s, because it has not been indexed by elasticsearch yet, it will not be picked up by the x scan, But when elasticsearch indexed it, and mark its timestamp as x-1s, the next scan at x+60s will only check time range (x, x+60s) for condition "more than 0 message in 1 min", so this message will not be scanned as well.
Solution: not sure if it is possible, but maybe alert scan should use the elasticsearch's processed timestamp? Or maybe change Graylog's alert scan from 1 minute to 30 seconds?
Temp Solution for users: Extend the condition's time range (from 1 minute to at least 2 minutes)

## Steps to Reproduce (for bugs)
1. Create two streams with exact same rules, one with condition "message count: more than 0 message in 1 min", the other one with condition "message count: more than 0 message in 5 min", both has the same alerts setup as well.
2. Overwhelm Graylog by sending thousands of messages (NOT match those streams) per second, keep elasticsearch fall behind.
3. Sent one message that matches the stream rules.
4. Check if those streams triggered any alert, expected: Yes, current: No.
5. Wait for one minute, stop overwhelming Graylog.
6. Check again if those streams triggered any alert, currently the 5 mins one did, but the 1 min one never had any alert during this test. (Both of the streams get the message.)

## Context
Alerts do not trigger consistently when they should. We may miss alerts when Graylog is busy, or the message was just sent too close to the scan time.

## Your Environment

* Graylog Version: 2.2.3
* Elasticsearch Version: 2.4.0
* MongoDB Version: 3.4.2
* Operating System: CentOS 6
* Browser version:

**Comment by joschi** [comment]
@Abuleilei What's the configuration of the [`alert_check_interval`](https://github.com/Graylog2/graylog2-server/blob/2.4.3/misc/graylog.conf#L456-L458) on your Graylog nodes?

Please also read http://docs.graylog.org/en/2.4/pages/streams/alerts.html for further details.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
