### ISSUE TITLE
Bind alerts/notifications to multiple streams

### ISSUE THREAD

**Issue by 0xmilkmix** [Graylog2/graylog2-server#4588]
## Expected Behavior

Would it be possible to bind alerts and their notifications to multiple streams/indices?

## Current Behavior
Alerts are currently bound to a single stream, making it clear but limits utilisation. 

In some cases you might have multiple tenants sending same types of logs stored in separate streams/indices. In this case, you have to duplicate alerts/notifications for each stream although it's the same alert/notification.

## Possible Solution
List of streams to which an alert and its notifications should be bound.

**Comment by bernd** [comment]
Alerting over multiple streams will be possible in the upcoming 3.1 release of Graylog.
