### ISSUE TITLE
Floating point values not allowed for threshold

### ISSUE THREAD

**Issue by tmostyn** [Graylog2/graylog2-server#4595]
The UI does not allow a floating point value to be entered for the Threshold field when creating a Field Aggregation Alert condition.  Metricbeat returns values between 0 and 1 (scaled floating point type) for CPU and filesystem use percentages.  This issue prevents creation of alerts on these metrics.

## Expected Behavior

The UI should allow a user to enter a floating point value between 0 and 1, 0.50, for example, for the Threshold of a Field Aggregation Alert condition.  Graylog should then alert on the condition set, if values received from Metricbeat for the specified metric are either above or below the Threshold, depending on the alert condition set, an alert should be generated.

## Current Behavior

When trying to enter a value of 0.50 for the Threshold of a Field Aggregation Alert Condition, the form informs the user to 'Please enter a valid value. The two nearest valid values are 0 and 1'.
 

## Steps to Reproduce (for bugs)

1.  Login to Graylog server from web UI
2.  Select 'Alerts' in the top menu bar.
3.  Select 'Manage Conditions' on the right in the 'Alert Overview'
4.  Select 'Add new condition' on the right in the 'Conditions' pane
5.  Select a stream on which to alert from 'Alert on stream' in 'Condition' pane
6.  Select 'Field Aggregation Alert Condition' from 'Condition type' in 'Condition' pane
7.  Select the 'Add alert condition' button in the bottom the 'Condition' pane
8.  Enter anything in 'Title' and 'Field' in the 'Create new Field Aggregation Alert Condition' form.
9.  Enter '0.50' in the 'Threshold' field.
10. Select 'Save' at the bottom of the 'Create new Field Aggregation Alert Condition' form.
11. Graylog UI does not save the form and informs the user under the 'Threshold' field:  'Please enter a valid value. The two nearest valid values are 0 and 1'

## Context

This is affecting us greatly.  We are trying to monitor filesystem and CPU usage in terms of percentage values.  We want to create alerts when values exceed specified thresholds.

We have servers reporting to Graylog (input streams) with Metricbeat.  Metricbeat report various percentages with a scaled floating point type so the returned values are between 0 and 1.  

## Your Environment

* Graylog Version:
Graylog v2.4.3+2c41897
* Elasticsearch Version:
```text
root@localhost:~# curl -XGET 'http://127.0.0.1:9200/'
{
 ...
  "version" : {
    "number" : "5.6.6",
    "build_hash" : "7d99d36",
    "build_date" : "2018-01-09T23:55:47.880Z",
    "build_snapshot" : false,
    "lucene_version" : "6.6.1"
  },
  "tagline" : "You Know, for Search"
}
```
* MongoDB Version:
```text
root@localhost:~# apt show mongodb-server
Package: mongodb-server
Version: 1:2.6.10-0ubuntu1
```
* Operating System:
```text
root@localhost:~# uname -a
Linux localhost 4.14.14-x86_64-linode94 #4 SMP Tue Jan 23 01:06:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
root@localhost:~# cat /etc/*releas*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
* Browser version:
Chrome: Version 63.0.3239.132

**Comment by joschi** [comment]
@tmostyn As a temporary workaround, you could scale these values up to an integer between 0 and 100 using a pipeline rule.

**Comment by tmostyn** [comment]
@joschi Thanks, I'll check the documentation and learn how to write pipeline rules.

**Comment by bernd** [comment]
This should not an issue anymore with the new events and alerts system. Please open a new issue if you still see the same issue with the new alerting. Thank you!
