### ISSUE TITLE
graylog.repo wrong address

### ISSUE THREAD

**Issue by jordan45453** [Graylog2/graylog2-server#4596]
When I pull down the graylog rpm with rpm -Uvh https://packages.graylog2.org/repo/packages/graylog-2.4-repository_latest.rpm

## Expected Behavior
When I do yum install graylog-server it should install the server.

## Current Behavior
I get an error that the path is incorrect, it looks like the /repo directory was remove and needs to be updated with the repo.

## Possible Solution
Change the path to the correct path at https://packages.graylog2.org/repo/packages/graylog-2.4-repository_latest.rpm

**Comment by joschi** [comment]
@jordan45453 Please post the complete error messages.

Did you follow the installation instructions at http://docs.graylog.org/en/2.4/pages/installation/operating_system_packages.html#rpm-yum-dnf?

**Comment by jordan45453** [comment]
Yes, I used that setup guide.

**Comment by joschi** [comment]
@jordan45453 Please post the complete error messages and the complete content of the file `/etc/yum.repos.d/graylog.repo`.

**Comment by jordan45453** [comment]
Entire Error:

[root@graylog ~]# yum install graylog-server
Loaded plugins: fastestmirror, langpacks
base/7/x86_64/signature                                                                                                                                                            |  811 B  00:00:00
base/7/x86_64/signature                                                                                                                                                            | 3.6 kB  00:00:00 !!!
elasticsearch-5.x/signature                                                                                                                                                        |  473 B  00:00:00
elasticsearch-5.x/signature                                                                                                                                                        | 1.3 kB  00:00:00 !!!
extras/7/x86_64/signature                                                                                                                                                          |  811 B  00:00:00
extras/7/x86_64/signature                                                                                                                                                          | 3.4 kB  00:00:00 !!!
https://packages.graylog2.org/repo/el/stable/2.4/x86_64/repodata/repomd.xml.asc: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

graylog                                                                                                                                                                            | 2.9 kB  00:00:00


 One of the configured repositories failed (graylog),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=graylog ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable graylog
        or
            subscription-manager repos --disable=graylog

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=graylog.skip_if_unavailable=true

failure: repodata/repomd.xml.asc from graylog: [Errno 256] No more mirrors to try.
https://packages.graylog2.org/repo/el/stable/2.4/x86_64/repodata/repomd.xml.asc: [Errno 14] HTTPS Error 404 - Not Found

graylog.repo contents:

[graylog]
name=graylog
baseurl=https://packages.graylog2.org/repo/el/stable/2.4/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-graylog

**Comment by jordan45453** [comment]
Entire Error: 

`[root@graylog ~]# yum install graylog-server
Loaded plugins: fastestmirror, langpacks
base/7/x86_64/signature | 811 B 00:00:00
base/7/x86_64/signature | 3.6 kB 00:00:00 !!!
elasticsearch-5.x/signature | 473 B 00:00:00
elasticsearch-5.x/signature | 1.3 kB 00:00:00 !!!
extras/7/x86_64/signature | 811 B 00:00:00
extras/7/x86_64/signature | 3.4 kB 00:00:00 !!!
https://packages.graylog2.org/repo/el/stable/2.4/x86_64/repodata/repomd.xml.asc: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

graylog | 2.9 kB 00:00:00

One of the configured repositories failed (graylog),
and yum doesn't have enough cached data to continue. At this point the only
safe thing yum can do is fail. There are a few ways to work "fix" this:

 1. Contact the upstream for the repository and get them to fix the problem.

 2. Reconfigure the baseurl/etc. for the repository, to point to a working
    upstream. This is most often useful if you are using a newer
    distribution release than is supported by the repository (and the
    packages for the previous distribution release still work).

 3. Run the command with the repository temporarily disabled
        yum --disablerepo=graylog ...

 4. Disable the repository permanently, so yum won't use it by default. Yum
    will then just ignore the repository until you permanently enable it
    again or use --enablerepo for temporary usage:

        yum-config-manager --disable graylog
    or
        subscription-manager repos --disable=graylog

 5. Configure the failing repository to be skipped, if it is unavailable.
    Note that yum will try to contact the repo. when it runs most commands,
    so will have to try and fail each time (and thus. yum will be be much
    slower). If it is a very temporary problem though, this is often a nice
    compromise:

        yum-config-manager --save --setopt=graylog.skip_if_unavailable=true
failure: repodata/repomd.xml.asc from graylog: [Errno 256] No more mirrors to try.
https://packages.graylog2.org/repo/el/stable/2.4/x86_64/repodata/repomd.xml.asc: [Errno 14] HTTPS Error 404 - Not Found`

graylog.repo Contents:

`[graylog]
name=graylog
baseurl=https://packages.graylog2.org/repo/el/stable/2.4/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-graylog`

**Comment by joschi** [comment]
@jordan45453 FWIW, the `repomd.xml.asc` file simply doesn't exist in the Graylog RPM repository (and also didn't for previous releases).

Could you please check the value of `gpgcheck` in your YUM configuration?

**Comment by joschi** [comment]
@jordan45453 Please try adding the following line to the `/etc/yum.repos.d/graylog.repo` file:
```text
repo_gpgcheck=0
```

**Comment by jordan45453** [comment]
@joschi That worked to install graylog. Doesn't this somewhat bypass security measures and not validate the install?

**Comment by joschi** [comment]
@jordan45453 See https://access.redhat.com/solutions/2850911 for details.

Yes, it's skipping the download and verification GnuPG signatures for all files from the repository.
But since they don't exist in our repository, they cannot be checked and other RPM-based distributions don't seem to verify them either.

We'll add the `repo_gpgcheck=0` line to our repository definitions to prevent these errors.

**Comment by jordan45453** [comment]
@joschi CentOS 7.4

**Comment by joschi** [comment]
@jordan45453 Thanks. This matches the details in the knowledge base article:

> With RHEL 7.4, the `stig-rhel7-disa` profile will add "repo_gpgcheck=1" to `/etc/yum.conf`
