### ISSUE TITLE
Add Multiple Inputs, Same Port

### ISSUE THREAD

**Issue by jordan45453** [Graylog2/graylog2-server#4599]
I am trying to add second UDP input, but I get an error.

## Expected Behavior
Ingest new messages from same port, new device.

## Current Behavior
»Address already in use.«. This means that you are unable to receive any messages from this input. This is mostly an indication for a misconfiguration or an error.

## Possible Solution
Do you have to open a new port for each device added of that protocol?

## Steps to Reproduce (for bugs)
1. Add UDP device.
2. Restart graylog.service and rsyslog
3. Add new UDP device.
4. Restart graylog.service and rsyslog
5. »Address already in use.«

**Comment by joschi** [comment]
@jordan45453 You can send messages from an (almost) arbitrary amount of clients to a single input. There's no need to create a new input per client.

Obviously you cannot start more than one network-based input on the same TCP or UDP port.
