### ISSUE TITLE
MongoDB installation on Ubuntu

### ISSUE THREAD

**Issue by jasonkeller** [Graylog2/graylog2-server#4604]
This is a request to update documentation for installation of MongoDB on Ubuntu.  Right now you have the following...

```
MongoDB
The Version included in Ubuntu 16.04 LTS can be used together with Graylog 2.4.x:

$ sudo apt-get install mongodb-server
```

I will say right now this is the road to hell.  There are no good ways off of MongoDB 2.6 on Ubuntu, especially in a replica set, and these are not official maintained packages from the maintainers.  I'm facing a daunting stepped-climb up to 3.6 (2.6 > 3.0 > 3.2 > 3.4 > 3.6), assuming I can even get 3.0 running on Xenial from a package somewhere.

Can we please point people to the latest official repo to start with?  Would save many people a lot of headache/heartburn in the long run.

**Comment by jalogisch** [comment]
we would merge a PR that includes the updated section in no time - so we appreciate any contribution.

**Comment by jasonkeller** [comment]
How do you do a pull request?  I've got a quick write up done for it.

**Comment by jalogisch** [comment]
go over to the documentation ( https://github.com/Graylog2/documentation ) and clone the repository, do you changes and then submit a PR.
Or use the Github online edit abilitys todo the changes.

**Comment by jasonkeller** [comment]
@jalogisch pull request submitted...

https://github.com/Graylog2/documentation/pull/420

**Comment by jasonkeller** [comment]
@jalogisch 

I deleted that branch and sent another pull request here, correcting which file is edited...sorry for the initial mixup; it's a madhouse here today.

https://github.com/Graylog2/documentation/pull/421
