### ISSUE TITLE
How to get a message in json without escape character ?

### ISSUE THREAD

**Issue by disantana** [Graylog2/graylog2-server#4611]
So, I send data from my app to graylog as a json. In log4j the json is without escape character but in my graylog stream show a incorrect json like this : `{\"request\":{\"URI\":\"/api/contas/consultar/limite/\",\"httpMethod\":\"GET\",\"headers\":\"{cache-control\\u003d[no-cache], postman-token\\u003d[a526f091-d3f8-4b1d-9771-25001acdb573], authorization\\u003d[a6ef1ed2-bcf6-4380-8a5b-ddb4057ece0d], user-agent\\u003d[PostmanRuntime/6.4.0], accept\\u003d[*/*], host\\u003d[localhost:9090], accept-encoding\\u003d[gzip, deflate], connection\\u003d[keep-alive]}\",\"body\":\"\",\"parameter\":{\"matricula\":[\"2322131\"]}},\"response\":{\"status\":500}}`

## Expected Behavior
A json without escape character.

## Possible Solution
I have tried send a json with the code `logger.info( StringEscapeUtils.unescapeJson(gson.toJson(lm)));` but its failed too.

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
