### ISSUE TITLE
Unable to Delete Graph Widget

### ISSUE THREAD

**Issue by nsiakotos** [Graylog2/graylog2-server#4613]
## Expected Behavior

1. Go to Dashboard
2. Click Unlock/Edit Dashboard
3. Click Delete Widget Trash Icon
4. Widget is removed from Dashboard

## Current Behavior

1. Go to Dashboard
2. Click Unlock/Edit Dashboard
3. Click Delete Widget Trash Icon
4. Widget clears out all content, widget box remains
5. Lock and refresh page, widget is still there with content
6. Only happens on graph widgets, other widgets delete as expected

## Steps to Reproduce (for bugs)

1. Go to Dashboard
2. Click Unlock/Edit Dashboard
3. Click Delete Widget Trash Icon
4. Widget clears out all content, widget box remains
5. Lock and refresh page, widget is still there with content
6. Only happens on graph widgets, other widgets delete as expected
7. I am able to delete the entire dashboard

## Context

1. Trying to remove graph widget from dashboard

Only relevant log I found in graylog server.log

2018-02-23T10:56:10.864-05:00 INFO  [DashboardWidgetsResource] Deleted widget <b046a7c4-ec96-4789-9ac0-a620c127daba> from dashboard <5a90397b33e86903d5c6743d>. Reason: REST request.

## Your Environment

3 Node graylog with mongodb local
3 Node elasticsearch 
* Graylog Version: 2.4.3
* Elasticsearch Version: 5.6.8
* MongoDB Version: 2.6.12
* Operating System: Centos 7.4.1708 (Core)
* Browser version: Chrome 64.0.3282.167

**Comment by joschi** [comment]
Duplicates #4525
Refs #4527

**Comment by atc0005** [comment]
@gerryeng

Just in case it's related, I wanted to note that I'm having this issue (or one close to it) with Graylog 2.4.3 and Google Chrome 66.0.3359.139. I tried using Mozilla Firefox 60 and was able to remove the widgets without any trouble.

**Comment by Packcy20** [comment]
Removing the widgets in Chrome it's not working but with  Mozilla Firefox 60 it works fine.

**Comment by edmundoa** [comment]
A fix for this will be included in the upcoming 2.4.5 release (https://github.com/Graylog2/graylog2-server/pull/4808).
