### ISSUE TITLE
graylog netflow sum function doesnt work

### ISSUE THREAD

**Issue by huegelc** [Graylog2/graylog2-server#4616]
Using netflow as a input. When I generate a chart  nf_bytes as SUM it rather shows as total. By adding this chart to a dashboard you can see that:

<img width="710" alt="graylog_-_dashboard_syslog" src="https://user-images.githubusercontent.com/6955465/36632726-691dbdf6-198a-11e8-9c85-6e4538a5b208.png">
<img width="1057" alt="grafik" src="https://user-images.githubusercontent.com/6955465/36633380-f23aee56-1994-11e8-9ff0-c7940928d18d.png">

```
Type: Field graph, cached for 10 seconds.  Widget is not bound to a stream.
More details:

Widget ID:
    7c03c461-fbd2-4236-a6ba-f7799cfe3eb4
Dashboard ID:
    5a88510e594bd100ad7b9edb
Valuetype:
    total
Renderer:
    line
Interpolation:
    linear
Timerange:
    { "type": "relative", "range": 0 }
RangeType:
    relative
Field:
    nf_bytes
Query:
    gl2_source_input:5a918dc1594bd100ac6e5259 AND 130.75.2.22
Interval:
    minute
Relative:
    0
```
* Graylog Version:Graylog 2.4.3+2c41897
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Hello @huegelc! Thanks for taking the time to report this issue. I am not seeing the problem yet. In which way is the value you get for the sum of the field not what you expected?

**Comment by huegelc** [comment]
Hi @dennisoelkers , thanks for your reply.

If you take a look at the screenshots below you see that I´ve created a nf_bytes graph with SUM as the value. 

![graylog_-_search](https://user-images.githubusercontent.com/6955465/36728975-e4d4a0e2-1bc2-11e8-97d1-b953138b4f75.jpg)


Now, if I add this chart to a dashboard it reverts the value from SUM to TOTAL:

![graylog_-_dashboard_netflow](https://user-images.githubusercontent.com/6955465/36728997-fc61e724-1bc2-11e8-8b22-265bd23c6864.jpg)

Here are the metrics of the widget:

```
Type: Field graph, cached for 10 seconds.  Widget is not bound to a stream.
More details:

Widget ID:
    031d1d09-7bd6-430e-a864-f0e545fb961e
Dashboard ID:
    5a87fe25643e742322b5ca2b
Valuetype:
    total
Renderer:
    line
Interpolation:
    linear
Timerange:
    { "type": "relative", "range": 0 }
RangeType:
    relative
Field:
    nf_bytes
Query:
    gl2_source_input:5a8866c5aefcbc20259a0be6
Interval:
    minute
Relative:
    0
```
Am I missing something?

**Comment by dennisoelkers** [comment]
I think there is a slight misunderstanding here, coming from our clumsy mixing of terms. An internal `Valuetype` (the one when you view the widget details) of `total` is equal to a selection of `Sum` when customizing the widget. Selecting `Total` for the `Value` when customizing a widget, is internally represented as a `Valuetype` of `count`. Sorry for this confusing behavior.

In any way:
  * `Sum`/`total`: sums up the values of all documents in the specified time range
  * `Total`/`count`: counts just the number of documents in the specified time range

I hope this helps!

**Comment by huegelc** [comment]
Sorry I lost you :) ..so why is the the graph on the dashboard wrong?

**Comment by huegelc** [comment]
closed due to inactivity
