### ISSUE TITLE
Searches in winlogbeat fields are Case Sensitive only

### ISSUE THREAD

**Issue by ion-storm** [Graylog2/graylog2-server#4620]
I am running the latest Graylog on Ubuntu 16.04 with winlogbeat sending in eventlog data.  When I do a search for winlogbeat_event_data_TargetUsername:MrSmith when it is logged as mrSmith or mrsmith Graylog returns no results.  I have 3 elasticsearch nodes running 5.6.8.  

How can I make searching fields case insensitive?

**Comment by joschi** [comment]
@ion-storm Message fields, which haven't been analyzed, can only be matched case-sensitive and with queries matching the complete field (e. g. regular expressions of wildcard queries matching the complete field content).

If you want to have full-text search for other fields than "message", "full_message", and "source", you'll have to create a custom Elasticsearch index mapping:

* http://docs.graylog.org/en/2.4/pages/configuration/elasticsearch.html#custom-index-mappings
* https://www.elastic.co/guide/en/elasticsearch/reference/5.6/analysis-analyzers.html
* https://www.elastic.co/guide/en/elasticsearch/guide/2.x/analysis-intro.html

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
