### ISSUE TITLE
The master branch can't build

### ISSUE THREAD

**Issue by bj1116** [Graylog2/graylog2-server#4621]
Git clone the master branch ,but can't build it ,have some error for "RuleLangParser"

public Rule parseRule(String id, String rule, boolean silent, PipelineClassloader ruleClassLoader) throws ParseException {
        final ParseContext parseContext = new ParseContext(silent);
        final SyntaxErrorListener errorListener = new SyntaxErrorListener(parseContext);

        final RuleLangLexer lexer = new RuleLangLexer(new ANTLRInputStream(rule));
        lexer.removeErrorListeners();
        lexer.addErrorListener(errorListener);

        final RuleLangParser parser = new RuleLangParser(new CommonTokenStream(lexer));
        parser.setErrorHandler(new DefaultErrorStrategy());
        parser.removeErrorListeners();
        parser.addErrorListener(errorListener);

**Comment by joschi** [comment]
@bj1116 According to Travis CI, our internal Jenkins CI, and my local machine, the master branch builds just fine. 😉 

➡️ https://travis-ci.org/Graylog2/graylog2-server/branches

You can take a look at the Travis CI configuration file for information how Graylog is being built.

https://github.com/Graylog2/graylog2-server/blob/bdf7147bc65b71c5ce419c04d64a3c2cf323a6c6/.travis.yml#L18-L24
