### ISSUE TITLE
graylog2/graylog docker container plugins

### ISSUE THREAD

**Issue by Noname2244** [Graylog2/graylog2-server#4623]
done
## Expected Behavior
A Volume for plugins is needed, ie. for enterprise plugins.

## Current Behavior
There is no volume for the plugin directory, ie. for adding enterprise plugin.

## Possible Solution
Mount of of the common directories

Virtual Machine Appliances | /opt/graylog/plugins/
Operating System Packages | /usr/share/graylog-server/plugin/

to a suitable local directory

## Steps to Reproduce (for bugs)
x

## Context
Can't add Enterprise plugin

## Your Environment
Using the  docker container graylog2/graylog  : latest
CE docker.

**Comment by joschi** [comment]
@Noname2244 Please refer to the documentation of the Graylog Docker container:
http://docs.graylog.org/en/2.4/pages/installation/docker.html#plugins

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
