### ISSUE TITLE
How to set Custom Search Result on Graylog?

### ISSUE THREAD

**Issue by exevolium** [Graylog2/graylog2-server#4628]
## Current Behavior

In the Graylog interface, I mark the definitions in the Fields section. When I refresh the page, the definitions I select become default. Could you ensure that these definitions are permanent when selected?

## Your Environment

* Graylog Version:2.4.3
* Elasticsearch Version:5.6
* MongoDB Version:3.2
* Operating System:CentOS7
* Browser version:Chrome 64.0.3282.186 

Source case:https://community.graylog.org/t/how-to-set-custom-search-result-on-graylog/4350

**Comment by joschi** [comment]
Duplicates #2836.
