### ISSUE TITLE
in Dashboard Histogram missing attribute "search query" in edit mode

### ISSUE THREAD

**Issue by eissko** [Graylog2/graylog2-server#4635]
## Expected Behavior

Having an option to edit "search query" of existing histogram in dashboard.

## Current Behavior

There is no option to edit "search query" of existing histogram. Only possible solution is create new histogram in a dashboard.

## Possible Solution

Add ability to edit "search query" of existing histogram like "quick values" and "count" do.

## Steps to Reproduce (for bugs)

1. Click some dashboard where histogram has been provided
2. Unlock dashboard - enable editing mode
3. Choose histogram and click edit mode
4. There si no current "search query"
5. Compare with other object like "quick values" or "counter"

## Context

Not big deal but... When changing "search query" of existing histogram in a dashboard there is no option to change it. Only one solution is creating new one.

## Your Environment

* Graylog Version: v2.4.3+2c41897
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version: Chrome 64.0.3282.186

**Comment by edmundoa** [comment]
Hi,

I'm closing this issue, as it is duplicating #3955. Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
