### ISSUE TITLE
Pipeline Function Request - to_geopoint

### ISSUE THREAD

**Issue by jasonkeller** [Graylog2/graylog2-server#4646]
Per https://community.graylog.org/t/pipeline-function-request-to-geopoint/4514

It would be a very nice addition to Graylog to have a pipeline function to specify the geo_point datatype for fields when recording geopoints to Elasticsearch for interfacing to external systems like Grafana, without mucking with templates.

**Comment by joschi** [comment]
According to the second example at https://www.elastic.co/guide/en/elasticsearch/reference/5.6/geo-point.html, the whole thing should already work if you're using a custom mapping for the respective fields, e. g. "src_coordinates" in your example.

From the Elasticsearch documentation:
```
PUT my_index
{
  "mappings": {
    "my_type": {
      "properties": {
        "location": {
          "type": "geo_point"
        }
      }
    }
  }
}

PUT my_index/my_type/2
{
  "text": "Geo-point as a string",
  "location": "41.12,-71.34" 
}
```

See http://docs.graylog.org/en/2.4/pages/configuration/elasticsearch.html#custom-index-mappings for details about custom index mappings in Graylog.

**Comment by jasonkeller** [comment]
@joschi that's modifying the index template, which must be done on a per-index-set basis (custom mappings).  I explicitly stated this would be to avoid that.  I also think this would be more in line with the direction you appear to provide with the other functions (to_date, to_ip, etc).  @lennartkoopmann correct me if I'm wrong that architecturally this appears to be the direction you want to head in vs constantly modifying index mappings underneath?  I guess I'm a bit confused as to the preferred direction here, for if we're supposed to modify index templates for everything, why do these other (to_) functions exist?

**Comment by i5okie** [comment]
Okay, could someone please fill me in as to why geo_point data type is not available in graylog?
As in without modifying the mappings.
