### ISSUE TITLE
Unable to perform search query Failed to parse query [message:*Error]

### ISSUE THREAD

**Issue by mahnunchik** [Graylog2/graylog2-server#4647]
I've faced with the error "Failed to parse query" for simple query.

## Expected Behavior

Wildcard search by `*Error`

## Current Behavior

Unable to perform search query Failed to parse query [message:*Error]

![image](https://user-images.githubusercontent.com/780935/37269588-16122642-25f1-11e8-942b-6dc3820f781f.png)

## Steps to Reproduce (for bugs)

1. Select stream
2. type `*Error` or `message:*Error`
3. Failed to parse query [message:*Error]

## Context
Docker-compose launch from docs.

## Your Environment

* Graylog Version:  2.4.3+2c41897 `graylog/graylog:2.4.3-1`
* Elasticsearch Version: `docker.elastic.co/elasticsearch/elasticsearch:5.6.8`
* MongoDB Version: `mongo:3.6`
* Operating System: Ubuntu 16.04 + Docker 17.12.1-ce, build 7390fc6
* Browser version: Chrome 64.0.3282.186

**Comment by joschi** [comment]
@mahnunchik Search queries with *leading* wildcard are disabled by default for performance reasons.

See http://docs.graylog.org/en/2.4/pages/queries.html#syntax and https://github.com/Graylog2/graylog2-server/blob/2.4.3/misc/graylog.conf#L313-L315 for details.

**Comment by dennisoelkers** [comment]
Can we improve the error message we are returning in the server's response? That would help users to solve it on their own. The error message which is returned in this case is not helping at all.
