### ISSUE TITLE
Copy input extractor not working for some syslog messages?

### ISSUE THREAD

**Issue by rayterrill** [Graylog2/graylog2-server#4662]
## Expected Behavior
Trying to defined a copy input extractor to normalize some user id values across multiple sources. Should copy value into the userid attribute.

## Current Behavior
Does not appear to work for some syslog entries (example below).

## Possible Solution
Unknown.

## Steps to Reproduce (for bugs)
Example syslog message:
```
CEF:0|CrowdStrike|FalconHost|1.0|DetectionSummaryEvent|Detection Summary Event|2| cn3Label=Offset deviceCustomDate1=50176-01-22 23:16:40 cn1=5910426sdf33549 sntdom=POP cs1Label=CommandLine cs6Label=FalconHostLink fname=net1.exe deviceCustomDate1Label=ProcessStartTime filePath=\\Device\\HarddiskVolume2\\Windows\\System32 cn3=3 externalID=f200664170ac4042sdfasdf511c6047f4a07a66 shost=PC1 cn1Label=ParentProcessId cs6=https://falcon.crowdstrike.com/activity/detections/detail/f20066417asdfasdf0ac4042511c6047f4a07a66/128916424789?_cid\=965ba3d65asdfaffb24ff28b119952aff6aee4 cs1="C:\\WINDOWS\\system32\\net1.exe" group MyGroup fileHash=3b6928bc39e5sadfasf530cead1e99269e7b1ee cn2=598497sdf642042 suser=myuser cn2Label=ProcessId msg=The command "net group" was executed, which attackers often use for lateral movement.
```

Extractor is set to always try to extract. Extraction strategy = copy, 

## Context
Trying to copy the value of the suser field into the userid field so we can search across all messages using userid.

## Your Environment
* Graylog Version: Graylog 2.4.3+2c41897 on localhost (Oracle Corporation 1.8.0_151 on Linux 4.4.0-96-generic)

**Comment by joschi** [comment]
@rayterrill Please provide the complete configuration of the extractors (and pipeline rules) you're using and some example messages (after they've been ingested, processed, and indexed).

**Comment by rayterrill** [comment]
Extractor config on my input GL_Syslog_UDP

Extractor type: Copy input
Source field: suser
Condition: Always try to extract
Store as field: userid
Extraction strategy: Copy
Extractor title: suser to userid
Add converted: N/a

I have 4 pipeline rules that drop extraneous messages, but nothing else. It isn't touching the messages in question.

Example messages:
```
cat: validateEntitlementsHmac
cn3: 4
cn3Label: Offset
cs1: CrowdStrike
cs1Label: ServiceName
deviceCustomDate1: 50176-05-18
deviceCustomDate1Label: Timestamp
deviceCustomDate2: 1521246397462
deviceCustomDate2Label: AuthActivityAuditEventTime
facility: Unknown
full_message: CEF:0|CrowdStrike|FalconHost|1.0|AuthActivityAuditEvent|Auth Activity Audit Event|| deviceCustomDate2=1521246397462 outcome=true deviceCustomDate2Label=AuthActivityAuditEventTime deviceCustomDate1Label=Timestamp cn3=4 deviceCustomDate1=50176-05-18 03:44:22 sourceTranslatedAddress=10.20.13.254 suser=Customer cs1Label=ServiceName cn3Label=Offset cs1=CrowdStrike Authentication cat=validateEntitlementsHmac
level: -1
message: CEF:0|CrowdStrike|FalconHost|1.0|AuthActivityAuditEvent|Auth Activity Audit Event|| deviceCustomDate2=1521246397462 outcome=true deviceCustomDate2Label=AuthActivityAuditEventTime deviceCustomDate1Label=Timestamp cn3=4 deviceCustomDate1=50176-05-18 03:44:22 sourceTranslatedAddress=10.20.13.254 suser=Customer cs1Label=ServiceName cn3Label=Offset cs1=CrowdStrike Authentication cat=validateEntitlementsHmac
outcome: true
source: mysource.mydomain.com
sourceTranslatedAddress: 10.20.13.254
suser: Customer
timestamp: 2018-03-17T00:26:33.596Z
```

Another one:
```
cn1: 591042633549
cn1Label: ParentProcessId
cn2: 598497642042
cn2Label: ProcessId
cn3: 3
cn3Label: Offset
cs1: C:\\WINDOWS\\system32\\net1.exe
cs1Label: CommandLine
cs6: https://falcon.crowdstrike.com/activity/detections/detail/f200664170ac4042511c6047f4a07a66/128916424789?_cid\=965ba3d65fb24ff28b119952aff6aee4
cs6Label: FalconHostLink
deviceCustomDate1: 50176-01-22
deviceCustomDate1Label: ProcessStartTime
externalID: f200664170ac4042511c6047f4a07a66
facility: Unknown
fileHash: 3b6928bc39e5530cead1e99269e7b1ee
filePath: \\Device\\HarddiskVolume2\\Windows\\System32
fname: net1.exe
full_message: CEF:0|CrowdStrike|FalconHost|1.0|DetectionSummaryEvent|Detection Summary Event|2| deviceCustomDate1Label=ProcessStartTime cs1Label=CommandLine cn3Label=Offset shost=MYMACHINE cn1=591042633549 cs6=https://falcon.crowdstrike.com/activity/detections/detail/f200664170ac4042511c6047f4a07a66/128916424789?_cid\=965ba3d65fb24ff28b119952aff6aee4 cs1="C:\\WINDOWS\\system32\\net1.exe" group MYGROUP fileHash=3b6928bc39e5530cead1e99269e7b1ee cs6Label=FalconHostLink cn2Label=ProcessId sntdom=MYDOMAIN suser=MYUSER msg=The command "net group" was executed, which attackers often use for lateral movement. cn3=3 fname=net1.exe cn2=598497642042 filePath=\\Device\\HarddiskVolume2\\Windows\\System32 externalID=f200664170ac4042511c6047f4a07a66 cn1Label=ParentProcessId deviceCustomDate1=50176-01-22 23:16:40
level: -1
message: CEF:0|CrowdStrike|FalconHost|1.0|DetectionSummaryEvent|Detection Summary Event|2| deviceCustomDate1Label=ProcessStartTime cs1Label=CommandLine cn3Label=Offset shost=MYMACHINE cn1=591042633549 cs6=https://falcon.crowdstrike.com/activity/detections/detail/f200664170ac4042511c6047f4a07a66/128916424789?_cid\=965ba3d65fb24ff28b119952aff6aee4 cs1="C:\\WINDOWS\\system32\\net1.exe" group MYGROUP fileHash=3b6928bc39e5530cead1e99269e7b1ee cs6Label=FalconHostLink cn2Label=ProcessId sntdom=MYDOMAIN suser=MYUSER msg=The command "net group" was executed, which attackers often use for lateral movement. cn3=3 fname=net1.exe cn2=598497642042 filePath=\\Device\\HarddiskVolume2\\Windows\\System32 externalID=f200664170ac4042511c6047f4a07a66 cn1Label=ParentProcessId deviceCustomDate1=50176-01-22 23:16:40
msg: The
shost: MYMACHINE
sntdom: MYDOMAIN
source: mysource.mydomain.com
suser: MYUSER
timestamp: 2018-03-17T00:26:33.593Z
```

Let me know what else I can provide @joschi

**Comment by joschi** [comment]
@rayterrill What type of input are you using exactly and what's the full configuration of that input?

**Comment by joschi** [comment]
If you're using a Syslog input, how are you parsing the CEF payload?

**Comment by rayterrill** [comment]
I have a bunch of extractors on this input - including a key=value extractor (below). I'm assuming that's how it's parsing?

Extractor type=Copy input
Source field=message
Condition=Always try to extract
Store as field=message
Extraction strategy = Copy
Extractor title = K=V Extractor
Add converter = N/A
Add Key=Value pairs as fields = Yes

Maybe the issue is that my extractors aren't sorted properly? Although I swear this used to work and I haven't changed the ordering.

**Comment by joschi** [comment]
@rayterrill A Key-Value Extractor wouldn't be able to extract a CEF-formatted message.

**Comment by rayterrill** [comment]
I actually don't know then.

The extractors I have configured on this input are (in this order:)

- Grok pattern (only applies to messages containing ASA-4-106023)
- Grok pattern (only applies to messages containing ASA-6-113005)
- Grok pattern (only applies to messages containing ASA-6-113004)
- Grok pattern (only applies to messages containing ASA-4-113019)
- a user > userid copy input extractor (this appears to not be working anymore either)
- Grok pattern (only applies to messages container BIGIP02 notice apmd\[14988\])
- Grok pattern (only applies to messages container BIGIP02 notice tmm[21706]:)
- suser to userid copy input extractor (the original reason for this ticket)
- the key = value extractor documented above

**Comment by joschi** [comment]
@rayterrill If the key-value extractor runs *after* the copy input extractor, then the "suser" field won't exist at the time the copy input extractor is executed.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by rayterrill** [comment]
@joschi That's what I figured although I swear this worked before. Cheers mate.
