### ISSUE TITLE
Sidecar collector and Graylog API

### ISSUE THREAD

**Issue by maxstarkov** [Graylog2/graylog2-server#4677]
Hello! I want to use graylog to process and store logs located on remote servers. To collect logs from remote servers, use Sidecar Collector, which is installed on these servers.
I'm interested in the following question:
Sidecar Collector periodically accesses some of the graylog API methods to get the settings. I need to restrict access to these open API methods so I want to know the addresses of these methods.

**Comment by joschi** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by mariussturm** [comment]
@maxstarkov spoiler: search here for `NewRequest`: https://github.com/Graylog2/collector-sidecar/blob/master/api/graylog.go
