### ISSUE TITLE
Field graph series name

### ISSUE THREAD

**Issue by FelixFV** [Graylog2/graylog2-server#4680]
Hello! 
feature request
I propose to provide the possibility to set the names for series on graphs
I think this can be useful for many users
As example: 
blue: all messages
yellow: messages marked as spam
![screensh1](https://user-images.githubusercontent.com/7019849/37817049-3e7d4a24-2e6d-11e8-8a63-b7562a19d13d.PNG)

## Your Environment
* Graylog Version: 2.4.3+2c41897, codename Wildwuchs

**Comment by Ragazzo** [comment]
@FelixFV @dennisoelkers any news on this one? was it implemented? can you please link me up to some docs if I can help with that to be implemented. thank you

**Comment by gabrielpedepera** [comment]
This feature was it already implemented?

**Comment by mmahacek** [comment]
Looking for follow up as well.  I see how to label a metric, but I would like to be able to apply a label to row/column fields as well - especially for logbeat collected data.

**Comment by HungryHowies** [comment]
+1 here on this feature

**Comment by dennisoelkers** [comment]
This has been implemented for a while, therefore I am closing this. 

@mmahacek, your request seems to be of a different kind. Feel free to open another issue describing your problem.
