### ISSUE TITLE
Pipeline: Stage: Cursor automatically move from stage field to stage rules field after input only one digit

### ISSUE THREAD

**Issue by cdengatgithub** [Graylog2/graylog2-server#4681]
when create or modify a pipeline stage, Cursor will automatically move from stage field to stage rules field just after input only one number and before all stage numbers input get done.
## Expected Behavior

when create/modify a pipeline stage, the cursor should keep in the stage field before press a return or tab.
## Current Behavior

when create or modify a pipeline stage, Cursor will automatically move from stage field to stage rules field just input only one digit into stage field and before press enter or tab.

## Steps to Reproduce (for bugs)

1. create/edit pipe stage
2. input a digit into stage field
3.
4.

## Your Environment

* Graylog Version: 2.4.3-1
* Elasticsearch Version: 5.6.8-1
* MongoDB Version: 3.6.3-1
* Operating System: CentOS 7.4
* Browser version: firefox-52.7.2-1

**Comment by joschi** [comment]
Refs https://community.graylog.org/t/cursor-automatically-jump-to-stage-rule-field-after-input-one-number-into-stage-field/4699

**Comment by ousmaneo** [comment]
Hi, I was working on this bug. 
And I'm not able to reproduce it ether on the current Master branch or on the Graylog 3.1.3 instance we have. Please provide more input .
