### ISSUE TITLE
Provide "join" function to complement "split"

### ISSUE THREAD

**Issue by twall** [Graylog2/graylog2-server#4688]
## Expected Behavior
Complement "split" function with "join" in functions available to pipeline rules.

I've got a bunch of messages coming in that need to have a given character or substring replaced by another.   A common use case is to convert a long message into a set of lines, then re-join those lines with a newline or BR tag.

For example, I might want to convert multiple "\r\n" sequences to a single "\n", or "<BR/>" to "\n".

## Current Behavior
No functions exist to perform these operations

## Possible Solution
I could use `split` to get rid of the "\r\n\r\n", but then I'd need a complementary `join`, e.g.
```
join(split(message, "\r\n\r\n"), "\n")
```

Another solution, `urldecode` (see #4706):
```
message = urldecode(message)
```

Or just perform a straight up replace (see #4705):
```
replace(message, "%2520", " "[, limit=0])
```

## Context
More flexibility in converting raw data into its desired form.

## Your Environment

* Graylog Version: v2.4.3+2c41897
* Operating System: ubuntu 16.16

**Comment by dennisoelkers** [comment]
@twall, this issues seems to cover multiple topics, can you please open separate issues for `urldecode` and `replace` and restrict this to `join`?
