### ISSUE TITLE
Syslog Inputs are missing from fresh installations

### ISSUE THREAD

**Issue by rootameen** [Graylog2/graylog2-server#4696]
Hi. 

I just finished RPM installation and noticed that Syslog inputs are completely missing from the platform, and as they are not available for installation separately, no syslog messages can be received.

## Expected Behavior
To have Syslog UDP / TCP inputs available in inputs list.

## Current Behavior
Only inputs available are Beats, 3 AWS Inputs (Flow, Logs, and CloudTrail, and 2 CEF Inputs (AMQP & Kafka)

## Possible Solution
Manual import of Syslog inputs?

## Steps to Reproduce (for bugs)
Regular Centos 7 64bit installation via RPM. SELinux/FW aren't the issue.

## Context
I noticed that after the installation, rsyslog daemon wasn't running, and no config was applied to it. I enabled the listeners for TCP/UDP and manually started it, then restarted Graylog without luck.

## Your Environment
Centos 7 64bit installation via RPM

* Graylog Version: graylog-server-2.4.3-1.noarch
* Elasticsearch Version: elasticsearch-5.6.8-1.noarch
* MongoDB Version: mongodb-org-3.6.3-1.el7.x86_64
* Operating System: CentOS Linux release 7.4.1708 (Core) 
* Browser version: Chrome 65

**Comment by edmundoa** [comment]
Hi,

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by rootameen** [comment]
Interesting. Sounds like a bug when key feature appears to be missing from the default installation. 
I'll post over the forums. Thanks.

**Comment by fega** [comment]
@rootameen hello, im having the same issue, also seems to me to be a bug, how did you solve it?
