### ISSUE TITLE
Possible Memory Leak in Graylog 2.4.3?

### ISSUE THREAD

**Issue by rbjorklin** [Graylog2/graylog2-server#4708]
For a while now we've been running an older version (2.2.x) of Graylog and it's been crashing due to OOM once every other month or so. We decided to upgrade to see if the problem had been resolved but it doesn't seem like it. See images at bottom where "Heap Usage (after GC)" is constantly increasing. GC reports were generated with: http://gceasy.io

## Expected Behavior
Graylog doesn't crash due to OOM every now and then.

## Current Behavior
Graylog does crash due to OOM every now and then.

## Steps to Reproduce (for bugs)
1. Have Graylog running for a month or two

## Your Environment

* Graylog Version: 2.4.3
* Elasticsearch Version: 5.6.8
* MongoDB Version: 3.6.3
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Browser version: Firefox 59.0.2
* Java version: jdk-10-10-ga.x86_64
`BEGIN EDIT`
* We are running GELF & Beats inputs with TLS and client auth.
`END EDIT`

`GRAYLOG_SERVER_JAVA_OPTS="-Xms1g -Xmx1g -server -XX:+UseParallelGC -XX:+UseTransparentHugePages -XX:+AlwaysPreTouch --add-modules java.corba,java.xml.bind --illegal-access=permit -Xlog:gc*:file=/var/log/graylog-server/gc.log"`

![graylog-first-gc-log](https://user-images.githubusercontent.com/1704798/38406570-f967467e-3975-11e8-9fe3-8914cfe01e17.png)
![graylog-second-gc-log](https://user-images.githubusercontent.com/1704798/38406573-fdf423b0-3975-11e8-8d4b-5ab4cb38df7a.png)

**Comment by rbjorklin** [comment]
$ jmap -histo:live 17151
     num     #instances         #bytes  class name (module)                                               
    -------------------------------------------------------                                               
       1:       1311300      165611968  [B (java.base@10)
       2:        427903       34915848  [Ljava.util.HashMap$Node; (java.base@10)                                                                                                                                     
       3:        173428       28580088  [I (java.base@10)                                                                                                                                                            
       4:        548910       21956400  java.util.LinkedHashMap$Entry (java.base@10)
       5:        322994       18087664  java.util.LinkedHashMap (java.base@10)
       6:        429524       13744768  java.util.HashMap$Node (java.base@10)
       7:          2608       13039712  [C (java.base@10)
       8:        224425       10772400  java.util.HashMap (java.base@10)
       9:        153991       10566968  [Ljava.lang.Object; (java.base@10)
      10:          6630        9609024  [S (java.base@10)
      11:        395864        9500736  java.lang.String (java.base@10)
      12:         68008        8705024  org.jvnet.hk2.guice.bridge.internal.GuiceServiceHk2Bean
      13:         78270        7513920  org.jvnet.hk2.internal.SystemDescriptor
      14:         68484        6026592  java.lang.reflect.Method (java.base@10)
      15:         74152        5338944  org.glassfish.hk2.utilities.DescriptorImpl
      16:        161336        5162752  sun.security.util.DerInputBuffer (java.base@10)
      17:        161336        5162752  sun.security.util.DerValue (java.base@10)
      18:        159511        5104352  java.util.LinkedList (java.base@10)
      19:        127305        5092200  java.util.TreeMap$Entry (java.base@10)
      20:        119365        4774600  java.math.BigInteger (java.base@10)
      21:        140089        4482848  sun.security.util.ObjectIdentifier (java.base@10)
      22:        276314        4421024  java.util.LinkedHashSet (java.base@10)
      23:        161336        3872064  sun.security.util.DerInputStream (java.base@10)
      24:        161325        3871800  [Lsun.security.x509.AVA; (java.base@10)
      25:        161325        3871800  sun.security.x509.AVA (java.base@10)
      26:        161325        3871800  sun.security.x509.RDN (java.base@10)
      27:         80530        3865440  java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync (java.base@10)
      28:        232857        3725712  java.lang.Object (java.base@10)
      29:        113194        3622208  java.util.concurrent.ConcurrentHashMap$Node (java.base@10)
      30:         85661        3426440  java.util.WeakHashMap$Entry (java.base@10)
      31:        135774        3258576  java.util.ArrayList (java.base@10)
      32:        131072        3145728  org.graylog2.plugin.buffers.MessageEvent
      33:        192205        3075280  java.util.LinkedHashMap$LinkedKeySet (java.base@10)
      34:         71731        2869240  jdk.nio.zipfs.ZipFileSystem$IndexNode (jdk.zipfs@10)
      35:         35089        2807120  java.net.URI (java.base@10)
      36:        109235        2621640  java.util.LinkedList$Node (java.base@10)
      37:         38810        2483840  java.util.concurrent.ConcurrentHashMap (java.base@10)
      38:         19879        2367168  java.lang.Class (java.base@10)
      39:         70082        2242624  sun.security.x509.AlgorithmId (java.base@10)
      40:         52590        2103600  org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext
      41:         42081        2019888  sun.security.x509.X500Name (java.base@10)
      42:         80532        1932768  java.util.concurrent.locks.ReentrantReadWriteLock (java.base@10)
      43:         71758        1722192  java.lang.Long (java.base@10)
      44:         21035        1682800  sun.security.x509.X509CertImpl (java.base@10)
      45:         10678        1649120  [Ljava.util.concurrent.ConcurrentHashMap$Node; (java.base@10)
      46:         65536        1572864  org.graylog2.shared.buffers.RawMessageEvent
      47:         98012        1568192  java.util.HashSet (java.base@10)
      48:         19504        1560320  com.google.common.cache.LocalCache$Segment
      49:         48327        1546464  java.lang.ref.ReferenceQueue (java.base@10)
      50:         42081        1458720  [Lsun.security.x509.RDN; (java.base@10)

**Comment by rbjorklin** [comment]
$ jmap -histo:live 17151
    num     #instances         #bytes  class name (module)
    -------------------------------------------------------
       1:       1650226      205757488  [B (java.base@10)
       2:        487992       39583176  [Ljava.util.HashMap$Node; (java.base@10)
       3:        223585       36451000  [I (java.base@10)
       4:        590195       23607800  java.util.LinkedHashMap$Entry (java.base@10)
       5:        366872       20544832  java.util.LinkedHashMap (java.base@10)
       6:        489282       15657024  java.util.HashMap$Node (java.base@10)
       7:          2621       13763392  [C (java.base@10)
       8:        257329       12351792  java.util.HashMap (java.base@10)
       9:        174998       12035576  [Ljava.lang.Object; (java.base@10)
      10:        474961       11399064  java.lang.String (java.base@10)
      11:         78008        9985024  org.jvnet.hk2.guice.bridge.internal.GuiceServiceHk2Bean
      12:          6629        9608944  [S (java.base@10)
      13:         88270        8473920  org.jvnet.hk2.internal.SystemDescriptor
      14:        211886        6780352  sun.security.util.DerInputBuffer (java.base@10)
      15:        211886        6780352  sun.security.util.DerValue (java.base@10)
      16:        166863        6674520  java.util.TreeMap$Entry (java.base@10)
      17:        156739        6269560  java.math.BigInteger (java.base@10)
      18:         69119        6082472  java.lang.reflect.Method (java.base@10)
      19:         84152        6058944  org.glassfish.hk2.utilities.DescriptorImpl
      20:        184046        5889472  sun.security.util.ObjectIdentifier (java.base@10)
      21:        178452        5710464  java.util.LinkedList (java.base@10)
      22:        211886        5085264  sun.security.util.DerInputStream (java.base@10)
      23:        211875        5085000  [Lsun.security.x509.AVA; (java.base@10)
      24:        211875        5085000  sun.security.x509.AVA (java.base@10)
      25:        211875        5085000  sun.security.x509.RDN (java.base@10)
      26:        310726        4971616  java.util.LinkedHashSet (java.base@10)
      27:        277336        4437376  java.lang.Object (java.base@10)
      28:         90530        4345440  java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync (java.base@10)
      29:        159926        3838224  java.util.ArrayList (java.base@10)
      30:        117745        3767840  java.util.concurrent.ConcurrentHashMap$Node (java.base@10)
      31:         46079        3686320  java.net.URI (java.base@10)
      32:        215230        3443680  java.util.LinkedHashMap$LinkedKeySet (java.base@10)
      33:         85741        3429640  java.util.WeakHashMap$Entry (java.base@10)
      34:        131072        3145728  org.graylog2.plugin.buffers.MessageEvent
      35:         92063        2946016  sun.security.x509.AlgorithmId (java.base@10)
      36:         45442        2908288  java.util.concurrent.ConcurrentHashMap (java.base@10)
      37:        120350        2888400  java.util.LinkedList$Node (java.base@10)
      38:         71731        2869240  jdk.nio.zipfs.ZipFileSystem$IndexNode (jdk.zipfs@10)
      39:         69056        2762240  org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext
      40:         55269        2652912  sun.security.x509.X500Name (java.base@10)
      41:         19971        2377600  java.lang.Class (java.base@10)
      42:         27629        2210320  sun.security.x509.X509CertImpl (java.base@10)
      43:         90532        2172768  java.util.concurrent.locks.ReentrantReadWriteLock (java.base@10)
      44:         81731        1961544  java.lang.Long (java.base@10)
      45:         55269        1915888  [Lsun.security.x509.RDN; (java.base@10)
      46:         57123        1827936  java.lang.ref.ReferenceQueue (java.base@10)
      47:        112071        1793136  java.util.HashSet (java.base@10)
      48:         39686        1718224  [Ljava.lang.String; (java.base@10)
      49:         10684        1651744  [Ljava.util.concurrent.ConcurrentHashMap$Node; (java.base@10)
      50:         65536        1572864  org.graylog2.shared.buffers.RawMessageEvent

**Comment by rbjorklin** [comment]
Looking at a heap dump these five classes show up at the top and are continuously increasing between dumps.

    org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext
    org.jboss.netty.handler.ssl.SslHandler
    sun.security.ssl.SSLEngineImpl
    sun.security.x509.X509CertImpl
    byte[]

I didn't say so in my original post but we are using TLS for a few of our inputs.

**Comment by jalogisch** [comment]
thank you for this detailed report. Did you see the same behaviour if you use JDK 8 / Java 8 which is the current supported Version for Graylog 2.4?

**Comment by rbjorklin** [comment]
I haven't taken any heap dumps with JDK 8 however Graylog crashed due to OOM every other month so while running on JDK 8 so I feel pretty confident in saying this problem exists on that version of Java as well.

**Comment by rbjorklin** [comment]
Restarted Graylog by choice just now or it would have happened very soon on its own due to OOM.
![graylog-third-gc-log](https://user-images.githubusercontent.com/1704798/38663666-bf8d8c44-3e37-11e8-9def-ebb9796d3cf9.png)

**Comment by rbjorklin** [comment]
Problem seems to have disappeared either by itself or after upgrading to 2.4.4.

**Comment by dennisoelkers** [comment]
Thanks for the update, @rbjorklin!
