### ISSUE TITLE
[Bug report] Missing Java modules while starting Graylog service

### ISSUE THREAD

**Issue by noavarice** [Graylog2/graylog2-server#4710]
I think this is a problem with my particular system, but maybe this may help you some way in the future, and if I had a mistake somewhere - please point me. There are missing Java modules while trying to start Graylog service - JAXB and CORBA

## Expected Behavior
Service starts properly

## Current Behavior
Errors occure during service startup. This is the `journalctl -xe` output: https://imgur.com/79NrezV

## Possible Solution
I have fixed this by adding CORBA and JAXB modules to the classpath manually in the GRAYLOG_SERVER_JAVA_OPTS variable (placed in the `/etc/default/graylog-server`):
`GRAYLOG_SERVER_JAVA_OPTS="--add-modules java.xml.bind --add-modules java.corba <rest of options>`. Fixed in the sense that graylog service starts without critical errors and web interface is accessible.
All these problems probably arise from the fact of using JDK 9 where this modules were removed from default classpath, but my JAVA_HOME definitely points to valid JDK 8 directory (see below)

## Steps to Reproduce (for bugs)
This problem had appeared right after installation. These are the steps I made:
1) install `MongoDB` from system package manager;
2) tried to install ES several times. Finally install from zip-archive;
3) install Graylog repo from deb package and then install Graylog itself, no problems occured.
4) start mongo and ES: `systemctl start mongodb.service`, `./<unpacked ES dir>/bin/elasticsearch` (previously `cluster.name` for ES was set to `graylog`). Both up & running - checked through browser (`localhost:27017` and `localhost:9200` accordingly)

## Your Environment
* Graylog Version: 2.4.3-1 from deb-package, no errors during installation
* Elasticsearch Version: 5.6.8 from zip-archive
* MongoDB Version: 3.4.7
* Operating System: Ubuntu 17.10, kernel version: 4.13.0-38-generic
* JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

**Comment by joschi** [comment]
@noavarice Graylog 2.x doesn't support Java 9 or later.

As you can see from the error messages and from the fact that adding JVM parameters introduced in Java 9 solve your problem, it is evident that you're *not* using a supported Java version to run Graylog 2.x. 😉
