### ISSUE TITLE
Unable to create new index set with default values

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#4724]
## Expected Behavior

Creating a new index set with default values (besides providing required values) should succeed.

## Current Behavior

When opening the new index set form, the `Field type refresh interval` shows `NaN` instead of a number. Submitting the form returns an error related to this.

![screen shot 2018-04-16 at 16 20 24](https://user-images.githubusercontent.com/41929/38815891-35dda34c-4195-11e8-85bb-cdd199e40c70.png)

## Steps to Reproduce (for bugs)

1. System -> Indices -> Create Index Set
2. Fill in required values
3. Click "Save"

## Your Environment

* Graylog Version: 3.0.0-alpha.2-SNAPSHOT (3822aecdb0d60fc039601ca9d12ef49f9adfc838)
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by edmundoa** [comment]
I checked that the `NaN` value in the interval field is gone, but there is still some error while submitting the form with the default field type refresh interval:

```
Can not construct instance of org.graylog2.rest.resources.system.indexer.responses.IndexSetSummary, problem: Null fieldTypeRefreshInterval
at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@3ca43619; line: 1, column: 705]
```

**Comment by waynekearns** [comment]
Currently the default field displays "1" with seconds selected in the drop down to the right, and it fails with that value as the default. If you click into the dialogue and attempt to delete "1", you cannot. The numeric value can be incremented by clicking on the up/down arrows. The newly incremented value cannot be selected/deleted, but changing the value allows the index set to be created.
