### ISSUE TITLE
new feature request: Web GUI localization support

### ISSUE THREAD

**Issue by cdengatgithub** [Graylog2/graylog2-server#4728]
Currently Graylog's Web GUI doesn't support localization. please offer localized web GUI or make localization related parts not hardcoded into codes so that others can easy do the localization job.
## Expected Behavior

1.  offer a separated parts from codes for localization.
2.  support localized Web GUI

## Current Behavior

doesn't support localized web GUI.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by florianvolle** [comment]
We agree that a localized web GUI would be better. Nevertheless I am closing this as we do not have it on our longterm roadmap.

Thanks!
