### ISSUE TITLE
Custom Colors for Widgets in Dashboards

### ISSUE THREAD

**Issue by ruby-is-pretty-cool** [Graylog2/graylog2-server#4759]
## Expected Behavior
I would like to see the ability to give a custom sequence of colors for dashboard widgets, especially for things like pie charts, added to Graylog Dashboards. Colors could allow us to more quickly communicate to viewers if something is good or bad, or differentiate between two widgets of the same type that are right next to each other in the dashboard.

## Current Behavior
Currently, the color scheme is always the same. For Histograms, the bars are always blue, and for pie charts the first color is always orange, the second pink, the third green and so on. This causes some confusion even to me as I view the pie graphs that are next to each other because I start to associate orange with one thing and then when I look at another graph I expect orange to correspond. 

## Possible Solution
My suggestion for fixing this is to allow the user to select custom color sequences for each widget (or maybe choose from a bunch of predefined color sequences if you prefer) so that the pie chart that represents errors could be reds and pinks and the pie chart that represents successful or info logs could be greens and blues. It would be awesome to make a histogram that is about errors a different color (preferably red) from the color of a histogram representing successful behaviors.

## Context
Allowing color customization would really enhance the control we have over how the user reads our data, allowing us to deliver information faster than the user could even read the titles on the widgets. The ability to distinguish between different graphs (and just to provide variety) would greatly enhance the appearance and usability of Graylog Dashboards for us.

* Graylog Version: 2.2
* Browser version: Firefox Quantum 59

**Comment by dennisoelkers** [comment]
@ruby-is-pretty-cool: This has been implemented recently in the [Views](https://www.graylog.org/features/views) feature which is part of Enterprise, but will also be part of the OSS core sooner or later. Thanks for your input!
