### ISSUE TITLE
netflow: weird graph value

### ISSUE THREAD

**Issue by huegelc** [Graylog2/graylog2-server#4777]
The netflow plugin dispalys the nf_bytes (sum) values above 1000M as `1B`
![grafik](https://user-images.githubusercontent.com/6955465/39705968-32d147c2-5210-11e8-9760-5ddc0b977fba.png)

## Expected Behavior

Should be 1G, 1.5G etc

## Your Environment

* Graylog Version: Graylog 2.4.3+2c41897 
* Elasticsearch Version: 
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@huegelc The graphs used in Graylog 2.4.x don't know anything about SI prefixes (https://en.wikipedia.org/wiki/Metric_prefix).

Instead, they counts in base 10.
The 'M' stands for million and the 'B' stands for billion. The next "unit" would be 'T' for trillion.
