### ISSUE TITLE
Uninstalling content packs

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#4780]
When uninstalling a specific instance of a content pack, Graylog needs to do the following things:

* [ ] Show entities marked for removal and ask user for confirmation
* [x] Resolve dependency order of the previously created entities
* [x] Stop/pause entities in reverse order
  * In case of error: Ignore, log error message (or create system notification), and continue
* [x] Remove entities in reverse order
  * In case of error: Ignore, log error message (or create system notification), and continue
* [x] Remove content pack snapshot

**Comment by bernd** [comment]
Closing this. The last open task has a separate issue already: https://github.com/Graylog2/graylog2-server/issues/5111
