### ISSUE TITLE
Deleting content packs

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#4781]
When deleting a version a content pack, Graylog needs to do the following things:

* Show snapshots created from this content pack and ask user for confirmation
  * Ask user if content pack instances should be uninstalled
* If instances should be uninstalled: Uninstall all instances of the content pack version (see #4780)
* Delete all snapshots based on the version of the content pack
* Delete version of the content pack

**Comment by bernd** [comment]
This is done.
