### ISSUE TITLE
set start page for user/group/role as admin

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#4785]
## Expected Behavior

As Administrator you should have the option to set a default start page for a user/group/role. This might be a dashboard or a stream. 

## Current Behavior

Only the user is able to set his start page, as Administrator you can not set that as default.

## Context

When working in bigger environments, having multiple roles/user/groups or a hudge number of people in one group it should be possible to set the default start page for them as Administrator.

## Your Environment

* Graylog Version: 2.4.4

**Comment by bernd** [comment]
This will be fixed once https://github.com/Graylog2/graylog2-server/pull/9444 has been merged.
