### ISSUE TITLE
Duplicate alerts after changing Graylog's alert scan from 1 minute to 30 seconds

### ISSUE THREAD

**Issue by gg-do** [Graylog2/graylog2-server#4797]
This is related to bug #4577 - Missing alerts with condition "more than 0 message in 1 min" when Graylog is high loaded. Our dev decided after posting that bug to change the alert_check_interval from 60s to 30s to resolve. Unfortuntaely, this has unexpected consequences. 

## Expected Behavior
We have a stream with a condition "message count: more than 0 message in 1 min" + "graylog alert scan = 30s". We expect to get one email with all alerts.

## Current Behavior
We believe the problem is related with the message receive time and elasticsearch index time are different. Initially we noticed that Graylog appears to have a "bubble" of time that is missed between scans. We posted here and someone suggested changing the alert time from 60->30s, which made sense at the time. Unfortuantely, since then we've realized that we get double alerts on busy stream. It appears (to me) that Since we scan every 30s, but look back 60s some alerts are ending up triggering twice, so they're in 2 different alert buckets.

Example from this morning:
Alert #1, recieved at 09:21am: Alert Description: Stream had 4 messages in the last 1 minutes with trigger condition more than 0 messages. (Current grace time: 0 minutes)
2018-05-17T14:20:38.109Z|Severity: 3|Logger: FIX.SessionMgr|Instrument for GBUN8 C1385 is not found! (+3 other error)

Alert #2, recived at 09:22am: Alert Description: Stream had 1 messages in the last 1 minutes with trigger condition more than 0 messages. (Current grace time: 0 minutes)
2018-05-17T14:20:38.109Z|Severity: 3|Logger: FIX.SessionMgr|Instrument for GBUN8 C1385 is not found!

As you can see both alerts have the same time stamps, but are creating 2 separate email alerts due to this bundling. 

## Possible Solution
I initially thought changing the grace period to 1minute and the time frame to look back to "2mins" but that appeared to miss emails when under significant stress, so I think maybe I don't have the best solution in mind for this.

## Steps to Reproduce (for bugs)
1. Create a few streams with one with conditions "message count: more than 0 message in 1 min" and scan time =30s
2. Overwhelm Graylog by sending messages to those stream.
3. Check email for alerts. You will see alerts 1 minute a part. Check each alert. usually the last alert on the 1st email is the first alert on the 2nd email.

## Context
Creating extra noise with these alerts tends to make people tune out these alerts more than they should. We'd prefer to only have them trigger once with all the alerts contained within it like it was doing before the alert scan time change.

## Your Environment

* Graylog Version: 2.2.3
* Elasticsearch Version: 2.4.0
* MongoDB Version: 3.4.2
* Operating System: CentOS 6
* Browser version:

**Comment by joschi** [comment]
@gg-do The issue you're describing is a direct consequence of how alerts are working in Graylog (i. e. scheduled searches).

In this case, everything is working as intended. If your alert scan interval is lower than the time range you've configured in your alert conditions, messages within that time range will trigger multiple (consecutive) alarms.

This being said, you might want to keep an eye on #4772.
