### ISSUE TITLE
[Plugin Request] JSON Webhook Notification Alert

### ISSUE THREAD

**Issue by adam-birds-hwt** [Graylog2/graylog2-server#4802]
It would be great to be able to just have a notification plugin that supports just a simple JSON formatted message to any webhook.

This way alerts can be customized to pretty much anything that supports incoming webhooks, such as Slack, Zulip and many more.

**Comment by joschi** [comment]
@adam-birds-hwt The HTTP alert notification does exactly that:
http://docs.graylog.org/en/2.4/pages/streams/alerts.html#http-alert-notification

**Comment by adambirds** [comment]
@joschi 
I think the instructions on that plugin documentation are wrong. I first ran the following command:
`git clone git@github.com:Graylog2/graylog-project.git`
I then tried running the following:
`scripts/bootstrap`
But the scripts directory didn't exist within the graylog-project folder.

So I then followed the instructions at https://github.com/Graylog2/graylog-project, I am at the bit, where I am ready to import to my IDE however I'm unsure which folder I'm meant to import, either the `graylog-project` or the `graylog-project-repos` folder. And I'm unsure where the skeleton plugin project is.

Can you advise?
