### ISSUE TITLE
Elasticsearch credentials are printed in startup log

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#4804]
When starting Graylog, the full URI to all Elasticsearch servers in the pool is printed and it includes the authentication credentials.

> [AbstractJestClient] Setting server pool to a list of 1 servers: [http://johndoe:secret@127.0.0.1:9200]

Authentication credentials should never be printed anywhere.

**Comment by joschi** [comment]
Refs searchbox-io/Jest#592
