### ISSUE TITLE
Weird HAProxy connection to nodes in cluster

### ISSUE THREAD

**Issue by huegelc** [Graylog2/graylog2-server#4807]
We have a graylog cluster setup working ( 3x 4vCPU 16GB RAM) behind HAProxy. On the proxy side, we balance (roundrobin) incoming syslog messages (forwarded) from one centralized syslog-ng server. 
## Expected Behavior

All three nodes should handle the same amount of messages
## Current Behavior

However, on the /system/nodes site I see that (most) of the connections go to only one node. While this node handles aprox. 4000msg/s the other two idle.
The HAProxy config is pretty straight forward.

## Your Environment

* Graylog Version: Graylog 2.4.4+4659dbe
* Elasticsearch Version: graylog centos repo
* MongoDB Version: graylog centos repo
* Operating System: Centos7
* Browser version:FF

**Comment by joschi** [comment]
@huegelc Please post the complete configuration of all involved components (HAProxy, Graylog, Graylog inputs, clients).

**Comment by joschi** [comment]
> The only way I can explain this, is that the syslog-ng server forwards all messages through one connection.

That's the default behavior when using Syslog over TCP. It usually doesn't make sense to open and close a full-fledged TCP (or even TCP+TLS) connection for each message.

If you want to send each message to a different Graylog node, you might want to use Syslog+UDP instead.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
