### ISSUE TITLE
event_data_param5 mapper_parsing_exception

### ISSUE THREAD

**Issue by rogermartensson** [Graylog2/graylog2-server#4810]
## Expected Behavior
No warning or indexer failure message.

## Current Behavior
I get mapper_parsing_exception on a parameter I guess comes from Windows Event Log.
(winlogbeat installed using graylog-collectory 0.1.5)

2018-05-28T14:36:18.235+02:00 WARN  [Messages] Failed to index message: index=<system_logs_0002_217> id=<8c6b3f45-6273-11e8-a844-005056af15be> error=<{"type":"mapper_parsing_exception","reason":"failed to parse [event_data_param5]","caused_by":{"type":"illegal_argument_exception","reason":"Invalid format: \"-\""}}>

## Your Environment
* Graylog Version: 2.4.4 
* Elasticsearch Version: 5.6.9
* MongoDB Version:
* Operating System: Ubuntu 16.04 
* Browser version:

**Comment by joschi** [comment]
@rogermartensson Thanks for reporting this!

You'll have to create a custom index mapping for the "event_data_param5" field (and ideally any field with varying "types").

Please refer to http://docs.graylog.org/en/2.4/pages/configuration/elasticsearch.html#custom-index-mappings for more details.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
