### ISSUE TITLE
Absolute Time Range Selector does not contain buttons to insert current time anymore

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#4815]
## Expected Behavior

RIght next to the 'to' and 'from' inputs in the absolute time range selector of the search bar used to be buttons inserting the current time and date into the input.

## Current Behavior

Those buttons are missing. Gone. Just not there.

## Possible Solution

It might be due to a `react-bootstrap` update in 2017.

## Steps to Reproduce (for bugs)

1. Go to "Search"
2. Select "Absolute" time range.
3. Look for buttons next to the 'from'/'to' inputs showing a magic wand.
4. Find nothing.

## Your Environment

* Graylog Version: 2.4.5
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
As far as I can see, the button has been missing since Graylog 2.3.0.

This being said, do we really need it if nobody complained about it or even realized it was missing for almost one year?
