### ISSUE TITLE
MessageInput should be able to terminate itself

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#482]
For inputs that do not run continuously, or inputs that have a natural "end of data" condition, it would be helpful if an input had a way of signalling that it stopped without an error.

This could either be done with a specific lifecycle state or a "backchannel" to its host.
The lifecycle state probably is the cleaner way.

**Comment by florianvolle** [comment]
Closing this as we currently do not see the usecase. Please reopen if you have additional input.
