### ISSUE TITLE
Save search result - not easy

### ISSUE THREAD

**Issue by hans-mayer** [Graylog2/graylog2-server#4822]
Dear All,

Recently I upgraded to 2.4.5+8e18e6a
Now it’s a little bit tricky to save a search result. Once you selected a saved searched criteria the “Save Search Criteria” button disappears. It is replaced by a “Saved search” button (only with update and delete possibility), even if the search string was modified. The only way to save a new criteria is to copy the search string, press the “Search” button in the top menu and paste the string into the search field. Now you can save this criteria as a new item.

Would be nice if this handling could be made easier.

I posted this in the community board and I was ask to post it it here as a bug report. Actually it is not really a bug. It's more a feature request  but it would be nice to solve this issue. 

Kind regards
Hans

* Graylog Version: 2.4.5+8e18e6a, codename Wildwuchs
* Elasticsearch Version: I do not know how to query the version 
* MongoDB Version: db version v3.4.9
* Operating System: Linux graylog 4.4.0-97-generic #120~14.04.1-Ubuntu SMP Wed Sep 20 15:53:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Browser version: Chrome 67

**Comment by joschi** [comment]
Refs #4744
Refs #2285

**Comment by joschi** [comment]
@edmundoa @dennisoelkers Could you please take a look at this issue?

**Comment by edmundoa** [comment]
As @joschi pointed out, this change of behaviour is caused by the fix for #2285. Without reworking how the UI for saved searches work, I can't see a way of fixing this and #2285 at the same time.
