### ISSUE TITLE
sflow support for flows

### ISSUE THREAD

**Issue by zapotah** [Graylog2/graylog2-server#4825]
## Reason for request
Most Juniper devices to this date offer sflow instead of netflow or IPFIX. Since the netflow plugin was integrated into graylog-server, the issue about incorporating sflow was lost into the sands of time. Sflow support would be a big step forwards for flow-analytics on graylog.

**Comment by joschi** [comment]
Duplicate of Graylog2/graylog-plugin-netflow#3
