### ISSUE TITLE
Smaller issues and tasks for the new sidecar & collectors implementation

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#4828]
This ticket tracks some problems that have been found during the review of https://github.com/Graylog2/graylog2-server/pull/4818. 

---

There seems to be a styling issue with the dropdown menu when selecting a collector for a configuration:

![image](https://user-images.githubusercontent.com/461/41051260-dc2b52ba-69b5-11e8-8827-e0f38b59fa80.png)

Being done as part of #4826 

---

When filtering for a specific configuration, the user can clear the selection to show all configurations again. The "clear selection" disappears if the user selects one collector/backend in the list while a configuration selection is active. (it's the same for other filter options like "collector")

![peek 2018-06-06 18-44](https://user-images.githubusercontent.com/461/41052653-b369b9b2-69b9-11e8-916f-92807d9335eb.gif)

✅ 
---

There is an issue when the sidecar configuration setting `send_status` is `false`. Some parts of the system cannot handle this.

Rendering a configuration doesn't work:

```
2018-06-06 19:07:32,010 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.NullPointerException: null
	at org.graylog.plugins.sidecar.services.ConfigurationService.renderConfigurationForCollector(ConfigurationService.java:128) ~[classes/:?]
	at org.graylog.plugins.sidecar.rest.resources.ConfigurationResource.renderConfiguration(ConfigurationResource.java:180) ~[classes/:?]
```

The sidecar details page doesn't render and fails with:

```
warning.js:33 Warning: Failed prop type: The prop `status` is marked as required in `StatusIndicator`, but its value is `null`.
```

```
bluebird.js:1486 Unhandled rejection TypeError: Cannot read property 'cpu_idle' of null
    at Object.formatNodeDetails (webpack:///./src/components/sidecars/sidecars/SidecarStatus.jsx?:87:51)
    at Object.render (webpack:///./src/components/sidecars/sidecars/SidecarStatus.jsx?:191:16)
```

✅ 
---

## Notes & Suggestions

- When first using the pre-defined filters on the "Administration" page, I expected the "Reset" button next to the "Find" button to reset the pre-defined filters as well. Maybe it makes sense to implement that. ✅ 
- It is currently hard to see which pre-defined filter is active. Maybe we can indicate this somehow. (e.g. bold font, marker icon/character) ✅ 
- ~~Pressing "Update" on the collector configuration page shows a user notification on success but doesn't redirect to the configuration overview. The user has to press the "Back" button for that.~~ See https://github.com/Graylog2/graylog2-server/issues/4828#issuecomment-395739250
- A sidecar configuration requires a `api_token` setting so the sidecar is able to authenticate against the Graylog API. Currently, a user has to navigate to "System / Authentication -> Select a user -> More Actions -> Edit tokens" to create a new access token.
  - How about adding the token management for the built-in sidecar user to the sidecar pages as well so it's easier to find? ✅

**Comment by edmundoa** [comment]
The behaviour in

> Pressing "Update" on the collector configuration page shows a user notification on success but doesn't redirect to the configuration overview. The user has to press the "Back" button for that.

is intended. Writing the configuration is more like editing some document than filling a form, so keeping the same site while editing seems to make sense in this case. People can test how the configuration works in the collectors that use them, and adjust it without having to go back and forth.

**Comment by edmundoa** [comment]
@bernd on my side, all issues listed here have a fix in the branch. Do you have anything else to add?

**Comment by edmundoa** [comment]
I also added changes to ensure we display the right totals in the configuration page, not the ones given by the pagination information.
