### ISSUE TITLE
Graylog Widget Description

### ISSUE THREAD

**Issue by nickusor** [Graylog2/graylog2-server#4831]
## Current Behavior
![image](https://user-images.githubusercontent.com/40067208/41167656-4159aaf0-6b4c-11e8-9e34-7879095637d3.png)

I just want to ask what means that "in 3 hours".

## Your Environment

It doesn't appear on every graylog server that I manage.
I have to say that if now shows "in 3 hours", after 1 hour it will still show "in 3 hours".

* Graylog Version: 2.4
* Operating System: Virtual Machine - Ubuntu
* Browser version: Google Chrome - Version  66.0.3359.181

If you need more informations, please ask!
Thank you.

**Comment by dennisoelkers** [comment]
This is supposed to show the time the widget was updated. What timezone are you on?

**Comment by nickusor** [comment]
My timezone is +2 GMT Bucharest/Romania

**Comment by dennisoelkers** [comment]
What is the timezone that is configured for your user? What time is it on the server your Graylog is running on? When you hover over the `in 3 hours` element with your mouse, what is the exact timestamp you see? What is your local time at this point?

**Comment by dennisoelkers** [comment]
Oh, and: Can you go go `System` -> `Overview` and tell me what is shown in the `Time configuration` box?

**Comment by nickusor** [comment]
Here is my time configuration
![image](https://user-images.githubusercontent.com/40067208/41228116-de0a0504-6d7f-11e8-9972-efcf11cfb307.png)

I have to say that I see "in 3 hours" even now, with sysdate timestamp when I hover my mouse over

**Comment by bernd** [comment]
The new search system doesn't show this value anymore so I am closing the issue.
