### ISSUE TITLE
Search: "Results retrieved at XX-XX-XX xx:xx:xx" does not update properly 

### ISSUE THREAD

**Issue by tryptych** [Graylog2/graylog2-server#4835]
Minor issue:

When you are updating your search results automatically every 1 second (or 5, or 10) and getting no results, or the same results, there is no way to tell if the search is actually doing anything and refreshing the screen properly. The GUI incorrectly states this on the top left side of the screen:

**Search result
Found 0 messages in 11 ms, searched in 44 indices.
Results retrieved at 2018-06-11 10:09:19.**

Each time it updates, it incorrectly prints the same thing and the time/date stamp is not updated.  This date/time stamp should be updated each time the search refreshes; it should be easier to tell that the screen is refreshing.

**Comment by coffee-squirrel** [comment]
This is still an issue under 3.1.2.

**Comment by bernd** [comment]
Closing this issue because the old search has been removed and it's shown correctly in the new search.
