### ISSUE TITLE
 Top Item missing in Dashboard 

### ISSUE THREAD

**Issue by 123dev** [Graylog2/graylog2-server#4836]
Graylog 2.4.1+0f97411
We have a stacked query which shows up properly in the search screen.
![image](https://user-images.githubusercontent.com/13109154/41241852-020d7152-6d6c-11e8-8c4c-b19cd3bde024.png)

When we add it to a dashboard, the top item is missing.
![image](https://user-images.githubusercontent.com/13109154/41241876-1085485e-6d6c-11e8-86de-ebff830101c6.png)

Also, the query is customized to show 200 items (all Top values), yet in the dashboard we see 4 top values (I assume it’s trying to show top 5 default, with one missing)

We first reported it [here](https://community.graylog.org/t/top-item-missing-in-dashboard/5550) and were advised to create a bug report.

Thanks

## Expected Behavior
- Top Item to be visbile
- Top Values count to reflect the search customization

## Steps to Reproduce (for bugs)
Add a stack query to a dashboard.
Note, there is a one to one match for the quick values field selected with the stacked field.
It represents
- Error Code
- Error Code Description

## Your Environment
* Graylog Version: 2.4.1+0f97411
* Elasticsearch Version: 5.6.3
* MongoDB Version: 3.4.9
* Operating System: Linux Debian jessie/sid ( 3.13.0-147-generic x86_64)
* Browser version: Chrome 66.0.3359.181 64 bit

**Comment by edmundoa** [comment]
Would you be so kind as to share the widget configuration (you can do a screenshot of what you see when you click in the info button on the bottom right corner of the widget), and also any errors that you see in your browser's console and Graylog server logs?

Thank you!

**Comment by 123dev** [comment]
Sure,
![image](https://user-images.githubusercontent.com/13109154/41300680-575e9366-6e34-11e8-9c21-8a02475f1a3a.png)

I don't see any errors (now) in Graylog, should I remove and re-add to dashboard tosee if I get any errors?
At no point I do see errors in the browser.

An interesting note:
If I select time period of 1 day, I see all entries including the top most (top 5 values instead of top 200)
7 day or 30 day time period and the top entry is missing, (top 4 values)

Thanks
