### ISSUE TITLE
I deleted graylog_deflector, can I rebuild or recreate it ?

### ISSUE THREAD

**Issue by creamJelly** [Graylog2/graylog2-server#4844]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I want to add a es node, I did something wrong. I got a notification "Deflector exists as an index and is not an alias". I followed the suggestion to delete graylog_deflector.
 I had 5 indexs before I did it, a graylog_deflector and graylog_0 to 3. Now I only have graylog_0 to 3.
What will happed after I delete if? Graylog will work as normal? I don't  know if I need to rebuild or create a index named "graylog_deflector". What shuold I do?
I'm sorry, my english is really bad. 

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by joschi** [comment]
@creamJelly The index alias will be recreated on the next rotation. You can manually rotate the write-active index on the System/Indices/Index set page with the Maintenance button.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by jalogisch** [comment]
he @creamJelly 

I think you refer to http://docs.graylog.org/en/2.4/pages/faq.html#how-do-i-fix-the-deflector-exists-as-an-index-and-is-not-an-alias-error-message 

The deflector will be recreated on Graylog start and connect to the Elasticsearch Cluster as alias.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
