### ISSUE TITLE
Message Count Alert Condition x 2

### ISSUE THREAD

**Issue by GTownson** [Graylog2/graylog2-server#4847]
On the alert condition drop down there are two identical listing for "Message Count Alert Condition"

## Current Behavior

![image](https://user-images.githubusercontent.com/28807776/41532076-6eca3e3e-72ed-11e8-960d-b9ea5f2e4b8f.png)

## Steps to Reproduce (for bugs)
1. Browse to the alert condition page
2. Select a stream
3. Click the alert condition dropdown 

## Your Environment
* Graylog Version: 2.4.4
* Elasticsearch Version: 5.6
* Operating System: Ubuntu 16.04 LTS

**Comment by joschi** [comment]
@GTownson Make sure to clear your browser cache and the cache of any transparent caching proxies between your browser and the Graylog web interface.

**Comment by GTownson** [comment]
@joschi I tried this and still see the two 'Message Count Condition' options.

**Comment by joschi** [comment]
@GTownson What's the output of the following cURL commands?
```text
# curl -u admin:password 'http://graylog.example.com/api/alerts/conditions/types?pretty=true'
# curl -u admin:password 'http://graylog.example.com/api/alerts/conditions?pretty=true'
```

**Comment by GTownson** [comment]
@joschi Please see below for the outputs of those commands. I also tried creating alert conditions for both message count condition options and have included a screenshot from the web interface below. 

`{
  "field_content_value" : {
    "type" : "field_content_value",
    "name" : "Field Content Alert Condition",
    "human_name" : "This condition is triggered when the content of messages is equal to a defined value.",
    "requested_configuration" : {
      "field" : {
        "human_name" : "Field",
        "additional_info" : { },
        "description" : "Field name that should be checked",
        "default_value" : "",
        "attributes" : [ ],
        "type" : "text",
        "is_optional" : false
      },
      "value" : {
        "human_name" : "Value",
        "additional_info" : { },
        "description" : "Value that the field should be checked against",
        "default_value" : "",
        "attributes" : [ ],
        "type" : "text",
        "is_optional" : false
      },
      "grace" : {
        "human_name" : "Grace Period",
        "additional_info" : { },
        "description" : "Number of minutes to wait after an alert is resolved, to trigger another alert",
        "default_value" : 0,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "backlog" : {
        "human_name" : "Message Backlog",
        "additional_info" : { },
        "description" : "The number of messages to be included in alert notifications",
        "default_value" : 0,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "repeat_notifications" : {
        "human_name" : "Repeat notifications",
        "additional_info" : { },
        "description" : "Check this box to send notifications every time the alert condition is evaluated and satisfied regardless of its state.",
        "default_value" : false,
        "attributes" : [ ],
        "type" : "boolean",
        "is_optional" : true
      }
    },
    "link_to_docs" : "https://www.graylog.org/"
  },
  "field_value" : {
    "type" : "field_value",
    "name" : "Field Aggregation Alert Condition",
    "human_name" : "This condition is triggered when the aggregated value of a field is higher/lower than a defined threshold for a given time range.",
    "requested_configuration" : {
      "field" : {
        "human_name" : "Field",
        "additional_info" : { },
        "description" : "Field name that should be checked",
        "default_value" : "",
        "attributes" : [ ],
		 "type" : "text",
        "is_optional" : false
      },
      "time" : {
        "human_name" : "Time Range",
        "additional_info" : { },
        "description" : "Evaluate the condition for all messages received in the given number of minutes",
        "default_value" : 5,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "threshold_type" : {
        "human_name" : "Threshold Type",
        "additional_info" : {
          "values" : {
            "LOWER" : "lower",
            "HIGHER" : "higher"
          }
        },
        "description" : "Select condition to trigger alert: when value is higher or lower than the threshold",
        "default_value" : "HIGHER",
        "attributes" : [ ],
        "type" : "dropdown",
        "is_optional" : false
      },
      "threshold" : {
        "human_name" : "Threshold",
        "additional_info" : { },
        "description" : "Value which triggers an alert if crossed",
        "default_value" : 0.0,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "type" : {
        "human_name" : "Aggregation Type",
        "additional_info" : {
          "values" : {
            "MEAN" : "mean value",
            "STDDEV" : "standard deviation",
            "MIN" : "min value",
            "MAX" : "max value",
            "SUM" : "sum"
          }
        },
        "description" : "Select statistical function to use in the aggregation",
        "default_value" : "MAX",
        "attributes" : [ ],
        "type" : "dropdown",
        "is_optional" : false
      },
      "grace" : {
        "human_name" : "Grace Period",
        "additional_info" : { },
        "description" : "Number of minutes to wait after an alert is resolved, to trigger another alert",
        "default_value" : 0,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "backlog" : {
        "human_name" : "Message Backlog",
        "additional_info" : { },
        "description" : "The number of messages to be included in alert notifications",
"default_value" : 0,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "repeat_notifications" : {
        "human_name" : "Repeat notifications",
        "additional_info" : { },
        "description" : "Check this box to send notifications every time the alert condition is evaluated and satisfied regardless of its state.",
        "default_value" : false,
        "attributes" : [ ],
        "type" : "boolean",
        "is_optional" : true
      }
    },
    "link_to_docs" : "https://www.graylog.org/"
  },
  "Aggregates Alert" : {
    "type" : "Aggregates Alert",
    "name" : "Message Count Alert Condition",
    "human_name" : "This condition is triggered when the number of messages is higher/lower than a defined threshold in a given time range.",
    "requested_configuration" : {
      "time" : {
        "human_name" : "Time Range",
        "additional_info" : { },
        "description" : "Evaluate the condition for all messages received in the given number of minutes",
        "default_value" : 5,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "threshold_type" : {
        "human_name" : "Threshold Type",
        "additional_info" : {
          "values" : {
            "MORE" : "more than",
            "LESS" : "less than"
          }
        },
        "description" : "Select condition to trigger alert: when there are more or less messages than the threshold",
        "default_value" : "MORE",
        "attributes" : [ ],
        "type" : "dropdown",
        "is_optional" : false
      },
      "threshold" : {
        "human_name" : "Threshold",
        "additional_info" : { },
        "description" : "Value which triggers an alert if crossed",
        "default_value" : 0.0,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "grace" : {
        "human_name" : "Grace Period",
        "additional_info" : { },
        "description" : "Number of minutes to wait after an alert is resolved, to trigger another alert",
        "default_value" : 0,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
},
      "backlog" : {
        "human_name" : "Message Backlog",
        "additional_info" : { },
        "description" : "The number of messages to be included in alert notifications",
        "default_value" : 0,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "repeat_notifications" : {
        "human_name" : "Repeat notifications",
        "additional_info" : { },
        "description" : "Check this box to send notifications every time the alert condition is evaluated and satisfied regardless of its state.",
        "default_value" : false,
        "attributes" : [ ],
        "type" : "boolean",
        "is_optional" : true
      }
    },
    "link_to_docs" : "https://www.graylog.org/"
  },
  "message_count" : {
    "type" : "message_count",
    "name" : "Message Count Alert Condition",
    "human_name" : "This condition is triggered when the number of messages is higher/lower than a defined threshold in a given time range.",
    "requested_configuration" : {
      "time" : {
        "human_name" : "Time Range",
        "additional_info" : { },
        "description" : "Evaluate the condition for all messages received in the given number of minutes",
        "default_value" : 5,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "threshold_type" : {
        "human_name" : "Threshold Type",
        "additional_info" : {
          "values" : {
            "MORE" : "more than",
            "LESS" : "less than"
          }
        },
        "description" : "Select condition to trigger alert: when there are more or less messages than the threshold",
        "default_value" : "MORE",
        "attributes" : [ ],
        "type" : "dropdown",
        "is_optional" : false
      },
      "threshold" : {
        "human_name" : "Threshold",
        "additional_info" : { },
        "description" : "Value which triggers an alert if crossed",
        "default_value" : 0.0,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "grace" : {
        "human_name" : "Grace Period",
        "additional_info" : { },
        "description" : "Number of minutes to wait after an alert is resolved, to trigger another alert",
        "default_value" : 0,
 "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "backlog" : {
        "human_name" : "Message Backlog",
        "additional_info" : { },
        "description" : "The number of messages to be included in alert notifications",
        "default_value" : 0,
        "attributes" : [ ],
        "type" : "number",
        "is_optional" : false
      },
      "repeat_notifications" : {
        "human_name" : "Repeat notifications",
        "additional_info" : { },
        "description" : "Check this box to send notifications every time the alert condition is evaluated and satisfied regardless of its state.",
        "default_value" : false,
        "attributes" : [ ],
        "type" : "boolean",
        "is_optional" : true
      }
    },
    "link_to_docs" : "https://www.graylog.org/"
  }
}`

`{
  "total" : 2,
  "conditions" : [ {
    "id" : "be8a8416-4354-4d77-99bf-29fc2d804538",
    "type" : "message_count",
    "creator_user_id" : "Admin",
    "created_at" : "2018-06-21T12:24:49.899+0000",
    "parameters" : {
      "backlog" : 1,
      "repeat_notifications" : false,
      "grace" : 0,
      "threshold_type" : "MORE",
      "threshold" : 1,
      "time" : 1
    },
    "in_grace" : false,
    "title" : "Account Creation"
  }, {
    "id" : "9cc60d60-2224-494d-a4e5-8b50ae285e19",
    "type" : "Aggregates Alert",
    "creator_user_id" : "Admin",
    "created_at" : "2018-06-21T12:26:25.827+0000",
    "parameters" : {
      "backlog" : 1,
      "repeat_notifications" : false,
      "grace" : 0,
      "threshold_type" : "MORE",
      "threshold" : 1,
      "time" : 5
    },
    "in_grace" : false,
    "title" : "User Account Created"
  } ]
}`

![image](https://user-images.githubusercontent.com/28807776/41726143-6e9e63c6-7569-11e8-833a-b4a9116d6bdd.png)

**Comment by dennisoelkers** [comment]
@GTownson: Is this still an issue on Graylog 3.3.x?

**Comment by bernd** [comment]
Closing this because the old alerting system has been replaced with events and alerts.
