### ISSUE TITLE
Alert Callbacks Associated with Alert Conditions

### ISSUE THREAD

**Issue by GTownson** [Graylog2/graylog2-server#4852]
## Expected Behavior
I believe it would be useful to be able to associate an alert callback with an individual condition instead of a stream.

## Current Behavior
 I was going to create a few different alerts on the All Messages stream however each of these alerts require a different email body in the email callback and therefore I had to create an individual stream for each alert.

## Possible Solution
We should be able to associate an alert callback with either a stream or with an individual alert condition, to make alerting more flexible.

## Context
I have had to create a stream for each alert condition as to be able to create separate alert condition.

* Graylog Version: 2.4.4
* Elasticsearch Version: 5.6.9

**Comment by joschi** [comment]
Duplicate of #3180.
