### ISSUE TITLE
Add permission check for ClusterDeflector cycle actions?

### ISSUE THREAD

**Issue by 1Jesper1** [Graylog2/graylog2-server#4857]
https://github.com/Graylog2/graylog2-server/blob/365d26fff714cf37b360d09a337b3138437f663a/graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterDeflectorResource.java#L47

**Comment by dennisoelkers** [comment]
Thank you for opening this issue!

While this might look like we do no permission check there, the permission check is actually happening implicitly [in a different place](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/rest/resources/system/DeflectorResource.java#L111). The `ClusterDeflectorResource` is forwarding requests to the master node (even if it is the master node itself), triggering the corresponding methods of the `DeflectorResource` there, which do the required permission checks.

**Comment by 1Jesper1** [comment]
Thanks for the explanation!
