### ISSUE TITLE
Check for RestPermissions.LOOKUP_TABLES_READ

### ISSUE THREAD

**Issue by 1Jesper1** [Graylog2/graylog2-server#4861]
https://github.com/Graylog2/graylog2-server/blob/365d26fff714cf37b360d09a337b3138437f663a/graylog2-server/src/main/java/org/graylog2/rest/resources/tools/LookupTableTesterResource.java#L63

**Comment by dennisoelkers** [comment]
Can you elaborate a bit why this check would be necessary? The resource in question is a stub for tests.

**Comment by 1Jesper1** [comment]
Ah, thought the (live) service was used, so the permission check is needed as it's also used at https://github.com/Graylog2/graylog2-server/blob/c463959b9e316a9ca6b2a3f73767703f889033cf/graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java#L208

**Comment by bernd** [comment]
@1Jesper1 Thank you! The check is indeed missing here. This resource is used when editing a lookup table extractor.
