### ISSUE TITLE
Place requireauthentication above class instead of above api methods

### ISSUE THREAD

**Issue by 1Jesper1** [Graylog2/graylog2-server#4862]
https://github.com/Graylog2/graylog2-server/blob/348b984021e9561cdccdd508fc4fe7956d53d2bd/graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ActionResource.java#L70

**Comment by dennisoelkers** [comment]
While this has no impact, it should be done to prevent future methods of the class having to repeat the annotation all over (and bearing the risk that it is forgotten).
