### ISSUE TITLE
Login page route for plugins

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [Graylog2/graylog2-server#4864]
Add route to login page for plugins.

## Expected Behavior
Plugins should be able to inject components to login page HTML. This would allow SSO-login links.

## Current Behavior
Plugins can't inject components to login page HTML.

## Possible Solution
Add route for login page.

## Context
We integrating our [Crowd SSO  to Graylog](https://github.com/NatLibFi/graylog-plugin-auth-crowd-sso).

**Comment by florianvolle** [comment]
I am closing this for now. Please double check if Crowd SSO supports a less intrusive way. E.g. using an Nginx proxy.
