### ISSUE TITLE
Re-enabled streams don't reliably re-enable alerts

### ISSUE THREAD

**Issue by hpetersFC** [Graylog2/graylog2-server#4866]
I found that re-enabling a previously paused stream doesn't reliably re-enable the associated alert. 

## Steps to Reproduce (for bugs)
- Have a working stream/alert/notification setup
- Pause the stream
- Re-enable the stream
- Modify the alert conditions if necessary to fulfil the condition

## Expected Behavior
- Alert fires

## Current Behavior
- Alert does not fire (or in one case, fired half an hour later, even though the condition was set for a time period of 5 minutes)

## Context
That's dangerous behaviour: We might think we have re-enabled a certain stream, but an alert would never fire off.
The workaround of creating the alert from scratch is inconvenient and time-consuming, esp on the less than ideal UI that GL2 has introduced for the whole stream/alert/notification setup.

We are using GL as part of a managed services offering - and our infrastructure folk have advised me that they don't believe it's an issue with either the infrastructure or the configuration of Graylog and is more likely a bug with the code. 

Graylog version - 2.4.3
Elasticsearch version - 5.5
Mongo version - 2.6.12
OS -  Ubuntu 16.04.4

**Comment by dennisoelkers** [comment]
Thank you for opening this issue, @hpetersFC!

A few questions to make for us to reproduce the issue:

1. What is the exact configuration of the alert condition that does not fire for a reenabled stream?
2. In which way do you need to modify the alert condition to make it work again?

**Comment by hpetersFC** [comment]
1. I have seen this with two alerts, and their alert conditions were:
- "Alert is triggered when there is more than one message in the last 6 minutes. Grace period: 60 minutes. Not including any messages in alert notification. Configured to repeat notifications."  This alert should have fired off after restarting it, but never did. 

- "Alert is triggered when there is less than one message in the last 10 minutes. Grace period: 60 minutes. Not including any messages in alert notification. Configured to repeat notifications."  For this alert I made it more sensitive by changing the threshold to "less than 1111 messages", then it should have fired off straight away. It did not fire off until half an hour later.

2. I haven't found a reliable way to make the alert condition work again. My current workaround is to create an entire new stream, alert, and notification from scratch with the exact same configuration as the old one - and those new ones work.

3. I am not sure. The "unresolved alerts" list doesn't make sense to me - I can see a couple of alert in there listed as "still ongoing" when I know the corresponding stream does not have any messages anymore. May be a problem unto itself.

**Comment by dennisoelkers** [comment]
Can you post the details of an erratic alert? There is an alert history which shows the timeline for alert checking which might be helpful.

**Comment by hpetersFC** [comment]
I have another incident which may give more clues:

- The stream/alert in question was not paused and re-enabled, so maybe that was a red herring.
- The Alert Timeline and Triggered Notification show the expected behaviour, i.e. around 22:45 when the incident occurred a notification appears to have been sent.
- In my email inbox, the email notification shows up with the right timestamp of 22:45 (although I can't tell when I actually received it)
- However, on Slack the alert notification doesn't show up until 23:10, so with a 25-minute delay. 


I guess it's possible that the Slack integration doesn't work flawlessly. 

But I would like to be able to rule out issues with the Graylog alerts themselves. 


_Optional Info_

Alert timeline
This is a timeline of events occurred during the alert, you can see more information about some events below.

2018-07-13 22:45:03.871
Graylog checks xxxx  no game verify solves (stage 1) (Message Count Alert Condition) condition on stream xxxx  no game verify solves (stage 1)
2018-07-13 22:45:03.871
Stream had 0 messages in the last 5 minutes with trigger condition less than 1 messages. (Current grace time: 60 minutes)
2018-07-13 22:45:03.871
Graylog triggers an alert for xxxx  no game verify solves (stage 1) (Message Count Alert Condition) and starts sending notifications
2018-07-13 22:45:04.249
Graylog sent xxxx  no game verify solves (stage 1) (Email Alert Callback) notification
2018-07-13 22:46:03.256
Condition is no longer satisfied, alert is marked as resolved

**Comment by bernd** [comment]
The alerting system has been rewritten for 3.2 and is not directly connected to streams anymore. So this issue shouldn't happen again. Please open a new issue if you can still see this with a recent Graylog version. Thank you!
