### ISSUE TITLE
gelf kafka plugin to use newer kafka consumer mechanism

### ISSUE THREAD

**Issue by nhamlh** [Graylog2/graylog2-server#4869]
gelf kafka plugin goes with graylog 2.4.4 still use the old connection mechanism which needs to connect to zookeeper servers.
## Expected Behavior

We should update the plugin to use newer mechanism which drops the information about zookeeper servers.

* Graylog Version: 2.4.4

**Comment by bernd** [comment]
@nhamlh We are working on this in https://github.com/Graylog2/graylog2-server/pull/4770. Please follow that PR for updates. Thank you!
