### ISSUE TITLE
Move generated collector config files into /var/lib/graylog-sidecar?

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#4887]
We are currently writing generated collector config files into the `/etc/graylog/sidecar/generated` directory.

I was wondering if we should write them into `/var/lib/graylog-sidecar/configurations` instead because `/etc` is usually used for static configuration files.

This would also remove the possibility to overwrite arbitrary system config files in `/etc/`.

TBD

**Comment by joschi** [comment]
I'm definitely for using `/var/lib/graylog-sidecar/configurations` (or a similar directory in `/var/lib/graylog-sidecar/`) for automatically generated files. :+1:

**Comment by bernd** [comment]
@mariussturm @mpfz0r @lennartkoopmann How do we want to continue with this? I still think it's a good idea to put the generated config files under something like `/var/lib/graylog-sidecar/configurations` and removing the option to configure the path in the UI.

As @lennartkoopmann said in #5051, there might be a use case for putting the files into arbitrary locations in the file system but I would like to default to the central location mentioned above, at least. And until we decide that, we can remove the option from the UI to avoid confusing users. The other way around (leaving it in for the preview and removing it later) will be harder.

What do you think?
