### ISSUE TITLE
Record Content Pack Import Timestamp

### ISSUE THREAD

**Issue by mustafaqasim** [Graylog2/graylog2-server#4896]
When we import a content pack multiple times for enhancement or fixing purposes, the imported content packs (CP) are listed in a radio list format and after you've uploaded a CP multiple time it becomes difficult to identify the different version.

## Expected Behavior

The imported content packs should be displayed in a tabular form with a timestamp column. The import timestamp will help us identify when we imported that particular CP.

## Current Behavior

Content packs are listed in a radio list form. See the attached screenshot. 

![image 055](https://user-images.githubusercontent.com/777303/42499223-9323d69c-8471-11e8-8c4e-e070f7340cc2.png)

## Possible Solution

Display imported content packs with more details including the timestamp of when it was imported. 

## Steps to Reproduce (for bugs)

1. Import a content pack
2. Import the same CP again (with or without any changes)
3. Import the same CP again multiple times throughout a Day/Week/Month/Year.

## Context
You can't talk like the following when working with content packs

"Hey, this change was introduced in the CP you imported on Jan 6, 2018 at 4:18 PM"
"Please revert to the CP I imported this morning."

## Your Environment

* Graylog Version: Graylog 2.4.3
* Elasticsearch Version: Version: 5.6.7, Build: 4669214/2018-01-25T21:14:50.776Z, JVM: 1.8.0_171
* MongoDB Version: v3.6.2
* Operating System: CentOS Linux release 7.5.1804 (Core)
* Browser version: Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by joschi** [comment]
@mustafaqasim Thanks for raising this issue.

The described functionality has been implemented for the next iteration of content packs which will be included in Graylog 3.0.0.
