### ISSUE TITLE
Percentiles for duration (numeric) fields

### ISSUE THREAD

**Issue by ronlut** [Graylog2/graylog2-server#4900]
I'm interested in creating a dashboard chart showing the 90/95/99 percentiles of our requests duration.
I have the request duration field available in my logs, but percentile options are missing in the "Generate chart" or the "Statistics" options.

## Expected Behavior
Ability to view / choose a percentile when generating a regular chart or statistics table.

## Current Behavior
Only `Total`, `Mean`, `Minimum`, `Maximum`, `Std. deviation`, `Variance`, `Sum`, `Cardinality` options are available.

## Possible Solution
Calculate percentile :)

## Context
I'm interested in creating a dashboard chart showing the 90/95/99 percentiles of our requests duration.

## Your Environment

* Graylog Version: 2.3.2-1
* Elasticsearch Version: 5.5.1
* MongoDB Version: 3.4
* Operating System: Ubuntu 16.04.4 LTS
* Browser version: Chrome 67.0.3396.99 64-bit

Thanks!

**Comment by Dougoc** [comment]
It's a great feature! No doubt will be of much help.

**Comment by jeremyjpj0916** [comment]
I see how to do this in the views page, but can we get this data on the /search/universal/*/stats API too 💯 ?
