### ISSUE TITLE
 4 indices with a total of 0 messages under management and not showing any message on search field

### ISSUE THREAD

**Issue by behalkarun** [Graylog2/graylog2-server#4907]
## Expected Behavior
Search should display Messages.

## Current Behavior
Input is shown as running but showing no messages in search and also indices create only 144B .

## Possible Solution
delete the index manually
delete the all journal file
Also run manually cycle deflector

## Steps to Reproduce (for bugs)
1) delete all messages in an index, keep the index
2) nothing see any coming message on search
3) delete index
4) delete indicies message

## Context
It looks like there are no Messages, but they are there but not displayed.
## Your Environment

* Graylog Version:1.3
* Elasticsearch Version:1.7.1
* MongoDB Version:3.00
* Operating System:CentOS 7
* Browser version: Chrome 67.0.3396.87

**Comment by joschi** [comment]
@behalkarun Please upgrade to the latest stable release of Graylog (which is Graylog 2.4.5 at the time of writing) and check, if the problem still exists.

**Comment by behalkarun** [comment]
below repo is not working that's why i am not able to upgarde


[graylog]
name=graylog
baseurl=https://packages.graylog2.org/repo/el/stable/2.4/$basearch/
gpgcheck=1
repo_gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-graylog

**Comment by behalkarun** [comment]
![image](https://user-images.githubusercontent.com/40602716/42691861-594cff54-86c7-11e8-9cec-13b255a3e3d5.png)
repo error see in attach

**Comment by joschi** [comment]
@behalkarun That's not how you use the URI. 🙄
For example, you haven't replaced the `$basearch` variable and even then, the URI wouldn't be complete.

Please follow the detailed installation instructions at http://docs.graylog.org/en/2.4/pages/installation/operating_system_packages.html#rpm-yum-dnf.

**Comment by behalkarun** [comment]
[root@wipro ~]# yum install graylog-server
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos-hn.viettelidc.com.vn
 * extras: centos.excellmedia.net
 * updates: centos-hcm.viettelidc.com.vn
base                                                     | 3.6 kB     00:00
elasticsearch-1.7                                        | 2.9 kB     00:00
extras                                                   | 3.4 kB     00:00
https://packages.graylog2.org/repo/el/stable/2.4/repodata/repomd.xml: [Errno 14] curl#60 - "Peer's certificate issuer has been marked as not trusted by the user."
Trying other mirror.
It was impossible to connect to the CentOS servers.
This could mean a connectivity issue in your environment, such as the requirement to configure a proxy,
or a transparent proxy that tampers with TLS security, or an incorrect system clock.
You can try to solve this issue by using the instructions on https://wiki.centos.org/yum-errors
If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by joschi** [comment]
> [Errno 14] curl#60 - "Peer's certificate issuer has been marked as not trusted by the user."

Either someone is playing man-in-the-middle with your network connections or the certificate store of your operating system is hopelessly out-of-date.

Anyway, there is no support for Graylog 1.3.x anymore. So please upgrade to the latest stable version and check if the problem still exists and if it does, open a new issue on GitHub.

Until then, I'll close this issue.

You can, of course, post your issue to the Graylog Community forums so that other members of the community might help you.

Make sure to include all necessary information, such as the complete configuration of Graylog and Elasticsearch, and the complete logs of your Graylog and Elasticsearch nodes.
