### ISSUE TITLE
Per-minute value of histogram widget changes back and forth between two values

### ISSUE THREAD

**Issue by hpetersFC** [Graylog2/graylog2-server#4910]
Several of our data scientists have noticed on occasion some data slices in histograms changing. 
E.g. as follows, when looking at the per-minute histogram widget for a certain query, updating every 100 seconds:

1) Initially the maximum spike appeared to be 62/min 
2) Looking again several minutes later, the maximum for the exact same minute now only looked to be 21/min 
3) This change between those values happened several times (even the next day) when the widget updated -- sometimes right in front of my eyes.

## Expected Behavior
Stats in widgets should remain consistent.

## Current Behavior
Stats in widgets can change back and forth between two values.

## Steps to Reproduce (for bugs)
Random

## Context
We need to be able to get a quick overview over certain stats - especially in times of crisis - using dashboards of several widgets. Also, the relative metrics between those widget's stats are important. If just one of the stats changes 3-fold, this throws out the relative metrics. It may lead to wrong conclusions and decisions based on incorrect data.

Querying for those stats directly may give the true value (haven't confirmed), but it's not a solution. We rely heavily on the widgets for quick overviews esp during crisis. A bit of fuzziness is ok, but a 3-fold change is quite bad. 

## Your Environment
Graylog version - 2.4.3
Elasticsearch version - 5.5
Mongo version - 2.6.12
OS - Ubuntu 16.04.4

**Comment by joschi** [comment]
@hpetersFC Could you please provide some screenshots or a screencast demonstrating the issue?

**Comment by hpetersFC** [comment]
Sure, see this recording: https://tinyurl.com/yc6p4tjk  (Google drive)

**Comment by garrows** [comment]
Bump

**Comment by bernd** [comment]
The widgets and search backend has been rewritten since this issue has been opened. Please open a new issue if this is still an issue with Graylog 3.3 or the upcoming 4.4. Thank you!
