### ISSUE TITLE
Can't execute search after upgrading to 2.4.5+8e18e6a

### ISSUE THREAD

**Issue by MauJFernandezUVR** [Graylog2/graylog2-server#4918]
After upgrading my two-node cluster to Graylog 2.4.5+8e18e6a I'm receiving an error in the Search tab and can't do any search.

## Expected Behavior
Search working normally.

## Current Behavior
After clicking on the Search tab, I'm presented with the following error:

```
Could not execute search
There was an error executing your search. Please check your Graylog server logs for more information.

Error Message:
Unable to perform search query closed
Details:
closed
Search status code:
500
Search response:
cannot GET https://10.30.20.148:9000/api/search/universal/relative?query=%2A&range=300&limit=150&sort=timestamp%3Adesc (500)
```

I'm also seeing a spam of this warning in the logs of the master node:

    2018-07-17T12:13:39.326-03:00 WARN  [IndexRotationThread] Deflector is not up. Not trying to point to another index.

But boths nodes are sending messages to the Elasticsearch cluster normally.

    GET graylog_deflector/_settings

```
{
  "graylog_327": {
    "settings": {
      "index": {
        "number_of_shards": "4",
        "provided_name": "graylog_327",
        "creation_date": "1531759114425",
        "analysis": {
          "analyzer": {
            "analyzer_keyword": {
              "filter": "lowercase",
              "tokenizer": "keyword"
            }
          }
        },
        "number_of_replicas": "1",
        "uuid": "l_jm-gRjTkK64cxKqoWvZg",
        "version": {
          "created": "5061099"
        }
      }
    }
  }
}
```

## Steps to Reproduce (for bugs)

1. Install Graylog 2.4.5+8e18e6a RPM version for RHEL 7.5
2. Open the Search tab

## Context

Cannot do searches or see the realtime income of messages.

## Your Environment

* Graylog Version: 2.4.5+8e18e6a
* Elasticsearch Version: 5.6.10
* MongoDB Version: 3.6.4
* Operating System: RHEL 7.5
* Browser version: Chrome 66.0.3359.117 (Official Build) (64-bit)

**Comment by joschi** [comment]
@MauJFernandezUVR Please post the complete logs of your Graylog and Elasticsearch nodes:
http://docs.graylog.org/en/2.4/pages/configuration/file_location.html#rpm-package
