### ISSUE TITLE
Graylog JVM memory leak?

### ISSUE THREAD

**Issue by joaopsys** [Graylog2/graylog2-server#4921]
I'm experiencing a memory leak in Graylog 2.4.6 (also happened in 2.4.5).

I'm running 2 Graylog nodes in 2 separate servers, in a docker container (from https://hub.docker.com/r/graylog/graylog/). I've allocated 32GB heap memory to JVM and a max of 48GB.

## Expected Behavior
When looking at the system nodes in the GUI, I can see the memory consumption pattern: 

It keeps going up, and then is flushed. **In the 'slave' node** everything seems fine, the usage goes up to 13-14GB and then is flushed back to 1-3GB. And that keeps going 'forever', which I believe is the expected behavior.

## Current Behavior
The master node starts by following the same consumption pattern. It goes up to 13-14GB and is then flushed back down to 1-3GB. However it keeps slowly adding up and at one point it goes up to 20GB and flushed back to 10, after a couple of hours, it goes up to 30GB and goes back to 20. And so on and so forth, until the JVM runs out of memory and the master instance stops responding to API requests. At this point, my Keepalived redirects the load to the slave node, which prevents the master node to actually crash.

## Context
I'm using Keepalived (LVS) to **load balance the inputs** to both my graylog instances. When the master dies, the 'slave' takes the full load and it handles it perfectly. Both instances have the exact same configuration and are running the exact same version of Graylog, in the same operating system and kernel.

I'm also using apache as a reverse proxy for the GUI/API, that one is not load balanced. It always leads to the master instance.

One thing I'm not doing (yet) is the replication of MongoDB. The host of the master node runs the main instance of mongodb in a docker container and the slave node is using that one as well for now.

## Your Environment

* Graylog Version: 2.4.6+ceaa7e4
* Elasticsearch Version:
* MongoDB Version:
* Operating System: CentOS Linux release 7.5.1804 - Linux 3.10.0-229.20.1.el7.x86_64
* Browser version:

## Configurations

Here is the relevant docker-compose configurations (same in both nodes):

- GRAYLOG_ROTATION_STRATEGY=count
- GRAYLOG_ELASTICSEARCH_MAX_NUMBER_OF_INDICES=100
- GRAYLOG_ELASTICSEARCH_MAX_SIZE_PER_INDEX=6442450944
- GRAYLOG_RETENTION_STRATEGY=delete
- GRAYLOG_ELASTICSEARCH_SHARDS=6
- GRAYLOG_ELASTICSEARCH_REPLICAS=1
- GRAYLOG_ELASTICSEARCH_INDEX_PREFIX=new_graylog
- "GRAYLOG_SERVER_JAVA_OPTS=-Xms32g -Xmx48g -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:NewRatio=1 -XX:MaxMetaspaceSize=256m -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow"

## Attachments

I don't exactly know how to extract more information from my instances, but here you can find a screenshot showing the master node with roughly the same load as the slave, but consuming way more memory.

https://i.imgur.com/sDFI8Gc.png

You can also see in this screenshot that the master node has already increased the memory threshold from 30.4GB to 32.7GB by itself.

**Comment by joschi** [comment]
@joaopsys 32 GB or 48 GB of heap memory is pretty much for Graylog. I've rarely seen setups needing more than 4 GB of heap memory for Graylog.

Are you sure that you really need that much heap memory for Graylog?
What's the message throughput and how big are the messages on average?
How much memory is left for the operating system to use as disk cache?

Also, 32 GB is quite an unfortunate amount of memory to choose. See https://blog.codecentric.de/en/2014/02/35gb-heap-less-32gb-java-jvm-memory-oddities/ for some details.

**Comment by joaopsys** [comment]
Got it. Since we have lots of free RAM, I thought I could just give Graylog all the space in the world, but I guess I should read about JVM a little more.

I downed it to 8GB initial and max memory for now, and if it doesn't work, I will down it to 4GB. I will come back with results.

Thank you for your help.

**Comment by joaopsys** [comment]
Noticing the same behavior with 8GB.

Slave node goes up to 3.2GB down to 1-1.5GB and sometimes even to 300-800MB. And it stays like this.

Master node it hitting 4.2GB down to 2-3GB and keeps raising the upper limit to 4.9, 5.2, 5.5 etc

Going with 4GB initial and max now.

**Comment by joschi** [comment]
@joaopsys Are you suffering any [`OutOfMemoryError`](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/memleaks002.html)s? If not, everything is fine.

**Comment by joaopsys** [comment]
It happened again, with 4GB. 

After it eventually gets to 4GB, the master node sometimes disappears and reappears from the pool and I start getting a lot of this in the logs:

graylog_1  | 2018-07-19 12:53:40,839 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
graylog_1  | 2018-07-19 12:57:22,040 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
graylog_1  | 2018-07-19 12:57:27,411 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.
graylog_1  | 2018-07-19 12:57:32,921 WARN : org.graylog2.periodical.NodePingThread - Did not find meta info of this node. Re-registering.

No OutOFMemoryError but I see this:

https://i.imgur.com/fLp9tqH.png

**Comment by joaopsys** [comment]
It's kinda huge, but here we go:

https://pastebin.com/PrX5gKGY

**Comment by joaopsys** [comment]
I have now swapped the master role and the problem persists on the same node (which is now slave). With this in mind, I kind of take the blame off graylog...Although the containers and the host are the exact same, I guess it's something I'll need to sort out myself.

**Comment by jalogisch** [comment]
You should watch the metrics and available perfomance data of the docker host. Graylog and Elasticsearch benefit from having exclusive ressources and behave strange on shared ressources.

**Comment by jalogisch** [comment]
Let us wait until @joaopsys came back.

**Comment by joaopsys** [comment]
Updated the kernel on both physical hosts, rebooted both of them, including elasticsearch. They seem to be ok right now, but I will leave this running for ~1 day and come back with results. Usually after 1 day I come back with 1 of the instances dead.

**Comment by joaopsys** [comment]
It actually survived the night :) 

Although I set the RAM usage to 4 initial, 8 max, it still managed to use the full 8 sometime during the night. I guess this was my problem all along, and I'm not really sure what it was, but I believe this can be closed.

Thank you for your help
