### ISSUE TITLE
Alias in search query

### ISSUE THREAD

**Issue by kn0x1c** [Graylog2/graylog2-server#4930]
Hey there, first of all, you are doing an insane job there, developing graylog, I love this tool so much!
While using it every day, I would find it useful if I would have the possibility to add aliases in my search query. 

## Expected Behavior
It should work like:
`source:<<system>> AND NOT ALIAS:ALL_Monitoring_Requests`
The aliases would be saved like searches. Also it could be possible to use saved searches as an alias. Both options are great.
The alias would represent a filter for all monitoring request like:
`ALL_Monitoring_Requests="(request:\/server-status OR request:\/ping.jsp OR request:\/monitoring*)`

## Current Behavior
There are saved searches, but you cant use them inline in the search query

## Possible Solution
I think about two Solutions:
1. Use saved searches also as aliases
Pro: You dont need to administrate a extra section for aliases
Contra: Maybe you loose the overview over the saved searches
2. Make a extra section aliases like saved searches
Pro:
Better for permission administrating
Better overview
Contra:
Another section and can be confusing since saved searches are existing too

## Context
If wan't to filter out monitoring request for different host you don't need to always retipe the requests. Useful for similar situations.

**Comment by jalogisch** [comment]
@kn0x1c with Version 3.0 we will have nearly something that you are looking for. After the release of 3.0 and your examination of the feature `views` isn't what you like to have, please re-open the issue.
