### ISSUE TITLE
Show warning if configured journal size does not fit on disk

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#4933]
## Expected Behavior
Graylog should warn if the journal would not fit at the configured location. 

## Current Behavior
You can configure any size at any location for the message journal and Graylog will accept this. That could potential damage the setup if the space is not enough for the configured journal size - messages will get lost when the journal is damaged.

## Possible Solution

- Graylog could warn on startup if the configured journal size will not fit into the configured disk (in the logfile)
- Graylog could warn at the nodes overview if the journal holding partition gets filled not leaving enough space for the journal.
- Graylog could give a notification like for journal usage if the partition would not fit.

## Context

Most users did not notice the setting of the journal size until they run into issue - but then it becomes really fast really messy. Users could have created multiple small partitions where /var is not big enough to hold the journal and the logfiles at once.

## Your Environment

* Graylog Version: 2.4.6

**Comment by radykal-com** [comment]
Hello, the PR implements the first and the third point of the posible solution list.

**Comment by boosty** [comment]
Fixed by https://github.com/Graylog2/graylog2-server/pull/11889
