### ISSUE TITLE
HTTP API error response shouldn't contain auto-value class names

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#4938]
## Expected Behavior

A HTTP API errors response should not contain any auto-value class names. This is what errors used to look like:

```json
{
    "message": "HTTP 404 Not Found", 
    "type": "ApiError"
}
```

## Current Behavior

In https://github.com/Graylog2/graylog2-server/pull/4573 the `ApiError` class got converted into an auto-value class. Since then the response looks like this:

```
$ http :9000/api/system/nonono
HTTP/1.1 404 Not Found
Content-Length: 60
Content-Type: application/json
Date: Tue, 24 Jul 2018 10:18:55 GMT

{
    "message": "HTTP 404 Not Found", 
    "type": "AutoValue_ApiError"
}
```

The same happens for other error classes like `ValidationApiError`!

## Possible Solution

Find a way to detect auto-value error classes and use the superclass name or strip the `AutoValue_` prefix from the `type` in the JSON error response.

## Steps to Reproduce (for bugs)

1. Execute a HTTP requests against the API with a path that doesn't exist
2. Check JSON error response

* Graylog Version: 3.0.0-alpha.2-SNAPSHOT (rev 3253e86e5)

**Comment by danotorrey** [comment]
I am investigating this. See https://github.com/FasterXML/jackson-annotations/issues/88 for discussion about same issue.
