### ISSUE TITLE
Updating no. of replicas index setting on Elasticsearch node doesn't reflect on Graylog web interface

### ISSUE THREAD

**Issue by emanzaman** [Graylog2/graylog2-server#4952]
I updated the number of replicas for an index using curl directly on my Elasticsearch instance:
`
curl -X PUT "$(hostname):9200/_settings" -H 'Content-Type: application/json' -d'
                {
                    "index" : {
                    "number_of_replicas" : 1
                }
            }'
`
On retreiving the index settings using the curl on Elasticsearch instance, it correctly reflects the updated number of replicas setting:
`{"graylog_0":{"settings":{"index":{"refresh_interval":"30s","number_of_shards":"1","provided_name":"graylog_0","creation_date":"1531919973947","analysis":{"analyzer":{"analyzer_keyword":{"filter":"lowercase","tokenizer":"keyword"}}},"number_of_replicas":"1","uuid":"SYUy8sbYQDGzBDex4_LpQA","version":{"created":"5060899"}}}}}`

## Expected Behavior
The updated number of replica should have correctly reflected in Graylog Web Interface on System/Indices page.

## Current Behavior
Graylog Web Interface on System/Indices page currently shows the number of replicas as 0.

## Your Environment
* Graylog Version: 2.4.3 
* Elasticsearch Version: 5.6.8
* MongoDB Version: 3.6.2
* Operating System: RHEL7
* Browser version: Chrome

**Comment by emanzaman** [comment]
I think I mistook the index set settings page for index setting page.
Apologies.

**Comment by jalogisch** [comment]
@emanzaman how should Graylog know what you have done with Elasticsearch not using Graylog as man-in-the-middle?

You would need to run the maintanance functions on the `System > indices > INDEX_NAME` page to query for the updates.

**Comment by emanzaman** [comment]
@jalogisch My understanding was that Graylog reads the data from Elasticsearch node itself for queries on indices.
Could you please be more specific on exactly which operation should I run in System > indices > INDEX_NAME?
Thanks,

**Comment by jalogisch** [comment]
you should run the `recalculate index range` what is in the drop down in the upper right on the index page.
