### ISSUE TITLE
v2.4.6+ceaa7e4 main search screen Histogram does not work correctly

### ISSUE THREAD

**Issue by control-panel** [Graylog2/graylog2-server#4969]
## Expected Behavior

Switching between time intervals: minutes, hour, day .... should correctly display time intervals

## Current Behavior

Correctly works only minute, while hour, day, week etc. are broken

## Steps to Reproduce (for bugs)

1. Switch to main search screen
2. Try to change time intervals on histogram from other than minute
3. Hour, day ... are broken
4.

## Your Environment

* Graylog Version: v2.4.6+ceaa7e4
* Elasticsearch Version: 5.6 (elastic official repo)
* MongoDB Version: 1:3.2.11-2+deb9u1 (Debian 9 stock)
* Operating System: Debian 9 (on VM) 
* Browser version: Mozilla Firefox  for Linux Mint 61.0.1

![graylog_histogram_minute](https://user-images.githubusercontent.com/11228044/43539672-2e774422-95ce-11e8-9a71-8b81c306bbe6.jpg)
![graylog_week_interval](https://user-images.githubusercontent.com/11228044/43539673-2ea5b0fa-95ce-11e8-8b6e-d0321766b8ff.jpg)

**Comment by edmundoa** [comment]
Sorry to ask again, but I am still not sure what you meant by reading the issue description. Looking at the screenshots, I guess you are referring to that display issue in the x-axis of the second chart you shared with us, where the data point does not have the correct label. Is that what you mean?

**Comment by control-panel** [comment]
Thank you for answer.
No, i mean that switching time intervals on histogram on default search screen did not work correctly.
From the other point of view one can say that time intervals(other than minute) on histogram are displayed incorrectly. It is not only display issue with x-axis but columns are also did not correspond to real situation.

But for now, i do not understand how you did this, histogram works correctly.

**Comment by jalogisch** [comment]
So the 'bug' happens when you select a timeframe you did not have any data for. 

Or to reword the issue. When you select a timeframe you did not have data for the histogram does not show the correct timezone settings. 

Is that correct?

**Comment by control-panel** [comment]
Yes, black line at the bottom of histogram appears instead of normal points for month(in this particular case) names.

**Comment by bernd** [comment]
This is fixed with the new search implementation.
