### ISSUE TITLE
Syslog UDP RST send by Graylog

### ISSUE THREAD

**Issue by lnxslck** [Graylog2/graylog2-server#4972]
This seems to be the same as #1105 but for UDP.

## Expected Behavior
I'm trying to send logs from a server into Graylog using rsyslog, but the logs don't show on Graylog, and looking at tcpdump the connections are being RESET

## Current Behavior
When i try to connect to the port configured on Graylog Input (for example 1514), i always get Connection Reset.
I can see the logs on the server (/var/log/*) but not on Graylog.

## Steps to Reproduce (for bugs)
This is my setup

Server A
Graylog v2.4.6+ceaa7e4
Ubuntu 16.04 x64
Rsyslog running on port 514

Graylog input configured for Syslog UDP on 0.0.0.0 port 8514

Server B
Rsyslog running
Configuration on rsyslog:  *.* @192.168.0.126:8514;RSYSLOG_SyslogProtocol23Format

1. Port 8514 is up on Graylog server

netstat -putan | grep 8514                                                                            
udp6       0      0 :::8514                 :::*                                1627/java       

3. Trying to connect
telnet 192.168.0.126 8514
Trying 192.168.0.126...
telnet: Unable to connect to remote host: Connection refused

4. Tcpdump showing Flag RESET

01:28:37.904333 IP (tos 0x10, ttl 64, id 55250, offset 0, flags [DF], proto TCP (6), length 60)
    SERVERB.58664 >SERVERA.8514: Flags [S], cksum 0xb52b (correct), seq 1048351280, win 29200, options [mss 1460,sackOK,TS val 2099661390 ecr 0,nop,wscale 7], length 0
01:28:37.904409 IP (tos 0x10, ttl 64, id 47954, offset 0, flags [DF], proto TCP (6), length 40)
   SERVERA.8514 > SERVERB.58664: Flags [R.], cksum 0x5680 (correct), seq 0, ack 1048351281, win 0, length 0

## Your Environment

All firewalls are down.

* Graylog Version: v2.4.6+ceaa7e4
* Elasticsearch Version: 5.6.10  
* MongoDB Version: 3.6.6
* Operating System: Ubuntu 16.04.05
* Browser version: Firefox/ Opera

Any solution for this?

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
