### ISSUE TITLE
Address already in use

### ISSUE THREAD

**Issue by TenGbps** [Graylog2/graylog2-server#4979]
I have many trouble to use TCP input, when i do a Stop/Start, 90% time i have error 'Address already in use'

We try
```
echo 1 > /proc/sys/net/ipv4/tcp_tw_recycle
echo 1 > /proc/sys/net/ipv4/tcp_tw_reuse

/etc/security/limits.conf
graylog soft    nofile  65536
graylog hard    nofile  65536
```
whitout sucess

![sans titre](https://user-images.githubusercontent.com/30792994/43827927-6715c218-9afb-11e8-9ec4-c4fb77fdafa0.png)

```
2018-08-08 10:55:43,362 ERROR: org.graylog2.shared.inputs.InputLauncher - The [org.graylog2.inputs.syslog.tcp.SyslogTCPInput] input with ID <5b6aafbb759a297e388c7ef2> misfired. Reason: Address already in use.
org.graylog2.plugin.inputs.MisfireException: org.graylog2.plugin.inputs.MisfireException: org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:12300
```

* Graylog Version: 2.4.5
* Elasticsearch Version: 5.5.1
* MongoDB Version: 3.6.4
* Operating System: CentOS7
* Browser version: Firefox 62

**Comment by jalogisch** [comment]
I can't verify that behaviour with the current 2.4.6 release of Graylog on `CentOS 7`.

On the default installation, without additional settings this can't be reproduced. Can you please share your additional settings and system hardenings.

**Comment by TenGbps** [comment]
![capture](https://user-images.githubusercontent.com/30792994/44030631-a89b9186-9f01-11e8-8b9e-76d26c9d3726.JPG)

Now i update in 2.4.6

**Comment by jalogisch** [comment]
We aren't able to reproduce that on our side - that is why I would point to the community board to find the error in your installation. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by TenGbps** [comment]
This issue is due to a bad configuration with rest_transport_uri & web_endpoint_uri
