### ISSUE TITLE
Is it possible to save data into clickhouse?

### ISSUE THREAD

**Issue by ev4ern** [Graylog2/graylog2-server#4989]

**Comment by jalogisch** [comment]
Graylog use MongoDB to store configuration and Elasticsearch for the log messages. As you can see in the Documentation:

http://docs.graylog.org/en/2.4/pages/architecture.html#minimum-setup

Please see the FAQ answer for other possible storage solutions.

http://docs.graylog.org/en/2.4/pages/faq.html#i-dont-want-to-use-elasticsearch-as-my-backend-storage-system-can-i-use-another-database-like-mysql-oracle-etc
