### ISSUE TITLE
Only graylog-server timezone is delay.

### ISSUE THREAD

**Issue by MitsuWindows** [Graylog2/graylog2-server#4993]
![image](https://user-images.githubusercontent.com/31452274/44061234-cec0b1b0-9f57-11e8-8ea8-3cb2cf57bae8.png)

I set up root_timezone = Europe/Vienna but only graylog server timezone is delay.  If it works correctly, server timezone also should be + +02:00.  How should I fix it?

## Your Environment

* Graylog Version: 2.4.6

**Comment by jalogisch** [comment]
The `root_timezone` is the timezone that is used for the admin/root user - where the password is declared in the configuration too - not the time of Graylog. It uses internal UTC. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).
