### ISSUE TITLE
Graylog 2.4.6 stops receiving messages, requires a restart

### ISSUE THREAD

**Issue by yonchin** [Graylog2/graylog2-server#5019]
The log message cannot be received every once in a while, then it can be restarted after the service, I do not know why?

**Comment by jalogisch** [comment]
thank you @yonchin to write this down. But without proper description and a way to reproduce your issue we would not be able to help you or find the bug that you might run into.

Please describe your environment, what plugins do you use, how many messages you handle what happens the last before the issue. How it can be reproduced, what logs did you have at Graylog.

The questions in the issue template are for a reason give.

**Comment by yonchin** [comment]
I would like to ask a question. I used fluent-bit for log forwarding, but there is no problem if it is output directly to elasticsearch. Where the input plugin for graylog USES Raw/Plaintext TCP,
Is this support is not enough now

**Comment by jalogisch** [comment]
The RAW Input is build into Graylog, no extra Plugin is needed.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
