### ISSUE TITLE
Histogram Interval Selector on Dashboards

### ISSUE THREAD

**Issue by GTownson** [Graylog2/graylog2-server#5035]
## Expected Behavior
Histograms in dashboards should be able to have their interval changed within the edit section.

## Current Behavior
To change the interval of a histogram on a dashboard you have to delete the widget and recreate it with the new interval.

## Context
The deletion and recreation of the histogram widgets takes more time than it would to edit it.

**Comment by dennisoelkers** [comment]
Fixed in `3.3`.
