### ISSUE TITLE
Consider making the default processor order more useful

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5040]
Currently, the default processor order makes the pipelines run before the message filter chain. Because stream matching happens in the message filter chain, pipelines are pretty much useless with default settings because they cannot be connected to a stream. (because the stream matching did not run yet)

I've seen many many users and customers bang their heads against the wall because pipelines just silently wouldn't run until the order is changed. I have also so far changed the order for every single setup I ever worked on.

I'd like to discuss if 3.0 is a good moment for a breaking change, where we make the pipeline processor run after the message filter chain.

**Comment by bernd** [comment]
I think 3.0 is a good moment to do breaking changes. We have to make sure that nothing will change for existing setups that get updated to 3.0, though.

**Comment by jalogisch** [comment]
I'm in for the change in 3.0.

We had talked about that several times in the past and want to avoid breaking any setup by changing that order.

Maybe it is possible to change that order just when the database is created and not for existing setups?

**Comment by jalogisch** [comment]
- In 2.5 we persist the default order if the user didn’t change it yet
- In 3.0 we then can check if there is a persisted processor order config and if not, use the new and better default order and persist it
- That means we only change the default order for new setups to avoid breaking existing ones
- This needs to be documented to make sure there are no surprises

**Comment by bernd** [comment]
I am moving this out of 2.5 because we don't have time for it.

**Comment by kroepke** [comment]
We've decided to postpone this change, because we cannot reliably detect whether users depend on the order or not.

The risk of breaking processing is too high for the reward at this point.
