### ISSUE TITLE
Custom Sidecar collector doesn't start

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5047]
![peek 2018-08-30 16-25](https://user-images.githubusercontent.com/35022/44880191-5c9ee800-ac71-11e8-8751-caeb545a9c4c.gif)

I was able to create a custom collector for metricbeat and it works really well but I can't get a auditd process to start. There is no error but there is also no configuration change triggered on the sidecar instance at all.

No errors or warnings in the `graylog-server` log file either.

![screenshot from 2018-08-30 16-30-43](https://user-images.githubusercontent.com/35022/44880442-11390980-ac72-11e8-9e8f-a0a351e71042.png)
![screenshot from 2018-08-30 16-30-30](https://user-images.githubusercontent.com/35022/44880443-11390980-ac72-11e8-855d-45fc67afd4a5.png)

**Comment by lennartkoopmann** [comment]
**UPDATE:** It doesn't work for the Metricbeat on a second node either. This seems to be a generic problem. I'm on `3.0.0-alpha.2-SNAPSHOT+73c96fa`

**Comment by edmundoa** [comment]
I think the problem is that you need to assign a configuration first. Otherwise the collector will either start and do nothing, or not start at all (I'm not familiar with that part of the code, so I can't tell for sure).

In any case, we need to make that clearer to users.

**Comment by lennartkoopmann** [comment]
Ohhhh, I see. :) Yes, that definitely needs to be made clearer to the user. :)

Keeping this ticket open and let you decide if you want to open another one. Thanks already!

**Comment by edmundoa** [comment]
Hopefully made clearer in #5181
