### ISSUE TITLE
Add tabs to Graylog search

### ISSUE THREAD

**Issue by DrWifey** [Graylog2/graylog2-server#5055]
I want to propose the feature of enabling tabs directly in Graylog Web-interface. Why?

How do we work with logs: (for example) first I search error messages by query: `level:<5`, then I specify some `traceId` to see full request path, then I specify some `sourceFileName` to see the details of data flow in it, so as a result I have 3-5 opened tabs and through 5 minutes I’m closing it because I have other tabs opened (not graylog) and it becomes 10-15 tabs. And it’s hard to restore them when I need it again.

So it’d be great if I can open the tabs inside graylog and even better if I can save them.
If I didn’t give enough details please let me know and I’ll try to explain better.
Thanks.

**Comment by dennisoelkers** [comment]
Thanks, @DrWifey. Took a while for this response, but this is exactly what we are now doing in `3.0` with the "Views" feature. You can learn more about it here: https://www.graylog.org/products/latestversion

**Comment by nosilver4u** [comment]
So, I was wondering about the same thing, and had even seen tabs in a demo on graylog.org somewhere. What/where are views? We use tabs constantly on our current solution for quickly switching between searches, and find them quite handy.
