### ISSUE TITLE
Stacked Fields dropdown list of the Quick Values widget created in a stream page contains the fields of all the streams.

### ISSUE THREAD

**Issue by eduault** [Graylog2/graylog2-server#5056]
## Expected Behavior
The list of fields that is displayed in the Stacked Fields dropdown list of the Quick Values widget created in a stream page should only contain the fields of this stream.

## Current Behavior
The list of fields that is displayed in the Stacked Fields dropdown list of the Quick Values widget created in a stream page contains the fields of all the streams.

## Possible Solution
Take into account the stream (and the query ?) when the Stacked Fields dropdown list of the Quick Values widget is displayed.

## Steps to Reproduce (for bugs)
1. Connect to Graylog Web interface using a browser, and login
2. Open a stream & search
3. Display a Quick Values widget for a field
4. Edit the Stacked Fields of the widget (Customize > Configuration > Stacked Fields > Arrow)
5. The list of fields that is displayed contains all the fields in Graylog, not only those of the current stream

## Context
I'm only declaring the bug that I discovered using the Quick Values widget.

## Your Environment
* Graylog Version: 2.4.6+ceaa7e4, codename Wildwuchs
* JVM: Oracle Corporation 1.8.0_172 on Linux 3.13.0-153-generic
* Elasticsearch Version:  Version: 5.6.3 (provided with Graylog AMI)
* MongoDB Version: v3.4.9 (provided with Graylog AMI)
* Operating System: Ubuntu on AWS (Linux graylog 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
* Browser version: Firefox, on a Windows PC in a business environment (proxy + firewall + security tools ...)

**Comment by DerPhlipsi** [comment]
I guess this is related to @jalogisch's finding in #4468 that the fields are loaded from the deflector.

**Comment by eduault** [comment]
The access rights to the Graylog data have to be implemented in the core of the Graylog server, not delegated to the widget code. And any data is concerned by this constraint : the messages, the list of fields, etc.
Any widget used by a user in a browser session should have its access to Graylog data restricted to the rights defined by the administrator for this user. The Graylog server should never allow any widget to access other data. Therefore, the Graylog server should always communicate with the widget in a security context including the user identity.

**Comment by dennisoelkers** [comment]
This has become obsolete, as the quick values widget is replaced by the aggregation builder in `3.2`.
