### ISSUE TITLE
Graphs looks different from stream tab and dashboards tab

### ISSUE THREAD

**Issue by ManuRivas21** [Graylog2/graylog2-server#5060]
When creating a multifield graph, it looks different from streams and from dashboards.

## Expected Behavior
Graphs should be the same in stream and in dashboard tab.

## Current Behavior
I'm creating a graph with 2 queries in the streams tab. This is how it looks:
![image](https://user-images.githubusercontent.com/42977101/45047047-3d8cc580-b078-11e8-87a6-65e84bfeb545.png)

However, when I add it to the dashboard, it looks like:
![image](https://user-images.githubusercontent.com/42977101/45047106-66ad5600-b078-11e8-9037-3ee00901e606.png)

## Steps to Reproduce (for bugs)
1.- Create a graph with 2 or more queries.
2.- Add the graph to a dashboard.

## Your Environment
Unknown (it's under my organization control)
* Graylog Version: Unknown
* Elasticsearch Version: Unknown
* MongoDB Version: Unknown
* Operating System: Unknown
* Browser version: Unknown

**Comment by TenGbps** [comment]
Yes agree, the graph on dashboard is not the same of search section
