### ISSUE TITLE
[Feature] Add timerange selection inside dashboard

### ISSUE THREAD

**Issue by TenGbps** [Graylog2/graylog2-server#5065]
Could you add the timerange selection is dashboard ?
Like both captures

![sans titre](https://user-images.githubusercontent.com/30792994/45092310-47b0d180-b115-11e8-8727-8ca6969bc779.jpg)

* Graylog Version: 2.4.6
* Elasticsearch Version: 5.5.1
* MongoDB Version: 2.6.12
* Operating System: CentOS7
* Browser version: Firefox 60 ESR

**Comment by dennisoelkers** [comment]
Thanks for the input. To support us tracking the issues, can you split out the custom colors for the charts in a separate issue? Those are unrelated features so we should track them separately.

**Comment by TenGbps** [comment]
Color issue creat here https://github.com/Graylog2/graylog2-server/issues/5229
