### ISSUE TITLE
Damaged repomd.xml file

### ISSUE THREAD

**Issue by r4yfx** [Graylog2/graylog2-server#5075]
Attempting to pull the repository down into spacewalk, and receive the following error message

14:33:07   Processing repository with URL: https://packages.graylog2.org/el/stableServer/2.4/x86_64
Repository group_spacewalkproject-java-packages is listed more than once in the configuration
14:33:09 ERROR: failure: repodata/repomd.xml from centos07-graylog2.4.repo: [Errno 256] No more mirrors to try.
https://packages.graylog2.org/el/stableServer/2.4/x86_64/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for centos07-graylog2.4.repo: Damaged repomd.xml file
14:33:09 Sync of channel completed in 0:00:02.
14:33:09 Total time: 0:00:02

Other channels appear to be working fine.

**Comment by gisselmann** [comment]
Packages are located under
https://packages.graylog2.org/el/stable/2.5/x86_64/repodata/repomd.xml
repodata unter
https://packages.graylog2.org/repo/el/stable/2.5/x86_64/repodata/

strange

**Comment by hrileyFLA** [comment]
This is still a problem. Can someone address this issue? As gisselmann noted, the repomd.xml is under a different path than the actual repo.

**Comment by kamsalisbury** [comment]
Validated that;
1. Had to change the repo base url from
`baseurl=https://packages.graylog2.org/repo/el/stable/3.2/$basearch/`
to
`baseurl=https://packages.graylog2.org/el/stable/3.2/$basearch/`

2. Then received
`https://packages.graylog2.org/el/stable/3.2/x86_64/repodata/repomd.xml: [Errno -1] Error importing repomd.xml for graylog: Damaged repomd.xml file`

**Comment by bernd** [comment]
I think this is a misunderstanding between what's shown in the https://packages.graylog2.org/ web UI and how the packages are actually reachable. The URL in the yum configuration needs the `/repo` prefix, otherwise it will not work.

Please use the instructions [here](https://docs.graylog.org/en/3.3/pages/installation/operating_system_packages.html#rpm-yum-dnf) to setup the Graylog repository.
