### ISSUE TITLE
Plugin Test Mismatch

### ISSUE THREAD

**Issue by megan201296** [Graylog2/graylog2-server#5080]
The [example](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/json.txt) for the `parse_json` function shows that you can then set fields using the `to_map` function but unless I'm doing something totally wrong, there is no `to_map` function in Graylog.

**Comment by jalogisch** [comment]
that function is available in 3.0 ( https://github.com/Graylog2/graylog-plugin-pipeline-processor/pull/228 ) but not in the current stable 2.4 - for that reason i'll close this. 

With reference to the community: https://community.graylog.org/t/parsing-json-in-a-pipeline/6739
