### ISSUE TITLE
Graylog2 metrics not working

### ISSUE THREAD

**Issue by collins-b** [Graylog2/graylog2-server#5089]
Looks like graylog metrics aren't working. Telegraf reports the following error when I do an API call.

```
"2018-09-09T18:35:30.048Z","telegraf","2018-09-09T18:35:30Z E! Error in plugin [inputs.graylog]: Response from url ""http://graylog:9000/api/system/metrics/multiple"" has status code 400 (Bad Request), expected 200 (OK)"
```
## Expected Behavior

API call should be successful

## Current Behavior

API call returns status code 400

## Steps to Reproduce (for bugs)

1. Enable graylog monitoring in telegraf
2. Do an API call, for example a POST on `/system/metrics/multiple` endpoint
3. Observer telegraf logs

## Your Environment

* Graylog Version: Graylog 2.4.6-1
* Elasticsearch Version: 5.6.3
* MongoDB Version: 3
* Operating System: Ubuntu
* Browser version:

**Comment by jalogisch** [comment]
please share your telegraf configuration and what you are requesting. Currently it looks more like a configuration issue.

**Comment by collins-b** [comment]
@jalogisch This is graylog section in the telegraf configuration:

```
[[inputs.graylog]]
  servers = ["http://graylog:9000/api/system/metrics/multiple"]
  ## Username and password
  username = "xxx"
  password = "xxx"
```

**Comment by jalogisch** [comment]
He @collins-b 

you need to add what metrics you like to get:

```
[[inputs.graylog]]
  servers = [
    "https://<YOUR_GRAYLOG_IP_OR_NAME>:9000/api/system/metrics/multiple",
  ]
  metrics = [
    "jvm.threads.count",
    "jvm.memory.total.init",
    "jvm.memory.total.used",
    "org.graylog2.journal.size",
    "org.graylog2.journal.size-limit",
    "org.graylog2.buffers.input.size",
    "org.graylog2.buffers.input.usage",
    "org.graylog2.buffers.output.size",
    "org.graylog2.buffers.output.usage",
    "org.graylog2.buffers.process.size",
    "org.graylog2.buffers.process.usage",
    "org.graylog2.journal.append.1-sec-rate",
    "org.graylog2.journal.utilization-ratio",
    "org.graylog2.throughput.input.1-sec-rate",
    "org.graylog2.throughput.output.1-sec-rate"
  ]
  username = "Your token here"
  password = "token"
  insecure_skip_verify = true
```

See this as example: https://grafana.com/dashboards/2549 

The above is working without issues in my lab.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
