### ISSUE TITLE
Netflow plugin problems with Cisco flows

### ISSUE THREAD

**Issue by ortizleo** [Graylog2/graylog2-server#5094]
Hello.

Netflow plugins ins't work stable with cisco flows, the flows are so slow to be processed (1 hour~ after) or not processed. Tested with softflowd-0.9.9 and works fine, but with cisco flows ins't working as expected.

Same problem than: 
https://github.com/Graylog2/graylog2-server/issues/4865
https://github.com/Graylog2/graylog-plugin-netflow/issues/30

## Expected Behavior
View and analyse cisco netflow V9 our V5.

## Current Behavior
Messages slow or not processed by graylog.

## Steps to Reproduce (for bugs)
1. With cisco router, just configure ip flow-destination
2. If haven't cisco router, can use GNS3 with some IOS image.

## Context
Graylog have the feature so i want to use.

## Your Environment
* Graylog Version: 2.4.6

**Comment by jalogisch** [comment]
I'm closing this issue, as it is duplicating #4865 . Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
