### ISSUE TITLE
How to setup an email when graylog server goes down. Any help will be appreciated.

### ISSUE THREAD

**Issue by JoeyJones** [Graylog2/graylog2-server#5096]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by jalogisch** [comment]
@JoeyJones the issue template are given for a reason.

I'll close this issue now and if you can write more than just the headline please open a new issue. 

thanks
