### ISSUE TITLE
Sidecar processes are shown as "running" even after host is offline

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5097]
I have a host with an installed sidecar but the host is currently not running. The whole machine is shut down.

This is properly reflected in the list of sidecars because it's marked as inactive and hidden by default, until I enable the option to show inactive sidecars:

![screenshot from 2018-09-11 18-48-06](https://user-images.githubusercontent.com/35022/45392005-573b8900-b5f3-11e8-8ed7-fdddeb0b4b9d.png)

However, it still shows all the collector processes as running:

![screenshot from 2018-09-11 18-47-50](https://user-images.githubusercontent.com/35022/45392010-60c4f100-b5f3-11e8-92e0-b94ae281a957.png)

## Your Environment

* Graylog Version: Graylog 3.0.0-alpha.2-SNAPSHOT+73c96fa

**Comment by edmundoa** [comment]
This was fixed here, at least we include an `inactive` indicator now: https://github.com/Graylog2/graylog2-server/pull/5092

Please reopen if you think this is still not clear enough :)

**Comment by edmundoa** [comment]
Now that I read this again: I'll reopen, since the collectors themselves shouldn't be marked as `running` anyway.

**Comment by edmundoa** [comment]
Regarding the `running` state, it has been fixed in https://github.com/Graylog2/graylog2-server/pull/5052, and it's in master already.

@lennartkoopmann can you update your branch and see if the problem still occurs? Thank you!

**Comment by bernd** [comment]
No response so we are closing this. Please re-open if the problem still exists. Thank you!
