### ISSUE TITLE
Sidecar collector status is confusing when sidecar itself is not running

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5107]
I have a sidecar on a host that is currently offline. The last reported status for all collectors was "running", so not all my collectors are showing as "running" even though none of them is actually running.

Even worse, when I restart a collector on that box (accidentally - didn't remember it was offline and didn't notice, because it's shows everything as "running"), only that restarted collector shows as "stopped":

![screenshot from 2018-09-13 15-10-46](https://user-images.githubusercontent.com/35022/45513201-a73b5c80-b767-11e8-941b-cb2a4e736851.png)

Should we show the collectors as "offline" or so, when the underlying sidecar instance is not there?

## Your Environment

* Graylog Version: 3.0.0-alpha.2-SNAPSHOT+73c96fa

**Comment by edmundoa** [comment]
Closing, as this seems to be the same issue as #5097. The current master should handle this situation, or at least be much more helpful with it.
