### ISSUE TITLE
Permissions by streams

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#511]
This is not an issue, but is more a feature request:

When you have an environment with a lot of users, is very difficult to set permissions per user.

An example:

You have stream A, and Stream B, with users A, B, C and D. You have to enter on each user to give him the correct permissions, as it would to be easier to set permissions directly on the Stream, entering on that and editing the stream and dashboard permissions.

Even, If you need to see who have access to what (like who can access the Production Logs Stream), you have to enter on each user to see if it have any permission on that stream, when It would to be easier to go directly to that stream and have a permissions field, to see who have read and write permission on that object.

Thanks in advice :)

**Comment by bernd** [comment]
We are currently working on role support which will fix this issue. Please use #1321 for tracking the progress. Thank you!
