### ISSUE TITLE
Do not allow content pack deletion if an installation exists

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#5116]
## Expected Behavior

A use should not be able to delete a content pack revision from the database as long as there is an active installation.

## Current Behavior

A user can delete a content pack revision from the database even though there is an installation record for it. That also means there is no way to get rid of the installation state in the database and the user is also unable to uninstall the content pack anymore.

## Steps to Reproduce (for bugs)

1. Create content pack
2. Upload content pack
3. Install content pack
4. Delete content pack

## Context

We will most probably need the content pack that has been used for an installation in the future to implement new features like upgrades.

This should be enforced in the UI and the server backend.

## Your Environment

* Graylog Version: 3.0.0-alpha.2-SNAPSHOT (rev 0dbe6f659)

**Comment by kmerz** [comment]
Solving this in the GUI as well just like 'Delete an used Index'
