### ISSUE TITLE
DNS resolver does not work with internal domain suffixes

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5124]
I'm getting this error when trying to perform a lookup on my router:

```
2018-09-17 17:06:42,148 ERROR: org.graylog.plugins.DnsLookupDataAdapter - Could not perform reverse DNS lookup for [172.4.43.184]
java.lang.IllegalStateException: Not under a registry suffix: pfsense.localdomain
```

I'd expect local domain suffixes to work. Have we tested if this works with internal addresses? For example, my local DNS resolver will resolve the IP "172.16.0.120" to the name of my local workstation, without a domain suffix. Just the hostname itself.

**Comment by danotorrey** [comment]
This is fixed in the latest version of the DNS Lookup adaptor.

**Comment by lennartkoopmann** [comment]
Thanks!! :)

**Comment by lennartkoopmann** [comment]
![screenshot_1](https://user-images.githubusercontent.com/35022/45654184-3ade9700-baa0-11e8-8aec-78a478efe59f.png)

Yes, that works. Thanks again!
