### ISSUE TITLE
Graylog can not search the ES data.

### ISSUE THREAD

**Issue by koreantramp** [Graylog2/graylog2-server#5138]
## Expected Behavior
Searching data.

## Current Behavior
Can't searching data.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Currently, there's no input data and I just search data from ES.
Because, ES has lots of past data already.

I configured graylog conf(server.conf) and ES conf.
But Graylog can not select(search) the data from the ES.

What is the problem?

## Your Environment
* Graylog Version: 2.4
* Elasticsearch Version: 5.6
* MongoDB Version: 3.6
* Operating System: CentOS 7
* Browser version: Chrome 69

**Comment by jalogisch** [comment]
Graylog will only display data that is ingested via Graylog - it is not a generic frontend for Elasticsearch.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
