### ISSUE TITLE
Search in stream on 1 day is not returning any message

### ISSUE THREAD

**Issue by eduault** [Graylog2/graylog2-server#5140]
Search in stream on 1 day is not returning any message

## Expected Behavior
Web Interface : The messages received in a stream during last 24h which are displayed when the user searches on 2 days should be displayed when the user searches on 1 day.

REST API (Using REST API browser) : The messages which are returned using GET /search/universal/relative in a stream on 2 days and which are less than 24h old should also be returned when the search is on 1 day.

## Current Behavior
Web Interface :
- When the user searches on 2 days in a stream, some of the messages which are displayed are less than 24h old.
- When the user searches on 1 day in the same stream, no message is displayed

![2018-09-20 10_35_22-graylog - stream scg communications - search in the last 2 days](https://user-images.githubusercontent.com/29234693/45809939-c25b1e80-bcc9-11e8-9cc9-67c7cc217f84.png)
![2018-09-20 10_34_54-graylog - stream scg communications - search in the last 1 day](https://user-images.githubusercontent.com/29234693/45809938-c25b1e80-bcc9-11e8-9625-788329b2e5da.png)

REST API (Using REST API browser) :
- When the administrator searches on 2 days in a stream, some of the messages which are returned are less than 24h old
- When the administrator searches on 1 day in the same stream, no message is returned

## Steps to Reproduce (for bugs)

Prerequisites :
1. The administrator configures a stream.
2. Some messages are received by GELF.

Web Interface :
1. The user searches on 2 days in this stream. Some of the messages histogram which are displayed are less than 24h old.
2. The user searches on 1 day in this stream. No message is displayed.

REST API (Using REST API browser) :
1. The administrator searches on 2 days in this stream, using GET /search/universal/relative operation, with and JSON Response Content Type, and those parameters:
- query	streams:5b8cf9d461d4970cb039a5c4
- range	172800
2. Called URL is http://ip:9000/api/search/universal/relative?query=streams%3A5b8cf9d461d4970cb039a5c4&range=172800&sort=timestamp%3Adesc&decorate=true
3. Some of messages which are returned are are less than 24h old.
4. The administrator searches on 1 day in this stream, using GET /search/universal/relative operation, with and JSON Response Content Type, and those parameters:
- query	streams:5b8cf9d461d4970cb039a5c4
- range	86400
5. Called URL is http://ip:9000/api/search/universal/relative?query=streams%3A5b8cf9d461d4970cb039a5c4&range=86400&sort=timestamp%3Adesc&decorate=true
6. No message is returned.

## Context
I discovered this issue using Graylog in my company (I'm the administrator).

## Your Environment
* Graylog Version: 2.4.6+ceaa7e4, codename Wildwuchs
* JVM: Oracle Corporation 1.8.0_172 on Linux 3.13.0-153-generic
* Elasticsearch Version:  Version: 5.6.3 (provided with Graylog AMI)
* MongoDB Version: v3.4.9 (provided with Graylog AMI)
* Operating System: Ubuntu on AWS (Linux graylog 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
* Browser version: Firefox, on a Windows PC in a business environment (proxy + firewall + security tools ...)

**Comment by eduault** [comment]
I have more details:
- this bug is reproducible with the default search too (i.e. not in a stream)
- a query on Graylog' ElasticSearch indexes returns some data, but a search in Graylog Web interface returns no data

ubuntu@graylog:~/scripts$ curl -X GET http://172.20.128.41:9200/graylog_1/_search -d '
{
    "query": {
        "range": {
            "creationDate": {
                "gte": "2018-09-20",
                "lt": "2018-09-21"
            }
        }
    },
    "size": 0
}'
{"took":8,"timed_out":false,"_shards":{"total":4,"successful":4,"skipped":0,"failed":0},"hits":{"total":30659,"max_score":0.0,"hits":[]}}

**Comment by eduault** [comment]
I have more details:
- this bug is reproducible with the default search too (i.e. not in a stream)
- a query on Graylog' ElasticSearch indexes returns some data, but a search in Graylog Web interface returns no data

ubuntu@graylog:~/scripts$ curl -X GET http://ip:9200/graylog_1/_search -d '
{
    "query": {
        "range": {
            "creationDate": {
                "gte": "2018-09-20",
                "lt": "2018-09-21"
            }
        }
    },
    "size": 0
}'
{"took":8,"timed_out":false,"_shards":{"total":4,"successful":4,"skipped":0,"failed":0},"hits":{"total":30659,"max_score":0.0,"hits":[]}}

**Comment by jalogisch** [comment]
Could you please check the field `timestamp` of this messages?

Graylog is taking this as source for the time it searches in and not any other information that might be available. So if you receive messages that contain a timestamp in the future Graylog will not find them unless you select this period in the exact dates.

**Comment by eduault** [comment]
This search in the Web interface works :
- time range: Relative, Search in all messages
- Query: timestamp:["2018-09-20 00:00:00.000" TO "2018-09-21 00:00:00.000"]

But this search in the Web interface doesn't works :
- time range: Absolute, 2018-09-20 00:00:00 to 2018-09-21 00:00:00
- Query: <empty>

**Comment by jalogisch** [comment]
thank you for clarification. 

For me this sounds like a bug. We will investigage.

**Comment by eduault** [comment]
Thank you.

**Comment by eduault** [comment]
For your information, my Graylog server has 2 indexes, graylog_0 and graylog1.

I recently used the attached script to delete some values is ElasticSearch.
[purge_graylog_data_in_ES_original.txt](https://github.com/Graylog2/graylog2-server/files/2404732/purge_graylog_data_in_ES_original.txt)
I found this script in Graylog community : https://community.graylog.org/t/deleting-logs-from-graylog-elasticsearch-a-howto/2318

And I also had graylog_0 index left with "blocks.write" : false for some time.

**Comment by eduault** [comment]
For your information, I'm sending the messages in Graylog using GELF HTTP. The messages timestamp can be set to a few days ago.

**Comment by eduault** [comment]
According to ElasticSearch documentation, I should not have used forcemerge on the current Graylog index (graylog_1).
![2018-09-24 10_42_46-graylog - index set - default index set](https://user-images.githubusercontent.com/29234693/45944006-dfa12d00-bfe8-11e8-8cb5-356d91a08e61.png)

And searching using the time range in Graylog Web interface doesn't return any message lass than 5 days old.
Is there a relation ?

**Comment by eduault** [comment]
Maybe I shouldn't have used the forcemerge API on active index (graylog_1).

I found this in the Curator Reference (https://www.elastic.co/guide/en/elasticsearch/client/curator/5.x/forcemerge.html):
A forcemerge should never be executed on an index that is actively receiving data. It should only ever be performed on indices where no more documents are ever anticipated to be added in the future.

Even if there is no such advice in the force merge API documentation (https://www.elastic.co/guide/en/elasticsearch/reference/5.6/indices-forcemerge.html).

**Comment by eduault** [comment]
I solved the problem using this procedure :

1. in REST API browser : POST /system/deflector/cycle
2. in Web interface, recalculate index ranges of old index (graylog_1) (maybe this step was not useful)

In order to avoid this kind of error, you should provide a clear and tested procedure about how we should proceed to delete data in Graylog's ElasticSearch indices, both in old and current indices.

And perhaps a way to recalculate index ranges of the current index.

**Comment by jalogisch** [comment]
we will add some parts into the documentation that will highlight that you need to recalculate the index range after you had tampered with the elasticsearch indicies.

**Comment by eduault** [comment]
Thank you.
Can you add some recommendations about the procedure that we should use to delete some messages in ElasticSearch, including temporary modifications of blocks.write flag of the graylog indices except the current one ?

**Comment by dennisoelkers** [comment]
As this is related to the old search code and does not seem to have been a bug/issue with the product, I am closing this issue.
