### ISSUE TITLE
GELF HTTP input does not support GZIP

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5143]
The GELF HTTP input in v3.0 returns a `HTTP 404` when receiving GZIP compressed POST requests. The same input in v2.4.6 handles GZIP correctly.

**Comment by bernd** [comment]
This is probably related to the upgraded Netty version in 3.0.

**Comment by lennartkoopmann** [comment]
@bernd @kroepke: Do you think we should leave this in 3.0? Please move it accordingly. Thank you!

**Comment by bernd** [comment]
@lennartkoopmann @kroepke Since this is a regression (it worked in 2.x) we should fix this. I guess this is a result of the netty update to version 4.x.
