### ISSUE TITLE
Old index is not marked as read only

### ISSUE THREAD

**Issue by markuchi** [Graylog2/graylog2-server#5145]
We have found some indexes are failing to be set as read only under certain conditions.
After a rolling restart of elasticsearch we found that logs were not being shipped to elasticsearch. Logs were being held in logs of Graylog.
Graylog server needed to be restarted to fix. 
However a couple times the active write index needed to be manually rotated before logs would flow in.

Normally we see in the logs "Flushed and set <graylog_183> to read-only"
When we needed to manually rotate the index the setting to read-only did not trigger.

We have only had to do this a couple times during rolling restarts but otherwise the system has been working fine.
It is extremely important that index only have the data for only the time periods for which they were the active write index. 
Maybe some form of maintenance task that checks for this periodically and warns the user of indexes not set as read only? 

* Graylog Version:  2.4.6+ceaa7e4, codename Wildwuchs
* Elasticsearch Version: 5.6
* MongoDB Version:  3.6.5
* Operating System: CentOS 7.-5.1804

**Comment by jalogisch** [comment]
@markuchi would you please describe clearly how we can reproduce this behavior with some clear instructions. 

With your current description, it is not possible for us to make a clear statement if this is a bug or not.

**Comment by markuchi** [comment]
We are not 100% sure how to replicate. 
It seems to be related to when you do a manual rotation of an active write index. 
We have had a few instances where after doing a rolling restart of elasticsearch, graylog is unable to send logs to ES and either restarting the whole server or rotating the active write index fixes this.
The times where we had to do this seems to line up with the indexes that were not set to read only.

I would imagine for anyone who has compliance requirements for storage of logs ensuring that only active write indexes are written to is of extreme importance. 
Some sort of task that goes back and checks if all indexes are read only or not would help greatly even if this potential bug is fixed and other bugs are found surrounding the same issue.
Maybe when the periodical maintenance is performed by the master the read only check can be performed?

At what interval do maintenance tasks occur and is index recalculation part of this?

**Comment by jalogisch** [comment]
You did not give much information that we can reproduce this situation. Without knowing what causes the issue we will not implement something that might help or might harm ... 

This will be put on `to-verify` but you will help us when you provide a reproducible description.

**Comment by markuchi** [comment]
If it happens again will try and get more information. until then we will have to do our own periodic checks on the indexes to ensure they are read only.

**Comment by bernd** [comment]
This didn't show up again at the issue creators setup so we are closing the issue. Please open a new issue if this becomes a problem again. Thank you!
