### ISSUE TITLE
+ (plus) sign in MongoDB password makes Graylog unreachable

### ISSUE THREAD

**Issue by eduault** [Graylog2/graylog2-server#5147]
## Expected Behavior
Graylog should work correctly after the "graylog-ctl set-mongodb-password" command, or provide an error message if the parameters to this command are incorrect.

## Current Behavior
Graylog accepts a + (plus) sign in the password of "graylog-ctl set-mongodb-password" command, but Graylog Web interface is not working anymore after that. It seems to initialize forever.

## Possible Solution
For main issue:
- Forbid + sign in password of "graylog-ctl set-mongodb-password" command, with an error message
- or fix the way Graylog is using this password (escape it in some commands ?)

## Steps to Reproduce (for bugs)
1. Pre-requisite : Graylog Web interface is working without any MongoDB password configured 
2. graylog-ctl set-mongodb-password -a -u admin -p aaa+bbb
3. graylog-ctl set-mongodb-password -g -u graylog -p aaa+bbb
4. graylog-ctl reconfigure
5. Try to connect to the Web interface => KO : Graylog seems to initialize forever
6. graylog-ctl set-mongodb-password -a -u admin -p aaabbb
7. graylog-ctl set-mongodb-password -g -u graylog -p aaabbb
8. graylog-ctl reconfigure
9. Try to connect to the Web interface => OK

## Context
I discovered this issue configuring my Graylog server.

## Your Environment
* Graylog Version: 2.4.6+ceaa7e4, codename Wildwuchs
* JVM: Oracle Corporation 1.8.0_172 on Linux 3.13.0-153-generic
* Elasticsearch Version:  Version: 5.6.3 (provided with Graylog AMI)
* MongoDB Version: v3.4.9 (provided with Graylog AMI)
* Operating System: Ubuntu on AWS (Linux graylog 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
* Browser version: Firefox, on a Windows PC in a business environment (proxy + firewall + security tools ...)

**Comment by Nihlander** [comment]
If I remember correctly, special characters have to be URL encoded so, in place of the '+' symbol put '%2B'.
It is not a perfect solution but, it can be used as a work around until the issue is resolved.

**Comment by jalogisch** [comment]
This issue was moved to Graylog2/omnibus-graylog2#62
