### ISSUE TITLE
LDAP settings are deleted by graylog-ctl commands, and it is not possible to reconfigure them anymore

### ISSUE THREAD

**Issue by eduault** [Graylog2/graylog2-server#5148]
LDAP settings are deleted by graylog-ctl commands, and it is not possible to reconfigure them anymore

## Expected Behavior
- Graylog LDAP settings should be kept as they are by graylog-ctl commands.
- And saving a new LDAP settings should have worked.

## Current Behavior
- Graylog LDAP settings displayed in Web interface are deleted by graylog-ctl commands (see Steps to Reproduce). And LDAP authentication is no more working. But there is still a document in MongoDB ldap_settings collection !
- And saving a new LDAP settings doesn't work anymore. I even had duplicated LDAP settings documents in Graylog MongoDB, and no workaround for this issue, other than deleting the LDAP configurations documents directly in MongoDB.

## Possible Solution
- For main point, I have no solution.
- But for duplicated LDAP settings problem, never register 2 LDAP configurations in Graylog MongoDB, because this completely blocks the LDAP Authentication. Graylog should always allow only 1 LDAP configurations in Graylog MongoDB when it is written.

## Steps to Reproduce (for bugs)
1. Pre-requisite : Graylog Web interface is working with an LDAP settings and some configured users authenticating using Active Directory, but without any MongoDB password configured, but there is. (and server-secret, hashed admin-password had been written directly in /opt/graylog/conf/graylog.conf)
2. graylog-ctl set-server-secret d53780a4...a3b28
3. graylog-ctl set-admin-password aaa+bbb
4. graylog-ctl set-mongodb-password -a -u admin -p aaabbb
5. graylog-ctl set-mongodb-password -g -u graylog -p aaabbb
6. graylog-ctl reconfigure
7. User abcd tries to connect using his Active Directory password => He get a "Invalid credentials, please verify them and retry." message
8. Admin user connects to Graylog MongoDB => There is a document in MongoDB ldap_settings collection !
9. Admin user connects to the Web interface, in Authentication Management > LDAP Settings page => The settings have disappeared
10. In the Web interface, the Admin registers the LDAP settings again, and save => "LDAP settings saved successfully" is displayed
11. In the Web interface, the Admin leaves the "LDAP Settings" page and reopens the "LDAP Settings" page => it is empty
12. Admin user connects to Graylog MongoDB => There are 2 documents in MongoDB ldap_settings collection !

## Context
I discovered this issue configuring my Graylog server.

## Your Environment
* Graylog Version: 2.4.6+ceaa7e4, codename Wildwuchs
* JVM: Oracle Corporation 1.8.0_172 on Linux 3.13.0-153-generic
* Elasticsearch Version:  Version: 5.6.3 (provided with Graylog AMI)
* MongoDB Version: v3.4.9 (provided with Graylog AMI)
* Operating System: Ubuntu on AWS (Linux graylog 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
* Browser version: Firefox, on a Windows PC in a business environment (proxy + firewall + security tools ...)

**Comment by jalogisch** [comment]
This issue was moved to Graylog2/omnibus-graylog2#63
