### ISSUE TITLE
Incorrect error message in login page when LDAP/Active Directory server is unreachable

### ISSUE THREAD

**Issue by eduault** [Graylog2/graylog2-server#5156]
## Expected Behavior
When a user authenticates in Graylog Web interface and the LDAP/Active Directory server is unreachable, the error message that is displayed should invoke a technical problem.

## Current Behavior
When a user authenticates in Graylog Web interface and the LDAP/Active Directory server is unreachable, the error message that is displayed is "Invalid credentials, please verify them and retry".

![2018-09-26 10_02_52-graylog - sign in](https://user-images.githubusercontent.com/29234693/46069049-ef507b00-c17a-11e8-847f-5d06c0cd06df.png)

## Possible Solution
Modify the error message.

## Steps to Reproduce (for bugs)
1. Try to authenticate in Graylog Web interface when the LDAP/Active Directory server is unreachable (timeout problem, cf. attached log file). 
[current_extract.txt](https://github.com/Graylog2/graylog2-server/files/2418902/current_extract.txt)

## Context
I discovered this issue using Graylog in my company (I'm the administrator).

## Your Environment
* Graylog Version: 2.4.6+ceaa7e4, codename Wildwuchs
* JVM: Oracle Corporation 1.8.0_172 on Linux 3.13.0-153-generic
* Elasticsearch Version:  Version: 5.6.3 (provided with Graylog AMI)
* MongoDB Version: v3.4.9 (provided with Graylog AMI)
* Operating System: Ubuntu on AWS (Linux graylog 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
* Browser version: Firefox, on a Windows PC in a business environment (proxy + firewall + security tools ...)

**Comment by jalogisch** [comment]
is LDAP the only available authentication source or did you have other still available?

If other are present it would not be helpful to display that LDAP is not reachable when the user still can use another authentication provider.

**Comment by eduault** [comment]
LDAP is the only authentication source that we use (excepted for the admin user). But I did not deactivate the other sources.

Graylog knows that I'm authenticating using LDAP : in the users collection in MongoDB, there is this document :
{
    "_id" : ObjectId("5b7ec7850503e40b11724229"),
    "password" : "User synced from LDAP.",
	...,
    "username" : "eduault"
}

**Comment by florianvolle** [comment]
Closing this as we have multiple authentication methods available and you do not want to expose that in an error message for security reasons.

**Comment by eduault** [comment]
This message would not pose any security risk : "Graylog experienced a technical problem. Please retry later, and contact the responsible if the problem still exists.".
