### ISSUE TITLE
Fix alignment in content pack create form

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#5157]
While playing with #5153, I noticed an alignment issue in the create content pack form:

<img width="636" alt="screen shot 2018-09-26 at 14 35 16" src="https://user-images.githubusercontent.com/716185/46080971-95ac7880-c19b-11e8-86dd-a109d8085a03.png">

* Graylog Version: Graylog 3.0.0-alpha.3-SNAPSHOT (d78f44302802df14b86d328a974acfc94346fd48)

**Comment by bernd** [comment]
@kmerz I guess this can be closed? It has been moved to DONE in the project but I don't see any pull request reference.

**Comment by kmerz** [comment]
Fixed by: Refs #5295
