### ISSUE TITLE
Can't change web_endpoint_uri after setting up first time

### ISSUE THREAD

**Issue by a9tm** [Graylog2/graylog2-server#5159]
After installation of graylog-server, I set `web_endpoint_uri = http://graylog.example.net` and I can access it to finish setting up. But then now I want to change the endpoint to `https://logs.example.net`  I can't access to new endpoint.

## Expected Behavior

Access to new URI after changing the `web_endpoint_uri` and restarting graylog-server.service

## Current Behavior

I can only access to old URI

## Steps to Reproduce (for bugs)

1. fresh install graylog-server
2. set `web_endpoint_uri = http://graylog.example.net`
3. setting up graylog
4. change `web_endpoint_uri = https://logs.example.net`
5. restart graylog-server.service then open new URI

## Your Environment

* Graylog Version: 2.4.6
* Elasticsearch Version: 5.6
* MongoDB Version: 2.6
* Operating System: Ubuntu 16.04
* Browser version: Firefox 61

**Comment by jalogisch** [comment]
You are able to change all settings without any problems - but you might need to adjust other settings to make it work.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by a9tm** [comment]
@jalogisch what settings?
