### ISSUE TITLE
Collector Configuration -> "Filebeat quick reference" documentation link is wrong

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#5162]
It currently links to the Pipeline Rules documentation.

We could link towards the elastic filebeats documentation here.
But since the configuration page is shared for all kinds of collectors (NXlog, winlogbeat, etc)
we might need to rethink that.

**Comment by jalogisch** [comment]
We should split the one-page description into multiple pages to make this easy
