### ISSUE TITLE
"Page not found" error when a user tries to create a notification

### ISSUE THREAD

**Issue by eduault** [Graylog2/graylog2-server#5170]
## Expected Behavior
The notification should be created when a user tries to create one, using the "Add new notification" button in the Web interface.
Or the "Add new notification" button should not be displayed if the user is not allowed to create one.

## Current Behavior
A "Page not found" is displayed when the a user tries to create a notification.
But the creation of the notification works when the admin user is doing it.

## Possible Solution
Remove the "Add new notification" button if the user don't have the rights to create one.
Or fix the issue when a user tries to create a notification.

## Steps to Reproduce (for bugs)
1. A user which is not the administrator (with no admin role) connects to the "Alerts" screen.
2. The user clicks on "Manage notifications" button
3. The user clicks on "Add new notification" button
4. The user fills the form : 
Notify on stream : "stream1"
Notification type : "Email Alert Callback"
5. The user clicks on "Add alert notification"
6. The user fills the "Create new Email Alert Callback" form : 
Title : notification1
E-Mail Receivers(optional) : john.doe@example.com
(all other fields left with the default values)
7. The user clicks on "Save"
8. An "Page not found" error page  is displayed.

![image](https://user-images.githubusercontent.com/29234693/46338281-02a68f00-c630-11e8-838a-982c1fb6fd59.png)

## Context
I discovered this issue using Graylog in my company (I'm the administrator).

## Your Environment
* Graylog Version: 2.4.6+ceaa7e4, codename Wildwuchs
* JVM: Oracle Corporation 1.8.0_172 on Linux 3.13.0-153-generic
* Elasticsearch Version:  Version: 5.6.3 (provided with Graylog AMI)
* MongoDB Version: v3.4.9 (provided with Graylog AMI)
* Operating System: Ubuntu on AWS (Linux graylog 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
* Browser version: Firefox, on a Windows PC in a business environment (proxy + firewall + security tools ...)

**Comment by edmundoa** [comment]
I have tried to reproduce this issue but I couldn't, it worked as expected. Do you see any errors in your browser JS console or in your Graylog server logs?

**Comment by jalogisch** [comment]
In addition, it would be nice to know what roles and rights does the user has that gets this error.

**Comment by eduault** [comment]
Here are the messages in the browser JS console :

Input elements should have an id prop, generating one for you Input.jsx:8:2
Input elements should have an id prop, generating one for you Input.jsx:8:2
Input elements should have an id prop, generating one for you Input.jsx:8:2
window.controllers/Controllers est obsolète. Veuillez ne pas l’utiliser pour détecter l’agent utilisateur (UA). index.js:1362
Input elements should have an id prop, generating one for you Input.jsx:8:2
Input elements should have an id prop, generating one for you Input.jsx:8:2
Input elements should have an id prop, generating one for you Input.jsx:8:2
Input elements should have an id prop, generating one for you Input.jsx:8:2
L’objet « Components » est obsolète. Il sera bientôt supprimé. conditions
Input elements should have an id prop, generating one for you Input.jsx:8:2
in Startnull main.js:42:5
[Afficher/Masquer les détails du message.] SyntaxError: redeclaration of var nextPromptResult prompt.js:1:1
There was an error fetching a resource: cannot POST http://ip:9000/api/streams/5b7ecca20503e40b117247c1/alarmcallbacks (403). Additional information: Not authorized to access resource id <5b7ecca20503e40b117247c1> FetchProvider.js:17:6
Unhandled rejection _onSubmit/<@http://ip/assets/15.0cbba45d8aad71248f6d.js:1:33401
o@http://ip/assets/app.0cbba45d8aad71248f6d.js:25:73001
[22]</n.exports/i.prototype._settlePromiseFromHandler@http://ip/assets/app.0cbba45d8aad71248f6d.js:25:46320
[22]</n.exports/i.prototype._settlePromise@http://ip/assets/app.0cbba45d8aad71248f6d.js:25:47120
[22]</n.exports/i.prototype._settlePromise0@http://ip/assets/app.0cbba45d8aad71248f6d.js:25:47819
[22]</n.exports/i.prototype._settlePromises@http://ip/assets/app.0cbba45d8aad71248f6d.js:25:49035
[2]</r.prototype._drainQueue@http://ip/assets/app.0cbba45d8aad71248f6d.js:25:2806
[2]</r.prototype._drainQueues@http://ip/assets/app.0cbba45d8aad71248f6d.js:25:2864
r/this.drainQueues@http://ip/assets/app.0cbba45d8aad71248f6d.js:25:1000
A/</<@http://ip/assets/polyfill.0cbba45d8aad71248f6d.js:1:67762
A/<@http://ip/assets/polyfill.0cbba45d8aad71248f6d.js:1:67632
a@http://ip/assets/polyfill.0cbba45d8aad71248f6d.js:1:26584
bluebird.js:1545 

![image](https://user-images.githubusercontent.com/29234693/46423623-4506c380-c737-11e8-9ee1-8d4b936b53da.png)

**Comment by eduault** [comment]
The user is a normal user authenticated using Active Directory. His profile was modified after his authentication in Graylog Web interface.
He has 2 roles :
- Reader
- Business user
The Business User role only adds some rights to read some streams ans dashboards.

**Comment by edmundoa** [comment]
Thank you for sharing those details with us!

For what I can see, this situation happens because the user can read some streams (included `5b7ecca20503e40b117247c1`), but does not have permissions to edit the selected stream. As notifications and conditions are tightly associated to streams, users need edit stream permissions in order to create new notifications and conditions.

On our side, I think we should modify that page to only display streams the user is allowed to edit, in that case we can avoid this situation.

**Comment by bernd** [comment]
This shouldn't be an issue anymore with the new events and alerts system.
