### ISSUE TITLE
Sorting on field just after index rotation returns an error

### ISSUE THREAD

**Issue by eduault** [Graylog2/graylog2-server#5175]
## Expected Behavior
Graylog should not return any error in this case.

## Current Behavior
Sorting on a field is not working after index rotation, and no new message since the rotation.
Searching in Graylog REST API Browser with a sort returns this error :

Request URL : http://172.20.209.67:9000/api/search/universal/relative?query=source%3Aspectre&range=1000000000&limit=1&sort=creationDate%3Adesc&decorate=true

Response Code : 500

Response Body :
```
{
  "message": "Unable to perform search query\n\nNo mapping found for [creationDate] in order to sort on",
  "details": [
    "No mapping found for [creationDate] in order to sort on"
  ]
}
```

![image](https://user-images.githubusercontent.com/29234693/46476942-ae470f00-c7e9-11e8-8966-f12f27b95dae.png)

## Possible Solution
The solution should not resolve only this specific scenario, but insure that this mapping error never (or rarely) happens .
- Regularly verify that in ElasticSearch that the mapping for each field name is existing ?
- When there is such an error, create the missing mapping in ElasticSearch ?

## Steps to Reproduce (for bugs)
1. Have an index set with an index : graylog_0
2. The administrator rotates the index in the Web interface (System > Indices > Default index set > Maintenance > Rotate active write index)
3. The administrator searches some messages in Graylog REST API Browser with a sort

![image](https://user-images.githubusercontent.com/29234693/46477514-19451580-c7eb-11e8-9fa3-2e78ca9a3977.png)

4. Graylog server returns an error : 
"Unable to perform search query\n\nNo mapping found for [creationDate] in order to sort on",
"No mapping found for [creationDate] in order to sort on"

![image](https://user-images.githubusercontent.com/29234693/46477557-337ef380-c7eb-11e8-8a60-7d7c6fdfdbc1.png)

## Context
I discovered this issue using Graylog in my company (I'm the administrator).

## Your Environment
* Graylog Version: 2.4.6+ceaa7e4, codename Wildwuchs
* JVM: Oracle Corporation 1.8.0_172 on Linux 3.13.0-153-generic
* Elasticsearch Version:  Version: 5.6.3 (provided with Graylog AMI)
* MongoDB Version: v3.4.9 (provided with Graylog AMI)
* Operating System: Ubuntu on AWS (Linux graylog 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
* Browser version: Firefox, on a Windows PC in a business environment (proxy + firewall + security tools ...)

**Comment by bernd** [comment]
This should work with Graylog 3.3. Please open a new issue if you still see problems with that version. Thank you!
