### ISSUE TITLE
Alerts not working for Windows EventID Field

### ISSUE THREAD

**Issue by ortizleo** [Graylog2/graylog2-server#5180]
Hello.
Im trying to configure alerts for specifics Windows EventID logs, but it not work. Others alerts works, using channel or source, but with EventID the alert is not triggered, what is the problem?

Yes, the stream are receiving the logs right.
No, nothing in graylog server.log.
Others alerts works.

## Expected Behavior
Receive alerts of specifics windows EventID.

## Current Behavior
With EventID field the alert not work, with others fields it works...

## Steps to Reproduce (for bugs)
1. Send windows log to Graylog with NXLog
2. Configure a stream with index
3. Configure Alert condition with: Field=EventID, Value=4722 (example), Backlog=1, Grace period=0

* Graylog Version: 2.4.6
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Centos
* Browser version: Chrome 6x

![condition](https://user-images.githubusercontent.com/17042298/46540707-7cd54e80-c890-11e8-984b-c5c38632f2ad.png)
![stream and eventid query](https://user-images.githubusercontent.com/17042298/46540708-7cd54e80-c890-11e8-8e51-91a8d82e99ad.png)
![teste - condition](https://user-images.githubusercontent.com/17042298/46540709-7d6de500-c890-11e8-8a06-59c6badb7506.png)

**Comment by ortizleo** [comment]
Hello.
It back works when I run a "yum update", maybe some broken package? 
Java and mongodb was updated too.

**Comment by jalogisch** [comment]
I take your message @ortizleo as "all is working fine now".

Will close this issue. Please re-open if you still have issues and explain what does not work as you expected.
