### ISSUE TITLE
Content pack "More action" menu confusing

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#5191]
## Expected Behavior
I previously installed a content pack and expected the action menu to allow me to uninstall it, but it only allows me to "Remove all".
From the action buttons it's also not clear how to get to the uninstall process (you need to click on the title on the other side of the screen and then uninstall).

## Current Behavior
![image](https://user-images.githubusercontent.com/52014/46727158-39a82080-cc80-11e8-9d73-0827c4c71359.png)

The action menu has a "Remove all" entry, which is confusing, because it's unclear what "all" is. All content packs? All installed entities?

## Possible Solution

Rename the "Remove all" entry to "Delete content pack".
Either add "Uninstall..." option to show the detail page, or otherwise make it clear how to get there.

**Comment by kmerz** [comment]
Uninstall can't be add since a user can't uninstall all installations of a content pack. Leaving the second option to make it clear. 

I would suggest to display the count of installations in the row, as a link which directs to the show page.

**Comment by kroepke** [comment]
Sounds good to me :)
