### ISSUE TITLE
Buffer HTTP Callback alerts

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#5192]
## Expected Behavior
If the target for HTTP Callback alert is not reachable Graylog should buffer the Callbacks and retry

## Context
When using Graylog HTTP Callbacks to start Workflows in tools like "the hive" (https://thehive-project.org/) and the connection is not possible it would be nice to not lose the alerts and having Graylog retry the alerting until a successful delivery.

## Your Environment

* Graylog Version: 2.4.6

**Comment by florianvolle** [comment]
@bernd This is relevant for the new alerting

**Comment by bernd** [comment]
The new alerting system in 3.2 is using a scheduler that retries notifications if there are temporary errors. I am closing this issue, please open a new one if this is still an issue with 3.3 or the upcoming 4.0 release. Thank you!
