### ISSUE TITLE
Content pack plugin-version constraint doesn't show plugin name

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#5195]
## Expected Behavior

The user should see the which plugin is required to install a content pack. Not just the version number. Otherwise the user doesn't know which plugin to install.

## Current Behavior

The list of content pack constraints doesn't show the name of the required plugin for the "plugin-name" constraint.

![image](https://user-images.githubusercontent.com/461/46747744-5a896980-ccb2-11e8-8906-c761d3bc714d.png)

## Steps to Reproduce (for bugs)

1. Create content pack that uses entities from a plugin
2. View content pack details

## Your Environment

* Graylog Version: 3.0.0-alpha.3-SNAPSHOT (rev 7e0701b81)

**Comment by kmerz** [comment]
Fixed by #5076
