### ISSUE TITLE
Feature Request: Saved searches visible to only the users who created them or in their stream

### ISSUE THREAD

**Issue by geekasso** [Graylog2/graylog2-server#520]
Saved searches should only be restricted to the users who created them or limited to their accessible stream

**Comment by pdepaepe** [comment]
+1

**Comment by sqldiablo** [comment]
+1 - Users with read-only roles can edit and delete all saved searches across the system, and not just their own. It would be great if it were configurable whether a given role and add, edit, delete, or view\use a saved search within various scopes (streams, inputs, etc.), and whether those saved searches are only visible to them or if they're global saved searches that any user can view\use.

**Comment by obieeclark** [comment]
+1

**Comment by NickMeves** [comment]
You guys have done a great job putting in top of the line enterprise permissions and access management.  This is probably one of the last security holes stopping me from getting more traction getting this system officially adopted in my organization.

**Comment by victor-mendes-eduardo** [comment]
+1

**Comment by rcicm** [comment]
+1

**Comment by Dougoc** [comment]
+1

**Comment by Racle** [comment]
+1

**Comment by Olentzero** [comment]
+1

**Comment by christophetd** [comment]
Any update on this issue?

**Comment by Vergil333** [comment]
+1

**Comment by osscombat** [comment]
wow 5 years for a feature request?!
+5

**Comment by gatis** [comment]
+1

**Comment by phanidileep** [comment]
+1
