### ISSUE TITLE
Feature request - Notify when an alert is resolved

### ISSUE THREAD

**Issue by annedroiid** [Graylog2/graylog2-server#5200]
It would be great to be able to get a notification when an alert condition is no longer occurring, as well as when it starts.

## Expected Behavior
When you set up a notification for an alert condition, there is an option to notify when the alert is closed.

## Current Behavior
This option does not exist. You will never be notified when an alert resolves itself.

## Context
We use PagerDuty for all of our alerts, and we have notification rules set up in Graylog so that an Incident is created when an alert goes off. However since a notification is not sent when the issue is resolved (like we get with our alerts from AWS and NewRelic) we have to manually go in and close them ourselves. It means that all of our statistics about how long incidents last and how long it takes to resolve are completely wrong, as if an incident happens in the night it won't be resolved until someone gets in in the morning. In addition, if the incident happens in the night and quickly resolves itself it means that we waste time in the morning investigating an incident that is no longer occurring. 

I have seen people suggesting before that you have another alert for the opposite of the error condition (so that you're notified when it's back to normal) but this will not work with PagerDuty.

**Comment by florianvolle** [comment]
@bernd This is relevant for the new alerting.

**Comment by bernd** [comment]
The new alerting and events system doesn't have the concept of a resolved alert anymore. But you can setup a event definition that creates a new event and sends a notification if a state changes.
