### ISSUE TITLE
AD Nested Groups

### ISSUE THREAD

**Issue by Wicht78** [Graylog2/graylog2-server#5204]
It would be helpful if it were possible to use an AD group in Graylog that contains AD groups itself.

Currently these permissions are not applied.
In most companies, there are existing groups which are assigned to users. These would be then authorized in the AD group for GrayLog, since this minimizes an administrative effort.

* Graylog Version: 2.6
* Elasticsearch Version: 5.x

**Comment by jalogisch** [comment]
dup of: https://github.com/Graylog2/graylog2-server/issues/1436 closing this.
