### ISSUE TITLE
Alarms are dependent on the stream processing rights

### ISSUE THREAD

**Issue by Wicht78** [Graylog2/graylog2-server#5205]
At the moment it is not possible to create new conditions and notifications without having rights for the stream.

There are groups in our environment that should not have permissions to change streams, but should create and edit alarms.

Due to this dependency this is not possible.
It would be very helpful if there were no dependency between the alarms and the streams, when editing the alarms area

* Graylog Version: 2.4.6
* Elasticsearch Version: 5.x

**Comment by bernd** [comment]
This is possible with the new alerting system in 3.2 and the upcoming entity sharing in 4.0.0.
