### ISSUE TITLE
Dependency of input:create right to pipeline

### ISSUE THREAD

**Issue by Wicht78** [Graylog2/graylog2-server#5206]
At the moment you have to give a role the right inputs:create to see the pipeline in the System menu.

But with this right I also give it the possibility to create a pipeline, which we don't want.

In my opinion it should therefore not depend on this setting whether a pipeline can be created or edited.

This rights are set for the Role:
  "pipeline:edit",
  "pipeline:read",
  "pipeline:create",
  "pipeline:delete",
  "pipeline_connection:edit",
  "pipeline_connection:read",
  "pipeline_rule:edit",
  "pipeline_rule:read",
  "pipeline_rule:create",
  "pipeline_rule:delete",

But they can't see the pipeline in the menue

**Comment by AntonEbel** [comment]
Fixed by #13188.
