### ISSUE TITLE
Process drl rules before stream matching

### ISSUE THREAD

**Issue by mschuett** [Graylog2/graylog2-server#521]
Currently the StreamMatcher filter runs before the Drools RulesEngine.
That means that if I use Drools rules to extract additional fields then I cannot use these fields for streams.

If it does not break anything else it would be great to change that order and run the RulesEngine first.

**Comment by dfch** [comment]
An additional thought regarding drools rule matching: if rules are only evaluated after the stream matching has already occurred, it should also possible to define rules in such a way that they only apply to certain streams. This could be implemented in a way that is compatible with the drools syntax by using thr ```entry-point``` keyword (and the stream name or stream id being the ```entry-point name) or to define separate drools sessions.

**Comment by dfch** [comment]
I really think this issue can be closed, as the RuleFilter actually now *runs before* the StreamMatchFilter (see my comment above and commit 05f44bc). I did some DROOLS tests on RCn (1 or 2) and could tag/edit a message so a StreamMatchFilter rule was able to assign a changed message to a specific stream.

**Comment by bernd** [comment]
Thanks for the feedback! Closing.
