### ISSUE TITLE
Double-check sidecar's authorisation

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#5211]
This is just a reminder to double-check sidecar's authorisation before the release. In the end we changed many things both in the backend and web, and we should ensure only users with the right permissions can access it.

**Comment by kmerz** [comment]
Typo in permissions:
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/plugins/sidecar/permissions/SidecarRestPermissions.java#L32
