### ISSUE TITLE
API browser complains about wrong request URI even though CORS is enabled

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#522]
There is a simple check in the JS somewhere that makes sure that the correct URI is used to access the API browser to avoid cross site request problems. However, if CORS is enabled (`rest_enable_cors = true`), the warning message still appears even though everything is working perfectly fine.

Do not show the warning if CORS is enabled.

**Comment by joschi** [comment]
@lennartkoopmann I couldn't reproduce that in Graylog 2.2.0.
