### ISSUE TITLE
Prevent User to add Content Pack Parameter to Grok Pattern

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#5220]
## Expected Behavior
A user should not be able to assign parameters to grok patterns during the creation of a grok pattern.
A grok pattern is a set of fixed rules which should not be altered on the installation.

## Possible Solution
The GUI will prevent the assignment of parameters to grok patterns.
The backend as well!

**Comment by bernd** [comment]
We discussed to move the object path flattening to the server to have more control and to have access to the distinct value types.

This might be useful for the flattening: https://github.com/wnameless/json-flattener
