### ISSUE TITLE
Widget color customization

### ISSUE THREAD

**Issue by TenGbps** [Graylog2/graylog2-server#5229]
Could you add in wedget custom color settings ?
 Like both captures

![image](https://user-images.githubusercontent.com/30792994/45095274-fb1dc400-b11d-11e8-9f33-edd457d21bd8.png)

* Graylog Version: 2.4.6
* Elasticsearch Version: 5.5.1
* MongoDB Version: 2.6.12
* Operating System: CentOS7
* Browser version: Firefox 60 ESR

**Comment by jtkkex** [comment]
Hear him!

It would be nice to have a pie where field value "red" is also shown with red colour "red", and "green" as "green" on the dashboard.

**Comment by TenGbps** [comment]
Yeap like
 > 5xx http error in red 
 > 4xx in orange
 > 3xx bleu
 > 2xx in green

**Comment by dennisoelkers** [comment]
This has been implemented for quite some years.
