### ISSUE TITLE
[RFE]: More wording when adding new tags for sidecar

### ISSUE THREAD

**Issue by tjyang** [Graylog2/graylog2-server#5231]
Existing GUI for adding new tag is confusing. 
Please add "and hit enter" after "Select a tag or create new ones by typing their name."

## Expected Behavior

Select a tag or "create new ones by typing their name and hit enter". 

## Current Behavior

![image](https://user-images.githubusercontent.com/378638/47293024-7eac4b00-d5ce-11e8-8a65-bd118591243b.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 2.4.6
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by florianvolle** [comment]
Thanks a lot for your feedback but I am closing this because the tagging system will be removed with the upcoming 3.0.
