### ISSUE TITLE
Display bug with quick value histogram

### ISSUE THREAD

**Issue by TenGbps** [Graylog2/graylog2-server#5233]
We have a display bug with a quick value histogram on dashboard, after 30 minutes, some value are be display like capture:

![image](https://user-images.githubusercontent.com/30792994/47420449-bd810300-d77e-11e8-84f4-26dbdb2aa886.png)

* Graylog Version: 2.4.6
* Elasticsearch Version: 5.5.1
* MongoDB Version: 2.6.12
* Operating System: CentOS7
* Browser version: Firefox 60 ESR

**Comment by bernd** [comment]
The quick values widget doesn't exist anymore since Graylog 3.2 and has been replaced with the aggregation builder. Please open a new issue if you still see this issue with Graylog >=3.2. Thank you!
