### ISSUE TITLE
Bug with histogram on switching relative to absolute 

### ISSUE THREAD

**Issue by TenGbps** [Graylog2/graylog2-server#5234]
On a stream, when you going back absolute to relative, the histogram stay empty :

![sans titre](https://user-images.githubusercontent.com/30792994/47421910-dc34c900-d781-11e8-9b05-ef22fb2cc7f2.gif)

* Graylog Version: 2.4.6
* Elasticsearch Version: 5.5.1
* MongoDB Version: 2.6.12
* Operating System: CentOS7
* Browser version: Firefox 60 ESR

**Comment by bernd** [comment]
This should be fixed with the new search page in Graylog 3.2 and later. Please open a new issue if you still see the same problem. Thank you!
