### ISSUE TITLE
Filter with underscore into the string

### ISSUE THREAD

**Issue by brenolacerda** [Graylog2/graylog2-server#5235]
I can not search for a word because this word contains an undescore before. How can I do it?

My current search: **source:machine_01 AND (message:"/api/sample1" OR message:"/api/sample2" OR message:"/api/sample3") AND message:"icontains"**

Result: Nothing.

Expected Result:  **"GET /api/sample1/?filter2=%22line__item__customer__id%22:48484,%22text__icontains%22:%2244848148%22&limit=10&offset=0&order= HTTP/1.0" 200 985**

**Comment by jalogisch** [comment]
You need to escape some characters - as written in the documentation: http://docs.graylog.org/en/2.4/pages/queries.html#escaping

So your search must be:

```
source:machine_01 AND (message:"\/api\/sample1" OR message:"\/api\/sample2" OR message:"\/api\/sample3") AND message:"icontains"
```

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
