### ISSUE TITLE
Long searches block other REST calls to graylog2-server

### ISSUE THREAD

**Issue by JeremyEinfeld** [Graylog2/graylog2-server#524]
If a long-running elasticsearch query is executed, most graylog2 queries during that time (even ones that only query MongoDB) are blocked until the query finishes. Both normal searches and dashboard widgets can block queries.

Searches that take longer than 5 seconds are especially problematic, due to the default 5-second Netty timeout (evidenced by "java.util.concurrent.TimeoutException: No response received after 5000" at graylog2-web-interface logging). The timeouts cause 504 and 403 responses (if it is an auth check), and if anyone runs a query longer than 6 seconds then all users that are viewing a dashboard are redirected to the home page as a result.

Files: https://gist.github.com/JeremyEinfeld/e51c3fb55dcf2d42a550
A CSV export of the REST requests (with server response times) surrounding an 8-second query (searching 250 million documents with some basic field operators), and a thread dump during a similar conditions.

**Comment by bernd** [comment]
Closing this. Please re-open if you still have problems with Graylog 1.1. Thank you!
