### ISSUE TITLE
Index page is loading very slowly

### ISSUE THREAD

**Issue by lesliefag** [Graylog2/graylog2-server#5244]
I have a graillog cluster with so many indexes, it takes more than 30 seconds to load the system page, can I somehow speed up the loading?

![default](https://user-images.githubusercontent.com/9318430/47581111-3d62c500-d959-11e8-959e-a4e7b7a86a12.png)

**Comment by jalogisch** [comment]
How many resources you have for Elasticsearch? It might be that the Elasticsearch cluster is not responsive enough to deliver the stats on this page.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by ion-storm** [comment]
We have about 50 different indexes in elasticsearch and graylog.  We are currently experiencing the same issue.  The backend Elasticsearch cluster is barely getting hit with CPU or memory usage, we have all of our nodes monitored with InfluxDB.  This seems more like a Graylog UI issue where Graylog should cache the Indexes page data to load it faster and then do periodic background refreshes.  The performance is really bad, it'll take about 2 minutes to load the index page.
