### ISSUE TITLE
Deleting content pack from its details page throws an error

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#5251]
## Expected Behavior

When the user deletes a content pack from the content pack details page, she should be redirected to the content pack overview because the content pack got deleted and we cannot show the details anymore.

## Current Behavior

Deleting the last content pack revision from a content pack details page throws an error:

![image](https://user-images.githubusercontent.com/461/47736122-42cc5200-dc6e-11e8-9ec3-1b6e1d925e48.png)

## Steps to Reproduce (for bugs)

1. Navigate to content pack details page
2. Delete last revision from the content pack
3. Check out the error

## Your Environment

* Graylog Version: 3.0.0-alpha.3-SNAPSHOT (rev aa299e552)

**Comment by bernd** [comment]
@kmerz I guess this can be closed? I has been moved to DONE in the project but there is no reference to any pull request.

**Comment by kmerz** [comment]
Fixed by: Refs #5296
