### ISSUE TITLE
Beat via Kafka

### ISSUE THREAD

**Issue by xuziheng1002** [Graylog2/graylog2-server#5254]
we use graylog and sidecar to collector application logs,but graylog-server input has been the bottle-neck, so we think it will be better if let Beat input get messages from kafka.
Is there any schedule to develop this feature now?

**Comment by florianvolle** [comment]
We do not have anything scheduled yet, but this is a valid request.

**Comment by BenoitPoulet** [comment]
is it on the roadmap ?

You are pushing Filebeat to ingest logs, but we are unable to connect it to a queue.

**Comment by BenoitPoulet** [comment]
any news from this ?

**Comment by rkmbaxed** [comment]
News would be great, we are also waitung for this feature.

**Comment by waab76** [comment]
Is there a reason that the existing Kafka inputs don't work for this case? What additional functionality are we hoping to get from specifically building a Kafka input for Beats?

**Comment by bernd** [comment]
@waab76 We can reuse the Kafka transport infrastructure but need a new Kafka-based input with a Beats codec. We have to find out how the Beats payload looks like. If it's the same binary payload that is used in the lumberjack protocol, we can probably reuse the Beats input's codec.

**Comment by waab76** [comment]
Tentatively targeting this for 6.1

**Comment by bernd** [comment]
@waab76 I reopened this issue because you mentioned that you are targeting it.

**Comment by ryan-carroll-graylog** [comment]
New input added in https://github.com/Graylog2/graylog2-server/pull/20067
