### ISSUE TITLE
Message not store in UTC value but UTC + 1

### ISSUE THREAD

**Issue by dgarros** [Graylog2/graylog2-server#526]
Hi 

I noticed that most (if not all) my messages received by Graylog2 are stored in UTC + 1 timestamp and not UTC

I'm in PST time zone as well as the server and the client

And for example, this log  (see below)

Is store with a timestamp of : 2014-04-22 18:50:38.000
While it has been received at : Apr 22 10:50:38 (PST) by the server 
The UTC value should be one hour before 

Any idea where it could come from ? 

It's very impacting because logs are showing up on the GUI with one hour delay

Thanks for your help
Damien

Information about my system 

MongoDB shell version: 2.4.10
Elasticsearch version 0.90.13
graylog2-web-interface v0.20.1
graylog2-server-0.20.1-1.el6.noarch.rpm
Centos Linux 2.6.32-431.11.2.el6.x86_64) 
CentOS release 6.5 (Final)

{
_index: graylog2_1
_type: message
_id: 9d721df0-ca46-11e3-9fd5-000c29995276
_version: 1
_score: null
_source: {
timestamp: 2014-04-22 18:50:38.000
message: jmonkey: jaguar-lf0, SWITCHOVER - RSNG-SRV2 Prev Master BBAK8783 | Prev Backup BBAK8886 
level: 6
_id: 9d721df0-ca46-11e3-9fd5-000c29995276
facility: user-level
source: sp-lnx1-eth0.dcbg.juniper.net
gl2_source_input: 5356a9a7e4b06636726a74e8
gl2_source_node: 92ca84c2-c996-40d9-b6c9-13aca365c7d2
full_message: <14>Apr 22 10:50:38 jmonkey: jaguar-lf0, SWITCHOVER - RSNG-SRV2 Prev Master BBAK8783 | Prev Backup BBAK8886
streams: [ ]
}
sort: [
message
null
]
}

**Comment by bernd** [comment]
There have been lots of changes since last year. Please check if this issue still exists with Graylog 1.1 and re-open the issue if you still have problems. Thank you!
