### ISSUE TITLE
API-Browser - broken "Throbber" image

### ISSUE THREAD

**Issue by krzotr** [Graylog2/graylog2-server#5262]
To get API-Browser we can use two similar addresses - `/api/api-browser` and `/api/api-browser/` (trailing slash `/`).
When we go to `/api/api-browser/`, select **Alerts** and click **Try it out!**, on the right side we see broken image "Throbber"

![graylog-server](https://user-images.githubusercontent.com/655681/47951821-748f3280-df66-11e8-96e2-9457e87f85b4.png)

## Expected Behavior

After we click "Try it out!" button in API-Browser, we should see "Throbber" image

## Current Behavior

After we click "Try it out!" button in API-Browser, we see a broken image to "Throbber"

## Possible Solution

Set correct image path to "Throbber" when we use API-Browser url `/api/api-browser/`

## Steps to Reproduce (for bugs)
1. Go to `/api/api-browser/`
2. Select `Alerts`
3. Click `Try it out!`

## Your Environment
Tested on  VM image **graylog-2.4.6-1.ova**

* Graylog Version: 2.4.6
* Elasticsearch Version: 5.6.3
* MongoDB Version: 3.4.9
* Operating System: Windows 7
* Browser version: Chrome/70.0.3538.77

**Comment by bernd** [comment]
This doesn't happen anymore in newer versions.
