### ISSUE TITLE
amqps support?

### ISSUE THREAD

**Issue by albix** [Graylog2/graylog2-server#527]
Moin,

I've tried to get [amqps](http://www.rabbitmq.com/ssl.html) up and running with v0.20.2-snapshot.2. Unfortunately I had no luck. I'm using RabbitMQ as broker with self signed certificates. What I'm missing is the option to set client side certificates on the radio amqp input.

It would be awesome if you add this feature!

Cheers,
Christian

**Comment by bernd** [comment]
The AMQP transports support TLS as of v1.0.0.
