### ISSUE TITLE
nxlog  sidecar generator error

### ISSUE THREAD

**Issue by dsever** [Graylog2/graylog2-server#5270]
Hi,

when generating configuration for windows nxlog. It generates invalid configuration like:

```
<Input 5be18d1d732ba958e642f48f>
	Module im_msvistalog
	PollInterval 1
	SavePos	True
	ReadFromLast True
	Query <QueryXML>
        <QueryList>
            <Query Id='1'>
                <Select Path='Application'>*</Select>
                <Select Path='Security'>*[Security/Level=4]</Select>
                <Select Path='System'>*</Select>
            </Query>
        </QueryList>
    </QueryXML>
</Input>
```

It should be without parameter in front of   <QueryXML>, or else it fails with error message

time="2018-11-06T14:29:17+01:00" level=info msg="[nxlog] Configuration change detected, rewriting configuration file." 
time="2018-11-06T14:29:17+01:00" level=error msg="[nxlog] Error during configuration validation: Expected </Select> but saw </Query> at C:\\Program Files\\graylog\\collector-sidecar\\generated\\nxlog.conf:39\r\r\n"

Dubravko

* Graylog Version:

Graylog 2.4.6

**Comment by dsever** [comment]
It looks like it work if XML expression in one liner like:

Query <QueryXML><QueryList><Query Id='1'><Select Path='Application'>*</Select><Select Path='Security'>*[Security/Level=4]</Select><Select Path='System'>*</Select></Query></QueryList></QueryXML>

**Comment by mariussturm** [comment]
Thanks for the investigation! Will close the issue for now, in 3.0 this should be no issue anymore.
