### ISSUE TITLE
Default time range in Search

### ISSUE THREAD

**Issue by 3-commerce** [Graylog2/graylog2-server#5275]
## Expected Behavior
I have changed the default time range in system/configurations become PT4H. It means everytime i visit Streams page, the result should automatically has time range for 4 hours.

## Current Behavior
I visit Streams page, the time range is for 4 hours but the result is still 5 minutes. So, i need to press Search button on the top-left corner and then it will give 4 hours results.

I have asked it in Graylog Community forum, screenshots and questions here
https://community.graylog.org/t/change-default-search-range-time/7494

* Graylog Version: 2.4.6
* Elasticsearch Version: 5.6.10
* MongoDB Version: 3.6.6
* Operating System: Ubuntu 16.04
* Browser version: Chrome 70.0 & Firefox 63.0 (Latest)

**Comment by bernd** [comment]
I just checked and this is still an issue in 4.0.0-rc.2.

**Comment by xkill** [comment]
It is an issue on 4.1

**Comment by luk-kaminski** [comment]
I do not even see an option to change this default in newer FL versions:

![image](https://github.com/Graylog2/graylog2-server/assets/100699120/e6306e75-a11d-42ea-9bc6-64ff1306f048)

I assume it may be a deprecated issue.
@Emy-01 -> I suggest closing.

**Comment by Emy-01** [comment]
@luk-kaminski pls confirm and if so, then we can close it.
