### ISSUE TITLE
Index range lost inconsistently

### ISSUE THREAD

**Issue by Centreville01** [Graylog2/graylog2-server#5288]
## Summary
Unable to consistently search messages from the stream with field name matching stream rule. The stream deflector reports "Time range of index is unknown because index range is not available. Please recalculate index ranges manually."  The stream deflector  index is not active.

## Expected Behavior
Search messages from desired streams consistently works.

## Current Behavior
Deploy our applications that integrate to Graylog server. Run search messages to gather logs from our applications. Periodically the stream was created and the documents are are received at Stream graylog index but the number of messages in current write-active index is zero.  It reports "Time range of index is unknown because index range is not available. Please recalculate index ranges manually." Follow instruction, click Maintenance -> Recalculate Index Ranges and nothing changes

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
See that "Time range of index is unknown, because index range is not available. Please recalculate index ranges manually."
Optional:
4. Click Maintenance -> Recalculate Index Ranges

1. Create stream index.
2. Explore our applications logs to Graylog .
3. Click Stream -  Desired stream index . Monitor message rate is incremented. 
4. Click Systems -  Indices  - Indices & Index sets. Monitor the number of documents is incremented. However the number of messages in current write-active index is zero. 

## Your Environment

* Graylog Version: 2.4.5
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Centos 7.1
* Browser version: 66.0.3359

**Comment by dennisoelkers** [comment]
Thanks for opening the issue, @Centreville01. I need some more information from you:

  * What is your Elasticsearch version?
  * Can you add the output of your Graylog server while recalculating index ranges?
