### ISSUE TITLE
Message source is missing for UDP transport based inputs

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#5293]
## Expected Behavior

Log messages coming in via UDP transports should have a `source` field.

## Current Behavior

Since the big netty upgrade from 3 to 4, all messages that arrive via UDP netty transports do not have a source field anymore.

![image](https://user-images.githubusercontent.com/461/48713485-b085f100-ec10-11e8-8d51-4e18ebf86db7.png)

## Possible Solution

Our [RawMessageHandler](https://github.com/Graylog2/graylog2-server/blob/12f456eced7d3d49487ccf54ff8470d70afd9832/graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/RawMessageHandler.java) is trying to get the remote address from the netty channel. This works for TCP channels but doesn't work for UDP channels. For UDP channels `ctx.channel().remoteAddress()` always returns `null`.

https://github.com/Graylog2/graylog2-server/blob/12f456eced7d3d49487ccf54ff8470d70afd9832/graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/RawMessageHandler.java#L40-L45

The remote address for UDP datagrams can be obtained via [DatagramPacket#sender()](https://netty.io/4.1/api/io/netty/channel/DefaultAddressedEnvelope.html#sender--). The problem is, that our [DatagramPacketHandler]() and [NetflowMessageAggregationHandler]() only pass on the actual payload byte buffer to subsequent netty handlers. That means we cannot get to the datagram packet sender in the RawMessageHandler later.

One possible solution could be to create a small container object that holds the payload byte buffer and the remote address instead of just passing on the payload byte buffer to subsequent netty handlers.
Another option might be to use netty channel attributes to set the remote address when still having access to the datagram packet and then read it in the RawMessageHandler. But that might be problematic because the same netty channel is used for all incoming packets so we might run into race conditions.

## Steps to Reproduce (for bugs)

1. Create raw UDP input
2. Send a UDP message via `echo udp test | ncat -u 127.0.0.1 5555`
3. Search for the message
4. Check "source" field. It's set to "unknown"

## Context

This basically breaks all messages that are coming in via UDP and which don't set a custom source!

## Your Environment

* Graylog Version: 3.0.0-alpha.4

**Comment by dennisoelkers** [comment]
This is most probably also the underlying cause of #5264.

**Comment by bernd** [comment]
> This is most probably also the underlying cause of #5264.

@dennisoelkers Yes! Thanks for the heads up!

**Comment by jam49** [comment]
This also appears broken for TCP syslog inputs in 2.5.1, works fine in 2.4.x
