### ISSUE TITLE
Beat Input drops metadata fileds

### ISSUE THREAD

**Issue by rwaffen** [Graylog2/graylog2-server#5313]
I'm sending logfiles from within kubernetes to graylog with filebeat. Filebeat adds cloud_metadata and kubernetes_metadata. But the addional fileds (the metadata) do not show up in graylog or elasticsearch.

## Expected Behavior
The metada is shown within graylog as filed

## Current Behavior
The fileds are missing.

## Steps to Reproduce (for bugs)
1. configure graylog Beat input
2. add filebeat as daemonset to kubernetes 

## Your Environment
* Graylog Version: 2.4.6
* Elasticsearch Version: 5.6.12
* MongoDB Version: 3.6.8
* Operating System: Oracle Linux Server release 7.5
* Browser version: Chrome 70.0.3538.110 (Offizieller Build) (64-Bit)
* Filebeat: 6.5.1

**Comment by rwaffen** [comment]
Graylog entry:
![bildschirmfoto 2018-11-26 um 09 19 36](https://user-images.githubusercontent.com/1800591/49001284-92fadf00-f15c-11e8-925e-40efc51207eb.png)

Kibana Entry from Testsystem:
![bildschirmfoto 2018-11-26 um 09 14 26](https://user-images.githubusercontent.com/1800591/49001324-aefe8080-f15c-11e8-8e26-af486b5ea173.png)

**Comment by rmalchow** [comment]
hi @rwaffen, 
i am seeing this as well ... and i am extremely surprised. after reading this, i am slightly relieved that at least it's not just me being stupid.
 
   `https://community.graylog.org/t/filebeat-without-sidecar/7779`

i would be extremely interested to see how this goes.

**Comment by rwaffen** [comment]
Hi @rmalchow ,

also spend 3 days until noticing that everything is okay, but graylog somehow drops the fields. tried all thing to configure prospectors, inputs, metadata. but nothing seemed to work. than i installed a second elasticsearch with kibana and also send logs to this destination... and voila, i got what i wanted, but not in graylog :-/

**Comment by bernd** [comment]
@rwaffen @rmalchow The beats input and 2.4 and the upcoming 2.5 has limited support for beats metadata fields.

Graylog 3.0 will ship with a new beats input that has more generic support for metadata fields.

**Comment by rwaffen** [comment]
So we have to wait until 3.0? which is only in early alpha atm! 
and you say it has only "more" support, but not full support?

**Comment by rmalchow** [comment]
i'm gonna give the alpha a go, let's see how that goes ...

**Comment by rmalchow** [comment]
also, it seems that it might be possible to install the new version of the plugin into an old(er) version of graylog. that might be another route to solve this

**Comment by rwaffen** [comment]
Hab the Same Idea. This could bei a solution. 🤔

**Comment by rmalchow** [comment]
just tried "Graylog 3.0.0-alpha.4+6e0b9cd" with otherwise more or less the exact same config (graylog listen_uri has changed, so, yeah). 

still no cigar:
![screen shot 2018-11-27 at 10 11 06](https://user-images.githubusercontent.com/4213287/49070814-d1f86580-f22c-11e8-87ec-6b73610b3b1b.png)

where tcpdump sees this:

![tcpdump](https://user-images.githubusercontent.com/4213287/49071087-75e21100-f22d-11e8-9148-3755a1bb4809.png)

**Comment by bernd** [comment]
@rmalchow You also have to switch to the new beats input. In 3.0 there are two beats inputs. "Beats" and "Beats (deprecated)" When you upgrade from 2.4 you are probably using the deprecated one. We kept the old one for backwards compatibility.

> also, it seems that it might be possible to install the new version of the plugin into an old(er) version of graylog. that might be another route to solve this

This is not possible, sorry. In 3.0 we moved the beats input plugin into Graylog core so it's not a plugin anymore.

> @rwaffen: So we have to wait until 3.0? which is only in early alpha atm!
> and you say it has only "more" support, but not full support?

Yes, you have to wait for 3.0 which will be released until the end of Q1/2019. "More" support was not very precise, sorry about that. It would be great if you can test your use case with a 3.0 alpha release so we can make sure it's supported. Thank you!

**Comment by rmalchow** [comment]
@bernd hi bernd, yes, in fact this is now working. fantastic. i'll keep testing it with some logback MDCs as well to make sure everything i need actually gets added. thank you for the hint.

i just forked the (deprecated) beats plugin ... basically with the goal of figuring out if a backport might be possible / worth it. care to voice an opinion wether this is a good idea or not?

**Comment by bernd** [comment]
Glad that it works for you now! :+1: 

> i just forked the (deprecated) beats plugin ... basically with the goal of figuring out if a backport might be possible / worth it. care to voice an opinion wether this is a good idea or not?

Feel free to do that. But you are on your own with that because we don't have the resources support it. :wink:

**Comment by rwaffen** [comment]
hmmm unsatisfying... but than i have to wait. i also tried the alpha, but i need this for a production system, and there i will not use alpha software ^^

**Comment by bernd** [comment]
I am closing this now because the metadata fields will be available with the new beats input in the upcoming 3.0 release.
