### ISSUE TITLE
Add to docs: How to avoid ES split-brain and how to avoid shard shuffling

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#533]
This page explains it pretty good: http://asquera.de/opensource/2012/11/25/elasticsearch-pre-flight-checklist/

Add information about the two scenarios to: http://support.torch.sh/help/kb/graylog2-server/configuring-and-tuning-elasticsearch-for-graylog2-v0200

**Comment by bernd** [comment]
Fixed in https://github.com/Graylog2/documentation/pull/66
