### ISSUE TITLE
This seems to be a bug

### ISSUE THREAD

**Issue by soar1688** [Graylog2/graylog2-server#5331]
I use docker-compose.yml on the official greylog website.
<img width="785" alt="1" src="https://user-images.githubusercontent.com/21233395/49235056-2457a300-f434-11e8-843b-07b7d82360c8.png">
It's failed
![2](https://user-images.githubusercontent.com/21233395/49235120-510bba80-f434-11e8-8e2b-7b84225724a3.png)
After this modification
![3](https://user-images.githubusercontent.com/21233395/49235251-a6e06280-f434-11e8-979c-8cb79a712822.png)
It's success
![4](https://user-images.githubusercontent.com/21233395/49235331-d8f1c480-f434-11e8-9597-193df56cc15d.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by jalogisch** [comment]
Unfortunately the issue is not reproducible in the latest release. Please re-open this issue if it still occurs, ideally with a set of reproducible steps. 

Thanks!
