### ISSUE TITLE
Indices page doesn't load after closing an index

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#5336]
The indices page doesn't load after closing an index (both from Graylog or ES directly). The frontend stays in a "loading" state, and there are no errors shown in the server logs. The API call fetching the indices data fails in the background with a 500 error:

```
http -a hans :9000/api/system/indexer/overview/5bfebddbe0015c1658e2dca5
HTTP/1.1 500 Internal Server Error
Connection: close
Content-Length: 286
Content-Type: application/json
Date: Fri, 30 Nov 2018 12:55:40 GMT
X-Graylog-Node-ID: 9c30baff-6fbe-45e8-a76f-4fb84e754361
X-Runtime-Microseconds: 132972

{
    "details": [
        "closed"
    ],
    "message": "Fetching message count failed for indices [graylog-25-es6_5, graylog-25-es6_0, graylog-25-es6_4, graylog-25-es6_3, graylog-25-es6_8, graylog-25-es6_1, graylog-25-es6_9, graylog-25-es6_6, graylog-25-es6_2, graylog-25-es6_10, graylog-25-es6_7]\n\nclosed"
}
```

I could reproduce this in 2.5 using ES 6.5.1, but it worked fine in 2.4.6 with ES 5.6.3.

## Steps to Reproduce (for bugs)
1. Go to _System -> Indices_ and click on an index set
2. Close an index
3. See that the page does not reload the indices any more
4. Reloading the page does not help, as the indices information never comes

## Your Environment
* Graylog Version: Graylog 2.5.0-beta.2-SNAPSHOT
* Elasticsearch Version: 6.5.1

**Comment by bernd** [comment]
Fixed in #5339
