### ISSUE TITLE
telegraf graylog input not working with graylog 2.5

### ISSUE THREAD

**Issue by kpointer** [Graylog2/graylog2-server#5358]
Installed graylog 2.5 and found the telegraf metrics input stopped working with the following error:

telegraf[85393]: 2018-12-03T16:11:03Z E! [inputs.graylog]: Error in plugin: Response from url "http://127.0.0.1:9000/api/system/metrics/multiple" has status code 400 (Bad Request), expected 200 (OK)

telegraf config:

   servers = [
     "http://127.0.0.1:9000/api/system/metrics/multiple",
   ]

  metrics = [
    "jvm.threads.count",
    "jvm.memory.heap.used",
    "jvm.memory.total.init",
    "jvm.memory.total.used",
    "org.graylog2.journal.size",
    "org.graylog2.journal.size-limit",
    "org.graylog2.buffers.input.size",
    "org.graylog2.buffers.input.usage",
    "org.graylog2.buffers.output.size",
    "org.graylog2.buffers.output.usage",
    "org.graylog2.buffers.process.size",
    "org.graylog2.buffers.process.usage",
    "org.graylog2.journal.append.1-sec-rate",
    "org.graylog2.journal.utilization-ratio",
    "org.graylog2.throughput.input.1-sec-rate",
    "org.graylog2.throughput.output.1-sec-rate"
  ]

* Graylog Version: 2.5.0
* Elasticsearch Version: 5.6.13
* MongoDB Version: 3.6.9
* Operating System: Ubuntu 16.04 LTS
* Browser version: Firefox 64.0b14

**Comment by junior466** [comment]
Here to report exact same issue after upgrade to 2.5 on Ubuntu.

**Comment by edmundoa** [comment]
This is caused by the addition of a CSRF protection header in 2.5 (`X-Requested-By`). As we are not the authors of the Telegraf input you need to open an issue in the plugin's repository. All API requests now need to set the `X-Requested-By` HTTP header, so I guess that plugin needs to include the header on its requests.
