### ISSUE TITLE
Radio inputs routing to different AMQP queues or topic exchanges ?

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#536]
According to #385 it should be possible to let inputs route to different AMQP queues or topic exchanges (just like the first invocation of graylog2-radio, see @lennartkoopmann comment on the referenced issue) ... but it does not look like that is possible with 0.20.2-rc1?

We have a lot of stuff that needs pre-processing before it gets ingested by our server nodes and this feature would allow us to do so rather elegantly (radios receives data, push that to pre-process queues, something does something to the messages in those queues and inserts the processed messages into a queue that our server nodes ingest).

The above has the definite benefit of allowing us to concentrate our redundancy and availability efforts towards our radio nodes (to make sure that we do not loose events) ... right now we have to duplicate this to the other tools that are needed in our toolchain which is rather inefficient ...

**Comment by bernd** [comment]
Closing this because radio has been deprecated as of v1.0.0. Please re-open this is still an issue. Thank you!
