### ISSUE TITLE
Unable to save existing roles successfully

### ISSUE THREAD

**Issue by cachemeoutside** [Graylog2/graylog2-server#5397]
It looks like the graylog dashboard is having some issues with editing/deleting EXISTING roles with slash characters in the title name. As of now, I'm unable to delete/edit my old roles with slashes in the title.

## Expected Behavior
Adding the role didn't spit out any errors, I'd think that editing/deleting the role would be seamless.

## Current Behavior
alphanumeric roles works just fine, but titles with slashes experience the issue described above

## Possible Solution
Probably a character escape or encoding issue? Either fix or prevent slashes from being allowed.

## Steps to Reproduce (for bugs)

1. Create a new role called: test role read/write
2. Edit newly created role, save shouldn't be executing anything and no errors are displayed
3. Delete newly created role, delete shouldn't be executing anything and no errors are displayed

## Context
Can't remove bad role names now. Are there any fixes I can run on the backend?

## Your Environment

* Graylog Version: 2.5.0-3
* Elasticsearch Version: 6.3
* MongoDB Version: 4.0
* Operating System: MacOS 10.14
* Browser version: 70.0.3538.110 Google and 63.0 Firefox

**Comment by edmundoa** [comment]
Hi,

I just tried to reproduce your issue in Graylog 2.5.0, but I could not:

![roles](https://user-images.githubusercontent.com/716185/49885137-cadd7400-fe36-11e8-93c5-2c50a6609225.gif)

How exactly are you trying to edit or delete roles? Do you see any errors in your Graylog server logs or web interface JS console?
