### ISSUE TITLE
Standard configuration file has bad standard data_dir setting

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5398]
The [standard Graylog configuration file](https://github.com/Graylog2/graylog2-server/blob/master/misc/graylog.conf) has the `data_dir` config set to just `data` and the operating system packages are taking over this setting, leading to failing report generation.

At least for the operating system packages, this should be an absolute path.

**Comment by bernd** [comment]
@lennartkoopmann I just did a 3.0 alpha OS package installation and the `data_dir` in `server.conf` is set correctly:

```
$ fgrep data_dir /etc/graylog/server/server.conf 
data_dir = /var/lib/graylog-server
```
Is your setup an upgraded setup from Graylog 2.x? And if so, have you updated your server config accordingly with the new defaults during the upgrade? There are some more changed settings in a 3.0 config.

**Comment by bernd** [comment]
@lennartkoopmann See also: http://docs.graylog.org/en/3.0/pages/upgrade/graylog-3.0.html#new-bin-dir-and-data-dir-configuration-parameters

**Comment by bernd** [comment]
I am closing this now because I believe it's a missing entry in your configuration file. Please reopen if this is actually a bug. Thank you!
