### ISSUE TITLE
make search time in "Field content Alert Condition" configurable

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#5401]
## Expected Behavior
All alert condition should have the option to configure the timeframe the alert condition is checked on.

## Current Behavior
The *Field content Alert Condition* is the only condition that uses a hardcoded timeframe. This is the `alert_check_interval` in the `server.conf`.

Because of this and the reason the next `alert search` runs the configured `alert_check_interval` after the last run has finished it can happen that you miss the timeframe the alert search actually takes. 

`Alert run` + `< time that search takes >` + `alert_check_interval` and the look back is only `alert_check_interval` you miss the time the search takes.

## Possible Solution
Make the search time for *Field content Alert Condition* configurable and make the default 5 minutes as for all other.

## Your Environment

* Graylog Version: 2.5

**Comment by jalogisch** [comment]
[FD#2455]

**Comment by bernd** [comment]
This can be done with the new alerting system in 3.1. Closing this ticket.
