### ISSUE TITLE
Support websockets in http input

### ISSUE THREAD

**Issue by pabl0rg** [Graylog2/graylog2-server#5412]
## Expected Behavior
Http input is easy to secure (using nginx reverse proxy with letsencrypt), whereas the other TLS options are a pain.  However, http inputs are slow.

## Possible Solution

If https inputs support websockets, GELF client libraries can be updated to send log messages over websockets instead of making a new connection for each message.

These guys tried websockets and had some success.  
http://www.wseas.us/e-library/conferences/2014/Istanbul/TELEDU/TELEDU-14.pdf

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by florianvolle** [comment]
Closing this as we are working on a batched http input to address performance issues.

Thanks!

**Comment by pabl0rg** [comment]
Hello @florianvolle where can I get info on the batched http input methods?  Thanks
