### ISSUE TITLE
Stop autofilling 'facility' field for Beats inputs

### ISSUE THREAD

**Issue by philomory** [Graylog2/graylog2-server#5421]
Incoming beats messages have their 'facility' field set to 'filebeat' (or just 'beats' in the new Beats2Codec). This is true whether a facility field value was set by Filebeat or not. "Facility" is an optional field and Graylog should not insert a value for an optional field that was absent in the source message, nor overwrite a source field with a different value (unless instructed to do so by a pipeline/extractor/etc).

## Expected Behavior
Incoming Beats messages with a facility field should retain the value specified in the facility field. Incoming Beats messages without a facility field should not have any value set for the facility field. This would be consistent with how e.g. the GELF input behaves.

## Current Behavior
Incoming Beats messages with a facility field have the value of that field overwritten with 'filebeat'.
Incoming Beats messages without a facility field have one added, with a value of 'filebeat'.

## Possible Solution
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsCodec.java#L145 (for original Beats codec)
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java#L92 (for new Beats2 codec)

## Steps to Reproduce (for bugs)
1. Create a Beats input
2. Run a Filebeat instance with the following configuration:
```
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /tmp/test.log
    fields:
      some_key: example_value
      facility: foo
  - type: log
    enabled: true
    paths:
      - /tmp/test2.log
    fields:
      some_key: example_value2
```
3. Observe that the ingested messages have their `some_key` field set appropriately, but their `facility` field is always `filebeat`.

## Context
We want to use the facility field in our log ingestion, but instead we'll be forced to invent some other field for this purpose. That's not really an insurmountable obstacle, but, why should the Beats input invent new fields or override existing ones in the first place? The GELF plugin doesn't exhibit this behavior.

## Your Environment
* Graylog Version: 2.5.0 and 2.4.6
* Elasticsearch Version: 6.5.2 and 5.6.6
* MongoDB Version: 2.6.12
* Operating System: CentOS 7
* Browser version: Google Chrome 70.0.3538.110

Note that we have not yet tried the 3.0 alpha; however the problematic line of code from the original Beats codec is still present in the new Beats codec, with the string value simply changed from 'filebeat' to 'beats'. I have inferred that the field will still be added/overwritten, but not confirmed it.

**Comment by philomory** [comment]
Looking more closely at the source code, I think the 3.0 beats codec will handle this slightly better than the 2.x beats codec: 3.0 sets fields from the source message _after_ it sets the automatic field values, so if the source message has a facility field, it'll overrule the default value of 'beats', unlike in 2.x. However, 3.0 still adds a spurious default value for messages with no facility set in the source message, which seems like poor behavior to me.

**Comment by mpfz0r** [comment]
refs https://github.com/Graylog2/graylog-plugin-beats/pull/29
