### ISSUE TITLE
Graylog 3.0.0-5.alpha.5 Extended Search / Views

### ISSUE THREAD

**Issue by pettai** [Graylog2/graylog2-server#5422]
Graylog 3.0.0-5.alpha.5 Extended Search / Views with non-default admin user gives stack trace:

Error:
'r is undefined; can't access its "format" property'

Stack Trace:
6cNfCzg8/f<@https://graylog-test/assets/plugin/org.graylog.plugins.enterprise.EnterprisePlugin/ExtendedSearchPage.95db17f93ad31b62d2d6.js:1:28010
it@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:18:61817
Vt@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:18:78129
Ut@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:18:78506
Tn@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:18:84899
gn@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:18:84286
Rn@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:18:83307
$t@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:18:82227
enqueueSetState@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:18:47300
24/W.prototype.setState@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:26:1647
value/</<@https://graylog-test/assets/plugin/org.graylog.plugins.enterprise.EnterprisePlugin/plugin.org.graylog.plugins.enterprise.EnterprisePlugin.95db17f93ad31b62d2d6.js:347:37832
e@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:10:1319
614/M.prototype.emit@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:82:1058845
trigger@https://graylog-test/assets/vendor.4024e2a8db732781a971.js:10:2183
_trigger@https://graylog-test/assets/plugin/org.graylog.plugins.enterprise.EnterprisePlugin/plugin.org.graylog.plugins.enterprise.EnterprisePlugin.95db17f93ad31b62d2d6.js:386:43481
execute/this.executePromise<@https://graylog-test/assets/plugin/org.graylog.plugins.enterprise.EnterprisePlugin/plugin.org.graylog.plugins.enterprise.EnterprisePlugin.95db17f93ad31b62d2d6.js:386:42960
a@https://graylog-test/assets/app.94b7b7609f41140f3a10.js:55:140197
e/<[22]</P.exports/A.prototype._settlePromiseFromHandler@https://graylog-test/assets/app.94b7b7609f41140f3a10.js:55:113585
e/<[22]</P.exports/A.prototype._settlePromise@https://graylog-test/assets/app.94b7b7609f41140f3a10.js:55:114385
e/<[22]</P.exports/A.prototype._settlePromise0@https://graylog-test/assets/app.94b7b7609f41140f3a10.js:55:115084
e/<[22]</P.exports/A.prototype._settlePromises@https://graylog-test/assets/app.94b7b7609f41140f3a10.js:55:116411
e/<[2]</a.prototype._drainQueue@https://graylog-test/assets/app.94b7b7609f41140f3a10.js:55:70331
e/<[2]</a.prototype._drainQueues@https://graylog-test/assets/app.94b7b7609f41140f3a10.js:55:70389
a/this.drainQueues@https://graylog-test/assets/app.94b7b7609f41140f3a10.js:55:68642
n@https://graylog-test/assets/polyfill.94b7b7609f41140f3a10.js:1:33531
j/<@https://graylog-test/assets/polyfill.94b7b7609f41140f3a10.js:1:33676
t@https://graylog-test/assets/polyfill.94b7b7609f41140f3a10.js:1:19923

Component Stack:

    in Unknown
    in ConnectStoresWrapper[Unknown/Anonymous] stores=currentUser
    in strong
    in div
    in span
    in d
    in div
    in div
    in Transition
    in b
    in div
    in b
    in div
    in b
    in div
    in div
    in r
    in div
    in AutoAffix
    in div
    in SideBar
    in ConnectStoresWrapper[SideBar] stores=viewMetadata
    in div
    in p
    in span
    in o
    in ConnectStoresWrapper[o] stores=widgets
    in span
    in t
    in ConnectStoresWrapper[t] stores=configurations,fieldTypes,searches,searchMetadata,viewState
    in div
    in b
    in p
    in div
    in b
    in div
    in p
    in p
    in Uncontrolled(p)
    in span
    in a
    in v
    in ConnectStoresWrapper[v] stores=queries,queryTitles,viewMetadata
    in withRouter(ConnectStoresWrapper[v] stores=queries,queryTitles,viewMetadata)
    in div
    in p
    in ExtendedSearchPage
    in ConnectStoresWrapper[ExtendedSearchPage] stores=executionState,parameters
    in o
    in i
    in u
    in ConnectStoresWrapper[u] stores=license
    in b
    in div
    in p
    in div
    in p
    in div
    in t
    in div
    in t
    in n
    in withRouter(n)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade

## Expected Behavior
Should work for created users as well...

## Current Behavior
Not working

## Steps to Reproduce (for bugs)
1. Create a user from Graylog user mgmt
2. Login with that user
3. Go to the extended search window
4. Error message will appear..

## Your Environment

* Graylog Version: 3.0.0-5.alpha.5 (installed from debs)
* Elasticsearch Version: 6.x
* MongoDB Version: 3.6
* Operating System: Ubuntu 16.04
* Browser version: Firefox stable

**Comment by dennisoelkers** [comment]
Thanks @pettai for reporting this!

Can you please check if assigning a timezone for that user helps?

**Comment by dennisoelkers** [comment]
@pettai: We have fixed some minor issues around timezone handling currently, which will land in the next alpha/beta.
