### ISSUE TITLE
Content pack installation dialog doesn't show entity title

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#5423]
## Expected Behavior

Installing a content pack from the content pack list page should show the entity title.

## Current Behavior

Pressing the install button on the content pack list page doesn't show the entity title. Doing the same from the content pack details page shows the entity title.

### Content pack list

![image](https://user-images.githubusercontent.com/461/50210722-28158000-0377-11e9-9737-34fdc489f99c.png)

### Content pack details

![image](https://user-images.githubusercontent.com/461/50210809-61e68680-0377-11e9-9636-7b5ee2b1202a.png)

## Steps to Reproduce (for bugs)

1. Press "Install" button on the content pack list page
2. Check "Title" for the entity

## Your Environment

* Graylog Version: 3.0.0-alpha.6-SNAPSHOT (rev 4ff7ea276)

**Comment by kmerz** [comment]
I can't reproduce the problem, @bernd can you check again, if the problem was perhaps solved already?

![graylog - content packs 2](https://user-images.githubusercontent.com/448763/50777632-65956b00-129c-11e9-84e8-71a735b97d32.png)
