### ISSUE TITLE
JSON Extractor drops boolean false (which errors out on ES data type of boolean)

### ISSUE THREAD

**Issue by demospace** [Graylog2/graylog2-server#5430]
When using a JSON extractor that includes a valid JSON boolean of "false" eg:  {"varname": false}, the extractor yields a blank field. With an index mapping in Elasticsearch of "boolean" an error is thrown as the null/blank is not interpreted as false.

I don't believe this is the same issue described in #5103.

## Expected Behavior
JSON extractor should parse boolean false into either the string "false" or another datatype that ES mappings will accept when set to "boolean."

## Current Behavior
See above.

## Steps to Reproduce (for bugs)
1. Create an index with a field mapping include a data type of "boolean"
2. Feed valid JSON to the JSON extractor with a boolean false eg: {"varname": false}
3. Attempt to store the document in ES

## Your Environment

* Graylog Version: 2.5
* Elasticsearch Version: 6.5.4
* MongoDB Version: na
* Operating System: Ubuntu 18.10
* Browser version: na

**Comment by sub50hz** [comment]
This appears to still be problematic for us as well.

**Comment by mayantec** [comment]
Any news on this topic?, looks quite old, and now on graylog 3.3 it's clear stills there.

**Comment by fizzka** [comment]
+1

**Comment by jalogisch** [comment]
I verified this issue as not present in Graylog 3.3.

# Way of testing

Create a RAW Input on Graylog Port 5555, ingested json messages on the command line:

```
 echo '{"array":[1,2,3],"boolean":true,"color":"gold","null":null,"number":123,"object":{"a":"b","c":"d"},"string":"Hello World"}' | nc 192.168.195.50 5555
```

created one json extractor on the first message:

![image](https://user-images.githubusercontent.com/404238/87678098-d4e5f800-c77a-11ea-98bb-c45f8c6981ca.png)

After that ingested the message again and got the following result:

![image](https://user-images.githubusercontent.com/404238/87678159-e7603180-c77a-11ea-95e3-22672f6eedff.png)


In addition to that I have tested the same message with the processing pipeline. Remove the extractor and used the following rule:

```
rule "extract json from field message"
when
 is_json(parse_json(to_string($message.message))) == true
then
 set_field("original_message", to_string($message.message));
 let json = parse_json(to_string($message.message));
 let map = to_map(json);
 set_fields(map);
 set_field("DEBUG", true);
end
```

With the result:

![image](https://user-images.githubusercontent.com/404238/87678355-21313800-c77b-11ea-9751-c68e6cc4661e.png)

This is not a bug and everything is working like it should.
