### ISSUE TITLE
Default stream must not added as entity to new content pack

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#5439]
When a pipeline is attached to the default stream the content pack will contain it as an entity, which then prevents installing it.

## Expected Behavior
When creating content pack with a pipeline and rule, it should be installable.

## Current Behavior
If the stream the pipeline is bound to already exists in the system, which is always the case for the default stream, then it cannot be installed at all.

## Steps to Reproduce (for bugs)
1. Create a pipeline, attach it to the default stream.
2. Create a content pack with that pipeline (it will add the default stream into the entity list).
3. Install the newly created content pack.
4. Note that it cannot be installed: an error is shown.

## Your Environment
* Graylog Version: 3.0.0-alpha.5

**Comment by pschichtel** [comment]
has anyone worked on this (or #5616) yet? if not, I might try to fix this until the end of this week.

**Comment by kroepke** [comment]
Hey, no I don't think anyone is actively working on this right now.
Please feel free to give it a shot!

**Comment by pschichtel** [comment]
Opened the pull request #6873.
