### ISSUE TITLE
Java 11 (LTS) support

### ISSUE THREAD

**Issue by TiNico22** [Graylog2/graylog2-server#5444]
Feature request / improvement for maintenance purpose for security purpose after Java 8 EOL

Java 8 is getting closer to his end of life 
the latest 2.5 has added the support for Elasticsearch 6.X which in the latest release (6.5) is supporting Java 11.

Does the Graylog 2.x series will support java 11 officially ? The official doc claim to support only java 8 http://docs.graylog.org/en/2.5/pages/installation.html#system-requirements and the same for the upcoming 3.0 release at this stage

**Comment by kroepke** [comment]
Hi!

We have not focused on testing Java 11 yet and are unlikely to require it any time soon.
That said, I understand that listing it as an officially supported JDK version has its benefits.
As 3.0 is already in beta, I'll put this into 3.1 for consideration.

From what I've seen from an application perspective I don't think supporting Java 11 is difficult, but we need to check various libraries if they have added support yet.

**Comment by kroepke** [comment]
Oh I meant to add: We do not plan on changing anything in the 2.5 release unless there are critical issues that need to be fixed.

IIRC 2.5 uses netty 3 somewhere in a default plugin, which afaik is not Java 11 compatible due to how the library is using `Unsafe`.

**Comment by kroepke** [comment]
For implementor reference: https://blog.joda.org/2018/09/from-java-8-to-java-11.html

**Comment by yfreund-ionos** [comment]
I believe this duplicates #5909 , which was already merged to master.
