### ISSUE TITLE
Prevent indexing to default Elasticsearch index when Kafka output is configured to a Stream

### ISSUE THREAD

**Issue by deepakmohanakrishnan1984** [Graylog2/graylog2-server#5447]
## Expected Behavior
The intention here is to process/enhance the incoming events in a Stream using pipeline (seq. of stages) and output it just to a Kafka cluster. But the streams in Graylog 2.5 mandates to define an index set and index all the incoming events to Elasticsearch by nature. I would like to avoid/prevent writing the events to Elasticsearch in this phase.

## Current Behavior
Graylog 2.5 writes the incoming events into the Elasticsearch cluster by default in addition to sending the output to Kafka(intended).

## Possible Solution
During stream creation make `IndexSet` as optional and send the events only to the associated outputs.

## Steps to Reproduce (for bugs)
1. Create a Stream
2. Associate a pipeline to add a new field, Say: a random hash value
3. Associate a Kafka output to the Stream
4. The events data in the stream is written to both Kafka (expected) and the Elasticsearch(unexpected)

## Context
I would like to preprocess the records(apply internal business logic, apply security rules etc) and send it to Kafka for later analytics/ML purpose. 

## Your Environment

* Graylog Version: 2.5
* Elasticsearch Version: 6.x
* MongoDB Version: 3.3
* Operating System: CentOS 7.x
* Browser version: NA

**Comment by jalogisch** [comment]
ref: #3253

**Comment by deepakmohanakrishnan1984** [comment]
We overcame this issue by configuring the default output to use DiscardMessageOutput. The side effect would be that said graylog could not be used for searching which is ok in our usecase. Feel free to close this issue.
