### ISSUE TITLE
Graylog2 stops receiving messages, requires a restart

### ISSUE THREAD

**Issue by dennisjac** [Graylog2/graylog2-server#545]
Hi,
for a second time now Graylog2 has stopped receiving new messages and I had to restart the server to fix the situation.
Any ideas how  I can debug this issue to get to the cause of this?

**Comment by bernd** [comment]
The v1.0 of Graylog is way more stable than the old 0.20 and 0.9x versions. Closing this issue. Please re-open if you still have problems with 1.0. Thank you!
