### ISSUE TITLE
graylog 3.0 beta 1 unwanted popup when changing page

### ISSUE THREAD

**Issue by TiNico22** [Graylog2/graylog2-server#5453]
## Expected Behavior
No pop up when no change made

## Current Behavior

There is a popup that ask to confirm that I will loose my change when navigating from a page to another
![graylog3 save](https://user-images.githubusercontent.com/7791737/50728321-2514e080-1128-11e9-8aa7-cbaf7f7502e4.jpg)

## Steps to Reproduce (for bugs)

The popup is always present when witching from a page/tab to onaother except when switch to "enterprise/extended" search page. 

## Your Environment

* Graylog Version: OVA 3.0 beta 1
* Browser version: Chrome 71 on windows 10

**Comment by TiNico22** [comment]
after restarting the browser the problem occurs only when leaving the extended search page

**Comment by dennisoelkers** [comment]
This is on purpose if you are leaving the extended search page or any view _after_ making some changes to prevent losing them accidentally. Is this happening erratically?

**Comment by TiNico22** [comment]
after a #service graylog-server restart the probelm still occurs without any change ongoing

**Comment by TiNico22** [comment]
same problem with a fresh install (from the new OVA Beta 2) 
leaving the enterprise search page show the popup

**Comment by dennisoelkers** [comment]
@TiNico22: I can reproduce the issue and there is already a PR fixing it, so it will be fixed in one of the next versions.

**Comment by TiNico22** [comment]
Great, because this bug was a little bit annoying when navigating in the GUI
