### ISSUE TITLE
Fix displayed collector status in collectors administration page

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#5471]
In the collectors administration page, the status filter does not display the right collector status:
<img width="1656" alt="screenshot 2019-01-08 at 15 55 26" src="https://user-images.githubusercontent.com/716185/50838283-f54f1e00-135d-11e9-8cbf-77b5b64bec3b.png">

## Steps to Reproduce (for bugs)
1. Go to the collectors administration page
2. Click on the _Collector Status_ filter dropdown
3. See status

## Your Environment
* Graylog Version: Graylog 3.0.0-beta.2-SNAPSHOT

**Comment by mpfz0r** [comment]
Fwiw, the filter itself seems to work. It's just the titles that are wrong.

**Comment by edmundoa** [comment]
Wrong button 💃
