### ISSUE TITLE
Timezones in UI incorrectly send to backend

### ISSUE THREAD

**Issue by yvdh** [Graylog2/graylog2-server#5479]
I am on Graylog 2.5.1 (but same issue on 2.4.6).
All my servers/admin user are configured to use Europe/Brussels (GMT +1).

![config](https://user-images.githubusercontent.com/16563417/50895688-1586e780-1407-11e9-8c01-a579938fc895.png)

I have a GELF input which sends in data with the ‘timestamp’ field in UTC (as it should). The server based ‘Timestamp’ (with a capital) shows a correct localized timestamp of when the message came in.

![gelf1](https://user-images.githubusercontent.com/16563417/50895713-28012100-1407-11e9-97b7-381d38a33e39.png)

When using the default relative query filters in the graylog2 web UI  (e.g. 'last 5 minutes' ) the local UI time is used without timezone information or is not translated to UTC. The result is that the backend interprets this as UTC and the query does not return the expected results.

## Expected Behavior

Predefined relative time queries should return correct results on the 'timestamp' field irrespective of the UI time, even if this field is in UTC time on the backend.

The predefined (relative) query should either convert the local UI time to UTC or provide timezone information in the json query so the backend can interpret it correctly. This is in the assumption the backend does interpret timezones in queries correctly and can match them with timezone of the stored 'timezone' field.

`
{
  "from": 0,
  "size": 150,
  "query": {
    "bool": {
      "must": {
        "match_all": {}
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "timestamp": {
                  "from": "2019-01-08 15:07:33.821",
                  "to": "2019-01-08 15:12:33.821",
                  "include_lower": true,
                  "include_upper": true
                }
              }
            },
            {
              "query_string": {
                "query": "streams:5c34b5c445837c03425baacf"
              }
            }
          ]
        }
      }
    }
  },
  "sort": [
    {
      "timestamp": {
        "order": "desc"
      }
    }
  ]
}
`

## Current Behavior

Local time is used in predefined relative time queries and seems to be intepreted as UTC, instead of converted as required.

## Possible Solution
Convert time in filters from UI time to UTC, or provide timezone info so the backend can do this when filtering.

## Steps to Reproduce (for bugs)

1. Set up servers and admin users with non-UTC timezone
2. Send in Gelf data with 'timestamp' as UTC time
3. Use one of the predefined relative time filters on the stream or input
4. Resulting message list  is incorrect

## Your Environment

Graylog 2.5.1 (but same issue on 2.4.6), OVA.

* Operating System (UI): Windows 10 64 bit
* Browser version: Chrome 71.0.3578.98

**Comment by dennisoelkers** [comment]
@yvdh: Thanks for reporting this. I cannot verify the issue. I have a user set to `Europe/Berlin` (CEST, so GMT+1 currently as well) and when I submit a search a relative time range, it is properly converted to UTC:

(submitted at 13:04)
```
                  "timestamp": {
                    "from": "2019-01-09 12:04:09.516",
                    "to": "2019-01-09 12:09:09.516",
```

Do you have any further information about the issue? Any step by step instruction how to reproduce this? Does it happen with every user with a non-UTC timezone?

**Comment by yvdh** [comment]
Hi there,

just confirmed my issue in Chrome and Firefox:
Local time is 12:10 PM (Europe/Brussels)
Query for 'Last 2 hours' says:
`
              "range": {
                "timestamp": {
                  "from": "2019-01-11 10:10:23.561",
                  "to": "2019-01-11 12:10:23.561",
                  "include_lower": true,
                  "include_upper": true
                }
              }
`
This is clearly not UTC time, which should be something like '2019-01-11T11:10:27.099Z'

Btw: it would practical if the query can be seen even if no records are found!
Cheers
Yves

**Comment by yvdh** [comment]
Hello again,
I now setup a GrayLog2 environment from scratch in CentOS 7 (i.e. not using the Ova virtual machines), and there queries are properly converted to UTC time! So, this issue maybe limited to the virtual machine environments only!

Btw. virtual machines as provided have problems running with the latest VMWare software (all kinds of 'hardware' not supported problems), this is the reason I proceeded with a manual install ...
