### ISSUE TITLE
Connection to Active Directory DC over IPv6 fails via FQDN

### ISSUE THREAD

**Issue by p-rintz** [Graylog2/graylog2-server#5505]
## Expected Behavior
Successful connection via FQDN via IPv6 to AD DC.

## Current Behavior
AD DC Connection via IPv6 fails. 
> ERROR [LdapConnector] Timed out connecting to LDAP server

Directly using an IPv6 succeeds.

## Steps to Reproduce (for bugs)
1. Have a AD DC (ours has an A and AAAA)
2. Graylog Server has IPv6 only
3. Input the FQDN of the DC into the Graylog LDAP settings
4. Try to connect
5. Fail

## Context
Trying to connect the graylog server (which does not have an IPv4 Address) to an AD DC.

## Your Environment

* Graylog Version: 2.5.1
* Elasticsearch Version: 6.5.4
* MongoDB Version: 3.6.9
* Operating System: Centos 7
* Browser version: Firefox 65

I edited this bug report as I did some more digging today and I think it might be because the Graylog Server receives an A record as well, but obviously cannot connect to the Domain Controller via it as it does not have an IPv4 Address itself. It then does not try to connect via IPv6 and just fails.

**Comment by bernd** [comment]
We switched to a new LDAP library in the upcoming 4.0 release. Please open a new issue if you still see this problem. Thank you!
