### ISSUE TITLE
Target global inputs to radio or server nodes

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#551]
Not all inputs should be completely "global", such as the Radio inputs, which don't make much sense to run on radio nodes.
Other scenarios include running global inputs on radio nodes only, but not on graylog2 server nodes (if the intention is to run radio nodes "on the edge" and having server nodes process the radio inputs' data only).

In short, improve the notion of "global" inputs, by supporting classes or groups of nodes.

**Comment by bernd** [comment]
Radio is gone. Closing this. Please re-open if still relevant.
