### ISSUE TITLE
Server name unknown

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#553]
Hi,

I'm trying to get a new Graylog Cluster running. But when the nodes connect, i see in the logging :
[service] [graylog2-server] added {[graylog2-server][ONcmp3MDS2WEQSRKK6xLLg][inet[/10.88.3.23:9350]]{client=true, data=false, master=false},}, reason: zen-disco-receive(from master [[Talbot, Glenn][GtlWsLJSScGG5kikeQQXdg][inet[/10.88.3.23:9300]]{master=true}]

But in the webinterface i see only one node which is "unknown". Why is it unknown?

**Comment by bernd** [comment]
Closing this. Please re-open if you still see this with Graylog 1.0.0. Thank you!
