### ISSUE TITLE
Sidecar configuration migration

### ISSUE THREAD

**Issue by tehpanta** [Graylog2/graylog2-server#5544]
After upgrading Graylog from 2X to 3X, all sidecar configuration is lost and has to be manually created from scratch

## Expected Behavior
After upgrading graylog server and sidecars to v3/v1 respectively, graylog should be able to migrate configuration from previous versions of sidecar management to new logic.

## Current Behavior
After upgrading, all configuration data is lost and left only on mongodb. User has to manually export the configuration data (in our case thousands of configuration snippets) and manually enter them into the new GUI for sidecar management.

## Possible Solution
Possible workaround would to have some sort of migration helper tool, that would create configuration tags and configurations underneath it from data in old sidecar configuration on demand.

## Steps to Reproduce (for bugs)
1. Have 2.X graylog server with sidecar configurations running.
2. Upgrade to graylog 3.X

## Context
This added a tremendous load on our team managing graylog topology.

## Your Environment

* Graylog Version: 2.5 > 3.0
* Elasticsearch Version: 6.5
* Operating System: RHEL 7+

**Comment by bernd** [comment]
@tehpanta The configurations are not lost. There is a "Collectors (legacy)" menu entry in "System" that still offers the old UI and APIs. Also, the old sidecar 0.1.x versions still work with the old APIs.

We also added a migration feature that allows you to import old sidecar collector configurations into the new system. 

![image](https://user-images.githubusercontent.com/461/51326882-5bc7f080-1a70-11e9-833a-3af870284590.png)

![image](https://user-images.githubusercontent.com/461/51326874-58346980-1a70-11e9-9f0f-079d95b77c83.png)

If you are testing the 3.0.0-beta.2 release, please open an issue if you don't have the menu item for the old UI or if the migration feature doesn't work. Thank you!

**Comment by tehpanta** [comment]
Oh. I missed that :) We have a custom plugin folder and didnt realize that I should copy anything from the package plugin folder (since in documentation, I found out you implemented mots plugins into the server package itself).

Thank you for clarifying for me. I see the section now and will try the migration feature tomorrow.

Thank you again!

**Comment by tehpanta** [comment]
Well I see the screen as you captured them. Including that there are no configuration uploads available.

And the System > collectors (legacy) doesnt have Details section...or am I missing something?

**Comment by mpfz0r** [comment]
"Details" is referring to the details of a specific selector.
I attached a small demo screencast. However, we need to release sidecar 0.1.8 first, before you can
use that feature.

![sidecar-mig](https://user-images.githubusercontent.com/3034831/51523713-8e853680-1e2c-11e9-9895-ce3041ddd989.gif)
