### ISSUE TITLE
Message not fully read (response)

### ISSUE THREAD

**Issue by meltingice** [Graylog2/graylog2-server#555]
Every 30 seconds exactly I am getting the error:

```
WARN : org.elasticsearch.transport.netty - [graylog2-server] Message not fully read (response) for [18644953] handler org.elasticsearch.action.support.nodes.TransportNodesOperationAction$AsyncAction$4@1429abfa, error [false], resetting
```

I saw in #237 that it could be due to Elasticsearch incompatibilities, but I am running ES 0.90.10 on both of our nodes and graylog2-server 0.20.2-rc1.

Can anyone point me in the right direction as to what may be causing this? Thanks!

**Comment by bernd** [comment]
Closing this. Please re-open if you still see this issue with Graylog 1.0.0. Thank you!
