### ISSUE TITLE
Would "Mask password fields of inputs returned by the REST API. (#5432)" fix be made available to the next 2.5.x release? 

### ISSUE THREAD

**Issue by patrickyau** [Graylog2/graylog2-server#5550]
The fix to hide passwords returned by input REST API is a security bug. We would hope to see this fix added to the next fix release v2.5.2. Is it the current plan to include this fix to the upcoming fix release?

## Expected Behavior
We expect the critical security fix would be included in the next minor release (e.g. 2.5.2). 
https://github.com/Graylog2/graylog2-server/commit/a562a3393d4229fdda6c6c17aa264d1a7002c748

## Current Behavior
We have this security bug even in v2.5.1.

## Possible Solution
Add this fix to the build of v2.5.2.

## Steps to Reproduce (for bugs)
Setup an input plugin with a password field and get the configuration via REST API.

## Context
I have security review and found this issue.

## Your Environment
We are currently running v2.4.6. Since v2.5.1 was released before this bug was reported, we hope to upgrade to the next fix release that contains this fix.

* Graylog Version: 2.4.6+ceaa7e4
* Elasticsearch Version: ES v5.x
* MongoDB Version: unknown
* Operating System: unknown
* Browser version: Google Chrome Version 71.0.3578.98

**Comment by dennisoelkers** [comment]
Is switching over to 3.0 (coming out in the middle of February) an option for you?

**Comment by patrickyau** [comment]
Since it is a critical security fix, we would hope to see the fix in the next fix release. Is there one (e.g. v2.5.2) be made available in this month or some time in Feb before v3.0?

**Comment by patrickyau** [comment]
Our business cannot easily move to v3 in a short time. We have leveraged GL REST APIs that moving to v3 will take us more time to go through full test cycles.

**Comment by dennisoelkers** [comment]
> We have leveraged GL REST APIs that moving to v3 will take us more time to go through full test cycles.

What does that mean? What is the issue that would hold you back from updating?

Changes between v1 and v2 were way more drastic than between 2.4 and 3.0 (see [upgrading notes](https://github.com/Graylog2/graylog2-server/blob/master/UPGRADING.rst)).

**Comment by patrickyau** [comment]
Hi, Dennis, I have reviewed the list of changes from 2.x to 3.0. We noticed that rest_listen_uri, web_endpoint_uri, rest_transport_uri, rest_enable_tls, rest_port_start, web_listen_uri, rest_enable_gzip, web_endpoint_uri, rest_enable_cors, and rest_transport_uri have been renamed. We also used the beat input and pipeline processor. Therefore, we expect to have higher effort to test compatibility to switch from 2.x to 3.0.

It would be much easier for us to upgrade to v2.5.2 first before migration to v3.0, resolving the immediate critical security issue.

**Comment by edmundoa** [comment]
@patrickyau We plan to release 2.5.2 including a fix for this issue in the next days, so please stay tuned!

**Comment by patrickyau** [comment]
> 
> 
> @patrickyau We plan to release 2.5.2 including a fix for this issue in the next days, so please stay tuned!

Hi, @edmundoa, Graylog v3.0 has been GA'ed on Feb 14, 2019. Do you have any insight on when v2.5.2 will be released which will contain this fix? Thank you very much for your information.

**Comment by edmundoa** [comment]
@patrickyau the plan is still to release it very soon. We found other issues while finishing 3.0.0 that need to be backported into 2.5.2 and we are working on it. Thank you for your patience!

**Comment by bernd** [comment]
@patrickyau The 2.5.2 release including this fix is available now. An official announcement will follow next week.
