### ISSUE TITLE
[3.0b3] GET /gettingstarted refers to missing www.graylog.org/support URL

### ISSUE THREAD

**Issue by dch** [Graylog2/graylog2-server#5554]
The default page, https://graylog.your.domain/gettingstarted URL has an
"I'm stuck" button which links to the missing https://www.graylog.org/support/ page. 

* Graylog Version: v3.0.0-beta.3+2ef60d2

## expected behaviour

I'm taken to a link where I can shower you with $MONEY$ ? graylog community forums?

I grepped in graylog2-server and didn't find a reference for this, must be in some other module.

**Comment by bernd** [comment]
This has been fixed. Thank you for the report!
