### ISSUE TITLE
Geo-Location Processor, How can i get my location language 

### ISSUE THREAD

**Issue by admover** [Graylog2/graylog2-server#5555]
[geoname_id] => 6252001
                    [iso_code] => US
                    [names] => Array
                        (
                            [de] => USA
                            [en] => United States
                            [es] => Estados Unidos
                            [fr] => États-Unis
                            [ja] => アメリカ合衆国
                            [pt-BR] => Estados Unidos
                            [ru] => Сша
                            [zh-CN] => 美国
                        )

                )

Like this, How can get this value where location is zh-CN.

**Comment by jalogisch** [comment]
This is related to https://github.com/Graylog2/graylog2-server/issues/5443 

As we currently have only a single language interface we would only set the language fixed to English.
