### ISSUE TITLE
Cannot create GROK pattern with underscores in field name.

### ISSUE THREAD

**Issue by ddimick** [Graylog2/graylog2-server#5563]
## Expected Behavior
Graylog should accept underscores in field name and create the grok pattern.

## Current Behavior
Graylog returns "Could not test Grok pattern
Testing Grok pattern "test" failed with status: cannot POST https://graylog.my.domain/api/system/grok (400)"

## Steps to Reproduce (for bugs)
Create a grok pattern like `(?<test_field>test)`, it will fail. Remove the underscore and create `(?<testfield>test)`, it will succeed.

## Your Environment
* Graylog Version: 3.0.0-beta.3-1
* Elasticsearch Version: 6.5.4
* MongoDB Version: 4.0.5
* Operating System: Server CoreOS 4.14.88, docker 18.06.1-ce, client Windows 10 Pro
* Browser version: Chrome 71.0.3578.98, Firefox 62.0.3 and Edge 42.17134.1.0

**Comment by kmerz** [comment]
Unfortunately this is not fixable. The java Pattern matcher does not allow to have underscores in its named  groups: 

https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html#groupname

> A capturing group can also be assigned a "name", a named-capturing group, and then be back-
> referenced later by the "name". Group names are composed of the following characters. The first 
> character must be a letter.
> 
>    The uppercase letters 'A' through 'Z' ('\u0041' through '\u005a'),
>    The lowercase letters 'a' through 'z' ('\u0061' through '\u007a'),
>    The digits '0' through '9' ('\u0030' through '\u0039'), 

The only alternative would be to implement our own Pattern Matcher which would be slightly out of scope.

**Comment by bernd** [comment]
@ddimick We fixed this issue in master and it will be backported into the upcoming 3.0.1. release.

**Comment by ayoublab92** [comment]
hello everyone, please i need hepl  i have the same problem with Graylog 2.5  I am blocked for creating GROK PATTERN , Graylog returns " Saving Grok pattern “name og grok pattern ” failed with status cannot POST http://@IP of graylog/api/system/grok (400)"

**Comment by kmerz** [comment]
@ayoublab92 github is meant for reporting bugs and discussing them. The reported bug is solved and backported to 3.0.1. Please upgrade your graylog to the fixed version. Try https//community.graylog.com to find help otherwise. This is not a forum.
