### ISSUE TITLE
Wrong histogram resolution in streams view

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#5568]
If you select "All Messages" from the stream view, graylog tries to render the default message count histogram with a resolution of minutes.
This request leads to an OOM on the server, and ends up in a loop.

## Expected Behavior
In contrast to the global search page, it should set the resolution to a reasonable
default value, (Years) in case of the global search.
Choosing a sane default resolution works for all relative time ranges, just not for "All Messages"

In addition, the 500 error returned by the API should be displayed to the user
and not end up in a site reload loop.

## Steps to Reproduce (for bugs)

0. (Provided that your index has enough messages)
1. Click on Streams -> All messages (or some other stream)
2. Chose "All messages" as a time range

* Graylog Version: 3.0-beta3  (probably also existent in earlier versions)

**Comment by mpfz0r** [comment]
After a little digging: This is related with PR #2289

Things to note:
1.) All indices checked by this code are deflectors and none of them has a valid timestamp.
2.) The code does not check whether only one index was searched.

**Comment by bernd** [comment]
This shouldn't be an issue anymore with the new search page. Please re-open if this is still an issue. Thank you!
