### ISSUE TITLE
Entities removed from new content pack version

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#5579]
## Expected Behavior
Creating a new version of a content pack, keeps the existing entities in the content pack unless deselected by the user. Entities that were in the previous content pack version should also be highlighted during edit.

## Current Behavior
Entities existing in the original content pack version appear as duplicates on the entity selection list, and are not included in the next content pack version, even if they are checked. 
![new-revision](https://user-images.githubusercontent.com/716185/51614855-ce304900-1f26-11e9-8f1f-7b555bd4644a.gif)

## Steps to Reproduce (for bugs)
1. Create content pack with some entities
2. Create new content pack version
3. See that the previously selected items appear double, and they have the same icon as the existing server entities
4. See that they are not included in the new revision in the end

## Your Environment
* Graylog Version: Graylog 3.0.0-beta.4-SNAPSHOT (87afab1)
* Browser version: Firefox developer edition (66.0b1)

**Comment by bernd** [comment]
Fixed in https://github.com/Graylog2/graylog2-server/pull/5614
