### ISSUE TITLE
graylog 3.0.0-8.beta.3: Views -> Loading component failed

### ISSUE THREAD

**Issue by pettai** [Graylog2/graylog2-server#5587]
Graylog 3.0.0-8.beta.3 Enterprise -> Views gives error:
Loading component failed: Loading chunk d1453899-6 failed. (error: https://graylog-test/assets/plugin/org.graylog.plugins.enterprise.EnterprisePlugin/ViewManagementPage.67b4c9566d2960f727f7.js)
Graylog 3.0.0-beta.1+e94dc5a on xxx-instance.cloud.sunet.se (Oracle Corporation 1.8.0_191 on Linux 4.4.0-36-generic) 

## Current Behavior
Doesn't work

## Steps to Reproduce (for bugs)
Upgraded/installed graylog-server + enterprise from the apt-repo
 
## Your Environment

* Graylog Version: 3.0.0-8.beta.3 (apt version)
* Elasticsearch Version: 5.x
* MongoDB Version: 3.6
* Operating System: Ubuntu 16.04
* Browser version: Firefox stable

**Comment by pettai** [comment]
Perhaps not, but I didn't have the views page open during the upgrade. I tested all the other pages like Extended Search etc., and they loaded & seemed to work like they should, though.
Anyway, I closed everything down and restarted the server components, and after that the Views page started to work as expected. 

Should I close this one?

**Comment by dennisoelkers** [comment]
It is a known issue. If you visited a page once before the upgrade, your browser will have the assets in memory. If not, it must load them when visiting the page. If you do that after a server upgrade was performed, the name of the asset requested by the browser will be invalid. I suggest closing this issue, but we will work on preventing this to happen in the future by advising the user to do a refresh in those cases (as described in #5588).

**Comment by kmcminn** [comment]
ran into this when upgrading from 3.1 -> 3.3. It wasn't a cached asset issue. In the end the only thing that resolved it was rebuilding mongo from scratch.
