### ISSUE TITLE
graylog-pre-3.0.0-8.beta.3 errors during OVA deploy on ESXi 6.7U1

### ISSUE THREAD

**Issue by SimplyRyan** [Graylog2/graylog2-server#5594]
## Expected Behavior

When deploying the OVA on VMWare ESXi 6.7u1 the deployment should complete without error. 

## Current Behavior

Deploying the OVA via the GUI results in the following error at step 5.

> Line 66: OVF hardware element 'ResourceType' with instance ID '5': No support for the virtual hardware device type '35'.

![graylog_beta](https://user-images.githubusercontent.com/5630595/51724059-b20be380-20af-11e9-986c-b999033bf0a4.png)

## Possible Solution

Unpack graylog-pre-3.0.0-8.beta.3.ova (unpack the ova with a compression utility like 7zip) and edit the graylog-preview.ovf file, remove the following section and save the file. 

```
         <Item>
            <rasd:AddressOnParent>3</rasd:AddressOnParent>
            <rasd:AutomaticAllocation>false</rasd:AutomaticAllocation>
            <rasd:Caption>sound</rasd:Caption>
            <rasd:Description>Sound Card</rasd:Description>
            <rasd:ElementName>sound</rasd:ElementName>
            <rasd:InstanceID>5</rasd:InstanceID>
            <rasd:ResourceSubType>ensoniq1371</rasd:ResourceSubType>
            <rasd:ResourceType>35</rasd:ResourceType>
         </Item>
```
Looks like a sound device that could possibly be removed from the OVA build process.

## Steps to Reproduce (for bugs)

1. Download OVA
2. Deploy OVA via ESXI GUI
3. Error noted on step 5

## Your Environment

* Graylog Version: graylog-pre-3.0.0-8.beta.3.ova
* Operating System: ESXI 6.7 U1

**Comment by mariussturm** [comment]
Closing this in favour of https://github.com/Graylog2/graylog2-images/issues/211 please follow that issue for more informations.
