### ISSUE TITLE
Wrong redirects in graylog web interface and nginx

### ISSUE THREAD

**Issue by agatahochor** [Graylog2/graylog2-server#5610]
I'm having problem with Graylog web interface and I wonder if it's a bug or misconfiguration.
It happens with graylog-server 3.0.0-beta.4 and nginx 1.10.3 as a web server. When I click on something from _System_ list, for example _Inputs_ I get redirected to /graylog/graylog/system/inputs instead of /graylog/system/inputs.

## Expected Behavior
Every item from _System_ list redirects to /graylog/system/<item>.

## Current Behavior
Every item from _System_ list redirects to /graylog/graylog/system/<item>.

## Your Environment
graylog.conf:
```
is_master = true
node_id_file = /etc/graylog/server/node-id
password_secret = ****

root_username = ****
# Create one by using for example: echo -n yourpassword | shasum -a 256
root_password_sha2 = ****

root_email = root@localhost
root_timezone = UTC

plugin_dir = /usr/share/graylog-server/plugin

http_bind_address = 192.168.2.154:9000
http_publish_uri = http://192.168.2.154:9000/

rotation_strategy = count

elasticsearch_hosts = http://127.0.0.1:9200 
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 4
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog

allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_analyzer = standard
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /var/lib/graylog-server/journal
lb_recognition_period_seconds = 3

mongodb_uri = ****
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5

content_packs_dir = /usr/share/graylog-server/contentpacks
content_packs_auto_load = grok-patterns.json
proxied_requests_thread_pool_size = 32
```

nginx conf: 
```
server {
       listen 443 ssl default_server;
       location /graylog/ {
         proxy_set_header Host $http_host;
         proxy_set_header X-Forwarded-Host $host;
         proxy_set_header X-Forwarded-Server $host;
         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header X-Graylog-Server-URL https://jetblue.isaacloud.com/graylog/;
         rewrite          ^/graylog/(.*)$  /$1  break;
         proxy_pass       http://graylog/;
       }
  }
```
* Graylog Version: 3.0.0-beta.4+299ccfa, codename Space Moose
* Elasticsearch Version: 5.6
* MongoDB Version: 3.2
* Operating System: Ubuntu 16.04
* Browser version: Firefox 64.0

**Comment by jalogisch** [comment]
you are missing the `proxy_pass` map - but the rewrite is not needed.

```
  	# Graylog reverse proxy
    	location /graylog/ {
        	proxy_set_header    Host $http_host;
        	proxy_set_header    X-Forwarded-Host $host;
        	proxy_set_header    X-Forwarded-Server $host;
        	proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        	proxy_set_header    X-Graylog-Server-URL https://$http_host/graylog/;
        	proxy_pass          http://graylog_web_interface;
        }
```

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by agatahochor** [comment]
I'm sorry I didn't include all nginx configuration,but proxy pass is present there... If it wasn't there I wouldn't be able to access web interface at all. It's not the case in this situation.

**Comment by agatahochor** [comment]
Could you reopen?

**Comment by jalogisch** [comment]
please re-read what I have written. 

> the rewrite is not needed

my configuration is working exactly like I have written in my lab - if you can provide us more information how we can reproduce that, please re-open the issue. If not you are invited to join the community.

**Comment by agatahochor** [comment]
I tried configuration without rewrite and it still works the same

**Comment by agatahochor** [comment]
But thank you for checking it out - i'm gonna look for help in community since it doesn't seem to be bug.

**Comment by i5okie** [comment]
I still think this is a bug with graylog.
When you hover over Search, streams, alerts, dashboards, sources.
the links will as per base_path..   `https://mydomain.com/graylog/search`... etc
but the links under system dropdown menu show up as:
`https://mydomain.com/graylog/graylog/system/overview`... etc and thats not reverse proxy fault that is clearly something with web interface, the way links are generated for the system submenu specifically.

**Comment by knobbysideup** [comment]
This is still an issue.  I have the same problem using Apache as a reverse proxy.

**Comment by agatahochor** [comment]
just FYI - this issue is discussed here: 
[https://community.graylog.org/t/nginx-reverse-proxy-https-with-graylog-3-0-on-subdirectory-e-g-server-com-graylog/8581/6](url)
