### ISSUE TITLE
Index Rotation Strategy not changing in 3.0 Preview

### ISSUE THREAD

**Issue by rblumenthal** [Graylog2/graylog2-server#5617]
Index Rotation Strategy settings not persisting after making changes in the web UI.

## Expected Behavior
When changing index rotation strategy to 'Index Time' and 'P1D' it would keep those settings after submitting

## Current Behavior
No matter what option is chosen for index rotation strategy, it goes back to 'Index Message Count' with a blank number.

## Your Environment

* Graylog Version: 3.0.0-rc.1
* Elasticsearch Version: 6.6
* MongoDB Version: 3.6
* Operating System: CentOS 7
* Browser version: Latest Chrome and Firefox

**Comment by bernd** [comment]
@rblumenthal Thank you for the report. We can reproduce it and are working on a fix.

**Comment by edmundoa** [comment]
This also affects adjusting index retention settings on rc.1.

**Comment by edmundoa** [comment]
Refs #5595

**Comment by bernd** [comment]
@rblumenthal Thank you again for the report! It will be fixed in the next release candidate of 3.0.0.

**Comment by rblumenthal** [comment]
> @rblumenthal Thank you again for the report! It will be fixed in the next release candidate of 3.0.0.

Great! Happy to have actually helped out.
