### ISSUE TITLE
Long query causes 400 Bad Request

### ISSUE THREAD

**Issue by vanderstack** [Graylog2/graylog2-server#5618]
logs are entering graylog from multiple sources and need to be aggregated to create a useful overview of what happened in chronological order. 

This involves searching messages with the query UserName:XXXX, and extracting the fields source, requestId, so that I have a new query:
(source: serverN, requestId: N) OR (source: serverN, requestId: N) OR (source: serverN, requestId: N).

If this query includes hundreds of requests, it becomes too long and the graylog api returns a 400 error:

## Expected Behavior
The query should be evaluated rather than returning a 400 response

## Current Behavior
The api returns a 400 response code

## Steps to Reproduce (for bugs)
enter the following as the url after your graylog server hostname:
search?rangetype=relative&fields=message%2Csource&width=1920&highlightMessage=&relative=1800&q=RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001+OR+RequestId%3A0HLK5BNM2U64O%5C%3A00000001

## Context
http request logs are entering graylog from multiple sources and need to be aggregated to create a useful overview of what happened in chronological order. 

This involves searching messages with the query UserName:XXXX, and extracting the fields source, requestId, to create a new query:

(source: serverN, requestId: N) OR (source: serverN, requestId: N) OR (source: serverN, requestId: N)...

The goal is to view a chronological history of logs for a users entire http session across all load balanced servers.

**Comment by kroepke** [comment]
Is there more information in the server log file?
