### ISSUE TITLE
'Show received messages' link can trigger OOM with field charts query

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#5620]
Once a chart is created on the search page, it keeps its initially configured resolution
and query. Extending the search time range to `all messages` can create a query
that runs either Graylog or Eleasticsearch out of memory.
(See #5559)

This is easily achieved by accident, since the 'Show received messages' link
on inputs defaults to `range=0`.

## Possible Solution
Change the link to use a range of `last 7 days` instead.

## Steps to Reproduce (for bugs)

![chart-oom](https://user-images.githubusercontent.com/3034831/51983050-0c35eb80-2498-11e9-884e-5ac24dd4f754.gif)

* Graylog Version: 3.0 rc1
* Elasticsearch Version: 6.6

**Comment by xavier-isecurity** [comment]
I think it will be better 5 minutes them 7 days, like streams, them the person can change it. 

There are inputs that in 7 days have large volumes.

**Comment by mpfz0r** [comment]
Since there was some controversy about my PR, let explain why this hasn't been fixed already...

Apparently, the 'show all messages' default was picked, because it would also include messages
with future timestamps, and some customers had issues finding there messages.

To address this, the link could get the messages from the last 5 minutes *and* everything from the future.

**Comment by aim4r** [comment]
Not sure if relevant, but please note that in some setups, including mine, last 5 minutes is not even an option. The minimum we have setup under "Search Configuration" is one hour.
