### ISSUE TITLE
Ability to customise charts, tables and widgets

### ISSUE THREAD

**Issue by Gradle999** [Graylog2/graylog2-server#5625]
I noticed an archived feature request for the ability to customise the x and y axis of charts and graphs within the WebGUI. Has this feature been carried forwards?

Ideally the feature would allow for something other than time along the x axis, so for example you could customise it to show IP addresses, hosts, usernames etc.

Also the ability to add or change the columns within tables, so you can tie multiple fields from a single query into the table. For example a query searching for all failed logins could have a table with the columns "time", "username" and "IP address", allowing for swifter problem solving.

**Comment by dennisoelkers** [comment]
Hello @Gradle999! Thanks for opening the issue. What you are describing is part of the new "Views" feature. You can use it in the upcoming 3.0 release. It is part of the enterprise feature set though, so you need to obtain a license (which is free for <=5gb/day).

**Comment by Gradle999** [comment]
Thanks @dennisoelkers, unfortunately I've got more that 5GBs a day so I've been unable to take advantage of the views feature. Was hoping it might be something in the pipeline for the open source version.

**Comment by dennisoelkers** [comment]
@Gradle999: Good news! The core functionality of the views is becoming open source and part of core in 3.1!

**Comment by bernd** [comment]
This is now part of the open source product.
