### ISSUE TITLE
Changed configuration of an output is not reflected on other nodes

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#5634]
## Expected Behavior

When changing the configuration of an output its settings should be active immediately on all nodes in the cluster.

## Current Behavior

Output configuration is not reloaded on other nodes than the one it was changed on, until these Graylog server(s) is/are restarted.

## Steps to Reproduce (for bugs)

1. Create an output (regardless of GELF or STDOUT)
2. Update its settings (e.g. change Prefix for STDOUT or host/port for GELF) on node A
3. Verify that new settings are not used on node B
4. Restart Graylog server(s) on node B
5. Verify that new settings are used on node B

## Your Environment

* Graylog Version: 3.0.0-rc.1
* Elasticsearch Version: 6.5.0
* MongoDB Version: 3.6.8
* Operating System:
* Browser version:

**Comment by bernd** [comment]
@dennisoelkers I am unable to reproduce that with 3.0.0-rc.1 in a production build.

I tried multiple ways. Default stream, regular stream. The config of my log output was always updated immediately.

**Comment by bernd** [comment]
I missed the that this is about a multi node setup, sorry. I only tested a single node.

**Comment by HenryTheSir** [comment]
Is this bug on any milestone? The behaviour creates an inconsistent output behaviour and always restarting is not really a solution.
