### ISSUE TITLE
Disable email field for LDAP User

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#5639]
## Expected Behavior
A field which can't be set by the admin user should not be configurable.

## Current Behavior
If the user changes the email address of a LDAP User the email will be set to the LDAP value after authentication.

## Possible Solution
- Disable email field in Users form for users from LDAP

or

- Keep email address after change and only fill it while creation or when empty. 

## Steps to Reproduce (for bugs)
1. Change email address of LDAP user
2. Log in as LDAP user
3. Look for the email address of the LDAP user

## Your Environment
* Graylog Version: Graylog 3.0 RC1 (aad8a4d51503155afc3cc03d0c904f237b0c3127)
* Operating System: Ubuntu 16.04
* LDAP Server: ActiveDirectoryStudio 2.0.0.v20170904-M13

**Comment by bernd** [comment]
This has been fixed in 4.0.
