### ISSUE TITLE
Prevent creating multiple global inputs on the same port

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#564]
Moved from original: https://github.com/Graylog2/graylog2-web-interface/issues/619

If I run:

```
curl --user admin:admin1 -XPOST http://localhost:12900/system/inputs -H "Content-Type: application/json" -d '{"type": "org.graylog2.inputs.gelf.udp.GELFUDPInput", "creator_user_id": "admin", "title": "gelf-udp", "global": true, "configuration": { "port": 12201, "bind_address": "0.0.0.0" } }'
```

multiple times, graylog will create the same input multiple times, even though the second one will obviously conflict with the first one.  If a bad request were returned instead, that would be much more helpful.

**Comment by florianvolle** [comment]
2,5 years later we could not reproduce this. Please reopen it still relevant ;)
