### ISSUE TITLE
Allow remove_field() function to take a regular expression or glob

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5653]
The `remove_field()` pipeline function currently only allows to remove fields that match an exact name. This works if I know which fields my message will have, but not for more dynamic data, like in DNS responses that can contain multiple answers to a request.

## Expected Behavior

I'd like to be able to remove all fields of a message that match a regular expression or glob pattern.

## Current Behavior

Currently, I can only remove fields if I know the name of each field.

## Context

![2019-02-07-121406_201x988_scrot](https://user-images.githubusercontent.com/35022/52433115-e4ff9f80-2ad1-11e9-99c9-40ee1002d009.png)

In this example, I'd like to call something like `remove_fields('dns_authorities_*')`.

**Comment by thaibinhindex** [comment]
I'm facing this problem
