### ISSUE TITLE
Checkboxes on Lookup Table Cache page are broken

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5658]
Not going to write a long description, because I think this shows the problem well:

![boxes](https://user-images.githubusercontent.com/35022/52441028-36fdf080-2ae5-11e9-8a19-f38edb4559c2.gif)

* Graylog Version: Graylog 3.0.0-rc.2+2667ff2
* Browser version: Firefox 65.0 on Ubuntu 18.04

**Comment by bernd** [comment]
I changed the title because this is about lookup table caches and not processing pipelines.
