### ISSUE TITLE
Windows File Limit Warning

### ISSUE THREAD

**Issue by droud** [Graylog2/graylog2-server#568]
When ElasticSearch is installed on a Win64 platform, it reports a file limit of -1, which causes graylog2 (via the web interface) to report an issue with ElasticSearch.  The file limit of -1 represents "unlimited" on Win64, thus should not trigger this warning.

**Comment by bernd** [comment]
Closing this because lots of stuff changed. Please re-open if you still see this problem with Graylog 1.0.0 and Elasticsearch 1.4.x. Thank you!
