### ISSUE TITLE
Graylog 3.0.0. broke 100-Expect

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/graylog2-server#5690]
## Expected Behavior
The 100-Expect should work for HTTP inputs. See https://github.com/Graylog2/graylog2-server/issues/1939 for information (related RFC, etc).

## Current Behavior

After client sends
`
POST /gelf HTTP/1.1
Content-Type: application/json; charset=utf-8
Host: server:444
Content-Length: 304
Expect: 100-continue
Connection: Keep-Alive
`
Graylog silently decides to close connection. 

## Possible Solution
No idea. Probably the Netty upgrade broke this between 2.5.0 and 3.0.0.

## Steps to Reproduce (for bugs)

1. Configure HTTP input
2. Use client that utilizes 100-Expect
3. The problem repdocudes

## Context

I wouldn't care otherwise, but .NET based clients and Microsoft's default libraries want to use this feature. Disabling the feature from clients is possible, but extra work.

## Your Environment

* Graylog Version: 3.0.0
* Elasticsearch Version: 5.6.x
* MongoDB Version: 4.x
* Operating System: Linux
* Browser version: Any

**Comment by mikkolehtisalo** [comment]
I believe this might be related:
```
2019-02-19T12:40:17.001+02:00 ERROR [AbstractTcpTransport] Error in Input [GELF HTTP/57cfeeb43e8b28286339d9d9] (channel [id: 0xdd6b11e5, L:/xx.xx.xx.xx:xx ! R:/xx.xx.xx.xx3:44478]) (cause java.lang.UnsupportedOperationException: unsupported message type: DefaultFullHttpResponse (expected: ByteBuf, DefaultFileRegion))
```

**Comment by wrigley418** [comment]
I observe the same results. It was working with 2.5.1+34194da, but received error mentioned above when running new 3.0 release. I viewed a packet capture and my HTTP client is also sending "Expect: 100-Continue"
