### ISSUE TITLE
Dashboard infobox out of place

### ISSUE THREAD

**Issue by Leyroh** [Graylog2/graylog2-server#5691]
there is a problem on the Dashboard. While customizing the graphs and move them around the Infobox, which shows the results, is always missplaced as soon as the graph is not on top of the window. The type of widget doesn't matter.
In this example my cursor is on top of the blue line:
![example](https://user-images.githubusercontent.com/47777008/53007308-465f3100-3437-11e9-8d69-bd0aa7af08f0.png)

## Expected Behavior

The infobox should be right next to the cursor.

## Current Behavior

the infobox appears way too low on the screen and behind other widgets.

## Steps to Reproduce (for bugs)

1. Create multiple widgets on a dashboard
2. Just move the widgets a bit up and down and scale
3. Let the widget show you the infobox and it's misplaced

## Context

It is a problem on all of my dashboards and not a "maybe it happens and maybe it won't"-bug :smile:

## Your Environment

* Graylog Version: 3.0
* Elasticsearch Version: 6.6
* MongoDB Version: v4.0.6
* Operating System: Server Centos 7 / Client Ubuntu 18
* Browser version: Firefox Version 65.0 (64-Bit)

**Comment by bernd** [comment]
We are using a new widget library in the new search page since Graylog 3.2 so this shouldn't be an issue anymore. Please open a new issue if you still see this issue in the new system. Thank you!
