### ISSUE TITLE
Cannot use extracted fields in notifications

### ISSUE THREAD

**Issue by Nklya** [Graylog2/graylog2-server#5698]
It seems that it's impossible to use extracted fields in notifications.

## Expected Behavior

I have input from Filebeat and 'GROK pattern' extractor which extracts different fields from the message. For example `username`.
The pattern looks like this `%{SYSLOGBASE}%{SPACE}New session %{BASE16NUM:session_id} of user %{USERNAME:user}.`

I checked this in both Graylog 2.5 and 3.0.

## Current Behavior

I want to use an extracted field in the notification. And when I put this to Slack alert
```
Message:
${foreach backlog message}${message.user}
${end}
```

I get an error 
```
com.floreysoft.jmte.message.ParseException: Error while parsing 'message.user' at location (2:29): Property 'user' on object 'source: hostname | message: Feb 20 11:37:34 hostname systemd-logind[779]: New session 24878 of user username. { offset: 194770 | gl2_remote_ip: 1.1.1.1 | gl2_remote_port: 56506 | streams: [2341234213412342134, 000000000000000000000001, 5c362f202f9e6e5e02daf781] | session_id: 421342 | pid: 434 | program: systemd-logind | type: auth | gl2_source_input: 234234234234234 | logsource: hostname | file: /var/log/auth.log | name: hostname | gl2_source_node: 2341234213412342134-fdf | _id: 2341234213412342134 | facility: filebeat | user: username | timestamp: 2019-02-20T11:37:43.728Z }' can not be accessed: "java.lang.NoSuchFieldException: user"!
```

But when I try to use fields that existed before extracting, like `source` or `timestamp`, all is ok.

## Possible Solution

I think that notification parser uses message before extraction.

## Steps to Reproduce (for bugs)

1. Add extractor to input
2. Try to use an extracted field in notification
3. Get an error

## Context

Cannot use extracted fields in Alarms

## Your Environment

* Graylog Version: 3.0.0-12
* Elasticsearch Version: 6.6.0
* MongoDB Version: 4.0.2
* Operating System: Ubuntu 18.04.1 LTS
* Browser version: Google Chrome 72.0.3626.109

P.S. I haven't found related issues

**Comment by tanji** [comment]
Hello,

same issue here:

```Error sending notification at 2019-02-25 14:03:34: Error while parsing 'message.site' at location (10:12): Property 'site' on object 'source: c-fsn1-92 | message: Uploaded file to S3 https://transport/fb6cb35977f4c/customer/2019-02-25_14:03:11_destination_error_113871.csv.compressed.gz { process: 5c73db88-0ffb-46f6-a22e-000000073ba2 | level: 6 | gl2_remote_ip: 1.1.1.1 | gl2_remote_port: 33476 | streams: [000000000000000000000001, 5c6159a62a0013450a0] | gl2_source_input: 54324939e4bdf1b7ace | site: 474018 | loglevel: info | name: bin-customer | gl2_source_node: 098a5358-ab21-4c65-a1ca-763266ca2392 | _id: b6605a44-38fd-11e9-bda2-0242ac120002 | facility: bin-customer | timestamp: 2019-02-25T13:03:14.916Z }' can not be accessed: "java.lang.NoSuchFieldException: site"!```

**Comment by tanji** [comment]
Woops... RTFM.

The message fields are accessible as a key-value map in `message.fields`.
@Nklya hence your field would be accessible by `message.fields.user`.
The same remark applies to the error above, that I solved by replacing `message.site` by `message.fields.site`.

**Comment by kroepke** [comment]
Unfortunately in the current alerting system each notification plugin is responsible for its own message formatting, so the documentation is misleading here.

For the email callback the correct way to refer to a custom field is `message.fields.user` in your example.
The Slack plugin appears to use `backlog` instead of `fields`.

We'll look at making this more consistent in upcoming versions.

**Comment by Nklya** [comment]
Thanks, @tanji, @kroepke !

It works now)

**Comment by Nklya** [comment]
It seems that Slack plugin uses the same name.

My working example:
```
${foreach backlog msg}
user: ${msg.fields.user}
host: ${msg.source}
time: ${msg.timestamp}
${end}
```
