### ISSUE TITLE
Graylog nodes running as a cluster in docker containers are unable to communicate with one another

### ISSUE THREAD

**Issue by steven-cherry** [Graylog2/graylog2-server#5700]
When running a Graylog cluster in docker containers spread across different hosts certain features refuse to work such as the /system/nodes. 

Clustering should work in Docker and non-Dockerised environments

## Current Behavior

This is because each graylog instance registers it's host name in MongoDB, the other nodes will use the host name listed in Mongo to connect to one another's API interface. When running in a docker container the host name will not be resolvable from nodes running on other hosts.

## Steps to Reproduce (for bugs)

1. Create a Graylog cluster running in docker containers spread accross at least 2 hosts
2. Access the UI 
3. Browse to the /system/nodes path

## Context

I'm trying to run Graylog using AWS ECS which of course is a container orchestration system.

## Your Environment

* Graylog Version: 2.4.6
* Elasticsearch Version: 5.6
* MongoDB Version: 4
* Operating System: Amazon Linux 
* Browser version: Chrome 71.0.3578.98

**Comment by jalogisch** [comment]
you need to configure how each graylog node is reachable by the other nodes for the inter-cluster-communication.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
