### ISSUE TITLE
Graylog 3.0 GELF HTTP error

### ISSUE THREAD

**Issue by mds1455975151** [Graylog2/graylog2-server#5705]
## Expected Behavior
>  grep -vE "^$|^#" /etc/graylog/server/server.conf
is_master = true
node_id_file = /etc/graylog/server/node-id
password_secret = xxx
root_password_sha2 = xxx
root_email = "graylog@xxx.cn"
root_timezone = Asia/Shanghai
bin_dir = /usr/share/graylog-server/bin
data_dir = /var/lib/graylog-server
plugin_dir = /usr/share/graylog-server/plugin
http_bind_address = 0.0.0.0:9000
http_publish_uri = http://10.2.6.75:9000/
http_external_uri = https://graylog.xxx.cn/
http_enable_cors = true
elasticsearch_hosts = http://10.2.6.74:9200
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 4
elasticsearch_replicas = 1
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_analyzer = standard
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /var/lib/graylog-server/journal
lb_recognition_period_seconds = 3
mongodb_uri = mongodb://localhost/graylog
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5
transport_email_enabled = true
transport_email_hostname = smtp.exmail.qq.com
transport_email_port = 465
transport_email_use_auth = true
transport_email_auth_username = graylog@xxx.cn
transport_email_auth_password = xxx
transport_email_subject_prefix = [graylog]
transport_email_from_email = graylog@xxx.cn
transport_email_web_interface_ur = https://graylog.xxx.cn
transport_email_web_interface_url = https://graylog.xxx.cn
proxied_requests_thread_pool_size = 32
![image](https://user-images.githubusercontent.com/12950929/53149335-58cc9c80-35e8-11e9-8702-4c33e2423fa9.png)

> tail -f /var/log/graylog-server/server.log 
2019-02-21T14:46:18.063+08:00 ERROR [AbstractTcpTransport] Error in Input [GELF HTTP/5c6e1f27592b033018e360d5] (channel [id: 0xfe17d94b, L:/10.2.6.75:12201 ! R:/100.120.71.128:10719]) (cause io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer)
2019-02-21T14:46:18.278+08:00 ERROR [AbstractTcpTransport] Error in Input [GELF HTTP/5c6e1f27592b033018e360d5] (channel [id: 0x0ab87910, L:/10.2.6.75:12201 ! R:/100.121.4.129:50178]) (cause io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer)
2019-02-21T14:46:18.644+08:00 ERROR [AbstractTcpTransport] Error in Input [GELF HTTP/5c6e1f27592b033018e360d5] (channel [id: 0x1cb49698, L:/10.2.6.75:12201 ! R:/100.121.4.1:24999]) (cause io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer)

## Environment
* Graylog Version: graylog-server-3.0.0-12.noarch
* Elasticsearch Version:elasticsearch-6.6.1-1.noarch
* MongoDB Version:mongodb-org-server-3.6.10-1.el7.x86_64
* Operating System:CentOS Linux release 7.4.1708 (Core)
* Browser version:any

**Comment by deeshe** [comment]
I'm closing this issue, as it is duplicating #5720 . Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
