### ISSUE TITLE
The manifest repo for graylog2-web-interface is missing

### ISSUE THREAD

**Issue by jtryan** [Graylog2/graylog2-server#5709]
## Expected Behavior

Yarn start in for the graylog fron end should run withour error

## Current Behavior

It returns this error
`Error: ENOENT: no such file or directory, open '/projects/graylog-nginx/test/graylog2-server/graylog2-web-interface/manifests/vendor-manifest.json'`

-- from the `manifests/package.json1` file, the `vendor-manifest.json` file is available at 

`"repository": {
    "type": "git",
    "url": "git+https://github.com/Graylog2/graylog-web-manifests.git"`

## Possible Solution

Put the repository back online or include the file in the current repo.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

I cannot build and run the front end interface
## Your Environment

* Graylog Version: 3.0.0
* Elasticsearch Version: n/a
* MongoDB Version: n/a
* Operating System: ubuntu 16., os x Mojave
* Browser version: n/a

**Comment by jtryan** [comment]
I think it is my error. I needed to run `yarn run build` before `yarn start`.

**Comment by zhansang** [comment]
disable_plugins 不是内部命令
