### ISSUE TITLE
Support Elastic Common Schema (ECS)

### ISSUE THREAD

**Issue by gruselglatz** [Graylog2/graylog2-server#5711]
Support the Elastic Common Schema to improve global search when using Graylog for Logs and Kibana for other stuff. So we can use global Filters in our Dashboards and use Log data form Graylog and Metrics from APM etc.

https://github.com/elastic/ecs#client

Related Issue: #4583

## Your Environment
Awsome Graylog 3.0 for Logs and Logbased Metrics + Sidecar. ELK Stack for APM, Metricbeat and so on.

**Comment by jalogisch** [comment]
This is kind of related that we do not have dots in field names - but the task of mapping the data into the specific fields is something you need todo in the processing pipelines. If the sender does not follow that schema.

I'll close this as we already have the request for the dots in field names - what was removed by elastic and two versions later re-enabled. What is the reason Graylog does not allow this. With the drop of ES2 support it would be possible to re-allow this - when technical no other reasons are given.

**Comment by cpmoore** [comment]
To clarify, ECS still advises against dots in the field names, rather the dot notation is used to express nested fields.  Eg `http.response.status_code: 200` is actually 
```
{
  "http": {
    "response": {
      "status_code": 200
    }
  }
}
```

**Comment by zez3** [comment]
https://www.elastic.co/guide/en/ecs/master/ecs-faq.html#dot-notation
