### ISSUE TITLE
MOTD after Login (infobox)

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#5712]
## Expected Behavior
As administrator I should be able to create a message that is shown as notification to all users after login - similar to the license warning at the top of the page.

## Current Behavior
No option is given to notify all users.

## Context
It might be needed in a distributed company that the admin of a system can inform all users that maintenance work is going on. As simple example why you want to give all users a notification on login.

**Comment by supahgreg** [comment]
It'd be nice if the notification (perhaps as an icon in the header similar to GitHub?) were somewhat dynamic, also appearing for users that were already logged in and going away when the message gets unset by an admin.  It's not uncommon for tabs to be left open for a while.

**Comment by kroepke** [comment]
This has been part of Graylog Enterprise since 4.1.
