### ISSUE TITLE
Graylog 3.0 System/Nodes -> Nodes view bug

### ISSUE THREAD

**Issue by bensnet1** [Graylog2/graylog2-server#5717]
Graylog 3.0 System/Nodes -> Nodes view bug

## Expected Behavior
System/Nodes -> Nodes view should give each nodes individual JVM status and message buffer numbers. ( this used to work this way )

## Current Behavior
System/Nodes -> Nodes view provides a single nodes JVM and buffer status and displays it across all the nodes in the cluster making the information useless.

## Possible Solution
Code fix.

## Steps to Reproduce (for bugs)

1. System/Nodes -> Nodes view on an older version of Graylog say 2.4.7
2. System/Nodes -> Nodes view on 3.0 Graylog
3. Compare display of JVM and message buffer
4.

## Context
This is needed for making sure a node does not overwhelmed in an AWS deployment where the ELB does not respect throttling. We use an alert based of the API to tell us if a node is filling up its buffer.

## Your Environment

* Graylog Version: Graylog 3.0.0+db6cf59
* Elasticsearch Version: AWS Elastic
* MongoDB Version: 3.x
* Operating System: Ubuntu
* Browser version: Firefox latest

**Comment by coffee-squirrel** [comment]
Do each of your nodes have a unique [`http_publish_uri`](https://github.com/Graylog2/graylog2-server/blob/3.0.0/misc/graylog.conf#L106)?  Sounds like it might be set to the same as [`http_external_uri`](https://github.com/Graylog2/graylog2-server/blob/3.0.0/misc/graylog.conf#L122).

FWIW, we're not seeing this issue under `3.0.0+db6cf59`.

```
# Node 1
is_master = true
http_bind_address = 0.0.0.0:8443
http_publish_uri = https://server1.mydomain.com:8443/
http_external_uri = https://mygraylog.mydomain.com/

# Node 2
is_master = false
http_bind_address = 0.0.0.0:8443
http_publish_uri = https://server2.mydomain.com:8443/
http_external_uri = https://mygraylog.mydomain.com/
```

**Comment by bensnet1** [comment]
Thanks for providing some suggestions. We have an immutable image bake via Spinnaker for this. I noticed we were using the old config file. Changing to the new names in the way you suggest worked. However, I used a wildcard so we can bake and image. Thanks and sorry for the overlooking of the config file on my end.
