### ISSUE TITLE
AD user can't create dashboard

### ISSUE THREAD

**Issue by Evgen787** [Graylog2/graylog2-server#5718]
External users from AD, cant create Dashboard..

## Expected Behavior
1) Create Dashboard Role
{
  "name": "Create dashboard",
  "description": "Permission for create dashboards",
  "permissions": [
    "dashboards:read"
    "dashboards:create",
    "dashboards:edit"
  ],
  "read_only": false
}
2) Assign role to AD user
3) Logins to graylog with AD user
4) Create dashboards

## Current Behavior
AD user dont have buttom Create Dashboard

## Steps to Reproduce (for bugs)
1) login with AD user with role dashboard with perm. edit,crearte,read
2) no buttom Create Dashboard available
3) login with admin (other browser window), AD user dont have role Create Dashboard on page Authentication Management / Users (reseted?)
4) Assign role again to AD user
5) Rrefresh browser page (AD user). Buttom exist, but if logout/login - no buttom Create Dashboard

## Your Environment

* Graylog Version: 2.4.6-1
* Elasticsearch Version:  ES 5.x
* MongoDB Version: 3.2.x
* Operating System: Debian 9
* Browser version:

**Comment by deeshe** [comment]
I'm closing this issue, as it is duplicating #4299 . Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
