### ISSUE TITLE
GELF/HTTP timeout with http keep-alive

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#5720]
## Current Behavior

Create a HTTP GELF Input and use the following curl to post a message:

```
curl -v -i -XPOST http://graylog.lan:12202/gelf -d '{"_testing_number": 12524, "_testing_string": "string", "host": "graylog.lan", "version": "1.1", "message": "perfmon dump", "short_message": "first"}' http://graylog.lan:12202/gelf
```

The second request will run into a timeout because the server does not respond.

## Context

With 3.0.beta.2 that worked, but beta.3 breaks this, what makes it related to:

REFS: https://github.com/Graylog2/graylog2-server/issues/5143
REFS: https://github.com/Graylog2/graylog2-server/issues/5503

> In beta2 and before, after Graylog responds with a 202 it closes the socket.  This forces the client to start a new TCP socket and all is good.
> In beta3+, the socket remains open.  The client tries to re-use the socket, but Graylog doesn't respond to the request.  This eventually forces either the client to fail (or app case) or in the case of CURL to re-try after a timeout.

[ FD#2392 ]
## Your Environment
* Graylog Version: 3.0

**Comment by mpfz0r** [comment]
It seems that http keep-alive was always broken.
The fix from #5503 only exposed that. Before it would always close the connection after the error,
thus not doing keep-alive at all :-)
