### ISSUE TITLE
Access message data from a java program

### ISSUE THREAD

**Issue by Imacutekayx** [Graylog2/graylog2-server#5722]
Hello,

I'm currently working on a way to get data from messages sent to Graylog and use them on a java program.
I can't find any documentation or answer to even know if this is possible.

Does anybody have an idea?

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
