### ISSUE TITLE
Graylog3 Alerts Sending Wrong Event in Message Backlog

### ISSUE THREAD

**Issue by orlando-jamie** [Graylog2/graylog2-server#5723]
We had an alert stream configured in graylog 2.5 looking for a field with a max value over a threshold. The grace period was set to 0 and message backlog set to 1. When this alert used to trigger, the offending log entry was emailed in the alert through the backlog variable in the alerts template. However, with the upgrade to graylog 3, the alert condition is still correctly triggered, however, we now get random events in the message backlog, not the triggering event. 

 
## Expected Behavior

There is a stream of similar log events. When a specific log with a configured field=value is seen, this is the event that should be emailed as part of the message backlog.

## Current Behavior

There is a stream of similar log events. When a specific log with a configured field=value is seen, a seemingly random log from the stream is sent in the alert email, not necessarily the triggering event. 

## Steps to Reproduce (for bugs)

1. Create a stream.
2. Create a Max Value Field Aggregation Alert looking for a field with a higher threshold than x. Grace period 0, message backlog 1.
3. Configure email alert to send the backlog message in the email.
4. Send a log triggering the alert. The triggering event is not necessarily the one in the email.

## Context

Incident response workflows depending on the contents of the alert do not have all of the necessary data available. 

## Your Environment

* Graylog Version:
graylog-server-3.0.0-12.noarch
* Elasticsearch Version:
elasticsearch-6.6.0-1.noarch
* MongoDB Version:
mongodb-org-server-2.6.12-1.x86_64
* Operating System:
CentOS Linux release 7.6.1810 (Core)
* Browser version:
Chrome

**Comment by deeshe** [comment]
I'm closing this issue, as it is duplicating #5401 . Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
