### ISSUE TITLE
Unexpected token: keyword (const)

### ISSUE THREAD

**Issue by jichen0322** [Graylog2/graylog2-server#5724]
Unexpected token: keyword (const)

When I compiled the code with maven, something message shown like  this:

[INFO]     ERROR in builtins.51e8eb8f6791006d02da.js from UglifyJs
[INFO]     Unexpected token: keyword (const) [./node_modules/graylog-web-plugin/lib/PluginManifest.js:1,0][builtins.51e8eb8f6791006d02da.js:10531,0]

Please forgive my poor english and help me!

## Your Environment

* Graylog Version:3.0.0
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
@jichen0322 Please explain how you checked out the code and what command you used to build the server. Also include the full output. Thank you!
