### ISSUE TITLE
Aid users with delete-by-query for time ranges

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#573]
Sometimes users want to run the delete by query manually to get rid of older messages.
As long as time-based retention hasn't shipped, we can aid them in generating the queries for them, based on the dates (delete index for those that match completely, delete by query for the others).

Note that doing a graylog2_* query leads to a clusterblocked exception, probably because of the deflector index being locked twice. This might be a ES bug, but we need to work around it somehow.

**Comment by bernd** [comment]
Graylog 1.0.0 ships with a time based retention strategy. Closing this.
