### ISSUE TITLE
ActiveDirectory user loses its admin role after relogin.

### ISSUE THREAD

**Issue by happyyangyuan** [Graylog2/graylog2-server#5732]
Is LDAP/Active Directory user losing roles except for 'Reader' role?

## Expected Behavior

If the administrator assigns the admin role to an active directory user the active directory user should own the admin permissions all the time until the admin role is removed from it by the graylog administrator.

## Current Behavior

omitted

## Possible Solution

Is the LDAP/AD role assignment code overwriting roles for the user no matter what roles is assigned to it already.

## Steps to Reproduce (for bugs)

1. Login the administrator.
2. Login an active directory user.
2. Assign admin role to an active directory user using the administrator.
3. Refresh the active directory user web interface, we can see its admin permissions are there.
4. Logout the active directory user and login again. The admin's permissions assigned all gone.
5. Query the roles of the active directory user in the graylog administrator's web interface, the roles list for is ad user is 'Reader' only.

## Context

Omitted

## Your Environment

All graylog components are running in Kubernetes cluster v1.11.3
* Graylog Version: 3.0
* Elasticsearch Version: 6.6.0
* MongoDB Version: 4.0.3
* Operating System: docker official image version, host machine os version is ubuntu 16.0.4
* Browser version: chrome and safari modern browsers both tested

**Comment by jalogisch** [comment]
I'm closing this issue, as it is duplicating #4299. Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
