### ISSUE TITLE
Add missing contentpack autoloader

### ISSUE THREAD

**Issue by BeAddicted** [Graylog2/graylog2-server#5744]
I encountered a problem when upgrading from Graylog 2.4 to Graylog 3.0. I'm mounting a contentpack into the contentpacks folder. In Graylog 2.4 the data/contentpacks folder already existed inside the docker image with the user graylog as owner and everything worked fine. 
Now in Graylog 3.0 it does not exist, which results in docker creating it while mounting. Now docker creates the directory with root as owner of the folder and only root has write permissions for that folder. Then in the entrypoint script it tries to make graylog the owner with chown which results in an error because graylog does not have permissions to do so.
Can you include the data/contentpacks folder again into the dockerimage so that this works as before?

**Comment by zaf187** [comment]
what release is this likely to be in?
