### ISSUE TITLE
Search do not include escaped characters

### ISSUE THREAD

**Issue by tleveque23** [Graylog2/graylog2-server#576]
In my search string I used 
    message:"Handling\:"
I used the '\' to escape the ':' character.
But Graylog seams to ignore that.
It return me everything that include the "Handling" string. With or without the ':' after.
I think this is a bug.

We are using:
Server and graylog2-web-interface v0.20.2

**Comment by bernd** [comment]
Closing this as we cannot do anything about it right now. Sorry.
