### ISSUE TITLE
netty tcnative runs code from /tmp directory

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#5762]
At runtime, Netty copies its tcnative shared library to `io.netty.native.workdir` which defaults
to `/tmp`.

First of all it's a bad security practice to run code from `/tmp` which other
users can potentially write to, but secondly some users mount their `/tmp` partition 
with `noexec` and this even breaks netty:

```
2019-03-11T16:59:24.962-04:00 INFO [NativeLibraryLoader] /tmp/libnetty_tcnative4839963212991134594.so exists but cannot be executed even when execute permissions set; check volume for “noexec” flag; use -Dio.netty.native.workdir=[path] to set native working directory separately.
```

I think we should find a better default for `io.netty.native.workdir` than `/tmp`.
Maybe the lib directory we use for libsigar.

**Comment by bernd** [comment]
This needs to be a directory where the graylog server process can write. Ideally we use a subdir in `data_dir`. (e.g. `/var/lib/graylog-server/<something>` when running with the OS packages)

**Comment by mpfz0r** [comment]
On Debian systems this triggers `needrestart` which happens after every `apt-get upgrade` run, asking for graylog to be restarted.
cf: https://github.com/liske/needrestart/issues/142
