### ISSUE TITLE
Request to update jackson-databind library to the latest 2.9.x

### ISSUE THREAD

**Issue by deepakmohanakrishnan1984** [Graylog2/graylog2-server#5775]
Request to update jackson-databind library to the latest 2.9.x

## Expected Behavior
I am trying to build a plugin which requires 2.9.x version of jackson-databind. The plugin tests works independently. But when I install it into graylog 3.x, it fails with the follwing error message:

```
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.9.6 requires Jackson Databind version >= 2.9.0 and < 2.10.0
graylog_1        | 	at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:61)
graylog_1        | 	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:18)
```
## Possible Solution
Upgrade jackson-databind to 2.9.x

## Context
The plugin I am building depends on jackson-databind 2.9.x version transitively. But graylog still uses the older version of it: `2.8.11.3`. This version mismatch causing a runtime error when the plugin is being loaded.

## Your Environment
* Graylog Version: 3.0.0
* Elasticsearch Version: 6.5.1 
* MongoDB Version: 3.x
* Operating System: Centos
* Browser version: Chrome/Safari

**Comment by kroepke** [comment]
I vaguely remember that there were issues with the update, but I can't recall the details anymore.
At the moment I can't promise a target date for updating this dependency.

Can you maybe shade your dependency in the plugin to allow making progress?

**Comment by deepakmohanakrishnan1984** [comment]
I tried using the 2.9.x in the plugin. But when installed into Graylog, somehow the class loaders choosing the class from older libraries. I think there are some setting to choose a dedicated class loader for plugin. Should I try go in that direction?

**Comment by bernd** [comment]
We updated to Jackson 2.9.10 in the meantime.
