### ISSUE TITLE
About Message Count Alert Condition

### ISSUE THREAD

**Issue by naokitakei** [Graylog2/graylog2-server#5776]
## My Question
I want to detect if the word "ERR-400" occurs 5 times in the "message" field.
I think that it is possible to use "Message Count Alert Condition". However, it is not detected correctly. Please tell me about the detection method.
I set the following in anticipation.

![image](https://user-images.githubusercontent.com/48579565/54412350-a777dd00-4735-11e9-8e7c-e512324bbf2c.png)

## My Environment

* Graylog Version:3.0
* Elasticsearch Version:6.6.2
* MongoDB Version:4.0
* Operating System:Ubuntu 18.04.2 LTS

**Comment by bernd** [comment]
The old alerting system has been replaced with events and alerts in 3.2. Please open a new issue if you still have this issue with the new system. Thank you!
