### ISSUE TITLE
Changing DNS lookup adapter configuration completely halts message processing

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5782]
When changing configuration of a DNS lookup adapter, the adapter seems to stop but never restart and leave the system halted (no more messages are being processed) until a service restart.

I can reproduce this behavior and tried it with a change to the timeout value as well as the DNS server address.

## Your Environment

* Graylog Version: Graylog 3.0.0+db6cf59

**Comment by mpfz0r** [comment]
I could not reproduce this.
However, I found another bug: #6295

**Comment by bernd** [comment]
@lennartkoopmann @mpfz0r I was able to reproduce this and I am working on a fix.
