### ISSUE TITLE
grok_pattern_exists function

### ISSUE THREAD

**Issue by philomory** [Graylog2/graylog2-server#5788]
I'd like a function in processing pipelines to check if a specified GROK pattern exists. I'd like to use it in in a rule like this:

```
rule "example"
when
  has_field("log_format") && grok_pattern_exists($message.log_format)
then
  let pattern = concat(concat("%{",$message.log_format),"}");
  let map = grok(pattern: pattern, value: $message.message, only_named_captures: true);
  set_fields(map);
end
```

## Expected Behavior
A boolean function, returns true if a grok pattern of the given name exists, false otherwise; for the purposes of this function it should not be necessary to manually wrap the pattern in `%{...}`, though obviously to _use_ the pattern in a subsequent call to `grok` you would need to do that.

## Current Behavior
No such function exists; if you attempt to use a grok pattern that does not exist, it's an error.

## Context
I try to get our developers to ship messages as GELF whenever possible, but for some legacy applications, updating the application code to change how logging is done is just not in the cards. So, we're shipping logs from those applications with Filebeat. Likewise I'd love to have Filebeat just parse the logs itself, but it's not really good at it; among other things, it can't dynamically set the timestamp, at all. Pipelines definitely seem to be the way to go if I don't want to spin up a Logstash instance in front of Graylog (I'd really rather not).

I came across this thread suggesting the addition of the `grok_pattern_exists` function: https://community.graylog.org/t/dynamic-grok-pattern-selection/8716/5

## Your Environment
* Graylog Version: 2.5 (hoping to upgrade to 3.0 soon)
* Elasticsearch Version: 6.5.2
* MongoDB Version: 2.6.12
* Operating System: CentOS 7
* Browser version: N/A

**Comment by jalogisch** [comment]
we already have PR for that function.

https://github.com/Graylog2/graylog2-server/pull/5699
