### ISSUE TITLE
Numeric Searches Return Invalid Data for '100'

### ISSUE THREAD

**Issue by urban-moniker** [Graylog2/graylog2-server#5797]
I have a numeric field (call it "number") that can have values of 1 to 100.  When I perform searches against this field it doesn't seem to handle anything with a value of 100 properly i.e.

Search: number:<50
Returns: anything less than 50, but also 100

Search: number:>50
Returns: anything more than 50, but excluding 100

Quick and dirty workaround has been to adjust the searches like so:

Search: number:<50 AND NOT number:100
Returns: anything less than 50

Search: number:>50 OR number:100
Returns: anything more than 50 including 100

* Graylog Version: 3.0.0
* Elasticsearch Version: 6.6.2

Not sure if this is a Graylog issue or an Elastic issue, or I'm doing something stupid, but the field is def stored as LONG as I can perform comparisons against it.

Thanks

**Comment by urban-moniker** [comment]
As a FYI here is an example of filtering a search for anything less than 90, but getting results for 100:

![number_issue](https://user-images.githubusercontent.com/23149626/54920438-2b328600-4efb-11e9-9dc1-3afe1911ee3d.png)

**Comment by kmerz** [comment]
Hey @urban-moniker,

I can't reproduce your bug as it seems. I will explain what I did as clear as possible. Perhaps you find a problem with my approach to reproduce your problem:

1. created a TCP Raw Text Input.
1. send a text message in (`my input 23`)
1. created a grok extractor (`my input %{NUMBER:input_num:long}`)
1. send various messages with different numbers ranging from 1 to 100 (`my input 50`...)
1. searched for `input_num:<50` and `input:>50`

I add screenshots with the results of my search.
![Graylog - Search (2)](https://user-images.githubusercontent.com/448763/58877206-7a055480-86d0-11e9-91db-e95960313931.png)
![Graylog - Search (1)](https://user-images.githubusercontent.com/448763/58877207-7a055480-86d0-11e9-9b47-9faea11de78b.png)
