### ISSUE TITLE
Content Packs: Stream is included twice after creating a new revision

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#5802]
When creating a new revision of a content pack that already includes a stream, the stream is added a second time if you don't manually remove it from the list of included content.

## Your Environment

* Graylog Version:  3.0.0+db6cf59

**Comment by kmerz** [comment]
Hi @lennartkoopmann,

so I can't reproduce your problem. here is what I did:

1. created a content pack only containing a stream
1. created a new version but here only the stream of the content pack was selected

Then I did another approach:

1. created a content pack selecting a pipeline rule of a stream
1. checked that the stream now got included via dependency resolution
1. created a new version

But here as well only the stream was there which needed no unselecting!

Can you help me reproduce the problem?
