### ISSUE TITLE
[UI] Window closes if mouseup event happens outside the window

### ISSUE THREAD

**Issue by gimmic** [Graylog2/graylog2-server#5803]
When creating a new stream or any element which is created inside a 'floating' UI dialog box, if you select text in a text field or for any reason begin a mouse click and end the mouse click outside the floating window, that window closes without notification. (Changing focus to the background page).
This is especially annoying if you're doing a lot of copy/paste or otherwise selecting values from existing fields and accidentally 'drag' the mouse outside the target floating window during selection. The window closes and all data input is lost. 

## Expected Behavior
Expected behavior: The mouseup event should not close the UI dialog, at least not without a confirmation. 

## Current Behavior
The 'floating' window closes without prompt, losing any unsaved data/configuration.

## Possible Solution
Do not close floating window dialogs by clicking outside the focused dialog window. Force users to 'close' out of the floating UI element if any data has been entered/changed.

## Steps to Reproduce (for bugs)
1. Open 'Create Stream' dialog
2. Put text in any text field in the dialog
3. Select the text, and while dragging mouse leave the dialog region (release click outside the form)
4. The form closes, losing any unsubmitted data/configuration

## Context
See description. 

## Your Environment
Chrome in Linux(Ubuntu), Graylog 3.0

* Graylog Version: Graylog 3.0.0+db6cf59 on [hostname] (Oracle Corporation 1.8.0_191 on Linux 4.4.0-142-generic)
* Elasticsearch Version: Not Applicable
* MongoDB Version: Not Applicable
* Operating System: Not Applicable
* Browser version: Chrome Version 73.0.3683.75 (Official Build) (64-bit) [current]

**Comment by lennartkoopmann** [comment]
@kyleknighted

**Comment by gimmic** [comment]
To provide a little context, an example gif. I hope you can tell what is going on here: https://imgur.com/a/7LsuUHH

This is entirely a user driven error, but I feel like closing any dialog without prompt(especially a configuration-heavy floating window) is not a good workflow. If the fields have been changed or otherwise edited there should be a confirmation dialog in closing the window on an unfocus mouse click event OR do not allow the window to be closed by an unfocus type action. Only allow "cancel" or "X" closing of the floating window if it is in any way changed or not blank.

**Comment by kyleknighted** [comment]
Thank you for the feedback @gimmic! We'll be investigating a resolution to this.

**Comment by Mexonizator** [comment]
Hello! Totally agree with the topicstarter. It's incredibly annoying. Is it known, when the issue is going to be resolved? Thanks!

**Comment by kyleknighted** [comment]
@Mexonizator Thanks for the interest! It was merged into master in PR #5823 and will be released with version 3.1 in Q3. If you want to build off of master, it's available, otherwise it will be in an official release asap 😊

**Comment by Mexonizator** [comment]
@kyleknighted, That's nice to hear!
