### ISSUE TITLE
graylog2 rotation strategy

### ISSUE THREAD

**Issue by xulongju** [Graylog2/graylog2-server#5806]
Hi All：
Currently using the graylog version: graylog-server 2.5
### problem:
Currently, the count rotation policy is used. When the service log is not properly input into the graylog service, the log can only view the current day. It cannot view yesterday or earlier information, and it is not convenient to handle business problems.

### I would like to ask: 
Does graylog2 support multiple rotation strategies at the same time? For example, time and count are configured simultaneously.

**Comment by jalogisch** [comment]
He @xulongju 

as you do not have the option in the UI, this kind of configuration you request is not possible.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
