### ISSUE TITLE
Extended search aggregate table limit

### ISSUE THREAD

**Issue by chris-y** [Graylog2/graylog2-server#5808]
The aggregate data table in the Extended Search area appears to be limited to 15 items with no option to increase this.

## Expected Behavior
All items should be displayed, or an option to edit the limit should be available.

## Current Behavior
Only the first 15 items are displayed in the table.

## Possible Solution
Add an option to remove or change the limit.

## Steps to Reproduce (for bugs)
1. Go to the basic search page and increase the search paramters to include enough data so you have a field which will have more than fifteen unique entries
2. Click on the field (I used 'source') and select "statistics"
3. Make a note of the value under 'cardinality'
4. Go to Enterprise/Extended Search
5. Perform the same search as before
6. Click on the same field and aggregate
7. Count the number of rows in the table - this should be the same as the cardinality value noted earlier, but instead is only fifteen.

## Context
Attempting to get an alphabetically sorted list of hostnames and IPs from DHCP logs

## Your Environment
* Graylog Version: 3.0.0
* Elasticsearch Version: 6.6.2
* MongoDB Version: 3.6.3
* Operating System: Ubuntu 18.04.2 LTS
* Browser version: Firefox 66.0

**Comment by kmerz** [comment]
@chris-y: When you edit the aggregation, you can select the amount of rows to display, by clicking on selected item in Row. There should be a small modal:

![Graylog](https://user-images.githubusercontent.com/448763/55007794-4e833100-4fe0-11e9-8568-a6a7a1271988.png)

Is that what you mean?

**Comment by chris-y** [comment]
Ah, yes, that's what I was looking for, thanks.  I didn't expect it to need to be set individually for each field but given how it works, that makes sense.

Maybe needs to be made a bit clearer that this is possible.  I clicked on the table heading thinking that might give me an option but it didn't (but I also thought it might let me sort it from there, and it doesn't do that either).  Perhaps just a case that I need to RTFM :)

**Comment by kmerz** [comment]
Glad it helped! Thanks for your input. The extended search is still under development and we are thankful for every input!

**Comment by deeshe** [comment]
@kmerz Can this issues be closed?

**Comment by dennisoelkers** [comment]
@deeshe: We are still considering it to be an issue and want to look for other ways to configure the pivot limit, which are more intuitive for the user.

**Comment by kmerz** [comment]
This issue is fixed with the new aggregation builder.
