### ISSUE TITLE
Field list in extended search shows fields of all streams in index set

### ISSUE THREAD

**Issue by chris-y** [Graylog2/graylog2-server#5809]
Toggling the list fields options in Extended Search makes no difference to the list of fields, and neither does modifying the list of streams.

## Expected Behavior
The list fields toggle defaults to "current stream", so adding a stream to the search should reduce the fields displayed in the list.

## Current Behavior
Clicking between current streams / all / all including reserved makes no difference to the list of fields displayed, and neither does adding a stream to the selection of streams to search.

## Steps to Reproduce (for bugs)
1. Visit Enterprise / Extended Search.
2. Look at the list of fields displayed.  Find a field you know isn't in a particular stream.
3. Add the stream which does not contain that field to the list of streams to search.
4. Check the list of fields and locate the field which should no longer be present.

## Context
Just annoying showing lots of fields, some the same with different cases, when I'm trying to find something.

## Your Environment
* Graylog Version: 3.0.0
* Elasticsearch Version: 6.6.2
* MongoDB Version: 3.6.3
* Operating System: Ubuntu 18.04.2 LTS
* Browser version: Firefox 66.0

**Comment by dennisoelkers** [comment]
I cannot reproduce this behavior. Is it possible that you are routing all of your streams to the same index set?

**Comment by chris-y** [comment]
Most of my streams are in the same index set.  If I select one which isn't I get the expected fields, so I know how it works now, but it still isn't how I'd expect it to.
