### ISSUE TITLE
GELF UDP input not starting (says 'Address already in use', but isn't)

### ISSUE THREAD

**Issue by exic** [Graylog2/graylog2-server#5825]
I just updated to graylog 3.0.1 from 2.5 and can't get my GELF UDP Input running. It says `input with ID <5ca322f447d5dd34504825ba> misfired. Reason: bind(..) failed: Address already in use.`, no matter what port I use. Also doesn't matter if I use bind address 0.0.0.0, 127.0.0.1 or my node's public IP.

Interestingly, I get the same messages when using a port different from 12201, but the port is being opened according to netstat. The extra line I get on port 12201 is this one: `ERROR [NettyTransport] Error in Input [GELF UDP/5ca342a647d5dd48b75dc567] (channel [id: 0xa64ae8ab, L:/0:0:0:0:0:0:0:0%0:12201]) (cause java.lang.NullPointerException)`

Trying to send something to the open port (`docker run --log-driver=gelf --log-opt gelf-address=udp://10.23.22.108:12202 busybox echo Hello Graylog`), I get the same NPE log line (but different 'id: ...') and the port is closed.

## Expected Behavior
Port should open and receive messages.

## Current Behavior
Can't receive messages. I get this log: https://termbin.com/wpws

## Possible Solution
Works on 2.5 …

## Steps to Reproduce (for bugs)

1. Update to 3.0.1
2. Add GELF UDP input on port 12201.

## Context
Rolled back now, 2.5 still works with UDP.

## Your Environment

* Graylog Version: 3.0.1-2
* Elasticsearch Version: 6.7.0
* MongoDB Version: 1:2.0.6-1.1+deb7u1
* Operating System: 3.2.0-6-amd64 #1 SMP Debian 3.2.102-1 x86_64 GNU/Linux (Debian 7.11 wheezy)
* Browser version: no browser involved

**Comment by florianvolle** [comment]
The UDP input needs the `SO_REUSEPORT` capability. Please make sure that your Docker container is configured correctly.

**Comment by exic** [comment]
I'm not running Graylog on Docker but on an old VM.

It looks like kernel 3.2 (which is shipped with Debian Wheezy) on the VM is too old. I read that SO_REUSEPORT was introduced in 3.9. I guess I'll have to update the whole system then, first.

Thanks anyway!

**Comment by bernd** [comment]
@exic Thank you for the update! We will update our documentation accordingly.
