### ISSUE TITLE
Stream titles not updating when cloned

### ISSUE THREAD

**Issue by omatron** [Graylog2/graylog2-server#5826]
## Expected Behavior

When you create a new Stream, the stream title ${stream.title} is set up. Then you clone a Stream, and change the Stream title it also updates the ${stream.title} variable.

## Current Behavior

When you create a new Stream, the stream title ${stream.title} is set up. Then you clone a Stream, and change the Stream title it does not update the ${stream.title} variable, then the output alert for example output to Slack, sends the wrong ${stream.title} and you customize it, so the alerts sent are coping the stream used to clone. 

## Possible Solution

When you rename a Stream it should update the variable ${stream.title}.

## Steps to Reproduce (for bugs)

1. Create a Stream like [Test] Stream, set up everything including output.
2. Clone the Stream change the stream name to [Test] Stream2.
3. Trigger the [Test] Stream2, the output will still be: New message in Graylog stream [Test] Stream

## Context

Send streams output alerts to Slack.

## Your Environment

* Graylog Version: 2.4.6
* Elasticsearch Version: 
* MongoDB Version:
* Operating System: 
* Browser version:

**Comment by florianvolle** [comment]
This could be a problem with the slack output. We need to verify this.

**Comment by kmerz** [comment]
- Created a stream named `[Test] Stream 1` with an Alert and a http Notifcation
- Send a notification to the http server and received `title: [Test] Stream 1`
- Cloned the stream and named the clone `[Test] Stream 2`
- Send a notification to the http server and received `title: [Test] Stream 2`

looks like a problem with the Slack alert!

**Comment by kmerz** [comment]
Tested it with graylog Version 3.1-pre-alpha (b050a5421840f9923c37981e99070e443232ae7a) and current slack-plugin version Works for me.

Can you provide any additional information?
