### ISSUE TITLE
Deflector exists as an index and is not an alias

### ISSUE THREAD

**Issue by mahnunchik** [Graylog2/graylog2-server#5845]
I could not fix the error:

```
Deflector exists as an index and is not an alias. (triggered 7 minutes ago)
The deflector is meant to be an alias but exists as an index. Multiple failures of infrastructure can lead to this. Your messages are still indexed but searches and all maintenance tasks will fail or produce incorrect results. It is strongly recommend that you act as soon as possible.
```

## Expected Behavior

Works after removal graylog and elastic data.

## Current Behavior
The same error.

## Steps to Reproduce (for bugs)
After error https://github.com/Graylog2/graylog2-server/issues/5843

## Your Environment

* Graylog Version: 3.0.1 `https://hub.docker.com/r/graylog2/graylog/tags`
* Elasticsearch Version: `docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.2`
* MongoDB Version: `mongo:3.6`
* Operating System: Ubuntu 18.04

**Comment by jalogisch** [comment]
Please see the Documentation: http://docs.graylog.org/en/3.0/pages/faq.html#how-do-i-fix-the-deflector-exists-as-an-index-and-is-not-an-alias-error-message

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by ik9999** [comment]
I had the same issue. Downgrading graylog/elasticsearch helped. This version works for me:

graylog/graylog:3.0.0-1

docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4

**Comment by mulgurul** [comment]
I tried to use the sparesome guide on how to fix this and ended up with graylog not being able to show index overview page, failing with:

![image](https://user-images.githubusercontent.com/5803230/66208175-c5e2fd00-e6b4-11e9-9390-04bc45692851.png)

Graylog 3.1.0+aa5175e on 904e9c006583 (Oracle Corporation 1.8.0_222 on Linux 4.4.0-165-generic)
