### ISSUE TITLE
is missing mandatory "host" field

### ISSUE THREAD

**Issue by sercanacar** [Graylog2/graylog2-server#5846]
## Expected Behavior

Sending logs from kubernetes cluster using fluent-bit

```
  fluent-bit-output.conf: |-
    [OUTPUT]
        Name          gelf
        Match         *
        Host          graylog-udp.logs.svc.cluster.local
        Port          12201
        Mode          udp
        Gelf_Short_Message_Key short_message

```

## Current Behavior

I can see logs via graylog UI, however graylog pod logs showing

```
logs/**graylog-1**[graylog-server]: 2019-04-05 09:05:27,010 WARN    [GelfCodec] - GELF message <f4269e00-5781-11e9-8c0a-821cd288d0e0> (received from <100.117.64.209:32874>) is missing mandatory "host" field. - {}
```
## Possible Solution

I have two pods graylog-0 & graylog-1 (highlighted above) and the messages are from graylog-1. Not sure if I mis-configured something

## Your Environment

Kubernetes via KOPS

* Graylog Version: helm graylog 2.5.1-3
* Elasticsearch Version:6.7.0
* MongoDB Version:3.6
* Operating System: kubernetes
* Browser version:

**Comment by florianvolle** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
