### ISSUE TITLE
[UI] Add quick 'NOT' filter button to field selector

### ISSUE THREAD

**Issue by iankoetter** [Graylog2/graylog2-server#5848]
Provide a "-" key next to the "+" field search appender button to automatically add "NOT field". Kibana has this feature and is used often to quickly filter out matches (whittle down rather than expanding search scope)

## Expected Behavior
A button to press to exclude a field message from the search pattern.

## Current Behavior
You hit the + to add the search term to the query then manually prepend NOT and hit search.

## Possible Solution
Add a filter button next to the + for -.

## Context
In our use cases for filtering through mass amounts of data, it's more common for a human to start with a wide net and reduce the search scope as things can be eliminated from the general query. 

* Graylog Version: 3.0

**Comment by gimmic** [comment]
https://github.com/billmurrin/graylog-plugin-quickvaluesplus-widget
![image](https://user-images.githubusercontent.com/568957/55832937-3fba7500-5adc-11e9-8020-a4899188121d.png)

**Comment by dennisoelkers** [comment]
Both of these ideas have been implemented already.
