### ISSUE TITLE
Graylog 3.0.1: After create USER using ReST API, Login GUI does not work

### ISSUE THREAD

**Issue by gianluca-valentini** [Graylog2/graylog2-server#5854]
Installed Graylog 3.0.1 OVA.
I create a new user using Java and ReST API (POST)

> /api/users 
It works fine on Graylog 2.4.6

## Expected Behavior
After create user I can access to Graylog web application using admin or new user account
## Current Behavior
I cannot access neither with admin nor with the new account. **I need to restart the application** and then it works fine

## Your Environment
VM linux using OVA

* Graylog Version: 3.0.1. OVA
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
@gianluca-valentini: Thanks for opening the issue. Can you please add the request(s) you did to create the user and the response for them?
