### ISSUE TITLE
Alert Notifications - Asynchronous Execution

### ISSUE THREAD

**Issue by deeshe** [Graylog2/graylog2-server#5871]
The old alerting system was executing alarm callbacks in a blocking way while running condition checks. That way of executing notifications has many drawbacks like blocking the alert condition execution. There also wasn't a concept of notification retries and proper error handling and reporting.

In the new system notification should run asynchronous. That means the component that creates events that have an assigned alert notification doesn't directly execute the notification but triggers a job in the scheduler to execute the notification.

Running notification jobs in the task scheduler also gives us features like retries, error handling and reporting as well as a history for free.

**Comment by bernd** [comment]
Done.
