### ISSUE TITLE
Multiple index rotation strategies on Graylog

### ISSUE THREAD

**Issue by mehrenreich** [Graylog2/graylog2-server#5892]
Some users have to comply regularities like GDPR or company requirements and are forced to keep or delete their indexes a defined minimum timeframe. 
However, this sometimes doesn't conform with their regular rotation strategy (eg. size or message count based).

It would be a great feature to define multiple strategies and let Graylog rotate the indexes based on whatever comes first.

For example:

```
Select rotation strategy: Index Size
Max size per index (in bytes): 1073741824
```
or
```
Select rotation strategy: Index Time
Rotation period (ISO8601 Duration): P1W
```

The index should get rotated whenever the size is 1GB **or** the age is 7 days.

**Comment by gimmic** [comment]
This would be nice and go a long way to solve some complexities around larger deployments which may have a lot of varied index sets. I've been struggling to come up with a good deployment or tuning strategy to balance shard distribution, retention, and index allocation when some index sets may incur large volumes in an hour while other sets might take days/weeks to fill up.

**Comment by mpfz0r** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/pull/14424
