### ISSUE TITLE
Pipeline rules already appended to stage should not appear in dropdown

### ISSUE THREAD

**Issue by gimmic** [Graylog2/graylog2-server#5896]
When adding a pipeline rule to a pipeline stage, the rules which are already attached to that stage should not appear in the drop down. It even lets you attempt to add the same rule to the pipeline stage multiple times.

## Expected Behavior
The active attached rules should not be listed among the rules to attach in the drop down. You should not be allowed to attach a rule multiple times to the same pipeline stage. 

## Current Behavior
![Alt Text](https://i.imgur.com/QA61Pgo.gif)

## Steps to Reproduce (for bugs)
1. Create pipeline rule
2. Append pipeline rule to pipeline stage
3. Save/Reload rule
4. Append same pipeline rule to same pipeline stage

* Graylog Version: 3.0.1

**Comment by edmundoa** [comment]
Fixed in #6743
