### ISSUE TITLE
Export raw messages to archive file

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#590]
Hi,

We are creating a plan to set-up Graylog2 for our huge production env. Because of the huge amount of logs, we would like to have 1 or 2 months in ES/Graylog and all the rest in archive files (plain). Is there any way to write the logs files to file aswell?

**Comment by bernd** [comment]
There is no option to do that with Graylog core at the moment. One possible solution would be to write an output plugin which writes the messages as JSON or plain text files to the file system.

Starting point on how to write plugins: http://docs.graylog.org/en/1.0/pages/plugins.html
