### ISSUE TITLE
Manage Static Lookup Tables via weberface, store in mongodb

### ISSUE THREAD

**Issue by iankoetter** [Graylog2/graylog2-server#5903]
As I have started working with lookup tables, I'm seeing some real limitations on management. The connectors are a bit messy to set up, and then management of things like CSV-based lookup tables falls back to node management at an OS file level. 

## Expected Behavior
Management of small-to-medium scale static lookup tables should be done from the weberface and content of the lookup tables could be stored in mongodb. 

## Current Behavior
Flat files must be placed on each graylog node and updated through out-of-band process.

## Possible Solution
Allow a simple form-based weberface or file upload in the UI to add a lookup table(Csv) to mongodb which could then be read from all cluster nodes.

## Context
Simple things like small-scale lookups for value translations could be more efficiently managed via the web UI.
Example lookup:
Field "conn_state" == "S0"
Lookup table provides: "S0", "Connection attempt seen, no reply"

* Graylog Version: 3.0.1

**Comment by aim4r** [comment]
Couldn't agree more, it would be great to have the possibility to upload basic CSVs via the UI.

**Comment by bernd** [comment]
Graylog Enterprise already has support for this: https://docs.graylog.org/en/4.0/pages/lookuptables.html#mongodb

Closing this issue.
