### ISSUE TITLE
LDAP connector does not verify TLS certificates

### ISSUE THREAD

**Issue by imrejonk** [Graylog2/graylog2-server#5906]
## Expected Behavior

Graylog should verify the LDAP server certificate chain up to a trusted root, and refuse the connection when the certificate chain cannot be verified.

## Current Behavior

Graylog accepts LDAP server certificates whose root certificate is not in any trust store. This presents a vulnerability for man-in-the-middle attacks.

## Steps to Reproduce (for bugs)

1. Navigate to the LDAP / Active Directory configuration page.
2. Enable LDAP, choose server type 'LDAP' and enter the address of a STARTTLS-enabled LDAP server, whose TLS certificate should not be verifiable by the server. Uncheck 'SSL' and 'Allow self-signed certificates'. Check 'StartTLS'.
3. Provide a bind DN and password in the 'System Username' and 'System Password' fields.
4. Click the 'Test Server Connection' button.

## Context

We run Graylog in a Docker container, using [the official Docker image](https://hub.docker.com/r/graylog/graylog). Our LDAP server is on a different network. We would be better protected against man-in-the-middle attacks if Graylog verifies the LDAP server certificate.

## Your Environment

* Graylog Version: 3.0.1
* Elasticsearch Version: 6.6.2
* MongoDB Version: 3.6.12
* Operating System: Debian 9 inside Graylog Docker container
* Browser version: Firefox 60.6.1esr

**Comment by SammyA** [comment]
Noticed same issue here:
Graylog Version: 3.3.2
Docker image: graylog/graylog:3.3

**Comment by imrejonk** [comment]
I just upgraded our Graylog installation to 3.3.3 and tried to reproduce this issue. Looks like Graylog now properly validates the LDAP TLS chain. Good to see that this was included in a patch release although it is a breaking change, security is important :)

@dennisoelkers Thanks for fixing this!

**Comment by dennisoelkers** [comment]
@imrejonk: Thanks for finding this issue in the first place and testing the fix! Much appreciated! :)
