### ISSUE TITLE
Errorpage "Cannot read property 'name' of null" in Authentication - Roles Creation

### ISSUE THREAD

**Issue by iT3han** [Graylog2/graylog2-server#5908]
## Expected Behavior
If you leave the "Create new role" page by clicking in the left menu on "Roles" again, you should not get the error.

## Current Behavior
If you leave the "Create new role" page by clicking in the left menu on "Roles" again, you get the "Something went wrong." page with the error message displayed below.

## Possible Solution
-

## Steps to Reproduce (for bugs)
1. Go to Authentication
2. Go to Roles
3. Click "Add new role"
4. Leave page by clicking on "Roles" again

![image](https://user-images.githubusercontent.com/43262157/56784375-6a9d0c80-67f0-11e9-9f54-7ac809f4f081.png)
![image](https://user-images.githubusercontent.com/43262157/56784422-a59f4000-67f0-11e9-97ab-782df502c971.png)

## Context
Not critical. If you leave the page by clicking on any other menu or submenu (i tried most of them) or by clicking the cancel button, everything works. 

## Your Environment

* Graylog Version: Graylog 3.0.1+de74b68 
* Elasticsearch Version: 6.7.1
* MongoDB Version: 3.6.3
* Operating System: Ubuntu 18.04.2 LTS
* Browser version: Chrome 73.0.3683.103 (64-Bit)

**Comment by edmundoa** [comment]
This will be fixed in Graylog 3.2.0.
