### ISSUE TITLE
Pipeline rule with geo lookup and possible empty array

### ISSUE THREAD

**Issue by oarnold** [Graylog2/graylog2-server#5911]
I am trying to setup a pipeline rule to get some additional geo information, as described in http://docs.graylog.org/en/3.0/pages/geolocation.html#.
The problem I am facing is that part of the result of the lookup can be empty.
In the below code for the rule setting the country code works fine, but the fields which depend on the subdivisions object can lead to the error

"For rule 'rule geoip lookup': In call to function 'set_field' at 7:2 an exception was thrown: Index: 0, Size: 0".

This happens because the subdivisions object is sometimes empty, for instance:

```
...
"country": {
  "confidence": null,
  "geoname_id": 1605651,
  "is_in_european_union": false,
  "iso_code": "TH",
  "names": {
    "de": "Thailand",
    "ru": "Тайланд",
    "pt-BR": "Tailândia",
    "ja": "タイ王国",
    "en": "Thailand",
    "fr": "Thaïlande",
    "zh-CN": "泰国",
    "es": "Tailandia"
  }
},
...
"subdivisions": []
```

Code for the rule:

```
rule "rule geoip subdivision lookup"
when
  has_field("IP")
then
  let geo = lookup("geoip-lookup", to_string($message.IP));

  set_field("IP_country_code", geo["country"].iso_code);
  set_field("IP_region_code", geo["subdivisions"].[0].iso_code);
  set_field("IP_region_name", geo["subdivisions"].[0].names.en);
end
```

Currently it seems not to be possible to only set the fiels IP_region_code and IP_region_name, when the array is not empty - or to use a default value, if the array is empty.

(Also posted in https://community.graylog.org/t/pipeline-rule-with-geo-lookup-and-possible-empty-array/10013)

**Comment by gianluca-valentini** [comment]
Hi, is there a solution about this issue?
Can somebody suggest hot to solve it or a workaround?

**Comment by justinjett** [comment]
I am also experiencing this same problem. 
This is found in the error log. 
Is there a way to reduce the logging from `WARN` to `DEBUG`?

```
WARN  [PipelineInterpreter] Error evaluating action for rule <cloudflare-geoip-subdivision-lookup/60ad0f945777ad5aa71eabd6> with message: REDACTED (Error: In call to function 'set_field' at 20:4 an exception was thrown: Index 0 out of bounds for length 0)
```

**Comment by adambirds** [comment]
Us there a fix for this, makes trying to fetch subdivision impossible without loads of errors, we should be able to set a default.

**Comment by adambirds** [comment]
@bernd @florianpopp is there any other update on when this may be fixed, seems like it shouldn't be too difficult to fix yet its been 3 years since this was reported. There should be way to set a default empty string if it doesn't return anything to avoid the error.

**Comment by gustavohellwig** [comment]
Any workaround for this? I'm also having the same issue.

**Comment by adambirds** [comment]
As per the linked PR, you can now set a default parameter to the set_field function.

**Comment by gustavohellwig** [comment]
Is this not the case: set_field("sourceip_geo_state_name", to_string(geo["subdivisions"].[0].names.en, "no_value"));
I'm still receive errors in the logs.

**Comment by adambirds** [comment]
It worked for me at the time but my graylog instance isn't active anymore so can't check! I'd raise a new issue if having errors and just link this issue. More likely to be picked up and looked at!

**Comment by gustavohellwig** [comment]
any updates on this? Still the problem exists.

**Comment by drewdin** [comment]
I am still having the same issue in version 6.2. All attempts below fail, with or without the to_string.

set_field("destination_ip_state_abbrev", to_string(geo["subdivisions"].[0].iso_code));
set_field("destination_ip_state_abbrev", to_string(geo["subdivisions"].["0"].iso_code));
set_field("destination_ip_state_abbrev", to_string(geo["subdivisions"].0.iso_code));
set_field("destination_ip_state_abbrev", to_string(geo["subdivisions"]["0"].iso_code));
