### ISSUE TITLE
Remove legacy alerting code

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#5919]
## Description

The legacy alerting code should be removed in favor of the new events system.

We need to make sure to keep everything we need to continue to support legacy alarm callbacks. (e.g. interfaces, implementations, etc.)

## Tasks

- [ ] Check which code we need to keep to support running legacy alarm callbacks
- [ ] Remove all other legacy alert code

## Open Questions

- [ ] tbd

**Comment by linuspahl** [comment]
I am closing this issue in favour of https://github.com/Graylog2/graylog2-server/issues/12988, the frontend art has been implemented with https://github.com/Graylog2/graylog2-server/pull/12987
