### ISSUE TITLE
Wrong Source name are showing

### ISSUE THREAD

**Issue by rguptarg** [Graylog2/graylog2-server#5922]
Hi Team,
I am new in Graylog, We have configured Graylog for Network Devices log, but for few devices I can't see proper message on Graylog. We are using "Syslog UDP" in Input.

We are using below device 
Cisco
HP
Lenovo
Palo Alto
Sonic wall
Fortinet
A10
Dell
Cyberroam

* Is there any way to check original/received message from Device ?

![graylog](https://user-images.githubusercontent.com/49057178/57063710-bf092600-6ce1-11e9-93f8-c80ccba36090.JPG)
 

* Graylog Version: Graylog 2.5.1+34194da 
* Elasticsearch Version:  "lucene_version" : "7.6.0", "minimum_wire_compatibility_version" : "5.6.0",   "minimum_index_compatibility_version" : "5.0.0"
* MongoDB Version: db version v4.0.6
* Operating System:  7.6 
* Browser version:

**Comment by gimmic** [comment]
This looks more like a parse error. You could set up a new input for raw UDP and keep the full message to see the message completely unfiltered/raw.

If you're using an input dedicated to that source type, you can also statically set it either in an extractor or via a static field mapping.

**Comment by rguptarg** [comment]
Thanks for reply.

Now We have configured RAW UDP as a Input and now datasource are coming correctly.

But As per my network team they have configured forwarding around 100 devices and I can see only 33 devices logs on graylog.

So Is there any option to check at backend(server end) / graylog end, we are receiving data or not ?

**Comment by j-n-s-k-n-r** [comment]
@rguptarg

You can use the built-in Rest API Browser.
You can found it under: hostname:9000/api/api-browser/

In the middle of the list you can found "Sources: Listing messages sources" 

The value for the Range should be 0.

Then you will get back a json Object with all host, that are sending logs. 


Cheers 
Jonas

**Comment by jalogisch** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
