### ISSUE TITLE
Specific Permissions for API Endpoints

### ISSUE THREAD

**Issue by joshuachang-coupa** [Graylog2/graylog2-server#5929]
Which permissions do I need for `/search/universal/relative` to access the Graylog stream outputs? 

## Context
I am wondering what the are the specific permissions related to the the relative search API endpoint. Thank you.

## Your Environment
For example, these are my current permissions. What are the specific `permissions` directives that I need for `search/universal/relative`? 
```
{
    "name" : "API Reader",
    "description" : "API Reader",
    "permissions" : [ "streams:read", "message:read", "messagecount:read", "collectors:read", "journal:read", "systemmessages:read", "inputs:read", "loggersmessages:read", "sidecar_collectors:read", "indexsets:read", "fieldnames:read", "buffers:read", "indexranges:read", "system:read", "stream_outputs:read", "sources:read", "indices:read", "outputs:read", "decorators:read", "loggers:read", "throughput:read", "messages:read" ],
    "read_only" : false
}
```
* Graylog Version: 3.0.1
* Elasticsearch Version: N/A
* MongoDB Version: N/A
* Operating System: MacOSX
* Browser version: N/A

**Comment by deeshe** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
