### ISSUE TITLE
Regex not evaluating \$ correctly

### ISSUE THREAD

**Issue by will-jac** [Graylog2/graylog2-server#5931]
I'm using a regex to search through the logs, but it doesn't look like any of the special characters (for instance, the group [\@\#\$\%\^\&\+\=]) ever result in matches.

For instance, searching "message:ExampleString" results in a match for the message "previous text, ... $ExampleString ... more of the message", but when I search "message:/\$ExampleString/", I get no results.

## Expected Behavior
The regex search
message:/\$ExampleString/
should match the portion of the message that is
$ExampleString

## Current Behavior
The regex search
message:/\$ExampleString/
does not match
$ExampleString
(Also, directly searching for message:\$ExampleString matches with things like ExampleString, without any $)

## Possible Solution
It is possible I am using the search interface wrong or my company has configured graylog in such a way to make this sort of search impossible, but I don't know

## Steps to Reproduce (for bugs)
Attempt to regex search for a string containing a $

## Your Environment

* Graylog Version: (I don't know how to find these. I know our graylog version is out of date)
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Windows 10
* Browser version: Firefox 66

**Comment by jalogisch** [comment]
how the search is working highly depends on the field type, the mapping and if the field is analyzed (means available for full text search).

You will find some more details in the Graylog Documentation about that: http://docs.graylog.org/en/3.0/pages/queries.html
