### ISSUE TITLE
Double hyphen showing up after output

### ISSUE THREAD

**Issue by jnance86** [Graylog2/graylog2-server#5932]
## Expected Behavior
I have an output the sends a raw formatted syslog to a different system. The external system is seeing a log file with double hyphens sent from Graylog. I would like that double hyphen removed. 

## Current Behavior
Graylog does not show the double hyphen. I can not see it within the UI. 

## Possible Solution
Just to be sure I created a pipeline and applied it to the output. The pipeline contains: 

rule "remove double dash"
when
  regex("\\x2D.\\x2D", to_string($message.message)).matches == true
then
  let new_message = to_string($message.message);
  let final_message = split(" \\- \\- ", new_message);
  let concat_message = concat(to_string(final_message[0]),to_string(final_message[1]));
  set_field("message", concat_message);
end

It does not show the double hyphens when I pull in one of the logs from the output stream. When I test the pipeline against a log it says Null, presumably because there's no double hyphen visible at that time. 

When I grab the incoming log from the target machine incoming packets I see the double hyphen (and so does the log reader app on that system). When I copy that log contents and post it into the pipeline simulator it properly removes the hyphen. 

Why is this double hyphen being added and how do I remove it?

## Your Environment

* Graylog Version: 2.4

**Comment by deeshe** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
