### ISSUE TITLE
"surrounding messages" in extended search

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#5934]
## Expected Behavior
Before the extended search replace the search, the feature surrounding messages need to be given. 

## Context
Using the surrounding messages should be given to make analyse of messages easier.

## Your Environment
* Graylog Version: 3

[ FD 2539 ]

**Comment by jalogisch** [comment]
https://github.com/Graylog2/graylog2-server/issues/6408

**Comment by dennisoelkers** [comment]
Closing in favor of #6408. Although this issue is older, the other one contains a comment now, that should not be lost.
