### ISSUE TITLE
Support Alerts and Conditions in content packs

### ISSUE THREAD

**Issue by madoke** [Graylog2/graylog2-server#5942]
Hi Team, 
Thank you for maintaining this project, which i've been using for some years now in multiple companies. This is more like a feature request, rather than an issue itself.

## Expected Behavior
When exporting streams via content pack, it would be nice that conditions and alerts were also exported.

## Current Behavior
Only the stream itself is exported for now. Conditions and Alerts have to be manually created each time

## Context
We have a graylog setup that serves multiple teams. Each team is responsible for creating their own streams, dashboards, alerts and conditions. In our particular case, after making changes to a dashboard/stream we export them into a content pack and keep the json under source control. This allows us to easily import/export our streams and dashboards to multiple graylog environments, while protecting the data from accidental deletion.

* Graylog Version: 3.0.1

**Comment by kmerz** [comment]
Hey @madoke,

Alert conditions are included in the content packs.

If you create a content pack with a stream which has a alert condition, the alert condition should be automatically part of the content pack.

Can you please test this and tell me if you run in any issues?

Thanks for your input!

**Comment by madoke** [comment]
@kmerz thanks for the clarification, i just tested this on a clean instalation of graylog 3.0.0 and it worked. I misinterpreted the content pack UI. Will close the issue, cheers !
