### ISSUE TITLE
"Getting started" guide not being loaded

### ISSUE THREAD

**Issue by slackware666** [Graylog2/graylog2-server#5943]
## Expected Behavior

After logging into Graylog for the 1st time, a "Getting started" guide was shown, including several links.

## Current Behavior

The guide is not shown, instead an error message

<img width="686" alt="Screenshot 2019-05-15 at 10 17 37" src="https://user-images.githubusercontent.com/516452/57759976-156f5f00-76fb-11e9-8337-b1d032dfb865.png">

The shown link leads to an ancient guide for the version 1.x.

<img width="926" alt="Screenshot 2019-05-15 at 10 17 57" src="https://user-images.githubusercontent.com/516452/57760085-4cde0b80-76fb-11e9-8c21-1fa33b936078.png">

* Graylog Version: 3.0.2

**Comment by jgallucci32** [comment]
Does your setup require use of a web proxy or have an SSL gateway using custom certificates to the internet? I saw that error on both occassions and was able to fix it. Outbound http proxy is in the documentation. To fix the SSL gateway issue you must supply a custom cacerts file for Java and then restart Graylog.

**Comment by slackware666** [comment]
JS was blocked by a content blocker🤦‍♂️
