### ISSUE TITLE
Alerts is not triggered some times

### ISSUE THREAD

**Issue by ortizleo** [Graylog2/graylog2-server#5944]
Hello.

Some times alerts is not triggered. We can find the message on stream but no alert is generated for this message. Why it happens? This problem occur in version 2.6 and now in version 3.0.1 too.

Is hard to reproduce the problem because it happens in random times.  Generally alerts works fine but graylog miss one or other alert some times. Also, no messages in Graylog server logs.

It is very bad because we cant trust in Graylog alert engine, that is an very important feature.

**Your Environment**
Graylog 3.0.1 
Oracle Corporation 1.8.0_212
SO Centos 7.5
MongoDB 3.6.12
Elasticsearch 6.4

**Comment by dennisoelkers** [comment]
Hey @ortizleo! Thanks for reporting this issue. Is it possible that the messages that should trigger alerts but do not are coming in to the Graylog server delayed/with wrong timestamps?

Graylog alerting is search-based, that means it is searching the last n seconds (depending on your configured interval, defaulting to 60 seconds) for messages matching the configured rules. If messages come in delayed (> alert interval) or with wrong timestamps, they are not found during the check run.

**Comment by ortizleo** [comment]
Hello.
My alert interval is configured for 40 seconds, message timestamp is right. I think that can be ES utilization, did you have some tip for it? Some tweaking?

**Comment by florianvolle** [comment]
Hi @ortizleo 
we are addressing this issue in the upcoming version 3.1.

**Comment by Safail** [comment]
So 3.3 is release but still have same problem.
