### ISSUE TITLE
Error when clearing Geo IP lookup adaptor field

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#5946]
The following error occurs when clearing the value for the Database type field on the Geo IP data adapter edit page. It looks like on-the-fly validation is happening, and it does not like a blank string for the field.

<details>
<summary>Error message</summary>
Could not validate lookup table data adapter ""
Lookup table data adapter validation failed: Can not deserialize value of type org.graylog.plugins.map.config.DatabaseType from String "": value not one of declared Enum instance names: [MAXMIND_CITY, MAXMIND_COUNTRY] at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@2c2104e1; line: 1, column: 147] (through reference chain: org.graylog2.rest.models.system.lookup.$AutoValue_DataAdapterApi$Builder["config"]->org.graylog.plugins.map.geoip.$AutoValue_MaxmindDataAdapter_Config$Builder["database_type"])
</details>

## Steps to Reproduce

![May-15-2019 16-18-19](https://user-images.githubusercontent.com/3423655/57810338-20db7e00-772d-11e9-9060-81b26a09313f.gif)

* Graylog Version: 3.1 SNAPSHOT

**Comment by ousmaneo** [comment]
Hi @danotorrey ,
It does not seem to be possible to reproduce this on the master branch.
I'm on version v3.2.0-SNAPSHOT.
Can you please provide with detailed steps?

**Comment by danotorrey** [comment]
Thanks for checking @ousmaneo! I will check if I can cause this again.
