### ISSUE TITLE
Remove field value quoting in alert condition with leading wildcards

### ISSUE THREAD

**Issue by mahnunchik** [Graylog2/graylog2-server#5949]
Alert condition with leading wildcards doesn't work as expected.

## Expected Behavior

Alert type:  Content Alert Condition
Field: `message`
Value: `*error`
Global setting: `GRAYLOG_ALLOW_LEADING_WILDCARD_SEARCHES: "true"`

Match message: `KeyError: ('coordinates', 'occurred at index 1101')`

## Current Behavior

`KeyError: ('coordinates', 'occurred at index 1101')` not matched by `*error`

## Possible Solution

Remove field value quoting in alert condition with leading wildcards

## Steps to Reproduce (for bugs)

In this issue: https://github.com/Graylog2/graylog2-server/issues/5794

## Your Environment

* Graylog Version: `graylog/graylog:3.0`
* Elasticsearch Version: `docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.2`
* MongoDB Version: `mongo:4.0`
* Operating System: Ubuntu 18.04
* Browser version: Netscape navigator 2.0

**Comment by bernd** [comment]
This should work with the new alerting system in 3.2. Please open a new issue if you still see problems. Thank you!
