### ISSUE TITLE
API: Stream created via api doesnt start, doenst work until 'edited'

### ISSUE THREAD

**Issue by rlogan403** [Graylog2/graylog2-server#596]
This is difficult to get replicated, but is causing problems (obviously). In this case Graylog 0.20.2, but similar on 0.20.3. One graylog server, and one elasticsearch server, all built via puppet, so replicating is somewhat easy.

Stream rule is simply triggered when the word 'burgle' is in the message. Running this command line log generation:
while true; do D=`date`; logger burgle $D; done

The JSON used to create this looks thus:
        {
            "creator_user_id": "admin",
            "description": "Drum",
            "rules": [
                {
                    "field": "message",
                    "inverted": false,
                    "type": 2,
                    "value": "burgle"
                }
            ],
            "title": "Test Bert"
        },

I use a python script to insert and enable the stream using the API. The script lives here:
https://github.com/qmetric/graylog2-api-tools

There are no issues indexing on the server. There is no excessive load.

From the two screenshots:
You can see the message rates for the 'Test Bert' stream:
![rate](https://cloud.githubusercontent.com/assets/2778465/3356612/1f00a87a-fac4-11e3-9063-3feffcd5017c.jpg)
But a search shows nothing for this stream???
![no_messages](https://cloud.githubusercontent.com/assets/2778465/3356613/22fa1ccc-fac4-11e3-925b-4daa39b699c5.jpg)

And then edit the stream (pause/resume in this case):
![now_messages](https://cloud.githubusercontent.com/assets/2778465/3356639/8ba7a938-fac4-11e3-9283-5db7a203de51.jpg)

The problem is, that it seems like perhaps there is some issue indexing messages that takes time, almost like they get to elasticsearch, but don't get flagged 'quickly' enough to be associated to the stream. Searches then fail.

One thing to note, this may not be stream related. I noted in these examples that the straight home search was failing to find any occurrence of 'burgle' as well. More worryingly, I stopped the 'while script' over 20 minutes ago, but I am still seeing messages from it arrive now in the web interface, and these are early ones when the 'while' test wasn't attaching a date, thus:

![home](https://cloud.githubusercontent.com/assets/2778465/3356722/a9c720b4-fac5-11e3-8404-caeb6f6db5fe.jpg)

Perhaps its related to time? Stuff entering graylog but not presented until the user interface thinks its 'that time'. In which case it may be on how messages are represented ... not sure if they are marked temporally on entry, or using the messages own timestamp ...

**Comment by bernd** [comment]
There have been many fixes regarding time zones since Jul. I am closing this. Please re-open if you still have problems with this in Graylog 1.0.0. Thank you!
