### ISSUE TITLE
/api/system/indices/ranges/INDEX/rebuild does not accept a dash in INDEX

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#5960]
I had to reindex a graylog index and decided to add `-version` to an existing graylog2 index (so the full name became `graylog2_5-6.7.0`). This works fine - but the **Recalculate index ranges** button throws a generic error (404 from the server) - which seems to be caused by the dash in the index name. Is this a known issue?

**Comment by SjonHortensius** [comment]
Hmm, apparently there is a different reason - because `graylog2_5.670` also throws a 404, is this a known issue. Do I need to inform graylog about new indices somehow - even though they appear in the list of indices just fine?

**Comment by SjonHortensius** [comment]
using the **close** button actually provides more details in the http-response - but this is not gracefully handled and the 404 error is ignored. The body, however, contains

```
{"type":"ApiError","message":"Index [graylog2_5-6.7.0] doesn't look like an index managed by Graylog."}
```

**Comment by bernd** [comment]
Graylog doesn't expect anything else than a number after the last `_` character. This is a limitation of the current implementation of index rotation and cannot be changed easily.

Unfortunately, renaming indices is currently not possible in Elasticsearch/OpenSearch so to reindex data it needs to be reindexed twice. `index_1 -> index_1_reindex -> index_1`.

I am closing this issue.
