### ISSUE TITLE
Changing streams via a dropdown menu

### ISSUE THREAD

**Issue by Mexonizator** [Graylog2/graylog2-server#5963]
Hello!

It'd be nice to have a dropdown menu to change the stream, that's being viewed, right on its page. 

As for now one has to return to the page with the list of streams and choose another one. 

As it's one of the most often actions, it'd be really convenient.

**Comment by florianvolle** [comment]
Hi @Mexonizator 
this will be part of the open sourced Views in the upcoming version 3.1

**Comment by Mexonizator** [comment]
Good to hear! Thanks!
