### ISSUE TITLE
Memory Leaks: Stop working after several hours

### ISSUE THREAD

**Issue by rlanore** [Graylog2/graylog2-server#597]
Hi,

My graylog2-server stop to work after some hours because server has no more memory. 
No error message

into init script i had add 
-Xms and -Xmx to 1G for graylog2-server

But top screen show that process consume 2G RAM

  PID USER      PR  NI  VIRT  RES  SHR S  %CPU %MEM    TIME+  COMMAND                                
 2375 elastics  20   0 2632m 2.4g  21m S 109.0 40.4   1794:40 java                                   
20199 root      20   0 1008m 295m 5292 S  13.3  4.9  69:42.23 java                                   
19962 root      20   0 2649m 2.0g  11m S   9.0 34.4  48:44.52 java                                   

root@silog-backend:/var/log/graylog2-server# ps -edf| grep 19962
root     19962     1 14 07:36 ?        00:47:33 /usr/bin/java -Xmx1g -Xms1g -jar /usr/share/graylog2-server/graylog2-server.jar -p /var/run/graylog2/graylog2-server.pid -f /etc/graylog2/server/server.conf
root     28353 12358  0 13:09 pts/0    00:00:00 grep 19962

root@silog-backend:/var/log/graylog2-server# java -version
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1~deb7u1)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)

**Comment by kroepke** [comment]
There used to be issues with metrics being collected for threads, which could leak metric information.

Could you try again with with either 0.92.4 or 1.0 beta, preferably the latter.
Thanks!

**Comment by bernd** [comment]
I am closing this issue now. Please re-open if you still see this problem with Graylog 1.0.0. Thank you!
