### ISSUE TITLE
Daily Widget won't get updated over night

### ISSUE THREAD

**Issue by JohanvMarion** [Graylog2/graylog2-server#598]
Hi,

We have placed a couple of widgets onto a Dashboard, so far so good
These widgets reflects counts on certain messages e.g.:
```
{
    "from": 0,
    "size": 100,
    "query": {
        "query_string": {
            "query": "\"[search term]\"",
            "allow_leading_wildcard": false
        }
    },
    "post_filter": {
        "bool": {
            "must": {
                "range": {
                    "timestamp": {
                        "from": "2014-06-26 00:00:00.000",
                        "to": "2014-06-26 23:59:59.000",
                        "include_lower": true,
                        "include_upper": true
                    }
                }
            }
        }
    },
    "sort": [
        {
            "timestamp": {
                "order": "desc"
            }
        }
    ]
}
```
The problems is that these counter won't get updated overnight.

As Search requirements we use: today 00:00:00 TO today 23:59:59 which get translated in the query.
`rangetype=keyword&relative=0&keyword=today+00%3A00%3A00+TO+today+23%3A59%3A59`

When we restart Graylog2-Server and we login again on the Dashboard these value's are being updated.
We tried to schedule a cron job to do this on a daily basis, but that doens't seem to work.
We can see from loggin information that the server restarts normally, but dashboard value's don't get updated. If we do run this manually it works.

Is there a good way to solve this issue? Maybe without restarting Graylog2-Server service?

**Comment by joschi** [comment]
This issue has been fixed in commit e6ee41bd4a47342be4e836252fa9c6bdf50deaab (Graylog 1.0.0 and later).

Please add a comment, if the problem still exists in current versions of Graylog.
