### ISSUE TITLE
Implement content pack integration for the new alerting system

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#5995]
## Description

The new alerting system needs to be integrated into the content pack system. The following components need to be included:

- [ ] Event definitions
- [ ] Notifications

**Comment by mpfz0r** [comment]
> ## Description
> 
> The new alerting system needs to be integrated into the content pack system. The following components need to be included:
> 
>     * Event processor definitions
> 
>     * Scheduler job definitions
> 
>     * Scheduler triggers
> 
>     * Notifications

IMO, we only need `Event defintions` and `Notifications`. The scheduler entries should be created automatically.

**Comment by bernd** [comment]
> IMO, we only need `Event defintions` and `Notifications`. The scheduler entries should be created automatically.

I agree and will update the list.
