### ISSUE TITLE
org.graylog2.plugin.alarms.callbacks.AlarmCallback interface does not expose _id to implementer 

### ISSUE THREAD

**Issue by jrunu** [Graylog2/graylog2-server#6002]
The plugin interface to implement custom notificatons does not expose the  _id that is associated with a configured instance of it. The Configuration passed just contains the fields exposed for configuration to the user.

## Expected Behavior
For each callback, the ObjecID of org.graylog2.alarmcallbacks.AlarmCallbackConfiguration should also be accessible.

## Current Behavior
Currently just the configuration information from the user exposed fields are accessible. The configuration passed to AlarmCallback::initialize() is sourced from AlarmCallbackConfiguration::getConfiguration().

## Context
I'm currently writing a plugin that has notifications with state for each configurated instance. This state needs to be stored, however I need a reliable (U)Id to create the relation between this state and the configuration instance. 

Currently I see now way to achieve this, besides abusing the name field for which there is no uniquess garantuee besides other concerns. 

Thanks

Ps: Is this the correct place or should I be rather posting this to the Community Development section?

**Comment by kroepke** [comment]
We are overhauling the alert system for 3.1 and will look into adding this capability there.

**Comment by jrunu** [comment]
Looking forward to that. I realized that I can't access the title either, so I opted for using the stream id. That has the side effect that there can only be one instance of the notification type per stream but that's an acceptable limitation for me as of now. Thanks.
