### ISSUE TITLE
Index is incorrectly included in the search target when it contains a document with timestamp "1970-01-01 00:00:00.000"

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#6014]
Index is incorrectly included in the search target when it contains a document with timestamp "1970-01-01 00:00:00.000"

## Expected Behavior
Indices should be filtered according to the time range defined in the query

## Current Behavior
Index is incorrectly included in the search target when it contains a document with timestamp "1970-01-01 00:00:00.000"

![image](https://user-images.githubusercontent.com/24830359/59503996-7c269a80-8eaa-11e9-84f4-a1b11cd9c072.png)

![image](https://user-images.githubusercontent.com/24830359/59504005-8779c600-8eaa-11e9-8190-7a34efe2d268.png)

```
curl -s -H 'Content-Type: application/json' 'http://localhost:9200/beats_90days_18/message/_search?size=1&pretty=true' -d '{ "sort" : [ {"timestamp" : { "order" : "asc" } } ] }' | grep '"timestamp"'
          "timestamp" : "1970-01-01 00:00:00.000"
```

## Steps to Reproduce (for bugs)
1. Index a document and match its timestamp using function parse_unix_milliseconds with value 0.
2. Use what ever search conditions
3. See what indices are queried

## Context
Because of this issue, an index with incorrect datatype is always included in the search results no matter what are the search conditions. And because of that incorrect datatype the Field statistics are broken. When I deleted the document with an incorrect timestamp and recalculated the index time range correct indices were targeted

## Your Environment

* Graylog Version: 3.0.1
* Elasticsearch Version: 6.7.2
* MongoDB Version: 4.0.7
* Operating System: CentOS 7
* Browser version: Safari

**Comment by jalogisch** [comment]
@hulkk thank you for this detailed report.

What you describe works like it was invented. Graylog takes the indices and does a `min`/`max` query on the date and use the found range for the calculation.

In addition for the search Graylogs gets a time range where it should search for logs and it just looks what indices contains messages in that range and search in that indices. 

I can't see any issue currently. If you can't follow or disagree please follow up

**Comment by hulkk** [comment]
Please read my report again.

In my example the search time range is in 14th of June 2019, and Graylog includes **incorrectly** the index beats_90days_18 only when there is at least one document with timestamp "1970-01-01 00:00:00.000".

After I deleted that single document with incorrect timestamp, the query was targeted correctly to only index beats_90days_29.

**Comment by dennisoelkers** [comment]
@hulkk: @jalogisch read and answered to your report correctly. Graylog stores metadata for each index containing the timestamps of the earliest and latest document respectively. For that index it stores that the index contain messages starting from January 1st, 1970 (because of the single message with the wrong timestamp) to ~7 days ago. Therefore it includes that index if you search for any timerange that is between those two dates.
