### ISSUE TITLE
Grok pattern illegal repitition

### ISSUE THREAD

**Issue by davejlong** [Graylog2/graylog2-server#6019]
Trying to create a Grok pattern to match Windows DHCP Audit Logs in Gray 3 and when I feed what I believe to be a correct Grok pattern (tested against [Grok Debugger](https://grokdebug.herokuapp.com/)) and I get an error back from Graylog

Grok pattern is:

```
%{NUMBER:id},%{DATE_US:date},%{TIME:time},%{DATA:message},%{IP:ip},%{HOSTNAME:hostname},%{MAC:macaddr},%{USER:user},%{NUMBER:transaction},%{NUMBER:qresult}
```

And some test sample data:

```
31,06/12/19,00:47:05,DNS Update Failed,192.168.20.76,SPARE-0114-DT.domain.local,,,0,6,,,,,,,,,2
30,06/12/19,00:47:05,DNS Update Request,192.168.20.76,SPARE-0114-DT.domain.local,,,0,6,,,,,,,,,0
11,06/12/19,00:47:05,Renew,192.168.20.76,SPARE-0114-DT.domain.local,F8B156C06C97,,2356879845,0,,,,0x4D53465420352E30,MSFT 5.0,,,,0
```

## Expected Behavior
Grok pattern tests and saves correctly.

## Current Behavior
Pattern throws error:

```
Grok Error
Illegal repetition near index 0
%{DHCP Audit Log}
^
```

## Steps to Reproduce (for bugs)
1. Go into create a new Grok Pattern
2. Paste the above pattern in as the Pattern
3. Give it a name
4. Try to save

## Your Environment

* Graylog Version: Graylog 3.0.2+1686930 on *** (Oracle Corporation 1.8.0_212 on Linux 5.1.8-300.fc30.x86_64)
* Elasticsearch Version: 6.8.0
* MongoDB Version: mongodb 4.0.10
* Operating System: Fedora 30
* Browser version: Firefox 67.0.2

**Comment by jalogisch** [comment]
He @davejlong 

are you sure that this is the same pattern that you use? I do not get any result from your pattern and your sample data.

![Bildschirmfoto 2019-06-18 um 08 17 02](https://user-images.githubusercontent.com/404238/59657594-7928f400-91a1-11e9-8483-1580be647ac7.png)

The above image is used the pattern creator in `System > Grok Pattern´
