### ISSUE TITLE
Changing Relative search timeframe not updating Histogram

### ISSUE THREAD

**Issue by george-viaud** [Graylog2/graylog2-server#6071]
## Expected Behavior
When selecting a different Relative time-frame in the search page, the histogram should update.

## Current Behavior
When selecting a different Relative time-frame in the search page, the histogram does not refresh / update.  Clicking play to submit the search, or even a hard-refresh of the page also fails to update the histogram.
![image](https://user-images.githubusercontent.com/16565894/60593936-a6a49e80-9d58-11e9-89fc-d5d9b941e9c1.png)

Note:  When changing to absolute or keyword, everything works as it should

## Your Environment
This is a fresh install (~2 weeks old) on an aws instance running Ubuntu, 2 cores 8GB ram

Live demo available via screenshare to project team upon request / if helpful

* Graylog Version: 3.0.2+1686930 on 3.217.218.53
* Elasticsearch Version: 6.8.1
* MongoDB Version: 4.0.10
* Operating System: Ubuntu 18.04 LTS (server)
* Browser versions reproduced on: 
- FireFox 67.0.4 (64-bit)
- Chromium 75.0.3770.90

**Comment by dennisoelkers** [comment]
@george-viaud: Thanks for reporting this. Can you record a screen share as gif and add it to the issue? That makes it clearer. A few questions:

- Can you reproduce the issue reliably?
- Does this always happen with the relative search or are there cases where it works as intended?
- Do you see anything in your browser's JS console or network tab that might be related?

**Comment by george-viaud** [comment]
@dennisoelkers thank you for the reply and questions.  Answers below - also, I'm available for any level of debug that would be helpful.

Please see attached animated GIF reproduction of the problem - In the video:
First I show the problem, changing relative search but histogram does not update date range.
Next I show absolute date does update the range (for clarity and contrast).

Reliably reproducible: I can reproduce 100% of the time on my system
Does this always happen...: Relative search appears to show this problem with all settings 100% of the time.
JS Console: There are no messages in the JS console log when reproducing this problem

Thank you

![graylog-histogram](https://user-images.githubusercontent.com/16565894/60605086-ba0e3480-9d6d-11e9-94c9-c9c475f414f6.gif)

**Comment by dennisoelkers** [comment]
@george-viaud: You are expecting that the search is updated immediately after changing the time range. This is not the case in the current search, you need to click the search/looking class button once more.

This issue is not the case with the views/extended search (for 3.0 available in enterprise, in 3.1 going to be part of the OSS core and in 3.2 replacing the existing search), which is updating the search immediately when the time range is changed. Therefore we will not fix this problem in the current search anymore.
