### ISSUE TITLE
Boolean UI Search loads 1 or 0 instead of True or False causing empty search results

### ISSUE THREAD

**Issue by BlueTeamNinja** [Graylog2/graylog2-server#6073]
When clicking the magnifying glass on a boolean value from **QUICK VALUES**, the search field is populated with 1 or 0, instead of true/false.  Likewise, the Quick Values pages displays 1 or 0 instead of true or false.

## Expected Behavior

The Quick Values view should be populated with true/false OR the search result should cater to field_name:1

I would suggest both be possible but for less effort, matching the Quick Values and their auto-populating search to simply display true/false instead of the underlying 1/0 would be ideal 

## Current Behavior

No messages found from filtering data right in front of you. 

## Steps to Reproduce (for bugs)

1. Create a Quick Values widget based on a boolean field
![image](https://user-images.githubusercontent.com/1891183/60603927-aae6b100-9d84-11e9-92ee-822e42f8d3b2.png)

2. Click the Search Autofill button
![image](https://user-images.githubusercontent.com/1891183/60604029-d8cbf580-9d84-11e9-822e-f7f7c6ae9dd7.png)

3. Nothing found from those results
![image](https://user-images.githubusercontent.com/1891183/60604078-f0a37980-9d84-11e9-99fa-fccb2a81270b.png)

## Context

Slows down productivity slightly. 

## Your Environment

* Graylog Version:  3.02
* Elasticsearch Version: 
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by jalogisch** [comment]
he @BlueTeamNinja 

the search page will be re-placed in 3.2 by the search that is currently known as extented search. This bug will not be fixed in the search anymore but we will leave that open as reference.
