### ISSUE TITLE
housekeeping for `system.messages` in MongoDB

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#6118]
## Context
Graylog does not provide the option or the ability to make some kind of house keeping on the mongoDB collection that is filled continuously. That might end in a huge mongoDB with an enormous `system.messages` collection that is of nearly no use. 

We should add one configuration flag (online available?) that holds the number of records or the time the internal logfile in the database should not go over. 

This will prevent Graylog server issues based on enormous MongoDB Databases.

## Your Environment

* Graylog Version: 3.0

[Z#2485]

**Comment by jalogisch** [comment]
This can be used to regular clean up the collection to keep only a month of data.

```
db.getCollection('system_messages').deleteMany({
    "timestamp":{
            $lt: new Date(new Date().setMonth(new Date().getMonth()-1))
    }
})
```

**Comment by rubinlinux** [comment]
The index_failures collection is a capped collection at 50 meg. Maybe system_messages should be the same? When mongo runs the disk out of space it causes a lot of trouble.

**Comment by boosty** [comment]
@patrickmann I assigned you, since you are already working on it.
