### ISSUE TITLE
Other Graylog nodes are not processing logs except master 

### ISSUE THREAD

**Issue by bhoss12** [Graylog2/graylog2-server#6121]
I have configured Graylog Cluster with 1 master and 2 nodes, and using Elasticsearch service and MongoDB service from AWS.

## Current Behavior

All the nodes should process logs but only Master is processing logs.
when I configured all nodes for http_publish_uri =  Master ip , then all the nodes are showing same logs processing as Master node. otherwise "The journal contains 0 unprocessed messages in 1 segment. 0 messages appended, 0 messages read in the last second." I am not sure how to configure correctly, please help me.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

All the nodes should process logs but only Master is processing logs.
when I configured all nodes for http_publish_uri =  Master ip , then all the nodes are showing same logs processing as Master node. otherwise "The journal contains 0 unprocessed messages in 1 segment. 0 messages appended, 0 messages read in the last second." I am not sure how to configure correctly, please help me.

## Your Environment

* Graylog Version: Graylog 3.0.2
* Elasticsearch Version: 6.7 AWS cluster service
* MongoDB Version: using as a service from Atlas
* Operating System: ubuntu 16
* Browser version: safari

**Comment by bhoss12** [comment]
![Uploading Screenshot 2019-07-10 at 9.41.01 PM.jpg…]()

**Comment by bhoss12** [comment]
Please find the attached screenshot

**Comment by jalogisch** [comment]
It looks like you do not ingest to all nodes. When you send messages only to the master node only this node will process the messages. Graylog does not distribute the message in the cluster for processing.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
