### ISSUE TITLE
How do I set up to allow only certain ips to commit logs

### ISSUE THREAD

**Issue by fanmingyi** [Graylog2/graylog2-server#6123]
Sorry, I'm a beginner

**Comment by jalogisch** [comment]
You need to configure your Inputs with certificate authentication and use that on the client. The other option would be to configure iptables or similar.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
