### ISSUE TITLE
[v3.1-beta] Views are one click too far away

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#6140]
In v3.1, I have to click twice to reach the new search page because it's behind "Create new". Not sure about a solution that also allows me to reach existing views quickly. cc @kyleknighted 

I believe that the "Create View" page is used heavily and it irritated me that I had to click twice.

![views1](https://user-images.githubusercontent.com/35022/61154772-a02ec900-a4b4-11e9-9f19-f6936176630f.png)

**Comment by kmerz** [comment]
This will not be fixed in 3.1.0 And will be hopefully fixed with https://github.com/Graylog2/graylog-plugin-enterprise/issues/1122
