### ISSUE TITLE
Sending GELF messages over https

### ISSUE THREAD

**Issue by jeanluclariviere** [Graylog2/graylog2-server#6145]
## Expected Behavior
The data we're sending to graylog is sensative and we would like to secure it over https, could someone point me in the right direction for configuring this, if it's possible?

We tried sitting our graylog server infront of an nginx reverse proxy, but GELF doesn't currently support the X-Forwarded-for header and so, although this works, all of the source IPs being logged in graylog are from the nginx proxy, not the source IP.

* Graylog Version: 2.5.1
* Operating System: RHEL7

**Comment by jeanluclariviere** [comment]
I should add that we've already secured the rest and web interfaces.

**Comment by jalogisch** [comment]
If you have the HTTP GELF Input you are able to define certificates that are used to create a secured input for https. 

The other option using a frontend you had already tried. If the proxy is seen as sending source you missed that field in the GELF messages ... 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by jeanluclariviere** [comment]
> If you have the HTTP GELF Input you are able to define certificates that are used to create a secured input for https.

I've asked the same question in the community and have yet to get an answer, terribly sorry to ask this here but if you could be more specific regarding this line of your reply specifically, it would be greatly appreciated. What and how do you mean by "define certificates that are used to create secured input".
