### ISSUE TITLE
Graylog causes an IllegalArguementException on Elasticsearch

### ISSUE THREAD

**Issue by Arkasian** [Graylog2/graylog2-server#6161]
Graylog causes an unexpected behaviour of Elasticsearch.

## Expected Behavior
When I enter Search tab, I would like to be able to view Messages graph, Statistics and Quick values.

## Current Behavior
For now, Graylog front-end app says that the back-end returned 
HTTP/1.1 500 Internal Server Error, but graylog.log does not contain any information about that event. Elasticsearch's log says much more:
[2019-07-18T11:27:01,521][DEBUG][o.e.a.s.TransportSearchAction] [bmkjLh9] All shards failed for phase: [query]
org.elasticsearch.ElasticsearchException$1: Fielddata is disabled on text fields by default. Set fielddata=true on [message] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory. Alternatively use a keyword field instead.

The thing is: Even though tha Graylog server uses field param in query, elasticsearch throws an exception. Despite adding the properties as the log says to [message] field, it still doesn't work.

## Possible Solution
I don't know possible solution for the actual code, however I would start looking for a problem in part where Graylog queries elasticsearch for [message] field. 

## Steps to Reproduce (for bugs)

I have:
1. installed Graylog 3.0.2,
2. connected it to Elasticsearch,
3. entered messages on the left side menu,
4. chosen one of suboptions of 'messages': Quick Values, Statistics etc. 
I've just followed the tutorial and nothing more. It is just not working.

## Context
Not much, Graylog works fine, but it is just a lack of the feature I'm expecting it to have.

## Your Environment

* Graylog Version: 3.0.2
* Elasticsearch Version: 6.8.1
* MongoDB Version: 4.0.10
* Operating System: CentOS 7 x86_64 kernel: 3.10.0-957
* Browser version: Firefox 68.0, Chrome 75.0.3770.100

**Comment by kroepke** [comment]
Could you please describe the steps you took to get this error message?
It's a bit difficult to exactly reproduce the issue otherwise.

Thanks!

**Comment by Arkasian** [comment]
Okay, I have updated as you asked for, sorry for lack of this information.

**Comment by kroepke** [comment]
The option to perform quick values and related analysis on the `message` field is disabled by default, because it is analyzed and this does often not behave like people expect. Also it has a considerable performance impact.
Did you enable the option?

**Comment by Arkasian** [comment]
Okay, I didn't know it as I am not the one who set up the Graylog in our test environment. I have passed the information to the administrator which is responsible for it. Thank you very much for you time and help.
Greetings.

**Comment by vjcalel** [comment]
@kroepke I have the same problem. Can you tell me how to disable that option ?
