### ISSUE TITLE
Graylog web UI doesn't working when using http auth together with nginx reverse proxy

### ISSUE THREAD

**Issue by sagaraspl** [Graylog2/graylog2-server#6169]
## Expected Behavior

When I am using nginx reverse proxy together with http auth graylog doesn't creating session and hence it doesn't working.

## Current Behavior

It is constantly asking for http auth.

## Steps to Reproduce (for bugs)

1. Setup graylog and nginx virtual host
2. Add http auth in nginx virutal host
3. Try to access graylog web UI and enter http auth username and password
4. It will constantly ask you for username and password and don't let you allow to move further.

## Your Environment

* Graylog Version: 3.0
* Elasticsearch Version: 6.6.1
* MongoDB Version: 3
* Operating System: Ubuntu 18
* Browser version: Chrome

**Comment by jalogisch** [comment]
As this is working for me, it is very likely that this is based on your configuration.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by sagaraspl** [comment]
Hi How can you close in this way?

At least you should then suggest in which configuration it works. I haven't altered any configuration, I just install graylog with docker and put nginx reverse proxy, so there shouldn't be any configuration issue.
