### ISSUE TITLE
Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by YoBrotato** [Graylog2/graylog2-server#6187]
I believe this issues persists in v3.0.x as well. As I was going through dashboard creation for the new 3.1.0.Beta.2 release, I tried to edit a widget in the dashboards panel. I got the error in the title. 

## Expected Behavior

Should be able to proceed with a dialog box to modify the parameters of the widget in question. 

## Current Behavior

(See screenshot) This specifically happens when an attempt is made to edit a **table** widget. Upon clicking the pencil icon, you are immediately directed to the error page ( gorilla / banana ). 

According to one of our customers, this issue was not present in Graylog v2.4. 
I too have observed this. 

## Possible Solution

See stack trace in attachment (from Chrome Version 76.0.3809.71 (Official Build) 

## Steps to Reproduce (for bugs)

1. Generate a table or chat with data from a regular Search
2. Add this to a dashboard ( any dashboard )
3. Go to Dashboards, click the 'unlock/edit' button in the upper right corner
4.Try to edit any widget that contains table data ( see screenshot ) 

## Context

Customers are not able to modify dashboards in production. The only workaround is to delete this dashboard widget, and re-create with the updated parameters. 

## Your Environment

* Graylog Version: graylog-3.1.0-beta.2
* Elasticsearch Version: 6.8.1-1 
* MongoDB Version: 4.0.10-1.el7
* Operating System: CentOS Linux 7 (Core) 3.10.0-957.21.3.el7.x86_64
* Browser version: Chrome Version 76.0.3809.71 (Official Build) 
[atx-logger-1564006657381.log](https://github.com/Graylog2/graylog2-server/files/3429160/atx-logger-1564006657381.log)
![image001](https://user-images.githubusercontent.com/20843217/61836385-9d818b80-ae45-11e9-851a-e5e52e7d335c.png)

yum list installed | egrep -i 'mongodb|elasticsearch|graylog-server'
elasticsearch-oss.noarch              6.8.1-1                          @elasticsearch-6.x
graylog-server.noarch                 3.1.0-2.beta.2                   @graylog
mongodb-org.x86_64                    4.0.10-1.el7                     @mongodb-org-4.0
mongodb-org-mongos.x86_64             4.0.10-1.el7                     @mongodb-org-4.0
mongodb-org-server.x86_64             4.0.10-1.el7                     @mongodb-org-4.0
mongodb-org-shell.x86_64              4.0.10-1.el7                     @mongodb-org-4.0
mongodb-org-tools.x86_64              4.0.10-1.el7                     @mongodb-org-4.0

**Comment by bernd** [comment]
I can reproduce that. Here is a stack trace from my dev environment:

```
Cannot read property 'find' of undefined


Stack Trace:

TypeError: Cannot read property 'find' of undefined
    at http://127.0.0.1:8080/graylog-plugin-enterprise.js:171189:26
    at Array.map (<anonymous>)
    at Select.render (http://127.0.0.1:8080/graylog-plugin-enterprise.js:171188:57)
    at finishClassComponent (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:14741:31)
    at updateClassComponent (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:14696:24)
    at beginWork (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:15644:16)
    at performUnitOfWork (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:19312:12)
    at workLoop (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:19352:24)
    at renderRoot (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:19435:7)
    at performWorkOnRoot (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:20342:7)
    at performWork (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:20254:7)
    at performSyncWork (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:20228:3)
    at interactiveUpdates$1 (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:20495:7)
    at interactiveUpdates (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:2170:10)
    at dispatchInteractiveEvent (webpack://__%5Bname%5D/./node_modules/react-dom/cjs/react-dom.development.js?:4882:3)

Component Stack:

    in Select (created by MultiSelect)
    in MultiSelect (created by QuickValuesConfiguration)
    in div (created by FormGroup)
    in FormGroup (created by QuickValuesConfiguration)
    in div (created by QuickValuesConfiguration)
    in QuickValuesConfiguration (created by QuickValuesWidgetEditConfiguration)
    in fieldset (created by QuickValuesWidgetEditConfiguration)
    in QuickValuesWidgetEditConfiguration (created by WidgetEditConfigModal)
    in fieldset (created by WidgetEditConfigModal)
    in div (created by BootstrapModalForm)
    in div (created by ModalBody)
    in ModalBody (created by BootstrapModalForm)
    in form (created by BootstrapModalForm)
    in div (created by ModalDialog)
    in div (created by ModalDialog)
    in div (created by ModalDialog)
    in ModalDialog (created by Modal)
    in Transition (created by Fade)
    in Fade (created by Modal)
    in RefHolder (created by Modal)
    in div (created by Modal)
    in Portal (created by Modal)
    in Modal (created by Modal)
    in Modal (created by BootstrapModalWrapper)
    in BootstrapModalWrapper (created by BootstrapModalForm)
    in BootstrapModalForm (created by WidgetEditConfigModal)
    in WidgetEditConfigModal (created by Widget)
    in div (created by Widget)
    in Widget (created by ShowDashboardPage)
    in div (created by ShowDashboardPage)
    in Resizable (created by GridItem)
    in DraggableCore (created by GridItem)
    in GridItem (created by ReactGridLayout)
    in div (created by ReactGridLayout)
    in ReactGridLayout (created by ResponsiveReactGridLayout)
    in ResponsiveReactGridLayout (created by WidthProvider)
    in WidthProvider (created by ReactGridContainer)
    in ReactGridContainer (created by ShowDashboardPage)
    in div (created by ShowDashboardPage)
    in div (created by Row)
    in Row (created by ShowDashboardPage)
    in span (created by ShowDashboardPage)
    in DocumentTitle (created by ShowDashboardPage)
    in ShowDashboardPage (created by LoadableComponent)
    in LoadableComponent (created by RouterContext)
    in div (created by Col)
    in Col (created by AppWithoutSearchBar)
    in div (created by Row)
    in Row (created by AppWithoutSearchBar)
    in div (created by AppWithoutSearchBar)
    in AppWithoutSearchBar (created by RouterContext)
    in div (created by AppWithGlobalNotifications)
    in AppWithGlobalNotifications (created by RouterContext)
    in AppErrorBoundary (created by withRouter(AppErrorBoundary))
    in withRouter(AppErrorBoundary) (created by App)
    in div (created by App)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router (created by AppRouter)
    in AppRouter (created by LoggedInPage)
    in LoggedInPage (created by LoadableComponent)
    in LoadableComponent (created by AppFacade)
    in AppFacade
```

**Comment by edmundoa** [comment]
I tried reproducing the issue in the 3.0.2 release and I couldn't, so I think this only affects the 3.1 beta release.

**Comment by bernd** [comment]
@YoBrotato This will be fixed in the upcoming beta release.

**Comment by YoBrotato** [comment]
YAAAAY I submitted my first bug/fix! :-D
