### ISSUE TITLE
Quick Values visualization does not get all required props in Dashboard

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#6189]
`QuickValuesVisualization` is missing `field` prop in Dashboards. Visiting a Dashboard with a Quick Values Widget displays a warning in the web console:

```
Warning: Failed prop type: The prop `field` is marked as required in `QuickValuesVisualization`, but its value is `undefined`.
    in QuickValuesVisualization (created by Widget)
    in Widget (created by ShowDashboardPage)
```

On closer inspection of the warning, `QuickValuesVisualization` is expecting a `field` prop with the field used to compute the aggregation and `Widget` is not setting this field when the visualization element is created.

Besides the warning, the only consequence this will have is that we won't pretty print time ranges, being inconsistent with the results in the search page.

## Possible Solution
Add `field` prop to `QuickValuesVisualization` when rendering from a Dashboard, or get that information from the `config` prop, where it can also be found.

## Steps to Reproduce (for bugs)
1. Connect to a Graylog development server with your browser
1. Add a Quick Values Widget to a Dashboard
1. Visit that Dashboard and see the warning in the browser console

## Your Environment

* Graylog Version: 3.1.0-beta.3-SNAPSHOT, 3.0.x

**Comment by bernd** [comment]
The quick values widget doesn't exist anymore so this can be closed.
