### ISSUE TITLE
[Events] Custom field creation failed

### ISSUE THREAD

**Issue by mehrenreich** [Graylog2/graylog2-server#6192]
When trying to create a custom field, even with not all needed information, an error `undefined is not an object (evaluating 'r.providers[0]')` happens.

This **does not happen** when selecting "Template" or "Lookup table".

![custom_field](https://user-images.githubusercontent.com/516452/61869565-3531b900-aedc-11e9-9dc4-0e4ed29867fc.gif)

## Expected Behavior

Get a friendly information / error message that not every field was filled (correctly).

## Steps to Reproduce (for bugs)
1. When defining a custom field, fill "Name"
2. check "Use field as Event Key"
3. leave "Set Value From" unselected
4. click "Done"

## Your Environment
* Graylog Version: Graylog 3.1.0-beta.2+d4e04e5

**Comment by edmundoa** [comment]
Yes, validation is pretty much still in the works. Refs #https://github.com/Graylog2/graylog2-server/issues/6153
