### ISSUE TITLE
Graylog LDAP issue

### ISSUE THREAD

**Issue by vankireddy** [Graylog2/graylog2-server#6195]
i am getting below WARNING in logfile very frequently
WARN : org.apache.directory.ldap.client.api.LdapNetworkConnection - null java.lang.NullPointerException: null
java.lang.NullPointerException: null
at org.apache.directory.ldap.client.api.LdapNetworkConnection.messageReceived(LdapNetworkConnection.java:2040) ~[graylog.jar:?]
at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:997) ~[graylog.jar:?]
at
can some one please help me on it
* Graylog Version: 3.0.5
* Elasticsearch Version: 
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by YoBrotato** [comment]
Hi vankireddy -

Do you believe this is a bug or defect with the Graylog basecode? If so, please fill out the required fields when submitting a issue request.

Similar users had configuration issues that were _resolved_ by contacting the community support groups:  https://community.graylog.org/t/solved-problems-with-ldap/9823

In the future, please seek guidance there before engaging the development team.
