### ISSUE TITLE
3.1 Beta 3 Events page do not display content

### ISSUE THREAD

**Issue by TiNico22** [Graylog2/graylog2-server#6205]
## Current Behavior

the page stay indefinitly with the message : 
 Loading Events information...

## Steps to Reproduce (for bugs)

1. clic on events menu 

## Your Environment

Graylog Version: 3.1 beta 3 (upgraded from 3.0.2 via rpm)
Elasticsearch Version: 6.8.1_1
MongoDB Version: 3.6
Operating System: centos7
Browser version: chrome 75

**Comment by benoc617** [comment]
Same issue here, My environment:
Graylog Version 3.1.0 beta 3 (from graylog/graylog/3.1.0-beta.3-1 docker container)
Elasticsearch Version: 6.5.4
MongoDB Version: 3.6
Operating System: CoreOS (kernel 4.13.16-coreos-r2)
Browser version: Chrome 75  and Safari 12.1.1

**Comment by bernd** [comment]
@TiNico22 @benoc617 Thank you for the feedback!

We had to change some database structures unfortunately. So the easiest way to "fix" this would be to start from scratch.

You *might* have luck with the following MongoDB script. (execute via `mongo graylog script.js`)

<details>

```json
db.scheduler_job_definitions.updateMany(
  {
    "config.type": {
      "$in": [
        "email-notification-v1",
        "legacy-alarm-callback-notification-v1",
        "http-notification-v1"
      ]
    }
  },
  {
    "$set": {
      "config.type": "notification-execution-v1"
    }
  }
);

db.scheduler_triggers.updateMany(
  {
    "data.type": {
      "$in": [
        "email-notification-v1",
        "legacy-alarm-callback-notification-v1",
        "http-notification-v1"
      ]
    }
  },
  {
    "$set": {
      "data.type": "notification-execution-v1"
    }
  }
);
```

</details>

**Comment by TiNico22** [comment]
No luck on my side with this script.
I will do a fresh install later.

**Comment by bernd** [comment]
@TiNico22 Okay, thanks for the feedback. I am closing this issue, please create a new one if you still run into problems. Thank you!
