### ISSUE TITLE
Integrating graylog with PHP and Perl

### ISSUE THREAD

**Issue by ahmadtamimi3** [Graylog2/graylog2-server#6206]
I want to manage (Logging) through  graylog 3.0.2 from two different applications(API and reporting system), the first application written in PHP 7, and second application written in Perl.

I found GELF library for PHP and perl, but it only supports graylog2

https://github.com/bzikarsky/gelf-php
https://metacpan.org/pod/Net::Graylog::Client

Is there a GELF library for graylog 3.0.2 ? or should I replace graylog3 version to graylog2

**Comment by jalogisch** [comment]
The founding name of Graylog is Graylog2 - In addition GELF is not bound to a Graylog version. The specification can be found in the documentation: https://docs.graylog.org/en/3.0/pages/gelf.html

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
