### ISSUE TITLE
graylog test echo message

### ISSUE THREAD

**Issue by kopevgale** [Graylog2/graylog2-server#6207]
hi all, anybody can correct me with this command?
I try send test message to my graylog server in my local net.

echo -e '{"version": "1.1","host":"192.168.1.5","short_message":"Short message","full_message":"Backtrace here\n\nmore stuff","level":1,"_user_id":9001,"_some_info":"foo","_some_env_var":"bar"}\0' | nc -w 1 192.168.1.5 9000

**Comment by jalogisch** [comment]
We have covered that in the Graylog documentation: https://docs.graylog.org/en/3.0/pages/gelf.html?example-payload#example-payload

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
