### ISSUE TITLE
Release 3.x compatible metrics-reporter plugin

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#6208]
The https://github.com/graylog-labs/graylog-plugin-metrics-reporter plugin has not been updated/released in a while, but is actually being used by various people in production.

Despite the fact that it is officially unsupported, we need to verify that it does work with 3.0/3.1 (it very likely already does, since those APIs are generally very stable).
To ease some concerns we should also create an updated release version of it (probably a 3.0 release).

Not all of the reporters are equally important, primarily we see https://github.com/graylog-labs/graylog-plugin-metrics-reporter/blob/master/metrics-reporter-prometheus/README.md being used in production environments.

**Comment by bernd** [comment]
A Graylog 3.x compatible version has been released: https://github.com/graylog-labs/graylog-plugin-metrics-reporter/releases/tag/3.0.0
