### ISSUE TITLE
New Legacy Alarm Callback Notification always displays error

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#6218]
Since #6199, creating a new Legacy Alarm Callback notification always displays an error:

![Screenshot 2019-07-30 at 16 45 12](https://user-images.githubusercontent.com/716185/62139467-b082d880-b2e9-11e9-9023-9893356f295f.png)

## Expected Behavior
Before the Legacy Notification is set, creating a new Notification should not display an error.

## Current Behavior
Creating a new Legacy Alarm Callback displays a misleading error before even selecting the type of Legacy Alarm Callback Notification.

## Steps to Reproduce (for bugs)
1. Go to Events -> Notifications -> New Notification
2. Select type "Legacy Alarm Callbacks" as Notification type
3. See the error

## Your Environment
* Graylog Version: Graylog 3.1.0-beta.4-SNAPSHOT

**Comment by bernd** [comment]
The error goes away once the legacy type got selected. But yeah, we need to add a condition to the error message to only show up if a legacy type has been selected.

Good catch, thank you! :+1:
