### ISSUE TITLE
Save LDAP/AD settings and additional default role throws an Error

### ISSUE THREAD

**Issue by snownx** [Graylog2/graylog2-server#6247]
I´m trying to connect my Graylog Cluster (3 Nodes) with the Active Directory.
1. Setup the Server configuration correctly.
2. Connection test:
Test Server Connection works fine.

3. & 4. Configure User and Group mappings:
Login Test works correctly.
But choose an Additional Default Roles throws throws Error: (intermediate value).split is not a function.

5. Save LDAP Settings -> saves the settings and throws Error: (intermediate value).split is not a function.

## Expected Behavior

1. Displays the rule.
2. Save the Settings and displays the Page to continue with LDAP Group Mapping. 

## Current Behavior

```
(intermediate value).split is not a function


Stack Trace:

value@https://FQDN/assets/app.c56ca1b0cddbade869a5.js:227:113201
ka@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:18:63009
Sa@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:18:62804
Da@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:18:66638
Fo@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:18:90682
Vo@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:18:91066
Ys@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:18:97953
Ss@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:18:97333
Ls@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:18:96354
Zo@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:18:95228
enqueueSetState@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:18:44755
24/b.prototype.setState@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:26:1665
_onLdapSettingsChange@https://FQDN/assets/4c1b965a-35.c56ca1b0cddbade869a5.js:1:31848
n@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:10:1324
614/a.prototype.emit@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:90:240635
trigger@https://FQDN/assets/vendor.91c91d4a31d54d96392a.js:10:2199
loadSettings/<@https://FQDN/assets/builtins.c56ca1b0cddbade869a5.js:88:138095
l@https://FQDN/assets/builtins.c56ca1b0cddbade869a5.js:104:88608
YPyIcTeH/</</<[22]</n.exports/O.prototype._settlePromiseFromHandler@https://FQDN/assets/builtins.c56ca1b0cddbade869a5.js:104:61890
YPyIcTeH/</</<[22]</n.exports/O.prototype._settlePromise@https://FQDN/assets/builtins.c56ca1b0cddbade869a5.js:104:62690
YPyIcTeH/</</<[22]</n.exports/O.prototype._settlePromise0@https://FQDN/assets/builtins.c56ca1b0cddbade869a5.js:104:63389
YPyIcTeH/</</<[22]</n.exports/O.prototype._settlePromises@https://FQDN/assets/builtins.c56ca1b0cddbade869a5.js:104:64716
YPyIcTeH/</</<[2]</s.prototype._drainQueue@https://FQDN/assets/builtins.c56ca1b0cddbade869a5.js:104:18582
YPyIcTeH/</</<[2]</s.prototype._drainQueues@https://FQDN/assets/builtins.c56ca1b0cddbade869a5.js:104:18643
s/this.drainQueues@https://FQDN/assets/builtins.c56ca1b0cddbade869a5.js:104:16866
u@https://FQDN/assets/polyfill.c56ca1b0cddbade869a5.js:1:33700
M/<@https://FQDN/assets/polyfill.c56ca1b0cddbade869a5.js:1:33845
f@https://FQDN/assets/polyfill.c56ca1b0cddbade869a5.js:1:20081


Component Stack:

    in t
    in t
    in div
    in t
    in div
    in t
    in t
    in fieldset
    in form
    in div
    in t
    in div
    in t
    in LdapComponent
    in span
    in t
    in t
    in div
    in t
    in div
    in t
    in AuthenticationComponent
    in div
    in t
    in div
    in t
    in span
    in AuthenticationPage
    in n
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in t
    in withRouter(t)
    in div
    in App
    in RouterContext
    in Router
    in h
    in t
    in n
    in AppFacade
```

## Steps to Reproduce (for bugs)

Additional Default Role:
1. System -> Authentication -> LDAP/Active Directory
2. Configure Settings and use LDAP or LDAPs
3. Configure User and Group mapping
4. Choose a Additional Default Role -> throws Error: (intermediate value).split is not a function

Save LDAP Settings:
1. System -> Authentication -> LDAP/Active Directory
2. Configure Settings and use LDAP or LDAPs
3. Configure User and Group mapping
4. Save LDAP Settings (LDAP Settings are saved)
5. Error: (intermediate value).split is not a function

## Your Environment

* Graylog Version: 3.1.0-4.rc.1
* Elasticsearch Version: 6.8.2
* MongoDB Version: 4.0.11
* Operating System: Debian 10.0 Buster
* Browser Version: FF 68.0.1
* Java Version: openjdk-11-jre-headless 11.0.3

Thanks for Help!

**Comment by edmundoa** [comment]
I could reproduce this issue by visiting `/system/authentication/config/legacy-ldap` in the web interface and having a configured LDAP server.

Looking a bit into the code, it seems that the Error is thrown in a `MultiSelect` when being passed down an Array `value` prop.

**Comment by snownx** [comment]
I installed graylog-server 3.1.0-5.rc.2 on all Nodes and the same Error still occurs.

**Comment by edmundoa** [comment]
Did you also upgrade all plugins to the latest RC version?

**Comment by snownx** [comment]
our content of the plugin directory (/usr/share/graylog-server/plugin) is:
graylog-plugin-aws-3.1.0-rc.2.jar
graylog-plugin-collector-3.1.0-rc.2.jar
graylog-plugin-threatintel-3.1.0-rc.2.jar
so i would say yes.

**Comment by edmundoa** [comment]
Thank you for the information!

I have tried to reproduce the issue in a fresh 3.1.0-rc.2 installation but could not. Would you be so kind as to share with us a screenshot with the list of installed plugins found in the _System -> Nodes  -> Node_ page? Please also ensure that all nodes are running the same version, in case you have a multi-node setup.

**Comment by snownx** [comment]
you are welcome! And thanks for your help!

Version running on all 3 Nodes:
Node_1: 3.1.0-rc.2+15c1997, codename Quantum Dog
![node_1](https://user-images.githubusercontent.com/53821763/62875946-39573680-bd24-11e9-9220-aba54094749c.PNG)

Node_2 3.1.0-rc.2+15c1997, codename Quantum Dog

![node_2](https://user-images.githubusercontent.com/53821763/62875948-39573680-bd24-11e9-9342-28a744c0965b.PNG)

Node_3 3.1.0-rc.2+15c1997, codename Quantum Dog
![node_3](https://user-images.githubusercontent.com/53821763/62875950-39efcd00-bd24-11e9-8738-966097dc14c3.PNG)

**Comment by edmundoa** [comment]
Thank you for sharing those details with us! 

I know it's an obvious question, but I still couldn't manage to reproduce the issue on the latest RC: did you restart all three servers after upgrading them? Also, could you please try to reproduce the issue in another browser?

**Comment by snownx** [comment]
It´s fixed, thank you so much for your help and the time you invested in it!
A fresh 3.1.0-rc.2 installation is working.

**Comment by edmundoa** [comment]
Great to read that! Thank you for taking the time of reporting the issue and making sure we fixed it! :)
