### ISSUE TITLE
Graylog sends unencrypted requests to Elasticsearch every few seconds

### ISSUE THREAD

**Issue by rbeumer** [Graylog2/graylog2-server#6258]
## Expected Behavior
Graylog should only send HTTPS requests to Elasticsearch if you configure HTTPS nodes in the elasticsearch_hosts variable.

## Current Behavior
Graylog is logging that ES requests are timing out and there are errors in the webinterface:

```
2019-08-07T15:30:57.543+02:00 ERROR [Cluster] Couldn't read cluster health for indices [graylog_*] (The target server failed to respond)
2019-08-07T15:30:57.544+02:00 INFO  [IndexerClusterCheckerThread] Indexer not fully initialized yet. Skipping periodic cluster check.
2019-08-07T15:31:02.043+02:00 ERROR [IndexFieldTypePollerPeriodical] Couldn't update field types for index set <Default index set/5d495d250c6853410c5a7d01>
```
Elasticsearch complains that there is unencrypted HTTP traffic being sent to port 9200:

```
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 474554202f5f616c6c2f5f616c69617320485454502f312e310d0a436f6e74656e742d4c656e6774683a203
```
In a Wireshark capture you can see that there are two kinds of requests:

```
GET /_all/_alias HTTP/1.1
Content-Length: 0
Host: [redacted]:9200
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.4 (Java/1.8.0_222)
Accept-Encoding: gzip,deflate

GET /_cluster/health/_all?local=true&timeout=60s HTTP/1.1
Content-Length: 0
Host: [redacted]:9200
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.4 (Java/1.8.0_222)
Accept-Encoding: gzip,deflate
```
Graylog is the only application compla

## Steps to Reproduce (for bugs)
Use HTTPS in your server.conf file:

```
elasticsearch_hosts = https://graylog:password@node1:9200,https://graylog:password@node2:9200,https://graylog:password@node3:9200
```

## Context

Graylog is not functional at the moment

## Your Environment

* Graylog Version: 3.0.2
* Elasticsearch Version: 6.8.2
* MongoDB Version: 3.6.3
* Operating System: Ubuntu 18.04
* Browser version: Latest Firefox

**Comment by bernd** [comment]
@rbeumer Thank you for the report!

Do you have `elasticsearch_discovery_enabled = true` in your Graylog config file by any chance?
That might be the issue because the Elasticsearch client is using the nodes list provided by the Elasticsearch server in that case. And that list of nodes is probably not using `https://` URLs.

**Comment by rbeumer** [comment]
I don't have access to the server right now but it seems that it is enabled. I use the Ansible role which defaults to true:

`./roles/Graylog2.graylog-ansible-role/defaults/main.yml:graylog_elasticsearch_discovery_enabled:                True`

So I should disable it and list all my ES hosts in the Graylog configuration? Weird that Elasticsearch doesn't advertise with `https://`, is there a way to verify the exact URL?

**Comment by rbeumer** [comment]
So it seems to work if I disable discovery. I understand that this is expected behavior at the moment, but shouldn't Graylog support discovery with authentication?

**Comment by bernd** [comment]
@rbeumer Thanks for the update!

To make this work, we have to make the URL scheme configurable for discovered nodes. The default is `http` and we currently don't have an option to change that to `https`.

I will create another ticket for this. Until we add a configuration option for the URL scheme, you have to list all your Elasticsearch nodes in `elasticsearch_hosts` as a workaround.

**Comment by bernd** [comment]
@rbeumer Please follow https://github.com/Graylog2/graylog2-server/issues/6280 for updates on this.

**Comment by rbeumer** [comment]
Thank you, I will close this issue
