### ISSUE TITLE
Is route_to_stream documented incorrectly?

### ISSUE THREAD

**Issue by gorbunovav** [Graylog2/graylog2-server#6259]
The documentation page describes arguments this way:
https://docs.graylog.org/en/latest/pages/pipelines/functions.html#route-to-stream 

`route_to_stream(id: string | name: string, [message: Message], [remove_from_default: boolean])`

(so there is only one argument for the stream identification)
it also contains examples supporting this way of usage.

But the "Rules quick reference" section in the Rule editor describes the syntax differently:

`route_to_stream([name], [id], [message], [remove_from_default]) : Void`

(there are two arguments now - one for the name and one for the id)

From my experience, only the second variant works.

#### My Environment

* Graylog 3.0.0+db6cf59 on 183a1a5b6ff1 (Oracle Corporation 1.8.0_181 on Linux 4.14.101-91.76.amzn2.x86_64)

**Comment by mehrenreich** [comment]
Made some tests routing test messages into several streams:

1. Created two inputs:

    - Random HTTP Message Generator: `override_source: host-1`
    - Random HTTP Message Generator: `override_source: host-2`

2. Created pipeline and according rule:

```
rule "route messages from host-1 to stream"
when
    to_string($message.source) == "host-1"
then
    // route_to_stream(id: "5d5151c9e64ada000fbb1ef8"); // works
    // route_to_stream(name: "host-1");                 // works
    // route_to_stream("host-1");                       // works
    // route_to_stream("5d5151c9e64ada000fbb1ef8");     // does not work
   
   // route_to_stream(id: "5d5151c9e64ada000fbb1ef8", name: "host-1"); // works
   // route_to_stream(id: "5d5151c9e64ada000fbb1ef8", name: "host-2"); // works -> host-1 stream
   // route_to_stream(name: "host-2"); // works
end
```

I'm gonna change the documentation.

**Comment by mehrenreich** [comment]
Inline documentation inside the quick reference must also be updated.

**Comment by bernd** [comment]
Using `route_to_stream("5d5151c9e64ada000fbb1ef8")` does not work because the current implementation is parsing it into the `name` parameter instead of the `id` parameter.

This is because the code doesn't know what parameter it is and falls back to the declaration order in the descriptor. There `nameParam` is declared before the `idParam`.

```java
return FunctionDescriptor.<Void>builder()
                .name(NAME)
                .returnType(Void.class)
                .params(of(
                        nameParam,
                        messageParam,
                        removeFromDefault))
                .description("Routes a message to a stream")
                .build();
```

In that case, the code should probably first check if it's an ID by using `streamCacheService.getById(id)` and then if it's a name by using `streamCacheService.getByName(name)`. Not sure if there is a better way.

**Comment by bernd** [comment]
We looked at this again and decided to fix the documentation. The code works as documented and is not broken.

When not using the named parameters, the first parameter is the `name` and not the `id`.
```
route_to_stream([name], [id], [message], [remove_from_default]);
```

So this will work:

```
route_to_stream("<name>");       // route to stream by name
route_to_stream(name: "<name">); // same as above
route_to_stream("", "<id>");     // route to stream by ID
route_to_stream(id: "<id>");     // same as above
```
The current documentation on docs.graylog.org is wrong and we will fix that.
