### ISSUE TITLE
Graylog does not recognize Group membership 

### ISSUE THREAD

**Issue by profhase** [Graylog2/graylog2-server#6273]
Users are not assigned to groups while they should. Probably a recognition problem.

When I try to login test in auth management, I get:

```
User's LDAP attributes

fhggender
    m
fhgmailalias
    me@mymail.de
groupmembership
    cn=mygroup1,ou=Groups,ou=Resources,ou=myou,o=myorg,c=DE, cn=mygroup3,ou=Groups,ou=Resources,o=myorg,c=DE, cn=mygroup2,ou=Groups,ou=Resources,ou=myou,o=myorg,c=DE
mail
    me@mymail.de
telephonenumber
    +49 2241 14-0
ou
    myou
cn
    My Cn
l
    My City
objectclass
    inetOrgPerson, Person, fhgUser, organizationalPerson, ndsLoginProperties, Top, DirXML-ApplicationAttrs

...

User's LDAP groups

LDAP server did not return any groups for the user.
```

## Expected Behavior
I would expect graylog to map groups

## Current Behavior
```
LDAP server did not return any groups for the user.
```

## Context
We are using novell edirectory. The groups are recognized properly (so I can select them in the ldap-group mapping). 

How does graylog evaluate the group membership?

## Your Environment

* Graylog Version: 3.0.2
* Elasticsearch Version: 6.6.1
* MongoDB Version: 3
* Operating System:
* Browser version:

**Comment by allangood** [comment]
I'm using MS AD and it works as expected.
Can you clarify your setup?

**Comment by profhase** [comment]
Sorry @allangood , this one has slipped through.

Our setup: 

- We use novell eDirectory

When I try the `Login Test` within the Ldap Settings for my user, I see:

```
groupmembership
    cn=mygroup1,..., cn=mygroup2,...
```

below it shows: 
```
User's LDAP groups

LDAP server did not return any groups for the user.
```

**Comment by nltommynl** [comment]
I have the same problem. We also use NetIQ eDirectory with the groupOfNames as object schema.

LDIF example:

```
dn: cn=graylog_group,ou=support_groups,ou=services,o=idvault
objectClass: groupOfNames
objectClass: Top
cn: graylog_admin
member: cn=username,ou=support_accounts,ou=services,o=idvault
```


Does anyone have any idea why this isn't working? The same works on our OpenLDAP server 😉.

**Comment by bernd** [comment]
This should not be an issue anymore in Graylog 4.0. Please open a new issue if you still see the problem. Thank you!
