### ISSUE TITLE
Make URL scheme for discovered ES nodes configurable

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6280]
## Description

Running Graylog with `elasticsearch_discovery_enabled = true` doesn't work with TLS at the moment.

The problem is that our ES client is using a `http` URL scheme by default for discovered nodes. This results in Graylog executing HTTP requests against the ES cluster where it should use HTTPS. See #6258 for details.

Our client is actually offering a configuration option for this but we currently don't expose that to the user. To fix that we should add a `elasticsearch_discovery_default_scheme` option to the Graylog config file that takes two possible values, `http` and `https`.
See [ClientConfig](https://github.com/graylog-labs/Jest/blob/1198ac83a504b50eab32a2514a8105b51ad6f14b/jest-common/src/main/java/io/searchbox/client/config/ClientConfig.java#L280) for the client option.

**Comment by gimmic** [comment]
Something related to this I also recently noticed. Is the discovered list of ES nodes always static? If so, the graylog nodes should randomize the order so that the first N hosts in the list are not slammed by every single graylog node.

**Comment by bernd** [comment]
This has been implemented in #6315 and will be part of the upcoming 3.2.0 release.
