### ISSUE TITLE
View Actions menu is pushed outside of the browser window with long strings

### ISSUE THREAD

**Issue by tabascoterrier** [Graylog2/graylog2-server#6282]
When opening the Actions menu for a long string in a View in 3.1.0 RC2, the menu renders mostly outside of the browser window, making it essentially unusable.  It works correctly for shorter strings.

## Expected Behavior
The Actions menu should be fully visible 

## Current Behavior
The Actions menu is mostly hidden out of the browser window

![image](https://user-images.githubusercontent.com/469812/62927655-e24a7380-bdae-11e9-85d0-a59cc7cfbb97.png)

## Steps to Reproduce (for bugs)
1. Create a View
2. Expand a message that has a long string (e.g. a user agent)
3. Click the menu icon

## Your Environment
* Graylog Version: 3.1.0-5.rc.2 via the apt repository plugin
* Elasticsearch Version: 6.8.1
* MongoDB Version: 4.0.10
* Operating System: Ubuntu 18.04
* Browser version: Firefox 68.0.1 and Chrome 76, both on macOS

**Comment by linuspahl** [comment]
Thank you again for reporting this problem. We have fixed this issue (https://github.com/Graylog2/graylog2-server/pull/7305) and released the changes with 3.2
