### ISSUE TITLE
Allow Multiple Roles Per LDAP Group Mapping

### ISSUE THREAD

**Issue by reighnman** [Graylog2/graylog2-server#6296]
In order to use a role such as "Views User" in addition to a custom role mapping, I have to create 2 separate groups and join the user to both.  Ideally this could be accomplished with 1 AD group if it was possible to tie it to more than 1 role.

Optionally you could add system roles/functions such as views and admin within the configuration of a group mapping, rather than their own roles.

## Expected Behavior
When configuring LDAP mappings, I should be able to specify more than 1 role per group.

## Current Behavior
Only 1 role is allowed per group mapping.

## Context
When provisioning users for the system, they have to be added to a generic group to grant them "Views" in addition to a team/department specific group that grants them access to their streams.

## Your Environment

3.1.0rc2

**Comment by reighnman** [comment]
https://i.imgur.com/LlIYgc5.png

**Comment by bernd** [comment]
LDAP group support is working differently now in 4.0. Closing this issue.

See the following links for more details:

- Announcement: https://www.graylog.org/post/announcing-graylog-v4-0
- Upgrade notes: https://docs.graylog.org/en/4.0/pages/upgrade/graylog-4.0.html
- Background information regarding group changes: https://github.com/Graylog2/graylog2-server/issues/9392#issuecomment-733892973
