### ISSUE TITLE
Regex not working when searching for java stacks

### ISSUE THREAD

**Issue by ayousseff** [Graylog2/graylog2-server#630]
Hi Team,

Thank you for this great tools, i have a problem when adding a regex filter of type java stack to a stream.
the message is the below

murex.apps.middleware.client.core.server.connection.engine.impl.distant.DistantClientConnection$ClientConnectionRemoteHandler.invoke(DistantClientConnection.java:137)
at $Proxy0.call(Unknown Source)

i need to filter on murex.apps.middleware , i used many regex but it is not working.
can you guys help me to find the correct regex to be used within the stream.

Regards,
Anthony

**Comment by bernd** [comment]
Graylog does not support searching via regex yet. You can create a new stream with a regex stream rule to route all stack traces into a stream. Then you can use that stream to only search in those exceptions.
