### ISSUE TITLE
/api/api-browser not loading with "Access-Control-Allow-Origin header contains multiple values" error

### ISSUE THREAD

**Issue by fungusakafungus** [Graylog2/graylog2-server#6303]
When following the "API browser" link for one of the nodes from /system/nodes, the api browser only loads partially, and the following is shown in the console:

> Access to XMLHttpRequest at 'https://graylog-xxx.xxx.com/api/api-docs' from origin 'http://10.10.10.10:9000' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, http://10.10.10.10:9000', but only one is allowed.
> api-browser:43 Unable to Load SwaggerUI
> api-browser:44 Can't read from server.  It may not have the appropriate access-control-origin settings.

## Expected Behavior
api browser loads

## Current Behavior
api browser doesn't load

## Possible Solution
Might be related to CORS headers being set in those two places:
https://github.com/Graylog2/graylog2-server/blob/740146ffa4af0eef3d4bb975a5c9b8cb7fd3f3f6/graylog2-server/src/main/java/org/graylog2/shared/rest/CORSFilter.java#L41
https://github.com/Graylog2/graylog2-server/blob/20ab7325eb82ec09c08ece0433e183412f32a05d/graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java#L107

## Steps to Reproduce (for bugs)
Setup graylog with a loadbalancer: a node at http://10.10.10.10:9000 and a LB at https://graylog-xxx.xxx.com

```
$ curl -v -HOrigin:http://10.10.10.10:9000/api/api-browser -s https://graylog-xxx.xxx.com/api/api-docs 2>&1 | grep access-control-allow-origin
< access-control-allow-origin: *
< access-control-allow-origin: http://10.12.64.85:9000/api/api-browser
```

## Your Environment

* Graylog Version: Graylog 3.0.2+1686930
* Elasticsearch Version: 6.8.1
* Browser version: MacOS X, Google Chrome Version 75.0.3770.100

**Comment by fungusakafungus** [comment]
Relevant config:
```
http_publish_uri = http://10.10.10.10:9000/ # node
http_external_uri = https://graylog-xxx.xxx.com/ # loadbalancer
```

Or is `http_external_uri` meant to be the external uri for this particular **node**? Not clear in the docs.

**Comment by dennisoelkers** [comment]
This is fixed in recent Graylog versions.
