### ISSUE TITLE
Problems with Views sidebar fields list being based on stream, not result set

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#6317]
The list of fields in the Views sidebar is based on the fields that are in all messages of a stream.

I have run into two problems with that when working against the "All Messages" stream that can contain a lot of different message types:

### Too many fields

It can simply lead to having too many fields. I'm sending all my syslog into the "All Messages" stream so it contains regular syslog, UFW and auditd logs. This leads to a humongous field list even after using a query to narrow down the result set to only UFW logs.

This was working better on the old search page.

### Inaccurate field types

In the same scenario as above, when selecting the "All Messages" stream and narrowing down the result set to only UFW logs using a query, I can't build a chart over the `length` field because it's marked as `compound(long,string)` because another log type in the same stream sends it as a string. However, all my UFW logs (all logs in the result set) have this field as a `long` so I should actually be able to build a chart.

Workaround is to create different streams and that would work for my UFW example, but the current behaviour is still confusing.

**Comment by dennisoelkers** [comment]
There are two issues in this one:

  1.) *Too many fields*: adding back showing only fields of the current search result is a duplicate.
  2.) *Inaccurate field types*: Tracked in #7507.

Closing this issue in favor of the two others.
