### ISSUE TITLE
Add JSON converter

### ISSUE THREAD

**Issue by 2ion** [Graylog2/graylog2-server#632]
For extracting information from log messages which contain JSON and might appear in logged query URLs and similar data, a JSON extractor would be useful.

**Comment by zacharyrankin** [comment]
:+1:

**Comment by jmyounker** [comment]
The number one requirement for our logging repository is that it can extract json from one field, and then index the json attributes as fields.  Despite all the pluses in Graylog's favor, we're choosing logstash because it can do this one thing.
