### ISSUE TITLE
API request for a day logging gives a timeout

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#633]
Hi,

I want to get one day of logging from the API in JSON with /search/universal/relative?query=*&range=86400 but this gives an timeout (good). But where can i change the timeouts?

**Comment by bernd** [comment]
Do you get a timeout from your http client or in the response from the server?

I am closing this because it is pretty old. Please re-open the ticket if you still have problems with this in Graylog 1.0.0. Thank you!
