### ISSUE TITLE
sidecar for data in and out

### ISSUE THREAD

**Issue by loveyang2012** [Graylog2/graylog2-server#6330]
Hello Mates,
  I have two problems：
 1. when I startup the graylog-server，I get a warning like this :
  _### WARN  [AbstractTcpTransport] receiveBufferSize (SO_RCVBUF) for input Beats2Input{title=Beats Input, type=org.graylog.plugins.beats.Beats2Input, nodeId=null} (cha
nnel [id: 0x6f3d0dc2, L:/0.0.0.0:8044]) should be 1048576 but is 249856._####
     I have set it to 1048576 in the beat config.
2.the number of logs is too high, but,I fond the data  between  three graylog-server is not blance
 one hosts is  In 160 / Out 160 msg/s. 
 another is In 583 / Out 583 msg/s.
the last one is very high, In 15053 / Out 15000 msg/s.
how to blance it between three hosts.

**Comment by florianvolle** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
