### ISSUE TITLE
I cant search string with backslash square bracket 

### ISSUE THREAD

**Issue by zino7825** [Graylog2/graylog2-server#6331]
## Expected Behavior

if filter rule : message:\[Utilization\]

I expected below :
[Utilization] xxx xxx 

## Current Behavior

if filter rule : message:\[Utilization\]
x.x.x.x : [Utilization] xxx xxx 
x.x.x.x : utilization x xx  <-- i don't want to find line

I think graylog 3.0 does not operate escape (backslash) character 
becuase square bracket is operated like special character.

## Your Environment

* Graylog Version: 3.0.0
* Elasticsearch Version: 6.7.0
* MongoDB Version: 4.0.10
* Operating System: centos 7.6
* Browser version: chrome 75.0.3770.90

**Comment by jalogisch** [comment]
He @zino7825 

you need to escape certain characters in the search ( http://docs.graylog.org/en/3.1/pages/queries.html#escaping ) 

If this works like you wish with escaped brackets all is fine - if not we need to check if your terms might be the reason.
