### ISSUE TITLE
${event.fields.message} unable to pass through to Alert Templates

### ISSUE THREAD

**Issue by ion-storm** [Graylog2/graylog2-server#6336]
When specifying ${event.fields.message} with ${source.message}, it is not passed through to the new alerting system, and if its included at all in aggregation, the alert does not even kick off.

Specs:
Graylog 3.1 Ubuntu 18.04

**Comment by mpfz0r** [comment]
Could you give us a little more details about your configuration?
A screenshot of the fields setting on your event definition and the email template would be useful.
