### ISSUE TITLE
Double quotes are escaped

### ISSUE THREAD

**Issue by imaemo** [Graylog2/graylog2-server#6338]
## Expected Behavior

if log contains double quotes, it will be escaped, 
this is origin log
``` json
{"keys": [{"report": "rancher"}]}
```

## Current Behavior

![image](https://user-images.githubusercontent.com/11534313/63441863-ab3a2900-c464-11e9-864a-b7111542da19.png)

## Steps to Reproduce (for bugs)

1. setup fluentd, and install gelf plugin : `fluent-plugin-gelf-hs:1.0.4`
2. configure fluentd, use tail as input source, example config ,https://github.com/roffe/kube-gelf/blob/master/fluent.conf
``` json
<source>
  @type tail
  path /var/log/containers/*.log
  pos_file /pos/containers.pos
  time_key time
  time_format %Y-%m-%dT%H:%M:%S.%NZ
  tag kubernetes.*
  format json
  read_from_head true
</source>
```
3. send message 
``` bash
$ cat << EOF >  /var/log/containers/a.log
{\"keys\": [{\"report\": \"rancher\"}]}
EOF

```
4. check logs on graylog web

## Your Environment

* Graylog Version: Graylog 2.5.1+34194da 
* Elasticsearch Version: 6.7.0
* MongoDB Version: 4.1
* Operating System: docker: Oracle Corporation 1.8.0_181 on Linux 3.10.0-693.2.2.el7.x86_64
* Browser version: chrome  76.0

**Comment by mpfz0r** [comment]
> 
> ```shell
> $ cat << EOF >  /var/log/containers/a.log
> {\"keys\": [{\"report\": \"rancher\"}]}
> EOF
> ```

Well, it looks like you actually put the escapes there yourself, since they will get passed
through your here-document. (https://en.wikipedia.org/wiki/Here_document#Unix_shells)

Please try with:
> ```shell
> $ cat << EOF >  /var/log/containers/a.log
> {"keys": [{"report": "rancher"}]}
> EOF
> ```

and reopen if this is still an issue.
