### ISSUE TITLE
Allow to store source IP address as field for some inputs

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#634]
Some inputs like Syslog, Plaintext or GELF could look at the source IP address and (if enabled) store it as a field like `source_ip`.

> it's not badly required but this is good think to have. I understand that packets could be spoofed but in case this is you LAN IPs it would help to group hosts by nets.

**Comment by bernd** [comment]
Closing this because the information is available since Graylog 1.0.0.
