### ISSUE TITLE
Can't Edit Lookup Table That Has Space In Name

### ISSUE THREAD

**Issue by aaronistheman** [Graylog2/graylog2-server#6347]
## Expected Behavior

When I attempt to edit a Lookup Table that's name has a space in it, editing it should work just as fine as it would if the Lookup Table's name did not have a space in it.

## Current Behavior

When I create a Lookup Table that has a space in its name (e.g. "Reverse DNS Lookup", "Another Test Table"), I am able to use the Lookup Table, but I cannot Edit it or view its details. When I try to do either of those, I get an error message reporting the failure ("Fetching lookup table Reverse DNS Lookup failed: cannot GET https://graylog..../api/system/lookup/tables/Reverse%20DNS%20Lookup?resolve=true (400)), _and then I am taken to the Edit page for the last Lookup Table that was successfully loaded (and which thus has no space in its name)._ This error does not occur at all with Lookup Tables that are identical except for having names with no spaces (e.g. "host-names"). Moreover, this only seems to matter with the name, not the title, of the Lookup Table.

## Possible Solution

There should be some sort of indication that the Lookup Table can't have a name that has a space in it. Or, preferably, names that don't have spaces should be outright rejected in the Lookup Table creation interface.

## Steps to Reproduce (for bugs)

1. Create a Lookup Table whose name has a space in it (give it any Data Adapter or Cache, as those details shouldn't matter).
2. After creating the table, return to the Lookup Tables page and attempt to Edit the table that you just created.

## Context

I can recreate the Lookup Table with a different name, so it's not a big issue, but I believe that there should be some sort of indication that the Lookup Table can't have a name that has a space in it.

## Your Environment

* Graylog Version: free version
* Operating System: Windows 10
* Browser version: Chrome

**Comment by radykal-com** [comment]
Hi,

what version of Graylog are u using? I'm trying to reproduce the problem in latest version and all is working fine. I have lookup tables with spaces in the name and they can be edit.

**Comment by radykal-com** [comment]
Hello again,

I have been doing the same tests again with version 3.0.1 (running in docker) and it is also working.
I tried by just setting any name with spaces (beginning with a space, spaces in the middle, spaces at the end, and mixed configurations), all of them are working in the build 3.0.1, at least the one from the docker tag 3.0.1.

So I can't reproduce this issue.

Maybe if someone else can also check it and confirm, would be better.

Also I don't know if in the graylog server logs there is any entry regarding the error you are receiving.

**Comment by kmerz** [comment]
@aaronistheman I also can't reproduce the problem

![Peek 2019-08-28 16-01](https://user-images.githubusercontent.com/448763/63862916-a964ee00-c9ad-11e9-966f-302f148e2c75.gif)

Can you please take a look if there is any hint of an error in the web console (press F12 to open it).
Or in the logs of graylog itself?
