### ISSUE TITLE
Cannot read property 'query' of undefined when replaying search

### ISSUE THREAD

**Issue by viebig** [Graylog2/graylog2-server#6355]
## Expected Behavior
Be able to run queries and see messages

## Current Behavior
Impossible to show input messages, when clicking replay query from dashboard, monkey error page appear with the following message:

`
Cannot read property 'query' of undefined
Stack Trace:
TypeError: Cannot read property 'query' of undefined
    at t.Z3h2JH4w.t.getSeriesInformation (http://xxx/assets/builtins.60a2621478c6c8ca385c.js:104:99716) ....
`

## Context
Issue happened after upgrading graylog from 3.1.x to 3.1.0-6 

## Your Environment

* Graylog Version: 3.1.0-6 
* Elasticsearch Version: 6.8.2
* MongoDB Version: 4.0.12
* Operating System: Ubuntu
* Browser version: Chrome 73.0.3683.86 (Official Build) (64-bit)

**Comment by dennisoelkers** [comment]
Hello @viebig,

we need some additional help from you debugging this issue. Can you please open up the Graylog Web Interface, go to your browser's JavaScript console, type `JSON.stringify(localStorage)` and add the output to this issue?

**Comment by viebig** [comment]
Works on firefox, issue just exists with chrome.
```
"{"pinned-field-charts":"{\"q2ac8vus82039ab2nvnqa6nseh44bhnzmde2\":{\"renderer\":\"bar\",\"interpolation\":\"linear\",\"interval\":\"minute\",\"query\":\"gl2_source_input:5b2a7641eac5e70b59f98850 AND callStatus:CONGESTION AND classifierType:AMD\",\"valuetype\":\"count\",\"rangetype\":\"relative\",\"chartid\":\"q2ac8vus82039ab2nvnqa6nseh44bhnzmde2\",\"field\":\"callStatus\",\"createdAt\":1532720159374,\"range\":{\"relative\":300}},\"4ckehkcwlcrm6hr47t6knb3l5kpi2hrvibef\":{\"renderer\":\"bar\",\"interpolation\":\"linear\",\"interval\":\"minute\",\"query\":\"gl2_source_input:5b2a7641eac5e70b59f98850 AND callStatus:SILENCE AND classifierType:AMD\",\"valuetype\":\"count\",\"rangetype\":\"relative\",\"chartid\":\"4ckehkcwlcrm6hr47t6knb3l5kpi2hrvibef\",\"field\":\"callStatus\",\"createdAt\":1532720197871,\"range\":{\"relative\":300}},\"iz90mmxb8cwmlb0966z1p2u3h8kwvr5kz8o9\":{\"renderer\":\"area\",\"interpolation\":\"basis\",\"interval\":\"minute\",\"query\":\"gl2_source_input:5b2a7641eac5e70b59f98850 AND callStatus:MACHINE AND classifierType:AMD\",\"valuetype\":\"count\",\"rangetype\":\"relative\",\"chartid\":\"iz90mmxb8cwmlb0966z1p2u3h8kwvr5kz8o9\",\"field\":\"callStatus\",\"createdAt\":1532720210584,\"range\":{\"relative\":0}},\"simuhf0m9kqo03h9f78z2od2nsu8ulwhwcvc\":{\"renderer\":\"bar\",\"interpolation\":\"linear\",\"interval\":\"minute\",\"query\":\"gl2_source_input:5b2a7641eac5e70b59f98850 AND callStatus:NOANSWER AND classifierType:AMD\",\"valuetype\":\"count\",\"rangetype\":\"relative\",\"chartid\":\"simuhf0m9kqo03h9f78z2od2nsu8ulwhwcvc\",\"field\":\"callStatus\",\"createdAt\":1532720187318,\"range\":{\"relative\":0}}}","sessionId":"\"ff229fbd-3011-4ecc-aa79-df057d932a18\"","stacked-graphs":"{\"iz90mmxb8cwmlb0966z1p2u3h8kwvr5kz8o9\":[\"3q22jpcjvflghly48bqth8yk0a6t3rpgf64k\",\"q2ac8vus82039ab2nvnqa6nseh44bhnzmde2\",\"hltj85691y3rm04vtni1oi9rby5w4ojhjiwp\",\"simuhf0m9kqo03h9f78z2od2nsu8ulwhwcvc\",\"4ckehkcwlcrm6hr47t6knb3l5kpi2hrvibef\"]}","username":"\"admin\""}"
```

**Comment by dennisoelkers** [comment]
@viebig: This is an issue in `3.1.0`/`3.1.1`. It seems like a stacked graph on the search page has lost some of its subgraphs. Do you have any idea how this could have happened?

We are addressing this in one of the next versions (`3.1.2`, if we are fast enough with the fix). For now you can enter the following command in your browser's JS console while being on the Graylog web if, to restore your search page:

```
delete localStorage['stacked-graphs']
```
This will remove the erroneous stacked graph and restore the remaining individual graphs, which you can stack again.
