### ISSUE TITLE
Logging: Separate Graylog Server from Index Failure Logs

### ISSUE THREAD

**Issue by shakalandy** [Graylog2/graylog2-server#6358]
To make Index Failure Debugging and Graylog internal debugging a bit easier it would be great to have separate logfiles for index failures and graylog internal stuff.
If you have a application logging going frenzy you're not able to identify upcoming errors in graylog itself anymore.
Maybe this could be done via log4j extension and be used as a lightweight solution for #4578 

## Expected Behavior
Have separated logfiles for all graylog internal logging and index failures.

## Current Behavior
All errors go to one logfile

## Possible Solution
provide possibility to configure this via log4j

## Context
Not be able to debug a graylog error resulting from an application logging going frenzy and flodding the logfile

## Your Environment

* Graylog Version: 3.0.2-1
* Elasticsearch Version: elasticsearch-6.8.1-1
* MongoDB Version: mongodb-server-2.6.12
* Operating System: RHEL 7
* Browser version: Chrome 75

**Comment by boosty** [comment]
We added a related feature in Graylog 4.2 (available in [Graylog Operations](https://www.graylog.org/products/operations) and [Graylog Cloud](https://www.graylog.org/products/cloud)):

https://docs.graylog.org/docs/indexer-and-processing-failures

It allows for storing indexing and processing failure notifications in a dedicated Elasticsearch/OpenSearch failure index. With a dedicated stream for such failure notifications, these messages can be logged and aggregated meaningfully into a dashboard, used to set up alert notifications, and more. It is also possible to keep the full original message that failed.
