### ISSUE TITLE
Grok patterns break processing

### ISSUE THREAD

**Issue by ArnY** [Graylog2/graylog2-server#6371]
I am using a 3 node graylog cluster, with a 3 node ES cluster. All 6 nodes are working properly and are healthy indexing between 5 and 10G messages per day.
I am trying to process logs from amavisd-new (spamassassin/av interface for mailers). I am adding a new grok patterns extractor on my syslog input (~125 msg/s). The new extractor only matches 1 or 2 messages per second:

The extractor:
```
Condition
    Will only attempt to run if the message includes the string spam-tag
Configuration
    grok_pattern: %{SYSLOGHOST}%{SYSLOGPROG}: %{AMAVIS_SA_RESULT}
    named_captures_only: 
```

The Grok patterns:
```
AMAVIS_SA_RESULT	\(%{DATA:amavis_thread}\) spam-tag, <(?:%{DATA:amavis_sender})?> -> <(?:%{EMAILADDRESS:amavis_recipient})?>(%{AMAVIS_RECIPIENT_LIST})?, %{AMAVIS_YES_NO:amavis_sa_spamtag}, score=(%{DATA:amavis_sa_score}|x) tagged_above=%{NOTSPACE} required=%{NOTSPACE} (%{WORD} )?tests=(\[(%{AMAVIS_SA_TEST_LIST})?\])
EMAILADDRESS	%{EMAILLOCALPART}@%{EMAILDOMAINPART}
EMAILDOMAINPART	\b(?:[0-9A-Za-z][0-9A-Za-z-]{0,62})(?:\.(?:[0-9A-Za-z][0-9A-Za-z-]{0,62}))*(\.?|\b)
EMAILLOCALPART	[a-zA-Z][a-zA-Z0-9_.+-=:]+
AMAVIS_RECIPIENT_LIST	(,<%{EMAILADDRESS:amavis_recipient}>)+
AMAVIS_SA_TEST_LIST	%{WORD:amavis_sa_test}=%{DATA}(, %{WORD:amavis_sa_test}=%{DATA})*
AMAVIS_YES_NO	(?:Yes|No)
```
Message example:

```
(13498-03) spam-tag, <ChloéAncaruo@1015thehawk.com> -> <xxxxx@xxxxx.com>, Yes, score=11.078 tagged_above=-1000 required=5 tests=[CRM114_UNSURE=0.1, FROM_EXCESS_BASE64=0.105, FSL_BULK_SIG=0.001, HTML_IMAGE_ONLY_12=1.629, HTML_IMAGE_RATIO_08=0.001, HTML_MESSAGE=0.001, HTML_SHORT_LINK_IMG_2=0.259, MIME_HTML_ONLY=1.105, MR_NOT_ATTRIBUTED_IP=0.2, NO_RDNS=0.5, RAZOR2_CF_RANGE_51_100=0.1, RAZOR2_CF_RANGE_E8_91_100=0.1, RAZOR2_CHECK=0.1, RDNS_NONE=1.274, SERGIO_SUBJECT_PORN014=3.544, T_REMOTE_IMAGE=0.01, UN_PHISHING_PW=0.1, URIBL_ABUSE_SURBL=1.948, URIBL_BLOCKED=0.001] autolearn=disabled
```

## Expected Behavior
graylog should process messages as usual, spiting the messages into named fields.

## Current Behavior
The process buffer on all 3 node fills up and the output buffer stays empty. Input buffer then starts to fill up too and nothing gets processed anymore. The problem occurs with graylog 3.0 and graylog 3.1.

Extractor's stats:
```
Total time

95th percentile:
    9μs
98th percentile:
    16μs
99th percentile:
    228μs
Standard deviation:
    121μs
Mean:
    10μs
Minimum:
    0μs
Maximum:
    4,941μs

Condition time

95th percentile:
    2μs
98th percentile:
    2μs
99th percentile:
    2μs
Standard deviation:
    0μs
Mean:
    1μs
Minimum:
    0μs
Maximum:
    17μs

Execution time

95th percentile:
    420μs
98th percentile:
    468μs
99th percentile:
    468μs
Standard deviation:
    77μs
Mean:
    296μs
Minimum:
    135μs
Maximum:
    10,828μs

Converter time

95th percentile:
    0μs
98th percentile:
    0μs
99th percentile:
    0μs
Standard deviation:
    0μs
Mean:
    0μs
Minimum:
    0μs
Maximum:
    68μs
```
**Removing the extractor does not fix the problem**. After removing the extractor, if I restart  graylog-server on a node, it will then process normally the disk journal (up to 3000msg/s of ouput) and everything goes back to normal.

If i leave the extractor and reboot the server, the output buffer fills up and 65536 messages get processed and the next 64535 messages are stuck in the process buffer.

There are no errors in the logs...

* Graylog Version: 3.0 and 3.1
* Elasticsearch Version: 6.5.4
* MongoDB Version: 4.0.12
* Operating System: debian stretch 9.9
* Browser version: Not revelant

**Comment by dennisoelkers** [comment]
@ArnY: Thanks for reporting this. I do not understand the last paragraph. What happened when you removed the extractor without restarting the server? I would expect it to finish processing the current messages in the processing processors (not the buffer) and then continue processing the process buffer without using the extractor. Depending on the current state it would take a little bit (What is the runtime of the GROK pattern for a single message?) before processing all currently processed messages using the extractor are finished and it can move on.

**Comment by ArnY** [comment]
@dennisoelkers When I remove the extractor , the process queue stays at 100% and the internal journal keeps growing, the output queue stays empty. When I remove the extradoc and restarts the graylog nodes, it quickly purge the internal journal at about 3000 msg/s which is what I would expect to happen as soon as I remove the extractor. 

I can try to remove the pattern and let graylog processs enqueued messages in the processor and see how long it takes, if it ever does.

But the grok pattern isn't that complex and shouldn't take more than a few μs to process a message (i'm using way more complex patterns for postfix and with a lot more messages without troubles)... I thought that's it was the extractor stats were about though.

**Comment by ArnY** [comment]
Hello @dennisoelkers,

I just re-tested. Added the grok pattern extractor to my input, waited a little while, noticed the 3 nodes' process buffer were full and nothing was processed anymore then removed the extractor. Processing seems to be completely stopped:

![Screenshot_2019-10-23 Graylog - Node fb97910b graylog1 cprv univ-nantes prive](https://user-images.githubusercontent.com/138363/67398858-9a647b80-f5ab-11e9-8ef9-26014c62f2b0.png)

I'll wait a few hours but I doubt graylog will suddently start reprocessing messages all a suddent.

I upgraded to graylog 3.1.0 a few weeks go but it apparently didn't fix anything.

Arnaud

**Comment by ArnY** [comment]
Hello,

I can confirm that, after 19 hours, nothing was processed since I removed the extractor. The process queue is still full, Graylog warns me that journal utilization is too high and that uncommited messages were deleted from journals.

Reboting the nodes fixes the problem as stated before.

Arnaud

**Comment by bernd** [comment]
@ArnY I tried to reproduce the issue with the information you have given us but I wasn't able to do so, unfortunately.

The grok extractor configuration you showed us was using `%{SYSLOGHOST}%{SYSLOGPROG}: %{AMAVIS_SA_RESULT}` as `grok_pattern` config. Your example message didn't include anything that could be matched by the `%{SYSLOGHOST}%{SYSLOGPROG}: ` part of the `grok_pattern` config, though. So in my test it didn't match the message you provided. I removed the `%{SYSLOGHOST}%{SYSLOGPROG}: ` part from the `grok_pattern` config and the message matched and information got extracted. So far so good. For the example message you showed us, the grok extraction was also pretty fast.

You are basically describing two problems here:

1. With the grok pattern configured in an input your message rate goes down
1. Removing the extractor from an input apparently doesn't actually remove it

I wasn't able to reproduce any of the two problems. :confused: 

To be able to debug this further we need the following things from you:

1. The graylog server log file that includes logs from the time your processing was slow and you removed the extractor from the input (it should have something like `Deleted extractor <ed5ee500-f759-11e9-8bc9-5e44551079b0> of type [GROK] from input <564dcd12c830e40a3ba4b743>.`)
1. The JSON output of the following commands executed on one of your graylog servers:
    - `curl -s -u admin localhost:9000/api/system/grok`
    - `curl -s -u admin localhost:9000/api/system/inputs/<input-id>/extractors` (make sure to replace the `<input-id>` placeholder with the ID of the related input)
1. Some example messages that include the parts that should be matched by `%{SYSLOGHOST}%{SYSLOGPROG}: ` in your example `grok_pattern` config of the extractor

Thank you!

**Comment by ArnY** [comment]
Hello @bernd 

Here are the debug infos you asked for:
- grok-before.json.txt and extractor-before.json.txt are the apis while the extractor was still active and the processing stuck
- grok-after.json.txt and extractor-after.json.txt were done after I removed the extractor
- graylog1.log is the log files listing everything from the 3 nodes except the lines about a beats input that isn't responding there were hundred of those and they are unrelated.



[graylog1.log](https://github.com/Graylog2/graylog2-server/files/3782544/graylog1.log)

[extractor-after.json.txt](https://github.com/Graylog2/graylog2-server/files/3782546/extractor-after.json.txt)
[extractor-before.json.txt](https://github.com/Graylog2/graylog2-server/files/3782547/extractor-before.json.txt)
[grok-after.json.txt](https://github.com/Graylog2/graylog2-server/files/3782548/grok-after.json.txt)
[grok-before.json.txt](https://github.com/Graylog2/graylog2-server/files/3782549/grok-before.json.txt)

**Comment by ArnY** [comment]
If i use the following extractor 
```
%{SYSLOGHOST} %{SYSLOGPROG}: \(%{DATA:amavis_thread}\) spam-tag, <(?:%{DATA:amavis_sender})?> -> <(?:%{EMAILADDRESS:amavis_recipient})?>((,<%{EMAILADDRESS:amavis_recipient}>)+)?, %{DATA:amavis_sa_spamtag},
```

The problem doesn't occur...

**Comment by ArnY** [comment]
Hello,

I kind of gave up graylog for a while and went back a few weeks ago. Upgraded to graylog server 4.0.1 and the problem still occurs. I added by amavis extractor.. It worked a few minutes before one of our graylog nodes' processing buffer filled up to 100% while i ts output buffer stalled at 0%. I removed the input from this node and moved it to another one... as expected, that node also stopped outputing messages after a few minutes.

**Comment by ArnY** [comment]
I did some more testing, suspecting it could come from a recursion or something in my amavis grok patterns, I added a "standalone" pattern that does not depends on other patterns, except default ones:
```
%{SYSLOGHOST} %{SYSLOGPROG:SYSLOGPROG}: \(%{DATA:amavis_thread}\) spam-tag, <(?:%{DATA:amavis_sender})?> -> <(?:%{EMAILADDRESS:amavis_recipient})?>((,<%{EMAILADDRESS:amavis_recipient}>)+)?, %{AMAVIS_YES_NO:amavis_sa_spamtag}, score=(%{DATA:amavis_sa_score}|x) tagged_above=%{NOTSPACE} required=%{NOTSPACE} (%{WORD} )?tests=(\[(%{DATA:amavis_sa_tests})?\])
```
after 30 minutes, the problem occured.

**Comment by ArnY** [comment]
I have reduced my extractor to 

%{SYSLOGHOST} %{SYSLOGPROG:SYSLOGPROG}: %{GREEDYDATA}, %{AMAVIS_YES_NO:amavis_sa_spamtag}, %{GREEDYDATA}

and that works. The problem is definitely grok related.

**Comment by ArnY** [comment]
I've finally identified the problem. Amavis can log long lines which are trunkated by the syslog. For example:

mx3.univ-nantes.fr/amavis.log:Apr  8 11:57:08 mx3.univ-nantes.fr amavis[28988]: (28988-08) Passed CLEAN {RelayedInternal}, MYNETS LOCAL [172.20.12.55]:44132 [193.52.101.135] <email1@domain1.tld> -> <email1@domain2.tld>, <email1@domain1.tld> -> <email1@domain2.tld>, <email1@domain1.tld> -> <email1@domain2.tld>, <email1@domain1.tld> -> <email1@domain2.tld>, <email1@domain1.tld> -> <email1@domain2.tld>, <email1@domain1.tld> -> <email1@domain2.tld>,Queue-ID: 0801841147BE,...

That extractor  <(?:%{DATA:amavis_sender})?> -> <(?:%{EMAILADDRESS:amavis_recipient})?> ((,<%{EMAILADDRESS:amavis_recipient}>)+) actually makes graylog choke on the trunkated log lines...

**Comment by bernd** [comment]
@ArnY Thanks for the update! :pray: Unfortunately, I think we cannot do much about messages truncated by the sender.

In Graylog 4.2, we improved the processing error handling a lot, so I think this error shouldn't block processing anymore. I will close the issue. Please re-open if you still see the problem with Graylog 4.2 or newer. Thank you!
