### ISSUE TITLE
Reimplement surrounding search for views

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#6408]
Requires:
  - stream set can be passed in URL to search page

**Comment by jalogisch** [comment]
we should consider to have the time you are able to select as "surrounding search" configurable in a very granular way. Like microseconds and seconds should be possible.

**Comment by kroepke** [comment]
For 3.2 the simplest way of achieving this would be to open a new browser tab with a search page configured according to the parameters:
 * the chosen time range (absolute range +/- around the original message)
 * the query as it was constructed in 3.1 and earlier:
   * the global configuration listed fields that, if present in the original message, were added to the new search query
 * the new search page opens with the standard widget configuration of the histogram and message table
 * the selected streams are also used in the new search page
 * the original message should be highlighted so it can be identified

Even dashboards, although they could technically create a second widget on the dashboard, should for now open this in a new search page.

If there are other improvements (per-dashboard configuration of fields, sort orders, custom time ranges etc.) we will consider them for 3.3 and following releases.

**Comment by dennisoelkers** [comment]
Refs #2532.

**Comment by dennisoelkers** [comment]
Refs #2793.

**Comment by dennisoelkers** [comment]
Fixed in #7612, #7616.
