### ISSUE TITLE
cluster_id is not re-generated on restart of graylog-server services

### ISSUE THREAD

**Issue by waynekearns** [Graylog2/graylog2-server#6414]
## Expected Behavior
In previous versions of Graylog, when a particular attribute was deleted it would be re-created on restart of the service. This feature is taken advantage of by users to recycle the default Graylog configuration in MongoDB. 

## Current Behavior
If the document _org.graylog2.plugin.cluster.ClusterId_ is deleted, it does not get generated on restart of Graylog. Instead it throws the error:

**Caused by: java.lang.IllegalStateException: Missing or empty Cluster ID. This should not happen**

## Steps to Reproduce (for bugs)
1. Stop Graylog (systemctl stop graylog-server) - if multipe in the cluster, stop all of them
2. Delete the UUID ( mongo graylog --eval 'db.cluster_config.deleteMany({"type":"org.graylog2.plugin.cluster.ClusterId"});'  )
If needed adjust the MongoDB settings of the database and connection.
3. Start Graylog ( systemctl stop graylog-server ) - if multiple, start the master first.
4. Check if Graylog is starting in the Graylog server.log and after a while, you can log in to the web interface and see the new cluster ID 

## Context
The process above is used to allow a mongodump to be used populate similar environments (Prod/Dev) while using a different license for each environment. 

## Your Environment

* Graylog Version: 3.0.2, 3.1.0, 3.1.1
* Elasticsearch Version: 6.8.2, 6.7.2
* MongoDB Version: 4.0.12, 4.0.9
* Operating System: Archlinux :D
* Browser version: Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by bernd** [comment]
The cluster ID gets regenerated automatically if it doesn't exist. The issue here is probably that the cluster ID generation is happening asynchronously and thus happening only after some services already needs it:

https://github.com/Graylog2/graylog2-server/blob/2276c836cb1bb89070f3fdc519023a08dabd4313/graylog2-server/src/main/java/org/graylog2/periodical/ClusterIdGeneratorPeriodical.java#L80-L85

We have one improvement task planned for 3.2.0 that will address this issue as well.

**Comment by nilanjanH** [comment]
@waynekearns - Would love to work on this issue. I am new to OSS & this would be my first contribution, so any pointers[if I am assigned this issue] would also be very much appreciated.

Thanks.

**Comment by bernd** [comment]
We now generate the cluster-ID in one of the first database migrations. This should fix any potential race conditions.
