### ISSUE TITLE
Plaintext View & Export of content of `message` field with pagination

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#6439]
## Context
If you like to simulate a *good old logfile* with the content of the field message - because your brain needs that. Or you have the need to have the content of the message field like it would look like on a server to be exported for 3rd party tools/usage it would be good to have the ability to show the content of `message` only, ordered by timestamp.

That is truly edge use case but special in corporate environment you will have the `message` field untouched like it looks on the server plus you need to be able to copy that content in a batch over to other system and tools. 

It is very similar to a data-view in the extended search but should have the options to copy/paste like in a text field.

## Your Environment

* Graylog Version: 3.1

**Comment by dennisoelkers** [comment]
There is now a plain text export format available.
