### ISSUE TITLE
Changing query tab titles in views

### ISSUE THREAD

**Issue by Behzadb** [Graylog2/graylog2-server#6443]
Currently, It is not possible to change query titles in a view. It would be helpful if we can change tiltle for each tab. I saw in a recent webinar that tabs have custome titles, however I wonder if it was an enterprise feature or it's just a bug in CE.

## Possible Solution
Adding a option to tab dropdown to change its title like the remove option.

## Your Environment
* Graylog Version: 3.1.0

**Comment by jalogisch** [comment]
You need to double click on the query tab name and change the name of the tab. 


We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
