### ISSUE TITLE
Graylog 3.1 is not honoring java security options for collector inputs

### ISSUE THREAD

**Issue by ion-storm** [Graylog2/graylog2-server#6444]
I hava Java security options set to disable TLS 1.0/1.1 for the beats inputs only.
jdk.tls.disabledAlgorithms=SSLv2Hello, SSLv3, TLSv1, TLSv1.1, EC keySize < 160, RSA keySize < 2048, DSA keySize < 2048
jdk.certpath.disabledAlgorithms=MD2, MD4, MD5, EC keySize < 160, RSA keySize < 2048, DSA keySize < 2048

Graylog 3.1 instance is not honoring the settings, the Graylog 2.5.2 instance allows TLS 1.1/1.2 to be disabled.

**Comment by mpfz0r** [comment]
Could be related to https://github.com/Graylog2/graylog2-server/pull/5216

**Comment by mpfz0r** [comment]
> Could be related to #5216
Red herring. It got broken with 3.0 when we introduced netty 4 with an OpenSSL backend.

**Comment by mpfz0r** [comment]
As a workaround, you can configure `transport_netty_tls_provider = jdk` in your `graylog.conf`
This way the inputs won't be using openssl.

**Comment by ion-storm** [comment]
thanks for the workaround

**Comment by bernd** [comment]
We will introduce a new `enabled_tls_protocols` config file option to make this configurable across the product in the upcoming 3.2 release.
