### ISSUE TITLE
JobSchedulerService "Couldn't execute next scheduler loop iteration" on non-master

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#6451]
After upgrading from 3.0.2 to 3.1.2 we see the following logged every second for the 1 non-master node in this cluster:

```
2019-09-16T13:45:14.378-05:00 INFO  [JobSchedulerService] Couldn't execute next scheduler loop iteration. Waiting and trying again.
```

* This message is not logged on the master node
* The master node is the only one with `is_master = true`
* A restart (of either node) makes no difference
* Each node has a unique ID in `/etc/graylog/server/node-id`
* Message processing doesn't seem to be impacted

## Expected Behavior

Clean upgrade from 3.0.2 to 3.1.2.

## Current Behavior

The [job scheduler](https://github.com/Graylog2/graylog2-server/blob/3.1/graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerService.java#L82) seems to have started on a non-master node?

## Steps to Reproduce (for bugs)

1. Have a 3.0.2 cluster (packages installed via repo+`yum`) with 1 master node and 1 non-master node
    * Plugins: AWS plugins, Collector, Enterprise Integrations, Graylog Enterprise, Integrations, Threat Intelligence Plugin
2. Remove the 3.0 repo on the master node
3. Add the 3.1 repo to the master node
4. Install version 3.1.2-1 of `graylog-server` (and aforementioned plugins) on the master node
5. Restart `graylog-server` on the master node
6. Repeat 2-5 for the non-master node

## Context

Attempting to roll out 3.1.x.

## Your Environment

* Graylog Version:  3.1.2
* Java Version:  AdoptOpenJDK 1.8.0_222
* Elasticsearch Version:  6.6.2-1
* MongoDB Version:  4.0.6-1
* Operating System:  RHEL 6.9

**Comment by mpfz0r** [comment]
This can happen, if you installed the enterprise plugin, but either don't have a vaild license,
or exceeded your license.

**Comment by coffee-squirrel** [comment]
@mpfz0r Thanks, that matches up.  This particular lower environment has the Enterprise plugins (as [the default behavior of the Chef cookbook](https://github.com/Graylog2/graylog2-cookbook/blob/3.0.2/attributes/default.rb#L7-L8)) but does not have a license applied.

Are there plans to change this behavior, or should we just exclude the plugins whenever there won't be a license (or a valid license) applied?

**Comment by mpfz0r** [comment]
I guess the least we should do is reduce the amount of log messages this creates right now.

**Comment by coffee-squirrel** [comment]
We rolled 3.1.2 out to an environment with a valid Enterprise license and (as expected based upon the earlier comment) don't see the message logged on non-master nodes.
