### ISSUE TITLE
Modify map in pipelines

### ISSUE THREAD

**Issue by fcoelho** [Graylog2/graylog2-server#6470]
## Expected Behavior

I'd like to have a way to modify maps in pipelines. Particularly, I'm looking for ways to do one of:

1. remove a key from a map
2. assign a value to a map key

I'm looking for something that would allow me to do something equivalent to:

```
// assign/replace
map["timestamp"] = parse_date(map["timestamp"]);
// remove
remove_key(map, "timestamp");
```

## Current Behavior
There's no way to modify map variables after they're created (that I could find in the documentation)

## Context
I'm trying to convert a `timestamp` field present in some log groups messages to an actual date object in a pipeline. See https://community.graylog.org/t/removing-key-from-pipeline-map/12037

## Your Environment

* Graylog Version: 3.1.0
* Elasticsearch Version: AWS 6.8
* MongoDB Version: 4.2.0

**Comment by jpuskar** [comment]
Just a bump (apologies).

**Comment by ckristo** [comment]
Would love to see this feature - seems missing according to [rule function docs](https://go2docs.graylog.org/5-0/making_sense_of_your_log_data/functions_by_category.html?tocpath=Making%20Sense%20of%20Your%20Log%20Data%7CPipelines%7CFunctions%7C_____2)

**Comment by ckristo** [comment]
Had a quick look at the code, grammar for RuleLang resides in [graylog2-server/blob/master/graylog2-server/src/main/antlr4/org/graylog/plugins/pipelineprocessor/parser/RuleLang.g4](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/antlr4/org/graylog/plugins/pipelineprocessor/parser/RuleLang.g4), function implementations in [graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions](https://github.com/Graylog2/graylog2-server/tree/master/graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions).

Looking at the grammar, it seems not very easy to add support for the`m[k]` syntax to access a map element. Therefore, I would suggest to introduce a function for that like `map_get(k, [default_val])`. To be consistent, I would suggest `map_remove(k)` for deleting a value from the map.

If there is interest in having these, I would try to come up with an implementation.

**Comment by patrickmann** [comment]
@ckristo Just curious, what use cases do you have in mind for this? Looking at the pipeline functions we don't do a lot with maps:
- multi-value returns from table lookup
- jsonpath return values
- to_map for subsequent set_fields

**Comment by ckristo** [comment]
Hey. Pretty much what @fcoelho wanted to achieve in the original issue - I parsed a JSON file and had a name clash with one of the predefined fields (also with `timestamp`). I could work around that by renaming the field at the generating source (nginx), but I guess there are log sources out there where this is not possible. The alternative would be to apply a prefix to all fields, but this seemed odd to me (for solving a name clash of a single field).

Nevertheless, it seems general map manipulation functions could come in handy for all the functions you listed :-)
