### ISSUE TITLE
/etc/graylog/server/GeoLite2-City.mmdb path for the GeoIP plugin is hardcoded.

### ISSUE THREAD

**Issue by manishjhawar** [Graylog2/graylog2-server#6503]
## Expected Behavior

When I customize the location of the MaxMind's `GeoLite2-City.mmdb` file and enable the plugin with the new location in the configuration, it is expected to work.

## Current Behavior

Instead, the plugin does not work and produces error logs saying the geoip database not found at `/etc/graylog/server/GeoLite2-City.mmdb` (which is the default path). So it seems that the default path is effectively hardcoded.

## Possible Solution

The customization was made while enabling the plugin, so it should have been picked along with the enabled status. Need to debug this most probably.

## Steps to Reproduce (for bugs)

1. Download, extract and put the `GeoLite2-City.mmdb` at a non-default location such as `/tmp/GeoLite2-City.mmdb`
2. Start Graylog server and enable the GeoIP plugin with the above path in the same dialog.
3. Ingest some logs with valid IP address values in a field.
4. Check that the geolocation does not work. Also check the log for the error described above.

## Context

Since the location `/etc/graylog/server/` seemed generic, I tried to put the `GeoLite2-City.mmdb` file under a `maxmind` folder and found that it does not work.

I have tried through the Docker Compose with image tag `3.1.2-1` and also checked read permissions for the `GeoLite2-City.mmdb` file.

## Your Environment

* Graylog Version: 3.1.2-1 (Docker image tag)
* Elasticsearch Version: 6.8.2 (Docker image tag)
* MongoDB Version: 3 (Docker image tag)
* Operating System: Ubuntu 18.04
* Browser version: Chrome 77.0.3865.90

**Comment by jalogisch** [comment]
![image](https://user-images.githubusercontent.com/404238/65778786-d17b7480-e146-11e9-85a5-ce1b6110ebef.png)


I do not agree with that, as I have exactly that. A non default path working. How did you mount the database into your docker container?

**Comment by manishjhawar** [comment]
@jalogisch Yes, the dialog updates the configuration as shown in your screenshot. But the plugin seems to be still using the default (hardcoded?) path internally.

BTW, I had mounted the database through a simple volume:
```
...
volumes:
  - ./maxmind:/etc/graylog/server/maxmind:ro
...
```

**Comment by jalogisch** [comment]
Did you checked if the UserID 1100 is able to read the file you have linked into the container?

As written before most (if not all) devs use a custom path without any problems.

**Comment by manishjhawar** [comment]
Yes, I did ensure that the database file is world-readable. In fact, they were owned by uid 1100 too.

I have not saved the logs unfortunately before taking the cluster down. I hope to spin it back up to capture them later in a week.

**Comment by titansmc** [comment]
it is not working for me, neither. I have ```/usr/share/graylog/geoip/GeoLite2-City.mmdb``` defined through the web interface but still I see the graylog server trying to find the DDBB from ```/etc/graylog/server/GeoLite2-City.mmdb```

```
-03-05 15:23:21,936 INFO    [LookupTableService] - Data Adapter whois/5d03a2822a25e5004f6436f1 [@5c772e91] RUNNING - {}
2020-03-05 15:23:21,936 INFO    [LookupTableService] - Data Adapter spamhaus-drop/5d03a27e2a25e5004f6436e6 [@2730222a] STARTING - {}
2020-03-05 15:23:21,932 ERROR   [FileInfo] - Couldn't get file info for path: /etc/graylog/server/GeoLite2-City.mmdb - {}
java.nio.file.NoSuchFileException: /etc/graylog/server/GeoLite2-City.mmdb
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_232]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_232]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_232]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:1.8.0_232]
```

Here you can see the screenshot of the current configuration

![image](https://user-images.githubusercontent.com/8192096/75996337-07930080-5efe-11ea-9a4c-6b2319446c0e.png)
