### ISSUE TITLE
Comic sans(?) used Views

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#6508]
## Expected Behavior
No comic sans or relative fonts in a professional product. Please see screenshot below from the Search functionality.

![Screen Shot 2019-09-30 at 17 47 19](https://user-images.githubusercontent.com/24830359/65889969-cc1e6400-e3aa-11e9-9e6a-9dd060ef283d.png)

## Current Behavior
Comic sans or relative font used in Views functionality.

![Screen Shot 2019-09-30 at 17 46 04](https://user-images.githubusercontent.com/24830359/65890072-fe2fc600-e3aa-11e9-9a74-086b0520e35c.png)

## Possible Solution
Change the font to e.g. Courier New

## Your Environment

* Graylog Version: 3.1.2

**Comment by dennisoelkers** [comment]
Hey @hulkk,

thank you for your very valuable contribution to the project.

The font family used is `Monaco, Menlo, "Ubuntu Mono", Consolas, source-code-pro, monospace`, not related to Comic Sans in any way.
