### ISSUE TITLE
Streams are sorted using guid instead of title in the Views

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#6514]
## Expected Behavior
Streams sorted alphabetically using title

## Current Behavior
Streams are sorted using stream guid.

Redacted screenshot:
![Screen Shot 2019-10-01 at 13 57 20](https://user-images.githubusercontent.com/24830359/65956934-40f9a880-e454-11e9-971b-f113a7123f16.png)

## Possible Solution
Use stream title when sorting.

## Steps to Reproduce (for bugs)
1. Create couple of streams
2. Open Views
3. Click "Select streams"

## Context
It would be more logical and usable, if streams would be in alphabetical order.

## Your Environment

* Graylog Version: 3.1.2

**Comment by dennisoelkers** [comment]
Thanks for reporting this. This is a reasonable complaint and we will fix this for the next version.
