### ISSUE TITLE
Permissions/roles boxes are not rendered correctly in "Edit (user) profile"

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#6515]
## Expected Behavior
Permissions/roles boxes should be rendered correctly in user information page.

Redacted screenshot:
![Screen Shot 2019-10-01 at 14 21 08](https://user-images.githubusercontent.com/24830359/65958353-dba7b680-e457-11e9-9c6e-e804b020a948.png)

## Current Behavior
Permissions/roles boxes rendered incorrectly in user information page.

Redacted screenshot:
![Screen Shot 2019-10-01 at 14 21 30](https://user-images.githubusercontent.com/24830359/65958404-fb3edf00-e457-11e9-8679-5f4bd99c33b3.png)

## Steps to Reproduce (for bugs)

1. Click user in the upper right corner
2. Click Edit profile
3. Add permissions/roles until the permissions/roles box should start to scale

## Context
Larger environments have multiple streams and roles. At least admins usually have dozens of permissions.

## Your Environment

* Graylog Version: 3.1.2

**Comment by jalogisch** [comment]
already fixed in upcoming version: https://github.com/Graylog2/graylog2-server/pull/6455
