### ISSUE TITLE
Function to change case on all available fields

### ISSUE THREAD

**Issue by gimmic** [Graylog2/graylog2-server#6527]
https://community.graylog.org/t/lowercase-field-names/12186

I’ve been trying to figure out a clean way to force lowercase on all field names. So far, I haven’t found a way to capture/iterate through every field in a pipeline parser. Something like $message.* or a way to use value substitution would be fantastic.

I wish I could figure out something like:
rename_field($message.$field, lowercase(to_string($message.$field));

## Expected Behavior
When receiving a large amount of varied logs, it might be nice to apply broad changes to fields or field names to help normalize. Since Elasticsearch is case sensitive, normalizing fields from sources that have differing cases would help reduce field count significantly.

## Current Behavior
Currently, some logs may bring in a field like 'username' while another source might use 'Username' or 'UserName'. While these can be fixed manually, when you're in the realm of a thousand+ fields, that can be intensive to chase down.

## Possible Solution
A function capable of being applied to every field name / value would help drastically. A variable to represent "current field value" would also help, so that you could do $message.$messagefield functions.

## Steps to Reproduce (for bugs)
Have various log sources and attempt to normalize case on field names across them without explicitly defining every field name with rename_field.

## Context
Specifically, bringing in Microsoft AD logs via JSON brings in annoyingly cased field names. This is retained through to ES storage. This isn't limited to AD logs but their choice of random capitalization isn't helpful. I would like to avoid changing the case of log data pre-ingestion for fidelity and avoiding CPU usage on the log origins.

## Your Environment
* Graylog Version: 3.1.2
* Elasticsearch Version: 6.8.3

**Comment by 1tft** [comment]
We also would welcome this feature. I think its a global issue (because elasticsearch handles fields case sensitive). Input plugin option to lowercase als field names would be a very good way to implement this feature at graylog.
Also I found no easy way to lowercase als field names e.g. with fluentd logshipper, so we definitely need this feature at graylog (enterprise).
