### ISSUE TITLE
Incorrect modal title when downloading a content pack

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#6540]
When downloading a Content Pack for a specific version, the title on the modal dialog reads "Export search result as CSV", the the download action actually downloads a JSON file (not CSV).

![image](https://user-images.githubusercontent.com/3423655/66238011-26c20380-e6bc-11e9-8a3c-e180886325bf.png)

![image](https://user-images.githubusercontent.com/3423655/66238029-38a3a680-e6bc-11e9-85dd-f58736ef1e7c.png)

## Expected Behavior
The title should not include CSV. It should also use the same verb as the button in my opinion.  Something like "Download Content Pack" would work.

## Your Environment

* Graylog Version:  3.1.2

**Comment by lingpri** [comment]
Please let me know, which project should I check out to fix this bug.
