### ISSUE TITLE
Pipeline rules should indicate where they are used.

### ISSUE THREAD

**Issue by waynekearns** [Graylog2/graylog2-server#6552]
## Expected Behavior
When viewing a pipeline rule there should be a method to find where this rule is used, and by extension whether it is used. This facilitates those who would create general purpose rules like "Server IP Enrichment" that could plug in to several streams, but they may want to know what will be affected in the data pipelines when altering the rule.

## Current Behavior
Use the API to poll ALL pipelines and then filter using a JSON parser for the pipeline rule in question and then iterate through the parents to create dependency list.

## Context
Rule changes and rule dependencies would be much easier to deduce and plan for, especially in a context where a large number of rules are in play.

## Your Environment

* Graylog Version: 3.1.2

**Comment by edmundoa** [comment]
Closing in favor of https://github.com/Graylog2/graylog2-server/issues/9724
