### ISSUE TITLE
Widgets from content packs share results

### ISSUE THREAD

**Issue by emmanuel-benoit** [Graylog2/graylog2-server#6556]
When dashboards are imported from a content pack through multiple installations with different parameters, their widgets display the same results despite having different configurations.

## Expected Behavior
Widgets on the two dashboards created from different installations of the same content pack should display their own results. 

## Current Behavior
Widgets on the two dashboards created from different installations of the same content pack display the same results.

## Possible Solution
I suspect this has something to do with the widgets having the same identifiers - since they are stored inside the dashboard document their configurations are indeed distinct, but the system caches the result by widget ID.
An (annoying) workaround consists in making every single widget ID a parameter.

## Context
Trying to configure streams and dashboards for different instances of the same application.

## Your Environment

* Graylog Version: 3.1.2
* Elasticsearch Version: 5.6.16
* MongoDB Version: 3.6.14
* Operating System: Debian 9.11

**Comment by dennisoelkers** [comment]
This should not be an issue anymore, as we do not cache widget results right now.
