### ISSUE TITLE
Improve Test Coverage of Search Backend

### ISSUE THREAD

**Issue by alex-konn** [Graylog2/graylog2-server#6583]
## Expected Behavior
The new search backend should be covered by automatic tests. 

## Current Behavior
Big parts of the code have no automatic tests at all.

## Possible Solution
Cover at least the most critical paths from API through `QueryEngine` in package `org.graylog.plugins.views.search` with unit and integration tests

**Comment by dennisoelkers** [comment]
Closing this, as we do have lots of full-backend-tests covering the search backend.
