### ISSUE TITLE
test button in alert notification

### ISSUE THREAD

**Issue by karkaaa** [Graylog2/graylog2-server#6593]
## Context
Hello,

After upgrade i can not find test button for alert notification. It is bug or disabled features?
Upgrade from 2.4.3 to 3.1.2.

Thx.
 
## Your Environment

* Graylog Version: 3.1.2
* Elasticsearch Version: 6.8.3
* MongoDB Version: 
* Operating System: Debian 9
* Browser version: Chrome latest

**Comment by mpfz0r** [comment]
This will be fixed in 3.1.3 : https://github.com/Graylog2/graylog2-server/pull/6549

**Comment by karkaaa** [comment]
on 3.1.1 working test button? maybe how else can i test for email sending on 3.1.2?
