### ISSUE TITLE
Unable to create more than one percentile metric for same field in aggregation

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#6597]
## Expected Behavior

Being able to create an arbitrary number of percentile metrics for the same field in aggregations

## Current Behavior

Adding the second percentile metric for the same field raises an error:

`Two sibling aggregations cannot have the same name: [805b866f-8832-41ab-92a7-fc15b6af30c5-series-percentile(http_response_code)].`

## Steps to Reproduce (for bugs)

1. Create custom aggregation
2. Add percentile metric for field
3. Add second percentile metric for same field

![Screen Shot 2019-10-16 at 15 12 08](https://user-images.githubusercontent.com/41929/66922460-66c3a780-f027-11e9-87c5-846a550b324c.png)

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by jeremyjpj0916** [comment]
Glad to see this getting picked up, mentioned it here:
https://community.graylog.org/t/stumbled-upon-this-gem-have-a-few-qs-about-graylog/12349/6?u=jeremyjpj0916
