### ISSUE TITLE
Show field type on mouseover field title

### ISSUE THREAD

**Issue by gimmic** [Graylog2/graylog2-server#6598]
It would be nice if the underlying document field types were more readily apparent from the graylog web UI.

There are two places that it could be useful to display a field's ES type: 
- on mouse over of a specific field in a search result
- in the field list on the left under search

Granted, it is possible the field type changes from index to index so it could display either the most recent field type or in the case of specific documents show the field type for that specific document field. 

## Current Behavior
There is not currently an easy way to see the underlying field types that I'm aware of. Using Kibana to check and review them. 

* Graylog Version: 3.1.2
* Elasticsearch Version: 6.8.x

**Comment by jalogisch** [comment]
he @gimmic you can see that already in the Views - that allows you to make this already in the current release of Graylog.
