### ISSUE TITLE
Views: Render geolocation as static points if no metric is applied

### ISSUE THREAD

**Issue by gimmic** [Graylog2/graylog2-server#6600]
Rather than require a metric(such as 'count()') in a view world map, allow entry of geolocation information and populate the map with dots indicating location hits if there is no metric applied.

## Expected Behavior
A simple dot placement on the world map for lat/long provided in a search result.

## Current Behavior
Leaving metric blank does not render any information onto the world map, even if there is lat/long data in the row.

## Possible Solution
Render the map with the same size dots for any lat/long in the query on the world map. If you wanted to get real fancy, code it so that the dots cannot overlap but sit adjacent. This way multiple hits to the same location naturally grow the size of the area covered. If the dot size is static, then as you zoom the map the coverage changes. 

* Graylog Version: 3.1.2
* Elasticsearch Version: 6.8.x

**Comment by dennisoelkers** [comment]
Fixed in #6737.
