### ISSUE TITLE
Value actions in View widgets Pie and Bar charts

### ISSUE THREAD

**Issue by shoothub** [Graylog2/graylog2-server#6612]
Please add Value actions in View widgets also for Pie and Bar charts

## Expected Behavior
Views widgets Pie chart and Bar chart should also support Value actions such as Add to query, Exclude from results. Now it is only supported in Data table and Single Number widgets.

## Current Behavior
You can only color in Pie or Bar charts widget in View. 

## Possible Solution
Add small arrow with Value actions menu next to values below chart. Or better, change behaviour of changing color, so you can change color only if you click on color rectable (make sence), but no value. If you click on value below chart, aplication should open Value actions menu.

![view-pie-chart-actions](https://user-images.githubusercontent.com/28008456/67079699-f25a4700-f193-11e9-8bcd-428d6bfec9d8.png)

## Your Environment
Graylog 3.1.2 OVA

**Comment by dennisoelkers** [comment]
Also relevant to the world map visualization: #1884.

**Comment by aim4r** [comment]
+1 for this.
It seems [#9396](https://github.com/Graylog2/graylog2-server/issues/9396) is a duplicate feature request.
