### ISSUE TITLE
 On the unresolved alerts screen - unresolved alerts are displayed as resolved ( Let user tick when an alert is actually resolved )

### ISSUE THREAD

**Issue by rafaelsanches123** [Graylog2/graylog2-server#6626]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
@rafaelsanches123 The alerting system in Graylog 3.1 switched to an event based model and there is no resolved/unresolved alert state at the moment. Building something you requested would also go further into the direction of an incident management system which we don't plan to build right now.

**Comment by rafaelsanches123** [comment]
Thank you for your attention @bernd!
