### ISSUE TITLE
Generating chart of any field throws debug error in elasticsearch log

### ISSUE THREAD

**Issue by iT3han** [Graylog2/graylog2-server#6630]
When we are adding charts of any field to current search results or to dashboard, elasticsearch reports following error in log:

[2019-10-22T12:59:22,137][DEBUG][o.e.a.s.TransportSearchAction] ... Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH ... Caused by: java.lang.IllegalArgumentException: Expected numeric type on field [Src_Hostname], but got [keyword] ...

The result of the chart is fine, but it does mess up our elasticsearch. logfile.

No ideas whats going on. See the attached logfile entry.

## Steps to Reproduce (for bugs)
1. Open a stream
2. Click "Generate chart" on any field in the left menu
3. Graph shows up in current search window and the log entry in elasticsearch appears

## Your Environment
* Graylog Version: 3.1.2
* Elasticsearch Version: 6.8.3
* MongoDB Version: 3.6.3
* Operating System: 18.04.3 LTS
* Browser version: Chrome  77.0.3865.120

[elasticsearch-error-graylog-chart.txt](https://github.com/Graylog2/graylog2-server/files/3755200/elasticsearch-error-graylog-chart.txt)

![elasticsearch-error-graylog-chart](https://user-images.githubusercontent.com/43262157/67280961-a3cbe600-f4ce-11e9-946e-89e773d44c6c.JPG)

**Comment by bernd** [comment]
@iT3han This can happen when you have different data types for the same field in different indices.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
