### ISSUE TITLE
amqp server input not able to process messages

### ISSUE THREAD

**Issue by h0nIg** [Graylog2/graylog2-server#664]
due to the restriction that the amqp server input requires a field that is not part of the default gelf format, the server is not able to process messages send directly from the application to the amqp broker. the input requires a "source" field but the common java gelf message generators does not have this field:

https://github.com/t0xa/gelfj/blob/master/src/main/java/org/graylog2/GelfMessage.java
https://github.com/Moocar/logback-gelf/blob/master/src/main/java/me/moocar/logbackgelf/GelfConverter.java

the source field is required on https://github.com/Graylog2/graylog2-server/blame/master/graylog2-inputs/src/main/java/org/graylog2/inputs/amqp/Consumer.java#L115

**Comment by bernd** [comment]
Graylog 1.0.0 ships with a GELF AMQP input that can read regular GELF messages from an AMQP broker.

Closing this issue now. Please re-open if you still have problems with this in Graylog 1.0.0. Thank you!
