### ISSUE TITLE
graylog2 radio amqp sender should be more reliable

### ISSUE THREAD

**Issue by h0nIg** [Graylog2/graylog2-server#665]
the sender should wait that the broker acknoledged the message and the message will definetly not get lost. In addition radio should try as long as possible to send the message to the broker (while(true)....)

```
channel = connection.createChannel();
channel.confirmSelect();
.....
channel.basicPublish(....);
channel.waitForConfirms();
```

**Comment by bernd** [comment]
Graylog radio is deprecated as of Graylog 1.0.0. Closing this issue now.
