### ISSUE TITLE
Graylog histogram resolution finer grained

### ISSUE THREAD

**Issue by jeremyjpj0916** [Graylog2/graylog2-server#6660]
I think it valuable to let people get histogram/metric values by the second if possible. Or more elegant/performant would be to give us a way to get get a pseudo of per second in a bucket like doing this in 

Splunk:
```
index=XXXX Something=Something | eval tps=1/900 | timechart span=15m sum(tps)
```

![image](https://user-images.githubusercontent.com/31913027/67545000-84e37480-f6c5-11e9-9549-9997b9a45768.png)

Histogram interval / bucket size. (year, quarter, month, week, day, hour or minute)

So maybe ```seconds``` could be exposed as a count() in the minute bucket / 60 in the chart to kinda achieve it without sacrificing performance for pseudo seconds(average per second as seen in minute buckets to verbalize it lol)? 

* Graylog Version: 3.1.2

**Comment by dennisoelkers** [comment]
Did you try doing it with the aggregation builder of the views? You can freely customize the aggregation interval for `timestamp` pivots in there.

**Comment by jeremyjpj0916** [comment]
@dennisoelkers I closed my work laptop for the day but will check it tomorrow, I remember I glanced at the views and did not see anything like that, do you have a screenshot handy what box in the UI enables the aggregation interval for the timestamp pivots? Otherwise I will see if I can find it in there.

Other features I am trying to see if Graylog can do the math on would be like Availability of Back-end API's based on analysis of message events HTTPStatus codes. 

Where Availability = % of ALL HTTPStatus codes not 5XX , I think this sort of logic is not possible in the views yet. 

I am a heavy user of Splunk and just trying to make suggestions that could help Graylog compete on some of the analytics and UI side of things. There is such a big market for it and yall are working towards a product that is comparable in many respects.

**Comment by jeremyjpj0916** [comment]
@dennisoelkers I think I am in the right place here:

![image](https://user-images.githubusercontent.com/31913027/67586769-66f72d80-f720-11e9-9aac-1c8144834359.png)

But I see no way to define buckets and things of the sort to achieve a line graph that can give me TPS of all the logs in this view. My query at the top of the UI for this view is just a grab all * relative to 1 day.

**Comment by dennisoelkers** [comment]
If you click on `timestamp` in the blue box of the `Rows` input, you can either generate more buckets (by using the slider) or define a manual bucketing interval (by deselecting the checkbox). Does this help?

**Comment by jeremyjpj0916** [comment]
@dennisoelkers AHHH yes thats what I am talking about. Although trying to 6 hours of logs on a per second bucket caused the page to become unresponsive 😆 . To really achieve a decent read on TPS Graylog would likely have to implement the ability to do something like get the events per minute(which loads super quick) and then just take the bucket values grabbed there and / 60 for avg tps per minute which is kinda what Splunk enables with the (| eval tps=1/900 | timechart span=15m sum(tps) to get it as tps in 15 minute buckets for example). But actually yes you did prove the functionality is there. Likely if I were to query a smaller interval range the TPS would not crash my browser. Appreciate it.

Will close this issue though as the feature is actually there. Enhancement could be to do like I mentioned to get psuedo TPS as a chart but happy to see it! Thx for giving me that insight.

**Comment by jeremyjpj0916** [comment]
![image](https://user-images.githubusercontent.com/31913027/67692622-d0707980-f976-11e9-873c-0b8d8a8d0371.png)

The intuitive thing woulda been something like this for me coming from Splunk maybe to get TPS in that manner.

**Comment by coffee-squirrel** [comment]
Just wanted to mention that I also had no idea about clicking on the blue box to get additional tuning options.

**Comment by jeremyjpj0916** [comment]
Yeah, was not super intuitive as a newb user but does provide good functionality. Definitely should be documented somewhere.

**Comment by dennisoelkers** [comment]
I do agree that it is hard to find right now. Instead of relying on the documentation (which a lot of users do not read and I do understand this) I would prefer making it more visible in the UI itself. We are working on improving the visual aggregation builder (this is how we call the component that generates a visualization and the aggregation that feeds it by specifying its building blocks) already to make elements like this more visible and the whole UI a bit more logical, maybe adding a small help text near the `Rows` element would help already? Or do you have any other ideas?

**Comment by coffee-squirrel** [comment]
Some help text could certainly be useful, although the aforementioned behavior isn't limited to fields in the Rows section.

Alternatively, perhaps the `fa-wrench` icon could be shown on each field.  There would be the downside of additional space required per field, however.

![image](https://user-images.githubusercontent.com/19417721/67767949-855e7100-fa1f-11e9-9066-5483ab6f0d95.png)
