### ISSUE TITLE
Allow creating searches through the API without assigning an id explicitly

### ISSUE THREAD

**Issue by alex-konn** [Graylog2/graylog2-server#6663]
As an API user I would like to create a search through the API without assigning a valid mongo ObjectId beforehand.

Currently POST /views/search returns a 500, if the submitted search object doesn't contain a valid Mongo ObjectId. Invalid IDs at least yield a half-decent error message, omitting the ID gives no error message at all.

## Possible Solution
Assign a new ObjectId to the search object, if it doesn't contain one. If an invalid ID is included, we should return a better error message.

**Comment by jgrammen-agilitypr** [comment]
I am also having this issue when trying to run search via the graylog api
https://community.graylog.org/t/graylog-3-3-9-search-api/18216

all the id fields had to be supplied as "id":"?"
for a valid search to be performed

**Comment by todvora** [comment]
Implemented in #11247
