### ISSUE TITLE
View page say messages are 0

### ISSUE THREAD

**Issue by jeremyjpj0916** [Graylog2/graylog2-server#6668]
Views page shows the number of records found to be 0 every search even though its not the case, see the bold **0 messages** lefthand side:

![image](https://user-images.githubusercontent.com/31913027/67608013-7b551d80-f754-11e9-9cc9-3ea954491807.png)

* Graylog Version: 3.1.2

**Comment by bernd** [comment]
I can reproduce this. When the last message table widget gets removed from the search, the number of messages is `0`. (tested with 3.2.0-beta.3-SNAPSHOT rev bc89350)

**Comment by kmerz** [comment]
For 3.2 we will remove the message count in the sidebar.
This needs to be mentioning in UPGRADING.rst

**Comment by dennisoelkers** [comment]
We have removed the message count for 3.2. Adding it back is tracked in #7386, closing this issue in favor of it.
