### ISSUE TITLE
Extractor management: load last received message instead of a 'recently received' one

### ISSUE THREAD

**Issue by 2ion** [Graylog2/graylog2-server#667]
When using the 'Load a message recently received by this input' button on the extractor management page, no message will be loaded if the last message received on this input had an old timestamp. For example, if I feed log messages dated a month ago and proceed with creating extractors for them, no sample message will be returned and I get the error "Could not load message. Make sure that ID and index are correct.". It probably is looking for messages with a 'search in the N last minutes/hours'.

Accordingly, either the behaviour is wrong (it should return one of the last messages received, regardless of their timestamp) or the button text needs to be fixed. Fixing the former aspect however makes more sense I think.

**Comment by kroepke** [comment]
It sounds to me like we should try with a conservative time range first (5 mins or whatever the value is right now) and go further back in time in case we do not find anything to avoid querying across a huge time span.

**Comment by edmundoa** [comment]
We changed this behaviour in 2.0, and now the recent message loader looks in all available indices for a message coming from the input. Please reopen if the problem still occurs in 2.x.
