### ISSUE TITLE
Views Widget Filter can't support queries regex format

### ISSUE THREAD

**Issue by jeremyjpj0916** [Graylog2/graylog2-server#6677]
![image](https://user-images.githubusercontent.com/31913027/67742682-1834e680-f9f3-11e9-8a6b-56c744c5a606.png)

![image](https://user-images.githubusercontent.com/31913027/67742840-75309c80-f9f3-11e9-94f1-0858f00c9239.png)

Tried adding a backslash as docs say to do on queries, also tried doing :5* by itself and that did not work either. 

* Graylog Version: 3.1.2

**Comment by kroepke** [comment]
I'm not sure this is still applicable to 3.2, can someone please verify if it is, and if not close the issue?
Thanks :)

**Comment by dennisoelkers** [comment]
In 3.2 the widget filter will vanish and replaced by other functionality, which supports regexes.
