### ISSUE TITLE
Users Client Address shows load balancer IP

### ISSUE THREAD

**Issue by radykal-com** [Graylog2/graylog2-server#6689]
## Expected Behavior
In a setup where graylog server nodes are behind a load balancer that sends the X-FORWARDED-* headers, it should reflect that IP in the UI (under Users -> Client Address)

## Current Behavior
The IP address/es of the load balancer are shown in the UI

## Possible Solution
Check for the existence of the X-FORWARDED-FOR header and set the Client Address from it, if not set act as it is now.

## Steps to Reproduce (for bugs)

1. Configure any Load balancer that sets the X-FORWARDED-* headers in front of graylog API
2. Log-in to graylog and check your Client Address under Authentication->Users->Client Address
3. Check the IP shown its from the load balancer

## Your Environment

* Graylog Version: 3.1.2
* Elasticsearch Version: 6.8
* MongoDB Version: 4.0.13
* Operating System: Ubuntu 16.04
* Browser version: Google Chrome 78

**Comment by jalogisch** [comment]
did you have set the trusted proxy? because if the forwarder is not part of that list graylog does not allow the overwrite.

**Comment by radykal-com** [comment]
Oh, no, I haven't it set up, will test with all the subnet range. Will come back with news

**Comment by radykal-com** [comment]
Closing this, settings the trusted proxies works. Thanks you
