### ISSUE TITLE
create event if sidecar gets inactive / active

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#6697]
## Expected Behavior
When a sidecar agent is reporting in or stopped reporting it's present graylog should write that as event that the alerting can act on the presence or missing of sidecars.

## Context
Some environments need to get notified when sidecars report in or are taken offline. Mostly in Multi-Team/Multi-Timezone environments where one team is responsible for the logging while other for the operation.

## Your Environment

* Graylog Version: 3.1

[z#842863]

**Comment by tmacgbay** [comment]
This would work well for us - when a new server is built, sidecar is automatically installed but Graylog has to be manually adjusted to the right collector set - this would remind the builder (me) to finish the job.

**Comment by llondono20** [comment]
This would be helpful since it would then alert the admin if there is an issue with a collector and you don't go a day or 2 without having any logs being collected. If anyone follows the NIST controls there is supposed to be an alert if a Syslog failure happens.

**Comment by Knightshift97** [comment]
Was this feature ever incorporated?  Generating alerts when "log monitoring fails" is now a security requirement that my organization has to meet, so it would be very helpful.

**Comment by arnaudluti** [comment]
interested as well !

**Comment by NEO-AMiGA** [comment]
Yes please thank you very much! 🤩 This would be very helpful to have.

**Comment by H2Cyber** [comment]
This would work well for our server fleet (which is not supposed to go down except for a few minutes during reboots), but not for our desktops. 

With this in mind, and if this feature gets implemented then I think :
* the user should have the ability to choose which sidecars would generate an alert if inactive / down
* the user should choose the tolerated timeout duration after which an event is triggered

**Comment by HungryHowies** [comment]
+1

**Comment by dio99** [comment]
+1

**Comment by Jenda2022** [comment]
+1

**Comment by damianharouff** [comment]
This has had a customer request via HS-1343758874.

**Comment by trogers-gfcu** [comment]
+1 Had a sidecar down for a week before we noticed.

**Comment by dio99** [comment]
one other options also would be to able to have scheduler to try to restart  sidecar agent  X times if the status is failing. i see this alot on sidecars.
