### ISSUE TITLE
Make search/dashboard actions consistent

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#6699]
On the search vs. dashboard pages there are currently two different ways to save the current state:

Search:
![Screen Shot 2019-10-31 at 10 37 52](https://user-images.githubusercontent.com/41929/67935624-8ed80c80-fbca-11e9-9642-caec585a19bd.png)

Dashboard:
![Screen Shot 2019-10-31 at 10 38 04](https://user-images.githubusercontent.com/41929/67935627-913a6680-fbca-11e9-81ce-36c201ea94ca.png)

Those should be made consistent the way they work.

**Comment by linuspahl** [comment]
Got fixed by https://github.com/Graylog2/graylog2-server/pull/7291
