### ISSUE TITLE
in out real time messages shows 0 messages when in cluster setup

### ISSUE THREAD

**Issue by tuwid** [Graylog2/graylog2-server#6700]
After upgrading to Graylog 3.1.2 the real-time message throughput in the top right corner stopped working although messages are getting processed fine. 
We noticed this behavior on cluster mode ( setup with 1 graylog master, 2 graylog inputs, a mongo cluster with 3 instances and ES cluster with 3 masters and 15 data nodes )
In a simpler setup with 1 master, ES cluster with 3 nodes and 1 mongo instance real-time counter works fine

## Expected Behavior
We should be able to see message throughput in real-time as in 2.X  

## Current Behavior
Counter show 0 in/0 out although more than 400 messages are getting processed per second

## Possible Solution
no idea 

## Steps to Reproduce (for bugs)
Setup graylog as advised in cluster mode (3 mongo instances in cluster mode, 3 ES masters, N ES data nodes, 1 graylog master and N input nodes ) and generate a high throughput of messages 

## Context
It's important for us to see the counter as its the primary indicator of issues during an incident with our logging cluster

## Your Environment
LB with haproxy pointing the web part to 1 graylog master and ports 12443 to 2 graylog inputs/message processors, a mongo cluster with 3 instances and ES cluster with 3 masters and 15 data nodes ( everything under docker ) 

* Graylog Version: 3.1.2+9e96b08 on 16b158732236 (Oracle Corporation 1.8.0_232 on Linux 4.4.0-1092-aws)
* Elasticsearch Version: 6.5.4
* MongoDB Version:3.7.9
* Operating System: Ubuntu 16.10 
* Browser version: Safari 13.0.2

**Comment by jalogisch** [comment]
@tuwid what are the `http_*` settings of each node? Does the `http_external_uri` point to the loadbalancer? Does the Loadbalancer set any kind of header?

Finally - does the user you use has the right to read the cluster status (means did you create a custom role?) 

Does your Browser show any error in the Network connection part of the web developer tools?

**Comment by tuwid** [comment]
@jalogisch thanks for the quick reply
I have only this as env variable GRAYLOG_HTTP_PUBLISH_URI pointing to the LB(haproxy) https://graylog.xxxxxxx and according to the docs this should populate http_external_uri as well.

I have 2 default roles assigned (Admin and Reader) which doesnt seem to be a permission issue unless one invalidates the other and these roles are mapped from LDAP. 
I have the same settings on my dev cluster and its working fine there 

The network connection part in the browser was the first thing I checked and there is no errror there. It might be worth mentioning that all these services are running on docker and I'm managing these from rancher 1.6

**Comment by jalogisch** [comment]
The `http_publish_uri` needs to be unique for EVERY Graylog node in your environment because that is taken to communicate in the cluster and build the statistic. This uri is used by each node to communicate with the other nodes. If that is not unique the numbers can't be counted. 

The `http_external_uri` needs to point to your loadbalanver URI.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
