### ISSUE TITLE
Update Disruptor and review API usage

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#671]
We are using an outdated disruptor release and could benefit from the more advanced usage patterns the newer releases provide (e.g. parallel event handlers).
Properly using the disruptor API can turn a few of our multi-producer scenarios into single producer ones for added performance.

**Comment by bernd** [comment]
We updated to the latest disruptor release in the meantime and also reviewed the API usage in Graylog when we did the journal.
