### ISSUE TITLE
Dashboard exported from search is not marked as `isNew`

### ISSUE THREAD

**Issue by kyleknighted** [Graylog2/graylog2-server#6735]
## Expected Behavior

Be able to save a Dashboard error free, or UI contextual changes to show missed required fields

## Current Behavior

```
backend.js:6 There was an error fetching a resource: cannot PUT http://localhost:9000/api/views/5dc2e7b1a64aab9615d41290 (400). Additional information: Cannot construct instance of `org.graylog.plugins.views.search.views.ViewDTO$Builder`, problem: Missing required properties: title
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1328]
```

## Steps to Reproduce (for bugs)

1. Create new Search on `3.2` feature flag
2. Save Search with name
3. Load saved Search
4. Click `Dashboard Export` button 
5. Click `Actions` dropdown buttonm
6. Click `Save` link

## Your Environment

* Graylog Version: `copy-widget` branch from https://github.com/Graylog2/graylog2-server/pull/6733
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
The "Save" action should be disabled for a dashboard that has been recently exported from a search without being "Saved as" afterwards.
