### ISSUE TITLE
Prevent modification of default event streams

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6738]
## Description

The default event streams "All events" and "All system events" can be modified by users at the moment. This is because we currently don't have a generic mechanism to protect system resources.

To prevent users from modifying the streams we should disable the UI elements for edit/delete and adjust the API to forbid modification of the database objects.

## Tasks

- [ ] Adjust UI to disable edit/delete buttons and forms based on the hardcoded stream IDs
- [ ] Adjust API to forbid modification/deletion based on the hardcoded stream IDs

**Comment by gimmic** [comment]
I agree here, I almost deleted the streams in cleanup.

**Comment by mpfz0r** [comment]
fixed with https://github.com/Graylog2/graylog2-server/pull/10983
