### ISSUE TITLE
Grok data type is ignored, affecting Quick values

### ISSUE THREAD

**Issue by zoulja** [Graylog2/graylog2-server#6739]
I'm processing Nginx access logs with Graylog
For HTTP status code I have the following grok pattern:
`%{HTTP_CODE:HTTP_CODE;int}`, where HTTP_CODE code pattern is: `[1-5][0-9][0-9]`
(Also, initially I tried `%{NUMBER:HTTP_CODE;int}`)
## Expected Behavior
Log matched this pattern is parsed and indexed properly(respecting type int)
Log not matched this pattern not indexed.

## Current Behavior
When I use Quick values on HTTP_CODE I often get errors like this:
`Loading quick values failed with status: Error: cannot GET http://1.2.3.4:9000/api/search/universal/relative/terms?query=gl2_source_input%3A5c94beb3d5256e0c0b346c77%20AND%20REQUEST%3A\%2FCPS\%2F*&range=28800&field=HTTP_CODE&order=HTTP_CODE%3Adesc&size=50&stacked_fields= (500)
`
I Chrome Developer Tools I see the following response:
```
message: "Unable to perform terms query↵↵{"root_cause":[],"type":"search_phase_execution_exception","reason":"","phase":"fetch","grouped":true,"failed_shards":[],"caused_by":{"type":"aggregation_execution_exception","reason":"Merging/Reducing the aggregations failed when computing the aggregation [gl2_terms] because the field you gave in the aggregation query existed as two different types in two different indices"}}"
type: "DetailedError"
```

In the System/Overview I see Indexer failures like these:
`{"type":"illegal_argument_exception","reason":"mapper [HTTP_CODE] of different type, current_type [long], merged_type [keyword]"}`

If I understand it properly by some reason Elasticsearch wrote some log with non-digit HTTP code.
I'm really confused how it's possible as my GROK statement is very specific.

Another consideration:  Somehow Quick Values affected in this scenario, where we just need to list all entries. Maybe it's possible to make this feature more tolerant?

--
## Possible Solution
N/A

## Steps to Reproduce (for bugs)
I don't know how to reproduce, since it's not clear how to identify record which were recognized incorrectly.

## Context
Need to be able to use Quick values in such basic scenario

## Your Environment

* Graylog Version: Graylog 3.1.2
* Elasticsearch Version: 6.8.3
* MongoDB Version: 4.0.12
* Operating System: Centos7.7
* Browser version: Chrome 73

**Comment by jalogisch** [comment]
https://community.graylog.org/t/whats-the-indexer-failures-logic/12609

**Comment by zoulja** [comment]
seems to be mapping issue
