### ISSUE TITLE
No source hostname/IP of syslog sender is present on messages indexed.

### ISSUE THREAD

**Issue by dgsus** [Graylog2/graylog2-server#6746]
If im not mistaken, according to https://github.com/Graylog2/graylog2-server/commit/375e61857837c33bd8206addc278e1afcce99049 this issue should be fixed, or maybe im interpreting this wrong and its not related to what im experiencing.

All the syslog messages i receive only have the following fields

facility
gl2_message_id
level
message
source
timestamp

Thanks in advance for your help!

## Expected Behavior
I should be able to see who sent the syslog message

## Current Behavior
Cant see who sent the syslog message

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version: 3.1.3
* Elasticsearch Version: 6.8.3
* MongoDB Version: 4.2.1
* Operating System: rhel
* Browser version:

**Comment by jalogisch** [comment]
@dgsus it is not clear for me if your `source` field does not hold information of the remote system. That information is taken from the sending system messages itself. 

Could you please be a little more verbose on your message. Thank you.
