### ISSUE TITLE
The timestamp in the alarm email received is wrong

### ISSUE THREAD

**Issue by vinzol** [Graylog2/graylog2-server#6747]
Hello, I am using 3.1.3 at present. Now I have such problems and need your help. The server has configured the time zone correctly, but the timestamp in the alarm email received is wrong. Is there any way to solve this problem?
Thanks in advance for your help!

**Comment by florianvolle** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
