### ISSUE TITLE
A view: the title of an element is not saved, unless enter is pressed

### ISSUE THREAD

**Issue by Mexonizator** [Graylog2/graylog2-server#6759]
Hi.

So the problem. When you want to edit, say, a tab's name, you doubleclick on it and enter the new name. Then click outside and the tab changes. After that you choose to save in the dropdown menu in the top right corner and think that everything has been saved.

But it hasn't. :) 

Why? Because it seems the saving happens only after the enter key is pressed. In all other cases it just resets as soon as the page has been refreshed or another tab selected.

It'd be nice to do something with that. :) 

Thanks!

Graylog Version: 3.1.3

**Comment by linuspahl** [comment]
Hello @Mexonizator, thank you for the hint!
We've fixed this problem and will release the related changes with the version 3.2.0

**Comment by Mexonizator** [comment]
You're welcome! 

Thanks a lot to you as well!

**Comment by dennisoelkers** [comment]
@Mexonizator: You can leave the issue open, it will be closed when 3.2.0 is out and we have a public release that fixes the issue.

**Comment by Mexonizator** [comment]
Ok!
