### ISSUE TITLE
Percentage in views data table

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#6763]
We'd like to be able to show the percentage each row of a views data table contributes to a total, which might be `count()` or something like `sum(traffic_accounting_size)`.

## Expected Behavior

As is possible with the old search page's "Quick values" and the "Pie Chart" visualization, we'd like to be able to show the percentage a particular row contributes to a certain total.

## Current Behavior

It looks like the pie chart might be the only visualization that shows percentages.

## Possible Solution

A `percentage(...)` metric that can be used to add a data table column representing the percentage a given row contributes to a certain sum.

## Context

We're putting together a view to monitor `traffic_accounting_size`, `count()`, etc. per log source.  It'd be useful to have data table columns representing the various percentages each source contributes to various totals.

## Your Environment

* Graylog Version: 3.1.3
* Elasticsearch Version: 6.6.2-1
* Operating System: RHEL

**Comment by aim4r** [comment]
This used to be avialable in the quick values widgets, but has disappeared in the more recent Graylog versions :(

**Comment by dennisoelkers** [comment]
Hey @coffee-squirrel & @H2Cyber,

we are currently working on a PR (#15738) implementing this, which will be part of `5.2`. Thanks for your patience!
