### ISSUE TITLE
Behavior of query-related field actions for metrics in views

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#6767]
The various view field actions that determine a new search query (Exclude from results, Add to query, etc.) don't seem to be useful unless the value is for a message field.  This can lead to invalid or misleading search queries.

## Expected Behavior

Query-related field actions are only allowed when it will result in a valid search query.

## Current Behavior

Field actions allow for generating invalid or useless search queries.  For example:
* For a data table widget with a `sum(bytes_sent)` metric renamed to `Total Bytes Sent`, selecting "Add to query" for a value results in `Total Traffic Bytes:1234` being added to the search query.
* For a single number widget with a `count()` metric, selecting "Use in a new query" results in an invalid search query of `count():5678`.

Admittedly, neither of those actions makes sense, but it is possible.

## Possible Solution

Only show query-related field actions if dealing with a message field.

## Steps to Reproduce (for bugs)

1. Have a view with data table and single value widgets using metrics (i.e. not just fields)
2. Use field actions on the metric values
3. Note the behavior described in "Current Behavior"

## Context

Just noticed this when clicking around in a view, and wondered what would happen.

## Your Environment

* Graylog Version: 3.1.3
* Elasticsearch Version: 6.6.2-1
* Operating System: RHEL
* Browser version: Firefox

**Comment by dennisoelkers** [comment]
This issue is still valid. Renaming a function causes checks if actions are applicable to ignore that it is the result of a function.

**Comment by linuspahl** [comment]
It looks like the described problems have been fixed a while ago.
