### ISSUE TITLE
Absolute time range with distant date impacts view's bar+line chart, scatter plot display

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#6790]
When defining an absolute time range from a prior (e.g. 2019-11-12 8:00:00) to distant future time (e.g. 2020-11-12 8:00:00) the results get smashed to the far left of a bar chart, line chart, or scatter plot.  This also happens with a distant past time, but to the right of the chart/plot.

## Expected Behavior

The chart/plot only shows the time range applicable to the results returned, and not the entire search window.

## Current Behavior

Results get compressed to a line at the far left (or right) of the chart/plot.
![image](https://user-images.githubusercontent.com/19417721/68774663-0eb29d80-05f3-11ea-808f-44b4fbefd8f0.png)
![image](https://user-images.githubusercontent.com/19417721/68774694-1b36f600-05f3-11ea-99d1-cf66ae69eef2.png)
![image](https://user-images.githubusercontent.com/19417721/68774713-25f18b00-05f3-11ea-9fd1-51dd1dd1070f.png)
![image](https://user-images.githubusercontent.com/19417721/68779797-da42df80-05fa-11ea-8a61-d7784a993330.png)

## Steps to Reproduce (for bugs)

1. Have a view with a bar graph display certain results (e.g. `count()` x `timestamp`)
2. Switch to an absolute time range and set the end date to 1 year in the future
3. Click the search icon to kick off a search (since hitting enter in the end date field doesn't seem to update things)
4. Note the thin bar/line at the far left

## Context

We wanted to display "_X specific time_ to _present_".  To avoid constantly changing the end date/time we set it to 1 year in the future, thinking that'd only control the search window and not how the chart/plot was rendered.

## Your Environment

* Graylog Version: 3.1.3
* Elasticsearch Version: 6.6.2-1
* MongoDB Version: 4.0.6-1
* Operating System: RHEL
* Browser version: Firefox 69.0.3

**Comment by dennisoelkers** [comment]
Hey @coffee-squirrel,

sorry for the late response and thanks for reporting this. Can you show the data table for the charts shown above? This would help finding out why the charts are rendered this way.

**Comment by coffee-squirrel** [comment]
@dennisoelkers Unfortunately I won't be able to show the data table, however the issue can be easily recreated by using an absolute time range that has a start date far before the first available message's date, or and end date far after the last available message's date.

This hasn't been causing us much grief, so if the timeframe displayed on a chart is intentionally tied to the search timeframe (rather than the start and end times of the actual search results) I'd be fine with closing this.
