### ISSUE TITLE
Dashboards in view can not change title

### ISSUE THREAD

**Issue by yoke88** [Graylog2/graylog2-server#6807]
Dashboards in view can not change title

## Expected Behavior
![Annotation 2019-11-15 083934](https://user-images.githubusercontent.com/3146226/68907648-84e60a00-0783-11ea-9465-025b88a8a9b0.jpg)

## Current Behavior
Event changed the title and save,it never changed

![image](https://user-images.githubusercontent.com/3146226/68907686-a3e49c00-0783-11ea-94db-1908f8ed283b.png)

## Possible Solution
Currently, there is no solution

## Steps to Reproduce (for bugs)
edit the dashboard title and save, nothing changes

## Context

the default title or default generated title was meaningless ,so i want to change it , but not works.
for example:
- Aggregating count() by category
- Untitled Message Table
## Your Environment

* Graylog Version: Graylog 3.1.3+cda805f on localhost (Oracle Corporation 1.8.0_171 on Linux 3.10.0-1062.4.1.el7.x86_64)
* Elasticsearch Version: 
* MongoDB Version:
* Operating System: centos 7.9
* Browser version: chrome 78.0.3904.97

**Comment by dennisoelkers** [comment]
Hey @yoke88, thanks for reporting this.

Did you save the view after changing the widget's title? If yes, could you please provide a step-by-step list to reproduce this?

**Comment by yoke88** [comment]
yes, i have saved the dashboard change and also save the view, but after this there is no change, i can not provide more steps。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by yoke88** [comment]
![can not change title](https://user-images.githubusercontent.com/3146226/69021861-3d19e980-09f4-11ea-97af-470e412f6658.gif)

**Comment by radykal-com** [comment]
Maybe related to #6759 ?

**Comment by radykal-com** [comment]
@yoke88 can you test if after setting the new title, pressing Enter key on the keyboard and then doing the saves does work?

**Comment by yoke88** [comment]
@radykal-com After input enter key , the title can be changed .thanks

**Comment by radykal-com** [comment]
@yoke88 Please close the issue if help is no longer needed :)

**Comment by dennisoelkers** [comment]
As this does not seem to be a bug, I am closing this.
