### ISSUE TITLE
make the left panel in view collapsible 

### ISSUE THREAD

**Issue by yoke88** [Graylog2/graylog2-server#6809]
make the left panel in view collapsible 
## What?
The left panel occupy lots of space of the screen ,can we hide it like grafana or kibana
![image](https://user-images.githubusercontent.com/3146226/68908690-04290d00-0787-11ea-9c65-5d7e18e3ab91.png)
![image](https://user-images.githubusercontent.com/3146226/68908747-2e7aca80-0787-11ea-823b-65e91b12dfff.png)

## Why?
the left panel is used infrequently , and occupy lots of space of the screen
## Your Environment

* Graylog Version:  Graylog 3.1.3+cda805f on localhost (Oracle Corporation 1.8.0_171 on Linux 3.10.0-1062.4.1.el7.x86_64)
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Centos 7.9
* Browser version: chrome 78.0.3904.97

**Comment by dennisoelkers** [comment]
Thanks @yoke88, we have already implemented this for `3.2` (#6467), which will be released together with lots of other changes in january.

**Comment by bernd** [comment]
Closing this because the sidebar can be collapsed in the upcoming 3.2 version.
