### ISSUE TITLE
Make Views and Saved Searchs exportable

### ISSUE THREAD

**Issue by yoke88** [Graylog2/graylog2-server#6810]
Make Views and Saved Searchs exportable
## What?

I can not export views and saved searchs

## Why?

mainly i have a test environment and a product environment ,the saved search  and views can not export and import easyly , so these items is not reusable

## Your Environment

* Graylog Version:  Graylog 3.1.3+cda805f on localhost (Oracle Corporation 1.8.0_171 on Linux 3.10.0-1062.4.1.el7.x86_64)
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Centos 7.9
* Browser version: chrome 78.0.3904.97

**Comment by dennisoelkers** [comment]
Thanks @yoke88 for reporting this. Can you tell us how your ideal workflow for exporting/importing views & saved searches would look like?

**Comment by jalogisch** [comment]
I personal see this as a duplicate of: https://github.com/Graylog2/graylog2-server/issues/6596

**Comment by yoke88** [comment]
if you have used grafana,  i wish i can export the view and saved search as json files,which i can import it back and i can edit it with a editor

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dennisoelkers** [comment]
Duplicate of #6596.
