### ISSUE TITLE
Notifications for Alerts are sent with delay

### ISSUE THREAD

**Issue by denis-zvonov** [Graylog2/graylog2-server#6818]
## Expected Behavior
When Alert occurs, if email notification is configured, email is sent within seconds.

## Current Behavior
Alerts generated in time, as defined by rules. Notifications are submitted to the mail server with delay (~40 mins) and it looks like they are submitted in a batch, all at once.

Test notification are fine, almost immediate.

## Possible Solution
Check for any job batching or scheduling in the mail pipeline. Check for possible waits/synchronizations.

## Steps to Reproduce (for bugs)
Hard to say.
I run a server for a couple of weeks with average load of several msg/sec.
I defined an Alert which checks every minute that there are more than limit amounts of messages in the stream.
Alerts were induced by stopping inbound messages. Overall about 50 of them.

## Context
I am monitoring integration infrastructure. Loss of connectivity is detected by the condition of the amount of heartbeats in a minute is less than a limit.

## Your Environment
Standard Graylog installation made with Ansible scripts.
java -version
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

* Graylog Version: 3.1.2
* Elasticsearch Version: 6.8.3
* MongoDB Version: 3.6.16
* Operating System: Ubuntu 18.04 LTS
* Browser version: Chrome

**Comment by emper0r** [comment]
+1

**Comment by Sharkovichus** [comment]
+1

**Comment by jalogisch** [comment]
he @denis-zvonov did you see the same with 3.1.3? cause we fixed some issues that might fit into that space.

In addition, do you have more than one Graylog node? If yes, does all nodes process messages in your setup?

**Comment by Sharkovichus** [comment]
Hello!
I have the same problem with 3.1.3

**Comment by denis-zvonov** [comment]
Hi @jalogisch ,
I have only one Graylog node. Let me some time to experiment a bit to try to repeat the problem on 3.1.3. So far I saw no repetitions. But with 3.1.2 the problem appeared also not immediately after upgrade.

**Comment by jalogisch** [comment]
we will wait until you get back to us @denis-zvonov
