### ISSUE TITLE
Show timestamp fields in localtime on Search in the UI

### ISSUE THREAD

**Issue by fpieressa** [Graylog2/graylog2-server#6820]
Today in Searches only the "timestamp" Graylog field is shown in localtime.  All other timestamps fields are shown in Zulu.  It will be very useful if they are also shown in localtime as the "timestamp" Graylog field.

Timestamp are all in UTC timezone as expected.  It will be great if all the timestamp fields are show in localtime on Searches, as the Graylog "timestamp" field.

## Why?

Today all the timestamp fields except the Graylog "timestamp" field are shown in Zulu, making them complex to read. It will be more simple if they are shown in localtime.  As a workaround, we build a decorator pipeline, but it will be more useful if they are handle natively by Graylog.

## Your Environment

* Graylog Version: 3.1.3
* Elasticsearch Version: 6.8.4
* MongoDB Version: 3.6
* Operating System: CentOS 7.6.1810
* Browser version: 70.0.1 (64-bit)

**Comment by dennisoelkers** [comment]
This has been fixed in the new search for `3.2.0`. Once a field has the `date` type, it will always be shown in the user's local time.
