### ISSUE TITLE
Cluster Global API Browser is showing wrong url

### ISSUE THREAD

**Issue by mummy1027** [Graylog2/graylog2-server#6823]
I have 3.1 running on a host with nginx reverse proxy.

It is okay to access example.io/graylog/api/api-browser/global/index.html

But Cluster Global API Browser is showing example.io/graylog/api/graylog/api-browser/global/index.html.

More details could be found on 
https://community.graylog.org/t/cluster-global-api-browser-and-api-browser-seems-not-right/12798

* Graylog Version: 3.1.3
* Elasticsearch Version:6.8.3
* MongoDB Version:4.0.10
* Operating System:Ubuntu 18.04
* Browser version:Chrome

**Comment by mpfz0r** [comment]
Thank you for your report. That's indeed a bug.
