### ISSUE TITLE
Views don't search on all indexes of a stream

### ISSUE THREAD

**Issue by dploeger** [Graylog2/graylog2-server#6828]
When using views to display a graph and selecting a specific stream, the graph seems to stop at the point in time, where the stream's index was rotated.

## Expected Behavior
A graph in the view should display all data across all indices of a selected stream.

## Current Behavior
The graph only displays data from where the rotation was done.

![image](https://user-images.githubusercontent.com/203453/69155435-fefaf380-0ae1-11ea-80d5-b7a7c6c15246.png)

When no stream is selected, the complete graph is shown

## Steps to Reproduce (for bugs)
1. Create an index that has a rotation (for example: daily rotation)
2. Collect data past that rotation point
3. Create a view showing a graph from that data

## Your Environment

* Graylog Version: 3.1.2
* Elasticsearch Version: 5.6.16
* MongoDB Version: 4.0.12
* Operating System: macOS 10.15.1 (19B88)
* Browser version: 78.0.3904.97

**Comment by kroepke** [comment]
This sounds like the index ranges aren't up to date for that index set.
Can you double check whether this problem continues to be there after choosing "Recalcuate index ranges" from the Maintenance menu on the affected index range page?

**Comment by dploeger** [comment]
It does, sadly. Recalculating didn't do anything.

**Comment by l0calhost** [comment]
I can confirm this for 

- Graylog 3.1.3
- ES 5.6.16

**Comment by bernd** [comment]
@dploeger @l0calhost Thank you for the report and information. A fix for this will be included in the upcoming 3.1.4 bug fix release.

Please make sure to read the release notes because it requires a manual step to recalculate the index ranges. (there was a bug in calculating them)
