### ISSUE TITLE
New message count alarm condition option: track message fields with identical values

### ISSUE THREAD

**Issue by 2ion** [Graylog2/graylog2-server#683]
For alarms based on the message count condition, it its for example often useful to trigger an alarm on the condition that if there were N messages during the last X minutes from the SAME IP address, without the IP address being known beforehand.

To generalise, it should be possible to set a tracker on specific message fields that triggers if there were >=N messages with the same value for the specified field.

The overhead of this tracker would be controlled by the time constraints of the message count condition.

**Comment by hc4** [comment]
Raising this feature request, because it is very useful for monitoring of arriving data per source (or per any other criteria) 
My case - I want to monitor, that every host provides data (currently I must create stream per host)
It looks like easy modification for existing "message count condition"
Just add "group by field" option and count messages per group for condition triggering

**Comment by hc4** [comment]
Also there is should be another parameter with list of "monitored" field values
Eg I want to monitor data, received from host1, host2 and host3 but not any other

**Comment by eddywebs** [comment]
Any idea on when this will be released ? It grea to know about any workarounds to facilitate this kind of use case in the meantime

**Comment by JoaoVictorValentim** [comment]
:(

**Comment by vchau** [comment]
I'm still holding out hope that this 4-years old feature will be implemented..

**Comment by 2ion** [comment]
@vchau Since 4 years ago we've gained a stable plugin API which allows you to implement this alert condition on your own in production quality, see http://docs.graylog.org/en/2.4/pages/plugins.html.

**Comment by bernd** [comment]
This is possible with the new alerting in 3.2 by using the cardinality function in an aggregation condition:

![image](https://user-images.githubusercontent.com/461/99160102-dea94900-26e3-11eb-9a9c-fe20fd4e2f64.png)
