### ISSUE TITLE
Remove http Uri from index.html

### ISSUE THREAD

**Issue by mojovski** [Graylog2/graylog2-server#6830]
I face a problem with the configuration via docker-compose:
```
- GRAYLOG_HTTP_EXTERNAL_URI=http://10.10.99.103:9000/
```
which makes the IP appear inside the index.html
```html
<body>
    <script src="http://10.10.99.103:9000/config.js"></script>
....
```

The problem is here, is that the graylog server is accessible from two different networks (it has two different IPs in different networks). If I access the server from network A, I see only IP IP_A, if I access the server from network B, I see it only via IP_B. Thus, if IP_A is 10.10.99.103, no one is able to access it from the network B.

I think a solution would be to remove the IP from the index.html and write
```html
<script src="/config.js"></script>
```
instead.

Can anyone advise how to achieve this?

Thank you very much!

**Comment by jalogisch** [comment]
You should carefully read about the `http_*` settings in the Graylog Documentation. If you want to access Graylog from two different locations you will need to have a proxy that sets the access location for the Graylog API for each location.

Graylog is in fact a browser application that needs to know where to reach the API to get data. By configuration this is via `http_external_uri` what can be overwritten by headers. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by mojovski** [comment]
Hi @jalogisch ,
Thanks for the quick answer.
Just to get it clear for me: it would not help to remove the IP from the index.html?
