### ISSUE TITLE
Avoid unnecessary search refreshes

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#6849]
## What?

The number of cases where a view tabs automatically initiates new searches to refresh itself should be reduced.

## Why?

When view tabs deal with a large amount of data, contain a fair number of widgets, etc., things like duplicating tabs and adjusting the search timeframe and/or query (potentially multiple times in a short period) can negatively impact Elasticsearch performance.

## Your Environment

* Graylog Version: 3.1.3
* Elasticsearch Version: 6.6.2
* MongoDB Version: 4.0.6
* Operating System: RHEL
* Browser version: Firefox

**Comment by dennisoelkers** [comment]
Thanks for reporting this. We are currently implementing a consistent behavior where after editing anything in a view (widget settings, the query string, timerange) etc. the search is refreshed, so what the user sees corresponds to the data returned in "all" cases. How would this work if the search is not refreshed when e.g. a query is duplicated? What should happen when a query is duplicated, as we cannot show anything in the widgets of a duplicated query until the search is executed?

**Comment by coffee-squirrel** [comment]
I certainly see the benefit of that; particularly, why it'd be good to run searches on query duplication and widget reconfiguration.

The main pain point for me is specifically related to adjusting the main search timeframe and query string, as there are typically multiple adjustments being made for a specific purpose (e.g. switching the start and end times, perhaps tweaking the query string) within a short amount of time.  These minor tweaks (especially depending upon what's changed) can slow things down and/or show results I don't really care about.  My preference would be to keep the `/search` behavior, where hitting Enter or clicking the search icon is required for search timeframe or query string changes.

**Comment by coffee-squirrel** [comment]
Perhaps a separate issue, but I noticed a search is executed if you click into, and then out of, the `to` and `from` inputs of an absolute time range, even if you didn't change the value.

**Comment by dennisoelkers** [comment]
Thanks for the input, @coffee-squirrel! We will consider the options we have and how to improve this for a future version. Not triggering a search refresh for unchanged timeranges is certainly easy to implement.

**Comment by dennisoelkers** [comment]
Refs #7203.

**Comment by coffee-squirrel** [comment]
Closed via #7829
