### ISSUE TITLE
Cant create or modify views over REST API

### ISSUE THREAD

**Issue by zambomarcell** [Graylog2/graylog2-server#6860]
## Expected Behavior
Create or modify views over REST API.

## Current Behavior

Enterprise/Views : 
Cant create or update view becouse get the following error message:
    Response Body

    {
      "type": "ApiError",
      "message": "View {id} doesn't exist"
    }

    Response Code

    404

    Response Headers

    {"Access-Control-Allow-Credentials":"true","Access-Control-Allow-Headers":"Authorization, Content-Type, X-Graylog-No-Session-Extension, X-Requested-With, X-Requested-By","Access-Control-Allow-Methods":"GET, POST, PUT, DELETE, OPTIONS","Access-Control-Allow-Origin":"https://xxxxxxxxxxxx","Access-Control-Max-Age":"600","Content-Length":"55","Content-Type":"application/json","Date":"Mon, 25 Nov 2019 10:49:42 GMT","X-Graylog-Node-Id":"32fb645d-f605-40be-bb2c-96b3861c8bbe"}

    I tested with post and put, with same results.

## Possible Solution
Fix the bug or write usefull example :) 

## Steps to Reproduce (for bugs)
1. open the api/api-browser
2. download the view json with get, modify the json
3. try to post or put
4. get error message.

## Context
We would like to generate the views with external tool (python script).

* Graylog Version:  3.1.2+9e96b08 (Oracle Corporation 1.8.0_212 on )
* Operating System: Linux 3.10.0-957.21.3.el7.x86_64
* Browser version: Chrome lastest

**Comment by dennisoelkers** [comment]
Hey @zambomarcell, thanks for reporting this!

How does the HTTP request look like (HTTP Action, URL, body)?

**Comment by zambomarcell** [comment]
Hey @dennisoelkers 

I just use the "get /views" method to get the views json.

Here is my sample json:


{
  "total": 3,
  "page": 1,
  "per_page": 50,
  "count": 0,
  "views": [
    {
      "id": "5dd7a1b9d978c8570935941b",
      "title": "Cardinality of IPs and dst_port",
      "summary": "",
      "description": "",
      "search_id": "5dd7a1fcd978c85709359442",
      "properties": [],
      "requires": {},
      "state": {
        "bf24aeaf-265e-4d4c-bc77-2261f535db0b": {
          "selected_fields": [
            "source",
            "message"
          ],
          "static_message_list_id": null,
          "titles": {
            "widget": {
              "2b475c76-56f4-423c-bfb4-a96b210c4fd2": "Message Count",
              "67d32f76-9a77-47b8-8627-7d3e802a328a": "All Messages"
            }
          },
          "widgets": [
            {
              "id": "f6986c0b-66b8-438d-b53c-8f46de0bab88",
              "type": "aggregation",
              "filter": null,
              "config": {
                "row_pivots": [
                  {
                    "field": "timestamp",
                    "type": "time",
                    "config": {
                      "interval": {
                        "type": "auto",
                        "scaling": null
                      }
                    }
                  }
                ],
                "column_pivots": [],
                "series": [
                  {
                    "config": {
                      "name": null
                    },
                    "function": "card(dst_ip)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "card(dst_port)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "card(src_ip)"
                  }
                ],
                "sort": [],
                "visualization": "line",
                "visualization_config": null,
                "formatting_settings": null,
                "rollup": true
              }
            },
            {
              "id": "67d32f76-9a77-47b8-8627-7d3e802a328a",
              "type": "messages",
              "filter": null,
              "config": {
                "fields": [
                  "timestamp",
                  "source"
                ],
                "show_message_row": true
              }
            },
            {
              "id": "2b475c76-56f4-423c-bfb4-a96b210c4fd2",
              "type": "aggregation",
              "filter": null,
              "config": {
                "row_pivots": [
                  {
                    "field": "timestamp",
                    "type": "time",
                    "config": {
                      "interval": {
                        "type": "auto",
                        "scaling": null
                      }
                    }
                  }
                ],
                "column_pivots": [],
                "series": [
                  {
                    "config": {
                      "name": null
                    },
                    "function": "count()"
                  }
                ],
                "sort": [],
                "visualization": "bar",
                "visualization_config": null,
                "formatting_settings": null,
                "rollup": true
              }
            }
          ],
          "widget_mapping": {
            "2b475c76-56f4-423c-bfb4-a96b210c4fd2": [
              "57feae43-0fd4-4842-82c8-cdbe05be9780"
            ],
            "67d32f76-9a77-47b8-8627-7d3e802a328a": [
              "22571b05-ff01-40ff-bdee-a9e5dcecce9a"
            ],
            "f6986c0b-66b8-438d-b53c-8f46de0bab88": [
              "ee00e4e1-4ee5-411f-9b1d-570a19449e2e"
            ]
          },
          "positions": {
            "f6986c0b-66b8-438d-b53c-8f46de0bab88": {
              "col": 1,
              "row": 1,
              "height": 4,
              "width": "Infinity"
            },
            "67d32f76-9a77-47b8-8627-7d3e802a328a": {
              "col": 1,
              "row": 7,
              "height": 6,
              "width": "Infinity"
            },
            "2b475c76-56f4-423c-bfb4-a96b210c4fd2": {
              "col": 1,
              "row": 5,
              "height": 2,
              "width": "Infinity"
            }
          },
          "formatting": {
            "highlighting": []
          }
        }
      },
      "dashboard_state": {
        "widgets": {},
        "positions": {}
      },
      "owner": "admin",
      "created_at": "2019-11-22T08:43:52.755Z"
    },
    {
      "id": "5dd67b948696b976c395b7c1",
      "title": "fortigate message type stat",
      "summary": "fortigate message type stat",
      "description": "",
      "search_id": "5dd79ee8d978c857093593ac",
      "properties": [],
      "requires": {},
      "state": {
        "382e607b-0aa4-44e2-8eb3-42a991337f0c": {
          "selected_fields": [
            "source",
            "message"
          ],
          "static_message_list_id": null,
          "titles": {
            "widget": {
              "7606964a-fc08-43b6-8174-e43b4da4b4ca": "Message Count",
              "d02d0856-3cdc-4221-b6c0-33f1eb94d1da": "All Messages",
              "1c1b2104-419b-458b-b3d3-31e63ac9e2c0": "Field Statistics for forti_type_event_rate_15m",
              "82f81c33-37db-4b8d-84b8-eb5d3157727a": "Field Statistics for port",
              "f4e79a82-853c-474f-b461-4aea504ba10a": "Aggregating count() by timestamp (copy)"
            }
          },
          "widgets": [
            {
              "id": "aebff88d-8508-4a5f-8f7d-fc400acefddb",
              "type": "aggregation",
              "filter": null,
              "config": {
                "row_pivots": [
                  {
                    "field": "timestamp",
                    "type": "time",
                    "config": {
                      "interval": {
                        "type": "auto",
                        "scaling": null
                      }
                    }
                  }
                ],
                "column_pivots": [],
                "series": [
                  {
                    "config": {
                      "name": null
                    },
                    "function": "avg(forti_type_event_rate_1m)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "avg(forti_type_traffic_rate_1m)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "avg(forti_type_utm_rate_1m)"
                  }
                ],
                "sort": [],
                "visualization": "line",
                "visualization_config": null,
                "formatting_settings": null,
                "rollup": true
              }
            },
            {
              "id": "fb723e6f-bc43-400f-a3ef-1c2f0870882a",
              "type": "aggregation",
              "filter": null,
              "config": {
                "row_pivots": [
                  {
                    "field": "timestamp",
                    "type": "time",
                    "config": {
                      "interval": {
                        "type": "auto",
                        "scaling": null
                      }
                    }
                  }
                ],
                "column_pivots": [],
                "series": [
                  {
                    "config": {
                      "name": null
                    },
                    "function": "avg(forti_type_event_rate_15m)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "avg(forti_type_traffic_rate_15m)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "avg(forti_type_utm_rate_15m)"
                  }
                ],
                "sort": [],
                "visualization": "line",
                "visualization_config": null,
                "formatting_settings": null,
                "rollup": true
              }
            },
            {
              "id": "c381d7fb-2267-455a-b191-e72a05d7b40d",
              "type": "aggregation",
              "filter": null,
              "config": {
                "row_pivots": [
                  {
                    "field": "timestamp",
                    "type": "time",
                    "config": {
                      "interval": {
                        "type": "auto",
                        "scaling": null
                      }
                    }
                  }
                ],
                "column_pivots": [],
                "series": [
                  {
                    "config": {
                      "name": null
                    },
                    "function": "avg(forti_type_event_count)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "avg(forti_type_traffic_count)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "avg(forti_type_utm_count)"
                  }
                ],
                "sort": [],
                "visualization": "line",
                "visualization_config": null,
                "formatting_settings": null,
                "rollup": true
              }
            }
          ],
          "widget_mapping": {
            "aebff88d-8508-4a5f-8f7d-fc400acefddb": [
              "a2939ce8-1b03-4e44-98d3-473c454e5142"
            ],
            "fb723e6f-bc43-400f-a3ef-1c2f0870882a": [
              "0e731f1e-7d35-4fb9-b6c2-d08249b01aaa"
            ],
            "c381d7fb-2267-455a-b191-e72a05d7b40d": [
              "3b7df147-4793-4a55-a2d9-46ec705d1ed3"
            ]
          },
          "positions": {
            "aebff88d-8508-4a5f-8f7d-fc400acefddb": {
              "col": 1,
              "row": 9,
              "height": 4,
              "width": "Infinity"
            },
            "fb723e6f-bc43-400f-a3ef-1c2f0870882a": {
              "col": 1,
              "row": 13,
              "height": 4,
              "width": "Infinity"
            },
            "c381d7fb-2267-455a-b191-e72a05d7b40d": {
              "col": 1,
              "row": 2,
              "height": 4,
              "width": "Infinity"
            },
            "3598b73b-e58d-47cd-8e9c-c2e6e883139e": {
              "col": 1,
              "row": 2,
              "height": 4,
              "width": 4
            }
          },
          "formatting": {
            "highlighting": []
          }
        }
      },
      "dashboard_state": {
        "widgets": {},
        "positions": {}
      },
      "owner": "admin",
      "created_at": "2019-11-21T11:53:33.574Z"
    },
    {
      "id": "5ddba69748428f127c537e72",
      "title": "fw stats",
      "summary": "",
      "description": "",
      "search_id": "5ddbab2148428f127c537f13",
      "properties": [],
      "requires": {},
      "state": {
        "a4bb8d87-3984-4d98-adfd-a0902360a433": {
          "selected_fields": [
            "source",
            "message"
          ],
          "static_message_list_id": null,
          "titles": {
            "widget": {
              "261e18ba-39b8-4e10-a0d8-645bdd3111de": "Message Count",
              "24e0c086-d409-4181-bbbc-0b2f47476d1f": "All Messages"
            }
          },
          "widgets": [
            {
              "id": "41b15ffd-f875-4414-8f81-9877b6dda0e2",
              "type": "aggregation",
              "filter": null,
              "config": {
                "row_pivots": [
                  {
                    "field": "timestamp",
                    "type": "time",
                    "config": {
                      "interval": {
                        "type": "auto",
                        "scaling": null
                      }
                    }
                  }
                ],
                "column_pivots": [],
                "series": [
                  {
                    "config": {
                      "name": null
                    },
                    "function": "card(action)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "card(alert)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "card(attack)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "card(app)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "card(bandwidth)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "card(apprisk)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "card(check_ET)"
                  },
                  {
                    "config": {
                      "name": null
                    },
                    "function": "card(check_misp)"
                  }
                ],
                "sort": [],
                "visualization": "line",
                "visualization_config": null,
                "formatting_settings": null,
                "rollup": true
              }
            }
          ],
          "widget_mapping": {
            "41b15ffd-f875-4414-8f81-9877b6dda0e2": [
              "a2884b8f-ee71-4581-b290-faaefaaf4835"
            ]
          },
          "positions": {
            "261e18ba-39b8-4e10-a0d8-645bdd3111de": {
              "col": 1,
              "row": 5,
              "height": 2,
              "width": "Infinity"
            },
            "24e0c086-d409-4181-bbbc-0b2f47476d1f": {
              "col": 1,
              "row": 7,
              "height": 6,
              "width": "Infinity"
            },
            "41b15ffd-f875-4414-8f81-9877b6dda0e2": {
              "col": 1,
              "row": 1,
              "height": 4,
              "width": "Infinity"
            }
          },
          "formatting": {
            "highlighting": []
          }
        }
      },
      "dashboard_state": {
        "widgets": {},
        "positions": {}
      },
      "owner": "admin",
      "created_at": "2019-11-25T10:01:50.037Z"
    }
  ]
}

**Comment by zambomarcell** [comment]
or one other

{
  "id": "5ddba69748428f127c537e73",
  "title": "fw stats2",
  "summary": "",
  "description": "",
  "search_id": "5ddbab2148428f124c537f13",
  "properties": [],
  "requires": {},
  "state": {
    "a4bb8d87-3984-4d98-adfd-a0902360a433": {
      "selected_fields": [
        "source",
        "message"
      ],
      "static_message_list_id": null,
      "titles": {
        "widget": {
          "261e18ba-39b8-4e10-a0d8-645bdd3111de": "Message Count",
          "24e0c086-d409-4181-bbbc-0b2f47476d1f": "All Messages"
        }
      },
      "widgets": [
        {
          "id": "41b15ffd-f875-4414-8f81-9877b6dda0e1",
          "type": "aggregation",
          "filter": null,
          "config": {
            "row_pivots": [
              {
                "field": "timestamp",
                "type": "time",
                "config": {
                  "interval": {
                    "type": "auto",
                    "scaling": null
                  }
                }
              }
            ],
            "column_pivots": [],
            "series": [
              {
                "config": {
                  "name": null
                },
                "function": "card(action)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(alert)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(app)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(appcat)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(appid)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(applist)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(apprisk)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(cat)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(catdesc)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(check_misp)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(check_misp_dst_ip)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(company)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(countapp)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(countweb)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(craction)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(crlevel)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(crscore)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(desc)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(direction)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dstcountry)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dstintf)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dstintfrole)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dst_ip)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dst_ip_geoip_city_name)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dst_ip_geoip_continent_code)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dst_ip_geoip_country_code2)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dst_ip_geoip_country_name)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dst_ip_geoip_dma_code)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dst_ip_geoip_ip)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dst_ip_geoip_region_name)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dst_ip_geoip_timezone)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dst_ip_geolocation)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(dst_port)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(duration)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(eventtype)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(gl2_message_id)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(host)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(hostname)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(identifier)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(incidentserialno)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(lanin)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(lanout)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(level)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(logdesc)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(logid)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(message)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(method)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(msg)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(policyid)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(policytype)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(poluuid)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(port)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(profile)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(program)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(proto)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(rcvdbyte)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(rcvddelta)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(rcvdpkt)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(reason)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(received_at)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(received_from)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(reqtype)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(sentbyte)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(sentdelta)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(sentpkt)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(service)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(session_id)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(sessionid)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(source)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(srccountry)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(srcintf)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(srcintfrole)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_ip)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_ip_geoip_city_name)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_ip_geoip_continent_code)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_ip_geoip_country_code2)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_ip_geoip_country_name)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_ip_geoip_ip)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_ip_geoip_location_lat)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_ip_geoip_location_lon)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_ip_geoip_region_name)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_ip_geoip_timezone)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_ip_geolocation)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(src_port)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(sslaction)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(subtype)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(syslog5424_pri)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(syslog_event_id)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(tags)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(trandisp)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(tranip)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(tranport)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(transip)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(transport)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(type)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(url)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(utmaction)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(vd)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(wanin)"
              },
              {
                "config": {
                  "name": null
                },
                "function": "card(wanout)"
              }
            ],
            "sort": [],
            "visualization": "line",
            "visualization_config": null,
            "formatting_settings": null,
            "rollup": true
          }
        }
      ],
      "widget_mapping": {
        "41b15ffd-f875-4414-8f81-9877b6dda0e2": [
          "a2884b8f-ee71-4581-b290-faaefaaf4835"
        ]
      },
      "positions": {
        "261e18ba-39b8-4e10-a0d8-645bdd3111de": {
          "col": 1,
          "row": 5,
          "height": 2,
          "width": "Infinity"
        },
        "24e0c086-d409-4181-bbbc-0b2f47476d1f": {
          "col": 1,
          "row": 7,
          "height": 6,
          "width": "Infinity"
        },
        "41b15ffd-f875-4414-8f81-9877b6dda0e2": {
          "col": 1,
          "row": 1,
          "height": 4,
          "width": "Infinity"
        }
      },
      "formatting": {
        "highlighting": []
      }
    }
  },
  "dashboard_state": {
    "widgets": {},
    "positions": {}
  },
  "owner": "admin",
  "created_at": "2019-11-25T10:01:50.037Z"
}

**Comment by alex-konn** [comment]
Hey @zambomarcell, sorry for not being able to get back to you earlier.
I was finally able to reproduce your error - there is obviously a bug in how path parameters are processed by our API browser.
This was only an issue when trying to update via PUT though. POST works fine. Can you confirm that?

**Comment by zambomarcell** [comment]
> Hey @zambomarcell, sorry for not being able to get back to you earlier.
> I was finally able to reproduce your error - there is obviously a bug in how path parameters are processed by our API browser.
> This was only an issue when trying to update via PUT though. POST works fine. Can you confirm that?

Sorry, i cant test it :(

**Comment by alex-konn** [comment]
No worries. Thanks for reporting it anyway! :+1:
