### ISSUE TITLE
Tests: Wrong name 'contenpacks' as directory path

### ISSUE THREAD

**Issue by dnsmichi** [Graylog2/graylog2-server#6882]
## Current Behavior

Not sure whether the test suite actually includes the contentpack tests if the directory is not named the same. Did not run any tests.

## Possible Solution

Rename the directory.

## Steps to Reproduce (for bugs)

Navigate to
https://github.com/Graylog2/graylog2-server/tree/master/graylog2-server/src/test/java/org/graylog2/rest/models/system

<img width="1110" alt="Screen Shot 2019-11-28 at 11 32 26" src="https://user-images.githubusercontent.com/382049/69799236-313bdd80-11d3-11ea-990f-71977bc791ce.png">

## Context

Reading the source to find out how to install a content pack via REST API.

## Your Environment

* Graylog Version: 3.1.3
* Elasticsearch Version: 6.8.5
* MongoDB Version: 4.0.0
* Operating System: CentOS 7
* Browser version: Version 78.0.3904.108

**Comment by mpfz0r** [comment]
> Not sure whether the test suite actually includes the contentpack tests if the directory is not named the same.

I'm not sure what you mean by `same`. The tests are running, and the tested class is
`org.graylog2.rest.models.system.contenpacks.responses.ContentPackInstallationRequest`
and the test is 
`org.graylog2.rest.models.system.contenpacks.responses.ContentPackInstallationRequestTest`

**Comment by dnsmichi** [comment]
Ok, then it is just naming problem, more cosmetic with the missing `t`. Since this class name is returned in case of API errors, one might look into possible bugs then - which I did by reading the source code.

**Comment by mpfz0r** [comment]
Ahh, and now I finally see the typo :-D
We'll fix that. Thank you :+1:
