### ISSUE TITLE
Query input autocompletion improvements

### ISSUE THREAD

**Issue by isaacegglestone** [Graylog2/graylog2-server#6909]
I've been informed that the original search bar issue that my team finds a lot more useful than the views search is going to be discontinued.  I would like to ask that it be kept as an optional configuration for views at minimum or to improve the views search to match some of the concerns.

**See my question on why the disparity here for source.**
[](https://community.graylog.org/t/search-bar-not-the-same-in-views-as-in-searches/12977)

Original auto complete functionality in the search feature has the following key benefits:

* Hitting tab includes the colon after the field name.
* Only need to type tab once to get full field name plus colon, vs two tabs to get only field name.
* Original Search includes helpers like exists, NOT exists etc in the autocomplete menu to make things faster.
* The search version of the message area allows you to click the magnifying glass and add fields to your search. We can't see this capability in the views version.

We don't use views at all for the above reasons.

Other complaints about the views search.

There doesn't seem to be any way to collapse the left hand portion of the screen to the left of the messages. This has field names in it and once selected we wish it to be collapsed so that we can see the message in full view.

This issue is also apparent in search view however its not quite as big as the views version. Also the  whole idea that we cannot collapse would be great to have fixed in  a new feature of views.

## Your Environment

* Graylog Version:  Graylog 3.1.3
* Elasticsearch Version: 6.5
* MongoDB Version: 3.6
* Operating System:   ( Linux 4.14.128-112.105.amzn2.x86_64)
* Browser version: Chrome (latest)

Deployed as pods in aws EKS using 
https://github.com/helm/charts/tree/master/stable/graylog
With docker image graylog/graylog:3.1.3

**Comment by dennisoelkers** [comment]
Hey @isaacegglestone, thanks for the input!

Keeping the original search bar is not an option at the moment, as the views are an almost complete rewrite of the current search functionality. We will constantly work on improving its features, especially auto-completion and you can expect it to be far superior to the current search bar in the next versions.

Good news is that the sidebar will be collapsible in 3.2 already. Your suggestions concerning the auto-completion probably make it into one of the next versions after that, as they are really small enough to fix quickly.

We are always thankful for all kinds of feedback, things you are missing or expect differently or stuff that you are happy about!

**Comment by dennisoelkers** [comment]
Most of the issues described in here have already been addressed:

```
* Hitting tab includes the colon after the field name. 
* The search version of the message area allows you to click the magnifying glass and add fields to your search. We can't see this capability in the views version.
```

This one will be included in one of the next versions:

```
* Original Search includes helpers like exists, NOT exists etc in the autocomplete menu to make things faster.
```

This one needs to be verified and potentially fixed for `3.3`:

```
* Only need to type tab once to get full field name plus colon, vs two tabs to get only field name.
```

**Comment by dennisoelkers** [comment]
```
* Only need to type tab once to get full field name plus colon, vs two tabs to get only field name.
```

The important part in here is that you have to press tab twice to get the first suggestion. This is unnecessary imo, the first suggestion should be focussed already.

**Comment by dennisoelkers** [comment]
There is no default setting for this in `react-ace`/`ace`, so we should invest some time boxed amount of effort to see if we can implement this using a custom action.
