### ISSUE TITLE
Add Permanent Link feature to views

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#6920]
## What?
The old search provided a Link to a message, where only the full message was displayed.
The new search uses the link but still shows the old search.

## Why?
In ticket systems it is useful to link to a specific message so  a user can work with it.

![Graylog - Message dc408c20-15d0-11ea-aeb5-00e18cb9c35a on graylog_36](https://user-images.githubusercontent.com/448763/70059232-b44ca180-15e0-11ea-95df-221806e64aa7.png)

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Fixed in #6994.
