### ISSUE TITLE
Allow setting the parsed JSON payload using the set_fields() method.

### ISSUE THREAD

**Issue by tuxknight** [Graylog2/graylog2-server#6963]
## What?

make pipeline works like json extractor

```
rule "json"
when
  // some condition
then
  let json = parse_json(to_string($message.some_field));
  set_fields(json);
end
```

## Why?

Sometimes users might want to parse and merge the JSON payload of a message
with the Graylog message without knowing the complete structure of the payload
or without having a fixed structure which could be selectively merged by using
the json_path() method.
Besides,  extractors are applied to single inputs, users might want to process their JSON payload with same business logic across many input sources.

## Your Environment

* Graylog Version:  Graylog 3.1.2+9e96b08
* Elasticsearch Version: 6.8
* MongoDB Version: 3.2
* Operating System: CentOS 7.7
* Browser version:  Chrome 79.0.3945.56

**Comment by jalogisch** [comment]
He @tuxknight 

I'm happy that you can already use that - but I'm sad that we did not document that really well

```
rule "extract-json"
when
    starts_with(to_string($message.message), "{") && ends_with(to_string($message.message), "}")
then
    let json = parse_json(to_string($message.message));
    let map = to_map(json);
    set_fields(map);
end
``` 

The `to_map` function has that option already documented but that might need to be a little more visible.

https://docs.graylog.org/en/3.1/pages/pipelines/functions.html#to-map
