### ISSUE TITLE
Search results filter uses local system time

### ISSUE THREAD

**Issue by Elemag** [Graylog2/graylog2-server#697]
It should respect the timezone set in the user's settings.

Our servers run in UTC and we're currently operating in EEST (UTC +3). All users in Graylog are configured to use UTC. But if I set a filter for messages between, for example
2014-08-24 00:00:00 and 2014-08-25 00:00:00
what I get are actually messages between 2014-08-23 21:00:00 and 2014-08-24 21:00:00
The filter seems to use systems' local time instead of the timezone set in the config.

**Comment by bernd** [comment]
There have been lots of fixes regarding time zone handling since August. Can you please re-open this if you still have these problems in Graylog 1.0.0? Thank you!
