### ISSUE TITLE
alerts/event definitions are visible for all `Alert Managers`

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#6976]
## Expected Behavior
Once defined the event definitions should be only visible for those that have the access right for the streams that are the source for the definition.

## Current Behavior
All `Alert Manager` can see all alert/event definition. 

## Possible Solution
In addition the `Alert Manager` role it should be checked if the user is able to access the stream that is taken as source for this event.

## Context
The old alerts worked stream based - so it was possible to give a role the ability to create their own alerts for their stream. With the new system all `Alert Manager` can always see all event definitions. 

This might expose data that should not be visible to other groups in Graylog. 

It should be possible (again) that if someone has access to data to create events/alerts based on the data he can see but not see/edit/delete all events/alerts by other users.

## Your Environment

* Graylog Version: 3.1.3

**Comment by mpfz0r** [comment]
I don't see this as a bug, but a missing feature.
The `Alert Manager` was meant to be a kind of super user for the new alerting.
The description reads `"Allows reading and writing all event definitions and event notifications (built-in)"`

We are aware that the new permissions system is currently lacking fine grained roles.
I think this should be discussed with @kroepke

**Comment by jalogisch** [comment]
From a user perspective this is a bug. Before the rights are stream based so each user could create on his streams alerts - now he can't and if he gets the (current) right for that he has access to everything.

Special if you have Graylog as a platform for log management and this current option will make it impossible and create the bottleneck in the ability to create/see alerts on your streams.

**Comment by bernd** [comment]
With the updated permissions system in 4.0 it is possible to share event definitions with users. Please open a new issue if there are still problems. Thank you!
