### ISSUE TITLE
Problem with report and views user/role migrations

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#6979]
## Expected Behavior

The migrations should not modify users and roles on every server start.

## Current Behavior

I am currently getting the following log messages on every server start:

```
2019-12-11 16:47:44,951 ERROR: org.graylog2.migrations.MigrationHelpers - Invalid user 'graylog-report', fixing it.
2019-12-11 16:47:44,952 INFO : org.graylog2.migrations.MigrationHelpers - graylog-report user is missing or invalid, re-adding it as a built-in user.
2019-12-11 16:47:44,994 INFO : org.graylog2.migrations.MigrationHelpers - Views User role is missing or invalid, re-adding it as a built-in role.
2019-12-11 16:47:45,215 ERROR: org.graylog2.migrations.MigrationHelpers - Invalid role 'Views Manager', fixing it.
2019-12-11 16:47:45,215 INFO : org.graylog2.migrations.MigrationHelpers - Views Manager role is missing or invalid, re-adding it as a built-in role.
```

It looks like we have a few conflicting migrations.

1. `graylog-report` user
    1. The `V20171012124000_AddReportUser` migration is adding the `graylog-report` user with a specific set of roles and permissions. It also updates the user on every reboot if the roles/permissions don't match the expected values
    1. The `V20191112121416_MakeReportUserViewsManager` migration modifies the `graylog-report` user on every reboot as well
    1. That means on every reboot we modify the `graylog-report` user twice
1. `Views User` role
    1. The `V20180817120900_AddViewsUsers` migration is adding the `Views User` role on every reboot
    1. The `V20191204000000_RemoveLegacyViewsPermission` role is removing the `Views User` role on every reboot
1. `Views Manager` role
    1. The `V20181220133700_AddViewsAdminRole` migration is adding or modifying the `Views Manager` role on every reboot
    1. The `V20191204000000_RemoveLegacyViewsPermissions` is modifying the `Views Manager` role on every reboot
    1. These two migrations overwrite their respective changes on every reboot

## Possible Solution

Since the `MigrationHelpers` methods check the current state on every reboot, we can probably just create a single migration that create the correct users and roles, instead of having several migrations that touch the same objects and overwriting their changes on every reboot.

- The `V20180817120900_AddViewsUsers` migration can be removed because `V20191204000000_RemoveLegacyViewsPermission` will delete that user again
- For the others we might want to create a single migration that ensures that the system has the correct roles and users.

## Steps to Reproduce (for bugs)

1. Restart graylog server
2. Check serer log file for lines that contain `MigrationHelpers`

## Your Environment

* Graylog Version: 3.2.0-SNAPSHOT rev ff86eb1d6

**Comment by dennisoelkers** [comment]
Fixed in #7202.
