### ISSUE TITLE
field missing when field name contains "/"

### ISSUE THREAD

**Issue by tuxknight** [Graylog2/graylog2-server#6988]
## Expected Behavior

expect all fields extracted from json

## Current Behavior

fields which name contains "/" are missing after json extractor.
most cases are kubernetes labels

## Steps to Reproduce (for bugs)

1. launch an input of type Raw/Plaintext TCP.

2. import this extractor to input
```
{
  "extractors": [
    {
      "title": "json",
      "extractor_type": "json",
      "converters": [],
      "order": 0,
      "cursor_strategy": "copy",
      "source_field": "message",
      "target_field": "",
      "extractor_config": {
        "list_separator": ", ",
        "kv_separator": "=",
        "key_prefix": "",
        "key_separator": "_",
        "replace_key_whitespace": false,
        "key_whitespace_replacement": "_"
      },
      "condition_type": "none",
      "condition_value": ""
    }
  ],
  "version": "3.1.3"
}
```
3. send message to input
```
echo '{"labels": {"io.k8s/name":"node","io.aws":"host"}}' |nc 10.15.200.23 5555
```

## Context
many kubernetes pod labels contain "/" and all these lebels will be missing in graylog.

## Your Environment

* Graylog Version:  Graylog 3.1.3
* Elasticsearch Version:  6.8
* MongoDB Version:  3.6
* Operating System:  CentOS Linux release 7.7.1908 (Core)
* Browser version: Chrome 79

**Comment by jalogisch** [comment]
he @tuxknight 

did you see the same behaviour when you use the processing pipeline for processing?

In addition to that, fieldnames have some limits:


- Lowercase only
- Cannot include `\`, `/`, `*`, `?`, `"`, `<`, `>`, `|`, ` ` (space character), `,`, `#`, `:`, `.`
- Cannot start with `-`, `_`, `+`
- Cannot be `.` or ``..`
- Cannot be longer than 255 bytes (note it is bytes, so multi-byte characters will count towards the 255 limit faster)

So you really want to create some processing rules that fix the fieldnames if you can't avoid such characters.

**Comment by tuxknight** [comment]
@jalogisch I see. I will try to handle the `/` thing before sending to graylog.
But is it possible to change that limitation in the future ?

**Comment by jalogisch** [comment]
@tuxknight it is not very likely as this limitations are given from Elasticsearch what is used as storage.

**Comment by tuxknight** [comment]
Thanks. Graylog is a great product.
