### ISSUE TITLE
Time unit interval selection for month converts to minute

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#6989]
## Expected Behavior
When selecting `1 month` I expect a bucket size of `1 month` not `1 minute`.

## Current Behavior
The `PivotConfigGenerator.js` takes the `timeunit` (month) and simply cuts the first
letter. But for month we need a uppercase `M` not a lowercase `m` which would mean minute.

## Possible Solution
Instead of only taking the first letter of the unit we should do a mapping here:
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.js#L18

## Steps to Reproduce (for bugs)
1. Create a new search
2. Edit the histogram
3. Toggle the timestamp automatic interval
4. Select `1 month`
5. Change the Result window to `30 days`
6. Watch your browser die while trying to render `43200` buckets.

## Your Environment
* Graylog Version: Graylog 3.2 pre alpha

**Comment by dennisoelkers** [comment]
Fixed in #7140.
