### ISSUE TITLE
Radio Input (AMQP) heartbeat

### ISSUE THREAD

**Issue by ThePsyjo** [Graylog2/graylog2-server#699]
Radio Inputs should try to contact to the broker periodically. If the connection is lost and the reconnect was not triggered, a graceful shutdown via wi or SIGTERM will bring the server to hang at  

org.graylog2.system.shutdown.GracefulShutdown - Attempting to close input org.graylog2.inputs.radio.RadioAMQPInput.53fc562fe4b062015e8b2a1f [Graylog2 Radio Input (AMQP)].

Obviously the message processing stops too.

**Comment by kroepke** [comment]
This is being address with the fix to #1010 and will be released in the next 1.1.0 beta-3.

I'll close this now, if there are still problems afterwards, please reopen this or the reference issue.

Thanks,
Kay
