### ISSUE TITLE
Add support for old dashboards in content packs for new views

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#7028]
## Expected Behavior
When installing a Content Pack with a old dashboard the content pack facade should
transform the old dashboard entity to a new view entity and install it as a new view dashboard.

## Current Behavior
The content pack installation will fail.

## Possible Solution
Add a new facade which will only transform old entities in new view entities and use
the ViewFacade to install them.

## Your Environment
* Graylog Version: 3.2 dev (573ce6cfa361dbbc7bf47a3903400b0fcc463cc6)

**Comment by danotorrey** [comment]
The content pack installation error due to dashboards can be reproduced with this content pack: 
[content-pack.json.txt](https://github.com/Graylog2/graylog2-server/files/4018741/content-pack.json.txt)
