### ISSUE TITLE
Ship a better/higher default configuration for output_batch_size

### ISSUE THREAD

**Issue by 2ion** [Graylog2/graylog2-server#705]
We see significantly improved/less CPU usage by Elasticsearch when setting output_batch_size = 1000 or higher even when dealing with lower loads (around 250 msg/s). The default configuration value of 25 seems to be quite low if not too low, it might be good to raise it a bit. It probably would be also useful to have the batch size adjust dynamically based on relevant metric values.

**Comment by joschi** [comment]
The default output batch size is now 500 (per f43bc8a2c49b07d8921269daf05d14cf0e0ba808).
