### ISSUE TITLE
Test container don't get cleaned up

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#7078]
If you execute ES integration tests (`MessagesIT`) from IntelliJ, there is no cleanup afterwards. I keep getting more docker instances:
```
$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                              NAMES
fe8a327d6525        elasticsearch:5.6.12   "/docker-entrypoint.…"   2 hours ago         Up 2 hours          0.0.0.0:32780->9200/tcp, 0.0.0.0:32779->9300/tcp   quizzical_bell
29951f3f8551        elasticsearch:5.6.12   "/docker-entrypoint.…"   2 hours ago         Up 2 hours          0.0.0.0:32777->9200/tcp, 0.0.0.0:32776->9300/tcp   heuristic_agnesi
471517d0454d        elasticsearch:5.6.12   "/docker-entrypoint.…"   2 hours ago         Up 2 hours          0.0.0.0:32774->9200/tcp, 0.0.0.0:32773->9300/tcp   wonderful_austin
```
As a workaround one can activate the reuse feature:
`echo 'testcontainers.reuse.enable=true' > ~/.testcontainers.properties`

**Comment by bsideup** [comment]
FYI [it was fixed in 1.12.4](https://github.com/testcontainers/testcontainers-java/pull/2051), consider updating

**Comment by mpfz0r** [comment]
@bsideup excellent! thanks for the heads up :)

**Comment by bernd** [comment]
@mpfz0r I just created https://github.com/Graylog2/graylog2-server/pull/7116 which fixes the issue for me. Can you please check if it's fixed for you as well? Thank you!
