### ISSUE TITLE
Worldmap widget shows a broken map

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7095]
Currently the worldmap widget shows a broken map:

![image](https://user-images.githubusercontent.com/46300478/71896886-3470a480-3155-11ea-89f5-217c05a71519.png)

It looks like the leaflet style (leaflet.css) is missing. I am currently figuring out how this worked before. When I add the needed css file, everything works like expected.

* Graylog Version: 3.2 beta

**Comment by dennisoelkers** [comment]
Fixed in #7106.
