### ISSUE TITLE
Event/Alert creation safety net

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#7096]
We should find a way to protect users from firing too many alerts.

I've seen a case, where a user created an Event definition with a email Notification that did not have a grace period set.
The definition resulted in 39 million events, where each of them triggered an email to be sent.
This stalled further event processing, because the scheduler was busy sending emails for
over three weeks.

Possible solutions: 
 - Don't allow the grace period to be disabled, but to be only to be set as low as one second.
 - Rate limit notification trigger creation to max  1000/minute?

**Comment by mpfz0r** [comment]
Another related feature would be showing the backlog of the scheduler,
and being able to cancel pending email notifications for a certain event notification.

**Comment by ozzi-** [comment]
same problem, only solution is waiting until ten thousand mails are sent? seriously 😂

**Comment by bigjohns97** [comment]
I am having this problem as well, thinking about starting over.

**Comment by theherodied** [comment]
Same problem here. Following.

**Comment by kvladimirovich10** [comment]
Same problem.

**Comment by TheNi** [comment]
same problem. Following.

**Comment by okwute419** [comment]
Is documentation needed here? We have a ticket to document "**Safety net to prevent excessive notification rate**". Just checking to see if this ticket is still relevant. @mpfz0r

**Comment by mpfz0r** [comment]
@okwute419  yeah, documentation would be nice. The ticket title is a bit misleading, though. instead of a safety net, we implemented the possibility to see how many notifications are queued plus a button to delete them.
see #12084 for details

**Comment by okwute419** [comment]
Can I discuss this further with you, so we can align on what the ask is?  I can set up a quick call for tomorrow or at your best convenience.

**Comment by mpfz0r** [comment]
@okwute419 we could try today between 4pm and 6pm CEST
