### ISSUE TITLE
Left Side of Widget Edit Mode in Aggregation Builder should be scrollable

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#7105]
Steps to reproduce:

1. Edit Aggregation widget
2. Zoom in just enough so the sidebar to the left of the graph is not shown completely
3. Try to scroll it to reach hidden controls

![Screen Shot 2020-01-08 at 10 45 06](https://user-images.githubusercontent.com/41929/71967875-3f364280-3204-11ea-8a55-aa326081dc28.png)

**Comment by linuspahl** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/pull/7114
