### ISSUE TITLE
Data Table with more fields than horizontal space is not scrollable inside the AggregationBuilder

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7109]
This issue is related to #7091. The fix for #7091 reenables the horizontal scrolling for the data table. The scroll bar also exists when editing the data table with the aggregation builder, but is not visible, due to some height calculation for the aggregation builder layout.

![image](https://user-images.githubusercontent.com/46300478/71969820-bf11dc00-3207-11ea-9c11-e4348edb09ec.png)

When adjusting the aggregation builder layout, the new layout should be flexible enough to fix #7105 as well.

## Steps to Reproduce (for bugs)
1. Open the aggregation builder
2. Create a data table with many table columns
3. Try to scroll horizontically

## Your Environment
* Graylog Version: 3.2 beta2

**Comment by dennisoelkers** [comment]
Fixed in #7114.
