### ISSUE TITLE
No audit log entry for URL whitelist change

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#7118]
## Expected Behavior

Adding or changing an URL whitelist entry should emit an audit log event.

## Current Behavior

I am getting an audit log event for the cluster config change, but I should get an audit event for the URL whitelist change:

![image](https://user-images.githubusercontent.com/461/72005683-7b8e9080-324e-11ea-8bc8-e50033985713.png)

## Possible Solution

I guess the URL whitelist UI is not using the `UrlWhitelistResource` (path: `/system/urlwhitelist`) resource, but the generic `ClusterConfigResource` (path: `/system/cluster_config`). If we change that, the audit event should be created.

The fix for this needs to be backported to 3.1.

## Steps to Reproduce (for bugs)

1. Navigate to "System / Configuration"
2. Open URL whitelist settings
3. Change or add whitelist entry
4. Check audit log under "Enterprise / Audit Log"

## Your Environment

* Graylog Version: 3.2.0-beta.3-SNAPSHOT

**Comment by danotorrey** [comment]
Fixed by https://github.com/Graylog2/graylog2-server/pull/7122
