### ISSUE TITLE
Missing message table sorting options

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#7119]
## Expected Behavior

The search page in 3.1 and earlier offered the possibility to sort the message table based on fields in the table. (ascending and descending)

![image](https://user-images.githubusercontent.com/461/72009540-687fbe80-3256-11ea-80be-6832d3fd8af1.png)

## Current Behavior

The message list widget in 3.2 doesn't have this.

## Your Environment

* Graylog Version: 3.2.0-beta.3-SNAPSHOT

**Comment by kroepke** [comment]
As the backend should not trivially allow it, we should look at supporting multiple sort orders in the same mechanism.

**Comment by dennisoelkers** [comment]
- Changing the sort field and direction should be possible from the table header and the widget edit mode
- Changing the sort field/direction resets pagination of this message table widget
