### ISSUE TITLE
Font Awesome css is getting imported multiple times

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7121]
## Expected Behavior
The font awesome css should only get imported once. 
Because we are using icons everywhere, it should be okay to import it once globally.
 
## Current Behavior
Currently the font awesome css is getting imported (in my case) eight times. The behavior is maybe related to the plugin system.

## Possible Solution
One possible solution could be adding the styles to the the vendor bundle by creating a shared asset folder for the font dependencies.

## Steps to Reproduce (for bugs)
You can easily test this by searching for "Font Awesome" in the page `<head>`. 

## Your Environment
* Graylog Version: 3.2 beta2

**Comment by Gaya** [comment]
Think it doesn't happen anymore. Can only find one style tag with font awesome CSS.

Can we close this @linuspahl ?

**Comment by linuspahl** [comment]
@Gaya You are right, this is no longer a problem.

**Comment by Gaya** [comment]
@linuspahl 🙌
