### ISSUE TITLE
Field terms are not handled correctly

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#7127]
## Expected Behavior

"_Show terms of message_" should show the **unique** terms of message, because that is what terms are for.

<img width="910" alt="Screenshot 2020-01-09 at 16 39 50" src="https://user-images.githubusercontent.com/24830359/72076859-f4e5bc00-32fe-11ea-9242-ec8673c826e6.png">

## Current Behavior

Duplicate terms are showed multiple times.

<img width="909" alt="Screenshot 2020-01-09 at 16 38 10" src="https://user-images.githubusercontent.com/24830359/72076900-04fd9b80-32ff-11ea-9654-6927b7427d46.png">

The message terms in Elasticsearch
```
{
  "_index" : "beats_90days_5",
  "_type" : "message",
  "_id" : "f-C7im8BRo-EVLluusuc",
  "_version" : 1,
  "found" : true,
  "took" : 1,
  "term_vectors" : {
    "message" : {
      "terms" : {
        "aaa" : {
          "term_freq" : 2
        },
        "bbb" : {
          "term_freq" : 1
        }
      }
    }
  }
}
```

## Possible Solution

Show only unique terms.

## Steps to Reproduce (for bugs)

1. Index message through Elasticsearch api
```
curl -X POST "localhost:9200/<your test index name>/message/" -H 'Content-Type: application/json' -d'
{
    "timestamp" : "2020-01-09 12:00:00.000",
    "message" : "aaa aaa bbb"
}
'
```
2. Open the message from Graylog user interface
`https://<your graylog url>/messages/<your test index name>/<message id>`
3. Click "Show terms of message"

## Context

With larger messages the terms box gets cluttered because it is not filtered to contain only unique terms.

## Your Environment

* Graylog Version: 3.0.1 / 3.1.2
* Elasticsearch Version: 6.7.2 / 6.8.0

**Comment by bernd** [comment]
Closing this issue because the terms feature doesn't exist anymore in the new search page.
