### ISSUE TITLE
HTTP Alarm callbacks 

### ISSUE THREAD

**Issue by ryanaverill** [Graylog2/graylog2-server#713]
I'm testing v0.21.0-beta4 and I found that when trying HTTP alarm callbacks, they aren't firing faster than one every minute or so. Is this intended or can it be changed?

My alert condition is set to: 
Alert is triggered when there are more than 0 messages in the last minute. Grace period: 0 minutes. 

Amazing new feature - on an already incredible project btw!

**Comment by s-thornton** [comment]
> The alarm callbacks are currently only being checked every 60 seconds. This value is hard coded and can't be configured in Graylog2.

Is this still the case in the current iteration of Graylog2?

**Comment by joschi** [comment]
@s-thornton No, see [`alert_check_interval`](https://github.com/Graylog2/graylog2-server/blob/2.0.3/misc/graylog.conf#L360-L362).
