### ISSUE TITLE
Cannot log into Graylog backend 3.1.31-1 ova

### ISSUE THREAD

**Issue by giorsgeks** [Graylog2/graylog2-server#7139]
### Steps to reproduce the problem

1. Cannot log into Graylog ova web interface, says wrong password, after checking /etc/graylog/server/server.conf file I find out there are many checksums in password_secret and root_password_sha2 lines, after deleting line root_password_sha2 = and regenerating checksum I logged in successfully.

![image](https://user-images.githubusercontent.com/4181698/72130395-13d96200-3382-11ea-928d-61d5889bc5f9.png)

### Environment

* Sidecar Version:
* Graylog Version: 3.2.3.1-ova
* Operating System:
* Elasticsearch Version:
* MongoDB Version:

**Comment by jalogisch** [comment]
You might want to read the Documentation about what this setting is about.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
