### ISSUE TITLE
noob install problem

### ISSUE THREAD

**Issue by skazal** [Graylog2/graylog2-server#714]
I'm trying to install graylog2 per the instructions for using 'yum' on a RHEL 6 host  (a new experience for me) and it is failing, can anyone please help?

```
$  sudo rpm -Uvh http://packages.graylog2.org/repo/packages/graylog2-0.21-repository-centos6_latest.rpm
[svc-mssc@vcld14rsafhas01 yum.repos.d]$  sudo rpm -Uvh http://packages.graylog2.org/repo/packages/graylog2-0.21-repository-centos6_latest.rpm
Retrieving http://packages.graylog2.org/repo/packages/graylog2-0.21-repository-centos6_latest.rpm
Preparing...                ########################################### [100%]
        package graylog2-0.21-repository-centos6-1.0.0-3.noarch is already installed
$ sudo yum install graylog2-server graylog2-web
Loaded plugins: rhnplugin
This system is receiving updates from RHN Classic or RHN Satellite.
http://packages.graylog2.org/repo/el/6Server/0.21/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: graylog2. Please verify its path and try again
```

Thanks,
 Skazal

**Comment by roddydairion** [comment]
I'm still having the same issue 
`[root@centos-1gb-nyc2-01 /]# yum -y install graylog2-server graylog2-web
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirrors.lga7.us.voxel.net
 * epel: mirror.us.leaseweb.net
 * extras: mirror.us.leaseweb.net
 * updates: mirror.cs.uwp.edu
https://packages.graylog2.org/repo/el/6/1.3/i386/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: graylog. Please verify its path and try again
`

Can anybody help please?

**Comment by roddydairion** [comment]
For those of you who are still having the PYCURL ERROR 22 issue. 
If it's not created already then create a repo in 
`/etc/yum.repos.d/graylog2.repo`
Overwrite with 
`[graylog2]
name=graylog2
baseurl=http://packages.graylog2.org/repo/el/$releasever/0.21/x86_64/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-graylog2
`
`# yum -y install graylog2-server graylog2-web`
This should now install the graylog server. You should also note that /etc/graylog/server/server.conf is now /etc/graylog2.conf 

Hope this helps.
