### ISSUE TITLE
Search state is not reflected in history/URL

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#7144]
## Expected Behavior
When changing the query text, reload interval or time frame, I expect the URL and browser history to reflect that state so that both reload and back/forward navigation works.
This was also the behavior of the previous search pages.

## Current Behavior
Neither URL nor history state reflects any changes made on the page, which causes using the browser navigation or reload to lose the user's state.

## Possible Solution
Add a limited amount of state to the URL hash and use it to populate the store's state when loading the page initially. This would also allow quick copy/paste sharing of simple searches (OTOH actually sharing it is obviously out of scope here).

## Steps to Reproduce (for bugs)
1. Navigate to "System" menu.
2. Navigate to "Search".
3. Enter query string "source:example".
4. Use browser back button.
This then takes you back to the system menu instead of the empty search.

Other changes that demonstrate this behavior include time range selection and stream selection.

## Context
Making simple changes about the search is one of the tasks users perform the most and to have no means of easily navigating back and forth makes it very difficult to use.
Additionally, this is a direct breaking change to how the search page behaved before, which means a lot of people will struggle with it.

## Your Environment

* Graylog Version: 3.2.0-beta.2

**Comment by kroepke** [comment]
I think at least the three main components of the search bar should be reflected in the state:

- query string
- time range selection
- stream selection

**Comment by gimmic** [comment]
Improving this will also allow for better use of breadcrumbs and branching search history/pathing. I've seen some really nice features in another commercial product which generates a branching tree view of search history, allowing you to jump back to prior searches and see the cascading search branches from that point(if that makes sense).

![image](https://user-images.githubusercontent.com/568957/72355217-a17fbf00-36ac-11ea-83cf-43011d13b119.png)

**Comment by kroepke** [comment]
I like that idea! We will be expanding on search history in Graylog 3.3 and certainly are open for suggestions :)
