### ISSUE TITLE
Context menu for fields is off in search sidebar for long field names

### ISSUE THREAD

**Issue by alex-konn** [Graylog2/graylog2-server#7146]
The context menu for fields in the search sidebar opens to the right of the field name element. This can be far to the right of the entire search bar for long field names.
This is probably rarely an issue in practice, but it looks related to what @linuspahl describes in #7132. We might need a general fix for context menus.

## Expected Behavior
The context menu should open at the cursor position or right next to the sidebar, not far out in the middle of the screen.

## Current Behavior
![fields-context-menu-far-right](https://user-images.githubusercontent.com/45592524/72167155-e1a02280-33ca-11ea-84ee-2518f3c1569f.gif)

## Your Environment
* Graylog Version: 3.2.beta2

**Comment by dennisoelkers** [comment]
Related to #7132.

**Comment by linuspahl** [comment]
Good point, a more dynamically positioned context menu would be great.
Regarding this issue,  increasing the default field list width could also reduce the confusion.

I would really appreciate a dynamic width, but all list items have an absolute position. Looks like this made sense for a previous implementation, but now we could also use a normal list layout and get rid of the `FixedSizeList` component from `react-window`.

**Comment by kmerz** [comment]
Fixed by https://github.com/Graylog2/graylog2-server/pull/7216
