### ISSUE TITLE
Migrate legacy API endpoints which are not working anymore (dashboards/saved searches)

### ISSUE THREAD

**Issue by alex-konn** [Graylog2/graylog2-server#7151]
For Dashboards API:

For `3.3`:
  - [x] Move current dashboards resource to `/legacy/dashboards`
  - [x] Move new dashboards resource to `/dashboards`
  - [x] Redirect from `/views/dashboards` to `/dashboards`
  - [x] Make frontend use `/dashboards` instead of `/views/dashboards`
  - [x] Add notice to upgrade notes that dashboards API format has changed

For `4.0`:
  - [x] Remove `/legacy/dashboards` route
  - [x] Remove `/views/dashboards` redirect
  - [x] Add notice to upgrade notes that `/views/dashboards` was removed
  - [x] Add notice to upgrade notes that legacy API was removed

For Saved Searches API:

For `3.3`:
  - [x] Move current saved searches resource to `/legacy/search/saved`
  - [x] Move new search resource to `/search/saved`
  - [x] Redirect from `/views/savedSearches` to `/search/saved`
  - [x] Make frontend use `/search/saved` instead of `/views/savedSearches `
  - [x] Add notice to upgrade notes that saved searches API format has changed

For `4.0`:
  - [x] Remove `/legacy/search/saved` route
  - [x] Remove `/views/savedSearches` redirect
  - [x] Add notice to upgrade notes that `/views/savedSearches` was removed
  - [x] Add notice to upgrade notes that legacy API was removed

Refs #7527.
Refs #8007.

**Comment by dennisoelkers** [comment]
Fixed in #8007, #8199.
