### ISSUE TITLE
Time based bar charts with a single value do not render correctly

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#7167]
## Expected Behavior
When rendering a time based bar chart with a single value, the user expects a broad bar
which is as broad as the time bucket.

## Current Behavior
Since we do not tell plotly how wide a time bucket is, it tries to calculated on its own, but since
it does not have a second data point to calculate the bucket size it assumes it to be really small.

## Possible Solution
We have the bucket size with which we aggregated the data points, we can tell plotly how wide
we want the bucktes (bars) to be.
https://plot.ly/javascript/bar-charts/#customizing-individual-bar-widths

## Steps to Reproduce (for bugs)
1. Create a time based (row pivot is a timestamp) bar chart widget.
2. Search for a time range with a single data point.

![Graylog (43)](https://user-images.githubusercontent.com/448763/72328568-7056bd00-36b3-11ea-992f-4d9844418a13.png)

## Your Environment
* Graylog Version: Graylog beta 3 (e5b97c8795774bdc3a66753f5c0ba4f337aee3ed)

**Comment by tocomo** [comment]
And sometimes it is not rendered at all.
![Screenshot from 2020-03-07 13-45-12](https://user-images.githubusercontent.com/3032624/76143738-3b933080-607a-11ea-91ea-da3c59ecd004.png)

**Comment by dmuntean** [comment]
I can confirm we are experiencing the same bar chart graph behaviour with Graylog version 3.2.4

**Comment by linuspahl** [comment]
Hello @tocomo,
I am currently working on this issue and tried to reproduce the described problem. I've mocked the search result (One message with the timestamp `2020-03-07 01:04:21 +01:00`) and used the same time range, but could not reproduce the bug.

If you can still work with the displayed dashboard, it would be great to know:
* in which way the search criteria of each widget is different
* if you see the search result, when you create a bar chart with the row pivot `timestamp` and the metrics `count()

**Comment by tocomo** [comment]
Now you have three different result count per widget.  The search range is 20 ms!!
![Screenshot from 2020-06-17 11-10-05](https://user-images.githubusercontent.com/3032624/84880579-faed7f00-b08c-11ea-93a8-d31458a94d4d.png)
![Screenshot from 2020-06-17 11-09-46](https://user-images.githubusercontent.com/3032624/84880481-d98c9300-b08c-11ea-9abf-c8926ec6b93a.png)

**Comment by tocomo** [comment]
Found it.  Pivot configuration was not automatic anymore. So 1 minute is larger then the result range!

**Comment by dennisoelkers** [comment]
@tocomo: Don't be surprised, i did hide your comment, as it was containing unmasked personal information (url at the bottom).

**Comment by linuspahl** [comment]
@tocomo Thanks a lot for your response, it is good to know that this causes the problem.
We have an issue for this behaviour https://github.com/Graylog2/graylog2-server/issues/6997 and will discuss the prioritization, due to your feedback.
