### ISSUE TITLE
multiline payload in additional fields

### ISSUE THREAD

**Issue by ThePsyjo** [Graylog2/graylog2-server#718]
using v0.20.6

Additional fields have all linebreaks removed and replaced by a whitespace. This makes it hard to read fields like 'stdout' or 'stderr' in the webinterface.

This is how i generate these 2 fields: 
```python
'_stdout': '\n'.join((l.strip() for l in tmpout)),
'_stderr': '\n'.join((l.strip() for l in tmperr)),
```

Spec says
`_[additional field] string (UTF-8) or number ... The verifying regular expression is: ^[\w\.\-]*$`
Why not \n ?

**Comment by bernd** [comment]
This seems to work now in Graylog 1.1.6. See the "issue" field in the screenshot.

![wuxhttyjuuubaaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/461/9173807/d086b618-3f7c-11e5-865b-611be10ed897.png)

Closing this issue now, please re-open if you still have problems. Thank you!
