### ISSUE TITLE
Data table shows "Empty Value" indicator for deduplicated fields

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#7181]
In data tables with multiple row pivots, values which are common between two rows are deduplicated and not supposed to be shown. In 3.2, instead of showing a blank cell, the `Empty Value` indicator is shown, which is supposed to be used in cases where the actual field value is an empty string.

**Comment by alex-konn** [comment]
Same thing happens in data tables where 0s should be shown.

![Screenshot from 2020-01-15 12-06-07](https://user-images.githubusercontent.com/45592524/72429397-2394e400-3790-11ea-903d-bdda5112c743.png)
