### ISSUE TITLE
Saving a search and defining spaces for the title, results in an error

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7192]
The backend already validates, if the title only consists of spaces, when saving a search and throws an error. This case should also be validated in the frontend.

## Steps to Reproduce
1. Open the search page
2. Open the dialog to save a search
3. Only define spaces for the title
4. Click on "Create new"

## Your Environment
* Graylog Version: 3.2.0-beta.4-SNAPSHOT

**Comment by dennisoelkers** [comment]
Not an issue anymore.
