### ISSUE TITLE
"Loading" and "Deleting" a saved search results in an empty looking list item.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7193]
Opening the overview for saved searches (on the search page) and clicking on the "Load" or "Delete" button, adds the `active` class for the selected list items, which changes the font color to "white".

![image](https://user-images.githubusercontent.com/46300478/72506994-52b85d80-3843-11ea-95f3-75a68a492518.png)

## Steps to Reproduce (for bugs)
1. Open the search page
2. Open the saved searches overview modal
3. Click on delete
4. Click on cancel in the browser dialog

## Your Environment
* Graylog Version: 3.2.0-beta.4-SNAPSHOT

**Comment by dennisoelkers** [comment]
Fixed in #7226.
