### ISSUE TITLE
Creating a new Dashboard and saving it redirects to views/[ID]

### ISSUE THREAD

**Issue by ousmaneo** [Graylog2/graylog2-server#7201]
![Kapture 2020-01-16 at 10 52 21](https://user-images.githubusercontent.com/1381455/72519035-7f25a700-384e-11ea-9319-96f295e99bcb.gif)

As you can see in the screenshoot, saving a new dashboard redirects to the new dashboard page but the url references views.

## Expected Behavior

The url of a newly created dashboard should be dashboard/[ID]

## Steps to Reproduce (for bugs)

1. Go to Dashboard 
2. Click Create new dashboard
3. Click Action => Save as 

## Your Environment

* Graylog Version: Graylog 3.2.0-beta.4-SNAPSHOT

**Comment by kmerz** [comment]
Fixed by https://github.com/Graylog2/graylog2-server/pull/7225
