### ISSUE TITLE
Message list widget pagination error is not getting cleared

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7204]
Due to the elastic search result window limit, an error will be displayed inside the message list widget, when clicking on a page which message count exceeds the limit.

This error is still visible, when executing a completely new search afterwards.

![image](https://user-images.githubusercontent.com/46300478/72523260-b486c080-385f-11ea-8ce9-2f22c330b521.png)

## Steps to Reproduce
1. Open the search page
2. Execute a search with many results (more 10000 messages, with default settings)
3. Click e.g. the last possible page, to see the error
4. Execute a new search

## Your Environment
* Graylog Version: 3.2.0-beta.4-SNAPSHOT

**Comment by dennisoelkers** [comment]
Fixed in #7268.
