### ISSUE TITLE
Opening dashboard share modal, throws an API error, when sharing is not configured

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7208]
When opening the dashboard share modal, the API throws a 404. 

```
GET http://localhost:9000/api/views/[view-id]/share 404 (Not Found)
backend.js:6 There was an error fetching a resource: cannot GET http://localhost:9000/api/views/[view-id]/share (404). Additional information: HTTP 404 Not Found
```

This is not the case once the user configured any kind of sharing for the dashboard.

## Steps to Reproduce (for bugs)
1. Create a new Dashboard
3. Save the dashboard (Actions -> Save as)
2. Click on Actions -> Share

## Your Environment
* Graylog Version: 3.2.0-beta.4-SNAPSHOT

**Comment by dennisoelkers** [comment]
This is kinda working as designed. If a view has not been shared, the endpoint returns a 404. The only impact is an error logged to the console, although the 404 is handled in the relevant store. The only thing left to do is preventing logging the error in `FetchProvider`.

**Comment by dennisoelkers** [comment]
Fixed, dashboard share modal was reimplemented for new permissions functionality.
