### ISSUE TITLE
Unify implemented modals

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7229]
There are some modals which behave differently compared to others. All problems or differences are related to the used Modal component. We should unify all implementations by using only `BootstrapModalWrapper` or `BootstrapModalForm` (for forms).

The `BootstrapModalForm` is missing in:
- `BigDisplayModeConfiguration` (fixed in #7582)
- `QueryTitleEditModal` (fixed in #7571)
- `ShareViewModal` (if possible, otherwise we will need to implement the `BootstrapModalWrapper`) (fixed in #7571)
- `ViewPropertiesModal` (fixed in #7249)

The `BootstrapModalWrapper` is missing in:
- `DebugOverlay` (fixed in #7571)
- `EditWidgetFrame`

This will fix the following problems / behaviour:
- `ViewPropertiesModal`, click on X Icon is not working
- `BigDisplayModeConfiguration` - click on backdrop is possible
- `ShareViewModal` - click on backdrop is possible

Besides this unification, we should disable the backdrop for the ParameterDeclarationForm (enterprise), by removing the backdrop prop for the `BootstrapModalWrapper`

These improvements should also fix https://github.com/Graylog2/graylog2-server/issues/2406

* Graylog Version: Graylog 3.2.0-beta.4-SNAPSHOT

**Comment by bernd** [comment]
@linuspahl There are quite a few merged PRs that mention this issue. Can it be closed? :smile:

**Comment by linuspahl** [comment]
Got fixed with #7582, #7571  and #7249.
