### ISSUE TITLE
Unable to edit saved search description

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#7239]
## Expected Behavior

A user should either be able to edit the description of a saved search or we shouldn't show the description.

## Current Behavior

I have a few saved searches that have been migrated from version 3.1. For the migrated ones the UI shows a description:

![image](https://user-images.githubusercontent.com/461/72821934-86dfb400-3c71-11ea-9e49-ed605df64ab2.png)

But I am unable to edit the description for new saved searches:

![image](https://user-images.githubusercontent.com/461/72821997-9f4fce80-3c71-11ea-98b4-53a75c29b5f7.png)

## Steps to Reproduce (for bugs)

1. Start a Graylog 3.1 server
2. Create a saved search in the old search UI
3. Upgrade to Graylog 3.2-beta
4. Check saved searches menu
5. Add new saved search

## Your Environment

* Graylog Version: 3.2.0-beta.4-SNAPSHOT (rev ee3c87c)

**Comment by linuspahl** [comment]
Thanks for the hint! With https://github.com/Graylog2/graylog2-server/pull/7238 we are no longer displaying the summary of a saved search.
