### ISSUE TITLE
Always run alert checks at the first second of a minute

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#724]
The alert annotation of a chart may be off with the actual chart data because the chart always shows full minute buckets and the alert check may have run somewhere in between.

![screen shot 2014-09-21 at 20 02 37](https://cloud.githubusercontent.com/assets/35022/4349530/7fc9da5a-41b9-11e4-9732-a2cc6a780863.png)

This example triggers alerts at a value higher than 25. You see that the alert annotation is not always under a bucket/bar with more than 25 messages. This is very confusing. (Disregard the first row of alerts which were based on another threshold)

Important: Wait at least 60 seconds before running the first check to avoid false positives triggered by not enough available data.

**Comment by bernd** [comment]
This should not be an issue anymore with the new alerting since 3.2. Please open a new issue if you still have this problem. Thank you!
