### ISSUE TITLE
Message list pagination does not work for dashboards

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7243]
It looks like the pagination of a message list widget does not work anymore, in the context of  dashboard. Clicking on another page results in an empty list. Having a look at the related request the new `total_results` number is wrong and the result `messages` list is empty.

## Steps to Reproduce
1. Create a dashboard
2. Create a message list widget
3. Define a time range for the widget, to receive many results
4. Use pagination

## Your Environment
* Graylog Version: Graylog 3.2.0-beta.4-SNAPSHOT

**Comment by alex-konn** [comment]
I think it's a frontend issue. Upon clicking on a page number in the message list widget the next search execution request is submitted with a wrong global override for the time range. Offset and limit (which look correct) in conjunction with the wrong time range can then lead to empty results.
