### ISSUE TITLE
Fields are out of reach for the user

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#7245]
## Expected Behavior
> The fields are now a click away and it really really slows down my workflow. I think all other tools have them immediately visible and easy to reach.
`Lennart Koopmann`

## Current Behavior
To give more space to the view the sidebar is now collapsed.  

## Your Environment
* Graylog Version: 3.2 beta 3

**Comment by linuspahl** [comment]
I am closing this issue because the described feature is part of #7860
