### ISSUE TITLE
Stream reflects the type of operator used to match stream rules `Must match all...` for AND

### ISSUE THREAD

**Issue by lingpri** [Graylog2/graylog2-server#7256]
## Description

Given the user creates a stream with 3 rules . "A message must match all of the following rules"

Field ipVersion must match exactly 6 (ipversion is 6)
Field ingressInterface must be greater than 1
Field octetDeltaCount must be smaller than 900

## Steps To Reproduce
1. Pulls data with octetDeltaCount > 900

![and_rule_match_error](https://user-images.githubusercontent.com/6947168/72944014-51080180-3d3d-11ea-9d0f-0020dde07187.png)

## Environment

- Graylog Version:
- Elasticsearch Version:
- MongoDB Version:
- Browser Version:

**Comment by jalogisch** [comment]
We need to verify that the stream routing working as expected. 

@lingpri could you verify if that is happening to new incoming messages or if you only notice old messages that are not matching your conditions.

**Comment by lingpri** [comment]
@jalogisch - Could you please let me know, what's the difference between old and new messages.

If this is happening for the old messages , then do you intend to call it as not a bug?

What is a New Message ? Please let me know , how do I simulate a new Message for any input ?
What is Old Message ? 
How many hours, minutes , seconds must have been passed to calll it a Old Message.
What additional information do you need from my end, to classify this bug as old or new ?

**Comment by jalogisch** [comment]
he @lingpri 

I mean by old messages that you have those messages already in your index written to elasticsearch, while a new message is something that is ingested after you made the configuration change.

The stream rules work only on messages during ingest, it will not look over data that is from the past already written into elasticsearch. 

That is the source of my question.

**Comment by lingpri** [comment]
@jalogisch - I'm thinking on these lines below. Please let me know what you think. I will perform an another round of testing. From what I recollect, the index pfsense_logs was prec-created for me and I had posted the message to this stream. I will validate again at my end and keep you posted.

> when there's an old message with a timestamp Feb 4 2020 11 am CST, if I pull up a message via All Messages and issue a command 'Test against a Stream', does that make it a new message ? we can call it like this message A arrived at this destination during various points in time... t1,t2..t3 etc...so we have a history of all different times, that a message arrived into a particular stream.

**Comment by lingpri** [comment]
@jan I changed the order , in which I setup the system

1. set up index
2. create stream
3. create Input 
4. found messages, that matches the stream rule.

I'm closing this issue, based on what you quoted earlier, 

> it will not look over data that is from the past already written into Elasticsearch.

**Comment by lingpri** [comment]
![ipfix_search](https://user-images.githubusercontent.com/6947168/74291830-ca22c500-4cfb-11ea-92db-1614c492b2cc.png)
