### ISSUE TITLE
Syslog output

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#726]
Hi,

I love the new output option in 0.90. But i'm missing a syslog output, we would like to forward logging to an rsyslog server to archive logging. But it only accepts syslog...

Is it possible to build in syslog as output?

**Comment by dfch** [comment]
We had the same requirement (but are running Graylog v1.0) and therefore we created a simple SYSLOG Output (which uses the [Graylog fork](https://github.com/Graylog2/syslog4j-graylog2) from [syslog4j](http://syslog4j.org) library). You can check the [syslogoutput
 repository](https://github.com/dfch/biz.dfch.j.graylog.plugin.output.syslogoutput) or [download the plugin](https://drone.io/github.com/dfch/biz.dfch.j.graylog.plugin.output.SyslogOutput/files) directly.

**Comment by nycoon** [comment]
Thank you mate.

**Comment by bernd** [comment]
Closing this because there is a Syslog plugin available [here](https://github.com/dfch/biz.dfch.j.graylog.plugin.output.syslogoutput).
