### ISSUE TITLE
Balancing on AWS Elasticsearch domains with multiple hosts

### ISSUE THREAD

**Issue by MartinEmrich** [Graylog2/graylog2-server#7262]
I experience the following behaviour (with graylog 3.1.3): Of an Amazon Elasticsearch domain with two nodes, only one is bein used, the other one is idling. 

Apparently Graylog resolved the Elasticsearch URL from `elasticsearch_hosts` once, and takes the first IP address returned.

Indeed AWS returns an A record for each node.

Is there a recommended way to spread the load across all Elasticsearch nodes with a single Graylog instance? I do not assume the IPs are stable...

Thanks!

Martin

**Comment by radykal-com** [comment]
Hi @MartinEmrich which metrics of the AWS ESS domain have you checked to see this behaviour? Im running Graylog 3.1.4 with an AWS ESS domain(2 data notes, 3 master nodes) and checking the CPU and storage seems both data nodes are handling traffic equally. Checking the indices within the nodes I can see both data nodes are storing primary and/or replica shards of each index.

Also, what are he shards and replica settings in your graylog indices?

**Comment by MartinEmrich** [comment]
@radykal-com I looked at the CPU load. The indices had only one shard, so the load concentrated on the host graylog was connected to. After creating new Indices with 2 shards, CPU load was spread across both nodes.

Apparently elasticsearch is designed to to spread the load across all nodes regardless of where the client connection is made to, so my immediate problem is solved. 

Only when the host graylog is connected to goes down (e.g. AZ failure), I don't know what will happen... will it freeze? will it try another DNS lookup to get the IP of another node?

As I do not require HA for our graylog installation, this won't be a big issue for me. So if this is not a problem per se, feel free to close this issue.

**Comment by radykal-com** [comment]
As far I know, AWS ESS balances all http requests along all data nodes (it provides a load balancer in front of the data nodes, so the IP addressed returned by the DNS are the different load balancers, one per AZ, not the data node IPs) so if one fails for some reason the requests should reach the other one without disrupting the service.

**Comment by MartinEmrich** [comment]
If that's the case, this issue could be closed as "works as designed" ;)
