### ISSUE TITLE
Auto save renaming of widget

### ISSUE THREAD

**Issue by ceruleancee** [Graylog2/graylog2-server#7266]
When attempting to rename a widget, name does not save unless enter/return is pressed 

## Expected Behavior

New name is saved when clicking the Save button. 

## Current Behavior

![widget01](https://user-images.githubusercontent.com/22039395/73027266-b5d46200-3df8-11ea-807f-177868c5be6a.gif)

## Possible Solution

Improvement would be to auto save the new name entered when the Save button is selected.

## Steps to Reproduce (for bugs)

1. Create a widget
2. rename it (dont press enter/return)
3. press save
4. new name is not saved

## Context

Reducing time editing a widget, minimize frustration

**Comment by dennisoelkers** [comment]
Fixed in #7292.
