### ISSUE TITLE
"Empty Search" button does not work

### ISSUE THREAD

**Issue by nhall-graylog** [Graylog2/graylog2-server#7280]
The "Empty Search" button on the search page does not clear the search field. When clicked, the button appears to do nothing.

## Expected Behavior
Expect that the button should clear the contents of the search field, resetting the search.

## Your Environment
OVA appliance running 3.2-beta-4. Tested in Safari and Chrome browsers to rule out potential browser compatibility issues

* Graylog Version: 3.2.0-beta-4
* Operating System: OSX 10.15.2
* Browser version: Chrome 79.0.3945.130, Safari 13.0.4

**Comment by linuspahl** [comment]
We just merged https://github.com/Graylog2/graylog2-server/pull/7214 which should fix the described behaviour.

**Comment by dennisoelkers** [comment]
Fixed in #7214
