### ISSUE TITLE
Streams - Set as startpage_ from more actions dropdown is not working.

### ISSUE THREAD

**Issue by lingpri** [Graylog2/graylog2-server#7282]
Under Streams, create a stream and click on ' Set as startpage_ from more actions' dropdown menu. This link is disabled.

## Expected Behavior
May be the link must not be disabled as per the test plan. 

## Current Behavior
Navigate to Streams -> Create a stream -> Click 'More Actions' and notice, the link is disabled.

**Comment by bernd** [comment]
@lingpri I am unable to reproduce that. That button will only work for regular user accounts but doesn't work for the root (default admin) user because that user is special.

Can you please retry with a regular user and re-open this issue if you still see a problem? Thank you!

**Comment by lingpri** [comment]
> @lingpri I am unable to reproduce that. That button will only work for regular user accounts but doesn't work for the root (default admin) user because that user is special.
> 
> Can you please retry with a regular user and re-open this issue if you still see a problem? Thank you!

@bernd I will try this again at my end.
