### ISSUE TITLE
"Expand all messages" not visible in all messages table

### ISSUE THREAD

**Issue by nhall-graylog** [Graylog2/graylog2-server#7284]
The "expand all messages" button is present, but is not fully visible in the message results table.

![image](https://user-images.githubusercontent.com/59845687/73093367-f9d07100-3ea3-11ea-96a0-f10e94c3cd84.png)

## Your Environment
OVA appliance running 3.2-beta-4. Tested in Safari and Chrome browsers.

* Graylog Version: 3.2.0-beta-4
* Operating System: OSX 10.15.2
* Browser version: Chrome 79.0.3945.130, Safari 13.0.4

**Comment by dennisoelkers** [comment]
The function itself is not present in 3.2.0 anymore. The visibility issue is an artifact of the message row being scrolled up a bit.
