### ISSUE TITLE
Alerts not working properly

### ISSUE THREAD

**Issue by rendau** [Graylog2/graylog2-server#7288]
I receive alert not on message appear, but on a next message. Next message may appear with a long time after, so I'am losing my alerts. I sent messages with longer interval than "Execute search every".

![image](https://user-images.githubusercontent.com/14363719/73132295-56b65d80-4043-11ea-98b8-5ce539611bd2.png)

## Expected Behavior
send alert when message appear, but not on the next message (after long time)

## Current Behavior
sends alert about message1 only on next message (message2). And if message2 will not appear - then no alert appear

## Steps to Reproduce (for bugs)

1. create alert configuration with http
2. create notification configuration
3. send message that fits notification condition
4. check http endpoint

## Your Environment
Messages sends via docker gelf driver for logs
Endpoint is - simple program that prints received alert to console

* Graylog Version: image: graylog/graylog:3.1 (3.1.4+1149fe1 on fe510147d8f7)
* Elasticsearch Version: image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.2
* MongoDB Version: image: mongo:3
* Operating System: Ubuntu server 18.04.3
* Browser version:

**Comment by rendau** [comment]
Is there any changes?

**Comment by baonq-me** [comment]
@rendau Checkout ElasticSearch refresh time. You have two option:
- Reduce refresh time of ES to lower than 10 seconds, or
- Increase search range in event

**Comment by patrickmann** [comment]
This issue was addressed in 5.0. Please upgrade.
https://github.com/Graylog2/graylog2-server/pull/13556
