### ISSUE TITLE
Data adapters / Cache form focus not working as expected

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7294]
While testing a different feature, I found a strange issue with the data adapters form.

After clicking on "Create Data Adapters" and selecting a data adapter type (e.g. DNS Lookup) a form with different inputs is visible.

When inserting a description the focus gets lost and the title input receives the focus. This is the case for all other inputs. Adding a title also automatically fills out the name input (don't know if this is a bug or feature)

It looks like the cache form has the same problem.

## Steps to Reproduce
1. Go to System -> Lookup Tables -> Data Adapter -> Create data adapter
2. Select a data adapter type
3. Try to fill out the form 

## Your Environment
* Graylog Version: 3.2.0-beta.5-SNAPSHOT

**Comment by edmundoa** [comment]
It looks like this is caused by https://github.com/Graylog2/graylog2-server/pull/7079

**Comment by linuspahl** [comment]
Fixed by #7294
