### ISSUE TITLE
Uninstallation of Dashboards in legacy content packs does not work post 3.2

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#7295]
If a content pack that contains Dashboards (installed before 3.2 upgrade) is uninstalled after the 3.2 upgrade is done, the dashboards in the content pack do not uninstall.

## Expected Behavior

The dashboards should uninstall with the content pack.

## Current Behavior

All other parts of the content pack uninstall, but the dashboards do not.

## Possible Solution

If uninstallation is too complicated to implement, perhaps we can consider documenting as a limitation.

## Steps to Reproduce (for bugs)

1. Install the attached content pack within a pre-3.2 installation. [cloudflare-logpush-content-pack.txt](https://github.com/Graylog2/graylog2-server/files/4117186/cloudflare-logpush-content-pack.txt)
2. Upgrade to version 3.2.
3. Uninstall the content pack. Notice that the Dashboards (Security, Bots etc.) remain installed.

* Graylog Version: 3.1.3 before upgrade. Upgraded to 3.2.0-beta.4-SNAPSHOT+cb33786 with a production build.
* Elasticsearch Version: 6.8.3
* MongoDB Version: 3.4.2

**Comment by kmerz** [comment]
I can't reproduce the bug. Dan can you try it again with the current master?

**Comment by danotorrey** [comment]
I'll check if this is reproducible still.

**Comment by danotorrey** [comment]
I retested this. The issue is not reproducible. All pre-3.2 content pack dashboards uninstall successfully after upgrade to 3.2.

**Comment by danotorrey** [comment]
@dennisoelkers I retested this. The issue is not reproducible. All pre-3.2 content pack dashboards uninstall successfully after upgrade to 3.2.
