### ISSUE TITLE
Update View terminology to Search/Dashboard terms

### ISSUE THREAD

**Issue by kyleknighted** [Graylog2/graylog2-server#7304]
## Current Behavior

Still have some areas where we are using the terminology `view`
![image](https://user-images.githubusercontent.com/122591/73203976-c2f89600-4103-11ea-83c2-dad682bf7221.png)

![image](https://user-images.githubusercontent.com/122591/75682967-e317f980-5c5b-11ea-8c99-ab9a7081dab1.png)

![image](https://user-images.githubusercontent.com/122591/75683013-fcb94100-5c5b-11ea-84df-f407966f7161.png)

**Comment by dennisoelkers** [comment]
Has been fixed a while ago.
