### ISSUE TITLE
implement output_cache_max_size

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#731]
In order to limit disk space usuage an option to limit the output_cache size would be useful.

If the limit is reached the message processing should be pausend and resuemd if the size is ok again. This would queue messages on the frontend (radio) nodes instead of the backend (servers).

Right now if ES becomes to slow or unresponsive the output cache grows until the disk is full and graylog2 crashes...

**Comment by joschi** [comment]
Closing this issue as Graylog 1.0.0 won't use the same spool/journal implementation and the new implementation supports a maximum size and/or age: https://github.com/Graylog2/graylog2-server/blob/1.0.0-rc.1/misc/graylog2.conf#L247-251
