### ISSUE TITLE
Filter list of dashboards to copy widgets to

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#7331]
## Expected Behavior
When clicking on copy to dashboard the user should get a list of dashboards where he has
edit permissions to.

## Current Behavior
The user gets a list of dashboards where he has read permissions to.

## Steps to Reproduce (for bugs)
1. Create Role with read dashboards and edit dashoards.
2. Assign Role to User.
3. Log in as user.
4. Go to search and copy a widget to dashboard and look at the list.

## Your Environment
* Graylog Version: 3.2 RC1

**Comment by linuspahl** [comment]
A side note, we need to filter the results in the backend, due to the pagination.

**Comment by kmerz** [comment]
Needs implementation of #9798
