### ISSUE TITLE
RE- Dashboards page will not load after upgrade to 3.2

### ISSUE THREAD

**Issue by cmiscloni** [Graylog2/graylog2-server#7334]
#7287  

@kmerz , the problem is still existing for me :(
I tried to upgrade from 3.1.4 to 3.2 RC1 but I had only the default source Dashboard and a view which was migrated to Dashboard.

[http://pastebin.fr/60590](url)

**Comment by bernd** [comment]
@kmerz It looks like the `showDataTable` field in an existing dashboard can be `null` or doesn't exist in all cases:

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.graylog.plugins.views.migrations.V20191125144500_MigrateDashboardsToViewsSupport.dashboardwidgets.QuickValuesConfig`, problem: Null showDataTable
```

**Comment by bernd** [comment]
@cmiscloni Can you please show us the response of `curl -u admin:<your-admin-password> localhost:9000/api/dashboards`? Thank you!

**Comment by bernd** [comment]
@cmiscloni Thank you for the report! We fixed this in https://github.com/Graylog2/graylog2-server/pull/7336 and it will be available in the upcoming final release.

**Comment by cmiscloni** [comment]
Thanks
