### ISSUE TITLE
Event Indices should not be offered when creating a new Stream

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#7341]
![image](https://user-images.githubusercontent.com/3034831/73539518-d53d4180-442d-11ea-9e06-2d5f98c9fafc.png)

**Comment by harshlancer** [comment]
It'd be really humble if someone explains to me what's the issue here.
Thank-you

**Comment by mpfz0r** [comment]
@harshlancer The problem is that the Event Indices are using a strict mapping, which makes them impossible to use with regular log data.
They are meant for internal use by our event system only.

However, this issue has been fixed with https://github.com/Graylog2/graylog2-server/pull/10983
already.
Thank you for you interest :+1:
