### ISSUE TITLE
Can't scroll in dashboard table with safari

### ISSUE THREAD

**Issue by ntimo** [Graylog2/graylog2-server#7344]
## Expected Behavior
Being able to scroll inside of a huge data table. When browsing a dashboard.

## Current Behavior
With Safari (Version 13.0.4 (15608.4.9.1.3)) its not possible to scroll inside of data tables. Also the scroll bar does not appear on the right side of the table. And yes I did multiple page reloads without cache (CMD+OPTION+R)

## Possible Solution
1. Use Firefox

## Steps to Reproduce (for bugs)
1. Create a dashboard with a huge table
2. Try to scroll in it using Safari

## Your Environment

* Graylog Version: Graylog 3.2.0+4edc81f on (Oracle Corporation 1.8.0_242 on Linux 5.0.0-37-generic)
* Browser version: Version 13.0.4 (15608.4.9.1.3)

## Screenshots
Safari:
<img width="424" alt="Screenshot 2020-01-31 at 20 31 35" src="https://user-images.githubusercontent.com/6145026/73568468-be681080-4468-11ea-9e52-20fd692848b7.png">

Firefox:
<img width="432" alt="Screenshot 2020-01-31 at 20 31 49" src="https://user-images.githubusercontent.com/6145026/73568477-c1fb9780-4468-11ea-8529-a117331490c4.png">

**Comment by linuspahl** [comment]
Thanks a lot for reporting this issue! We will release a fix for this problem with the next bugfix release.
