### ISSUE TITLE
Consistent naming for inputs

### ISSUE THREAD

**Issue by ceruleancee** [Graylog2/graylog2-server#7345]
Currently there is an inconsistency of the naming convention for the inputs. Of the ~30 inputs, there are 5 that contain the word "input" in the name of the input 

## Expected Behavior

Consistent naming convention

## Current Behavior

there are 5 inputs that contain the word "input" in the name of the input 
![launch new input input](https://user-images.githubusercontent.com/22039395/73573455-053e1200-4439-11ea-9974-dba510f919bf.png)
<img width="314" alt="Inputs with Inputs in name" src="https://user-images.githubusercontent.com/22039395/73573539-2f8fcf80-4439-11ea-813d-3fcc1bfbb0be.png">

## Possible Solution

Remove the word "inputs" in the input name

## Steps to Reproduce (for bugs)

1. System
2. Inputs
3. Select Input
4. Launch New Input

## Context

Mostly it just looks awkward in the UI

## Your Environment

* Graylog Version: Graylog 3.3.0-SNAPSHOT
* Elasticsearch Version: 5.6.14
* Operating System: Mac OS X 10.15.2
* Browser version: Firefox 72.0.2

**Comment by Chunters** [comment]
Inputs not in one place...

**Graylog2/graylog2-server repository**
CEF AMQP Input
CEF Kafka Input
CEF TCP Input
CEF UDP Input

**Graylog2/graylog-plugin-aws repository**
AWS CloudTrail Input

**Graylog2/graylog-plugin-integrations repository**
Palo Alto Networks Input (TCP)

**Comment by Chunters** [comment]
Someone watching pull requests? Is there any understanding of when to get feedback?
