### ISSUE TITLE
If dashboard is changed Enterprise report breaks

### ISSUE THREAD

**Issue by ntimo** [Graylog2/graylog2-server#7347]
If you change a dashboard and save it the enterprise report plugin will not be able to find the dashboard anymore. And you can't edit the content of the report anymore without deleting and recreating it.

## Expected Behavior
You should be able to normally edit the reports content.

## Current Behavior
Editing does not works since Graylog can't find the dashboard.

## Steps to Reproduce (for bugs)
1. Create a dashboard
2. Add it to a report
3. Edit the dashboard and save it
4. Try to edit the content of the report

## Logs
```
graylog_1        | 2020-02-01 13:23:44,133 ERROR: org.graylog.plugins.report.api.ReportService - Could not find dashboard <5d13a916b7776b000da24df1>, skipping it from report <5e347d8f4f676b0011607e0b>
```

## Your Environment

* Graylog Version: Graylog 3.2.0+4edc81f on (Oracle Corporation 1.8.0_242 on Linux 5.3.0-28-generic)
* Graylog Enterprise Version: 3.2.0
* Operating System: Ubuntu 18.04 (Docker)
* Browser version: Safari (Version 13.0.5 (15608.5.11))

**Comment by alex-konn** [comment]
@ntimo, thanks for your report! I couldn't reproduce this though. Could you specify in more detail in what way you edited the dashboard and how you tried to edit the report?

**Comment by ntimo** [comment]
Sure, first off all it was a old dashboard from Graylog 3.1. I deleted multiple widgets and added new ones. I also changed the placements of the widgets on the dashboard. And then at the end just saved it with the save button. Then I went to the enterprise reports page and clicked on "Contents" button which resulted in the error message posted above. If you need anything else please let me know.

**Comment by alex-konn** [comment]
Thanks for the quick reply, @ntimo! Have you tried to edit your report after the upgrade to 3.2 but before editing the dashboard?

**Comment by ntimo** [comment]
@alex-konn 
Yes, that also resulted in the same error. I even deleted the report created a new one, then edited the dashboard and it still broke.

**Comment by alex-konn** [comment]
@ntimo, so you're saying you even got the error after the upgrade to 3.2 without changing the dashboard at all?
Anyway, I can now reproduce the error whenever I delete a widget from the dashboard but not on any other changes. 
So thanks again for your report! :smiley: It would be awesome, if you could confirm that widget deletion is indeed the only cause for the error you're seeing - as that would not explain why you're getting it even without any changes to the dashboard.

**Comment by ntimo** [comment]
@alex-konn I can indeed confirm that it only happens when you delete a widget from a dashboard.

**Comment by alex-konn** [comment]
Excellent! The fix should go into our first bugfix release.
