### ISSUE TITLE
Enterprise reports don't contain all table rows

### ISSUE THREAD

**Issue by ntimo** [Graylog2/graylog2-server#7349]
When generating reports with the Graylog Enterprise plugin the data tables do not contain all table rows but seem to be limited to only a few rows.

## Expected Behavior
The report should contain all table rows.

## Current Behavior
Not all rows are included.

## Steps to Reproduce (for bugs)
1. Create a dashboard with a huge table
2. Generate a report from this table

## Your Environment

* Graylog Version: Graylog 3.2.0+4edc81f on (Oracle Corporation 1.8.0_242 on Linux 5.3.0-28-generic)
* Graylog Enterprise Version: 3.2.0
* Operating System: Ubuntu 18.04 (Docker)
* Browser version: Safari (Version 13.0.5 (15608.5.11))

### Old reports (Graylog version 6.1.x):
<img width="631" alt="Screenshot 2020-02-02 at 17 10 37" src="https://user-images.githubusercontent.com/6145026/73611129-fabd7d00-45de-11ea-97ed-8a0b9889af51.png">

### New reports (Graylog version 6.2.0):
<img width="466" alt="Screenshot 2020-02-02 at 17 10 20" src="https://user-images.githubusercontent.com/6145026/73611134-fd1fd700-45de-11ea-82ac-382651e2d293.png">

**Comment by ntimo** [comment]
Since the Update to Graylog 3.2.1 the reports look like this: The scroll bar inside of the pdf is a bit ironic since you can't use it :D .
<img width="569" alt="Screenshot 2020-02-04 at 23 02 40" src="https://user-images.githubusercontent.com/6145026/73791417-8f240d00-47a2-11ea-9961-8883d85dd33c.png">

**Comment by dennisoelkers** [comment]
Thanks for reporting this issue, @ntimo!

We are fixing this issue and include the fix in one of the next releases (currently aiming for 3.2.2).
