### ISSUE TITLE
Add timerange indicator to dashboard widgets

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#7358]
## What?

Dashboard widgets should show the timerange they are configured with.

## Why?

Each dashboard widget is configured with a timerange. Mixing different timeranges in widgets is possible. Without any indication of the configured timerange of a widget it's hard to understand the data you are looking at.

## Your Environment

* Graylog Version: 3.2.0

**Comment by kmerz** [comment]
We should also display (or make it easy to display) the used query.

**Comment by aim4r** [comment]
Meanwhile I'm enjoying adding the timerange info to each widget title, across a dozen dashboards with 5 pages each :)

**Comment by linuspahl** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/pull/10508
