### ISSUE TITLE
Migrated Views appear to have hidden filters

### ISSUE THREAD

**Issue by chris-y** [Graylog2/graylog2-server#7366]
I have some Views which were migrated to Dashboards from Graylog 3.1.4 to 3.2.0.
These Views have searches attached to them which appear to be no longer visible, but are still being applied.  I also have individual graphs with filters on them which again are not visible but are still being applied.  New graphs on the same view pick up the old hidden search which is quite confusing!

## Expected Behavior

The migrated Views should have their search visible on the top search bar, and filters visible in the individual widget properties.

## Current Behavior

Searches and filters are being applied but are not shown on either the top search bar or in the individual widget properties, so are not editable.

## Steps to Reproduce (for bugs)

1. Create a View in Graylog 3.1.4
2. Apply a global search, create a graph, apply a filter to that graph.
3. Upgrade to Graylog 3.2
4. Look in the new dashboard and see that the search and filter have disappeared but are still being applied.

## Context
This is making it very confusing to see what is actually being shown on a Dashboard which has been migrated from a View.

## Your Environment

* Graylog Version: 3.2
* Elasticsearch Version: 6.8.6
* MongoDB Version: 3.6.3
* Operating System: Ubuntu 18.04
* Browser version: Edge 79.0.309.71

**Comment by dennisoelkers** [comment]
Thanks for reporting this, @chris-y!

We are working on an automated migration that is converting widget filters to widget queries. It will be released ASAP in one of the next patch releases, most probably 3.2.2.
