### ISSUE TITLE
Re-add "run query" or equivalent functionality for dashboard graphs

### ISSUE THREAD

**Issue by chris-y** [Graylog2/graylog2-server#7372]
## What?

Please re-add the ability to run a query based on a Dashboard graph.
Prior to 3.2, it was possible to click on a "play" button on a dashboard graph to run the associated query on a search page.

## Why?

It is currently impossible to find more information about graph results easily.  On tables there is a "show documents for value" which does something similar, and this functionality being made available for graphed results would probably be sufficient.

## Your Environment

* Graylog Version: 3.2
* Elasticsearch Version: 6.8.6
* MongoDB Version: 3.6.3
* Operating System: Ubuntu 18.04
* Browser version: Edge 79.0.309.71

**Comment by brucegivens** [comment]
Wholeheartedly agree, would love to see the return of the play button or similar functionality - this is slowing us down when we need to drill down and explore the data behind the graphs.

**Comment by Pandur2001** [comment]
Here, also! Without the play button a drill down is really annoying. This is my most used functionality within the dashboards!

**Comment by gimmic** [comment]
Agreed, this is useful to pivot from graph data back to query.

**Comment by bessudnov** [comment]
Agreed, this is must have feature, now losing of it gives a lot of problems :(
