### ISSUE TITLE
Total result count missing from query page

### ISSUE THREAD

**Issue by gimmic** [Graylog2/graylog2-server#7386]
## What?
With the updated view to queries, there is no longer a quick reference for hits on the query visible that I can see. 

## Expected Behavior
When performing a query, a quick summary of the search results should be cleanly displayed.
Expected: "Query executed in 190ms at 2020-02-04 15:09:52. Total results: 1,334,232"

## Current Behavior
There is no visible "hits" count that I can see in a default search. Search statistics are hidden away on the side menu under information.

## Possible Solution
Search result statistics should be plainly visible on the main query screen. This helps the analyst understand average query time(and how complex queries impact searches). This also gives a quick rough estimate on the volume of hits for the specific query performed. 

## Your Environment
* Graylog Version: 3.2.1

**Comment by kroepke** [comment]
For the later discussion (but please bear in mind I'm a crappy designer :) ):

How about adding a single line beneath the query bar, that displays some metadata about the search, such as its total result count, when it was last run, and potentially other info that might be relevant.

**Comment by kroepke** [comment]
(Sorry mausgerutscht)

**Comment by gimmic** [comment]
Yeah, something like
"Query executed in 190ms at 2020-02-04 15:09:52. Total results: 1,334,232 in 12 indexes."
A single line, snuck in anywhere around the query bar would be best in my opinion(below, above).

**Comment by gimmic** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/568957/73953445-04d4c980-48c6-11ea-8374-3c9d457dab22.png)

**Comment by roberulloa** [comment]
Please add this, does not make any sense to remove it. It was very useful, not the "solution" of adding the message count.
Thanks! 👍

**Comment by Ric747** [comment]
Hi guys, is there any plan to re-add this feature? It was indeed extremely useful!

**Comment by elonderin** [comment]
any workaround until then ?

**Comment by dennisoelkers** [comment]
@elonderin: Yes, you can add a message count widget to your search, showing you the document count for your current query.
