### ISSUE TITLE
Time Retention: two indexes are created instead of one

### ISSUE THREAD

**Issue by cumafo** [Graylog2/graylog2-server#7387]
## Expected Behavior
One index per day

## Current Behavior
Every night at around 00:03 a new index is created according to settings but then, some minutes later, yet another one, see attached log. As I understand it, the retention period will then be half of what I specify.
Got the same behavior with graylog 2.4 and 3.0.

## Context
My intention is to have one index per day and keeping them for X days.

##Environment
Ubuntu: 16.04.1 LTS
Graylog: 3.1.4-1, 3 nodes, 3 shards, 1 replica
Elastic: 5.6.16
Mongo: 3.4.24
Retention: Time, P1D (1 day, a day), Max # indexes 90.

[elastic.log](https://github.com/Graylog2/graylog2-server/files/4158339/elastic.log)

**Comment by jalogisch** [comment]
he @cumafo 

did you use the same Elasticsearch server/MongoDB for more than one Graylog installation? 

Your described behaviour is only seen if you use the same Elasticsearch servers with multiple Graylog installations but the same prefix for the indices.

**Comment by cumafo** [comment]
No, elastic&mongodb dedicated to graylog. However, the setup pretty old, started it about 2012. Could mongodb need some cleanup perhaps?

**Comment by cumafo** [comment]
We have another (stage) installation that behaves exactly the same. That is after I changed from #doc/size to time based retention.

**Comment by jalogisch** [comment]
he @cumafo 

did you have multiple Graylog servers and have on all server `is_master=true` setting? This is the only reason I can find for that.

**Comment by cumafo** [comment]
Hello.
Probably the case. Removed all but one and now it looks good.
Thanks
/C

**Comment by bernd** [comment]
The issue was most probably related to the problem that two nodes in the cluster had `is_master=true`.
