### ISSUE TITLE
Legend charts with columns can hide actual graph

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#7391]
## Expected Behavior
When creating a timebased bar chart widget the user acutally wants to see the widget.

## Current Behavior
The user has a timebased bar chart widget with `IP` in column which is displaying the Top 5 IPs per bucket. Since the requesting IPs can be vary a lot the legend explodes even with the column limitation of 5. This leads to following issue:

![column-limit](https://user-images.githubusercontent.com/448763/73828607-df7e8780-4801-11ea-8606-ecdc90af39d4.png)

## Possible Solution
Limit the amount of IPs displayed in the legend and make the legend expandable to select a color for a IP.

## Steps to Reproduce (for bugs)
1. Have a log with really a big amount of different IPs (field values).
2. Create a timebased chart (timestamp in row) and the IP field in column.
3. See the legend explode.

## Context
https://community.graylog.org/t/rollback-3-2-3-1/13745/9
https://community.graylog.org/t/upgrade-to-3-2-causes-dashboard-issues/14054

## Your Environment
* Graylog Version: 3.2.0

**Comment by melvin-suter** [comment]
We face the same issue along with the fact, that I can't just show the columns, there always has to be a count, which takes up all the space and stretches the bars enormous.

Bar Chart are at the current state unusable.

**Comment by linuspahl** [comment]
I am closing this issue because we are now displaying a scrollbar when a legend contains too many items.
