### ISSUE TITLE
Aggregation builder config popovers stack up

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#7392]
## Expected Behavior
When configuring a pivot or series element in the aggregation builder, I'd expect that clicking outside of the popover closes it.

## Current Behavior
I need to click "Done" to dismiss the popover, even though it is the only option I have. Even if I open another configuration popover the previous one does not dismiss.

![image](https://user-images.githubusercontent.com/52014/73832097-d09ad380-4807-11ea-8133-18874c1a724e.png)

## Possible Solution
Either give me a "Cancel" button for reverting my changes next to the "Done" button, so I actually have a choice, or simply dismiss the popover when I'm clicking somewhere else.

## Steps to Reproduce (for bugs)
1. Open Sources dashboard
2. Edit Histogram widget
3. Click timestamp pivot config
4. Click "count()" series config

## Context
When clicking out to discover options, configuration items keep stacking up, which can get confusing: "Why is this still open, I didn't change anything and chose something else".
Especially new users might be confused by the amount of stacked popovers.

## Your Environment
* Graylog Version: 3.2.1

**Comment by dennisoelkers** [comment]
Fixed in #10281.
