### ISSUE TITLE
Editing titles of widgets/dashboard tabs is inconsistent

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#7396]
## Expected Behavior
I expect the way to rename things to work roughly the same on the same page.

## Current Behavior
Dashboard tabs are renamed by selecting "Edit Title" from their context menu, which opens a modal (this is consistent with a lot of other places in Graylog).
Editing widget titles is only possible by double-clicking into their title, not even the Edit mode of the widget offers to set the name.

![bug-rename](https://user-images.githubusercontent.com/52014/73833820-e2ca4100-480a-11ea-934f-559366215db6.gif)

## Possible Solution
Either add the "Edit title" option to the widget context menu (consistent with tabs) and/or allow to edit the title in the "Edit" mode of the widget.

## Steps to Reproduce (for bugs)
See screen recording and "current behavior".

## Context
A user new to the concepts might struggle to find and remember the ways to rename items.

## Your Environment

* Graylog Version: 3.2.1

**Comment by becksteadn** [comment]
Thanks for this! I had no idea you needed to double-click to edit the titles.
