### ISSUE TITLE
Add dashboard function to move widget to other query tab

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#7399]
A widget created on a dashboard tab is bound to this one. If the user decides that this widget would be better on a different tab, the user needs to remove and recreate it on the other tab.

Instead, there should be a widget action allowing the user to select the tab that widget should be moved to. Then, it should be removed from the current tab and moved to the selected one.

**Comment by linuspahl** [comment]
This issue got duplicated with #8152 and fixed with #8236

Duplicate of #8152
