### ISSUE TITLE
Clearing selection doesn't work in Sidecar

### ISSUE THREAD

**Issue by qarmin** [Graylog2/graylog2-server#7406]
When I select one of log collector in Sidecar menu and then I want to clear this field, then nothing happens.

![Plik](https://user-images.githubusercontent.com/41945903/73916771-5b3e0a00-48be-11ea-9f3e-ab62ac883cd1.gif)

## Your Environment

* Graylog Version: 3.2.0-3.beta.3
* Elasticsearch Version: 6.8.6-1
* MongoDB Version: 4.0.14-1.el7
* Operating System:  CentOS 7
* Browser version: Firefox 72.0.2

**Comment by cmiscloni** [comment]
Same problem for me

**Comment by asmodianx** [comment]
same issue re-created in Graylog 3.2.2+2f9a628 on Ubuntu 18.04 in firefox

**Comment by shadowimmage** [comment]
Same issue exactly as in the gif above. Firefox console shows

> `>TypeError: this is undefined ------------------ SelectPopover.jsx:107:4`

... for each time the "clear selection" is clicked.

Version: 3.2.3+a9c061c
OS: Ubuntu 18.04.4 LTS x64
