### ISSUE TITLE
Outputs that cannot be initialized are being tried to initialize constantly

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#741]
When a `MessageOuput` is throwing an exception in its `initialize` method, the server tries to initialize it again for every message that goes through the `OutputRouter`.

![screen shot 2014-10-19 at 02 12 29](https://cloud.githubusercontent.com/assets/35022/4691592/cc49d8d2-5724-11e4-8bf6-61e12a14e4b7.png)

**Comment by kroepke** [comment]
What is the state of this issue, @dennisoelkers ?
Is it already in 1.0?
