### ISSUE TITLE
Replay of dashboard widget missing

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#7411]
## Expected Behavior
Since a widget is based on its own search, it has underlying data.
Graylog 3.1 and earlier had a "Play" button that took the user to the search page displaying the underlying data.

## Current Behavior
There is no "Play" button to easily see the underlying data.

## Possible Solution
Add such a button that opens a new search with the histogram, message table and widget visualization as displayed on a dashboard.

## Steps to Reproduce (for bugs)
n/a

## Context
Changed behavior when coming from 3.1.

## Your Environment

* Graylog Version: 3.2.1

**Comment by gimmic** [comment]
This is a duplicate of #7372

**Comment by kroepke** [comment]
@gimmic good catch, closing this in favor of #7372
thanks!
