### ISSUE TITLE
Make "Updating search result" bubble flicker less during auto-refresh

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#7412]
## Expected Behavior
When setting a dashboard or search to refresh automatically Graylog should not render distracting, flashing, elements.

## Current Behavior
When automatically refreshing a search result or dashboard page, Graylog briefly renders the blue "Updating search result" bubble.
Especially on high refresh frequencies, this can be very distracting.

## Possible Solution
When using auto-refresh, do not render the bubble but use some other, non-intrusive, indicator that the page is refreshing.

## Steps to Reproduce (for bugs)
1. Open a search page.
2. Set refresh frequency to 1s.
3. Observe the flickering "updating" bubble.

## Context
Anything moving on a screen will distract the user from the data they are trying to observe.

## Your Environment
* Graylog Version: 3.2.1

**Comment by dennisoelkers** [comment]
Fixed in #7539 & #7691.
