### ISSUE TITLE
Dashboard elements use too much whitespace

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#7413]
## Expected Behavior
To maximize the amount of data being displayed, widgets and other elements should allow using only the required amount of whitespace to visually separate them from other components.

## Current Behavior
Compared to previous versions the dashboard widgets use more whitespace.

## Steps to Reproduce (for bugs)
Compare 3.1 and 3.2 dashboards for increased whitespace usage.

## Your Environment
* Graylog Version: 3.2.1

**Comment by tocomo** [comment]
I had the idea to fix that with stylish. But did run out of time. 
![graylog-fixes](https://user-images.githubusercontent.com/3032624/74263736-b11c1300-4cff-11ea-96d0-af60f0299fd4.png)

**Comment by dennisoelkers** [comment]
Fixing in `4.1`.
