### ISSUE TITLE
LDAP User account name case sensitive

### ISSUE THREAD

**Issue by logopk** [Graylog2/graylog2-server#7417]
Login with LDAP authentication creates users after authentication with case-sensitive Usernames

## Expected Behavior
Loginname should be case-insensitive:
Login with "myLoginName" and "Myloginname" should login with the same graylog user

## Current Behavior
Login with "myLoginName" will create an user account
Login with "Myloginname" will create another user account
Any combination of upper and lower case letters will create new users.

Both authenticate against the same AD object.

If I assign roles to the first user, the second login will get the basic default roles.

## Possible Solution
well: store AD-accountnames always in lowercase?

## Steps to Reproduce (for bugs)
see above

## Context
Accounts get created that are useless

## Your Environment
* Graylog Version: 3.2.1
* Elasticsearch Version: 
* MongoDB Version:
* Operating System: Linux Debian Docker
* Browser version: Chrome 80

**Comment by radykal-com** [comment]
Hi, I'd like to help with this, but maybe one Graylog member should decide if saving the usernames always in lowercase is a good solution or there is any drawback with it.

**Comment by bernd** [comment]
This should be fixed in 4.0. We are no longer using the username that the user typed into the login field but we always use the name that is returned by the AD server. That way we don't create duplicate accounts anymore.

Please open a new issue if you still see problems with 4.0. Thank you!
