### ISSUE TITLE
having an option to show aggregation result 'undefined'  if field is missing

### ISSUE THREAD

**Issue by tocomo** [Graylog2/graylog2-server#7418]
example data:
{ title:sample, x:1}
{ title:sample, x:1}
{ title:sample, x:1}
{ title:sample, x:1}
{ title:sample, x:2}
{ title:sample, x:2}
{ title:sample, x:2}
{ title:sample}

search by "sample" and count group aggregtion for x:
##what i get:
1: 4 
2: 3

##What i need:
1: 4 
2: 3
"missing":1

## Why?
verry often i stack the group count value and wont see the lost items!

## Your Environment
graylog 3.2

**Comment by tocomo** [comment]
![Screenshot from 2020-02-07 13-18-35](https://user-images.githubusercontent.com/3032624/74030097-7e47e700-49ae-11ea-8ea5-23052fd70c59.png)

**Comment by dennisoelkers** [comment]
Thanks for reporting this, @tocomo! We already have this issue on our long list and plan to address it in one of our next release.

**Comment by dennisoelkers** [comment]
This has been fixed in `5.0`.
