### ISSUE TITLE
Prevent unnecessary render cycles of search components

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7424]
We have currently a number of unnecessary render cycles in the component hierarchy of search/dashboards, that could be reduced to increase performance.

Possible strategies:

  - implementing `shouldComponentUpdate`/`React.memo` and implement props equality checks
  - Reduce the scope of used state (consuming stores locally at close to the leafs of the component tree as possible)

This issue is related: https://github.com/Graylog2/graylog2-server/issues/7276

## Your Environment
* Graylog Version: Graylog 3.2.1

**Comment by dennisoelkers** [comment]
Fixed mostly in #7671.
