### ISSUE TITLE
Fixing unreliable frontend tests

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7426]
Especially the `CreateNewDashboard` test is unreliable and sometimes fails during the CI build. We should properly cleaning up periodic requests to avoid dangling promise rejections. 

This PR (https://github.com/Graylog2/graylog2-server/pull/7381) should already improve the behaviour and we should evaluate the result.

## Your Environment
* Graylog Version: Graylog 3.2.1

**Comment by dennisoelkers** [comment]
Frontend tests are currently pretty stable. Closing this for now.
