### ISSUE TITLE
Unify message count and message table widget loading spinner icon

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7427]
When adding the message count widget, "N/A" will be displayed until the the correct count got loaded:
![image](https://user-images.githubusercontent.com/46300478/74147406-6cab4d00-4c03-11ea-8560-7d9ca630d4db.png)

The message table already shows a loading icon, but it is not spinning. When I saw it first I thought I need to click on the icon to load the results.
![image](https://user-images.githubusercontent.com/46300478/74147493-a419f980-4c03-11ea-887c-4afbd6e31850.png)

One possible solution is using the default loading spinner icon for both widgets.

## Your Environment
* Graylog Version: Graylog 3.2.1

**Comment by dennisoelkers** [comment]
This is fixed in `4.2`.
