### ISSUE TITLE
Error "e is undefined" while loading existing view

### ISSUE THREAD

**Issue by dzn03** [Graylog2/graylog2-server#7433]
## Expected Behavior
The view should load without an error when clicking on it for the first time after login.

## Current Behavior
If I open any view for the first time after login I get an error:
![Error page](https://abload.de/img/unbenannt2k3jz3.png)
Reloading (F5) the browser does not help. I have to click on the view a second time at _/views_

## Steps to Reproduce (for bugs)
1. Login
2. Goto _/views_
3. Click on any view
4. You will see the error page
5. Click on the view again
5. View will load properly

## Context
**Browser console output:**
TypeError: "e is undefined"
    _isNewView ViewActionsMenu.jsx:96
    render ViewActionsMenu.jsx:113
    ka vendor.91c91d4a31d54d96392a.js:18
    Sa vendor.91c91d4a31d54d96392a.js:18
    Da vendor.91c91d4a31d54d96392a.js:18
    Fo vendor.91c91d4a31d54d96392a.js:18
    Vo vendor.91c91d4a31d54d96392a.js:18
    Ys vendor.91c91d4a31d54d96392a.js:18
    Ss vendor.91c91d4a31d54d96392a.js:18
    Ls vendor.91c91d4a31d54d96392a.js:18
    Zo vendor.91c91d4a31d54d96392a.js:18
    enqueueSetState vendor.91c91d4a31d54d96392a.js:18
    setState vendor.91c91d4a31d54d96392a.js:26
    t ShowViewPage.jsx:75
    s bluebird.js:5256
    _settlePromiseFromHandler bluebird.js:3278
    _settlePromise bluebird.js:3335
    _settlePromise0 bluebird.js:3380
    _settlePromises bluebird.js:3459
    _drainQueue bluebird.js:185
    _drainQueues bluebird.js:195
    drainQueues bluebird.js:69
vendor.91c91d4a31d54d96392a.js:18:74995
    lo vendor.91c91d4a31d54d96392a.js:18
    callback vendor.91c91d4a31d54d96392a.js:18
    no vendor.91c91d4a31d54d96392a.js:18
    to vendor.91c91d4a31d54d96392a.js:18
    Ro vendor.91c91d4a31d54d96392a.js:18
    Xo vendor.91c91d4a31d54d96392a.js:18
    Os vendor.91c91d4a31d54d96392a.js:18
    unstable_runWithPriority vendor.91c91d4a31d54d96392a.js:35
    Os vendor.91c91d4a31d54d96392a.js:18
    Ys vendor.91c91d4a31d54d96392a.js:18
    Ss vendor.91c91d4a31d54d96392a.js:18
    Ls vendor.91c91d4a31d54d96392a.js:18
    Zo vendor.91c91d4a31d54d96392a.js:18
    enqueueSetState vendor.91c91d4a31d54d96392a.js:18
    setState vendor.91c91d4a31d54d96392a.js:26
    t ShowViewPage.jsx:75
    s bluebird.js:5256
    _settlePromiseFromHandler bluebird.js:3278
    _settlePromise bluebird.js:3335
    _settlePromise0 bluebird.js:3380
    _settlePromises bluebird.js:3459
    _drainQueue bluebird.js:185
    _drainQueues bluebird.js:195
    drainQueues bluebird.js:69

## Your Environment
* Graylog Version: 3.1.0+aa5175e
* Elasticsearch Version: 6.8.2
* MongoDB Version: 4.0.16
* Operating System: 18.04.4 LTS (GNU/Linux 4.15.0-76-generic x86_64)
* Browser version: Firefox 72.0.2 (64-Bit)

**Comment by dennisoelkers** [comment]
@dzn03: You are using an outdated version of Graylog. Can you retry using `3.1.4` or `3.2.1`?
