### ISSUE TITLE
generate widget names by default

### ISSUE THREAD

**Issue by tocomo** [Graylog2/graylog2-server#7436]
## What?
Instead of showing "Untitled whatever" show what the filters and time search range is. Most of the time i do not have to customize the title anymore. 
Alternatives:  
 * print title  + filter and timerange
 * show filter and timerange on **mouse over** the title

## Why?
it takes 3 clicks to open a widget and to close it. Imagin 10 widgets. Horrible.
Actually widgets are hard to use because i do not know if it is still showing the right data.

## Your Environment
* Graylog Version:
graylog 3.2.1

**Comment by tocomo** [comment]
![graylog-fixes](https://user-images.githubusercontent.com/3032624/74265420-d4948d00-4d02-11ea-9fb4-3693e34eb8bd.png)

**Comment by dennisoelkers** [comment]
This has been implemented for quite a while.
