### ISSUE TITLE
percentile function

### ISSUE THREAD

**Issue by cmiscloni** [Graylog2/graylog2-server#7437]
I have an error when I try to add a percentile function in Dashboard

I get the following error:

`While retrieving data for this widget, the following error(s) occurred:
Search type returned error: Expected numeric type on field [Count], but got [keyword].`

Thanks

**Comment by kmerz** [comment]
@cmiscloni could you show me how your widget is configured? It looks to me you try to add a "keyword" field to a series expecting a "numeric" type.

**Comment by cmiscloni** [comment]
@kmerz, yes see below a screenshot

![image](https://user-images.githubusercontent.com/4446733/74326644-0bae8100-4d8b-11ea-8520-6d665f85160e.png)

**Comment by kmerz** [comment]
Okay, I see. But I need the configuration which is broken to help you. Here is no error.

**Comment by cmiscloni** [comment]
The new one

![image](https://user-images.githubusercontent.com/4446733/74329749-a9f11580-4d90-11ea-9701-425f234727d5.png)

**Comment by kmerz** [comment]
Then now let's have a look what type the field `Count` is.

You can check that by clicking on the sidebar and filter for the value:
![Graylog (58)](https://user-images.githubusercontent.com/448763/74415890-8ab3c000-4e44-11ea-9eab-a1a5e2491a1b.png)

**Comment by cmiscloni** [comment]
Strange, it's look like the Count field is a String.
Do you know how to do to have like the older version of Graylog, the percentage of each count() of message in a Dashboard ?

Thanks

**Comment by kmerz** [comment]
To be honest I think 3.2 is missing this series function. Would you mind opening a feature request for this? Please explain the use case for that so I have better arguments for a possible backport to 3.2.

I will close this bug now, since the description is not matching the actual problem. But please do not hesitate to reference this bug in the feature request.
