### ISSUE TITLE
No autocompletion in search field for "_exists_"

### ISSUE THREAD

**Issue by Houtek** [Graylog2/graylog2-server#7441]
## Expected Behavior
In 3.1.x and earlier there was autocompletion in the search field when you typed _exists_

## Current Behavior
No more autocompletion, only when using the field name

## Your Environment

* Graylog Version: 3.2
* Elasticsearch Version: 686
* MongoDB Version: v4.0.16
* Operating System: Ubuntu 
* Browser version: Firefox 68.4.1esr

**Comment by Houtek** [comment]
Adding @xtruthx

**Comment by gimmic** [comment]
I can confirm this and would consider it a bug. We use _exists_ a lot in queries.

**Comment by dennisoelkers** [comment]
Hey @Houtek & @gimmic,

we have addressed this and it will be fixed in `3.2.3`.
