### ISSUE TITLE
Clicking a stream's title from the streams page returns "page not found" when graylog is under a subpath

### ISSUE THREAD

**Issue by s1shed** [Graylog2/graylog2-server#7447]
## Expected Behavior
I have nginx in front of graylog, accessible under a subpath using the instructions at https://docs.graylog.org/en/latest/pages/configuration/web_interface.html#making-the-web-interface-work-with-load-balancers-proxies .

Clicking a stream such as "All messages" when not using a subpath will load a page at https://hostname.tld/streams/000000000000000000000001/search which is essentially the search page with the stream selected. This should also work when using a subpath.

## Current Behavior
When clicking the stream name from the streams page when graylog is under a subpath I see the "page not found" page.

The rest of the application appears to be working normally.

## Steps to Reproduce (for bugs)
1. Configure nginx as a reverse proxy, accessible under a subpath
2. Click the streams tab at the top
3. Click a stream such as "All events"
4.

## Your Environment

* Graylog Version: Graylog 3.2.1+dbaac33 (docker tag graylog:3.2)
* Elasticsearch Version: docker tag elasticsearch-oss:6.8.2 
* MongoDB Version:  3.6.17 (docker tag mongo:3)
* Operating System: Debian unstable
* Browser version: Firefox 72.0.2 & Chrome 80.0.3987.87

**Comment by jalogisch** [comment]
he @s1shed 
what is your nginx configuration look like? Did you include the rewrite?

**Comment by s1shed** [comment]
Hi,

My nginx config is practically the same as what's documented in the documentation other than 

* using `/gl/ ` as the subpath instead of `/graylog/` ; and
* adding `proxy_set_header X-Forwarded-Proto $scheme;` (the problem existed without this line)


```
  location /gl/ {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Server $host;                                                                                      
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Graylog-Server-URL https://$server_name/gl/;
      rewrite ^/gl/(.*)$ /$1 break;
      proxy_pass http://127.0.0.1:9000;
    }
 ```

and the related config from the file `docker-compose.yml`

```
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=https://mydomain.tld/gl/
```

As said earlier, the other parts of the application appear to be functional for me when using nginx as a reverse proxy.

I do not see this behaviour when I access the application at http://127.0.0.1:9000 directly.


![not_found](https://user-images.githubusercontent.com/8793762/74431017-c5c6eb00-4e66-11ea-98b5-0cc7b0521992.gif)

**Comment by zoledian** [comment]
FYI
You can reproduce this bug without a proxy by simply putting a subpath in these server.conf values:
http_publish_uri = http://example.com:9000/subpath/
http_external_uri = http://example.com:9000/subpath/

**Comment by cubed-it** [comment]
me too, why I did the update... ;)

**Comment by davama** [comment]
Wow!
I have been back and forth with this: https://community.graylog.org/t/stream-page-not-found-gorilla/13898/6

Was going to report but I guess it's done!

**FYI**: streams work when you do not use a subdirectoy in nginx.

Nice!

**Comment by dennisoelkers** [comment]
Thanks, @s1shed, @zoledian, @cubed-it & @davama for reporting this issue and supporting us debugging it.

I have found the underlying cause and created a PR for it, that is going into the next patch release of Graylog, hopefully being released soon.

**Comment by s1shed** [comment]
Perfect in 3.2.2 :+1:
