### ISSUE TITLE
Graylog2 date extractor doesn't match with elastic search type

### ISSUE THREAD

**Issue by ypasmk** [Graylog2/graylog2-server#749]
Even though the extractor is working and the conversion to a timestamp is done, the field is passed as a string to elastic search instead of timestamp/date

**Comment by ypasmk** [comment]
is this planned for implementation? I mean it's really not nice not to be able to control your data types ... ES is supposed to be used for analysis as well and having proper data types is not a trivial issue

**Comment by florianvolle** [comment]
Closing this as it can be solved using Pipelines by now.

Thanks!
