### ISSUE TITLE
Bring Back "Highlight Results" Checkbox

### ISSUE THREAD

**Issue by nstr10** [Graylog2/graylog2-server#7494]
For reasons I can't fathom you appear to have removed the option to turn on/off result highlighting in search results.

**Comment by dennisoelkers** [comment]
Hey @nstr10, thanks for reporting this! In order to make the product more useful, I would be happy to know what higher-level problem you are solving using the highlighting toggle?

**Comment by nstr10** [comment]
Thanks for the rapid response!
I use a browser extension called Dark Reader to dynamically alter page styles, which causes highlighted text to be unreadable due to lack of contrast.
Additionally, it is only on rare occasions that I've found the highlighting helpful at all; most of the time it is a nuisance in my opinion, with or without the readability issues.
Maybe this isn't supported usage, but why break/remove something that your users were using?

**Comment by dennisoelkers** [comment]
Thanks for clarifying this, @nstr10!

Right now you can disable highlighting of search terms globally by adding

```
allow_highlighting = false
```

to your server config file. Other than that, we are working on improving the display of highlights on all kinds of different themes and color environments, but we are not reimplementing the `Highlight results` checkbox, sorry.

**Comment by nstr10** [comment]
That setting affects all users. Different users are likely to have different needs and preferences. Why will the checkbox not be reimplemented? It was a useful option to have and there is no apparent reason behind its removal.

This is how you drive away users.
