### ISSUE TITLE
Add Disable/Stop Button on Event Definition

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#7497]
## What?
Add a button to disable a Event Definition

## Why?
1. First of all if a event is about to happen and the admin wants to switch of the alert to prevent emails beeing send out for no reason. So he does not have to delete the alter but can instead just pause it.
2. For debugging reasons so you can pause a event definition to easier find the culprit.

## Your Environment
* Graylog Version: 3.2.2 (dev to 3.3.0)

**Comment by coffee-squirrel** [comment]
I was about to open a feature request but noticed this, so here's the content I would've submitted:


## What?

From a Graylog administrator perspective it would be nice to be able to pause/stop both event definitions and notifications.  As a workaround "disabling" event definitions could be done by creating criteria that will never match, and "disabling" notifications could be done by detaching the notification from all event definitions referencing it (potentially many) or creating an invalid target, or in the extreme case deletion of either, however that is messy.

## Why?


For various reasons, teams may ask us to temporarily disable a particular event definition and then enable it at a later time.  Although we could invalidate the criteria or remove any notifications attached, that is not as convenient as clicking a button to toggle it on/off.

Similarly, but less typical, we might have a need to disable all notifications going to a particular target and then enable it at a later time.  We could invalidate the notification configuration or attempt to identify every place the notification is used, but that is not as convenient as clicking a button to toggle it on/off.

## Your Environment


* Graylog Version: 3.2.4
* Elasticsearch Version: 6.8.6
* MongoDB Version: 4.0.16
* Operating System: RHEL
