### ISSUE TITLE
graylog how to sync fields from logstash?

### ISSUE THREAD

**Issue by tzm7614** [Graylog2/graylog2-server#7518]
Environment info:
elasticsearch-6.8.6
graylog-3.1.3
logstash-7.5.1
mongodb-3.0.8.

Logstash outputs the result:
{
          "type" => "system_kernel",
          "host" => "host01",
    "@timestamp" => 2020-02-21T02:03:07.595Z,
       "program" => "systemd",
          "path" => "/var/log/messages",
     "timestamp" => "Feb 21 10:03:01",
     "logsource" => "pc-zjdssdstest01",
       "message" => "Feb 21 10:03:01 host01 systemd: Started Session 39820 of user root.",
      "@version" => "1"
}
{
          "type" => "system_kernel",
          "host" => "host01",
    "@timestamp" => 2020-02-21T02:03:07.595Z,
       "program" => "systemd",
          "path" => "/var/log/messages",
     "timestamp" => "Feb 21 10:03:01",
     "logsource" => "pc-zjdssdstest01",
       "message" => "Feb 21 10:03:01 host01 systemd: Starting Session 39820 of user root.",
      "@version" => "1"
}

graylog result:  Graylog does not have those fields in logstash

![image](https://user-images.githubusercontent.com/19198734/74998951-2ffa1400-5495-11ea-96bc-0c44b5fee93b.png)

**Comment by jalogisch** [comment]
dear @tzm7614 cross posting on all channels will not solve the problem faster:

https://community.graylog.org/t/graylog-how-to-sync-fields-from-logstash/14098

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
