### ISSUE TITLE
checkProductionBuild.js fails with optional parameters injected by yarn

### ISSUE THREAD

**Issue by jrunu** [Graylog2/graylog2-server#7522]
When yarn detects HTTP and HTTPS proxy settings, these are added to the module calls as optional parameters. With checkProductionBuild.js these are interpreted as file paths and the script subsequently fails.

## Expected Behavior
Ignore optional options or if appropriate honour them.

## Current Behavior
```
[INFO] --- frontend-maven-plugin:1.8.0:yarn (yarn run check-production-build) @ graylog2-server ---
[INFO] Found proxies: [optional{protocol='http', host='XXX', port=Y}]
[INFO] Running 'yarn run check-production-build --https-proxy=XXX:Y --proxy=XXX:Y' in /graylog-project-repos/graylog2-server/graylog2-web-interface
[INFO] yarn run v1.19.2
[INFO] $ node checkProductionBuild.js --https-proxy=XXX:Y --proxy=XXX:Y
[INFO] internal/fs/utils.js:220
[INFO]     throw err;
[INFO]     ^
[INFO] 
[INFO] Error: ENOENT: no such file or directory, open '--proxy=XXX:Y'

```
## Possible Solution
yargs is already in the dependecies. I think it could be used to "skim off" any optional parameters passed to the script.

## Steps to Reproduce (for bugs)
Run mvn package optional with -Dmaven.test.skip=true (It will skip this target with -DskipTests) 

## Context
Indirectly affected by it. Trying to setup up an enviroment to build plugins. I got other issues with the build as well, may or may not be related.

## Your Environment

* Graylog Version: 3.2

**Comment by dennisoelkers** [comment]
Hey @jrunu, thanks for reporting this! Does this produce errors for other tasks execute by `frontend-maven-plugin` as well? Which environment variables exist in your environment for your proxy configuration?

**Comment by jrunu** [comment]
Hi  @dennisoelkers. I don't think so. It does get appended to other commands like webpack and generally they run fine I'd say. Here is another excerpt, the failure in this is due to something else I think, considering the circumstances. It was working before(tm), minus the tests. The problem with checkProductionBuild is more like a side show event I wanted to get out of the equation.

```
[INFO] --- frontend-maven-plugin:1.8.0:yarn (yarn install) @ graylog-plugin-aws ---
[INFO] Found proxies: [optional{protocol='http', host='XXX', port=Y}]
[INFO] Running 'yarn install --https-proxy=XXX:Y--proxy=XXX:Y' in /graylog-project-repos/graylog-plugin-aws
[INFO] yarn install v1.19.2
[INFO] [1/4] Resolving packages...
[INFO] success Already up-to-date.
[INFO] Done in 0.66s.
[INFO] --- frontend-maven-plugin:1.8.0:yarn (yarn run build) @ graylog-plugin-aws ---
[INFO] Found proxies: [optional{protocol='http', host='XXX', port=Y}]
[INFO] Running 'yarn run build --https-proxy=XXX:8080 --proxy=XXX:Y' in /graylog-project-repos/graylog-plugin-aws
[INFO] yarn run v1.19.2
[INFO] $ webpack --bail --https-proxy=XXX:Y --proxy=XXX:Y
[INFO] /graylog-project-repos/graylog-plugin-aws/node_modules/webpack-cli/bin/cli.js:93
[INFO] 				throw err;
[INFO] 				^
[INFO] 
[INFO] Error: Cannot find module './lib/PluginWebpackConfig'
```

In terms of enviroment configuration, I have set HTTP_PROXY, HTTPS_PROXY as well as FTP_PROXY in the /etc/enviroment. Additionally I added a proxy entry to /etc/maven/settings.xml. I may have performed a blood sacrifice at some point to get the proxy working for yet another maven plugin, but I think that was for a different project, not graylog.

**Comment by jrunu** [comment]
@dennisoelkers While looking for something else I stumbled over this node at the end of the graylog-project README:

> To be able to run builds in environments that needs proxy settings to access the internet, first run >mvn with the option to disable proxy by-pass to yarn.
>
>mvn -Dfrontend.yarn.yarnInheritsProxyConfigFromMaven=false
>
>Add the Proxy settings to the users .yarnrc:
>
>proxy "https://<user>:<password>@proxy.in.lan:8080"
>https-proxy "https://<user>:<password>@proxy.in.lan:8080"

If I understand it correctly setting it up and running everything by defulat this way, wouldn't trigger the bug above. So I think it would be fair to say this is a non-issue.
