### ISSUE TITLE
Unexpected API behaviour for dashboards in 3.2

### ISSUE THREAD

**Issue by mayrstefan** [Graylog2/graylog2-server#7527]
After upgrading from Graylog 3.1.2 to 3.2.2 I'm facing some unexpected API challenges

# Legacy dashboard API
## Expected Behavior
Creating a dashboard using the legacy API should create a dashboard that is visible in the UI

## Current Behavior
The API call only creates a legacy dashboard. The UI only shows views. The API calls for the legacy dashboard return the newly created dashboard but it cannot be used anywhere except the API

## Possible Solution
For old dashboards the summary shows that an internal migration to views took place. Calls to the legacy dashboard API should internally work on views instead of old dashboards

## Steps to Reproduce (for bugs)
1. Use the REST API browser
2. Go to Legacy/Dashboards
3. POST /dashboards to create a new dashboard
4. GET /dashboards to verify it has been created
5. Change into Graylog UI /dashboards - the newly created dashboard is missing

# View API
## Expected Behavior
If views are the new dashboards we expected the API to be as simple as well

## Current Behavior
I don't even understand the new API how to create a new view which represents a dashboard. The REST API browser only shows "ViewDTO" as parameter without an explanation. After some trial an error I found there is a type "DASHBOARD". But I still don't get what we need for "search_id" and "state".

## Possible Solution
Explain the required parameters in the REST API manager or add a section to the documentation or changelog

## Steps to Reproduce (for bugs)
1. Use the REST API browser
2. Go to Views
3. POST /views { "type": "DASHBOARD", "title":"demo title","description":"demo desc" }
4. Error message tells us searchId and state are missing.
5. Further experiments show as that we have to write "search_id" in JSON instead of the stated "searchId". I still don't kow what a search id is.

## Context
For our internal tenants we create a stream, a role and a dashboard which they can work in. We got surprised that our automation still can successfully create dashboards but our tenants don't see them.

## Your Environment

* Graylog Version: 3.2.2
* Elasticsearch Version: 6.8.0
* MongoDB Version: 3.4
* Operating System: SLES12
* Browser version: IE11, Chrome 77

**Comment by dennisoelkers** [comment]
Fixed in #7802.
