### ISSUE TITLE
Current streams filter for fields does not work

### ISSUE THREAD

**Issue by ntimo** [Graylog2/graylog2-server#7528]
## Expected Behavior
When viewing a stream and then using the "current streams" filter in the fields menu only fields should be shown that are actually part of the stream in the list below.

## Current Behavior
All other fields are also shown, meaning that fields from other streams are shown that do not belong to currently opened stream.

## Steps to Reproduce (for bugs)
1. Open a stream
2. Click on x2 on the sidebar on the left side
3. Select "current streams"
4. View the list below

## Your Environment

* Graylog Version: Graylog 3.2.2+2f9a628 on xxx (Oracle Corporation 1.8.0_242 on Linux 5.3.0-28-generic)
* Operating System: Ubuntu 18.04
* Browser version: Safari (13.0.5 (15608.5.11))

## Screenshot
<img width="454" alt="Screenshot 2020-02-23 at 15 17 33" src="https://user-images.githubusercontent.com/6145026/75113624-cffb9d00-564f-11ea-8db0-151e88afa8f4.png">

**Comment by dennisoelkers** [comment]
Hey @ntimo, thanks for reporting this! We are already tracking this issue in #5809.
