### ISSUE TITLE
v3.2 missing feature: search time lookups

### ISSUE THREAD

**Issue by asmodianx** [Graylog2/graylog2-server#7534]
## What?

In graylog 3.1 there were search time lookups (beautifiers).  In 3.2 there are not as the search screen has been replaced by the view screen

## Why?

In splunk there are search time and index time transformations and lookup features.  The advantage of index time look ups is that you can cross reference information and the log entry will contain that information as of the time of indexing.  Search time indexing is cross referencing using current information. If the lookup table is subject to change then this is useful. 

The new interface has multiple drop downs on both values and fields, adding a lookup feature to a field would resolve this request. Preferably having it in the left hand dock would fully bring this feature back to feature parity with 3.1

## Your Environment

Your Environment

Graylog 3.2.2+2f9a628 on aux-graylog1 (Private Build 1.8.0_242 on Linux 4.15.0-88-generic)

    Graylog Version:
    Graylog 3.2.2+2f9a628

    Elasticsearch Version:
    6.8.6

    MongoDB Version:
    v4.0.16

    Operating System:
    ubuntu 18.04 x64

    Browser version:
    Firefox

**Comment by dennisoelkers** [comment]
What are `search time lookups (beautifiers)`? Do you mean decorators? These are present in `3.2`, but you do configure them per message table (as you can now have multiple message table widgets).

**Comment by asmodianx** [comment]
So this is a training/documentation issue.
After looking at the drop down I am seeing this now.

I might recommend making note of this in release notes. 
This resolves my issue.
