### ISSUE TITLE
Tests can fail due to a different iteration order in HashSet

### ISSUE THREAD

**Issue by cpugputpu** [Graylog2/graylog2-server#7542]
The tests in `org.graylog2.utilities.IPSubnetConverterTest#testDefault` and `org.graylog2.utilities.IPSubnetConverterTest#testNormalize` can fail due to assertion failures.
## Expected Behavior
`assertThat(converter.convertTo(results)).isEqualTo(defaultList);` will pass the check all the time.

## Current Behavior
`org.junit.ComparisonFailure`: 
expected:<"127.0.0.1/32,0:0:0:0:0:0:0:1/128"> 
but was:<"0:0:0:0:0:0:0:1/128,127.0.0.1/32">
at `org.graylog2.utilities.IPSubnetConverterTest.testDefault(IPSubnetConverterTest.java:42)`

## Reason Analysis
When calling `converter.convertTo(results)`, the returned string can be different on different JVM versions. The `results` is implemented as a HashSet in `IPSubnetConverter.java`, which makes no guarantee about the iteration order. 
The specification about HashSet says that "it makes no guarantees as to the iteration order of the set; in particular, it does not guarantee that the order will remain constant over time". The documentation is here for your reference: https://docs.oracle.com/javase/8/docs/api/java/util/HashSet.html

## Possible Solution
The fix is to use LinkedHashSet instead of HashSet. In this way, the iteration order will not be different any more and the code will be more stable.

**Comment by mpfz0r** [comment]
Fixed with #7543
