### ISSUE TITLE
Auto query / Update Search Results is too aggressive and queries at inopportune times.

### ISSUE THREAD

**Issue by gimmic** [Graylog2/graylog2-server#7572]
The auto query to refresh the results triggers at inopportune times while building a query. This results in unnecessary user waits and excessive load on the graylog/elasticsearch clusters while doing large queries.

## Expected Behavior
When doing multiple filter settings in a query, there should be no background search until the user indicates it is time to execute a query. 

## Current Behavior
Start a query, then change to absolute time. Selecting a "start" time triggers an auto-query, before you're even able to set a "stop" time. 

## Possible Solution
Set a user preference option to disable auto query execution. That way if you're doing a lot of banal queries and you want this feature enabled, you can use it. Those of us who want to set multiple query filters before the data is "refreshed" can do so by disabling this feature.  

## Steps to Reproduce (for bugs)
1. Try to rapidly change multiple aspects of any query. Especially bad with time window selection.
![searchannoyance](https://user-images.githubusercontent.com/568957/75456780-945b1e80-5940-11ea-8983-7f8d780d2a41.gif)

**Comment by dennisoelkers** [comment]
Thanks @gimmic, for reporting this!

We have heard a lot of times that changing the time range should not require an additional action to trigger refreshing the search. Nevertheless, the absolute time range selection might be an exception to this. We will look into improving this for one of the next version.

**Comment by gimmic** [comment]
You could also create a visual appearance change, such as a glowing effect, to the query icon(the magnifying glass) when the query parameters have changed but a new search has not been executed. 

I personally do not want to send excessive queries to the cluster unless I'm ready for it to perform that search.

**Comment by gimmic** [comment]
@dennisoelkers the more I am using the absolute time picker today, the more I notice it is bug territory. It gets very difficult to manually select a time window as every time focus changes or there is *any* input on the time frame, a query runs.

**Comment by gimmic** [comment]
With 3 widgets open it took me 2 minutes and 33 seconds to successfully set a specific start date/time and end date/time. The UI is unresponsive while the query refresh is in play. 
Click Start window (refresh wait)
Click into the date day (refresh wait)
Type the new date in. (refresh wait)
Click the end timeframe (refresh wait)
Click the date (refresh wait)
Type the new date (refresh wait)
Click the time (refresh wait)
Change the time (refresh wait)

Any mouse input triggers a refresh :(

**Comment by rmoorecpcc** [comment]
Yes this behavior makes using graylog an incredibly frustrating experience. I can't even type in a simple search query such as "source: someserver123" without it executing two or three times. It is worse on the default search all streams page, making me think the field autocomplete and idle input timer on the search bar are fighting each other. This wasn't an issue before version 3.2, and is exacerbated by the high number of field names some of our systems output.
