### ISSUE TITLE
Add some kind of "support bundle"

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#758]
There should be a feature that exports a "support bundle" which contains information about the Graylog2 setup. This will be helpful when debugging problems.

Some examples below. (please add more in comments)
- Graylog2 server metrics
- Log files
- ES cluster status
- ES index status
- JVM stats
- Config files
- ...

Sensitive data should be stripped or masked if possible!

**Comment by florianvolle** [comment]
This is now possible with Apollo and will most likely be implemented for customer support bundles in Graylog Enterprise.
