### ISSUE TITLE
Tests can fail in LookupCacheKeyTest.java

### ISSUE THREAD

**Issue by cpugputpu** [Graylog2/graylog2-server#7594]
The tests in `org.graylog2.plugin.lookup.LookupCacheKeyTest#serialize` and `org.graylog2.plugin.lookup.LookupCacheKeyTest#serializePrefixOnly` can fail when executing `assertThat(node.fieldNames()).containsExactly("prefix", "key");` . 
Actual and expected have the same elements but not in the same order, at index 0 actual element was:  <"key"> whereas expected element was:  <"prefix">

## Expected Behavior
The order of elements should be stable across different JVM versions or vendors so that the tests can always pass.

## Current Behavior
Tests may fail since the order of the elements is non-deterministic.

## Reason Analysis
The root cause of this failure lies in a third-party library here `com.fasterxml.jackson.databind.util.ClassUtil.getDeclaredFields` when executing `final JsonNode node = objectMapper.convertValue(cacheKey, JsonNode.class);`, which will finally call `java.lang.Class.getDeclaredFields`. The specification about getDeclaredFields() says that "the elements in the returned array are not sorted and are not in any particular order". The documentation is here for your reference: https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getDeclaredFields--
And the behaviour might be different for different JVM versions or vendors

## Possible Solution
Though the root cause is deep in a third-party library, the fix is to change the assert statement from containsExactly to containsExactlyInAnyOrder so that the order of the elements will not affect the assertion.

**Comment by edmundoa** [comment]
Closing, this was fixed in #7595.
