### ISSUE TITLE
Support for fractional date histogram intervals

### ISSUE THREAD

**Issue by GrasshopperDev** [Graylog2/graylog2-server#761]
I was looking at the elastic search documentation and noticed that the date histogram supports partial units like 1.5h, 10m, etc...

http://www.elasticsearch.org/guide/en/elasticsearch/reference/0.90/search-facets-date-histogram-facet.html

Graylog only seems to support the specific intervals though (minute, hour, day, week, month, quarter, year). Is it possible to get support for these partial intervals? Being able to get intervals like 5 or 10 minutes would be really useful compared to being forced to either 1 minute or 1 hour with no in between.

(This https://github.com/Graylog2/graylog2-web-interface/issues/866 issue from the web board is related, and would be implementable using this feature)

**Comment by florianvolle** [comment]
This might be interesting as a fully customizable option.

**Comment by gimmic** [comment]
Bounced into this today. Would be nice to have a customizable histogram bucket value.

**Comment by gimmic** [comment]
Apparently this is already in the Enterprise version and so it will not be added to the open source edition. It's a very easy API call to build the histogram buckets in the backend Elastic. Anyone looking for this functionality in OSS I suggest hooking up Kibana to the backend ES graylog storage to retain this feature(among others).

**Comment by bernd** [comment]
> Apparently this is already in the Enterprise version and so it will not be added to the open source edition.

@gimmic Why do you think this wouldn't be added to open source? The plan is that the new search page we currently have in Enterprise only will eventually replace the existing search page in the open source product. This just didn't happen yet because we are not done with the new search.

See also this comment: https://github.com/Graylog2/graylog2-server/issues/3473#issuecomment-464005253

**Comment by dennisoelkers** [comment]
Fixed in `3.1.0` already, being part of OSS views, which are now the default search.
