### ISSUE TITLE
Cannot view messages in Streams

### ISSUE THREAD

**Issue by capricorn800** [Graylog2/graylog2-server#7615]
Hi!
I am using version 3.2 and I cannot view messages in the Streams. I can see the messages coming to Streams but they are not displaying.

97 messages/second. Must match at least one of the 1 configured stream rule.

Thanks

**Comment by Kimmyzhao** [comment]
<img width="1226" alt="QQ20200307-130859@2x" src="https://user-images.githubusercontent.com/11455494/76137184-d983fc80-6074-11ea-8294-5b03d8b6221e.png">

**Comment by florianvolle** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by kroepke** [comment]
This is most often related to a wrong timezone associated with the events. Can you check for a 24h time window, also going into the future?
