### ISSUE TITLE
Kafka plugin features - Direct connection to Brokers, TLS Authentication + encryption  

### ISSUE THREAD

**Issue by jozefbarcin** [Graylog2/graylog2-server#7617]
## What?

I'm missing this features in latest kafka plugin:
* Direct connection to Brokers - support of bootstrap protocol. Our case is: Only Kafka brokers are available for consumers (GRAYLOG). Zookepers are in private IP range, they are not accessible for consumers. Related to https://github.com/Graylog2/graylog2-server/issues/5778

* TLS Authentication + encryption  - consume logs from kafka encrypted way
  https://kafka.apache.org/documentation/#security_ssl
  
* support latest kafka versions

* support parameter `client-id` to have ability to enforce quotas per consumer https://kafka.apache.org/documentation/#design_quotas
 

## Your Environment

* Graylog Version: 3.0.2, 3.2.2
* Java Version: openjdk-8-jre-headless
* Elasticsearch Version: 6.8.6
* MongoDB Version: 4.0.13
* Operating System: Ubuntu 18.04
* Browser version: Firefox 73.0.1

**Comment by mpfz0r** [comment]
Work in progress: https://github.com/Graylog2/graylog2-server/pull/7504

**Comment by bernd** [comment]
This has been implemented in #7504
