### ISSUE TITLE
Feature request - create new dashboard option from search console

### ISSUE THREAD

**Issue by asmodianx** [Graylog2/graylog2-server#7629]
## Expected Behavior

Need to create new dashboard to receive graphs from search interface.  
## Current Behavior

cannot create and save a new empty dashboard when copying an aggrigate chart to a dashboard, can only select an existing dashboard.
## Possible Solution

feature request: in search interface add "create new dashboard" button or trailing option in dashboard scrolling list.

## Steps to Reproduce (for bugs)

1. login to graylog to an account with admin permissions or appropriate dashboard/search privileges
2. click on search
3. search for something
4. create aggregate from a field
5. on the chart drop down click copy to dashboard
6. only allows to copy to existing dashboard and will not allow creation of new dashboard.

## Context

This is a work flow issue (probably low priority)
## Your Environment

Graylog 3.2.2+2f9a628 on aux-graylog1 (Private Build 1.8.0_242 on Linux 4.15.0-88-generic)
Ubuntu 18.04
Firefox

**Comment by dennisoelkers** [comment]
Thanks for your feedback, @asmodianx! This is a good idea. I am putting this into our backlog for the next version(s).
