### ISSUE TITLE
graylog2 running but service dead

### ISSUE THREAD

**Issue by JensKuehnel** [Graylog2/graylog2-server#763]
Hi,
when mongodb is not running, the service graylog2-server status shows "graylog2-server dead but subsys locked", but ps ax still shows the graylog2-server process.
Running on Centos 6 with graylog2-server-0.91.1-1.noarch

reproducer:

```
$ service mongodb stop
$ service graylog2-server restart
$ sleep 5
$ service graylog2-server status
graylog2-server dead but subsys locked
$ ps axfwww| grep graylog2-server
 9593 ?        Sl     0:04 /usr/bin/java -jar -Dlog4j.configuration=file:///etc/graylog2/server/log4j.xml /usr/share/graylog2-server/graylog2-ser
```

**Comment by bryangwilliam** [comment]
I just installed graylog-server 1.2.1 and this still seems to be an issue. The service reports as "dead but subsys locked", and every time I run "service graylog-server restart" it starts up a new process while the old one is still running. The log contains the following error on the first instance:

```
2015-10-13T19:52:47.256-06:00 ERROR [MongoConnectionProvider] Error connecting to MongoDB: Timed out after 10000 ms while waiting to connect. Client view of cluster state is {type=Unknown, servers=[{address=localhost:27017, type=Unknown, state=Connecting, exception={com.mongodb.MongoException$Network: Exception opening the socket}, caused by {java.net.ConnectException: Connection refused}}]
```

And this for all the subsequent instances (after trying to restart the service):

```
2015-10-13T19:53:18.255-06:00 ERROR [KafkaJournal] Unable to start logmanager.
kafka.common.KafkaException: Failed to acquire lock on file .lock in /var/lib/graylog-server/journal. A Kafka instance in another process or thread is using this directory.
```

**Comment by ykfq** [comment]
```bash
[root@Control ~]# service graylog-server restart
Stopping graylog-server:                                   [FAILED]
Starting graylog-server:                                   [  OK  ]
[root@Control ~]# service graylog-server status
graylog-server dead but subsys locked

[root@Control ~]# tail -f /var/log/graylog-server/server.log
2017-04-11T11:37:48.423+08:00 ERROR [CmdLineTool] Invalid configuration
com.github.joschi.jadconfig.ValidationException: The minimum length for "password_secret" is 16 characters.
```

It said that the `password_secret` is short than 16 characters, so I generate a random tring with `pwgen -s -n 16`  and changed the value of `password_secret`  in the configuration file `/etc/graylog/server/server.conf ` , then restart the service with `service graylog-server restart`, la couple minitues later ,I was able to access the web `http://ip:9000/` whit user `admin` and password set above.
