### ISSUE TITLE
Add multiple fields pr. extractor

### ISSUE THREAD

**Issue by LordMike** [Graylog2/graylog2-server#765]
I've found myself making two or more extractors for each message recently, as there are multiple pieces of information I want to fetch. So right now I'm keeping track of all the extractors via. excel, so that I can copy/paste the correct identifiers ("run only if this string is present") and the correct names (makes them easier to find again).

It'd be cool if the extractors could be grouped or otherwise combined, so that for a single "run if this string is present", we can run multiple fields on it (some regex, some placement etc.). Other benefits (besides not checking the same string multiple times) could be that once you've split the string/input by spaces, there's no need to do it again. :)

**Comment by bernd** [comment]
This is now possible with the processing pipelines. http://docs.graylog.org/en/2.1/pages/pipelines.html
