### ISSUE TITLE
Create Stream Rule generates a bad request

### ISSUE THREAD

**Issue by lasoares** [Graylog2/graylog2-server#7659]
## Expected Behavior
I should be able to create a stream rule, I am creating the same rule as always on previous versions like 3.2.1

## Current Behavior
After creating a stream rule I receive the following error:
Error creating a stream rule with status cannot POST http://ip:9000/streams/guid/rules (400)
when I check the Header, the field is empty, but I have the value input in the box, and I check that is a warning on the browser that the field can't be empty, so it assumes that is empty but is not.

## Steps to Reproduce (for bugs)
1.Create a stream
2.Create a stream rule
3.Fill the Field, Type and Value inputs with no empty values
4.Hit Save, and I get the error 400 bad request

## Your Environment
I never have this issue, when installing directly from OVA appliance on version 3.2.1, now I am having an issue after install thew new graylog version 3.2.2 from scratch

* Graylog Version: 3.2.2
* Elasticsearch Version: 
* MongoDB Version: 
* Operating System: ubuntu
* Browser version: Chrome 80.0.3987.132 and IE11

**Comment by dennisoelkers** [comment]
Thanks @lasoares for reporting this issue!

I have just tried to reproduce this, but it worked well. Can you please go to the network tab of your browser and extract the request body and the response of the affected http request? This would help us a lot debugging this issue.

Also: Are you running a proxy/load balancer/anything that could tamper the request between your browser and the Graylog API?

**Comment by lasoares** [comment]
Hello @dennisoelkers ,
Please the images with than info in the link bellow, this was a colleague that install the graylog 3.2.2 from scratch without using the OVA appliance that had this issue, he share the image with me:
https://imgur.com/a/kNla4u6
Apologies, but i just have this images, I believe that you are able to see the request and response body for that images.
The graylog solution was installed on an Ubuntu machine running on Azure, and it does not use nginx as reverse proxy.

**Comment by dennisoelkers** [comment]
@lasoares: What i can see from the images is that a rule with an empty field name is created. Is this on purpose? Usually, this should be prevented from a browser-side validation that forces the field to be filled. Which browser is used?
