### ISSUE TITLE
Limit selectable fields in 3.2 to search results - bring back 3.1 feature

### ISSUE THREAD

**Issue by Mike-FUT** [Graylog2/graylog2-server#7675]
## What?
In 3.1 when running a search you could then selct fields on the left side that were limited to the results of the current page.
In 3.2 this feature has gone.
I'm only feeding two systems into Graylog but still the amounts of fields is immense.
With 3.1 you could run a simply query and only the fields available for that query the fields were displayed by selecting “List fields of current page”.

## Why?
With 3.2 you have to dig through tons of fields which makes it a lot more inefficient than it was with 3.1.

Btw, even better than the 3.1 feature to "list fields of current page" would be to "list fields of current search results".

Some screenshots you can find in my forum post:
https://community.graylog.org/t/limit-selectable-fields-in-3-2-to-search-results/14092/3

## Your Environment
* Graylog Version: 3.2

**Comment by dennisoelkers** [comment]
Hey @Mike-FUT,

thanks for reporting this issue. We are already tracking it in #7517.
