### ISSUE TITLE
After ugrade from 3.1.x to 3.2.x users no longer have permission to find or delete previously saved searches

### ISSUE THREAD

**Issue by juliohm1978** [Graylog2/graylog2-server#7676]
Recently upgraded to [Graylog 3.2.3](https://hub.docker.com/layers/graylog/graylog/3.2.3-1/images/sha256-746c5b81ae9787696935433cf0079978fb36ce8d642f0c5e10308239e2d0ceb9?context=explore), and now non-admin users are unable to find saved searches they had created under 3.1.x.

I think this might be related to https://github.com/Graylog2/graylog2-server/issues/7515, where users that create new saved searches cannot delete them.

We have users configured via LDAP/Active Directory with automatically assigned roles based on groups from that directory. Users are still correctly assigned to roles, but it seems that some default permissions assumed under 3.1.x are missing in 3.2.x.

In the UI, the only permissions I'm allowed to give to roles are for Streams and Dashboards.

![image](https://user-images.githubusercontent.com/4145456/76528244-428dba80-644f-11ea-9768-c097b90372b7.png)

Is there a way to further control or correct user permissions? That would be a good workaround for the moment.

## Your Environment

* Graylog Version: graylog/graylog:3.2.3-1
* Installation via helm chart stable/graylog:1.5.8
* Elasticsearch Version: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
* MongoDB Version: unguiculus/mongodb-install:0.7
* Operating System: 

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
* Browser version: Firefox 73.0 (64-bit)

**Comment by dennisoelkers** [comment]
Hey @juliohm1978,

thanks for reporting this issue! We are already tracking it in #7640. I will add another clarifying comment in there, therefore I am closing this issue.
