### ISSUE TITLE
Elasticsearch cluster is green but failed to rotate index

### ISSUE THREAD

**Issue by on99** [Graylog2/graylog2-server#7699]
## Expected Behavior

Index retention checks should not be skipped.

## Current Behavior

Index retention checks are skipped.

## Steps to Reproduce (for bugs)

I cannot reproduce the bug but have a live example.

## Context

Everything seems to be OK, e.g., elasticsearch cluster is green as shown in graylog web interface, logs can be successfully processed and can be searched, however, index are not correctly rotated.

![image](https://user-images.githubusercontent.com/13196393/76874382-138da380-68aa-11ea-935d-765d6df08044.png)

I found these lines of log in `/var/log/graylog-server/server.out`
```
2020-03-17T23:29:54.765+08:00 INFO  [IndexRetentionThread] Elasticsearch cluster not available, skipping index retention checks.
2020-03-17T23:34:54.794+08:00 INFO  [IndexRetentionThread] Elasticsearch cluster not available, skipping index retention checks.
2020-03-17T23:39:54.770+08:00 INFO  [IndexRetentionThread] Elasticsearch cluster not available, skipping index retention checks.
2020-03-17T23:44:54.766+08:00 INFO  [IndexRetentionThread] Elasticsearch cluster not available, skipping index retention checks.
2020-03-17T23:45:09.860+08:00 INFO  [IndexRangesCleanupPeriodical] Skipping index range cleanup because the Elasticsearch cluster is unreachable or unhealthy
```

This is very weird, I just spot the bug after it broke my elasticsearch cluster several times due to disk usage. There is nothing changes after I restart graylog-server and elasticsearch cluster several times.

## Your Environment

* Graylog Version: Graylog 2.4.6+ceaa7e4 on graylog (Oracle Corporation 1.8.0_171 on Linux 4.4.0-159-generic)
* Elasticsearch Version: 5.6.3
* Operating System: Ubuntu 16.04

**Comment by jalogisch** [comment]
he @on99 

as you can see the very first message in your screenshot is "Deflector exists as an alias" - this can happen in some situations and later versions of Graylog take care of that. In addition the installations guides include settings to avoid such a situation. 

For those running into this situation we have created this entry in our documentation: https://docs.graylog.org/en/3.2/pages/faq.html#how-do-i-fix-the-deflector-exists-as-an-index-and-is-not-an-alias-error-message

This looks like a bug in Graylog but it is an operational problem that you can solve by following the steps.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. If you can't solve the problem with the above linked guide, please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
