### ISSUE TITLE
Timestamp sorting moved/missing in 3.2

### ISSUE THREAD

**Issue by benoc617** [Graylog2/graylog2-server#7707]
In versions of graylog prior to 3.2, there was functionality in the search interface to reverse sort on timestamp, or sort on other fields.  This is apparently no longer present in 3.2 (or is moved somewhere undocumented?).

## Expected Behavior
Click on the widget next to timestamp field and sort in ascending/descending order.

## Current Behavior
"sort" option is no longer available anywhere in the UI (or documentation) that I could locate.

## Possible Solution
Re-introduce the "sort" option for fields (at least, timestamp), or if it is still there somewhere, please put it in the documentation.

## Context
Our users regularly use the web interface to view search results in reverse time order (most recent on bottom vs. on top) and this does not seem possible with 3.2

## Your Environment

* Graylog Version: 3.2.1
* Elasticsearch Version: 6
* MongoDB Version:
* Operating System:  coreos, docker container graylog
* Browser version: chrome and firefox and safari, multiple versions

**Comment by dennisoelkers** [comment]
Thanks for reporting this, @benoc617. The feature has been reimplemented in `3.2.3`, therefore I am closing this issue.
