### ISSUE TITLE
Graylog2 should store the messages which triggers an alert

### ISSUE THREAD

**Issue by dfisek** [Graylog2/graylog2-server#772]
Currently Graylog2 do not store the messages which triggered an alert, but only put them into the email/alert callbacks when those are sent.

Storing the messages can make way to new features such as:
* Viewing alerts via a web interface. Would be of additional use, if instant notification fails for some reason.
* Retrieving full error messages from REST API (for integration with 3rd party applications).

**Comment by joschi** [comment]
This feature has been added in Graylog 1.2.0: https://www.graylog.org/announcing-graylog-1-2-ga-release-includes-30-new-features/
