### ISSUE TITLE
Confusing warning about SO_RCVBUF

### ISSUE THREAD

**Issue by pschyska** [Graylog2/graylog2-server#7720]
I configured rmem_max to the default buffer size of the GELF UDP input: 262144. On server startup, the input warns about a wrong SO_RCVBUF.

## Expected Behavior
The GELF UDP input should account for the fact that SO_RCVBUF is doubled when reading.
````
       SO_RCVBUF
              Sets  or  gets the maximum socket receive buffer in bytes.  The
              kernel doubles this value (to allow space for bookkeeping over‐
              head)  when  it  is  set  using setsockopt(2), and this doubled
              value is returned by getsockopt(2).  The default value  is  set
              by  the  /proc/sys/net/core/rmem_default  file, and the maximum
              allowed value is set by the  /proc/sys/net/core/rmem_max  file.
              The minimum (doubled) value for this option is 256.
````
## Current Behavior
```
org.graylog2.inputs.transports.UdpTransport - receiveBufferSize (SO_RCVBUF) for input GELFUDPInput{title=GELF UDP, type=org.graylog2.inputs.gelf.udp.GELFUDPInput, nodeId=null} (channel [id: 0x23250661, L:/0.0.0.0:12201]) should be 262144 but is 524288.
```
## Possible Solution
I don't know what the correct value to enter in the UI is. rmem_max or rmem_max*2. If the latter, this is IMHO confusing and should be documented. If the former I suspect the calculation (and triggering the warning) is wrong.

## Steps to Reproduce (for bugs)

1. sysctl -w net.core.rmem_max=262144
2. Start graylog
3. Start GELF UDP input with defaults

## Your Environment

* Graylog Version: 3.2.3+a9c061c, codename Ethereal Elk
* Elasticsearch Version: 6.8.6
* MongoDB Version: 3.6.17
* Operating System: 3.10.0-1062.9.1.el7.x86_64
* Browser version:

**Comment by braiam** [comment]
This behavior is still present in 3.3.0

**Comment by mikkolehtisalo** [comment]
When it says `should be 262144 but is 524288.` Netty just probably doesn't understand the doubling described in the man page. This should be documented because the confusing message takes a while to investigate.

**Comment by bernd** [comment]
The check we are using is expecting the value to be exactly the same:

https://github.com/Graylog2/graylog2-server/blob/9847fe195eda353aa9976f88d3a7a39f902569ce/graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java#L436-L439

I think we can change the condition to `receiveBufferSize < expectedRecvBufferSize` to only log a warning if the actual value is less that the expected value.

**Comment by borjam** [comment]
> The check we are using is expecting the value to be exactly the same:

Sorry to step on an old issue (and I am going to open a new, related one) but this deserves a clarification.

getsockopt(SO_RCVBUF) returning double the buffer size configured with setsockopt(SO_RCVBUF) is a **Linuxism**. Non standard (given that the sockets API is much older than Linux) and it breaks POLA.

So, the library doing this should implement the check in a Linux aware way. 

If you are on a Linux system and you do a setsockopt(SO_RCVBUF)  ->  expect double the amount when querying it with getsockopt(). At least until someone decides to add some implementation detail to the returned amount such as the number of power supplies or whatever ;)

On other standard socket subsystems it should return the same value.
