### ISSUE TITLE
Alert condition not working for long type for value >0.6

### ISSUE THREAD

**Issue by JaikumarKrishna** [Graylog2/graylog2-server#7721]
Hi ,

I am processing data which contains name , value columns. Value contains float,long types based on type of the name(name1,name2).

**name :name1
value: 0.7345
name:name2
Value:2.345**
In alert i have configured condition for particular name(name1 contains long value like 0.73) . If my name value greater than 0.6 it should trigger an alert.so i configured condition

**value > 0.6**

(maximum value is 1) ,But its not triggering the alert. Its working for float format name values(name2), . Whenever my datatype is long the alert condition is not working , I tried to convert this long into float in pipeline rule, but only long ,double functions are available there. Help me to sort out this issue.

**Find the below link which i posted in graylog  community , they told its a bug and asked me to raise an issue.**
[](https://community.graylog.org/t/alert-condition-not-working-for-long-type-for-value-0-6/14525)

Thanks,

**Comment by bernd** [comment]
@JaikumarKrishna Which Graylog version are you running?

**Comment by JaikumarKrishna** [comment]
@bernd 

Its Graylog 3.1.3

**Comment by bernd** [comment]
@JaikumarKrishna Can you please show us a screenshot of the event definition configuration page where you configured the condition? ("Filter & Aggregation" tab) Thank you!

**Comment by JaikumarKrishna** [comment]
@bernd 
Please find the screenshots
In this Metrics*pct I am processing **Metrics_process_memory_rss_pct,Metrics_process_cpu_total_pct,
Metrics_swap_used_pct,Metrics_memory_actual_used_pct**
and few more . Among those few are in long format, few are in float as i explained above.

![metrics1](https://user-images.githubusercontent.com/4845951/78216820-4c4b9080-74d8-11ea-862a-915bd0e49b4b.PNG)
![metrics2](https://user-images.githubusercontent.com/4845951/78216833-54a3cb80-74d8-11ea-84fa-3e55cfe588cd.PNG)

Thanks,

**Comment by mpfz0r** [comment]
I'm not sure whether this is a problem with alerting, or you're just having trouble ingesting
your data into graylog in the first place.

The alerting code treats every condition as double value, so I think it's unlikely to be a bug there.

Are you sure that you've got all your underlying data in graylog?
Or is this more of a mapping problem? (a field that was already mapped as long cannot be filled with float values).
