### ISSUE TITLE
TLSed up beats/gelf connections fail without jvm11

### ISSUE THREAD

**Issue by patcable** [Graylog2/graylog2-server#7726]
In Graylog 3.2.3 my TLS'ed up Beats and GELF HTTP inputs do not properly start because of:
```
2020-03-19T17:18:31.050Z WARN  [ChannelInitializer] Failed to initialize a channel. Closing: [id: 0xf414e0ee, L:/172.16.22.79:25044 - R:/172.16.10.39:52096]
java.lang.IllegalArgumentException: TLSv1.3
```

## Expected Behavior
TLS'ed up inputs work as expected and data flows to them after an upgrade.

## Current Behavior
No data is able to come into my graylog instance.

## Possible Solution
* Be more explicit that folks running JVM8 *need* to update `enabled_tls_protocols` because it wont work out of the box - vs burying it a few levels in the docs
* Tell folks to go to JVM 11 

## Steps to Reproduce (for bugs)
* Have inputs that use TLS (beats, gelf over http)
* Upgrade from 3.1.4 to 3.2.3
* Be running Java 8

## Your Environment
Was running a Java8. Now running Java11 things seem happy. Part of this is my bad - i looked at the changelog vs. the upgrade guide which is not how this project manages those changes. But i wanted to call it out and perhaps submit a doc fix because i think other folks who use TLS'ed up inputs may run into this.

**Comment by bernd** [comment]
@patcable What is the exact Java 8 version you are running?

TLSv1.3 works fine for me with the latest Java 8 version:

```
$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```

**Comment by patcable** [comment]
Fascinating -- Honestly, I would have bumped up my JVM8 version (it was pretty old 😬), but everything i found on the internet (and, eventually the config page) said i needed JVM11 for TLSv1.3 support, so I just went in that direction. I may put together a docs PR for that kind of thing.

**Comment by bernd** [comment]
Let's check if we can find out on input start if TLSv1.3 is supported in the JVM and then fall back to 1.2 if needed.

**Comment by bernd** [comment]
Also update documentation and upgrade notes and point to https://github.com/openjsse/openjsse

**Comment by patcable** [comment]
That sounds pretty reasonable. Thanks so much for taking the time! fwiw, so far so good on JVM11 - but any tuning recommendations on JVM8/11 would be a good thing to document too. ie - should folks continue to use CMS GC? I'm grabbing some of these assumptions from the Deployment stuff in https://github.com/Graylog2/graylog2-cookbook/blob/master/attributes/default.rb#L185

**Comment by mpfz0r** [comment]
@patcable Which exact java 8 version and OS do I need to reproduce this?

**Comment by mikkolehtisalo** [comment]
Just to comment about the GC question: No. Use G1, because it is simply more advanced and performs the best.

**Comment by mpfz0r** [comment]
refs #7130
