### ISSUE TITLE
Separate Extractors from Inputs

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#773]
Currently the extractors are persisted as embedded documents inside the inputs in MongoDB. This means that extractors currently cannot be shared between multiple inputs and will also be deleted if the enclosing input is being deleted.

Since extractors are describing actions on the contents of incoming messages and not the inputs themselves (or anything related to the concrete inputs at all), they should be standalone entities rather than embedded entities. Once the entities have been extracted, extractors could be used on multiple inputs in parallel without having to copy them around.

**Comment by bernd** [comment]
This will be obsolete with the upcoming message pipeline feature. Closing the issue.
