### ISSUE TITLE
Performance issue in aggregation builder drop-down

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#7753]
## Description

I have a Graylog setup with around 2600 fields. When typing in the drop-down fields to filter for a specific field, the input is lagging behing. In the following GIF I click into the select field and immediately start to type. I takes a while until my typed characters are visible. The same goes for deleting the characters with the backspace key.

In the animation I did:

1. Try to type "source" into the field (I typed wrong)
1. Delete the field name with backspace
1. Type source again

![Peek 2020-03-25 16-34](https://user-images.githubusercontent.com/461/77554601-94562c00-6eb6-11ea-88ad-48d6be1e8e52.gif)

The chrome performance tools show that the UI is spending a lot of time in the react-select library:

![Screenshot from 2020-03-25 16-31-40](https://user-images.githubusercontent.com/461/77554575-8c968780-6eb6-11ea-826e-9d7cb7d62128.png)

## Steps to Reproduce (for bugs)

1. Create a lot of message fields in Elasticsearch
2. Open the aggregation builder for a widget
3. Start to type in the "ROWS" field
4. Observe delay until characters show up

## Your Environment

* Graylog Version: 3.3.0-SNAPSHOT (rev 0ab8db1)

**Comment by ikaldus** [comment]
I have a similar setup regarding the fields count:  
There are about 2600 unique fields in all of the index sets. Majority of the logs are stored in index set having 2600 fields. There are also about 10 smaller index sets which contain about 30-100 fields each.

UI become almost unusable after upgrading from 2.3 to 3.2 and I'm observing exessive network traffic between Graylog web and mongo master node, also massive garbage colllection activity on the web nodes while users do search/dashboard related stuff.

So far I have tracked down that frequent queries are being made towards /api/views/fields that take about 70 seconds to complete and everything else seems to wait for them to complete. 
At the same time /api/system/fields returns all the 2600 field with 2-3 seconds.

**Comment by dennisoelkers** [comment]
Hey @ikaldus, thanks for the feedback!

The difference between `/api/system/fields` and `/api/views/fields` is that the former is querying Elasticsearch, while the latter is querying your MongoDB. Spending 70s to retrieve 2600 fields seems kinda excessive to me, is your MongoDB host particularly loaded or has very little resources?

**Comment by ikaldus** [comment]
My MongoDB is running with replicaset on 3 VMs that also host Graylog and Elasticsearch master node roles, but nothing else. Mongo is the main cpu user on the primary replicaset node and secondary nodes does not seem to service any queries other than needed for replication. Those VMs have 4vCPU and it's 30-40% utilized (load average around 3, peaks 16), but adding more CPUs does not really increase the speed of that query. 
From mongotop I see that most used collection at that time is index_field_types and mongostat shows net_out around 200m.
The index_field_types collection holds field information about 1500 indexes.

**Comment by dennisoelkers** [comment]
@ikaldus: I think I have found a reason for the issues you are seeing and created a PR addressing them in #7865. This should land in `3.3.0`, which will come out soon™. Thanks for your input!
