### ISSUE TITLE
Sorting numerical number not working

### ISSUE THREAD

**Issue by BaptisteBdn** [Graylog2/graylog2-server#7758]
I'm not able to sort on a field that is not the timestamp. I've tried with multiple field (strings and number) but is it not sorting correctly. 

## Expected Behavior
Sort a field in ascending/descending order.

## Current Behavior
When I try to sort a field containing doubles (or integer or strings) it is not sorted in the correct order. 

With doubles descending : (I've extracted the number and modified it with a pipeline)
![Screenshot_2020-03-26 Graylog(2)](https://user-images.githubusercontent.com/31347719/77632263-088fde80-6f4e-11ea-8957-0351e1888a33.png)

With strings descending : 
![Screenshot_2020-03-26 Graylog(1)](https://user-images.githubusercontent.com/31347719/77631946-95866800-6f4d-11ea-8a3d-fc9399a0f61e.png)

## Possible Solution
Maybe check the sort function ?

## Steps to Reproduce (for bugs)
1. Create a new field (number or string)
2. Try to sort on this field

## Context
I'm trying to sort my logs with a number to fix the inaccuracy of the timestamp sorting.

## Your Environment

* Graylog Version: 3.2.4
* Elasticsearch Version: 6.8.6
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Hey @BaptisteBdn!

Thanks a lot for reporting this. This is related to a very aggravating mistake of mine that slipped in into the release. I have created a PR addressing it and the next patch release will fix it. Sorry for the mess!
