### ISSUE TITLE
Absolute Timerange Searches unneeded Elasticsearch Indices

### ISSUE THREAD

**Issue by NickMeves** [Graylog2/graylog2-server#778]
During an absolute timerange search for a range decently in the past (lets say a search for the month of July), all indices that have any data after the "From" date are included in the search.

For instance rather than searching just the 10 indices that have messages in the time range of July (stored in Mongo via recalculate ranges, right?) it searches all 70 indices that have been created since the "From" date, significantly slowing down the search performance speed and taxing the Elasticsearch nodes.

**Comment by NickMeves** [comment]
Gonna self-bump this :)

Now that our data archives are much more expansive than when I posted this back in November, being able to look at slices of time in the past without having a query hit every open index since then would be huge.

Re-opening closed indices to find historical data is nearly impossible in Graylog since the search is too intensive.  We might have to move to analyzing them directly via Kibana so we can get an ES query just on the indices we want.

**Comment by bernd** [comment]
This will be fixed in the upcoming Graylog 1.2.0 release. The index range calculation and index selection has been updated.

I am closing this now, please re-open if you still have these problems with 1.2.0. Thank you!
