### ISSUE TITLE
Keyword Time Range always uses UTC timezone

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#7796]
The keyword time range used by our search is creating a new `Parser` instance in the `NaturalDateParser` class using the `UTC` timezone. This returns incorrect/unexpected results for time specifications. E.g. "yesterday 00:00:00" results in "02:00:00" for CET.

There are two options:

  - refactoring the time range classes so keyword time ranges have access to the timezone of the user who is executing the search
  - **adding a `timezone` property to the keyword range which allows setting a timezone**

Refs #7358

**Comment by cawfehman** [comment]
perhaps related to this bug, or perhaps just more of a data point.  The keyword yesterday is not behaving as I would think.  If I run a search using keyword "yesterday"  today April 6, 2020, I would think it would tell Graylog to limit the search to April 5, 2020 from 00:00:00 to 23:59:59.  Instead it returns results from the previous 24 hours, beginning with the current time.

searching for "yesterday" at 11:23:00am returns results from April 5, 2020 11:23:00 through April 6, 2020 11:22:59.

those are the same results as when searching for the "last 24 hours".  That is working as expected.

again, not sure if related or another data point, or something else.

**Comment by radykal-com** [comment]
Hi @dennisoelkers,

My PR is almost working, I'm a newbie with react (well, with any frontend technology) and I'm unable to load the currentUser to get the timezone.

It's always loading the default one: https://github.com/Graylog2/graylog2-server/pull/7911/files#diff-247bc39966476e445d297a7d2c315b78R127
If I change the default one to any other it works as expected, but it never loads the one from the user.

Can you check what is wrong with it please? 

Thanks you,

**Comment by radykal-com** [comment]
@cawfehman as per your question, seems the problem is in the underlying library Graylog uses to parse natural language into date ranges.
Check: http://natty.joestelmach.com/doc.jsp
Most of the dates are interpreted as relative, so yesterday is like "from 24 hours ago"

**Comment by cawfehman** [comment]
@radykal-com Thanks for the info... but there are alot of issues IMO with having yesterday == from 24 hours ago.  For example, If it's 1pm and I want to do a search from something that happened at 12pm, selecting yesterday shouldn't return those results and yet it does.  Likewise... searching for something that occured at 12pm the previous day, yesterday should return those results and it doesn't.   

Taking a quick look at the link you sent seems to indicate that the relative dates (like yesterday) should only take into account the date and not the time. so from that, yesterday should be just that.

Appreciate you taking time to look at this... Sorry for the delayed response.
