### ISSUE TITLE
Changing Number of Values in Pivot Configuration doesn't work in Safari

### ISSUE THREAD

**Issue by fmalykh** [Graylog2/graylog2-server#7806]
## Expected Behavior

Changing _Number of Values_ in Pivot Configuration for a selected _ROW_ should update search results presenting number of values chosen.

## Current Behavior

Changing _Number of Values_ in Pivot Configuration  for a selected _ROW_ cleares current search and Pivot. Default search screen is presented.

## Steps to Reproduce (for bugs)

1. Type a search query of your interest
2. Click _Fields_, select any, click _Show top values_
3. When a _Pivot_ appears (Aggregating count() by FieldName), click _Actions_ button, _Edit_
4. In the _ROWS_ filter, click on the field you are performing aggregation on
5. Change _Number of Values_ and press _Done_

![image](https://user-images.githubusercontent.com/49435326/78131139-39c34f80-7423-11ea-96f7-f596fa9d7928.png)

## Context

I can no longer change _Nuber of Values_ (ex. _TOP X Values_)
This works fine in Chrome.
## Your Environment

* Graylog Version: 3.2.4-1
* Elasticsearch Version: 6.8.7
* MongoDB Version: 4.0.13
* Operating System: macOS Catalina 10.15.4
* Browser version: Safari 13.0.5 (15608.5.11)

**Comment by dennisoelkers** [comment]
Thanks @fmalykh for reporting this! I can reproduce this on my machine. We will investigate it and fix this in one of the next versions!
