### ISSUE TITLE
Provide percentage and count view just like "quick values" of Graylog Version pre 3.2

### ISSUE THREAD

**Issue by bksts** [Graylog2/graylog2-server#7822]
Beginning with Graylog Version 3.2, I am missing a daily used feature

**Pre Vers 3.2 had "quick values**"

quick value show both:
a) percentage and
b) count
of a field value

I really felt in love with this table having percentage and count value in one row.
Number one usage for investigations!
![grafik](https://user-images.githubusercontent.com/46027642/78331392-3b595880-7586-11ea-913c-ecbc7c7c0519.png)

**since Vers 3.2.3 "show top values"**
show top values shows only:

a) count
of a field value

Now you need to create another widget (Pie chart) to get precentage
![grafik](https://user-images.githubusercontent.com/46027642/78331460-5deb7180-7586-11ea-851d-18a94ad0cb85.png)

It’s getting more complicated and the “percentage” values of field names are getting harder to see.

A table view (message table) including “count” and “percentage” was perfect!

**Comment by dennisoelkers** [comment]
Thanks for reporting this, @bksts! 

We already have that on our list and will bring it back in one of the next versions. I will keep you updated in this issue!

**Comment by andreydanin** [comment]
Percentage and count were available in a pie char view earlier. Pie chart in 3.3.9 contains only percentage (without count) :(

**Comment by aim4r** [comment]
The question about this specific feature has  been asked to @lennartkoopmann in a recent GL 4 demo. If memory serves, he indicated that the feature was "never gone", and that it has always been available in recent GL versions via the quick values menu. 

I might be missing the obvious, but on the recent GL versions (including 4) I never figured out how to display _percentages_ **and** _count_ in a data table.

Looking at the community site and the issues in Github, it seems that _many_ other loyal users are also missing this capability.

**Comment by joakimlemb** [comment]
Any updates on this? The "quick value" feature is one of the most useful ones, and the new type is way worse than the old one.

**Comment by HungryHowies** [comment]
I'm curious also

**Comment by steljwagh** [comment]
Me too, I just spend 2 hours on getting a percentage besides count, just to find this issue.

**Comment by H2Cyber** [comment]
> Thanks for reporting this, @bksts!
> 
> We already have that on our list and will bring it back in one of the next versions. I will keep you updated in this issue!

Is this feature still on the radar for a future release ? We really miss the ability to display percentages besides count.

**Comment by pachecogonzalo** [comment]
> Thanks for reporting this, @bksts!
> 
> We already have that on our list and will bring it back in one of the next versions. I will keep you updated in this issue!

Do you have this feature still in mind for future realeases? We're installing a new Graylog 5.0 cluster and this feature actually makes me doubt if I prefer the 5.0 over the 3.1.4 (which we still didn't upgrade)

**Comment by JBHilke** [comment]
This is also one of the reasons we have not updated our 3.1.4 Graylog.  We have a test Graylog now running version 5.1 but it still does not have Quick Values, or the easy pivot to Histogram, which makes quick analytical work easy.   In the versions before 3.2, you can build a histogram of values in 3 clicks.

**Comment by dennisoelkers** [comment]
Hey @pachecogonzalo, @JBHilke,

we are currently working on a PR (#15738) reimplementing this, which will be part of `5.2`. Thanks for your patience!
