### ISSUE TITLE
Graylog event definitions do not get scheduled correctly after editing "Search within the last"

### ISSUE THREAD

**Issue by oaxiento** [Graylog2/graylog2-server#7841]
We noticed that event definitions do not run as configured (eg. every 1 minutes) after changing the "Search within the last" setting.

## Current Behavior
When we create an event definition and set the following fields under "Filter & Aggregation":

- Search within the last: 1 minutes
- Execute search every: 1 minutes

... the following mongo document will be created in "scheduler_triggers":

```json
{
	"_id": "5e8c6a0688ea5f254b775049",
	"job_definition_id": "5e8c6a0688ea5f254b775048",
	"start_time": "2020-04-07T11:54:46.852Z",
	"end_time": null,
	**"next_time": "2020-04-07T11:55:46.851Z",**
	"created_at": "2020-04-07T11:54:46.852Z",
	"updated_at": "2020-04-07T11:54:46.852Z",
	"triggered_at": "2020-04-07T11:54:52.546Z",
	"status": "runnable",
	"lock": {
		"clock": "0",
		"progress": 0,
		"last_lock_time": "2020-04-07T11:54:52.546Z",
		"owner": null
	},
	"schedule": {
		"type": "interval",
		"interval": "60000",
		"unit": "MILLISECONDS"
	},
	"data": {
		"type": "event-processor-execution-v1",
		"timerange_from": "2020-04-07T11:54:46.852Z",
		"timerange_to": "2020-04-07T11:55:46.851Z"
	}
}
```

So far, so good. Everything works as expected and the scheduler runs every minute. After we change the event definition to:

- Search within the last: 5 hours
- Execute search every: 1 minutes

... the mongo document will be changed to:

```json
{
	"_id": "5e8c6a0688ea5f254b775049",
	"job_definition_id": "5e8c6a0688ea5f254b775048",
	"start_time": "2020-04-07T11:54:46.852Z",
	"end_time": null,
	**"next_time": "2020-04-07T16:55:46.852Z",**
	"created_at": "2020-04-07T11:54:46.852Z",
	"updated_at": "2020-04-07T11:56:12.494Z",
	"triggered_at": "2020-04-07T11:55:52.296Z",
	"status": "runnable",
	"lock": {
		"clock": "0",
		"progress": 0,
		"last_lock_time": "2020-04-07T11:55:52.296Z",
		"owner": null
	},
	"schedule": {
		"type": "interval",
		"interval": "60000",
		"unit": "MILLISECONDS"
	},
	"data": {
		"type": "event-processor-execution-v1",
		"timerange_from": "2020-04-07T11:55:46.852Z",
		"timerange_to": "2020-04-07T16:55:46.852Z"
	}
}
```

Notice the "next_time" field. After changing the event definition, the scheduler will only run this job 5 hours after the change, even though it should still be running every minute. After 5 hours the job will run every 1 minute again.

## Expected Behavior
Changing "Search within the last" should not affect the time on which the job will run next.

## Steps to Reproduce (for bugs)
1. Create a new event definition
2. Under "Filter & Aggregation" set  "Search within the last" to "1 minutes" and "Execute search every" to "1 minutes"
3. Save the definition
4. Open the event definition and change the value for "Search within the last" to "5 hours"

## Your Environment

* Graylog Version: 3.1.4
* Elasticsearch Version: 6.8.7
* MongoDB Version: 4.0.16
* Operating System: CentOS 7
* Browser version: Firefox 75

**Comment by radykal-com** [comment]
Hi, I cannot reproduce this one in latest version

**Comment by oaxiento** [comment]
Hi, I can reproduce the issue on 3.2.4 ...

I created an event definition with the default schedule and search period (Search within the last: 1 min, Execute search every: 1 min). Having a look at the database the follwoing objects got created:

Object in `scheduler_job_definitions`:
```
{
	"_id": "5e9571cb282603772aa4350f",
	"title": "TEST321",
	"description": "",
	"config": {
		"type": "event-processor-execution-v1",
		"event_definition_id": "5e9571cb282603772aa4350d",
		"parameters": {
			"type": "aggregation-v1",
			"timerange": {
				"type": "absolute",
				"from": "2020-04-14T08:17:19.896Z",
				"to": "2020-04-14T08:18:19.896Z"
			},
			"streams": [],
			"batch_size": 500
		},
		"processing_window_size": "60000",
		"processing_hop_size": "60000"
	}
}
```

Object in `scheduler_triggers`:
```
{
	"_id": "5e9571cb282603772aa43510",
	"job_definition_id": "5e9571cb282603772aa4350f",
	"start_time": "2020-04-14T08:18:19.907Z",
	"end_time": null,
	"next_time": "2020-04-14T08:19:25.837Z",
	"created_at": "2020-04-14T08:18:19.907Z",
	"updated_at": "2020-04-14T08:18:19.907Z",
	"triggered_at": "2020-04-14T08:19:20.828Z",
	"status": "runnable",
	"lock": {
		"clock": "0",
		"progress": 0,
		"last_lock_time": "2020-04-14T08:19:20.828Z",
		"owner": null
	},
	"schedule": {
		"type": "interval",
		"interval": "60000",
		"unit": "MILLISECONDS"
	},
	"data": {
		"type": "event-processor-execution-v1",
		"timerange_from": "2020-04-14T08:18:19.897Z",
		"timerange_to": "2020-04-14T08:19:19.896Z"
	}
}
```

After setting _"Search within the last"_ to 5 hours, while leaving _"Execute search every"_ at 1 minute:

Object in `scheduler_job_definitions`:
```
{
	"_id": "5e9571cb282603772aa4350f",
	"title": "TEST321",
	"description": "",
	"config": {
		"type": "event-processor-execution-v1",
		"event_definition_id": "5e9571cb282603772aa4350d",
		"parameters": {
			"type": "aggregation-v1",
			"timerange": {
				"type": "absolute",
				"from": "2020-04-14T03:20:06.177Z",
				"to": "2020-04-14T08:20:06.177Z"
			},
			"streams": [],
			"batch_size": 500
		},
		"processing_window_size": "18000000",
		"processing_hop_size": "60000"
	}
}
```

Object in `scheduler_triggers`:
```
{
	"_id": "5e9571cb282603772aa43510",
	"job_definition_id": "5e9571cb282603772aa4350f",
	"start_time": "2020-04-14T08:18:19.907Z",
	"end_time": null,
	"next_time": "2020-04-14T13:19:19.897Z",
	"created_at": "2020-04-14T08:18:19.907Z",
	"updated_at": "2020-04-14T08:20:06.180Z",
	"triggered_at": "2020-04-14T08:19:25.843Z",
	"status": "runnable",
	"lock": {
		"clock": "0",
		"progress": 0,
		"last_lock_time": "2020-04-14T08:19:25.843Z",
		"owner": null
	},
	"schedule": {
		"type": "interval",
		"interval": "60000",
		"unit": "MILLISECONDS"
	},
	"data": {
		"type": "event-processor-execution-v1",
		"timerange_from": "2020-04-14T08:19:19.897Z",
		"timerange_to": "2020-04-14T13:19:19.897Z"
	}
}
```

You just have to look at the _"next_time_" setting, which gets set from "next_time": "2020-04-14T**08:19:25.837**Z" to "next_time": "2020-04-14T**13:19:19.897**Z" (+5h). So this job will not run every minute after it got saved, it will start running every minute, 5 hours later than expected. In my understanding "next_time" shouldn't be touched when changing "Search within the last", as the schedule (execute every 1 min) stays the same.

**Comment by radykal-com** [comment]
Hi @oaxiento I've tested it again with my 3.2.4 version cluster and I could reproduce the error as you described. When I tried past day I used my local copy with latest changes from master and I could not reproduce it
