### ISSUE TITLE
Disable searching via onChange event

### ISSUE THREAD

**Issue by oinqu** [Graylog2/graylog2-server#7849]
## What?

`onChange` actions inside searchbar component should be optional. Using a mouse to unselect the search query bar, the streams bar or time range bars should not re-run search queries. Making a search query should be possible only by pressing the green search button.

Our company is missing the ability to configure this behavior globally in, for example, Graylog search configuration menu.

## Why?

I understand that `onChange` functionality may be very useful for some, but with large installations it tends to cause an increase of systems load, which can be easily avoided, and harm user experience. 

Our Graylog installation is shared within tens of devops teams, so we have many concurrent users actively using the platform for searching their logs. In some cases, users can perform 3-5 or even more unwanted search queries during composing the query they actually want to run. Usually those unwanted queries are caused by copying and pasting text from elsewhere into the search bar, stream and time range changes. Those queries can be quite large, containing something ambiguous (wildcards, large time periods), hence the systems load increase.

This search bar behavior can be especially annoying in case you want to copy some part of some message from the previous query, but clicking on the message unfocuses the search bar with an unfinished query and this runs a new search, causing the desired message to be gone from messages widget below.

## Your Environment

* Graylog Version: Graylog 3.2.4+a407287 (Docker)

**Comment by dennisoelkers** [comment]
Thanks for the feedback, @oinqu! It helps us a lot putting your request into context.

We are already tracking the same issue in #7572. To ease our process, I am closing this issue.

I am currently working on a PR that is addressing this issue (#7829), which will be part of the upcoming `3.3.0`, which will be released pretty soon.
