### ISSUE TITLE
Grok - when extracting integers or specific field type, all imported are text not grok field type like integer or date. 

### ISSUE THREAD

**Issue by asmodianx** [Graylog2/graylog2-server#7856]
Grok - when extracting integers or specific field type, all imported are text not grok field type.  need to have converters like in regex parsing or make fields with grok types
## Expected Behavior

Grok extracts with "%{BASE10NUM:numerical_field}" should get hinted at the field type of number.

OR that field needs to have a numerical converter that can be applied to it like in regex's

AND/OR reporting needs an option to apply string-to-number() function so a text field can be used in charting.

## Current Behavior

GROKING values currently only creates text fields

## Possible Solution

there are sum and other functions in graphs, why not add a string to number function so badly extracted fields can have useable charting?
## Steps to Reproduce (for bugs)

1. create grok extractor
2. extract a number %{BASE10NUM:numerical_field} 
3. try to do a line chart on the resulting event numerical_field field.
4. chart malfunctions because numerical_field is text

## Context

grok expressions are a means of streamlining extraction of data from log events but only does so with text which is only good for top 10 lists.  I would argue the ability to chart numbers in log management has much more value than a simple top 10 list and so either improving the grok extractor page to include a type hint or a field by field type identification feature or a string to number function in the chart feature would provide significant improvement in graylog.
## Your Environment

Graylog 3.2.3+a9c061c on aux-graylog1 (Private Build 1.8.0_242 on Linux 4.15.0-91-generic)
es 6.8.7
mdb 4.0.16
ubuntu 18.04
firefox

**Comment by bernd** [comment]
@asmodianx You can use converters in your grok patterns as documented here: https://docs.graylog.org/en/3.2/pages/extractors.html#using-grok-patterns-to-extract-data

Example: `len=%{NUMBER:length;int} src=%{IP:srcip} sport=%{NUMBER:srcport} dst=%{IP:dstip} dport=%{NUMBER:dstport}`

Is that enough for your use case?

**Comment by asmodianx** [comment]
tested with floating point numbers, long and int.  no success.
the extractor test suggested that my syntax is correct in that float numbers had ".0" added to them however the resulting fields are still strings.

**Comment by asmodianx** [comment]
Example I used:  {BASE10NUM:class1_qos_kbps:float}

**Comment by bernd** [comment]
> Example I used: {BASE10NUM:class1_qos_kbps:float}

@asmodianx The separator between the field name is a semicolon (`;`) not a colon (`:`). Is that the issue?

**Comment by asmodianx** [comment]
Error when trying to apply avg function
While retrieving data for this widget, the following error(s) occurred on field that had grok long hint set:

"Unable to perform search query: Expected numeric type on field [class4_qos_kbps], but got [keyword]."

**Comment by asmodianx** [comment]
tried 

> 
> 
> > Example I used: {BASE10NUM:class1_qos_kbps:float}
> 
> @asmodianx The separator between the field name is a semicolon (`;`) not a colon (`:`). Is that the issue?

Tried that too.  docs say ":" though

**Comment by asmodianx** [comment]
good call on syntax.  this make a little progress but charts still not working. 
"While retrieving data for this widget, the following error(s) occurred:
    Unable to perform search query: Expected numeric type on field [class4_qos_kbps], but got [keyword]."

**Comment by asmodianx** [comment]
and yes, im limiting the search to most resent values with extractor changes

**Comment by asmodianx** [comment]
do the charts need a specific kind of number? long?  It seems silly to not be able to change the number from string or type to float or double with a function within the chart as some times you are dealing with data from different sources using different number types or text.

**Comment by asmodianx** [comment]
My observations so far:  Though I am seeing the extractor "think" its getting numbers its being ingested into elasticsearch as text.  Though I noticed something interesting.  the field changes from "String" to "Class2_qos_kbps = compound(long,string)" after rolling the index.  So I think this resolve the immediate issue. though I would like to see some type conversion functions for charts in the future.  Thanks for hanging in there with me.
