### ISSUE TITLE
Message Count Display Issue

### ISSUE THREAD

**Issue by bud1979** [Graylog2/graylog2-server#7883]
Message Count window by default has a visual flaw when displaying on the Search Page.

## Expected Behavior
Would like to see the date and time in full, and not have the "legend" over top of those fields in the default view

## Current Behavior
Currently when you load the search the "count()" is over the time increments and does not show them nicely in the windows.  If you expand this down do 2.5-3x length it shows up cleaner.

<img width="305" alt="Screen Shot 2020-04-15 at 7 43 56 AM" src="https://user-images.githubusercontent.com/26657656/79344716-6a0ff100-7eed-11ea-8a1a-790ddc91e688.png">

Expanded: 

<img width="320" alt="Screen Shot 2020-04-15 at 7 43 33 AM" src="https://user-images.githubusercontent.com/26657656/79344750-76944980-7eed-11ea-8b53-07073e35b68a.png">

## Steps to Reproduce (for bugs)

1. Open search Page

## Context
Just generally using the product, this can be a visual defect

## Your Environment

* Graylog Version: 3.2.4
* Elasticsearch Version: 6.8
* MongoDB Version: 4.x
* Operating System: Mac
* Browser version: Chrome

**Comment by kmerz** [comment]
We only show the legend if more then one label is visible, that is why we do not show the legend anymore in the message histogram. Problem solved.
