### ISSUE TITLE
Dashboard widget search text should still be readable when it is overridden

### ISSUE THREAD

**Issue by miwent** [Graylog2/graylog2-server#7912]
## What?

The widget search text should still be readable even when there is a filter overriding the search time/query values.

## Why?

Sometimes when building dashboards it's useful to know what the widget search query text is.

Viewing the widget search query currently requires first disabling the overriding filter.

![image](https://user-images.githubusercontent.com/61566003/79600635-78106e00-80b5-11ea-85ec-b043d4055317.png)

It may even make sense to allow edits to the search query even when filtered as the widget search is still active.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Fixed in #10527.
