### ISSUE TITLE
some logs messages don't show on dashboard (but are received)

### ISSUE THREAD

**Issue by Urahara** [Graylog2/graylog2-server#7959]
## Expected Behavior
All messages sent have to show properly. 

## Current Behavior
I feed graylog daily with over 100 different apps, but in some cases some messages from random apps start don't show, and then suddenly reappear (without me doing anything). 

## Possible Solution
Don't know, sometimes i reboot my machine but it doesn't always work.

## Steps to Reproduce (for bugs)
I don't know how to simulate it because it happens randomly. **But I noticed that although it doesn't appear in the interface, messages appear in the journalctl.**, another thing i realized is that sometimes removing some **extra fields** the messages start appear.

I use the command below to see if the message is sent:
```sh
tail -f /var/log/graylog-server/server.log | grep message
```

## Context
I'm trying to keep up with my processes and it hurts me because I don't know if the process is running correctly.

## Your Environment

* Graylog Version: 2.4.7+9116ead
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Ubuntu 16.04.6 LTS
* Browser version:

I don't where i have to lookup to find Elasticsearch/MongoDB version.

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
