### ISSUE TITLE
Define unmapped type for sort fields in CSV export

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#7963]
If a field is specified for sorting for a CSV export that does not exist in all affected indices, an exception will be thrown, because Elasticsearch does not know which type it should use to sort on. 

To prevent this, we need to provide an unmapped type option value for the field, similar to what we are doing in #7569. This means: If the field is present in at least one of the indices, we should use the type from there to pass as unmapped type. If the field is present in none of the indices, we should provide an arbitrary type. If if exists with multiple types, we need some kind of resolution logic, trying to map those types onto a third type or bailing out.

**Comment by todvora** [comment]
Related to the old legacy CSV export. There is no sorting in the current export implementation. Closing this issue now. Feel free to reopen if there is still any usage for this.
