### ISSUE TITLE
How to get RPM?

### ISSUE THREAD

**Issue by Djf2884** [Graylog2/graylog2-server#798]
Hello,

I m actually using graylog2 since some month but due to security reason i had to remove it from DMZ zone after installation time.

Graylog2 servers are installed with RPMs for Redhat 6 (EL6) and i would like to continue to use the RPM packages instead of tar.gz.

It seem that i can't download rpm directly from graylog2 website but i need to use the repository and unfortunatelly i can't download rpm packages on my computer to upload them on my jump server.

Is there anyway to download GRAYLOG2 RPM on a windows computer?

Thx for ur help.

**Comment by bernd** [comment]
Thanks for the report. We will make the package repository browsable in the future so you will be able to find and download the packages directly.

**Comment by Djf2884** [comment]
Thx u bernd :)

**Comment by bernd** [comment]
You can now browse the package repository here: https://packages.graylog2.org/
