### ISSUE TITLE
Setting "disable_output_cache = true"  makes radio node master cache grow very quickly.

### ISSUE THREAD

**Issue by timukas** [Graylog2/graylog2-server#799]
Hi,

In graylog2-server-0.93.0-SNAPSHOT-20141202145626 with radio, disabling cache output (disable_output_cache = true) makes radio master cache constantly increasing.
Rabbitmq message rate drops from 4500 event/sec to 3200 event/sec.

When output cache enabled, radio's master cache is empty, message rate is ~4500, but output cache is not used.

Seems strange to me or what do you think?

**Comment by bernd** [comment]
The input and output caches have been removed for 0.93. I will close this issue, please reopen if you still see problems with radio and RabbitMQ. Thank you!
