### ISSUE TITLE
"Your Graylog Enterprise license is missing." when enterprise plugin installed without license

### ISSUE THREAD

**Issue by coffee-squirrel** [Graylog2/graylog2-server#7990]
## Expected Behavior

Enterprise plugins being installed should not have any impact unless an Enterprise license (valid or invalid) exists.

## Current Behavior

If an environment has the Enterprise plugins installed, but not an Enterprise license, users will see a red banner in the Search view:

> Your Graylog Enterprise license is missing.
> To be able to use parameter support in views, you need to obtain a valid Graylog Enterprise license. For further information, please check the Graylog Enterprise page.

## Possible Solution

Check whether an Enterprise license exists, do nothing related to Enterprise functionality if one does not.

## Steps to Reproduce (for bugs)

1. Create a 3.2.4 environment with Enterprise plugins and an Enterprise license installed
2. Remove the Enterprise license (perhaps the limits were exceeded)
3. Note the aforementioned red banner shows up in the Search view
4. Remove the Enterprise plugins and restart Graylog
5. Note the banner no longer shows up

## Context

We have an environment that was using a 5GB/day license, but exceeded that limit.  We decided to remove the license for now to clear up the Enterprise license violation banner.  After removing the license we then had a red banner on the Search page about the Enterprise license missing.

Related to https://community.graylog.org/t/ent-license-requested-after-update-to-3-2-2/14125/7 , and somewhat related to #6451 (where having the Enterprise plugins installed without a license resulted in odd behavior).

## Your Environment

* Graylog Version: 3.2.4  (matching Enterprise plugins)
* Elasticsearch Version: 6.8.6
* MongoDB Version: 4.0.16
* Operating System: RHEL
* Browser version: Firefox 74 and Chrome 80

**Comment by kroepke** [comment]
Yes, you are right, that page should not display the warning so prominently when there are no licenses installed.

**Comment by coffee-squirrel** [comment]
@dennisoelkers Out of curiosity, why was this closed?

**Comment by coffee-squirrel** [comment]
@dennisoelkers was this closed intentionally?
