### ISSUE TITLE
Worldmap viewport changes when switching between dashboard pages

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#7997]
The worldmap widget is currently changing its viewport, when a user switches between dashboard pages.

![worldmap-viewport](https://user-images.githubusercontent.com/46300478/80570152-9867f300-89fa-11ea-8a2b-cc6d18427d83.gif)

While we've fixed this problem for dashboards with a scrollbar https://github.com/Graylog2/graylog2-server/issues/7107 it still occurs in the described scenario.

The main problem is the worldmaps width (prop) is changing while the widget grid is being built.
One possible fix is defining a `key` for the `Map` component which includes the provided width. But we should try to avoid changing the width while building the widget grid. Using the `key` prop will result in unnecessary re-renders.

* Graylog Version: 3.3.beta1

**Comment by dennisoelkers** [comment]
I just tried to reproduce the issue and I am not sure if I understood it correctly. When I open a dashboard with a world map and change the center of the map, switching back and forth between another dashboard tab centers the world map back to the viewport defined when saving it. When I do not change the center of the map and switch back and forth between other tabs, I always end up with the same viewport of the map.

So generally this kinda works as expected, but is not ideal for the user. If a user is centering the map differently than persisted and switches tabs to look up something else, a user would expect the map to still have the same viewport and not getting recentered. Unfortunately, we are only mounting widgets which are currently visible and unmount widgets of a tab which is left, so we don't know the previous state anymore. If we want to keep it, we have two options:

  1.) maintain a temporary state in the frontend that is not persisted
  2.) always mount all widgets, even those which are not shown
