### ISSUE TITLE
Search page scrolling not working properly with Safari

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#8003]
The search page scrolling is currently not working properly with Safari:
![image](https://user-images.githubusercontent.com/46300478/80586484-50a29500-8a15-11ea-97cb-f390438cc558.png)

`overflow: auto` does not have an effect on the search page content section. One possible solution is define the fixed height `height: calc(100vh - 50px)` for this section instead of the `div` which contains the content and the sidebar.

* Graylog Version: 3.3.beta1

**Comment by WouldYouKindly** [comment]
Same with 3.2.4
