### ISSUE TITLE
graylog-plugin-integrations  build mvn

### ISSUE THREAD

**Issue by dio99** [Graylog2/graylog2-server#8014]
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.graylog.plugins:graylog-plugin-integrations:jar:3.2.4
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: io.pkts:pkts-core:jar -> duplicate declaration of version 3.0.5 @ line 136, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ----------< org.graylog.plugins:graylog-plugin-integrations >-----------
[INFO] Building graylog-plugin-integrations 3.2.4
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- frontend-maven-plugin:1.8.0:install-node-and-yarn (install node and yarn) @ graylog-plugin-integrations ---
[INFO] Node v12.13.1 is already installed.
[INFO] Yarn 1.19.2 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.8.0:yarn (yarn install) @ graylog-plugin-integrations ---
[INFO] yarn not inheriting proxy config from Maven
[INFO] Running 'yarn install' in /home/larssand/Downloads/graylog/graylog-plugin-integrations
[INFO] yarn install v1.19.2
[INFO] [1/4] Resolving packages...
[INFO] success Already up-to-date.
[INFO] Done in 0.25s.
[INFO] 
[INFO] --- frontend-maven-plugin:1.8.0:yarn (yarn run build) @ graylog-plugin-integrations ---
[INFO] yarn not inheriting proxy config from Maven
[INFO] Running 'yarn run build' in /home/larssand/Downloads/graylog/graylog-plugin-integrations
[INFO] yarn run v1.19.2
[INFO] $ webpack --bail
[INFO] Running in production mode
[INFO] Hash: 9ec463eef3b47da2f305
[INFO] Version: webpack 3.12.0
[INFO] Time: 1420ms
[INFO]                                                                          Asset       Size  Chunks             Chunk Names
[INFO]     plugin.org.graylog.integrations.IntegrationsPlugin.9ec463eef3b47da2f305.js      63 kB       0  [emitted]  plugin.org.graylog.integrations.IntegrationsPlugin
[INFO] plugin.org.graylog.integrations.IntegrationsPlugin.9ec463eef3b47da2f305.js.map     367 kB       0  [emitted]  plugin.org.graylog.integrations.IntegrationsPlugin
[INFO]                                                                    favicon.png  436 bytes          [emitted]  
[INFO]                                                                     index.html  410 bytes          [emitted]  
[INFO]                                                                    module.json  285 bytes          [emitted]  
[INFO]                 plugin.org.graylog.integrations.IntegrationsPlugin.module.json  285 bytes          [emitted]  
[INFO]    [1] delegated ./node_modules/prop-types/index.js from dll-reference __vendor 42 bytes {0} [built]
[INFO]    [2] delegated ./node_modules/react/react.js from dll-reference __vendor 42 bytes {0} [built]
[INFO]    [7] ./src/web/aws/common/Routes.js 1.37 kB {0} [built]
[INFO]   [13] ./src/web/index.jsx 1.01 kB {0} [built]
[INFO]   [14] ../graylog2-server/graylog2-web-interface/src/webpack-entry.js 703 bytes {0} [built]
[INFO]   [18] ../graylog2-server/graylog2-web-interface/src/util/AppConfig.js 744 bytes {0} [built]
[INFO]   [22] ./src/web/aws/AWSInputConfiguration.jsx 856 bytes {0} [built]
[INFO]   [23] ../graylog2-server/graylog2-web-interface/src/util/History.js 284 bytes {0} [built]
[INFO]   [37] ./src/web/aws/cloudwatch/CloudWatchApp.jsx 2.24 kB {0} [built]
[INFO]   [41] ./src/web/aws/context/Sidebar.jsx 337 bytes {0} [built] [failed] [1 error]
[INFO]   [42] ./src/web/aws/context/FormData.jsx 2.77 kB {0} [built]
[INFO]   [43] ./src/web/aws/context/Steps.jsx 2.76 kB {0} [built]
[INFO]   [44] ./src/web/aws/context/Api.jsx 3.23 kB {0} [built]
[INFO]   [45] ./src/web/aws/context/AdvancedOptions.jsx 2.21 kB {0} [built]
[INFO]   [48] ./package.json 495 bytes {0} [built]
[INFO]     + 34 hidden modules
[INFO] 
[INFO] ERROR in ./src/web/aws/cloudwatch/CloudWatch.jsx
[INFO] Module build failed: SyntaxError: Unexpected token (113:5)
[INFO] 
[INFO]   111 | 
[INFO]   112 |   return (
[INFO] > 113 |     <>
[INFO]       |      ^
[INFO]   114 |       {dirty && !lastStep && <ConfirmLeaveDialog route={route} question="Are you sure? Your new Input will not be created." />}
[INFO]   115 |       <Wizard steps={wizardSteps}
[INFO]   116 |               activeStep={currentStep}
[INFO] 
[INFO]  @ ./src/web/aws/cloudwatch/CloudWatchApp.jsx 29:18-41
[INFO]  @ ./src/web/index.jsx
[INFO] 
[INFO] ERROR in ./src/web/aws/context/Sidebar.jsx
[INFO] Module build failed: SyntaxError: Unexpected token (7:42)
[INFO] 
[INFO]    5 | 
[INFO]    6 | export const SidebarProvider = ({ children }) => {
[INFO] >  7 |   const [sidebar, setSidebar] = useState(<></>);
[INFO]      |                                           ^
[INFO]    8 | 
[INFO]    9 |   const clearSidebar = () => {
[INFO]   10 |     setSidebar(<></>);
[INFO] 
[INFO]  @ ./src/web/aws/cloudwatch/CloudWatchApp.jsx 19:15-45
[INFO]  @ ./src/web/index.jsx
[INFO] Child html-webpack-plugin for "index.html":
[INFO]      1 asset
[INFO]        [0] ../graylog2-server/graylog2-web-interface/node_modules/html-webpack-plugin/lib/loader.js!../graylog2-server/graylog2-web-interface/templates/index.html.template 1.71 kB {0} [built]
[INFO]        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
[INFO]        [3] (webpack)/buildin/module.js 517 bytes {0} [built]
[INFO]         + 1 hidden module
[INFO] Child html-webpack-plugin for "module.json":
[INFO]      1 asset
[INFO]        [0] ../graylog2-server/graylog2-web-interface/node_modules/html-webpack-plugin/lib/loader.js!../graylog2-server/graylog2-web-interface/templates/module.json.template 541 bytes {0} [built]
[INFO]        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
[INFO]        [3] (webpack)/buildin/module.js 517 bytes {0} [built]
[INFO]         + 1 hidden module
[INFO] Child html-webpack-plugin for "plugin.org.graylog.integrations.IntegrationsPlugin.module.json":
[INFO]      1 asset
[INFO]        [0] ./node_modules/html-webpack-plugin/lib/loader.js!../graylog2-server/graylog2-web-interface/templates/module.json.template 575 bytes {0} [built]
[INFO]        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
[INFO]        [3] (webpack)/buildin/module.js 517 bytes {0} [built]
[INFO]         + 1 hidden module
[INFO] error Command failed with exit code 2.
[INFO] error Command failed with exit code 2.info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.734 s
[INFO] Finished at: 2020-04-30T16:32:28+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:yarn (yarn run build) on project graylog-plugin-integrations: Failed to run task: 'yarn run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
