### ISSUE TITLE
Allow cloning of existing event definitions

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#8017]
## What?

Allow cloning of existing event definitions in the UI. Using the "clone" button should open the "new event definition" page so the user can adjust and save it.

## Why?

If you create lots of similar event definitions it's pretty tedious to always start from scratch. Having cloning support would make this way easier.

## How?

Add a button or drop-down option for “clone” or “copy” to each event on the Event Definition page.  When selected, the UI should fetch the config for the Event Definition, append “ (COPY)” to the title, and store it as a new Event Definition.

**Comment by aim4r** [comment]
+1

**Comment by l0calhost** [comment]
+1, this would improve my workflow by a lot.
