### ISSUE TITLE
Dirty Flag is true for newly saved searches

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#8029]
## Expected Behavior
After saving a new search the user expects that the dirty flag indicator (the yellow star) is not yellow
but blue

## Current Behavior
After freshly creating the saved search the start is yellow. Saving a again cleans the dirty flag.

## Your Environment
* Graylog Version: 3.3 development

**Comment by dennisoelkers** [comment]
The same behavior can be observed by loading a saved search (which is probably the same code path).

**Comment by dennisoelkers** [comment]
Not reproducible anymore.
