### ISSUE TITLE
graylog login page is blank

### ISSUE THREAD

**Issue by xymsayly** [Graylog2/graylog2-server#8053]
I installed graylog using the rpm package,and service port listening is normal.
![image](https://user-images.githubusercontent.com/34665997/81186484-6d2a6880-8fe5-11ea-8245-50a6385540a3.png)
However, when I access port 9000 in the browser, the js script cannot be loaded
![image](https://user-images.githubusercontent.com/34665997/81186859-e5912980-8fe5-11ea-8a5c-4b607a66c5f5.png)
Can you help provide some troubleshooting methods or suggestions?Thank you very much.

**My Environment:**
Graylog Version:    graylog-server-3.2.4-1
Elasticsearch Version:   elasticsearch-6.8.6
MongoDB Version:  mongodb-org-server-4.0.18
Operating System: Amazon2 Linux
Browser version: microsoft edge(chromium)

**graylog server config:**
[root@ip-10-123-70-41 ~]# cat /etc/graylog/server/server.conf | grep -v "#" | egrep -v "^$"
is_master = true
node_id_file = /etc/graylog/server/node-id
password_secret =kd7ZnX14bfNQiKpi3OyFLEtMqKcgRKyQGvVr9O4bW22givHBsCk2Gq95j7m0aD1j8rd9NlO1234
root_password_sha2 = 67727a41b5b1d4dfca981e4045b1234
root_email = "test@test.com"
root_timezone = Asia/Shanghai
bin_dir = /usr/share/graylog-server/bin
data_dir = /var/lib/graylog-server
plugin_dir = /usr/share/graylog-server/plugin
http_bind_address = 0.0.0.0:9000
rotation_strategy = count
elasticsearch_max_docs_per_index = 20000000
elasticsearch_max_number_of_indices = 20
retention_strategy = delete
elasticsearch_shards = 4
elasticsearch_replicas = 0
elasticsearch_index_prefix = graylog
allow_leading_wildcard_searches = false
allow_highlighting = false
elasticsearch_analyzer = standard
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
message_journal_dir = /var/lib/graylog-server/journal
lb_recognition_period_seconds = 3
mongodb_uri = mongodb://localhost/graylog
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5
http_connect_timeout = 60s
http_read_timeout = 60s
http_write_timeout = 60s
proxied_requests_thread_pool_size = 32

**Comment by Fabiano2** [comment]
Hi, I think I have got this same problem,  Did you get it fixed? if yes could explain how? tks.
