### ISSUE TITLE
Large number of streams causing major performance issues with fields request

### ISSUE THREAD

**Issue by tkuronen** [Graylog2/graylog2-server#8063]
There seems to be already some issues reqarding the new fields list behavior in Graylog 3.2, like:
https://github.com/Graylog2/documentation/issues/818
https://github.com/Graylog2/graylog2-server/issues/7535
https://github.com/Graylog2/graylog2-server/issues/7675

However I wanted to bring up also a quite critical performance issue when user is having eg. hundreds of streams.

## Expected Behavior
Fetching a simple list of fields should not take minutes even if there is large number of streams that the user have access to.

## Current Behavior
In search view of the UI, browser is making a GET request to /api/views/fields in order to fetch all the fields to the new sidebar.

As an admin user having permission to all streams (we have 107) one request usually takes a minute or two, sometimes even more and returning simply list of 2643 fields in our case.
![image](https://user-images.githubusercontent.com/41315949/81382305-d78ef600-9116-11ea-9308-3bc97c2d10fc.png)

Browser can have multiple GET requests to fields endpoint pending simultaneously which seems to make UI unusable in browser because other requests are waiting fot that:
![image (1)](https://user-images.githubusercontent.com/41315949/81384737-c3e58e80-911a-11ea-88de-fbadd657ddac.png)

...and also eating lots of CPU resources in UI nodes (we have 2 nodes dedicated only for UI):
![image](https://user-images.githubusercontent.com/41315949/81384572-8a148800-911a-11ea-97dc-7a3b796acc58.png)

However as an end user having permissions to only one stream, fields request takes some seconds returning 181 fields and UI is still usable.

Actual list of fields seems to be in MongoDB's index_field_types collection where the list is fetched quickly. So is there maybe some very CPU intensive operations handling the fields list fetched from MongoDB ? Eg. some checks which of all the fields are included in streams that the user is having permissions to ?

Regarding to mongotop, most of time is spent on reading collection index_field_types but this can hardly be a bottleneck because results are returned quickly if asking directly from DB:
![image (2)](https://user-images.githubusercontent.com/41315949/81385569-37d46680-911c-11ea-8b5a-b78109cf90b7.png)

## Possible Solution
I noticed that some kind of fields list refactoring is planned to 3.3. Would that help with these UI performance issues ?

## Your Environment

* Graylog Version: 3.2.4
* Elasticsearch Version: 6.8.8
* MongoDB Version: 4.0.17
* Operating System: RHEL 7.7
* Browser version: Chrome 81.0.

**Comment by dennisoelkers** [comment]
Hey @tkuronen,

thanks for filing the issue and providing extensive information about it. Very much appreciated!

As you have noticed, we have already been working on this issue. It is fixed in #7865, which is being part of `3.3.0`. It is currently in beta and supposed to be released in the next weeks.

I hope this helps. If you still encounter this issue after updating to `3.3.x`, please reopen the issue.

**Comment by dennisoelkers** [comment]
Fixed in #7865.

**Comment by nikolay-px** [comment]
I got an awful performance issues of this API request on search page, so it's probably unrelated to this issue.
Should I create a new issue?

Details described here https://community.graylog.org/t/rebuild-fields-index-slow-api-views-fields-requests/17665

**Comment by ihor-sviziev** [comment]
Hi,
We also have the same issue. We had many fields on Graylog 3.0, but after migrating to 3.3.9, the search became really slow.

We removed all the messages containing many unnecessary fields, but it didn't help as the fields are still returning.

Is there any way to remove not needed fields from the fields listed while no messages are referencing them anymore?
