### ISSUE TITLE
Search in the latest graylog versions does not work

### ISSUE THREAD

**Issue by ivaylopivanov** [Graylog2/graylog2-server#8079]
After migrating from graylog 2.4.6+ceaa7e4 to 3.0 (tried on 3.2 as well) the search does not work. Assuming I'm sending the following message

```
{
  "source": "whatever",
  "params": {
    "nested": "value"
  }
}
```

If I search for the word "value" I will get the message in the result for graylog 2.4.6 and prior but I will not get any results for graylog 3.0
## Expected Behavior
To return the message when searching for the word

## Current Behavior
Not working as the versions before

## Steps to Reproduce (for bugs)

1. Install latest graylog
2. Send the message
3. Search for the word "value"

* Graylog Version: 3.2
* Elasticsearch Version: 6
* MongoDB Version: 3.6.12
* Operating System: maxos and ubuntu

**Comment by jalogisch** [comment]
he @ivaylopivanov 

would you please share what kind of input you have used to ingest the message and if you have any kind of extractors running on this input. 

From the given information this can't be seen. 

Thank you

**Comment by jalogisch** [comment]
https://community.graylog.org/t/params-not-being-indexed/15342/2

**Comment by ivaylopivanov** [comment]
I will close this for now because I do not have the time to provide you with the details.
