### ISSUE TITLE
The title of an ad hoc search "Untitled search" displayed in the sidebar, can be misleading

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#8085]
We currently display the title of saved searches and dashboards in the sidebar. On the default search page, the title is "Untitled Search". This can be misleading, because it gives the impression the title can be changed.

We can improve this by:
* Adjusting the title on the default search page and stream search page (E.g. Ad-hoc Search)
* Displaying an option to edit the (saved search / dashboard) title, in the sidebar.

Graylog Version: 3.3.beta2

**Comment by nosilver4u** [comment]
That would be much appreciated. Earlier I found myself trying to click the title (several times, just to make sure I wasn't doing something wrong), only to find it just closed the sidebar. Eventually figured out that I needed to save a search and then it would show the name of my saved search over there.

**Comment by linuspahl** [comment]
This has been fixed a while ago with https://github.com/Graylog2/graylog2-server/pull/8294

We ended up with the default title "Unsaved search".
