### ISSUE TITLE
Nested JSON objects not documented in API Browser

### ISSUE THREAD

**Issue by alex-konn** [Graylog2/graylog2-server#8087]
## Expected Behavior
Nested Json objects should recursively be documented.

## Current Behavior
The best we can get is all top-level fields. Random example:
![Screenshot from 2020-05-11 17-37-20](https://user-images.githubusercontent.com/45592524/81580753-230f0180-93ae-11ea-8484-28d86b27f98d.png)
Note that the `timerange` is present, but what fields might it have?

* Graylog Version: 3.3.0-beta.3-SNAPSHOT

**Comment by alex-konn** [comment]
Looking at the implementation I see two problems:
1. The generated JSON schema actually contains data about nested objects, but the UI doesn't display it.
2. `JsonSubTypes` information is lost. E.g., we have multiple implementations of `org.graylog2.plugin.indexer.searches.timeranges.TimeRange` with different fields, but the schema only contains the `type` field from the interface.

Example:
`curl -u admin:admin -H "X-Requested-By: peterchen" -v localhost:9000/api/api-docs/views/search/messages | jq '.models.MessagesRequest'`

**Comment by dennisoelkers** [comment]
This is fixed in #10637.
