### ISSUE TITLE
streams - quick add rule - matcher github url is broken

### ISSUE THREAD

**Issue by lingpri** [Graylog2/graylog2-server#8107]
stream matchers web link url is broken, while performing  a `quick add rule` action in streams.

URL : 
https://github.com/Graylog2/graylog2-server/tree/3.3/graylog2-server/src/main/java/org/graylog2/streams/matchers

## Expected Behavior
please fix the broken link.

## Current Behavior
url link is broken.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
I was trying to understand, how the matcher type works, so that i can create varied matcher type stream rules.

## Your Environment

* Graylog Version: 3.3.0-beta.3-SNAPSHOT 
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
The URL does not work yet, because we do not have branched off a `3.3` branch. It will work after the final release.
