### ISSUE TITLE
streams - _Set as startpage_ is not working for admin users

### ISSUE THREAD

**Issue by lingpri** [Graylog2/graylog2-server#8108]
the action button ` _Set as startpage_` is not working for admin users. its available for `reader` users.I'm wondering , how to use this feature effectively and what are the use cases 
for this action.

## Expected Behavior
_Set as startpage_ must be enabled for admin users.

## Current Behavior
_Set as startpage_  disabled for admin users.
![set_as_start_page](https://user-images.githubusercontent.com/6947168/81725770-f6112c00-944b-11ea-9eba-a47e5ac3d1da.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
3.3 release testing

## Your Environment

* Graylog Version: 3.3.0-beta.3-SNAPSHOT
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Hey @lingpri,

this function is disabled for the `admin` user, which does not have an entry in the mongo db. For other users bearing the `Admin` _role_, it should be usable. Can you validate this and close the issue if it holds true?

**Comment by lingpri** [comment]
hi @dennisoelkers - yes it works for `non-admin` user. I created a role `syslog specialist` with permissions to read and write to a stream named `syslog` and added a user to this role `syslog specilaist` and logged in with this user and am able to see the action `set as start page' . when I log in with url `localhost:8080`, am able to see the `syslog` stream is defaulted.
