### ISSUE TITLE
Allow defining total amount of column pivots for an aggregation

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#8111]
The configuration option "Number of values" of a column pivot currently relates to each row pivot. Imagine the following scenario:

* The field timestamp is configured as a row
* The field source is configured as a column with the option "Number of values" with an amount of 2
* The two sources with the highest amount of messages for timestamp X are A and B
* The two sources with the highest amount of messages for timestamp Y are B and C

In this case e.g. a line chart will display three categories (A, B and C). It would be helpful to be able to configure to total amount of categories / column pivots, which is based on the amount of all results for a category / column pivot.

* Graylog Version: 3.2

**Comment by chalfling** [comment]
This is really annoying. I was able to create a Data Table with several "Group By Rows" and limiting results from each row like "limit by 1 result", but now I can't.

Example:
event(limit 10) | srcip(limit 1) | total
Logon  | 192.168.0.1 | 500
Logoff | 192.168.1.1 | 200
XML Attack | 192.168.2.1 | 100
XSS Attack | 192.168.3.1 | 50
SQL Injection | 192.168.4.1 | 10

Then a was able to see top 10 events with The top1 Source.

Now is something like:
event | srcip | total (row limit 10)
Logon  | 192.168.0.1 | 500
Logon  | 192.168.0.2 | 450
Logon  | 192.168.0.3 | 400
Logon  | 192.168.0.4 | 350
Logon  | 192.168.0.5 | 300
Logon  | 192.168.0.6 | 250
Logon  | 192.168.0.7 | 200
Logon  | 192.168.0.8 | 150
Logon  | 192.168.0.9 | 100
Logon  | 192.168.0.10 | 50

For me this is a Breaking Change =(
