### ISSUE TITLE
Web interface loads very slow

### ISSUE THREAD

**Issue by ifurs** [Graylog2/graylog2-server#8123]
After updating Graylog from 3.1 version to 3.2, the web-interface began to load longer than before, now the login page loads in ~2 minutes.
I also noticed that the `app.js` file started to take up ~6MB when in the previous version it took up ~1.9MB

## My Environment
* Graylog Version: 3.2.4
* Elasticsearch Version: 6.8.7
* MongoDB Version: 4.0.17
* Operating System: Debian 9

**Comment by dennisoelkers** [comment]
Thanks, @ifurs, for reporting this to us.

We have noticed this regression as well and fixed it in https://github.com/Graylog2/graylog2-server/pull/7598. It will be part of `3.3.0` coming very soon.

Is it also slow for you after the initial load? Your browser should have cached the assets after fetching them once.

**Comment by ifurs** [comment]
It slow only for the initial load. Yes browser cached the assets after initial load

**Comment by JSylvia007** [comment]
I think I may be having the same issue, but mine is not slow, it completely times-out.  I'm not sure when it happened, but it was all working just fine.

**Comment by kroepke** [comment]
This should be fixed in the linked pull request, please open another issue if this problem persists with 3.3.0 (which should be released in a few days).

Thanks!
