### ISSUE TITLE
Elasticsearch integration tests should test multiple versions

### ISSUE THREAD

**Issue by alex-konn** [Graylog2/graylog2-server#8146]
## Expected Behavior
We should have integration tests that verify the system works with all supported Elasticsearch versions
By default all integration tests should test all supported major versions.
In addition it should be possible to define one or more version in the implementing  test class, which will be used instead of the default versions.

## Current Behavior
Only one version can be tested

## Context
It's probably worthwhile to do #7655 before, maybe only for Elasticsearch. The MongoDb stuff can be done later.

**Comment by dennisoelkers** [comment]
Fixed in #11011.
