### ISSUE TITLE
Since 3.2 permissions set for dashboards are not enough

### ISSUE THREAD

**Issue by Nklya** [Graylog2/graylog2-server#8161]
Hello.

I've found a problem after migrating Graylog to 3.2.4+a407287 permissions are broken and it's not described in the documentation.

## Expected Behavior
If you adding to role access "Allow reading", it should be enough to open this dashboard for a view as a user with this role assigned.

## Current Behavior
If a user cannot read streams used in the dashboard, they cannot see it, even if they have "Allow reading" permissions for the dashboard. Instead, they get "party gorilla" page.
![Screen Shot 2020-05-19 at 17 56 56](https://user-images.githubusercontent.com/26086394/82347093-e1aad180-99ff-11ea-803e-d7fedddf4215.png)

## Possible Solution
I think it can be fixed in the permissions system or at least current behavior should be added to the documentation.

## Steps to Reproduce (for bugs)
1. Create a dashboard with a couple of graphs
2. Add a user with permissions "Allow reading" to a dashboard, but without permissions to read streams
3. Try to open the dashboard
4. Get an error

## Context
Now you cannot allow a user to view a dashboard without allowing him to read messages in the streams, that are used in the dashboard.

## Your Environment
* Graylog Version: 3.2.4+a407287
* Elasticsearch Version: 6.8.7
* MongoDB Version: 4.0.17
* Operating System: Ubuntu 18.04.3 LTS
* Browser version: Safari 13.1 (I suppose other browsers will be the same )

**Comment by florianpopp** [comment]
The error message is fixed in 3.3. Please update to the latest version.

Thank you.

**Comment by leepfrog-ger** [comment]
I dont see how this is fixed. Yes, the error message has be specified, but the use case is still not possible (any more) and to my knowledge this has *not* been added to the documentation in the mean time. 

This is a breaking change to the previous versions (see details here: https://github.com/Graylog2/graylog2-server/issues/7570#issuecomment-640763271) and should be treated and documented as such in the release notes, upgrade instructions and the general dashboard documentation.
