### ISSUE TITLE
Throughput on UI not aggregated in 3.3.0

### ISSUE THREAD

**Issue by zemek** [Graylog2/graylog2-server#8172]
The message throughput in the top right corner of the UI (in/out) seems to only show throughput for a single node, rather than the aggregate of the cluster after upgrading to 3.3.0. Looking at the `/system/nodes` endpoint, I can see that each node is processing messages correctly.

## Expected Behavior
Throughput should show the sum of all nodes

## Current Behavior
Throughput appears to only show the throughput of a single node, or the average of each node?

**Comment by chalfling** [comment]
Same here.
