### ISSUE TITLE
Dashboard Widgets not showing right values

### ISSUE THREAD

**Issue by bud1979** [Graylog2/graylog2-server#8173]
It seems the dashboards have a built in value for the streams, as as seen in the video, if you add a stream, and remove it, you get different values.

## Expected Behavior
Need to have the value shown at first load of the dashboard, and if modified it comes back to the same value, not a new value

## Current Behavior
Starts off as Zero, but after adding and removing "all messages" it comes off at 8

## Steps to Reproduce (for bugs)

Follow GIF
![IssueSearch](https://user-images.githubusercontent.com/26657656/82481328-5b8b9b00-9a92-11ea-8b48-ec8cd00f3857.gif)

## Context
In creating Security content, we ran into this issue, where our Dashboards are not showing up as expected on first launch

## Your Environment

* Graylog Version: 3.3.0 rc1
* Elasticsearch Version: 6.8
* MongoDB Version: 4.0

**Comment by dennisoelkers** [comment]
During a short debugging session we were not able to reproduce the issue.

@bud1979, please reopen this issue if you see this happening again, thank you! :)
