### ISSUE TITLE
API Browser page unable to login on 3.3.0

### ISSUE THREAD

**Issue by joshdeaver** [Graylog2/graylog2-server#8178]
After upgrading from 3.2.4 to 3.3/0, the http://localhost:9000/api/api-browser page no longer accepts a user id and password.  No error message, no way to submit credentials, enter does not work and no login button.

## Expected Behavior
Page should login and show swagger API browser

## Current Behavior
No error message, no way to submit credentials

## Steps to Reproduce (for bugs)

1. http://localhost:9000/api/api-browser
2. Enter credentials
3. Attempt to submit with enter key
4.

## Your Environment

* Graylog Version: 3.3.0
* Elasticsearch Version: 
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by kmerz** [comment]
Hey @joshdeaver,
I assume your API Browser looks like this right now:
![Graylog REST API browser](https://user-images.githubusercontent.com/448763/82668004-31c0a880-9c39-11ea-9764-f456ad1d03c9.png)

This is not a login page you see, but rather an uncompleted page render. If you open your webdev console, you should see errors.

To fix that problem you have to use the same value of `http_bind_address` to access the API browser. Default would be `127.0.0.`.

So try to access your page with: http://127.0.0.1:9000/api/api-browser
and tell me if that fixes your problem.

**Comment by joshdeaver** [comment]
That is exactly correct and using the http_bind address works fine.
Assuming there is another value I can add in one of the configs to add support for FQDN?

Thanks for the response as well.

Josh

    On Friday, May 22, 2020, 07:36:44 AM CDT, Konrad Merz <notifications@github.com> wrote:  
 
 


Hey @joshdeaver,
I assume your API Browser looks like this right now:


This is not a login page you see, but rather an uncompleted page render. If you open your webdev console, you should see errors.

To fix that problem you have to use the same value of http_bind_address to access the API browser. Default would be 127.0.0..

So try to access your page with: http://127.0.0.1:9000/api/api-browser
and tell me if that fixes your problem.

**Comment by boosty** [comment]
> Assuming there is another value I can add in one of the configs to add support for FQDN?

Please have a look at `http_publish_uri`:
- https://docs.graylog.org/docs/rest-api
- https://docs.graylog.org/docs/web-interface

Also consider using the global API browser: 
https://github.com/Graylog2/graylog2-server/issues/12831#issuecomment-1149964942

I am closing this, as the original question has been answered.
