### ISSUE TITLE
Graylog preload extractors in docker ?

### ISSUE THREAD

**Issue by Krishjs** [Graylog2/graylog2-server#8181]
Context
Expected Content
Your Environment
Graylog Version: 3.2
Elasticsearch Version:6.8.5
MongoDB Version:3
Operating System:Centos
Browser version:Chrome 81.04
Team,
Is there a way we can save the extractor and input configuration within the docker image of the graylog (I know it is saved in mongo db but is there a config that can load the extractors on start ?
Basically I want certain configuration on multiple instance but I don't want to configure the extractors in each instance manually ?

**Comment by radykal-com** [comment]
Have you tried through the API?

**Comment by Krishjs** [comment]
I could try with the API for that I kind need to create a script to run after the graylog is up ? What I am asking is there way the graylog boot with configuration ?

**Comment by jalogisch** [comment]
as written in the other issue you have opened:

https://github.com/Graylog2/documentation/issues/877

Content Pack preloading

https://docs.graylog.org/en/3.3/pages/configuration/server.conf.html

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
