### ISSUE TITLE
Search autocomplete broken

### ISSUE THREAD

**Issue by ntimo** [Graylog2/graylog2-server#8183]
When typing a s into the search filed it autocompletes it to something completely broken.

## Expected Behavior
Normal typing in search field is possible

## Current Behavior
When typing a single char like a s graylog tries to autocomplete the result. This makes it impossible to search for stuff. Without pasting the search query from a third party tool.

## Steps to Reproduce (for bugs)
1. Open some stream
2. Try to type the word "source"
## Your Environment

* Graylog Version: Graylog 3.3.0+4ea5649 on (Oracle Corporation 1.8.0_252 on Linux 4.15.0-99-generic)
* Elasticsearch Version: 6.8.9
* MongoDB Version:
* Operating System: Docker Ubuntu 18.04
* Browser version: Firefox (76.0.1 (64-bit)) and Safari (Version 13.1 (15609.1.20.111.8))

Gif of the bug:
![ezgif-3-565a602da08c](https://user-images.githubusercontent.com/6145026/82646303-a9301100-9c14-11ea-8e7b-a061a1f414cd.gif)

**Comment by kmerz** [comment]
Hello @ntimo 

I am not able to reproduce this problem. Could you have a look into your `web developer console` of your firefox (`F12`) when typing in the search query and report if you can see there anything?

**Comment by ntimo** [comment]
Hey @kmerz,
yes sure. I get a lot of these errors when I start typing:
![Screenshot 2020-05-22 at 10 45 01](https://user-images.githubusercontent.com/6145026/82649380-63297c00-9c19-11ea-9a04-ce02e6c2d15f.png)

**Comment by kmerz** [comment]
@ntimo do you have any plugins installed and are they also on the same version as your master?
And could clear you cache for this site, perhaps old assets are referenced here?

**Comment by ntimo** [comment]
@kmerz Yes I have the following plugins installed:

- Graylog Enterprise 3.3.0
- https://github.com/irgendwr/TelegramAlert/ version 2.3.0
- https://github.com/graylog-labs/graylog-plugin-metrics-reporter 3.0.0

I also cleared the browser cache and it did not affect the bug at all

**Comment by kmerz** [comment]
@ntimo could you give it a try without the `TelegramAlert` plugin? This is also shipping assets and might interfere with the assets from core. It might be you need to wait for another build of that plugin to be in sync with core. After removing the plugin you need to clear the cache again.

**Comment by ntimo** [comment]
Sure, let me reconfigure my Graylog. Will report back to you in a second.

**Comment by ntimo** [comment]
Indeeded removing the telegram alert plugin fixed the issue :( I will contact the maintainer. Thanks for your time. Sorry I couldn't figure that out myself.

**Comment by kmerz** [comment]
No problem, glad we found the problem. It is a bummer that our frontend plugin system works that way.

**Comment by irgendwr** [comment]
@kmerz is there anything I can do different to prevent this in the future?
Since switching the plugin to the new system this has also increased my plugins size since it contains a lot of Graylog assets.
In development it was also common that whenever I included some components it would also include a huge part of the Graylog frontend, even background pictures! (which where not required nor used in the components)

**Comment by kmerz** [comment]
@irgendwr There is nothing which can be done right now. We want to work in the future on that problem, but it is not planed anytime soon.
