### ISSUE TITLE
Seach query - works when stream is not selected

### ISSUE THREAD

**Issue by xel-AB** [Graylog2/graylog2-server#8193]
When you do a custom query seaerch like
winlogbeat_event_id:*
against a custom created stream no data is returned.

Query returns some data from "All messages" (or when no stream is selected).
When the same query is run against a custom stream - no results are returned.
When you select custom stream and no search query - msg's are returned
We have a stream that has Windows event's with id's and when we try to query stream for those id's - nothing is returned.

## Expected Behavior

Query run against a custom stream should return relevant data.

## Current Behavior

When doing query against a custom stream no data / events are returned

## Steps to Reproduce (for bugs)

1. Create custom stream - for winlogbeat input (stream with 2 rules match source and match winlogbeat_event_id)
2. Search custom stream for any event id - winlogbeat_event_id:*

## Context

We try to monitor Windows (un)succesful login activity

## Your Environment

* Graylog Version: 3.3.0-5
* Elasticsearch Version: 6.8.9-1
* MongoDB Version: 4.0.18-1.el7
* Operating System: RHEL 7.8
* Browser version: Firefox 68.8.0esr

**Comment by xel-AB** [comment]
![event1](https://user-images.githubusercontent.com/65892667/82796909-9157c780-9e76-11ea-806b-e63e9baef1bc.png)
![event2](https://user-images.githubusercontent.com/65892667/82796928-9b79c600-9e76-11ea-8767-5aedf63f271e.PNG)

**Comment by xel-AB** [comment]
Creating a new index and directing stream to it did improve the situation.
We can query the stream, however have only results from index-creation timestamp.

**Comment by kmerz** [comment]
Hi @xel-AB,

the index ranges are broken of your stream. You can fix that by recalculating your index ranges:
![recalculate-index-range](https://user-images.githubusercontent.com/448763/82801413-92402780-9e7d-11ea-99e0-7a1c22534ced.gif)

**Comment by xel-AB** [comment]
Could be a cese, initiated range rebuild

![obraz](https://user-images.githubusercontent.com/65892667/82802221-d1bb4380-9e7e-11ea-8a95-0cd3f30df513.png)
