### ISSUE TITLE
Consolidate settings in configuration file

### ISSUE THREAD

**Issue by joschi** [Graylog2/graylog2-server#820]
The configuration file for Graylog2 has grown quite a bit over time and contains some inconsistencies which should be fixed.

Such inconsistencies include the naming of configuration settings and the units of configuration values, e. g. some time-related values (most timeout settings) are implicitly given in milliseconds, some are given in seconds (`alert_check_interval`), and some have a unit suffix (`elasticsearch_max_time_per_index`).

In order to enable users to quickly check and migrate their configuration, we should provide a migration tool which automatically converts a configuration file from the old format to the new one.

**Comment by bernd** [comment]
We didn't do this for more than a year. I am closing this now, please re-open if you think this will happen in the near future. :wink:
