### ISSUE TITLE
Views User Role fails to load existing view

### ISSUE THREAD

**Issue by andolirien** [Graylog2/graylog2-server#8209]
## Expected Behavior
A user with Role "Views User" navigates to the Views -> Load Existing page. They then click on an existing view from the list, and are shown the view.

## Current Behavior
The user with Role "Views User" navigates to the Views -> Load Existing page, sees the list, but when clicking the view from the list, is redirected to the "Not Found" page with the chimp/banana thing.

## Possible Solution
Not sure if this is an issue with roles, permissions, or if I've got it misconfigured.

## Steps to Reproduce (for bugs)
1. Fresh install, use LDAP authentication
2. Have new users get "Views User" role automatically
3. Create simple view of "source:hostname", for the user to view
4. When the user with "Views User" role selects the admin-created view from the existing views list, get redirected to not found page.

## Context
Basically, I'm trying to create or use a role that will allow read-only access into our logs. I want no write access or ability to edit views, dashboards, etc., but for the user to be able to see views, searches, whatever that have been created by admins for the read only user to see. The "Views" functionality seems to be what I want, but I can't figure out why the "views user" can't load an existing view.

## Your Environment
Graylog is installed in a Rancher controlled Kubernetes environment. Authentication is handled by LDAP, with automatically assigned roles upon login (User admin page in Graylog confirms that the Roles are being assigned correctly).
* Graylog Version: 3.1.4
* Elasticsearch Version: 7.6.2
* MongoDB Version: 3.15.0
* Operating System: ...K8s?
* Browser version: Chrome 83.0.4103.61

**Comment by dennisoelkers** [comment]
Is the user with the `Views User` permitted to see the streams of that view? If the view does not reference any streams (which translates to retrieving messages from all streams the user has access to), does the user have access to _any_ stream at all?

**Comment by dennisoelkers** [comment]
I noticed you are using a rather old version (`3.1.4`, while `3.3.0` has come out, which improves search/views a lot). Is there any reason that keeps you from updating?
