### ISSUE TITLE
 ERROR [MasterCacheWorkerThread] Error while trying to work on MasterCache

### ISSUE THREAD

**Issue by CaesarC** [Graylog2/graylog2-server#821]
![1111](https://cloud.githubusercontent.com/assets/7133914/5486822/e35f5b6e-86e5-11e4-9f50-d1523b45c6e7.png)
![222](https://cloud.githubusercontent.com/assets/7133914/5486823/e6ec0eee-86e5-11e4-8ac1-508d6c257c1e.png)
^.^i don't know what happened.Some one go to help me ~

**Comment by kroepke** [comment]
The entire code path is removed from 1.0 and handled differently. As there will be no more major updates to 0.92.x I will close this now.
Please give Graylog 1.0 beta a try: https://www.graylog2.org/news/post/0014-graylog-v1-0-0-beta1
