### ISSUE TITLE
In multiple nodes, the load balancing of overstocked data cannot be achieved

### ISSUE THREAD

**Issue by xlogin** [Graylog2/graylog2-server#8234]
I have multiple graylog nodes, and the problem I find is that when the data is overstocked, each machine has an uneven backlog of data, which results in some machines being busy and some machines being idle.
So I plan to add kafka nodes to the front of the graylog cluster, even though graylog itself has its own kafka capabilities.But this should get each node busy.

## Your Environment

* Graylog Version: 3.2.5
* Elasticsearch Version: 6.8.8
* MongoDB Version: 3.2
* Operating System: Centos 7 x64
* Browser version: Google Chrome 81.0

**Comment by radykal-com** [comment]
Hi, How do you distribute the load across Graylog nodes? With a load balancer in front of them?

**Comment by xlogin** [comment]
> Hi, How do you distribute the load across Graylog nodes? With a load balancer in front of them?

Yes, I used a load balancer in front of multiple nodes。Do you have any good Suggestions on this?

Thanks！

**Comment by radykal-com** [comment]
Mmmmh it is very strange. I also do round robin in the load balancer and the nodes load distribution is pretty balanced. Maybe the bottleneck is in some kind of messages with a complex processing that may lead to one node getting more of those messages than the others?
