### ISSUE TITLE
checkDiskUsage also checks non-data nodes

### ISSUE THREAD

**Issue by dploeger** [Graylog2/graylog2-server#8239]
## Expected Behavior
No alerts for disk watermarks are reported for Elasticsearch-nodes, that hold no data.

## Current Behavior

ES-nodes that are non-data nodes are currently considered when checking for low disk watermarks in https://github.com/Graylog2/graylog2-server/blob/4ad05ae37ba7afd317bf4b866725c662aa41e87b/graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java#L107

This leads to irritating alerts in the Graylog UI:

![image](https://user-images.githubusercontent.com/203453/83254278-d3eb0e00-a1ae-11ea-999c-02d92079bf43.png)

## Possible Solution

Either filter out ES nodes, that don't have the data role in https://github.com/Graylog2/graylog2-server/blob/4ad05ae37ba7afd317bf4b866725c662aa41e87b/graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java#L149

or filter them out in checkDiskUsage around here

https://github.com/Graylog2/graylog2-server/blob/4ad05ae37ba7afd317bf4b866725c662aa41e87b/graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java#L115

## Steps to Reproduce (for bugs)

1. Add a node to the ES cluster, that has the data role deactivated ({{node.data: false}} in elasticsearch.yml)
2. Increase the disk usage percent to over the cluster's low watermark level

=> An alert for that node is shown in the Graylog UI

## Context

We're using non-data nodes as master nodes to achieve a three-node-setup. Non-data nodes don't use disk watermark thresholds as no data is scheduled on them in any case.

Our master nodes are not very big in size, so the disk watermark alert is shown for them and this is irritates the user as it may point to an Elasticsearch cluster failure.

## Your Environment

* Graylog Version: 3.3.0
* Elasticsearch Version: 6.8.9
* MongoDB Version: 4.0.12
* Operating System: Ubuntu 16.04
* Browser version: 83.0.4103.61

**Comment by dennisoelkers** [comment]
Thanks for reporting this, @dploeger! We will look into it and fix it for one of the next versions.

**Comment by radykal-com** [comment]
I just opened a PR to fix this one as it was my mistake
