### ISSUE TITLE
The "Nodes with too long GC pauses" notification needs a link to a help doc

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#824]
The "Nodes with too long GC pause" notification needs a link to a documentation page giving some context about why this could have happened and what to look at to fix it.

I can do that!

**Comment by SjonHortensius** [comment]
While you're at it; could you also link the node-id in that message to /system/nodes/$ID? It would make it easier to determine which node it is (if you could resolve the name too that would be even better)

**Comment by sidcarter** [comment]
Has this change been made? Would be good to know how to fix these notifications.

**Comment by kroepke** [comment]
it's not documented yet, but you can use the changes made in https://github.com/Graylog2/graylog2-server/commit/105acc69a3df11e138dd8a3dab9bf7231ec27645#diff-6a799d0cfe63415fa5504473f27b933aR54

those apply to pre-1.0 versions as well.
you might still see that warning, but overall performance should improve.

**Comment by kroepke** [comment]
the new defaults will mostly collect garbage concurrently to the application with much smaller pauses.
if those collectors are in use we no longer run the GC pauses checks, compare #899

**Comment by kroepke** [comment]
1.0 change the GC defaults and indexing uses less memory, too, so we'll close this.
