### ISSUE TITLE
Enterprise Linux 8 support

### ISSUE THREAD

**Issue by TiNico22** [Graylog2/graylog2-server#8241]
## What?
No support of el8 distro with 3.3

Rpm for el8 available (rhzl and centos)

## Why?

Thinking about switching to rhel8 distro for new fresh server install

## Your Environment

* Graylog Version: 3.x
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by mikkolehtisalo** [comment]
Rhel 7 is afaik in maintenance support 2 already. That means it is not being developed anymore, and will for the next 3 years receive only critical bug fixes. After that the support will end. No one should make fresh Rhel 7 installs anymore, Rhel 8 should have been the default for a while already.

**Comment by jalogisch** [comment]
I just want to mention - we did not adjust the Step-by-Step copy&paste installation guide (yet) 

https://docs.graylog.org/en/3.3/pages/installation/os/centos.html

That is the missing item.
