### ISSUE TITLE
Sometimes Dashboard stops showing data after changing time selection

### ISSUE THREAD

**Issue by xavier-isecurity** [Graylog2/graylog2-server#8242]
## Expected Behavior

If I change time from ```No Override``` to ```Relative```, it should bring the data for the selected time every time if there is data. And when changing back to ```No Override``` it should bring data as it is configured in the aggregations every time.

## Current Behavior

Sometimes when I change the selection of time to ```Relative```, the dashboard stops showing data and it kind keep broken. When I go back to ```No Override``` it stops showing data, and even if I clear the cache, open it again in the next day it does not show the data anymore. The queries was working before and if I use them in the ```Search``` it brings data.

This is what is print in the console right when I open it:

![image](https://user-images.githubusercontent.com/66122973/83261750-3e418580-a192-11ea-9254-4d3893c0eacf.png)

## Steps to Reproduce (for bugs)

1. Open a dashboard with tabs.
2. Change time from ```No Override``` to ```Relative```.
3. Select ```Search in the last 7 days```.
4. Click on ```Filter``` button.
5. Change back to ```No Override```.
6. Click on ```Filter``` button.

It doesn't happen everytime, but already happened 4 times with me, I don't what is the exactly requirements to replicate this bug.

## Context

The issue gives a lot of instability, because we spent a lot of time building one dashboard and it just stop working. And it can be in front of a client.

## Your Environment

* Graylog Version: Graylog 3.3.0+4ea5649
* Elasticsearch Version: "6.8.9"
* MongoDB Version: v3.6.3
* Operating System: Ubuntu 18.04 LTS (GNU/Linux 4.15.0-20-generic x86_64)
* Browser version: Google Chrome Versão 83.0.4103.61 (Versão oficial) 64 bits

**Comment by dennisoelkers** [comment]
Hey @xavier-isecurity,

thanks for reporting this. Do you have any plugins installed?

**Comment by xavier-isecurity** [comment]
> Hey @xavier-isecurity,
> 
> thanks for reporting this. Do you have any plugins installed?

I have those:

![image](https://user-images.githubusercontent.com/66122973/83268838-94b3c180-a19c-11ea-986a-9647b05c387b.png)

**Comment by dennisoelkers** [comment]
Your integrations plugin is out of date. How did you update to 3.3?

**Comment by xavier-isecurity** [comment]
- Rotate all index
- Stop all nodes, but one.
- Upgrade all nodes.
- Restart Live node.
- Restart the others.

I check the plugins in all nodes, we have three, and in the slave nodes there was not the integration plugin, I am installing it and restarting the server to see what will happen. I will bring updates soon.

**Comment by xavier-isecurity** [comment]
Hi @dennisoelkers 

It happen again, but without changing the query time, I was just adding editing aggregations. 

The reset with the recent version of the plugin was made after this today, the log error message in the console disappear, but the dash is still broken.

I will send an update if it happen again.

**Comment by xavier-isecurity** [comment]
It was fixed after editing one widget again. Changing the query time of an agreggation.

**Comment by xavier-isecurity** [comment]
Hi @dennisoelkers,

It is still happening, usually is when a query doesn't complete for what I am seeing, and it comes back to normal after you edit query or time range in the dashboard and it does a different query. Maybe the cache from JVM is saving the failed query.

Thanks,
Vinícius Xavier.

**Comment by dennisoelkers** [comment]
Hey @xavier-isecurity,

that's not good to hear. Can you reproduce the issues or does it happen randomly? Steps to reproduce it would help us a lot.

**Comment by xavier-isecurity** [comment]
Randomly, we have a lot of data, like 2 thousands messages per second. Sometimes it can get over 10 thousands per second. 

It is more frequently when I don't wait the dashboard update after an edition for edit it again.

**Comment by dennisoelkers** [comment]
Hey @xavier-isecurity,

do you still see this issue happening?

**Comment by dennisoelkers** [comment]
Closing due to being outdated. Please reopen if this is still an issue for you!
