### ISSUE TITLE
syslog udp input date in source

### ISSUE THREAD

**Issue by dio99** [Graylog2/graylog2-server#825]
Hi got the date as source when sending directly to syslog udp input ?? if i send to a rsyslog and forward in rsyslg to graylogs syslog udp input then i get right fileds.
This is on evry type of device... Cisco Asa, Fortigates, Fortimanger. Linux servers, Mcafee....

any hints of what to do setup for this ?
now i forward all logs from 2 rsyslog servers but i want to send directly to graylog2 server.
// Anders

**Comment by kroepke** [comment]
If there's more information whether this is a bug or not please reopen the issue.
