### ISSUE TITLE
Graylog crash on specific widget size and type in Dashboards

### ISSUE THREAD

**Issue by facyber** [Graylog2/graylog2-server#8259]
I noticed that my Graylog crashes when I resize a widget with counting something, to a specific size. I notice that the number is sort of lagging up-down before it froze and then I am asked by Firefox to stop the page. Bellow on a picture, I marked with red rectangle the widget size that crashes the Graylog. I tried with some other types of graphs like pie charts for example and resize it to the same size and no issue. Only when Single number visualization type is used.

## Expected Behavior
Widget should resize and number shouldn't shaking (not sure how to describe better).

## Current Behavior
When you resize the widget with counting number to a specific size, Graylog page crash (Firefox ask you to keep waiting or to stop the script).

## Steps to Reproduce (for bugs)
1. Create Total count widget based on any field (for example total number of IPs)
2. Add it to the Dashboard
3. Resize the widget so specific size (450x210px should be, widget size, at least that's what Firefox shows)
4. Watch the button start shaking.

## Your Environment
* Graylog Version: 3.3
* Elasticsearch Version: 6.8.9
* MongoDB Version: 4.0.18
* Operating System: Ubuntu 18.04
* Browser version: Firefox 76.0

![graylog_issue](https://user-images.githubusercontent.com/8742227/83526087-35301b80-a4e6-11ea-9922-ce4b667ff7f2.png)

**Comment by dennisoelkers** [comment]
Hey @facyber,

thanks for reporting this! We are already tracking this and will fix it in one of the next releases. Therefore I am closing this issue. If you feel the referenced issue is not identical to your problem, please reopen this issue with additional information.

Fixed in #7563.
