### ISSUE TITLE
Charts showing different range time them selected

### ISSUE THREAD

**Issue by xavier-isecurity** [Graylog2/graylog2-server#8263]
## Expected Behavior

When selecting absolute time range the start and end of the chart be exactly what is selected

## Current Behavior

The time showing in the chart is quite different them selected.
![image](https://user-images.githubusercontent.com/66122973/83555982-88559e80-a4e5-11ea-9b81-b8bfa23ea850.png)

## Possible Solution

Probably some time normalization.

## Steps to Reproduce (for bugs)

1. Change the time for absolute
2. Select Any time range

## Context

It is not consistent showing different data them selected on time range.

## Your Environment

* Graylog Version: Graylog 3.3.0+4ea5649 
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:  83.0.4103.61 64bits

**Comment by kmerz** [comment]
@xavier-isecurity I don't seem to be able to reproduce this problem in a current version, could you please verify if that problem still exists?
