### ISSUE TITLE
Content Package Dashboards has tabs order mixed after install

### ISSUE THREAD

**Issue by xavier-isecurity** [Graylog2/graylog2-server#8264]
## Expected Behavior

When installing Content Package with dashboards that have tabs, the tabs should keep the original order.

## Current Behavior

The tabs got order mixed after installing the contenta package dashboards.

## Possible Solution

Review how the dashboards are saving tabs and how to keep the order.

## Steps to Reproduce (for bugs)

1. Create a content package with dashboards that has at least four tabs.
2. Install the content package
3. Check the dashboards tabs

Some of them got mixed and some don't.

## Context

It is not a big issue because we still can duplicate the tabs and rename them to keep the right order. But will be good don't have that trouble.

## Your Environment

* Graylog Version: Graylog 3.3.0+4ea5649 
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by chalfling** [comment]
Maybe a option to change/edit tabs order will do the work.
