### ISSUE TITLE
Error with backlog in aggregated event

### ISSUE THREAD

**Issue by AngelTG2** [Graylog2/graylog2-server#8265]
Hello,
I’ve create an aggregation event to check the number of BIND commands of a user to an LDAP server. If the user exceeds 10 binds per minute graylog will raise an alert.
I’ve create a pipeline to extract the username (ldap_dn), the operation (ldap_operation) and the method (ldap_method). These fields are create correctly in the message.
The alert is fired correctly, but the messages included in the backlog aren’t. Several messages regarding another usernames appear in the middle.

I’m using Graylog 3.3.0 over CentOS 7 (with Graylog 3.2.4 I’ve the same problem)

The format of the messages is this:
>conn=289188 op=0 BIND dn=“uid=user,dc=domain,dc=com” method=128

The event definition is:
>Condition Type: Filter & Aggregation
Search Query: ldap_operation:BIND AND \_exists\_:ldap_method
Search within the last: 1 minute
Execute search every: 10 seconds

>Aggregation
Group by field(s): ldap_dn
Condition: count(ldap_dn) >= 10

>Notification
Grace Period: 10 minutes
Message backlog: 10

If I try 10 times to bind with user1, the alert is fired but in the backlog appears messages related to user2. For example:
>conn=289188 op=0 BIND dn=“uid=user1,dc=domain,dc=com” method=128
conn=289189 op=0 BIND dn=“uid=user1,dc=domain,dc=com” method=128
conn=289190 op=0 BIND dn=“uid=user2,dc=domain,dc=com” method=128
conn=289191 op=0 BIND dn=“uid=user2,dc=domain,dc=com” method=128
conn=289192 op=0 BIND dn=“uid=user1,dc=domain,dc=com” method=128
conn=289193 op=0 BIND dn=“uid=user1,dc=domain,dc=com” method=128
conn=289194 op=0 BIND dn=“uid=user1,dc=domain,dc=com” method=128
conn=289195 op=0 BIND dn=“uid=user2,dc=domain,dc=com” method=128
conn=289196 op=0 BIND dn=“uid=user1,dc=domain,dc=com” method=128
conn=289197 op=0 BIND dn=“uid=user1,dc=domain,dc=com” method=128

It seems than the field “ldap_dn” (grouped by) is ignored to extract the backlog messages.
It would be more useful that only the related messages appears.

**Comment by jalogisch** [comment]
I'm closing this issue, as it is duplicating https://github.com/Graylog2/graylog2-server/issues/6381. Please subscribe to that issue and add comments there for any remarks you have and to track the progress of the issue.

Thank you!
