### ISSUE TITLE
Show row even if one field doesn't exist

### ISSUE THREAD

**Issue by xavier-isecurity** [Graylog2/graylog2-server#8289]
## What?

If we have a row in a table or in any aggregation, that has two field, A and B, but in some of the rolls the B field doesn't exist, instead of not showing the roll, show a N/A or a "-" in the place and still show tha data of the field A.

## Why?

Many time when building dashboards we face situations that we want to show data that maybe one field of this data will not exist for each row, however we still wanna show the rows that doesn't have this field, but have others selected fields.

For exemplae:

| Column A   | Column B   | count() |
|-----|-----|---------|
| value a-1   | value b-1 | 3       |
|     | value b-2 | 2       |
| value a-2   | N/A | 4       |
| N/A | value b-3| 4       |
|     | value b-4   | 3       |
|     | balue b-4   | 1       |

N/A: When doesn't have values.

## Your Environment

* Graylog Version: Graylog 3.3.0+4ea5649
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Fixed in #12958.
