### ISSUE TITLE
Not open the input with search in "All Messages"

### ISSUE THREAD

**Issue by xavier-isecurity** [Graylog2/graylog2-server#8303]
## What?

When click to open the input messages, open it with a short-time range query.

## Why?

When we click to see the input messages it opens the search with the "All Messages" query. But it can happen that your input has a lot of messages over time, what will result in a very heavy query for elasticsearch. So it will be nice if it open in a short time, them we can change for whenever time we want.

## Your Environment

* Graylog Version: 3.3.0+4ea5649
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Thanks @xavier-isecurity, for filing this issue. We are already tracking it and actually have a PR addressing it, so I am closing this issue. If you think that the referenced issue does not cover your problem, please reopen this issue with additional information.

Duplicate of #5620.
