### ISSUE TITLE
Null frame delimiter option checked by default for GELF input

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#831]
![screen shot 2014-12-25 at 22 31 47](https://cloud.githubusercontent.com/assets/35022/5554960/e6423568-8c85-11e4-8a85-ee02700425a7.png)

!) Very confusing because it also says that the newline separator is default
2) I cannot remember that we do actually support both newline and null byte separators. Please check that this is true at all.

**Comment by bernd** [comment]
I changed it to this.

![png](https://cloud.githubusercontent.com/assets/461/5644383/402cfdba-9663-11e4-855e-725201879a9a.png)
