### ISSUE TITLE
Several stream output issues

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#832]
1. NPE when trying to load outputs of a stream when the stream has no outputs (fixed in 65e375f72bd837bf381598482c15a52f26a0d2e6)
  1. Assigning outputs to streams was not working (fixed in 81393f40c4d0e3b9e6f8ae514034b38fbbdc73ba)
  1. Existing outputs of streams are not listed in web interface but returned by API
  1. Newly assigned outputs are not actually loaded into the output routing mechanisms. You have to restart the server to have messages routed into it. They are only added to MongoDB.
  1. Unassigned or terminated outputs are only removed from MongoDB and keep running until a restart of the server.

**Comment by kroepke** [comment]
point 4 doesn't seem to be true, if the stream is resumed the outputs are properly loaded and used.

**Comment by lennartkoopmann** [comment]
what if the stream was running when the output was assigned?

**Comment by kroepke** [comment]
@lennartkoopmann i removed that comment because it was wrong. the commit after your comment fixes that issue.

fixing the display bug now.

**Comment by lennartkoopmann** [comment]
Thanks!
