### ISSUE TITLE
Elasticsearch wont connect

### ISSUE THREAD

**Issue by joepointon123** [Graylog2/graylog2-server#8338]
No matter what I try graylog wont connect to the elasticseach instance im using . 

See Server.log file - 
2020-06-12T15:08:51.693Z INFO  [JerseyService] Enabling CORS for HTTP endpoint
2020-06-12T15:08:54.021Z WARN  [discovery] [graylog-86377c0a-3596-4ce3-8d1d-ec5fac06bdd9] waited for 3s and no initial state was set by the discovery
2020-06-12T15:08:54.022Z INFO  [node] [graylog-86377c0a-3596-4ce3-8d1d-ec5fac06bdd9] started
2020-06-12T15:08:59.037Z WARN  [IndexerSetupService] Could not connect to Elasticsearch
2020-06-12T15:08:59.037Z INFO  [IndexerSetupService] If you're using multicast, check that it is working in your network and that Elasticsearch is accessible. Also check that the cluster name setting is correct.
2020-06-12T15:08:59.038Z INFO  [IndexerSetupService] See http://docs.graylog.org/en/2.2/pages/configuration/elasticsearch.html for details.
2020-06-12T15:09:05.625Z INFO  [IndexRangesCleanupPeriodical] Skipping index range cleanup because the Elasticsearch cluster is unreachable or unhealthy
2020-06-12T15:09:06.625Z INFO  [NetworkListener] Started listener bound to [10.1.2.4:12900]
2020-06-12T15:09:06.627Z INFO  [HttpServer] [HttpServer] Started.
2020-06-12T15:09:06.634Z INFO  [JerseyService] Started REST API at <http://10.1.2.4:12900/>
2020-06-12T15:09:16.266Z INFO  [NetworkListener] Started listener bound to [10.1.2.4:9000]
2020-06-12T15:09:16.266Z INFO  [HttpServer] [HttpServer-1] Started.
2020-06-12T15:09:16.267Z INFO  [JerseyService] Started Web Interface at <http://10.1.2.4:9000/>
2020-06-12T15:09:16.268Z INFO  [ServerBootstrap] Services started, startup times in ms: {OutputSetupService [RUNNING]=116, JournalReader [RUNNING]=117, InputSetupService [RUNNING]=120, BufferSynchronizerService [RUNNING]=128, KafkaJournal [RUNNING]=136, ConfigurationEtagService [RUNNING]=165, StreamCacheService [RUNNING]=209, PeriodicalsService [RUNNING]=266, IndexerSetupService [RUNNING]=8477, JerseyService [RUNNING]=25707}
2020-06-12T15:09:16.272Z INFO  [ServiceManagerListener] Services are healthy
2020-06-12T15:09:16.288Z INFO  [InputSetupService] Triggering launching persisted inputs, node transitioned from Uninitialized [LB:DEAD] to Running [LB:ALIVE]
2020-06-12T15:09:16.294Z INFO  [ServerBootstrap] Graylog server up and running.
2020-06-12T15:09:16.434Z INFO  [InputStateListener] Input [Syslog TCP/5ee23d54f9662b79f21ff275] is now STARTING
2020-06-12T15:09:16.485Z ERROR [InputLauncher] The [org.graylog2.inputs.syslog.tcp.SyslogTCPInput] in

elasticsearch.yml - 
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: graylog
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
# node.name: master-1
# node.master:true
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
path.data: /var/lib/elasticsearch
#
# Path to log files:
#
path.logs: /var/log/elasticsearch
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this

#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
# network.host: 127.0.0.1
#
# Set a custom port for HTTP:
#
# http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when this node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.seed_hosts: ["serverIP:9300"]
#
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
#cluster.initial_master_nodes: ["master-1"]
#
# For more information, consult the discovery and cluster formation module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 1
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true

And the sevrver.conf file - 

# The auto-generated node ID will be stored in this file and read after restarts. It is a good idea
# to use an absolute file path here if you are starting Graylog server from init scripts or similar.
node_id_file = /etc/graylog/server/node-id

# You MUST set a secret to secure/pepper the stored user passwords here. Use at least 64 characters.
# Generate one by using for example: pwgen -N 1 -s 96
password_secret = passsecret

# The default root user is named 'admin'
#root_username = admin

# You MUST specify a hash password for the root user (which you only need to initially set up the
# system and in case you lose connectivity to your authentication backend)
# This password cannot be changed using the API or via the web interface. If you need to change it,
# modify it in this file.
# Create one by using for example: echo -n yourpassword | shasum -a 256
# and put the resulting hash value into the following line
root_password_sha2 = my pass
# The email address of the root user.
# Default is empty
#root_email = ""

# The time zone setting of the root user. See http://www.joda.org/joda-time/timezones.html for a list of valid time zones.
# Default is UTC
#root_timezone = UTC

# Set plugin directory here (relative or absolute)
plugin_dir = /usr/share/graylog-server/plugin

# REST API listen URI. Must be reachable by other Graylog server nodes if you run a cluster.
# When using Graylog Collectors, this URI will be used to receive heartbeat messages and must be accessible for all collectors.
rest_listen_uri = http://10.privIP:12900

# REST API transport address. Defaults to the value of rest_listen_uri. Exception: If rest_listen_uri
# is set to a wildcard IP address (0.0.0.0) the first non-loopback IPv4 system address is used.
# If set, this will be promoted in the cluster discovery APIs, so other nodes may try to connect on
# this address and it is used to generate URLs addressing entities in the REST API. (see rest_listen_uri)
# You will need to define this, if your Graylog server is running behind a HTTP proxy that is rewriting
# the scheme, host name or URI.
# This must not contain a wildcard address (0.0.0.0).
#rest_transport_uri = http://192.168.1.1:9000/api/

# Enable CORS headers for REST API. This is necessary for JS-clients accessing the server directly.
# If these are disabled, modern browsers will not be able to retrieve resources from the server.
# This is enabled by default. Uncomment the next line to disable it.
#rest_enable_cors = false

# Web interface listen URI.
# Configuring a path for the URI here effectively prefixes all URIs in the web interface. This is a replacement
# for the application.context configuration parameter in pre-2.0 versions of the Graylog web interface.
web_listen_uri = http://10.privIP:9000/

# Web interface endpoint URI. This setting can be overriden on a per-request basis with the X-Graylog-Server-URL header.
# Default: $rest_transport_uri
web_endpoint_uri = http://ServersIP:12900
# List of Elasticsearch hosts Graylog should connect to.
# Need to be specified as a comma-separated list of valid URIs for the http ports of your elasticsearch nodes.
# If one or more of your elasticsearch hosts require authentication, include the credentials in each node URI that
# requires authentication.
#
# Default: http://127.0.0.1:9200
#elasticsearch_hosts = http://node1:9200,http://user:password@node2:19200
elasticsearch_hosts = http://127.0.0.1:9200
# settings to be passed to elasticsearch's client (overriding those in the provided elasticsearch_config_file)
# all these
# this must be the same as for your Elasticsearch cluster
elasticsearch_cluster_name = graylog

# The prefix being used to generate the Elasticsearch node name which makes it easier to identify the specific Graylog
# server running the embedded Elasticsearch instance. The node name will be constructed by concatenating this prefix
# and the Graylog node ID (see node_id_file), for example "graylog-17052010-1234-5678-abcd-1337cafebabe".
# Default: graylog-
#elasticsearch_node_name_prefix = graylog-

# A comma-separated list of Elasticsearch nodes which Graylog is using to connect to the Elasticsearch cluster,
# see https://www.elastic.co/guide/en/elasticsearch/reference/2.3/modules-discovery-zen.html for details.
# Default: 127.*.*.*
elasticsearch_discovery_zen_ping_unicast_hosts = ServersIP:9300

Can anyone shed some light?

**Comment by radykal-com** [comment]
Hi,

First of all, can you tell us the version of graylog and ES you are running?

**Comment by joepointon123** [comment]
elasticsearch  - "number" : "7.7.1",
greylog-server - 2.2.3

**Comment by radykal-com** [comment]
Check this page for graylog elasticsearch compatibility chart:
https://docs.graylog.org/en/latest/pages/configuration/elasticsearch.html

Version 2.2 is only compatible with Elasticsearch 2.4.x

Latest graylog version 3.3 is compatible with Elasticsearch 6 and I think @dennisoelkers is working on Elasticsearch 7 compatibility

**Comment by jalogisch** [comment]
he @joepointon123 

as already pointed out by @radykal-com this Graylog Version is not compatible with your selected Elasticsearch verison.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
