### ISSUE TITLE
input cache keeps growing

### ISSUE THREAD

**Issue by ghost** [Graylog2/graylog2-server#835]
We have graylog2-web-interface v0.92.3 (Oracle Corporation 1.7.0_65 / Linux 3.13.0-43-generic) running on Ubuntu 14.04 and we keep seeing this error messsage in the logs

2014-12-29T01:49:23.536Z ERROR [MasterCacheWorkerThread] Error while trying to work on MasterCache <org.graylog2.caches.DiskJournalCache.Input>.
java.lang.NullPointerException
2014-12-29T01:49:29.273Z ERROR [AbstractCacheWorkerThread] Exception while working on cache:
java.lang.NullPointerException

Input cache keeps growing without flushing while we see GC too long errors on the front-end as well.

Anybody has an idea?

**Comment by bubo77** [comment]
Hi,

So back in the net. My graylog server died again. at the moment after cleaning all the caches restarting everything i am already at 4 GB input cache.
curl @127.0.0.1:12900/system/buffers?pretty=true
{
  "buffers" : {
    "output" : {
      "utilization_percent" : 0.0,
      "utilization" : 539
    },
    "input" : {
      "utilization_percent" : 100.0,
      "utilization" : 1024
    }
  },
  "master_caches" : {
    "output" : {
      "size" : 0
    },
    "input" : {
      "size" : 4791113
    }
  }

I've upgraded to oracle java 1.8 and the frequency of this error
2015-01-05T11:07:18.140Z ERROR [MasterCacheWorkerThread] Error while trying to work on MasterCache <org.graylog2.caches.DiskJournalCache.Input>.
java.lang.NullPointerException

is slower now. I am still getting the GC timout with 1 second setting it is avarage 1.5-2 sec. Not sure it has anything to do with anything

**Comment by bubo77** [comment]
Now we are at 9 Gb

{
  "buffers" : {
    "output" : {
      "utilization_percent" : 0.0,
      "utilization" : 860
    },
    "input" : {
      "utilization_percent" : 0.0,
      "utilization" : 704
    }
  },
  "master_caches" : {
    "output" : {
      "size" : 0
    },
    "input" : {
      "size" : 10121588
    }
  }

**Comment by bubo77** [comment]
{
  "buffers" : {
    "output" : {
      "utilization_percent" : 100.0,
      "utilization" : 1024
    },
    "input" : {
      "utilization_percent" : 100.0,
      "utilization" : 1024
    }
  },
  "master_caches" : {
    "output" : {
      "size" : 0
    },
    "input" : {
      "size" : 12678601
    }
  }
last update i think you catch the drift
