### ISSUE TITLE
How to add new Chart to graylog2?

### ISSUE THREAD

**Issue by jo5690** [Graylog2/graylog2-server#838]
I want to add new chart to show search result .new chart form flot.js,like pie chart and so on.

It can't add new to dashboard .I package the graylog2-rest-client source to new .jar file which add new class extends DashboardWidget.java and others.
when i click "add to dashboard" ,it message failure and no warn or error.
what else i should do?

**Comment by kroepke** [comment]
Adding dashboard widgets is a pretty involved process that requires changes in both server and web interface. I'm afraid I can't give you a concise guideline on how to do it.

However, if you have a specific request for a widget, you can update this issue so we can track the feature request.

Thanks!
