### ISSUE TITLE
Graylog2  classify Network device type?

### ISSUE THREAD

**Issue by shaman478** [Graylog2/graylog2-server#839]
Hello all,

We used Graylog2 0.92.3 plus SLES syslog-ng to received network devices logs,
Network devices sending their logs via UPD port to SLES syslog-ng server,
Graylog2 used syslog udp input to import the network device messages.

well, you know there have many kinds of network device type(router,switch,firewall or others),sometime the network guy search one keyword but this keyword maybe exist on both router and firewall side,
 my network colleagues ask me can we classify the network device type on Graylog2 or syslog-ng side? 
i mean can we detect the logs from which type of network device and  when you want to search one keyword we can selected one device type such as router or swicht firstly, it can be to reduce the search area more accurate.  I am not sure whether Graylog2 can be achieve this request or maybe it can be achieve with syslog-ng side?  thanks for your reply.

below is our graylog2 and syslog-ng configuration:

![1](https://cloud.githubusercontent.com/assets/9427526/5575368/8ab4a798-9014-11e4-878d-82efd00b6805.jpg)
![2](https://cloud.githubusercontent.com/assets/9427526/5575369/8ab4f892-9014-11e4-991c-3a7afe7a3500.jpg)
![3](https://cloud.githubusercontent.com/assets/9427526/5575370/8ab80776-9014-11e4-810e-aa759a6c7db7.jpg)

**Comment by kroepke** [comment]
The best option would be to add a field to the syslog message if possible, or use the source ip to search.

However, this is a question that is better addressed to our mailing list, as it is not a feature request or bug report.
Please use graylog2@googlegroups.com or the corresponding google group https://groups.google.com/forum/?fromgroups=#!forum/graylog2

I'll close this.

Best regards!
