### ISSUE TITLE
Graylog generates instability when have it more than 800 shards

### ISSUE THREAD

**Issue by chalfling** [Graylog2/graylog2-server#8414]
## Expected Behavior

Works with more than 800 shards

## Current Behavior

Can't view page "/system/indices" or others like "/system/index_sets/xxxxxx"
I have 4 index's sets with 2 shards and 1 replica each. With Rotation P1D and Max N# 90 days.
When shard's count is fewer than 800 like 50 days all works fine. But when shard's count more than 800 or around 850-900 I can't see indices page, all cluster became slow, if I restart a elasticsearch node I need to wait several hours to cluster became green.

I'm missing something? Can I change some settings to work?

## Your Environment

* Graylog Version: 3.3.1
* Elasticsearch Version: 6.8.7
* MongoDB Version: 4.2
* Operating System: FreeBSD 12.1

**Comment by hulkk** [comment]
I think your elasticsearch cluster is not keeping up. We don't have issues with this and we have currently over 10.000 shards.

**Comment by chalfling** [comment]
> I think your elasticsearch cluster is not keeping up. We don't have issues with this and we have currently over 10.000 shards.

Can you send your elasticsearch.yml, jvm.options?
How many Elasticsearch nodes do you have?
How about CPU and RAM per node?
Did you run on top of HDD or SSD?

Thank you!

**Comment by jalogisch** [comment]
he @chalfling  

I would like to share this blog post with you, this gives you some guidance and inside to elasticsearch and how many shards it can handle (with what hardware); https://www.elastic.co/blog/how-many-shards-should-i-have-in-my-elasticsearch-cluster

As @hulkk pointed out, this is not Graylog having problems. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
