### ISSUE TITLE
String "null" in log messages causes issues in pipeline rules

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#8417]
## Expected Behavior

Strings should be handled as strings no matter if the string is "null"

## Current Behavior

String "null" is interpreted as null and it causes WARN

Pipeline rule which contains
`to_string($message.type) == "null"`

Causes following WARN when log message contains string "null".
`WARN  [EqualityExpression] left expression evaluated to null, returning false: $message.type`

## Context

Certain filebeat configurations use type as "null" if it is not explicitly added.

## Your Environment

* Graylog Version: 3.3.1

**Comment by kroepke** [comment]
Does the log message contain `null` or `"null`"?

`to_string(null)` will return the default value (which is `""` if not passed as the second parameter to `to_string`).
`to_string("null")` returns `"null`" for me.

Looking at the code I can't immediately see how `to_string` ever returns `null`, which is what the warning claims it has gotten.
In fact when I force it to return `null`, the warning I get is different:
```
2020-06-29 15:08:56,457 WARN : org.graylog.plugins.pipelineprocessor.ast.expressions.EqualityExpression - left expression evaluated to null, returning false: to_string(value: $message.type)
```

Are you sure that it is the expression that triggers the warning? I'm pretty sure it is related to an expression that uses `$message.type == something` directly, without a function call.
