### ISSUE TITLE
Search widgets, which got created with a pre 3.2 version, can have a not supported time unit format

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#8439]
It is possible that a dashboard or saved search which got created with a pre 3.2 version contains widgets which have a not supported time unit format.

In terms of a search, row groups can have an interval like:
```
"interval" : {
  "timeunit" : "1y",
  "type" : "timeunit"
},
```
where the timeunit `1y` is not supported.

In terms of a view, row pivot configs can have an interval like:
```
 "interval" : {
  "type" : "timeunit",
  "value" : 1,
  "unit" : "years"
}
```
where the unit `years` is not supported

* Graylog Version: 3.3.2

**Comment by janheise** [comment]
What would be the solution to this? Support "y"? Or deprecate those searches?

**Comment by janheise** [comment]
No bug tickets regarding this came up in the last 18 months, so we close it as it does not seem to be a relevant issue.
