### ISSUE TITLE
Landscape Mode for Reports

### ISSUE THREAD

**Issue by ChristopherKB** [Graylog2/graylog2-server#8441]
## What?

Add the ability to format reports in landscape orientation.

## Why?

Certain widgets don't work well in portrait orientation. The ability to turn it to landscape would improve report appearance and readability.

## Your Environment

* Graylog Version: 3.3.x
* Elasticsearch Version: NA
* MongoDB Version:NA
* Operating System:NA
* Browser version:NA

**Comment by janheise** [comment]
it's not possible right now using the regular printOptions. see: https://bugs.chromium.org/p/chromedriver/issues/detail?id=3996 for reference.
We might add landscape mode using css though (will not work for paper size)

**Comment by dennisoelkers** [comment]
Fixed in Graylog2/graylog-plugin-enterprise#3220.
