### ISSUE TITLE
Stream Search Crashes

### ISSUE THREAD

**Issue by ivelichkovich** [Graylog2/graylog2-server#8442]
When searching in graylog 3.2 and 3.3 the search works fine. However, if I select the stream "All Messages" (where I stuff all the non system logs, the UI freezes and I need to exit my browser) (tried in chrome and safari)

## Expected Behavior
Can search.

## Current Behavior
if the stream is selected for search it crashes however all streams search works perfectly.

* Graylog Version: 3.2, 3.3.0, 3.3.1, 3.3.2
* Elasticsearch Version: 6.8
* MongoDB Version: 3.6
* Operating System: graylog/graylog container running on k8s
* Browser version: Chrome and Safari

**Comment by dennisoelkers** [comment]
Can you try this with the browser's JS console open to check if there are any errors?
