### ISSUE TITLE
"fingerprint" is reserved field name?

### ISSUE THREAD

**Issue by ajoslin103** [Graylog2/graylog2-server#8453]
I created an extractor that copies a message field named "json" out to a field named "jsonObj" 

Followed by a 2nd extractor that [using a marketplace module] parses that field and adds the results as message fields 

When a field in the original json is named "fingerprint" the process silently fails 

When I renamed it to "browserprint" the process succeeded

If this is not the right place to discuss this I understand -- there are a lot of moving parts and this one might not be in GL's court

thanks

stay safe
be well
get better

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
