### ISSUE TITLE
graylog2 should use the elasticsearch 1.4 client

### ISSUE THREAD

**Issue by opswhisperer** [Graylog2/graylog2-server#847]
Since 0.92 supports elasticsearch 1.4, the graylog2 server should also use the 1.4 client. When a 1.3 node connects to a 1.4 cluster Elasticsearch treats the whole cluster as 1.3 when reporting its version. 

This, for example, breaks Kibana 4 which requires ES 1.4.

**Comment by lonesomegeek** [comment]
Totally agree. I'm stucked with the same problem. Is there a workaround available (ie: copy index to another node that supports ES Client 1.4?)

+1 for this!

**Comment by kroepke** [comment]
We should update the client in 1.1, too late for 1.0

**Comment by bernd** [comment]
The Elasticsearch client got upgraded to 1.4.x. Closing this issue.
