### ISSUE TITLE
lookup table with name geoip leads to loop

### ISSUE THREAD

**Issue by sbaygithub** [Graylog2/graylog2-server#8470]
## Expected Behavior
I expect that the configuration page for the lookup table will be showed when you want to edit it.

## Current Behavior
When you created a lookup table with the name geoip and want to edit it's configuration the page ends in a loop and you
see the message "Server is currently unavailable" and many times "Fetching lookup table geoip failed: Request has been terminated Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc." See my attached screenshot

 I've checked also the Server Log but there is nothing logged.

## Steps to Reproduce (for bugs)
1. Create a new lookup table with the name geoip
2. Go on the overview page and click on edit
3. The page always refreshes without your interaction and shows error messages.

## Context
I created a new lookup table to get the geoip city information which is used in one of my
pipelines.

## Your Environment

* Graylog Version: 3.3.2-1
* Java Version: openjdk 11.0.7 (openjdk-11-jre-headless)
* Elasticsearch Version: 6.8.10
* MongoDB Version: 4.2.8
* Operating System: Debian 10.4
* Browser version: Firefox 77.0.1

<img width="1670" alt="Screenshot 2020-07-02 at 12 14 53" src="https://user-images.githubusercontent.com/49241858/86348116-80f9f000-bc5f-11ea-9aca-2481299224bb.png">

**Comment by edmundoa** [comment]
Hi @sbaygithub,

I had a hard time reproducing this on a clean Firefox setup but then I discover another Firefox instance I had was showing the same behaviour. It turned out I have an ad-blocker installed that is causing this issue, since one of the rules blocks any requests to `/geoip?`:

<img width="1098" alt="Screenshot 2021-01-11 at 17 17 25" src="https://user-images.githubusercontent.com/716185/104208875-4dc7c300-5431-11eb-9235-c3657bcfd343.png">

Do you have by any chance an ad-blocker installed on that Firefox setup? If yes, could you try again after disabling the ad-blocker or whitelisting Graylog? Thank you!

**Comment by sbaygithub** [comment]
Thanks for reproducing the issue. I can confirm that this issue only persists when an ad-blocker is used in the browser.
In my case I use Firefox with uBlock origin, after deactiving it for the Graylog site the page immediately loaded.

**Comment by sbaygithub** [comment]
> Hi @sbaygithub,
> 
> I had a hard time reproducing this on a clean Firefox setup but then I discover another Firefox instance I had was showing the same behaviour. It turned out I have an ad-blocker installed that is causing this issue, since one of the rules blocks any requests to `/geoip?`:
> 
> <img alt="Screenshot 2021-01-11 at 17 17 25" width="1098" src="https://user-images.githubusercontent.com/716185/104208875-4dc7c300-5431-11eb-9235-c3657bcfd343.png">
> 
> Do you have by any chance an ad-blocker installed on that Firefox setup? If yes, could you try again after disabling the ad-blocker or whitelisting Graylog? Thank you!

Thanks for reproducing the issue. I can confirm that this issue only persists when an ad-blocker is used in the browser.
In my case I use Firefox with uBlock origin, after deactiving it for the Graylog site the page immediately loaded.

**Comment by edmundoa** [comment]
Glad that it solved the issue! Thank you for your patience with it and the quick feedback :)
