### ISSUE TITLE
TV/Fullscreen Mode table field name duplicated

### ISSUE THREAD

**Issue by chalfling** [Graylog2/graylog2-server#8483]
## Expected Behavior

Only name one name field or custom name field.

## Current Behavior

Duplication of name field

## Steps to Reproduce (for bugs)

1. Create a table
2. Put to TV/Full Screen mode
3. Se bug
![Screenshot](https://user-images.githubusercontent.com/9088569/86481120-c123a600-bd25-11ea-8caf-7e3204910626.png)
## Your Environment

* Graylog Version: 3.3.2

* Elasticsearch Version: 6.8.7
* MongoDB Version: 4.2
* Operating System: FreeBSD 12.1

**Comment by dennisoelkers** [comment]
Thanks @chalfling, for reporting this. I can reproduce the issue and will prepare a fix for one of the next versions.

**Comment by chalfling** [comment]
Thank you @dennisoelkers !
