### ISSUE TITLE
Node metrics page unreliable due to timeouts in metrics/namespace/org

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#8489]
## Expected Behavior

Node metrics page should handle timeouts better and metrics requests should not be expensive.

## Current Behavior

https://redacted/api/cluster/redacted/metrics/namespace/org request is expensive and causes timeouts which are not handled correctly.

<img width="1351" alt="Screenshot 2020-07-06 at 14 23 11" src="https://user-images.githubusercontent.com/24830359/86588418-51672280-bf94-11ea-9196-6b0cd3fec5c8.png">

```
There was an error fetching a resource: cannot GET https://redacted/api/cluster/redacted/metrics/namespace/org (500). Additional information: timeout FetchProvider.js:21:14
    n FetchProvider.js:21
    E FetchProvider.js:42
    request FetchProvider.js:98
    c bluebird.js:5370
    _settlePromiseFromHandler bluebird.js:3366
    _settlePromise bluebird.js:3423
    _settlePromise0 bluebird.js:3468
    _settlePromises bluebird.js:3544
    u bluebird.js:145
    s bluebird.js:138
    _drainQueues bluebird.js:154
    drainQueues bluebird.js:67
```

## Steps to Reproduce (for bugs)

1. Go to Nodes pages
2. Open Metrics

## Your Environment

* Graylog Version: 3.3.1

**Comment by bernd** [comment]
This has been fixed in https://github.com/Graylog2/graylog2-server/pull/9316 which will be included in the upcoming 3.3.9 and 4.0.0 releases. Thank you for the report.
