### ISSUE TITLE
radio LB-Status down if RabbitMQ is full

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#852]
Right now radio tries to write to RabbitMQ even if the Queue is very big or almost full. This leads to a situation where it is alomst impossible to ever reprocess these messages... 

An option which says do not write anymore (set lb status to down) if the queue has more than x amount of messages might make sense here. There should be two options:
max_queue_size = 50.000.000
renanable_after_size = 10.000.000
It would not make sense to enable the queue with 49.999.999 messages becase a flipping status is not desired too.

In this case the radio node get's out of the loadbalancer distribution and it might be possible to process the messages again.

**Comment by kroepke** [comment]
Unfortunately AMQP 0.9.1 does not have a method to retrieve the queue size, so there's no reliable way to get that metric.

**Comment by bernd** [comment]
Closing this because radio is deprecated as of Graylog 1.0.0.
