### ISSUE TITLE
Permission checking when clicking on replay search in a dashboard widget

### ISSUE THREAD

**Issue by jgkirschbaum** [Graylog2/graylog2-server#8533]
## Expected Behavior
Clicking on the _replay search_ button on a widget in a dashboard should honor the users permission set and execute the query defined in the dashboard widget without landing on the login page.

## Current Behavior
Clicking on the _replay search_ button on a widget in a dashboard results in getting the login page.

## Steps to Reproduce (for bugs)
1. Create a user with read and no write permmission on a specific stream.
2. Ensure that the user has no permissions on the _all messages_ stream.
![g4](https://user-images.githubusercontent.com/12797213/87312577-082d4a80-c521-11ea-8df6-a71e8480b8b8.png)
3. Create a dashboard widget with a search query on that specific stream the user has permissions to.
![g0](https://user-images.githubusercontent.com/12797213/87309507-ffd31080-c51c-11ea-9a70-1d8bcf0ca483.png)
4. Navigate as the user from step 1 to that dashboard a click on the _replay search_ button on the widget.
![g1](https://user-images.githubusercontent.com/12797213/87309125-77547000-c51c-11ea-9264-3d19b5a15988.png)
5. The login page opens up.
![g2](https://user-images.githubusercontent.com/12797213/87309181-86d3b900-c51c-11ea-9062-b9b74397fcaf.png)
After successful login it redirects to `/search?rangetype=relative&streams=5d2f2bf328260349cac59bb8&q=&relative=300`

## Context
This issue is a showstopper for us because of our permission system inside graylog. Not every user is allowed to see all streams, therefore no user other than the administrators is authorized to see the _all messages_ stream. We still use Graylog 3.1.4 and there everything works well.

## Your Environment
* Graylog Version: 3.3.1
* Elasticsearch Version: 6.8.9
* MongoDB Version: 4.0.18
* Operating System: CentOS 7.8
* Browser version: Firefox 78.0.2

**Comment by dennisoelkers** [comment]
Hey @jgkirschbaum!

I am not sure I understood the issue completely. In steps 1-3, where does the `All Messages` stream come into play?

**Comment by jgkirschbaum** [comment]
@dennisoelkers I put an image in step 2 which should explain the step and put a liitle more text in step 5.

**Comment by jgkirschbaum** [comment]
Update:

My latest research showed that it has nothing to do with the permissions, but that it's a browser-specific problem. It works with Chrome and runs into the error shown above with Firefox, but only if you open Graylog in a private window.

**Comment by jgkirschbaum** [comment]
Could you please close or delete. This is not really a bug.

**Comment by dennisoelkers** [comment]
Thanks for your efforts to nail down the issue, @jgkirschbaum. Much appreciated!
