### ISSUE TITLE
Absolute Time Range fields clip off last digits

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#8556]
## Current Behavior
The absolute Time Range fields clip off the time. 

See here with the app in full-screen width 2560px wide:
![image](https://user-images.githubusercontent.com/3423655/87637711-ec08f380-c742-11ea-95ef-09dc9c988d6d.png)

And here in half-window width 1200px wide:

![image](https://user-images.githubusercontent.com/3423655/87637977-4e61f400-c743-11ea-921f-be63cefae5f9.png)

## Steps to Reproduce (for bugs)

1. Click the Time Range picker and choose Absolute
![image](https://user-images.githubusercontent.com/3423655/87637764-04790e00-c743-11ea-8c9a-71c994893f42.png)

## Your Environment

* Graylog Version: Graylog 3.3.1-SNAPSHOT+7d659de on
* Operating System: macOS Catalina 10.15.5 
* Browser version: Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by dennisoelkers** [comment]
Fixed for `4.1`.
