### ISSUE TITLE
New pipeline rule cannot be saved or applied twice

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#8560]
![pipelinebug](https://user-images.githubusercontent.com/3034831/87672950-07d8bd80-c774-11ea-9004-2b47842c45b4.gif)

* Graylog Version: master (cd01bd9d2c)

**Comment by bernd** [comment]
@mpfz0r Duplicate of https://github.com/Graylog2/graylog2-server/issues/7348?

**Comment by mpfz0r** [comment]
> @mpfz0r Duplicate of #7348?

It is. With the addition, that `Apply` twice doesn't work either.
IMO this is purely a frontend bug.

**Comment by Gaya** [comment]
Couldn't reproduce, maybe #9340 fixed this already?

**Comment by mpfz0r** [comment]
it most certainly is. thanks for checking :+1:
