### ISSUE TITLE
Working Graylog with big messages

### ISSUE THREAD

**Issue by DySprozin** [Graylog2/graylog2-server#8567]
Hi there! We collect logs from our java app by the Graylog 3.2 (sidecar+filebeat). Some messages have size 1-2 Mb (stacktrace), so when search result containes 10-15 such messages, Graylog web-interface works very slow, hangs and even craches browser tab. Is there solution to the problem (besides reduce stacktrace size)?

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
