### ISSUE TITLE
Creating a Pipeline with the API, without asigning a Source at the same time.

### ISSUE THREAD

**Issue by hasturo** [Graylog2/graylog2-server#8578]
Hello,

im trying to create a Pipeline without a assigned Stage/Rule with the API. In API Description the Parameter for source and stages are optional. But im not able to create a Pipeline without. 
In Webgui im able to Create a Pipeline but there, like a workaround, the Pipeline gets a Stage automagicaly which is not deletable.

I dont know if this is a Bug or the API Description is misleading. I expected to be able to create a Pipeline without any Stage.

I tried Graylog Version: Graylog 3.3.0+4ea5649

Best Regards, Hasturo

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by hasturo** [comment]
Hello Florian,

of course i tried the Forum first. https://community.graylog.org/t/configuring-pipeline-through-api/16428/6 

- Hasturo
