### ISSUE TITLE
WebUI: reports error "n is undefined"

### ISSUE THREAD

**Issue by ghost** [Graylog2/graylog2-server#8584]
## Expected Behavior

I expect that the requested site will be open

## Current Behavior

Sometimes when I'm logged in and request for example the Search or Dashboard it redirects
me to the error page with the message "n is undefined" (See Screenshot)
<img width="1671" alt="graylog_bug21720" src="https://user-images.githubusercontent.com/49241858/88019761-c7d65980-cb2a-11ea-9609-f141ba16883b.png">

## Steps to Reproduce (for bugs)
Please note that this bug only appears sometimes and not always. 

- Login into Graylog WebUI
- Go on any page like on Streams or Dashboards
- You should get an error page

## Your Environment

* Graylog Version: 3.3.2
* Elasticsearch Version: 6.8.10
* MongoDB Version: 4.2.8
* Operating System: Debian Buster 10.4
* Browser version: Firefox 78.0.2 (64-bit) under MacOS 10.15.6

**Comment by dennisoelkers** [comment]
Can you post more of the included stack trace? If it is not shown properly on the page, could you please check your browser's JS console? Ideally, repeat the step that triggers the error while the console is open.

**Comment by sbaygithub** [comment]
Here is the stack trace:
`[n] is undefined
Stack Trace:
render@https://graylog.local/assets/17e2f36c-19.ee54c4a9a01f2cd94626.js:1:21992
Wi@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:69874
Pi@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:69669
Ms@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:105468
uc@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:96717
sc@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:96640
Qs@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:93670
Ko/<@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:45312
29/exports.unstable_runWithPriority@https://graylog.local/assets/vendor.043dd426065882df527b.js:42:3988
Xo@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:45021
Ko@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:45259
Uo@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:45192
Gs@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:90455
enqueueSetState@https://graylog.local/assets/vendor.043dd426065882df527b.js:26:48977
24/y.prototype.setState@https://graylog.local/assets/vendor.043dd426065882df527b.js:34:1296
n@https://graylog.local/assets/vendor.043dd426065882df527b.js:18:2700
614/a.prototype.emit@https://graylog.local/assets/vendor.043dd426065882df527b.js:133:220231
trigger@https://graylog.local/assets/vendor.043dd426065882df527b.js:18:3581
list/<@https://graylog.local/assets/builtins.ee54c4a9a01f2cd94626.js:35:261498
c@https://graylog.local/assets/builtins.ee54c4a9a01f2cd94626.js:35:249359
i/<[22]</n.exports/I.prototype._settlePromiseFromHandler@https://graylog.local/assets/builtins.ee54c4a9a01f2cd94626.js:35:222297
i/<[22]</n.exports/I.prototype._settlePromise@https://graylog.local/assets/builtins.ee54c4a9a01f2cd94626.js:35:223097
i/<[22]</n.exports/I.prototype._settlePromise0@https://graylog.local/assets/builtins.ee54c4a9a01f2cd94626.js:35:223796
i/<[22]</n.exports/I.prototype._settlePromises@https://graylog.local/assets/builtins.ee54c4a9a01f2cd94626.js:35:225148
u@https://graylog.local/assets/builtins.ee54c4a9a01f2cd94626.js:35:176320
s@https://graylog.local/assets/builtins.ee54c4a9a01f2cd94626.js:35:176260
i/<[2]</a.prototype._drainQueues@https://graylog.local/assets/builtins.ee54c4a9a01f2cd94626.js:35:177374
a/this.drainQueues@https://graylog.local/assets/builtins.ee54c4a9a01f2cd94626.js:35:176193
Component Stack:
    in BufferUsage
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in a
    in div
    in i
    in ShowNodePage
    in n
    in div
    in t
    in div
    in t
    in t
    in AppWithoutSearchBar__StyledRow
    in div
    in t
    in div
    in t
    in AppContentGrid__Container
    in u
    in St
    in div
    in wt
    in o
    in Unknown
    in withRouter(Component)
    in d
    in mt
    in ConnectStoresWrapper[mt] stores=currentUser
    in c
    in RouterContext
    in Router
    in ar
    in lr
    in Unknown
    in n
    in Y
    in ConnectStoresWrapper[Y] stores=currentUser,server,sessionId
    in t
    in p`

**Comment by dmke** [comment]
Same here, using Graylog 3.3.5 and Elasticsearch 6.8.9 (both running in Docker).

<details><summary>Stacktrace</summary>

```
n is undefined

Stack Trace:

osx3epUg/os<@https://graylog.example.com/assets/ExtendedSearchPage.1ec71fc30880f2142b45.js:1:174393
m/<@https://graylog.example.com/assets/app.1ec71fc30880f2142b45.js:60:247452
value@https://graylog.example.com/assets/app.1ec71fc30880f2142b45.js:60:248629
Wi@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:69874
Pi@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:69669
Ms@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:105468
uc@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:96717
sc@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:96640
Qs@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:93670
Ko/<@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:45312
29/exports.unstable_runWithPriority@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:42:3988
Xo@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:45021
Ko@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:45259
Uo@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:45192
Gs@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:90455
enqueueSetState@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:26:48977
24/y.prototype.setState@https://graylog.example.com/assets/vendor.043dd426065882df527b.js:34:1296
c/</<@https://graylog.example.com/assets/NewSearchPage.1ec71fc30880f2142b45.js:1:5888


Component Stack:

    in ConnectStoresWrapper[Provider] stores=view,configs
    in Wu
    in ConnectStoresWrapper[Wu] stores=view
    in as
    in withRouter(as)
    in Unknown
    in n
    in c
    in withRouter(c)
    in Unknown
    in n
    in Unknown
    in n
    in div
    in c
    in div
    in wt
    in o
    in Unknown
    in withRouter(Component)
    in d
    in ft
    in ConnectStoresWrapper[ft] stores=currentUser
    in c
    in RouterContext
    in Router
    in ra
    in la
    in Unknown
    in n
    in Y
    in ConnectStoresWrapper[Y] stores=currentUser,server,sessionId
    in t
    in p
```

</details>

Yesterday, the search did work, and I've not updated the container images in the meantime.

**Comment by tocomo** [comment]
Same versions ...

```
TypeError: e[n] is undefined
    render BufferUsage.jsx:70
    Wi vendor.043dd426065882df527b.js:26
    Pi vendor.043dd426065882df527b.js:26
    Ms vendor.043dd426065882df527b.js:26
    uc vendor.043dd426065882df527b.js:26
    sc vendor.043dd426065882df527b.js:26
    Qs vendor.043dd426065882df527b.js:26
    Ko vendor.043dd426065882df527b.js:26
    unstable_runWithPriority vendor.043dd426065882df527b.js:42
    Xo vendor.043dd426065882df527b.js:26
    Ko vendor.043dd426065882df527b.js:26
    Uo vendor.043dd426065882df527b.js:26
    Gs vendor.043dd426065882df527b.js:26
    enqueueSetState vendor.043dd426065882df527b.js:26
    setState vendor.043dd426065882df527b.js:34
    n vendor.043dd426065882df527b.js:18
    emit vendor.043dd426065882df527b.js:133
    trigger vendor.043dd426065882df527b.js:18
    list MetricsStore.js:147
    c bluebird.js:5370
    _settlePromiseFromHandler bluebird.js:3366
    _settlePromise bluebird.js:3423
    _settlePromise0 bluebird.js:3468
    _settlePromises bluebird.js:3548
    u bluebird.js:145
    s bluebird.js:138
    _drainQueues bluebird.js:154
    drainQueues bluebird.js:67
    promise callback*o bluebird.js:4593
    _queueTick bluebird.js:163
    settlePromises bluebird.js:128
    _fulfill bluebird.js:3494
    _resolveCallback bluebird.js:3285
    r bluebird.js:3338
    promise index.js:97
    callback client.js:645
    m client.js:465
    emit index.js:145
    onreadystatechange client.js:761
    _end client.js:735
    end client.js:711
    promise index.js:80
    I bluebird.js:1033
    _resolveFromExecutor bluebird.js:3337
    I bluebird.js:2922
    promise index.js:79
    then index.js:121
    value FetchProvider.js:92
    U FetchProvider.js:183
    U FetchProvider.js:186
    list MetricsStore.js:141
    n vendor.043dd426065882df527b.js:18
    emit vendor.043dd426065882df527b.js:133
    trigger vendor.043dd426065882df527b.js:18
    triggerAsync vendor.043dd426065882df527b.js:18
    exports _invoke.js:5
    <anonymous> _task.js:35
    d _task.js:21
    P _task.js:25
    GuUTRImU _task.js:57
    Webpack 13
vendor.043dd426065882df527b.js:26:82383

```

**Comment by jpaniagua-e7** [comment]
We have experienced similar issue with GrayLog latest 3.3.8, ES 6.8.7 and Mongo 3.6.3 - Firefox 81.0.2, Windows 10 2004

`
n is undefined

Stack Trace:

osx3epUg/es<@http://graylog:9000/assets/ExtendedSearchPage.4678e54c30f1075e4dd8.js:1:172840
m/<@http://graylog:9000/assets/app.4678e54c30f1075e4dd8.js:60:247452
value@http://graylog:9000/assets/app.4678e54c30f1075e4dd8.js:60:248629
Wi@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:69874
Pi@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:69669
Ms@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:105468
uc@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:96717
sc@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:96640
Qs@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:93670
Ko/<@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:45312
29/exports.unstable_runWithPriority@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:42:3988
Xo@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:45021
Ko@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:45259
Uo@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:45192
Gs@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:90455
enqueueSetState@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:26:48977
24/y.prototype.setState@http://graylog:9000/assets/vendor.8d6aa5835c8302c41e2f.js:34:1296
c/</<@http://graylog:9000/assets/NewSearchPage.4678e54c30f1075e4dd8.js:1:6354


Component Stack:

    in ConnectStoresWrapper[Provider] stores=view,configs
    in Au
    in ConnectStoresWrapper[Au] stores=view
    in ts
    in withRouter(ts)
    in Unknown
    in n
    in g
    in c
    in withRouter(c)
    in Unknown
    in n
    in Unknown
    in n
    in div
    in c
    in div
    in wt
    in o
    in Unknown
    in withRouter(Component)
    in d
    in mt
    in ConnectStoresWrapper[mt] stores=currentUser
    in i
    in RouterContext
    in Router
    in ar
    in Unknown
    in ConnectStoresWrapper[Unknown/Anonymous] stores=streams
    in lr
    in Unknown
    in n
    in Y
    in ConnectStoresWrapper[Y] stores=currentUser,server,sessionId
    in t
    in p
`

**Comment by dennisoelkers** [comment]
I was never able to reproduce this issue and it has not been reported for a while, therefore I am closing this issue. If this still happens with any of the supported versions (4.0+), please reopen this issue!
