### ISSUE TITLE
ES Date types (Timestamps in Graylog) Alters based on Graylog search

### ISSUE THREAD

**Issue by LHTNGUYEN** [Graylog2/graylog2-server#8585]
Graylog relative search alters the timestamp, when viewing data in a table.
This happens when the search is for the last 2 hours and above, even though
the event messages is the exact same, and the individual values are correct
when looking on a message table or directly in ES index. This is on Graylog
3.3.2.

## Expected Behavior
These timestamp field should not change value on the table view, whether
your searching for events from the last 2 hour or simply all messages

## Current Behavior
Timestamp fields should not be altered on when viewing them on an aggregate
table, simply because the relative search time is increased as it does now.

## Steps to Reproduce (for bugs)

1.Create a aggregate table, and group items based on some ID, and include timestamp
2. Start increasing the relative search interval and the timestamp value changes.

Search in last 8 hours
Would change the time stamp to:
2020-07-14 13:18:00 +00:00

Would change the time stamp to:
2020-07-01 00:00:00 +00:00

Note:
This is only happening under the search tab, however under dashboard, reproducing
same steps, in a created dashboard it actually does not alter the timestamp.

## Context
We want to monitor server performances by using Graylog, on certain times
of the day, and is why we are using some of theses timestamps, with keys
to group perfomance data based on servername and the timestamp for when
a process we wanted to monitor started.

## Environment
* Docker Version:
3
* Graylog Version:
3.3.2
* Elasticsearch Version:
6.8.5
* MongoDB Version:
3
* Operating System:
Linux CentOS 7
* Browser version:
Chrome Version 83.0.4103.116 (64-bit)

**Comment by florianpopp** [comment]
@LHTNGUYEN Thanks for reporting. Could you provide a screenshot?
