### ISSUE TITLE
Field name is displayed twice

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#8587]
## Expected Behavior
The Field name should only be displayed once.

## Current Behavior
At the moment I found two locations where the field name is displayed twice. One is the the permalink of a single message the other is inside a table view of the reports. It might have multiple other parts I did not discovered yet.

![image](https://user-images.githubusercontent.com/404238/88053337-eacd3180-cb5b-11ea-9fcb-4cfff4690ecb.png)

## Steps to Reproduce (for bugs)

Open any message as permalink message. 

## Your Environment

* Graylog Version: 3.3.2

**Comment by dennisoelkers** [comment]
Fixed in #8570.
