### ISSUE TITLE
Drools 

### ISSUE THREAD

**Issue by aurelianu** [Graylog2/graylog2-server#859]
Can you please help me regarding this issue

http://stackoverflow.com/questions/27906636/drools-rule-engine-validation-service-knowledgebuilder-initialization-error

Thanks in advance!

**Comment by kroepke** [comment]
Sorry, I'm afraid we cannot help with general programming questions. However, feel free to look at our code to figure out how to use the drools API programmatically:
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/rules/DroolsEngine.java#L50
