### ISSUE TITLE
Nodes with too long GC pauses with G1GC

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/graylog2-server#8592]
Graylog generates a lot of GC pause alerts like

> Nodes with too long GC pauses (triggered 2 days ago)
> There are Graylog nodes on which the garbage collector runs too long. Garbage collection runs should be as short as possible. Please check whether those nodes are healthy. (Node: 7ee19339-0bae-45fe-9325-56166bcf088e, GC duration: 1699 ms, GC threshold: 1000 ms)

after switching to G1 GC. I believe the alerts are in error. GC probably does take a long time with G1GC, but as the world isn't stopped it isn't an issue. This alert should probably be modernized for use with newer JVMs with newer garbage collectors.

**Comment by zino7825** [comment]
I've same experienced after upgrade java from 8 to 11.

**Comment by mikkolehtisalo** [comment]
For now it is possible set `gc_warning_threshold = 5s` as workaround.

**Comment by boosty** [comment]
https://github.com/Graylog2/graylog2-server/pull/13929#issuecomment-1326126342
