### ISSUE TITLE
Refactor search and dashboard sharing to the new grants system

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#8598]
## Description

The search and dashboard sharing needs to be integrated into the new grants system.

We are currently using a separate system for dashboard and search sharing that lives next to our regular permission system. Since we now have a proper replacement with grants, the old search and view sharing should be migrated over.

## Tasks

- [ ] Migrate existing search and dashboard shares into grants

**Comment by mpfz0r** [comment]
Refs #8801

**Comment by linuspahl** [comment]
Got closed with: #8801
