### ISSUE TITLE
Graylog2 notifications?

### ISSUE THREAD

**Issue by shaman478** [Graylog2/graylog2-server#860]
Hello expert,

After we included one high workload network device(Barracuda) to Graylog2 platform, there have one notifications show us:

Nodes with too long GC pauses 16 hours ago
There are Graylog2 nodes on which the garbage collector runs too long. Garbage collection runs should be as short as possible. Please check whether those nodes are healthy. (Node: 29ced5e1-2ba7-4439-b1a2-141c354b1ca4, GC duration: 1848 ms, GC threshold: 1000 ms)

 Barracuda is one firewall system which will be generate around 1000 messages every hour, we want to what happened for this notification, it's some problme or not? thanks.

B.R
Yan da

**Comment by joschi** [comment]
We've chosen the threshold (default is 1 second) for the warning message to a value which usually causes problems (e. g. disconnects from the Graylog2 cluster or from the Elasticsearch cluster).

If you're fine with a higher threshold, you can change it in your `graylog2.conf` with the `gc_warning_threshold` setting.

In general, 1000 messages per hour shouldn't pose any problems at all, if you're not running on a C64 or an equivalently sized VM…

For additional questions which are not bug reports or feature requests, I'd like to encourage you to use our mailing list at https://groups.google.com/forum/#!forum/graylog2
