### ISSUE TITLE
Find a way to export entity ownership permissions to the frontend

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#8603]
The newly introduced wwnership permissions are not compatible with the existing permissions,
because they use GRNs instead of simple IDs.

Currently we return only `WildcardPermissions` to the frontend in `UserServiceImpl`

**Comment by mpfz0r** [comment]
not sure why Fixes #issueid doesn't work anymore :/

**Comment by bernd** [comment]
> not sure why Fixes #issueid doesn't work anymore :/

@mpfz0r See: https://github.com/Graylog2/graylog2-server/issues/8727#issuecomment-683637628 :wink:
