### ISSUE TITLE
Graylog2 support collect Microsoft Exchange tracking message?

### ISSUE THREAD

**Issue by shaman478** [Graylog2/graylog2-server#861]
Hello Expert,

We just want to know Graylog2 can be collect Microsoft Exchange and Trend-Micro InterScan Security Virtual Appliance tracking message or not?
if yes please give us some idea how to achieve this, thanks a lot.

B.R
Yan da

**Comment by joschi** [comment]
Graylog2 doesn't specifically support collecting messages from Microsoft Exchange or Trend Micro InterScan Web/Messaging Security, but as long as those products can send data into Graylog2 (e. g. via syslog, Windows EventLog, or any means), you can apply extractors to get structured information out of those messages and analyze them in Graylog2. 

For additional questions which are not bug reports or feature requests, I'd like to encourage you to use our mailing list at https://groups.google.com/forum/#!forum/graylog2
