### ISSUE TITLE
While retrieving data for this widget, the following error(s) occurred: Connection refused (Connection refused).

### ISSUE THREAD

**Issue by elyoncyber** [Graylog2/graylog2-server#8614]
Greetings, just finished deploying elastic, fluentd, and graylog.

Configured the input following instructions in the guide.

However  for all the widgets under the search tab It's displaying the following error:

![image](https://user-images.githubusercontent.com/34746882/88336040-eb033380-ccf9-11ea-8e4d-a58247e31150.png)

**Comment by jalogisch** [comment]
he @elyoncyber 

as you did not share any useful information you might like to share them in the community that somebody can help you.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by elyoncyber** [comment]
Thank you for your kind and considerate comment. It definitely sets a positive tone and brand perception of Graylog.
