### ISSUE TITLE
o365 dashboard bar-chart shows incorrect y-axis value

### ISSUE THREAD

**Issue by lingpri** [Graylog2/graylog2-server#8655]
the bar-chart with a visualization config of `stacked` mode is not behaving the way it should , looking at how its plotting the data.

## Expected Behavior
The Y-axis of the count must be at 103 and not above 200. Also missing units in Y axis. It must say `total number of records`

## Current Behavior
![dashboard_o365](https://user-images.githubusercontent.com/6947168/88841256-4b372100-d1a3-11ea-8e21-14e9cb11657f.png)

![graph_attributes](https://user-images.githubusercontent.com/6947168/88842465-1deb7280-d1a5-11ea-9c04-86b3f536fc94.png)

## Possible Solution
The area chart seems to be at the right Y-axis unit. I'm wondering about the bar chart with `stacked` mode.
https://www.highcharts.com/demo/bar-stacked

## Steps to Reproduce (for bugs)
https://smd-dev.torch.sh/dashboards/5f2194473a045813b558638c

## Context
The issue was found while building o365 dashboard.

## Your Environment

* Graylog Version:3.3.3
* Elasticsearch Version:
* MongoDB Version:
* Operating System: Ubuntu (bionic beaver)
* Browser version:

**Comment by lingpri** [comment]
![mode_barchart_group](https://user-images.githubusercontent.com/6947168/88843533-e382d500-d1a6-11ea-8244-da8d7318c672.png)

probably a mode of 'group` fixes the issue and it helps identify null ip addresses.

**Comment by kmerz** [comment]
Hi @lingpri,

the Y axis is correct. Since it is a stacked graph you need to sum up your stacked graphs:

Count 103 + AzureActiveDirectory 14 + SharePoint 89 == 206
