### ISSUE TITLE
Browser tab freezes after saving a Pipeline Rule and returning to the Pipeline Rules page

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#8657]
## Expected Behavior

That the Pipeline Rules page successfully loads and is responsive after clicking Save & Close on the Edit Pipeline page.

## Current Behavior

After returning to the Pipeline Rules page when clicking Save & Close or even the browser Back button after editing a Pipeline Rule, the entire browser tab freezes. All metrics for the rules are stuck in the "Calculating..." state:

![image](https://user-images.githubusercontent.com/3423655/88897622-e4217700-d24b-11ea-975c-b2f2f9ef659a.png)

For me, this is only reproducible in my local dev environment on the `cloud/cloud-3.3.json`, which is based on `3.3`.

I have not yet tested with a prod jar build, but I plan to. 

## Steps to Reproduce (for bugs)

1. Edit any pipeline rule.
2. Click Save & Close on the rule (or Back)
3. Browser tab freezes and never recovers. CPU spins up high.

## Your Environment

* Graylog Version: Graylog 3.3.3-SNAPSHOT (`cloud/cloud-3.3.json` manifest)
* Elasticsearch Version: 5.6-alpine
* MongoDB Version: 3.6
* Operating System: Mac OS Catalina 10.15.5 (19F101)
* Browser version: Chrome 84.0.4147.105 (Official Build) (64-bit)

**Comment by danotorrey** [comment]
I tried to capture a Chrome profile recording (from the Performance tab), but was unable to. It freezes and never completes.

**Comment by bernd** [comment]
I can reproduce this in my dev environment. /cc @dennisoelkers 
The browser tab freeze for a few seconds, sometimes longer and sometimes I have close the tab. This happens in Chrome and Firefox on Ubuntu Linux. (but only with the dev server)

**Comment by Gaya** [comment]
This is not happening on `cloud-4.0`, do we need to fix this issue in `cloud-3.3` or let the upgrade to `cloud-4.0` fix this?

**Comment by edmundoa** [comment]
I think we plan to start releasing `cloud-4.0` in the next days/weeks, so I would vote for waiting until `cloud-4.0` arrives.

**Comment by danotorrey** [comment]
I noticed today that this is happening in dev mode still. I pretty easily stumble on it when I work with Pipelines in dev mode.

**Comment by edmundoa** [comment]
@danotorrey it's been a long time since this happened last time. Could you share what you mean with "dev mode" and which Graylog and browser versions you are using, please? Thank you!

**Comment by danotorrey** [comment]
Thanks for the followup @edmundoa. It happens when I am running Graylog in my local development environment (with Intellij).

Graylog version: Graylog 4.2.0-SNAPSHOT 
Crome version: 91.0.4472.114 (Official Build) (x86_64)

This is what I see when the page freezes. To trigger it, I go to the Pipeline Rules page (`http://localhost:8080/system/pipelines/rules`), and add or edit a rule a few times. After saving a rule I am returned to the Pipeline Rules page again, and it freezes.
![image](https://user-images.githubusercontent.com/3423655/125128739-11b1aa00-e0c4-11eb-84ec-bc77161700be.png)

The page does not seem to recover after a few minutes, which eventually results terminating the page: 
![image](https://user-images.githubusercontent.com/3423655/125128955-5f2e1700-e0c4-11eb-9051-166c0d15c718.png)

**Comment by edmundoa** [comment]
I was able to reproduce this issue on Safari and Edge on Mac, will try to gather some information for debugging.

**Comment by edmundoa** [comment]
So far my investigation shows that most of the time is spent comparing props in the `shouldComponentUpdate` method of `connect`. The culprit for that seems to be that the `MetricContainer` component gets passed a React element as child, and the `isDeepEqual` function we use for comparing props is doing a deep comparison of each React element.

I _guess_ this is more visible in development than in production because React adds some extra information to the elements that needs to be compared. I will check doing a full build and testing how things are with production mode on.

To test if performance improved by avoiding deep comparing React elements, I did this change in `isDeepEqual.ts`:

``` diff
diff --git a/graylog2-web-interface/src/stores/isDeepEqual.ts b/graylog2-web-interface/src/stores/isDeepEqual.ts
--- a/graylog2-web-interface/src/stores/isDeepEqual.ts	(revision 931a85926f37b02497103886b96cf216742c1e30)
+++ b/graylog2-web-interface/src/stores/isDeepEqual.ts	(date 1629388827264)
@@ -14,6 +14,7 @@
  * along with this program. If not, see
  * <http://www.mongodb.com/licensing/server-side-public-license>.
  */
+import React from 'react';
 import { isEqualWith, isFunction } from 'lodash';
 
 const hasFn = (obj, fn) => (obj && obj[fn] && isFunction(obj[fn]));
@@ -29,6 +30,10 @@
     return first.equals(second);
   }
 
+  if (React.isValidElement(first) || React.isValidElement(second)) {
+    return false;
+  }
+
   return undefined;
 };
 
```

I am also attaching a zip file with two performance profiles I captured on Edge (I hope it loads on any Chromium-based browser): one as it is right now, one after doing the change shown above.

[new-pipeline-rule-performance-profiles.zip](https://github.com/Graylog2/graylog2-server/files/7016207/new-pipeline-rule-performance-profiles.zip)
