### ISSUE TITLE
Pipeline Editior did not recognize wrong condition "AND NOT"

### ISSUE THREAD

**Issue by xtruthx** [Graylog2/graylog2-server#8658]
## Expected Behavior
It should not be possible to save a conditon which has a "AND NOT". The pipeline Editor should thrown an ERROR
## Current Behavior
You can save the rule like:
```
rule "and not"
when
       has_field("foo") AND NOT
       has_field("bar")
then
     set_field("foo","foo");
end
```

The it throws pipeline process errors in the log and the documents are running through the rule and are lost.

## Your Environment

* Graylog Version: 3.2.6
* Elasticsearch Version: 6.8.11
* MongoDB Version: 4.2.6

**Comment by makstock** [comment]
@xtruthx You can check with the below rule and provide your result on it.

rule "and not"
when
       has_field("foo") AND NOT
       has_field("bar")
then
     set_field("foo","foo");
end

**Comment by xtruthx** [comment]
sorry but there is no difference between yor rule and the one of me. I had in my example a misstak with single quotes on the rule name, that it. 
But i just remove the idents which are not the cause.

**Comment by patrickmann** [comment]
@xtruthx I also cannot reproduce the reported issue. The rule fires and sets field "foo" as expected.

Why do you think AND NOT is illegal? I see nothing in the docs that would indicate that.
