### ISSUE TITLE
Pipeline editor always return to pipeline rules overview on `save & close`

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#8660]
## Expected Behavior
The `save & close` click should send you to where you where BEFORE you entered the editor. That if you enter the rule editor from a pipeline view you return to this pipeline view after `save & close`.

## Current Behavior
`save & close` always sends you to the rule overview screen. You need to hit `apply` and `cancel` to return to the page where you have started the editor from.

## Steps to Reproduce (for bugs)

1. select a rule by click on the name in the pipeline overview
2. click `save & close` 

## Context
if you have a big list of rules and many pipelines it generates more work and multiple clicks if you hit `save & close`. This is frustration pure for the user in bigger environment. 

## Your Environment

* Graylog Version: 3.3

**Comment by xtruthx** [comment]
Thank you @jalogisch .This is the reason why i hit `Apply` first and then use `Close` to get back to the curent pipeline instead of falling back to the Rule Set. I literaly simulate `save&close`
