### ISSUE TITLE
Search configuration relative time ranges not sorted

### ISSUE THREAD

**Issue by sbaygithub** [Graylog2/graylog2-server#8694]
## Expected Behavior

When I update the relative time ranges via API they should be in the correct order

## Current Behavior
When I update over the API the search configuration and there the relative time ranges the order totally wrong 
```
{'query_time_range_limit': 'PT0S', 'relative_timerange_options': {'PT5M': 'Search in the last 5 minutes', 'PT10M': 'Search in the last 10 minutes', 'PT15M': 'Search in the last 15 minutes', 'PT30M': 'Search in the last 30 minutes', 'PT1H': 'Search in the last 1 hour', 'PT2H': 'Search in the last 2 hours', 'PT6H': 'Search in the last 6 hours', 'PT8H': 'Search in the last 8 hours', 'PT12H': 'Search in the last 12 hours', 'P1D': 'Search in the last 1 day', 'P2D': 'Search in the last 2 days', 'P5D': 'Search in the last 5 days', 'P7D': 'Search in the last 7 days', 'P14D': 'Search in the last 14 days', 'P30D': 'Search in the last 30 days', 'PT0S': 'Search in all messages'}, 'surrounding_timerange_options': {'PT1S': '1 second', 'PT5S': '5 seconds', 'PT10S': '10 seconds', 'PT30S': '30 seconds', 'PT1M': '1 minute', 'PT5M': '5 minutes'}, 'surrounding_filter_fields': ['file', 'source', 'gl2_source_input', 'source_file'], 'analysis_disabled_fields': ['full_message', 'message']}
```

See screenshot:
<img width="810" alt="graylog_search_bug" src="https://user-images.githubusercontent.com/49241858/89307092-f4cd5500-d670-11ea-81c2-6629c3aa0f94.png">

## Steps to Reproduce (for bugs) 
1. I've do a put request on https://graylog.host/api//system/cluster_config/org.graylog2.indexer.searches.SearchesClusterConfig with the code:
```
{'query_time_range_limit': 'PT0S', 'relative_timerange_options': {'PT5M': 'Search in the last 5 minutes', 'PT10M': 'Search in the last 10 minutes', 'PT15M': 'Search in the last 15 minutes', 'PT30M': 'Search in the last 30 minutes', 'PT1H': 'Search in the last 1 hour', 'PT2H': 'Search in the last 2 hours', 'PT6H': 'Search in the last 6 hours', 'PT8H': 'Search in the last 8 hours', 'PT12H': 'Search in the last 12 hours', 'P1D': 'Search in the last 1 day', 'P2D': 'Search in the last 2 days', 'P5D': 'Search in the last 5 days', 'P7D': 'Search in the last 7 days', 'P14D': 'Search in the last 14 days', 'P30D': 'Search in the last 30 days', 'PT0S': 'Search in all messages'}, 'surrounding_timerange_options': {'PT1S': '1 second', 'PT5S': '5 seconds', 'PT10S': '10 seconds', 'PT30S': '30 seconds', 'PT1M': '1 minute', 'PT5M': '5 minutes'}, 'surrounding_filter_fields': ['file', 'source', 'gl2_source_input', 'source_file'], 'analysis_disabled_fields': ['full_message', 'message']}
```
2. Check in Graylog under Search the times or go in Configuration > Search Configuration ->  Relative time range options

## Context

I want to update the times to add 10min, 6h, 12h as a option to the search time.

## Your Environment

* Graylog Version: 3.3.3-1
* Java Version: 1.0.8+10
* Elasticsearch Version: 6.8.10
* MongoDB Version: 4.2.8
* Operating System: MacOSX 10.15.6
* Browser version: Firefox 79.0 (64-bit)

**Comment by sbaygithub** [comment]
We've fixed that problem, the reason was that Deployment server was running on Python 3.5.3 after switching to Python 3.7.3 everything works as expected now.

**Comment by dennisoelkers** [comment]
@sbaygithub: Thanks for the update. How is this issue related to Python?

**Comment by sbaygithub** [comment]
@dennisoelkers We use a small python script which makes API calls to Graylog update our the configuration of the components, like Streams, Dashboards and etc...
