### ISSUE TITLE
2FA support for Graylog Authentication

### ISSUE THREAD

**Issue by ChristopherKB** [Graylog2/graylog2-server#8695]
## What?

We would like to add a layer of 2 factor authentication to the Graylog Web UI. Our internal product for 2FA is Duo and I believe most of our other tools use SAML auth to enable the 2FA redirect.

## Why?

It will increase the security of our Graylog instance and allow us to follow our corporate IT security policies.

## Your Environment

* Graylog Version: 3.3.2
* Elasticsearch Version: 6.8.0
* MongoDB Version: v4.0.5
* Operating System: CentOS-7
* Browser version: Chrome v84.0.4147.105 / FireFox v79.0

**Comment by strikaco** [comment]
## Additional Why?

Per [American] Executive Order 13800 in 2017, by Fall 2020 (right about now) *all* defense contractors must be audited for CMMC compliance-- which stipulates implementation of multifactor authentication to protect logging/auditing infrastructure.

Enterprise Graylog breezed through the audit's log aggregation, analysis, RBAC and other nitpicks, but failed hard on the underwhelming MFA support-- which makes it noncompliant by default and a poor choice of tool for defense industry clients expecting OIDC or SAML integration post-2020. 

Our current options for compliance are to scramble to hack something together or perform faith-based compilation of random SAML Graylog plugins found on Github and pray they weren't authored by the PRC. Neither of these solutions [should rightfully] pass a cybersecurity audit of this nature.

**Comment by loosus456** [comment]
Just adding on here: we received a preliminary report of an IT compliance audit today, and Graylog was specifically flagged because it requires LDAP for external user authentication, doesn't support OpenID Connect or SAML, and has no significant support for MFA.

When security companies are recommending that we don't use Graylog -- itself a security product -- it looks kind of bad.
