### ISSUE TITLE
Saved Search Deletion - Should not clear screen

### ISSUE THREAD

**Issue by bud1979** [Graylog2/graylog2-server#8708]
When you delete a saved search, it clears the entire search window, and the pop-up from the saved search.

## Expected Behavior
When you delete the saved search in the pop-up, would expect to be left on the pop-up, and not close it out and refresh to a blank search page.  If you are mid search, or have changed any of the table fields, these are cleared out as well, which is not what would be expected by deleting a saved search.

## Current Behavior
Search is deleted, page is refreshed and all set back to default.

## Possible Solution
Just delete the saved search, but nothing else would be done. Allow the user to close out the saved search window

## Steps to Reproduce (for bugs)

1.  Add a couple fields to the table on the main search
2. Remove/Delete a saved search (Page is then refreshed)

## Your Environment

* Graylog Version:  3.3.3+

**Comment by dennisoelkers** [comment]
Thanks for reporting this, @bud1979!

I have just noticed that this is a duplicate. Closing this in favor of the slightly older #8330.
