### ISSUE TITLE
Pivot Configuration UI for widgets is unintuitive - refine UI or better documentation?

### ISSUE THREAD

**Issue by rayterrill** [Graylog2/graylog2-server#8717]
## Expected Behavior

The "Pivot Configuration" UI for widgets is unintuitive - we use that to modify for example the bucket sizes for dates to switch to 1 day, but there's nothing in the UI or documentation that I could find that points to clicking the value in the widget selection box as the mechanism to do that pivot configuration (I had to ask @lennartkoopmann).

## Current Behavior

Pivot configuration works, but it's not easy to find.

## Possible Solution

Modify the UI to make it more intuitive that clicking the item gives you additional options?
Add a prominent note to the documentation noting the functionality?
Add a note on the widget configuration screen itself noting how to make additional pivot configurations?

## Steps to Reproduce (for bugs)

1. Create a widget with @timestamp in the Rows column
2. Click the word @timestamp to see the Pivot Configurations

## Context

This is more refinement - just making it easier for people to see how this works.

## Your Environment

* Graylog Version: 3.2.1

**Comment by dennisoelkers** [comment]
This has been fixed in the new aggregation builder.
