### ISSUE TITLE
Pipeline creation only possible with sources field and not via stages

### ISSUE THREAD

**Issue by rosaLux161** [Graylog2/graylog2-server#8722]
The API documentation specifies that pipeline rules can be specified with both stages and source.

However, it only works if the source is specified.

**API doc:**
```
 urn:jsonschema:org:graylog:plugins:pipelineprocessor:rest:PipelineSource {
id (string, optional),
title (string, optional),
description (string, optional),
source (string, optional),
stages (array[object], optional),
created_at (string, optional),
modified_at (string, optional),
errors (array[object], optional)
} 
```

```
{'type': 'ApiError', 'message': 'Cannot construct instance of `org.graylog.plugins.pipelineprocessor.rest.PipelineSource`, problem: Null source\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 293]'}
```

## Expected Behavior
Usage of only stages field should link pipeline to rules.

## Current Behavior
Usage of only stages field doesn't link pipeline to rules.

This works:
```
  {
    "title": "test_pipeline",
    "source": "pipeline \"test_pipeline\"\nstage 0 match either\nrule \"test_rule_1\"\nrule \"test_rule_2\"\nstage 1 match either\nrule \"test_rule_3\"\nend"
  }
```

This doesn't work:
```
  {
    "title": "test_pipeline",
    "stages": [
      {
        "stage": 0,
        "match_all": false,
        "rules": [
          "test_rule_1",
          "test_rule_2"
        ]
      },
      {
        "stage": 1,
        "match_all": false,
        "rules": [
          "test_rule_3"
        ]
      }
    ]
  }
```

## Possible Solution
Only sources are specified here: [https://github.com/Graylog2/graylog2-server/blob/7fe3f6d42aa43b2ac24fa925b6e28bec216acb7a/graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/PipelineDao.java]

## Steps to Reproduce (for bugs)
1. POST or PUT on pipeline api endpoint with only stages field

## Context

Going over the stages field is better implemented for automation than the sources field, which only consists of one string.

## Your Environment

* Graylog Version: 3.3.2+ade4779
* Elasticsearch Version: 6.3.0
* MongoDB Version: 4.2.1
* Operating System: Debian 10 64
* Browser version: N/A

**Comment by patrickmann** [comment]
The system is actually performing as intended. Despite what it may seem like from the API docs, pipelines/pipeline does not take a stages data input. We only return stages in the response. 

The API doc could definitely be improved here; also, a more meaningful error message would be nice. I will suggest this to the team.
