### ISSUE TITLE
Admin wildcard permission ("*") doesn't work for GRNPermission checks

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#8727]
## Description

The ownership check in `RestResourceWithOwnerCheck` is using a `GRNPermission` instead of a `WildcardPermission`. That means even an admin user (with a `*` permission) needs an `own` grant in the grants table to be able to share an entity.

Admin users shouldn't need a grant for an entity to be able to share it.

**Comment by mpfz0r** [comment]
not sure why github didn't do this automatically

**Comment by bernd** [comment]
> not sure why github didn't do this automatically

@mpfz0r Because GitHub only closes issues automatically when a PR is merged into the default branch. (`master` in our case) Since we merge into `features/permissions`, this hasn't been closed.
