### ISSUE TITLE
Disable stream share button if user doesn't own stream

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#8728]
The "share" button on streams is currently not disabled if the current user doesn't own the stream.

![image](https://user-images.githubusercontent.com/461/89658666-1d528a80-d8cf-11ea-9c6f-10317dca62fa.png)

Pressing the button leads to an error page. To avoid that, we should disable the button for streams that are not owned by the current user.

**Comment by linuspahl** [comment]
When working on this issue we should also implement this check for dashboards and saved searches.

**Comment by kmerz** [comment]
Fixed with #8804
