### ISSUE TITLE
reader role has no access to search page

### ISSUE THREAD

**Issue by sbaygithub** [Graylog2/graylog2-server#8745]
## Expected Behavior
I expect that the default role permissions for the "Reader" group grants you automatically access to the global search page as the permissions already include savedsearches:read and savedsearches:write. 

This bug was fixed in Graylog 2.4.6 already, see #2520 and #620

## Current Behavior
Currently in the default role permissions for the "Reader" group a user has only access to the stream search but not to the standard search page.

## Steps to Reproduce (for bugs)
1. Create a new role over the WebUI or API
2. Assign the role to a user 
3. Login with the created user

## Context
I wanted to create roles which has access to specific streams and the search. As a workaround I needed to give my created roles additionaly the permissions:
```
searches:absolute
searches:keyword
searches:relative
```

## Your Environment

* Graylog Version: 3.3.3-1
* Java Version: 1.0.8+10
* Elasticsearch Version: 6.8.10
* MongoDB Version: 4.2.8
* Operating System: MacOSX 10.15.6
* Browser version: Firefox 79.0 (64-bit)

**Comment by kroepke** [comment]
this is related to https://github.com/Graylog2/graylog2-server/issues/8779 which we should be able to do in 4.0
