### ISSUE TITLE
LDAP authentication not evaluating "groupMembership" attribute

### ISSUE THREAD

**Issue by milaq** [Graylog2/graylog2-server#8763]
With Novell eDirectory, the group membership is referenced with the attribute `groupMembership` instead of AD's `memberOf`.
This leads to a problem where group members are not being recognized by the authentication code. 

## Expected Behavior
Group membership is correctly identified by evaluating a user's `groupMembership` attribute and mapped by the authentication flow.

## Current Behavior
The login test outputs:
`LDAP server did not return any groups for the user.`
although multiple groups are set for the respective user.

## Possible Solution
I didn't dig any deeper into the codebase, but maybe adding the attribute `groupMembership` as a valid way for the authentication to evaluate group membership here: https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java#L190 would be enough.

## Steps to Reproduce
1. Setup LDAP groups
2. Test login with user which has groups referenced via `groupMembership`

## Context
* Novell eDirectory as LDAP backend

## Your Environment
* Graylog Version: Graylog 3.3.2+ade4779 (Official Docker image)
* Java Version: 1.8.0_252
* Elasticsearch Version: 
* MongoDB Version: 3
* Operating System: Debian Buster
* Browser version:

**Comment by bernd** [comment]
We don't use the `memberOf` attribute anymore since 4.0 but do group resolving in a different way. So this one can be closed.
