### ISSUE TITLE
Always lowercase usernames when creating a GRN

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#8768]
When I create a user with the username `Theusername` and I try to assign an entity for this user, (POST `/prepare` with `selected_grantee_capabilities` ) the user (in the context of the response) is being listed with the GRN  `grn::::user:Theusername` in `available_grantees` but in `selected_grantee_capabilities` we use `grn::::user:theusername`.

**Comment by mpfz0r** [comment]
Fixed with #9084
