### ISSUE TITLE
Enable multi-select for TeamsSelector, RolesSelector and UsersSelector

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#8792]
Currently the `TeamsSelector`, `RolesSelector` and `UsersSelector` only support the assignment of one item, but it would improve the usability to be able to assign multiple items. 

Here is an overview of the necessary changes:
- User edit page
  - `RolesSelector`: Needs to be changed in the frontend
  - `TeamsSelector`: Needs to be changed in the frontend and backend https://github.com/Graylog2/graylog2-server/issues/9029
- Team edit page
  - `UsersSelector`: Uses same endpoints like `TeamsSelector`
  - `RolesSelector`: Needs to be changed in the frontend
- Role edit page
  - `UsersSelector` Needs to be changed in the frontend and backend https://github.com/Graylog2/graylog2-server/issues/9029

**Comment by kmerz** [comment]
Fixed with #9107 and others
