### ISSUE TITLE
Graylog behind 2 reverse proxies. 

### ISSUE THREAD

**Issue by briantownjr** [Graylog2/graylog2-server#8815]
Outside network --> Boundary Proxy << ---->>Graylog server with nginx reverse proxy on it

Graylog3 installed on Centos 8 box. SELINUX disabled. Firewalld turned off. 
Graylog server.conf set to bind to $IP:9000
Graylog server nginx configuration follows documentation setup with change on location:

```
server
{
    listen      443 ssl http2;
    server_name $IP;
    # <- your SSL Settings here!

    location /graylog/
    {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Graylog-Server-URL https://$server_name/graylog/;
      proxy_pass       http://127.0.0.1:9000;
    }
}
```
Boundary Reverse proxy configuration for Graylog is running apache. 
Setup on reverse proxy apache config:
```
<Location /graylog>
                ProxyPass https://$IP/graylog/
                ProxyPassReverse https://$IP/graylog/
        </Location>
```

## Expected Behavior
Outside proxy handle Graylog login and web requests for the internal system

## Current Behavior
Connection timeouts when looking at network stats on Firefox/Chrome for config.js and all other parts of graylog after the initial connection back to Graylog server. If I go to outsideproxy.foo.bar/graylog however on the graylog system itself it works just fine. Any other system though can't get to outsideproxy.foo.bar/graylog. 

## Possible Solution
I have tried removing the nginx config on the graylog server and just doing a proxy on the outside serve, doing a proxypass to $IP:9000 there but that has the same issues.

Not sure if there is a sub path I am missing in the server.conf configuration somewhere. I know in order to Proxy a few other tools like Redmine/Netbox I had to use subpath/subdirectory settings. 

## Steps to Reproduce (for bugs)

1. Install Graylog on Centos 8
2. Install nginx on Graylog system and set up using above code
3. Setup basic apache reverse proxy on another remote system pointing to Location /graylog to proxypass to graylog server

## Context

I would like to be able to utilize the outside proxy for connections to graylog from outside our internal network (Not to the internet, just our outside corporate network). Right now I can only connect to graylog while on the internal network.

## Your Environment

* Graylog Version: 3.3
* Java Version: 1.8
* Elasticsearch Version: 6.8.11
* MongoDB Version: 4.2.8
* Operating System: Centos8 64bit
* Browser version: Firefox 79/Chrome84

**Comment by jalogisch** [comment]
He @briantownjr 

please check the documentation in this: https://docs.graylog.org/en/3.3/pages/configuration/web_interface.html#apache-httpd-2-x

You forgot to add the header that is needed - `RequestHeader set X-Graylog-Server-URL "https://graylog.example.org/"` - that your Browser gets knowledge about the URL it can reach the Graylog API for communication. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
