### ISSUE TITLE
GELF output hostname resolution only performed during initialisation

### ISSUE THREAD

**Issue by gavllew** [Graylog2/graylog2-server#882]
graylog2-server 0.92.3

When configuring a new GELF output, a destination hostname is requested.  Through testing, it would appear that this hostname is only resolved once (when the output is initialised), and any subsequent changes to the DNS record are ignored until the graylog service is restarted.

For the TCP transport, it would make sense to at least re-resolve the hostname when reconnecting.  For the UDP transport, re-resolving the address periodically may be a good idea.

Use case: our graylog installation runs in a cloud environment, as does the service that receives the GELF output.  To support fail-over and graceful upgrades, we would usually configure a DNS entry with a short TTL to point at the appropriate server.

**Comment by kroepke** [comment]
There are JVM parameters for DNS caching, usually those defaults are geared towards not performing lookups again, IIRC.

Have a look at http://docs.oracle.com/javase/7/docs/technotes/guides/net/properties.html#nct to see if tweaking those settings helps to solve your problem.
If they do please let us know so we can put this into our documentation somewhere.

I'll leave this ticket open for that purpose.

**Comment by gavllew** [comment]
Thanks for the info, but I don't think that's what is causing this particular behaviour.  In `graylog2-server/src/main/java/org/graylog2/outputs/GelfOutput.java`, the `buildTransport` method constructs an `InetSocketAddress` to pass to the `GelfConfiguration` constructor.  This means that the underlying GELF client only possesses an IP address (not the hostname), and since the client handles the reconnects all future connections will target that original address.

**Comment by kroepke** [comment]
I see. Yes we should change that, we'll see if we can get it done before the final.

**Comment by gavllew** [comment]
Thanks!

**Comment by bernd** [comment]
There is still an issue for the UDP transport. See Graylog2/gelfclient#5.
