### ISSUE TITLE
URL containing a query as url parameter is modified when window is loaded 

### ISSUE THREAD

**Issue by hawkpatrick** [Graylog2/graylog2-server#8820]
## Expected Behavior

When I save a search, then modify the query (without saving it), copy+paste the browser's URL to the modified search then the search result contains the modified query and the search field shows results matching the modified query.  

## Current Behavior

Currently the pasted URL is getting modified automatically and suddenly contains the saved query. After a second it gets modified again automatically and shows the modified query again. The modified query is put to the search field as well. But the results still contain the logs matching the saved query. 

## Possible Solution

Fix the handling of url parameters. 

## Steps to Reproduce
1. I open the search page. 
2. I enter a search query A. 
3. I click the search symbol. 
4. I get search result A. 
5. I click on save. 
6. I modify the search, entering search query B. 
7. I click on the search symbol. 
8. I get search result B.
9. I copy the browser URL (containing query B). 
10. I paste the browser URL in another browser tab or window. 
11. The search field shows query A (Or sometimes shows query B).  Expectation: The search field should alwys show query B.
12. The result panel shows result A. (Never shows result B). Expectation: The result panel should always show result B.

## Context

We want to be able to quickly share links to searches without saving them. We therefore want to just copy + paste the URL. This worked fine in version 2.x 

We want to be able to link to a search from other applications passing the query as parameter. 
In version 2.x we were able to build an URL to a stream, passing the fields that should be shown, the time range and the query as URL parameters. 
With version 3 this is not possible anymore. Instead we try the following: We save a search, create a link to that saved search and pass the query and time window as URL parameters. However due to the bug described above the results panel is not showing the logs we want. 

## Your Environment

* Graylog Version: 3.2 and 3.3
* Java Version: ?
* Elasticsearch Version: ?
* MongoDB Version: ?
* Operating System: ?
* Browser version: Chrome 84.0

I could provide more information and a screencast / screenshot if needed.

**Comment by dennisoelkers** [comment]
Thanks for the input, @hawkpatrick!

1.) What do you mean when you say "With version 3 this is not possible anymore"? You should be able to include at least query and time range in the URL. The set of selected fields is not stored in the URL anymore, as in v3 you can have multiple message lists with potentially differing field selections.

2.) When I follow your steps and modify search query B manually in the query input, the URL is updated correctly for me and it includes the new search query. When I copy this and open it in a new browser tab/window, the correct query and result is shown. What am I doing wrong? How do you manipulate your query after saving the search?

**Comment by hawkpatrick** [comment]
Hi @dennisoelkers,

thanks for the quick reply. 
1.) I know that query and time range still is possible but without fields I cannot use this anymore. Users would have to configure the fields by themselfe for each search which would be a pain and lead to not using the links anymore at all. Therefore I came up with the idea to save the seach and link to the saved search: Selected fields and streams are pre-configured in the saved search, query and time-range are passed as URL parameters. BUT: This does not work:

2) I'll show you an example in screenshots to avoid a misunderstanding but it seems that your system and mine behave differently (we have 3.3.2 on dev and 3.2.2 test instance, behaviour is same on both though). 

![steps1-4](https://user-images.githubusercontent.com/30664154/90789948-c9e92f00-e307-11ea-9301-a7e7d04da708.png)
![steps5-8](https://user-images.githubusercontent.com/30664154/90789950-ca81c580-e307-11ea-89f9-0fa228e548f7.png)
![steps9-10](https://user-images.githubusercontent.com/30664154/90789951-ca81c580-e307-11ea-8727-65af49ca7bdf.png)

I don't know if it is important but we have update interval set to "Not Updating" (see symbol in top right corner)

**Comment by dennisoelkers** [comment]
Thanks for the update.

After step 10, what happens if you press the search button with the looking glass icon?

**Comment by dennisoelkers** [comment]
@hawkpatrick, thanks! Can you reliably reproduce this? If you follow the steps, does it happen every time? If yes, do you see anything in your browser's JS console?

**Comment by hawkpatrick** [comment]
@dennisoelkers It is 100% reproducable on 3.3 and 3.2. I can not say in which version the bug appeared for the first time but a colleague of mine just told me that the bug was not yet there in 3.2.4, and appeared with the upgrade on 3.2.6. 


The only thing I see in the JS console is: 

```
bluebird.js:1545 Warning: a promise was created in a handler at /<GRAYLOG_URL>/assets/builtins.8db32af0c31b8447f8a4.js:76:20215 but was not returned from it, see http://goo.gl/rRqMUwError
at L (https://<GRAYLOG_URL>/assets/builtins.8db32af0c31b8447f8a4.js:76:33894)
at O.r._warn (https://<GRAYLOG_URL>/assets/builtins.8db32af0c31b8447f8a4.js:76:28961)
at Object.checkForgottenReturns (https://<GRAYLOG_URL>/assets/builtins.8db32af0c31b8447f8a4.js:76:39168)
at O._settlePromiseFromHandler (https://<GRAYLOG_URL>/assets/builtins.8db32af0c31b8447f8a4.js:76:63884)From previous event:
at O.F [as _captureStackTrace] (https://<GRAYLOG_URL>/assets/builtins.8db32af0c31b8447f8a4.js:76:33566)
at O._then (https://<GRAYLOG_URL>/assets/builtins.8db32af0c31b8447f8a4.js:76:59226)
at O.e._passThrough (https://<GRAYLOG_URL>/assets/builtins.8db32af0c31b8447f8a4.js:76:45453)
at O.e.lastly.e.finally (https://<GRAYLOG_URL>/assets/builtins.8db32af0c31b8447f8a4.js:76:45558)
at f.validate (https://<GRAYLOG_URL>/assets/builtins.8db32af0c31b8447f8a4.js:76:97504)
at a.n (https://<GRAYLOG_URL>/assets/vendor.5452e7a2fdfb6282da0a.js:10:1594)
at a.emit (https://<GRAYLOG_URL>/assets/vendor.5452e7a2fdfb6282da0a.js:78:243907)
at Function.trigger (https://<GRAYLOG_URL>/assets/vendor.5452e7a2fdfb6282da0a.js:10:2469)
at https://<GRAYLOG_URL>/assets/vendor.5452e7a2fdfb6282da0a.js:10:2573
at GJnkpH39.t.exports (https://<GRAYLOG_URL>/assets/polyfill.8db32af0c31b8447f8a4.js:1:29466)
at y.<computed> (https://<GRAYLOG_URL>/assets/polyfill.8db32af0c31b8447f8a4.js:1:82575)
at Number.m (https://<GRAYLOG_URL>/assets/polyfill.8db32af0c31b8447f8a4.js:1:82433)
at MessagePort.d (https://<GRAYLOG_URL>/assets/polyfill.8db32af0c31b8447f8a4.js:1:82455)
```

However, I don't know if this stack has something to do with the described bug. The same stack appears when I click on "Search" in the top level menu and then load a saved search.

**Comment by MingyuanWangDB** [comment]
This is working again currently under a staging environment with an update to Graylog 3.3.4. The experience suffers however from some non-deterministic behavior.  

**Example URLs**

- Original search

https://log-iat.dbv.comp.db.de/search/5f0c912247047c6c3268ec56

- The same search with adjusted search parameters:  

https://log-iat.dbv.comp.db.de/search/5f0c912247047c6c3268ec56?q=%22C-0%22&rangetype=relative&streams=5e3ae0709792aa0009a61b9a%2C5dc13c3f3348b4000bcea895&relative=172800

It seems that the loading of an adjusted URL to a search is based on these single steps: 
1. Remember the current set of parameters (query, range type, time offset, and streams) of the URL
2. Load the chosen search with its originally saved parameters
3. Transfer those remembered parameters from step 1 overwrite on the GUI. 
4. Trigger a new query with these parameters on the chosen search (with preselected coloums)

Sometimes it appears to get stuck after step 3, which is probably caused by a failed trigger. 

We're not yet sure if this is a bug dedicated to 3.2.6. So we'll keep inspecting this case. 
@hawkpatrick
