### ISSUE TITLE
Implement user preferences for user edit and details page

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#8826]
The user preferences (`enableSmartSearch`, `themeMode`, `updateUnfocused`, `dashboardSidebarIsPinned`, `searchSidebarIsPinned`) need to be integrated for the new user management. 
They should be display in a new section on the user details and edit page. On the edit page all options with a boolean value should be displayed as a checkbox. The `themeMode` is the only option which is not a boolean it should be configurable by using a select.

**Comment by kmerz** [comment]
Fixed with #8846
