### ISSUE TITLE
Alert Message Aggregation "Group by Field(s)" differ from Backlog Message

### ISSUE THREAD

**Issue by chalfling** [Graylog2/graylog2-server#8828]
I had a summarize log messages matching the Filter on Event section aggregating by "account_name" but differ from Backlog messages details.

Like this:
--- [Event Definition] ---------------------------
Title:       Test - User Blocked
Description: Blocked user alert
Type:        aggregation-v1
--- [Event] --------------------------------------
Timestamp:            2020-08-19T15:23:59.663Z
Message:              Test - User Blocked: mary.test - count()=2.0
Source:               node1
Key:                  
Priority:             3
Alert:                true
Timestamp Processing: 2020-08-19T15:23:59.663Z
Timerange Start:      2020-08-19T11:23:59.663Z
Timerange End:        2020-08-19T15:23:59.662Z
Fields:
--- [Backlog] ------------------------------------

Last messages accounting for this alert:

{index=graylog_16, message=2020-08-19T08:38:53.456323-3:00 HOST-SERV01.Test.corp Snare Enterprise Agent for Windows - MSWinEventLog             - 4         Security              6880362             Wed Aug 19 08:38:52 2020   4740     Microsoft-Windows-Security-Auditing   HOST-PC\john.test             N/A       Success Audit    HOST-SERV01.Test.corp        User Account Management                     A user account was locked out.    Subject:   Security ID:  S-1-5-18   Account Name:  HOST-SERV01$   Account Domain:  Test   Logon ID:  0x3E7    Account That Was Locked Out:   Security ID:  S-1-5-21-2076740144-1007505197-787892545-33049   Account Name:  john.test    Additional Information:   Caller Computer Name: HOST-PC        775787, source=HOST-SERV01, fields={date=2020-08-19T08:38:53-03:00, agent=Snare Enterprise Agent for Windows, priorityNum=5, criticality=4, pid=0, program=snare, dvc_name=HOST-SERV01.Test.corp, gl2_source_input=5e46d610be052a54dcf5b328, event_type=Success Audit, cat=User Account Management, account_name=john.test, host=HOST-SERV01.Test.corp, asset_hostname=asset_unknown, gl2_source_node=5f7e2f30-047a3c960a2d-363e-4977-b6fc, event_src=Security, event=A user account was locked out, source_name=Microsoft-Windows-Security-Auditing, gl2_accounted_message_size=1275, snare_counter=6880362, submit_time=Wed Aug 19 08:38:52 2020, gl2_message_id=Y1WPDBPBF95CX01EG387H467KA, priority=notice, event_id=4740, domain=HOST-PC, facility=user, user=john.test}, id=8eaba870-e210-11ea-86e8-005056b67d9a, timestamp=2020-08-19T11:38:52.918Z, stream_ids=[5e663438be052a05458f231d]}

The Account Name "mary.test" was blocked 2 times in the last 4 hours(from 11:23 am to 15:23 pm witth timezone +0:00) and the event was triggered. But Backlog Message was from "john.test" that was blocked only one time at 4 hours ago(08:38 am with timezone -03:00 OR 11:38 am with timezone +0:00).

I think that Backlog Messages was to see details from its alerts, but it is the wrong detail that was brought to me. 

## Steps to Reproduce (for bugs)

1. Create a alert to 2 events or more from a user(like blocked user, attempt to logon)
2. Configure 1 backlog message
3. Generate 2 events to a user(mary) and generate a third event to another user(john)
4. You will receive backlog of a alert from another user(that not generate the alert)

## Your Environment

* Graylog Version: 3.3.5 (also 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4)
* Java Version: 1.8
* Elasticsearch Version: 6.8.7
* MongoDB Version: 4.2
* Operating System: FreeBSD 12.1

**Comment by chalfling** [comment]
This also happen in Graylog's version 3.3.8

**Comment by bernd** [comment]
We fixed the alert backlog scoping in Graylog 4.1. I am closing the issue; please open a new issue if you still see the problem with Graylog 4.1 or newer. Thank you!
