### ISSUE TITLE
Filter `-myfield: "my exact phrase"` still finds messages with field `myfield` containing string `my exact phrase`

### ISSUE THREAD

**Issue by Drugoy** [Graylog2/graylog2-server#8831]
## Expected Behavior

The search for `-myfield: "my exact phrase"` should exclude messages where field `myfield` contains string `my exact phrase`.

## Current Behavior

<img src="https://i.imgur.com/qIJL45V.png">

## Possible Solution

I don't know, maybe I need some ElasticSearch index/field tweaks, but I'd like to know which ones and I think this knowledge would better belong to the [Search query language syntax](https://docs.graylog.org/en/latest/pages/searching/query_language.html#syntax) page.

## Steps to Reproduce (for bugs)

1. Have a message with some long text/string that contains string `my exact phrase` in the `myfield` field.
2. Use search filter `-myfield: "my exact phrase"`
3. The search should not find you the message you have.

## Context

Again, I try to reduce the bug's conditions down to the bare minimum. I do this analytically. The query in the screenshot has a long set of conditions all chained via "AND" and has only one 'positive' condition `Severity: ERROR`, the rest are conditions excluding some messages.

## Your Environment

* Graylog Version: 3.3.3
* Java Version: 1.8.0_242
* Elasticsearch Version: 6.8.5-1
* MongoDB Version: 4.0.13-1.el7
* Operating System: CentOS 7, Linux 3.10.0-1127.el7.x86_64
* Browser version: Latest chromium, irrelevant.

**Comment by dennisoelkers** [comment]
Hey @Drugoy,

it looks like the `-` operator can be used only when using a single term after. That means, you cannot use `-field:content`, but only `-content`. In your case, it could be `-"my exact phrase"`. If you really need to match on a `field:content` condition, you need to use `NOT`, e.g. `NOT myfield:"my exact phrase"`.

As this does not seem to be a problem with Graylog, I am closing this issue. If you have additional information that indicate that this is a bug nonetheless, please reopen it.

**Comment by Drugoy** [comment]
This doesn't sound right at all, because it sometimes works juuust fine.
<img src="http://i.imgur.com/7iuvua9.png">

**Comment by Drugoy** [comment]
@dennisoelkers as an outsider - I don't have enough rights to re-open the issue, but I surely would like to do so.

**Comment by Drugoy** [comment]
Some important detail about this bug: the bug is that negative condition seems to work ONLY for full value matches, not partial ones:
<img src="https://i.imgur.com/sQNwnmm.png">
<img src="https://i.imgur.com/ZnTU9Fb.png">

**Comment by Drugoy** [comment]
Ran a few more tests, looks like there might be something wrong with particular fields.
Some messages have a field `StackTrace`. Some of those messages have phrases like `Unable blablba` as values in that field.
However searching for `StackTrace: "Unable"` returns nothing at all.

**Comment by Drugoy** [comment]
This field has type `keyword`, that's probably the reason.
Now I don't know if this ticket should remain closed or not.
