### ISSUE TITLE
Mouse hovering over a value on an histogram chart displays all the values with the same color

### ISSUE THREAD

**Issue by emmanuel-ts** [Graylog2/graylog2-server#8867]
### Current Behavior
On the Search page, when generating a Quick Values chart for a field, and displaying it as an histogram, multiple values for this field are assigned the same color. Moreover, when hovering the mouse over one value, ALL the values that were assigned the same color are displayed on the histogram (the others being grayed).

### Expected Behavior
When hovering the mouse over one value, only this value should be displayed, even if some other values have the same color. It would also be nice to be able to select the colors as implemented in the Views feature.

### Context
The particular search used to create this histogram contains a lot of different values for one field, and narrowing down the data by mouse hovering would be appreciated. It is possible to display the Quick Values chart as a Pie Chart, and then select one value to add to search query, but as the histogram is displayed on a Dashboard, it would be nice to visually narrow the data down within the Dashboard instead.

Graylog Version: 3.1.3
Browser version: Firefox Quantum 60

### Example
In this example, hovering the mouse over the "538" value or the "861" value lead to the same result displayed below : both values are emphasized (in pink).
![Test-Histogram](https://user-images.githubusercontent.com/70209784/91181002-aef03380-e6e8-11ea-861c-cad706bd37ef.png)

**Comment by dennisoelkers** [comment]
Hey @emmanuel-ts,

unfortunately you are using a rather old version of Graylog. We are not releasing any new versions in the 3.1.x tree, especially considering that we did a major rewrite of the search frontend for 3.2. Therefore I am closing this issue. Please try using the latest version and if the problem still persists, open a new issue.
