### ISSUE TITLE
Store LDAP settings in server.conf or .env

### ISSUE THREAD

**Issue by Nebucatnetzer** [Graylog2/graylog2-server#8872]
Currently the LDAP settings get saved in the database.
For an automated setup however it would be nice to have the settings in the server.conf file or in the .env file.

**Comment by homerobono** [comment]
I don't believe that such config should be set at config file level. This is a shared setting, and you can insert it on your database for your automated setup.

**Comment by pkaroluk** [comment]
It's not a good idea to store LDAP passwd in the config file. But as we're talking you should think about allow set multiple LDAP Servers for the HA.

**Comment by Nebucatnetzer** [comment]
Ah forgot about the multiple servers.
We currently only use it on one server.
I like to automatically setup my system as far as possible so that I don't have to do so much manual work when I want to recreate the server for whatever I need it.

About not storing the password in the config file, it's a read only user.
Not really that much of a problem.

You can close the issue if you want, I still think it would be handy to have the LDAP automatically get configured when I deploy a new server.

**Comment by bernd** [comment]
We will support multiple identity providers in the future and they will be configured in the database.
