### ISSUE TITLE
Add pipeline function to remove multiple fields 

### ISSUE THREAD

**Issue by lingpri** [Graylog2/graylog2-server#8874]
make a pipeline function to remove multiple fields with a new class `RemoveFields.java` . it provides a way to exclude a list of fields in a message.

example: http://ipaddress:8080/system/pipelines/rules/new

![pipeline_rule](https://user-images.githubusercontent.com/6947168/91359928-2098b200-e7bb-11ea-9cfe-a001c8540bd0.png)

## What?
it must be able to remove multiple fields in a message in a single command.

existing function : `remove_field`
add new function : `remove_fields`

## Why?
just so we don't repeat ourselves. refer `setFields.java`

## Your Environment

* Graylog Version:
* Elasticsearch Version:6.x
* MongoDB Version:4.x
* Operating System:ubuntu
* Browser version:firefox-79.0

**Comment by jalogisch** [comment]
[z#843888]

**Comment by damianharouff** [comment]
It looks like this has been implemented via https://github.com/Graylog2/graylog2-server/pull/19268

**Comment by bernd** [comment]
Closed in #19268.
