### ISSUE TITLE
api-browser buttons use the http_bind_address instead of http_external_uri (AWS-ec2 / GCP VM issue)

### ISSUE THREAD

**Issue by katmai** [Graylog2/graylog2-server#8879]
## Expected Behavior
the api-browser buttons located in system/nodes -> nodes, to use the http_external_uri when displaying the clickable url, instead of http_bind_address 

## Current Behavior
the api-browser buttons use the http_bind_address instead of http_external_uri 
![image](https://user-images.githubusercontent.com/1245160/91450587-bd6f5400-e87c-11ea-8d6d-9e5eef26455a.png)

this is an issue for machines that are on AWS/EC2 because even if you try to set the http_bind_address to 0.0.0.0, the internal ip of the VM will be shown as clickable link and won't work

## Possible Solution
when displaying the buttons, use the http_external_uri

## Steps to Reproduce (for bugs)
![gl](https://user-images.githubusercontent.com/1245160/91451119-61f19600-e87d-11ea-8a60-7b80c70e1a4e.png)
bottom left corner, you can see the displayed url

## Context
convenience - clicking the api buttons in the interface to easy reach the node api endpoint.

## Your Environment

* Graylog Version: 3.3.4
* Java Version:
* Elasticsearch Version: 6.8.11
* MongoDB Version:
* Operating System: ubuntu 20
* Browser version: edge 84

**Comment by jalogisch** [comment]
he @katmai 

that is done on purpose and works as it should. You usually want to be able to connect to a node direct by that button. To solve the problem you run into we have the `cluster global api browser` that work with the `http_external_uri`. 

Try this and please close the issue if that solves your problem.

**Comment by katmai** [comment]
got it. thanks!
