### ISSUE TITLE
graylogctl fails to remove pid file

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#889]
```
05:32:31 graylog-1.0.0-beta.2$ GRAYLOG_CONF=graylog.conf ./bin/graylogctl stop
Stopping graylog-server (77047) ...
Waiting for graylog-server to halt.
rm: /tmp/graylog.pid: No such file or directory
graylog-server stopped
```

**Comment by joschi** [comment]
The PID file is removed by Graylog2 when it was shutdown correctly. The removal in the control scripts is just for unclean shutdowns.

* Code ref: https://github.com/Graylog2/graylog2-server/blob/1.0.0-beta.2/graylog2-bootstrap/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java#L139-139

**Comment by kroepke** [comment]
Ah I see!
It was printing an error or warning. Can we silence that? Looks odd.

**Comment by joschi** [comment]
@kroepke Yes. :wink:

**Comment by kroepke** [comment]
Yay! Thanks :)
