### ISSUE TITLE
Allow moving widgets between pages

### ISSUE THREAD

**Issue by ConnerKid** [Graylog2/graylog2-server#8895]
There is no way to move widgets to a specific page in a dashboard, or to copy a widget to a specific page in a dashboard. The only workaround is to duplicate a page and delete the widgets.

## Why?

We are trying to use dashboards/pages as an organizational tool. The dashboard would contain multiple pages with related data but different widgets. For example, we are trying to have a dashboard on a specific customer. Page 1 would be data relating to open orders for that customer, Page 2 would be regarding payment/invoice information. These two pages require different widgets.

Having the dashboard be a 'hub' of sorts for a specific topic is useful while having pages be more tailored to specific widgets/visualizations.

**Comment by dennisoelkers** [comment]
This has been fixed in #8236 and will be part of the next release.
