### ISSUE TITLE
User Creation does not check if the backend returns successfully

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#8912]
When creating a user and a validation does not succeed in the backend the frontend does happily return that everything is fine. Even though no user was created!

**Comment by linuspahl** [comment]
@kmerz While working on https://github.com/Graylog2/graylog2-server/pull/9293 I could not reproduce this behaviour. Are you still able to reproduce the described problem?

**Comment by kmerz** [comment]
Nope I could not either! Close it now. My guess it was fixed with UsersDomain! So good job @linuspahl
