### ISSUE TITLE
Can't add widgets to other than default dashboard tabs

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#8925]
I created a second tab on a dashboard but there is no way to add a widget to it from a search result page. The "Add to Dashboard" button always adds it to the first/default tab and I cannot move it from there to the second tab I created.

* Graylog Version: 3.3.5

**Comment by dennisoelkers** [comment]
Refs #8895.

**Comment by gerdesj** [comment]
I too am a bit frustrated by the lack of what seems to be obvious functionality.  However I don't know how hard it is to implement.

I think the definitions are stored in JSON definitions so it might be quite easy to implement moving things around - between dashboards and dashboard pages.

If it isn't that simple, I'd be happy with an interim clipboard or my local file storage that does an export/import workflow using existing functionality until a better solution is found.

**Comment by dennisoelkers** [comment]
This has been implemented in #8236 and will be part of the next release.

Refs #8152.
