### ISSUE TITLE
New regex conditions

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-server#895]
Right now we can choose any of these condions:
* Always try to extract
* Only attempt extraction if field contains string
* Only attempt extraction if field matches regular expression 

We need this additional condtions to speed up our processing:
* Only attempt extraction if field xyz is present
* Only attempt extraction if field xyz is not present

A typical use case is that we parse our firewall logs, their are two types of formats. So we have two rules like cisco_src_ip and juniper_src_ip. Both rules setup a new field called src_ip. Using the new condition we could ensure that we do not parse for juniper ips if we already got a csico ip.
Futhermore their might be messages which don't belong to any firewall. So we do not need to scan for cisco_src_port if cisco_src_ip is not found.

**Comment by bernd** [comment]
You can use the pipeline processor for this. http://docs.graylog.org/en/2.1/pages/pipelines.html
