### ISSUE TITLE
'Search' tab missing for non-admins

### ISSUE THREAD

**Issue by NiceRath** [Graylog2/graylog2-server#8954]
**'Search' tab missing for non-admins**

## Expected Behavior
Non-admin users seeing the 'Search' tab in their UI.

## Current Behavior
Since the upgrade to version 3.3.x (from 3.2.x) our non-admin users can't see the 'Search' tab.
If the users manually write 'https://graylogserver/search' into their browser -> the search is opening without problems.

I couldn't find any missing privilege or information to this behavior in the release notes.

## Steps to Reproduce (for bugs)
1. Upgrade to 3.3.x
2. Access via non-admin user
3. No 'Search' tab is showing

## Context
Some users like to use this search to find logs if they don't yet know in which stream they are in.

## Your Environment
* Graylog Version: 3.3.4-1
* Java Version: openjdk-11-jre-headless 11.0.7+10-3~deb10u1
* Elasticsearch Version: 6.8.11
* MongoDB Version: 4.2.6
* Operating System: Debian 4.19.98-1
* Browser version: Chrome 85.0.4183.102

**Comment by dennisoelkers** [comment]
Hey @NiceRath, thanks for reporting this. We have fixed this issue in #8917, which will be included in 4.0.

**Comment by NiceRath** [comment]
Hey @dennisoelkers. Thank you for the information.
Have a nice day!
