### ISSUE TITLE
Error to add an extractor to input over api

### ISSUE THREAD

**Issue by keaoner** [Graylog2/graylog2-server#8957]
## Expected Behavior

In the swagger interface of the graylog api I try to push an extractor into an input when I validate I have an error message

### error:
`{
  "type": "ApiError",
  "message": "Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token\n at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@16c98e9b; line: 4, column: 16] (through reference chain: org.graylog2.rest.models.system.inputs.extractors.requests.CreateExtractorRequest[\"converters\"])"
}`

### My json
`{
 "title": "Nombre de document répondant à la question dans le moteur de recherche",
 "extractor_type": "copy_input",
 "converters": [
    {
     "type": "numeric",
     "config": {}
    }
  ],
 "order": 1,
 "cut_or_copy": "copy",
 "source_field": "nbr_de_document_repondant_a_la_recherche",
 "target_field": "nombre_de_document_repondant_a_la_recherche",
 "extractor_config": {},
 "condition_type": "none",
 "condition_value": ""
}`

## Current Behavior
Why this request does not work when the Json is valid and respects the expected format?

## Steps to Reproduce (for bugs)
1. Go to the swagger interface of the API
2. Select "Extractors: Extractors of an input" and "POST / system / inputs / {inputId} / extractors"
3. Copy and paste this json and validate
4. The error message is displayed

## Your Environment
* Graylog Version: AWS AMI 3.2
* Java Version: Openjdk 11
* Operating System: Ubuntu 18
* Browser version: Chrome 84

**Comment by antiphp** [comment]
How did you solve it?

**Comment by antiphp** [comment]
OK I found the issue myself by checking how the request in the UI looks like and it's

```json
converters: { "date": { "date_format": "..." } }
```

Assume not a bug since the whole API has those inconsistencies.

**Comment by danielw1990** [comment]
Same problem here, what UI are you referring too? The best hint I currently have is the API browser which only describes converters as "object".
So I tried removing it. But then it turns out the indicator "optional" does not mean it's optional.

Just having a full documentation on what objects the API actually expects would be immensely helpful. As that does not always line up with what the API puts out, like in this case.

Also foreign key mismatches give the same error as a missing property etc.

**Comment by antiphp** [comment]
The graylog server's UI. If you open the browsers web console (F12?) you can see outgoing request to the API and check their format.

**Comment by danielw1990** [comment]
Ah, interesting, I did not know that the Web UI is just a javascript client that uses the API.
Okay, that helps a lot those requests have to work or the UI wouldn't. 

Thanks.
