### ISSUE TITLE
trusted_proxies only accepts subnets

### ISSUE THREAD

**Issue by oscarlofwenhamn** [Graylog2/graylog2-server#8965]
## Expected Behavior

The [docs](https://docs.graylog.org/en/3.1/pages/configuration/server.conf.html#web-rest-api) states, regarding setting `trusted_proxies`, that 
>Comma separated list of trusted proxies that are allowed to set the client address with X-Forwarded-For header. May be subnets, or hosts.

Adding hosts here should therefore work.

## Current Behavior

Adding hosts to the config causes a `ParameterException` with the following output:
```
com.github.joschi.jadconfig.ParameterException: Couldn't convert value for parameter "trusted_proxies"
	at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:141) ~[graylog.jar:?]
	at com.github.joschi.jadconfig.JadConfig.process(JadConfig.java:99) ~[graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.processConfiguration(CmdLineTool.java:351) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.readConfiguration(CmdLineTool.java:344) [graylog.jar:?]
	at org.graylog2.bootstrap.CmdLineTool.run(CmdLineTool.java:178) [graylog.jar:?]
	at org.graylog2.bootstrap.Main.main(Main.java:50) [graylog.jar:?]
Caused by: com.github.joschi.jadconfig.ParameterException: Invalid subnet: {HOSTNAME}
	at org.graylog2.utilities.IPSubnetConverter.convertFrom(IPSubnetConverter.java:41) ~[graylog.jar:?]
	at org.graylog2.utilities.IPSubnetConverter.convertFrom(IPSubnetConverter.java:31) ~[graylog.jar:?]
	at com.github.joschi.jadconfig.JadConfig.convertStringValue(JadConfig.java:167) ~[graylog.jar:?]
	at com.github.joschi.jadconfig.JadConfig.processClassFields(JadConfig.java:139) ~[graylog.jar:?]
```
This is true for hostnames in the format foo.bar.bleh and foo-bar-bleh alike.

## Possible Solution

I am guessing the issue is that `trusted_proxies` is defined to have the converter `IPSubnetConverter`, meaning anything that isn't a subnet isn't converted properly. 
See: https://github.com/Graylog2/graylog2-server/blob/13c6ca505c13fcdfcaed3b079151941d70603197/graylog2-server/src/main/java/org/graylog2/Configuration.java#L156

This assumption is further strengthened by the fact that `getTrustedProxies` returns a set of IpSubnets:
https://github.com/Graylog2/graylog2-server/blob/13c6ca505c13fcdfcaed3b079151941d70603197/graylog2-server/src/main/java/org/graylog2/Configuration.java#L308-L310

This should be changed to accept hosts as well, or the documentation should be updated to state it only allows subnets (if that is the case and is the desired case forward).

Disclosure: I am using the Graylog Docker image, and as such am adding config to the `graylog.conf` file rather than a `server.conf` file. If this is what makes a difference in this working or not, a new formulation of the issue will be necessary I assume.

**Comment by radykal-com** [comment]
You can set individual hosts with the format ip/32. I think the what you mean is that graylog does not allows hostnames, only IP CIDR notation.

**Comment by oscarlofwenhamn** [comment]
Ah, I misunderstood the functionality, I'll edit the issue. Is there any way to avoid having to specify IPs for similar functionality?
I've deployed the containerized version in a Kubernetes cluster, and it looks like I will be needed to add cluster resources as trusted proxies. Since these have ephemeral IPs, specifying them would be impossible in the long run.

**Comment by radykal-com** [comment]
I'm not 100% sure but I think it's not possible atm. The addresses configured as trusted proxy are just parsed and configured during bootstrap of the graylog servers. To allow a more dynamic environment, graylog would need to resolve the hostnames configured for each request it receives, and that will make graylog response times increase.

If graylog and the trusted proxy containers are running in a private environment (single or multiple k8s clusters) you can try to add the big subnets where all the k8s nodes IPs are in. This is just a workaround and may have some security concerns in case you don't want any container in the cluster to be treated as a trusted proxy, but this way at least any request from outside your cluster won't be trusted

**Comment by oscarlofwenhamn** [comment]
>(...) try to add the big subnets where all the k8s nodes IPs are in (...)
Yeah, that's what I've been testing out as well, possibly there could be some way to designate a subnet for some resources to use which I could then limit to only run the correct ones. 

Are there _any_ other ways to integrate Graylog with an outside source for authentication? I've been looking around for ways to integrate with my OIDC tool (Keycloak, specifically), but this header-based authenticator is the only one I've really found. Do you have any other suggestion, such that I could avoid this problem altogether?

**Comment by radykal-com** [comment]
mmmmh AFAIK https://docs.graylog.org/en/3.3/pages/users_and_roles/external_auth.html#single-sign-on SSO with a custom header can be configured. If you are looking for an OAuth2 authentication... i think it's not possible, it used to be a 3rd party plugin but it seems deprecated now

**Comment by oscarlofwenhamn** [comment]
Ok, thanks for the input, I'll keep experimenting with a custom header and possibly an OIDC-sidecar of some sort (I think that might be the securest way to do it; serve the sidecar on something like `/oidc` and after authentication add the user info to the custom header and redirect back to Graylog. That way, hopefully, only adding localhost as a trusted proxy should be enough. Closing, since the issue is based on a misunderstanding of functionality.

**Comment by k0inwork** [comment]
Could be - just could be - that in some cases (I dont know which) graylog after simple restart wont reread the config. I had to reboot the VM for changes to take effect. And that took me some white hair.
