### ISSUE TITLE
Ability to email alerts for internal Graylog notifications

### ISSUE THREAD

**Issue by jgallucci32** [Graylog2/graylog2-server#8983]
## What?

Graylog generates system notifications usually when there is a critical issue with the Graylog system itself. Some examples include:
* Uncommited messages deleted from journal
* Journal utilization is too high
* Elasticsearch nodes disk usage above flood stage watermark
*  You are running an outdated Graylog version

Currently these notifications only appear if you login to the system and do not have any other method to notify administrators of Graylog. Graylog should have the ability to generate an alert (or direct SMTP message) if there are problems with the system. One suggestion would be to use the built-in All system events stream to configure the alert in a similar manner to regular alerts.

## Why?

If admins do not login to the system every day there is a risk the Graylog system will become critical and fail to collect logs. This can be detrimental to production operations. Email alerts ensure problems with Graylog can be addressed before they become critical.

## Your Environment

* Graylog Version: 3.3.2
* Elasticsearch Version: 6.8.10-1
* MongoDB Version: 4.0.19-1
* Operating System: RHEL 7.8
* Browser version: Chromium Edge

**Comment by mikkolehtisalo** [comment]
Meanwhile you can try running something like this in cron:

https://gist.github.com/mikkolehtisalo/18f6b90418a635c9a3c11c3ff3f6706a

**Comment by ctriegg-mak** [comment]
Maybe a solution would be to write this to the graylog system event index? Then a event rule could be created to generate a notification.

**Comment by nicosalvadore** [comment]
Hi @florianpopp !

Is this a feature the graylog team will work on in the next future ?
The forwarding of these notifications to the graylog **system events** stream is a great idea.
Thanks in advance

**Comment by boosty** [comment]
This was recently implemeted via https://github.com/Graylog2/graylog2-server/pull/13833
