### ISSUE TITLE
GC warning thread should take into account non-pausing collector phases

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#899]
Sometimes, when using ParNew and CMS the warning thread erroneously throws a fit because the non-pausing phases of those collectors take much longer than the warning period.

If possible, use only the stop-world-phases of CMS to compare against the warning threshold. Refer to https://blogs.oracle.com/jonthecollector/entry/hey_joe_phases_of_cms

**Comment by Helix-DB3** [comment]
#12503 #12641 Talking Back what was taken from me. Kill Melissa Jon's Wife or Mother RIGHT?????????Or Wrong. If Im wrong please let me know and I will Apologize. But I will have you know I pulled the SUN(center of galaxy) closer to EARTH. NOT SURE IF IT IS STILL INCHING CLOSER OR IF IT STOPPED.
![shodan io-47 93 5 238](https://user-images.githubusercontent.com/96703991/167966552-de6bfe8a-b5ca-4f30-bb91-213ba338b919.jpeg)
