### ISSUE TITLE
Set Dashboard to be Default Start Page by User

### ISSUE THREAD

**Issue by ChristopherKB** [Graylog2/graylog2-server#9004]
## What?

The customer has users who only use Graylog to monitor dashboards. Starting on that dashboard saves them time and effort and automates a repetitive task.

## Your Environment

* Graylog Version: Current
* Elasticsearch Version: NA
* MongoDB Version: NA
* Operating System: NA	
* Browser version:

**Comment by dennisoelkers** [comment]
Duplicate of #9002.
