### ISSUE TITLE
JSON parsing: add shallow parsing up to a certain path depth

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#9021]
## What?
Add JSON parsing function(s) that support shallow parsing a deeply nested JSON document, returning all the key/value pairs up to a certain depth (optionally starting at a JSONPath expression).
The unparsed portion of the subtree would be returned as a string, instead of being parsed, allowing either storing it verbatim or parsing it in a later stage.

## Why?
When dealing with deeply nested documents, especially from sources like AWS services, the number of unique paths in that document can easily be in the tens of thousands, leading to too many fields in an index.
Most of the time those fields aren't important for searching but need to be displayed later on.
Given the variable nature of these documents, it's often hard to impossible to know all the interesting paths beforehand, so parsing just the first one or two levels of the JSON document helps in navigating it, without catastrophically exploding the number of keys.

Removing the extra keys is often not possible, either, because their names are not known ahead of time, so they cannot be easily removed later on.

## Your Environment

* Graylog Version: 3.3.5

**Comment by boosty** [comment]
Related: #8706

**Comment by pbrzica** [comment]
Is there any ETA on this issue?
Would be great to see this included in Graylog 4.

**Comment by patrickmann** [comment]
Could somebody clarify the expected return value with regard to unparsed content below the depth cut-off?
E.g. given the JSON below, what would be the expected result for depth=2? The resulting JSON tree would include only fields `k0`, `k1`, `k2` and not `k11`, `k21`; but how should the unparsed content be returned? These could be fragments from a bunch of different places within the tree and not particularly useful. 

I suggest we just ignore anything below the cut-off. If there are additional requirements in future, we can always extend the function or provide a new function to address that.

```
{
  "k0": "v0",
  "obj1": {
    "k1": "v1",
    "obj11": {
      "k11": "v11"
    }
  },
  "obj2": {
    "k2": "v2",
    "obj21": {
      "k21": "v21"
    }
  }
}
```

**Comment by boosty** [comment]
Hi @patrickmann, I talked about this with @kroepke and @bernd. We like your proposal of ignore anything below the cut-off 👍

**Comment by boosty** [comment]
Assigned @dulanism for documentation (once this is done)
