### ISSUE TITLE
Allow bulk update when assigning users for roles and teams

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#9029]
Currently the API only supports the assignment of one user in the context of teams and roles. 

We should remove:
- `/teams/<team-id>/member/add/<username>`
- `/authzRoles/<role-id>/assignee/<username>`

and add endpoints which allow adding multiple users (Or change the existing ones).

Adjusting the related "remove" endpoints is not necessary UI wise, but we should adjust them to be consistent.
Here is the related UI issue: https://github.com/Graylog2/graylog2-server/issues/8792.

When working on this we might consider also fixing this: https://github.com/Graylog2/graylog-plugin-enterprise/issues/1712

**Comment by kmerz** [comment]
Fixed with #8792
