### ISSUE TITLE
Status badging of failed/stopped Inputs

### ISSUE THREAD

**Issue by waab76** [Graylog2/graylog2-server#9036]
## Expected Behavior
Generally speaking, when an item on a UI has a red badge, it is in a bad or unexpected state.  Green or blue badging generally indicates a good/expected state and yellow or orange badging indicates less severe bad or unexpected states.

An input that was deliberately stopped by a user should have status badging indicating that it is in an expected state.

An input that was stopped by the system (possibly due to excessive failures) should have status badging indicating that it is in an unexpected/bad state and requires user attention.

## Current Behavior
![Screen Shot 2020-09-24 at 10 48 21 AM](https://user-images.githubusercontent.com/6466251/94161915-2fbf5e00-fe54-11ea-9244-b8faed57fcc7.png)

Currently, when a user manually stops an input, it gets a red status badge with the text "Not Running".  This can be seen on the Syslog UDP input in the attached screenshot.

When the system stops an input (due to excessive failures), it gets a yellow/orange status badge with the text "Stopped".  This can be seen on the O365 input in the attached screenshot.

This gives the impression that the Syslog UDP input is in a bad/unexpected state (which it is not) while the O365 input is a lower priority (which it is not).

## Possible Solution
My preference would be for inputs manually stopped by the user to have a blue status badge with the text "Stopped" or "User Stopped".  This would indicate that it is in an expected state while differentiating it from the green "Running" inputs.

Similarly, inputs automatically stopped by the system should have a red status badge with text like "Not Running" or "System Stopped".  This would indicate that they are in an unexpected state and require user attention.

**Comment by bud1979** [comment]
One thing we need to keep in sync, is what ever color we picked for a disabled input, by the user, we need to keep the same color as for the "alerts" in a disabled state,  currently that is yellow/orange like:

<img width="533" alt="Screen Shot 2020-09-24 at 9 14 14 AM" src="https://user-images.githubusercontent.com/26657656/94164518-5d9da600-fe46-11ea-94bb-cfcbf66bc332.png">
