### ISSUE TITLE
Fixed Header Rows for Search views

### ISSUE THREAD

**Issue by ChristopherKB** [Graylog2/graylog2-server#9037]
## What?

The header row on a search result should remain fixed as the user scrolls down the screen. 

## Why?

The column headings are now lost and it is impossible to tell what a column heading is once you leave the top of the screen. It makes it very difficult to scan through multiple lines during analysis.

## Your Environment

* Graylog Version: All versions
* Elasticsearch Version:NA
* MongoDB Version:NA
* Operating System:NA
* Browser version:NA

**Comment by maxiadlovskii** [comment]
Fixed in [#13466](https://github.com/Graylog2/graylog2-server/pull/13466)
