### ISSUE TITLE
Inconsistent logging with GELF driver

### ISSUE THREAD

**Issue by viktormatrai** [Graylog2/graylog2-server#9046]
Hi!

I've a strange problem. 

Logs are inconsistently sent to stdout when the conatiners log driver is gelf, so those are not appearing in graylog dash either. 

What make it even more strange, that it somedays working, some days not. The service which the logs are coming from is going silent at GMT 0:00 and when it's starts to "speak" again it's the first log after GMT 0:00 just on another day. 

What makes it even more strange 2: when it's in 'silence', it does log except logs are in json format containing keys like level, timestamp, message, tag, etc. (same as are contained by the GELF dictionary)

The service is written in go. Logs are sent through UDP. Container is configured with docker-compose.

Does anybody have an idea for this issue?

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
