### ISSUE TITLE
time format is different in search UI 

### ISSUE THREAD

**Issue by linux0x5c** [Graylog2/graylog2-server#9060]
I have a question. The format of the time field in the nginx log I collected is as follows 2020-09-30T14:11:36+08:00, but I use the extender to extract the time in the following format yyyy-MM-dd, but searching The format displayed in the panel is not the format I want, hover the mouse over the time field, and the floating window shows the correct format. I don’t know why, please help, thank you.

![image](https://user-images.githubusercontent.com/35218713/94659553-0e201400-0337-11eb-80fb-0d8a9631b403.png)

![image](https://user-images.githubusercontent.com/35218713/94659005-36f3d980-0336-11eb-8074-7737524414c7.png)

* Graylog Version: 3.3.5
* Java Version: openjdk version "1.8.0_265"
* Elasticsearch Version: 6.8.5
* MongoDB Version: 3.6
* Operating System:  CentOS Linux release 7.6.1810 (Core)
* Browser version:  Microsoft Edge 85.0.564.63

**Comment by linux0x5c** [comment]
What I am looking forward to looks like below.
![image](https://user-images.githubusercontent.com/35218713/94659358-bc778980-0336-11eb-956a-7598d8f391e2.png)

**Comment by dennisoelkers** [comment]
@linux0x5c: When you are ingesting a date-like string, Elasticsearch will identify it as a timestamp and types the field according to that. So most probably the `time` field in your index is of type `date`. What you can do now is to create a [custom index mapping](https://docs.graylog.org/en/3.3/pages/configuration/elasticsearch.html?highlight=custom%20mapping#custom-index-mappings) that defines the `time` field as being a `keyword`. That would mean though, that you cannot perform date-related queries on that field. More information on date parsing [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html).

**Comment by linux0x5c** [comment]
@dennisoelkers : Tks,Dennis,I will create a custom index mapping to solve it.
