### ISSUE TITLE
Usage of msgpack leaks memory into PermGen

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#907]
Each new `RadioMessageCodec` gets a new `MessagePack` instance via injection. This results in new classes generated for each message that is processed and eventually leads to PermGen exhaustion.

![yk](https://cloud.githubusercontent.com/assets/461/5818527/8556bc2a-a0b6-11e4-9582-970020895e86.png)

**Comment by lennartkoopmann** [comment]
![](http://www.reactiongifs.com/r/yxi.gif)
