### ISSUE TITLE
Reference users by ID

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/graylog2-server#9084]
Most of our code is currently referencing users by name.

The upcoming IdP code will add support to allow renaming of users.
Instead of trying to fix up all references if a user gets renamed, it's a cleaner solution to reference users by ID.

At least for the new grants, roles and teams code, we should reference users by ID instead of the username. In a future version we also want to use references in other code parts as well, but this is out of scope for the 4.0 release.

Tasks:
 - Identify all calls to `UserService.load(<username>)` and check which ones need to be changed to an ID.
 - Change user GRNs to ids. `grn::::user:hans` -> `grn::::user:54e3deadbeefdeadbeef0001`
 - Change existing permissions -> grants migrations
 - Update existing permissions / teams frontend code so it addresses users by ID

**Comment by mpfz0r** [comment]
Fixes #8768

**Comment by bernd** [comment]
Fixed in https://github.com/Graylog2/graylog2-server/pull/9123
