### ISSUE TITLE
pivot number of aggregation values can't be changed

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#9087]
## Expected Behavior
changing the number of items in the aggregation should not blank the results and it needs to be possible to save the number of aggregation numbers. 

## Current Behavior
3.3.6 introduced a bug 

## Steps to Reproduce (for bugs)

1. create top n values 
2. edit the widget (select items 25)

* Graylog Version: 3.3.6

**Comment by chalfling** [comment]
Hello @jalogisch I can't change time range too.

I tried to make a video of theses bugs. This happen on stream's page and dashboards's page.

See video bellow
![screen-capture](https://user-images.githubusercontent.com/9088569/95138884-af490900-0741-11eb-9531-bdb6119b2b15.gif)
