### ISSUE TITLE
Make it possible to share the default message stream in the UI

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#9106]
The default stream is kinda special. That's why we disabled the "More Actions" menu for that stream. This also hides the "Share" button for that stream.

The default message stream should be shareable as well, so we need to find a solution.

![image](https://user-images.githubusercontent.com/461/95333406-09b2a880-08ad-11eb-959f-1f3e611379dd.png)

**Comment by linuspahl** [comment]
I am closing this issue because it gets fixed with https://github.com/Graylog2/graylog2-server/issues/9247
