### ISSUE TITLE
Add telemetry configuration to default config

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#914]
Add all telemetry plugin configuration options to `misc/graylog2.conf`.

**Comment by joschi** [comment]
Should we really? I mean it's still "only" a plugin.

**Comment by bernd** [comment]
As far as I understand, we want as many people to use it as possible. /cc @lennartkoopmann 

If the default config contains the (disabled) config options and a comment with an explanation and maybe a link, users are more likely to find it I guess.
