### ISSUE TITLE
Too many SetIndexReadOnly system jobs scheduled?

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#920]
there's no indication of which index they are for, possibly caused by my incredibly low retention/rotation settings.
need to investigate
![screenshot](https://cloud.githubusercontent.com/assets/52014/5903116/204e67f0-a580-11e4-9735-64814d647c28.png)

**Comment by kroepke** [comment]
maybe not possible to display the index the job is for, if not this is not critical. just go and read the code again to make sure it's not completely broken (which is unlikely, but still)

**Comment by joschi** [comment]
FWIW, I couldn't reproduce the issue with low rotation interval.

**Comment by kroepke** [comment]
possibly this was an artifact of something else, my rotation interval was really short and load was really high.

**Comment by joschi** [comment]
Closed by merging #1054 and Graylog2/graylog2-web-interface#1161
