### ISSUE TITLE
Mail notifications fails with TLS

### ISSUE THREAD

**Issue by BaptisteBdn** [Graylog2/graylog2-server#9207]
## Expected Behavior

Graylog should send a mail when there is an alert.

## Current Behavior

My Graylog-server upgraded from 3.3.7 to 3.3.8 last thursday and I haven't received any mails since.
When I try to execute a **Test Notification** it fails with the following errors : 
```
Email Transport Configuration is missing or invalid! (triggered an hour ago)
The configuration for the email transport subsystem has shown to be missing or invalid. Please check the related section of your Graylog server configuration file. This is the detailed error message: Email transport is not enabled in server configuration file!
```
We've been using the same configuration for over a year now so I don't think the problem is here.
```
An error occurred while trying to send an email! (triggered an hour ago)
The Graylog server encountered an error while trying to send an email. This is the detailed error message: org.apache.commons.mail.EmailException: Sending the email to the following server failed : mail.host.com:port (javax.mail.MessagingException: Could not convert socket to TLS; nested exception is: java.net.SocketTimeoutException: Read timed out)
```
I'm a little troubled here because we haven't changed anything to our mail servers. When I'm trying to send a mail from the Graylog servers it worked. However the changelog for the 3.3.8 is supposed to be only for the Entreprise version..

## Steps to Reproduce (for bugs)

1. Execute Test Notification with TLS activated

## Your Environment

* Graylog Version: 3.3.8-1
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Hey @BaptisteBdn, thanks for reporting this!

There are no code changes between 3.3.7 and 3.3.8, so I am a bit irritated. Did you try rolling back to 3.3.7 to see if it helps? A read time out does indicate to me that it seems to be related to the environment (packet filter?) and not to Graylog itself. Maybe something implicitly changed due to the Graylog restart required for the update?

**Comment by BaptisteBdn** [comment]
Hi, thanks for answering.
 
I've roll backed to 3.3.7 and it stills does not work so it has nothing to do with the update.

> Maybe something implicitly changed due to the Graylog restart required for the update?

I think something must have happened then because I don't know why Graylog thinks the configuration is missing or invalid.
I will close the issue for now and will retry to make it work. However if you have any idea what could be broken feel free to re-open it.

**Comment by dennisoelkers** [comment]
@BaptisteBdn: Thanks a lot for the update!
