### ISSUE TITLE
Clicking on a link of the active authentication service with the id in the link does the page not recognize the service as active 

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#9224]
## Expected Behavior
When clicking on an link leading to an activated service the page of that authentication service should show the synced teams and users.

## Current Behavior
The page does not see the service as activated and there for does not show the synced users and teams.

## Your Environment

* Graylog Version: graylog pre 4.0 beta

**Comment by bernd** [comment]
This has been fixed in 4.0.
