### ISSUE TITLE
Synced teams list on the authentication service details page displays only the ID of related users

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#9239]
The details page for active authentication services contains an overview of all synced teams which also lists the related users. The list of related users currently displays the user ID and not their full name.

## Possible Solution
We need to provide the user names in the response for synced teams, to display them correctly in the UI.

**Comment by linuspahl** [comment]
@mpfz0r @bernd On the teams overview page the request which fetches all teams returns:

```
{
  context: { 
    username_map: {...}
  },
  teams: ...
}
```

Can we implement the same for the request which fetches the synced teams?

**Comment by bernd** [comment]
> @mpfz0r @bernd On the teams overview page the request which fetches all teams returns:
> 
> ```
> {
>   context: { 
>     username_map: {...}
>   },
>   teams: ...
> }
> ```
> 
> Can we implement the same for the request which fetches the synced teams?

@linuspahl Sure :+1:
