### ISSUE TITLE
Explain how to share entities on user edit page.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#9249]
## What?
Previously, sharing entities like dashboards and streams has been part of the user edit page, now it can be done while editing / viewing an entity.

We plan to explain this change on the user edit and details page, by adding an alert above the roles section. The alert should also contain an example of the share button.

**Comment by bernd** [comment]
@linuspahl We might also want to consider adding some kind of "inverted" share dialog to users and teams pages. That way a user with the appropriate permissions can go to a user account or team and create shares for entities that user is an owner of.
