### ISSUE TITLE
UI: Front-end banners do not have a close button (X)

### ISSUE THREAD

**Issue by BlueTeamNinja** [Graylog2/graylog2-server#9251]
Firefox: 82

![image](https://user-images.githubusercontent.com/1891183/96907717-9e9ad180-1469-11eb-81f5-3fbf49c833d4.png)

Reproduction Steps: 

- Generate an error such as saving an invalid pipeline rule
- Error boxes do not fade away and do not have an (X)

Graylog: 4.0b2

**Comment by kyleknighted** [comment]
Thank you for the report @BlueTeamNinja 

> Error boxes do not fade away and do not have an (X)

Could you share what you were doing that lead to a notice that never faded away? 

I am unable to recreate this issue in Firefox. If the notice banner is clicked, it immediately fades away, else it fades away automatically within 7-10 seconds.

**Comment by BlueTeamNinja** [comment]
My apologies.  I think the time delay may have thrown me off.  I will investigate a bit further but I believe that the delay was just longer than I was expecting, so between that, not seeing an [X], and me not intuitively clicking on the banner I thought I was experiencing UI issues.  

In saying that, it did lead to a few awkward moments, like waiting for this to clear up: 

![image](https://user-images.githubusercontent.com/1891183/97310489-aaa3dc00-1839-11eb-9a50-4e4ff9029832.png)

I will update and confirm if the problem persists or just my impatience.
