### ISSUE TITLE
UI: Apply THEN Save & Close on New Processing Rule errors

### ISSUE THREAD

**Issue by BlueTeamNinja** [Graylog2/graylog2-server#9252]
Firefox: 82

![image](https://user-images.githubusercontent.com/1891183/96908279-66e05980-146a-11eb-97b4-9dd0bfda5140.png)

Steps to Reproduce: 

- Create a New, valid Pipeline processing Rule.  
- Click Apply
- Then immediately click Save & Close

**Comment by kyleknighted** [comment]
This bug was introduced in #6351, and I probably moved it around a bit when I redid the Pipeline to have a ContextProvider. Perhaps with a second set of eyes we can get it sorted out. @kmerz Would you have time this week to help me look into this?
