### ISSUE TITLE
Radio configuration overrides message_journal_enabled in code

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#927]
This is a major code smell, because the InputBufferImpl depends on configuration.isMessageJournalEnabled to set  up the correct processing pipeline.
Unfortunately radio shares this code and does the wrong thing if the default setting is true in BaseConfiguration.

Fixing #924 broke this.

**Comment by bernd** [comment]
Closing this now because radio is deprecated and the smelly code will be gone once radio is gone.
