### ISSUE TITLE
InvalidPathException loading blacklist.drl

### ISSUE THREAD

**Issue by ckasek** [Graylog2/graylog2-server#928]
Using 1.0 beta 3, I get this error on startup, trying to run on Windows 7:

ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Error injecting constructor, java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:\C:\dev\graylog-1.0.0-beta.3\graylog.jar!\blacklist.drl

Seems to be the same (or similar) issue that #732 attempted to fix.

**Comment by kroepke** [comment]
There are more issues than just the drools file path on Windows, mostly around file handling in Kafka (which is being used internally for persistence).

I'll try to fix the obvious drools related things, but message_journal_enabled should be set to false on Windows until we identify what can be done about the kafka issues.
