### ISSUE TITLE
Total amount in shared user entities overview response does not change on filter

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#9291]
## Current Behavior
The `total` value in the response for `api/shares/user/username` is not changing when a filter / query is defined.

* Browser version:

**Comment by mpfz0r** [comment]
Refs https://github.com/Graylog2/graylog2-server/pull/8896

If I revert above change, `total` will reflect the filtered, **pagniated** results.

Which then doesn't show the pagination, if more then 10 entries are found.

I'm still not sure when to use `grand_total`
https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/database/PaginatedList.java#L38
