### ISSUE TITLE
NullPointerException in HostInfo.java on Windows7

### ISSUE THREAD

**Issue by ckasek** [Graylog2/graylog2-server#930]
Trying to get 1.0.0-rc.1 running on a windows 7 machine.  During startup, there are NPE's being thrown due to hostInfo command from Mongo not having values for fields that aren't nullable in HostInfo.

I can provide the full stack trace, but this seems to be the relevant bit:
```
Caused by: java.lang.NullPointerException: Null versionString
        at org.graylog2.system.stats.mongo.AutoValue_HostInfo_Extra.<init>(AutoValue_HostInfo_Extra.java:30)
        at org.graylog2.system.stats.mongo.HostInfo$Extra.create(HostInfo.java:143)
        at org.graylog2.system.stats.mongo.MongoProbe.createHostInfo(MongoProbe.java:76)
        at org.graylog2.system.stats.mongo.MongoProbe.<init>(MongoProbe.java:51)
        at org.graylog2.system.stats.mongo.MongoProbe$$FastClassByGuice$$1d626bf1.newInstance(<generated>)
```

This is the output of the hostInfo command in Mongo on my Windows 7 machine:
```
{
        "system" : {
                "currentTime" : ISODate("2015-01-28T18:59:01.464Z"),
                "hostname" : "chkasek-974mnx1",
                "cpuAddrSize" : 64,
                "memSizeMB" : 16266,
                "numCores" : 8,
                "cpuArch" : "x86_64",
                "numaEnabled" : false
        },
        "os" : {
                "type" : "Windows",
                "name" : "Microsoft Windows 7",
                "version" : "6.1 SP1 (build 7601)"
        },
        "extra" : {
                "pageSize" : NumberLong(4096)
        },
        "ok" : 1
}
```

I understand that Windows isn't exactly a supported platform for running the server, but I'm doing my best to try and get it running due to environment restrictions I have.

**Comment by kroepke** [comment]
Thank you for the report!

We are simply lacking the proper testing infrastructure for Windows right now but are of course interested in getting Graylog to work on Windows.

A short term solution for your problems:
Set 
message_journal_enabled = false
disable_sigar = true

in your graylog2.conf.
That should fix the errors you've describe.
I'll leave this bug report open so we can address the underlying issue.
