### ISSUE TITLE
Dark theme switches to white theme when opening new tabs in rapid order

### ISSUE THREAD

**Issue by lennartkoopmann** [Graylog2/graylog2-server#9301]
When opening new tabs in rapid order, some of the new tabs will switch back to the light theme even when I'm on the dark theme. I can reproduce this but others can't, making be believe this might be latency related because my setup runs over the internet, a few thousand miles away.

![Peek 2020-10-26 14-23](https://user-images.githubusercontent.com/35022/97491340-02bd0a00-1930-11eb-80bf-b1d755d85c4d.gif)

## Your Environment

* Graylog Version: 4.0.0-beta.2
* Mozilla Firefox for Ubuntu 82.0 (64-bit)

**Comment by kyleknighted** [comment]
Spoke with @lennartkoopmann and no longer appears to be an issue.
