### ISSUE TITLE
Journal reader will stall when segment is truncated

### ISSUE THREAD

**Issue by thll** [Graylog2/graylog2-server#9305]
## Expected Behavior

If a journal segment is truncated in a way that it abruptly ends in the middle of an entry, the journal reader should skip the broken entry and continue reading at the start of the next journal segment.

## Current Behavior

When reaching the end of the first segment, the journal reader will silently stop reading indefinitely. This leads to the journal filling up but no more messages being processed.

## Possible Solution

When the journal reader attempts to read a truncated entry, the Kafka stack will return nothing. Currently we are treating this as if we have reached the end of the journal. We should however check if the journal contains more entries (e.g. in subsequent segments) and increment our read offset until we are able to successfully read entries again.

## Steps to Reproduce (for bugs)

1. Start a Graylog server with an empty journal (delete `data/journal`)
2. Stop elasticsearch
3. Send 100.000 messages, each 2048 bytes, to the server, e.g. using the RAW TCP input
4. Stop the Graylog server
5. Open the first segment of the journal (`data/journal/messagejournal-0/00000000000000000000.log`) in an editor and truncate the last entry
6. Start elasticsearch
7. Start the Graylog server. Notice that it processes some messages (up to and including offset 47342 in my case) but then stops processing altogether.

* Graylog Version: `e231e93f4cf63e54a54850d83b30e7d4609cd619`
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by bernd** [comment]
Reopen because we had to revert due to a race condition.
