### ISSUE TITLE
Duplicate subdirectory in Enterprise Navigation link

### ISSUE THREAD

**Issue by oscarlofwenhamn** [Graylog2/graylog2-server#9308]
## Expected Behavior

When running Graylog in a subdirectory like `www.example.com/graylog`, with the webserver settings detailed in the docs, internal links should work.

## Current Behavior

For non-enterprise version, in v 3.3.7, when clicking the Enterprise link in the Navigation menu links to `www.example.com/graylog/graylog/system/enterprise`.

## Possible Solution

Not sure, maybe since the Enterprise link is pushed in Navigation.jsx and should be getting a correct NavigationLink (where duplicate prefixes should be fixed? #5703), maybe the duplication fix is mainly working for links in the System dropdown and the Enterprise link-implementation needs to be fixed?
https://github.com/Graylog2/graylog2-server/blob/e231e93f4cf63e54a54850d83b30e7d4609cd619/graylog2-web-interface/src/components/navigation/Navigation.jsx#L78-L84,
* Graylog Version: 3.3.7

**Comment by dennisoelkers** [comment]
Closing due to being outdated. Please reopen if this is still an issue for you!
