### ISSUE TITLE
Searches Do Not Display After Daylight Savings Time

### ISSUE THREAD

**Issue by ldod-lle** [Graylog2/graylog2-server#9331]
No messages being displayed in Search dialog after DST cutover on 1 Nov. 
## Expected Behavior

Search results display.
## Current Behavior

No search results display, though there is activity in the indices. 
## Possible Solution

Unknown
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

Cannot search active events. 
## Your Environment

* Graylog Version:3.3.8
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System: RHEL 7.9
* Browser version: Firefox 82.

**Comment by dennisoelkers** [comment]
Hey @ldod-lle,

thanks for getting in touch. We need some more information about your issue. 

1. Can you see if messages continue to be indexed? You can check if your indices are growing on your `System` -> `Indices` page.
2. Do you see any errors in your server log?

**Comment by ldod-lle** [comment]
Thanks for the quick response - I was able to confirm that the indices are still running, and I see no errors with the graylog server itself. I am able to see messages in the past still, but they stopped at 0500 on 1 Nov.

**Comment by ldod-lle** [comment]
PS: Is there a data cap in the free version?

**Comment by HenryTheSir** [comment]
No, there is no limit in the free version. 

Looks like your Cluster is/was in flood stage. What does your Elasticsearch Log logs and what does the IN/OUT Metric in the top right corner display (its cropped in your image)?

**Comment by ldod-lle** [comment]
flow_mgr.flows_removed                        | Total                     | 25
flow_mgr.rows_checked                         | Total                     | 65536
flow_mgr.rows_skipped                         | Total                     | 65448
flow_mgr.rows_empty                           | Total                     | 24
flow_mgr.rows_maxlen                          | Total                     | 2
tcp.memuse                                    | Total                     | 2293760
tcp.reassembly_memuse                         | Total                     | 1481100
dns.memuse                                    | Total                     | 9568
http.memuse                                   | Total                     | 119740
flow.memuse                                   | Total                     | 7478720

The meter right now is indicating 0/0. I shutdown one of the major log producers in the interim.

**Comment by ldod-lle** [comment]
Additional info - my Process/Output buffers are 100%. I take that this is bad.  :/

**Comment by ldod-lle** [comment]
I guess at this point if someone can tell me how to reset the entire instance, I'd like to do that - this is just an experimental VM.

**Comment by HenryTheSir** [comment]
Elasticsearch Log ?

**Comment by ldod-lle** [comment]
We can close this, going to burn down the VM and start over. Not really sure what happened other than the 1M backlogged messages had something to do with it. I'll be more careful pruning my inputs.
