### ISSUE TITLE
No email recipient(s) while configuring alerts

### ISSUE THREAD

**Issue by offlinejke** [Graylog2/graylog2-server#9343]
I'm using graylog-server in docker. After configuring smtp for alert notifications, i can not add any recipients. "No options" while click on the field "Email recipient(s)", and i can not enter any email by my own.

Version: 3.3.7+924e45c, codename Sloth Rocket
JVM: PID 18, Oracle Corporation 1.8.0_265 on Linux 4.9.0-12-amd64

root_email = "email@domain.com"
transport_email_enabled = true
transport_email_hostname =  smtp.eu.mailgun.org
transport_email_port = 587
transport_email_use_auth = true
transport_email_auth_username = name@domain.com
transport_email_auth_password = xxxxxxxxxxxxxxxxxxx-xxxxxxxxxxxx
transport_email_subject_prefix = [graylog]
transport_email_from_email = sender@domain.com
transport_email_use_tls = true
transport_email_use_ssl = true

**Comment by bernd** [comment]
@offlinejke You can just enter one or more email addresses in the "Email recipient(s)" form by clicking into the form, type the email address and press enter or click the "Create ..." message.

![Peek 2020-11-09 15-52](https://user-images.githubusercontent.com/461/98556768-b369c880-22a3-11eb-96e7-b19a9f365505.gif)
