### ISSUE TITLE
 ｢wdm｣: Error: ENOENT: no such file or directory, open 'E:\dz\study\zs\graylog2-server-master\graylog2-web-interface\manifests\vendor-manifest.json'

### ISSUE THREAD

**Issue by zhansang** [Graylog2/graylog2-server#9351]
when i run yarn start 
then the wrong info:
 ｢wdm｣: Error: ENOENT: no such file or directory, open 'E:\dz\study\zs\graylog2-server-master\graylog2-web-interface\manifests\vendor-manifest.json'

should i do any else  please help  thans

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Hey @zhansang,

please run `yarn build` once before, that should fix it.

**Comment by zhansang** [comment]
i use version 3.3.0

**Comment by zhansang** [comment]
$ disable_plugins=true webpack --config webpack.bundled.js
'disable_plugins' 不是内部或外部命令，也不是可运行的程序
或批处理文件。  the wrong info

**Comment by dennisoelkers** [comment]
This was fixed in #8487, which is currently in master only. You can try to cherry-pick 02a83d0d743d1be9543f807348c2a5e796bc317e into your `3.3` branch.

**Comment by zhansang** [comment]
when i  yarn build  

ERROR in ./node_modules/graylog-web-plugin/plugin.js
Module not found: Error: Can't resolve './lib/PluginManifest' in 'E:\vue_project\graylog2-server-3.3.0\graylog2-web-interface\node_modules\graylog-web-plugin'
 @ ./node_modules/graylog-web-plugin/plugin.js 2:18-49
 @ ./src/index.jsx
 @ multi webpack-hot-middleware/client?reload=true ./src

ERROR in ./node_modules/graylog-web-plugin/plugin.js
Module not found: Error: Can't resolve './lib/PluginStore' in 'E:\vue_project\graylog2-server-3.3.0\graylog2-web-interface\node_modules\graylog-web-plugin'
 @ ./node_modules/graylog-web-plugin/plugin.js 3:15-43
 @ ./src/index.jsx
 @ multi webpack-hot-middleware/client?reload=true ./src
