### ISSUE TITLE
how to remove the login page

### ISSUE THREAD

**Issue by zhansang** [Graylog2/graylog2-server#9362]
## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by zhansang** [comment]
Remove login page   so can  i  modify login permission verification

**Comment by dennisoelkers** [comment]
@zhansang: We do not support removing the login page right now. What is the high-level problem you want to solve?

**Comment by zhansang** [comment]
the graylog in   my website  by  iframe , so when i want to browse graylog  i need to login first .  so  can  i   browse gralog without login

**Comment by bernd** [comment]
Graylog always requires a login to access the data. We don't have any plans to remove this in the future. Sorry.
