### ISSUE TITLE
Build error on Windows

### ISSUE THREAD

**Issue by zhansang** [Graylog2/graylog2-server#9363]
ERROR in ./node_modules/graylog-web-plugin/plugin.js
Module not found: Error: Can't resolve './lib/PluginManifest' in 'E:\vue_project\graylog2-server-3.3.0\graylog2-web-interface\node_modules\graylog-web-plugin'
 @ ./node_modules/graylog-web-plugin/plugin.js 2:18-49
 @ ./src/index.jsx
 @ multi webpack-hot-middleware/client?reload=true ./src

ERROR in ./node_modules/graylog-web-plugin/plugin.js
Module not found: Error: Can't resolve './lib/PluginStore' in 'E:\vue_project\graylog2-server-3.3.0\graylog2-web-interface\node_modules\graylog-web-plugin'
 @ ./node_modules/graylog-web-plugin/plugin.js 3:15-43
 @ ./src/index.jsx
 @ multi webpack-hot-middleware/client?reload=true ./src

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
