### ISSUE TITLE
Error - the server returned: 400 - cannot POST http://172.16.104.110:9800/api/system/sessions (400)

### ISSUE THREAD

**Issue by zhansang** [Graylog2/graylog2-server#9364]
when i login 
Error - the server returned: 400 - cannot POST http://172.16.104.110:9800/api/system/sessions (400)
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
Hey @zhansang,

do you see anything in your browser's console or your  Graylog server log?

**Comment by kong-kyle** [comment]
> 嘿@zhansang，
> 
> 您在浏览器的控制台或 Graylog 服务器日志中看到任何内容吗？

Print log createRequest is null, sometimes it can be obtained and sometimes it cannot

**Comment by kong-kyle** [comment]
> 嘿@dennisoelkers，
> 
> 勇气浏览器的控制台或 Graylog 服务器日志中看到任何内容？

Start service call /api/system/sessions, sometimes 200, sometimes 400, see log 400 when createRequest is null, but restart several times can be successful
