### ISSUE TITLE
multiple grok patterns with the same name can be created

### ISSUE THREAD

**Issue by cmock** [Graylog2/graylog2-server#937]
Running 1.0.0-8.rc.1from the Debian packages.

It is possible to create multiple grok patterns with the same name, both via the "create pattern" dialog and by importing from file (both by importing the same file twice, and by having multple patterns with the same name in a single file).

What should happen:

* When using the "create pattern" dialog, it should be impossible to save a pattern with an already-existing name.

* When importing a file, some sort of conflict resolution would be needed. This could be on a per-file level: if the newly imported file contains names that are already present, the user should have the choice to:
  * cancel processing of that file
  * overwrite existing patterns

  This would cover my usecase of keeping grok patterns in files, editing them there and importing them. Other usecases may be better served by a conflict resolution on a per-pattern basis.

**Comment by kroepke** [comment]
easiest solution is to do two things:

1) validate individual patterns in the client (js code) when editing
2) add "replace all patterns" checkbox to bulk import to allow overwriting all existing patterns, such as when uploading patterns from authoritative source

**Comment by Svolentin** [comment]
Patterns can be added multiple times via Apply content button:
![screen shot 2017-04-05 at 16 11 24](https://cloud.githubusercontent.com/assets/325606/24706992/90f16dd4-1a1a-11e7-9c9c-5152bac29123.png)
Graylog server 2.2.3

**Comment by jalogisch** [comment]
@Svolentin 

please do not highjack old long closed issue with something new.

If you are facing some issue, please open a new one.
