### ISSUE TITLE
Empty Dashboard with great Time Range(Two Weeks)

### ISSUE THREAD

**Issue by chalfling** [Graylog2/graylog2-server#9371]
Hello!

I created a Dashboard with some widgets with time range keyword like:
two week ago to past week
or
last week

I created “Single Number” widget also “Table” widgets.

More de 95% at time that I open this Dashboard I can’t see any data it’s all empty, then I retry some times until data showed. I think this has something about elasticsearch query timeout.

Is it possible to change Elasticsearch query timeout? Where can I change it?

Same problem in Stream’s page when searching a relative time range of last 14 days or 7 days. I think I’m reaching a timeout because is a huge volume of data.

## Your Environment

* Graylog Version: 3.3.8
* Java Version: 1.8
* Elasticsearch Version: 6.8.7
* MongoDB Version: 4.2
* Operating System: FreeBSD 12.1

**Comment by dennisoelkers** [comment]
Hey @chalfling!

Thanks for getting in touch. Do you see any errors in your browser's console or your Graylog server logs?

**Comment by chalfling** [comment]
Hi @dennisoelkers!

I see no log errors on Graylog Server.

From Browser's Console I cleaned cache and run as fresh then on first loading on Dashboard I got something like this:
DevTools failed to load SourceMap: Could not load content for http://example.com:9000/assets/plugin/org.graylog.aws.AWSPlugin/plugin.org.graylog.aws.AWSPlugin.f2cd3046f5d8c08ce593.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://example.com:9000/assets/app.4678e54c30f1075e4dd8.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://example.com:9000/assets/LoadingPage.4678e54c30f1075e4dd8.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://example.com:9000/assets/LoggedInPage.4678e54c30f1075e4dd8.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://example.com:9000/assets/ExtendedSearchPage.4678e54c30f1075e4dd8.js.map: Load canceled due to load timeout
DevTools failed to load SourceMap: Could not load content for http://example.com:9000/assets/vendors~ExtendedSearchPage.4678e54c30f1075e4dd8.js.map: Load canceled due to load timeout

But tried to refresh page several times and no console messages.

I looked into Browser's Network and saw that "execute" file took some time to run then returns a 201 code. I looked into reponse JSON and can see several data and values from my tables, but all tables in the page is blank.

On response JSON I can see data like:
![Screenshot_20201105_115500](https://user-images.githubusercontent.com/9088569/98256789-be4bf280-1f5d-11eb-9b4e-f1d92a83c651.png)
Then I can see on Response's JSON that I have 100 rows on my table with all data and values, but this doesn't show on tables in the Graylog Dashboard.

Last week when I refresh page nearly a 100 times then in ONE time I got the results on Dashboard's page, now this week I upgraded from 3.3.7 to 3.3.8 and now refreshing page 100 times not work, but I can think the upgrade was not the problem.

Has anything more that I need to test?

Thank you!

**Comment by dennisoelkers** [comment]
Is the issue occuring with every dashboard or only this specific one?

**Comment by chalfling** [comment]
> Is the issue occuring with every dashboard or only this specific one?

Yes only this Dashboard, even if i override all time range to "last day" or "last hour". I got response JSON but all widgets are blank(tables) or N/A(single number).

**Comment by chalfling** [comment]
If I reduce the number of pivot fields of a three fields table from default(15 values each) to something like 3 values each(so the number of rows will be fewer) then all tables and other widgets shows it's data.

**Comment by chalfling** [comment]
When I updated to 4.0.0 it's got better! Now only one TAB from Dashboard is empty, other 3 TABs has values =)

**Comment by chalfling** [comment]
On 4.0.1 I didn't have this issue
