### ISSUE TITLE
Explain reason why an unsaved search cannot be shared

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#9382]
An unsaved search cannot be shared and we grey out the button. There is no explanation _why_ it cannot be shared.

![image](https://user-images.githubusercontent.com/461/98343287-e39a3880-2011-11eb-8ff6-cc955117d888.png)

It would be nice if we can add a small hover or popover like we do for share buttons when a non-owner tries to share something.

**Comment by linuspahl** [comment]
Fixed with https://github.com/Graylog2/graylog2-server/pull/9383
