### ISSUE TITLE
Problem starting Graylog2 after upgrading

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#940]
I've upgraded the Graylog2 Server to the 1.0 RC1 version.

After doing this, the GS Server is not starting (or taking a veeeery long time to start).

The last messages (in debug mode) are the following: 

2015-02-03 20:13:24,642 INFO : org.graylog2.bindings.providers.RulesEngineProvider - No static rules file loaded.
2015-02-03 20:13:25,444 INFO : org.graylog2.buffers.OutputBuffer - Initialized OutputBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
2015-02-03 20:13:26,077 DEBUG: org.graylog2.streams.StreamRouter - Not updating router engine, streams did not change (fingerprint=10e3476e6b141f669b388fcba1100e8bb711285e)
2015-02-03 20:13:26,403 DEBUG: org.graylog2.streams.StreamRouter - Not updating router engine, streams did not change (fingerprint=10e3476e6b141f669b388fcba1100e8bb711285e)

This last message (Not updating router engine) repeats a lot of times (as it was on infinite loop), and the server doesn't open the HTTP port and starts serving requests.

I've 121 streams and 296 stream rules, and dumping the TCP packets I can see traffic between the Server and  MongoDB, specially on those 2 schemas.

This occurs with servers on master and non-master mode.

Thanks in advice.

**Comment by rikatz** [comment]
Aditional information:

Just took the measurement of time to start the Server:

2015-02-03 22:21:27,514 INFO : org.graylog2.bindings.providers.RulesEngineProvider - No static rules file loaded.
**2015-02-03 22:21:29,172** INFO : org.graylog2.buffers.OutputBuffer - Initialized OutputBuffer with ring size <65536> and wait strategy <BlockingWaitStrategy>.
**2015-02-03 22:39:33,958** INFO : org.graylog2.bootstrap.ServerBootstrap - Graylog2 server 1.0.0-rc.1 (56f861f) starting up. (JRE: Oracle Corporation 1.8.0_25 on Linux 2.6.32-431.5.1.el6.x86_64)
2015-02-03 22:39:34,013 INFO : org.graylog2.shared.initializers.PeriodicalsService - Starting 16 periodicals ...

Thinking about let this in Debug to see what is Graylog Server doing between those two actions. But still have this problem.

Another test I've done: Renaming on MongoDB the streams and streamrules 'tables' (I don't know how this is called on MongoDB). After doing this the Graylog Server starts instantly, so I really think there is an issue between the Graylog Server and those tables on MongoDB, when they're big.

**Comment by rikatz** [comment]
And more things:

When trying to start all the three nodes at same time (1 master and 2 slaves), something strange happens:

2015-02-03 22:55:32,278 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Error injecting constructor, java.lang.IllegalStateException: The pool is closed
2015-02-03 22:55:32,278 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Error in custom provider, java.lang.NullPointerException
2015-02-03 22:55:32,278 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error: Error injecting constructor, com.mongodb.MongoException: **not authorized for query on graylog2.streams**
2015-02-03 22:55:32,279 ERROR: org.graylog2.bootstrap.commands.Server -

################################################################################

ERROR: Unable to connect to MongoDB. Is it running and the configuration correct?

So, probably something happening with this startup routine :(

**Comment by rikatz** [comment]
More information: on mongod.log (of the master server):

Tue Feb  3 23:34:40.324 [conn697531] query graylog2.streamrules query: { stream_id: ObjectId('53ac34400cf24e6cd03add0e') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 locks(micros) r:101968 nreturned:3 reslen:319 101ms
Tue Feb  3 23:34:40.326 [conn697523] query graylog2.streamrules query: { stream_id: ObjectId('5436f414c130c9065a58d039') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 locks(micros) r:117476 nreturned:3 reslen:332 119ms
Tue Feb  3 23:34:40.326 [conn697533] query graylog2.streamrules query: { stream_id: ObjectId('53fb30300cf2ce7ad46e63a1') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 locks(micros) r:105313 nreturned:2 reslen:219 105ms
Tue Feb  3 23:34:40.326 [conn697540] query graylog2.streamrules query: { stream_id: ObjectId('53bea1600cf2fbb63f53fa7d') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 locks(micros) r:133021 nreturned:2 reslen:219 133ms
Tue Feb  3 23:34:40.327 [conn697530] query graylog2.streamrules query: { stream_id: ObjectId('5469ff8ac13094dcff80a7b0') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 1 locks(micros) r:195677 nreturned:2 reslen:219 102ms
Tue Feb  3 23:34:40.341 [conn697536] query graylog2.streamrules query: { stream_id: ObjectId('5436f2d3c130c9065a58cef6') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 2 locks(micros) r:191072 nreturned:3 reslen:332 106ms
Tue Feb  3 23:34:40.341 [conn697541] query graylog2.streamrules query: { stream_id: ObjectId('5452af4ec1302f7fd123d38d') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 2 locks(micros) r:187223 nreturned:3 reslen:320 104ms
Tue Feb  3 23:34:40.341 [conn697553] query graylog2.streamrules query: { stream_id: ObjectId('53f4a9b90cf27310bead79af') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 2 locks(micros) r:190949 nreturned:2 reslen:219 107ms
Tue Feb  3 23:34:40.343 [conn697539] query graylog2.streamrules query: { stream_id: ObjectId('53bea1600cf2fbb63f53fa7d') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 2 locks(micros) r:189493 nreturned:2 reslen:219 105ms
Tue Feb  3 23:34:40.344 [conn697529] query graylog2.streamrules query: { stream_id: ObjectId('54bfaae70cf2c68ae04e9ad4') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 2 locks(micros) r:191656 nreturned:3 reslen:316 107ms
Tue Feb  3 23:34:50.199 [conn697516] query graylog2.streamrules query: { stream_id: ObjectId('54c3f5540cf2ef1457a56087') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 1 locks(micros) r:231073 nreturned:3 reslen:315 115ms
Tue Feb  3 23:34:50.204 [conn697564] query graylog2.streamrules query: { stream_id: ObjectId('543d8c7dc130c9065a6f9703') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 2 locks(micros) r:318261 nreturned:3 reslen:324 159ms
Tue Feb  3 23:34:50.204 [conn697513] query graylog2.streamrules query: { stream_id: ObjectId('543d3c200cf2a9f71a0d3fdb') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 2 locks(micros) r:239631 nreturned:2 reslen:220 121ms
Tue Feb  3 23:34:50.224 [conn697560] query graylog2.streamrules query: { stream_id: ObjectId('53908c490cf2610fe6e96fce') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 locks(micros) r:169353 nreturned:2 reslen:220 169ms
Tue Feb  3 23:34:50.224 [conn697572] query graylog2.streamrules query: { stream_id: ObjectId('53ce9dc50cf29a216850afb1') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 1 locks(micros) r:350007 nreturned:3 reslen:322 181ms
Tue Feb  3 23:34:50.259 [conn697540] query graylog2.streamrules query: { stream_id: ObjectId('54bfb5010cf259de11834952') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 2 locks(micros) r:215372 nreturned:3 reslen:320 152ms
Tue Feb  3 23:34:50.231 [conn697555] query graylog2.streamrules query: { stream_id: ObjectId('54be8ad20cf2e856ff74ba0c') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 1 locks(micros) r:328948 nreturned:3 reslen:316 166ms
Tue Feb  3 23:34:50.232 [conn697563] query graylog2.streamrules query: { stream_id: ObjectId('5409fe500cf2b598f31f5980') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 locks(micros) r:103537 nreturned:2 reslen:215 103ms
Tue Feb  3 23:34:50.265 [conn697556] query graylog2.streamrules query: { stream_id: ObjectId('54417e9b0cf2dd67628cdabc') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 locks(micros) r:172275 nreturned:2 reslen:220 172ms
Tue Feb  3 23:34:50.289 [conn697545] query graylog2.streamrules query: { stream_id: ObjectId('53d90ac30cf2cf88a2b52170') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 locks(micros) r:219213 nreturned:2 reslen:219 219ms
Tue Feb  3 23:34:50.294 [conn697553] query graylog2.streamrules query: { stream_id: ObjectId('533b0b2a0cf2cf143ffd567e') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 1 locks(micros) r:471306 nreturned:2 reslen:220 238ms
Tue Feb  3 23:34:50.297 [conn697511] query graylog2.streamrules query: { stream_id: ObjectId('538e25a20cf2c26a4f0f019f') } ntoreturn:0 ntoskip:0 nscanned:296 keyUpdates:0 numYields: 1 locks(micros) r:226693 nreturned:2 reslen:220 117ms
 

A lot of times :)

**Comment by bernd** [comment]
Thanks for the report. What is the value of `processbuffer_processors` in your Graylog server config?

And are you able to provide us with a dump of your `streams` and `streamrules` MongoDB collection? (bernd[at]graylog.com)

**Comment by rikatz** [comment]
Bernd sure.

My value is pretty high (joschi just complained about this), it's 1000. Got this value while trying to debug why my server didn't archieve more than 2k msgs/s (now, when it starts gets something like 8k msgs/s without problem...)

Sent to your email the collections :) If there is any problem can use IRC also to send this :)

Thank you very much :)

**Comment by bernd** [comment]
Yeah, a value of 1000 basically means you have 1000 threads that are asking MongoDB for the streams and streamrules every second. :smiley:

The value of `inputbuffer_processors` + `processbuffer_processors` should not be bigger than the number of CPU cores in your machine.

Can you please try with a lower value and see if you still have problems? Thanks!

**Comment by rikatz** [comment]
Sure, going to work I'll see this.

Thus, what are the recomendations to calculate the inputbuffer and the processbuffer values (including the CPU cores value)? Just trying to achieve the right value to the size of my company :) Any other recomendation to get those values?

Thanks!!

**Comment by bernd** [comment]
We are working on a tuning guide for these values.

As said earlier, it depends on the number of CPU cores in your machine. The default value of `processbuffer_processors` is `5`. Maybe play with that one to find the sweet spot. There is one CPU-bound thread started for each processor so you do not want to have more of those than you have CPU cores.
 I would leave the `inputbuffer_processors` value at the default of `2` for starters.

**Comment by rikatz** [comment]
@bernd  ,  ok, so it worked. I've 16 cores, 2 allocated to inputbuffer, and 14 to processbuffer. Now I'm going to monitor the performance of this new version, and if something else happens I'll report another issue.

I'm closing this issue, thank you very much for your help.

**Comment by bernd** [comment]
Great to hear and thanks for the update! :smiley:
