### ISSUE TITLE
Ambiguous UI in stream/dashboard selection

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/graylog2-server#9401]
When user sees the UI component

![image](https://user-images.githubusercontent.com/7376695/98511156-007e7800-226d-11eb-9da2-6c8dd6d0dc2d.png)

it's hard to tell if one should tap also the selections from the left of the items besides the read/edit selection from the right. Does the save button handle all the selections no matter the selection on the left? What extra value does the left side selection produce? Are there mass operations we can do?

I am all for reusing UI components but in this case the result is confusing when the UI has unnecessary extra elements. This probably should be reworked.

**Comment by bernd** [comment]
This is no longer an issue with the new permissions system in 4.0. Please open a new issue if you still see problems. Thank you!
