### ISSUE TITLE
Custom Graphics Not Displaying on T

### ISSUE THREAD

**Issue by ChristopherKB** [Graylog2/graylog2-server#9418]
When trying to define custom graphics for reporting, nothing shows in final report, despite UI allowing the upload of the graphics file and the display of the graphic in the previews. File is under the stated limit and in a supported file format. Behavior happens with either png or jpg files. Attached one custome PNG file as example.
## Expected Behavior

Logo files should display on the final generated PDF report.

## Current Behavior

Logo files do not display on the final generated PDF report.
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
[
![EOLAS](https://user-images.githubusercontent.com/30323202/98593703-2ae62a80-2299-11eb-81e4-c01c83bd6678.png)
](url)
## Your Environment

* Graylog Version:
* Java Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by dennisoelkers** [comment]
This if fixed already for `4.0` and `3.3` and will be part of the next releases.
