### ISSUE TITLE
Import extractors returns NPE

### ISSUE THREAD

**Issue by edmundoa** [Graylog2/graylog2-server#942]
Using 1.0.0-rc.2, importing extractors may fail with a NPE.

**Comment by bernd** [comment]
I was able to import the apache and heroku extractors from graylog.org, but the clavister one did not work. It seems to have a broken `converters` section. (3 with empty `{}` and one with a broken `date` type config)

Nevertheless, our code should somehow handle this or at least provide a better error message.

Tested with 1.0.0-rc.2.

**Comment by edmundoa** [comment]
Fixed with changes in PRs #960 and Graylog2/graylog2-web-interface#1115.
