### ISSUE TITLE
Get back Statistics existed before 3.2

### ISSUE THREAD

**Issue by zoulja** [Graylog2/graylog2-server#9432]
In 3.1 we had a very useful Statistics function.
I click Statistics on response_time field - and I see very simple and clear table with Min/Max/Average/etc values.
So I can understand whole picture in a few seconds.
Now we have some pale shadow of that powerful and really user friendly function.
Please get it back

**Comment by dennisoelkers** [comment]
@zoulja: Could you please add a bit of context about the issues you are having with the current statistics function?

**Comment by zoulja** [comment]
Could you please take a look at current implementation and compare it with the previous one
https://docs.graylog.org/en/3.1/pages/queries.html?highlight=Statistics#analysis ?

I think the issue is self-explanatory, I just can't get understanding of response_time (as example) range and deviations, as it was possible before just in 2 clicks

**Comment by dennisoelkers** [comment]
Hey @zoulja,

we are trying to incorporate user feedback into our planning, but we do rely on proper and precise feedback. It is hard to extract actionable insights from very vague statements. Please list exactly what your issues are, otherwise I have to close this issue as it is not helping anyone.

**Comment by zoulja** [comment]
Dear @dennisoelkers 
The issues are: new Statistics misses Mean,Minumin,Maximum,Std.Deviation,Variance,Sum,Cardinality values, existed before 3.2
These values are widely used during analysis to estimate response time abnormity in the selected period.
Probably you can created more detailed pre-defined template to mimic previous implementation

**Comment by dennisoelkers** [comment]
@zoulja, this is what I get when I use the `Statistics` function on a numeric field:

![image](https://user-images.githubusercontent.com/41929/98924255-e941c380-24d4-11eb-89ee-732a73c7e1b7.png)

In which way is this missing the values you listed?

**Comment by zoulja** [comment]
Ah, I got it now. Most probably before my data was mixed(string+float) so I saw irrelevant statistics page.
My bad, thanks a lot for clarification, @dennisoelkers 

Probably it would be better to describe this screen in documentation as it was in 3.1 documentation?

**Comment by dennisoelkers** [comment]
Hey @zoulja,

you are welcome. We are now showing the type of the field in the actions dropdown as well, so it is always good to check if the type is what you would expect. You are right regarding the documentation. I will create an issue so we work on improving the docs regarding this!
