### ISSUE TITLE
Play-Button for Events

### ISSUE THREAD

**Issue by ihe-nu** [Graylog2/graylog2-server#9438]
## What?
I'd like to have a Play-Button for Events and Alerts as it exists for the dashboards.

## Why?
It would speed up my investigations a lot. At the moment I'm copy&paste everything together from start or use one predefined view.

## Details
Every Event has a few values in its definition:
* Stream(s)
* Search query
* time (time to rescan + time to consider) 
* optional: group by some field name

If I hit the play-button next to the event I'd like to have a stream-view with those properties already in place. If there is a value in "group by", I'd like to have the box from "Show top values" for that field as well.

## Your Environment

* Graylog Version: 3.3.8

**Comment by jalogisch** [comment]
[Z#844276]

**Comment by ihe-nu** [comment]
Also with Graylog 4.0.5 this is still very high on my whish-list. :smile:
