### ISSUE TITLE
Make startpage restable for User

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#9443]
## Expected Behavior
A user must be able to reset the startpage. So he can reach the graylog default startpage (Search without streams).

## Current Behavior
We miss a reset button and a once choosen stream as startpage cannot be made undone.

## Possible Solution
- `4.1` Make a input field in the settings section of a user with a reset button
- `4.0` Add a reset button to the header of the User Pages

**Comment by bernd** [comment]
The 4.0 fix got merged, moving this issue to milestone 4.1.0.

**Comment by linuspahl** [comment]
Got closed with https://github.com/Graylog2/graylog2-server/pull/9448
