### ISSUE TITLE
Text formatting and styling issues

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#9447]
## Description

I collected a few styling and formatting issues that I noticed in the product.

### Lookup Data Adapter Details

![image](https://user-images.githubusercontent.com/461/98813491-885ab280-2424-11eb-91d7-44deccbe7036.png)

### System / Indices

![image](https://user-images.githubusercontent.com/461/98817184-0b323c00-242a-11eb-8d5c-52bc90d245da.png)

### Node Overview

![image](https://user-images.githubusercontent.com/461/98817581-96133680-242a-11eb-98dc-34876b09de3c.png)

### Node Metrics

![image](https://user-images.githubusercontent.com/461/98817695-ca86f280-242a-11eb-9990-32406097639b.png)

### Input Metrics

![image](https://user-images.githubusercontent.com/461/98817911-2487b800-242b-11eb-9f6d-44124f33adbe.png)

### Index Set Configuration

![image](https://user-images.githubusercontent.com/461/98818623-1a19ee00-242c-11eb-884c-4412901b8939.png)

### Pipeline Editor with dark theme

I personally find the dark blue color in the syntax highlighting a bit hard to read on the dark background:

![image](https://user-images.githubusercontent.com/461/98821851-5d765b80-2430-11eb-8d9e-351807a75511.png)

## Your Environment

* Graylog Version: 4.0.0-rc.1

**Comment by aim4r** [comment]
Another annoying one (on 4.0.1) :

![Styling](https://user-images.githubusercontent.com/764189/100469067-e7cbea00-30d5-11eb-86fd-ac1f00d55a53.png)
