### ISSUE TITLE
Graylog 0.92.4 unable to do time range search after an "Indexer failures"

### ISSUE THREAD

**Issue by laghoule** [Graylog2/graylog2-server#945]
I'm unable to do a "time range search" after someone put invalid data (level) in a GELF HTTP input. This invalid data has caused un "indexer failures", and now this seem to have caused a problem with the "time range search", even if I "recalculate index range" manually.

As a workaround, I have manually cycle the deflector, and now the time range search is working again.

**Comment by bclermont** [comment]
:+1:

**Comment by bernd** [comment]
There have been lots of changes since 0.92.4. I am closing this issue now, please re-open if you still have problems. Thank you!
