### ISSUE TITLE
After change of search, search request gets fired 2x

### ISSUE THREAD

**Issue by HenryTheSir** [Graylog2/graylog2-server#9467]
When the search is changed, e.g. added stream, removed stream, added query element or removed query element the click on the search button triggers two (different?) searches.

## Expected Behavior
Search gets triggered one time

## Current Behavior
Search triggers multiple times
![grafik](https://user-images.githubusercontent.com/11004513/98939576-f0270100-24e9-11eb-8da2-672a427790c9.png)

## Possible Solution
Fire just onetime?

## Steps to Reproduce (for bugs)
1. Search
2. Change Serach 
3. Open Browsers Network Requests Tab (F12)
4. Search and see two 'execute' Post Requests with different searchid fired 

## Context
Fast and reliable system

## Your Environment

* Graylog Version: 3.3.8
* Java Version: 8
* Elasticsearch Version: 6.8.10
* MongoDB Version: %
* Operating System: Client Windows/Linux
* Browser version: Current Firefox Windows/Linux

**Comment by dennisoelkers** [comment]
Hey @HenryTheSir!

Thanks for reporting this. We will work on this for one of the next 4.x versions.
