### ISSUE TITLE
Leading wildcard searches generate exception on 1.0.0-RC2

### ISSUE THREAD

**Issue by henrikjohansen** [Graylog2/graylog2-server#947]
```
(You caused a org.graylog2.restclient.lib.APIException. API call failed GET http://@10.xxx.xxx.xxx:12900/search/universal/relative/histogram?range=300&interval=minute&query=*virus&range_type=relative&filter=* returned 400 Bad Request body: {"query":"*virus","begin_column":0,"begin_line":0,"end_column":0,"end_line":0})
```
Leading wildcard searches are not allowed in our config but earlier versions did not throw execeptions for those queries ...

**Comment by bernd** [comment]
Thanks for the report. Reproduced on rc.3.

**Comment by henrikjohansen** [comment]
I'll claim a Jever for my hard testing work next time im in Hamburg :)

**Comment by bernd** [comment]
One. Deal! :beers: :wink:

**Comment by henrikjohansen** [comment]
![b8x6irgcqaaurcd](https://cloud.githubusercontent.com/assets/1473308/6062703/229a234e-ad52-11e4-8d51-868f9955d65a.jpg)

**Comment by bernd** [comment]
:smile:
