### ISSUE TITLE
Relative timerage selector and search doesn't adhere to query time range limit

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#9487]
## Expected Behavior

The search page should adhere to the query time range limit and shouldn't allow users to use a larger time range.

![image](https://user-images.githubusercontent.com/461/99154023-e5689980-26ac-11eb-8c8d-2f1676cf5f75.png)

## Current Behavior

The configured query time range limit is not used. The selection of time ranges is not changed and the backend doesn't restrict searches to the configured range.

![Peek 2020-11-14 19-12](https://user-images.githubusercontent.com/461/99154100-8eaf8f80-26ad-11eb-9d5c-8289ff344e36.gif)

## Related Issues

Refs #1901
Refs #3263
Refs #4787

## Steps to Reproduce (for bugs)

1. Configure a small query time range limit at "System / Configuration"
2. Go back to the search page and search for a longer time range

## Your Environment

* Graylog Version: 4.0.0-rc.2

**Comment by kyleknighted** [comment]
Upcoming UI work will show the limit restriction in the browser, but I do believe we need additional work in the backend to validate API calls

**Comment by linuspahl** [comment]
To ensure we unify the frontend and backend validation: If the limit is set to e.g. "10 minutes", we allow the execution of a search with a relative range that equals the limit (in this case 10 minutes). We only show an error if the range is greater than the limit.
