### ISSUE TITLE
LDAP settings getting stored multiple times

### ISSUE THREAD

**Issue by Nebucatnetzer** [Graylog2/graylog2-server#9494]
I've experienced some problems with the LDAP settings.
I haven't really found out how it is happening but something causes my Graylog instance to forget its LDAP settings.
After some debugging I found out that it doesn't actually forget them but saves them multiple times to the DB which then causes Graylog to fail because it doesn't know which one to use.
IMO the easiest would be to just get rid of that warning about the multiple backends and just use the newest settings or something.

**Comment by bernd** [comment]
This will be fixed in the upcoming 4.0 release. The LDAP configuration part has been rewritten for the new version. Please open a new issue if you still see the same problem with 4.0. Thank you!
