### ISSUE TITLE
Can't "Add to query" or "Remove from results" any items with $ sign at the end

### ISSUE THREAD

**Issue by Mike-FUT** [Graylog2/graylog2-server#9497]
## Expected Behavior
When using aggregation "Show top values" for Windows Domain Controller logs there will be plenty of entries like "TargetUserName" that end with $. For example if a desktop's hostname is "desktop123" it will show up as "desktop123$".
I would expect to filter these items with "Add to query" or "Remove from results".

## Current Behavior
When clicking "Add to query" or "Remove from results" for an entry that ends with a $ sign it won't filter anymore.
instead a message is displayed in a reddish box below the query:

Undeclared query parameters: 
All parameters used in the search query need to be declared before the query can be used:

## Steps to Reproduce (for bugs)
See above.

## Context
This happens a lot with filtering Windows Domain Controller logs.

## Your Environment
Graylog 3.3.8+e223f85
(Private Build 1.8.0_272 on Linux 5.4.0-52-generic)

**Comment by Mike-FUT** [comment]
Update: I just noticed that it makes no difference where the $ sign is. The messahe to declare query parameters even turns up when the $ sign is in the middle.

**Comment by chalfling** [comment]
I think that $ sign is a regex to end of string, I think it must be escaped with a backslash , then to Add ou Remove from query you need something like: AND NOT hostname:desktop123\\$
