### ISSUE TITLE
Support for LDAP Groups

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#951]
Not an issue, but a feature request for next versions:

It would be great if support to LDAP groups is added to Graylog.

Example: I have my user, it's part of the group 'group1'.

On the stream, I add that everybody on the group 'group1' have the view of that stream, so I don't need to add manually a user to a stream when it joins a new group (a development group, as an example).

And thanks for the hard work guys, the software is amazing!!

**Comment by zolech** [comment]
+1

 LDAP Group synchronization is what we are waiting for

**Comment by rikatz** [comment]
@kroepke great job!!! Thanks guys for this awesome software, Graylog is transforming on a game changer!!
