### ISSUE TITLE
Incorrect support link in "Need further help?" block

### ISSUE THREAD

**Issue by danotorrey** [Graylog2/graylog2-server#9515]
When a startup error occurs with Graylog, a message similar to the following appears. The link for the Commercial support option is broken when visited.
```
################################################################################

ERROR: Unable to probe any host for Elasticsearch version!

Please see the following link(s) to help you with this error:

* http://docs.graylog.org/en/4.0/pages/configuration/elasticsearch.html

Need further help?

* Official documentation: http://docs.graylog.org/
* Community support: https://www.graylog.org/community-support/
* Commercial support: https://www.graylog.com/support/

Terminating. :(

################################################################################
```

## Expected Behavior

The commercial support link should be changed to https://www.graylog.org/technical-support

## Current Behavior

Link points to the wrong

## Steps to Reproduce (for bugs)

Try to start Graylog without Elasticsearch running.

## Your Environment

* Graylog Version: Graylog 4.0.0-rc.2

**Comment by danotorrey** [comment]
I'll fix this with a small PR shortly.

**Comment by bernd** [comment]
Re-open for backport.

**Comment by bernd** [comment]
This is done.
