### ISSUE TITLE
Issue with Quick Values - Return Code

### ISSUE THREAD

**Issue by rikatz** [Graylog2/graylog2-server#952]
While using the 1.0 rc2 version, with Apache Logs tryied to generate quick values of the Return Codes and got an error on the Web Interface.

Also, on the Graylog Server the following WARN appears:

Unable to execute search: Failed to execute phase [fetch], [reduce]

This is strange, because other bigger values (as Agent, Request) this doesn't happen. I've also cycled the deflector, but the issue still happens.

Any idea?

Thanks!

**Comment by edmundoa** [comment]
Hi,

Thank you for reporting this issue.

Which error do you get on the web interface? That would help to try to locate the problem. As the quick values are loaded with an AJAX call, you may also find more information by opening your browser's developer tools and checking the network requests.

**Comment by rikatz** [comment]
@edmundoa Tks for the quick Answer.

The following is the full request:

Remote Address:10.XX.XX.XX:443
Request URL:https://graylog.rkatz/graylog/a/search/fieldterms?rangetype=relative&q=*&field=response&relative=300&stream_id=53762a440cf22409b57a2a8f
Request Method:GET
Status Code:400 Bad Request
Request Headersview source
Accept:*/*
Accept-Encoding:gzip,deflate
Accept-Language:pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4
Connection:keep-alive
Cookie:PLAY_SESSION="9742ad4efbd8e135ff0bfaacc5ff6d1a5e1b2c75-disconnected_orig_uri=%2Fgraylog%2Fsystem&sessionid=413be459dac629817c8e6fa3864bef96162d569a680c1f75fca396d0ad8957166e3840a52c054c2611c220abb76537b83a7e6991685bad6cb787bc2601c2b63d"
Host:graylog.rkatz
Referer:https://graylog.rkatz/graylog/streams/53762a440cf22409b57a2a8f/messages?q=%2A&rangetype=relative&relative=300&width=1425
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36
X-Requested-With:XMLHttpRequest
Query String Parametersview sourceview URL encoded
rangetype:relative
q:*
field:response
relative:300
stream_id:53762a440cf22409b57a2a8f
Response Headersview source
Cache-Control:no-cache
Connection:close
Content-Length:0
Content-Type:text/plain; charset=UTF-8
Date:Fri, 06 Feb 2015 13:09:30 GMT

**Comment by edmundoa** [comment]
The request you shared looks just fine, all query strings are identical to those I got while trying to reproduce the issue. That means that the problem is likely on Elasticsearch while performing the search. Could you please try to execute the following command and send the related logs from Graylog server and Elasticsearch? You may also send them by email to edmundo[at]graylog[dot]com if you don't want to leak any information by accident.

`curl -XGET -i 'http://<username>:<password>@<graylog-server>:12900/search/universal/relative/terms?field=response&query=*&range=300&filter=*'`

Please remember to change the `username`, `password` and `graylog-server` fields with the right values for your installation.

**Comment by rikatz** [comment]
curl -u 'user:password' -XGET -i 'http://10.XX.XX.XXX:12900/search/universal/relative/terms?field=response&query=*&range=300&filter=*'HTTP/1.1 200 OK
Content-Type: application/json
X-Runtime-Microseconds: 295278
Transfer-Encoding: chunked

{"time":257,"terms":{"200":751930,"301":506,"400":33,"302":26790,"500":5796,"501":28,"403":21468,"304":14895,"404":868,"206":97,"415":3,"405":1},"missing":17515,"other":0,"total":822415,"built_query":"{\"from\":0,\"query\":{\"match_all\":{}},\"facets\":{\"gl2_terms\":{\"terms\":{\"field\":\"response\",\"size\":50},\"facet_filter\":{\"bool\":{\"must\":{\"range\":{\"timestamp\":{\"from\":\"2015-02-06 15:40:23.849\",\"to\":\"2015-02-06 15:45:23.849\",\"include_lower\":true,\"include_upper\":true}}}}},\"global\":false}}}"}


So this query worked, nothing happened on GS or ES.

**Comment by rikatz** [comment]
@edmundoa One detail, I'm using rc2 and not rc3. Do you think some of the bug fixes just fixed this?

**Comment by edmundoa** [comment]
@rikatz looking at the closed issues on rc3, there shouldn't be any changes related to this. Anyway I'll take a look, even if it is to know this is fixed.

The response is looking good, is it still failing when you use the quick values from the web interface? It may be some temporary problem...

**Comment by rikatz** [comment]
Yes, now it's working. That's very very strange :( I was facing this issue since yesterday...Don't know, but no problem. Thanks for the answer, will keep testing to see if catch some more bug before the final release ;)

**Comment by edmundoa** [comment]
It's a bit weird, but maybe it was related to an old ES index that got closed or deleted at some point. Please reopen the ticket if you find the same issue again.
Thank you for trying to catch all those nasty bugs! :-)
