### ISSUE TITLE
Get back Sources tab existed before 3.2

### ISSUE THREAD

**Issue by zoulja** [Graylog2/graylog2-server#9522]
In 3.1 we had a very useful Sources tab.
I click Sources - and can estimate which nodes send logs, proportions, how many Gb, can filter it and so on.
So I can understand whole picture in a few seconds.
Now we have some pale shadow of that powerful and really user friendly function.
Please get it back

**Comment by aim4r** [comment]
Upvote from me.

**Comment by jalogisch** [comment]
@zoulja 

this header navigation can now be found at `Dashboards > Sources` as we wanted to not overwhelm the top navigation. 

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by zoulja** [comment]
Thanks a lot for the clarification @jalogisch !
Actually it was supposed a feture request (I selected this type during creation), not a bug, sorry for this misunderstanding
