### ISSUE TITLE
Generate reports and CSVs in local time

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#9546]
## What?

As a user, I know that the values I see for log timestamps in my browser are localized to my browser's time. This differs when I generate a report or a CSV, as those values show system time or UTC (z-4329). I'd like to have the option to generate reports/CSVs in my local time, versus system time.

**Comment by bernd** [comment]
Duplicate of https://github.com/Graylog2/graylog2-server/issues/4523 and related to https://github.com/Graylog2/graylog2-server/issues/8011.

**Comment by asachs01** [comment]
@bernd is there a possibility of getting some traction on the associated requests given we have a paying customer asking for it?

**Comment by asachs01** [comment]
@bernd bumping again. I know you closed this, but I've not seen any activity on the other 2 issues you linked to. Can you comment on if this will be prioritized given we have a paying customer asking for this?

**Comment by edward-marrufo** [comment]
@dennisoelkers do we have any movement on this? We have another different customer asking us about this issue.

**Comment by dennisoelkers** [comment]
Not fixed in #11734, just the export part.
