### ISSUE TITLE
Eight hours less

### ISSUE THREAD

**Issue by zx4java** [Graylog2/graylog2-server#9547]
![image](https://user-images.githubusercontent.com/42798227/99630355-afdcfb00-2a74-11eb-935e-92a9d63a1416.png)
![image](https://user-images.githubusercontent.com/42798227/99630381-c08d7100-2a74-11eb-88af-897c7166c2e3.png)
![image](https://user-images.githubusercontent.com/42798227/99631361-6e4d4f80-2a76-11eb-82fd-d69d87793080.png)
versions:
es-6.8.5
graylog-4.0.0
deploy-method: docker

**Comment by bernd** [comment]
@zx4java Can you please explain? Just pasting screenshots without any explanation makes it really hard to figure out what issue you are seeing. Thank you!

**Comment by zx4java** [comment]
![image](https://user-images.githubusercontent.com/42798227/99640076-67790980-2a83-11eb-86b1-c90e1e992221.png)
![image](https://user-images.githubusercontent.com/42798227/99640083-6942cd00-2a83-11eb-9f1a-00e7a4349a19.png)

The timestamp of the search result of the same message differs by 8 hours from that of the input recent message load. Both root_timezone and /etc/timezone in my docker have been cut into the same timezone Asia/Shanghai, but it doesn't seem to affect...I wonder if you are following me

**Comment by zx4java** [comment]
I used timestamp search to verify the saved timestamp, which made me a little confused. I don't know why, because I checked that all the time zones in my application have been unified, but the display in the Time Configuration is correct
![image](https://user-images.githubusercontent.com/42798227/99640556-056cd400-2a84-11eb-9107-71396e5eb50f.png)

**Comment by dennisoelkers** [comment]
@zx4java: The timestamp in the `@timestamp` field is shown as UTC and not in the local time of the user. I guess that is the issue?

**Comment by zx4java** [comment]
Yes, there is another confusion. I used the date conversion in Converter to convert nginx to time_local field, which would take 8 hours less. But I guess it should be the same problem.
![image](https://user-images.githubusercontent.com/42798227/99684365-5993aa80-2abc-11eb-8421-a1eb2ad71679.png)
![image](https://user-images.githubusercontent.com/42798227/99684372-5bf60480-2abc-11eb-84cb-297e34fed77f.png)

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
