### ISSUE TITLE
Not able to set the graylog2 server in cluster

### ISSUE THREAD

**Issue by shivakhuba** [Graylog2/graylog2-server#955]
Wanted to set two nodes in cluster.

I have made one as master another as slave, but getting "misfired. Reason: Address already in use"

Kindly request to provide me the documentation to set the graylog2 server in cluster.

**Comment by joschi** [comment]
The error message looks like there's already running another process on the network interface you want Graylog to bind to. You can check this with `netstat -tln` or `lsof -i :12900`.

For general questions like this, kindly use the mailing list at https://groups.google.com/forum/#!forum/graylog2
