### ISSUE TITLE
Lookup tables - `purge key` should purge it from all cluster members

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#9554]
## Expected Behavior

When purging a key from the caches in the lookup tables that should happen on all nodes and not only the one you are connected too.

![image](https://user-images.githubusercontent.com/404238/99664170-17407e00-2a68-11eb-91f2-458d401b98c3.png)

That is a potential problem as it is not clear that this is done only on the node you are connected too and not on all members of the cluster. When you are using a cache that is used by all cluster members that is not a problem, but if you have only local mem caches this can be a problem. 

## Current Behavior
Deletion is only done on the node that you are connected.

## Possible workround
Change the settings of the cache will end in a restart of the caches and with that a purge of all cached content. 
Purging the key via API endpoint that runs to all nodes in the cluster.

## Context
As long as there is no cache that is used by all cluster members this can cause Graylog nodes to have different results from DSV lookups.

**Comment by l0calhost** [comment]
+1, i currently need to workaround with a shell script manually deleting on every single cluster node.
