### ISSUE TITLE
Link for `graylog-sidecar` tokens on sidecars page results in an error in 4.0

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#9555]
## Expected Behavior

When accessing a user's tokens via `system/users/tokens/graylog-sidecar` I should be able to view the tokens for that user.

## Current Behavior

Currently when accessing the System-->Sidecars page and clicking on `Create or reuse a token for the graylog-sidecar user`, I receive an error:

![CleanShot 2020-11-19 at 09 03 54](https://user-images.githubusercontent.com/898627/99676280-46de8e80-2a46-11eb-82ca-b99375ad124a.gif)

## Workaround
The `graylog-sidecar` tokens page can be accessed by clicking on the `Edit tokens` action on the System -> Users & Teams page.
![image](https://user-images.githubusercontent.com/46300478/100087297-d1f8c380-2e4e-11eb-8762-dbf964a0ba60.png)

## Your Environment

* Graylog Version: 4.0 rc2

**Comment by repusnimda** [comment]
same problem

**Comment by repusnimda** [comment]
:) Ha-ha! This link on **System/Sidecars** didn't work. For view/edit/create sidecar tokens go to **System\Users and Teams**, find user **Sidecar System User (built-in)**, and select **More actions\Edit tokens**

**Comment by linuspahl** [comment]
@repusnimda That's right!
We will fix the link on the sidecars page with the next patch release.

**Comment by linuspahl** [comment]
Got fixed with #9605 and #9613 (4.0)
