### ISSUE TITLE
Failed to start up after upgrade from 2.5 to 3.0

### ISSUE THREAD

**Issue by limanzhang-ess** [Graylog2/graylog2-server#9557]
After upgraded to 3.0.2, the graylog-server service was started but there are many errors and visiting through nginx got 502 Bad Gateway. 
Here is the error in log:
2020-11-19T15:01:25.940+01:00 ERROR [CmdLineTool] Guice error (more detail on log level debug): Error injecting constructor, java.lang.NullPointerException

Before the upgrade, I did the following:
1. Change the configuration
rest_listen_uri | http_bind_address | 127.0.0.1:9000
rest_transport_uri | http_publish_uri | http://$http_bind_address/
web_endpoint_uri | http_external_uri | $http_publish_uri

2. Add elasticsearch and mongodb uri, which are both installed locally.
      elasticsearch_hosts =http://127.0.0.1:9200
      mongodb_uri = mongodb://127.0.0.1:27017

3. change proxy for nginx:
proxy_set_header x-graylog-server-url https://$server_name/

Reference:
https://docs.graylog.org/en/3.3/pages/upgrade/graylog-3.0.html

What did I miss in the upgrade?

Thank you in advance!

**Comment by samupr** [comment]
I had the same problem and it was caused by the plugin `graylog-plugin-auth-sso`. After removing, service started perfectly.

**Comment by limanzhang-ess** [comment]
Thank you for the reply. 
I have removed all of the old plugins before upgrading. Now there are three plugins in the plugin folder with version 3.0.2.

**Comment by limanzhang-ess** [comment]
ls /usr/share/graylog-server/plugin
graylog-plugin-aws-3.0.2.jar  graylog-plugin-collector-3.0.2.jar  graylog-plugin-threatintel-3.0.2.jar

**Comment by limanzhang-ess** [comment]
Old plugins:
graylog-plugin-aws-2.4.6.jar    graylog-plugin-collector-2.4.6.jar               graylog-plugin-netflow-2.4.6.jar
graylog-plugin-beats-2.4.6.jar  graylog-plugin-enterprise-integration-2.4.6.jar  graylog-plugin-pipeline-processor-2.4.6.jar
graylog-plugin-cef-2.4.6.jar    graylog-plugin-map-widget-2.4.6.jar              graylog-plugin-threatintel-2.4.6.jar

**Comment by limanzhang-ess** [comment]
Should I upgrade all of the old plugins?

**Comment by jalogisch** [comment]
Only use the plugins compatible with your Graylog version.

Remove all of the above mentioned and your Graylog will work.

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
