### ISSUE TITLE
Graylog Development Setup error - Server currently unavailable

### ISSUE THREAD

**Issue by snmsmanager** [Graylog2/graylog2-server#9571]
Hi,

I've setup development environment as per the document and start graylog2-web-interface using port 8000 as below.
 **yarn start --host=192.168.8.10 --port=8000**

But when I try to access Express web server using "http://192.168.8.10:8000/" it says "**Server currently unavailable and We are experiencing problems connecting to the Graylog server running on http://localhost:9000/api**." 

![image](https://user-images.githubusercontent.com/5483940/99863957-af547980-2bc6-11eb-90c6-65a401d3a181.png)

It is same even I change the "**config.js**" to "**gl2ServerUrl: 'http://192.168.8.10:9000/api**',"

Regards,
Pradeep.

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
