### ISSUE TITLE
GrayLog UI with Other indices

### ISSUE THREAD

**Issue by pabrahamusa** [Graylog2/graylog2-server#9572]
I am new to GrayLog and want to check whether I can use the Web Interface with any other indices other than Elastic Search. I have a Lucene based index with rest based queries supported. is it possible to use graylog UI to hook up with my custom lucene index? or do I always have to use ElasticSearch?

**Comment by dennisoelkers** [comment]
Hey @pabrahamusa,

thanks for getting in touch. Right now you always need an Elasticsearch backend for your log messages. _If_ your backend is 100% API-compatible with Elasticsearch, it _could_ work too, but that would not be supported.

**Comment by pabrahamusa** [comment]
Thanks @dennisoelkers for the info. Hence closing the ticket.
