### ISSUE TITLE
graylog2-ctl split not working?

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#958]
Hi,

Am i missing something?
I have 2 Amazon instances running the original AMI.
Started the first :

graylog2-ctl set-admin-password bla
graylog2-ctl reconfigure

On the second :

graylog2-ctl set-cluster-master 10.0.0.76
graylog2-ctl reconfigure

Now i have a working webinterface on the second node, but on the "Nodes" page it only shows the first machine. Why?

**Comment by mariussturm** [comment]
Hi,
whats your desired state? The second node should be another Elasticsearch node, Graylog server or web interface?

**Comment by dennusb** [comment]
Hi,

I want to "complete" nodes, both running everything...

**Comment by mariussturm** [comment]
The current idea is to 'extend' a full running Graylog with more ES nodes or more Graylog server instances. I will check what is missing in your case...

**Comment by dennusb** [comment]
Thanks :)

**Comment by dennusb** [comment]
They need to contact the exact same MongoDB (or Mongo needs to be clustered) but all the hosts (when using 2 servers with all roles) are contacting their own Mongo.... and that does not work :) Maybe fix it in a new Chef cookbook thingy?

**Comment by mariussturm** [comment]
I have updated the AMIs for 0.92.4, could you please give it a try?
