### ISSUE TITLE
Elasticsearch exception [type=index_not_found_exception, reason=no such index []] error after update elasticsearch

### ISSUE THREAD

**Issue by aLuViAn87** [Graylog2/graylog2-server#9588]
Updated Graylog 3.3.8 to 4 and restarted, everything went fine. Updated elasticsearch from 6.8 to 7.10 and the following error is displayed on message count and all messages widgets in "search" screen :

While retrieving data for this widget, the following error(s) occurred:
Elasticsearch exception [type=index_not_found_exception, reason=no such index []].
## Expected Behavior

Message Count and all messages should display data

## Current Behavior

The following message occurs :
While retrieving data for this widget, the following error(s) occurred:
Elasticsearch exception [type=index_not_found_exception, reason=no such index []].
Elastic Cluster Health is Green, all shards are accessible. No errors inside Graylog Server logfiles or Elastic logs.

## Possible Solution

Seems Graylog is searching for an index that does not exist in indices.

## Steps to Reproduce (for bugs)

1. Update existing Graylog 3.3.8 to 4.0
2. Update existing Elasticsearch 6.8 to 7.10
3. Restart Graylog server
4. Go to Graylog server Homepage

## Your Environment

* Graylog Version: 4.0
* Java Version: 1.8
* Elasticsearch Version: 7.10
* MongoDB Version: 4.2
* Operating System: CentOS 8
* Browser version: Chrome 68

**Comment by jalogisch** [comment]
he @aLuViAn87 

did you restart Graylog AFTER you have updated elasticsearch? Changing the elasticsearch version transparent while Graylog is running does not work.

**Comment by aLuViAn87** [comment]
> he @aLuViAn87
> 
> did you restart Graylog AFTER you have updated elasticsearch? Changing the elasticsearch version transparent while Graylog is running does not work.

Yes I restarted and it still has the same behavior.

**Comment by aLuViAn87** [comment]
The issue was coming from a partially restored mongodump and was unrelated to graylog nor elastic. I'm closing the issue.
