### ISSUE TITLE
Use new java.time date format specifiers

### ISSUE THREAD

**Issue by zoulja** [Graylog2/graylog2-server#9590]
After upgrading to GL4.0/ES7.10 I'm observing a lot of the following records in graylog's log:
> 2020-11-23T16:08:05.853+03:00 WARN  [RestClient] request [POST http://127.0.0.1:9200/_msearch?typed_keys=true] returned 1 warnings: [299 Elasticsearch-7.10.0-51e9d6f22758d0374a0f3f5c6e8f3a7997850f96 "'y' year should be replaced with 'u'. Use 'y' for year-of-era. Use new java.time date format specifiers."]

Please advise how to handle this and whether I should worry abt it.
Probably Graylog should update some date symbols https://docs.graylog.org/en/4.0/pages/extractors.html?highlight=minute#standard-date-converter-format-string-table?

* Graylog Version: 4.0
* Java Version: not really sure, some bundled I believe
* Elasticsearch Version: 7.10 OSS
* MongoDB Version:  v4.0.21
* Operating System: Centos 7
* Browser version: Chrome 87

Thanks in advance

**Comment by dennisoelkers** [comment]
Hey @zoulja,

we are aware of this. It is not an issue and is not impacting functionality. It will probably be gone in one of the next patch versions.

**Comment by zoulja** [comment]
Got it, thanks!
