### ISSUE TITLE
Crash of mongodb created multiple write alias targets

### ISSUE THREAD

**Issue by Nhyalgotphores** [Graylog2/graylog2-server#9592]
We have experienced crash of mongodb which lead to unrecognized indicies, after triggering recalculation the log contains

`2020-11-19T15:13:21.747+01:00 INFO [RebuildIndexRangesJob] Recalculating index ranges for index set DBs (sam_*): 20 indices affected.
2020-11-19T15:13:21.748+01:00 ERROR [RebuildIndexRangesJob] Multiple write alias targets found, this is a bug.` 

Is there way to manually correct those?

## Your Environment

* Graylog Version: 3.3.8+e223f85
* Java Version: openjdk version "1.8.0_265"
* Elasticsearch Version: 6.8.12-1
* MongoDB Version: 4.0.20-1
* Operating System: CentOS Linux release 8.2.2004
* Browser version: N/A

**Comment by jalogisch** [comment]
he @Nhyalgotphores 

you need to delete the index aliases `*_deflector` for all execpt the latest index in elasticsearch. This is done easiest via some sort of UI, like cerebro or simila.r

**Comment by Nhyalgotphores** [comment]
Thanks, deleting those solved the issue.
