### ISSUE TITLE
Message table does not include microseconds

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#9604]
## Expected Behavior
all available time information should be displayed proper. 

## Current Behavior
![image](https://user-images.githubusercontent.com/404238/100200354-c4027b80-2efe-11eb-8ef9-0c731b8eb08d.png)

even when microseconds are available those are not displayed in the message table view.

## Possible Solution
I myself would not display if those are not given (or is 000) otherwise display the included microsecond in the display on the message table.

## Context
In the current world having only seconds is not always enough - past Graylog versions have displayed those microseconds but the current did not anymore. 

## Your Environment
* Graylog Version: 4.0 / 3.3.9

[z#844348]

**Comment by dennisoelkers** [comment]
For completeness: this has been the case since 3.2.0 and a complete timestamp is available when expanding a message's details.

**Comment by HenryTheSir** [comment]
> 
> 
> For completeness: this has been the case since 3.2.0 and a complete timestamp is available when expanding a message's details.

In 3.3.8 one need to hover to see the exact timestamp. Otherwise this is a second bug.
