### ISSUE TITLE
New Retention Strategy: Freeze Index

### ISSUE THREAD

**Issue by chalfling** [Graylog2/graylog2-server#9617]
## What?

Freeze Indices as these like Closed Indices do not consume resources but still are available for search.

## Why?

I think this is better than reopen a index when I need to search a older data.

## Your Environment

* Graylog Version: 4.0.0
* Elasticsearch Version: 7.9.3
* MongoDB Version: 4.2.5
* Operating System: FreeBSD 12.1

**Comment by bernd** [comment]
Note: the freeze index API is a commercial feature and only available in Elasticsearch x-pack.

**Comment by chalfling** [comment]
> Note: the freeze index API is a commercial feature and only available in Elasticsearch x-pack.

Yeah, you are right! Thank you and sorry!

**Comment by chalfling** [comment]
> Note: the freeze index API is a commercial feature and only available in Elasticsearch x-pack.

![Screenshot_20210214_124522](https://user-images.githubusercontent.com/9088569/107881304-90fad300-6ec2-11eb-9702-a8a9a25f9bc1.png)

![Screenshot_20210214_124640](https://user-images.githubusercontent.com/9088569/107881339-b4258280-6ec2-11eb-9fb3-861d0ab21d19.png)

My default license on Elasticsearch7.9.3 from FreeBSD ports is "Basic". I can freeze and unfreeze indices via curl command.

But Graylog can't read(search) from a frozen index

**Comment by bernd** [comment]
@chalfling Can you please show us any error messages and Graylog server log errors you see? Thank you!

**Comment by chalfling** [comment]
> @chalfling Can you please show us any error messages and Graylog server log errors you see? Thank you!

Hello @bernd I'm not seeing any error. This behavior is exactly like when my index was closed.
I was using Retention's Close Strategy on Graylog's Index Set Config. But I migrate to Elasticsearch Index Lifecycle Policy, because Graylog doesn't support this option.

This is my Policy:

>PUT _ilm/policy/180days-age-35days-hot
>{
>  "policy": {
>    "phases": {
>      "hot": {
>        "min_age": "0ms",
>        "actions": {
>          "set_priority": {
>            "priority": null
>          }
>        }
>      },
>      "cold": {
>        "min_age": "35d",
>        "actions": {
>          "freeze": {},
>          "set_priority": {
>            "priority": 0
>          }
>        }
>      },
>      "delete": {
>        "min_age": "180d",
>        "actions": {
>          "delete": {
>            "delete_searchable_snapshot": true
>          }
>        }
>      }
>    }
>  }
>}

This is my index that was frozen from policy:

> GET freebsd_313/_ilm/explain'
> {
>   "indices": {
>     "freebsd_313": {
>       "index": "freebsd_313",
>       "managed": true,
>       "policy": "180days-age-35days-hot",
>       "lifecycle_date_millis": 1610323203763,
>       "age": "35.56d",
>       "phase": "cold",
>       "phase_time_millis": 1613354443967,
>       "action": "complete",
>       "action_time_millis": 1613354445892,
>       "step": "complete",
>       "step_time_millis": 1613354445892,
>       "phase_execution": {
>         "policy": "180days-age-35days-hot",
>         "phase_definition": {
>           "min_age": "35d",
>           "actions": {
>             "freeze": {},
>             "set_priority": {
>               "priority": 0
>             }
>           }
>         },
>         "version": 1,
>         "modified_date_in_millis": 1613315666539
>       }
>     }
>   }
> }


Because this policy I was able to search only the last 35 days, more than that was frozen and not searchable. When my policy of Retention on Graylog's settings was to Close indices older than 35 days, obviously I couldn't search more than 35 days.

I don't have a issue with not searching in frozen indices, If I need it I'll unfreeze the indices. What I think will be really helpful is to be able to manage Frozen Indices on Graylog and able to Create a Retention Strategy to Freeze Older Indices.

More helpful will be to create Two or More Retention Strategy like I did directly on Elasticsearch: 180 days retention (delete) and 35 days hot indices(frozen). I suggested this on this "issue": https://github.com/Graylog2/graylog2-server/issues/8738

Thank you!

**Comment by bernd** [comment]
@chalfling We are not supporting commercial Elasticsearch features in Graylog. Frozen indices are a commercial feature. They are only available for free with their "Basic" license. Sorry!
