### ISSUE TITLE
SO_RCVBUF warn on Graylog 4

### ISSUE THREAD

**Issue by malinkinsa** [Graylog2/graylog2-server#9627]
I duplicate my question from the forum.
After update Graylog from 3.3.8 to 4.0.0 with change ES version to 7.10.0 one of my Netflow UDP input started to lose almost all data with next warning in log:
`| 2020-11-26 09:24:33,931 WARN : org.graylog2.inputs.transports.UdpTransport - receiveBufferSize (SO_RCVBUF) for input NetFlowUdpInput{title=Office Netflow, type=org.graylog.plugins.netflow.inputs.NetFlowUdpInput, nodeId=998dccaf-8d52-4782-8294-2b4a9b160ea6} (channel [id: 0x7e47f7ca, L:/0.0.0.0:2056]) should be 262144 but is 524288.`

I am doing `sysctl -w net.core.wmem_max=262144` on host machine - nothing.

Some of the logs still come in. But these are a few percent.
But if i stop this input - i have a similar warn on my second netflow connector, but no problems with logs.

May be you have any solution for this case?

**Comment by florianpopp** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
