### ISSUE TITLE
processing pipeline - function `parse_string_as_json` 

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#9633]
## Expected Behavior
It should be possible to parse a string in the processing pipeline like the extractors do. 

## Current Behavior
It is always needed to know the json structure and use `parse_json` and `json_path` to create fields out of a KNOWN json structure. 

## Possible Solution
Make it possible to have the same functionality the current extractor for json parsing has. Parse a string and make all new fields with values. Plus have the option to flatten. 

## Context
Multiple issues show that JSON parsing is an issue. We should make it as easy as possible to consume json logs. 

## Your Environment
* Graylog Version: 4 / 3

[Z#844347]

**Comment by l0calhost** [comment]
+1 !! It definitely shoould be possible to extract json in a pipeline rule without manually handling the structure.

**Comment by boosty** [comment]
We added new processing pipeline features in 4.3, which seem to solve this issue:
- https://www.graylog.org/post/announcing-the-graylog-v4-3-release-candidate
- https://github.com/Graylog2/graylog2-server/issues/8706
- https://github.com/Graylog2/graylog2-server/issues/9021

**Comment by boosty** [comment]
See https://github.com/Graylog2/graylog2-server/issues/8706#issuecomment-1022289793
