### ISSUE TITLE
Links Missing from Sidecar Screen

### ISSUE THREAD

**Issue by JPNetEdwards** [Graylog2/graylog2-server#9677]
In Graylog 4.0.1 the Links for 'Overview', 'Administration', and 'Configuration' are missing from the Sidecar screen

## Expected Behavior
When going to example URL:

https://graylogserver.com/system/sidecars

Links for 'Overview', 'Administration', and 'Configuration' should be present at the top right of the screen. 

## Possible Solution
I am able to manually enter the following example URL:

https://graylogserver.com/system/sidecars/administration
https://graylogserver.com/system/sidecars/configuration

And on this page the three links are present. They just don't appear on the Overview main page.

## Steps to Reproduce (for bugs)
1. Log into Graylog server
2. Systems
3. Sidecar
4. Links Missing

## Context
I am trying to setup Sidecars for our Windows client after standing up a new Graylog server

## Your Environment
* Graylog Version: 4.0.1
* Java Version: 1.8.0
* Elasticsearch Version: 7
* MongoDB Version: 4.0
* Operating System: Ubuntu 20.04
* Browser version: Chrome 87

![Sidecar Administration Screen](https://user-images.githubusercontent.com/75326921/100769189-b438da80-33c9-11eb-85b7-2f6204ae52c5.png)
![Sidecar Configuration Screen](https://user-images.githubusercontent.com/75326921/100769190-b4d17100-33c9-11eb-83f2-ff1254cf621f.png)
![Sidecar Overview Screen](https://user-images.githubusercontent.com/75326921/100769192-b4d17100-33c9-11eb-87e6-77f7b14d025e.png)

**Comment by linuspahl** [comment]
@JPNetEdwards Thanks a lot for reporting this issue! We will release a fix with the next patch release.
