### ISSUE TITLE
Alerts feature "Filter has NOT results"

### ISSUE THREAD

**Issue by whoami-ru** [Graylog2/graylog2-server#9681]
### Expected Behavior
Alerting by log absence.

### Current Behavior
Alerting by query "Filter has result" or "Aggregation of results reaches a threshold".

### Possible Solutione
Add additional query "Filter has not result".

### Context
For example, if logs from any host stop coming to Graylog you need to receive alerts.

### Your Environment
Graylog Version: 3.1.4+1149fe1

**Comment by chalfling** [comment]
I do this with aggregation and count() == 0

**Comment by whoami-ru** [comment]
@chalfling thanx!

**Comment by whoami-ru** [comment]
It works just for one host. Maybe someone knows how to implement such a case?

**Comment by whoami-ru** [comment]
I realized that it's impossible in the current configuration =).
