### ISSUE TITLE
GELF AMQP Input plugin does not re-read configuration change after being stopped

### ISSUE THREAD

**Issue by dfch** [Graylog2/graylog2-server#969]
It seems that the GELF AMQP Input does not detect changes in the plugin configuration after the input has been stopped. 
If I follow the code correctly, after a ```stop``` of the input, the underlying ```transport``` is not destroyed, but only ```stop()``` is called. So after a change of the configuration the new config is not propagated to the the transport and the old transport configuration is still used.

	Version:1.0.0-rc.4 (d18cd9c) (Moose)
	JVM:PID 2110, Oracle Corporation 1.7.0_71 on Linux 2.6.32-504.el6.x86_64

**Comment by kroepke** [comment]
How did you update the input?

We just looked at the code but couldn't immediately find the problem you describe.
When an existing input is launched again (e.g. after being stopped manually) a new MessageInput instance is created with the current configuration.
This includes creating a new Transport object, as well.

The old transport should not be reused at all, it is discarded together with the MessageInput (as is the codec).

**Comment by dfch** [comment]
I stopped the input, updated the configuration and restarted the input. Then I got this strange behaviour that the old settings were still applied.

I now re-checked this and somehow get different results, so I am currently not able to reproduce this in a stable way. When I have news on this I will reopen or recreate the issue and close it for now.

sorry to have bothered, Ronald
