### ISSUE TITLE
new java.time date format specifiers after upgrade to 4.0

### ISSUE THREAD

**Issue by Nhyalgotphores** [Graylog2/graylog2-server#9690]
After major upgrade the log contains

 `2020-12-03T10:09:04.375+01:00 WARN  [RestClient] request [POST http://127.0.0.1:9200/_msearch?typed_keys=true] returned 1 warnings: [299 Elasticsearch-7.10.0-51e9d6f22758d0374a0f3f5c6e8f3a7997850f96 "'y' year should be replaced with 'u'. Use 'y' for year-of-era. Use new java.time date format specifiers."]
`

## Expected Behavior
If it is for backward compatibility it should be muted in log, if not it should be adopted.

## Current Behavior
Spamming this message in log for all requests that return it.

## Possible Solution
Adopt new format or mute the message and adopt it later.

## Steps to Reproduce (for bugs)
Upgrade to graylog 4.0 and elasticsearch 7.10

## Context
The issue leads to significant increase of log size.

## Your Environment

* Graylog Version:4.0
* Java Version:1.8.0
* Elasticsearch Version:7.10
* MongoDB Version:4.4
* Operating System:Centos 8

**Comment by dennisoelkers** [comment]
Hey @Nhyalgotphores,

thanks for reporting this. We are aware of the issue and it will be fixed in one of the next releases.

**Comment by Nhyalgotphores** [comment]
Hello @dennisoelkers 
Is there possibility to mute that message to prevent excessive logging?

**Comment by qwsj** [comment]
Also have this issue after upgrading to 4.0.2
```Package: graylog-server
Version: 4.0.2-1
License: SSPL
Vendor: graylog
Architecture: all
Maintainer: Graylog, Inc. <hello@graylog.org>
Installed-Size: 175003
Depends: uuid-runtime
Conflicts: graylog2-web, graylog-web, graylog
Replaces: graylog2-server
Section: net
Priority: extra
Homepage: https://www.graylog.org/
Description: Graylog server
Description-md5: bc2d4f8a10fe2ef75ffd64454742166f
Filename: pool/stable/4.0/g/graylog-server/graylog-server_4.0.2-1_all.deb
MD5sum: 05831798d78f129aeb812da0304c2550
SHA1: 79fe6852ccf01740c7b7b445005796953239a56e
SHA256: 36efea37f1ad914ea007274d23ddc5eb98e1db7cf80df76543469bf36438e227
SHA512: 6f3c87f8447ff8667934bdef100711a4d6937ce7b3e95a82068234a920e0f8c85b39aabe771c96160e3f5fc2b1a8acb2b77523574ab2eefe00d12bae66de3559
Size: 160805182
```

```
ii  elasticsearch-oss             7.10.2                       amd64        Distributed RESTful search engine built for the cloud
ii  graylog-server                4.0.2-1                      all          Graylog server
```

```
2021-02-01T08:48:14.457+01:00 WARN  [RestClient] request [POST http://127.0.0.1:9200/_msearch?typed_keys=true] returned 1 warnings: [299 Elasticsearch-7.10.2-747e1cc71def077253878a59143c1f785afa92b9 "'y' year should be replaced with 'u'. Use 'y' for year-of-era. Use new java.time date format specifiers."]
```

**Comment by dseira** [comment]
I'm getting the same warning after a major upgrade (from 3.3 to 5.0):

```
2023-03-30T17:59:15.355+02:00 WARN  [RestClient] request [POST http://127.0.0.1:9200/_msearch?typed_keys=true] returned 1 warnings: [299 Elasticsearch-7.10.2-747e1cc71def077253878a59143c1f785afa92b9 "'y' year should be replaced with 'u'. Use 'y' for year-of-era. Use new java.time date format specifiers."]
```

My stack versions is:

```
graylog-server 5.0.5
elasticsearch-oss 7.10.2
mongo 5.0.15
```
