### ISSUE TITLE
API Endpoint /api/system/stats throws Exception

### ISSUE THREAD

**Issue by HenryTheSir** [Graylog2/graylog2-server#9697]
API Endpoint /api/system/stats throws exception

## Expected Behavior

Working API Endpoint

## Current Behavior
First try:
![grafik](https://user-images.githubusercontent.com/11004513/101018437-ca7e9c00-356b-11eb-82c8-4f00a1a1f1f6.png)

second try:
![grafik](https://user-images.githubusercontent.com/11004513/101018386-bb97e980-356b-11eb-80f1-0ce2900cff72.png)

## Steps to Reproduce (for bugs)

1. Open API Endpoint
2. Open API Endpoint second time
3.
4.

## Your Environment

* Graylog Version: 3.3.8
* Java Version:  AdoptOpenJDK 11.0.7
* Elasticsearch Version: 6.8
* MongoDB Version: %
* Operating System: % 
* Browser version: %

**Comment by asachs01** [comment]
@HenryTheSir I'm not seeing the error on `/api/system/stats` that you're seeing, so this seems to be environmental and not an issue with the product itself:

<details>
  <summary>curl Graylog /stats endpoint</summary>
<pre>
curl -u $GRAYLOG_API_TOKEN http://logs00.example.net:9000/api/system/stats | jq .                                                                                                                           
Enter host password for user 'redacted':
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7864  100  7864    0     0   247k      0 --:--:-- --:--:-- --:--:--  247k
</pre>
<pre>
{
  "fs": {
    "filesystems": {
      "/usr/share/graylog-server/plugin": {
        "path": "/usr/share/graylog-server/plugin",
        "mount": "/",
        "dev": "/dev/mapper/ubuntu--vg-ubuntu--lv",
        "type_name": "local",
        "sys_type_name": "ext4",
        "total": 104623726592,
        "free": 62457602048,
        "available": 57098960896,
        "used": 42166124544,
        "used_percent": 43,
        "inodes_total": 6520832,
        "inodes_free": 6352958,
        "inodes_used": 167874,
        "inodes_used_percent": 2,
        "disk_reads": 105905,
        "disk_writes": 1556130,
        "disk_read_bytes": 4612654080,
        "disk_write_bytes": 8948936704,
        "disk_queue": -1,
        "disk_service_time": -1
      },
      "/var/lib/graylog-server": {
        "path": "/var/lib/graylog-server",
        "mount": "/",
        "dev": "/dev/mapper/ubuntu--vg-ubuntu--lv",
        "type_name": "local",
        "sys_type_name": "ext4",
        "total": 104623726592,
        "free": 62457602048,
        "available": 57098960896,
        "used": 42166124544,
        "used_percent": 43,
        "inodes_total": 6520832,
        "inodes_free": 6352958,
        "inodes_used": 167874,
        "inodes_used_percent": 2,
        "disk_reads": 105905,
        "disk_writes": 1556130,
        "disk_read_bytes": 4612654080,
        "disk_write_bytes": 8948936704,
        "disk_queue": -1,
        "disk_service_time": -1
      },
      "/var/lib/graylog-server/journal": {
        "path": "/var/lib/graylog-server/journal",
        "mount": "/",
        "dev": "/dev/mapper/ubuntu--vg-ubuntu--lv",
        "type_name": "local",
        "sys_type_name": "ext4",
        "total": 104623726592,
        "free": 62457602048,
        "available": 57098960896,
        "used": 42166124544,
        "used_percent": 43,
        "inodes_total": 6520832,
        "inodes_free": 6352958,
        "inodes_used": 167874,
        "inodes_used_percent": 2,
        "disk_reads": 105905,
        "disk_writes": 1556130,
        "disk_read_bytes": 4612654080,
        "disk_write_bytes": 8948936704,
        "disk_queue": -1,
        "disk_service_time": -1
      },
      "/usr/share/graylog-server/bin": {
        "path": "/usr/share/graylog-server/bin",
        "mount": "/",
        "dev": "/dev/mapper/ubuntu--vg-ubuntu--lv",
        "type_name": "local",
        "sys_type_name": "ext4",
        "total": 104623726592,
        "free": 62457602048,
        "available": 57098960896,
        "used": 42166124544,
        "used_percent": 43,
        "inodes_total": 6520832,
        "inodes_free": 6352958,
        "inodes_used": 167874,
        "inodes_used_percent": 2,
        "disk_reads": 105905,
        "disk_writes": 1556130,
        "disk_read_bytes": 4612654080,
        "disk_write_bytes": 8948936704,
        "disk_queue": -1,
        "disk_service_time": -1
      }
    }
  },
  "jvm": {
    "version": "1.8.0_275",
    "vm_name": "OpenJDK 64-Bit Server VM",
    "vm_version": "25.275-b01",
    "vm_vendor": "Private Build",
    "spec_name": "Java Virtual Machine Specification",
    "spec_version": "1.8",
    "spec_vendor": "Oracle Corporation",
    "start_time": 1606975620956,
    "mem": {
      "heap_init": 2147483648,
      "heap_max": 2040135680,
      "non_heap_init": 2555904,
      "non_heap_max": -1,
      "direct_memory_max": 2040135680
    },
    "input_arguments": [
      "-Xms2g",
      "-Xmx2g",
      "-XX:NewRatio=1",
      "-XX:+ResizeTLAB",
      "-XX:+UseConcMarkSweepGC",
      "-XX:+CMSConcurrentMTEnabled",
      "-XX:+CMSClassUnloadingEnabled",
      "-XX:-OmitStackTraceInFastThrow",
      "-XX:+UseParNewGC",
      "-Dlog4j.configurationFile=file:///etc/graylog/server/log4j2.xml",
      "-Djava.library.path=/usr/share/graylog-server/lib/sigar",
      "-Dgraylog2.installation_source=deb"
    ],
    "boot_class_path": "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes",
    "class_path": "/usr/share/graylog-server/graylog.jar",
    "system_properties": {
      "awt.toolkit": "sun.awt.X11.XToolkit",
      "file.encoding.pkg": "sun.io",
      "java.specification.version": "1.8",
      "log4j.configurationFile": "file:///etc/graylog/server/log4j2.xml",
      "sun.cpu.isalist": "",
      "sun.jnu.encoding": "UTF-8",
      "java.class.path": "/usr/share/graylog-server/graylog.jar",
      "java.vm.vendor": "Private Build",
      "sun.arch.data.model": "64",
      "java.vendor.url": "http://java.oracle.com/",
      "user.timezone": "Etc/UTC",
      "os.name": "Linux",
      "java.vm.specification.version": "1.8",
      "graylog2.installation_source": "deb",
      "user.country": "US",
      "sun.java.launcher": "SUN_STANDARD",
      "sun.boot.library.path": "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64",
      "sun.java.command": "/usr/share/graylog-server/graylog.jar server -f /etc/graylog/server/server.conf -np",
      "io.netty.native.workdir": "/var/lib/graylog-server/libnative",
      "org.glassfish.grizzly.DEFAULT_MEMORY_MANAGER": "org.glassfish.grizzly.memory.HeapMemoryManager",
      "sun.cpu.endian": "little",
      "user.home": "/var/lib/graylog-server",
      "user.language": "en",
      "java.specification.vendor": "Oracle Corporation",
      "java.home": "/usr/lib/jvm/java-8-openjdk-amd64/jre",
      "file.separator": "/",
      "line.separator": "\n",
      "java.vm.specification.vendor": "Oracle Corporation",
      "java.specification.name": "Java Platform API Specification",
      "java.awt.graphicsenv": "sun.awt.X11GraphicsEnvironment",
      "io.netty.native.deleteLibAfterLoading": "false",
      "sun.boot.class.path": "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes",
      "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
      "java.runtime.version": "1.8.0_275-8u275-b01-0ubuntu1~20.04-b01",
      "user.name": "graylog",
      "path.separator": ":",
      "os.version": "5.4.0-56-generic",
      "java.endorsed.dirs": "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed",
      "java.runtime.name": "OpenJDK Runtime Environment",
      "file.encoding": "UTF-8",
      "java.vm.name": "OpenJDK 64-Bit Server VM",
      "java.vendor.url.bug": "http://bugreport.sun.com/bugreport/",
      "java.io.tmpdir": "/tmp",
      "java.version": "1.8.0_275",
      "user.dir": "/",
      "os.arch": "amd64",
      "java.vm.specification.name": "Java Virtual Machine Specification",
      "java.awt.printerjob": "sun.print.PSPrinterJob",
      "sun.os.patch.level": "unknown",
      "java.util.logging.manager": "org.apache.logging.log4j.jul.LogManager",
      "java.library.path": "/usr/share/graylog-server/lib/sigar",
      "java.vm.info": "mixed mode",
      "java.vendor": "Private Build",
      "java.vm.version": "25.275-b01",
      "java.ext.dirs": "/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext",
      "sun.io.unicode.encoding": "UnicodeLittle",
      "java.class.version": "52.0"
    },
    "garbage_collectors": [
      "ParNew",
      "ConcurrentMarkSweep"
    ],
    "memory_pools": [
      "Code Cache",
      "Metaspace",
      "Compressed Class Space",
      "Par Eden Space",
      "Par Survivor Space",
      "CMS Old Gen"
    ]
  },
  "network": {
    "primary_interface": "ens18",
    "interfaces": {
      "lo": {
        "name": "lo",
        "addresses": [
          "127.0.0.1"
        ],
        "mac_address": "00:00:00:00:00:00",
        "mtu": 65536,
        "interface_stats": {
          "rx_packets": 285722,
          "rx_errors": 0,
          "rx_dropped": 0,
          "rx_overruns": 0,
          "rx_frame": 0,
          "tx_packets": 285722,
          "tx_errors": 0,
          "tx_dropped": 0,
          "tx_overruns": 0,
          "tx_carrier": 0,
          "tx_collisions": 0,
          "rx_bytes": 317801560,
          "tx_bytes": 317801560
        }
      },
      "ens18": {
        "name": "ens18",
        "addresses": [
          "192.168.1.1"
        ],
        "mac_address": "00:00:00:00:00:00",
        "mtu": 1500,
        "interface_stats": {
          "rx_packets": 3449069,
          "rx_errors": 0,
          "rx_dropped": 16160,
          "rx_overruns": 0,
          "rx_frame": 0,
          "tx_packets": 3182984,
          "tx_errors": 0,
          "tx_dropped": 0,
          "tx_overruns": 0,
          "tx_carrier": 0,
          "tx_collisions": 0,
          "rx_bytes": 1973817153,
          "tx_bytes": 1881236470
        }
      }
    },
    "tcp": {
      "active_opens": 955,
      "passive_opens": 114,
      "attempt_fails": 812,
      "estab_resets": 1,
      "curr_estab": 109,
      "in_segs": 3188731,
      "out_segs": 3997925,
      "retrans_segs": 62,
      "in_errs": 0,
      "out_rsts": 934
    }
  },
  "os": {
    "load_average": [
      2.27,
      2.18,
      1.35
    ],
    "uptime": 32214,
    "processor": {
      "model": "Common KVM processor",
      "vendor": "Intel",
      "mhz": 3503,
      "total_cores": 4,
      "total_sockets": 2,
      "cores_per_socket": 2,
      "cache_size": 16384,
      "sys": 0,
      "user": 1,
      "idle": 93,
      "stolen": 0
    },
    "memory": {
      "total": 8348459008,
      "free": 135557120,
      "free_percent": 42,
      "used": 8212901888,
      "used_percent": 57,
      "actual_free": 3506712576,
      "actual_used": 4841746432
    },
    "swap": {
      "total": 0,
      "free": 0,
      "used": 0
    }
  },
  "process": {
    "pid": 1051,
    "open_file_descriptors": 193,
    "max_file_descriptors": 64000,
    "cpu": {
      "percent": 4,
      "sys": 122480,
      "user": 544100,
      "total": 666580
    },
    "memory": {
      "total_virtual": 6140907520,
      "resident": 1630957568,
      "share": 29020160
    }
  }
}
</pre>
</details>
Can you elaborate more on how you're trying to access the endpoint? Have you tried running a curl to see if you get the same error?

**Comment by HenryTheSir** [comment]
I think the JDK is the reason. 

https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.management/share/classes/sun/management/RuntimeImpl.java#L100

Can you retest with jdk11 @asachs01 ?

**Comment by asachs01** [comment]
Ah, yep. Openjdk11 produces the same error. cc @bernd & team to confirm. They'll be the best folks to determine what changes we need to make to support Java 11.

**Comment by bernd** [comment]
This has been fixed in #9840. Please update to 4.1 or newer. Thank you!
