### ISSUE TITLE
Make Graylog 4.0 HTTP Auth support Roles header

### ISSUE THREAD

**Issue by wxiaoguang** [Graylog2/graylog2-server#9702]
## What?

In SSO plugin for 3.x, there are two headers: `Remote-User` and `Roles`

But in Graylog 4.0, the SSO plugin is removed, the built-in HTTP Auth only supports `Remote-User`

https://github.com/Graylog2/graylog2-server/blob/f35df42e165ac570b8b27de3f8eeac85e74ed610/graylog2-server/src/main/java/org/graylog2/security/headerauth/HTTPHeaderAuthConfig.java#L32

## Why?

Users created by HTTP Auth should have correct roles.

## Your Environment

* Graylog Version: 4.0

**Comment by cameronattard** [comment]
+1, this feature is very important to us.

**Comment by wxiaoguang** [comment]
Hello, is there a plan or not? If no plan (or by design), I think the issue can be closed.
