### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by arrmo** [Graylog2/graylog2-server#9707]
Hi,

I have been running v3.3 of Graylog for a while, no issues at all. Just upgraded today to v4.0, and now my access to the web interface is broken (can't log in). I checked the Chrome DevTools console, and I see this new error. Any suggestions of how to correct it?
```
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Thanks!

## Current Behavior
As above - I can no longer log in to the web console. Here is the (recurring) error message, from Chrome DevTools,
```
Access to XMLHttpRequest at 'http://192.168.2.64:9000/api/system/sessions' from origin 'http://linuxserver.home:9000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

No issues before (on v3.3).

## Possible Solution
Did try editing Apache2 (conf file), adding (from some searching),
```
Header always set Access-Control-Allow-Origin "*"
```

But no change in results.

## Steps to Reproduce (for bugs)
Just trying to log in to the web interface.

## Your Environment
* Graylog Version: v4.0 (v3.3 was fine, no issues)
* Java Version: openjdk 11.0.9.1 2020-11-04
* Elasticsearch Version: N/A
* MongoDB Version: N/A
* Operating System: Ubuntu 20.10
* Browser version: Chrome (current)

**Comment by asachs01** [comment]
@arrmo can you try adding this attribute to your config, restart and let us know the results?

`http_enable_cors = true`

I suspect that this is likely the issue. As of 4.0, we disable cross origin requests by default https://docs.graylog.org/en/4.0/pages/upgrade/graylog-4.0.html#disabled-cross-origin-requests-by-default.

**Comment by arrmo** [comment]
Yep, that fixed it - thanks! Does the default need to go back to true?

In any case, appreciate the help!

**Comment by asachs01** [comment]
I can't really comment on whether or not we'd consider defaulting to true. I'd imagine there's a reason for defaulting to false, but that's probably better explained by one of our engineers.

**Comment by arrmo** [comment]
NP, appreciate it. Thanks again for the help.
