### ISSUE TITLE
Graylog 4.0 LDAP login failed

### ISSUE THREAD

**Issue by anatoly-kryzhanovsky** [Graylog2/graylog2-server#9710]
## Expected Behavior
exists user can successfully login with their LDAP credential

## Current Behavior
on the 'User Login Test' section i see 'login failed
on the login screen i see 'Invalid credentials, please verify them and retry'

## Possible Solution
no idea

## Steps to Reproduce (for bugs)
1.  i already have graylog 3.3.8 runned inside docker (actually inside k8s), configured to use  LDAP authenticator
2.  i updated image spec to use last image (4.0.1)
3.  elasticsearch and mongo has actual version (checked by documentation)
4.  after new image was downloaded and service become available i can reach login ui and login via internal user 
5.  i see message about LDAP settings need to be reviewed
6.  i double check parameters and it is ok. also i try to 'Test server connection' in 'Server Connection Check' section - it is ok
![image](https://user-images.githubusercontent.com/15654012/101357122-74cf2a00-38b2-11eb-8a8c-2171feff3165.png)

7.  i double check parameter for user sync and it is also ok, but then i try to 'User Login Test' i receive message 'Login failed'
i try use different username that exists in LDAP, double check password - no luck. If i try to input not existing user i receive another message - 'User does not exist'.

![image](https://user-images.githubusercontent.com/15654012/101357427-d7c0c100-38b2-11eb-8e3b-efba7dd7361d.png)
![image](https://user-images.githubusercontent.com/15654012/101357452-e14a2900-38b2-11eb-9dd5-ab9b227d360f.png)

## Context
so i can't login using LDAP account, but still can login using internal authenticator...

## Your Environment

* Graylog Version: 4.0.1
* Java Version: openjdk version 1.8.0_275
* Elasticsearch Version: 7.10.0
* MongoDB Version: 4.4.2
* Operating System: ubuntu 
* Browser version: opera 72

**Comment by anatoly-kryzhanovsky** [comment]
**UPDATE 1**

i try to deploy same environment in docker locally - same result: i can connect to server without problem, but i cant validate user connection during setup and i can login via LDAP user

**Comment by jothoma1** [comment]
Same problem here after upgrading to graylog 4

**Comment by namaiiee2222** [comment]
Any Update?
I've got same issue with graylog 4.0.2

**Comment by namaiiee2222** [comment]
> Any Update?
> I've got same issue with graylog 4.0.2

The problem is with usernames with "."
For example username: test, is ok but username: "test.test" has login failed massage :(

**Comment by jothoma1** [comment]
Graylog 4.0.6 just arrived but issue is still present
it prevent my team to log on... really bad :( 
for us it's not a "." problem our username did not have a "."

**Comment by jothoma1** [comment]
Graylog 4.0.7 still nothing. Really bad, some of our users can't login anymore

**Comment by jothoma1** [comment]
@bernd yes it's activated

**Comment by jothoma1** [comment]
@bernd here is a debug log from an AD user which is exactly correct in sending its password but cannot log in into Graylog

![image](https://user-images.githubusercontent.com/19167503/124107303-63738800-da65-11eb-9dd8-9c2862a77b39.png)

**Comment by patrickmann** [comment]
@jothoma1 I was also unable to repro the behavior using OpenLDAP and the Graylog 4.0.9 docker image. Unfortunately the trace is not helpful - it just confirms that authentication fails due to missing or invalid credentials. This happens under the control of the widely used Apache Shiro library, so it is unlikely that a new bug has been introduced here. 

We have seen similar issues in the past, due to misconfigured LDAP auth configuration settings, e.g. wrong Search Base DN.

To narrow this down:
- Does user login test (in auth configuraton) fail for all users, or only some?
If it is failing for all users, please double-check all of the LDAP user synchronization settings
- Verify the user data with a different tool, e.g. ldapsearch. Do results look good and do they match the user synchronization settings?

**Comment by patrickmann** [comment]
Closing due to lack of feedback - issue is not actionable without further information.
Please re-open if problem still exists.
