### ISSUE TITLE
 Nodes with too long GC pauses

### ISSUE THREAD

**Issue by sanketn1990** [Graylog2/graylog2-server#972]
Hello friends,

I am using graylog2 on production environment with 3 graylog2 servers processing aroung 1000msgs/second. From past couple of days my system crashes with a message 

There are Graylog2 nodes on which the garbage collector runs too long. Garbage collection runs should be as short as possible. Please check whether those nodes are healthy. (Node: 69929831-8b08-4a63-ae13-2b5906ff3ba1, GC duration: 2119 ms, GC threshold: 1000 ms)

Can you help me so as where I can change this parameter.

Thanks in advance

**Comment by joschi** [comment]
You can change the threshold in your `graylog2.conf` with the `gc_warning_threshold` setting (https://github.com/Graylog2/graylog2-server/blob/0.92.4/misc/graylog2.conf#L352-354).

For general support questions kindly use our [mailing list](https://groups.google.com/forum/#!forum/graylog2) or our [IRC channel](https://webchat.freenode.net/?channels=%23graylog2).

**Comment by sanketn1990** [comment]
this will just delay the notification time but will not solve the problem of long duration gc. thses are my jvm parameters of elastic search

/usr/bin/java -server -Djava.net.preferIPv4Stack=true -Des.config=/usr/local/etc/elasticsearch/elasticsearch.yml -Xms9570m -Xmx9570m -Xss256k -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Delasticsearch -Des.pidfile=/usr/local/var/run/glelastica01.pid -Des.path.home=/usr/local/elasticsearch -cp :/usr/local/elasticsearch/lib/*:/usr/local/elasticsearch/lib/sigar/* org.elasticsearch.bootstrap.Elasticsearch

can der be any changes that can be done?

**Comment by joschi** [comment]
@sanketn1990 Please use the [mailing list](https://groups.google.com/forum/#!forum/graylog2) or the [IRC channel](https://webchat.freenode.net/?channels=%23graylog2) for general support questions. Thanks!
