### ISSUE TITLE
Visual Indicator of Where Pipeline Rules are applied.

### ISSUE THREAD

**Issue by ChristopherKB** [Graylog2/graylog2-server#9724]
## What?

There is currently no way to see if a given pipeline rule is assigned to a pipeline without manually reviewing all pipelines. A visual indicator on the rules overview page would be a logical place to put such a feature.

A feature that allows you to sort by pipeline, or even search by pipelines would also be useful.

## Why?

An organization that uses pipelines, even moderately, quickly ends up with a large rule base. Maintenance of that rule base becomes difficult because you can't see where rules are applied.

A visual indicator on the rule overview page would allow users to see which pipelines would be affected by the change or removal of a rule. It would also allow users to know which rules may safely be deleted without affecting running pipelines.

## Your Environment

* Graylog Version: All
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by boosty** [comment]
Assigned @dulanism for documentation.

**Comment by dulanism** [comment]
Will talk to Mr. Chris Black about this.

**Comment by boosty** [comment]
@dulanism I guess for the docs you will mostly be interested in the resulting UI change. A preview can be found here: https://github.com/Graylog2/graylog2-server/pull/11507#issuecomment-954832493
