### ISSUE TITLE
Allow focussing widget to show it instead of widget grid

### ISSUE THREAD

**Issue by dennisoelkers** [Graylog2/graylog2-server#9727]
## What?

As a user, I want to be able to display a single widget in the most distraction-free way possible. I want it to be shown instead of the widget grid, taking up all available screen space (besides the search and side bar). This state should not be persisted when the view is searched. Triggering actions (like creating new widgets) will unfocus the widget and return to the grid.

## Why?

Focussing a widget allows the user to use as much screen space for a single task (e.g. reading a long list of logs or analyzing a complex chart) as possible.

## Your Environment

* Graylog Version:
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by kmerz** [comment]
Fixed with #9711
