### ISSUE TITLE
Update Amazon AMI

### ISSUE THREAD

**Issue by dennusb** [Graylog2/graylog2-server#973]
Hi,

I saw Graylog V1 is here :) Very cool. But can i easily update the existing (running) Amazon AMI's? Or do i need to start new ones?

**Comment by mariussturm** [comment]
Hi,
currently you have to restart a new vm, We are working on an update
procedure.

On 19 February 2015 at 14:14, dennusb <notifications@github.com> wrote:

> Hi,
>
> I saw Graylog V1 is here :) Very cool. But can i easily update the
> existing (running) Amazon AMI's? Or do i need to start new ones?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Graylog2/graylog2-server/issues/973>.
>



-- 
Developer

Tel.: +49 (0)40 609 452 077
Fax.: +49 (0)40 609 452 078

TORCH GmbH - A Graylog Company
Steckelhörn 11
20457 Hamburg
Germany

https://www.graylog.com <https://www.torch.sh/>

Commercial Reg. (Registergericht): Amtsgericht Hamburg, HRB 125175
Geschäftsführer: Lennart Koopmann (CEO)
