### ISSUE TITLE
Output to Syslog (UDP/TCP)

### ISSUE THREAD

**Issue by nycoon** [Graylog2/graylog2-server#974]
Hey,

it would be nice to forward some messages to other monitoring systems like Zenoss via the default syslog protocol. For GELF you need an seperate middleware (like logstash) to parse the data for this kind of systems.

Kind regards, Rene

**Comment by dfch** [comment]
duplicate #726

**Comment by dfch** [comment]
Hi René, I created a SYSLOG Output plugin, see #726 for source and download. Maybe this goes into the direction you need. RFC5424 implementation is currently not complete. Ronald
