### ISSUE TITLE
AWS Cloudtrails plugin broken in 1.0.0

### ISSUE THREAD

**Issue by rossesposito** [Graylog2/graylog2-server#975]
Using AWSInput-0.3.0.jar. Ensured my server.conf in /etc uses an absolute path to the plugin dir. Input does not appear in the dropdown list. The telemetry plugin does work.

I see this warning in the server log:

2015-02-19 17:34:49,035 WARN : org.graylog2.inputs.PersistedInputsImpl - Cannot instantiate persisted input. No such type [com.graylog2.input.AWSInput].

**Comment by joschi** [comment]
Thanks for reporting this! We've just updated the AWS plugin at https://www.graylog.org/resource/plugin/5453d4e0e4b0d324cb87ad5e/ for Graylog 1.0.0.
