### ISSUE TITLE
Migrate graylog2 v0.92 to graylog v1.0

### ISSUE THREAD

**Issue by scordone** [Graylog2/graylog2-server#977]
Hi,
Im about to migrate from v 0.92 to v 1.0 but i installed the v1.0 from the ova file, and i can't find a way to restore the snapshot from elasticsearch containing all my logs from v0.92 to the v1.0 since elasticsearch is not standalone and i can't curl it.
Can you please tell me if there is any way to migrate logs from one installation to the other? i can't affort to lose all this data.
Thanks in advance.

**Comment by SjonHortensius** [comment]
Why don't you just copy /var/lib/elasticsearch over?

**Comment by bernd** [comment]
You could also use the Elasticsearch snapshot/restore feature to do that. http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/modules-snapshots.html

Hope that helps!
