### ISSUE TITLE
Graylog 4.0 + Java 11 = WARNING: sun.reflect.Reflection.getCallerClass is not supported.

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#9802]
## Expected Behavior

Unsupported classes should not be used.

## Current Behavior

Running Graylog 4.0 with Java 11 generates following Warning

`WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.`

## Steps to Reproduce (for bugs)

1. Install Graylog 4.0.1 with Java 11
2. Start service
3. Check service status

## Your Environment

* Graylog Version: 4.0.1
* Java Version: openjdk version "11.0.9" 2020-10-20 LTS

**Comment by Seb35** [comment]
This is the same warning as in #7223 (just different Graylog version).

**Comment by shivamtiwari18** [comment]
Using Graylog 5  + Java 11 = WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
generate same error.

How to reslove this issue.

**Comment by loveyang2012** [comment]
> Using Graylog 5 + Java 11 = WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance. generate same error.
> 
> How to reslove this issue.

hahah

**Comment by bernd** [comment]
> Using Graylog 5 + Java 11 = WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance. generate same error.
> 
> How to reslove this issue.

We are working on a fix here: https://github.com/Graylog2/graylog2-server/pull/14884
