### ISSUE TITLE
Graylog not start with http_enable_tls

### ISSUE THREAD

**Issue by device-x** [Graylog2/graylog2-server#9807]
Graylog not start with http_enable_tls

I try run graylog 4.0.1 on centos 7 in container with java 1.8.0_102-b14

## Current Behavior
Errors in log
`Suppressed: com.google.common.util.concurrent.ServiceManager$FailedService: JerseyService [FAILED]`
`Caused by: java.security.GeneralSecurityException: org.bouncycastle.pkcs.PKCSException: unable to read encrypted data: JCE cannot authenticate the provider BC`

Full log with exeption in attach 
[graylog-error-log.txt](https://github.com/Graylog2/graylog2-server/files/5696801/graylog-error-log.txt)

## Possible Solution
Dirty fix possible
`wget https://oss.sonatype.org/content/repositories/releases/org/bouncycastle/bcpkix-jdk15on/1.64/bcpkix-jdk15on-1.64.jar`
`wget https://oss.sonatype.org/content/repositories/releases/org/bouncycastle/bcprov-jdk15on/1.64/bcprov-jdk15on-1.64.jar`

And put this jar's to /usr/java/jdk180_64_102/jre/lib/ext/

## Your Environment

* Graylog Version: 4.0.1
* Java Version: 1.8.0_102-b14
* Elasticsearch Version: 6.8.8
* MongoDB Version: 4.0.18
* Operating System: centos 7

**Comment by HenryTheSir** [comment]
Your Java Version Update seems quite old. Can you Update your Java Version to a newer minor Update?

**Comment by device-x** [comment]
Hell, really, successfully run on openjdk version "1.8.0_202". 
Sorry about it

**Comment by mpfz0r** [comment]
Thanks @HenryTheSir and @device-x for your feedback :+1:
