### ISSUE TITLE
User cannot edit his own timezone setting

### ISSUE THREAD

**Issue by kmerz** [Graylog2/graylog2-server#9813]
## Expected Behavior
A user should be able to change his own timezone setting since it is not security relevant.

## Current Behavior
Right now the whole settings section is only visible for a admin user.

## Possible Solution
Display the settings section and only hide the Timeout section to the user.

## Notes
This is already fixed in 4.1 development

## Your Environment
* Graylog Version: 4.0

**Comment by bernd** [comment]
Fixed in #9813
