### ISSUE TITLE
Regression: universal/absolute/export requires limit field

### ISSUE THREAD

**Issue by jrunu** [Graylog2/graylog2-server#9817]
After an upgrade to 4.0.1 from 3.3.X unless a limit is specified /search/universal/absolute/export returns no content. 

## Expected Behavior
No Change in behaviour, returns all messages for the search query.

## Current Behavior
No content returned, with a HTTP 200

## Possible Solution

Current workaround, setting limit to 1000000000

## Steps to Reproduce (for bugs)
1. Go to the API Browser 
2. Select the "Legacy/Search/Absolute" Endpoint
3. Try a search with and without limit field 

## Your Environment

* Graylog Version: 4.0.1+6a0cc0b
* Elasticsearch Version: 7.10.1

**Comment by dennisoelkers** [comment]
Hey @jrunu,

thanks for reporting this! Which ES-version do you use with 4.0?

**Comment by jrunu** [comment]
Hi @dennisoelkers, we're running ES 7.10.1. That is actually quite a relevant piece of information to know, don't know why my mind blanked that.  I updated the issue as well.
