### ISSUE TITLE
legacy collector in dark mode unreadable ( `/system/collectors` )

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/graylog2-server#9819]
## Current Behavior
![image](https://user-images.githubusercontent.com/404238/102367306-e77a8c80-3fb9-11eb-9d1a-41722a91ea29.png)

it is impossible to read the text because it is white on white.

## Context
Even that is legacy - as long as we have them it should be usable. 

## Your Environment
* Graylog Version: 4

**Comment by edmundoa** [comment]
I backported the change into the 4.0 branch in https://github.com/Graylog2/graylog-plugin-collector/pull/174, since I consider this something to be fixed in the next bugfix release.
