### ISSUE TITLE
Graylog 3.3 repository broken

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#9827]
## Current Behavior

Official 3.3 repository broken.

```
graylog/x86_64/other_db        FAILED
https://packages.graylog2.org/repo/el/stable/3.3/x86_64/repodata/4f90da914494aa4f32d304328ea4d40ef1d5d73ea2d752b3d288b4d134239c9f-other.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found          ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
graylog/x86_64/filelists_db    FAILED
https://packages.graylog2.org/repo/el/stable/3.3/x86_64/repodata/b3898b0bb28c0dc41bef37f315cdd3a96963ec2fe34e9947d91098e3c665a86f-filelists.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found      ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
https://packages.graylog2.org/repo/el/stable/3.3/x86_64/repodata/b3898b0bb28c0dc41bef37f315cdd3a96963ec2fe34e9947d91098e3c665a86f-filelists.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
failure: repodata/b3898b0bb28c0dc41bef37f315cdd3a96963ec2fe34e9947d91098e3c665a86f-filelists.sqlite.bz2 from graylog: [Errno 256] No more mirrors to try.
https://packages.graylog2.org/repo/el/stable/3.3/x86_64/repodata/b3898b0bb28c0dc41bef37f315cdd3a96963ec2fe34e9947d91098e3c665a86f-filelists.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
```

## Steps to Reproduce (for bugs)

1. sudo rpm -Uvh https://packages.graylog2.org/repo/packages/graylog-3.3-repository_latest.rpm
2. sudo yum makecache

**Comment by asachs01** [comment]
@hulkk this doesn't seem like a bug IMO. I'm  able to spin up a CentOS box and retrieve the rpm package and install it without issue, as well as create the yum cache:

<img width="882" alt="CleanShot 2020-12-17 at 09 27 30@2x" src="https://user-images.githubusercontent.com/898627/102500283-2526f600-404a-11eb-8768-417e67311ddc.png">

This leads me to think this is an issue specific to your environment. Have you tried cleaning the yum cache or spinning up something like a Vagrant CentOS box to confirm that the official repo is indeed broken?

**Comment by hulkk** [comment]
Weird, first time had this issue and we are doing the installations using ansible so no manual steps. 

`Yum clean all` helped.
