### ISSUE TITLE
Broken link for Kafka input

### ISSUE THREAD

**Issue by florianvolle** [Graylog2/graylog2-server#983]
Version 1.0.0
System/ Nodes/ installed, available input types:

https://www.graylog.org/documentation/sending/kafka/ Should redirect to Kafka input on documentation page but Kafka input is missing in documentation.

**Comment by bernd** [comment]
Moving this to the 1.1.0 milestone because in 1.0 the Kafka input is only useful for radio. Once #322 is implemented, it should be documented.

**Comment by bernd** [comment]
Moving to 1.2.0 milestone so we can add the doc links once Graylog2/documentation#19 got implemented.
