### ISSUE TITLE
Elasticsearch 7.x queries expect "u" for year

### ISSUE THREAD

**Issue by mikkolehtisalo** [Graylog2/graylog2-server#9846]
After ES upgrade to 7.10 I found this from Graylog's logs:

`2020-12-26T16:29:14.464+02:00 WARN  [RestClient] request [POST http://logs:9200/_msearch?typed_keys=true] returned 1 warnings: [299 Elasticsearch-7.10.1-1c34507e66d7db1211f66f3513706fdf548736aa "'y' year should be replaced with 'u'. Use 'y' for year-of-era. Use new java.time date format specifiers."]`

Everything probably works, and I have no clue what causes it. Probably some automatically built ElasticSearch query is in fact incorrect?

**Comment by dennisoelkers** [comment]
Hey @mikkolehtisalo,

thanks for reporting this. We are already aware of this issue and tracking it in #9690.
