### ISSUE TITLE
Output Plugin configuration cannot be changed and Output Plugin cannot be paused

### ISSUE THREAD

**Issue by dfch** [Graylog2/graylog2-server#985]
When I configure an Output Plugin and I set the configuration on the initial configuration dialogue I cannot change that configuration after it is once saved  (it can only be deleted). However with Input Plugins it is possible to change a configuration after it is initially saved.
In addition, an Output Plugin cannot be paused (only deleted), which is in contrast to Input Plugins again.

This really reduces the functionality of Output Plugins. E.g. I have an output forwarder sending messages to a specific target system/host, I have to delete the complete output just to change target the system/host and might lose messages.
Pausing an Output Plugin also makes sense where I want to switch the output to different targets programmatically (e.g. to an alternative backup output). By having to re-create the Output Plugins over and over again I most certainly have to re-specify credentials (which would not be necessary if I was able to pause and resume as with the Input Plugin and where the programme/script might have the actual credentials of the to be configured output (cf. ISO27001 *segregation of duties*)).

**Comment by kroepke** [comment]
This is fixed in the 1.1 betas with https://github.com/Graylog2/graylog2-web-interface/pull/1230

**Comment by kroepke** [comment]
Pausing is still not supported, I've opened https://github.com/Graylog2/graylog2-server/issues/1191 to track that feature request.
