### ISSUE TITLE
/sources endpoint removed?

### ISSUE THREAD

**Issue by asachs01** [Graylog2/graylog2-server#9853]
## Expected Behavior

I should be able to see the `/sources` api endpoint as in 3.3.8

<img width="1775" alt="CleanShot 2020-12-29 at 10 13 37@2x" src="https://user-images.githubusercontent.com/898627/103294512-ff8ddb00-49bf-11eb-8135-b7dc16ec5175.png">

## Current Behavior

The `/sources` endpoint seems to have been removed, or at the very least doesn't show up in the API browser in 4.X

<img width="1766" alt="CleanShot 2020-12-29 at 10 26 12@2x" src="https://user-images.githubusercontent.com/898627/103294678-50053880-49c0-11eb-9dd3-b4e3218baa08.png">

No mention of removing this endpoint is present in the changelog. 

Given that we're working with a customer to use this endpoint, not having it around in 4.X (which the customer is on), is hampering our ability to support them and their use case.

**Comment by dennisoelkers** [comment]
Hey @asachs01,

yes, the endpoint was removed, as the "Sources" page was migrated from being a snowflake to use our dashboard functionality instead. We [removed a couple of other endpoints for 4.0](https://github.com/Graylog2/graylog2-server/blob/master/UPGRADING.rst#api-endpoint-removals), but I forgot to include the removal of `/sources` in there. Sorry for that! I will catch up on that.

**Comment by asachs01** [comment]
Hi @dennisoelkers, no sweat! Thanks for the clarification.
