### ISSUE TITLE
AlarmCallback Plugin configuration cannot be changed and AlarmCallback Plugin cannot be paused

### ISSUE THREAD

**Issue by dfch** [Graylog2/graylog2-server#986]
When I configure an AlarmCallback Plugin and I set the configuration on the initial configuration dialogue I cannot change that configuration after it is once saved  (it can only be deleted). However with Input Plugins it is possible to change a configuration after it is initially saved.
In addition, an AlarmCallback Plugin cannot be paused (only deleted), which is in contrast to Input Plugins again.

This really reduces the functionality of AlarmCallback Plugins. E.g. I have an alarm sending messages to a specific target group (of operators depending on the time/shift), I have to delete the complete AlarmCallback just to change target the group and might lose messages.
Pausing an AlarmCallback Plugin also makes sense where I want to switch the alarm to different targets programmatically (e.g. to an alternative backup alarm system). By having to re-create the AlarmCallback Plugins over and over again I most certainly have to re-specify credentials (which would not be necessary if I was able to pause and resume as with the Input Plugin and where the programme/script might have the actual credentials of the to be configured AlarmCallback (cf. ISO27001 *segregation of duties*)).

**Comment by dennisoelkers** [comment]
Editing alarm callbacks is possible with 2.0 now. Closing this in favor of #1015.
