### ISSUE TITLE
UI performance of stream overview page worse after upgrading to graylog 3.3

### ISSUE THREAD

**Issue by JTabel** [Graylog2/graylog2-server#9869]
## Expected Behavior

The stream overview page should load in a timely manner. 

## Current Behavior

The page takes too long to load. This is a rather subjective assumption, but we are using the stream overview page as a measurement of our graylog performance for our users, so we have some data. We usually expect the page to load within 3 seconds 99% of the time. Currently, this measurement shows us that the page takes around 5 seconds to load. When querying the list of streams via the API, it is quite fast, so we expect it to just be slow rendering on the webpage or additional API requests done while loading the page. We have a total of 214 streams, which definitely will factor in here, but shouldn't slow it down that much. Also the amount of streams hasn't changed after the upgrade.

## Possible Solution

We currently only see two possible solutions: 

1. Upgrade graylog to 4.0, which introduces pagination. This might fix the situation, but is no guarantee. We also need to plan the upgrade since it is a quite large graylog installation used quite heavily by our developers.
2. Add more hardware to the cluster. Obviously this might take time.

## Steps to Reproduce (for bugs)

1. Measure load time of stream overview page with graylog 3.1 and a large amount of streams
2. Upgrade graylog to 3.3
3. Measure load time of stream overview page with graylog 3.3 and a large amount of streams

## Context

We are doing internal SRE for our graylog installation, since it is an essential tool in our logging chain. After the upgrade we first noticed that our measurement wasn't working at all, so fixed our probe. After the probe was fixed we noticed a worse performance, which was also already reported separately by users. Since especially the UI performance is user facing and get's noticed first, we do not want to make a compromise by just increasing our success condition for the measurement.

## Your Environment

* Graylog Version: 3.3.8
* Java Version: Private Build 1.8.0_222 on Linux 4.15.0-66-generic
* Elasticsearch Version: 6.8.13
* MongoDB Version: 3.6.12-3.2.xenial
* Operating System: Ubuntu 18.04
* Browser version: Chrome (current version)

**Comment by dennisoelkers** [comment]
Hey @JTabel!

Thanks a lot for your feedback! Can you do a profiling run in your browser (preferably Chrome/Chromium) and send the snapshot to us? You could either attach it to this issue or (for privacy concerns) send it via mail.

**Comment by JTabel** [comment]
Sure, is there a specific mail address to use or can I use the one in your profile?

**Comment by dennisoelkers** [comment]
The one in my profile is fine. Thanks a lot! :)
