### ISSUE TITLE
AlarmCallback cannot validate configuration settings before it is first invoked

### ISSUE THREAD

**Issue by dfch** [Graylog2/graylog2-server#987]
When you configure an AlarmCallback Plugin and enter the configuration, this configuration is only evaluated when the AlarmCallback is actually invoked the first time (based on an alert). This is because `initialize(final Configuration configuration)` and `checkConfiguration()` are not called before first invocation and I see no other means for the plugin to verify this configuration.

This means an operator (or script) cannot verify the proper setup of an AlarmCallback (notably the checking of credentials and target system) except for _actually firing_ an alert which might pose unforeseen side-effects in production environments.

**Comment by dfch** [comment]
@FabioQ are you sure that your commit  https://github.com/FabioQ/graylog2-server/commit/6762e903ee01865129bfe5affdcb8bc6fb52f119 will fix this issue. As gar as I can see your Code Deals with Radio nodes but Not with AlarmCallback Plugins. Sorry if I have eben mistaken. Ronald

**Comment by kroepke** [comment]
The push to FabioQ/graylog2-server seem to have triggered a few hooks because the original commits were referring to the wrong repository (server vs web-interface). None of them pertain to the updated issues. :(

**Comment by dfch** [comment]
Is there any plan to address this issue?

*update to this issue* [checkConfiguration](https://github.com/Graylog2/graylog2-server/blob/a5cec6ee646044d55789cd516569fb7a56a478fd/graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/alarms/callbacks/AlarmCallback.java#L45) seems to get never called at all (a [search](https://github.com/Graylog2/graylog2-server/search?utf8=%E2%9C%93&q=checkConfiguration&type=Code) reveals no hits for an AlarmCallback). Instead the plugin is [created and directly called every time](https://github.com/Graylog2/graylog2-server/blob/f7ba3529bd3f72f8c565b52cb0edbee5f9067f78/graylog2-server/src/main/java/org/graylog2/periodical/AlertScannerThread.java#L102-L107) an alert is triggered (also for the [DummyAlert](https://github.com/Graylog2/graylog2-server/blob/d713637601609418895647c2463d349834c172c4/graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertReceiverResource.java#L167-L168))
