### ISSUE TITLE
Dashboard URLs which contain a query param for an invalid focused widget can result in an unresponsive page.

### ISSUE THREAD

**Issue by linuspahl** [Graylog2/graylog2-server#9881]
## Description
This bug only exists on the current master branch. We recently implemented the possibility to focus a widget. Focusing a widget will add its id as a query param to the URL.

This can result in a broken / unresponsive page  in some cases:
- Create a new dashboard (but do not save it), add a widget, focus the widget, reload the page.
- On a dashboard with e.g. two pages, focus a widget on the second dashboard page and reload the application.
- On a dashboard with e.g. two pages, focus a widget on the first page, open the second page.
- On a dashboard or saved search focus a widget, copy the link, remove the widget, save the dashboard or saved search, open the copied link.
![dashboard](https://user-images.githubusercontent.com/46300478/104183837-dedb7180-5412-11eb-83d3-868c4c4c8760.gif)

**Comment by dennisoelkers** [comment]
I can simplify the error case a bit:

1. Open Dashboard
2. Focus a widget
3. Change focused widget id in URL slightly

It looks like we need to handle an invalid widget id a bit differently and check if the focused widget exists.
