### ISSUE TITLE
Debian packages do not allow for privileged ports < 1024

### ISSUE THREAD

**Issue by simmcomm** [Graylog2/graylog2-server#991]
Having installed GA 1.0 release from debian packages, users graylog and graylog-web got created, however those users have no access to privileged ports < 1024.

Thus when trying to run the web interface on port 80 or 443 it won't start up, as well is Graylog unable to attach to Syslog port 514.

There seems to be a solution with authbind available. It should be considered for the package installation.

**Comment by bernd** [comment]
Yes, we try to avoid running the Graylog services with superuser privileges. The os packages are prepared to be configured with authbind. (see `GRAYLOG_COMMAND_WRAPPER` in `/etc/default/graylog-server` for example)

I would recommend to use a web server like nginx to proxy requests to the web interface. This also makes it easier to configure ssl for the web interface.

If you really have to use the 514 port for syslog, you might consider using iptables to redirect the traffic to a different port.

**Comment by reighnman** [comment]
The other option is to give permission to the java process directly with setcap e.g.

setcap 'cap_net_bind_service=+ep' /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java

**Comment by bernd** [comment]
Thanks for the `setcap` hint! Closing this, please re-open if needed.

**Comment by razvanphp** [comment]
Just out of curiosity, why do you recommend using nginx instead of the buit-in HTTP server?

We had some problems in the past with Gateway Timeout when graylog is slow, but other than that, the only "minus" I see is that you can't force redirect 80 -> 443 easily.
