### ISSUE TITLE
Add prometheus metrics endpoint with proper tag support

### ISSUE THREAD

**Issue by kroepke** [Graylog2/graylog2-server#9914]
## What?
Add a Prometheus metrics endpoint to the standard of Graylog.
The exposed metrics should support tags for time series wherever they make sense, to more cleanly map to what Prometheus users expect to see.
It should be possible to bind the metrics endpoint to a separate address/port than the API, to allow for unauthenticated scraping from exporters/Prometheus. Oftentimes this will be either an internal monitoring network or localhost.

## Why?
Exposing metrics in a flat way makes it difficult to work with using Prometheus and it is easier to flatten them for systems that do not have tag support, than the other way around.
Prometheus is a very common choice for collecting metrics, and Graylog should support it out of the box, without having to install an extra plugin that only solves half the problem.

## Related issues:
https://github.com/graylog-labs/graylog-plugin-metrics-reporter/issues/29
https://github.com/graylog-labs/graylog-plugin-metrics-reporter/issues/35
https://github.com/graylog-labs/graylog-plugin-metrics-reporter/issues/28

## Your Environment

* Elasticsearch Version: 4.0

**Comment by mpfz0r** [comment]
It might make sense to consider using https://micrometer.io/  instead of coding this directly for prometheus

**Comment by jalogisch** [comment]
[z#844502]

**Comment by kroepke** [comment]
We should definitely consider various options, yes!

**Comment by l0calhost** [comment]
+1 fpr micrometer consideration, metric push mechanism would be a second big benefit to the tags.
