### ISSUE TITLE
Message processing gets blocked - thread dump included

### ISSUE THREAD

**Issue by hulkk** [Graylog2/graylog2-server#9917]
## Expected Behavior

Message processing should never get blocked, there should be some kind of method for self healing, e.g. timeout. And if self healing does not work, there should be error handling which would at least log the problem.

## Current Behavior

In some cases message processing gets blocked, please see screenshot and thread dump below. No events in user interface or logs.

Last time this kind of behaviour was related to GELF TCP outputs #9064
This time the GELF TCP outputs are checked, tested and restarted and it should not be the cause this time. Also Graylog service and the server has been restarted.

![Screenshot 2021-01-15 at 17 17 46 - output 0 copy](https://user-images.githubusercontent.com/24830359/104753215-5a655780-5760-11eb-81c8-079bda7c565a.png)

Thread dump of node 060bfd4c / redacted-graylog018.redacted Taken at Fri Jan 15 2021 17:17:55 GMT+0200

[thread-dump-2021-01-15.txt](https://github.com/Graylog2/graylog2-server/files/5821821/thread-dump-2021-01-15.txt)

## Your Environment

* Graylog Version: 3.3.8
* Java Version: openjdk version "1.8.0_272"

**Comment by hulkk** [comment]
This time issue was related to message processing rule in pipeline.

```
//    let message_masked = regex_replace("(.*\s)(Authorization)(.*)\,(.*)", to_string($message.message), "$1 $2: ***MASKED***, $4");
//    set_field("message", message_masked);
```

Commenting this resolved the issue. Graylog should be able to handle problematic prosesing rules without halting totally, or at least as a bare minimum Graylog should be able to indicate where the problem is.

**Comment by phaabe** [comment]
Same here with Graylog 4.0.2
I guess it is the same bug. 
**Current behavior**
* Create a few streams
* Create a new GELF output with TCP and TLS and assign one stream to it (everything works fine until here)
* Assign a second stream to same output (here it seems to break)
* GUI cannot show new logs anymore
* After restarting the graylog service everything works as configured

I can provide more information if needed.

**Comment by luk-kaminski** [comment]
The problem still seems to be present in 5.1.

It seems that the best way to reproduce it is to create a Gelf TCP Output, pointing to wrong address. Removing this output later on has a potential to make further damage.

Effects:
1. Buffers are stuck.
![Screenshot 2023-04-27 at 14-45-47 Graylog - Node c04934d6 _ lkaminski-graylog](https://user-images.githubusercontent.com/100699120/234885358-2fcb39f5-bd74-4142-a2d3-ac0ede54b8bd.png)
2. Messages do not land in ES/OS.
3. When accessed in debugger, messages tend to contain information about output, even if it was removed:
![Zrzut ekranu z 2023-04-27 15-47-18](https://user-images.githubusercontent.com/100699120/234885787-19315a58-c087-4221-ac2e-55bebeaa61bf.png)

4. OutputBufferProcessor seem to be stuck:
![Zrzut ekranu z 2023-04-27 14-47-11](https://user-images.githubusercontent.com/100699120/234885861-a1dfd2c7-68c5-4cb0-b872-6c1c6362c0df.png)

I am not familiar with that part of the codebase, so please take all the observations with reserve.

Restarting the GL server helps - messages from the journal are processed and land in ES/OS.

**Comment by bernd** [comment]
@luk-kaminski Can you post the exact steps you did to reproduce the issue? I can't reproduce it.

I am getting timeout messages but ingesting continues. And when I remove the output from a stream it's removed in upcoming messages.

```
org.graylog2.gelfclient.transport.GelfTcpTransport - Connection failed: connection timed out: /10.11.12.13:12300
```

**Comment by luk-kaminski** [comment]
Hi @bernd,

Here are the steps:
1. Run GL.
2. Check that all inputs are originally stopped.
3. Check that "All messages" Stream has no output added.
4. Check that all buffers are empty.
5. Create an incorrect Gelf output (i.e. to localhost, on port nobody is listening to).
6. Run random HTTP input.
7. Add Gelf output to "All messages" Stream.

There are the following GL log messages appearing now:
`2023-04-28 10:30:19,103 ERROR: org.graylog2.gelfclient.transport.GelfTcpTransport - Connection failed: Połączenie odrzucone: localhost/127.0.0.1:12201`
`2023-04-28 10:30:19,299 WARN : org.graylog2.buffers.processors.OutputBufferProcessor - Timeout reached. Not waiting any longer for stream output writer threads to complete.`
Output buffer starts filling.

8. Delete Gelf Output globally.

There are no more GL log messages.
Output buffer is still filling. Number of unprocessed messages grows.
No new documents are inserted into Elasticsearch.
Throughput on "All messages" Stream is still ~40msg/s, but I bet it will go to 0 when the output buffer fills, as it was previously.

Please let me know if you can reproduce it now.

**Comment by luk-kaminski** [comment]
Similar issue: https://github.com/Graylog2/graylog-plugin-enterprise/issues/4623

**Comment by bernd** [comment]
@luk-kaminski I can reproduce it now. Thank you! My message rate was too low. :smile:

**Comment by bernd** [comment]
@luk-kaminski I created a draft PR to fix the issue: https://github.com/Graylog2/graylog2-server/pull/15385
