### ISSUE TITLE
Search: Query Time Limit does not seem to validate in backend

### ISSUE THREAD

**Issue by kyleknighted** [Graylog2/graylog2-server#9935]
## Expected Behavior

Server should validate that the query time limit has not been exceeded

## Current Behavior

if a User has a defined Query Time Limit, they are still able to modify the URL directly to search past this limit.

- `/system/configurations` Query Time Limit set to `PT30M` (30 Minutes)
- `/search?q=&rangetype=relative&relative=2592000` 30 day relative search with a non-admin User account

I am getting results returned within our SMD Dev environment.
Upcoming updated UI will help solve some of these problems, but I am concerned that API access could still leak data past the limit.

* Graylog Version: `main` branch

**Comment by bernd** [comment]
@kyleknighted Duplicate or related to https://github.com/Graylog2/graylog2-server/issues/9487?

**Comment by kyleknighted** [comment]
@bernd thanks for bringing that issue to my attention, mine is a duplicate of yours. I will close it now
