### ISSUE TITLE
Qucik setup package not linked to on website

### ISSUE THREAD

**Issue by gzcwnk** [Graylog2/graylog2-server#995]
To get to the tgz package via wget I have to guess the version number, in this case 1.0.0. Really you should have a proper link, or allow a web browser to see what is in the directory so it can be determined and downloaded.

**Comment by joschi** [comment]
There is a valid and up-to-date download link in the docs at http://docs.graylog.org/en/latest/pages/installation.html#download-and-start-the-quick-setup-application (which the downloads page links to) but I agree that the download link could be more obvious.

**Comment by joschi** [comment]
I've added a direct download link to https://www.graylog.org/download/
