### ISSUE TITLE
Bad choice of color for actions after archiving in dark mode

### ISSUE THREAD

**Issue by HenryTheSir** [Graylog2/graylog2-server#9964]
![grafik](https://user-images.githubusercontent.com/11004513/105715489-f855e080-5f1d-11eb-8d72-66ab027a0b09.png)

## Expected Behavior
Good contrast to see which action is active

## Current Behavior
Bad contrast which does not show which action is active

## Possible Solution
change color

## Steps to Reproduce (for bugs)
1. Open Index Page and Edit Index Set
2. Change Retention Strategie to archive
3. 
4.

## Your Environment

* Graylog Version: 4.0 
* Java Version: 11 
* Elasticsearch Version:
* MongoDB Version:
* Operating System:
* Browser version:

**Comment by kyleknighted** [comment]
Hey @HenryTheSir thanks for bringing this to our attention!
Some of these more dynamic components hid from us during the theme transition and we will work on getting a resolution out for this as soon as we can.
