### ISSUE TITLE
repo fialire for RHEL7

### ISSUE THREAD

**Issue by gzcwnk** [Graylog2/graylog2-server#997]
failure: repodata/repomd.xml from graylog: [Errno 256] No more mirrors to try.
https://packages.graylog2.org/repo/el/7Server/1.0/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

**Comment by joschi** [comment]
We currently do not provide official packages for RHEL7 and CentOS 7, but you can use the ones provided for RHEL6. Please see Graylog2/fpm-recipes#2 for details.

**Comment by bastelfreak** [comment]
Hi,
are there any plans to update the mirror and add a RHEL7/CentOS7 directory? Otherwise it is not possible to use the puppetmodule for graylog2 on centos7.

**Comment by joschi** [comment]
@bastelfreak Please see the referenced issue.
