### ISSUE TITLE
Licence: Copyright owner MongoDB, Inc (?)

### ISSUE THREAD

**Issue by MMeent** [Graylog2/graylog2-server#9979]
Just to confirm: is MongoDB, Inc the owner of the copyright on Graylog? If not, could you please correct your LICENCE file?

**Comment by lennartkoopmann** [comment]
The copyright line refers to the copyright of the text of the license.

For example, the [GPLv3 license](https://www.gnu.org/licenses/gpl-3.0.en.html) has a similar line on top:

> Copyright © 2007 Free Software Foundation, Inc. <https://fsf.org/>
