### ISSUE TITLE
User-admin timezone is incorrect

### ISSUE THREAD

**Issue by SjonHortensius** [Graylog2/graylog2-server#998]
How should I correct the timezone for the admin-user? It is off by one hour (it used to be correct).

I use graylog 1.0.0

**Comment by joschi** [comment]
You can use the `root_timezone ` setting in the configuration file to change the timezone for the admin user (https://github.com/Graylog2/graylog2-server/blob/1.0.0/misc/graylog2.conf#L28-30).

**Comment by SjonHortensius** [comment]
thanks; that works fine

**Comment by varnav** [comment]
'root' is confusing as we're talking about admin everywhere else
