### ISSUE TITLE
Index Set

### ISSUE THREAD

**Issue by luweijun1992** [Graylog2/graylog2-server#9980]
Version: 4.0.2
ES: 7.10.2
Mongodb: v4.2.11
When I set a single index up to 20 documents, when the index has reached 20 documents, the index is not rotation; when I set a maximum of 20 indexes, the earliest index is not deleted after all more than 20. What's the matter, and what else do I need to set.
![image](https://user-images.githubusercontent.com/58923704/106093766-d94c8e00-616b-11eb-9aae-89cc14d180a4.png)

**Comment by hulkk** [comment]
Why would you want to rotate every 20 documents? Reasonable amount is around n*100.000 - 1.000.000 documents.

**Comment by luweijun1992** [comment]
> Why would you want to rotate every 20 documents? Reasonable amount is around n*100.000 - 1.000.000 documents.

I was just testing it, but it wasn't set up that way.

**Comment by bernd** [comment]
We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
