### ISSUE TITLE
drop_message need help

### ISSUE THREAD

**Issue by luweijun1992** [Graylog2/graylog2-server#9983]
I need to delete the type of message in the screenshot, what should I do? 
How to write the pipeline configuration file.
I use the following configuration, but it has no effect.
`rule "Drop Syslog Messages"`
`when`
`    contains(to_string($message.message), "User=_system_", true)`
`then`
`    drop_message();`
`end`
![image](https://user-images.githubusercontent.com/58923704/106121675-c7caac80-6192-11eb-9386-f27417257dab.png)

**Comment by jalogisch** [comment]
he @luweijun1992 

those processing pipeline rule will work only on new incoming messages and not already ingested ones. I might guess wrong that you want to remove the already ingested messages what is not possible from within Graylog UI.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!

**Comment by luweijun1992** [comment]
> he @luweijun1992
> 
> those processing pipeline rule will work only on new incoming messages and not already ingested ones. I might guess wrong that you want to remove the already ingested messages what is not possible from within Graylog UI.
> 
> We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).
> 
> Thank you!

I'm just going to process new messages, but I'm still going to get the messages, not get deleted.
