### ISSUE TITLE
Slow syslog processing speed with force_rdns enabled

### ISSUE THREAD

**Issue by bernd** [Graylog2/graylog2-server#999]
There seems to be a problem when the `force_rdns` option for Syslog inputs is enabled. Users report high CPU usage and reduced message throughput.

See: https://groups.google.com/forum/?hl=en#!topic/graylog2/bW2glCdBIUI

**Comment by bernd** [comment]
The problem is that the JVM [does not cache reverse DNS lookups](https://bugs.openjdk.java.net/browse/JDK-6656822). The available JVM DNS cache settings like "networkaddress.cache.ttl" only affect forward DNS lookups.

The code for doing the reverse lookups in Graylog did not change in a long time, so this problem is not new in 1.0.

I my test setup enabling "force_rdns" for a syslog input reduced the throughput from around 7000 msg/s to 300 msg/s. This was without a local DNS cache. Once I installed a DNS cache on the Graylog server, the throughput went up to around 3000 msg/s.

We will investigate if there is a sane way to cache the reverse lookups ourselves. In the meantime I suggest to test with a DNS cache installed on the Graylog server nodes to see if that helps or to disable the "force_rdns" setting.

**Comment by jalogisch** [comment]
this should be resolved by a local resolver that does the caching.
